src/Mod/Draft/draftviewproviders/view_dimension.py

`DraftVecUtils.getPlaneRotation` can now return None. The `view_dimension.py` code did not handle that.

Draft: V0.21 version of getPlaneRotation caused a dimension bug

---

src/Mod/Draft/importDXF.py

There is no more reason to have FreeCAD use a specific branch of the dxf importer libraries (at some point FreeCAD master and stable release needed different versions because of py2/py3). Better switch to use the master branch.
Fixes issue yorikvanhavre/Draft-dxf-importer#26
I left the system in place in case this is needed again in some future

Draft: use master version of dxf libraries

---

src/Mod/Sketcher/Gui/Utils.cpp
src/Mod/Sketcher/Gui/Utils.h

in order to replace
```cpp
geo->getTypeId() == Part::GeomEllipse::getClassTypeId()
```
with
```
Sketcher::isEllipse(*geo)
```

Sketcher: add TypeId checking helpers

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

* The menu text and tooltip of the Sketcher_ConstrainRadius command shouldn't be different if part of the group command or not. The explicit mentioning to change the weight of a B-Spline is pointless and confusing
* The order of Sketcher_ConstrainRadius and Sketcher_ConstrainDiameter has flippend when used in Sketcher_CompDimensionTools
* The command Sketcher_ConstrainRadiam is completely missing
* The command Sketcher_ConstrainSnellsLaw was wrongly re-added
* CmdSketcherCompConstrainRadDia uses a wrong context

Sketcher: fix several inconsistencies in Sketcher_CompDimensionTools

---

src/Mod/TechDraw/App/DrawUtil.cpp
src/Mod/TechDraw/App/DrawUtil.h
src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
src/Mod/TechDraw/Gui/ViewProviderViewPart.h

This PR implements a solution to a long standing problem where users press the delete key instead of using the CosmeticEraser command.  This deletes the entire view instead of the selected cosmetic element.

[TD]allow cosmetic deletion via DEL

---

src/Gui/CMakeLists.txt
src/Gui/EditableDatumLabel.cpp
src/Gui/EditableDatumLabel.h
src/Gui/SoDatumLabel.cpp
src/Gui/SoDatumLabel.h
src/Gui/TaskView/TaskImage.cpp
src/Gui/TaskView/TaskImage.h

It actually moves the spinbox gestion outside of TaskImage such that it can be reused in other places, notably in sketcher.
This will be a prerequisit of 'tool setting' branch, to draw the parameters on the view directly rather than in the taskbox.
It does not change any functionality.
Dear reviewer, I draw your attention to the ~EditableDatumLabel dtor to make sure everything is handled/deleted properly as I'm not 100% sure.
> Thank you for creating a pull request to contribute to FreeC
> AD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.
> 
> - [ ]  Your Pull Request meets the requirements …

[Core] Create EditableDatumLabel, a datumLabel that can be edited with a spinbox

---

src/Mod/Part/App/Geometry.cpp

If a project contains an unknown geometry extension then the attempt to create it returns a null pointer which isn't checked and causes a segmentation fault.
See also forum: https://forum.freecad.org/viewtopic.php?t=81091

Part: fix crash in Geometry::Restore()

---

src/Mod/Assembly/Gui/Resources/icons/Assembly_CreateJointBall.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_CreateJointCylindrical.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_CreateJointParallel.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_CreateJointPlanar.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_CreateJointTangent.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_Joint.svg

The newly added assembly joint icons (https://github.com/FreeCAD/FreeCAD/pull/10677) had some spacing issues that made certain ones look small on the toolbar, fixed those. 
Also @PaddleStroke I added a generic joint icon that can be used as the icon for the "Joints" group under the Assembly. It isn't perfect but it should look fine in the tree view.

Assembly: Fix joint icons

---

src/Gui/DlgMacroExecute.ui
src/Gui/DlgMacroExecuteImp.cpp
src/Gui/DlgMacroExecuteImp.h

This adds 2 labels and 2 line edits above the macro files list box:
Find file: [LineEditFile] Find in files: [LineEditFindInFiles]
[macro file names list box]
LineEditFile text is used to search the filenames for matches to the filter the user has entered.  Example: if the user types in "a" (without the quotes) then only files with "a" in the filename get listed in the list box.  Regular expressions are supported.  A check is done if the text entered is a valid regex expression.  If it is not valid, then we use a simpler text search with QString::contains().
LineEditFindInFiles text is used to further filter the results of the first filter to only include files containing text entered in LineEditFindInFiles.  This is also a regular expression search unless it's an invalid regex …

[Macro Execute Dialog] add file name and file content filtering

---

src/Mod/Draft/draftobjects/shape2dview.py

Add `Shape.SubShapes` instead of a copy of the shape. This avoids cut problems if there are intersecting solids.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=81240

Draft: shape2dview: avoid issues with intersecting solids

---

src/Gui/ComboView.cpp
src/Gui/ComboView.h
src/Gui/Control.cpp
src/Gui/Control.h
src/Gui/DockWindowManager.cpp
src/Gui/DockWindowManager.h
src/Gui/MainWindow.cpp
src/Gui/MainWindow.h
src/Gui/PreferencePages/DlgSettingsGeneral.cpp
src/Gui/PreferencePages/DlgSettingsGeneral.h
src/Gui/Workbench.cpp

Rework the current behaviour of the ComboView to make it more flexible. It moves the Task view out of the ComboView and makes it a stand-alone dock widget. 
See https://forum.freecad.org/viewtopic.php?p=626732#p626732 and https://forum.freecad.org/viewtopic.php?t=79950

Gui: make layout of Combo, Property and Tree view more flexible

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

Proposal to mitigate/fix #10651
Changes Sketcher_Dimension constraint options for 1point from [lock, distance] to [distance, lock]
@PaddleStroke

[Sketcher] Change Sketcher_Dimension 1point constraint order

---

src/Mod/Sketcher/App/SketchObjectPy.xml

This is the first batch of a general overhaul of SketchObject's python documentation. This was sitting on my shelf for way too long already, thus I thought I submit the first batch now for review. I do plan to continue this work, however progress is more than slow.
Style like in e.g. `Part.makeLine(...)`, which seems to loosely follow Google's recommendations [1]. Note that the signature *is* repeated in the docstrings, as it's not "inspectable" (see notes for non-python implementations in `inspect.signature` [2] and my preliminary attempt to change this in #10544).
[1]: https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
[2]: https://docs.python.org/3/library/inspect.html#inspect.signature

Sketcher: Update SketchObject's python docs, first batch

---

src/Gui/FreeCADGuiInit.py
src/Gui/Selection.cpp
src/Gui/Selection.h
src/Gui/SoFCUnifiedSelection.cpp

Add the possibility to set the style of selection between greedy and normal.
This is usefull for tools that require a greedy selection, like partDesign Fillet.
Also makes the python interface.
@wwmayer can you please have a look ?
There is one little thing that can be improved it's that currently you do 
`Gui.Selection.setSelectionStyle(0)`
when it would be best to have an enum to do 
`Gui.Selection.setSelectionStyle(Gui.Selection.SelectionStyle.GreedySelection)`
But I could not find how to implement this enum in python. I tried to look at `Gui.Selection.ResolveMode.NoResolve` but couldn't find where it's implemented.

Core: Selection : Add possibility to set the style of selection

---

src/Mod/Part/App/HLRBRep/HLRBRep_AlgoPyImp.cpp

As discussed in #10726, this small pull request fixes it.
The following listing works as opposed in the issue
``` python
>>> origin = App.Vector(0, 0, 0)
>>> direction = App.Vector(0, 1, 0)
>>> xDirection = App.Vector(1, 0, 0)
>>> algo = Part.HLRBRep.Algo()
>>> algo.setProjector(origin, direction, xDirection)
>>> algo.setProjector(origin, direction, xDirection, 1.0)
```

Part: Fix a missing argument for HLR projector

---

src/Mod/Assembly/CMakeLists.txt
src/Mod/Assembly/CommandCreateAssembly.py
src/Mod/Assembly/CommandCreateJoint.py
src/Mod/Assembly/CommandInsertLink.py
src/Mod/Assembly/Gui/Resources/Assembly.qrc
src/Mod/Assembly/Gui/Resources/panels/TaskAssemblyCreateJoint.ui
src/Mod/Assembly/InitGui.py
src/Mod/Assembly/JointObject.py
src/Mod/Assembly/UtilsAssembly.py

This is a basic implementation of a constraint system for the assembly wb.
The approach is the one that uses 'joint connectors'. It is a similar approach as A4 but the idea is to generate the placement based on the user selection. So for example you select the plane face4 of your body, the joint-connector placement is going to be the rotation of that plane, and the position of the face4 vertex that is the closer to your mouse. It is also similar to the approach of two well known commercial package.
The reason of this choice is that the solver developped by Dr Koh is following this logic to build assembly. Also this workflow is good and intuitive.
- 'Create Assembly' also create a 'joints' folder.
- Adds 'create joint xxx' commands. These commands prompt the user to select 2 features of 2 …

Assembly joints

---

src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.h

Fixes https://github.com/FreeCAD/FreeCAD/issues/10603
In Sketcher_Dimension and also in general moving the constraint : Enable the user to select the complementary angle he wants based on the position of the mouse. Similarly as how he can choose distance/DistanceX/Y.
Forum discussions : 
https://forum.freecad.org/viewtopic.php?t=28321
https://forum.freecad.org/viewtopic.php?t=80994

Sketcher_Dimension: Enable the user to select what angle he wants.

---

src/Mod/TechDraw/App/AppTechDrawPy.cpp
src/Mod/TechDraw/App/ProjectionAlgos.cpp
src/Mod/TechDraw/App/ProjectionAlgos.h

This pull requests exposes two functions to Python that allows Python code and workbenches to generate SVG images. See #10733.
This pull request exposes `TechDraw.build3dCurves()` and `TechDraw.exportSVGEdges()` and it is a convenient addition for workbenches that want more control over SVG export, possibly in relation to Part HLR, see for example #10726.
This pull request is independent of but related to #10726. In order to test the code below with the Part HLR module, it is necessary to have the changes from #10727. With that code in place, the following is possible creating an SVG from Python like so:
``` python
doc = App.ActiveDocument
doc.addObject("Part::Box","Box")
obj = doc.ActiveObject
obj.Label = "Cube"
doc.recompute()
shape = obj.Shape
view = Gui.ActiveDocument.ActiveView …
```

TechDraw: Expose two functions for SVG export

---

src/App/Document.cpp
src/App/Document.h
src/App/Property.h
src/App/PropertyContainer.cpp
src/App/PropertyContainer.h
src/App/private/DocumentP.h
tests/src/App/CMakeLists.txt
tests/src/App/Document.cpp

Before we can really begin [#10353](https://github.com/FreeCAD/FreeCAD/issues/10353), Document needs to be able to provide a `StringHasher`. This PR brings in the bare minimum code required to load and save the StringHasher in a Document. It does _not_ fully implement storing the naming information, nor does it implement the "forceXML" mechanism for the hasher.
The first commit is as close to @realthunder's original code as could be made to compile in current FreeCAD without making any significant changes to the code structure (in particular I did not implement the `pimpl` code in `PropertyContainer`).
Planned follow-up commits include some basic C++ modernization cleanup, and basic tests.

App/Toponaming: Add StringHasher to Document

---

src/Mod/Draft/DraftGeomUtils.py
src/Mod/Draft/draftgeoutils/geometry.py

The functions have been copied from the WorkingPlane class. It makes sense to also have them available outside that class. The WorkingPlane class will later be updated to use these functions so that duplicate code is avoided.
Note that the default tolerance of the project_point_on_plane function is 1e-7. In the original projectPoint function it is sys.float_info.epsilon (too small for FreeCAD IMO).

Draft: Add distance_to_plane and project_point_on_plane to geometry.py

---

src/Mod/Arch/ArchWindow.py

With the current code, if you place a simple door and change its Opening property to 50, the door leaf and the frame intersect. This PR fixes that issue.

Arch: avoid intersecting solids in windows and doors with openings

---

src/Gui/Document.cpp

Example code:
```
doc = App.newDocument()
doc.addObject(type = "Part::Feature", viewType = "MeshGui::ViewProviderMesh")
```

Gui: fix possible memory leak if inappropriate view provider is created

---

src/Mod/Arch/CMakeLists.txt

The ArchSketchObject.py module was not in the cmake file and therefore not installed.

Arch: Added missing ArchSketchObject to cmake file

---

.clang-format

Sorting the included headers regularly leads to build failures. Especially when PCH is enabled the PreCompiled.h must be the very first include

clang-format: disable sorting of includes

---

.pre-commit-config.yaml

For backport fixes the automatic changes by pre-commit should be avoided as this leads to hundreds of modified files.

[Release 0.21] pre-commit: Avoid automatic commits for backport fixes

---

src/Gui/PreferencePages/DlgSettingsEditor.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/10122
The 8514oem font is added when Windows users change DPI to for example 125% see https://answers.microsoft.com/en-us/windows/forum/all/windows-add-font-8514oem-when-i-change-windows-dpi/2ec32e81-52d9-40a0-ab35-07a8ef9051b8
which in turn results in a warning in the Report View which makes little sense to the user.

[Preferences] Exclude 8514oem from Monospace fonts

---

src/Gui/NavigationStyle.cpp
src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h
src/Gui/ViewProvider.h
src/Gui/ViewProviderMeasureDistance.cpp
src/Gui/ViewProviderMeasureDistance.h

(cherry picked from commit fcbee3ad4997737bd455ee2294bde4113a1f409f)
Backport of #9969.

[Backport] Improve object center rotation mode

---

src/Gui/NaviCube.cpp

(cherry picked from commit c2bf9efc7d7842116c34f58bf445dbd72cd3f131)
Backport of #10703.

[Backport] Improve accuracy for navigation cube's rotate to nearest feature

---

src/Mod/Fem/Gui/Command.cpp

Follow-up on #10519, resolves #10786 - cleaning the remaining names that shouldn't use "constraint"

FEM naming fix part 2 (removes remaining incorrect "constraint" usage)

---

src/Gui/CommandLink.cpp
src/Gui/CommandStructure.cpp
src/Gui/CommandView.cpp
src/Gui/Workbench.cpp

This PR does several things : 
- Put Link in the command group
- Give Link a proper tooltip (screenshot outdated: tooltips changed).
- Put sel_back and sel_forward in the treeview actions group rather than in root of view toolbar. This way they now appear in the view menu (they weren't before) and they don't appear in the root of view toolbar.
- Give them proper names and tooltips (screenshot outdated: tooltips changed)
- Remove 'Link Navigation' from the view toolbar
- Put 'Link Navigation' in the view menu where it was missing.
- Remove 'Bouding box' from the view toolbar (its still in view menu)
- Reorder the view toolbar so that the order makes sense.
Lastly it improves the tooltips of std_part and std_group.
Fixes #10755
Fixes #10756
Fixes #10757
Fixes #10758

Toolbar View and Structure cleaning

---

src/Gui/CMakeLists.txt
src/Gui/DemoMode.cpp
src/Gui/NavigationAnimation.cpp
src/Gui/NavigationAnimation.h
src/Gui/NavigationAnimator.cpp
src/Gui/NavigationAnimator.h
src/Gui/NavigationStyle.cpp
src/Gui/NavigationStyle.h
src/Gui/PreferencePackTemplates/View.cfg
src/Gui/PreferencePages/DlgSettingsNavigation.cpp
src/Gui/PreferencePages/DlgSettingsNavigation.ui
src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h
src/Gui/View3DPy.cpp
src/Gui/View3DSettings.cpp

---
I have been working to improve navigation animations. This PR contains mostly refactoring. I have added a `NavigationAnimator` that manages active `NavigationAnimation`s. An animation must be played through the animator. …

Gui: Refactor navigation animations

---

src/Mod/Part/BOPTools/ShapeMerge.py

Some notes:
Earlier, when adding to the list `connected_to`. the numbers are added in order from `range(len(groups)`, so we are already in order and every `i_group` is unique.
As per https://github.com/FreeCAD/FreeCAD/issues/6878#issuecomment-1368330972 this might not be necessary. However, @DeepSOIC also mentions the entire method could be optimized so I can work on that here.

[Part] Optimize snippet of code in `ShapeMerge.py`

---

src/Mod/Draft/draftobjects/shapestring.py

Calculation of the justification vector required the use of `optimalBoundingBox` and should happen after applying the oblique angle.

Draft: ShapeString: improve ObliqueAngle

---

src/Base/MatrixPy.xml
src/Base/MatrixPyImp.cpp
src/Tools/generateBase/generateMetaModel_Module.xsd
src/Tools/generateBase/generateModel_Module.py
src/Tools/generateTemplates/templateClassPyExport.py

This is to remove superfluous calls of
```
if (!PyArg_ParseTuple(args, ""))
return nullptr;
```
from many Python functions.

Python: Support METH_NOARGS methods

---

src/Base/Matrix.cpp
src/Base/Matrix.h
src/Base/MatrixPy.xml
src/Base/MatrixPyImp.cpp
src/Base/Rotation.cpp
src/Mod/Test/BaseTests.py
tests/src/Base/CoordinateSystem.cpp
tests/src/Base/Rotation.cpp

Added a `decompose()` method to Matrix that returns four matrices representing shear, scale, rotation and move. So that `matrix = move*rotation*scale*shear`. This is the order move rotation and scale are applied to a link. i think a link is the only object that can be scaled.  Therefore I think this type of decomposing is best suited for FreeCAD.
The returned rotation is the inverse of the one needed to realign the x axis and the xy plane.
The remaining shear always has the form:
```
1  a  b  0
0  1  c  0
0  0  1  0
0  0  0  1
```
I'm then using the Matrix.decompose() in the Rotation(Matrix) method. That means we do not need to throw an exception there anymore when the matrix is complex. 
Fixes #9576 
Discussion: https://forum.freecad.org/viewtopic.php?t=75448
Related to PR: …

Matrix decomposing and create Rotation from any Matrix

---

src/Gui/CommandMacro.cpp
src/Gui/PreferencePackTemplates/Shortcuts.cfg
src/Gui/Workbench.cpp
src/Mod/Web/Gui/Workbench.cpp

And adds the stop functionality to the Std_DlgMacroRecord command. ie if you start recording, the button becomes a stop button.
There might be some usecases where the user stops the recording by another mean than the command (in python for example?) and in this case the command wouldn't update. But I don't know if there are actually such usecases.
Fixes https://github.com/FreeCAD/FreeCAD/issues/10834

[Macro toolbar] Remove stop from toolbar and menu

---

src/Mod/TechDraw/App/DrawViewArch.cpp
src/Mod/TechDraw/App/DrawViewArch.h

This PR is a companion to Arch PR #10816.  It implements the c++ changes required to support line spacing in ArchView.
Further details here: https://forum.freecad.org/viewtopic.php?t=81470&sid=00e784953cffb76c6c2aba078d80f312

[TD]add line spacing property

---

src/Mod/Draft/WorkingPlane.py

After this PR the `Plane` class inherits from the `PlaneBase` class.
Related issue:
#5603.
Previous PR:
#10766
The following functions have been updated:
`__init__`
* `u` argument can be a WP now.
* Input vectors are copied.
* Added the `weak` argument.
* the `doc` attribute was not used and has been removed.
`__repr__`
* Inherited.
* The `position` is now also shown.
`copy`
* Uses `match` from the parent class which uses the local `_get_prop_list` function. Again vectors are copied.
`offsetToPoint`
* I could not find evidence that this function is used anywhere.
* The `direction` argument did not make a lot of sense (only worked in 2D). It is now ignored.
* Removed the overly long docstring.
* The function now uses an external function: `DraftGeomUtils.distance_to_plane`.
`projectPoint` …

Draft: Update the Plane class (step 1)

---

src/Mod/Path/Path/Post/scripts/centroid_post.py
src/Mod/Path/PathTests/TestCentroidPost.py

This adds G43 tool height compensation to the centroid CAM post-processor using a similar approach to the G43 support in the MACH3 post.
Specifically, G43 is emitted at every tool change by default and a new `--no-tlo` post argument can restore the old behaviour of no height compensation being emitted. These both match how the MACH3 post does it.

Add G43 tool height compensation to centroid post

---

src/Mod/Path/Path/Post/UtilsArguments.py
src/Mod/Path/Path/Post/UtilsExport.py
src/Mod/Path/Path/Post/UtilsParse.py
src/Mod/Path/Path/Post/scripts/refactored_centroid_post.py

This is one in a series of PR's where I am taking code from at least 4 postprocessor files partially written by different people, combining them into three files, then trying to make the code more consistent and simpler. The long term goal is to enable much simpler postprocessor files with much less copied code in each postprocessor file and much more "shared" code in the three Utils*.py files.
In this PR I refactored the "export_common" function to make it more maintainable.  This also required refactoring the "parse_a_path" and "parse_a_group" functions a bit to stay compatible.  I also removed "message" command handling since it didn't seem to be able to be used.

Path:  Major refactoring of the export_common function.

---

src/Mod/TechDraw/App/DimensionGeometry.cpp
src/Mod/TechDraw/App/DimensionGeometry.h
src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/Gui/QGIViewDimension.cpp

When a line and a vertex are selected, the Length dimension currently use closest points of the finite edge. It's not the mathematical definition of the distance which require the projection of the point on the infinite line.
When selecting the upper right vertex and the bottom line:
Left the current implementation, Right the true length given by this PR
https://forum.freecad.org/viewtopic.php?t=81561
EDIT: update screenshot with corrected extension line

TechDraw: Implements projected Length dimension

---

conda/environment.devenv.yml

This commit adds two dependencies to the conda development environment:
- Add `yaml-cpp` to bring the conda development environment back in line with current `HEAD`.
- Add `pre-commit` to support the pre-commit hooks outlined in the Developers Handbook.

Update conda development dependencies.

---

.clang-tidy

Currently this check isn't enabled but when pushing a PR then the lint checker warns about non-explicit constructors which is a bit annoying because the PR must be updated to fix the warning or in most cases it won't be fixed at all.
By enabling this check the developer already sees the warning before pushing a PR.

Clang-tidy: enable check google-explicit-constructor

---

src/Mod/Part/TestPartApp.py

https://github.com/FreeCAD/FreeCAD/issues/10868
The CI tests are supposed to fail because they either cause a segmentation fault or raise an SEH exception.

Part: Add several unit tests for an empty edge or face

---

src/Gui/DlgMacroExecuteImp.cpp

Sets the focus on the Find: line edit.  Saves the user the necessity of clicking on the line edit in order to filter by file name.  The only other widget in this dialog that accepts keyboard input is the Find in files: line edit, but I think this one is the more commonly used one.

[MacroExecuteDialog] set keyboard focus to LineEditFind

---

src/Base/Observer.h

and remove the `assert(0)` statement as this is an indication of a problem in the code but not serious enough to crash the application

Base: replace calls of printf() with Console().DeveloperWarning()

---

src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

When in Sketcher edit mode, a tool button is activated, while the view has been changing to view of a different type, it segfaults.
This commit checks the pointer of the view to ensure correct type before activation, and refusing to activate if not of the correct type.
fixes #10809

Sketcher: Fix segfault when activating a tool in a different view

---

src/Mod/Fem/Gui/TaskPostBoxes.cpp
src/Mod/Fem/Gui/TaskPostBoxes.h

Remove nodes  used when a point is picked. Fixes #10438 
A `SoCoordinate3` and a `SoMarkerSet` remained in the scene graph after the point selection process was finished. Now are removed when the task box is closed.

Fem: Remove markers from scenegraph - fixes #10438

---

src/Mod/Material/TestMaterialsApp.py

Update Python tests to work with other locales
This fixes issues #10917 and #10924
Numeric values were beign compared to strings that did not take into account localizations. The test was modified to work regardless of localization.
There is still a known issue when working with pt_BR.UTF8. The default encoder for this localization is not UTF8 resulting in an error working with a parameter that returned the UTF character for the Greek letter mu in its units.

Material: Update Python tests to work with other locales Issues #10917 and #10924

---

src/CXX/Python3/Objects.hxx

Remove template argument list from constructor names. It has never been necessary, and is forbidden in C++20 (n.b. [CWG 2237](https://cplusplus.github.io/CWG/issues/2237.html)). This has also been independently fixed upstream in [r449](https://sourceforge.net/p/cxx/code/449/).
Fixes #10952.

Fix build for C++20

---

src/Gui/PreferencePages/DlgSettingsDocument.ui

With PR #10016 the saving of thumbnails is on by default but the spin box to set the size is still disabled. This results into an inconsistency and one has to click the Save thumbnails check box twice to enable the size widget.

Gui: Enable the thumbnail size widget by default

---

src/Gui/ViewProviderPlane.cpp

Correction of #9361. Fixes memory leak.
<details><summary>Here is the fragment of the leak report.</summary>
```cpp
Direct leak of 36 byte(s) in 3 object(s) allocated from:
#0 0x7f867b612a92 in operator new(unsigned long) ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:248
#1 0x7f867a3d921c in Gui::ViewProviderPlane::attach(App::DocumentObject*) /home/xtemp09/Downloads/FreeCAD/src/Gui/ViewProviderPlane.cpp:85
#2 0x7f867a022d19 in Gui::Document::slotNewObject(App::DocumentObject const&) /home/xtemp09/Downloads/FreeCAD/src/Gui/Document.cpp:693
#3 0x7f867a03a2fd in void std::__invoke_impl<void, void (Gui::Document::*&)(App::DocumentObject const&), Gui::Document*&, App::DocumentObject const&>(std::__invoke_memfun_deref, void (Gui::Document::*&)(App::DocumentObject const&), …
```

[GUI] Fix memory leak in ViewProviderPlane.cpp

---

src/Gui/PreferencePages/DlgSettingsWorkbenchesImp.cpp

This fixes an issue with the workbench list where the workbench name has a Qwidget background, while the list has a Qlist background.
Also the Qwidget background was in front of the Qlist hover background color.
Before:
After:

Workbench list in settings, small UI fix.

---

src/Gui/GestureNavigationStyle.cpp
src/Gui/MayaGestureNavigationStyle.cpp

When dragging in the Gesture and MayaGesture navigation styles, the rotation center indicator is not shown because the rotation center is not set. The added lines set the rotation center before dragging.

Gui: Fix rotation center indicator for Gesture styles

---

src/Gui/Thumbnail.cpp

When saving the thumbnail there is a check if the 3D window is the active window. This check fails if a document is saved for the first time because the appearing file dialog causes the 3D window to not be active any more. Thus, no snapshot of the 3D window will be created and the program logo will be saved instead. A workaround is to save the document twice.
This PR removes the check for the active window so that the snapshot can be created. The issue might be related to #10937.

Gui: Initial save of a document doesn't have the expected thumbnail

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

Fix typo making Sketcher_Dimension fails for angles.
Fixes https://github.com/FreeCAD/FreeCAD/issues/10984

[Sketcher]Fix typo making Sketcher_Dimension fails for angles.

---

src/Mod/Fem/Gui/TaskPostBoxes.cpp
src/Mod/Fem/Gui/TaskPostBoxes.h

Currently the callback functions and the connection used to pick the points in the `TaskPostDataAtPoint` and `TaskPostDataAlongLine` functions are not removed properly. So this lead in a crash if, for example, click the `Select Point` button and close the dialog without end the  points selection process since the markers are destroyed but the callback remains active. In fact, each time the button is pressed, a callback and a connection are established.
Additionally, there is some rework in the point marker classes to avoid code duplication and to use pointers to initialize the objects.
The `TaskPostDataAlongLine` and `TaskPostDataAtPoint` boxes are created using pointers to their specific view provider objects.
These changes fix the problem without changing the current code structure too …

Fem: Remove callback added by filters task box and rework marker classes

---

src/Mod/Arch/importOBJ.py

Fixes #6187.
Other fixes:
* Made handling of shapes and global placement more consistent.
* Shapes without curves were also triangulated.
* Polygonal faces could have flipped normals and duplicate points.

Arch: Fix multiple issues with ImportOBJ.py

---

src/Base/Base64.cpp
src/Base/Base64.h
src/Base/Base64Filter.h
src/Base/CMakeLists.txt
src/Base/FileInfo.h
src/Base/Reader.cpp
src/Base/Reader.h
src/Base/Writer.cpp
src/Base/Writer.h
tests/src/Base/Base64.cpp
tests/src/Base/CMakeLists.txt
tests/src/Base/Reader.cpp
tests/src/Base/Writer.cpp

This PR adds @realthunder's Base64 encoding/decoding support to Reader and Writer. The code in the first commit is nearly identical to that in the Toponaming branch, with the exception of the addition of two enum classes to replace boolean parameters. 
* `Base64ErrorHandling` (replaces a boolean indicating whether or not to throw an error on bad character data)
*  `CharStreamFormat` (replaces a boolean indicating whether to Base64-encode/-decode the data). `CharStreamFormat` is defined in the [src/Base/FileInfo.h](https://github.com/FreeCAD/FreeCAD/compare/master...chennes:toponamingPhase3Card1?expand=1#diff-6fba68d97e78796c20dbf9d25340188f74cf7014ec48c3e705090a704679af2a) header because it's needed by both `Reader` and `Writer` -- @wwmayer does that seem like an OK place for it?
Two …

App/Toponaming: Add base64 encoding to XML

---

src/Mod/Draft/importDXF.py

Draft: Use DXF OCS when importing circles and arcs to Part shapes

---

src/Gui/MainWindow.cpp
src/Gui/OverlayManager.cpp
src/Gui/OverlayManager.h
src/Gui/OverlayParams.cpp
src/Gui/OverlayWidgets.h
src/Gui/PreferencePages/DlgSettingsTheme.cpp
src/Gui/PreferencePages/DlgSettingsTheme.ui
src/Gui/Stylesheets/CMakeLists.txt

Fixes several issues of https://github.com/FreeCAD/FreeCAD/pull/7888:
* Since Qt5.11 QDesktopWidget is marked as deprecated and has been removed in Qt6. New code has to use QScreen instead.
* QMetaObject::invokeMethod: No such method Gui::OverlayManager::raiseAll()
* 'globalPos' is deprecated: Use globalPosition() [-Wdeprecated-declarations]

Gui: fixes OverlayManager issues

---

src/Gui/Stylesheets/Dark-modern.qss
src/Gui/Stylesheets/Dark.qss
src/Gui/Stylesheets/Darker.qss
src/Gui/Stylesheets/Light-modern.qss
src/Gui/Stylesheets/Light.qss

I finally figured out how to do this PR properly. So I made a new PR.
There was an empty placeholder spot in the Qcombobox in Fusion/Linux style in the stylesheets.
I tried to remove the spot, noticed it was caused by Qcombobox:indicator and I ended up fixing the indicator.
It can be debated if this indicator is useful, as it isn't shown in the no-stylesheet option.
I personally found it looks pretty good and is useful. I'd suggest try it out in main, and we can always remove it afterwards. 
Before:
After:

[stylesheets]Fix for Qcombobox in Qstyle Fusion 

---

src/Mod/Path/App/VoronoiEdgePyImp.cpp

Closes #8102.
If one follows the steps described by @br4243, `Voronoi::point_type orthognalProjection` dividing by zero, returns NaN. This NaN is fed to `Part::GeomArcOfParabola::setRange` causing freeze. This pull request fixes the issue.

[Path] Prevent division by zero

---

src/Mod/Fem/Gui/TaskPostBoxes.cpp
src/Mod/Fem/Gui/TaskPostBoxes.h
src/Mod/Fem/Gui/ViewProviderFemPostFilter.cpp
src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp

The change in `TaskPostDisplay` from `Gui::ViewproviderDocumentObject` to `ViewProviderFemPostObject` avoids potential crashes since `TaskPostDisplay` is intended to use properties of the `ViewProviderFemPostObject` class.
See comments in #10980

Fem: Change TaskPostBoxes constructors to specific view providers

---

src/Gui/DockWindowManager.cpp
src/Gui/DockWindowManager.h
src/Gui/PreferencePages/DlgSettingsGeneral.cpp
src/Gui/PreferencePages/DlgSettingsGeneral.ui
src/Gui/Workbench.cpp

Overlay management is not stable yet and causes serious problems to many users. This PR allows to deactivate it entirely.

Gui: implement option to disable overlay management

---

src/Gui/DlgPreferences.ui
src/Gui/DlgPreferencesImp.cpp
src/Gui/DlgPreferencesImp.h

The reset button opens a menu that offers all options to reset the user settings.
This fixes the UI issues as discussed in https://github.com/FreeCAD/FreeCAD/pull/10688

Gui: Switch back to a single Reset button

---

src/Gui/PreferencePackManager.cpp

This PR adds `"<mod>/overlay"` path to search paths of "overlay" prefix. This allows preference packs to register custom overlay stylesheets.
I think that we should think about better ways of doing that kind of stuff. Package metadata could include elements like 
```
<searchpath prefix="qss" path="." />
<searchpath prefix="overlay" path="./overlay" />
```
which should enable package developers to have better control over the search paths. This should however be done in another request and issue.
Fixes: #11023

Gui: Register overlay search path from preference packs

---

src/Mod/Draft/draftutils/gui_utils.py

Related issue:
#10634
Also needed to avoid warnings from the PlaneGui class.

Draft: Change get_3d_view to only return the active 3D view

---

src/Mod/Arch/ArchReference.py

This allows [Arch Reference](https://wiki.freecad.org/Arch_Reference) to undistinguish somefile.FCStd from somefile.fcstd
Issue #10874

Arch: Made Arch Reference case-insensitive

---

src/Gui/OverlayManager.cpp

As mentioned by @realthunder in https://github.com/FreeCAD/FreeCAD/issues/11015#issuecomment-1762922058 the https://github.com/realthunder/FreeCAD/commit/bdf7af1380c932371f4d01dab243c832dd2c68ec commit broke wheel event passing in overlay widgets. Reverting one block fixes the issue, I did not revert the other change as this function is used also in other places which seems to work fine.
Fixes: #11015

Gui: Target proper widget when passing wheel event

---

src/Mod/Draft/draftguitools/gui_arcs.py
src/Mod/Draft/draftguitools/gui_trackers.py

Forum topic:
https://forum.freecad.org/viewtopic.php?t=81956
This PR basically reverts PR #10556.
The angular offset required for the Draft_Arc command is handled in the gui_arc.py file instead. Also removed the unused `u` and `urotated` variables from that file.

Draft: Fix angular dimension issue caused by #10556

---

src/Mod/Draft/Resources/ui/TaskSelectPlane.ui
src/Mod/Draft/draftguitools/gui_selectplane.py

Related issue:
#5603
Previous PR:
#11010
* This PR implements the new PlaneGui class for the Draft_SelectPlane command.
* As mentioned in the previous PR, almost all working plane related code has been removed from gui_selectplane.py.
* The task panel has a new button "Next" to switch to the next working plane in the history.
* Both the "Previous" and "Next" buttons are only enabled if there is a corresponding step in the history.
* PlaneGui stores a working plane per 3D view, but the other commands have to be updated before that system is fully functional.
* Code to update the toolbar when switching to a different view will be added later.

Draft: Update gui_selectplane.py

---

src/Mod/Arch/importSHP.py
src/Mod/Help/dlgPreferencesHelp.ui

- The string of the some tooltips are very long that use all screen width.
- In other `.ui` files seems to be a max width of about 80 characters.
- This commit shortens the long strings.
- Also fixes some words capitalization noted by david69 on Crowdin
Example of other tab in settings with good width:
QtDesigner preserves the line breaks.

Help module: Shorten string width to 80 characters.

---

src/Gui/OverlayManager.cpp

I've no idea why, but for some reason if synthesized event is passed into `QGraphicsView` it is not processed. It however works ok if we pass `graphicsView->viewport()` as receiver of the event. However as `View3DInventorViewer` also indirectly derives from `QAbstractScrollArea` it is also affected by the `qobject_cast<QAbstractScrollArea*>(parent)`, and in that case passing events to viewport does not work. Maybe some Qt experts know why, I'm not one of them.
Changing `qobject_cast` to more specific class seems to work fine for both cases, and does not make the code worse.
@wwmayer if you could take a look please, maybe you will be able to find better solution.
Fixes: #11015

Gui: Target 3DViewer directly for overlay wheel events

---

CONTRIBUTING.md

FreeCAD switched to use "main" branch in development. Updating CONTRIBUTING.md to reflect that.
Three changes:
- Mention of the main branch name, 
- Mention that releases are made from main branch,
- Link to the contributors list
https://github.com/FreeCAD/FreeCAD/discussions/10226

Update CONTRIBUTING.md to reflect branch naming change

---

src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp
src/Mod/PartDesign/Gui/TaskTransformedParameters.h

A null pointer will never be passed to TaskTransformedParameters(). So, there is no point in explicitly checking for a null pointer (in this inconsistent way).

PD: fix constructor of TaskTransformedParameters

---

src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.cpp

QRegExp has been replaced with QRegularExpression and isn't part of the base of Qt6 any more

Sketch: fix Qt6 build failure

---

src/Mod/Draft/WorkingPlane.py

Related issue:
#5603.
* An 'auto' WP should not be added to the history if the previous WP in the history is also 'auto'.
* The `get_working_plane` function should only call `set_to_default` if the GUI is up. The axis of the returned WP should match global +Z if the GUI is not up.

Draft: PlaneGui: minor fixes

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.cpp
src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.h

* Remove private unused field 'sketchView'
* Mark constructor with single argument as explicit
* Mark virtual methods of base class as override
* Fix clang code model parsing error
* Avoid too short identifiers
* Avoid redundant ternary operators
* Avoid passing Base::Unit by value but by const reference

Sketch: fix several compiler and lint warnings

---

src/Mod/TechDraw/App/Cosmetic.cpp
src/Mod/TechDraw/Gui/TaskCosmeticCircle.cpp

Hello,
with this PR I would like to provide 3 fixes for Cosmetic Circle, or Cosmetic Arc of Circle resp.
1) Correct task dialog title: This is trivial.
2) Problems with changed center coordinates after save/reload: The dialog takes (and stores) center coordinates from AoC permaStart, however when restored, permaStart is not filled from AoC center, but from startPnt. This is here fixed in Cosmetic.cpp:302-303
3) Problems with "reversing" AoC after save/reload: If a cosmetic AoC is created (e.g. from angle 0 to 270), it correctly shows the arc, however when saved and restored, the arc is now displayed like 90 to 360. The reason is the underlying OCC edge must be flipped along the ZX plane, because Qt uses screen coordinates system ([0, 0] in top left corner). When such "inverted" AoC edge …

[TechDraw] - Cosmetic Circle fixes

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

Remove unused bothexternal variable that is a leftover of a refactor.

Sketcher: commandConstraint : remove leftover bothexternal variable.

---

src/Mod/Draft/WorkingPlane.py

Related issue:
#5603.
* The history idx value was not handled properly.
* Part.getShape() ignores the Placement of a selected BuildingPart. Have to use `place * obj.Placement`.

Draft: PlaneGui: some minor fixes

---

src/Gui/OverlayManager.cpp
src/Gui/OverlayParams.cpp
src/Gui/OverlayParams.h
src/Gui/OverlayParams.py

Fixes #11020.
In the file I changed, OverlayParams.cpp, I see a bunch of `// Auto generated code (Tools/params_utils.py:xxx)`. Not sure how that auto generation works but this makes me wonder if the manual changes may get overwritten again if the code is regenerated for some reason.

Gui: Remove CornerNaviCube from OverlayParams and use directly in OverlayManager

---

src/Mod/Fem/Gui/BoxWidget.ui
src/Mod/Fem/Gui/CylinderWidget.ui
src/Mod/Fem/Gui/PlaneWidget.ui
src/Mod/Fem/Gui/SphereWidget.ui
src/Mod/Fem/Gui/TaskPostDataAlongLine.ui
src/Mod/Fem/Gui/TaskPostDataAtPoint.ui

reduce horizontal space taken for better UX
mentioned at https://github.com/FreeCAD/FreeCAD/issues/11016#issuecomment-1762926895
Other dialogs may need similar changes, I would like people to point out which ones
All of these dialogs preferred using a ton of horizontal space and left a lot of empty vertical space, this should make them more user friendly
new dialogs:
even on a 1360x768 screen the dialogs now only take 1/4 of the view and don't require scrolling for usage (depending on toolbars layout)

[FEM] Improve some task dialog layouts

---

src/Mod/PartDesign/App/FeatureLinearPattern.cpp

A selected edge of a sketch is not in local coordinates and thus its corresponding axis mustn't be multiplied with the sketch placement as this will lead to a wrong direction vector.
Forum: https://forum.freecad.org/viewtopic.php?t=82022

PD: wrong direction determined for linear pattern

---

src/Mod/Fem/Gui/TaskFemConstraintTemperature.cpp
src/Mod/Fem/Gui/TaskFemConstraintTemperature.h
src/Mod/Fem/Gui/TaskFemConstraintTemperature.ui

This fixes #11109.
Change the radio buttons for one combo box with the `ConstraintType` values.
Depending on the value of this property, the `Temperature` spinbox or the `Concentrated heat flux` spinbox becomes visible.

Fem: Connect constraint temperature spinboxes to properties and task dialog rework - fixes #11109

---

src/Gui/Document.cpp
src/Gui/View3DInventor.cpp

Goal : change the icons of the document tabs in the mdi tab bar.
Fixes : #11150

MDI tabs, meaningful icons.

---

src/Mod/Path/Path/Op/Area.py

This PR fixes issue #11107
_buildProfileOpenEdges uses Path.fromShapes to generate G-Code from the wire. However Path.fromShapes reverses the wire if that shortens the travel move to the start point. By always manually setting the first or last vertex of the wire (depending on obj.Direction) instead of using self.endVector the edge is allways milled in the correct direction.

Path: fix Profile open edges not respecting selected cutting direction

---

src/Gui/InventorAll.h

Build is failing on window this morning. After looking into it it comes from https://github.com/FreeCAD/FreeCAD/commit/f566b449a68bbdf0836dd5474c12214ced0ea379
The header is missing from precompiled.
#include <Inventor/draggers/SoDirectionalLightDragger.h>
@wwmayer

Fix build failing due to f566b44

---

src/Mod/TechDraw/Gui/CommandAnnotate.cpp
src/Mod/TechDraw/Gui/QGIViewPart.cpp

Two small fixes:
1) If a cosmetic circle/arc is selected, but _CosmeticLine_ command invoked followed by _OK_ press, program crashes. The same happens if straight cosmetic edge is selected, _CosmeticCircle_ command invoked and _OK_ pressed. The extended condition prevents the crash.
2) The cosmetic edge Qt object should be marked properly as "cosmetic". Though the property is not used right now, it should be set correctly.

[TechDraw] - Cosmetic edge fixes

---

src/Gui/CMakeLists.txt
src/Gui/DemoMode.cpp
src/Gui/NavigationAnimation.cpp
src/Gui/NavigationAnimation.h
src/Gui/NavigationAnimator.cpp
src/Gui/NavigationAnimator.h
src/Gui/NavigationStyle.cpp
src/Gui/NavigationStyle.h
src/Gui/PreferencePackTemplates/View.cfg
src/Gui/PreferencePages/DlgSettingsNavigation.cpp
src/Gui/PreferencePages/DlgSettingsNavigation.ui
src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h
src/Gui/View3DPy.cpp
src/Gui/View3DSettings.cpp

- Animations are played through an Animator
- Standard animations have a fixed duration and inherit from QVariantAnimation
- The animation duration can be changed in the preferences
- Fix animations when using the two arrows above the NaviCube
- Start an animation or start and wait for an animation
- Replaces standard camera animations (e.g. by selecting standard views or NaviCube) with FixedTimeAnimation
- Replace View3DInventorViewer's CameraAnimation with FixedTimeAnimation
- Replace OpenInventor navigation style infinite spin animation with SpinningAnimation
- Stops an active animation when a new animation is started
- Stops an active animation when the user starts dragging, panning or zooming
- Refactor reorientCamera so it can be used in animations
- Enable animations by default
- …

Gui: Refactor navigation animations (attempt 2)

---

src/Mod/TechDraw/Gui/QGIEdge.cpp
src/Mod/TechDraw/Gui/QGIEdge.h
src/Mod/TechDraw/Gui/QGIPrimPath.cpp
src/Mod/TechDraw/Gui/TaskLineDecor.cpp
src/Mod/TechDraw/Gui/TaskLineDecor.h

This PR improves line decoration handling:
1) Double clicking on an edge invokes Line Decoration dialog. This aims to improve productivity when creating a drawing. The changes involved are in files QGIEdge.h and QGIEdge.cpp .
2) When the Line Decoration dialog is invoked, all updates to style are immediately reflected. This is perfect. However when _Cancel_ is pressed, the old style values were not stored anywhere and in fact, there was no difference between pressing _OK_ or _Cancel_. It just closed the dialog. With this PR, the line styles are fully preserved and restored, if the user decides to press _Cancel_. These changes are contained in TaskLineDecor.h and taskLineDecor.cpp files.
3) Small fix of earlier refactorization. Without setting the pen style, all lines are drawn as solid. …

[TechDraw] - Line Decoration Improvements

---

src/Mod/Draft/WorkingPlane.py

Update wp._view before call to set_to_default, set_to_auto requires a 3D view.

Draft: PlaneGui: update wp._view earlier

---

src/Base/Interpreter.cpp

This enables python debuggers to stack trace after an exception. See https://forum.freecad.org/viewtopic.php?p=714349#p714349
This is authored by @bdieterm I'm just submitting it.

Base: set sys.last_vars to enable post mortem debugging after exception

---

src/Gui/MainWindow.cpp
src/Gui/Splashscreen.cpp
src/Gui/Splashscreen.h

Add a parameter to disable messages of the splashscreen. Boot faster without loosing the splashscreen.

SplashScreen: add parameter to disable messages on the splashscreen

---

src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h

one of the modes for line is wrongly named IMO
- point, length, width
should instead be:
- point, width, height
or
- point, vector
since it does not set the length of the line but horizontal and vertical distance between endpoints, plus the width is set before the height so it should be the second thing mentioned.

Sketcher: fix Line tool settings mode name

---

src/Gui/NavigationStyle.cpp

With navigation animations, and the rotation center indicator enabled, the rotation center was shown when the spinning animation was active. For example, after dragging in the OpenInventor navigation style or when using Tools->view  turntable...->Play. I don´t think the rotation center should be shown in animations. Furthermore, the shown rotation center in the spinning animation is wrong.
This change stops showing the rotation center in spinning mode.

Gui: Hide rotation center when in spinning mode

---

src/Gui/Splashscreen.cpp

Change [code] to ``` as code tag don't recognize and user need manualy correct tag when post About info on github.

Correct code tag for info

---

src/Mod/Path/Path/Post/UtilsArguments.py
src/Mod/Path/Path/Post/scripts/refactored_centroid_post.py
src/Mod/Path/Path/Post/scripts/refactored_grbl_post.py
src/Mod/Path/Path/Post/scripts/refactored_linuxcnc_post.py
src/Mod/Path/Path/Post/scripts/refactored_mach3_mach4_post.py
src/Mod/Path/PathTests/TestRefactoredMach3Mach4Post.py

This is part of the work for  #6117.
This is one in a series of PR's where I am taking code from at least 4 postprocessor files partially written by different people, combining them into a few files, then trying to make the code more consistent and simpler. The long term goal is to enable much simpler postprocessor files with much less copied code in each postprocessor file and much more "shared" code in the Utils*.py files.
In this PR I added typing information to the refactored postprocessors.

Path:  Added typing to the refactored postprocessors.

---

src/Mod/Path/CMakeLists.txt
src/Mod/Path/Path/Post/scripts/wedm_post.py

Added Path PostProcessor for old WEDM machines configurable for different machines:
G91 incremental coordinates
--relative				(Dissabled by default)
Specific comment character
--comments-character			(None by default)
Specific space character, use "" to ommit spaces
--command-space				(" " by default)
Add character before newline
--endline-character			(None by default)
Multiplier for machines that use not standard dimensions like micrometers (1000)
--scale					(1 by default)
Define decimal points
--precision				(3 for mm, for inch by default)
Add trailing 0s
--fixed-length				(0 (disabled) by default)
G0 rapid moves disabled by default, replaced with G1
--use-rapids				(Set flag to enable G0)
Disable setting units on output code G20/21
--omit-units				(Set flag to avoid setting units) …

Added Path PostProcessor for old WEDM machines

---

src/Mod/Sketcher/App/SolverGeometryExtension.h
src/Mod/Sketcher/Gui/CommandConstraints.cpp

Fixes #11165
When the user select an arc with Sketcher_Dimension, if the arc's radius is not a DoF, then the tool offer arc angle as a first option.
@maxwxyz it is working in all cases where the radius is constrained so that's nice.

Sketcher_Dimension: If radius of arc is not DoF, then offer arc angle first

---

src/Gui/EditableDatumLabel.cpp
src/Gui/EditableDatumLabel.h
src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
src/Mod/Sketcher/Gui/DrawSketchController.h
src/Mod/Sketcher/Gui/DrawSketchDefaultWidgetController.h
src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h
src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h

@abdullahtahiriyo this PR fixes a first batch of comments that has been made.
It does not implement the preference to disable onviewparameters as you are doing it already.
Fixes issues by @0penBrain 
> * Most severe one is probably the Tab management. Eg. when drawing a rectangle, X coord is the selected one. If I press Tab, I go to Y coord. Fine. But here if I press Tab again, then coord selection is lost forever. I would expect Tab only to circle between currently available coords/dims. Also I'd expect Shift+Tab to work (circling in the other direction).
> * While keeping the coord/dim boxes on the viewport is well handled on top and left, it isn't on right and bottom where they disappear out of view.
> 
> * The mode named "Diagonal corners" isn't. It is "1 corner + length & width". A …

[Sketcher] Tool parameter : various fixes

---

src/Mod/Sketcher/Gui/DrawSketchController.h
src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h
src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
src/Mod/Sketcher/Gui/DrawSketchHandler.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

As per:
https://forum.freecad.org/viewtopic.php?p=716863#p716863
Problems:
* Continuous mode is not well handled. Eg. drawing a rectangle, if I press Esc/RMB after clicking the first point (and before clicking the second), the rectangle feature is just left, instead of just canceling the current rectangle and be ready for a new one.
* I got some cases where pressing Esc does nothing, but I'm not able to reproduce reliably, so will eventually come back later on this one.
Solution:
- ESC or RMB will reset the handler to the first state machine state if not in the first state. If already in the first state, it terminates the handler.

Sketcher: continuous mode improvements

---

src/Mod/Draft/draftobjects/base.py

There are more objects where `props_changed_placement_only` should always return `False`. The common denominator seems to be a non-empty OutList.
https://github.com/FreeCAD/FreeCAD/issues/8771
https://forum.freecad.org/viewtopic.php?t=82436

Draft: improved props_changed_placement_only function

---

src/Mod/Draft/Resources/ui/preferences-draftsnap.ui
src/Mod/Draft/draftguitools/gui_edit.py
src/Mod/Draft/draftguitools/gui_grid.py
src/Mod/Draft/draftguitools/gui_snapper.py
src/Mod/Draft/draftguitools/gui_trackers.py

This PR improves the behavior of the Draft grid:
* Options in the preferences: "Always show the grid" and "Show the grid during commands".
* The parameters are used for new views. In existing views the grid can be toggled either during a command or when no command is active.
* When switching to a different workbench all grids are hidden unless GridHideInOtherWorkbenches is set to `False`. This can be a Fine-tuning parameter IMO.
Notes:
* The defaultCameraHeight parameter becomes obsolete. It was only used in very specific circumstances.
* The code of PR #8818 becomes obsolete. It makes more sense to use `App.activeDraftCommand` instead of adding a `tool` argument to some functions. Will do some related cleanup later.
* Improved alignment for the related preference ui. The checkbox …

Draft: Improve grid behavior

---

src/Mod/TechDraw/Gui/QGIFace.cpp
src/Mod/TechDraw/Gui/QGIFace.h
src/Mod/TechDraw/Gui/QGIViewPart.cpp
src/Mod/TechDraw/Gui/QGIViewSection.cpp
src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
src/Mod/TechDraw/Gui/ViewProviderViewPart.h
src/Mod/TechDraw/Gui/ViewProviderViewSection.cpp
src/Mod/TechDraw/Gui/ViewProviderViewSection.h

This pull request implements #6527 with the possibility to set color and transparency of faces per view. The default color and transparency are obtained from TechDraw Preferences - Color - (Transparent) Faces setting. On top of that, also the color and transparency of the section cut surface can be set independently of the color of the faces.
For transparency values 0 (opaque) and 100 (invisible) everything works perfectly. However because the transparency can be set as a percentage (identically what the 3D view allows), there are some issues, which can not be easily resolved. Let's inspect the figure below, all views have faces color set to blue rgb(0, 0, 255) and transparency to 50%:
-  View1 is drawn as desired and expected. There are no problems with single face views.
- View2 …

[TechDraw] Fixes #6527 - Implement face transparency

---

src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h

================================================================
In some DSHs instead of the convenience function, the code is being duplicated because of the need to access the geometry after pushing it to the std::vector.
This commit leverages emplace_back return reference to improve code reuse.

Sketcher: DSH - improving geo creation helpers for ShapeGeometry

---

src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h

Previous version return an reference to the smart pointer to generic Part::Geometry.
This version returns a type specific naked pointer, while ShapeGeometry keeps ownership and memory management, so if an arc is created a Part::ArcOfCircle is returned.

Sketcher: DSH Default - improve return value of ShapeGeometry functions

---

src/Gui/Action.cpp

It might happen that files stored in MRU list do not exist anymore e.g. have been deleted by the user from the file system.
In such a case they shouldn't be added to "Open recent" menu.
This PR fixes #11247

Gui: Do not add non-existing files to open recent menu

---

src/Gui/ReportView.cpp

Console error, warnings, ... allow for a notifiername. This appears separately in the notification area. However, the report view ignores it.
This commit prepends the notifier string separated by a semicolon, if not empty.
It solves the problem that, if the message did not include the notifier, this was not indicated in the Report View.
If the message included the notifier, then it was duplicated in the notification area.

Gui: ReportView - include notifier string

---

src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h

Improving helper function to return a reference.

SketcherGui: DSH Default - return reference in ShapeConstraint helpers

---

src/Mod/Draft/Draft.py
src/Mod/Draft/Resources/ui/preferences-draft.ui
src/Mod/Draft/draftutils/utils.py

The tolerance function now derives its value from the precision preference.
Additonally:
Removed the epsilon() function. It did not make sense and was not used.

Draft: remove the tolerance preference

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Problem: The function worked for sketches in X-Y Plane. But not for other orientation.
Solution: Account for the sketch orientation.

SketcherGui: Fix preselectAtPoint for non X-Y orientations

---

src/Mod/Draft/DraftGui.py
src/Mod/Draft/Resources/ui/preferences-draft.ui

This PR removes the copymode (Global copy mode) preference.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=82679
Additionally useSupport is removed from preferences-draft.ui, turning it into a fine-tuning preference. Use of this feature is rare and may not be supported in the future. No need to present this preference to new users in the UI.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=80689

Draft: prefs: remove copymode, useSupport no longer via UI

---

src/Gui/QuantitySpinBox.cpp

Problem:
When the value set is a double, a new Quantity is created, which does not follow the previously configured format (setDecimals).
Solution:
To copy the old format to the newly created quantity.

Gui: QuantitySpinBox - keep format on setValue

---

src/Mod/TechDraw/App/DrawView.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneralImp.cpp
src/Mod/TechDraw/Gui/MDIViewPage.cpp
src/Mod/TechDraw/Gui/PreferencesGui.cpp
src/Mod/TechDraw/Gui/PreferencesGui.h
src/Mod/TechDraw/Gui/QGEPath.h
src/Mod/TechDraw/Gui/QGIEdge.h
src/Mod/TechDraw/Gui/QGIFace.h
src/Mod/TechDraw/Gui/QGIPrimPath.cpp
src/Mod/TechDraw/Gui/QGIPrimPath.h
src/Mod/TechDraw/Gui/QGIVertex.h
src/Mod/TechDraw/Gui/QGIView.cpp
src/Mod/TechDraw/Gui/QGIView.h

When creating a larger drawing, the need to hold the Ctrl key every moment is quite tedious . This pull request adds "Enable Multiselection Mode" option to TechDraw's General preferences, which allows to add/remove vertices, edges and faces in the same view to/from the selection by plain clicking. If more than one item in the tree is selected, the multiselection mode is not activated.
The pull request consist of 2 commits fixing the issues I have encountered during the development, then 4 commits cleaning the code or removing obsolete features and finally the single commit implementing the multiselection mode.
The way how multiselection mode for TechDraw is implemented is rather a "hack". Unfortunately, QGraphicsItem does not support SelectionMode in the manner the QAbstractItemView does. …

[TechDraw] Multiselection mode for vertices/edges/faces

---

src/Gui/ExpressionBinding.cpp

If the QLineEdit is disabled the current color group of the cached QPalette is set to 'Inactive'. Now when enabling the QLineEdit the wrong palette is set and the text looks like it's inactive.
See forum: https://forum.freecad.org/viewtopic.php?p=719459#p719459

Gui: save active palette

---

src/Mod/Draft/DraftGui.py
src/Mod/Draft/Resources/ui/preferences-draft.ui
src/Mod/Draft/draftguitools/gui_stretch.py

With this PR the following 5 command modes are automatically stored in the preferences:
* "ContinueMode"
* "RelativeMode"
* "GlobalMode"
* "fillmode" (existing preference, removed from the Preferences Editor)
* "SubelementMode"
Additionally:
Three commands (Draft_Ellipse, Draft_Rectangle and Draft_Stretch) call `setRelative` after the 1st point has been specified and would permanently switch on relativeMode. After this PR this switch is temporarily.

Draft: store more command modes in prefs

---

src/Mod/Arch/importIFClegacy.py
src/Mod/Arch/importOBJ.py

To avoid having to restart after changing the Draft precision parameter.

Arch: remove global precision variables

---

src/Mod/Part/App/Geom2d/Curve2dPyImp.cpp

Hi,
Currently, the toShape() method of Geom2dCurve is not consistent upon its various signatures.
When no face or surface support is passed, the resulting edge contains both a 3D curve and a PCurve (on the XY plane).
When a face or surface support is passed, the resulting edge contains only a 3D curve. The PCurve data gets lost.
A face built from such edges is not valid.
The proposed fix avoids the loss of the PCurve data in these situations.
Test code:
```
import FreeCAD
import Part
vec2 = FreeCAD.Base.Vector2d
def info(edge):
print(f"Curve 3D : {edge.Curve}")
print(f"Curve 2D : {edge.curveOnSurface(0)}")
surf = Part.Cylinder()
p1 = vec2(1.0, -1.0)
p2 = vec2(2.0, -1.0)
l12 = Part.Geom2d.Line2dSegment(p1, p2)
e1 = l12.toShape()
info(e1)
e2 = l12.toShape(surf)
info(e2)
```

Part : fix edge creation of Geom2d curves

---

src/Gui/DlgPreferences.ui
src/Gui/DlgPreferencesImp.cpp
src/Gui/DlgPreferencesImp.h
src/Gui/PrefWidgets.cpp
src/Gui/PropertyPage.cpp
src/Gui/PropertyPage.h

This PR will introduce new navigation style for preferences dialog based on `QTreeView`. It will consolidate naviagtion into left pane of the settings dialog removing tab navigation from the main view. In theory it also allows deeper structures for preferences to be introduced but it is not recommended and not used as of now. 
This PR also is a major refactor of the `DlgPreferencesImp` class. I've tried to simplify overall structure and remove code that is no longer needed due to previous updates and things that are no longer problem. I do not see any issues with the current state of the UI but it is possible that I removed a little bit too much.
I'm also far from being a QT expert so there may be some questionable solutions that should be implemented in different way - feel free to point …

[Gui] Rework preferences navigation as TreeView - Part 1

---

src/Gui/NavigationAnimation.cpp
src/Gui/NavigationStyle.cpp
src/Gui/NavigationStyle.h
src/Gui/View3DInventorViewer.cpp

This PR fixes #11243 and re-fixes #6836. #9699, The original fix for #6836 was a huge improvement but I was still able to reproduce the cut corners and sometimes random glitches. With this fix that does not happen anymore, at least during my testing.
The new approach finds a bounding sphere of the scene, then it is repositioning the camera such that the `nearDistance` can be 0 and the `farDistance` the diameter of the bounding sphere. Finally, to fix #11243, we change the focal distance so the focal point stays the same.
Currently, this fix runs only in `NavigationStyle::reorientCamera(..)`. There are also other methods that change the camera where it is still possible to get glitchy results.  I am going to take a look at coin3d `SoRenderManagerP::setClippingPlanes()` to see if I can make …

Gui: Fix window center rotation mode and orthographic view clipping

---

src/App/ComplexGeoData.cpp
src/App/ComplexGeoData.h
src/App/PropertyGeo.cpp
src/App/PropertyGeo.h
tests/src/App/ComplexGeoData.cpp

Add the serialization functions to `ComplexGeoData`, and completes the `PropertyComplexGeoData` implementation of the Toponaming branch. Note that this code is NOT called by any active code yet, it exists to support upcoming TNP work.
The first commit is just @realthunder's `ComplexGeoData` code as originally written. The second commit applies our clang-format and resolves most issues identified by clang-tidy. The third commit adds the code for `PropertyComplexGeoData`, and the fourth commit is a minor refactor to address code complexity.
The fifth commit adds some simple tests for the serialization code: no tests exist yet for the deserialization, which will require some refactoring to be testable.

ComplexGeoData and PropertyComplexGeoData serialization

---

src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
src/Mod/Sketcher/Gui/Workbench.cpp

Create a command group for trim extend split.
The goal is to reduce the size of toolbars (https://github.com/FreeCAD/FreeCAD/issues/11208).

[Sketcher] Group Trim/extend/split.

---

src/Mod/Part/App/Tools.cpp

Fix #8394 
I'm unsure about this, as there was no precedent for throwing an exception in this source module.  It does seem to operate correctly, but maybe there's a more appropriate solution.

Defend against surface not created from invalid face

---

src/Mod/Path/PathTests/TestRefactoredTestPost.py
src/Mod/Path/PathTests/TestRefactoredTestPostGCodes.py
src/Mod/Path/PathTests/TestRefactoredTestPostMCodes.py

This is one in a series of PR's where I am taking code from at least 4 postprocessor files partially written by different people, combining them into a few files, then trying to make the code more consistent and simpler. The long term goal is to enable much simpler postprocessor files with much less copied code in each postprocessor file and much more "shared" code in the Utils*.py files.
In this PR I added some lines of "###..." between the tests to make them easier to find and fixed a few typo's.

Path:  Added separator lines to make the tests easier to find

---

src/Mod/Part/BOPTools/BOPFeatures.py
src/Tools/SubWCRev.py

See https://forum.freecad.org/viewtopic.php?t=82687
When doing a boolean cut using a link as a cutting tool there is an error message in the report view related to copying visual attributes, in particular the view object's DisplayMode property.  When the object is a link the view object's DisplayMode property is "Link", which is not in the enumeration ["Flat Lines", "Shaded", "WireFrame", "Points"].
This PR will fetch the DisplayMode of the linked object and copy that instead of the link object itself.
@realthunder Would you mind taking a look at this?  Perhaps there is a better way?

[Part Workbench]Prevent error when using link in boolean cut

---

src/Mod/Import/App/dxf/ImpExpDxf.cpp

Rather than generating Python code and interpreting it, which, in C++, is fraught with issues of creating the correct syntax for a str token when the text contains certain special characters like double-quote and backslash, the modified code makes call(s) to PyObject_CallObject which takes the C++ string and makes the appropriate conversion itself. The steps in building the Position passed to make_text are also done using c++ objects until the final Python Placement object is needed.
Closes #11408

Use PyObject_CallObject rather than interpreting generated code

---

src/Mod/Part/App/OpenCascadeAll.h

When https://github.com/FreeCAD/FreeCAD/pull/7193 merged today it broke the headers when using PCH -- adding this OCCT header to OpenCascadeAll.h resolves the issue.

Part: Add BRepFeat_MakeRevol.hxx to Precompiled header

---

src/Mod/Part/App/HLRBRep/HLRBRep_AlgoPy.xml
src/Mod/Part/App/HLRBRep/HLRBRep_PolyAlgoPy.xml
src/Mod/Part/App/HLRBRep/HLRBRep_PolyAlgoPyImp.cpp
src/Mod/Part/App/HLRBRep/HLRToShapePy.xml
src/Mod/Part/App/HLRBRep/PolyHLRToShapePy.xml

closes #10728.
Note, that this PR overrides  #11233.
It is based on the same commit of @RohanMishra315 but builds on it.
This PR makes the following contributions:
- Since OCCT has a C++ interface, the Python interface needs to be adapted. I carefully checked the types of the Python bindings and matched the documentation accordingly.
- OCCT has lots of missing documentation. I tried to fill in missing pieces as much as possible. As a result, the HLR documentation in FreeCAD's Python interface is now better than OCCT's! (As an example [rg1LineVCompound() in the **poly** algorithm](https://dev.opencascade.org/doc/refman/html/class_h_l_r_b_rep___poly_h_l_r_to_shape.html#a8e64459b306d4d8684766663519f4132) is documented in OCCT but not in the [**non-poly** …

[Part] Missing API documentaton Python HLR

---

src/Mod/Draft/draftutils/params.py

The Draft statusbar widgets should not be displayed in the Arch and BIM workbenches.
Also updated the copyright header to the current standard.

Draft: param observer: improve handling of statusbar widgets

---

src/Mod/Draft/Resources/ui/preferences-drafttexts.ui
src/Mod/Draft/draftguitools/gui_annotationstyleeditor.py
src/Mod/Draft/draftutils/init_draft_statusbar.py
src/Mod/Draft/draftutils/utils.py
src/Mod/Draft/draftviewproviders/view_dimension.py
src/Mod/Draft/draftviewproviders/view_draft_annotation.py

Additionally:
* Added the DimShowLine preference. Layout of the tab will be updated later.
* Improved handling of DraftAnnotationScale preference: catch division by zero and use it for the default anno style.

Draft: make default anno style non-global

---

src/3rdParty/salomesmesh/inc/SMESH_SMDS.hxx
src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp

vtkMTimeType was introduced in vtk 7.1 so minimum required vtk version with this is 7.1 which available on ubuntu 20.04
@wwmayer

Fix #11449 3rdPart/salomesmesh vtk 9.3 compatibility

---

src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg

This pull request implements #7317 so face area computation is not limited to polygons. I have tested several shapes with arcs and bezier curves, the computation seems to work fine.
There are other 2 minor changes. First is a proposed icon change. I have tried to create an icon, which would better represent the "face area" operation. From my point of view it looks better, however if the old one stays, I am not offended!
The second additional change is converting length units ending with ^2 (squared) to length units with ² superscript. E.g. "mm^2" → "mm²". Again, for me this looks much better, but definitely it is not something extra important.
I believe the change will fulfill the expectations, in case of any issues please let me know.

[TechDraw] Fixes #7317 - Calculate Area of Arbitrary Faces

---

src/Gui/Inventor/MarkerBitmaps.cpp
src/Gui/PreferencePages/DlgSettings3DViewImp.cpp

This isn't the first time this has been requested on the forum but see the most recent discussion https://forum.freecad.org/viewtopic.php?t=82927
As I only have a 2K screen they do appear quite large but I'm aware of how much that will be reduced on higher DPI.
Hopefully one of the devs or self compile users with a 4K screen can test this on their setup.

[Gui] Add 20, 25 and 30px marker sizes to assist users of 4K screens

---

src/Mod/TechDraw/TechDrawTools/CommandHoleShaftFit.py

In order to stop the user triggering the command when nothing is selected and if the user selects geometry such as the edge of a hole instead of a dimension then they receive constructive feedback.

[Techdraw] Hole & Shaft Fit Error Enhancement

---

src/Mod/Sketcher/Gui/CommandAlterGeometry.cpp
src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
src/Mod/Sketcher/Gui/Resources/icons/constraints/Sketcher_ToggleActiveConstraint.svg
src/Mod/Sketcher/Gui/Resources/icons/constraints/Sketcher_ToggleConstraint_Driven.svg
src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_ToggleConstruction.svg
src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_ToggleConstruction_Constr.svg

This is my attempt to make the toggle icons more uniform. And remove the confusion between toggleConstruction and carboncopy. Fixes https://github.com/FreeCAD/FreeCAD/issues/11471
The toggle construction and toggle driving icons are changing when you click them.

Sketcher : Replace toggle icons.

---

src/Mod/Draft/Resources/ui/preferences-drafttexts.ui
src/Mod/Draft/draftguitools/gui_texts.py
src/Mod/Draft/draftmake/make_text.py
src/Mod/Draft/draftutils/gui_utils.py
src/Mod/Draft/draftutils/utils.py
src/Mod/Draft/draftviewproviders/view_dimension.py
src/Mod/Draft/draftviewproviders/view_draft_annotation.py
src/Mod/Draft/draftviewproviders/view_label.py
src/Mod/Draft/draftviewproviders/view_text.py

* DisplayMode controlled by new pref DefaultAnnoDisplayMode. This replaces the old dimstyle pref.
* LineSpacing pref is now used when creating annotations. Will be added to prefs ui later.
* format_object no longer changes FontSize as this conflicted with the height parameter in the make_text function.
* make_text function updated.

Draft: improve handling of anno DisplayMode and LineSpacing

---

src/Mod/Start/Gui/Workbench.cpp
src/Mod/Start/StartPage/StartPage.py
src/Mod/Start/StartPage/TranslationTexts.py

- reloading the start page now retranslates all the texts
- extend the observer to watch language changes
Fixes #9996

Start: Allow dynamic translation of start page

---

src/Gui/NavigationStyle.cpp
src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h

#11243 was not completely fixed. This PR fixes #11243. The problem also occurred when dragging and using the scroll wheel to zoom at the same time. This only happend with rotation mode = window center and _zoom at cursor_ enabled. @maxwxyz can you confirm this works?
The problem is resolved by updating the position of the rotation center, to the new focal point, after zooming. ~~This PR also introduces a small regression which is a flickering rotation center after zooming using the scroll wheel. However, when you start dragging again without zooming then it does not flicker anymore. In my opinion not really a problem to worry about. This flickering appears to be resolved by https://github.com/coin3d/coin/pull/509.~~

Gui: Update rotation center indicator after zoom

---

src/Gui/DlgPreferences.ui
src/Gui/DlgPreferencesImp.cpp
src/Gui/DlgPreferencesImp.h

This adds QScrollArea widget to DlgPreferences which in turn allows preference pages to be scrollable. Stacked widget sizes are forced to selected widget so scroll area should appear when it is needed.
Second commit ensures that after selecting item the group is automatically expanded. User can force expansion by explcitly clicking expand button, groups expanded that way will stay expanded unless user collapses them. Otherwise non-active group will be collapsed automatically.
This PR also changes default size of the dialog to 1000x900 - for pages that are larger it results in vertical scroll.
Fixes #11511
Fixes #11530
Fixes #11004

Gui: Add ScrollArea to Preferences and auto expand groups

---

conda/environment.devenv.yml

Alter the `conda/environment.devenv.yml` to include `conda` and `mamba` as dependencies.
`mamba-devenv` will remove any package not listed in this file, removing the packages `conda` and `mamba` from the newly created conda environment.  This renders the newly created conda environment inoperable.  I believe this is a behavioral difference with `conda devenv` which was previously used.

Add conda and mamba to the conda-devenv.

---

src/Gui/Workbench.cpp

Following the discussion https://forum.freecad.org/viewtopic.php?t=82937&start=20 which seemed to reach consensus about this.
This PR hides macro toolbar by default.

Core: Hide macro toolbar by default.

---

src/Mod/PartDesign/App/FeatureHelix.cpp

After much instrumenting and trial and error, it appears we set the wrong mode when the angle is zero.  Not clear if there was some past version of the library that needed the special case removed here.  Also cleaned up a little unneeded code.
This should fix #9377

Correct #9377 issue with accuracy in AdditiveHelix

---

src/Mod/Draft/Draft.py
src/Mod/Draft/Resources/ui/preferences-draft.ui
src/Mod/Draft/Resources/ui/preferences-draftinterface.ui
src/Mod/Draft/Resources/ui/preferences-draftsnap.ui
src/Mod/Draft/Resources/ui/preferences-drafttexts.ui
src/Mod/Draft/Resources/ui/preferences-draftvisual.ui
src/Mod/Draft/draftguitools/gui_snapper.py
src/Mod/Draft/draftguitools/gui_trackers.py
src/Mod/Draft/draftutils/gui_utils.py
src/Mod/Draft/draftutils/utils.py
src/Mod/Draft/draftviewproviders/view_dimension.py
src/Mod/Draft/draftviewproviders/view_draft_annotation.py

The format_object function in gui_utils.py still requires some work (in connection with the Draft_SetStyle command). This will be done later.

Draft: implement DefaultAnnoLineWidth and DefaultAnnoLineColor prefs

---

src/Mod/Part/App/TopoShapeFacePyImp.cpp

In the past ShapeAnalysis::OuterWire() was used that may fail to determine the correct outer wire.
Forum thread: https://forum.freecad.org/viewtopic.php?t=83122

Part: use BRepTools::OuterWire to get outer wire of a face

---

src/Gui/CommandWindow.cpp
src/Gui/MainWindow.cpp
src/Gui/ToolBarManager.cpp
src/Gui/ToolBarManager.h
src/Gui/Workbench.cpp

This adds the Std_ToggleToolBarLock action mentioned in #4992. It is exposed in the context menu of toolbar and also in the view -> toolbars app menu.
Fixes #11595

Gui: Add ability to easily lock Toolbars from UI

---

src/Gui/DlgEditorImp.cpp

This is in effect a backport of https://github.com/FreeCAD/FreeCAD/commit/951aafde6085eb58711505459a7d3b13c78c5864 though the file structure changed during the 0.22.dev cycle.

[0.21] [Preferences] Exclude 8514oem from Monospace fonts

---

src/Gui/ViewProviderGeometryObject.cpp

As described by @Roy-043 in the forum (see [here](https://forum.freecad.org/viewtopic.php?t=83066)), the transparency of an object is changed from the default transparency to zero after changing the object's color.
The following script can be used to reproduce the problem and to show the resolved behavior:
```python3
import Part
doc = App.newDocument()
pg = App.ParamGet('User parameter:BaseApp/Preferences/View')
backup_default_transparency = pg.GetInt('DefaultShapeTransparency')
pg.SetInt('DefaultShapeTransparency', 70)
obj = doc.addObject('Part::Box')
assert obj.ViewObject.Transparency == 70
obj.ViewObject.ShapeColor = (0.5, 0.0, 0.0)
if obj.ViewObject.Transparency != 70:
print('WARNING: transparency was changed to',
obj.ViewObject.Transparency, 'when changing the color.')
else: …
```

Gui: fix partially initialized default transparency

---

src/Mod/TechDraw/App/Geometry.cpp
src/Mod/TechDraw/App/Geometry.h
src/Mod/TechDraw/Gui/CommandExtensionPack.cpp

This pull requests hands over the computation of intersections to OCC, so we  to compute them between any two arbitrary edges the TechDraw views use. As a result, the number of intersection points created can be now higher than two, e.g. for BSplines.
The current algorithm did not limit the results to the edge boundaries, which I find quite useful, so I have tried to preserve this behavior, though for lines it does not have much sense to create unreachable cosmetic points in a galaxy far far away. Therefore there is a limit derived from the "crazy edge" detection procedure, namely 10.000mm. Of course, this constant can be changed to any other reasonable value.
I have tried to test the change as much as possible, however still there can be some catches. In case of any issues, please let me …

[TechDraw] Use OCC to compute intersections for any types of edges

---

src/Mod/TechDraw/App/Preferences.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp
src/Mod/TechDraw/Gui/QGIViewPart.cpp

This PR implements a fix for hidden line style where the wrong parameter was being used.  It also addresses some confusion between a line style's position in the list of available styles vs the actual line number.

[TD]Fix hidden line style

---

src/Mod/Part/Gui/SoBrepFaceSet.cpp

This fixes #11517. See https://github.com/FreeCAD/FreeCAD/issues/11517#issuecomment-1837139082 for the cause of the problem.
Using `materialIndex.setValuesPointer()` only when the values change prevents the continuous cache invalidation and fixes the low fps.
To make this work I also had to remove [these](https://github.com/FreeCAD/FreeCAD/commit/6711e53d1681e86d9ea88783fa9353a8b84c13ce#diff-e4fb66281089c4211e8116c2a8bf4e05736a12e47518ca5786f3481ddb4f714fL646-L648) lines. I am not sure what the intention of these lines was and if removing it causes any side effects. Please review carefully.

Part: Use materialIndex.setValuesPointer() only if the new values are different

---

contrib/.vscode/tasks.json

The task type `shell` on Windows would invoke the user's default shell, which may not always correctly run the `conda/setup-environment.cmd` script.  Using the type `process` invokes the script directly, avoiding the issue.

VSCode: Change setup conda environment task type to process.

---

src/Gui/DemoMode.cpp
src/Gui/NavigationAnimator.cpp
src/Gui/NavigationAnimator.h
src/Gui/NavigationStyle.cpp
src/Gui/NavigationStyle.h
src/Gui/PreferencePackTemplates/View.cfg
src/Gui/PreferencePages/DlgSettingsNavigation.cpp
src/Gui/PreferencePages/DlgSettingsNavigation.ui
src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h
src/Gui/View3DSettings.cpp

There are some complaints about the infinite spin animation in the OpenInventor and CAD navigation style after dragging.  [here on reddit](https://www.reddit.com/r/FreeCAD/comments/17yhq1f/stop_that_crazy_autorotation/), and here https://github.com/FreeCAD/FreeCAD/issues/11243#issuecomment-1789149331. I personally also find this spin animation slightly annoying but I would still like to use the other animations so disabling animations is not the solution.
This PR groups settings for animations together and adds a separate checkbox to enable the spin animations. This checkbox is disabled by default. With this change it is still possible to have animations when selecting standard views or the navigation cube but the annoying spin animation will only be played when you enable it.

Gui: Add a separate checkbox for enabling spinning animations

---

src/Gui/DlgPreferences.ui
src/Gui/DlgPreferencesImp.cpp

This ensures that preference windows does not start taller than available geometry. Preferences dialog will now leave at least 100px of free space so it does not exceed available screen height and does not take entire screen height.

Gui: Cap starting height of Preferences dialog

---

src/Mod/Path/Path/Main/Gui/Sanity.py

Attempts to fix https://github.com/FreeCAD/FreeCAD/issues/11479 though there seems to be some deeper issue that I just can't replicate with the OP's setup.

[Path] Sanity, change default zero CycleTime from float to string

---

src/Mod/Sketcher/Gui/CommandSketcherTools.cpp

* Menu text "Offset geometry" (singular).
* Shortcut "Z, O" was already in use. Changed to "Z, T".

Sketcher: Sketcher_Offset: menu text and shortcut

---

src/Mod/TechDraw/App/DrawProjectSplit.cpp
src/Mod/TechDraw/App/DrawProjectSplit.h

In certain views, there are unselectable closed areas, which can not be selected and thus not hatched. The main problem lied in assumption that edges are identical, if their end points are identical, however this can be true only for line segments, but not for arcs etc. Here is a basic figure of 180° arc intersected by 2 line segments illustrating the problem:
Rather than fixing this particular issue, I suggest to use OCC's General Fuse algorithm to perform the operation of fusing overlapping edges and splitting them at their intersections.
I am attaching a file containg a sketch consisting of 2 BSplines and 1 line segment and a view of this sketch on a TechDraw page. The current TechDraw implementation lets the user to select only 2 upper areas together at once, but not the bottom area. …

[TechDraw] Use OCC to split intersecting edges

---

src/Mod/Draft/draftguitools/gui_snapper.py
src/Mod/Draft/draftutils/utils.py

It is superfluous. The maxSnapEdges parameter can be set to zero.

Draft: remove maxSnap parameter

---

src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfHyperbola.h

The crash seems to be caused by the notification area function trying to retrieve the name of a deleted object.
I moved the line `sketchgui->purgeHandler();` after the function, thus fixing the crash described in #10975.
CC @abdullahtahiriyo

[Sketcher] Fix crash described in #10975

---

src/App/PropertyStandard.cpp
src/Gui/NotificationArea.cpp

Two requests under issue #11183:
- Do not expose developer message to the user
- Improve the notification area so that a same message is not repeated over and over, but grouped together indicating the number of repetitions.

Notification Area Improvements

---

src/Mod/Draft/Resources/ui/TaskPanel_SetStyle.ui
src/Mod/Draft/Resources/ui/preferences-drafttexts.ui
src/Mod/Draft/draftguitools/gui_setstyle.py
src/Mod/Draft/draftutils/init_draft_statusbar.py
src/Mod/Draft/draftutils/params.py
src/Mod/Draft/draftutils/utils.py
src/Mod/Draft/draftviewproviders/view_draft_annotation.py

This parameter replaces DraftAnnotationScale.
The parameter can be changed in the preferences and with the Draft_SetStyle command.

Draft: Introduce DefaultAnnoScaleMultiplier parameter

---

src/Mod/Draft/draftutils/params.py

This PR introduces a new get_param function. For its default values it checks a dictionary largely filled by reading the preferences UI files. The goal is to have all defaults in one place to avoid inconsistencies. The dictionary is created once and then stored in a global variable.
Once merged this function will be implemented in Draft and Arch. The get_param function in utils.py will become obsolete.
Related issue: #10176

Draft: new get_param function with defaults

---

src/Mod/Draft/importDXF.py

See: https://github.com/yorikvanhavre/Draft-dxf-importer/pull/28

Draft: increase DXF Python library version to 1.42

---

src/Mod/Path/Path/Op/Area.py

Fix #11411 
I've spent a while going through all the Area and AreaParams code, and most of Path.  As far as I can see, there are several other places using precision at 1e-06.
From a practical milling standpoint, 0.1 microns or 1e-04 mm or 4e-06 inches appears to be the limit, so this seems reasonable.
I wasn't able to find any other ways to fix this problem, nor was I successful in pinpointing what change between 0.20.2 and 0.21.0 triggered it.

Tweak section tolerance to make base layer of paths work again

---

src/Mod/Draft/Resources/ui/preferences-dxf.ui
src/Mod/Draft/importDXF.py
src/Mod/Import/App/AppImportPy.cpp
src/Mod/Import/App/dxf/ImpExpDxf.cpp
src/Mod/Import/App/dxf/ImpExpDxf.h
src/Mod/Import/App/dxf/dxf.cpp
src/Mod/Import/App/dxf/dxf.h
src/Mod/Import/Gui/AppImportGuiPy.cpp
src/Mod/Import/Gui/CMakeLists.txt
src/Mod/Import/Gui/dxf/ImpExpDxfGui.cpp
src/Mod/Import/Gui/dxf/ImpExpDxfGui.h

Fixes #8806
Fixes #6924
This change:
1. Provides a hook for GUI-dependent code in the C++ importer (since color is a Gui concept) via a new class `ImpExpDxfReadGui` derived from `ImpExpDxfRead` and ultimately created by importDXF.py if the ImportGui module is available.
2. Sets the color on created FreeCAD objects based on the color specified in the DXF file, including handling BYLAYER color, using a new virtual methods which do nothing in `ImpExpDxfRead` but set color in `ImpExpDxfReadGui`.
3. Refactors the reader code in CDxfRead to remove substantial duplication involved in reading the individual attribute records that make up each entity. My goal here was to eliminate, or at least greatly reduce, the lint that shows up when a PR is submitted, and on noticing that it was mostly the …

Make C++ DXF importer set entity colors per DXF contents

---

src/Mod/Draft/draftutils/params.py

See #11677
Added a parameter to the dictionary. The get_parameter and set_parameter functions now print a warning if a parameter is not found.

Draft: implement new get_param functions (step 6)

---

src/Mod/Draft/draftgeoutils/geometry.py

This avoids issues with TechDraw views of Arch models if there is no active 3D view.

Draft: intermediate fix for get_normal: check if 3D view exists

---

src/Mod/Sketcher/App/Sketch.cpp
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
src/Mod/Sketcher/Gui/Utils.cpp
src/Mod/Sketcher/Gui/Utils.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Propagate circles distance constraint to arcs.

Sketcher: Arc to Other distance constraint

---

src/Mod/TechDraw/App/DrawViewDetail.cpp
src/Mod/TechDraw/App/DrawViewDetail.h
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawColors.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawColorsImp.cpp
src/Mod/TechDraw/Gui/PreferencesGui.cpp
src/Mod/TechDraw/Gui/PreferencesGui.h
src/Mod/TechDraw/Gui/QGISVGTemplate.cpp
src/Mod/TechDraw/Gui/QGIViewPart.cpp
src/Mod/TechDraw/Gui/TemplateTextField.cpp
src/Mod/TechDraw/Gui/TemplateTextField.h

This PR implements 2 changes:
> use of an underline instead of the small green squares to identify editable text in templates.
> adds preferences and properties to control the display of detail view highlights.

[TD]Template field underline

---

src/Gui/3Dconnexion/GuiNativeEventMac.cpp

For quite some time the MacOS version of FreeCAD detects the SpaceMouse from 3DConnexion but is unable to receive any events when using the recent drivers. The last working driver seems to be the 10.7.0.
This PR changes the registration of the application to the driver to use the wildcard constant instead of a bundle ID that the FreeCAD does not seem to possess. The driver then uses the application name to do the check.
Tested on MacBook Air M2 15" running Sonoma 14.2, with SpaceMouse Pro and driver 10.8.2.

fix compatibility with current Mac 3Dconnexion driver

---

.github/workflows/actions/linux/build/action.yml

Errors in the Ubuntu builds are not caught because the exit code of `tee` is observed instead of the exit code of the build.
Setting the shell option `set -o pipefail` will propagate the exit code of any process in a pipeline that is not successful, permitting the CI script to get an accurate assessment of the build status.

CI: set pipefail Linux build action

---

src/Gui/Action.cpp
src/Gui/Action.h
src/Gui/Command.cpp
src/Gui/Command.h
src/Mod/Sketcher/Gui/CommandConstraints.cpp

This is fix to issue mentioned in the #11717, on discord and forum that for smart dimension tool the chosen tool should not be remembered. This will ensure that the "smart" tool is always visible on the toolbar and other tools are accessible in case that such explicit choice is needed.
It does not have issue attached as I simply wanted to check how hard it would be to fix - quite easy as it seems.
https://github.com/FreeCAD/FreeCAD/assets/747404/684d84bb-60d0-4c6e-9685-89cfbd8b953e
I changed only the behavior of smart dimension tool, everything else should be considered as part of other PRs.

Gui: Allow ActionGroups to not remember choice

---

.github/workflows/actions/linux/configure/action.yml
.github/workflows/actions/linux/install/action.yml
.github/workflows/actions/runCPPTests/runSingleTest/action.yml
.github/workflows/actions/runPythonTests/action.yml

As noted in [this comment](https://github.com/FreeCAD/FreeCAD/pull/11758#issuecomment-1859788651), additional actions should fail if any sub-process fails.
This commit adds `pipefail` option to:
* .github/workflows/actions/linux/configure/action.yml
* .github/workflows/actions/linux/install/action.yml
* .github/workflows/actions/runCPPTests/runSingleTest/action.yml
* .github/workflows/actions/runPythonTests/action.yml

CI: add pipefail to additional workflow actions.

---

src/App/GroupExtension.cpp
src/Mod/Arch/TestArch.py

Fix for #9277.
This fixes the immediate issue with space bar or Std_ToggleVisibility,  Thats a step forward.  It seems to allow all the visibility switches at each level to not be overridden when you set them manually,  fixing that issue as well.
I'm not sure if the exact behaviors when you have architectural parts inside a group inside a BuildingPart are completely what we want - you can turn visibility on and off at each level, and it affects the parts at the bottom just fine.  I'm not sure what our expected behaviors are for all permutations of Vis On/Off inside of Vis On/Off inside of Vis On/Off.
The complexity level here is fairly high ( at least for my experience level in this codebase), and it took quite a bit of debug time to locate the issue.

Add test for child visibility in Arch BuildingPart or GroupExtensions

---

src/Mod/TechDraw/App/ShapeExtractor.cpp

This PR addresses a issue with link objects with element count != 0.

[TD]prevent gp_GTrsf::Trsf() - non-orthogonal GTrsf

---

src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
src/Mod/TechDraw/Gui/DrawGuiUtil.h
src/Mod/TechDraw/Gui/MDIViewPage.cpp
src/Mod/TechDraw/Gui/MDIViewPage.h
src/Mod/TechDraw/Gui/QGIView.cpp
src/Mod/TechDraw/Gui/QGIView.h
src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
src/Mod/TechDraw/Gui/QGIViewBalloon.h
src/Mod/TechDraw/Gui/QGIViewDimension.cpp
src/Mod/TechDraw/Gui/QGIViewDimension.h
src/Mod/TechDraw/Gui/QGIViewPart.cpp
src/Mod/TechDraw/Gui/QGIViewPart.h

As Part View is able to provide sub-items to selection, it is desirable to make the vertices/edges/faces also visually selected, when the current selection is changed e.g. from Python code.
This pull request adds this ability, while trying to respect the subitems selection attitude. This means when nothing is selected:
`Gui.Selection.addSelection('doc', 'View')` adds only the view to the selection, but none of the subitems. The frame and label of the view are highlighted.
`Gui.Selection.addSelection('doc', 'View', 'Edge1')` adds the 1st edge to the selection, highlights it, causes the view item to be selected in the tree, but does not highlight the view frame and label on the TechDraw page.
`Gui.Selection.addSelection('doc','View', '')` adds the view, but none of its subitems. It acts in …

[TechDraw] Implement proper selection of subitems

---

src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/CommandDecorate.cpp
src/Mod/TechDraw/Gui/CommandExtensionDims.cpp

This pull request aims to replace "horrible hacks" with plain touch() call doing basically the same thing, i.e. updating the tree view, so the dimension item becomes a child of its part view. There should be no functionality changes except auto-selecting the newly created dimension for improved workflow.
In case any there are any problems or unexpected effects, please let me know.

[TechDraw] Tree view update refactoring

---

src/Mod/Part/App/CMakeLists.txt
src/Mod/Part/App/TopoShape.h
src/Mod/Part/App/TopoShapeCache.cpp
src/Mod/Part/App/TopoShapeCache.h
src/Mod/Part/App/TopoShapeExpansion.cpp
tests/src/Mod/Part/App/CMakeLists.txt
tests/src/Mod/Part/App/TopoShapeCache.cpp

This code is from @realthunder's Toponaming branch, modified slightly for testability and to clarify some names. The tests are new code. The tests are not exhaustive, but serve to exercise and demonstrate the use of the new class. This class forms the foundation of the very large changeset in the TopoShape class, and while it is unused in the current codebase, it will be used extensively in upcoming additions to this class.
My intent is to squash this into two commits: one that represents @realthunder's original work, and one that is my changes to it.

Part/Toponaming: Add TopoShape cache

---

src/Mod/TechDraw/Gui/ViewProviderDrawingViewExtension.cpp

This PR implements a fix for an unusual situation reported here: https://forum.freecad.org/viewtopic.php?t=83825
If a TechDraw object somehow becomes disconnected from its parent or page, then there can be a crash when the ViewProvider attempts to handle a drop operation.  It is not clear how the situation in the forum thread was created.

[TD]fix fail when dropping onto corrupt object

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

https://github.com/FreeCAD/FreeCAD/pull/11745#issuecomment-1870435624
Always show auto HorVer tool command in the toolbar when the tool is present (concise toolbar option by @obelisk79 )
Currently the last used tool is shown as command in the toolbar, this PR makes the auto tool not remember the last sub tool, like currently also implemented in the auto dimension tool.

Always show auto HorVer tool command in the toolbar (like auto dimension) when concise option is enabled

---

src/Mod/Path/InitGui.py
src/Mod/Path/Path/Main/Gui/JobDlg.py

This PR is as a result of https://github.com/FreeCAD/FreeCAD/issues/11839 which took quite a bit of explaining to the user. Whether in future the word _document_ needs to be in red is up for discussion but for now I've just added `for this document` to the message box as well as the document unit schema lookup obviously.

[Path] Move Units Schema check from system level to document level

---

src/Mod/TechDraw/Gui/QGIView.cpp

This PR implements a fix for an issue in positioning secondary views in projection groups as reported here: https://forum.freecad.org/viewtopic.php?t=83925

[TD]fix positioning of secondary views

---

src/Gui/ViewProviderGeometryObject.cpp

With PR #11586 I introduced a bug that caused the default shape color setting to be ignored.
This PR will fix that.
see also:
https://forum.freecad.org/viewtopic.php?t=83924
https://forum.freecad.org/viewtopic.php?t=83066
Code to test the old and new behavior:
```python3
import Part
doc = App.newDocument()
pg = App.ParamGet('User parameter:BaseApp/Preferences/View')
backup_default_transparency = pg.GetInt('DefaultShapeTransparency')
pg.SetInt('DefaultShapeTransparency', 70)
obj = doc.addObject('Part::Box')
assert obj.ViewObject.Transparency == 70
obj.ViewObject.ShapeColor = (0.5, 0.0, 0.0)
if obj.ViewObject.Transparency != 70:
print('WARNING: transparency was changed to',
obj.ViewObject.Transparency, 'when changing the color.')
else:
print('transparency is still ok after changing color') …
```

Gui: fix ignored default shape color

---

src/Gui/DlgPreferences.ui

This introduces optional horizontal scrollbar, looses up the minimum size applied to dialog and narrows a dialog a little bit by default.
Forum dicsussion: https://forum.freecad.org/viewtopic.php?p=724001#p724001

Gui: Allow narrower preferences dialog

---

src/Gui/NavigationStyle.cpp
src/Gui/NavigationStyle.h
src/Gui/OpenSCADNavigationStyle.cpp
src/Gui/TinkerCADNavigationStyle.cpp

This PR fixes several right click context menu issues.
The OpenSCAD navigation style did not show the context menu when right clicking. Now it does.
The TinkerCAD navigation style showed the context menu after a fast drag. Now it only shows it when right mouse is released and the view was not dragged.
This PR fixes #10624 where the context menu always popped up after a drag in the sketcher. And the same for the OpenSCAD style but then for panning.
To fix these issues I added two variables: `hasDragged` and `hasPanned`. These are used to detect if the view was actually dragged or panned when the mode is/was `DRAGGING` or `PANNING`. The TinkerCAD and OpenSCAD styles check the `hasDragged` and `hasPanned`  variable and set processed to true when the right mouse button is released.

Right click context menu fixes

---

src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h
src/Mod/Sketcher/Gui/DrawSketchHandlerRotate.h

Change the tool description of polar pattern (rotate) and polygon in the Sketcher WB to better hint users to modify with U and J key. Added line breaks to the copy constraints tooltip.
@PaddleStroke fixing https://github.com/FreeCAD/FreeCAD/pull/11264#issuecomment-1868324482
Before:
After:

Sketcher: change tool description of rotate and polygon tool

---

src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp

Provide a default axis for polar patterns in multitransformation

---

src/Gui/Workbench.cpp
src/Mod/PartDesign/Gui/Workbench.cpp

Fixes parts of #11355
Placement command is added to the context menu in the tree and view if objects are selected which can be "placed"

Add placement command to context menu

---

src/App/ObjectIdentifier.cpp
src/Mod/Part/parttests/regression_tests.py
src/Mod/Sketcher/SketcherTests/TestSketchExpression.py

Detect circular references in sketches, and add corresponding tests

---

conda/conda-env.yaml
conda/setup-environment.cmd
conda/setup-environment.sh

During the installation of the devenv, some packages are re-installed.  As this may take place in parallel with the installation of other packages, re-installation of the base packages may break the other packages due to missing core libraries resulting in a failure.
This PR correctly sets the Python to 3.11.x, preventing an unnecessary upgrade, and also sets the `--no-prune` option to `mamba-devenv`, preventing the re-installation of the core packages.

CI: Fix issues affecting conda devenv installation resulting in failures.

---

src/Mod/Arch/ArchWindowPresets.py

The Frame property controls the extrusion of the window components. It should receive the w2 instead of the h1 value.

Arch: Arch_Window: wrong value for Frame property

---

src/Mod/Arch/ArchWindow.py

Fixes a problem introduced with a previous PR of mine (#7591). Hosts would only be touched if that property of the window was modified. But the hosts of a window should also update if other properties of the window change.
Additionally a width or height change of a window now touches the hosts on the subsequent shape change.

Arch: Arch_Window fix and improve handling of hosts

---

src/Mod/Arch/ArchWall.py

See discussion on FreeCAD forum :
- https://forum.freecad.org/viewtopic.php?p=727868#p727868 ( How to use the partdesign_subshapebinder for walls / Walls on "3d sketch"? )

[ArchWall] Fix getExtrusionData() with DraftWire base problem

---

src/Gui/ActiveObjectList.cpp
src/Mod/PartDesign/Gui/CommandBody.cpp

Fixes #10371
The circular reference is caused by incomplete object path in active object (`Gui.activeView().getActiveObject('pdbody', True)`) when creating new body in an active App::Part.

Fix object path in active object when creating new body in App::Part

---

src/Mod/PartDesign/App/FeatureHole.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/11672 even though the root cause is user education, i.e. don't create two circles in the same location.

[PartDesign] Hole, ignore duplicate circle/curve centers

---

src/Mod/Import/App/dxf/ImpExpDxf.cpp
src/Mod/Import/App/dxf/ImpExpDxf.h
src/Mod/Import/App/dxf/dxf.cpp
src/Mod/Import/App/dxf/dxf.h
src/Mod/Import/Gui/dxf/ImpExpDxfGui.h
src/Mod/Path/libarea/AreaDxf.cpp
src/Mod/Path/libarea/AreaDxf.h

Eliminate m_measurement_inch to clean up logic for priority of MEASUREMENT and INSUNITS. Save the actual scaling factor rather than the scaling enum so a switch statement is not executed for each call to mm() Add to CDxfRead the work to handle dxfScaling option, ImpExpDxfRead just has to set it up now. Get the scaling factor from a lookup table rather than a switch statement Display a message explaining what the scaling factor is and where it comes from

Streamline scaling for DXF import

---

src/Base/QuantityLexer.c
src/Base/UnitsApi.cpp
src/Base/UnitsSchema.h
src/Base/UnitsSchemaImperial1.cpp
src/Base/UnitsSchemaInternal.cpp
src/Base/VectorPyImp.cpp

Currently in the string description for unit system "degree" (unit name) appears instead of "°" (symbol). In the same entries appear "mm", "kg", "s" opposed to "millimeter", "kilogram", "second". So I think could be a better fit to use the symbol for the unit instead.
As an example SOLIDWORKS uses the full name of the units instead of only the symbols.
Usually the use of "s" instead of "sec" is preferred for time unit second.
Affects strings presented to the user on the combobox to select unit system.
- The symbol to represent angles on "degree" unit is '°'
- Change imperial velocity to "ft/s" to enforce the use of 's' symbol as second
Also added colons to TODOs to get highlightning.

[Base/Units] Change strings' description

---

src/Gui/ViewProviderPart.cpp
src/Gui/ViewProviderPart.h
src/Mod/PartDesign/Gui/ViewProviderBody.cpp
src/Mod/PartDesign/Gui/ViewProviderBody.h

Change the description of the default 'Toggle active object' command in the right click menu based on the current state of the selected object.
Currently it always says "Toggle active object".
The PR would say "Active object" and displays a checkbox as icon. If the object is currently not the active object the checkbox is unchecked, otherwise the checkbox is checked.
The code previously called the double click function which was now refactored in two new functions.
Before:
After:
https://github.com/FreeCAD/FreeCAD/assets/6246609/2b237541-f1e3-4b16-9cb3-3e9cb10e0ee1

Change the description of the default 'Toggle active object' command

---

src/Mod/TechDraw/App/DrawComplexSection.cpp
src/Mod/TechDraw/Gui/QGIViewPart.cpp

This PR applies the fix for preventing failure during  restore (#11817) to v0.21.

[TD]prevent fail during document restore (backport #11817)

---

src/Gui/OpenSCADNavigationStyle.cpp

Fixes #10623.
Best I could come up with is to prohibit dragging using left mouse button when in sketch/editing mode. Dragging is still possible using middle mouse button + right mouse button. Left mouse button keeps working when not in editing mode.

Gui: Prohibit dragging using LMB in sketch mode for OpenSCAD style

---

src/Doc/CONTRIBUTORS
src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.h
src/Mod/Sketcher/Gui/Workbench.cpp

fixes #11818 
This PR introduces a *contextual* right click context menu in the Sketcher WB which shows different commands based on the selection of the user (none, one or multiple geometry elements, or constraints).
The current context menu is static and is overloaded with commands which are either greyed out or not working in Sketcher.
New:
https://github.com/FreeCAD/FreeCAD/assets/6246609/49426bf8-56a2-46f5-bd6c-cd768a9386d5
Old:

Sketcher: contextual right click context menu based on selection

---

src/Mod/Path/Path/Op/Profile.py

The calculated midpoint of a wire (coordinate at half the path length) was sometimes wrong because the edges were not sorted.
This will fix #11922.

Path: fix wire midpoint calculation

---

src/Mod/Import/App/AppImportPy.cpp
src/Mod/Import/App/CMakeLists.txt
src/Mod/Import/App/SketchExportHelper.cpp
src/Mod/Import/App/SketchExportHelper.h
src/Mod/Import/App/dxf/dxf.cpp

This PR implements a fix for issue #11224. 
Sketches are projected onto their base plane before export.  This converts the sketch geometry so it appears to be on the XY plane.

[Import]Flatten sketch before dxf export. (fix #11224)

---

src/Gui/propertyeditor/PropertyEditor.cpp
src/Gui/propertyeditor/PropertyEditor.h

Fixes https://github.com/FreeCAD/FreeCAD/issues/11794
Hide headers of property view as they are self explanatory: 
And enable resizing on all cells (as before you could resize only on headers, which was a problem if you hide headers).

Property editor: Hide header and enable resizing on all cells.

---

src/Mod/Draft/draftmake/make_array.py
src/Mod/Draft/draftmake/make_clone.py
src/Mod/Draft/draftmake/make_patharray.py
src/Mod/Draft/draftmake/make_pointarray.py

The function would trigger the creation of duplicate Draft Polar Arrays (only on Linux and only if the Fuse option is selected and the Link Array option deselected).
Forum topic:
https://forum.freecad.org/viewtopic.php?t=84090
The reapply_diffuse_color function is no longer required anyway as Issue #8340 has been fixed.

Draft: remove reapply_diffuse_color workaround

---

tests/src/App/StringHasher.cpp

The PyObject desctructor requires an initialized interpreter, otherwise PyGILState_Ensure crashes.
Fixes #11878

[App] Fix segfault due to missing Py_Initialize in StringIDRefTest

---

src/Mod/Draft/Resources/ui/preferences-dxf.ui

This option control DXF export but was confusingly in the Import options area. Fixes #11659

Move the "Treat ellipses...as polylines" to DXF *output* options group

---

src/Base/Vector3D.cpp
src/Base/Vector3D.h
src/Base/VectorPy.xml
src/Base/VectorPyImp.cpp

Extend Python class App.Vector by a boolean function `isParallel`.
Usage: 
```python
vec1 = App.Vector(...)
vec2 = App.Vector(...)
tol = 0.01
if vec1.isParallel(vec2,tol):
....
```
Returns True if the two vectors are parallel, otherwise returns False.

[base] Extend Python class App.Vector by isParallel function

---

src/Gui/DlgPreferencesImp.cpp
src/Gui/DlgPreferencesImp.h

As every page is contained in the same QScrollArea we must ensure that after page is changed the scrolled area is scrolled back to top-left corner.
Fixes: #11981

Gui: Reset scroll position after preference page change

---

src/Mod/Part/App/TopoShape.cpp
src/Mod/Part/App/TopoShape.h

- currently in working state
- replaces manual re-definition of every method with inheritance (not recommended by RT in case OCC updates TopoDS_Shape, but we deemed it rare enough)
- would be nice to somehow template the the wrapper functions, but I gave up on that
- Something needs to be done with the move/moved/locate/located situation, it's a spaghetti bolognese

Toponaming shapeprotector

---

src/App/ComplexGeoData.cpp
src/App/ComplexGeoData.h
src/Mod/Part/App/TopoShape.h
src/Mod/Part/App/TopoShapeExpansion.cpp
tests/src/Mod/Part/App/CMakeLists.txt
tests/src/Mod/Part/App/TopoShapeExpansion.cpp

This implements the method originally called `makECompound` (and now called `makeElementCompound`) as well as all auxiliary methods required by it. This is the first of the toponaming-aware object creation methods being added to the TopoShape class.
There is some follow-on work to be done refactoring the `mapSubElement`, which has very high complexity and requires some additional tests before it can be refactored safely.

Toponaming: makeElementCompound

---

src/Mod/Fem/Gui/ViewProviderAnalysis.cpp
src/Mod/Fem/Gui/ViewProviderAnalysis.h
src/Mod/Fem/Gui/ViewProviderFemPostPipeline.cpp
src/Mod/Fem/Gui/ViewProviderFemPostPipeline.h

If a pipeline is selected, its `SoNode` is added to the Analysis object node.
With these changes the pipeline node is removed when the pipeline is deleted.

Fem: Remove pipeline node from analysis view provider - fixes #11175

---

src/Gui/DlgPreferencesImp.cpp
src/Gui/PreferencePages/DlgSettings3DViewImp.cpp
src/Gui/PreferencePages/DlgSettings3DViewImp.h
src/Gui/PreferencePages/DlgSettingsCacheDirectory.cpp
src/Gui/PreferencePages/DlgSettingsCacheDirectory.h
src/Gui/PreferencePages/DlgSettingsEditor.cpp
src/Gui/PreferencePages/DlgSettingsEditor.h
src/Gui/PreferencePages/DlgSettingsGeneral.cpp
src/Gui/PreferencePages/DlgSettingsGeneral.h
src/Gui/PreferencePages/DlgSettingsMacroImp.cpp
src/Gui/PreferencePages/DlgSettingsMacroImp.h
src/Gui/PreferencePages/DlgSettingsNavigation.cpp
src/Gui/PreferencePages/DlgSettingsNavigation.h
src/Gui/PreferencePages/DlgSettingsWorkbenchesImp.cpp
src/Gui/PreferencePages/DlgSettingsWorkbenchesImp.h

Continues the modifications for #10161
This PR adds the management of the parameters set using Preference Pages Widgets that aren't derived from `PrefWidgets` objects and therefore ignored by the `PreferencePage::resetSettingsToDefaults` method
The Preference Pages subject to this PR are only the ones within the directory `src/Gui/PreferencePages`, no modifications have been made to the Preference Pages of the various Workbenches

[Feature Request] [Core] [Preferences] Reset preference pages parameters set without using "PrefWidgets" objects

---

src/Mod/Fem/App/FemConstraint.cpp
src/Mod/Fem/App/PreCompiled.h

With some trimmed surfaces, it may happen that the points selected based on the iso-curves used to place the constraint arrows do not coincide with the interior of the surface.
In that case, with this commit, the arrows are placed on the outer wire.
See  #6073.

Fem: Fix constraint arrows - fixes #6073

---

src/App/PreCompiled.h
src/Mod/Mesh/Gui/PreCompiled.h
src/Mod/Part/Gui/PreCompiled.h

This PR adds some missing includes when attempting to build with `-DFREECAD_USE_PCH=ON`.
Each commit is split by module. The most notable one is moving inclusion of QtAll after glext, so that we can set GL_GLEXT_PROTOTYPES before it's too late.

Fix build with precompiled headers

---

src/Mod/Draft/DraftGui.py

In a previous PR of mine I have reorganized some lines of code in DraftGui.py without realizing that this would reposition checkboxes. This PR fixes that.

Draft: Task panel checkboxes were repositioned by accident

---

src/Mod/Material/App/MaterialLoader.cpp
src/Mod/Material/App/MaterialValue.cpp
src/Mod/Material/App/ModelLibrary.cpp

QRegExp has been replaced with QRegularExpression and isn't part of the base of Qt6 any more

Material: fix Qt6 build failure

---

src/Mod/Path/App/Area.cpp
src/Mod/Path/App/Area.h
src/Mod/Path/App/AreaPy.xml
src/Mod/Path/App/AreaPyImp.cpp
src/Mod/Path/Path/Op/Area.py
src/Mod/Path/Path/Op/PocketBase.py
src/Mod/Path/libarea/AreaClipper.cpp

[Forum post](https://forum.freecad.org/viewtopic.php?t=78773&sid=5fa0a750380e7bd8c78aa626592c5bb5&start=30)
This PR is my next iteration of rest machining for FreeCAD. It discards the old approach of using internals of the Area class to determine previously cleared regions, and instead computes those regions by processing the gcode from earlier operations. This is trickier, but comes with the advantage of being more flexible: in this version of the rest machining feature, any operation (most notably Adaptive operations) can be the source tool path for rest machining.
Even with the improvements from this iteration, only Area operations (Pocket, Pocket3D, Profile) can take advantage of rest machining. I hope to implement rest machining for Adaptive tool paths in my next pass improving this …

[Path] Rest machining from gcode

---

src/Mod/Draft/DraftGui.py

Since V0.19 self.facecolor had two types: integer (initial value) or QColor. With this PR it is again always a QColor.

Draft: DraftGui.py make type of self.facecolor consistent

---

src/Mod/Fem/femexamples/constraint_selfweight_cantilever.py
src/Mod/Fem/femobjects/constraint_selfweight.py
src/Mod/Fem/femsolver/calculix/write_constraint_selfweight.py
src/Mod/Fem/femsolver/elmer/equations/deformation_writer.py
src/Mod/Fem/femsolver/elmer/equations/elasticity_writer.py
src/Mod/Fem/femtest/data/calculix/constraint_selfweight_cantilever.inp

The self-weight constraint now supports modifying the gravity value.
A `PropertyAcceleration` and a `PropertyVector`  are used to control the gravity module and (normalized) direction.   
Previous `PropertyFloat` used to represent the gravity direction are removed.
Now, both CalculiX and Elmer solvers can use customized gravity values.

Fem: Improve self weight constraint - fixes #11652

---

src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h
src/Mod/Sketcher/Gui/DrawSketchHandlerBSplineByInterpolation.h

Gives a better idea of the shape of the B-spline than just control polygon.
This PR is being supported through an FPA grant.

[Sketcher] Draw B-spline when creating in edit mode

---

src/Mod/Fem/App/FemConstraintDisplacement.cpp
src/Mod/Fem/App/FemConstraintForce.cpp
src/Mod/Fem/App/FemConstraintInitialTemperature.cpp
src/Mod/Fem/App/FemConstraintPressure.cpp
src/Mod/Fem/App/FemConstraintTemperature.cpp
src/Mod/Fem/App/FemConstraintTransform.cpp
src/Mod/Fem/App/FemPostFilter.cpp

Functions to handle property changes should also call the corresponding function of the base class.

Fem: Call base class handleChangedProperyType function

---

src/Mod/TechDraw/Gui/CommandExtensionPack.cpp

This PR implements a fix for an issue reported here: https://forum.freecad.org/viewtopic.php?t=84497.
The issue involves the location of cosmetic features on rotated views.

[TD]handle View rotation in ExtensionPack circle centerlines

---

src/Mod/Material/App/MaterialConfigLoader.cpp
src/Mod/Material/App/MaterialLibrary.cpp
src/Mod/Material/App/Materials.cpp
src/Mod/Material/App/Model.cpp
src/Mod/Material/App/ModelLibrary.cpp
src/Mod/Material/App/ModelLoader.cpp
src/Mod/Material/App/PreCompiled.h
src/Mod/Material/Gui/Array2D.cpp
src/Mod/Material/Gui/Array3D.cpp
src/Mod/Material/Gui/ArrayDelegate.cpp
src/Mod/Material/Gui/ArrayModel.cpp
src/Mod/Material/Gui/BaseDelegate.cpp
src/Mod/Material/Gui/ImageEdit.cpp
src/Mod/Material/Gui/ListDelegate.cpp
src/Mod/Material/Gui/ListEdit.cpp
src/Mod/Material/Gui/ListModel.cpp
src/Mod/Material/Gui/MaterialDelegate.cpp
src/Mod/Material/Gui/MaterialsEditor.cpp
src/Mod/Material/Gui/PreCompiled.h
src/Mod/Material/Gui/TextEdit.cpp

PreCompiled.h had fallen out-of-date, and some files that it included were being re-included later outside the checks.

[Materials] Correct PreCompiled.h inclusions

---

src/Mod/PartDesign/App/FeatureLinearPattern.cpp
src/Mod/PartDesign/WizardShaft/WizardShaft.py

I tested on my local machine at worked fine. There is something more I should care?
For example the `pre-coomit` hook didn't change the length of the line, 145 char width.
```pre-commit
clang-format.........................................(no files to check)Skipped
```
Fix https://github.com/FreeCAD/FreeCAD/issues/12068

PartDesign: Update Length/Offset when Occurrences changes 

---

src/Mod/Material/App/AppMaterial.cpp
src/Mod/Material/App/MaterialLibrary.cpp
src/Mod/Material/App/ModelLibrary.cpp

`Materials` types that inherit from `Base::BaseClass` were not initialized properly.
Not initializing types leads to a lot of crashes and undefined behavior (especially from Python's Material module, which until now was basically unusable) and results in material cards being inaccessible from some workbenches like FEM.

Material: Initialize types

---

src/App/DocumentObject.cpp
src/App/DocumentObject.h
src/App/Link.cpp
src/Gui/ViewProviderLink.cpp

I am splitting the PR https://github.com/FreeCAD/FreeCAD/pull/11053 into a sequence of simpler PRs. This is the second in this sequence. The first one is: https://github.com/FreeCAD/FreeCAD/pull/11139.
Basically, the `DocumentObject::getNameInDocument()` method has three different uses:
1. Obtains the name of this object within the `Document`. (legitimate use)
2. Indicates if the object is attached to a Document. Returns `nullptr` in case not. See: https://github.com/FreeCAD/FreeCAD/pull/11139.
3. Provides a "DAG key" to refer to this object. (this patch)
This PR creates the method `getDagKey()` that shall be used in the context of item 3, instead of relaying on `getNameInDocument()`.
The main idea is to, in the near future, change `getNameInDocument()` and make it never return an invalid …

Does not rely on the pointervalue returned by getNameInDocument() to use as a DAG key.

---

src/Mod/Sketcher/App/PythonConverter.cpp
src/Mod/Sketcher/App/PythonConverter.h
src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
src/Mod/Sketcher/Gui/ShortcutListener.cpp
src/Mod/Sketcher/Gui/ShortcutListener.h
src/Mod/Sketcher/Gui/ViewProviderSketch.h
src/Mod/Sketcher/Gui/Workbench.cpp

Add support to copy/paste geometries in sketcher using ctrl-X/C and ctrl-V
Geometries (and relevent constraints) are copied to computer clipboard as python command text. Enabling exporting and paste in other Freecad instances or even share on forum.
Video description : https://forum.freecadweb.org/viewtopic.php?f=9&t=65892
This is a rework of https://github.com/FreeCAD/FreeCAD/pull/5480
So it appeared that creating commands in sketcher with the same shortcuts override CommandDoc general commands. Which solves the initial problem.

[Sketcher] Add copy/cut/paste sketcher commands

---

src/Gui/propertyeditor/PropertyEditor.h

This is a virtual method that is being overridden, but it was missing the `override` keyword.

Gui: Add missing override

---

src/Mod/Draft/Draft.py
src/Mod/Draft/draftguitools/gui_layers.py
src/Mod/Draft/draftmake/make_layer.py
src/Mod/Draft/drafttests/draft_test_objects.py
src/Mod/Draft/draftviewproviders/view_layer.py

The current make_layer function has a `None` default for the shape color and the line color. With that value the current preference is used. This, and how the function is called, results in some confusing behaviors:
* Newly created layers will only use 2 values from the preferences when they might use 5. The latter makes more sense for the end-user IMO.
* Layers created during DXF import (for example) will have a different shape color depending on the current preferences.
* The make_layer function may reapply colors that have already been set by the view provider.
To solve this all view property related function parameter have been changed to a not None value. If a None value is supplied the view property as set by the view provider is not changed. The Layer Manager has been updated …

Draft: Improve layer functions

---

src/Mod/Draft/drafttaskpanels/task_shapestring.py

Related issue #12058.
Fixes the "\n" issue when creating the ShapeString. I can't reproduce the other problems.

Draft: ShapeString double escape backslash in string

---

src/Mod/Import/App/dxf/dxf.h

This PR implements a fix for warning messages in dxf.cpp.    
These warnings appear to have been introduced  by commit 2c0bc89f62.  The warnings appear on linux/gcc.  It appears MS compiler (and possibly clang) allow this construct.
The construct "using eDXFGroupCode_t = enum {" causes a number of warning messages of the form: 
/home/wile/Source/FreeCAD/src/Mod/Import/App/dxf/dxf.h:429: warning: ‘CDxfRead’ has a field ‘CDxfRead::m_record_type’ whose type has no linkage [-Wsubobject-linkage]
In file included from /home/wile/Source/FreeCAD/src/Mod/Import/App/dxf/ImpExpDxf.h:32,
from /home/wile/Source/FreeCAD/src/Mod/Import/App/AppImportPy.cpp:53:
/home/wile/Source/FreeCAD/src/Mod/Import/App/dxf/dxf.h:429:20: warning: ‘CDxfRead’ has a field ‘CDxfRead::m_record_type’ whose type has no linkage …

[Import]fix linkage warning on linux/gcc

---

src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_BSplineApproximate.svg
src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_BSplineInsertKnot.svg
src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_JoinCurves.svg
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Add B-Spline commands in the contextual right click menu in the Sketcher WB, depending of the selection of
- B-Splines
- Knots
- BSpline + Points
+fine tuned icons for better identification.

[Sketcher] Add contextual BSpline commands in right click menu

---

src/Mod/Part/App/TopoShapeMapper.cpp

Part/TopoShapeMapper: Add missing PreCompiled include

---

src/Mod/TechDraw/App/Cosmetic.cpp
src/Mod/TechDraw/Gui/Widgets/CompassWidget.cpp

This PR implements 2 fixes for issues reported here: https://forum.freecad.org/viewtopic.php?t=84557 and here: https://forum.freecad.org/viewtopic.php?p=734873#p734873
The first is a situation where cosmetic edges do no remember their format.  The second is a case where a change in a widget is not propagated correctly.

[TD]Small Section and Cosmetic Edge Fixes

---

src/Gui/Stylesheets/images_dark-light/check_dark_disabled.svg
src/Gui/Stylesheets/images_dark-light/check_light_disabled.svg
src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
src/Mod/Sketcher/Gui/TaskSketcherElements.h

This ensures that checkboxes drawn in the Elements UI of the sketcher can be styled using the correct style.
Three changes are introduced:
1. paint() method uses style provided by the widget, not application.
2. Indicator is drawn using `PE_IndicatorCheckBox` not `CE_CheckBox` - it allows to use `::indicator` in qss to style it properly. This works the same as TreeView.
3. Fix for minor issues with text alignment and extension of selected items background to cover checkbox. This is how other controls of this kind work.
It also completely refactors the rendering delegate introducing dedicated method for calculating rects of each element and method for rendering each sub control. Thanks to this refactor we can be sure that areas drawn are the same as areas checked for events in …

Sketcher: Apply styling to elements and constraints UI

---

src/Gui/ViewProviderOriginFeature.cpp
src/Mod/Fem/Gui/ViewProviderFemMesh.cpp
src/Mod/Import/Gui/dxf/ImpExpDxfGui.cpp
src/Mod/Part/CMakeLists.txt
src/Mod/Part/Gui/DlgProjectionOnSurface.cpp
src/Mod/Part/TestPartGui.py
src/Mod/Part/parttests/ColorTransparencyTest.py

As described in the [forum](https://forum.freecad.org/viewtopic.php?p=734688#p734688), the transparency value of an App::Plane object is set to the default transparency instead of zero after creation.
During creation, the App::Plane object is assigned the specified default shape color and then the color is set (again) to a fixed color for the plane (light-blue). But the transparency was not set to a fixed value and therefore kept the default transparency value.
This PR also adds the missing transparency specification to some other objects.
To test the changes, the following Python code can be executed:
```python3
doc = App.newDocument()
pg = App.ParamGet('User parameter:BaseApp/Preferences/View')
backup_default_transparency = pg.GetInt('DefaultShapeTransparency') …
```

Gui: add explicit transparency specification

---

src/Mod/AddonManager/CMakeLists.txt
src/Mod/AddonManager/addonmanager_readme_viewer.py
src/Mod/AddonManager/package_details.py

GitHub recently broke the rendering of the README, so I am taking this opportunity to streamline the Addon Manager a bit and remove our dependency on QtWebEngine (Chromium). For Addon README.md display it uses Qt's native Markdown rendering when possible. For macros right now it is just dumping the HTML into the QTextBrowser, which does not do a very nice job of rendering it. In a follow-up PR I will strip out the top portion of the wiki page to clean things up.
Note that one consequence of this change is that images will render at a significantly lower quality than they did in the full-blown Chromium browser. Qt's QTextBrowser does not display images very well.

Addon manager: remove QtWebEngine

---

src/App/Application.cpp
src/App/PropertyUnits.cpp
src/App/PropertyUnits.h
src/Base/Unit.cpp
src/Base/Unit.h
src/Base/UnitsSchemaInternal.cpp
src/Base/UnitsSchemaMKS.cpp
src/Mod/Fem/App/FemConstraintContact.cpp
src/Mod/Fem/App/FemConstraintContact.h
src/Mod/Fem/Gui/Command.cpp
src/Mod/Fem/Gui/Resources/ui/ConstraintTie.ui
src/Mod/Fem/Gui/TaskFemConstraintContact.cpp
src/Mod/Fem/Gui/TaskFemConstraintContact.h
src/Mod/Fem/Gui/TaskFemConstraintContact.ui
src/Mod/Fem/femexamples/constraint_contact_shell_shell.py
src/Mod/Fem/femexamples/constraint_contact_solid_solid.py
src/Mod/Fem/femobjects/constraint_tie.py
src/Mod/Fem/femsolver/calculix/write_constraint_contact.py
src/Mod/Fem/femsolver/calculix/write_constraint_tie.py
src/Mod/Fem/femtaskpanels/task_constraint_tie.py
src/Mod/Fem/femtest/data/calculix/constraint_contact_shell_shell.inp
src/Mod/Fem/femtest/data/calculix/constraint_contact_solid_solid.inp
src/Mod/Fem/femtest/data/calculix/constraint_tie.inp

* Add new unit `StiffnessDensity` ($\text{Force/Lenght}^3 \equiv \text{Pressure/Lenght}$)  and the corresponding `App::PropertyStiffnessDensity`, basically a spring stiffness per unit area needed to use in contact stiffness and the stick slope value used by the `*FRICTION` keyword. (currrently it is said that the unit should be Pressure like the elastic modulus, but this is incorrect).
* Add support for `ADJUST` parameter on the `CONTACT PAIR` card  for contact constraint.
* Add support for specifying stick slope value in `*FRICTION` keyword.
* Add support for `ADJUST` parameter in tie constraint.
* Use quantity spin box in both constraint task dialogs.
@FEA-eng Do you want to test this?
Some links:
http://www.dhondt.de/ccx_2.21.pdf#subsubsection.6.7.5 …

Fem: Improve contact and tie constraints - fixes #11653

---

src/Mod/Arch/ArchBuildingPart.py

The Transform option from the Tree view context menu did not work.

Arch: BuildingPart fix setEdit and unsetEdit

---

src/Mod/Material/App/MaterialManagerPyImpl.cpp
src/Mod/Material/App/MaterialPyImpl.cpp

`Py_False` or `Py_True` should not be used directly on function return without increasing the reference count

Material: Return new reference to Python boolean and change format unit to parse path

---

conda/environment.devenv.yml

An update to the `conda-forge` package `pcl` from version `1.13.1` to `1.14.0` resulted in build failures only present on Windows.  Pinning the package to `1.13.1` resolves the build issues.

Conda: Pin PCL to v1.13.1 to fix build errors on Windows.

---

src/Mod/AddonManager/Addon.py
src/Mod/AddonManager/addonmanager_git.py
src/Mod/AddonManager/addonmanager_installer.py
src/Mod/AddonManager/addonmanager_metadata.py
src/Mod/AddonManager/addonmanager_workers_startup.py
src/Mod/AddonManager/manage_python_dependencies.py
src/Mod/AddonManager/package_details.py
src/Mod/AddonManager/package_list.py

Support changing the name of the primary branch. To change your primary branch:
1) Make the change in your primary remote repo
2) Update your package.xml file to list the new repo branch
3) Update .gitmodules file in FreeCAD/FreeCAD-Addons repo
The Addon Manager will recognize this as an available update and automatically switch your installed branch name (if your addon was installed using git -- if it was installed via ZIP this just pulls a new copy of the zip file).
Fixes #12130.

Addon Manager: Allow primary branch name change

---

src/Gui/CommandFeat.cpp

Create a transaction in the currently selected document to allow the user to roll-back the color assignment.
Closes #11689

Make the random color assignment undo-able

---

src/Mod/Sketcher/Gui/SketcherSettings.ui
src/Mod/Sketcher/Gui/SketcherSettingsAppearance.ui

* Titles in sentence case.
* No space before colon.
* Choose instead of chose.
* Vertex item first in "Colors outside Sketcher" as well.

Sketcher: minor fixes to 2 prefs ui files

---

src/Mod/Arch/ArchCommands.py
src/Mod/Arch/ArchWindow.py
src/Mod/Arch/Resources/ui/preferences-arch.ui
src/Mod/Arch/Resources/ui/preferences-archdefaults.ui

Follow-up PR of #11940.
* The new ui layout follows that of the Draft preferences.
* The ConversionFast checkbox enables/disables the 3  preferences listed below it.
* The WindowColor preference was removed. It is not a per-object, or even a per-file setting. The fix in #11940 would change windows in existing projects when they are recomputed. It is therefore better to keep the V0.21 solution where the glass is colored according to the preferences and the rest of the window receives a color based on its ShapeColor. Users who want to apply specific colors can use a multi-material.

Arch: Revised preference ui files, remove WindowColor

---

src/Mod/Arch/ArchSectionPlane.py

* Restores Arch_Axis bubbles in a TechDraw_ArchView. This fixes a regression in V0.21 and 0.22, I suspect an unwanted side-effect of a previous PR of mine (#8688).
* Also fixes the linetype of axes and other annotation objects in a TechDraw_ArchView.

Arch: Bring back Axis bubbles and show annotation DrawStyle in ArchView

---

src/Mod/Part/App/OpenCascadeAll.h

Fix master not compiling with precompiled. https://forum.freecad.org/viewtopic.php?t=84835
@chennes

Part: Add BRepFill_Generator to the OpenCascadeAll.h

---

src/Mod/Part/App/TopoShape.cpp
src/Mod/Part/App/TopoShape.h

related to comment in https://github.com/FreeCAD/FreeCAD/commit/a74c6b339160c48b26b8bc191138a583a6a2aee4#comments of https://github.com/FreeCAD/FreeCAD/pull/11896
This PR adds a check on objects of class `ShapeProtector` before performing `Nullify()`
as reported in https://forum.freecad.org/viewtopic.php?t=84536 the lack of this check causes a segfault when the `Nullify()` method is called

Toponaming shapeprotector Nullify() check

---

src/Mod/Sketcher/Gui/DrawSketchController.h

Asynchronous events on MacOS seemed to trigger a change after the handler's deletion.

Sketcher: Add check for handler's existence

---

src/Mod/Draft/draftguitools/gui_edit.py
src/Mod/Draft/draftguitools/gui_groups.py
src/Mod/Draft/draftguitools/gui_trackers.py
src/Mod/Draft/draftmake/make_point.py
src/Mod/Draft/draftutils/gui_utils.py

The draftToolBar.getDefaultColor() function is an indirect way of retreiving a parameter. It is better to avoid it where possible.

Draft: Avoid draftToolBar.getDefaultColor outside DraftGui.py

---

src/Mod/Draft/draftguitools/gui_lines.py

The Draft_Wire command can combine selected Draft_Wires and Draft_Lines into a single wire. This function did not always behave properly.
* Edges were not sorted, the result could have a different shape (with the correct vertexes).
* If edges formed  a closed shape the resultant wire was not closed.

Draft: Fix Draft_Wire conversion function

---

src/App/PropertyPythonObject.cpp

Related #10460
Amendment to 83d4080f.
Check for attribute `__func__` for Python >= 3.11 to avoid calling built-in `__getstate__/__setstate__`.

App: fix PropertyPythonObject persistence backward compatibility

---

src/Mod/Draft/draftmake/make_circulararray.py
src/Mod/Draft/draftmake/make_dimension.py
src/Mod/Draft/draftmake/make_label.py
src/Mod/Draft/draftmake/make_orthoarray.py
src/Mod/Draft/draftmake/make_patharray.py
src/Mod/Draft/draftmake/make_pointarray.py
src/Mod/Draft/draftmake/make_polararray.py

Some error messages would only work if objects were supplied as strings. These would fail if objects were passed (as objects) that had already been deleted.

Draft: Fix messages that only worked for objects supplied as strings

---

src/Mod/Fem/App/HypothesisPy.cpp

a) `#include <SMESH_Version.h>` needs to be unconditional. Otherwise the defines are not visible. 
b) move an #endif one line lower.

Fix MEFISTO removal

---

src/Mod/Part/App/FeaturePartBoolean.cpp
src/Mod/Part/App/FeaturePartCommon.cpp
tests/src/Mod/Part/App/FeaturePartBoolean.cpp
tests/src/Mod/Part/App/FeaturePartCommon.cpp

No tests because they go on the subclasses ( FeaturePartFuse, FeaturePartCut, FeaturePartCommon, FeaturePartSection ).
The non-existent tests are already committed.  Subclasses coming up next.
` _boolean = dynamic_cast<Part::Boolean*>(_doc->addObject("Part::Boolean"));  
`
Doesn't create a useful object, and the UI always just creates the subclass appropriate to the operation you chose.

Toponaming: transfer in FeaturePartBoolean

---

src/Mod/Fem/femobjects/base_fempythonobject.py
src/Mod/Fem/femobjects/constraint_tie.py
src/Mod/Fem/femsolver/calculix/write_constraint_tie.py

Add support for cyclic symmetry.
This also fixes the loading of the old Tie constraint object prior to #12133 since in that commit the existence check for the `Adjust` property was not added when restoring the object (currently old files are loaded without adding this property).
Normally I would have generated two pull requests, one for the correction and another to add the cyclic symmetry, but since some helper functions are added for use in creating properties and restoring the `DocumentObject`, I decided to put it together in a single commit.
The idea of the helper functions is to avoid code duplication and string comparison that usually occurs in `onDocumentRestored` when modifications are made to the properties.
The location of the axis of symmetry is obtained by applying the …

Fem: Fix restoring old Tie constraint and add support for cyclic symmetry - fixes #12155

---

src/Mod/AddonManager/addonmanager_connection_checker.py
src/Mod/AddonManager/addonmanager_workers_utility.py

Two changes here, to fix #11120 --
1) Refactor the signal connection and disconnection from the connection check screen to ensure a second launch of the addon manager still has the correct signals connected.
2) Switch to using a non-blocking QNetworkManager connection so that the connection check is more nearly identical to the normal way the Addon Manager accesses data from the internet.

Addon Manager: Fix signals in connection check

---

src/Mod/AddonManager/addonmanager_workers_utility.py

The connection check code incorrectly handled the case of multiple incoming connections, interpreting them all as connection check signals. This is the first of two connection code fixes incoming.

Addon Manager: Correct connection check (Part 1)

---

src/Mod/AddonManager/addonmanager_workers_utility.py

Depending on the version of Qt, QByteArray doesn't always get automatically treated as bytes in Python.

Addon Manager: Correct usage of QByteArray

---

src/Mod/Draft/draftguitools/gui_edit.py

The relative checkbox was hidden by mistake.

Draft: Draft_Edit: restore Relative checkbox

---

src/Mod/TechDraw/App/DrawView.cpp
src/Mod/TechDraw/App/DrawView.h
src/Mod/TechDraw/App/DrawViewSymbol.cpp
src/Mod/TechDraw/App/DrawViewSymbol.h
src/Mod/TechDraw/App/Geometry.cpp
src/Mod/TechDraw/App/Geometry.h
src/Mod/TechDraw/Gui/CommandAnnotate.cpp
src/Mod/TechDraw/Gui/QGIView.cpp
src/Mod/TechDraw/Gui/QGIView.h
src/Mod/TechDraw/Gui/QGSPage.cpp
src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.cpp
src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.h
src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp
src/Mod/TechDraw/Gui/ViewProviderDrawingView.h
src/Mod/TechDraw/Gui/ViewProviderLeader.cpp
src/Mod/TechDraw/Gui/ViewProviderPage.cpp
src/Mod/TechDraw/Gui/ViewProviderSymbol.cpp
src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp

This pull request aims to implement issue #11684 by adding "Owner" property to all Symbols (i.e. not only Surface Finish symbols). This new property specifies the drawing view to which the Symbol is attached so once the owner view is moved, the attached symbol is moved as well. The Owner property can be freely changed to another view or left completely blank, in which case the "owner" becomes the whole page.
The Surface Finish Symbol can be now attached  to any Part View, Leader Line or (if nothing is selected) to a page. There is also a small improvement in case a Part View subitem is seleted. In this case the Surface Finish Symbol is placed in the center of given subitem. 
The pull request contains some generic code infrastructure for implementing the parent/owner switching for other …

[TechDraw] Add Owner property to Symbols

---

src/Mod/Arch/importIFC.py

Objects in `sharedobjects` were not recomputed during the import process. They had a null shape preventing the correct calculation of clone placements.
Forum topic:
https://forum.freecad.org/viewtopic.php?p=738864#p739039

Arch: importIFC fix clone placement

---

src/Mod/Part/App/TopoShapeExpansion.cpp
src/Mod/Part/App/TopoShapeMapper.cpp

Main does not build following #12237
Please be careful about precompiled includes @chennes @bgbsww

Fix compilation failures in TopoShapeExpansion and TopoShapeMapper.

---

src/Gui/DlgMacroExecute.ui

Fix warning about already existing `QLabel` with name "label"

Fix warning in DlgMacroExecute.ui

---

src/Gui/BlenderNavigationStyle.cpp
src/Gui/CADNavigationStyle.cpp
src/Gui/InventorNavigationStyle.cpp
src/Gui/MayaGestureNavigationStyle.cpp
src/Gui/NavigationStyle.cpp
src/Gui/NavigationStyle.h
src/Gui/OpenCascadeNavigationStyle.cpp
src/Gui/OpenSCADNavigationStyle.cpp
src/Gui/RevitNavigationStyle.cpp
src/Gui/TinkerCADNavigationStyle.cpp
src/Gui/TouchpadNavigationStyle.cpp

Fixes #12030.
This PR consists of 3 types of fixes. The first commit makes sure the right click context menu won't be shown after dragging, panning or zooming. The second commit prevents starting the sketcher rubber-band selection while another navigation button is pressed. The third commit prohibits switching to another mode while the rubber-band selection is active.

Gui: Mouse navigation fixes

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.h

This PR improves the contextual right click menu in the Sketcher WB.
1. Consider preselection: You can now directly right click on an element and pull up the contextual menu for the element you've clicked on. This also works if you already have a selection, then it considers the item you've right clicked on for the contextual commands. For example select a circle and then follow with a right click on a line will pull up the menu with dimension (distance) and tangent. Previously it would only considered the selected elements, so you would need one extra left click. This is also the behavior in other (CAD) software tools. 
2. Add functionality to also consider external geometry.
3. Remove commands which (currently) cannot work with a selection (e.g. fillet, trim). They would need to clear …

Improvements to Sketcher context menu

---

src/Gui/NaviCube.cpp
src/Gui/NaviCube.h
src/Gui/PreferencePackTemplates/View.cfg
src/Gui/PreferencePages/DlgSettingsNavigation.cpp
src/Gui/PreferencePages/DlgSettingsNavigation.ui
src/Gui/View3DSettings.cpp

Implement the InactiveOpacity option, allowing the user to dim the navigation cube when not focused by making it transparent.
This feature is present in many CAD softwares and IMO is quite useful to make the cube slightly less noticeable when working on the model.

Dim the Navigation Cube when not active

---

src/Mod/PartDesign/Gui/ViewProviderDatumCS.cpp

This is a small harmless visual improvement of the LCS representation in the 3D window: it leaves a small empty gap at the origin of the LCS which allows to select the point/vertex on which the LCS is attached. The lines are thicker and the blue one (Z) is darker. There is no real problem involved, it's purely cosmetic
New visual:
Previous visual:

Improve visual of LCS in 3D window (ViewProviderDatumCS.cpp)

---

src/Mod/Fem/Gui/ViewProviderAnalysis.cpp
src/Mod/Fem/Gui/ViewProviderAnalysis.h

Calling `doubleClicked` method implies an attempt to add the currently partially attached object to the list of selected objects, which generates the reported bug.
The activation of the analysis object is already done by executing the `FEM_Analysis` command.

 Fem: Prevent selection of partially attached object - fixes #12163

---

src/Gui/PreferencePages/DlgSettingsUI.cpp
src/Gui/PreferencePages/DlgSettingsUI.h
src/Gui/PreferencePages/DlgSettingsUI.py

Remove the selection checkbox preference from Display->UI. The same preference exists under General->Selection.
When changing the preference and then applying the settings, it reverts back to the value under General->Selection and thus is not usable.

Resolve #12248: Remove redundant and non-functional selection checkbox preference

---

src/Gui/ViewProviderImagePlane.cpp

When copying&pasting an ImagePlane whose ImageFile property is a PropertyFile we'd get two updateData notifications, one when the property value is restored (which doesn't do much as the file doesn't exist yet) and another when the RestoreDocFile method is invoked.
The solution is simple, do not set Xsize and Ysize when importing the object as we expect the properties to already have the correct values.
Closes #11036

Avoid overriding ImagePlane size during import

---

src/Gui/PropertyView.cpp

This allows it to easily find the widgets with Qt's findChild() method

Gui: Give property editors an object name

---

src/Mod/Part/Gui/DlgProjectionOnSurface.cpp
src/Mod/Part/Gui/DlgProjectionOnSurface.h

When the height is zero no solid is produced, the code was thus showing the result of the previously selected projection height.
Closes #12113

Clear projected shape when changing extrude height

---

src/Mod/AddonManager/AddonManagerTest/app/test_utilities.py
src/Mod/Path/PathTests/TestCentroidPost.py
src/Mod/Path/PathTests/TestGrblPost.py
src/Mod/Path/PathTests/TestLinuxCNCPost.py
src/Mod/Path/PathTests/TestMach3Mach4Post.py
src/Mod/Path/PathTests/TestRefactoredCentroidPost.py
src/Mod/Path/PathTests/TestRefactoredGrblPost.py
src/Mod/Path/PathTests/TestRefactoredLinuxCNCPost.py
src/Mod/Path/PathTests/TestRefactoredMach3Mach4Post.py
src/Mod/Path/PathTests/TestRefactoredTestPost.py
src/Mod/Path/PathTests/TestRefactoredTestPostGCodes.py
src/Mod/Path/PathTests/TestRefactoredTestPostMCodes.py

Never really noticed this until a CLion switch had me building in a subdirectory of the source tree, instead of one adjacent to it.  Suddenly I was seeing a gcode.txt and AM_INSTALLATION_DIGEST.txt show up pretty much ever time I went to commit, because I run the tests as part of my workflow.
This fixes this; the Path is a cleanly removing generating a test file that was never actually used - the contents are tested separately.  The AddonManager part is a bit more failsafe / heavy handed as I didn't find a clear place to address the generation of the file.

Stop tests from leaving files around after execution

---

cMake/FreeCAD_Helpers/CompilerChecksAndSetups.cmake

CMAKE_CXX_COMPILER_VERSION are always greater than  3.9

Clean CompilerChecksAndSetups.cmake

---

src/Base/Quantity.cpp
tests/src/Base/Quantity.cpp

fix #12204 and fix #12206
All uses I found of this function where to construct python commands

Base: escape quotes in Quantity::getSafeUserString

---

src/Mod/Arch/ArchWindow.py

Values in getSolidSignature must be rounded, else matching solids are often not found.

Arch: Arch_Window round values in getSolidSignature

---

src/Mod/Arch/ArchRoof.py

Hi ! 
I'm author of following [topic](https://forum.freecad.org/viewtopic.php?p=733834). 
In current implementation ArchRoof subvolume generated properly only for wire-based roof.
For solid-base roof it uses given shape as-is. But proper implementation will be 'extrude given shape horizontally up'.
This can be done via macros, [that i showed in topic](https://forum.freecad.org/viewtopic.php?p=738858#p738858).
I didn't sure that my macros code is valid and work in all cases, but if you also check it, maybe we can include this behaviour as default for solid-roof case (in future PR, if code will be correct)
---
In this PR, i just want to give user ability, to override default behaviour and set custom subvolume.
I add new field, and also i refactor getSubvolume method, because in current …

Arch: add subvolume property for ArchRoof (for roof based on solid shape)

---

src/Mod/MeshPart/App/AppMeshPartPy.cpp

This commit enables multithreading use when exporting large quantities of objects (for instance for external rendering).
GIL release is only applied to mesher call, which is pure C / no Python, and only if explicitely required via a new parameter.
In case this new parameter is not set, the previous behavior remains (hold GIL), thus ensuring ascendant compatibility.
This PR replaces https://github.com/FreeCAD/FreeCAD/pull/12241 (@marioalexis84)

Release GIL while meshing in MeshPart.meshFromShape (2nd proposal)

---

src/Mod/Part/Gui/ViewProviderGridExtension.cpp

Fixes the problem where View_FitAll would compute a huge bounding box when the infinite grid is enabled.
Closes #11570

PD: Exclude the grid group from bbox computation

---

src/Mod/Assembly/Gui/CMakeLists.txt

Builds are broken on some platforms without this line.

Assembly: Add ${COIN3D_INCLUDE_DIRS} to CMakeLists.txt

---

tests/src/Mod/Sketcher/App/planegcs/Constraints.cpp

Correct the size of the knot vector used (described here with knots and multiplicities).

[Sketcher] planegcs: Fix issue in arc-B-spline tangent test

---

src/Mod/Assembly/Gui/CMakeLists.txt

Assembly Gui is including <Base/PyObjectBase.h> which in turn includes <Python.h>, so path to Python includes is needed.

Assembly: Add ${PYTHON_INCLUDE_DIRS} to CMakeLists.txt

---

src/App/Material.cpp
src/Mod/Material/Resources/Materials/Appearance/Default.FCMat
src/Mod/Part/Gui/DlgSettingsObjectColor.ui

As discussed with @davesrocketshop the default material appearance is adjusted to better grasp the objects shape (surfaces and contours) with specular highlights and a low ambient color. 
In the long run, this will be replaced with the new material system and the corresponding material pickers / shape appearance preferences.

[Material] Adjust default material appearance

---

src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py

According to the Qt docs, on some platforms (Windows) QProcess::start emits the started signal before the function returns.
With the current implementation of run/stop Calculix, this involves stopping the process immediately after starting it.
To solve this, stopCalculix is connected before runCalculix, so that on the first click the call to stopCalculix is irrelevant.
@FEA-eng can you confirm that this solves the issue on Windows?

Fem: Prevent stop CalculiX immediately - fixes #12448

---

src/Mod/Part/App/FeaturePartBoolean.cpp
src/Mod/Part/App/FeaturePartBoolean.h
src/Mod/Part/App/FeaturePartCommon.cpp
src/Mod/Part/App/FeaturePartCommon.h
src/Mod/Part/App/FeaturePartCut.cpp
src/Mod/Part/App/FeaturePartCut.h
src/Mod/Part/App/FeaturePartFuse.cpp
src/Mod/Part/App/FeaturePartFuse.h
src/Mod/Part/App/FeaturePartSection.cpp
src/Mod/Part/App/FeaturePartSection.h
src/Mod/Part/App/TopoShape.h
src/Mod/Part/App/TopoShapeExpansion.cpp
tests/src/Mod/Part/App/TopoShapeMakeShape.cpp

Get rid of the unnecessary versions of makeElementShape.
Bring over the opCode definitions in the boolean operations.
Fix an issue with incorrect TNP branch boolean code before we flip over.
Some mild delinting.

Toponaming/Part: Remove makeElementShape and cleanup opcode code

---

src/Gui/Application.cpp
src/Gui/Application.h
src/Main/FreeCADGuiPy.cpp

Since the added support for transparent overlay docking widget, FreeCAD reports errors such as
```
Cannot find icon: qss:overlay/close.svg
Cannot find icon: qss:overlay/overlay.svg
Cannot find icon: qss:overlay/mode.svg
...
```
during start-up via `Gui.showMainWindow()` when having FreeCAD imported as a Python module.
To fix that, I copied the necessary code from src/Gui/Application.cpp and adapted it accordingly. I also copied other code parts to make other features such as StyleSheets work in the FreeCAD Gui when it was started from an imported module.
I am aware that duplicated code should be avoided, but my C++ skills and my knowledge of the FreeCAD code base are too limited to come up with a cleaner solution. Any hints from experienced FreeCAD developers are welcome.

Gui: add missing setup code to FreeCADGui started via Gui.showMainWindow()

---

src/App/Expression.cpp
src/App/ExpressionParser.h
tests/src/App/CMakeLists.txt
tests/src/App/ExpressionParser.cpp
tests/src/App/PropertyExpressionEngine.cpp

Solution B: `parsequant()` expression language function

Resolve #11965 (B) no proper execute() for cross-property references

---

src/Gui/View3DInventorViewer.cpp

Finds the bounding sphere when the editing view provider is set. This ensures the right bounding sphere is used for finding the near and far clipping plane
Fixes #12288

Gui: Fix disappearing element handles in sketcher

---

src/Mod/Arch/exportIFC.py

Some objects had their IFC class set to "None" which we decided many epochs ago to prevent because the class is an enum
Fixes yorikvanhavre/FreeCAD-NativeIFC#60
Fixes yorikvanhavre/FreeCAD-NativeIFC#59

[Arch] Always use a default IFC type

---

conda/environment.devenv.yml

Python is pinned in `conda/conda-env.yaml` to the desired version.  This commit also pins the Python version in `conda/environment.devenv.yml` to prevent Python to be downgraded unexpectedly to satisfy dependency constraints.

Conda: Pin Python to prevent automatically downgrading without error.

---

conda/environment.devenv.yml

The dependency `coin3d` has included a necessary bugfix which eliminates the build error that required pinning.

Conda: Unpin coin3d as the latest bugfix version corrects the build incompatibility.

---

conda/environment.devenv.yml

FreeCAD can now be built with OCCT 7.8.0, removing the need to be pinned to 7.6.3.

Conda: Unpin OCCT as FreeCAD now builds with OCCT 7.8.0+.

---

src/Mod/TechDraw/App/Preferences.cpp
src/Mod/TechDraw/App/Preferences.h
src/Mod/TechDraw/Gui/PreferencesGui.cpp
src/Mod/TechDraw/Gui/PreferencesGui.h
src/Mod/TechDraw/Gui/QGIHighlight.cpp
src/Mod/TechDraw/Gui/QGIHighlight.h
src/Mod/TechDraw/Gui/QGISectionLine.cpp
src/Mod/TechDraw/Gui/QGISectionLine.h
src/Mod/TechDraw/Gui/QGIViewPart.cpp
src/Mod/TechDraw/Gui/TaskProjGroup.cpp
src/Mod/TechDraw/Gui/TaskProjGroup.h
src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp

This PR implements two small patches to TechDraw.  This first corrects the tooltips in the projection group dialog.   The second makes section lines adhere to ANSI/ASME standards.

[TD]Fix asme section line

---

CMakeLists.txt
src/Gui/PythonWrapper.cpp

https://forum.freecad.org/viewtopic.php?t=80726

Gui: fixes #12540: ‘ModuleShiboken’ was not declared in this scope

---

src/Mod/Fem/femmesh/meshtools.py
src/Mod/Fem/femsolver/calculix/solver.py
src/Mod/Fem/femsolver/calculix/write_femelement_geometry.py
src/Mod/Fem/femsolver/calculix/write_mesh.py
src/Mod/Fem/femtest/data/calculix/ccx_cantilever_beam_circle.inp
src/Mod/Fem/femtest/data/calculix/ccx_cantilever_beam_pipe.inp
src/Mod/Fem/femtest/data/calculix/ccx_cantilever_beam_rect.inp
src/Mod/Fem/femtest/data/calculix/ccx_cantilever_ele_seg2.inp
src/Mod/Fem/femtest/data/calculix/ccx_cantilever_ele_seg3.inp

replaces #12444 and fixes #12320 (plus adds more versatility as mentioned in the comment under #12444)
This PR adds a new property BeamReducedIntegration to the CalculiX solver. If true (by default), beam elements B31 and B32 are replaced with B31R and B32R, respectively. This way it's possible to use the Pipe beam section and to obtain accurate results when plasticity is involved (mentioned in the comment under #12444).

FEM Beam reduced integration

---

src/Gui/PythonWrapper.cpp

Foreign Python objects needs to be passed as Py::Object(). Py::asObject() is stealing reference and object might be garbage collected even before dereferenced. Problem didn't show in the original code because methods Py::asObject() was used in were never called.
Fixes: ac6f991baff6 (Gui: Consolidate Python -> Qt class conversion)

Gui: PythonWrapper: Do not steal reference  (fixes #12542)

---

src/Mod/AddonManager/AddonManagerTest/app/test_installer.py
src/Mod/AddonManager/addonmanager_installer.py

Updating using the ZIP-based method failed for addons on GitHub - this fixes the issue by correctly searching for the expected subdirectory name instead of assuming there is only one subdirectory.

Addon Manager: Fix ZIP-based update

---

src/Mod/PartDesign/App/FeatureHelix.cpp

Use the wires of the computed face instead of the selected ones.
Fix #12084

PartDesign_Helix: use computed wires

---

src/Gui/Tree.cpp
src/Gui/Tree.h
src/Gui/ViewProvider.h
src/Gui/ViewProviderDocumentObject.cpp
src/Gui/ViewProviderDocumentObject.h
src/Gui/ViewProviderDocumentObjectGroup.h
src/Gui/ViewProviderGroupExtension.cpp
src/Gui/ViewProviderPart.h

Fixes https://github.com/FreeCAD/FreeCAD/issues/5907
This PR enables users to sort items by drag and drop. It also refactor the code of the drop-event.
- Dropping between 2 items place the object between both objects.
- Works within groups (App::Part and Group) (not others like Body, origin...).
- Works in root of documents.
Reference : 
https://forum.freecad.org/viewtopic.php?style=5&t=35316&start=10
https://github.com/FreeCAD/FreeCAD/pull/4626 reverted after : https://forum.freecad.org/viewtopic.php?f=3&t=63744

Tree: Enable sorting when drag&drop.

---

src/Gui/Icons/TreeItemInvisible.svg
src/Gui/Icons/TreeItemVisible.svg
src/Gui/Icons/resource.qrc
src/Gui/PreferencePages/DlgSettingsUI.cpp
src/Gui/PreferencePages/DlgSettingsUI.h
src/Gui/PreferencePages/DlgSettingsUI.py
src/Gui/Tree.cpp
src/Gui/Tree.h
src/Gui/TreeParams.cpp
src/Gui/TreeParams.h
src/Gui/TreeParams.py

In the preferences under Display->UI a user can enable a checkbox to show an additonal icon (eye) before the normal tree view icon. This icon shows the visiblity status of the item and when the user clicks this icon the visibility of the item is toggled. This is a faster alternative to selecting the item and then pressing the space bar.
When working with PartDesign I often switch between the different features to see what my moddeling steps are and this also helps with debugging. I find it annyoung that I always have to click on the feature and then press space. With this icon I just have to click once to switch between the features.
This is a feature from @realthunder LinkMerge branch. This is not a port but a small bare bones implementation.
I hope this is something that can be added to …

Add an icon to toggle the visibility of items in the tree view

---

src/App/Application.cpp
src/App/CMakeLists.txt
src/App/SuppressibleExtension.cpp
src/App/SuppressibleExtension.h
src/App/SuppressibleExtensionPy.xml
src/App/SuppressibleExtensionPyImp.cpp
src/Gui/Application.cpp
src/Gui/CMakeLists.txt
src/Gui/Tree.cpp
src/Gui/ViewProviderSuppressibleExtension.cpp
src/Gui/ViewProviderSuppressibleExtension.h

Many objects can be suppressed, this extension aims to provide a unique visualization in the tree view.
Fix #12361

Core: Create a SuppressibleExtension to provide the Suppressed property to all the WBs

---

src/Gui/BlenderNavigationStyle.cpp
src/Gui/CADNavigationStyle.cpp
src/Gui/RevitNavigationStyle.cpp

Fixes a regression in the Blender, CAD and Revit navigation style caused by #12104.
With this PR the selected faces are no longer de-selected after rotating using the left and middle mouse buttons.
https://forum.freecad.org/viewtopic.php?t=85491

Gui: Fix selection in Blender, CAD and Revit style

---

src/Mod/AddonManager/Addon.py
src/Mod/AddonManager/AddonManager.py
src/Mod/AddonManager/AddonManagerOptions.ui
src/Mod/AddonManager/Widgets/addonmanager_widget_view_control_bar.py
src/Mod/AddonManager/addonmanager_workers_startup.py
src/Mod/AddonManager/package_list.py

This adds the UI and backend to support sorting addons by "score". The value itself is not provided directly by FreeCAD, but is fetched from a user-specified data source online, as specified by the `AddonScoreURL` parameter. That data source should provide a JSON dictionary where the keys are either the URL of the addon or its name (as specified in either the .gitmodules file of the Addons repo, or the name of the macro), and the values are integer values of arbitrary scale.
Test/example score data can be found here: https://gist.githubusercontent.com/chennes/e8f60e80f16e6ffbd057dd47ca36ad2a/raw/7b118cca8e84444c3379919bbd744b99e6ef6711/addon_score_for_testing.json
(Note that isn't a meaningful "score", it is just the length of the addon's description field, and is only intended as a test …

Addon Manager: Add support for Addon Score

---

src/Gui/Tree.cpp

Remove warning in https://github.com/FreeCAD/FreeCAD/pull/12293#discussion_r1503038369 
#12293

Remove useless warning in Tree.cpp introduced by 12293

---

src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfHyperbola.h

so that it does not give 0/0 when cos(phi) = 0
This gave problems if the first two points defined in the sketcher had the same x-coordinate - e.g. when using snap to grid
See: https://forum.freecad.org/viewtopic.php?t=85224

Change the calculation of the b parameter of the hyperbolic arc

---

src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h

The texts for the modes were changed to match those of the line tool.

Sketcher: improve GUI texts for rectangles

---

src/App/PropertyGeo.h

Addresses clang-tidy complaint: declaration 'Feature' is never referenced, but a declaration with the same name found in another namespace 'Part' [bugprone-forward-declaration-namespace]

App: Remove unneeded forward declaration

---

src/Mod/PartDesign/Gui/CMakeLists.txt
src/Mod/PartDesign/Gui/TaskLinearPatternParameters.cpp
src/Mod/PartDesign/Gui/TaskLinearPatternParameters.h
src/Mod/PartDesign/Gui/TaskLinearPatternParameters.ui
src/Mod/PartDesign/Gui/TaskMirroredParameters.cpp
src/Mod/PartDesign/Gui/TaskMirroredParameters.h
src/Mod/PartDesign/Gui/TaskMirroredParameters.ui
src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp
src/Mod/PartDesign/Gui/TaskMultiTransformParameters.h
src/Mod/PartDesign/Gui/TaskMultiTransformParameters.ui
src/Mod/PartDesign/Gui/TaskPolarPatternParameters.cpp
src/Mod/PartDesign/Gui/TaskPolarPatternParameters.h
src/Mod/PartDesign/Gui/TaskPolarPatternParameters.ui
src/Mod/PartDesign/Gui/TaskScaledParameters.cpp
src/Mod/PartDesign/Gui/TaskScaledParameters.h
src/Mod/PartDesign/Gui/TaskScaledParameters.ui
src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp
src/Mod/PartDesign/Gui/TaskTransformedParameters.h
src/Mod/PartDesign/Gui/TaskTransformedParameters.ui

The PD Pattern task panels contain a lot of code duplication around the feature list which makes it difficult to work on the
common ui elements.
These commits move the code for the feature list into the base class ``TaskTransformedParameters``. All the duplicated widgets
are removed from the ui files. The pattern specific ui files only contain the widgets for their parameters. These are then added
to a placeholder widget in the common ui files at runtime.
The ui file for the MultiTransform pattern also contains such a placeholder widget.
The command report for the python console was not consisent which is also fixed by refactoring the ``apply()`` function.
The rest is code cleanup:
- Replace ``enum`` with ``enum class``
- Use default member initializers
- Limit member access as much as …

Refactoring and cleanup of PD Pattern task panels

---

src/Mod/Part/App/OpenCascadeAll.h

Missing file, compilation fails with PCH turned on.

Part: Add  BRepOffsetAPI_MakeEvolved.hxx to OpenCascadeAll.h

---

src/Mod/Part/App/OpenCascadeAll.h

Part: Add BRepOffsetAPI_MakeFilling.hxx to OpenCascadeAll.h

---

src/Gui/Splashscreen.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/12399
This PR removed the code blocks from the copied `About info` in the splash screen. The 3 quotes mess with the GitHub issue template and have to be manually deleted to be formatted correctly. The forum also does not support the 3 quotes as code block.
The `About info` is copied as plain text to the clipboard, the GitHub issue template will automatically display the pasted plain text as code block. No need to manually adjust it, just copy&paste.
Demo of current issue:

About info: remove code block quotes / copy plain text

---

src/Gui/SoFCUnifiedSelection.cpp

The element type SoModelMatrixElement must be enabled for the node types SoHighlightElementAction and SoSelectionElementAction. Otherwise an assert() will fail and causes a crash in debug mode.

Gui: Enable SoModelMatrixElement

---

src/Mod/Part/App/FaceMakerBullseye.cpp

This is a user-visible exception, shown in a dialog box. Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/299

PD: Translate wire not closed exception

---

src/Mod/Path/Path/Base/Gui/GetPoint.py

Commit c36979f removed the argument from Snapper.off() which is used in GetPoint.py. This causes the Tag dressup user interface to give an error when trying to save or close the widget for adding a new point.
(Should I create an issue for such small pull requests?)

Path: fix error in Tag dressup when adding a point.

---

src/Mod/AddonManager/AddonManager.py
src/Mod/AddonManager/CMakeLists.txt
src/Mod/AddonManager/TODO.md
src/Mod/AddonManager/Widgets/addonmanager_widget_addon_buttons.py
src/Mod/AddonManager/Widgets/addonmanager_widget_package_details_view.py
src/Mod/AddonManager/Widgets/addonmanager_widget_readme_browser.py
src/Mod/AddonManager/Widgets/addonmanager_widget_view_selector.py
src/Mod/AddonManager/addonmanager_git.py
src/Mod/AddonManager/addonmanager_package_details_controller.py
src/Mod/AddonManager/addonmanager_preferences_defaults.json
src/Mod/AddonManager/composite_view.py
src/Mod/AddonManager/package_list.py

This brings back something akin to the original Addon Manager display, with the side-by-side display of the list and details views.

Addon Manager: Refactor primary view and enable composite

---

src/Gui/NavigationAnimation.cpp
src/Gui/NavigationAnimation.h
src/Gui/PreferencePackTemplates/View.cfg
src/Gui/PreferencePages/DlgSettingsNavigation.ui
src/Gui/View3DInventorViewer.cpp

This adds an option (enabled by default) to use the InOutCubic easing function in navigation animations. By using this, the start and end of the animations are more smooth instead of directly going to the max speed or 0.

Gui: Add easing to navigation animations

---

src/FCConfig.h

removed discontinued code
__MWERKS__ OSX discontinued from 2005
winnt and mingw are removed

[main] clean FCConfig.h

---

src/App/DocumentObject.cpp
src/App/DocumentObject.h
src/Gui/CommandFeat.cpp
src/Gui/Icons/Std_ToggleFreeze.svg
src/Gui/Icons/resource.qrc
src/Gui/Tree.cpp
src/Gui/Workbench.cpp

Fix  **#5545  Switch on and off parametric behaviour of document objects**

Introduce object freeze

---

src/Gui/TinkerCADNavigationStyle.cpp

The rotation center moved when using the TinkerCAD navigation style and rotation mode set to window center. This happend when pressing MMB -> move mouse -> pressing RMB -> releasing MMB -> move mouse.
This is fixed by setting the rotation center before entering dragging mode.

Gui: Set rotation center when entering dragging in TinkerCAD style

---

src/Mod/Path/libarea/Adaptive.cpp

Remove adjacent coincident and nearly-coincident points from Path. This is issue #6217 
This is based on PR#5276 by sundtek, but it only collapses adjacent points on the Path. It also addresses (IMO) most of the feedback on the original PR.
see also discussion on the forum: https://forum.freecadweb.org/viewtopic.php?f=15&t=42755&start=10#p555566
test file: [glitch.zip](https://github.com/FreeCAD/FreeCAD/files/14441490/glitch.zip)
before:
after:

PATH: Fix adaptive glitch by removing coincident points

---

src/Mod/Part/App/PartFeature.cpp
src/Mod/Part/App/PartFeature.h
tests/src/Mod/Part/App/PartFeature.cpp

Importing method `create()` of `Part::Feature`
Dependency needed for #12535

Part/Toponaming: Transfer Part::Feature::create()

---

src/Mod/Fem/App/FemVTKTools.cpp

For `vtkUnstructuredGrid`, calling `SetCells` sequentially, overrides the previous data.
@FEA-eng

Fem: Use mixed cell types in pipeline unstructured grid - fixes #12581

---

tests/src/Mod/Part/App/FeaturePartCommon.cpp
tests/src/Mod/Part/App/PartFeature.cpp
tests/src/Mod/Part/App/PartTestHelpers.cpp
tests/src/Mod/Part/App/TopoShapeExpansion.cpp

Note that once the test helper is corrected, a couple of existing tests then show platform variations.  A shallow investigation reveals no obvious coding errors and that the code matches with the linkstage3 branch.  There is still a question of if this never-tested-before result is indicating subtle hidden bugs, so appropriate comments inserted.

Toponaming/Part: Correct elementsMatch to test all entries

---

src/Gui/CommandLink.cpp
src/Gui/CommandStructure.cpp

Extra HTML tags were added outside the translation NOOP. They were unnecessary, and broke translation. Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/283

Gui: Fix translation strings for Part, Group, and Link

---

src/Mod/TechDraw/TechDrawTools/CommandHoleShaftFit.py

Will fix https://github.com/FreeCAD/FreeCAD-translations/issues/303 (once translations get updated). Also fixes the error dialog's lack of translation. Note that translators prefer not to have HTML tags when possible, so I've shifted this to using `\n` to get the newlines.

TD: Clean up translations of HoleShaftFit

---

src/Mod/TechDraw/Gui/TaskSectionView.cpp

Switch to %n form so translators can adjust based on the number. Also allows English adaptation to plural/singular, if desired. Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/281

TD: Fix translation of pending updates string

---

src/Mod/TechDraw/App/DrawWeldSymbol.cpp
src/Mod/TechDraw/App/DrawWeldSymbol.h
src/Mod/TechDraw/Gui/QGIWeldSymbol.cpp
src/Mod/TechDraw/Gui/QGIWeldSymbol.h
src/Mod/TechDraw/Gui/QGSPage.cpp
src/Mod/TechDraw/Gui/TaskWeldingSymbol.cpp
src/Mod/TechDraw/Gui/ViewProviderPage.cpp

This pull request ports Weld Symbols parent handling to the common infrastructure based on PRs #12342, #12421 and #12749. The benefits are corrected tree view positioning and the possibility to switch weld symbol between different leader lines freely. Also the code maintainability should be improved.
I have made some basic testing and it seems there are no issues, but as always, bugs may creep in. In such a case please let me know.

[TechDraw] Reimplement Weld Symbol parent linking

---

src/Gui/ExpressionCompleter.cpp

Closes #12785. The cause of the segmentation fault is access to the already deleted _QMenu_. Simple setting attribute `Qt::WA_DeleteOnClose` and removal of `delete menu` prevented it. To reproduce the crash, one needs to mess up the `user.cfg` file in the way described in the issue.
Here is the fragment from the issue to mess up the `user.cfg` file:
```xml
<FCParamGroup Name="Expression">
<FCText Name="EditorTrigger">=</FCText>
<FCBool Name="AntoHideEditorIcon" Value="1"/>
<FCBool Name="NoSystemBackground" Value="1"/>
<FCInt Name="EditDialogBGAlpha" Value="1"/>
<FCInt Name="EditDialogWidth" Value="300"/>
<FCInt Name="EditDialogHeight" Value="214"/>
<FCInt Name="EditDialogTextHeight" Value="35"/>
</FCParamGroup>
```
---
This commit changes also unconnected things:
- usage of …

Fix the crash described in #12785

---

.github/ISSUE_TEMPLATE/PROBLEM_REPORT.yml

Removes optional title key from the issue template on the FreeCAD GitHub project. The intention is to avoid having to include a placeholder issue title. This has two benefits:
1. Fix the current inconsistency of having a template that refers to the submission as a "Problem" and its description referring to it as an "Issue". E.g. `name: Report a Problem` (used also in the template chooser), `title: "Replace with a concise issue title"`
2. Save the reporters the step of selecting the `title: "Replace with a concise issue title"` placeholder string and deleting it before writing their issue title. If the string were selected by default,  it'd make it easier. But it's not, as far as I can tell.
This also avoids the `title must be of type String and cannot be empty. ` error that popped up …

Remove placeholder title from PROBLEM_REPORT.yml issue report template

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Closes #11954. 
- [This topic](https://forum.freecad.org/viewtopic.php?t=72796) has similar backtrace and reproduction steps, however, the user did not create an issue on Github.
- [This issue comment](https://github.com/FreeCAD/FreeCAD/issues/9198#issuecomment-1763448152) also has the same backtrace, but no separate issue has been created.
`proxyVPrdr->renderMgr->getCamera()` returns `nullptr` and then this `nullptr` is fed to `vp->onCameraChanged(cam)` causing segmentation fault.
This commit checks if camera is `nullptr` and shows a warning instead of crashing.
<details><summary>Screenshot</summary>
</details>

Fix segmentation fault in Sketcher

---

src/Mod/Import/Gui/dxf/ImpExpDxfGui.cpp

MinGW needs to know about the COIN_DLL export macro

Fix build failure for MinGW

---

src/Gui/DlgExpressionInput.cpp
src/Gui/DlgExpressionInput.h

If for the DlgExpressionInput the user config parameter 'NoSystemBsckground' is set to True it's not used as a normal dialog but as a pop-up window. In this mode the context-menu of the ExpressionLineEdit isn't working. A previous commit (a3036d16f1de) fixed a crash but not this issue.
For Qt4 DlgExpressionInput has overridden the eventFilter() to handle using the context-menu but this is not working any more for Qt5 or Qt6. Luckily, it has appeared that with Qt5 and Qt6 it works out-of-the box now and the event filter is not needed any more.

Gui: Fix using context-menu of ExpressionLineEdit

---

src/Mod/Draft/DraftGui.py
src/Mod/Draft/Resources/ui/preferences-draftsnap.ui
src/Mod/Draft/draftguitools/gui_base_original.py
src/Mod/Draft/draftguitools/gui_tool_utils.py

This PR introduces a new "Mouse delay" preferences located under Edit -> Preferences -> Draft -> Grid and Snapping
* When mouse delay is set to 0, nothing happens, same as how it works now
* When it's set to a value, ex. 1 second, after you enter a number in one of the coordinate fields in Draft/Arch, the mouse will not change the value anymore during 1 second. After that, it resumes normal working.
* If you set the value to something very high, for ex. 3600 (one hour), mouse movement will be disabled after you start entering numeric values, until the command is finished.
This fixes #11807

Draft: Introduce mouse delay

---

src/Mod/Fem/femmesh/gmshtools.py
src/Mod/Fem/femobjects/mesh_gmsh.py
src/Mod/Fem/femtest/data/elmer/group_mesh.geo

As discussed with @FEA-eng, this gives partial support for hexahedral elements meshing.

Fem: Add partial support for hexahedral elements

---

src/Mod/Part/Gui/TaskAttacher.cpp
src/Mod/Part/Gui/TaskAttacher.h

Eliminate default title, which is untranslatable. Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/300

PD: Translate attachment task title

---

src/Mod/Sketcher/Gui/Command.cpp

`QWidgetAction` is not supplying the correct context to `tr()`, so explicitly set it for these three classes.
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/287
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/286
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/285

Sketcher: Translate rendering order menu

---

src/Gui/Tree.cpp

The icons in the testStatus() function are taken by reference and modified inside. This seems to be used for caching when the same item occurs multiple times in the tree. This can be the case for groups.
The visibility icon was added without taking the cached icon into consideration and so it was added a second time.
The code is now moved into the if statement checking for this case.

Fix #12780: An additional visibility icon is shown for features in groups

---

src/Gui/SoDatumLabel.cpp

Fix a selection issue. May depends on OpenGL version?
**Previously:**
not pre-selected
pre-selected
selectable zone
**With this fix**
EDIT: certainly due to QUAD deprecation: see https://www.khronos.org/opengl/wiki/Primitive#Quads

Core: Fix unselectable area in SoDatumLabel

---

src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
src/Mod/Sketcher/Gui/Workbench.cpp

Sketcher_ConstrainLock after Sketcher_ConstrainAngle.
Sketcher_ConstrainRadiam before Sketcher_ConstrainRadius.
This was not always correct.
See also #12667.

Sketcher: correct position of ConstrainLock and ConstrainRadiam in GUI

---

src/Mod/Draft/draftviewproviders/view_layer.py

Allows to add a *HideChildren* property to Draft layers to prevent them from claiming their objects. This allows other workbenches to create layers that don't list their contents, while leaves current Draft layers unchanged.

Draft: Allow to prevent layers to claim children

---

src/Mod/AddonManager/Widgets/addonmanager_widget_readme_browser.py

Fixes #12825. Even with "GitHub flavored Markdown" enabled, Qt's Markdown processor chokes on some HTML tags. This small method removes the tags that are known to break rendering. It may be extended in the future to do a more intelligent replacement.

Addon Manager: Strip some HTML tags from Markdown

---

src/Mod/AddonManager/addonmanager_package_details_controller.py
src/Mod/AddonManager/addonmanager_readme_controller.py

When no macro metadata is downloaded, the macro has no URL yet. Fixes #12724

Addon Manager: Fix README fetch for macros

---

src/Mod/AddonManager/manage_python_dependencies.py

When running a pip install, the manager must wait for the previous thread to complete before beginning the next. Fixes #12834.

Addon Manager: Python package installer wait for thread

---

.github/ISSUE_TEMPLATE/PROBLEM_REPORT.yml
.github/labels.yml

- Change label from `WB Path` to `WB CAM` --> already done
- Change label action to apply new label and change folder name to look for
- Change issue template to have CAM in the dropdown. Path is kept as it is still called Path in the stable release. New would be `CAM/Path`

Relabel Path to CAM in GitHub template and label action

---

src/Main/MainGui.cpp

"QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix"

Gui: Remove ".desktop" suffix from QGuiApplication::setDesktopFileName()

---

src/Mod/AddonManager/Widgets/addonmanager_widget_readme_browser.py
src/Mod/AddonManager/addonmanager_readme_controller.py

External links to relative files were not being followed because Qt had no way of knowing how to get to the file. Complicating matters, for links to markdown files we don't want the "raw" page (showing the markdown) to be the thing loaded in your browser, we want the rendered version. Fixes #12832.

Addon Manager: Fix relative external links

---

src/Mod/Part/App/PlateSurfacePy.xml
src/Mod/Part/App/RectangularTrimmedSurfacePy.xml
src/Mod/Part/App/ShapeFix/ShapeFix_EdgePy.xml

Related to https://github.com/FreeCAD/FreeCAD/issues/12547 as a part of improving API documentation for FreeCAD.

Added-API-Documentation-for-RectangularTrimmedSurfacePy.xml and others.

---

src/Mod/TechDraw/TechDrawTools/TaskHoleShaftFit.py

According to ISO 286 there is supposed to be a space inbetween the nominal size and the tolerance class. This change just adds this space. Fixes #12922

TechDraw: Add space before tolerance class for hole/shaft fits

---

src/Mod/TechDraw/App/DrawViewPy.xml
src/Mod/TechDraw/App/DrawViewPyImp.cpp
src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/Workbench.cpp

This PR removes the obsolete Link Dimension command from the toolbar (but not the menu) and exposes DrawView::getScale to Python.

[TD]2 small fixes 

---

src/Mod/Material/materialtools/cardutils.py

Fixes #12933
The previous card implementation used a parameter to select either solids or fluids. The current material dictionary ignored the parameter and only returned solids. This PR restores the use of the material type filter.

Material: Call to import_materials only returning solids

---

src/Mod/Material/App/MaterialPyImpl.cpp
src/Mod/Material/App/Materials.cpp
src/Mod/Material/App/Materials.h
src/Mod/Material/materialtests/TestMaterials.py

Fixes #12935
The previous card implementation transferred strings directly to the card dictionary without interpretation. The new material system parses the file data, producing a dictionary for compatibility. The new dictionaries localized the strings which is incorrect. This PR removes that localization.

Material: Removes localization from the material card dictionary

---

src/Mod/Fem/Gui/PreCompiled.h

A couple of missing `Inventor/nodes` includes.

FEM: Add two missing PreCompiled.h includes

---

src/App/GroupExtension.h

For more details see: https://forum.freecad.org/viewtopic.php?t=86001
The reason of the crash is that the GIL is not locked while accessing certain Python functions

App: Fix segmentation fault while dragging object

---

src/Mod/Drawing/Gui/Command.cpp
src/Mod/Drawing/Gui/DrawingView.cpp

The deprecated Drawing module still uses some classes that have been removed with Qt6. These are the classes:
* QRegExp that is replaced with QRegularExpression
* QGLWidget that is replaced with QOpenGLWidget

Drawing: Fixes #12953

---

src/Mod/TechDraw/App/DrawProjGroupItem.cpp
src/Mod/TechDraw/App/DrawView.cpp
src/Mod/TechDraw/App/DrawView.h
src/Mod/TechDraw/Gui/QGIProjGroup.cpp
src/Mod/TechDraw/Gui/QGIView.cpp
src/Mod/TechDraw/Gui/QGIView.h
src/Mod/TechDraw/Gui/QGSPage.cpp
src/Mod/TechDraw/Gui/ViewProviderPage.cpp

This pull request follows with converting the parent handling code on common infrastructure (see #12812 for details). This time there is no owner/parent property which could be changed by the user, but still the code can benefit from the transition.
As a part of the refactoring effort, I have removed the explicit position locking on the QGIView level. It was used only for DrawProjectionGroupItem and with the QGIView's setFlag(ItemIsMovable, !isLocked) in updateView() it was just duplicating already existing functionality with rather unfortunate consequences.
I believe this pull request does not introduce any regressions, but in spite of my testing this can still happen. In such a case please let me know, so I can fix them.

[TechDraw] Unify Projection Group parent linking

---

src/Mod/TechDraw/TechDrawTools/CommandAxoLengthDimension.py

Use new function getScale() instead of Scale property to receive the scale of the selected view.

[TD] AxoLengthDimension: use getScale() instead of Scale

---

src/Mod/TechDraw/App/CMakeLists.txt
src/Mod/TechDraw/App/DimensionAutoCorrect.cpp
src/Mod/TechDraw/App/DimensionAutoCorrect.h
src/Mod/TechDraw/App/DimensionReferences.cpp
src/Mod/TechDraw/App/DimensionReferences.h
src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/App/DrawViewDimension.h
src/Mod/TechDraw/App/DrawViewPart.cpp
src/Mod/TechDraw/App/Geometry.cpp
src/Mod/TechDraw/App/Geometry.h
src/Mod/TechDraw/App/GeometryMatcher.cpp
src/Mod/TechDraw/App/GeometryMatcher.h
src/Mod/TechDraw/App/Preferences.cpp
src/Mod/TechDraw/App/Preferences.h
src/Mod/TechDraw/Gui/Command.cpp
src/Mod/TechDraw/Gui/QGIViewDimension.cpp

This PR separates the code responsible for handling dimension reference problems out of the base DrawViewDimension into a new file DimensionAutoCorrect.  It also includes a number of improvements to the LTNP algorithms:
- additional geometry types
- add method to handle line like bsplines
- handle deleted ref body feature
- add test for empty savedGeometry
- add switch for matcher/LTNP on/off

[TD]Refactor LTNP correction code for Dimensions

---

src/Mod/TechDraw/Gui/TaskDimension.cpp
src/Mod/TechDraw/Gui/TaskDimension.h

This PR is a follow-on to #12966.  It implements the weak_ptr check suggested here: https://forum.freecad.org/viewtopic.php?p=747232#p747232
- prevent crash if dimension deleted by Python while dialog is open

[TD]use weak_ptr as deletion guard in Dimension dialog

---

src/Gui/MDIView.cpp
src/Gui/MDIView.h
src/Gui/MainWindow.cpp
src/Gui/MainWindow.h
src/Gui/StartupProcess.cpp

fixes #11858 
current active document is shown in the main window title bar. An asterisk is displayed in front, if unsaved changes exist.
current, always static:
new:

Display current active document in main window title

---

src/Gui/NaviCube.cpp

Edit: now this PR only adds 'fit selection'
Fixes https://github.com/FreeCAD/FreeCAD/issues/12317
This adds menu entries to the navicube button. The idea is to make the menu more complete so that users can hide the view toolbar and still have access to all its functionality.
Before left, after right
Remarks : 
- Yes I have put front/top... even though the cube provide this already. My reasoning is that sometimes I use the view toolbar because I don't want to analyze the cube to find top view. So I still like to have quick access to those.
- I have not added the Std_TreeViewActions because they feel out of context here. And not very useful so feel ok only in the main menu. Thoughts ?

Navicube : Add missing view menu entries.

---

src/Mod/Fem/femmesh/meshtools.py
src/Mod/Fem/femsolver/calculix/write_femelement_geometry.py
src/Mod/Fem/femtest/data/calculix/ccx_cantilever_beam_circle.inp
src/Mod/Fem/femtest/data/calculix/ccx_cantilever_beam_pipe.inp
src/Mod/Fem/femtest/data/calculix/ccx_cantilever_beam_rect.inp
src/Mod/Fem/femtest/data/calculix/ccx_cantilever_ele_seg2.inp
src/Mod/Fem/femtest/data/calculix/ccx_cantilever_ele_seg3.inp

closes #12818 
Changes not only the rotation of the cross section, but the order of the 1,2-dimensions for the RECT beam section - now matches with CalculiX docs. This might be a breaking change for some 3rd Parties (if any), but it doesn't break anything in FreeCAD
Tested on Windows
- Example CCX cantilever beam rectangle gives the same result in both the previous and the proposed version
- Checked all directions
- Checked ElementRotation1D with different angles
.FCStd files are in the forum thread: https://forum.freecad.org/viewtopic.php?t=85951

FEA: fix 1d beam cross section orientation

---

src/Gui/CommandView.cpp
src/Gui/Workbench.cpp

fixes #12864 
This PR creates a grouped command button in the toolbar for all the default views (more in the issue). It is enabled by default.
All previously visible individual view buttons are available as a separate toolbar and can be easily enabled.
Previously (too much space):
With this PR:
Optionally all current individual toolbar buttons for the 7 views are still available:

UI/UX: Create a toolbar command group for default views

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Adds the command for the perpendicular constraint to the context menu in Sketcher if a line and conic is selected.

Sketcher: Contextual right click menu: add perpendicular for line and conic selection

---

src/Mod/Arch/exportIFC.py

The Arch IFC exporter is extended so it can also work on an existing ifcopenshell file instance, appending objects to it instead of creating a file from scratch

Arch: Allow the IFC exporter to append to an existing IFC file

---

src/Gui/Application.cpp
src/Gui/MDIView.cpp
src/Gui/MDIView.h
src/Gui/MainWindow.cpp

* fix hard crash in MainWindow::_updateActions() if no MDI view exists
* in MDIView::buildWindowTitle() use the label of the document because this changes when saving it while the name is immutable
* fix const correctness in MDIView::buildWindowTitle()
* do not set the modified flag of the main window in MDIView::buildWindowTitle() but in the calling instance
* move setting the main window title to Application::viewActivated to reduce code duplication
* fix missing application name if FreeCADGui is loaded as Python module

Gui: fix several regressions caused by PR #12035

---

src/Mod/Arch/ArchSpace.py

New variables are now available for ArchSpace in the Text attribute: $description and $longname, which will show the `Description` and `Long Name` IFC attributes respectively.

Arch: Added longname and description to ArchSpace Text variables

---

tests/src/Mod/Part/App/AttachExtension.cpp
tests/src/Mod/Part/App/CMakeLists.txt

Create two plane features and map the second on the first plane with map mode 'FlatFace'
This PR demonstrates a regression caused by the commits 7945bf68 and 2adff99c14

Tests: add test for attach extension

---

src/Mod/PartDesign/Gui/Utils.cpp

The reason of the crash is a static_cast of an unknown type that causes undefined behaviour. The feature AdditiveLoft has the property Section of type PropertyLinkSubList but the function does a static_cast to PropertyLinkList.
The solution is to use a dynamic_cast that returns null if the cast fails.

Issue #11989: Segfault on "Move Object to Other Body"

---

src/Mod/Part/App/AttachEnginePyImp.cpp
src/Mod/Part/App/AttachExtension.cpp
src/Mod/Part/App/Attacher.cpp
src/Mod/Part/App/Attacher.h
src/Mod/PartDesign/Gui/Command.cpp

Fix #13055.   Passes #13078.  Also passes all other c++ and python tests.

Toponaming/Part: Move missed attacher code into place

---

src/Mod/Fem/App/CMakeLists.txt
src/Mod/Fem/App/FemPostObject.cpp
src/Mod/Fem/App/FemPostObject.h
src/Mod/Fem/App/FemPostObjectPy.xml
src/Mod/Fem/App/FemPostObjectPyImp.cpp
src/Mod/Fem/App/FemPostPipelinePy.xml
src/Mod/Fem/Gui/ViewProviderFemConstraintPy.xml
src/Mod/Fem/Init.py
src/Mod/Fem/feminout/importVTKResults.py

It works using the `Export...` item in the menu bar and from Python using the `writeVTK` method of post-processing objects.
File extension is automatically detected from data type.
@FEA-eng

Fem: Export post-processing data to VTK - fixes #5816

---

src/Mod/Arch/ArchStructure.py
src/Mod/Arch/ArchWall.py

Some Arch tools behave like Draft tools (they allow "drawing"). These should be registered to Draft so additional Draft mechanisms such as the grid turning automatically on/off apply.

Arch: Register interactive arch tools to draft

---

src/Mod/TechDraw/App/DrawViewSection.cpp
src/Mod/TechDraw/App/LineGenerator.cpp
src/Mod/TechDraw/App/Preferences.cpp
src/Mod/TechDraw/Gui/QGIViewSection.cpp

This PR implements a fix to a problem with the initial painting of PAT hatches on section views as reported here:  https://forum.freecad.org/viewtopic.php?t=86257&sid=5fc5a6dca5f30062cd1370d1ba182958
I also includes a temporary patch that affect dev users as reported here: https://forum.freecad.org/viewtopic.php?t=86183&sid=5fc5a6dca5f30062cd1370d1ba182958

[TD]Fix no PAT hatch on first paint

---

src/Mod/TechDraw/TechDrawTools/TaskHoleShaftFit.py

The commit modifies how hole/shaft fits are displayed in TechDraw.
ISO 286/14405-1 calls for a plus sign if the limit is positive and a minus sign if the limit is negative. A zero limit should have neither a plus nor a minus sign. This commit adds the plus sign.
Fixes #13092

Add leading plus (+) in hole/shaft fit limit

---

conda/conda-env.yaml
conda/environment.devenv.yml

Miniforge has upgraded from 23.x.y to 24.x.y, permitting the unpinning of dependencies. Furthermore, these pinned packages cause build issues with the latest version of Miniforge.

Conda: Unpin packages post miniforge upgrade.

---

src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h
src/Mod/Sketcher/Gui/CMakeLists.txt
src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
src/Mod/Sketcher/Gui/DrawSketchHandlerSymmetry.h
src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
src/Mod/Sketcher/Gui/Resources/icons/pointers/Sketcher_Pointer_Create_Symmetry.svg

Rework the symmetry tool, instead of using last selected geo as reference which is kind of clunky, you just select the geos you want and trigger the tool. Then you can hover on any line or point and see the resulting geos. Clicking on a line or point validate the tool.
You also now have the option to create symmetric constraints, so that the created geos are linked to the original.
Testing required. @FEA-eng

[Sketcher] Symmetry tool rework.

---

src/Mod/TechDraw/Gui/ViewProviderPage.cpp
src/Mod/TechDraw/Gui/ViewProviderPageExtension.cpp
src/Mod/TechDraw/Gui/ViewProviderPageExtension.h
src/Mod/TechDraw/Gui/ViewProviderViewClip.cpp
src/Mod/TechDraw/Gui/ViewProviderViewClip.h
src/Mod/TechDraw/Gui/Workbench.cpp

This PR address 3 low hanging fruits in techdraw : 
- Fixes #13061
In sketcher double clicking on a sketch changes the active workbench to sketcher.
Similarly double clicking on an assembly switch to assembly.
For consistency, I offer to implement the same behavior when double clicking on a page, switch to techdraw.
- Fixes #12375 :
Techdraw has a 'move view' tool that is pointless. Moving views should be done by drag and drop. It actually was supported before but got broken with the introduction of `canDropObjectEx
- Fixes #12379:
Remove add/remove from clip. It is now possible to drag and drop between page and clip groups. It is even possible to drag and drop between different pages pages/clip groups.
Remove the Clip toolbar as it now has a single entry, and put the clip button to the …

TechDraw: Fix drag&drop of views. Add auto-switch to techdraw on double click.

---

src/App/ComplexGeoDataPy.xml
src/App/ComplexGeoDataPyImp.cpp
src/Mod/Part/CMakeLists.txt
src/Mod/Part/TestPartApp.py
src/Mod/Part/parttests/TopoShapeTest.py
tests/src/Mod/Part/App/FeaturePartCut.cpp

Also establishes a Python test approach.
The element map testing is incomplete, as that needs at least one python interface to a TopoShape operation; that is slated to be Part.Compound in a separate PR; the tests can and will be upgraded as part of that PR.
The tests are in fact run as part of the CI - I had a failure on .MemSize to prove it.

Toponaming/Part Bring in Python layer for ComplexGeoData

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h
src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
src/Mod/Sketcher/SketcherTests/TestSketchFillet.py

I have not changed the name of the `areColinear` function.

Sketcher: Spelling colinear -> collinear

---

src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h
src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h
src/Mod/Sketcher/Gui/Utils.cpp
src/Mod/Sketcher/Gui/Utils.h

The same function exists in the Draft module but don't fix it there to avoid to possibly break add-ons
A follow-up PR of #13135

Sketcher: fix typo in function name -> areCollinear

---

src/Mod/TechDraw/Gui/Workbench.cpp

Remove "cosmetic eraser" from toolbar as it can be done by selecting and pressing delete, which is the expected workflow.
Fixes https://github.com/FreeCAD/FreeCAD/issues/13072
@WandererFan

TechDraw: Remove "cosmetic eraser" from toolbar

---

src/Mod/TechDraw/App/CosmeticExtension.cpp
src/Mod/TechDraw/Gui/QGIEdge.cpp
src/Mod/TechDraw/Gui/QGIEdge.h
src/Mod/TechDraw/Gui/QGIPrimPath.cpp
src/Mod/TechDraw/Gui/QGIView.cpp
src/Mod/TechDraw/Gui/QGIViewPart.cpp
src/Mod/TechDraw/Gui/QGIViewPart.h
src/Mod/TechDraw/Gui/QGSPage.cpp
src/Mod/TechDraw/Gui/QGVNavStyle.cpp
src/Mod/TechDraw/Gui/QGVNavStyleTouchpad.cpp
src/Mod/TechDraw/Gui/ViewProviderPage.cpp

This PR implements a fix for issue #13067.  This fix prevents the creation of the undo transaction that can not be applied since cosmetic elements are not document objects.

[TD]fix fail on undo of cosmetic delete

---

src/Mod/Sketcher/App/SketchObject.cpp

It isn't clear if this method override from the linkstage3 branch is correct.  This disables it while we dig into it.

Toponaming/Part: Bug fix for #13169 while we sort out required sketcher changes.

---

src/Mod/Part/App/TopoShapePy.xml
src/Mod/Part/App/TopoShapePyImp.cpp

Two changes to python distToShape() function.
- Add optional tolerance to distToShape in order to catch more results if desired.
- Enable multithreading to distToShape. This was added in OCCT in commit [0f05f21194a6711251182a118643efc9eb6c322b](https://git.dev.opencascade.org/gitweb/?p=occt.git;a=commit;h=0f05f21194a6711251182a118643efc9eb6c322b). Published in version [7.6.0](https://git.dev.opencascade.org/gitweb/?p=occt.git;a=shortlog;h=refs/tags/V7_6_0). I get x3 to x6 performance boost on a rather complex 20 Mo STEP file.

[Part] Add optional tolerance and enable multithreading to distToShape 

---

src/Mod/Sketcher/Gui/Command.cpp

The old menu text of Sketcher_MapSketch did not describe the tool very well. Not just a face can be selected.
"Map sketch to face..." -> "Attach sketch..."
Forum topic:
https://forum.freecad.org/viewtopic.php?t=86112

Sketcher: Improve menu text of Sketcher_MapSketch

---

src/Mod/PartDesign/Gui/Workbench.cpp

fixes https://github.com/FreeCAD/FreeCAD/issues/6043
Adds missing commands to the tree context menu in the Part Design WB to be consistent across WBs.
Previously in PD:
Previously in Part:
With this PR in PD:

Part Design: add missing commands to tree context menu

---

src/Mod/Inspection/App/InspectionFeature.cpp
src/Mod/Mesh/App/Core/Grid.cpp
src/Mod/Mesh/App/Core/Grid.h
tests/src/Mod/Mesh/App/Mesh.cpp

Remove problematic method MeshGrid::Rebuild(unsigned long, unsigned long) and MeshGrid::CalculateGridLength(unsigned long, unsigned long)
For almost flat meshes CalculateGridLength may compute a grid with a huge amount of cells that allocates the whole RAM of the system while for an exactly flat mesh a grid with a sensible number of cells is computed.
Use the overloaded methods of MeshGrid::Rebuild(unsigned long) and MeshGrid::CalculateGridLength(unsigned long) instead

Mesh: Fix grid creation for almost flat meshes

---

src/Tools/SubWCRev.py

Fix regexp string quoting that cause warnings during cmake

Fix regexp string quoting

---

src/Base/Console.h

The notifier string must be a std::string() instead of an empty C string as otherwise the wrong methods are called so that all messages are sent to the void.
This regression was caused by commit dc08aa8e0f80cec

Base: Fix console logging macros

---

src/Gui/Action.cpp
src/Gui/Action.h
src/Gui/CMakeLists.txt
src/Gui/PreferencePages/DlgSettingsWorkbenches.ui
src/Gui/PreferencePages/DlgSettingsWorkbenchesImp.cpp
src/Gui/PreferencePages/DlgSettingsWorkbenchesImp.h
src/Gui/WorkbenchManager.cpp
src/Gui/WorkbenchManager.h
src/Gui/WorkbenchSelector.cpp
src/Gui/WorkbenchSelector.h

Fixes https://github.com/FreeCAD/FreeCAD/issues/8692
Introduce Tab-Bar workbench selector (inspired by triplus' addon)
Can go on any side (north/south/west/east) : 
Preferences : 
You can configure text / icon or both. (for combobox too btw)
Can be put on the corner widget same as the combobox:
**The default is not changed : ComboBox as a toolbar with text & icons.**

[Core] Introduce Tab-Bar workbench selector

---

src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp
src/Mod/PartDesign/Gui/TaskTransformedParameters.h

Previously the active Body would be checked and used to add new subfeatures.
This would either do nothing, when no Body was active, causing confusion for users becaues than can edit other features without an active Body.
Or it would add the subfeature to the wrong Body if another Body than the one of the MultiTransform was active.
Now the Body of the MultiTransform is checked and used. This fixes #12491.

Allow adding subfeatures to MultiTransform if there is no active Body

---

src/Mod/PartDesign/App/FeatureTransformed.cpp

This ignores suppressed features in patterns but just skipping over them. No additional shapes are generated for them.
This requires #12537 and fixes #12914.

Ignore suppressed features in patterns

---

src/Gui/ViewProviderSuppressibleExtension.cpp

Fix #13001 
- Add a validity test on linked `App::DocumentObject`
- Rename variables for a better readability
EDIT : Fix #13043

[PD] Fix crash related to SuppressibleExtension

---

src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/13136
Double clicking on :
- a sketch changes the active workbench to sketcher.
- a assembly switch active workbench to assembly.
- a body switch active workbench to partDesign.
- an Analysis container switch active workbench to FEM
- a techdraw page switch active workbench to techdraw
For consistency we could have the same behavior when double clicking on a spreadsheet, switch to spreadsheet.

SpreadSheet: Double clicking a spreadsheet changes to spreadsheet wb

---

src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h
src/Mod/Sketcher/Gui/DrawSketchHandler.cpp

Add a line mid-point (symmetric) auto constraint when creating geometries.
Refactor a little bit of code at the same time (for loop, auto)
Fixes #10704
Fix one part of #11414
Also mentioned in #6240
@pierreporte

Sketcher: Add line mid-point auto-constraint

---

src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/Gui/DrawSketchHandlerSymmetry.h

Sketcher: Symmetry fix an error message when hovering on non-line geos. Also prevent validation of tool when clicking on non-line geos.
Fixes #13164

Sketcher: Symmetry fix #13164

---

src/Gui/CommandView.cpp
src/Gui/Workbench.cpp

Fixes #11353 : 
- Groups now toggling their content correctly.
- The command toggle the PD body instead of the tip
- The command placement in the View menu is fixed.

Core: Std_ToggleTransparency: Fixes #11353

---

src/Mod/Part/App/AppPartPy.cpp
src/Mod/Part/App/TopoShapeCompSolidPyImp.cpp
src/Mod/Part/App/TopoShapeFacePyImp.cpp
src/Mod/Part/App/TopoShapePy.xml
src/Mod/Part/App/TopoShapePyImp.cpp
src/Mod/Part/App/TopoShapeShellPyImp.cpp
src/Mod/Part/App/TopoShapeSolidPyImp.cpp
src/Mod/Part/parttests/TopoShapeTest.py

Python implementations for CompSolid, Face, Shell, Solid as well as missing entries in TopoShape and cleanups from prior PR.

Toponaming/Part move in PyImps

---

src/Mod/Material/App/CMakeLists.txt

My gentoo build failed, it is yaml-cpp 0.7.0.
change if branch version in #12423.
tested on 0.7.0 on linux and 0.8.0 on windows.

fix for yaml version

---

src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp

The use of static_cast here could cause undefined behaviour because at this point it's not guaranteed that findBodyOf() really returns a PartDesign::Body

PD: replace static_cast with dynamic_cast

---

src/Mod/PartDesign/Gui/ViewProviderShapeBinder.h

The problem is caused by conflicting values of the anonymous enum of ViewProviderSubShapeBinder. The solution is to set a higher value than the highest value of EditMode

PD: Fixes 12673: Transforming of sub-shape binder fails

---

src/Gui/CommandLink.cpp

Currently the active button of the Std_LinkActions command is toggable that is confusing behaviour. This PR makes the action group non-checkable

Gui: Fix Std_LinkActions

---

src/Mod/CAM/Gui/Resources/panels/PageOpDrillingEdit.ui
src/Mod/CAM/Path/Base/Generator/drill.py
src/Mod/CAM/Path/Op/Drilling.py
src/Mod/CAM/Path/Op/Gui/Drilling.py
src/Mod/CAM/Tests/TestPathDrillGenerator.py

Adds a checkbox to output a G85 cycle used for reaming or boring. The cycle is like a normal drilling op, but feeds back out of the hole instead of performing a rapid move.
G85 does not support peck or dwell, so those other options are disabled when the "Feed retract" option is enabled in the UI.
The new option looks like this:
I didn't put too much effort into making the UI nice as IMO the drilling config pane could use a more general rework anyway, so it's just another checkbox thrown in for now. Do let me know if you'd like a different UI layout or element though!
Peck and Dwell are disabled when Feed retract is enabled:
P.s. I am not a Python/Qt developer whatsoever, so I may have made some simple mistakes.

CAM/Drilling: Add feed retract option to drilling op settings for reaming/boring heads

---

src/Gui/DocumentPy.xml
src/Gui/DocumentPyImp.cpp

GuiDocuments have a "Modified" attribute that says if the doc has been modified or not (and prints an * in the titlebar). This attribute is read-only in the python interface (only getter is defined).
With [NativeIFC](https://github.com/yorikvanhavre/FreeCAD-NativeIFC), we are handling IFC files natively in FreeCAD, so all file loading/saving is done inside the module already, there is no more saving to .FCStd files. Last bit missing, not be annoyed by FreeCAD that the document has not been saved.
So this implements a resetModified() python method to unset the Modified flag.
I considered making the Modified attribute writable (implement a setter), but I'm not sure... People could play wrongly with that and they would loose the warning to save the file when closing FreeCAD. I thought maybe …

Gui: Allow to unset modified state

---

src/Ext/freecad/CMakeLists.txt
src/Mod/Fem/CMakeLists.txt
src/Mod/Material/CMakeLists.txt
src/Mod/Material/Gui/CMakeLists.txt
src/Mod/Robot/CMakeLists.txt

Fixes #12949 
There are several inconsistencies between a built and an installed version. This PR fixes most of them:
* Copy some missing Python modules to Ext of the build directory
* Do not intall `__init__.py` to the sub-directories of the z88 directory
* Do not install the testprog.* files
* Files listed in MatGuiImages are not copied during the build
* Don't install Material_rc.py
* Install materials-editor.ui to the correct sub-directory

Mat: Material editor can't be opened from FEM_MaterialSolid and FEM_MaterialFluid

---

src/Mod/Part/App/WireJoiner.cpp

Added precompiler directive to use `std::hash` instead of `HashCode(INT_MAX)` if `OCC_VERSION_HEX >= 0x070800`
Fixes https://github.com/FreeCAD/FreeCAD/issues/13210

Part/Toponaming: WireJoiner - use std::hash

---

src/Tools/updatecrowdin.py

Material's translation resources are not in the Gui subdirectory.

Fix Material resource location

---

src/App/GeoFeature.cpp
tests/src/Mod/Sketcher/App/SketchObject.cpp

* Restored previous logic of GeoFeature::getElementName()
* Added precompiler directive to use the old logic if FC_USE_TNP_FIX isn't defined, otherwise use the new logic
* Reworked SketchObjectTest::getElementName() as a consequence of the previous points
fixes #13009
fixes #13248

App/Toponaming: GeoFeature - fixes #13009 - fixes #13248

---

src/Mod/Fem/App/FemConstraint.cpp
src/Mod/Fem/App/FemConstraint.h
src/Mod/Fem/Gui/ViewProviderFemConstraint.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraint.h
src/Mod/Fem/femtools/membertools.py

A suppressed constraint is no more written in the solver's input file and so not take into account for analysis.
Fix (partial) #12115

FEM: allow to Suppress the constraints

---

src/Gui/PreferencePackTemplates/Sketcher_Colors.cfg
src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h
src/Mod/Sketcher/Gui/EditModeCoinManager.cpp
src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.cpp
src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h
src/Mod/Sketcher/Gui/EditModeGeometryCoinConverter.cpp
src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp
src/Mod/Sketcher/Gui/SketcherSettings.cpp
src/Mod/Sketcher/Gui/SketcherSettingsAppearance.ui

This PR changes the color of points in sketcher following DWG discussion.
1- edges (Line/arcs...) end/start points : Normal geo color (white)
2- Conic centers : construction geo color (blue)
3- Construction point : construction geo color (blue)
4- normal point : normal geo color (white)
5- When a point is coincident to another point : Constraint color (red) (other points colors render on top).
6 - Point tool now creates point that reflect construction mode. ie real point or construction point.
7 - Remove Vertex color from preferences as vertexes now use the geometry colors
Fixes https://github.com/FreeCAD/FreeCAD/issues/12582
@pierreporte let me know if you think it closes https://github.com/FreeCAD/FreeCAD/issues/11919
Partial fix of https://github.com/FreeCAD/FreeCAD/issues/11799, …

Sketcher: Change rendering colors of points.

---

src/Mod/Assembly/App/AssemblyObject.cpp

FreeCAD is crashing during 'Solve Assembly' call if the Part property (Assembly/Joints/Fixed/Joint Connector 1/Part1 or Assembly/Joints/Fixed/Joint Connector 2/Part2) of fixed Joint is unset.
Steps to reproduce:
- make simple Assembly e.g. of two cubes with Fixed joint
- Select Fixed joint in the tree and go-to property 'Data' tab
- Select Part1 or Part2 of 'Joint Connector 1' or 'Joint Connector 2' and remove this reference
- call 'Solve Assembly' now
The FreeCAD will crash here because the call
App::DocumentObject* part = getLinkObjFromProp(joint, propPartName); will return NULL pointer.
The property Part1 or Part2 can get empty (unset) during usual construction operations - during changing construction history and it can be very hard to find the cause of FreeCAD crash on a big model. …

Assembly: fix segfault when Part property of Joint Connector is missing

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

The edit datum dialog is opened by double-clicking on a dimensional constraint in a sketch. However, the double-clicking event doesn't work realiably on some systems. As a workaround this PR adds the command to the context-menu.
For more details see the forum thread: https://forum.freecad.org/viewtopic.php?t=71137

Sketch: add command to context-menu to change value of constraint

---

src/Mod/Fem/femtest/app/test_ccxtools.py

Closes #12965 
* Migrated tests from test_solver_calculix to test_ccxtools (consequence of `calculix` removal, #12876)
* Removed `test_name` from functions' parameters: was unused
* Ran code formatter

FEM: migrate calculix tests to ccxtools tests

---

src/Mod/Fem/femtest/app/support_utils.py
src/Mod/Fem/femtest/function_tests/test_support_utils.py

This is an attempt to close #7188 and resolve issues in #12985
Still using `difflib.unified_diff` to check files, but this PR adds a more thorough check for lines that differ.
1. Lines are split into elements by using different strategies, as there are different file formats. Then these elements are converted to float
2. Then the lines are compared element-wise as floats with some absolute tolerance (`1e-10`)
3. If the lines are equal element-wise, they are removed from the lines that differ
I felt a strong urge to write some tests to better document the behaviour of the `parse_diff` function, to check its correctness and for ease of checking for others. There is no practice to test a particular function in FEM WB, so adding such a test is debatable - I'm open to discussion
@FEA-eng, …

FEM: Float comparison for FEM tests

---

src/Mod/Fem/feminout/importToolsFem.py
src/Mod/Fem/femsolver/calculix/solver.py
src/Mod/Fem/femsolver/calculix/write_step_equation.py

fixes #11646 and also adds uncoupled temp-disp analysis type
a new property `Thermo Mech Type` is added; by default, it's set to `coupled` - nothing changes, but it can be also set to `uncoupled` (then the analysis type is uncoupled temperature-displacement) or `pure heat transfer` (then the analysis type is heat transfer)

Add uncoupled temp-disp and heat transfer CalculiX FEM analysis types

---

src/Gui/OverlayManager.cpp

Fixes #13212.
Sets `_trackingWidget` to nullptr when **all** mouse buttons are released. @maxwxyz can you confirm this works?

Gui: Fix navigation with overlays

---

src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp

@FEA-eng this fix the display mode for old files.
Files saved with the development branch after the addition of `Nodes (surface only)` and up to this fix, will be affected similarly, but for other saved modes. (Not very problematic since its only for the development branch).

Fem: Fix display modes order - fixes #13326

---

src/Mod/Import/CMakeLists.txt
src/Mod/Import/InitGui.py
src/Mod/Import/TestImportGui.py
src/Mod/Part/parttests/ColorPerFaceTest.py
src/Mod/PartDesign/TestPartDesignGui.py

This PR demonstrates the known regressions of the recently merged material branch:
* Changing the transparency after setting color per face will reset them
* The result of boolean operations or compound doesn't inherit the colour of its input objects
* If colour is set per face to a boolean operaton object then saving and restoring the file causes weird rendering behaviour because material binding is set to PER_PART but only a single colour is defined
* If a shape inside a part container has set colour per face then saving and restoring as STEP file causes weird rendering behaviour for the same reason
* Shape binder or datum objects don't show the correct default shape colour

Mod: Show regressions in shape colouring

---

src/Mod/TechDraw/Gui/QGIFace.cpp
src/Mod/TechDraw/Gui/QGIFace.h
src/Mod/TechDraw/Gui/QGSPage.cpp
src/Mod/TechDraw/Gui/QGSPage.h

This PR implements a fix for a regression reported in issue #13338.
- last worked in v0.20
- svg hatch tile field is not cropped on export to svg.  svg tiles are replaced by pixmap tiles for export.

[TD]file hatch clipping on svg export (fix #13338)

---

src/Gui/Command.cpp

This very likely fixes the crash reported at https://forum.freecad.org/viewtopic.php?t=86874

Gui: fix crash in PythonCommand::isChecked()

---

src/Mod/AddonManager/AddonManagerOptions.ui
src/Mod/AddonManager/manage_python_dependencies.py

Not used since:
760aaf4afe ("Addon Manager: Complete migration away from GitPython", 2024-01-27)
---
This can be backported too.

Addon Manager: Remove mentions of GitPython

---

src/App/Material.cpp
src/App/Material.h
src/App/MaterialPy.xml
src/App/MaterialPyImp.cpp
src/App/PropertyStandard.cpp
src/App/PropertyStandard.h
src/Gui/CommandFeat.cpp
src/Gui/ViewProviderGeoFeatureGroupExtension.cpp
src/Gui/ViewProviderGeometryObject.cpp
src/Gui/ViewProviderGroupExtension.cpp
src/Gui/ViewProviderOriginGroupExtension.cpp
src/Gui/ViewProviderSuppressibleExtension.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintPy.xml
src/Mod/Fem/Gui/ViewProviderFemMeshPy.xml
src/Mod/Mesh/Gui/ViewProvider.cpp
src/Mod/Mesh/Gui/ViewProviderMeshPy.xml
src/Mod/Part/Gui/Command.cpp
src/Mod/Part/Gui/CommandSimple.cpp
src/Mod/Part/Gui/DlgProjectionOnSurface.cpp
src/Mod/Part/Gui/ViewProviderAttachExtension.cpp
src/Mod/Part/Gui/ViewProviderExt.cpp
src/Mod/Part/Gui/ViewProviderExt.h
src/Mod/PartDesign/Gui/ViewProviderDatum.cpp
src/Mod/PartDesign/Gui/ViewProviderShapeBinder.cpp
src/Mod/PartDesign/Gui/ViewProviderShapeBinder.h

* Refactor MaterialPy to avoid code duplication
* Fix  PropertyMaterial::Save to create valid XML output
* Add PropertyMaterialList::resizeByOneIfNeeded to avoid code duplication
* Fix ViewProviderGeometryObject
1. Remove code that cannot be executed: inside the constructor it cannot ever happen that getObject() returns a valid object
2. In ViewProviderGeometryObject::handleChangedPropertyName call the method of the direct base class as otherwise this may break the mechanism in the future
3. Shape is a property of an extension module -> move its handling to ViewProviderPartExt
* Adjust parent class for Python wrappers
* Fix Std_RandomColor
* Fix Part_RefineShape and Part_Section
* Fix shape appearance of datum features, shape binder and shape sub-binder

Fix material issues

---

src/Base/Stream.h
tests/src/Base/CMakeLists.txt
tests/src/Base/Stream.cpp

This adds the matching output class for the StringInputStream class, to handle multi-line strings in the same way that LinkStage3 does (and therefore retain file compatibility with the ElementMap output).
~~In order to make the template specialization work I have to use a `std::string`, rather than a `std::string &`, and I'm not sure why yet. Anyone who knows template specialization better than I do please feel free to explain..~~

Toponaming/Base: Add ASCII stream output class

---

src/Mod/AddonManager/AddonManagerOptions.ui
src/Mod/AddonManager/manage_python_dependencies.py

Backport of:
6af79ebe00 ("Addon Manager: Remove mentions of GitPython", 2024-04-14)
---
As requested in [#13458](https://github.com/FreeCAD/FreeCAD/pull/13458#issuecomment-2054328013)

[backport] Addon Manager: Remove mentions of GitPython

---

src/Mod/TechDraw/App/DrawPage.cpp
src/Mod/TechDraw/App/DrawPage.h
src/Mod/TechDraw/App/DrawPagePy.xml
src/Mod/TechDraw/App/DrawPagePyImp.cpp
src/Mod/TechDraw/App/DrawView.cpp
src/Mod/TechDraw/App/DrawViewClip.cpp
src/Mod/TechDraw/App/DrawViewClip.h
src/Mod/TechDraw/App/DrawViewCollection.cpp
src/Mod/TechDraw/App/DrawViewCollection.h
src/Mod/TechDraw/Gui/Command.cpp
src/Mod/TechDraw/Gui/QGSPage.cpp
src/Mod/TechDraw/Gui/TaskLinkDim.cpp
src/Mod/TechDraw/Gui/ViewProviderPage.cpp
src/Mod/TechDraw/Gui/ViewProviderPageExtension.cpp
src/Mod/TechDraw/Gui/ViewProviderProjGroup.cpp
src/Mod/TechDraw/Gui/Workbench.cpp

Enable App::Links of views to work. So that it is more consistent with the rest of the application than current 'Share Views' (fixes #12374).
Remove Share View from toolbar.

TechDraw: Enable App::Links to work with view.

---

src/App/StringHasher.cpp
src/Mod/Part/App/TopoShapeExpansion.cpp

The corrects the string hasher output to use the `TextOutputStream` class to handle multi-line data. It also removes unneeded hasher reset code from `resetElementMap` that was breaking the synchronization between references and marks of string IDs.

Base/Toponaming: Correct string hasher output

---

src/Mod/TechDraw/Gui/QGSPage.cpp
src/Mod/TechDraw/Gui/QGSPage.h

This PR implements a fix for leader positioning on document restore as reported here: https://forum.freecad.org/viewtopic.php?t=86973

[TD]set Leader QGraphicsItem parentage on restore

---

src/Base/Parameter.cpp
tests/src/Base/Parameter.cpp

When restarting the application (e.g. after installing an addon) the application will be closed and a new instance will be launched. Now it can happen that the old instance is still busy writing the config files to disk while the new instance wants to read them in. At this time it's possible that a config file is in an invalid state so that the new instance will ignore it but then starts with a default configuration. Later when closing the new instance the config files will be overwritten and destroy the user's original settings.
By using a lock file this race condition will be avoided. It uses a timeout of 1 second that should be enough for the old instance to write the files to disk.

Base: Fix possible race condition when restarting the application

---

src/Mod/Material/App/Materials.cpp
src/Mod/Material/App/Materials.h
src/Mod/Material/Gui/BaseDelegate.cpp
src/Mod/Material/Gui/BaseDelegate.h
src/Mod/Material/Gui/ListDelegate.cpp
src/Mod/Material/Gui/ListEdit.cpp
src/Mod/Material/Gui/ListEdit.ui
src/Mod/Material/Gui/ListModel.cpp
src/Mod/Material/Gui/MaterialDelegate.cpp
src/Mod/Material/Gui/MaterialDelegate.h
src/Mod/Material/Gui/MaterialsEditor.cpp
src/Mod/Material/Gui/MaterialsEditor.h

There were several issues here, not just one. The following are fixed:
Incorrect display of Quantity items (NaN)
Editing and updating quantity items
Editing and updating items on the first row.
There are still issues with editing lists, but these were known issues at the time of initial merge. This has been split out into issue #13435
fixes #13020

Material: Problems editing Quantity properties

---

src/Mod/Part/App/TopoShapePyImp.cpp

Projection of complex BSpline curves (containing more than 16 segments) currently fails.
Example code below projects a BSpline curve with 17 segments on a plane shape.
Output projection is empty.
```
num = 18
alt = [0,1] * num
pts = [FreeCAD.Vector(i, alt[i], 0) for i in range(num)]
bsc = Part.BSplineCurve()
bsc.buildFromPoles(pts, False, 1)
edge = bsc.toShape()
rts = Part.RectangularTrimmedSurface(Part.Plane(), -50, 50, -50, 50)
plane_shape = rts.toShape()
proj = plane_shape.project([edge])
print(proj.Edges)
```
Related bug in Curves workbench : [#116](https://github.com/tomate44/CurvesWB/issues/116)

Part: fix shape projection of complex BSpline curves

---

src/Mod/OpenSCAD/OpenSCADFeatures.py

`onChanged()` triggers for the first time before all of the properties are loaded, so it can fail to compute properly at that stage, depending on the load order.
However, it's not necessary to compute geometry in `onChanged()` at all, because that's usually supposed to happen in `execute()` anyway. The solution here is to just not do `onChanged()` at all.
Fixes #13558

OpenSCAD: Fix CSG computing geometry too early

---

src/Mod/Draft/Resources/ui/preferences-draft.ui
src/Mod/Draft/Resources/ui/preferences-draftsnap.ui

* The MouseDelay pref does not belong in the "Grid and snapping" pref group.
* Max. value was missing. Without it the spinbox only goes to 100.
* The 3600 suggestion was removed from the tooltip as it is an unworkable value. But entering it is possible now.

Draft: Move MouseDelay pref to General group and set max value

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

The current constraints menu texts are not very consistent. Particularly the mix of adverbs (horizontally) and adjectives (symmetrical) is strange.

Sketcher: Make constraints menu texts more consistent

---

src/Mod/Sketcher/Gui/CommandCreateGeo.cpp

Create circle -> Create circle by center (compare arc and ellipse)
three points -> 3 points (compare ellipse)

Sketcher: Make geometry menu texts more consistent

---

src/Mod/Fem/App/FemMesh.cpp
src/Mod/Fem/App/FemMesh.h
src/Mod/Fem/App/FemMeshPy.xml
src/Mod/Fem/App/FemMeshPyImp.cpp
src/Mod/Fem/femmesh/meshtools.py
src/Mod/Fem/femsolver/calculix/write_mesh.py

This pull request extends the ABAQUS writer to select the element types available in CalculiX.
A set of "variants" is added to manage how to map mesh elements to specific solver elements.
See the Python `writeABAQUS` function for more details.
Additionally, the need to overwrite the .inp file to change element types is avoided. The second commit removes the now unused functions.
@FEA-eng your suggestions are welcome.

Fem: Add element types to ABAQUS writer

---

src/Tools/generateBase/generateTools.py

```py
src/Tools/generateBase/generateTools.py:144: SyntaxWarning: invalid escape sequence '\+'
rbe = re.compile("\+")
```

Tools: Resolve SyntaxWarning in generateTools.py

---

src/Mod/Draft/draftguitools/gui_trackers.py

The red, green, blue colors were hard-coded, now the FreeCAD-wide axes colors are used.
Relates to issue #12208

Draft: Use preference-stored colors for axes colors

---

src/Mod/Material/App/AppMaterial.cpp
src/Mod/Material/App/MaterialFilter.cpp
src/Mod/Material/App/MaterialFilter.h
src/Mod/Material/App/MaterialFilterPy.xml
src/Mod/Material/App/MaterialFilterPyImpl.cpp
src/Mod/Material/App/MaterialLibrary.cpp
src/Mod/Material/App/MaterialLibrary.h
src/Mod/Material/App/MaterialManager.cpp
src/Mod/Material/App/MaterialManager.h
src/Mod/Material/App/MaterialManagerPyImpl.cpp
src/Mod/Material/Gui/AppMatGui.cpp
src/Mod/Material/Gui/CMakeLists.txt
src/Mod/Material/Gui/DlgDisplayProperties.ui
src/Mod/Material/Gui/DlgDisplayPropertiesImp.cpp
src/Mod/Material/Gui/DlgDisplayPropertiesImp.h
src/Mod/Material/Gui/DlgSettingsMaterial.cpp
src/Mod/Material/Gui/DlgSettingsMaterial.ui
src/Mod/Material/Gui/MaterialTreeWidget.cpp
src/Mod/Material/Gui/MaterialTreeWidget.h
src/Mod/Material/Gui/MaterialTreeWidgetPy.xml
src/Mod/Material/Gui/MaterialTreeWidgetPyImpl.cpp

Improves the MaterialTreeWidget beyond minimum viable product.
- Filters can now be filter lists to allow a variety of filtering options.
- User preferences allow the inclusion/exclusion of favorites and recents.
- Widget state such as expansion, tree expansions, etc are saved and restored.
- show current appearancee material when editing.
- implements a python interface
Fixes #13421: always opens full tree

Material: MaterialTreeWidget usability enhancements

---

src/Mod/Start/StartMigrator.py

@chennes This fixes the Start migration script.
If you have a fresh configuration then `AutoloadModule` does not exist but it still is `StartWorkbench` so we should use this as default in case `AutoloadModule` is not found.
Everyone who compiled #13134 or later and did not see the new Start should manually set `ShowOnStartup` to true using Tools->Edit parameters at BaseApp/Preferences/Mod/Start.

Start: Fix migration script

---

src/Mod/Start/App/DisplayedFilesModel.cpp
src/Mod/Start/Gui/CMakeLists.txt
src/Mod/Start/Gui/FileCardDelegate.cpp
src/Mod/Start/Gui/FileCardDelegate.h
src/Mod/Start/Gui/FileCardView.cpp
src/Mod/Start/Gui/FlowLayout.cpp
src/Mod/Start/Gui/FlowLayout.h
src/Mod/Start/Gui/Manipulator.cpp
src/Mod/Start/Gui/PreCompiled.h
src/Mod/Start/Gui/StartView.cpp
src/Mod/Start/Gui/StartView.h

* Do not try to open empty file name
* Add command Start_Start only once. This fixes an error message that the command is duplicated. And it fixes a memory leak
* Make the new StartPage look more like the old one
* Use style sheets to give visual feedback about hovered or clicked buttons & labels

Start: Fix new start page

---

src/Mod/Start/App/AppStart.cpp
src/Mod/Start/CMakeLists.txt
src/Mod/Start/Gui/AppStartGui.cpp
src/Mod/Start/Gui/FileCardDelegate.cpp
src/Mod/Start/Gui/Manipulator.cpp
src/Mod/Start/Gui/StartView.cpp

Microsoft GSL is already packaged on Gentoo Linux, which I have compiled FreeCAD main with using this change. It is also available in Arch and Debian. I think this would make packaging FreeCAD easier in due course.

Start: Allow system Microsoft GSL to be used

---

src/Mod/Draft/draftutils/gui_utils.py

```
'PySide6.QtGui.QImage' object has no attribute 'byteCount'
load_texture: unable to load texture
```
A similar change was made before:
eced6aaed1 ("Qt5: 'int QImage::byteCount() const' is deprecated since Qt 5.10: Use sizeInBytes [-Wdeprecated-declarations]", 2020-06-08)

Draft: Fix QImage object has no attribute 'byteCount'

---

src/Mod/TechDraw/Gui/TaskProjGroup.cpp

Warning: result of comparison against a string literal is unspecified (use an explicit string comparison function instead) [-Wstring-compare]

TD: Fix compiler warning

---

src/Gui/3Dconnexion/navlib/NavlibCmds.cpp

Fixed an issue with invalidated iterators.

3Dconnexion Navlib: Fix for removeMarkups() function (fixes #13635)

---

src/Mod/PartDesign/App/FeatureSketchBased.cpp

PD: Fixes crash if sub-element name of reference axis is empty

---

src/Gui/DlgPreferences.ui

Stylesheets associated with controls were applied too aggressively by the Qt, causing issues with rendering tooltips etc. 
was:
This narrows styles to exact controls.

Fix issues with wrong color for preference page tooltips

---

src/Mod/Import/App/dxf/dxf.cpp

Import: C++ DXF importer wrongly scaled polyline bulges

---

src/Mod/Draft/importDXF.py

Otherwise old versions will still be used in the current FreeCAD session.

Draft: legacy DXF importer: downloaded libs should be reloaded

---

src/Gui/ViewProviderSuppressibleExtension.cpp

Update context menu with a toggle for suppress property with checkmark (checked when suppressed).
This is to be in line with active body or active object in the tree context menu:
@FEA-eng FYI
@FlachyJoe  FYI, maybe this could be like this for the frozen state.

UI: Update context menu with a toggle for suppress property

---

src/Mod/Assembly/Gui/Resources/icons/Assembly_SolveAssembly.svg

Previous icon was not rendered correctly because of overlay effects, just a grey blob:
This PR updates the logo without these effects to render correctly.

UI: update icon for assembly recompute

---

src/Mod/Sketcher/Gui/Workbench.cpp

Reorganize sketcher toolbars a little bit following initial efforts from @obelisk79 
See before after :

Sketcher: Small reorganization of toolbars

---

src/Mod/Fem/App/FemConstraint.cpp
src/Mod/Fem/App/FemConstraint.h
src/Mod/Fem/App/FemConstraintTransform.cpp

To be merged after https://github.com/FreeCAD/FreeCAD/pull/13274.
@FEA-eng could you test? The last commit fixes #7030 (initial scaling for very small and big objects).
Scaling is based on a characteristic length of the objects, basically the diagonal of the bounding box, so symbols scale linearly with the shapes.

Fem: Constraint symbol scaling based on shape size - fixes #7030

---

src/Mod/Fem/Gui/ViewProviderFemConstraint.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraint.h
src/Mod/Fem/Gui/ViewProviderFemConstraintContact.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintDisplacement.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintFixed.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintFluidBoundary.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintHeatflux.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintInitialTemperature.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintOnBoundary.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintPlaneRotation.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintPressure.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintSpring.cpp
src/Mod/Fem/Gui/ViewProviderFemConstraintTemperature.cpp
src/Mod/Fem/femviewprovider/view_constraint_tie.py

To be merged after #13274.
Removes unused constraint symbol view properties.
Now the color of the symbol is controlled by the ShapeAppearance property.

Fem: Remove unused view properties

---

src/Mod/Sketcher/Gui/DrawSketchHandler.cpp

Accessing the parameter manager inside ~CurveConverter() is undefined behaviour because it will be accessed after the main() function has been exited.
Fixes #13622

Sketcher: Fix possible crash inside ~CurveConverter()

---

src/Mod/TechDraw/Gui/Workbench.cpp

Remove the tool 'Project shape' from techdraw view toolbar.
Following discussion in https://github.com/FreeCAD/FreeCAD/issues/13347.
Before closing the issue I'll let @yorikvanhavre confirm if we need to add this tool in draft in a command group with Draft_Shape2DView. But it seems that TD tool is a duplicate of Draft_Shape2DView so it's probably not necessary.
The tool is still available in the menu.

TechDraw: remove 'Project Shape' from Techdraw toolbar

---

src/Mod/Fem/femobjects/base_fempythonobject.py
src/Mod/Fem/femobjects/constant_vacuumpermittivity.py
src/Mod/Fem/femobjects/constraint_bodyheatsource.py
src/Mod/Fem/femobjects/constraint_centrif.py
src/Mod/Fem/femobjects/constraint_currentdensity.py
src/Mod/Fem/femobjects/constraint_electrostaticpotential.py
src/Mod/Fem/femobjects/constraint_flowvelocity.py
src/Mod/Fem/femobjects/constraint_initialflowvelocity.py
src/Mod/Fem/femobjects/constraint_initialpressure.py
src/Mod/Fem/femobjects/constraint_magnetization.py
src/Mod/Fem/femobjects/constraint_selfweight.py
src/Mod/Fem/femobjects/element_fluid1D.py
src/Mod/Fem/femobjects/element_geometry1D.py
src/Mod/Fem/femobjects/element_geometry2D.py
src/Mod/Fem/femobjects/element_rotation1D.py
src/Mod/Fem/femobjects/material_common.py
src/Mod/Fem/femobjects/material_mechanicalnonlinear.py
src/Mod/Fem/femobjects/material_reinforced.py
src/Mod/Fem/femobjects/mesh_boundarylayer.py
src/Mod/Fem/femobjects/mesh_gmsh.py
src/Mod/Fem/femobjects/mesh_group.py
src/Mod/Fem/femobjects/mesh_region.py
src/Mod/Fem/femobjects/result_mechanical.py
src/Mod/Fem/femobjects/solver_ccxtools.py

Properties added in python with `obj.addProperty()` are removable by user throw the property editor. The status `LockDynamic` has to be set to prevent this.

FEM: prevent python added properties to be removed

---

src/Gui/PythonWrapper.cpp

Fixes errors like the following
```
error: cannot convert ‘Shiboken::Module::TypeInitStruct*’to ‘PyTypeObject**’ {aka ‘_typeobject**’} in assignment
| types = Shiboken::Module::getTypes(requiredModule);
|         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
|                                           |
|                   Shiboken::Module::TypeInitStruct*
```

Gui: Use Shiboken::Module::TypeInitStruct for module imports via Shiboken6

---

.github/workflows/sub_buildWindowsConda.yml

@adrianinsaval  @chennes 
This addresses an omission in the Windows Conda workflow that is present in the scripts: 
* [conda/setup-environment.cmd#L10](https://github.com/FreeCAD/FreeCAD/blob/main/conda/setup-environment.cmd#L10)
* [conda/setup-environment.sh#L12](https://github.com/FreeCAD/FreeCAD/blob/main/conda/setup-environment.sh#L12)
This should resolve the Windows Conda setup-related failures which are due to pruning library files that are being used by the active Python interpreter resulting in segfaults.

CI: Use --no-prune when installing the devenv on Windows to prevent errors.

---

src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_PageDefault.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ProjectionGroup.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Symbol.svg
src/Mod/TechDraw/Gui/Resources/icons/preferences-techdraw.svg

It is aimed to provide integrity by including the shape used in other workbenches in technical drawing icons. Accordingly, all icons containing technical drawings have been changed. If I missed anything, please let me know. Thank you from now.
This is not exactly an issue. It is a new detail to make it feel more compact. For this reason, no issue was created, a pull request was made directly.

Gui:Making Technical Drawing icons compatible with Part Design and Assembly icon

---

.github/workflows/sub_buildWindows.yml

@adrianinsaval @chennes 
CI on Windows fails occasionally due to PowerShell's `Move-Item` refusing to move `libpack` items into a directory that already exists.  As the destination directory is the `$(env.builddir)/bin`, this issue is frequently encountered.
Attempts to use `Copy-Item` and `New-Item` proved fruitless, so reverting to enabling the CMake option `FREECAD_COPY_LIBPACK_BIN_TO_BUILD` to ensure that copying the necessary `libpack` binaries is performed without error.

CI: Enable FREECAD_COPY_LIBPACK_BIN_TO_BUILD to address Windows CI failures.

---

tests/src/App/DocumentObserver.cpp

The 'normalized' test fails on Windows Conda, and the overall test class needs work. This simply disables the tests so that CI is useful in the interim.

Tests: Disable DocumentObserverTest pending refactor

---

src/Mod/Measure/Gui/Command.cpp

writing this as a normal message is completely unnecessay, I'm not sure writing something is necesary at all. With this at least it won't normally pollute the repor view

Measure: write init message to log instead

---

src/Mod/Draft/draftviewproviders/view_point.py

Without this mod there is an error when opening a V0.21 file with a Draft Point. As well as when creating a Draft Point in V0.22.

Draft: update Draft Point viewprovider to account for ShapeAppearance

---

src/Mod/Draft/draftguitools/gui_lines.py

The Draft line/polyline tool creates a temp object while drawing, for self-snapping, that should not appear in the tree.
Fixes #13700

Draft: Do not show temporary line object in tree

---

src/Mod/Arch/ArchCurtainWall.py

All Arch Objects have self.Type defined, add here for Arch Curtain Wall.
self.Type = "Axis"
self.Type = "AxisSystem"
self.Type = "Building"
self.Type = "BuildingPart"
self.Type = "Component"
self.Type = "Equipment"
self.Type = "Fence"
self.Type = "Floor"
self.Type = "Frame"
self.Type = "Grid"
self.Type = "MaterialContainer"
self.Type = "Panel"
self.Type = "Pipe"
self.Type = "Precast"
self.Type = "Profile"
self.Type = "Project"
self.Type = "Rebar"
self.Type = "Reference"
self.Type = "Roof"
self.Type = "Schedule"
self.Type = "SectionPlane"
self.Type = "Site"
self.Type = "Space"
self.Type = "Stairs"
self.Type = "Structure"
self.Type = "Truss"
self.Type = "Wall"
self.Type = "Window"
FC Forum Discussion - https://forum.freecad.org/viewtopic.php?t=87210

[ArchCurtainWall] add self.Type definition like other Arch Objects

---

src/Mod/TechDraw/App/Preferences.cpp
src/Mod/TechDraw/Templates/Default_Template_A4_Landscape.svg

This PR implements a fix for issue issue #13539.  In PR #13368 the default template was renamed.  This PR adds a new fallback template and adjusts the preference function to return the new default template file,
Additional discussion on forum: https://forum.freecad.org/viewtopic.php?t=87239&sid=49290882ca3ba68ee813770b981bb5ce

[TD]add fallback default template

---

src/Mod/Arch/ArchSchedule.py

Arch: Arch Schedule allow ^2 and ^3 in unit string

---

src/Base/PreCompiled.h
src/Base/Sequencer.cpp
src/Mod/Start/Gui/GeneralSettingsWidget.h
src/Mod/Start/Gui/ThemeSelectorWidget.cpp

Compilation fixes needed under Fedora 40
Justifications:
1. `std::find_if` and `std::reverse` are in `<algorithm>` but it was not explicitly included
2. The `3rdParty/GSL/include` usage in some GSL includes is inconsistent with other gsl includes
3.

Add <algorithm> include and remove explicit 3rdparty/GSL include reference

---

src/Mod/TechDraw/App/DrawTemplate.cpp
src/Mod/TechDraw/App/DrawTemplate.h

This pull request implements the requested splitting of "sheet" field in the "X / Y" form (X for page ordinal number, Y for total count of pages) into two separate values accessible through:
**page_number** autofill value, which determines the position of the new page in the collated set of all page names (identical to X in sheet field)
and
**page_count** autofill value, which delivers the total page count in given document (corresponds to Y in sheet field)
The change is rather minimal, thus I would not expect any fundamental issues, but some testing is definitely welcome. In case of any problems, please let me know.

[TechDraw] Issue #13661 - Split sheet autofill to separate values

---

src/Gui/PreferencePacks/Classic/post.FCMacro

In order for the "Classic" preference pack to work as expected, it must actually *remove* any value set for the Editor/Text, not just set it to a default value.

Themes: Explicitly remove Editor/Text setting in Classic

---

src/Mod/Arch/ArchMaterial.py
src/Mod/Material/importFCMat.py

Fixes #13821 by adapting the old material paths to the new scheme:
1. Update the materials filesystem path when reading them
2. Materials can now be in subfolders: traverse directories to read all materials
I'm aware of https://github.com/FreeCAD/FreeCAD/issues/13821#issuecomment-2094225362. I've addressed this as a quicker way to get back the Materials function before https://github.com/FreeCAD/FreeCAD/pull/13783 gets merged, which might take longer. The intention is certainly not to step on anyone's toes, so if this is already being worked on, or can be fixed in a better way, feel free to close this PR.

Arch: adapt materials to new Materials path scheme

---

src/Gui/Tree.cpp
src/Gui/Tree.h

The underlying problem is the method DocumentItem::updateItemSelection() where the selection is altered. This may cause the destruction and recreation of the DocumentObjectItems so that the passed pointer can become dangling.
The issue is fixed in two steps:
1. Add the method 'DocumentObjectItem *findItem(App::DocumentObject* obj, const std::string& subname) const' to safely re-access the item.
2. Add a boolean flag 'dirtyFlag' and the methods insertItem() and removeItem() to DocumentObjectData. This is needed to check when the iterator over the container becomes invalid.

PD: Fix crash when adding sketch to loft via tree view

---

src/Gui/BlenderNavigationStyle.cpp
src/Gui/CADNavigationStyle.cpp
src/Gui/GestureNavigationStyle.cpp
src/Gui/GestureNavigationStyle.h
src/Gui/InventorNavigationStyle.cpp
src/Gui/MayaGestureNavigationStyle.cpp
src/Gui/NavigationStyle.cpp
src/Gui/NavigationStyle.h
src/Gui/OpenCascadeNavigationStyle.cpp
src/Gui/OpenSCADNavigationStyle.cpp
src/Gui/RevitNavigationStyle.cpp
src/Gui/TinkerCADNavigationStyle.cpp

- Renamed the method `NavigationStyle::pan` to `NavigationStyle::setupPanningPlane` and use it in more places to reduce duplicate code
- Modified `NavigationStyle::lookAtPoint` to use the panning plane if it can't find a hit point with an object. This makes it possible to pan to any point using the Gesture and MayaGesture navigation style when pressing MMB or H
- Fixes a small issue where the animation is not triggered when there is no hit point (see video)
https://github.com/FreeCAD/FreeCAD/assets/14298143/faa6bca1-07c9-4598-857b-b89612b8e3ce

Gui: Improve lookAtPoint

---

src/Mod/Part/App/TopoShapeCompSolidPyImp.cpp
src/Mod/Part/App/TopoShapeCompoundPyImp.cpp
src/Mod/Part/App/TopoShapeShellPyImp.cpp

Creating a shape with Part.CompSolid(), Part.Compound() or Part.Shell() is a null shape. In order to allow to append sub-shapes with the add() method a valid shape must be created beforehand.
This fixes #13208

Part: Create CompSolid/Compound/Shell if null before adding a sub-shape

---

src/Mod/Fem/Gui/ViewProviderFemMesh.cpp
src/Mod/Fem/Gui/ViewProviderFemMesh.h
src/Mod/Fem/Gui/ViewProviderFemMeshPyImp.cpp

This fixes #6131 FemMesh coloring issue (fix #5815 requires one more step, since currently only first-order meshes are colored correctly).
With this pull request it is possible to save and restore custom colors on meshes, including transparency.
An enumeration property `ColorMode` is added to select the color mode. There are three options:
* `Overall`: The color of the object is determined entirely by `ShapeAppearance` property.
* `ByElement`: The mesh is colored by element based on the values of the `ElementColorArray` property.
* `ByNode`: The mesh is colored by node based on the values of the `NodeColorArray` property.
Properties `NodeColorArray` and `ElementColorArray` are added to set custom diffuse colors on meshes.
They behave as is next below:
* The array contains a single color: …

Fem: Save and restore custom colors of elements in mesh - fixes #6131

---

src/Mod/Fem/Gui/Resources/symbols/ConstraintHeatFlux.iv
src/Mod/Fem/Gui/Resources/symbols/ConstraintTemperature.iv

Increase the base size of the temperature and heat flux symbols. They are currently too small.
Change `SoMaterial` to `SoBaseColor` in .iv files so that the white cylinders of both symbols are affected by transparency.

Fem: Rescaling and transparency fix for heat constraint symbols

---

src/Gui/PythonWrapper.cpp
src/Gui/PythonWrapper.h
src/Gui/TaskView/TaskDialogPython.cpp
src/Mod/Arch/ArchAxis.py
src/Mod/Arch/ArchAxisSystem.py
src/Mod/Arch/ArchCommands.py
src/Mod/Arch/ArchComponent.py
src/Mod/Arch/ArchCutPlane.py
src/Mod/Arch/ArchRoof.py
src/Mod/Arch/ArchSectionPlane.py
src/Mod/Arch/ArchWindow.py
src/Mod/CAM/Path/Dressup/Gui/Boundary.py
src/Mod/CAM/Path/Dressup/Gui/Tags.py
src/Mod/CAM/Path/Op/Gui/Base.py
src/Mod/CAM/PathPythonGui/simple_edit_panel.py
src/Mod/Draft/DraftGui.py
src/Mod/Draft/drafttaskpanels/task_selectplane.py
src/Mod/Fem/femsolver/solver_taskpanel.py
src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py
src/Mod/Fem/femtaskpanels/task_result_mechanical.py
src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py
src/Mod/OpenSCAD/OpenSCADCommands.py
src/Mod/Part/AttachmentEditor/TaskAttachmentEditor.py
src/Mod/PartDesign/InvoluteGearFeature.py
src/Mod/PartDesign/SprocketFeature.py
src/Mod/PartDesign/WizardShaft/WizardShaft.py
src/Mod/TemplatePyMod/TaskPanel.py

Because PySide6 treats `enum`s and `QFlags` as `IntEnum`s and `IntFlag`s respectively I've added converters for Python PySide enums to C++, and due to this I've modified the requirements of task panel's `getStandardButtons` to return standard buttons without casting them to `int`. Fixes #13605 and part of #13303. Related to #6992.

Fixups with Qt6 enums

---

src/Gui/Workbench.cpp

Add `Std_Measure` command to tool menu, currently only present in toolbar.

UI: Add Std_Measure command to menu

---

src/Mod/Sketcher/Gui/CommandAlterGeometry.cpp
src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
src/Mod/Sketcher/Gui/SketcherSettings.ui
src/Mod/Sketcher/Gui/Workbench.cpp

Following the intention from @obelisk79 and @PaddleStroke and after some discussion on discord this PR continues the effort from https://github.com/FreeCAD/FreeCAD/pull/11717 and https://github.com/FreeCAD/FreeCAD/pull/13509
Update Sketcher toolbar UI:
- Group all create tools for arcs (arc of circle, ellipse, hyperbola, parabola)
- Group all create tools for conics (circles, ellipses)
- Group toggle driving and (de)activate constraints
- Make unified coincident tool the default (both individual tools available in preferences)
- Update arrangement of icons, consistent between toolbars and menu
Previously:
This PR:

Sketcher / UI: Update Sketcher Toolbars

---

src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h

Sketcher: Add a guard for not asking information of a point of a curve which doesn't exist

---

src/Mod/Help/Help.py
src/Mod/Help/dlgPreferencesHelp.ui

If PySide webenginewidgets is not available, the Help module now defaults to opening the doc in the desktop browser.
Fixes #13788

Help: Removes use of WebGui

---

src/Gui/MainWindow.cpp
src/Gui/MainWindow.h
src/Mod/Measure/App/Measurement.cpp
src/Mod/Measure/App/Measurement.h
src/Mod/Measure/App/MeasurementPy.xml
src/Mod/Measure/App/MeasurementPyImp.cpp
src/Mod/Measure/Gui/AppMeasureGui.cpp
src/Mod/Measure/Gui/CMakeLists.txt
src/Mod/Measure/Gui/QuickMeasure.cpp
src/Mod/Measure/Gui/QuickMeasure.h
src/Mod/Measure/Gui/QuickMeasurePy.xml
src/Mod/Measure/Gui/QuickMeasurePyImp.cpp
src/Mod/Measure/InitGui.py

Introduce quick measure. This adds a small label on the status bar on the right side that gives basic information about selection :
- lenght of edges
- Area of faces
- Volume of solids
- distances ...
Also as a small thing, it makes the text of the status bar label selectable so you can select it and copy it.
Fixes https://github.com/FreeCAD/FreeCAD/issues/12049

Core / Measure: Introduce QuickMeasure

---

src/Mod/Measure/App/Preferences.cpp
src/Mod/Measure/Gui/DlgPrefsMeasureAppearanceImp.ui

Default colors of the new unified measurement tool are hard to see on either light or dark themes:
This PR sets line and background color to a green which is visible on most themes. Contrast ratio between annotation text and text background is 13.65:1
After:

UI: Change default UMF colors for better contrast

---

src/Mod/Fem/Gui/Command.cpp
src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp

This fixes #13695 by resetting the color bar and setting the Data property of the new filter from the input filter.
To be consistent, the field displayed in the created filter is the same as the one used in the input filter.
With the second commit,  the input filter is hidden if a new filter is created.
@maxwxyz

Fem: Reset field color bar - fixes #13695

---

src/Gui/Document.cpp
src/Gui/Tree.cpp
src/Gui/Tree.h
src/Gui/ViewProviderDocumentObject.cpp
src/Gui/ViewProviderDocumentObject.h

This fixes #13690: Reordering top level objects destroys the Placement

Gui: Do not reset placement when reordering top-level objects

---

src/Gui/OverlayManager.cpp

Problem was caused by replacing the widget even if it should be invisible. 
Fixes: #13349

Gui: Remove redundant overlay header

---

src/Gui/PropertyView.cpp

To be consistent with the rest of "view" panels, change "Property View" to sentence case ("Property view")

Change property view panel title to sentence case

---

conda/conda-env.yaml
conda/environment.devenv.yml

I believe this fix will address the intermittent failures of Windows Conda CI.
The issue is that under Windows when the dynamic library the executable is linked against is deleted, there is a risk of a segmentation fault.  The `libmamba` library brings in `libzstd` to decompress files, and when it upgrades `zstd` from 1.5.5 to 1.5.6 this deletes the version it is linked to, sometimes while it is still using the library.
By pinning zstd to the latest version, we prevent the upgrade and the threat of deleting the library still in-use.
This issue does not affect Linux and macOS as those systems simply [`unlink()`](https://www.man7.org/linux/man-pages/man2/unlink.2.html) the deleted files upon deletion, and perform the actual deletion when the number of open file handles drops to 0. …

Conda: pin zstd==1.5.6 to fix Windows CI failures.

---

src/Gui/PythonWrapper.cpp

See https://github.com/FreeCAD/FreeCAD/pull/13611#issuecomment-2097126565

Gui: Fix PythonWrapper::toEnum() to also accept a Python int as argument

---

src/Mod/Draft/Resources/ui/preferences-dxf.ui

Draft: Add "legacy importer only" to DXF option

---

src/App/CMakeLists.txt
src/Base/CMakeLists.txt

The translations of the FreeCAD App & Base were not included in the build process. This patch fixes this issue.

include translations of the FreeCAD App & Base

---

src/Mod/Draft/drafttests/test_draftgeomutils.py

While working on PR #13683 an exception was raised in `get_extended_wire` that caused the test function `test_get_extended_wire` to fail.
However, due to the complexity of the test code it was impossible to figure out for which wire and parameters the function failed. After refactoring the code it was possible.

Draft: refactor TestDraftGeomUtils

---

src/Mod/Measure/App/Preferences.cpp
src/Mod/Measure/App/Preferences.h
src/Mod/Measure/Gui/DlgPrefsMeasureAppearanceImp.cpp
src/Mod/Measure/Gui/DlgPrefsMeasureAppearanceImp.ui

Remove leftover "Mirror" and "DistanceFactor" properties from measure preference dialog.
Closes #13805

[Measure] Remove unused properties from measure preferences

---

src/Gui/TaskMeasure.cpp

This PR does two things:
- Add some remaining label strings (Mode/Result/Close) for translation
- Improve the wording of the annotate button as described in #13734
- Improve the tooltip for the close button

MeasureGui: Improve measure task wording

---

src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp

This PR adds the value of measurements to the end of the label as proposed in #13707.
The value is placed after a colon character. When the user edits the label everything after the first occurrence of a colon character gets overwritten. The label is rewritten whenever the measurement is updated.

[MeasureGui] Add measurement value to label text

---

contrib/.vscode/scripts/VSCodeAutostartDebug.FCMacro
contrib/.vscode/scripts/WaitForDebugpy.py

Port 6000 has conflicts with some software.  Set the port to 39999, which unreserved by IANA and should make it far less likely to falsely report debug readiness.
@Pesc0

VSCode: Use port 39999 to test for debugger readiness.

---

src/App/Document.cpp
src/App/Document.h
src/App/DocumentPy.xml
src/App/DocumentPyImp.cpp
src/Gui/Tree.cpp
src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/CommandInsertLink.py
src/Mod/Assembly/UtilsAssembly.py

If a root object has a link pointing to it, then it is not returned by RootObjects.
Having a look at the function in cpp it seems to be because its checking if the inList is empty to determine if its a root object.
https://forum.freecad.org/viewtopic.php?p=756837#p756837

Core: Document getRootObjects : Fix bug of objects linked not returned.

---

src/Gui/Action.cpp
src/Gui/Action.h
src/Gui/ToolBarManager.cpp
src/Gui/ToolBarManager.h
src/Gui/WorkbenchSelector.cpp
src/Gui/WorkbenchSelector.h

Please don't squash - I keep the commit history meaningful :)
This changes back placement of the "more" button of the WB TabBar to be at the end, where it should be naturally placed. In order to ensure that it is always visible the control was reworked to show this button always after the tab bar widget which now is dynamically sized. This is behavior that is well known from browsers.
This commit also ensures that active workbench is always visible in the TabBar by adding additional temporary tab when necessary. This tab will automatically dissapear when not needed.
https://github.com/FreeCAD/FreeCAD/assets/747404/c13018f6-26f7-4f0a-a31e-19ab75a6004d
https://github.com/FreeCAD/FreeCAD/assets/747404/d1171ec4-5533-4d6b-a775-1d2e590370f5 …

Gui: Move more button to the end WB TabBar

---

src/Mod/Draft/Resources/ui/TaskPanel_SetStyle.ui
src/Mod/Draft/draftguitools/gui_setstyle.py
src/Mod/Draft/draftutils/params.py
src/Mod/Draft/draftutils/utils.py

Discussion: #13657.
To accommodate the new properties the task panel now has a tabbed interface. The properties on the Annotation tab have been reordered to match the related Preference page.
The order of the Shape appearance properties matches the related Preference page as well. I do not understand why these properties have have different order in the Properties view (if you expand the ShapeAppearance node). @davesrocketshop Do you know the reason for this?

Draft: Draft_SetStyle new Material handling

---

src/Mod/Measure/Gui/AppMeasureGui.cpp
src/Mod/Measure/Gui/QuickMeasure.cpp
src/Mod/Measure/Gui/QuickMeasure.h
src/Mod/Measure/InitGui.py

* Create QuickMeasure in C++ instead of Python to avoid that it will be garbage collected
* Handle exceptions in case of invalid selections
* Refactor QuickMeasure class
* Fix linter warnings

Measure: Fix quick measure

---

src/Gui/DlgParameterImp.cpp
src/Gui/DlgPropertyLink.cpp
src/Gui/DocumentModel.cpp
src/Gui/DocumentRecovery.cpp
src/Gui/GraphvizView.cpp
src/Gui/Language/Translator.cpp
src/Gui/Macro.cpp
src/Gui/NotificationArea.cpp
src/Gui/Splashscreen.cpp
src/Gui/StartupProcess.cpp
src/Gui/ToolBarManager.cpp
src/Gui/propertyeditor/PropertyItem.cpp
src/Mod/Drawing/Gui/Command.cpp
src/Mod/Material/App/Materials.cpp
src/Mod/Sketcher/Gui/EditDatumDialog.cpp
src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
src/Mod/Sketcher/Gui/TaskSketcherMessages.cpp
src/Mod/Start/Gui/FlowLayout.cpp
src/Mod/TechDraw/Gui/MDIViewPage.cpp
src/Tools/updatecrowdin.py
src/Tools/xmlformat/main.cpp

Nothing fancy, just some cleanup:
- `qAsConst` → `std::as_const`
- `QLocale::languageToString` instance → `QLocale::languageToString` static
- `QLocale::countryToString` instance → `QLocale::countryToString` static
- `QApplication::setActiveWindow` → `MainWindow::activateWindow`

Fix backwards-compatible Qt6 warnings

---

src/Mod/Sketcher/App/SketchObject.cpp

Fix #13910 by echoing existing code that avoids setting an element name on standalone geometry points

Toponaming: Fix point crash bug #13910

---

src/Mod/Draft/Resources/ui/TaskSelectPlane.ui
src/Mod/Draft/Resources/ui/preferences-draftsnap.ui

Fixes #13090
1. _"<kbd>Main lines every</kbd> nn" box_: change to "<kbd>Major lines every</kbd> nn lines". Essentially updating nomenclature from "main, normal" to "major, minor" lines, both in the input boxes and in the tooltips.
1. <kbd>Grid spacing</kbd>: change to <kbd>Line spacing</kbd>
1. <kbd>Grid size</kbd>: add a read-only label that shows the size in units of the resulting grid.
| Before | After |  
|---|---|
|![Before](https://github.com/FreeCAD/FreeCAD/assets/148809153/0e47d223-397f-438e-ade1-a2856b7b9bd7)|![After](https://github.com/FreeCAD/FreeCAD/assets/148809153/41140ac4-054f-476a-95f8-36d726c3bd84)|

Update grid size nomenclature

---

src/Mod/Fem/Gui/TaskFemConstraintDisplacement.ui
src/Mod/Fem/Gui/TaskFemConstraintFixed.ui
src/Mod/Fem/Gui/TaskFemConstraintForce.ui
src/Mod/Fem/Gui/TaskFemConstraintHeatflux.ui
src/Mod/Fem/Gui/TaskFemConstraintPressure.ui
src/Mod/Fem/Gui/TaskFemConstraintSpring.ui
src/Mod/Fem/Gui/TaskFemConstraintTemperature.ui

Continuation of #13921, a small step towards #11666
Changes the constraint task panel tips to suggest correct selection order and removes the misleading suggestions that multiple faces have to be selected.

FEM: Further improvement of the misleading constraint descriptions regarding the geometry selection

---

src/Gui/Stylesheets/Dark-modern.qss
src/Gui/Stylesheets/Dark.qss
src/Gui/Stylesheets/Darker.qss
src/Gui/Stylesheets/Light-modern.qss
src/Gui/Stylesheets/Light.qss

Small fix to issue in the menu that happens when a menu is selected but not active.
Now:
Then (ignore the branch lines and such)
@kadet1090 pointed me to this.

Small stylesheet fix to issue in the preference menu

---

src/Mod/Sketcher/Gui/DrawSketchControllableHandler.h
src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h

fixes #13999
@wwmayer I could not reproduce the crash on windows. Can you please check and feedback if this solves correctly the crash ?

Sketcher: fixes #13999

---

src/Mod/TechDraw/App/AppTechDrawPy.cpp

Solves issue #13728, 2nd attempt.
The function DrawDimHelper::makeExtentDim() now returns an object to Python, which properties can be used.
Macro to test:
`'''
- Select an existing view
- Start the macro
A horizontal Extent Dimension is created.
The view's scale, and the extent dimension's raw value is printed.
'''
import TechDraw
import TechDrawTools.TDToolsUtil as Utils
view = Utils.getSelView()
scale = view.getScale()
extentDim = TechDraw.makeExtentDim(view,[],0)
value = extentDim.getRawValue()
print(scale,value)
view.requestPaint()`

[TD]Expose DimExtent in Python (2nd attempt, replaces PR #13976)

---

src/Mod/TechDraw/Gui/PagePrinter.cpp
src/Mod/TechDraw/Gui/QGIFace.cpp
src/Mod/TechDraw/Gui/QGIViewPart.cpp
src/Mod/TechDraw/Gui/QGSPage.h

This PR implements a fix for issue #14027.   It reverts Svg hatch exporting to the method used in v021.
Additional forum discussions: https://forum.freecad.org/viewtopic.php?t=87667 and 
https://forum.freecad.org/viewtopic.php?t=86643

[TD]revert to v0.21 hatch exporting (fix #14027)

---

src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/App/GeometryMatcher.h

This PR implements a fix for issue #13992.   
Note that I do not get compile warnings here.  A difference in options, perhaps.
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Version: 0.22.0dev.37358 (Git)
Build type: debug
Branch: fixGeometryMatcherWarning
Hash: 3a0152b076dd7791c9724c286963d74b5814e24f
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk , OCC 7.7.1
Locale: English/Canada (en_CA)
Installed mods: 
* BOLTSFC 2022.11.5
* sheetmetal 0.2.63
* fasteners 0.4.56
* FreeCAD_Electric
* freecad.gears 1.0.0
* Curves 0.6.29
* Assembly4 0.50.9
* A2plus 0.4.64

[TD]fix #13992 - compile warnings

---

src/Mod/Draft/draftobjects/hatch.py

Edges longer than ca. 10m are considered 'crazy' in the TD Workbench. Hatch patterns are also checked. As a workaround some intermediate scaling is applied.
Addionally: `transformShape` instead of `transformGeometry`. The latter results in B-splines.

Draft: Draft_Hatch workaround for TD edge length limit

---

src/Mod/TechDraw/Gui/Resources/icons/arrow-ccw.svg
src/Mod/TechDraw/Gui/Resources/icons/arrow-cw.svg
src/Mod/TechDraw/Gui/Resources/icons/arrow-down.svg
src/Mod/TechDraw/Gui/Resources/icons/arrow-left.svg
src/Mod/TechDraw/Gui/Resources/icons/arrow-right.svg
src/Mod/TechDraw/Gui/Resources/icons/arrow-up.svg
src/Mod/TechDraw/Gui/Resources/icons/arrowdot.svg
src/Mod/TechDraw/Gui/Resources/icons/arrowfilled.svg
src/Mod/TechDraw/Gui/Resources/icons/arrowfork.svg
src/Mod/TechDraw/Gui/Resources/icons/arrownone.svg
src/Mod/TechDraw/Gui/Resources/icons/arrowopen.svg
src/Mod/TechDraw/Gui/Resources/icons/arrowopendot.svg
src/Mod/TechDraw/Gui/Resources/icons/arrowpyramid.svg
src/Mod/TechDraw/Gui/Resources/icons/arrowtick.svg
src/Mod/TechDraw/Gui/Resources/icons/bottomline.svg
src/Mod/TechDraw/Gui/Resources/icons/circular.svg
src/Mod/TechDraw/Gui/Resources/icons/continuous-line.svg
src/Mod/TechDraw/Gui/Resources/icons/dash-line.svg
src/Mod/TechDraw/Gui/Resources/icons/dashDot-line.svg
src/Mod/TechDraw/Gui/Resources/icons/dashDotDot-line.svg
src/Mod/TechDraw/Gui/Resources/icons/dot-line.svg
src/Mod/TechDraw/Gui/Resources/icons/hexagon.svg
src/Mod/TechDraw/Gui/Resources/icons/inspection.svg
src/Mod/TechDraw/Gui/Resources/icons/none.svg
src/Mod/TechDraw/Gui/Resources/icons/rectangle.svg
src/Mod/TechDraw/Gui/Resources/icons/square.svg
src/Mod/TechDraw/Gui/Resources/icons/triangle.svg

When starting the change in TechDraw, I first resized the slightly boring ones. The aspect ratios of the black icons have not changed, only the 48x48 area they are in has been changed and enlarged to fit it. And one or two more boring changes.

[Icons]Applying Icon Size Rules to TechDraw

---

src/Mod/AddonManager/NetworkManager.py

QtNetwork.QNetworkRequest has a small API change that is addressed in this commit.
Closes #14083.

AddonManager: Adapt to Qt6/PySide6

---

src/Gui/Icons/resource.qrc
src/Gui/Splashscreen.cpp
src/Gui/Splashscreen.h

Add a tab to the About FreeCAD dialog that embeds the contents of PRIVACY_POLICY.md. Third-party providers should ensure that they replace that file with their own policy when building. @sliptonic

Gui: Add privacy policy to About

---

src/Gui/Application.cpp
src/Gui/CommandStd.cpp

This adds a command that will reload currently active stylesheet - a must have for stylesheet developers.
It is not exposed in any default toolbar or menu - you have to add it manually.

Gui: Add Std_ReloadStyleSheet command

---

src/Gui/ViewProviderLink.cpp

Add 'Go To Linked Obj' to Tree context menu of Links.
Fixes #12167

Tree: Add 'Go To Linked Obj' to context menu of Links

---

src/Gui/CommandView.cpp
src/Gui/PreferencePackTemplates/Shortcuts.cfg
src/Gui/Workbench.cpp

This removes two leftover commands from part's measure system.

PartGui: Remove remaining measure "clear all" and "toggle delta" commands

---

src/Mod/Fem/App/FemVTKTools.cpp
src/Mod/Fem/feminout/importCcxFrdResults.py
src/Mod/Fem/feminout/importToolsFem.py
src/Mod/Fem/femobjects/result_mechanical.py
src/Mod/Fem/femsolver/calculix/write_step_output.py
src/Mod/Fem/femtest/data/calculix/thermomech_bimetall.inp

Fixes #12117.
The heat flux values are saved in the HeatFlux property of the FemResult object.
The visualization is accesible from the pipelines.
@FEA-eng

Fem: Load heat flux from CalculiX results - fixes #12117

---

src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensionsImp.cpp
src/Mod/TechDraw/Gui/Workbench.cpp

Make the smart dimension tool the default one, all current tools grouped under this.

TechDraw: make the dimension tool the default

---

src/Gui/SoDatumLabel.cpp

Fix #14049 
Fix #13557
arrow drawn CCW and text was not shown in every cases.

Gui: fix SoDatumLabel arrow and text disappear

---

src/Mod/TechDraw/Gui/QGIViewPart.cpp

This PR adds the ability to apply a format to hidden lines as requested here: https://forum.freecad.org/viewtopic.php?t=86774
Previously, hidden lines always used the line style set in preferences and ignored any format applied.

[TD]allow custom format for hidden lines

---

src/App/GeoFeature.cpp
src/App/GeoFeature.h
src/Gui/CommandView.cpp
src/Gui/Icons/align-to-selection.svg
src/Gui/Icons/resource.qrc
src/Gui/View3DInventor.cpp
src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h
src/Gui/Workbench.cpp
src/Mod/Part/App/PartFeature.cpp
src/Mod/Part/App/PartFeature.h

This PR introduces a first version for aligning the camera with the normal of a face or with the direction of an edge. I will continue improving its usability after this PR is merged and eventually implement all sub-features of #11234.
The code is inspired from realthunder's branch, however, I simplified it a bit.
@maxwxyz, can you provide the icon.
Currently, you can run the command by entering the line below in the Python console.
`Gui.SendMsgToActiveView("AlignToSelection")`

Align camera to faces and edges

---

src/Mod/Fem/femtools/checksanalysis.py

Since boundary conditions can be applied via rigid body constraint now, the static analysis check needs to be updated. I also made the message more straightforward and fixed 2 typos.

FEM: Update static analysis check for boundary conditions

---

src/Mod/PartDesign/App/Feature.cpp

fix #11212 
Suppressed is shown when compiled with FC_USE_TNP_FIX

PartDesign: hide Suppressed property with FC_USE_TNP_FIX flag

---

src/Mod/BIM/Resources/icons/Arch_Project_IFC.svg
src/Mod/BIM/Resources/icons/Arch_Reference.svg
src/Mod/BIM/Resources/icons/BIM_Classification.svg
src/Mod/BIM/Resources/icons/BIM_IfcElements.svg
src/Mod/BIM/Resources/icons/BIM_IfcProperties.svg
src/Mod/BIM/Resources/icons/BIM_IfcQuantities.svg
src/Mod/BIM/Resources/icons/BIM_Layers.svg
src/Mod/BIM/Resources/icons/BIM_Material.svg
src/Mod/BIM/Resources/icons/BIM_Phases.svg
src/Mod/BIM/Resources/icons/BIM_Preflight.svg
src/Mod/BIM/Resources/icons/BIM_Windows.svg
src/Mod/BIM/Resources/icons/IFC_document.svg
src/Mod/BIM/Resources/icons/Part_document.svg

Following [PR 13865](https://github.com/FreeCAD/FreeCAD/pull/13865) using a standard Document element for icons, here the BIM Workbench is updated to use the same element and improve overall consistency. SVG files have also been cleaned up a bit (remove unused resources and save as plain svg).
See before (top) and after (bottom) :
Other BIM icons will be updated in following PRs.

BIM : update icons with Document element

---

src/Mod/Assembly/UtilsAssembly.py

Cone offers the apex for JCS selection : Fixes https://github.com/FreeCAD/FreeCAD/issues/13958

Assembly: JCS selection: cones surfaces offers the cone's apex.

---

cMake/FreeCAD_Helpers/SetGlobalCompilerAndLinkerSettings.cmake
tests/CMakeLists.txt
tests/src/Mod/Material/App/TestMaterials.cpp
tests/src/Mod/Part/App/TopoShape.cpp
tests/src/Mod/Part/App/TopoShapeExpansion.cpp

Enable the Topological Naming Problem mitigation code. This is an interim step: eventually the flag will be removed, along with the old code.
Fixes #8432.

Toponaming: Enable FC_USE_TNP_FIX code

---

src/Mod/PartDesign/App/FeatureGroove.cpp
src/Mod/PartDesign/App/FeatureHelix.cpp
src/Mod/PartDesign/App/FeatureHole.cpp
src/Mod/PartDesign/App/FeatureRevolution.cpp
src/Mod/PartDesign/App/FeatureSketchBased.cpp
src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py

Note moved, unchanged getVerifiedFace.  Aligning source position with LS3 for easier comparison.

Toponaming: Cleanup verified face calls

---

src/Mod/BIM/bimcommands/BimProjectManager.py

after BIM merge to ARCH WB
can't  open BIM Project Setup
due to some import missing and error
fix the translate() missing
and
BuildingType Error
to make this manager dialog be able to open

[BIM]  fix BIM Project Manager import error

---

src/Mod/BIM/Resources/ui/preferences-ifc-export.ui
src/Mod/BIM/importers/exportIFC.py
src/Mod/BIM/nativeifc/ifc_tools.py

Following a discussion on https://community.osarch.org/discussion/comment/20540#Comment_20540 , it appears what we are currently doing at FreeCAD, that is, aggregating groups inside a building structure, is illegal.
With this PR, groups nested inside building structures will now by default be exported as IfcElementAssemblies. 
However, since we (okay, I) firmly believe groups nested inside building structures are a good idea, and so far most BIM apps have no problems with it, there is an option under Edit -> Preferences -> I/O -> IFC export to disable this and get back to the previous behaviour (groups exported as IfcGroups and aggregated). This option is clearly marked as non-standard compliant.

BIM: Allow to export groups as assemblies

---

src/Mod/TechDraw/App/DimensionAutoCorrect.cpp
src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/App/Geometry.cpp
src/Mod/TechDraw/App/Geometry.h
src/Mod/TechDraw/App/GeometryMatcher.cpp

This PR implements fixes for some of the problems identified in issue #14054.  In particular it addresses the handling of older documents by the reference auto-correct process and a flaw in the code which treats BSplines as Circles.

[TD]Fix Loading Dims (partial fixes #14054) 

---

src/Mod/BIM/bimcommands/BimCutPlane.py

Restored the original copyright header of the Arch_CutPlane command that was rewritten by mistake

BIM: Restored original copyright header of ArchCutPlane command

---

src/Mod/BIM/ArchCurtainWall.py

- Add Overridges property to let user to select particular edge(s) in a Sketch / ArchSketch to use create the shape of the Arch Curtain Wall (instead of using all edges by default).
ENHANCEMENT by External 'ArchSketch' Add-on:
- GUI 'Edit Curtain Wall' Tool is provided in external Add-on ('SketchArch') to let users to select the edges interactively.
- The selection of edges is 'Toponaming-Tolerant' if ArchSketch is used in Base (and SketchArch Add-on is installed).
- Warning : Not 'Toponaming-Tolerant' if just Sketch is used.
- Property is ignored if Base ArchSketch provided the selected edges.
Forum Discussion:
- https://forum.freecad.org/viewtopic.php?p=756554#p756554 [ ArchSketch ] - Curtain Wall, Slab, ArchWall etc. on Same ArchSketch

[ArchCurtainWall] Add OverrideEdges & ArchSketch Support

---

src/Mod/BIM/bimcommands/BimTutorial.py

UI file is now in a resources file.
Translate function was not defined.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=87830

BIM: Fix BIM tutorial issues

---

src/Mod/Part/App/FeaturePartFuse.cpp

This pull request add a minor modification. It allows to speed up the multi_fuse operation by setting the parallel flag given by OpenCascade to true.

Adding parallel running to the multi_fuse operation

---

src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/MDIViewPage.cpp
src/Mod/TechDraw/Gui/MDIViewPage.h
src/Mod/TechDraw/Gui/TaskDimRepair.cpp

This PR implements a fix for one of the items raised in #14051.  Specifically it ensures that the selection state is left clean for the next operation.

[TD]Fix selection issue in DimensionRepair(partial fix #14051)

---

src/Mod/TechDraw/App/LineGenerator.h

Addresses the missing #include <map> from LineGenerator.cpp.
This was prompted by a compiler error on Linux systems utilizing gcc14.
Also reported in this issue: https://github.com/FreeCAD/FreeCAD/issues/14245

Resolves missing TechDraw include for GCC14 compilers

---

src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
src/Mod/TechDraw/Gui/DrawGuiUtil.h
src/Mod/TechDraw/Gui/QGIPrimPath.cpp
src/Mod/TechDraw/Gui/TaskDimRepair.cpp
src/Mod/TechDraw/Gui/TaskDimRepair.h

This PR implements a fix for issue #14052 where greedy selection was not supported
if the view was not the first item in the selection.
This PR also include a fix for issue #14054 where the dimension type was being 
changed incorrectly.

[TD]Allow greedy selection for complex selection (fix #14052, #14054)

---

src/Mod/Fem/Gui/Resources/symbols/ConstraintRigidBody.iv

Fixes #14133
@FEA-eng The sticks are a little thinner and the node a little bigger.

Fem: Increase size of reference node symbol in rigid body constraint - fixes #14133

---

CONTRIBUTING.md

Adding a mandatory presentation for UI changing pull requests.
> If a PR changes the user interface (UI), the body of the text MUST include a presentation of these UI changes, preferably with screenshots of the previous and revised state.

Contributing: add details for UI changes

---

src/App/Application.cpp
src/Base/Parameter.cpp
src/Base/Parameter.h
src/Gui/StartupProcess.cpp
src/Gui/StartupProcess.h

This PR includes #13845 but adds locking to reading a config file as well, as proposed in [this comment](https://github.com/FreeCAD/FreeCAD/pull/13845#issuecomment-2096090023).

Core: Add read lock to fix for possible race conditions reading/writing config files

---

src/Mod/TechDraw/App/DrawViewSection.cpp
src/Mod/TechDraw/App/DrawViewSection.h
src/Mod/TechDraw/Gui/QGIView.cpp
src/Mod/TechDraw/Gui/QGIView.h
src/Mod/TechDraw/Gui/QGIViewDimension.cpp
src/Mod/TechDraw/Gui/QGIViewDimension.h
src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp
src/Mod/TechDraw/Gui/Workbench.cpp

1 - Enable snapping views to align them vertically/horizontally.
When you drag a view, if you get near aligning them, it will snap them into position.
Making the tool TechDraw_ExtensionPositionSectionView obsolete.
Removes the tool TechDraw_ExtensionPositionSectionView from toolbar.
2 - Enable snapping of dimensions to align them
- snap text to the center
- Snap dimension to other dimension positions.
- Removes TechDraw_ExtensionPosChainDimensionGroup
- Removes TechDraw_ExtensionCascadeDimensionGroup
Video demo 
https://github.com/FreeCAD/FreeCAD/assets/19984177/8b8e67c4-a4f9-41be-b2b8-9fd14d585c49

TechDraw: Introduce snapping

---

src/Mod/AddonManager/AddonManager.py
src/Mod/AddonManager/package_list.py

This PR supports the functionality to start the Addon Manager for a specific addon. 
The current implementation tries to be as unobtrusive to the original code as possible. This is accomplished by introducing a new preference that captures a search string and filter based on whether this preference is set. It also emits signals for when the Addon Manager is finished, allowing a client addon to reset the preferences to their original values.
For a client addon to open the Addon Manager, it can do the following (as taken from the Ondsel Lens addon):
``` python
class UpdateManager:
def storePreferences(self):
pref = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Addons")
self.autocheck = pref.GetBool("AutoCheck")
self.statusSelection = pref.GetInt("StatusSelection") …
```

AddonManager: Support selecting addon on start

---

src/Mod/Material/App/Materials.cpp
src/Mod/Material/App/Materials.h
src/Mod/Material/App/Model.h
src/Mod/Material/Gui/CMakeLists.txt
src/Mod/Material/Gui/Command.cpp
src/Mod/Material/Gui/DlgInspectAppearance.cpp
src/Mod/Material/Gui/DlgInspectAppearance.h
src/Mod/Material/Gui/DlgInspectAppearance.ui
src/Mod/Material/Gui/DlgInspectMaterial.cpp
src/Mod/Material/Gui/DlgInspectMaterial.h
src/Mod/Material/Gui/DlgInspectMaterial.ui
src/Mod/Material/Gui/Workbench.cpp
src/Mod/Part/Gui/Workbench.cpp
src/Mod/PartDesign/Gui/Workbench.cpp
tests/src/Mod/Material/App/TestMaterialProperties.cpp

Dialogs to view the Appearance and Material properties of an object
These inspectors are intended to be used when debugging Appearance and Material issues in a model.
The Appearance inspector displays the appearance properties of an object. This will be more useful once PR 13792 is merged which migrates parts to use ShapeAppearance instead of DiffuseColor. This shows each of the appearance properties per face for the object.
The Material inspector shows the material, models, and properties assigned to a model. It displays useful debugging information such as the UUID and file paths associated with eacch of the items. This is useful when finding and resolving model conflicts.

Material: Appearance and Material inspectors

---

src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h
src/Gui/ViewProvider.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.h

Problem solved here is that, in the way the "Select all" command is handled, it always acts at document level selecting all objects in the tree.
It leads to strange behavior when editing a sketch and pressing "Ctrl+A": nothing in the sketch is selected, but all document objects are (behind the scenes) which triggers unexpected tool activation and so on.
This PR solves this is a flexible manner by implementing a mechanism that will, if a view provider is currently in edit mode, let it decide if it wants to handle the command or not.
In the actual PR, the VPSketch just gets the command and tells the viewer it is handled there, so that strange behavior is gone.
It is let for future work to implement the "Select All" logic in the VPSketch.

Gui: offer possibility to editing view provider to handle "Select All" command

---

conda/environment.devenv.yml

Qt WebEngine is no longer a necessary dependency.

Conda: Remove Qt WebEngine.

---

src/Mod/Fem/Gui/Command.cpp

Corrects rigid body constraint tooltip and changes its name in the menu/toolbar from _Constraint rigid body_ to _Rigid body constraint_ (to follow the naming changes done at the beginning of the development cycle).

FEM: Correct rigid body constraint tooltip and name

---

src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp
src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp
src/Mod/Measure/Gui/ViewProviderMeasureBase.h
src/Mod/Measure/Gui/ViewProviderMeasureDistance.cpp

Currently the initial positioning of UMF measurements is static which often feels out of place as described in #13808.
This PR improves the behavior by:
- scaling the distance/angle measurement offsets with openinventors "getWorldToScreenScale" factor
- offsetting the annotation label text in screenspace and converting it to a 3d location

[MeasureGui] Make initial measurement placement scale with viewport zoom

---

src/Mod/PartDesign/WizardShaft/WizardShaft.svg

Mentioned here: 
https://forum.freecad.org/viewtopic.php?t=87898
Shaft wizard is not consistent in colors / style with other Part Design icons.
@FreeCAD/design-working-group  FYI
Previously:
PR:

UI: Adjust shaft wizard icon to match other Part Design icons

---

src/Gui/View3DSettings.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Handle the situation where the user has a hard crash in Edit Mode by resetting parameter on entering 3D view.
Fixes https://github.com/FreeCAD/FreeCAD/issues/13989
With PR applied to default material:
versus current situation of being unable to determine where the sketch geometry is against the object behind.

[Sketcher] Change HeadlightIntensity entering and exiting Edit Mode

---

src/Mod/Start/Gui/StartView.cpp

On systems with legacy monitors the display might be not as large as needed to display completely the start page. In that case the user is forced to use the keyboard to scroll horizontally the start page.

add horizontal scrollbar to start page

---

src/Mod/Fem/App/CMakeLists.txt

On my system only OpenMP 2.0 was present and the build was [failing](https://github.com/FreeCAD/FreeCAD/issues/12586#issuecomment-2041047115).
In that case enforcing OpenMP version allowed to skip FEM linking and avoids build errors.

Enforce OpenMP version

---

src/Mod/PartDesign/Gui/Workbench.cpp
src/Mod/Sketcher/Gui/Workbench.cpp

Based on discussion in: https://github.com/FreeCAD/FreeCAD/pull/14118 and https://github.com/FreeCAD/FreeCAD/pull/13833
- Replaces toolbar command group for lines (grouped Polyline + Line) with separate commands
- Adds PartDesign_ShapeBinder back to the menu
If possible, polyline can be improved for feature freeze, otherwise maybe a setting (like the new dimension tool).
Shapebinder will not be fully integrated until feature freeze.
@berberic2 Is that change ok for you? So I'd rather leave the CommmandGroup in for working with it, the toolbar are restored.
@FreeCAD/design-working-group FYI

UI: Revert UI command change in Sketcher and PartDesign

---

src/Mod/Draft/draftobjects/layer.py
src/Mod/Draft/draftviewproviders/view_layer.py

Discussion: #13657.
This PR adds  the ShapeAppearance view property to Draft Layers.
The DefaultShapeColor is used for the DiffuseColor of the ShapeAppearance material. Other material properties are not based on the preferences when a layer is created.
The old ShapeColor and Transparency properties remain (ShapeColor as a hidden property) and are kept in synch with the ShapeAppearance. This is consistent with how ShapeAppearance is implemented in Core.
The gui_layers.py and make_layer.py files do not have to be changed. They manipulate the vobj via the mentioned old properties.

Draft: Draft_Layer new Material handling

---

src/Mod/Draft/draftobjects/shape2dview.py

Fixes #14312.
The `new _get_shapes` function could return the original object shape. This caused a problem if `sh.reverse()` executed.
Note that the file in the linked issue does not produce the error as it does not contain a shape with a negative volume.

Draft: fix _get_shapes in shape2dview.py

---

src/Mod/CAM/Gui/DlgSettingsPathColor.ui

fix a sizing issue with the CAM color dialog.
The problem only appears with OpenDark and similar themes.  
Before.  The labels are clipped even if the window is resised.
After.  The labels size correctly.

fix color preference dialog

---

src/Mod/Material/App/MaterialLoader.cpp

The YAML library is unable to open files with UTF8 paths
fixes #14352

Materials: Correct issue with UTF8 path

---

src/Mod/BIM/bimcommands/BimSetup.py

Setting the WP to "Auto" is confusing for beginners. That is why this was changed to "Top" in the Draft WB. The same should happen in the BIM WB.

BIM: change default for defaultWP to Top

---

src/Mod/BIM/bimcommands/BimPreflight.py
src/Mod/BIM/importers/importSHP.py

Leaving urls outside translated strings prevents translations from being updated on url change.
[Python F-strings](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals) suggested by @furgo16

BIM: Move urls outside translated strings

---

src/Mod/BIM/bimcommands/BimViews.py

when I compile in Qt6
it appears the error below:
```
10:37:43  Traceback (most recent call last):
10:37:43    File "/home/***/Documents/Project/FreeCAD/build/Mod/BIM/bimcommands/BimViews.py", line 172, in update
10:37:43      if vm.isVisible() and (vm.tree.state() != vm.tree.EditingState):
10:37:43                                                ^^^^^^^^^^^^^^^^^^^^
10:37:43  AttributeError: 'PySide6.QtWidgets.QTreeWidget' object has no attribute 'EditingState'
```
in PySide6
EditingState is under `PySide6.QtWidgets.QtreeWidget.State.EditingState`
so just  need to change to vm.tree.State.EditingState
and I think this is also work at PySide2 when compile in Qt5  as well

[BIM] fix BimView Qt6 Support

---

src/Mod/BIM/ArchStructure.py
src/Mod/BIM/InitGui.py
src/Mod/BIM/bimcommands/BimBeam.py
src/Mod/BIM/bimcommands/BimColumn.py
src/Mod/BIM/bimcommands/BimCommon.py
src/Mod/BIM/bimcommands/BimCompound.py
src/Mod/BIM/bimcommands/BimCut.py
src/Mod/BIM/bimcommands/BimExtrude.py
src/Mod/BIM/bimcommands/BimFuse.py
src/Mod/BIM/bimcommands/BimLayers.py
src/Mod/BIM/bimcommands/BimMaterial.py
src/Mod/BIM/bimcommands/BimOffset.py
src/Mod/BIM/bimcommands/BimPreflight.py
src/Mod/BIM/bimcommands/BimRewire.py
src/Mod/BIM/bimcommands/BimSimpleCopy.py
src/Mod/BIM/bimcommands/BimWindows.py

This makes BIM commands inactive when the active view is not a 3D view (most were already, some were missing)

BIM: Fixed IsActive of BIM commands

---

src/Mod/BIM/InitGui.py

Following up on #13783, this is a rework of the toolbars and menus in the BIM workbench.
Basically:
* All Arch and all BIM tools are there
* Menus and toolbars are reorganized into broad categories, each with as few as possible submenus:
* 2D/Drafting (Draft tools)
* 3D/BIM (BIM tools + some generic 3D tools)
* Modify (contains generic move/rotate/copy, 2D modif tools and 3D modif tools)
* Manage (these are all from BIM)
* Utils (kind of dirty at the moment, all the tools that didn't fit in the other categories, the idea is basically that everything is there for 1.0. That menu needs further discussion)
* The toolbars are split into smaller toolbars so users can turn on/off parts of them to use less space. It is then possible to have either a "large toolbars layout", a "minimal toolbars …

BIM: Reworked menus and toolbars

---

src/Mod/Measure/App/Measurement.cpp

If a Base::Exception is thrown in Measurement::getShape() then it's handled by the catch(...) handler and converted into a Base::RuntimeError. This behaviour hides the original Base::Exception.
Example:
Selecting a datum plane raises the error 'Measurement: Unknown error retrieving shape' because the original Base::ValueError isn't forwarded.

Measure: Fix exception handling

---

src/Gui/CMakeLists.txt
src/Gui/CommandStructure.cpp
src/Gui/DlgAddPropertyVarSet.cpp
src/Gui/DlgAddPropertyVarSet.h
src/Gui/DlgAddPropertyVarSet.ui
src/Gui/ViewProviderVarSet.cpp
src/Gui/ViewProviderVarSet.h
src/Gui/Workbench.cpp
src/Mod/PartDesign/App/Body.cpp
src/Mod/PartDesign/Gui/ViewProviderBody.cpp

This PR is an alternative solution to the problem discussed in #13038. I still believe PR #13112 would be very valuable but it is a large PR and I think it would benefit from a broader discussion. This PR is much smaller and only focused on variable sets. It allows you to easily add properties to variable sets.
It provides a GUI command to create variable sets and it presents you with a dialog to add properties. It allows you to also add the value of the property immediately once the type has been established. It makes use of the editors available in core, so for lengths and floats you get the familiar input box with expression support and for links you get the familiar dialog to select an object.
If a Part is active, the variable set will be created inside the part and adding new …

Core: Add properties to variable sets

---

src/Gui/DlgExpressionInput.cpp
src/Gui/DlgExpressionInput.h
src/Gui/DlgExpressionInput.ui

This allows users to directly add properties to variable sets from within the expression input dialog improving a workflow for parameterized design.
Closes #13139
A video that shows the functionality:
https://github.com/FreeCAD/FreeCAD/assets/5336482/5e0b6b8e-97a4-498f-bdc9-ce649089c55a

Gui: Add VarSet support to expression dialog

---

src/Mod/PartDesign/App/Body.cpp
src/Mod/PartDesign/App/Body.h
src/Mod/PartDesign/App/FeatureMultiTransform.cpp
src/Mod/PartDesign/App/FeatureMultiTransform.h
src/Mod/PartDesign/App/FeatureScaled.cpp
src/Mod/PartDesign/App/FeatureScaled.h
src/Mod/PartDesign/App/FeatureTransformed.cpp
src/Mod/PartDesign/App/FeatureTransformed.h
src/Mod/PartDesign/Gui/Command.cpp
src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp
src/Mod/PartDesign/Gui/TaskTransformedParameters.h
src/Mod/PartDesign/Gui/TaskTransformedParameters.ui

This allows applying the patterns to the whole base feature's shape. 
This makes it easier to design symmetric Bodies, especially if the feature list contains non-additive/subtractive features.
As mentioned in the issue, I think this requires some help on the UI side to make this new mode discoverable for the user.
Does someone have an idea for this?
This would resolve the following issues:
- fixes #12489
- fixes #11947
- fixes #8439
- fixes #5678
This is based on my refactoring PRs, so I will keep it a draft until those are merged.

Add a new mode to PD patterns that will transform the base feature's shape instead of the tool shapes

---

src/Gui/NaviCube.cpp
src/Gui/Workbench.cpp

Adding the new command to align the view to the selection (currently only available in the toolbar) to the menu and context menu.

UI: Add Std_AlignToSelevtion to menu bar and context menu

---

src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/QGVPage.cpp

- Fixes https://github.com/FreeCAD/FreeCAD/issues/14328 : initial selection handling
- fix D shortcut that was wrongly assigned to radius.
- fix radius/diameter command names (it was always named 'radius')
- Remove some useless leftover comments

TechDraw: Smart dimension: Fix initial selection handling.

---

src/Mod/TechDraw/Gui/QGIViewDimension.cpp
src/Mod/TechDraw/Gui/QGIViewDimension.h

Fixes https://github.com/FreeCAD/FreeCAD/issues/14325 
Fixes https://github.com/FreeCAD/FreeCAD/issues/14333
1 - Dimensions of different types (Distance / DistanceX) not snapping: Now if the labels are parallel then it snaps.
2 - Center snapping not accurately on center : There was a problem in how the center of the label was defined, which did not take into account the angle of the label.
3 - For small dimensions the snapping zone is small : Instead of using a % of the dimension, we use a fraction of the cascade spacing variable which is similar to the font size.

TechDraw: Fixes snapping bugs.

---

src/Gui/TaskCSysDragger.cpp

Changing the transform tool icon to use the Std_TransformManip icon instead of a checkmark and changing the heading from Increment to Transform.
Previously:
PR:

UI: Change transform tool task box icon and heading

---

src/Mod/Tux/InitGui.py

This PR uses the Tux addon (which in any case is already used to tweak stuff in Draft/Arch/BIM...) to detect a situation where both the BIM addon and the built-in BIM workbench are present.
If such a situation is met, the BIM addon path is renamed from UserAppDataDir/Mod/BIM to UserAppDataDir/Mod/BIM021 and the user gets a warning to restart FreeCAD.
Fixes #14072

Tux: Detect and fix BIM addon

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/JointObject.py

If the user adds limits to joints (length or angle both) with bad values (ie min > max), then they just failed silently. Instead we fix them.
Fixes https://github.com/Ondsel-Development/FreeCAD/issues/61

Assembly: Fix bad limits automatically

---

src/Gui/Tree.cpp

The visibility of link elements must be set with setElementVisible. This will first try to use that API otherwise it falls back to setting the Visibility property.
This seems to work, but I'm not sure if this is correct. I don't understand when to use `setElementVisible` and what the interactions are with sub elements and such. 
Fixes #14064

Fix visibility icon for link elements

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.h

This ensures that color of sketch gets updated with user changing preferences and after loading files. PointColor and LineColor should be hidden, marked as transient and removed from existing documents. This should still work for older versions of FreeCAD as it will load defaults.
To ensure backward compatiblity migration strategy is to compute default value for this property based on the color. If it is non-white (the default value in FreeCAD) we assume that the change was inentional and that it should be kept as-is turning automatic coloring off. In other cases it is enabled by default.
While the Auto Color property is enabled the properties to set the color are hidden.
File without explicit colors:
File with explicit colors:
Fixes: #13980

Gui: Update sketcher colors after file load

---

src/Mod/Part/Gui/DlgExportHeaderStep.ui
src/Mod/Part/Gui/DlgExportStep.ui
src/Mod/Part/Gui/DlgImportStep.ui
src/Mod/Part/Gui/DlgPartImportStepImp.cpp
src/Mod/Part/Gui/DlgSettingsGeneral.cpp

Currently it translated into some languages
src/Mod/Part/Gui/Resources/translations/
```
./Part_ru.ts-2554-      <translation>ШАГ</translation>
./Part_ru.ts-3134-      <translation>ШАГ</translation>
./Part_ru.ts-3142-      <translation>ШАГ</translation>
./Part_id.ts-2631-      <translation>LANGKAH</translation>
./Part_id.ts-2664-      <translation>LANGKAH</translation>
./Part_id.ts-3245-      <translation>LANGKAH</translation>
./Part_id.ts-3253-      <translation>LANGKAH</translation>
./Part_id.ts-3504-      <translation>LANGKAH</translation>
./Part_vi.ts-2660-      <translation>BƯỚC</translation>
./Part_vi.ts-2693-      <translation>BƯỚC</translation>
./Part_vi.ts-3271-      <translation>BƯỚC</translation>
./Part_vi.ts-3279-      <translation>BƯỚC</translation>
./Part_vi.ts-3530- …
```

Part: Not needed translation for STEP

---

src/Mod/Part/App/AttachExtension.cpp
src/Mod/Part/App/AttachExtension.h
tests/src/Mod/Part/App/AttachExtension.cpp

This is added to conveniently change the attacher type of a Part object.
Hint: A new property is used to avoid to break project files when opening it with an older version.
See also forum thread: https://forum.freecad.org/viewtopic.php?t=87891

Part: Add AttacherEngine of type PropertyEnumeration

---

src/Mod/Part/App/TopoShapeExpansion.cpp
src/Mod/PartDesign/App/FeatureExtrude.cpp
src/Mod/PartDesign/App/FeaturePad.cpp
src/Mod/PartDesign/App/FeaturePocket.cpp
src/Mod/PartDesign/App/FeatureSketchBased.cpp
src/Mod/PartDesign/App/FeatureSketchBased.h

#11135 fix attempt
Allow a shape or multiple faces to be selected as UpToFace.
Revert no longer useful #11136 as the shape can be selected.
NB: the Pad and Pocket task dialogs need refactoring and issue #11192 prevent to edit the faces list from GUI so the only way to set the UpToFace property with shape or multiple faces is python:
```python
App.ActiveDocument.Pad001.UpToFace = [(App.ActiveDocument.Pad,["Face1","Face2"])]
```

PD: Extrude to face or shape

---

src/Gui/CMakeLists.txt
src/Gui/So3DAnnotation.cpp
src/Gui/So3DAnnotation.h
src/Gui/SoFCCSysDragger.cpp
src/Gui/SoFCCSysDragger.h
src/Gui/SoFCDB.cpp

Transform gizmo (dragger) used SoAnnotation which disables GL_DEPTH_TEST resulting in rendering elements in wrong order. This PR introduces new coin node: So3DAnnotation that delays rendering and clears depth buffer before drawing which results in proper order of elements. As this destroys information in the depth buffer it is crucial to run this action after the scene is rendered.
If it causes problems I'll try to either delay it further or preserve depth buffer in FBO - but this will be slower.
Before:
After:
Fixes: #14302 
ping: 
- @qewer33 - FYI
- @PaddleStroke - I heard that you struggle with the same thing in assembly workbench. I'm not sure how to expose this to python - so I could use your help here.

Gui: Fix rendering order of transorm gizmo

---

src/Gui/Tree.cpp

> [!WARNING]  
> I don't have ability to build FreeCAD with Qt5 right now. So I need someone to test if this solution works with Qt5. To test it use patched OpenLight: https://github.com/obelisk79/OpenTheme/pull/30
>
> You can checkout it from your `~/.local/share/FreeCAD/Mod/OpenTheme` directory using:
> ```
> git fetch origin pull/30/head:qt6-workaround
> git checkout qt6-workaround
> ```
This aims to fix rendering of tree view items in Qt6. While I don't belive that this is a good way to fix this, I am worried that it is the only way to do it.
**BC BREAK:** This change introduces artificial QTreeView widget that can be targeted using QSS and can be used in the delegate for painting background of items. `QTreeView::item` would now be used to render background for the whole row, while …

Gui: Fix document tree background rendering with overlay (Qt6)

---

src/Mod/Part/App/FeatureExtrusion.cpp
src/Mod/Part/App/FeatureExtrusion.h

This is added to conveniently change the face maker type of an extrusion object.
Hint: A new property is used to avoid to break project files when opening it with an older version.

Part: Add FaceMakerMode of type PropertyEnumeration

---

src/App/ComplexGeoData.h

Toponaming: defend against uninitialized elementMap in getElementHistory

---

src/Mod/PartDesign/App/FeatureDressUp.cpp
src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp

This should solve many "invalid edge" warnings on chamfers and fillets.

Toponaming fix dress up shadow subs

---

src/Mod/Start/Gui/GeneralSettingsWidget.cpp

It's not allowed to store the C string of a tmp. byte array as the pointer will become dangling and causes undefined behaviour

StartGui: Fix crash in GeneralSettingsWidget::onNavigationStyleChanged

---

src/Mod/BIM/ArchWall.py

To avoid confusion, attributes e.g. Align, Width, Offset, Override (Align/ Width/ Offset) would be disabled, if Base object is ArchSketch which provided the above information
FC Forum Discussion :  https://forum.freecad.org/viewtopic.php?t=87721&start=30#p763761

[ArchWall] Disable Input (ReadyOny) if Base (ArchSketch) Provided

---

src/Mod/BIM/bimcommands/BimWPCommands.py

Update the BIM WP commands to use the new Draft code. This ensures correct GUI behavior.
This also fixes the BIM_SetWPSide command which would align to the left side instead of the right side. The right side matches the behavior of Draft_SelectPlane and also the icon of the command.

BIM: Update WP commands

---

src/App/FreeCADInit.py

When executing FreeCAD in interactive console-mode, the init-script tries to load readline for a better input experience and enables tab-completion. This code is neither executed when running in GUI mode, nor when the console is not itneractive, e.g. when reading a script from stdin.

App: Add readline-based tab-completion

---

src/Gui/TaskMeasure.cpp

This PR allows the measure tool to measure linked objects which wasn't possible before as described in #14332.

MeasureGui: Don't resolve selection objects in TaskMeasure

---

src/Gui/PreferencePages/DlgSettingsGeneral.cpp
src/Gui/StartupProcess.cpp
src/Gui/StartupProcess.h

This adds `Preferences/General/QtStyle` string user parameter that allows theme developers to set proper Qt style.

Gui: Add QtStyle user parameter

---

src/App/Application.cpp

Importing FreeCAD as a module in a normal Python interpreter (e.g. /usr/bin/python3) stopped working with Python 3.12 (but works normally with Python 3.11).
When executing `import FreeCAD as App`, the Python 3.12 interpreter crashes with
"Fatal Python error: PyImport_AppendInittab: PyImport_AppendInittab() may not be called after Py_Initialize()".
I have tested this fix on Debian bookworm with Python 3.11 and Arch Linux with Python 3.12.

Core: fix import of FreeCAD in a Python 3.12 interpreter

---

src/Mod/AddonManager/manage_python_dependencies.py

...this is more likely to occur since the BIM workbench integration and new users installing ifcOpenShell by pip before running AddonManager.
Error raised:
```
13:59:19  Traceback (most recent call last):
13:59:19    File "/home/username/freecad-daily-build/Mod/AddonManager/AddonManager.py", line 420, in do_next_startup_phase
13:59:19      phase_runner()
13:59:19    File "/home/username/freecad-daily-build/Mod/AddonManager/AddonManager.py", line 661, in check_python_updates
13:59:19      PythonPackageManager.migrate_old_am_installations()  # Migrate 0.20 to 0.21
13:59:19    File "/home/username/freecad-daily-build/Mod/AddonManager/manage_python_dependencies.py", line 393, in migrate_old_am_installations
13:59:19      os.makedirs(new_directory)
13:59:19    File "/usr/lib/python3.10/os.py", …
```

[AddonManager] Fix Error on Existing Python Additional Packages Folder

---

src/Mod/Sketcher/Gui/TaskSketcherElements.cpp

Selecting lots of elements in the sketcher slows down quadratically because we were redrawing the entire element list widget for each element.
https://github.com/FreeCAD/FreeCAD/issues/14446

Speedup sketcher item selection

---

src/Main/MainGui.cpp

Changing the splashscreen text color from an arbitrary light blue to the new FreeCAD primary blue according to the guideline.
I'm sure there will be a new splash screen image for 1.0 but this changes just the text color so we won't forget. If needed, it can be changed with a different image if it should not fit the chosen image.
@FreeCAD/design-working-group FYI
New:

UI: Change splashscreen text color to the new FreeCAD blue

---

src/Mod/Part/App/Attacher.cpp
src/Mod/Part/App/Attacher.h
src/Mod/Part/Gui/AttacherTexts.cpp
tests/src/Mod/Part/App/Attacher.cpp

Add ParallelPlane attachment/map mode
It results in an attachment similar to ObjectXY but with the XY plane translated to pass through a selected vertex.
It is most useful to place sketches: pick a plane (XY, XZ, YZ) or another sketch then select a vertex to automatically translate the sketch in its Z/normal-direction. In contrast to the Translate attachment/map mode it does not move the origin in 2D/Sketcher.
Here's a screenshot:
Selected (in green) is the vertex (Sketch:Vertex3) to translate the TestSketch (also green) which contains and X and Y for visual reference. Note how X and Y are lifted from the origin XY plane.
And another screenshot showing attaching against YZ and the same vertex:
"Why is this needed? Can't you achieve the same with:"
"Translate attachment/map mode": No, …

Part: Add ParallelPlane attachment mode

---

conda/environment.devenv.yml

@oursland I think #13345 fixed windows compilation with latest pcl so we can update

Unpin pcl on conda devenv and update to use libboost-devel

---

src/Gui/DlgMaterialPropertiesImp.cpp
src/Gui/DlgMaterialPropertiesImp.h
src/Mod/Material/Gui/DlgDisplayPropertiesImp.cpp
src/Mod/Material/Gui/DlgDisplayPropertiesImp.h
src/Mod/Part/Gui/TaskFaceAppearances.cpp
src/Mod/Part/Gui/TaskFaceAppearances.h

Because a PropertyMaterialList property is used now it makes no sense any more to pass a list of view providers to the dialog as it's impossible to set the material at a certain index. Therefore the dialog has been simplified and setting the material property must be done by the calling instance.

Gui: Refactor DlgMaterialPropertiesImp

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/Gui/Resources/preferences/Assembly.ui
src/Mod/Assembly/Preferences.py

Adds a preference to enable the Ondsel Solver debug.
When this preference is set to true, the solver will create "runPreDrag.asmt" and "dragging.log" files in the default directory of std::ofstream (on windows it is the desktop).
This will help users give bug reports when solving goes wrong, such as this https://github.com/FreeCAD/FreeCAD/issues/14185

Assembly: Add preference to enable debug files of dragging

---

src/Base/MatrixPyImp.cpp

Base: Fix compiler warning

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/App/AssemblyObject.h

This adds a validation step before applying the placement returned by the solver to avoid applying bad solutions.
This first PR implement the mechanism and add a first validation : That the grounded objects do not move. If the solver tries to move a grounded object, then the solution will be ignored and the dragging continue.
Further tests can be added later. For example we could test if the joints are still correctly aligned (for fixed/slider/revolute/cylindrical).

Assembly: Add validation step during dragging to ignore bad solves

---

src/Mod/PartDesign/Gui/ViewProviderExtrude.cpp

Fixes build problems that occurred after merge of #14433 that was using DiffuseColor color that was removed after CI was done and did not conflict because it was use in a new file.
Fixes: #14599

Gui: Fix use of no longer existing DiffuseColor property
