FreeCAD/FreeCAD

src/Mod/Part/App/PrimitiveFeature.cpp
src/Mod/Part/App/PrimitiveFeature.h

Add readonly length properties to part helix and spiral

---

src/Gui/ApplicationPy.cpp
src/Gui/Inventor/MarkerBitmaps.cpp

as requested by @Roy-043 for use in Draft Wb see https://github.com/FreeCAD/FreeCAD/pull/11524#issuecomment-1826307225

[Gui] Add HourGlass markers including larger sizes

---

src/Mod/Draft/Resources/ui/preferences-draft.ui
src/Mod/Draft/Resources/ui/preferences-draftinterface.ui
src/Mod/Draft/Resources/ui/preferences-draftsnap.ui
src/Mod/Draft/Resources/ui/preferences-drafttexts.ui
src/Mod/Draft/Resources/ui/preferences-draftvisual.ui

* Removed DefaultAnnoDisplayMode. This will become a fine-tuning preference.
* Removed HatchPatternResolution as it was not used.
* Added DefaultAnnoLineColor and DefaultAnnoLineWidth. These will be implemented in other parts of the Draft code in later PRs.

Draft: Revised preference ui files

---

src/Mod/Part/App/PartFeatures.cpp
src/Mod/Part/Gui/TaskSweep.ui

Default freenet to true for sweep to fix rendering bug

---

cMake/FreeCAD_Helpers/ConfigureCMakeVariables.cmake
cMake/FreeCAD_Helpers/SetupSalomeSMESH.cmake
src/App/PropertyExpressionEngine.h
src/Base/Builder3D.h

https://github.com/msys2/MINGW-packages/issues/19175#issuecomment-1833783752

MSYS: fix CMake configure and build for MinGW

---

src/Mod/Start/Gui/Workbench.cpp

for runtime error see https://github.com/FreeCAD/FreeCAD/pull/11513#issuecomment-1837300296
Only triggered when StartPage is closed for instance when the user has the preference closeStart set to True.

[Start] Fix minor regression from #11513

---

src/Gui/SoDatumLabel.cpp
src/Gui/SoDatumLabel.h
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h
src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

This PR improve the rendering of the (2lines) angle and radius SoDatumLabel

[Sketcher] Improve angle & radius constraint rendering

---

src/Mod/Fem/App/FemMesh.cpp
src/Mod/Mesh/App/MeshPyImp.cpp
src/Mod/Points/App/PointsGrid.cpp
src/Mod/Points/App/Properties.cpp
src/Mod/ReverseEngineering/App/AppReverseEngineering.cpp

clean unused code
remove unnecessary casts

casts clean

---

src/Mod/TechDraw/Gui/QGIRichAnno.cpp
src/Mod/TechDraw/Gui/QGIRichAnno.h

This PR contains  backports of 2 fixes to SVG export.

[TD]backport of SVG Export Fixes

---

src/Mod/TechDraw/CMakeLists.txt

See discussion https://forum.freecad.org/viewtopic.php?t=83220

[Techdraw] Add missing Line Styles to CMakeLists.txt

---

src/Mod/TechDraw/App/LineGenerator.cpp
src/Mod/TechDraw/App/LineGenerator.h
src/Mod/TechDraw/App/Preferences.cpp
src/Mod/TechDraw/App/Preferences.h
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.h
src/Mod/TechDraw/Gui/TaskComplexSection.cpp
src/Mod/TechDraw/Gui/TaskComplexSection.h
src/Mod/TechDraw/Gui/TaskComplexSection.ui
src/Mod/TechDraw/Gui/TaskSectionView.cpp
src/Mod/TechDraw/Gui/TaskSectionView.h
src/Mod/TechDraw/Gui/TaskSectionView.ui

This PR implements fixes for 2 issues:
Section scale not equal to base view scale reported here: https://forum.freecad.org/viewtopic.php?t=82762, and
#11634 preference drop downs for line styles

[TD]Section scale and preference drop downs

---

src/Mod/TechDraw/TechDrawTools/CommandAxoLengthDimension.py
src/Mod/TechDraw/TechDrawTools/TDToolsUtil.py

Improve the TechDraw_AxoLengthDimension tool. If the created dimension measures parallel to the 3D x-, y- or z-axis, the real (3D) value is calculated automatically and inserted into the dimension label as text.

[TD] Improve TechDraw_AxoLengthDimension tool

---

src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp

Add missing initialization of MirrorPlane on non sketch objects (fixes #11571)

---

src/Mod/TechDraw/App/DrawProjectSplit.cpp

When the scrubEdges() receives a single edge as input, we must not invoke the OCC BOPAlgo_Builder, otherwise the Perform() call raises "BOPAlgo_AlertTooFewArguments" error.

[TechDraw] Fix scrubEdges() OCC error with single input edge

---

src/Mod/Draft/DraftGeomUtils.py
src/Mod/Draft/draftfunctions/downgrade.py
src/Mod/Draft/draftfunctions/move.py
src/Mod/Draft/draftfunctions/offset.py
src/Mod/Draft/draftfunctions/rotate.py
src/Mod/Draft/draftfunctions/scale.py
src/Mod/Draft/draftfunctions/svg.py
src/Mod/Draft/draftfunctions/svgshapes.py
src/Mod/Draft/draftfunctions/upgrade.py
src/Mod/Draft/draftgeoutils/general.py
src/Mod/Draft/draftmake/make_clone.py
src/Mod/Draft/draftmake/make_label.py
src/Mod/Draft/draftmake/make_layer.py
src/Mod/Draft/draftobjects/bezcurve.py
src/Mod/Draft/draftobjects/bspline.py
src/Mod/Draft/draftobjects/circle.py
src/Mod/Draft/draftobjects/ellipse.py
src/Mod/Draft/draftobjects/polygon.py
src/Mod/Draft/draftobjects/rectangle.py
src/Mod/Draft/draftobjects/wire.py
src/Mod/Draft/draftutils/params.py

Draft: implement new get_param functions (step 1)

---

src/Mod/Draft/draftguitools/gui_annotationstyleeditor.py
src/Mod/Draft/draftguitools/gui_arcs.py
src/Mod/Draft/draftguitools/gui_base_original.py
src/Mod/Draft/draftguitools/gui_beziers.py
src/Mod/Draft/draftguitools/gui_edit.py
src/Mod/Draft/draftguitools/gui_ellipses.py
src/Mod/Draft/draftguitools/gui_groups.py
src/Mod/Draft/draftguitools/gui_hatch.py
src/Mod/Draft/draftguitools/gui_labels.py
src/Mod/Draft/draftguitools/gui_layers.py
src/Mod/Draft/draftguitools/gui_lines.py
src/Mod/Draft/draftguitools/gui_offset.py
src/Mod/Draft/draftguitools/gui_points.py
src/Mod/Draft/draftguitools/gui_polygons.py
src/Mod/Draft/draftguitools/gui_rectangles.py
src/Mod/Draft/draftguitools/gui_selectplane.py
src/Mod/Draft/draftguitools/gui_setstyle.py
src/Mod/Draft/draftguitools/gui_snapper.py
src/Mod/Draft/draftguitools/gui_tool_utils.py
src/Mod/Draft/draftguitools/gui_trackers.py
src/Mod/Draft/draftutils/params.py

Draft: implement new get_param functions (step 2)

---

src/Mod/Draft/drafttaskpanels/task_circulararray.py
src/Mod/Draft/drafttaskpanels/task_orthoarray.py
src/Mod/Draft/drafttaskpanels/task_polararray.py
src/Mod/Draft/drafttaskpanels/task_scale.py
src/Mod/Draft/drafttaskpanels/task_shapestring.py
src/Mod/Draft/draftutils/gui_utils.py
src/Mod/Draft/draftutils/init_draft_statusbar.py
src/Mod/Draft/draftutils/messages.py
src/Mod/Draft/draftutils/params.py
src/Mod/Draft/draftutils/utils.py
src/Mod/Draft/draftviewproviders/view_base.py
src/Mod/Draft/draftviewproviders/view_dimension.py
src/Mod/Draft/draftviewproviders/view_draft_annotation.py
src/Mod/Draft/draftviewproviders/view_label.py
src/Mod/Draft/draftviewproviders/view_layer.py
src/Mod/Draft/draftviewproviders/view_text.py
src/Mod/Draft/draftviewproviders/view_wire.py
src/Mod/Draft/draftviewproviders/view_wpproxy.py

Draft: implement new get_param functions (step 3)

---

src/Mod/Draft/DraftGui.py
src/Mod/Draft/DraftVecUtils.py
src/Mod/Draft/WorkingPlane.py
src/Mod/Draft/draftutils/params.py
src/Mod/Draft/importDWG.py
src/Mod/Draft/importDXF.py
src/Mod/Draft/importOCA.py
src/Mod/Draft/importSVG.py

Draft: implement new get_param functions (step 4)

---

src/Mod/Import/App/dxf/dxf.cpp

Code by @tmksw
Fixes https://github.com/FreeCAD/FreeCAD/issues/11394
Relates to https://github.com/FreeCAD/FreeCAD/issues/6461
Fixes https://github.com/FreeCAD/FreeCAD/pull/11697

Fix DXF importer wrongly prioritizes the MEASUREMENT variable

---

src/Mod/Draft/WorkingPlane.py
src/Mod/Draft/draftguitools/gui_labels.py
src/Mod/Draft/draftutils/params.py

Draft: implement new get_param functions (step 5)

---

src/Mod/TechDraw/CMakeLists.txt

See discussion https://forum.freecad.org/viewtopic.php?t=83554

[TechDraw] Correct typo in folder name

---

src/Mod/Part/App/GeometryDoubleExtensionPy.xml

Docs: minor tweek to GeometryDoubleExtensionPy.xml

---

src/Gui/ViewProviderGroupExtension.cpp

Gui: fix group visibility toggle

---

src/App/MaterialPyImp.cpp
src/Gui/Camera.cpp
src/Mod/TechDraw/App/Preferences.cpp

Removed unnecessary float casts

---

src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h

Fixing one line offset in sketcher by removing the use of BRepOffsetAPI_MakeOffsetFix and using OCC BRepOffsetAPI_MakeOffset directly.
Fixes #11706
Discussion : https://forum.freecad.org/viewtopic.php?p=725100#p725100

[Sketcher] Fix offset of single line

---

src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp

Fix a display error with point to line distance constraint
https://github.com/FreeCAD/FreeCAD/pull/9166#issuecomment-1864351095

Sketcher: Fix Point to Line Distance

---

src/Mod/TechDraw/App/LandmarkDimension.cpp
src/Mod/TechDraw/App/ShapeExtractor.cpp
src/Mod/TechDraw/App/ShapeExtractor.h
src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/DimensionValidators.cpp
src/Mod/TechDraw/Gui/DimensionValidators.h

This PR implements a fix for #11783 and a fix for a problem with edge-vertex dimensions reported here: https://forum.freecad.org/viewtopic.php?t=83632

[TD]Fix Landmark Dimension #11783

---

src/Mod/TechDraw/App/ShapeExtractor.cpp

This PR implements a fix for a problem with Std_Link objects as sources for views as reported here: https://forum.freecad.org/viewtopic.php?t=83679
The link placement property was being applied twice.

[TD]fix double transform for linked objects

---

src/Mod/TechDraw/CMakeLists.txt
src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
src/Mod/TechDraw/Gui/Workbench.cpp
src/Mod/TechDraw/TechDrawTools/CommandPositionSectionView.py
src/Mod/TechDraw/TechDrawTools/TDToolsUtil.py
src/Mod/TechDraw/TechDrawTools/__init__.py

The new version of the PositionSectionView tool allows to position section views generated by inclined section cuts.
Discussion see: https://forum.freecad.org/viewtopic.php?t=66952
Documentation in wiki, see Usage 2: https://wiki.freecad.org/TechDraw_ExtensionPositionSectionView
Also two issues were solved:
- The LineStyle issue (@WandererFan: discussed a few days ago)
- The MenuBar issue, discussed in: https://github.com/FreeCAD/FreeCAD/pull/11655#issuecomment-1856052966

[TD] New extended version of PositionSectionView tool.

---

src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui

... to correctly indicate that it only applies to new objects.

[TechDraw] italicize leaderline auto-horizontal preference checkbox

---

src/Mod/TechDraw/App/DrawComplexSection.cpp
src/Mod/TechDraw/Gui/QGIViewPart.cpp

This PR implements a fix for a problem encounter by complex section during document restore as reported here: https://forum.freecad.org/viewtopic.php?t=83733&sid=deb8b00bbf538e7154315ed016619b70

[TD]Fix fail during restore

---

package/fedora/freecad.spec

Update Fedora COPR freecad.spec from master to main branch

---

src/Mod/TechDraw/App/AppTechDrawPy.cpp
src/Mod/TechDraw/App/Cosmetic.cpp
src/Mod/TechDraw/App/Cosmetic.h
src/Mod/TechDraw/App/CosmeticVertex.cpp
src/Mod/TechDraw/App/CosmeticVertex.h
src/Mod/TechDraw/App/DrawDimHelper.cpp
src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
src/Mod/TechDraw/Gui/CommandAnnotate.cpp
src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
src/Mod/TechDraw/Gui/TaskCosVertex.cpp
src/Mod/TechDraw/TechDrawTools/TaskAddOffsetVertex.py

This PR implements a fix for positioning of Cosmetic Vertices on rotated views as reported here: https://forum.freecad.org/viewtopic.php?t=83725

[TD]Cosmetic vertex rotation

---

src/Mod/TechDraw/App/Cosmetic.h
src/Mod/TechDraw/App/LineGenerator.cpp
src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
src/Mod/TechDraw/Gui/TaskSelectLineAttributes.cpp
src/Mod/TechDraw/Gui/TaskSelectLineAttributes.h
src/Mod/TechDraw/Gui/TaskSelectLineAttributes.ui

This PR modifies ExtensionDims and ExtensionPack methods to use standard line types and line formatting.

[TD]Use standard lines and format in extensions

---

src/App/DocumentPy.xml

Also some minor spelling fixes.
Related to #11754.

App: improve tooltip for ActiveObject

---

src/Base/RotationPyImp.cpp

Fix Rotation constructor error msg

---

src/Mod/TechDraw/Gui/TaskCosVertex.cpp

This PR corrects a problem where cosmetic vertices were unscaled twice before saving.

[TD]fix duplicate unscale of CosmeticVertex

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/11904
@chennes

Sketcher_dimension : Fixes ctrl-z crash

---

src/Base/Reader.h

Fixes https://github.com/FreeCAD/FreeCAD/issues/11809

Build: Fix visibility of fields in Reader.h to be compiled with GCC 13

---

src/App/Expression.cpp
src/App/Expression.h
tests/src/App/Expression.cpp

Resolve #11825 - no automatic quantity conversion:` App::anyToQuantity`

Resolve #11825 - no automatic quantity conversion: App::anyToQuantity

---

src/Mod/TechDraw/App/DrawViewDetail.cpp
src/Mod/TechDraw/App/DrawViewPart.cpp
src/Mod/TechDraw/App/ShapeExtractor.cpp

This PR implements a fix for #11945.  Additional detail in this forum topic: https://forum.freecad.org/viewtopic.php?t=84213
The PR restores the previous detail view algorithm which seems to better handle geometry error in the source object.

[TD]Revert detail to piecewise algo (fix #11945)

---

src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/Gui/QGISVGTemplate.cpp

This PR corrects a problem with icons for Dimensions reported here: https://forum.freecad.org/viewtopic.php?p=731836#p731836

[TD]fix Dimension icons

---

src/Mod/PartDesign/Gui/TaskPipeParameters.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/11961
Author of https://github.com/FreeCAD/FreeCAD/pull/11357 agrees to backing out of PR, see https://github.com/FreeCAD/FreeCAD/issues/11961#issuecomment-1889721739

[PartDesign] Revert Refresh body after pipe created #11357

---

src/Gui/Stylesheets/Dark-modern.qss
src/Gui/Stylesheets/Dark.qss
src/Gui/Stylesheets/Darker.qss
src/Gui/Stylesheets/Light.qss

Fixes https://github.com/FreeCAD/FreeCAD/issues/11964

[Gui] Fix Status Bar Tooltip Visibility

---

src/Gui/Stylesheets/Dark-blue.qss
src/Gui/Stylesheets/Dark-green.qss
src/Gui/Stylesheets/Dark-modern-blue.qss
src/Gui/Stylesheets/Dark-modern-green.qss
src/Gui/Stylesheets/Dark-modern-orange.qss
src/Gui/Stylesheets/Dark-modern-pink.qss
src/Gui/Stylesheets/Dark-orange.qss
src/Gui/Stylesheets/Dark-pink.qss
src/Gui/Stylesheets/Darker-blue.qss
src/Gui/Stylesheets/Darker-green.qss
src/Gui/Stylesheets/Darker-orange.qss
src/Gui/Stylesheets/Darker-pink.qss
src/Gui/Stylesheets/Light-blue.qss
src/Gui/Stylesheets/Light-green.qss
src/Gui/Stylesheets/Light-orange.qss
src/Gui/Stylesheets/Light-pink.qss

Raised by https://github.com/FreeCAD/FreeCAD/issues/11964 but the file structure has changed significantly in 0.22dev so https://github.com/FreeCAD/FreeCAD/pull/11967 can't be backported.

[Gui] [021] Fix Status Bar Tooltip Visibility

---

src/Mod/Path/Path/Op/Vcarve.py

Issue 8064 occurs when FreeCAD passes a Voronoi diagram to Boost that becomes self-intersecting when Boost truncates the diagram's coordinates to integers.  This occurs when the discretizer slightly misses closing the polygon generated for the letter by less that FreeCAD's epsilon, then the wrapping Python code closes the polygon by adding the initial polygon point as the final point. This creates a short segment that, depending on the position of the letter in the coordinate system, may end up being moved one Boost coordinate delta away from the intended point, which can end up self-intersecting.
Since the miss is very small, FreeCAD should treat it as it it were the initial point.  There's no need for a duplicate copy of the initial point, so we remove this point close to the initial …

Fix for issue 8064 missing letters when V-carving a string.

---

src/Mod/TechDraw/Gui/CommandExtensionPack.cpp

Solve the issue reported in https://forum.freecad.org/viewtopic.php?t=84315

[TD] Solve issue in VertexAtIntersection

---

src/Mod/Fem/App/AppFem.cpp
src/Mod/Fem/App/HypothesisPy.cpp
src/Mod/Fem/App/HypothesisPy.h
src/Mod/Fem/App/PreCompiled.h
src/Mod/MeshPart/App/CMakeLists.txt
src/Mod/MeshPart/App/Mesher.cpp
src/Mod/MeshPart/Gui/CMakeLists.txt

Guard MEFISTO code with version check against SMESH.

---

src/Mod/PartDesign/SprocketFeature.py

Backport of https://github.com/FreeCAD/FreeCAD/pull/11786, tested successfully on 0.21 Branch using English and Portuguese

[PartDesign] [021] Backport Sprocket fix bug with translated references

---

src/Mod/TechDraw/Gui/QGSPage.cpp

This PR implements a fix for issue #11889.

[TD]fix Balloon parentage in tree (fix #11889)

---

src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/DimensionValidators.cpp
src/Mod/TechDraw/Gui/DimensionValidators.h

This PR implements some minor improvements to dimension validators.

[TD]Dimension validation improvements

---

src/Mod/Sketcher/Gui/Utils.cpp
src/Mod/Sketcher/Gui/Utils.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.h

Fixes https://github.com/FreeCAD/FreeCAD/issues/11605
Double click on an edge select all the connected geometries.

[Sketcher] Define double click on edges : Select the whole wire.

---

tests/src/App/ComplexGeoData.cpp
tests/src/Base/Reader.cpp

See post [Debug build fails : Libpack faulty](https://forum.freecad.org/viewtopic.php?t=84376&start=3) for context...

Tests: Avoid use of fmtlib when not needed

---

src/Mod/TechDraw/App/DrawProjGroupItem.cpp
src/Mod/TechDraw/App/DrawProjGroupItem.h
src/Mod/TechDraw/App/DrawView.h
src/Mod/TechDraw/Gui/TaskComplexSection.cpp
src/Mod/TechDraw/Gui/TaskSectionView.cpp

This PR implements a fix for #12001.

[TD]Fix section scale with DPGI base view (fix #12001)

---

src/Gui/DlgPreferencesImp.cpp

This fixes problem with scroll jumping after selecting page on bottom of the pages tree view. It was caused by collapsing group of the current item and then re-expanding it few lines after.
Fixes: #12000

Gui: Fix scroll behaviour in preference pages selector

---

src/App/MappedElement.cpp
src/App/MappedElement.h
tests/src/App/MappedElement.cpp

Add the comparison method for MappedName.

App/Toponaming: Add Comparator for mapped elements

---

src/Mod/Path/Path/Main/Gui/Job.py

fixes problem with orderby combo box not being populated correctly with translation

fixes #12029

---

src/Mod/TechDraw/App/DrawViewSection.cpp
src/Mod/TechDraw/App/DrawViewSection.h
src/Mod/TechDraw/Gui/QGIViewPart.cpp

This PR implements a fix that prevents a fail caused by a section line stretch factor of 0.

[TD]Fix section line stretch

---

src/Mod/Fem/femexamples/equation_electrostatics_capacitance_two_balls.py

Fem: Set PotentialEnabled to False in capacitance_two_balls example - fixes #9707

---

src/Mod/Tux/NavigationIndicatorGui.py
src/Mod/Tux/Resources/Tux.qrc
src/Mod/Tux/Resources/icons/NavigationOpenSCAD_dark.svg
src/Mod/Tux/Resources/icons/NavigationOpenSCAD_light.svg
src/Mod/Tux/Resources/icons/NavigationTinkerCAD_dark.svg
src/Mod/Tux/Resources/icons/NavigationTinkerCAD_light.svg

Fixes https://github.com/FreeCAD/FreeCAD/issues/11983

[Gui] [Tux] Status Bar - Fix Nav Style Icons and theme recognition

---

src/Gui/PreferencePages/DlgSettingsEditor.cpp

Related to #11969
According to suggestions, in `DlgSettingsEditor.cpp` the for loops have been modernized to range-for loops

[Core] [Preferences] Modernize for loop in DlgSettingsEditor.cpp

---

src/Gui/SoDatumLabel.cpp
src/Gui/SoDatumLabel.h
src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.h

Fixes https://github.com/FreeCAD/FreeCAD/issues/11976
Fixes https://github.com/FreeCAD/FreeCAD/issues/12010
- Improve rendering of arc-angle
- Improve rendering of line-angle
- Improve rendering of arc-distances by adding arc helpers
- Fix radius arc helper that were wrong in some conditions.
@FlachyJoe @maxwxyz

[Sketcher] Improve rendering of arc-angle, line-angle, arc-distances and fix radius

---

src/Mod/Draft/draftguitools/gui_clone.py

Draft: Inform user that objects without a Shape cannot be cloned

---

src/Gui/PythonWrapper.cpp

@marioalexis84, @chennes, this commit is supposed to fix the crash reported in #11775.

Correction of #11775

---

src/Mod/Arch/importDAE.py

Forum topic:
https://forum.freecad.org/viewtopic.php?t=84626

Arch: importDAE: DaeUnsupportedError is defined in common.py

---

src/Mod/Draft/drafttaskpanels/task_scale.py

Draft: Draft_Scale: make sure scale inputboxes show at least 6 decimals

---

src/Mod/TechDraw/Gui/CommandExtensionPack.cpp

This PR implements fixes for 2 issues reported here: https://forum.freecad.org/viewtopic.php?t=84589.
The issues involve the extend line and cosmetic thread functions.

[TD]Fix extension cosmetics

---

src/Mod/AddonManager/NetworkManager.py

Addon Manager: Don't fail during signal disconnect

---

src/Mod/AddonManager/addonmanager_installer.py
src/Mod/AddonManager/addonmanager_macro.py
src/Mod/AddonManager/addonmanager_uninstaller.py

Also improve macro removal. Fixes #11213.

Addon Manager: Allow .py filenames

---

src/Mod/AddonManager/addonmanager_git.py

Addon Manager: Fix git detection on mac

---

src/Mod/TechDraw/Gui/CommandExtensionPack.cpp

This PR implements another fix for the extension command reported here: https://forum.freecad.org/viewtopic.php?t=84589&sid=f43a646714ce15b866fdc381a8c6ede2
This fix involves the creation of bolt hole circle center lines.

[TD]fix extension bolt hole circle re scale/rotate

---

src/Mod/Draft/draftutils/init_draft_statusbar.py

The FEM UserSchema (8) was not handled by the code.

Draft: Scale widget did not handle FEM unit system

---

src/Mod/AddonManager/addonmanager_git.py
src/Mod/AddonManager/change_branch.py
src/Mod/AddonManager/change_branch.ui
src/Mod/AddonManager/package_details.py

Addon Manager: Complete migration away from GitPython

---

src/Mod/AddonManager/addonmanager_utilities.py

Addon Manager: Add support for codeberg.org repos

---

src/Gui/SoDatumLabel.cpp

SoDatumLabel: Add arrowheads to angles. And improve arrowhead rendering.
Fixes https://github.com/FreeCAD/FreeCAD/issues/12105

SoDatumLabel: Add arrowheads to angles. And improve arrowhead rendering.

---

tests/src/Mod/Part/App/TopoShapeMakeShapeWithElementMap.cpp

Added test for Tag Info generated by makeShapeWithElementMap
**!!!IMPORTANT NOTE!!!:** This test makes sense only for single shapes and shapes that aren't generated by geometrical operations.
A more robust version of this test will be developed, if needed, to test more complex shapes

Tests/Toponaming: Add test for single shapes

---

src/Mod/Draft/draftguitools/gui_fillets.py
src/Mod/Draft/draftmake/make_fillet.py
src/Mod/Draft/draftobjects/fillet.py

There were still too many messages.

Draft: Fix messages for Draft_Fillet

---

src/Mod/Part/App/Geometry.cpp
src/Mod/Part/App/Geometry.h
src/Mod/Part/App/GeometryExtension.cpp
src/Mod/Part/App/GeometryExtension.h

Existing methods appear to be tested by the existing python suite.  This passes all python and c++ tests.

Transfer in Geometry.x changes from RT branch

---

src/Mod/Material/App/CMakeLists.txt

See comments in https://github.com/FreeCAD/FreeCAD/pull/11764

Material: Avoid potential dependency of core system on application module

---

src/Base/Tools.cpp
src/Base/Tools.h
src/Gui/CommandLink.cpp
src/Gui/ExpressionBinding.cpp
src/Mod/PartDesign/Gui/CommandBody.cpp
src/Mod/Sketcher/Gui/EditDatumDialog.cpp
src/Mod/Spreadsheet/Gui/PropertiesDialog.cpp
tests/src/Base/Tools.cpp

reported at https://forum.freecad.org/viewtopic.php?p=714249#p714249 and likely other places

Avoid sending unscaped quotes to python console

---

src/Mod/Arch/ArchProject.py
src/Mod/Arch/ArchSite.py
src/Mod/Draft/draftguitools/gui_subelements.py

Fixes possible Segmentation faults in conditions where RootNode child does not exist.
See forum discussion https://forum.freecad.org/viewtopic.php?p=738286#p738286

[Arch] [Draft] Add guard for RootNode specific child

---

src/Mod/Material/App/MaterialLoader.cpp
src/Mod/Material/App/MaterialManager.cpp
src/Mod/Material/App/MaterialManager.h
src/Mod/Material/App/Materials.cpp
src/Mod/Material/App/Materials.h
src/Mod/Material/MaterialEditor.py
src/Mod/Material/materialtools/cardutils.py

Improves compatibility when using the legacy editor.
Corrects a number of issues that prevented saved files from being displayed when using the legacy editor.
Reduces the verbosity of console messages.

Material: Material editor enhancements

---

src/Mod/Part/App/TopoShape.cpp
src/Mod/Part/App/TopoShape.h
src/Mod/Part/App/TopoShapeExpansion.cpp
src/Mod/Part/App/TopoShapeMapper.cpp
src/Mod/Part/App/TopoShapeMapper.h
src/Mod/Part/App/modelRefine.h
tests/src/Mod/Part/App/CMakeLists.txt
tests/src/Mod/Part/App/TopoShapeExpansion.cpp
tests/src/Mod/Part/App/TopoShapeMakeElementRefine.cpp

~~This should pass CI as soon as #12229 is merged.~~  And OCCT7.8.0 patches are added, and testing cleaned up.

Toponaming: Transfer in makeElementRefine

---

src/Mod/Sketcher/App/Sketch.cpp
src/Mod/Sketcher/App/Sketch.h
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/planegcs/Constraints.cpp
src/Mod/Sketcher/App/planegcs/Constraints.h
src/Mod/Sketcher/App/planegcs/GCS.cpp
src/Mod/Sketcher/App/planegcs/GCS.h
src/Mod/Sketcher/App/planegcs/Geo.cpp
src/Mod/Sketcher/App/planegcs/Geo.h
src/Mod/Sketcher/Gui/CommandConstraints.cpp
tests/src/Mod/Sketcher/App/planegcs/CMakeLists.txt
tests/src/Mod/Sketcher/App/planegcs/Constraints.cpp

Replaces #9125 with the branch in my personal fork (as opposed to the Ondsel one).
Part of this work was done while I was part of Ondsel Inc., and the rest of the work is being supported through an FPA grant.

[Sketcher] General Tangency with B-splines (re-do)

---

src/Mod/Draft/importDXF.py

See:
https://github.com/FreeCAD/FreeCAD/issues/10985#issuecomment-1932797213

Draft: importDXF.py: make_bezcurve args should be lowercase

---

src/Mod/Draft/draftobjects/shapestring.py

Forum topic:
https://forum.freecad.org/viewtopic.php?t=85147

Draft: ShapeString improve stick font detection and fix fuse error

---

src/Mod/AddonManager/install_to_toolbar.py

Addon Manager: Use the installed macro icon

---

src/Mod/Arch/ArchWindow.py

See https://github.com/FreeCAD/FreeCAD/pull/11868#issuecomment-1937633689

Arch: Arch_Window fix clone recompute issue

---

src/Mod/Help/Help.py
src/Mod/Help/dlgPreferencesHelp.ui

See: https://github.com/FreeCAD/FreeCAD-Help/pull/23

Help: Fix path for off-line documentation

---

src/Mod/PartDesign/App/Feature.cpp
src/Mod/PartDesign/App/Feature.h

[PD] Add a Suppressed property to disable a feature

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/12083
A - Ignore points and non-line geos when making a parallel constraint.
B - Modernize for loops and use auto where static_cast Obj

[Sketcher] Constraint Parallel : ignore selected points

---

src/Mod/Part/Gui/TaskAttacher.ui

Resolve #12235: labels in `Mod/Part/Gui/TaskAttacher.ui`

Resolve #12235: labels in `Mod/Part/Gui/TaskAttacher.ui`

---

src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py

Add a slot to start/stop CalculiX based on process and exit status.
This panel still needs some work to make the output consistent and fix the printed time.
@FEA-eng, would you like to test this?

Fem: Enable "Stop CalculiX" button - fixes #11448

---

src/Mod/Mesh/Gui/ViewProviderTransformDemolding.cpp

removed unused code

---

src/Mod/Material/Gui/Array2D.cpp
src/Mod/Material/Gui/ListDelegate.h
src/Mod/Material/Gui/MaterialDelegate.cpp
src/Mod/Material/Gui/MaterialsEditor.cpp
src/Mod/Part/App/FaceMakerBullseye.h
src/Mod/Part/App/Geometry.cpp
src/Mod/PartDesign/App/FeatureHole.cpp
src/Mod/Robot/Gui/ViewProviderTrajectory.cpp
src/Mod/Sketcher/App/PythonConverter.cpp
src/Mod/Sketcher/App/Sketch.cpp
src/Mod/Sketcher/Gui/SketcherSettings.ui
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

* fix -Wsometimes-uninitialized
* fix -Wunused-parameter
* fix -Wunused-variable
* fix -Winconsistent-missing-override
* fix -Wsign-compare
* fix -Wreorder-ctor
* fix -Wtautological-overlap-compare

Mod: fix several compiler warnings:

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

Fix icon order in constraint menu

---

src/Base/Vector3D.cpp
src/Base/Vector3D.h
tests/src/Base/Vector3D.cpp

Fix the methods and add unit tests.
See https://github.com/FreeCAD/FreeCAD/pull/11800#discussion_r1480348529

Base: fix IsNormal() and IsParallel()

---

src/Mod/Fem/Gui/PreCompiled.h
src/Mod/Import/App/ImportOCAF.cpp
src/Mod/Import/App/ImportOCAF.h
src/Mod/Import/App/ImportOCAFAssembly.cpp
src/Mod/Import/App/ImportOCAFAssembly.h
src/Mod/Part/App/ImportStep.cpp
src/Mod/Part/App/OpenCascadeAll.h
src/Mod/Part/App/ShapeMapHasher.h
src/Mod/Part/App/TopoShapePyImp.cpp
src/Mod/Part/Gui/ViewProviderExt.cpp
src/Mod/Sandbox/Gui/AppSandboxGui.cpp

* Removes a leftover of some includes of Standard_math.hxx
* Add a helper class ShapeMapHasher to simplify code

Improve port to OCC 780

---

src/Mod/Sketcher/Gui/CMakeLists.txt
src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
src/Mod/Sketcher/Gui/DrawSketchControllableHandler.h
src/Mod/Sketcher/Gui/DrawSketchController.h
src/Mod/Sketcher/Gui/DrawSketchDefaultWidgetController.h
src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h
src/Mod/Sketcher/Gui/DrawSketchHandlerRotate.h
src/Mod/Sketcher/Gui/DrawSketchHandlerTranslate.h
src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
src/Mod/Sketcher/Gui/Resources/icons/pointers/Sketcher_Pointer_Create_Translate.svg
src/Mod/Sketcher/Gui/Resources/icons/tools/Sketcher_Translate.svg
src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.cpp
src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.h
src/Mod/Sketcher/Gui/Workbench.cpp

Translate DSH : replacement for rectangular array / move / copy / clone
Please note that it does not remove the code of the commands rectangular array / move / copy / clone. It only removes them from the toolbar/menus. Should the code be removed as well ?

[Sketcher] Translate DSH : replacement for rectangular array / move / copy / clone

---

src/Mod/Part/App/TopoShape.cpp
src/Mod/Part/App/TopoShape.h
src/Mod/Part/App/TopoShapeExpansion.cpp
tests/src/Mod/Part/App/TopoShapeExpansion.cpp

Toponaming/Part:  Move getSubTopoShape

---

src/Mod/PartDesign/App/Feature.cpp
tests/src/Base/Vector3D.cpp

PD: handle null pointer in Feature::getBaseShape

---

src/Mod/Part/App/Attacher.cpp
src/Mod/Part/Gui/AttacherTexts.cpp

Extract a line from the intersection of two faces.
Closes #6870
Please give it a spin, I didn't manage to break it after some use...

PD: Implement 1D intersection for attachments

---

src/Mod/Part/App/TopoShape.h
src/Mod/Part/App/TopoShapeExpansion.cpp
tests/src/Mod/Part/App/PartTestHelpers.cpp
tests/src/Mod/Part/App/PartTestHelpers.h
tests/src/Mod/Part/App/TopoShapeExpansion.cpp

Toponaming/Part: Transfer in MakeElementDraft

---

.github/workflows/issue-metrics.yml

add action workflow to generate monthly issue metrics https://github.com/github/issue-metrics

Issue Metrics Workflow

---

.github/ISSUE_TEMPLATE/PROBLEM_REPORT.yml

Adding the dropdown option for the integrated Assembly WB

[GitHub] Add Assembly option to Problem Issue Template

---

src/Mod/Draft/draftmake/make_array.py
src/Mod/Draft/draftmake/make_clone.py
src/Mod/Draft/draftmake/make_patharray.py
src/Mod/Draft/draftmake/make_pointarray.py

Stuff that was missed in #11946

Draft: remove reapply_diffuse_color workaround step 2

---

src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.h

This PR implements a fix for a problem reported here: https://forum.freecad.org/viewtopic.php?p=740392#p740392
- prevent premature save of LineStandard  >> wrong parameter value

[TD]fix Prefs Annotation tab

---

src/Mod/Fem/Gui/DlgSettingsFemCcx.ui
src/Mod/Fem/femsolver/calculix/solver.py
src/Mod/Fem/femsolver/calculix/write_step_equation.py

FEM new matrix solver types (PaStiX and Pardiso)

---

src/Gui/PreferencePackTemplates/Window_Colors.cfg
src/Gui/PreferencePacks/Classic/Classic.cfg
src/Gui/PreferencePacks/Dark behave/Dark behave.cfg
src/Gui/PreferencePacks/Dark contrast/Dark contrast.cfg
src/Gui/PreferencePacks/Dark modern/Dark modern.cfg
src/Gui/PreferencePacks/Dark/Dark.cfg
src/Gui/PreferencePacks/Darker/Darker.cfg
src/Gui/PreferencePacks/Light modern/Light modern.cfg
src/Gui/PreferencePacks/Light/Light.cfg
src/Gui/PreferencePacks/ProDark/ProDark.cfg
src/Gui/ViewProviderGeometryObject.cpp

@chennes David pointed out that I've missed these files in PR #12380

[Material] missed files to change default shape color

---

src/Mod/Path/Path/Post/scripts/uccnc_post.py

Fixed canned drill cycles for uccnc post. Fixes #12365

[Path] Bugfix uccnc_post.py

---

src/Mod/Part/App/FeaturePartFuse.cpp

Code transfer in.  Tests already merged in repo.

Toponaming/Part FeaturePartFuse 

---

cMake/FindPyCXX.cmake

Pycxx version are always > 6.2

Clean FindPyCXX.cmake

---

src/Mod/Sketcher/Gui/SketcherRegularPolygonDialog.ui

[Sketcher] Fix typo in polygon task dialog

---

src/App/StringHasher.cpp
src/Base/Stream.cpp
src/Base/Stream.h

Based on the modifications to InputStream from the LinkStage3 fork. Needed for correct restoration of StringHasher.

Base: Add ASCIIInputStream

---

src/Gui/PythonWrapper.cpp
src/Gui/propertyeditor/PropertyEditor.cpp

* removed unused variable
* port to Qt6

Fix warnings

---

src/App/StringHasher.cpp
src/Base/Stream.cpp
src/Base/Stream.h

As suggested by @wwmayer [here ](https://github.com/FreeCAD/FreeCAD/pull/12485#issuecomment-1953280981).

Base: Rename ASCIIInputStream to TextInputStream

---

src/Mod/AddonManager/AddonManagerOptions.ui
src/Mod/AddonManager/NetworkManager.py
src/Mod/AddonManager/package_list.py

Correct error in the way the Addon Manager fetched and displayed license data.

Addon Manager: Fix metadata license fetch and display

---

src/App/VarSet.cpp

Fix compilation errors with MSVC.

App: Add PreCompiled.h to Varset cpp file

---

src/Mod/Fem/Gui/DlgSettingsFemGeneral.ui
src/Mod/Fem/femmesh/meshtools.py

Enable the checkbox and set default value to false for the experimental feature.

Fem: Enable checkbox for references mesh groups - fixes #10071

---

src/Gui/propertyeditor/PropertyItem.cpp
src/Gui/propertyeditor/PropertyItem.h

* Use int for shininess and set a range of [0, 100]
* Use int for transparency and set a range of [0, 100]

Gui: Improve editors PropertyMaterialItem and PropertyMaterialListItem

---

src/Gui/MouseSelection.cpp
src/Gui/MouseSelection.h
src/Gui/NavigationStyle.cpp
src/Gui/NavigationStyle.h
src/Gui/View3DInventorViewer.cpp
src/Mod/Part/App/TopoShape.cpp
src/Mod/Part/App/TopoShape.h
src/Mod/TechDraw/App/DrawViewPart.cpp
src/Mod/TechDraw/Gui/QGIPrimPath.cpp
src/Mod/TechDraw/Gui/QGIPrimPath.h
src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
src/Mod/TechDraw/Gui/ViewProviderViewSection.cpp

QGIPrimPath::setHighlighted, TopoShape::setShapePlacement and TopoShape::getShapePlacement are obsolete and never used

Core, wb techdraw, wb part :Removed deprecated func

---

src/Base/Interpreter.cpp

Reported as [Annoying Warning regression when saving macros](https://forum.freecad.org/viewtopic.php?t=84758)

Base: Fix #12061

---

src/Mod/PartDesign/Gui/ViewProviderDatumPoint.cpp

Give the user some feedback by changing the color of the datum point marker as the user selects or hovers over it.
Closes #9540

PD: Make datum points highlightable/selectable

---

src/Mod/Fem/Gui/Resources/ui/ElementGeometry1D.ui

FEM Pipe beam section - clarifying the diameter type in the task window

---

src/Mod/Fem/feminout/importCcxFrdResults.py

Fem: Create mesh for check type analysis in CalculiX - fixes #12503

---

src/Gui/ViewProviderSuppressibleExtension.cpp
src/Gui/ViewProviderSuppressibleExtension.h

Master does not build on windows with precompiled. Fixes https://github.com/FreeCAD/FreeCAD/pull/12412
@wwmayer @chennes whoever come first please.

Fix ViewProviderSuppressibleExtension

---

cMake/ConfigureChecks.cmake

Clean ConfigureChecks.cmake

---

src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h

Fixes https://github.com/FreeCAD/FreeCAD/issues/12322
Change the bahavior of line DSH length/width mode so that it behaves like the rectangle length/width DSH.

[Sketcher] Line DSH Fixes #12322 

---

src/Mod/AddonManager/package_list.py

Addon Manager: Fix scroll distance on scrollbar click

---

src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h

The descriptions were sometimes not accurate (major/minor radius for ellipses). I have also tried to improve the constistency a little.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=85396

Sketcher: improve GUI texts for arcs and conics

---

src/Mod/Part/App/TopoShape.h
src/Mod/Part/App/TopoShapeExpansion.cpp
tests/src/Mod/Part/App/TopoShapeExpansion.cpp

Also repairs / improves the elementsMatch and allElementsMatch  test assertion helpers.

Toponaming/Part:  replace element shape and remove element shape

---

src/Mod/PartDesign/App/Feature.cpp
src/Mod/PartDesign/App/Feature.h
src/Mod/PartDesign/App/FeatureBoolean.cpp
src/Mod/PartDesign/Gui/ViewProvider.cpp
src/Mod/PartDesign/Gui/ViewProvider.h

PD: Use SuppressibleExtension

---

src/Mod/TechDraw/App/DrawProjGroup.cpp
src/Mod/TechDraw/Gui/QGSPage.cpp
src/Mod/TechDraw/Gui/TaskProjGroup.cpp
src/Mod/TechDraw/Gui/TaskProjGroup.h

This PR implements a fix for issue #12625.   Additional forum discussion is here: 
https://forum.freecad.org/viewtopic.php?t=66668&sid=bbb8fcd1373e450eecde9ad66ef9744d
https://forum.freecad.org/viewtopic.php?t=85666&sid=bbb8fcd1373e450eecde9ad66ef9744d
- also fix checkbox correspondence with view position

[TD]fix Projection Group front view position <fix #12625>

---

src/Mod/TechDraw/Gui/PagePrinter.cpp
src/Mod/TechDraw/Gui/PagePrinter.h

This PR implements fixes for page format issues reported here: https://forum.freecad.org/viewtopic.php?p=743439#p743439
and here:
https://forum.freecad.org/viewtopic.php?t=85518

[TD]fix printAll formats

---

src/Mod/Draft/draftguitools/gui_annotationstyleeditor.py

Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/288

Draft: Translate annotation styles editor

---

src/Mod/Sketcher/App/Sketch.cpp
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h
src/Mod/Sketcher/App/SketchObjectPyImp.cpp
src/Mod/Sketcher/App/planegcs/Constraints.cpp
src/Mod/Sketcher/App/planegcs/Constraints.h
src/Mod/Sketcher/App/planegcs/GCS.cpp
src/Mod/Sketcher/App/planegcs/GCS.h
src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp

Make a C1 continuity at joining. WIP: Intended for when there is already a tangent constraint; those checks are coming.

Sketcher: Improve Join Curves

---

src/Mod/Fem/femexamples/equation_magnetodynamics_2D_elmer.py
src/Mod/Fem/femexamples/equation_magnetostatics_2D_elmer.py

fixes #9784
Solution consulted with @Roy-043

Elmer FEM 2D electromagnetic examples fix

---

src/Mod/Fem/femobjects/material_mechanicalnonlinear.py
src/Mod/Fem/femsolver/calculix/write_femelement_material.py

a small step towards #11642
replaces meaningless _simple hardening_ with _isotropic hardening_ and adds _kinematic hardening_

FEM CalculiX isotropic and kinematic hardening

---

src/Mod/Fem/femcommands/commands.py
src/Mod/Fem/femtools/checksanalysis.py

Remove the need to include geometrical nonlinearity when nonlinear material is used in CalculiX FEM

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

UI/tooltip change only.
Fixes https://github.com/FreeCAD/FreeCAD/issues/10718
Sketcher_ConstrainTangent creates either a tangent or colinear constraint. The colinear functionality is hard to discover, as it is never mentioned in the tool.

[Sketcher] Add description of colinear function to Sketcher_ConstrainTangent

---

src/App/ComplexGeoData.cpp
src/App/ComplexGeoData.h
src/App/DocumentObject.cpp
src/App/DocumentObject.h
src/App/Property.cpp
src/App/PropertyContainer.h
src/App/PropertyGeo.cpp
src/App/PropertyGeo.h
src/Mod/Part/App/AppPart.cpp
src/Mod/Part/App/Attacher.cpp
src/Mod/Part/App/PropertyTopoShape.cpp
src/Mod/Part/App/PropertyTopoShape.h
tests/src/Mod/Part/App/CMakeLists.txt
tests/src/Mod/Part/App/FeaturePartCommon.cpp
tests/src/Mod/Part/App/PartFeature.cpp
tests/src/Mod/Part/App/PartFeatures.cpp
tests/src/Mod/Part/App/PropertyTopoShape.cpp

~~This is currently fairly rough, but likely warrants early review.~~
Unfortunately fairly large, brings a chunk of interrelated pieces over.

Toponaming/Part: property topo shape

---

src/Mod/Sketcher/App/SketchObject.cpp

Fix warning: add explicit braces to avoid dangling else [-Wdangling-else]

Sketch: fix compiler warning

---

src/Mod/Part/Gui/CommandFilter.cpp

Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/284

Part: Correct context for selection filter

---

src/Mod/AddonManager/Widgets/addonmanager_widget_global_buttons.py
src/Mod/Sketcher/Gui/Workbench.cpp

Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/274

Addon manager update number string translation

---

src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp

For more details see: https://forum.freecad.org/viewtopic.php?p=745031#p745031

Sketcher: fix crash when trying to edit malformed sketch

---

src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp

This PR implements a fix for an issue with unit of measure display in spreadsheet views reported here: https://forum.freecad.org/viewtopic.php?t=85824&sid=6391ce69b67511dc5b52d16bc4a89bf7

[TD]correct s/s cell format

---

src/Mod/TechDraw/Gui/Workbench.cpp

Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/278

TD: Add missing translation strings to menu

---

src/Mod/MeshPart/App/Mesher.cpp
src/Mod/Part/App/BRepMesh.cpp
src/Mod/Part/App/BRepMesh.h
src/Mod/Part/App/CMakeLists.txt
src/Mod/Part/App/TopoShape.cpp

This refactors the code of TopoShape::getFacesFromDomains and the the private class BrepMesh of the MeshPart module to reduce code duplication.

Part: Add class BRepMesh

---

src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h

Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/302

Sketcher: Translate menu entries for rectangle spec

---

src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArcSlot.h
src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h
src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h
src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h

See https://github.com/FreeCAD/FreeCAD-translations/issues/302 and https://github.com/FreeCAD/FreeCAD/pull/12731

Sketcher: Fix missing translations in DSH tools

---

src/Mod/Draft/DraftGui.py
src/Mod/PartDesign/Gui/Workbench.cpp

Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/289

Fix missing translations in task panel

---

src/Mod/Sketcher/Gui/Workbench.cpp

Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/277

Sketcher: Fix missing translation of 'Sketcher visual'

---

src/Mod/Fem/femexamples/equation_flow_elmer_2D.py
src/Mod/Fem/femexamples/equation_flow_initial_elmer_2D.py
src/Mod/Fem/femexamples/equation_flow_turbulent_elmer_2D.py

Elmer FEM 2D flow examples fix

---

src/Mod/Part/App/BRepMesh.cpp
tests/src/Mod/Part/App/BRepMesh.cpp
tests/src/Mod/Part/App/CMakeLists.txt

For the concatenated domains check if points are duplicate and if yes remove them

Part: fixes #12744: mesh export creates open edges

---

src/Mod/TechDraw/TechDrawTools/CommandAxoLengthDimension.py

Solve the scale issue discussed in https://forum.freecad.org/viewtopic.php?t=85929
Replace local function checkParallel by global function isParallel

[TD] Solve scale issue in AxoLengthDimension

---

src/Mod/CAM/Path/Main/Gui/Sanity.py

If the toolshape isn't on the local system, Sanity would fail trying to get the thumbnail. Now fails gracefully.

CAM:  fix edgecase with missing toolshape

---

src/Tools/updatecrowdin.py
src/Tools/updatets.py

Tools: Path -> CAM

---

.github/labels.yml

Auto-assign 'Materials' label to Material related PRs

labels.yml: Add Materials label

---

src/Mod/TechDraw/App/Cosmetic.cpp
src/Mod/TechDraw/App/CosmeticVertex.cpp
src/Mod/TechDraw/App/DimensionFormatter.cpp
src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
src/Mod/TechDraw/Gui/QGIViewDimension.cpp
src/Mod/TechDraw/Gui/ViewProviderDimension.cpp
src/Mod/TechDraw/Gui/ViewProviderDimension.h
src/Mod/TechDraw/TechDrawTools/TaskHoleShaftFit.py

This PR implements fixes for three issues:
HoldShaft/Tolerances: https://forum.freecad.org/viewtopic.php?t=86094
Thread lines: https://forum.freecad.org/viewtopic.php?t=85405
Delete while dialog in progress: https://forum.freecad.org/viewtopic.php?t=86109

[TD]Assorted fixes

---

src/Mod/Fem/femsolver/calculix/solver.py

FEM: Correct property description after #12703

---

src/Mod/Draft/Resources/ui/preferences-draftsnap.ui

corrected typos in the new preference description

DRAFT: Fixed typos in the mouse delay preference description

---

src/Mod/TechDraw/TechDrawTools/CommandAxoLengthDimension.py
src/Mod/TechDraw/TechDrawTools/CommandPositionSectionView.py
src/Mod/TechDraw/TechDrawTools/CommandVertexCreations.py

Fix header whitespace
[skip ci]

TD: Fix whitespace in various headers

---

src/Mod/Arch/exportIFC.py
src/Mod/Arch/exportIFCHelper.py

This fixes the export of Draft arrays as IfcElementAssembly
Fixes issue #12802

Arch: Fixed IFC export of arrays

---

src/Mod/Assembly/Gui/Resources/icons/Assembly_CreateJointCylindrical.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_CreateJointRevolute.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_CreateJointSlider.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_SolveAssembly.svg

Updated icons as the three joints below are very similar, especially at small size.
Was done with DWG in the loop.

UI: Assembly - update too similar icons

---

src/Mod/Draft/draftutils/utils.py

Allow Draft.get_type to recognize NativeIFC objects

[Draft] Made get_type aware of IFC objects

---

src/App/ComplexGeoData.h
src/App/IndexedName.h
src/Mod/Part/App/FeatureChamfer.cpp
src/Mod/Part/App/FeatureFillet.cpp
src/Mod/Part/App/PartFeature.cpp
src/Mod/Part/App/PartFeature.h
src/Mod/Part/App/TopoShape.cpp
src/Mod/Part/App/TopoShapeExpansion.cpp
src/Mod/Part/Gui/DlgFilletEdges.cpp
tests/src/Mod/Part/App/FeatureChamfer.cpp
tests/src/Mod/Part/App/TopoShapeExpansion.cpp

Toponaming/part features chamfer, fillet; dependencies and test updates

---

src/Base/Interpreter.cpp

For more details see: https://forum.freecad.org/viewtopic.php?p=748296#p748296

Base: enable user site-packages for Py >= 3.11

---

.github/workflows/actions/runCPPTests/runAllTests/action.yml
tests/src/Mod/PartDesign/App/CMakeLists.txt
tests/src/Mod/PartDesign/App/DatumPlane.cpp

This adds a unit test to demonstrate the regression reported with https://github.com/FreeCAD/FreeCAD/issues/13055
The regression is caused by https://github.com/FreeCAD/FreeCAD/pull/12885

tests: Test case for issue #13055

---

src/Mod/Draft/draftobjects/label.py

The proposed code fixes the following issues:
1. There is no check if the target object itself has a property that matches the label type.
2. If a subelement is selected that does not have the label type property, the value from the main object is displayed instead.
3. The default text is an empty string.
Example:
Currently If you select a vertex of a wire, and select "Length" as the label type, you will get the length of the wire. With the new code the text will then be "Length not available for (sub)object".
Forum topic (issue 1):
https://forum.freecad.org/viewtopic.php?t=86222

Draft: Improve logic of Draft_Label texts

---

src/Gui/MainWindow.cpp

See https://forum.freecad.org/viewtopic.php?p=748736#p748736

Gui: clear the title bar after closing the last MDI window

---

src/Mod/Part/App/ExtrusionHelper.cpp
src/Mod/Part/App/ExtrusionHelper.h
src/Mod/Part/App/FeatureExtrusion.cpp
src/Mod/Part/App/FeatureExtrusion.h
tests/src/Mod/Part/App/FeatureExtrusion.cpp
tests/src/Mod/Part/App/PartTestHelpers.cpp

Toponaming/Part Move in feature extrusion

---

src/Mod/PartDesign/App/FeatureHelix.cpp
src/Mod/PartDesign/App/FeatureHelix.h
src/Mod/PartDesign/PartDesignTests/TestHelix.py

If we don't break the helix path at each turns we get a valid path for MakePipe (solid) even with an angle.
To be tested carefully.
Pind @bgbsww

[PartDesign] Still a helix fix

---

src/Mod/TechDraw/App/DrawComplexSection.cpp
src/Mod/TechDraw/App/DrawUtil.cpp
src/Mod/TechDraw/App/DrawUtil.h
src/Mod/TechDraw/App/ShapeUtils.cpp
src/Mod/TechDraw/App/ShapeUtils.h

This PR implements a fix for ComplexSection with certain view directions reported here: https://forum.freecad.org/viewtopic.php?t=86341

[TD]Fix complex section for certain view directions

---

src/Mod/Part/App/AppPart.cpp
src/Mod/Part/App/CMakeLists.txt
src/Mod/Part/App/FeatureProjectOnSurface.cpp
src/Mod/Part/App/FeatureProjectOnSurface.h
src/Mod/Part/Gui/AppPartGui.cpp
src/Mod/Part/Gui/CMakeLists.txt
src/Mod/Part/Gui/Command.cpp
src/Mod/Part/Gui/DlgProjectionOnSurface.cpp
src/Mod/Part/Gui/DlgProjectionOnSurface.h
src/Mod/Part/Gui/ViewProviderProjectOnSurface.cpp
src/Mod/Part/Gui/ViewProviderProjectOnSurface.h

Part: Make Part_ProjectionOnSurface parametric

---

src/Mod/Fem/App/FemPostObject.cpp

FEM: Rename vtkWriter to femVTKWriter to make MSVC happy

---

src/Mod/Draft/draftobjects/pointarray.py

Draft: add Fuse property to pointarray

---

src/Mod/Draft/draftobjects/patharray.py
src/Mod/Draft/draftobjects/pathtwistedarray.py

Draft: add Fuse property to patharray and pathtwistedarray

---

src/Gui/CommandView.cpp
src/Gui/Workbench.cpp

fixes https://github.com/FreeCAD/FreeCAD/pull/12878#issuecomment-2027814069
- adding missed view top command
- arrangement as everywhere

UI: Add missing view top option

---

src/Gui/Workbench.cpp

Gui: Std_ViewLeft should be last in "Individual views" toolbar

---

cMake/FreeCAD_Helpers/PrintFinalReport.cmake
src/Mod/Material/App/CMakeLists.txt

Attempt to fix problem with yaml-cpp reported at https://forum.freecad.org/viewtopic.php?t=84376
@PaddleStroke please test if you have time

Material: fix windows debug builds

---

src/Gui/SoDatumLabel.cpp
src/Gui/SoDatumLabel.h
src/Mod/Sketcher/App/Sketch.cpp
src/Mod/Sketcher/App/planegcs/Constraints.cpp
src/Mod/Sketcher/App/planegcs/Constraints.h
src/Mod/Sketcher/App/planegcs/GCS.cpp
src/Mod/Sketcher/App/planegcs/GCS.h
src/Mod/Sketcher/App/planegcs/Geo.h
src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Extend constraint distance to arc length.
Fix #9924 
Current status:

Sketcher : ArcLength Constraint

---

src/Mod/AddonManager/manage_python_dependencies.py

Addon Manager: Python package installer wait for thread

---

src/Mod/Material/Gui/BaseDelegate.cpp
src/Mod/Material/Gui/MaterialDelegate.cpp
src/Mod/Material/Resources/Models/Thermal/Thermal.yml
src/Mod/Material/materialtests/TestMaterials.py
tests/src/Mod/Material/App/TestMaterials.cpp

Fixes #13019
Adds the property 'Thermal Expansion Reference Temperature' to the Thermal properties

Material: Add thermal reference temperature

---

src/Mod/Sketcher/App/SketchObject.cpp

Sketcher: Chamfer Fix #13049

---

src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
src/Mod/Fem/Gui/ViewProviderFemPostObject.h

Fem: Improve post-processing object style - fixes #13017

---

src/Mod/Fem/ObjectsFem.py

Change default 2D element thickness from 20 to 1

---

src/Mod/Arch/importWebGL.py

Tested locally: this results in a working WebGL export using the attached file in #13186

Fix to WebGL export. Closes: #13186

---

src/Base/ParameterPy.cpp

https://forum.freecad.org/viewtopic.php?t=86585

Base: expose a method to rename a parameter group to Python

---

src/Mod/Arch/ArchCommands.py
src/Mod/Arch/ArchPipe.py

Forum topic:
https://forum.freecad.org/viewtopic.php?t=86556

Arch: Arch_Pipe did not process Subtractions and Additions

---

src/Mod/Fem/feminout/importToolsFem.py

FEM: Fixed typos in one error message

---

src/Base/Parameter.cpp
src/Gui/Application.cpp
src/Gui/WorkbenchSelector.cpp
src/Mod/Drawing/Gui/TaskOrthoViews.cpp
src/Mod/Mesh/App/WildMagic4/Wm4System.cpp
src/Mod/Part/App/FaceMaker.h
src/Mod/Part/App/PartFeature.cpp
src/Mod/Part/App/WireJoiner.cpp
src/Mod/Sketcher/Gui/DrawSketchHandlerSymmetry.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.h
tests/src/Misc/fmt.cpp
tests/src/Mod/Part/App/PartFeature.cpp

* fix -Winconsistent-missing-override
* fix -Wunused-but-set-variable
* fix -Wunused-parameter
* fix -Wdeprecated-declarations

Fix several compiler warnings

---

src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/App/DrawViewDimension.h

This PR implements a fix for a problem with corrupt dimension references as reported here: https://forum.freecad.org/viewtopic.php?p=750827#p750827

[TD]fix fail on corrupt dimension reference

---

src/Mod/Spreadsheet/importXLSX.py

Correcting spelling of "address"

---

src/Mod/Arch/importIFCHelper.py
src/Mod/Fem/femexamples/ccx_cantilever_beam_rect.py
src/Mod/Fem/femexamples/constraint_contact_solid_solid.py
src/Mod/Fem/feminout/exportNastranMesh.py
src/Mod/Fem/femtools/ccxtools.py

Correcting spelling of "seems"

---

src/Mod/TechDraw/Gui/DimensionValidators.cpp
src/Mod/TechDraw/Gui/DimensionValidators.h

Corrected spelling of "occurrences"

---

src/Mod/PartDesign/CMakeLists.txt
src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
src/Mod/PartDesign/PartDesignTests/__init__.py
src/Mod/PartDesign/TestPartDesignApp.py

And set up a file for future TNP tests to go in.  This initial test has been temporarily setup to just print the status rather than fail, since the code base does not yet support TNP.

Add an initial test to show TNP

---

src/Mod/Sketcher/Gui/DrawSketchHandlerTranslate.h

Fixes #13189
Sketcher_Translate: Horizontal and vertical constraints are lost

Sketcher: Translate Fixes #13189 horizontal/vertical lost.

---

src/Mod/Material/materialtools/cardutils.py

Correcting spelling of "preferred"

---

.git-blame-ignore-revs
.pre-commit-config.yaml
src/Mod/AddonManager/Widgets/addonmanager_widget_progress_bar.py
src/Mod/AddonManager/addonmanager_readme_controller.py
src/Mod/AddonManager/manage_python_dependencies.py
src/Mod/Drawing/DrawingPatterns.py
src/Mod/Show/ShowUtils.py
src/Mod/Show/mTempoVis.py
src/Mod/Start/StartPage/StartPage.py
src/Mod/Test/Document.py
src/Mod/Test/TestGui.py
src/Tools/SubWCRev.py
src/Tools/doctools.py
src/Tools/embedded/PySide/mainwindow.py
src/Tools/embedded/PySide/mainwindow2.py
src/Tools/embedded/PySide/mainwindow3.py
src/Tools/generateBase/generateTools.py
src/Tools/updateppa.py

As discussed in last week's PR Review Meeting, this version of Black should run on all supported development platforms. Replaces PR #13083.

Precommit: Update black

---

src/Mod/TechDraw/App/AppTechDraw.cpp
src/Mod/TechDraw/App/CMakeLists.txt
src/Mod/TechDraw/App/DimensionGeometry.cpp
src/Mod/TechDraw/App/DimensionGeometry.h
src/Mod/TechDraw/App/DrawBrokenView.cpp
src/Mod/TechDraw/App/DrawBrokenView.h
src/Mod/TechDraw/App/DrawBrokenViewPy.xml
src/Mod/TechDraw/App/DrawBrokenViewPyImp.cpp
src/Mod/TechDraw/App/DrawUtil.cpp
src/Mod/TechDraw/App/DrawUtil.h
src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/App/DrawViewPart.cpp
src/Mod/TechDraw/App/DrawViewPart.h
src/Mod/TechDraw/App/DrawViewPartPy.xml
src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
src/Mod/TechDraw/App/ShapeExtractor.cpp
src/Mod/TechDraw/App/ShapeUtils.cpp
src/Mod/TechDraw/App/ShapeUtils.h
src/Mod/TechDraw/Gui/CMakeLists.txt
src/Mod/TechDraw/Gui/Command.cpp
src/Mod/TechDraw/Gui/PreferencesGui.cpp
src/Mod/TechDraw/Gui/PreferencesGui.h
src/Mod/TechDraw/Gui/QGIBreakLine.cpp
src/Mod/TechDraw/Gui/QGIBreakLine.h
src/Mod/TechDraw/Gui/QGIUserTypes.h
src/Mod/TechDraw/Gui/QGIViewPart.cpp
src/Mod/TechDraw/Gui/QGIViewPart.h
src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_BrokenView.svg
src/Mod/TechDraw/Gui/Workbench.cpp

This PR implements a solution to long standing feature request #5694.

[TD]Implement Broken View (fixes  #5694)

---

.github/workflows/sub_lint.yml

update c++ version from 11 to 17

Update default c++ version into sub_lint.yml

---

src/Mod/TechDraw/App/DrawSVGTemplate.cpp
src/Mod/TechDraw/App/DrawSVGTemplate.h
src/Mod/TechDraw/App/DrawTemplate.cpp
src/Mod/TechDraw/Gui/ViewProviderTemplate.cpp

This PR implements a fix for a problem with template autofill for number of sheets in a document reported here: https://forum.freecad.org/viewtopic.php?t=86660&sid=d08d24f65df2c102a267be6729212508

[TD]fix templated autofill for sheet

---

src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h

Sketcher: Rectangle DSH Fixes #12297

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/Workbench.cpp

fixes https://github.com/FreeCAD/FreeCAD/pull/12161#issuecomment-2016914460
Refine proposed constraints on point selection.
Add symmetry tool to context menu.
Rearrange commands to be consistent with the toolbar.

Sketcher: Update Sketcher context menu commands

---

src/Mod/Arch/ArchWall.py

See FC Forum Discussion
- https://forum.freecad.org/viewtopic.php?t=86365

[ArchWall] Fix regression make block from DraftWire

---

src/Mod/Arch/ArchReference.py

General upgrade of the Arch Reference tool, so it can work with more filetypes
* Fixed translations
* Reference objects can now use whole file contents instead of having to choose a part
* Support for DXF files
* Support for IFC files (if NativeIFC is available)
* General code cleanup

Arch: Upgraded reference tool

---

src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py

Cover most of the PartDesign objects.

Toponaming/Part: Upgrade Part Design tests

---

.github/workflows/actions/windows/getCcache/action.yml
.github/workflows/actions/windows/getLibpack/action.yml

switch to node 20: fix deprecation warning
update
actions/cache/save to v4
actions/cache/restore to v4

fix deprecation warning

---

.github/workflows/labeler.yml

fix deprecation warning
updated action/labeler to v5

fix deprecation warning 2

---

src/Gui/OverlayManager.cpp

@wwmayer this fixes the warning (https://github.com/FreeCAD/FreeCAD/pull/13330#issuecomment-2048084887)

Fix compiler warning

---

.github/labels.yml

The labeler action changed it supported formats in v5, this (should) fix the issue.

GitHub: Fix label YAML format

---

src/Mod/TechDraw/App/DrawBrokenView.cpp
src/Mod/TechDraw/App/DrawBrokenView.h
src/Mod/TechDraw/App/DrawUtil.cpp
src/Mod/TechDraw/App/DrawUtil.h
src/Mod/TechDraw/Gui/QGIBreakLine.cpp
src/Mod/TechDraw/Gui/QGIViewPart.cpp

This PR implements a fix to issue #13404.

[TD]handle odd projection cs in broken view

---

src/Mod/PartDesign/App/ShapeBinder.cpp
src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py

Toponaming/Part:  move in shape binder

---

src/Mod/Sketcher/Gui/DrawSketchHandlerTrimming.h

Sketcher: Trim tool, hold click and move. Fixes #6152
https://github.com/FreeCAD/FreeCAD/assets/19984177/a0677d48-e11a-4936-8a1e-d6636397d69a

Sketcher: Trim tool, hold click and move. Fixes #6152

---

src/Mod/CAM/Path/Post/scripts/grbl_post.py

Problem somehow snuck back in after #12247.   This should correct.

Have grbl_post not write - file just like other postprocessors

---

src/Mod/TechDraw/App/DrawBrokenView.cpp
src/Mod/TechDraw/App/DrawBrokenView.h
src/Mod/TechDraw/App/DrawViewDimension.cpp

This PR implements fixes for dimensions in the new BrokenView feature.

[TD]fix BrokenView dimensions

---

src/Mod/TechDraw/App/DimensionGeometry.cpp
src/Mod/TechDraw/App/DrawViewDetail.cpp
src/Mod/TechDraw/App/DrawViewDetail.h

This PR fixes an issue with 3d dimensions in detail views as reported here: https://forum.freecad.org/viewtopic.php?t=86855&sid=b45368ca80a57b90628a0f1833f137ab

[TD]fix 3d dimension position on DetailView

---

src/Mod/TechDraw/App/DimensionReferences.cpp
src/Mod/TechDraw/App/DrawUtil.cpp
src/Mod/TechDraw/App/DrawViewPart.cpp

This PR implements a fix for handling corrupt references in dimensions as reported in issue #13448.

[TD]fix crash on corrupt reference (fix #13448)

---

src/Mod/TechDraw/App/DrawViewPartPy.xml
src/Mod/TechDraw/App/DrawViewPartPyImp.cpp

This PR adds 2 python methods to DrawViewPart.

[TD]Expose getVisibleVertexes/getHiddenVertexes to Python

---

src/Mod/CAM/Path/Main/Gui/JobDlg.py
src/Mod/CAM/Path/Op/Gui/FeatureExtension.py
src/Mod/CAM/Path/Op/Gui/Profile.py
src/Mod/CAM/Path/Tool/Gui/Bit.py
src/Mod/CAM/Path/Tool/Gui/BitLibrary.py

various fixes for issues in 
https://github.com/FreeCAD/FreeCAD-translations/issues/253

[path] translation fixes

---

src/Mod/Fem/App/FemMeshShapeNetgenObject.cpp
src/Mod/Fem/App/FemMeshShapeNetgenObject.h
src/Mod/Fem/Gui/TaskTetParameter.cpp
src/Mod/Fem/Gui/TaskTetParameter.h
src/Mod/Fem/Gui/TaskTetParameter.ui

fixes #12716
@marioalexis84 Can you test this later? It looks ok on Ubuntu but there are known issues when compiling with Netgen (not only on my side) so it would be good if you could confirm that it works properly - actually affects the mesh.
Perhaps someone could also compile on Windows? It seems that Netgen works much better there and maybe doesn't cause those compilation issues (btw. I wonder if they are fixable).

FEM Netgen Min. Size

---

src/App/MappedName.cpp

[App] Remove unused code in `App/MappedName.cpp`

---

src/Mod/Draft/draftguitools/gui_grid.py

Draft: Draft_ToggleGrid should update the grid

---

src/Mod/Draft/DraftGui.py

Draft: Fix error when deleting first digit of input

---

src/App/GeoFeatureGroupExtension.cpp

Clean  GeoFeatureGroupExtension.cpp

App: clean

---

src/Mod/Robot/App/Trajectory.cpp

removed multiple pi definition

[MOD] removed multiple pi definition

---

src/Doc/CONTRIBUTORS

Relevant whenever my initial PR (#13559) gets merged.

Add myself as contributor

---

src/Mod/CAM/App/PathSegmentWalker.cpp

removed duplicated pi definition

[Mod] removed duplicated pi

---

src/Mod/Fem/Gui/PreCompiled.h

FEM: Add SoSwitch.h to PreCompiled

---

src/Gui/PreCompiled.h

Fixes compilation on MSVC. Also re-sort the STL list.

Gui: Add random to PreCompiled.h

---

src/Mod/TechDraw/Gui/QGTracker.h
src/Mod/TechDraw/Gui/TaskCosVertex.cpp
src/Mod/TechDraw/Gui/TaskDetail.h
src/Mod/TechDraw/Gui/TaskLeaderLine.cpp

This PR addresses issue #13409: Refactor TD/Gui/TaskDetail.h to use a proper enum.

TechDraw: Refractor tracker action with proper enum

---

src/Mod/TechDraw/App/DrawProjGroup.cpp
src/Mod/TechDraw/App/DrawProjGroup.h
src/Mod/TechDraw/App/DrawProjGroupItem.cpp
src/Mod/TechDraw/App/DrawProjGroupItem.h
src/Mod/TechDraw/App/DrawViewPart.cpp
src/Mod/TechDraw/App/DrawViewPart.h
src/Mod/TechDraw/Gui/Command.cpp
src/Mod/TechDraw/Gui/QGIProjGroup.cpp
src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_CameraOrientation.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_View.svg
src/Mod/TechDraw/Gui/TaskProjGroup.cpp
src/Mod/TechDraw/Gui/TaskProjGroup.h
src/Mod/TechDraw/Gui/TaskProjGroup.ui
src/Mod/TechDraw/Gui/ViewProviderPage.cpp
src/Mod/TechDraw/Gui/ViewProviderPage.h
src/Mod/TechDraw/Gui/ViewProviderPageExtension.cpp
src/Mod/TechDraw/Gui/ViewProviderProjGroupItem.cpp
src/Mod/TechDraw/Gui/ViewProviderProjGroupItem.h
src/Mod/TechDraw/Gui/ViewProviderViewClip.cpp
src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
src/Mod/TechDraw/Gui/Workbench.cpp

1 - We have currently 3 tools that are mutually exclusive. Insert view for shapes, insert spreadsheet and insert arch. The selection of one tool isn't allowed for other tools. Hence it is possible to have one tool inserting all those kind of views.
-> Enable the 'Insert View' tool to create spreadsheet, Arch, SVG and Images views.
-> Remove the Insert spreadsheet and insert arch tools from toolbar.
-> Update the icon to show the insert is more capable.
Note: It is noted that insert spreadsheet could offer a taskbox with more functionality and would thus warrant a taskbox. But the tool currently does not offer such possibility. When the Insert spreadsheet tool is improved and has a proper taskbox letting user type in tables directly for instance, then the tool can be added to the toolbar. …

TechDraw: Unify Insert View tools (View, ProjGroup, Sheet, Arch, svg, image)

---

src/App/Link.cpp

App: fix linked copy on change group out of scope problem

---

src/Gui/MainWindowPy.cpp

See https://forum.freecad.org/viewtopic.php?t=87097

Gui: Fix MainWindowPy::removeWindow

---

src/Mod/Draft/draftfunctions/upgrade.py
src/Mod/Draft/draftutils/gui_utils.py
src/Mod/Draft/draftutils/utils.py
src/Mod/Draft/draftviewproviders/view_layer.py

Revert the Draft WB related changes of #13294.

Draft: revert Draft WB changes from #13294

---

src/Mod/Arch/ArchWall.py

[ArchWall] fix onChanged() length to support ArchSketch

---

src/Mod/Draft/importDXF.py

Fixes #13621.
Currently the legacy DXF importer creates a main group with the DXF name if a DXF is imported into an existing FreeCAD document. For each DXF layer it then creates a sub-group (or Draft Layer) inside that main group. Objects are nested in the sub-groups (or Draft Layers).
This does not make sense for Draft Layers as they should be nested in the LayerContainer, which should be in the root of the FreeCAD document.
Both for Draft Layers and sub-groups there is the issue that if mutliple DXF files are imported in the same FreeCAD document, exising Draft Layers and sub-groups are not taken into account. For example for each DXF a new "0" group/layer is created (with a Label that is not "0" and therefore not recognized), and if there are objects on that layer a new group/layer is …

Draft: legacy DXF importer fix group and layer behavior

---

src/Gui/WorkbenchSelector.cpp

Fix small issue introduced by the move of the + tab to the beginning (#13508).
Fixes https://github.com/FreeCAD/FreeCAD/issues/13602

Core: TabBar: fix issue following #13508

---

src/App/Application.cpp
src/App/CMakeLists.txt
src/App/CleanupProcess.cpp
src/App/CleanupProcess.h
src/Base/Quantity.cpp
src/Mod/Material/App/AppMaterial.cpp
src/Mod/Material/App/MaterialManager.cpp
src/Mod/Material/App/MaterialManager.h
src/Mod/Material/App/ModelLoader.cpp
src/Mod/Material/App/ModelManager.cpp
src/Mod/Material/App/ModelManager.h

* Fix memory leak in Quantity::parse
* Add class CleanupProcess to allow to free resources when closing the application
* Fix two direct memory leaks in ModelLoader::addToTree and ModelLoader::loadLibrary
* Fix several memory leaks caused by cyclic references

Fix memory leaks

---

src/Gui/PreferencePages/DlgSettingsCacheDirectory.ui

Gui: Clarify cache directory as read-only in prefs, add Browse tooltip

---

src/App/Material.cpp
src/App/PropertyStandard.cpp
src/Gui/Application.cpp
src/Gui/ViewProviderGeometryObject.cpp
src/Gui/ViewProviderGeometryObject.h
src/Gui/ViewProviderGeometryObjectPy.xml
src/Gui/ViewProviderGeometryObjectPyImp.cpp

https://forum.freecad.org/viewtopic.php?t=87121

Gui: expose ViewProviderGeometryObject::getUserDefinedMaterial() to Python

---

src/Mod/Fem/femsolver/reportdialog.py
src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py
src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py
src/Mod/Fem/femtools/femutils.py

Fixes #13562 , existing output window example: https://github.com/FreeCAD/FreeCAD/issues/13562#issue-2254619551
using this PR:

[FEM] CCX Solver and Gmsh Mesh Task Panel Colour output improvements

---

src/App/DocumentObject.cpp
src/App/DocumentObject.h
src/App/DocumentObserver.cpp
src/App/DocumentObserver.h
tests/src/App/CMakeLists.txt
tests/src/App/DocumentObject.cpp
tests/src/App/DocumentObserver.cpp

Adding/updating code required for the future import of class `Part::SubShapeBinder`

App/Toponaming: import SubObjectT dependencies for SubShapeBinder

---

src/App/MeasureManager.cpp
src/Gui/InventorAll.h

fix precompile on lastest unified measurement

---

src/Mod/Arch/ArchBuildingPart.py

BuildingParts did not move their children if they were inside groups
fixes #13568

Arch: Fixed move with host

---

src/Gui/ArcEngine.cpp

https://github.com/FreeCAD/FreeCAD/pull/9750#issuecomment-2086478001

Gui: fix possible build failure

---

PRIVACY_POLICY.md

This PR adds a privacy policy to the source tree in response to Issue #10372.

[Admin]add privacy policy

---

cMake/FreeCAD_Helpers/SetupShibokenAndPyside.cmake

As requested in the forums: https://forum.freecad.org/viewtopic.php?p=757519#p757519

cMake: Restore wrappers for QtWebEngine

---

src/Mod/TechDraw/App/CMakeLists.txt
src/Mod/TechDraw/App/DimensionAutoCorrect.cpp
src/Mod/TechDraw/App/DimensionAutoCorrect.h
src/Mod/TechDraw/App/DimensionGeometry.cpp
src/Mod/TechDraw/App/DimensionGeometry.h
src/Mod/TechDraw/App/DimensionReferences.cpp
src/Mod/TechDraw/App/DimensionReferences.h
src/Mod/TechDraw/App/DrawUtil.cpp
src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/App/DrawViewDimension.h
src/Mod/TechDraw/App/DrawViewPart.cpp
src/Mod/TechDraw/App/Geometry.h
src/Mod/TechDraw/App/GeometryMatcher.cpp
src/Mod/TechDraw/App/GeometryMatcher.h
src/Mod/TechDraw/App/GeometryObject.cpp
src/Mod/TechDraw/App/ShapeUtils.cpp
src/Mod/TechDraw/App/ShapeUtils.h

This PR implements a fix where autocorrect was not handling scaled and rotated reference geometry properly.

[TD]fix dimension autocorrect

---

src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/SketcherTests/TestSketcherSolver.py

Ensure we set up a valid sketch even with invalid external references

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

Sketcher: Dimension tool : add arc length following #12602
@FlachyJoe

Sketcher: Dimension tool : add arc length following #12602

---

src/Gui/MainWindow.cpp

The Help module is now part of FreeCAD. So, there is no need any more to run the addon manager

Gui: simplify MainWindow::showDocumentation()

---

src/Mod/Start/Gui/GeneralSettingsWidget.cpp

Start: Fix selection and ordering of language

---

src/Mod/Sketcher/Gui/DrawSketchController.h

Sketcher: fix OVP placement issue #13827

---

src/Mod/Material/App/MaterialManagerPy.xml
src/Mod/Material/App/MaterialManagerPyImpl.cpp
src/Mod/Material/App/MaterialPy.xml
src/Mod/Material/App/MaterialPyImpl.cpp
src/Mod/Material/App/ModelLibrary.cpp
src/Mod/Material/CMakeLists.txt
src/Mod/Material/TestMaterialsApp.py
src/Mod/Material/materialtests/TestMaterialCreation.py

Expands the Python API to allow for material creation. With test cases.

Material: Expanded Python API

---

src/Mod/Sketcher/App/SketchObject.cpp

Mistaken enabling of known bad code

Fix #13858

---

src/Gui/PythonWrapper.cpp
src/Gui/ToolBarManager.cpp
src/Gui/ToolBarManager.h
src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/App/PreCompiled.h
src/Mod/Assembly/Gui/PreCompiled.h
src/Mod/Assembly/Gui/ViewProviderAssembly.cpp

* Fix build failures and warnings
* Fix linter warnings
* Refactor several methods of ToolBarManager

Fix build failure and warnings

---

src/Mod/Test/CMakeLists.txt
src/Mod/Test/TestPerf.py
tools/profile/perftest.sh

Small tweak to test script to support future compares of file contents

Toponaming: Support saving the tnp recalculated file in profile testing

---

src/Mod/PartDesign/App/ShapeBinder.cpp

This fixes the reported regression: https://forum.freecad.org/viewtopic.php?t=87229

PD: Fix ShapeBinder::execute() if Support is empty

---

src/Gui/Tree.cpp
src/Gui/ViewProvider.h
src/Gui/ViewProviderSuppressibleExtension.cpp

Introduce a signal slot for tree item highlight change.

Fix #13107

---

src/App/DocumentObjectPyImp.cpp
src/App/DocumentPyImp.cpp
src/App/PropertyContainerPyImp.cpp
src/App/PropertyStandard.cpp
src/Base/RotationPyImp.cpp
src/Gui/ViewProviderPyImp.cpp
src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
src/Mod/TechDraw/App/PropertyCenterLineList.cpp
src/Mod/TechDraw/App/PropertyCosmeticEdgeList.cpp
src/Mod/TechDraw/App/PropertyCosmeticVertexList.cpp
src/Mod/TechDraw/App/PropertyGeomFormatList.cpp

Fix memory leaks with PySequence_GetItem

---

src/Mod/Fem/Gui/TaskFemConstraintDisplacement.ui
src/Mod/Fem/Gui/TaskFemConstraintFixed.ui
src/Mod/Fem/Gui/TaskFemConstraintForce.ui
src/Mod/Fem/Gui/TaskFemConstraintTemperature.ui

FEM: Change the misleading constraint descriptions regarding the geometry selection

---

src/Mod/Measure/Gui/QuickMeasure.cpp

https://forum.freecad.org/viewtopic.php?t=87647

Mesure: Ignore ValueError exceptions in quick measure

---

src/Mod/Part/App/AttachExtension.cpp
src/Mod/Part/App/PartFeature.cpp
src/Mod/PartDesign/App/FeatureExtrude.cpp
src/Mod/PartDesign/App/FeatureExtrude.h
src/Mod/PartDesign/App/FeatureFillet.cpp
src/Mod/PartDesign/App/FeatureLoft.cpp
src/Mod/PartDesign/App/FeaturePad.cpp
src/Mod/PartDesign/App/FeaturePocket.cpp
src/Mod/PartDesign/App/FeaturePocket.h
src/Mod/PartDesign/App/FeatureRevolution.cpp
src/Mod/PartDesign/App/FeatureSketchBased.cpp
src/Mod/PartDesign/App/FeatureSketchBased.h
src/Mod/PartDesign/PartDesignTests/TestPocket.py
src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h

GetElementName is just relocated within the file to ease side-by-side comparisons.  No changes to it.

Toponaming: Bring in Chamfer, Fillet code and add tests

---

src/Mod/CAM/Path/Main/Gui/Job.py
src/Mod/CAM/Path/Main/Sanity/Sanity.py

Fix small sanity error
Fix small error with job visibility

fix minor bugs with sanity report and job visibility

---

src/Mod/Draft/draftguitools/gui_lineslope.py

Forum topic:
https://forum.freecad.org/viewtopic.php?t=87686

Draft: Draft_Slope input did not obey Decimals pref

---

src/Mod/Draft/draftguitools/gui_split.py

Fixes #13951.
Regression introduced by #12261.

Draft: Draft_Split fix unhandled exception

---

src/Mod/BIM/ArchStructure.py
src/Mod/BIM/bimcommands/BimWall.py
src/Mod/BIM/bimcommands/BimWindow.py

Deletes the trackers only after recompute
Fixes #13915

Arch: Fixed trackers ending too soon

---

.github/ISSUE_TEMPLATE/PROBLEM_REPORT.yml
.github/labels.yml

Update GitHub Actions for Arch->BIM rename

---

src/Mod/Draft/draftguitools/gui_arcs.py
src/Mod/Draft/draftguitools/gui_arrays.py
src/Mod/Draft/draftguitools/gui_base.py
src/Mod/Draft/draftguitools/gui_base_original.py
src/Mod/Draft/draftguitools/gui_beziers.py
src/Mod/Draft/draftguitools/gui_grid.py
src/Mod/Draft/draftguitools/gui_hatch.py
src/Mod/Draft/draftguitools/gui_layers.py
src/Mod/Draft/draftguitools/gui_planeproxy.py
src/Mod/Draft/draftguitools/gui_selectplane.py
src/Mod/Draft/draftguitools/gui_styles.py
src/Mod/Draft/draftutils/gui_utils.py

Draft: improved IsActive behavior

---

src/Mod/TechDraw/Templates/A0_Landscape_ISO5457_advanced.svg
src/Mod/TechDraw/Templates/A0_Landscape_ISO5457_minimal.svg
src/Mod/TechDraw/Templates/A1_Landscape_ISO5457_advanced.svg
src/Mod/TechDraw/Templates/A1_Landscape_ISO5457_minimal.svg
src/Mod/TechDraw/Templates/A2_Landscape_ISO5457_advanced.svg
src/Mod/TechDraw/Templates/A2_Landscape_ISO5457_minimal.svg
src/Mod/TechDraw/Templates/A3_Landscape_ISO5457_advanced.svg
src/Mod/TechDraw/Templates/A3_Landscape_ISO5457_minimal.svg
src/Mod/TechDraw/Templates/A4_Landscape_ISO5457_advanced.svg
src/Mod/TechDraw/Templates/A4_Landscape_ISO5457_minimal.svg
src/Mod/TechDraw/Templates/A4_Portrait_ISO5457_advanced.svg
src/Mod/TechDraw/Templates/A4_Portrait_ISO5457_minimal.svg
src/Mod/TechDraw/Templates/ISO 5457/ISO7200_titleblock_1_minimal.svg
src/Mod/TechDraw/Templates/ISO 5457/ISO7200_titleblock_2.svg
src/Mod/TechDraw/Templates/ISO 5457/ISO7200_titleblock_3_advanced.svg
src/Mod/TechDraw/Templates/ISO 5457/ISO7200_titleblock_4.svg
src/Mod/TechDraw/Templates/ISO 5457/ISO7200_titleblock_5_maximal.svg

Added the autofill attributes added by PR #5903 to the ISO template series.

[TechDraw] Added freecad:autofill attribute to ISO templates

---

src/Mod/TechDraw/App/Preferences.cpp
src/Mod/TechDraw/App/Preferences.h
src/Mod/TechDraw/Gui/Command.cpp
src/Mod/TechDraw/Gui/CommandDecorate.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvancedImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawColorsImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensionsImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneralImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawHLRImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawScaleImp.cpp
src/Mod/TechDraw/Gui/QGISectionLine.cpp
src/Mod/TechDraw/Gui/QGISectionLine.h
src/Mod/TechDraw/Gui/QGIViewPart.cpp
src/Mod/TechDraw/Gui/TaskHatch.cpp
src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
src/Mod/TechDraw/Gui/ViewProviderViewPart.h

This PR implements fixes for a number of preference related requests, including issues #12686 and #12239.
- section line convention label
- remove superfluous save/restore on changeEvent
- change default scrub count
- add preference for default symbol dir
- add preference for display of section cut line

[TD]assorted Preference updates (fix #12686, #12239)

---

src/Mod/AddonManager/Resources/icons/compact_view.svg
src/Mod/AddonManager/Resources/icons/composite_view.svg
src/Mod/AddonManager/Resources/icons/expanded_view.svg
src/Mod/AddonManager/Resources/icons/sort_ascending.svg
src/Mod/AddonManager/Resources/icons/sort_descending.svg

split of https://github.com/FreeCAD/FreeCAD/pull/13564 as follow up for https://github.com/FreeCAD/FreeCAD/pull/14041
@chennes @0penBrain FYI, does this work?

Addon manager: update icons for legibility on dark themes

---

src/Mod/Assembly/Gui/Resources/icons/Assembly_ExplodedView.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_ExplodedViewGroup.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_ExportASMT.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_JointGroup.svg
src/Mod/Assembly/Gui/Resources/icons/Assembly_SolveAssembly.svg
src/Mod/Assembly/InitGui.py
src/Mod/Assembly/JointObject.py

Consistency following https://github.com/FreeCAD/FreeCAD/pull/13865
- update assembly icons to be consistent with main updates
- add commands to menu/toolbar.

UI: update assembly icons to be consistent with main updates

---

src/Gui/SoTextLabel.cpp
src/Gui/SoTextLabel.h
src/Gui/TaskMeasure.cpp
src/Mod/Measure/App/MeasureArea.h
src/Mod/Measure/App/MeasureLength.h
src/Mod/Measure/App/MeasurePosition.h
src/Mod/Measure/App/MeasureRadius.h
src/Mod/Measure/Gui/AppMeasureGui.cpp
src/Mod/Measure/Gui/DlgPrefsMeasureAppearanceImp.ui
src/Mod/Measure/Gui/Resources/Measure.qrc
src/Mod/Measure/Gui/Resources/icons/Measurement-Angle.svg
src/Mod/Measure/Gui/Resources/icons/Measurement-Area.svg
src/Mod/Measure/Gui/Resources/icons/Measurement-CenterOfMass.svg
src/Mod/Measure/Gui/Resources/icons/Measurement-Distance.svg
src/Mod/Measure/Gui/Resources/icons/Measurement-Group.svg
src/Mod/Measure/Gui/Resources/icons/Measurement-Inertia.svg
src/Mod/Measure/Gui/Resources/icons/Measurement-Position.svg
src/Mod/Measure/Gui/Resources/icons/Measurement-Radius.svg
src/Mod/Measure/Gui/Resources/icons/Measurement-Volume.svg
src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp
src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp
src/Mod/Measure/Gui/ViewProviderMeasureBase.h
src/Mod/Measure/Gui/ViewProviderMeasureDistance.cpp

This PR addresses #13710
It adds icons to:
- the labels in the 3d view
- the elements in the tree view
- the measurement group in the tree view
Icons by @maxwxyz

Add measurement icons

---

src/Gui/SoDatumLabel.cpp
src/Gui/SoDatumLabel.h

* Fix possible crashes with SoDatumLabel
* Fix linter warnings in SoDatumLabel
* Refactor SoDatumLabel::GLRender()

Gui: Fix datum label

---

src/Gui/Tree.cpp

Gray out all columns in the tree if an item is invisible

---

src/Gui/ToolBarManager.cpp
src/Gui/ToolBarManager.h

Fixes few issues with code found by @wwmayer

Gui: Fix ToolBarManager review remarks

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Fix second bug described in https://github.com/FreeCAD/FreeCAD/issues/13629

Sketcher: Fix line to arc point distance movement problem

---

src/Mod/Fem/Gui/TaskFemConstraintRigidBody.ui

Following #13921 and #14002, now the task panel selection tip of the newly implemented rigid body constraint also needs to be updated

FEM: Update selection tip of rigid body constraint

---

src/Mod/Sketcher/App/Sketch.cpp
src/Mod/Sketcher/App/Sketch.h

Split updateGeometry() into smaller blocks where each geometry type is handled in a separate function.

Sketch: Refactor Sketch::updateGeometry()

---

src/Mod/Import/App/ImportOCAF.cpp

mod: clean ImportOCAF.cpp

---

src/Mod/TechDraw/Gui/CommandCreateDims.cpp

Fix typo in TechDraw tooltip

---

src/Mod/BIM/Resources/ui/ArchMultiMaterial.ui
src/Mod/BIM/Resources/ui/dialogCreateProject.ui
src/Mod/BIM/Resources/ui/dialogImport.ui
src/Mod/BIM/Resources/ui/dialogPreflight.ui
src/Mod/BIM/Resources/ui/dialogSetup.ui
src/Mod/BIM/Resources/ui/dialogSpaces.ui
src/Mod/BIM/Resources/ui/dialogWelcome.ui

Fix #14161
Fix some UI typos, use US English and remove WIP notice in Welcome dialog

BIM : fix typos in UI strings

---

src/Mod/Import/App/ImportOCAF.cpp

fix compile warning: removed unused variable found_face_color

[mod:import] removed unused variable

---

src/Mod/BIM/InitGui.py
src/Mod/BIM/Resources/Arch.qrc
src/Mod/BIM/Resources/icons/preferences-bim.svg
src/Mod/BIM/Resources/ui/dialogSetup.ui
src/Mod/BIM/Resources/ui/dialogWelcome.ui
src/Mod/BIM/Resources/ui/preferences-ifc-export.ui
src/Mod/BIM/Resources/ui/preferences-ifc.ui
src/Mod/BIM/bimcommands/BimSetup.py

* Reworded welcome screen, removed "update" section
* Removed Webtools and Start option from setup dialog - fixes #14179
* Renamed Arch preferecnes to BIM - fixes #14121
* Moved NativeIFC preferences to BIM - fixes #14137

BIM: Reworked preferences and setup screens

---

src/Mod/BIM/ArchWall.py

PR #13648 was wrongly left out from the big BIM merge. This PR re-adds it

BIM: Reapplied #13648

---

src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp
src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp
src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.h
src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheetPyImp.cpp

Sheet: Make ViewProviderSpreadsheet.h self-contained

---

src/Mod/Help/dlgPreferencesHelp.ui

Detected by Carlo D on CrowdIn

Help: Fix typo whlle -> while

---

src/Mod/CAM/PathSimulator/AppGL/EndMill.cpp
src/Mod/CAM/PathSimulator/AppGL/SimShapes.cpp
src/Mod/CAM/PathSimulator/AppGL/SimShapes.h

[Cam] fix warning

---

src/Mod/BIM/Arch.py

Bug reported at:
https://github.com/FreeCAD/FreeCAD/issues/14262

[Arch] Fix bug at Arch.py : makeStairs & makeRailing

---

src/Mod/BIM/bimcommands/BimViews.py

BIM: Fixed decimal separator error

---

src/Mod/BIM/bimcommands/BimSetup.py

BIM: Fixed grid settings in setup tool

---

src/Mod/CAM/CMakeLists.txt
src/Mod/CAM/Gui/Resources/panels/ToolBitSelector.ui
src/Mod/CAM/Path/Base/Util.py
src/Mod/CAM/Path/Tool/Bit.py
src/Mod/CAM/Path/Tool/Gui/BitLibrary.py

Create a more useful tooltip
fix missing dovetail shape
Add a combobox to the dock to simplify library changing

Stage 1 improving the CAM tool system

---

src/Mod/BIM/nativeifc/ifc_openshell.py

... to allow starting the IfcOpenShell installer

Fix translate function typo for IfcOpenShell installer

---

src/Mod/Draft/draftobjects/facebinder.py

Fixes #14242.
In the current dev fusing an empty shape with a face or solid no longer works (probably introduced with #14169). The reason for starting with an empty shape was the assumption that the end result would then always have a default placement. But that is only correct if multiple objects are fused.
In the new version of the code fusing no longer starts with an empty shape. The default placement issue is solved by always returning a compound.
Additionally the value for the Area property is now taken after offsetting and fusing the faces.

Draft: update fuse behavior in facebinder.py

---

src/Mod/Fem/Gui/Command.cpp

Fem: Don't hide input filter with DataAtPoint and DataAlongLine - fixes #14135

---

src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp

Fixes red points issues described in #13849

Sketcher: Fixes red points issue #13849

---

src/App/Application.cpp
src/Base/Parameter.cpp
src/Base/Parameter.h
src/Gui/StartupProcess.cpp
src/Gui/StartupProcess.h

Fix still possible race conditions as described here: https://github.com/FreeCAD/FreeCAD/pull/13522#issuecomment-2091671952

Core: Fix possible race conditions when reading or writing config file

---

src/Mod/Fem/Gui/TaskFemConstraintRigidBody.cpp
src/Mod/Fem/Gui/TaskFemConstraintRigidBody.h

Fixes #14172
@FEA-eng  @maxwxyz

Fem: Update ReferenceNode property from task dialog - fixes #14172

---

src/Mod/MeshPart/App/AppMeshPart.cpp
src/Mod/MeshPart/App/AppMeshPartPy.cpp
src/Mod/MeshPart/App/CurveProjector.cpp
src/Mod/MeshPart/App/MeshAlgos.cpp
src/Mod/MeshPart/App/MeshAlgos.h
src/Mod/MeshPart/App/MeshFlatteningBoostPython.cpp
src/Mod/MeshPart/App/MeshFlatteningNurbs.cpp

[MeshPart] clean

---

src/Gui/Icons/zoom-all.svg

Following [PR 13932](https://github.com/FreeCAD/FreeCAD/pull/13932) (based on Forum and Discord discussions)
Second PR

UI : update zoom-all.svg icon

---

src/Mod/BIM/bimcommands/BimTDPage.py

BIM: Fixed missing import in TDView

---

src/Gui/Icons/Std_DlgParameter.svg
src/Gui/Icons/document-new.svg
src/Gui/Icons/edit-copy.svg
src/Gui/Icons/edit-cut.svg
src/Gui/Icons/edit-delete.svg
src/Gui/Icons/edit-paste.svg
src/Gui/Icons/preferences-display.svg
src/Gui/Icons/preferences-general.svg
src/Gui/Icons/preferences-system.svg
src/Gui/Icons/window-new.svg

Updated GUI icons for consistency:
- new icons for cut, copy, paste, delete
- new new document icon according to DWG discussion (the + replaces the sun), TechDraw will be updated separately
- new icons for preferences
- new icon for parameters (using the same gear as the new logo)
Previously:
This PR:

UI: Update icons for consistency

---

src/Mod/Draft/WorkingPlane.py

Draft: Enable TNP in SelectPlane

---

src/Mod/Sketcher/App/PythonConverter.cpp

Sketcher: Fix copy of geo constrained to axis. Fixes #14233

---

src/Gui/Document.cpp

More details here
https://forum.freecad.org/viewtopic.php?t=70256#p761628

Use for predefined filename string its Label value

---

src/Mod/Sketcher/App/SketchAnalysis.cpp
src/Mod/Sketcher/App/SketchAnalysis.h
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/CMakeLists.txt
src/Mod/Sketcher/SketcherTests/TestSketchValidateCoincidents.py
src/Mod/Sketcher/TestSketcherApp.py

* Add test case for degenerated geometry
* Add test case for deleting constraints with external geometry
* Add test case for validating constraints

[Sketcher] Add new Fix Missing Coincident test

---

src/Mod/BIM/bimcommands/BimWall.py

BIM: Fixed wall paramerers

---

src/Mod/BIM/utils/buildPsets.py

BIM: Fix buildingsmart-tech.org url links

---

src/Mod/BIM/ArchWall.py
src/Mod/Draft/draftgeoutils/offsets.py

(Similar to Width and Align per edge features)
ArchWall.py - Add Override Offset property & ground work for Multi-Layer Wall 
Offsets.py - Add offset per edge support to ArchWall
Forum Discussion :
- https://forum.freecad.org/viewtopic.php?p=759634#p759634

[ArchWall] Add Offset per Edge Feature

---

src/Mod/BIM/importers/importSHP.py

Changed obsolete import - Fixes #14261

BIM: Fixed import in importSHP

---

src/Mod/Draft/draftguitools/gui_move.py
src/Mod/Draft/draftguitools/gui_rotate.py

Fixes a collateral problem reported in issue #12624

Draft: Fixed ghosts vanishing when using mouse delay

---

src/Mod/PartDesign/App/FeatureSketchBased.cpp

Thanks for noting this, @FlachyJoe

Toponaming: Restore use of AttachmentSupport

---

src/Mod/PartDesign/Gui/Command.cpp

Toponaming: fix bug with points in sketches

---

src/Mod/TechDraw/App/BalloonPropEnum.cpp
src/Mod/TechDraw/App/BalloonPropEnum.h
src/Mod/TechDraw/App/CMakeLists.txt
src/Mod/TechDraw/App/MattingPropEnum.cpp
src/Mod/TechDraw/App/MattingPropEnum.h
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui
src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
src/Mod/TechDraw/Gui/DrawGuiUtil.h

This PR implements fixes for preference issues reported here:  https://forum.freecad.org/viewtopic.php?p=756962#p756962  and  here: https://forum.freecad.org/viewtopic.php?t=87995

[TD]Icons in dark scheme

---

src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h

Currently OVP (On-View Parameters / Quick Dimensions) only allows for constraining circles with radius constraint, while circles typically are constrained with diameter.
This PR uses the preferred setting and constrains the circle accordingly:

[Sketcher] Respect Auto/Diameter/Radius settings for Circles when using OVP

---

src/Mod/Sketcher/App/SketchAnalysis.cpp
src/Mod/Sketcher/App/SketchAnalysis.h
src/Mod/Sketcher/App/SketchObject.cpp

* Move helper classes to anonymous namespace
* Refactor detectMissingPointOnPointConstraints
* Refactor makeMissingPointOnPoint
* Refactor makeMissingVerticalHorizontal
* Refactor makeMissingEquality
* Refactor autoconstraint
* Refactor detectMissingEqualityConstraints
* Fix linter warnings

Sketch: Refactor SketchAnalysis

---

src/Mod/Material/Gui/MaterialTreeWidget.cpp

Remove notification when a folder is selected rather than a material

Materials: Tree Widget selection change

---

src/Mod/TechDraw/Gui/QGVPage.cpp

Smart Dimension: Fix cannot pan with middle mouse click. Fixes #14326

TechDraw: Smart Dimension: Fix cannot pan with middle mouse click.

---

src/Mod/Material/App/MaterialManagerPy.xml
src/Mod/Material/App/MaterialManagerPyImpl.cpp

API changes to inherit a material

Materials: Inheritance API

---

src/Mod/BIM/bimcommands/BimSetup.py

@yorikvanhavre please see feedback from forum https://forum.freecad.org/viewtopic.php?p=763064#p763064 this PR is just to assist in the IfcOpenShell install for new users who are not using a packaged version of FreeCAD.

[BIM] Add fallback ifcOpenShell installation fix for Python 3.10, 3.11 & 3.12 systems

---

src/Mod/Draft/draftobjects/layer.py

There are two unnecessary Layer warnings:
1. A 'might break' warning when deleting an object nested in a layer.
2. An 'out of scope' warning for objects also nested in f.e. a Std_Part.
To avoid them the Group property type was changed to `App::PropertyLinkListHidden`.

Draft: Fix two Layer warnings

---

src/Base/UnitsSchemaInternal.cpp
src/Base/UnitsSchemaMKS.cpp
src/Mod/Fem/CMakeLists.txt
src/Mod/Fem/Gui/Resources/ui/BodyHeatSource.ui
src/Mod/Fem/femmesh/meshsetsgetter.py
src/Mod/Fem/femmesh/meshtools.py
src/Mod/Fem/femobjects/constraint_bodyheatsource.py
src/Mod/Fem/femsolver/calculix/write_constraint_bodyheatsource.py
src/Mod/Fem/femsolver/calculix/writer.py
src/Mod/Fem/femsolver/elmer/equations/heat_writer.py
src/Mod/Fem/femtaskpanels/task_constraint_bodyheatsource.py
src/Mod/Fem/femtools/membertools.py

@FEA-eng 
The conversion from power per unit mass to power per unit volume is done internally according to the material density of the selected solid.

Fem: Add body heat source to CalculiX writer - fixes #11650

---

src/Mod/PartDesign/App/FeatureExtrude.h
src/Mod/PartDesign/Gui/AppPartDesignGui.cpp
src/Mod/PartDesign/Gui/CMakeLists.txt
src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
src/Mod/PartDesign/Gui/TaskExtrudeParameters.h
src/Mod/PartDesign/Gui/TaskPadParameters.cpp
src/Mod/PartDesign/Gui/TaskPadParameters.h
src/Mod/PartDesign/Gui/TaskPadPocketParameters.ui
src/Mod/PartDesign/Gui/TaskPocketParameters.cpp
src/Mod/PartDesign/Gui/TaskPocketParameters.h
src/Mod/PartDesign/Gui/TaskSketchBasedParameters.cpp
src/Mod/PartDesign/Gui/TaskTransformedParameters.h
src/Mod/PartDesign/Gui/ViewProviderDressUp.cpp
src/Mod/PartDesign/Gui/ViewProviderDressUp.h
src/Mod/PartDesign/Gui/ViewProviderExtrude.cpp
src/Mod/PartDesign/Gui/ViewProviderExtrude.h
src/Mod/PartDesign/Gui/ViewProviderPad.cpp
src/Mod/PartDesign/Gui/ViewProviderPocket.cpp
src/Mod/PartDesign/Gui/ViewProviderPocket.h

This adds UI for the Up To Shape feature in #11392 - must be merged after. 
For now it supports selecting only one shape and set of faces as it would be too hard to implement UI that supports the list in such short time frame. I'm also very not happy with how much code it required, the selection UI must be reworked in the future: https://github.com/FreeCAD/FreeCAD/issues/14432
https://github.com/FreeCAD/FreeCAD/assets/747404/33731d59-9c45-40cd-85e4-1b502da35285

GUI: Add UI for Up To Shape feature

---

src/Mod/PartDesign/App/FeatureRevolution.cpp
src/Mod/Sketcher/App/SketchObject.cpp

[mod] clean

---

src/Mod/Sketcher/Gui/SketcherSettingsAppearance.ui

Fix https://github.com/FreeCAD/FreeCAD/issues/14438

Sketcher: Fix default value of dimConstrDeactivatedColor

---

src/Mod/Part/App/Geometry.cpp
src/Mod/Sketcher/App/Constraint.cpp
src/Mod/TechDraw/App/CenterLine.cpp
src/Mod/TechDraw/App/Cosmetic.cpp
src/Mod/TechDraw/App/CosmeticVertex.cpp
src/Mod/TechDraw/App/Geometry.cpp

Guard all uses of basic_random_generator for thread safety

---

src/Gui/DlgPropertyLink.cpp

Fix SubElements selection for PropertyLinkSubList

---

src/Mod/PartDesign/App/FeatureExtrude.cpp
src/Mod/PartDesign/PartDesignTests/TestPad.py

Fix can't pad a sketch on datum plane

---

src/Base/Interpreter.cpp

The current venv code uses an old-style venv mechanism and does not work with recent venvs. This PR adds corrected support for Python 3.11 and later.

Base: Support virtual environment in Py>=3.11

---

src/Mod/BIM/bimcommands/BimCutPlane.py

To address issue reported at https://forum.freecad.org/viewtopic.php?t=87750

BIM: add missing imports for Arch_CutPlane

---

src/Mod/CAM/libarea/kurve/Finite.cpp

[MOD] clean Finite.cpp

---

src/Main/MainPy.cpp

[Main] MainPy.cpp clean

---

src/Mod/BIM/ArchPanel.py
src/Mod/BIM/bimcommands/BimPanel.py

BIM: Fix Arch Panel imports

---

src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h

Fix https://github.com/FreeCAD/FreeCAD/issues/14645

Sketcher: Fix circle diameter OVP

---

src/Mod/TechDraw/App/DrawViewPart.cpp
src/Mod/TechDraw/App/Geometry.cpp
src/Mod/TechDraw/Gui/Grabber3d.cpp
src/Mod/TechDraw/Gui/TaskActiveView.cpp
src/Mod/TechDraw/Gui/TaskActiveView.h

This PR implements fixes for ActiveView issues reported here: #14641 and here: https://forum.freecad.org/viewtopic.php?t=88393.
This PR also includes a minor fix for #12110 that produces a message when no geometry is retrieved from HLR.

[TD]Fix ActiveView crop fields

---

src/Mod/TechDraw/App/DrawDimHelper.cpp
src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/DimensionValidators.cpp

This PR implements a fix for a problem reported here: 
https://forum.freecad.org/viewtopic.php?t=88440
The program was confused by having both 2d and 3d geometry in the selection.

[TD]fix segfault on confused selection

---

src/Gui/PythonWrapper.cpp
src/Gui/PythonWrapper.h
src/Gui/TaskView/TaskDialogPython.cpp

Fix conversion of StandardButton enum and int

---

src/Mod/Fem/femsolver/calculix/write_constraint_rigidbody.py
src/Mod/Fem/femsolver/calculix/write_step_output.py

Fem: Write reaction force from rigid body nodes - fixes #14558

---

src/Mod/Fem/App/FemMesh.cpp
src/Mod/Fem/App/FemMeshPy.xml

Fem: Force z=0 for plane stress, plane strain and axisymmetric elements in writeABAQUS - fixes #12875

---

src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
src/Mod/Assembly/Gui/ViewProviderAssembly.h
src/Mod/Assembly/JointObject.py

Fixes https://github.com/FreeCAD/FreeCAD/issues/14597
When user deletes a component, also delete the joints.

Assembly: deleting a component deletes its joints.

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/App/AssemblyObject.h

- Fix part of https://github.com/FreeCAD/FreeCAD/issues/14443
- Fix https://github.com/FreeCAD/FreeCAD/issues/14444 by updating the solver where a fix was posted
- Fix error message due to impossibility to swap const char*

Assembly: Fix bug of distance joint between point and circle

---

src/Gui/Document.cpp
src/Gui/Document.h
src/Gui/DocumentPy.xml
src/Gui/DocumentPyImp.cpp
src/Gui/Tree.cpp
src/Mod/Assembly/CommandInsertLink.py
src/Mod/Assembly/UtilsAssembly.py
src/Mod/Test/CMakeLists.txt
src/Mod/Test/GuiDocument.py
src/Mod/Test/InitGui.py

Core: Add Gui::Document::getTreeRootObjects() Fixes #14373

---

src/Mod/Sketcher/App/SketchObject.cpp

Fix importing arcs and elliptical arcs as external geometry:
- Fix importing elliptical arcs issue #8700.
- Fix importing arcs into sketches in the case where they project as elliptical arcs.
- Fix a discontinuity that happens when an external arc projects down to a segment. The segment end points should not jump around if the projection angle changes from 89.9 to 90 degrees.
- When handling external geometry: compare points for equality in a consistent way and remove some dead code.
Example handling of various external geometry arcs:
Note 1-Circle and 2-Arc show the special case where the angle between the sketches is just right to exactly project from an Ellipse and an Elliptical Arc. (The BSplines with green markings are from checking Parabolas and Hyperbolas still work as previously)

Sketcher: Fix importing arcs and elliptical arcs as external geometry

---

src/Mod/Draft/draftguitools/gui_hatch.py

To make using Esc work properly the task panel should have the focus.

Draft: Draft_Hatch put focus on task panel

---

src/Mod/Part/App/AttachExtension.cpp
src/Mod/Part/App/AttachExtension.h

Part: Fix AttachmentSupport when loading files from previous versions

---

src/Mod/Fem/Gui/PreCompiled.h
src/Mod/Sketcher/App/PreCompiled.h

Some files missing from PreCompiled.h from this morning's PR Review Meeting merges.

Fem/Sketcher: Fix missing PreCompiled.h files

---

src/Mod/Fem/App/AppFem.cpp
src/Mod/Fem/App/FemSetElementNodesObject.cpp
src/Mod/Fem/App/FemSetElementNodesObject.h
src/Mod/Fem/Gui/AppFemGui.cpp
src/Mod/Fem/Gui/Command.cpp
src/Mod/Fem/Gui/TaskCreateElementSet.cpp
src/Mod/Fem/Gui/TaskCreateElementSet.h
src/Mod/Fem/Gui/TaskDlgCreateElementSet.cpp
src/Mod/Fem/Gui/TaskDlgCreateElementSet.h
src/Mod/Fem/Gui/ViewProviderSetElementNodes.cpp
src/Mod/Fem/Gui/ViewProviderSetElementNodes.h
src/Mod/Fem/Gui/Workbench.cpp

* Fix copyright notices
* Fix linking errors
* Refactor DefineNodesCallback and DefineElementsCallback
* Clean-up code

FEM: Fix linking errors & clean-up code

---

src/Mod/Draft/draftviewproviders/view_point.py

Fixes #14804
Added (also don't make sense for a point object):
* AngularDeflection
* DrawStyle
* Pattern
* PatternSize
Removed:
* DiffuseColor (property no longer exists)
* LineMaterial (already hidden by default)

Draft: Fix onChanged in view_point.py

---

src/Mod/TechDraw/Gui/QGIWeldSymbol.cpp

This PR implements a fix for weld symbol positioning as reported here: https://forum.freecad.org/viewtopic.php?t=88513&sid=80da6d71e9826c1ea33c340bef16f4cc

[TD]fix weld symbol position

---

src/Gui/SoFCUnifiedSelection.cpp
src/Gui/View3DInventorSelection.cpp

Only adjust found element names

---

src/Doc/CONTRIBUTORS

Add myself as a contributor

---

src/Mod/Fem/femguiutils/selection_widgets.py
src/Mod/Fem/femtaskpanels/task_constraint_bodyheatsource.py
src/Mod/Fem/femtaskpanels/task_constraint_centrif.py
src/Mod/Fem/femtaskpanels/task_constraint_currentdensity.py
src/Mod/Fem/femtaskpanels/task_constraint_electrostaticpotential.py
src/Mod/Fem/femtaskpanels/task_constraint_flowvelocity.py
src/Mod/Fem/femtaskpanels/task_constraint_initialflowvelocity.py
src/Mod/Fem/femtaskpanels/task_constraint_initialpressure.py
src/Mod/Fem/femtaskpanels/task_constraint_magnetization.py
src/Mod/Fem/femtaskpanels/task_constraint_sectionprint.py
src/Mod/Fem/femtaskpanels/task_constraint_tie.py
src/Mod/Fem/femtaskpanels/task_element_fluid1D.py
src/Mod/Fem/femtaskpanels/task_element_geometry1D.py
src/Mod/Fem/femtaskpanels/task_element_geometry2D.py
src/Mod/Fem/femtaskpanels/task_element_rotation1D.py
src/Mod/Fem/femtaskpanels/task_material_common.py
src/Mod/Fem/femtaskpanels/task_mesh_boundarylayer.py
src/Mod/Fem/femtaskpanels/task_mesh_group.py
src/Mod/Fem/femtaskpanels/task_mesh_region.py

Fixes #14001.
Electromagnetic, fluid, and body heat source constraints have the same problem. This pull request fixes it for all of them.
@FEA-eng

Fem: Remove selection observer - fixes #14001

---

src/Mod/CAM/Path/Tool/Gui/BitLibrary.py

Toolcreatebug

---

src/Mod/CAM/App/Area.cpp
src/Mod/CAM/Path/Main/Sanity/Sanity.py
src/Mod/CAM/Path/Op/Adaptive.py
src/Mod/CAM/Path/Op/Area.py
src/Mod/CAM/Path/Op/Base.py
src/Mod/CAM/Path/Op/Deburr.py
src/Mod/CAM/Path/Op/Gui/Base.py
src/Mod/CAM/Path/Op/Gui/FeatureExtension.py
src/Mod/CAM/Path/Op/Gui/Probe.py
src/Mod/CAM/Path/Op/Gui/ThreadMilling.py
src/Mod/CAM/Path/Op/Gui/Vcarve.py
src/Mod/CAM/Path/Op/PocketBase.py
src/Mod/CAM/Path/Op/Probe.py
src/Mod/CAM/Path/Op/Slot.py
src/Mod/CAM/Path/Op/Vcarve.py
src/Mod/CAM/Path/Tool/Gui/BitLibrary.py

fixes:  https://github.com/Ondsel-Development/FreeCAD/issues/93 fixes https://github.com/Ondsel-Development/FreeCAD/issues/87 fixes https://github.com/Ondsel-Development/FreeCAD/issues/88
fix threadmilling error if not proper tool
fix vcarve error if no proper tool
fix probe error if no proper tool
fix deburr error if no base geometry
Fix adaptive op error if no base geometry

Fixing 'red ink' bugs in CAM

---

src/Mod/BIM/Resources/ui/preferencesNativeIFC.ui
src/Mod/BIM/nativeifc/ifc_import.py

BIM: fix SwitchWB preference by switching to BIM WB

---

src/Mod/BIM/bimcommands/BimViews.py

BIM: Simplificed BimViews.getTreeViewItem

---

src/Mod/Material/materialtests/TestMaterialFilter.py
src/Mod/Part/TestPartGui.py
src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py

These are some minor issues I hit while running the test suite for the first time. These are likely from newer libraries on Arch, or the tests just might have bitrotted a little bit.

Tests: Fix some minor test failures

---

src/Mod/AddonManager/AddonManager.py

General cleanup of the main entry point.

Addon Manager: Linter cleanup

---

src/Mod/Fem/App/FemMeshPyImp.cpp
src/Mod/Fem/Gui/TaskCreateElementSet.cpp

This code seems to be using an older-style loop construction that generated an extraneous integer counter. Migrated to a simple while loop.

FEM: Remove set but unused variable

---

src/Mod/Assembly/JointObject.py

Fix a bug in presolve. It should not happen when there's a loop of joints or the solver can fail because of it.

Assembly: Fix a bug with presolve.

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
src/Mod/Assembly/Gui/ViewProviderAssembly.h

Fix https://github.com/FreeCAD/FreeCAD/issues/14806

Assembly: Do not attempt to drag grounded objects.

---

src/Mod/Assembly/JointObject.py
src/Mod/Assembly/UtilsAssembly.py

Fix https://github.com/FreeCAD/FreeCAD/issues/14906
Fix https://github.com/FreeCAD/FreeCAD/issues/14907

Assembly: Fix link to external sub assemblies issues.

---

src/Mod/TechDraw/Gui/QGIView.cpp
src/Mod/TechDraw/Gui/QGIViewDimension.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/14785

TechDraw: Snap: disable snap if ALT is pressed.

---

src/Mod/AddonManager/AddonManager.py
src/Mod/AddonManager/NetworkManager.py
src/Mod/AddonManager/addonmanager_workers_startup.py

Also fixes data type problems with variable declarations in __init__

Addon Manager: Fix Qt6 redirect-following code

---

src/Mod/Assembly/JointObject.py

Fix https://github.com/FreeCAD/FreeCAD/issues/14458

Assembly: Gears: Fix crash on selection -> tool workflow

---

src/Mod/Part/App/PropertyTopoShape.cpp

Fix #14952 performance problem mistakenly introduced in #14100.

Toponaming: Remove unnecessary fix() call to Bugfix #14952

---

src/Gui/WorkbenchSelector.cpp
src/Gui/WorkbenchSelector.h

Addresses a few minor linter complaints (and updates the license text to the current preferred block).

Gui: WorkbenchSelector linter cleanup

---

src/Mod/Part/App/BodyBase.cpp
src/Mod/Part/App/PartFeature.cpp
src/Mod/PartDesign/App/Body.cpp
src/Mod/PartDesign/App/FeatureBase.cpp
src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h

Builds on #14536 and fixes #14577.  Cleans up a couple of old tests and adds two new ones.

Toponaming: support base feature in body correctly.

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCascadeHorizDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCascadeObliqueDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCascadeVertDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateHorizCoordDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateObliqueCoordDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateVertCoordDimension.svg

[Icons]Revision of TechDraw Icons(Cascade-Coord)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateHorizChainDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateObliqueChainDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateVertChainDimension.svg

[Icons]Revision of TechDraw Icons(chain)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateHorizChamferDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateVertChamferDimension.svg

[Icons]Revision of TechDraw Icons(Chamfer)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDecreaseDecimal.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionIncreaseDecimal.svg

[Icons]Revision of TechDraw Icons(Decimal)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Dimension_Pointer.svg

#14145
Solve: https://github.com/FreeCAD/FreeCAD/issues/14203

[Icons]Revision of TechDraw Icons(Dimension_Pointer)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateLengthArc.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionInsertDiameter.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionInsertRepetition.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionInsertSquare.svg

[Icons]Revision of TechDraw Icons(Insert)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ProjBottom.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ProjFront.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ProjFrontBottomLeft.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ProjFrontBottomRight.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ProjFrontTopLeft.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ProjFrontTopRight.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ProjLeft.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ProjRear.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ProjRight.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ProjTop.svg

[Icons]Revision of TechDraw Icons(proj)

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/App/AssemblyObject.h
src/Mod/Assembly/Gui/Resources/panels/TaskAssemblyCreateJoint.ui
src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
src/Mod/Assembly/Gui/ViewProviderAssembly.h
src/Mod/Assembly/Gui/ViewProviderAssemblyPy.xml
src/Mod/Assembly/Gui/ViewProviderAssemblyPyImp.cpp
src/Mod/Assembly/JointObject.py
src/Mod/Assembly/UtilsAssembly.py

Set one checkbox for each limit.
Fixes https://github.com/FreeCAD/FreeCAD/issues/14690
https://github.com/FreeCAD/FreeCAD/assets/19984177/c093beee-7904-42e8-b390-4fd20d4eb73b

Assembly: Limits: Set one checkbox for each limit.

---

src/Gui/CMakeLists.txt
src/Gui/SoFCColorBar.cpp
src/Gui/SoFCColorBar.h
src/Gui/SoFCColorBarNotifier.cpp
src/Gui/SoFCColorBarNotifier.h
src/Gui/SoFCColorGradient.cpp
src/Gui/SoFCColorGradient.h
src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
src/Mod/Inspection/Gui/ViewProviderInspection.cpp
src/Mod/Mesh/Gui/ViewProviderCurvature.cpp

This solves one part of issue #10717

Core: Update color bar when changing preferences

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionSelectLineAttributes.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_DecorateLine.svg

[Icons]Revision of TechDraw Icons(LineAttributes)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmArc.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmCircle.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmCircle3Points.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionHoleCircle.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionLineParallel.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionLinePerpendicular.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_CosmeticCircle.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_LeaderLine.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Line2Points.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Midpoints.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Quadrants.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_RedrawPage.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_RichTextAnnotation.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Symbol.svg

[Icons]Revision of TechDraw Icons(blue)

---

src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_2LineCenterline.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_2PointCenterline.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_FaceCenterLine.svg

[Icons]Revision of TechDraw Icons(Centerline)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_3PtAngleDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AngleDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Balloon.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_DiameterDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Dimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_DimensionRepair.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_HorizontalDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_HorizontalExtentDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_LandmarkDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_LengthDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_LinkDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_RadiusDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_VerticalDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_VerticalExtentDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_AxoLengthDimension.svg

[Icons]Revision of TechDraw Icons(Dimensions)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionExtendLine.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionShortenLine.svg

[Icons]Revision of TechDraw Icons(Line lengths)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_CameraOrientation.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionPositionSectionView.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ActiveView.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_BrokenView.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ClipGroup.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_DetailView.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Multiview.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ProjectShape.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ShareView.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_View.svg

[Icons]Revision of TechDraw Icons(view)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionVertexAtIntersection.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_AddOffsetVertex.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_CosmeticVertex.svg

[Icons]Revision of TechDraw Icons(Vertex)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionThreadBoltBottom.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionThreadBoltSide.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionThreadHoleBottom.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionThreadHoleSide.svg

[Icons]Revision of TechDraw Icons(Thread)

---

src/Mod/Part/App/Geometry.cpp
src/Mod/Sketcher/App/SketchObject.cpp
tests/src/Mod/Part/App/CMakeLists.txt
tests/src/Mod/Part/App/Geometry.cpp

Fixes #12592.
~There is still a problem with the other (non-periodic) B-spline shown in that issue's example.~
If anyone wants to check it out, this issue was introduced in 728a880078f04e24bfe5ed215c95c4032f073683.

[Part][Sketcher] Fix some B-spline trimming issues

---

src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_SurfaceFinishSymbols.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_WeldSymbol.svg

[Icons]Revision of TechDraw Icons(symbol)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionPosHorizChainDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionPosObliqueChainDimension.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionPosVertChainDimension.svg

[Icons]Revision of TechDraw Icons(posChain)

---

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionLockUnlockView.svg
src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Lock.svg

[Icons]Revision of TechDraw Icons(lock)

---

src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_GeometricHatch.svg
src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Hatch.svg

[Icons]Revision of TechDraw Icons(Hatch)

---

src/Mod/BIM/nativeifc/ifc_openshell.py

BIM: Check for pip when running IfcOpenShell update

---

src/Mod/Draft/draftobjects/shape2dview.py

Draft: fix Draft_Shape2DView warnings

---

src/Gui/Quarter/QuarterWidgetP.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/14988

Gui: Fix crash in QuarterWidgetP::removeFromCacheContext

---

src/Mod/Mesh/Gui/Command.cpp
src/Mod/MeshPart/Gui/Command.cpp

See forum: https://forum.freecad.org/viewtopic.php?t=88734

Mesh: Use a lower threshold for the MeshPart_SectionByPlane command

---

src/Mod/PartDesign/Gui/TaskThicknessParameters.cpp
src/Mod/PartDesign/Gui/TaskThicknessParameters.h

* Fix linter warnings in TaskThicknessParameters
* Refactor TaskThicknessParameters
* Reformat TaskThicknessParameters

PD: Do not set hard-coded maximum for thickness parameter

---

src/Mod/Fem/feminout/exportNastranMesh.py

"will not be work" --> "will not work"

FEM: Fix a small typo in the Mystran error message

---

src/Mod/TechDraw/App/Preferences.cpp
src/Mod/TechDraw/App/Preferences.h
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneralImp.cpp
src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
src/Mod/TechDraw/Gui/DrawGuiUtil.h
src/Mod/TechDraw/Gui/MDIViewPage.cpp
src/Mod/TechDraw/Gui/MDIViewPage.h
src/Mod/TechDraw/Gui/QGSPage.cpp
src/Mod/TechDraw/Gui/TaskProjGroup.cpp
src/Mod/TechDraw/Gui/TaskProjGroup.ui
src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp

This PR implements a number of small fixes.
- camera/front direction buttons give no indication of selected option
- empty config causes wrong default line width (issue #15180)
- missing config option for showing view labels
- multiselect does not clear selection if non-geometry object selected 
(https://forum.freecad.org/viewtopic.php?t=88911&sid=19ac0880d30b44a7e6a299f091f16584)

[TD]Collection of small fixes

---

src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp

This PR implements a fix for a problem with spreadsheet display as reported here: https://forum.freecad.org/viewtopic.php?t=88908&sid=bb2eea9c39e140f1a669a2de0ed4ec26

[TD]fix display of spreadsheet cells with no horiz alignment

---

src/Mod/Robot/Gui/Command.cpp

clean [Robot] Command.cpp

---

src/Mod/Sandbox/Gui/GLGraphicsView.cpp

[Mod] clean GLGraphicsView.cpp

---

src/Mod/Sandbox/Gui/Overlay.cpp

[Mod:overlay] clean Overlay.cpp

---

src/Mod/Assembly/CommandInsertLink.py
src/Mod/Assembly/Gui/Resources/panels/TaskAssemblyInsertLink.ui

Assembly: Enable Insert Component taskbox to grow with the number of items.
Fixes https://github.com/FreeCAD/FreeCAD/issues/14717

Assembly: Enable Insert Component taskbox to grow

---

src/Gui/Quarter/ContextMenu.h
src/Gui/Quarter/DragDropHandler.cpp
src/Gui/Quarter/EventFilter.cpp
src/Gui/Quarter/FocusHandler.cpp
src/Gui/Quarter/ImageReader.cpp
src/Gui/Quarter/InputDevice.cpp
src/Gui/Quarter/Keyboard.cpp
src/Gui/Quarter/Mouse.cpp
src/Gui/Quarter/QuarterWidget.cpp
src/Gui/Quarter/QuarterWidget.h
src/Gui/Quarter/QuarterWidgetP.cpp
src/Gui/Quarter/SpaceNavigatorDevice.cpp
src/Gui/Quarter/devices/InputDevice.h
src/Gui/Quarter/devices/Keyboard.h
src/Gui/Quarter/devices/Mouse.h
src/Gui/Quarter/devices/SpaceNavigatorDevice.h
src/Gui/Quarter/eventhandlers/DragDropHandler.h
src/Gui/Quarter/eventhandlers/EventFilter.h
src/Gui/Quarter/eventhandlers/FocusHandler.h
src/Gui/SoTouchEvents.cpp
src/Gui/View3DInventorViewer.cpp

* Removes unused default constructors of the device classes
* Changes several doc strings

Quarter: Update Quarter code

---

src/Mod/Fem/App/FemConstraintBearing.cpp

Prevent crash if shape is null

Fem: Check null shape in constraint bearing

---

src/Mod/Sketcher/Gui/DrawSketchHandlerScale.h
src/Mod/Sketcher/Gui/DrawSketchHandlerTranslate.h

Fix https://github.com/FreeCAD/FreeCAD/issues/13240

Sketcher: scale/translate: fix OVP warning if disabled

---

src/Mod/Measure/Gui/DlgPrefsMeasureAppearanceImp.ui

Switch to a more descriptive name for each.

Measure: Fix repeated element name in UI file

---

src/Mod/Mesh/App/AppMesh.cpp

Replacement for the removed old distance tool

Mesh: Allow to measure distances with a mesh

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

- Fixes https://github.com/FreeCAD/FreeCAD/issues/14966
- Also refactor a bit by adding finishDimensionCreation to reduce code copies.
- Fix https://github.com/FreeCAD/FreeCAD/issues/12033

Sketcher: Dimension: Fix 2 bugs.

---

src/Mod/Sketcher/Gui/DrawSketchDefaultWidgetController.h
src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h

- Fix https://github.com/FreeCAD/FreeCAD/issues/14981
- Fix combobox not updating when methode  is changed by M key.

Sketcher: Bspline: few fixes

---

src/Gui/PreferencePacks/Classic/post.FCMacro

Remove QtStyle when applying Classic theme

---

src/Mod/Help/dlgPreferencesHelp.ui

Help: Added explaining note to preferences dialog

---

src/Mod/Fem/Gui/DlgSettingsFemGeneral.ui

"when open result dialog" --> "when opening result dialog"

FEM: Fix typo in general preference

---

src/Mod/Assembly/Gui/Resources/preferences/Assembly.ui

"Esc leave edit mode" --> "Esc leaves edit mode"

Assembly: Small fix of Assembly preference text

---

src/Mod/Part/Gui/SectionCutting.ui

Fixes #15233
Permanent Section Cutting --> Persistent Section Cutting

Fix confusing Persistent section cut window title

---

src/Mod/Part/App/PropertyTopoShape.cpp

Adjust PropertyTopoShape::Save code for correctness.

---

src/Mod/Test/Document.py

Demonstrates the failure of #15253

Test: Add test to validate correct XML output of Content attribute

---

src/Mod/Assembly/CommandCreateJoint.py
src/Mod/Assembly/JointObject.py

Fix https://github.com/FreeCAD/FreeCAD/issues/14722
Requires https://github.com/FreeCAD/FreeCAD/pull/15116 to be merged to be functional.

Assembly: Create joint: prevent errors on undo/ctrl-Z

---

src/Gui/PreferencePages/DlgSettingsUI.ui
src/Mod/BIM/Resources/ui/preferences-arch.ui
src/Mod/CAM/Gui/Resources/panels/PathEdit.ui
src/Mod/CAM/Gui/Resources/preferences/PathJob.ui
src/Mod/Mesh/Gui/DlgSettingsMeshView.ui
src/Mod/Part/Gui/DlgExportStep.ui
src/Mod/Part/Gui/DlgImportStep.ui
src/Mod/Part/Gui/DlgSettingsObjectColor.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawColors.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui

Fixes multiple typos found in Preferences

Fix various typos in Preferences

---

src/Mod/BIM/nativeifc/ifc_generator.py
src/Mod/BIM/nativeifc/ifc_layers.py
src/Mod/BIM/nativeifc/ifc_materials.py
src/Mod/BIM/nativeifc/ifc_selftest.py
src/Mod/BIM/nativeifc/ifc_tools.py

BIM: Fixed IfcOpenShell imports

---

src/Mod/BIM/nativeifc/ifc_generator.py
src/Mod/BIM/nativeifc/ifc_tools.py

Fixes the remaining reported issues caused by the NativeIFC merge
Fixes #14428

BIM: Fixed remaining warnings and popups

---

src/Mod/BIM/nativeifc/ifc_viewproviders.py

BIM: Added delay to ifc viewprovider drag and drop

---

src/Mod/AddonManager/Widgets/addonmanager_widget_global_buttons.py

Addon Manager: Correct update button text regression

---

src/Mod/AddonManager/AddonManager.py

Addon Manager: Fix Python dependencies button

---

src/Mod/AddonManager/NetworkManager.py
src/Mod/AddonManager/addonmanager_firstrun.py
src/Mod/AddonManager/addonmanager_installer_gui.py
src/Mod/AddonManager/addonmanager_update_all_gui.py
src/Mod/AddonManager/change_branch.py
src/Mod/AddonManager/install_to_toolbar.py
src/Mod/AddonManager/manage_python_dependencies.py

Addon Manager: Eliminate use of Qt::WindowStaysOnTopHint

---

src/Mod/BIM/nativeifc/ifc_openshell.py

BIM: more tests in IfcOpenShell tool

---

src/Mod/Sketcher/App/SketchObject.cpp

fix https://github.com/FreeCAD/FreeCAD/issues/15042

Sketcher: Fix undo of external creation not working.

---

src/Mod/Assembly/CommandInsertLink.py

Fix https://github.com/FreeCAD/FreeCAD/issues/14651

Assembly: Insert link : Insert to origin if it is within view.

---

src/Base/SmartPtrPy.cpp

Core: Add a missing interpeter lock

---

CODE_OF_CONDUCT.md
PRIVACY_POLICY.md
src/Mod/BIM/ArchBuildingPart.py
src/Mod/BIM/ArchRoof.py
src/Mod/BIM/ArchSpace.py
src/Mod/BIM/Resources/create_qrc.py
src/Mod/BIM/bimcommands/BimArchUtils.py
src/Mod/BIM/bimcommands/BimBeam.py
src/Mod/BIM/bimcommands/BimClassification.py
src/Mod/BIM/bimcommands/BimEquipment.py
src/Mod/BIM/bimcommands/BimPipe.py
src/Mod/BIM/bimcommands/BimProject.py
src/Mod/BIM/bimcommands/BimRebar.py
src/Mod/BIM/bimcommands/BimSectionPlane.py
src/Mod/BIM/bimcommands/BimTogglePanels.py
src/Mod/BIM/bimcommands/BimTruss.py
src/Mod/BIM/bimcommands/BimViews.py
src/Mod/BIM/nativeifc/ifc_openshell.py
src/Mod/BIM/nativeifc/ifc_selftest.py
src/Mod/BIM/utils/convertPsets.py

Cleans code, doesn't touch translations.

BIM: Trim trailing newlines

---

src/Mod/TechDraw/App/DrawViewCollection.cpp
src/Mod/TechDraw/App/ShapeExtractor.cpp
src/Mod/TechDraw/TechDrawTools/CommandAxoLengthDimension.py
src/Mod/TechDraw/TechDrawTools/CommandPositionSectionView.py

Cleans code, doesn't touch translations.

TD: Trim trailing newlines

---

src/Mod/Fem/femsolver/mystran/writer.py

"will not be work" --> "will not work"

FEM: Fix further typo in Mystran error message

---

src/Mod/Measure/App/MeasureDistance.cpp
src/Mod/Part/App/MeasureClient.cpp
src/Mod/Part/App/MeasureInfo.h

Measure: Fix memory leak in MeasureDistanceInfo

---

src/Mod/Fem/femtaskpanels/task_material_common.py

Fixes #12950
@marioalexis84 and @davesrocketshop FYI

FEM: Fix error with custom material card

---

src/Gui/PreferencePages/DlgSettingsUI.ui
src/Mod/Fem/Gui/TaskTetParameter.ui

Two instances produce warnings from automoc.

UI: Fix repeated names in UI files

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/13131

Sketcher: re-apply cursor of tool when clicking.

---

src/Mod/Material/Gui/MaterialDelegate.cpp
src/Mod/Material/Gui/MaterialTreeWidget.cpp
src/Mod/Material/materialtests/TestMaterialFilter.py
src/Mod/Material/materialtools/Tools/ConvertFCMat.py

Cleans code, doesn't touch translations.  
CC @davesrocketshop

Materials: Trim trailing newlines

---

src/Mod/Part/App/AttachExtension.cpp

Toponaming: Restore code for instant sketch position updates

---

src/Gui/DlgParameterImp.cpp
src/Gui/DownloadItem.cpp
src/Mod/Material/Gui/Array2D.cpp
src/Mod/Material/Gui/Array3D.cpp
src/Mod/Material/Gui/MaterialSave.cpp
src/Mod/Material/Gui/MaterialsEditor.cpp
src/Mod/Sketcher/Gui/DrawSketchKeyboardManager.cpp
src/Mod/Sketcher/Gui/ShortcutListener.cpp
src/Mod/TechDraw/Gui/QGIViewPart.cpp

* Fix Delete key in parameter editor
* Fix Delete key in material editor
* Fix Delete key in tech draw view

Sketcher: Delete key in non-functional in macOS

---

src/App/PropertyLinks.cpp
src/Gui/SoFCUnifiedSelection.cpp

Toponaming: Process mapped names during selection

---

src/Tools/updatecrowdin.py

Tools: Support Qt6 in updatecrowdin.py

---

src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
src/Mod/Sketcher/Gui/DrawSketchHandler.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfHyperbola.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfParabola.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArcSlot.h
src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h
src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h
src/Mod/Sketcher/Gui/DrawSketchHandlerExtend.h
src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h
src/Mod/Sketcher/Gui/DrawSketchHandlerLineSet.h
src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h
src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h
src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h
src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h

Fix https://github.com/FreeCAD/FreeCAD/issues/12510

Sketcher: Fix bug of auto-constraints icon not clearing up on mouseMove.

---

src/Gui/CMakeLists.txt
src/Gui/Multisample.cpp
src/Gui/Multisample.h
src/Gui/PreferencePages/DlgSettings3DView.ui
src/Gui/PreferencePages/DlgSettings3DViewImp.cpp
src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h

* Add class Multisample to check supported MSAA modes
* Use of Multisample class
* Allow to set MSAA 4x option. Fixes #15369

Gui: Allow to set MSAA 4x option

---

src/Mod/BIM/importers/importOBJ.py

BIM: Fix Wavefront OBJ color export

---

src/App/Document.cpp
src/Gui/Document.cpp

Core: Add missing Python interpreter locks

---

src/Mod/BIM/nativeifc/ifc_psets.py

BIM: Fixed IFC import with None psets

---

src/Mod/BIM/nativeifc/ifc_tools.py

BIM: Fixed empty IFC decomposition

---

src/Mod/TechDraw/App/LineNameEnum.cpp
src/Mod/TechDraw/App/LineNameEnum.h
src/Mod/TechDraw/Gui/DrawGuiUtil.cpp

This PR implements a fix for issue #15391.

[TD]translate line names at time of use (fix #15391)

---

src/Mod/PartDesign/App/Body.cpp
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h

Toponaming: Missing getSubObject code in PartDesign::Body

---

src/Mod/Assembly/Gui/ViewProviderAssembly.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/15361

Assembly: Fix edit mode to allow users to transform the assembly.

---

src/Mod/BIM/importers/importOBJ.py

BIM: Fix bug in OBJ import caused by missing utf8 encoding

---

src/Mod/Fem/femobjects/base_femelement.py
src/Mod/Fem/femobjects/base_femmeshelement.py
src/Mod/Fem/femobjects/element_fluid1D.py
src/Mod/Fem/femobjects/element_geometry1D.py
src/Mod/Fem/femobjects/element_geometry2D.py
src/Mod/Fem/femobjects/element_rotation1D.py
src/Mod/Fem/femobjects/mesh_boundarylayer.py
src/Mod/Fem/femobjects/mesh_group.py
src/Mod/Fem/femobjects/mesh_region.py
src/Mod/Fem/femviewprovider/view_base_femelement.py
src/Mod/Fem/femviewprovider/view_base_femmaterial.py
src/Mod/Fem/femviewprovider/view_base_femmeshelement.py
src/Mod/Fem/femviewprovider/view_element_fluid1D.py
src/Mod/Fem/femviewprovider/view_element_geometry1D.py
src/Mod/Fem/femviewprovider/view_element_geometry2D.py
src/Mod/Fem/femviewprovider/view_material_common.py
src/Mod/Fem/femviewprovider/view_material_reinforced.py
src/Mod/Fem/femviewprovider/view_mesh_boundarylayer.py
src/Mod/Fem/femviewprovider/view_mesh_group.py
src/Mod/Fem/femviewprovider/view_mesh_region.py

This PR fixes #15408. A regression was introduced in https://github.com/FreeCAD/FreeCAD/pull/14793

Fem: Use own base class for Python objects - fixes #15408

---

src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp

Fem: Fix manual color bar range specification - fixes #15013

---

src/Mod/Measure/Gui/Command.cpp

[Measure] Correctly restrict command availability

---

src/Mod/TechDraw/Gui/TaskLeaderLine.cpp

This PR fixes an issue where the initial point of a leader added to a rotated view was misplaced.

[TD]fix leader start point on rotated view

---

src/Mod/AddonManager/first_run.ui

Addon Manager: Silence warning due to use of horizontal line

---

src/Mod/BIM/nativeifc/ifc_viewproviders.py

Last fix introduced a new bug, that is now fixed here.
Fixes #15477

BIM: Better fix to IFC viewprovider

---

src/Gui/TaskView/TaskView.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/15474

PD: Fix crash when pressing ESC on chamfer/fillet dialog

---

src/Mod/Fem/Gui/DlgSettingsFemMystran.ui

Fem: Fix mystran preference path - fixes #15348

---

src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
src/Mod/Fem/Gui/ViewProviderFemPostObject.h

Fem: Handle single value field - fixes #14022

---

src/Mod/Fem/femmesh/gmshtools.py

Fem: Remove unused gmsh option - fixes #6354

---

src/Mod/Assembly/App/BomObject.cpp
src/Mod/Assembly/App/BomObject.h

Fix https://github.com/FreeCAD/FreeCAD/issues/15387
Also removes groups from being listed fixing : 
Fix https://github.com/FreeCAD/FreeCAD/issues/15373

Assembly: BOM: Fix same name different doc issue.

---

src/Gui/PreferencePages/DlgSettingsUI.ui

Fixes #15513 tested Start module, Macro editor, Spreadsheet, Techdraw page and Plot sub windows which all behave as required.

[Gui] Overlay set hide in non 3D view to be true/checked

---

src/App/GeoFeatureGroupExtension.cpp
src/App/GroupExtension.cpp
src/App/Link.cpp
src/App/PropertyExpressionEngine.cpp
src/App/PropertyExpressionEngine.h
src/App/PropertyLinks.cpp
src/App/PropertyLinks.h
src/Mod/Part/App/PropertyGeometryList.cpp
src/Mod/Part/App/PropertyGeometryList.h
src/Mod/Part/App/PropertyTopoShape.cpp
src/Mod/PartDesign/App/Feature.cpp
src/Mod/Spreadsheet/App/PropertySheet.cpp
src/Mod/Spreadsheet/App/PropertySheet.h

Fourth in series of incremental code transfers to solve the save/restore errors with objects with element maps..

Toponaming: Transfer in getLinksTo

---

contrib/.vscode/launch.json
contrib/.vscode/settings.json
src/Gui/3Dconnexion/navlib/NavlibCmds.cpp
src/Gui/ArcEngine.h
src/Gui/CommandLink.cpp
src/Gui/PreferencePages/DlgSettingsEditor.cpp
src/Gui/PreferencePages/DlgSettingsWorkbenchesImp.cpp
src/Gui/RemoteDebugger.py
src/Gui/TreeParams.cpp
src/Gui/View3DInventorViewer.cpp
src/Mod/Draft/draftmake/make_label.py
src/Mod/Material/App/Materials.h
src/Mod/Measure/App/MeasureLength.cpp
src/Mod/Measure/App/MeasureRadius.cpp
src/Mod/Measure/Gui/CMakeLists.txt
src/Mod/Measure/UtilsMeasure.py
src/Mod/PartDesign/App/FeatureHelix.cpp
src/Mod/PartDesign/PartDesignTests/TestHelix.py
src/Mod/Sandbox/Gui/Overlay.cpp

Minor fixes. No translations touched.

Fix trailing newlines and minor typo fixes

---

src/Mod/Fem/Gui/TaskFemConstraint.cpp
src/Mod/Fem/Gui/TaskFemConstraint.h
src/Mod/Fem/Gui/TaskFemConstraintBearing.cpp
src/Mod/Fem/Gui/TaskFemConstraintBearing.h
src/Mod/Fem/Gui/TaskFemConstraintDisplacement.cpp
src/Mod/Fem/Gui/TaskFemConstraintDisplacement.h
src/Mod/Fem/Gui/TaskFemConstraintFixed.cpp
src/Mod/Fem/Gui/TaskFemConstraintFixed.h
src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.cpp
src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.h
src/Mod/Fem/Gui/TaskFemConstraintForce.cpp
src/Mod/Fem/Gui/TaskFemConstraintForce.h
src/Mod/Fem/Gui/TaskFemConstraintHeatflux.cpp
src/Mod/Fem/Gui/TaskFemConstraintHeatflux.h
src/Mod/Fem/Gui/TaskFemConstraintPlaneRotation.cpp
src/Mod/Fem/Gui/TaskFemConstraintPlaneRotation.h
src/Mod/Fem/Gui/TaskFemConstraintPressure.cpp
src/Mod/Fem/Gui/TaskFemConstraintPressure.h
src/Mod/Fem/Gui/TaskFemConstraintRigidBody.cpp
src/Mod/Fem/Gui/TaskFemConstraintRigidBody.h
src/Mod/Fem/Gui/TaskFemConstraintSpring.cpp
src/Mod/Fem/Gui/TaskFemConstraintSpring.h
src/Mod/Fem/Gui/TaskFemConstraintTemperature.cpp
src/Mod/Fem/Gui/TaskFemConstraintTemperature.h
src/Mod/Fem/Gui/TaskFemConstraintTransform.cpp
src/Mod/Fem/Gui/TaskFemConstraintTransform.h

and make Delete key working on macOS

FEM: Fix convoluted event handling of constraint task boxes

---

src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
src/Mod/Assembly/Gui/ViewProviderAssembly.h

Enable to edit joint by double clicking them in the 3d view.
Fix https://github.com/FreeCAD/FreeCAD/issues/14701

Assembly: define joint double click on 3dview

---

src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h

Sixth in series of incremental code transfers to solve the save/restore errors with objects with element maps..

Toponaming:  bring in SketchObject::InternalShape

---

src/Mod/Part/App/TopoShapeExpansion.cpp
src/Mod/Sketcher/App/PreCompiled.h
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.h
src/Mod/Sketcher/SketcherTests/TestSketcherSolver.py
tests/src/Mod/Sketcher/App/SketchObject.cpp

Eighth in series of incremental code transfers to solve the save/restore errors with objects with element maps..

Toponaming:  Bring in ExportGeo and refmaps

---

src/Mod/Sketcher/App/SketchObject.cpp

Fix warning: -Wunused-but-set-variable

Sketch: Fix compiler warnings

---

src/Mod/Part/App/Attacher.cpp
src/Mod/Sketcher/App/SketchGeometryExtension.cpp
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/SketcherTests/TestSketcherSolver.py

Appear to be fixed:  #15549  #15380 #15484   Each of these should get verified before being closed which is why no direct Fix link here.  I'm pretty sure on these ( my tests worked ), and very hopeful on 15549.

Toponaming:  Final save/restore changes

---

src/Mod/BIM/importers/exportIFC.py

Bug-fix Consecutive face (Wall segment) touch at corner.
Forum Discussion : https://forum.freecad.org/viewtopic.php?p=771954#p771954

[Arch ExportIFC] Bug-fix Consecutive Face Touch at Corner

---

src/Mod/Draft/draftgeoutils/offsets.py

BIM: Fix index out of range error for circular wall

---

src/Gui/View3DInventorViewer.cpp

Fixes #10048
Until Qt 6.6 custom cursors are not shown at all on Wayland, so add a workaround. See also QTBUG-95434.
Workaround is limited to FreeCAD running on Wayland and Qt versions between 5.13 and 6.6. Versions prior implementing needed `QImage:: convertTo` are unlikely to be found running on Wayland.
As soon as the oldest supported Qt version becomes 6.6 on Linux, this workaround should be removed.

Gui: Buggy Wayland custom cursors workaround

---

src/Gui/PreferencePages/DlgSettingsUI.ui

Fixes #15244
Default new user's settings:
FYI @kadet1090

[Gui] Syncronise preferences page Display > UI with default settings

---

src/Mod/Draft/draftgeoutils/intersections.py

Fixes #13797.
The code as suggested by @alafr works fine and has basically been implemented.
Code has also been checked against #15350.

Draft: Fix snap intersection hang

---

src/Gui/Control.cpp

See https://forum.freecad.org/viewtopic.php?p=773347#p773347

Gui: Fix Gui.Control.showModelView()

---

src/Mod/Fem/femmesh/femmesh2mesh.py

Fixes https://github.com/FreeCAD/FreeCAD/issues/15644

FEM: FemMesh2Mesh fix quad elements

---

src/Mod/Mesh/Gui/RemeshGmsh.cpp
src/Mod/MeshPart/Gui/Tessellation.cpp

adds missing 2D meshing algorithm to Gmsh mesher in Mesh wb

MESH: Add missing Gmsh 2D algorithm (Quasi-structured Quad)

---

src/Mod/BIM/InitGui.py
src/Mod/BIM/bimcommands/BimViews.py

BIM: Fix BIM Views panel open behavior on WB activation

---

src/Mod/Assembly/CommandCreateBom.py
src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h

I don't know if I'll find more typos other day, so you can merge now or wait if any other appers.

Fix typos on Assembly & Sketcher WBs

---

src/Mod/PartDesign/App/FeatureHelix.cpp
src/Mod/PartDesign/App/FeatureHelix.h
src/Mod/PartDesign/PartDesignTests/TestHelix.py

[PD] Revert 316506f, back to shell algo for some helix cases

---

src/App/Application.cpp
src/App/PropertyContainerPyImp.cpp
src/Base/Exception.cpp
src/Base/Exception.h
src/Base/PyObjectBase.cpp
src/Base/PyObjectBase.h
src/Mod/Fem/femobjects/base_femelement.py
src/Mod/Fem/femobjects/base_femmeshelement.py
src/Mod/Fem/femobjects/base_fempythonobject.py
src/Mod/Fem/femobjects/constraint_bodyheatsource.py
src/Mod/Fem/femobjects/constraint_sectionprint.py
src/Mod/Fem/femobjects/constraint_tie.py
src/Mod/Fem/femobjects/material_common.py
src/Mod/Fem/femobjects/material_reinforced.py
src/Mod/Fem/femobjects/mesh_gmsh.py

Similar to [#14897](https://github.com/FreeCAD/FreeCAD/issues/14897), but for Material, Element geometry and Mesh Elements obejcts.
@FEA-eng

Fem: Fix link scope for Python objects

---

src/Mod/Fem/femexamples/buckling_lateraltorsionalbuckling.py
src/Mod/Fem/femexamples/buckling_platebuckling.py
src/Mod/Fem/femexamples/equation_deformation_spring_elmer.py
src/Mod/Fem/femexamples/rc_wall_2d.py

FEM: Remove obsolete "Fix" property from a few examples to repair them

---

src/Mod/Part/App/PartFeature.cpp
src/Mod/Part/App/PartFeature.h
src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
src/Mod/PartDesign/Gui/TaskFilletParameters.cpp

Toponaming: add code to implement guessing missing references

---

src/Mod/BIM/nativeifc/ifc_psets.py

Better fix for #15436
Fixes #15436

BIM: Fixed nativeIFC psets loading - 

---

src/Mod/Assembly/UtilsAssembly.py

Fix https://github.com/FreeCAD/FreeCAD/issues/15691

Assembly: Fix migrationScript2

---

src/Mod/Draft/draftgeoutils/faces.py

Bug-fix Consecutive face (Wall segment) touch at corner.
Forum Discussion :  https://forum.freecad.org/viewtopic.php?p=769213#p769213

[DraftBind] Bug-fix Consecutive Face Touch at Corner

---

src/Mod/PartDesign/App/FeatureTransformed.cpp
src/Mod/PartDesign/App/FeatureTransformed.h
src/Mod/PartDesign/PartDesignTests/TestLinearPattern.py
src/Mod/PartDesign/PartDesignTests/TestPolarPattern.py
src/Mod/Sketcher/App/SketchObject.cpp

This is substantially covered by existing tests, so just tweaked them.

Toponaming: Additional element map changes to transform

---

src/Mod/PartDesign/App/FeatureLoft.cpp
src/Mod/PartDesign/PartDesignTests/TestLoft.py

Toponaming:  fix loft mistake and complete test

---

src/Mod/AddonManager/addonmanager_installer.py
src/Mod/AddonManager/addonmanager_workers_startup.py

Fixes error reported by drmacro on Discord.

Addon Manager: Ensure metadata exists before use

---

src/App/ElementNamingUtils.cpp
src/App/ElementNamingUtils.h
src/App/StringHasher.cpp
src/Mod/Part/App/CrossSection.cpp
src/Mod/PartDesign/App/FeatureTransformed.cpp
src/Mod/PartDesign/PartDesignTests/TestMultiTransform.py
src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py

fix #15515  fix #15468 fix #14669 Correct stringhasher save.

Toponaming: Fix transformed; abstract index element name generation

---

src/Gui/Application.cpp
src/Gui/Assistant.cpp
src/Gui/CommandView.cpp
src/Gui/DlgExpressionInput.cpp
src/Gui/FileDialog.cpp
src/Gui/GuiApplicationNativeEventAware.cpp
src/Gui/PythonConsole.cpp
src/Gui/QSint/actionpanel/freecadscheme.cpp
src/Gui/SoFCCSysDragger.cpp
src/Gui/ToolHandler.cpp
src/Gui/Widgets.cpp
src/Gui/propertyeditor/PropertyItem.cpp
src/Mod/TechDraw/Gui/QGVPage.cpp

Deprecated for many years now.

GUI: Update MacOS detection macro

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Closes https://github.com/FreeCAD/FreeCAD/issues/15584.

Core: Fix a missing interpreter lock

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/App/AssemblyObject.h

Fix https://github.com/FreeCAD/FreeCAD/issues/15805

Assembly: Fix distance joints

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/UtilsAssembly.py

Fix https://github.com/FreeCAD/FreeCAD/issues/15817

Assembly: Fix objects in group would not have the dragger appear

---

src/Gui/FileDialog.cpp
src/Gui/FileDialog.h

Closes https://github.com/FreeCAD/FreeCAD/issues/15203
Alternative to https://github.com/FreeCAD/FreeCAD/pull/15581

Core: Fix export extension problem

---

.github/workflows/CI_master.yml
src/Gui/Stylesheets/FreeCAD Dark.qss
src/Gui/Stylesheets/overlay/Dark Theme + Dark Background.qss
src/Gui/Stylesheets/overlay/Dark Theme + Light Background.qss
src/Gui/Stylesheets/overlay/Light Theme + Dark Background.qss
src/Gui/Stylesheets/overlay/Light Theme + Light Background.qss

So there still some issues, like a missing comma.

Stylesheet fixes-part VI: The return of the comma 

---

src/App/StringHasher.cpp
src/Mod/PartDesign/App/FeatureTransformed.cpp
src/Mod/PartDesign/PartDesignTests/TestLinearPattern.py
src/Mod/PartDesign/PartDesignTests/TestPolarPattern.py
src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
tests/src/App/StringHasher.cpp

Toponaming: Missing shape hasher line; fixed cleaned Transformed

---

src/Mod/Start/Gui/PreCompiled.h

Start: Fix compilation with MSVC

---

src/Mod/CAM/Path/Op/Gui/CircularHoleBase.py

Fixes #15478 which has been listed as a feature request, with relation to the use of toolchangers is a debatable point but I'll leave it to the Maintainers to decide if it should wait until Post 1.0

[CAM] Fix numeric sorting of drill diameters

---

src/Mod/CAM/Gui/AppPathGuiPy.cpp

Fixes #15909  
regression bug caused by Path->CAM module rename.

[CAM] Fix Gcode import 

---

.github/workflows/CI_master.yml

Take two, because the issue has re-emerged!

CI: Disable Windows conda due to mamba bug.

---

src/Mod/BIM/importers/exportIFC.py

Fix bug introduced in #15530.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=89790
@paullee0 can you check please? Thanks.

BIM: Fix oversight in #15530

---

src/Mod/TechDraw/App/Geometry.cpp

This PR implements a fix for issue #15901.

[TD]fix asCircle error calculation (fixes #15901)

---

src/Mod/TechDraw/App/Cosmetic.cpp
src/Mod/TechDraw/App/DrawUtil.cpp
src/Mod/TechDraw/App/Geometry.cpp
src/Mod/TechDraw/App/Geometry.h

This PR implements a fix for issue #15724.

[TD]fix crash on Cosmetic line > 10m (fix #15724)

---

.github/labels.yml

This adds the Measurement tag to the Labeler CI
[skip ci]

labels.yml: add Measurement label

---

src/Mod/Part/Gui/ViewProvider.cpp

* Fixes hard crashes and throw an exception if value is out of range
* Fixes several linter warnings

Part: Make ViewProviderPart::applyMaterial more robust

---

src/Mod/Part/App/Geometry.cpp
src/Mod/Part/App/PreCompiled.h
src/Mod/Sketcher/App/Constraint.cpp
src/Mod/Sketcher/App/PreCompiled.h
src/Mod/TechDraw/App/CenterLine.cpp
src/Mod/TechDraw/App/Cosmetic.cpp
src/Mod/TechDraw/App/CosmeticVertex.cpp
src/Mod/TechDraw/App/Geometry.cpp
src/Mod/TechDraw/App/PreCompiled.h

Building: Boost dependency errors

---

src/Mod/Part/App/TopoShapeMapper.cpp

Toponaming fix #15969 following LS3 code change

---

src/Mod/Fem/Gui/ViewProviderFemMesh.cpp

row:119: fix compile warning: variables 'j'and 'i' is not initialized
row 662: float numbers x, y, z are used without initialization

[FEM] fix compile warnings ->ViewProviderFemMesh.cpp

---

src/Mod/Sketcher/App/planegcs/Constraints.cpp
src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h
src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h
src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp

Not yet completely successful.

[Sketcher] Attempt to fix #14736

---

src/Mod/Part/App/FeatureRevolution.cpp
src/Mod/Part/App/FeatureScale.cpp
src/Mod/Part/App/PartFeatures.cpp
src/Mod/PartDesign/App/FeatureSketchBased.cpp
src/Mod/PartDesign/PartDesignTests/TestShapeBinder.py
src/Mod/TechDraw/App/ShapeExtractor.cpp

Update to Toposhape versions and fix shapebinder references with test

---

src/Mod/Part/App/FaceMaker.cpp

Ignore standalone points in sketches when building faces

---

src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py

Pure reformatting plus one added method description comment.

Toponaming: Run black on the entire toponaming python test file.

---

src/Mod/BIM/importers/exportIFC.py
src/Mod/BIM/importers/importIFC.py
src/Mod/BIM/importers/importIFClegacy.py
src/Mod/BIM/importers/importJSON.py
src/Mod/BIM/importers/importOBJ.py
src/Mod/BIM/importers/importSH3D.py
src/Mod/BIM/importers/importSHP.py
src/Mod/BIM/importers/importWebGL.py

Fixes #16137
Similar to this fix:
https://github.com/FreeCAD/FreeCAD/pull/13337#discussion_r1564806896

BIM: Fix Python 3.12 run time error with importers

---

src/Mod/Material/Gui/DlgSettingsMaterial.ui

Fixes https://github.com/FreeCAD/FreeCAD/issues/16098
FYI @davesrocketshop

[Material] Prefs - User Directory - set to Directory chooser

---

src/Mod/Sketcher/Gui/DrawSketchController.h
src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h

Fix https://github.com/FreeCAD/FreeCAD/issues/15814

Sketcher: Fix autoconstraint issue

---

src/Mod/Draft/draftguitools/gui_trimex.py

Selecting an edge or vertex of a solid was not handled properly. The tool does not support these subelements, but the code did not call self.finish() is such cases.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=90159
Fixes #16139

Draft: Fix error handling of Draft_Trimex

---

src/Mod/TechDraw/App/DrawView.h
src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
src/Mod/TechDraw/Gui/QGIViewBalloon.h

This PR implements a fix for issue #15726.

[TD]fix balloon drag on rotated view (fix #15726)

---

src/Mod/Part/App/TopoShapeExpansion.cpp
tests/src/Mod/Part/App/TopoShapeExpansion.cpp

Fix #16013 and fix the Ruled Surface element map tests while I'm at it.

Fix #16013

---

src/Mod/TechDraw/Gui/PagePrinter.cpp

This PR implements a fix for issue #15848 where the page margins in Pdf exports were not set correctly.

[TD]fix page margins on pdf export (fix #15848)

---

src/Mod/Measure/App/Measurement.cpp

clean Measurement.cpp

---

src/Mod/Part/App/TopoShapeExpansion.cpp
src/Mod/Part/parttests/regression_tests.py

Part/Toponaming: Import TopoShape::prepareProfiles() from LS3

---

src/App/Link.cpp
src/App/Link.h
src/Gui/ViewProviderLink.cpp
src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/App/AssemblyObject.h
src/Mod/Assembly/App/AssemblyObjectPy.xml
src/Mod/Assembly/App/AssemblyObjectPyImp.cpp
src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
src/Mod/Assembly/Gui/ViewProviderAssembly.h
src/Mod/Assembly/JointObject.py
src/Mod/Assembly/UtilsAssembly.py

Fix https://github.com/FreeCAD/FreeCAD/issues/14623
Fix https://github.com/FreeCAD/FreeCAD/issues/15822

Assembly: Link groups

---

src/Mod/TechDraw/Gui/TaskCosVertex.cpp

This PR implements a fix for issue #16179.

[TD]fix projection group detection (fix #16179)

---

src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/App/DrawViewDimension.h

This PR implements a fix for issue #16172.

[TD]fix dim text wrong side of dim line (fix #16172)

---

src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.cpp
src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.h
src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.ui

Before
After
Who don't like better UI? #12719

[TechDraw] Improve UI for TaskSurfaceFinishSymbols

---

src/Mod/CAM/Path/Main/Gui/SimulatorGL.py
src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.cpp
src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.h
src/Mod/CAM/PathSimulator/AppGL/GlUtils.h
src/Mod/CAM/PathSimulator/AppGL/MillPathSegment.cpp
src/Mod/CAM/PathSimulator/AppGL/MillSimulation.cpp
src/Mod/CAM/PathSimulator/AppGL/MillSimulation.h
src/Mod/CAM/PathSimulator/AppGL/SimDisplay.cpp
src/Mod/CAM/PathSimulator/AppGL/SimDisplay.h

This PR fixes the following issues:
No support for trackpad - issue #16073 
Helix / arc simulation error - issue #16052
Wrong zoom direction
Insufficient zoom range 
Edit: fixes issue  #16180 as well (tool generation issue)

[CAM SIMULATOR] Bug fixes for Issues #16073 and #16052

---

src/Mod/Draft/draftviewproviders/view_layer.py

Fixes: #16201
Changing the Group property type of layers to `App::PropertyLinkListHidden` also means that they longer occur in the InList of nested objects. This side-effect was missed in #14506.

Draft: Fix regression with layer drag-and-drop behavior

---

src/Mod/TechDraw/App/DrawUtil.cpp
src/Mod/TechDraw/App/DrawUtil.h
src/Mod/TechDraw/App/DrawView.cpp
src/Mod/TechDraw/App/DrawView.h
src/Mod/TechDraw/App/DrawViewSection.cpp
src/Mod/TechDraw/App/DrawViewSection.h
src/Mod/TechDraw/App/Preferences.cpp
src/Mod/TechDraw/App/Preferences.h
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneralImp.cpp
src/Mod/TechDraw/Gui/QGIView.cpp
src/Mod/TechDraw/Gui/QGIView.h

This PR implements a fix for the section view snapping algo.  It also fixes #15312.

[TD]Fix section snapping (fix #15961)

---

src/Mod/TechDraw/App/Geometry.cpp

This PR implements a fix for issue #16136.

[TD]fix outer torus edge not rendered (fix #16136)

---

src/Mod/Part/parttests/regression_tests.py
src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h

Fix https://github.com/FreeCAD/FreeCAD/issues/16255

Test: remove unecessary toggle that is failing the test

---

src/Mod/Fem/Gui/Resources/ui/Material.ui
src/Mod/Fem/femsolver/calculix/write_femelement_material.py
src/Mod/Fem/femtaskpanels/task_material_common.py

fully fixes #12934
This fix consists of 3 parts:
- check of empty string fix from @benj5378 (#16270)
- higher maximum values - they were way too low which was a nasty bug/oversight: https://github.com/FreeCAD/FreeCAD/pull/16270#issuecomment-2329560196
- correct writing of viscosity to CalculiX input files (it was broken and did not use kinematic viscosity)

FEM: Fluid material properties fix

---

src/Gui/ViewProviderLink.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/16232

App::Link: fix crash with Draft Array

---

src/Mod/BIM/ArchWindow.py

V1.0 fix for the transparency of glass panels in windows and doors.

BIM: Fix window transparency

---

src/Mod/TechDraw/Gui/QGSPage.cpp

This PR implements a fix for issue #16234.
[Cap_balloonOriginWrongPos_wme.FCStd.not.zip](https://github.com/user-attachments/files/16859745/Cap_balloonOriginWrongPos_wme.FCStd.not.zip)

[TD]fix initial balloon placement on rotated view (fix #16234)

---

src/Mod/BIM/bimcommands/BimWindow.py

BIM: BimWindow.py add missing imports

---

src/Mod/BIM/ArchFence.py

* ShapeAppearance property was misspelled.
* The post and section objects could not be Std_Parts (because they do not have a DIffuseColor).
* Minor improvements to the handling of Bodies.
* Removed the `if __name__ == '__main__':` section. This code is no longer relevant.
Same as:
https://github.com/FreeCAD/FreeCAD/pull/16285

BIM: ArchFence: Fix some color issues

---

src/3rdParty/libE57Format/src/CheckedFile.cpp
src/App/Application.cpp
src/Mod/MeshPart/App/CMakeLists.txt

Forum thread: https://forum.freecad.org/viewtopic.php?t=80792

Port: Include some important changes of the OpenBSD port

---

src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/16354

[Spreadsheet] Fix CSV import by insert

---

src/Mod/PartDesign/App/FeatureHelix.cpp
src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py

Fix the issue described here: https://forum.freecad.org/viewtopic.php?t=90156

[PD] Fix helix placement

---

src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h

Fix https://github.com/FreeCAD/FreeCAD/issues/15834
Fix round corner + thickness issue if radius + thickness = 0. This case needs to be handled separately.
Fixing this uncover a problem with 3 points rectangle frame: doEnforceControlParameters was not correctly enforcing position for non-square-angles rectangles. This PR also fix this.

Sketcher: Fix round corner + thickness issue if radius + thickness = 0

---

src/Gui/PreferencePages/DlgSettingsLightSources.cpp
src/Gui/PreferencePages/DlgSettingsLightSources.h
src/Gui/PreferencePages/DlgSettingsLightSources.ui

@maxwxyz, added _Push In_ and _Pull Out_ buttons, replaced colors. Now the dialog looks like this.
https://github.com/user-attachments/assets/4e5b4903-9fe3-4383-b783-c7314cd9515b

[GUI] Enable sort of zoom in Light Sources dialog

---

src/Mod/Fem/femsolver/elmer/writer.py
src/Mod/Fem/femtest/data/elmer/box_static_0_mm.sif

See https://github.com/FreeCAD/FreeCAD/pull/16351 comments.
@FEA-eng

Fem: Set Elmer result output format to Ascii

---

src/Mod/CAM/Path/Main/Gui/SanityCmd.py

set default directory for sanity
Respond correctly if user cancels  
Fixes #14796

CAM Fix minor sanity bugs

---

src/Mod/BIM/bimcommands/BimViews.py

BIM: Fixed bug in BimViews

---

cMake/FreeCAD_Helpers/CompilerChecksAndSetups.cmake

only   CXX 23, 20 and 17 standards are allowed

fix CXX standard selection

---

src/Mod/Draft/draftgeoutils/geo_arrays.py
src/Mod/Draft/draftobjects/patharray.py

Draft: fix division by zero and count is zero for path arrays

---

src/Mod/Measure/Gui/TaskMeasure.cpp

[Measure] Redirect enter key press to apply button

---

src/Gui/BitmapFactory.cpp
src/Gui/BitmapFactory.h
src/Gui/StartupProcess.cpp

Gui: Use FreeCAD Theme only for FreeCAD stuff

---

src/Mod/Draft/draftfunctions/svg.py

Problem with the same cause as #16212.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=90601

Draft: Fix regression with layer print color

---

src/Mod/BIM/importers/exportIFC.py

As shown in the image here:
https://github.com/FreeCAD/FreeCAD/issues/16485#issue-2523042111

BIM: exportIFC.py fix UnboundLocalError

---

src/Mod/TechDraw/Gui/MDIViewPage.cpp

This PR implements a fix for issue #16447.

[TD]allow SaveCopy from MDIViewPage (fix #16447)

---

src/Mod/BIM/importers/exportIFC.py
src/Mod/BIM/nativeifc/ifc_generator.py
src/Mod/BIM/nativeifc/ifc_layers.py
src/Mod/BIM/nativeifc/ifc_materials.py
src/Mod/BIM/nativeifc/ifc_selftest.py
src/Mod/BIM/nativeifc/ifc_tools.py
src/Mod/BIM/nativeifc/ifc_viewproviders.py

Although this is not strictly 1.0 material, I think this would do good to merge before the release as v0.8 is progressively being spread around, for ex. in snap, and soon in conda https://anaconda.org/conda-forge/ifcopenshell

BIM: Support for IfcOpenShell 0.8

---

src/Gui/Application.cpp

I broke some windows compilers.  I'm having myself flogged now.
Hat tip to @Syres916 for the quick alert.

Core: Bad programmer.  Use C++ syntax to not upset some compilers

---

src/Mod/PartDesign/Gui/SketchWorkflow.cpp

PartDesign: When creating Sketch inside a Body in a link, use link position

---

src/Mod/Measure/Gui/TaskMeasure.cpp

Fixes #16564 introduced in a7831ee

Revert "[Measure] Fix redundant variable assignment"

---

src/Mod/BIM/ArchSchedule.py

BIM: show AutoUpdate of existing ArchSchedule

---

src/Mod/Measure/App/Measurement.cpp
src/Mod/Measure/Gui/QuickMeasure.cpp

QuickMeasure was not using the new globalplacement so it was failing in many cases.
Related : https://github.com/FreeCAD/FreeCAD/issues/14559

Measure: Fix quickmeasure globalplacement.

---

src/Gui/Application.cpp
src/Gui/Application.h
src/Mod/Start/Gui/StartView.cpp

Core: Move the recompute dialog to after Gui opens not on per doc signal

---

src/Mod/Part/App/Tools.cpp
src/Mod/Part/App/Tools.h
src/Mod/Part/App/TopoShapeExpansion.cpp
src/Mod/PartDesign/App/FeatureExtrude.cpp
src/Mod/PartDesign/App/FeatureExtrude.h
src/Mod/PartDesign/App/FeatureSketchBased.cpp
src/Mod/PartDesign/App/FeatureSketchBased.h
src/Mod/PartDesign/PartDesignTests/TestPad.py

[PD] fix pad uptoface and uptoshape

---

src/Gui/View3DInventorViewer.cpp

Gui: Fix segfault in align to selection tool

---

src/App/GeoFeature.cpp

This fixes several of the cases in #16207 but not all.  The remaining cases need analysis as to the cause.

Toponaming: Correct error in resolveElement

---

src/Mod/PartDesign/App/FeatureHole.cpp
src/Mod/PartDesign/App/FeatureHole.h
src/Mod/Sketcher/SketcherTests/TestSketcherSolver.py

I don't understand how this got missed, or how the existing test that was checking for the element map wasn't getting run.

Toponaming: transfer feature hole

---

src/Mod/Tux/NavigationIndicatorGui.py

Tux: Fix default orbit style shown in status bar

---

src/Mod/Part/App/TopoShapeExpansion.cpp
src/Mod/PartDesign/PartDesignTests/TestPad.py

[PD] Fix Pad uptoshape and add unit test

---

src/Mod/TechDraw/Gui/MDIViewPage.cpp

This PR implements a fix for issue #16538.

[TD]fix double pdf file on win (fix #16538)

---

src/Mod/TechDraw/App/Geometry.cpp

This PR implements a fix for issue #16646.

[TD]fix torus render (fix #16646)

---

src/Mod/TechDraw/Gui/Command.cpp

This PR implements a fix for issue #16593.

[TD]respect camera direction preference (fix #16593)

---

src/Mod/TechDraw/Gui/Command.cpp

This PR implements a fix for an issue reported on the forum (https://forum.freecad.org/viewtopic.php?p=782469#p782469) and later as issue #16693.
edit: wrong issue linked.

[TD]fix BrokenView selection (fix #16693)

---

src/Mod/TechDraw/App/DrawUtil.cpp
src/Mod/TechDraw/App/DrawUtil.h
src/Mod/TechDraw/Gui/Command.cpp
src/Mod/TechDraw/Gui/CommandDecorate.cpp
src/Mod/TechDraw/Gui/PagePrinter.cpp
src/Mod/TechDraw/Gui/TaskActiveView.cpp
src/Mod/TechDraw/Gui/TaskGeomHatch.cpp
src/Mod/TechDraw/Gui/TaskHatch.cpp

This PR implements a fix for issue #16646.

[TD] Fix win file spec backslash (fix #16646)

---

src/Gui/View3DInventorViewer.cpp
src/Mod/TechDraw/Gui/QGVPage.cpp

The very same problem as #14547, same solution.

TechDraw: Buggy Wayland custom cursors workaround

---

src/Mod/BIM/nativeifc/ifc_status.py
src/Mod/BIM/nativeifc/ifc_tools.py

BIM: Fixed adding missing windows when converting to IFC

---

src/Gui/MainWindow.cpp
src/Gui/StartupProcess.cpp
src/Gui/StartupProcess.h

[Proposal] Small change to fix Splash Screen show time until a refactoring of StartupProcess is done.
Please consider for 1.0.
https://github.com/user-attachments/assets/0d759695-aa1a-4027-8fa0-698c6c5b12ed

Splash Screen minimal show time. Issue #16264

---

src/Mod/PartDesign/App/FeatureExtrude.cpp
src/Mod/PartDesign/App/FeatureSketchBased.cpp
src/Mod/PartDesign/App/FeatureSketchBased.h
src/Mod/PartDesign/PartDesignTests/TestPad.py

[PD] Fix Pad uptoface with custom direction

---

src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp

This PR implements a fix for issue #16783.

[TD]fix bad default value (fix #16783)

---

src/Mod/TechDraw/App/Preferences.cpp
src/Mod/TechDraw/App/Preferences.h
src/Mod/TechDraw/Gui/TaskProjGroup.cpp
src/Mod/TechDraw/Gui/TaskProjGroup.h

This PR implements fixes for issues #16788 and #16785.

[TD]Fix proj convention (fix #16788, fix #16785)

---

src/Mod/CAM/PathSimulator/AppGL/GuiDisplay.cpp
src/Mod/CAM/PathSimulator/AppGL/MillSimulation.cpp
src/Mod/CAM/PathSimulator/AppGL/MillSimulation.h
src/Mod/CAM/PathSimulator/AppGL/OpenGlWrapper.h
src/Mod/CAM/PathSimulator/AppGL/Shader.cpp
src/Mod/CAM/PathSimulator/AppGL/Shader.h
src/Mod/CAM/PathSimulator/AppGL/SimDisplay.cpp
src/Mod/CAM/PathSimulator/AppGL/SimDisplay.h

Since the old SSAO shaders were under CC license which is not compatible with FreeCad's, I changed the code to use code samples from a book with MIT license which is compatible.

[CAM Simulator][1.0] Change usage of sample shader code to one with compatible license.

---

src/Mod/TechDraw/Gui/TaskDimRepair.cpp

This PR implements a fix for issue #16894.

[TD]fix no dim repair on area (fix #16894)

---

src/Mod/TechDraw/App/DrawViewDimension.cpp

This PR implements a fix for issue #16892.

[TD]Fix auto correct msg missing16892

---

src/Build/CMakeLists.txt

Fix build error with Makefiles for missing Version h

---

src/App/PropertyLinks.cpp
src/Gui/SoFCUnifiedSelection.cpp
src/Mod/Assembly/JointObject.py

Fix #16207.   I have switched from a python based solution to a lower level c++ one.

Assembly: Correctly build reference from selection subname

---

src/Mod/BIM/ArchWall.py

In V1.0 the handling of wall normals has changed. As a result existing walls with their Normal set to [0, 0, 0], based on wires or faces with a shape normal pointing towards -Z, would be extruded in that direction instead of towards +Z as before. To avoid this their Normal property is changed to [0, 0, 1].

BIM: Compatibility fix for walls based on wire or face with -Z normal

---

src/Mod/Draft/draftfunctions/svgshapes.py

Forum topic:
https://forum.freecad.org/viewtopic.php?t=90942

Draft: avoid confusing SVG warning for nested circles and ellipses

---

src/Mod/BIM/bimcommands/BimWall.py

BIM: BimWall add missing imports

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

In auto constrainer. Fixes #12684

[Sketcher] If origin selected: don't do distance to origin

---

src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/DimensionValidators.cpp

This PR implements a fix for issue #16851.

[TD]fix parallel edge test (fix  #16851)

---

src/Gui/TextEdit.cpp
src/Gui/TextEdit.h

[Gui] TextEdit, zoom on Ctrl + wheel

---

src/Mod/Fem/Gui/CMakeLists.txt
src/Mod/Fem/Gui/Resources/Fem.qrc
src/Mod/Fem/Gui/Resources/ui/DlgSettingsNetgen.ui
src/Mod/Fem/InitGui.py
src/Mod/Fem/ObjectsFem.py
src/Mod/Fem/femcommands/commands.py
src/Mod/Fem/femtest/app/test_object.py

Add preference page to select between old and new Netgen mesh implementations.
@FEA-eng

Fem: Add option to use old Netgen mesher implementation

---

src/Gui/NavigationStyle.h
src/Gui/TouchpadNavigationStyle.cpp

Gui: Fix Touchpad navigation style panning in edit mode

---

src/Mod/Part/Gui/TaskAttacher.cpp
src/Mod/Part/Gui/TaskAttacher.h

Fix https://github.com/FreeCAD/FreeCAD/issues/7580
@wwmayer

Core: Fix #7580

---

src/Mod/BIM/ArchCommands.py

FreeCAD Discussion Forum -
https://forum.freecad.org/viewtopic.php?t=91180&start=30#p786308

[Arch] Bug Fix : ArchRemove Creates Cyclic Dependency and TNP

---

src/Mod/Assembly/JointObject.py

Fix https://github.com/FreeCAD/FreeCAD/issues/17111

Assembly: Fix gear/belt switch on checkbox toggle

---

src/Mod/Fem/App/FemConstraintHeatflux.cpp
src/Mod/Fem/App/FemConstraintHeatflux.h
src/Mod/Fem/Gui/Resources/ui/ConstraintCentrif.ui
src/Mod/Fem/Gui/Resources/ui/ElementGeometry1D.ui
src/Mod/Fem/Gui/Resources/ui/ElementGeometry2D.ui
src/Mod/Fem/Gui/Resources/ui/MeshBoundaryLayer.ui
src/Mod/Fem/Gui/Resources/ui/MeshNetgen.ui
src/Mod/Fem/Gui/Resources/ui/MeshRegion.ui
src/Mod/Fem/Gui/TaskFemConstraintHeatflux.cpp
src/Mod/Fem/Gui/TaskFemConstraintHeatflux.h
src/Mod/Fem/Gui/TaskFemConstraintHeatflux.ui
src/Mod/Fem/Gui/TaskFemConstraintSpring.cpp
src/Mod/Fem/Gui/TaskFemConstraintSpring.h
src/Mod/Fem/Gui/TaskFemConstraintSpring.ui
src/Mod/Fem/femguiutils/selection_widgets.py
src/Mod/Fem/femobjects/constraint_centrif.py
src/Mod/Fem/femsolver/calculix/write_constraint_heatflux.py
src/Mod/Fem/femsolver/elmer/equations/heat_writer.py
src/Mod/Fem/femtaskpanels/task_constraint_centrif.py
src/Mod/Fem/femtaskpanels/task_element_geometry1D.py
src/Mod/Fem/femtaskpanels/task_element_geometry2D.py
src/Mod/Fem/femtaskpanels/task_mesh_boundarylayer.py
src/Mod/Fem/femtaskpanels/task_mesh_netgen.py
src/Mod/Fem/femtaskpanels/task_mesh_region.py

Fixes https://github.com/FreeCAD/FreeCAD/issues/5655
The only object left pending is ElementFluid1D which will be updated in a separate pull request.
Note:
The modifications are not very big, but there are changes in the code style to move from camel case to snake case in Python files.
@FEA-eng

Fem: Use expressions in fem task panels

---

src/Mod/Assembly/JointObject.py

Fix https://github.com/FreeCAD/FreeCAD/issues/16598
Fix https://github.com/FreeCAD/FreeCAD/issues/16383

Assembly: Fix joint labels bad auto-rename issue.

---

src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
src/Mod/PartDesign/Gui/TaskDressUpParameters.h

PD: Fix crash when clicking on invalid edge in task panel

---

src/Mod/Draft/draftfunctions/upgrade.py

Forum topic:
https://forum.freecad.org/viewtopic.php?t=91357

Draft: Fix upgrade function: delete argument was ignored in case of draftify

---

src/Mod/Assembly/JointObject.py

Fix https://github.com/FreeCAD/FreeCAD/issues/10785
By removing the camera callback we are fixing : 
Fix https://github.com/FreeCAD/FreeCAD/issues/16981
Fix https://github.com/FreeCAD/FreeCAD/issues/16252 (superseeding : https://github.com/FreeCAD/FreeCAD/pull/17051)
It also Fix https://github.com/FreeCAD/FreeCAD/issues/13953

Assembly: Remove JointObject camera callbacks. And fix lock highlight.
