src/Mod/Fem/App/FemConstraintTransform.cpp, src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
* variable 'xAngle' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
* variable 'yAngle' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
* variable 'zAngle' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
* unused variable 'base' [-Werror,-Wunused-variable]
* unused variable 'extrude' [-Werror,-Wunused-variable]
=> Fix several compiler warnings

src/Mod/CAM/Gui/Resources/panels/PageOpDeburrEdit.ui, src/Mod/CAM/Gui/Resources/panels/PageOpHelixEdit.ui, src/Mod/CAM/Path/Base/Generator/helix.py, src/Mod/CAM/Path/Dressup/Gui/LeadInOut.py, src/Mod/CAM/Path/Geom.py, src/Mod/CAM/Path/Op/Area.py, src/Mod/CAM/Path/Op/Deburr.py, src/Mod/CAM/Path/Op/Helix.py, src/Mod/CAM/Path/Op/PocketBase.py, src/Mod/CAM/Path/Op/Profile.py, src/Mod/CAM/Path/Post/scripts/heidenhain_post.py, src/Mod/CAM/Tests/PathTestUtils.py, src/Mod/CAM/Tests/TestPathDressupDogbone.py, src/Mod/CAM/Tests/TestPathGeom.py, src/Mod/CAM/Tests/TestPathHelixGenerator.py, src/Mod/CAM/Tests/TestPathProfile.py
As per title. I don't write much Python so I may have missed something silly, but the tests pass (locally anyway).
The translations were done with a naive find and replace. My editor stripped trailing whitespace which I can undo if it's significant, otherwise apologies for the diff noise. I'm unsure how to test if the translations are still correct.
Closes #14314
=> CAM: Rename CW/CCW to Climb/Conventional for consistency

src/Mod/Import/TestImportGui.py
If the option 'Enable STEP compound merge' is active the test would fail
=> Test: make test for STEP import independent of user settings

src/Mod/Draft/draftobjects/shape2dview.py
Null shapes do not have a ShapeType (strange IMO). The function did not take that into account.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=88397
=> Draft: _get_shapes in shape2dview.py did not handle null shapes

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
Fixes https://github.com/FreeCAD/FreeCAD/issues/14634
Start edit sketch, press ESC : does not exit edit mode
Start a sketcher tool, press ESC : that terminates the tool. Press ESC again : does not exit edit mode
Both are a focus problem. The MDI does not have focus as user clicked somewhere outside of it. So VPSketch does not receive the ESC key signal. So it does not exit.
=> Sketcher: Fix ESC not working in 2 situations

src/App/PropertyStandard.cpp, src/App/PropertyStandard.h
The PropertyMaterialList is supposed to guarantee that it always has at least one element
=> Core: Make sure that PropertyMaterialList cannot become empty

src/Mod/CAM/Path/Main/Gui/SimulatorGL.py, src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.cpp, src/Mod/CAM/PathSimulator/AppGL/EndMill.cpp
Bug: Cam simulation always shows all operations even if only partial items are selected. 
This a fix to Issue #14513 
I have also restricted the opengl version to 4.1 core, and this might fix the issue in MacOS where the display is an empty window (Issue #14348). I do not have MacOS to test it so hopefully it will be tested by the community later.
Fixes also issue #14613: some tools are not displayed correctly.
=> CAM: Fix issue #14513 - simulation of partially selected operations not working

src/Mod/Draft/WorkingPlane.py
#14206 was an intermediate solution. Now that  `Part.getShape` can handle the new `SubElementNames` it needs to be removed as it breaks the handling of subelements in links.
=> Draft: revert #14206 to fix WP alignment

cMake/FreeCAD_Helpers/SetGlobalCompilerAndLinkerSettings.cmake
See https://stackoverflow.com/questions/78598141/first-stdmutexlock-crashes-in-application-built-with-latest-visual-studio
=> MSVC: Fix crash with std::mutex

src/Gui/SelectionView.cpp, src/Gui/SoFCUnifiedSelection.cpp, src/Gui/View3DInventorSelection.cpp
This fixes #14521 the reported bug first seen in selections of CAM model objects where only one selection could be made.
It also cleans up the Selection View to show short element names, and not full history names.
Fix #13248
=> Toponaming: fix secondElementSelection and SelectionView

src/Tools/dmg_settings.py, src/Tools/macos_sign_and_notarize.sh
This uses dmgbuild to create a DMG with bigger icons and a symlink to /Applications. As it does not yet contain a background image or color, it adapts to dark and light mode settings:
Partially addresses https://github.com/FreeCAD/FreeCAD-Bundle/issues/242.
See also the related pull request for the weekly builds: https://github.com/FreeCAD/FreeCAD-Bundle/pull/251
=> macOS: Add symlink to /Applications and use bigger icons

src/Gui/ViewProviderGeometryObject.cpp
Under certain conditions an objects transparency would no be updated.
fixes #14568
=> Materials: Render Transparency

src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
QListWidget::item is not declared as Q_SIGNALS and thus cannot be used as sender in QObject::connect()
=> PD: Fix Qt warning at runtime

src/Mod/BIM/ArchPrecast.py, src/Mod/BIM/ArchWindow.py, src/Mod/BIM/bimcommands/BimWindow.py
Fix bug reported in the forum https://forum.freecad.org/viewtopic.php?t=88499 error raised using BimWindow:
```
15:42:45  Running the Python command 'Arch_Window' failed:
File "/opt/freecad-source/freecad-build/Mod/BIM/bimcommands/BimWindow.py", line 135, in Activated
FreeCADGui.Snapper.getPoint(callback=self.getPoint,movecallback=self.update,extradlg=self.taskbox())
^^^^^^^^^^^^^^
File "/opt/freecad-source/freecad-build/Mod/BIM/bimcommands/BimWindow.py", line 325, in taskbox
self.im = QtSvg.QSvgWidget(":/ui/ParametersWindowFixed.svg")
^^^^^^^^^^^^^^^^
module 'PySide.QtSvg' has no attribute 'QSvgWidget'
```
Previous fix before BIM Wb integration: https://github.com/FreeCAD/FreeCAD/pull/13554
=> [BIM] Fix QSvgWidget is not a child of QtSvg in PySide6

src/Mod/BIM/InitGui.py
The BIMBots service has been discontinued so the command should be removed from the BIM WB.
Related to issue opensourceBIM/BIMbots-FreeCAD#2
=> BIM; Removed BIMBots

src/Gui/CommandView.cpp, src/Gui/PreferencePages/DlgSettingsSelection.ui
Small improvement of the preference text
before: "Preselect the object in 3D view when mouse over the tree item"
after: "Preselect the object in 3D view when hovering the cursor over the tree item"
=> Preselection preference text improvement

src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.h, src/Mod/Import/App/AppImportPy.cpp, src/Mod/Import/App/ReaderStep.cpp, src/Mod/Import/App/ReaderStep.h, src/Mod/Import/Gui/AppImportGuiPy.cpp, src/Mod/Part/App/OCAF/ImportExportSettings.cpp, src/Mod/Part/App/OCAF/ImportExportSettings.h, src/Mod/Part/Gui/DlgImportStep.cpp, src/Mod/Part/Gui/DlgImportStep.ui
Added the ability to select the encoding of the source file when importing.
Requires OCCT version 7.8.0 and higher
Fix https://github.com/FreeCAD/FreeCAD/issues/7987
=> Select code page during STEP Import 

src/Mod/Part/App/MeasureClient.cpp
Currently MeasureLength fails when trying to measure circles and arcs. The relevant code where the exception occurs can actually be be simplified as the rotation of the measured element is not needed to place the measure label.
Fixes #14411 
Fixes #14534
=> Measure: Fix MeasureLength failure when measuring circles/arcs

src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
Users report that they have a hard time figuring out that 'Array transform' does movement/translations, and 'Polar transform' does rotation. Hence this adjustment of their user-visible names.
=> Adjust names of two Sketcher tools to make their functions discoverable

src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femobjects/solver_ccxtools.py, src/Mod/Fem/femsolver/calculix/solver.py
Fixes #13383
The initialization of the properties is moved to a base class and the preference parameters are used in the activation of the commands.
@wwmayer, @FEA-eng
=> Fem: Remove dependency of calculix solver classes on user parameters - fixes #13383

src/Mod/Measure/Gui/QuickMeasure.cpp, src/Mod/Measure/Gui/QuickMeasure.h
Fix https://github.com/FreeCAD/FreeCAD/issues/14618
Adds a timer so that quickmeasure excecute only once in the case of box selection.
Adds a limit to 100 objects/subnames as very large selection (1000 edges for example) can take a significant time. 100 edges does not seem to slow down selection.
@wwmayer
=> QuickMeasure: fix large selection slow down.

src/Mod/BIM/importers/exportIFC.py
The Dir vector of Part extrusions also needs to be scaled if obj.LengthFwd.Value is zero.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=88121
=> BIM: fix extrusion vector scaling for IFC export

src/Mod/Part/AttachmentEditor/TaskAttachmentEditor.py
This regression was brought to light by https://github.com/FreeCAD/FreeCAD/pull/12885 but appears to have been missed in the Python 2 to 3 migration.
Fixes https://github.com/FreeCAD/FreeCAD/issues/13804 `name 'basestring' is not defined` message box error. This wasn't just affecting PartDesign sketches, I was getting it triggered opening 0.20 files with just standard unattached sketches using 0.22dev.
=> [Part] Attachment Editor correct Python 2 reference

src/Mod/Part/App/TopoShape.cpp
With this commit the TopoShape::_makeTransform() use makeGTransform() if scale is zero to avoid crash according to issue #14562
=> Part: Handle zero scale in TopoShape::_makeTransform

src/Mod/Fem/Gui/TaskFemConstraintSpring.ui
Currently the height of the references widget is very small
=> Fem: Fix height of reference list widget in spring constraint task panel

src/Gui/DlgPreferences.ui
=> Remove unusable Help button from Preferences

src/Mod/Draft/draftobjects/shape2dview.py
=> Fix too large spaces in two Draft Shape2DView property descriptions

src/Mod/Draft/draftguitools/gui_split.py
To make using Esc work properly the 3D view should have the focus.
=> Draft: Draft_Split put focus on 3D view

src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
The crash occured because `PartDesignGui::TaskDressUpParameters::setSelection` was invoked with `nullptr`.
This commit compares _current_ with `nullptr` and exits selection mode if nothing is selected. The crash is described in the issue comment. [^1]
Here is the backtrace. 
<details><summary>Backtrace</summary>
```cpp
Process 1813 stopped
* thread #1, name = 'FreeCAD', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x0)
frame #0: 0x00007ffff6e4e6f1 libFreeCADGui.so`QListWidgetItem::text(this=0x0000000000000000) const at qlistwidget.h:85:22
82       void setFlags(Qt::ItemFlags flags);
83  
84       inline QString text() const
-> 85           { return data(Qt::DisplayRole).toString(); }
86       inline void setText(const QString &text);
87  
88       inline …
```
=> Fix crash described in 14370 (issue comment)

src/Mod/Sketcher/App/SketchObject.cpp
Fix #14563.   Could not devise a test to trigger this fail, which comes as a result of mouse movement triggering a redraw of a sketch in edit mode that contains invalid external geometry because the validation when the sketch goes into edit mode was failing to catch the correct exception type thrown by TNP code.
=> Toponaming: Fix crash with invalid external geometry

src/Mod/TechDraw/App/DrawViewSymbol.cpp
Qt 6.5 and later provide a new interface for setContent, and the old interface will be deprecated as of Qt 6.8.
=> TD: Use new Qt6.5 interface for setContent

src/Mod/Assembly/CommandInsertLink.py
Assembly: InsertLink: Use doc.Label instead of doc.Name because of bug of doc.Name not updating when file is saved.
Fixes https://github.com/FreeCAD/FreeCAD/issues/14684
=> Assembly: InsertLink: Use doc.Label instead of doc.Name 

src/Mod/Fem/Gui/PreCompiled.h, src/Mod/Fem/Gui/TaskCreateElementSet.cpp
* Move global (non-static) variables into anonymous namespace to avoid possible linking issues that may cause UB
* Fix compiler warnings
* Do not reinvent the wheel and use boost::to_upper_copy instead of own implementation
=> FEM: Fix several issues

src/Mod/TechDraw/Gui/DrawGuiUtil.cpp, src/Mod/TechDraw/Gui/DrawGuiUtil.h, src/Mod/TechDraw/Gui/QGIView.cpp, src/Mod/TechDraw/Gui/QGSPage.cpp, src/Mod/TechDraw/Gui/QGSPage.h
This PR implements a fix for issue #14051.  The QGraphicsScene and tree selection
states were getting out of sync when multi-select was active in the scene.
=> [TD]fix scene and tree selection sync

src/Mod/PartDesign/Gui/ViewProviderBody.cpp
Make sure that the view provider of a body feature provides the requested property
=> PD: Fix crash in ViewProviderBody::unifyVisualProperty

src/Gui/CMakeLists.txt, src/Gui/ToolBarAreaWidget.cpp, src/Gui/ToolBarAreaWidget.h, src/Gui/ToolBarManager.cpp, src/Gui/ToolBarManager.h, src/Gui/WorkbenchSelector.cpp
Since ToolBarAreaWidget is not a private class any more move its declaration and definition to their own source files.
=> Gui: Move ToolBarAreaWidget to its own files

src/Mod/BIM/ArchStairs.py
Fixes #14377
If the base edge of a stairs has a delta Z, the start point must have lowest Z. The `makeStraightStairsWithLanding` code fails otherwise.
Using `edge = Part.LineSegment().toShape()` is not the most efficient, but matches the pattern used elsewhere in the code.
=> BIM: Fix base edge direction for Arch_Stairs

src/Mod/Draft/draftgeoutils/fillets.py, src/Mod/Draft/draftmake/make_fillet.py
Fixes #11435
Draft_Fillet could already handle arcs, provided they were not Draft_Arcs. The `_extract_edge` function in make_fillet.py had a strange logic, and could also return a wire which would result in problems later.
Another issue was that the `fillet` function in fillets.py did not handle the order of the edges correctly if one of the edges was an arc and the other a straight edge. The arch had to be selected first to prevent this error.
=> Draft: Fix 2 issues to make Draft_Fillet handle arcs properly

src/Mod/BIM/ArchComponent.py
This is the easiest solution to #14687 I could come up with.
=> BIM: ArchComponent Only counts planar surfaces as vertical areas

src/Mod/Draft/draftguitools/gui_join.py
Add a type check for the selected objects. All must be Draft Wires.
Fixes #14727.
=> Draft: Add type check to Draft_Join

src/Mod/BIM/bimcommands/BimCopy.py
When the BIM Copy tool is used, it turns on the "Copy" checkbox in the task panel. Consequently, when running other Draft tools afterwards (Move, Rotate..) their Copy checkbox stays turned on even if that was not the intent. This PR fixes that by having the BIM Copy tool restore the Copy checkbox state when it's finished
=> BIM: Fix Copy tool stealing copy mode

src/Mod/BIM/importers/exportIFC.py
When exporting to IFC, extrusions (BIM/Arch extruded objects or Part Extrudes) are detected as such and exported as extrusions. This is intended for solids, as all IFC objects are supposed to be solids. However, in FreeCAD one can also use Part Extrusions to extrude lines to form faces. Since extruding lines is badly (or not at all?) supported by IFC, and it's not the intention anyway, it's best to export those not as extrusions but as Breps, which support non-solids well.
=> BIM: IFC: Export non-solids as Breps

src/Mod/BIM/Arch.py, src/Mod/BIM/ArchPipe.py
Pipe objects now have a *ProfileType* property that can be Circle (default), Square or Rectangle.
=> BIM: Added square and rectangular profiles to pipes

src/Mod/Assembly/Gui/CMakeLists.txt, src/Mod/Assembly/Gui/PreCompiled.h, src/Mod/CAM/PathSimulator/AppGL/EndMill.cpp, src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp, src/Mod/TechDraw/Gui/CommandExtensionPack.cpp, tests/src/Mod/Material/App/TestMaterials.cpp, tests/src/Mod/Part/App/FeatureChamfer.cpp, tests/src/Mod/Part/App/FeatureFillet.cpp, tests/src/Mod/Part/App/TopoShapeExpansion.cpp
* avoid redefines in Assembly
* explicit cast from size_t to int
* remove unused variables
* avoid implicit cast from double to float
* in test cases replace EXPECT_FLOAT_EQ with EXPECT_DOUBLE_EQ or EXPECT_NEAR when doubles are used
=> MSVC: Fix compiler warnings

src/Mod/Assembly/CommandCreateBom.py
Fix Ubuntu 20.04 CI failing that was due to an unecessary import.
=> Fix Ubuntu 20.04 CI failing

src/Mod/AddonManager/composite_view.py
When using a non-composite view, remember the scroll location of the packages list, and restore it when Back is clicked. Fixes #14776.
=> Addon Manager: Remember scroll position on Back

src/Gui/Tree.cpp
clang does not see the original `assert()` as a "use" of this variable, so compiling with "-Werror=unused-variable" fails. Since the code is only doing an assert, I've also wrapped it in an FC_DEBUG macro to clarify that it's only for debugging purposes and has no side effects (which I believe is true -- `getParentItem()` shouldn't actually change `item`).
=> Gui: Silence unused variable

src/Mod/CAM/Path/Main/Gui/SimulatorGL.py
The new CAM simulator imports `QDialogButtonBox` from `PySide2.QtWidgets`. This causes the CAM workbench to fail when Qt6 is used. Importing fom `PySide` instead fixes the issue.
=> CAM: replace import of PySide2 with PySide

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/femobjects/base_femelement.py, src/Mod/Fem/femobjects/base_femmeshelement.py, src/Mod/Fem/femobjects/element_fluid1D.py, src/Mod/Fem/femobjects/element_geometry1D.py, src/Mod/Fem/femobjects/element_geometry2D.py, src/Mod/Fem/femobjects/element_rotation1D.py, src/Mod/Fem/femobjects/mesh_boundarylayer.py, src/Mod/Fem/femobjects/mesh_group.py, src/Mod/Fem/femobjects/mesh_region.py, src/Mod/Fem/femviewprovider/view_base_femconstraint.py, src/Mod/Fem/femviewprovider/view_base_femelement.py, src/Mod/Fem/femviewprovider/view_base_femmaterial.py, src/Mod/Fem/femviewprovider/view_base_femmeshelement.py, src/Mod/Fem/femviewprovider/view_base_femobject.py, src/Mod/Fem/femviewprovider/view_element_fluid1D.py, src/Mod/Fem/femviewprovider/view_element_geometry1D.py, src/Mod/Fem/femviewprovider/view_element_geometry2D.py, src/Mod/Fem/femviewprovider/view_element_rotation1D.py, src/Mod/Fem/femviewprovider/view_material_common.py, src/Mod/Fem/femviewprovider/view_material_mechanicalnonlinear.py, src/Mod/Fem/femviewprovider/view_material_reinforced.py, src/Mod/Fem/femviewprovider/view_mesh_boundarylayer.py, src/Mod/Fem/femviewprovider/view_mesh_group.py, src/Mod/Fem/femviewprovider/view_mesh_region.py
Create own base class for Python objects for future improvements. Also, this fixes #14637.
@FEA-eng
=> Fem: Create own base class for Python objects - fixes #14637

src/Gui/SoFCUnifiedSelection.cpp, src/Gui/View3DInventorSelection.cpp, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
Fix #14847.  Add (adjusted) proposed test from #13248.  Correct test exposed by #14801 .
=> Toponaming: Check for selection mapped element name

src/Mod/Sketcher/Gui/SketcherSettings.cpp
fixes #14658 
renames preferences for OVP to:
- None
- Dimensions only
- Position and dimensions
@FreeCAD/design-working-group FYI
=> Sketcher: Rename OVP preference options

src/Mod/Draft/draftgeoutils/fillets.py
If two straight edges were selected the chamfer distance would be recalculated so that the length of the straight segment would be equal to `r` (the radius entered by the user). But this was, and is, not done if one or both edges are arcs.
By removing the recalculation code the endpoints of the straight chamfer edge now always match the endpoints of the fillet arc that would be created for the same radius. This also matches the fillet/chamfer behavior of a Draft_Wire and Draft_Rectangle and also the behavior we see in for example Part and Sketcher.
=> Draft: Remove Draft_Fillet chamfer recalculation

src/Mod/Draft/draftguitools/gui_dimensions.py
The Draft_Dimension command could convert Std_MeasureDistance objects. These have recently become obsolete. This PR removes the related code.
=> Draft: remove code related to obsolete Std_MeasureDistance objects

src/Mod/BIM/bimcommands/BimSetup.py
Fixes #14675.
Note that I would prefer to use the FEM unit system (always mm). BIM_Setup does not support that, and this PR does not change that.
=> BIM: fix BIM_Setup unit system issue

src/Mod/Sketcher/Gui/TaskSketcherElements.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
related to #13009
with TNP code enabled the selection of external geometries doesn't work as for the issue above.
This PR should fix the issue, probably without importing all the code related to #13310
=> [Sketcher] Fix external edges selection

src/Gui/Tree.cpp
Fixes https://github.com/FreeCAD/FreeCAD/issues/14732
Removes the automatic switch to CopyAction.
=> Core: Tree: Remove mode that creates copy automatically.

src/Gui/View3DSettings.cpp, src/Mod/Sketcher/Gui/SketcherSettings.cpp, src/Mod/Sketcher/Gui/SketcherSettings.ui, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
Fixes https://github.com/FreeCAD/FreeCAD/issues/13989
And reverts changes from https://github.com/FreeCAD/FreeCAD/pull/14013 as this did not solve https://github.com/FreeCAD/FreeCAD/issues/13989 This solution works in all themes and with all colors and shininess values without making the document darker or changing light direction.
The idea is:
- change to the override draw style `No Shading` when entering a sketch. Therefore, no light needs to be changed and the sketch is always visible
- change back to the previous override draw style when leaving the sketch
A new preference is introduced: `Disable shading in edit mode`, default activated.
If this setting is checked, the override draw style switches to `No Shading` when entering the sketch edit mode.
The previous override draw style is …
=> Sketcher: Changes override draw style when entering sketch edit mode.

src/Gui/Quarter/QuarterWidget.cpp, src/Gui/Quarter/QuarterWidget.h, src/Gui/View3DInventorViewer.h
Closes #14189. This commit partially reverts d15c7d067341eacd10245b58465902546cdedea6 and fb372012991c3b6da359115f3e329f3166ebc5bc.
This pull request must be carefully checked before merge; perhaps, ven. @wwmayer might want to look at it.
I don't know the cause of the crash.
=> Fix the crash when closing a document

src/Gui/WorkbenchSelector.cpp, src/Gui/WorkbenchSelector.h
It ensures that for icon-only style it is displayed in the middle and empty text is not accounted while calculating tab size hint. This also disables changing workbenches via scroll.
After:
Before:
Custom styles may need to target `QTabBar[style="icon-only"]` to apply specific fixes like disabling padding like:
```scss
QTabBar[style="icon-only"]::tab {
min-width: 16px;
min-height: 16px;
&:top, &:bottom {
padding-right: 0;
}
&:left, &:right {
padding-top: 0;
}
}
```
Fixes: https://github.com/FreeCAD/FreeCAD/issues/14282
Fixes: https://github.com/FreeCAD/FreeCAD/issues/14165
=> Gui: Workbench TabBar - fix scroll and icon-only paddings

src/Mod/CAM/libarea/CMakeLists.txt, src/Mod/MeshPart/App/CMakeLists.txt
On some systems the boost-python suffix is not exactly as the code currently expects. To avoid getting even more guessing in the CMake files about how exactly the python component is named in the boost installation we introduce a variable FORCE_BOOST_PY_SUFFIX that can enforce a specific suffix. If the variable is not set the behavior is as before.
=> implement FORCE_BOOST_PY_SUFFIX

src/Gui/Application.cpp, src/Mod/Fem/Gui/TaskCreateElementSet.cpp, src/Mod/Import/App/AppImportPy.cpp, src/Mod/Import/App/ReaderStep.cpp, src/Mod/Import/App/ReaderStep.h, src/Mod/Import/Gui/AppImportGuiPy.cpp, src/Mod/Part/App/OCAF/ImportExportSettings.cpp, src/Mod/Part/App/OCAF/ImportExportSettings.h, src/Mod/Part/App/STEP/ImportExportSettings.cpp, src/Mod/Part/App/STEP/ImportExportSettings.h, src/Mod/Part/Gui/DlgImportStep.cpp, src/Mod/Part/Gui/DlgImportStep.h, src/Mod/Part/Gui/DlgImportStep.ui
Currently a modal dialog is used directly in ImportGui.open()/ImportGui.insert() that makes it impossible to use the functions in a script because they will be blocked
* Support of import options
* Move options handling to ImportGui.importOptions
* Simplify handling of Resource_FormatType
=> Import: Avoid modal dialog inside ImportGui.open()

src/Gui/Tree.cpp
The gui texts for "Show description" and "Show internal name" were inconsistent.
"Show description column" -> "Show description"
"Show an extra tree view column for item description. -> "Show a description column for items."
=> Gui: Tree.cpp make some gui texts more consistent

.pre-commit-config.yaml
This pins the versions of pre-commit code to known git commits rather than mutable branches or tags.
=> pre-commit: Pin versions

src/Mod/Fem/Gui/TaskFemConstraint.cpp, src/Mod/Fem/Gui/TaskFemConstraint.h
It's not clear what the comment on these meant, but the compiler marks them as unused. Maybe vestigial?
=> FEM: Remove unused members

src/App/ComplexGeoData.cpp, src/App/Property.cpp, src/App/Property.h, src/Base/Reader.cpp, src/Base/Writer.cpp, src/Base/Writer.h, src/Mod/Part/App/PropertyTopoShape.cpp, src/Mod/Part/App/PropertyTopoShapeList.cpp, src/Mod/Part/App/PropertyTopoShapeList.h, src/Mod/Part/App/TopoShape.cpp, src/Mod/Part/parttests/TopoShapeTest.py, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
Add a test to prove that elementmaps in a sketch last past a save and restore.  Correct the shape and property code at various levels to work correctly.
=> Toponaming: Fix save and restore of elementmaps

src/Gui/ViewProvider.cpp, src/Gui/ViewProvider.h, src/Gui/ViewProviderPy.xml, src/Gui/ViewProviderPyImp.cpp, src/Mod/Assembly/CommandInsertLink.py
Fix https://github.com/FreeCAD/FreeCAD/issues/14933
Fix another unlisted bug where groups where appearing even if they had nothing interesting (joint group were appearing for example). It was because it was using OutListRecursive and groundedObject linked to a part.
So instead it now use claimChildren. So the tree is building correctly.
This PR also adds 'claimChildrenRecursive' to view provider.
=> Assembly: Insert Component: Fix assembly not appearing

src/Gui/Quarter/QuarterWidget.cpp
Move this variable inside the (no-longer-used?) debug block.
=> Gui: Remove unused ref to GL context

src/Mod/Part/App/TopoShapeExpansion.cpp, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py, tests/src/Mod/Part/App/TopoShapeExpansion.cpp
Change the definitions of the `makeElementWires` methods, aligning them with LS3 fork.
For reference:
https://github.com/realthunder/FreeCAD/blob/0e9cf4aa7c7bac94a83edd07b4bd74a71a26446c/src/Mod/Part/App/TopoShapeEx.cpp#L3004
https://github.com/realthunder/FreeCAD/blob/0e9cf4aa7c7bac94a83edd07b4bd74a71a26446c/src/Mod/Part/App/TopoShapeEx.cpp#L3181
In my tests this fixes #14436
=> Part/Toponaming: makeElementWires - import from LS3 fork

src/Mod/AddonManager/composite_view.py
In Qt6 the Addon Manager does not expand to fill the view -- this PR addresses that. Fixes #14841.
=> Addon Manager: Allow widget expansion in Qt6

src/Gui/ReportView.cpp
ReportView has a missing Python interpreter lock.  It is not breaking FreeCAD in general but it is deemed a bug nonetheless.  See #14957.
Closes #14957.
=> Core: Fix a missing Python interpreter lock

cMake/FreeCAD_Helpers/SetupCoin3D.cmake
Making this a fatal error kills the Snap builds. Fixes #14955
=> cMake: Make a failure to import Pivy non-fatal

src/Mod/TechDraw/App/DrawSVGTemplate.cpp, src/Mod/TechDraw/App/DrawTemplate.cpp, src/Mod/TechDraw/App/DrawTemplate.h, src/Mod/TechDraw/Gui/DlgTemplateField.cpp, src/Mod/TechDraw/Gui/DlgTemplateField.h, src/Mod/TechDraw/Gui/DlgTemplateField.ui, src/Mod/TechDraw/Gui/QGISVGTemplate.cpp, src/Mod/TechDraw/Gui/TemplateTextField.cpp, src/Mod/TechDraw/Gui/TemplateTextField.h
This PR is a continuation of PR #14863 and implements a fix for the display of autofill value and handling of various common spellings in svg code as discussed here: https://forum.freecad.org/viewtopic.php?t=88142
=> [TD]Fix template autofill - show autofill value and handle multiple spellings

src/Mod/BIM/InitGui.py
Missing or wrong items from the Arch->BIM migration
Issue #14087
=> BIM: Adeed missing menu entries

src/Gui/PreferencePages/DlgSettingsGeneral.cpp, src/Gui/PreferencePages/DlgSettingsGeneral.ui
For Preferences > General > Application > Tree view mode:
- Remove the 'Both' option from the tooltip, as this option is no longer available.
- Rephrase the ComboView option (and by extension the TreeView and PropertyView) to be simpler and self-descriptive.
- Allows for an easier and more genuine translation
**Before**:
**After**:
=> Update Tree view mode tooltip and text in Preferences

src/Mod/Assembly/CommandCreateBom.py, src/Mod/Assembly/Gui/Resources/panels/TaskAssemblyCreateBom.ui, src/Mod/Assembly/Gui/ViewProviderBom.cpp, src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp
- Fixes some comments from @wwmayer 
- Make auto-generated columns bold to differentiate them from custom columns
- Add a help button with details
- Rename 'Detail parts' to 'Parts children' as I think it's clearer.
=> Assembly: BOM follow up

src/Gui/MainWindow.cpp, src/Gui/ToolBarAreaWidget.cpp, src/Gui/ToolBarManager.cpp, src/Gui/ToolBarManager.h, src/Gui/resource.cpp, src/Mod/BIM/BimStatusBar.py, src/Mod/BIM/bimcommands/BimIfcExplorer.py, src/Mod/BIM/bimcommands/BimViews.py, src/Mod/Draft/DraftGui.py
This adds dragging support for toolbars placed in custom toolbar areas. It is achived by creating our own custom ToolBar class that handles logic of providing custom gripper. This is required because Qt hides gripper when toolbar is not direct child of the main window which cannot be overriden. Custom class should allow us to create more capable toolbars in the future so it should be great addition on its own.
Continuation of PR https://github.com/FreeCAD/FreeCAD/pull/13571, replaces https://github.com/FreeCAD/FreeCAD/pull/13973.
@PaddleStroke If you could test it that would be nice.
=> Gui: Add dragging support for custom ToolBarAreas

src/Mod/Part/App/FeaturePartBoolean.cpp, src/Mod/Part/App/FeaturePartCommon.cpp, src/Mod/Part/App/FeaturePartFuse.cpp, src/Mod/Part/Gui/DlgSettingsGeneral.ui, src/Mod/PartDesign/App/FeatureAddSub.cpp, src/Mod/PartDesign/App/FeatureBoolean.cpp, src/Mod/PartDesign/App/FeatureTransformed.cpp, src/Mod/PartDesign/App/ShapeBinder.cpp, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py, src/Mod/Sketcher/SketcherTests/TestSketcherSolver.py
fixes https://github.com/FreeCAD/FreeCAD/issues/13472
Makes these preferences activated by default to check and refine the model:
@howie-j FYI
=> Activate Part/Part Design check and refine preferences by default

src/Gui/SoTextLabel.cpp, src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp, src/Mod/Measure/Gui/ViewProviderMeasureBase.h
Currently the icons in measurement labels are always black which can be a problem when the background color is changed. With this PR  the icon's color is is updated whenever the textcolor property changes.
=> MeasureGui: Paint icons in textcolor

src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
Fixes #14795: testPartDesignElementMapSketch: Duplicate test method name
=> PD: Rename duplicated test method

src/Mod/Assembly/App/AssemblyObject.cpp, src/Mod/Assembly/App/AssemblyObject.h, src/Mod/Assembly/AssemblyTests/TestCore.py, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp, src/Mod/Assembly/JointObject.py, src/Mod/Assembly/UtilsAssembly.py
Modify the properties of assemblies joints so that they can support the TNP mitigation.
Object1/2 Element1/2 Vertex1/2 string properties are replaced by Object1/2 PropertyXLinkSub
Note: it appears that PropertyXLinkSub currently is not updating when shape changes, which should be fixed separately.
Note2: this introduce a migration script to support backward compatibility.
Fixes https://github.com/FreeCAD/FreeCAD/issues/14102
=> Assembly: TNP

src/Mod/BIM/bimcommands/BimBox.py, src/Mod/Draft/draftguitools/gui_trackers.py
Fixes #14823.
Depending on the order and location of the picked points, the Placement of the Box could be unexpected. The Height value was always positive if points were picked, a negative Height entered in the input box would lead to errors.
Additonally:
* Avoided some code duplication.
* Added a proper transaction to make the command undoable.
=> BIM: Fix BIM_Box command

src/Mod/BIM/bimcommands/BimIfcExplorer.py
Fixes the error message that appears when closing the dialog with no file open - fixes #14422
=> BIM: Fixed error when closing IfcExplorer tool

src/Mod/Start/Gui/StartView.cpp
=> StartView: Escape file paths when loading

src/Mod/Sketcher/App/ExternalGeometryFacade.cpp
The format string of the warnings were incorrect and caused an fmt::format_error exception
=> Sketcher: Fix format string in ExternalGeometryFacade::initExtensions()

src/Mod/Start/Gui/Manipulator.cpp, src/Mod/Start/Gui/StartView.cpp, src/Mod/Start/Gui/StartView.h
Do not attach the Start Page to an existing document as otherwise weird behaviour can be observed:
1. Start FreeCAD
2. Open a project file or data file
3. Open the Start Page
4. Make a change to the document
5. Close the document. You won't be asked to save your change
6. In the tree view the document is still shown because the Start Page is attached to the document
7. Close the Start Page. Now you will be asked to save your change
=> Start: Make the Start Page a passive view

src/Mod/PartDesign/Gui/Workbench.cpp
Fixes #15162
This tool has no toolbar button so the PR only removes it from the PD menu.
=> PD: Remove the Migrate tool from GUI

src/Gui/Workbench.cpp
=> Gui: Don't show Python console by default

cMake/FreeCAD_Helpers/SetupQt.cmake
We should no longer need this module.
=> cMake: Remove use of Core5Compat from Qt6

src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h
Command::doCommand may throw an exception that isn't handled by the active sketch handler. This may leave it in an inconsistent state and can cause a crash later.
See #14945
=> Sketcher: Handle PyException in createGeneratedAutoConstraints

src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h
=> Sketcher: BSpline: Fix crash when cancelled while only one autoconstrained point

src/Mod/Part/App/MeasureClient.cpp
This fixes the issues described in #14593 by by explicitly passing the last object in the subjects subobject list to getTopoShape as well as the subElementName.
fixes #14593
=> Measure: Fix restoring/creating measurements of sketch elements

src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h
Fixes https://github.com/FreeCAD/FreeCAD/issues/14964
If you created a new sketch, then start the bspline tool and change mode, it would crash.
It's because it was doing a abortCommand on reseting the tool before the command was opened. So it cancelled the create sketch command. The sketch object being gone the tool handler caused an illegal storage access while trying to access it.
=> Sketcher: BSpline DSH: Fix crash #14964

src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp, src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
Combining booleans and integers using bitwise OR is considered unsafe by MSVC, generating `warning C4805: '|': unsafe mix of type 'int' and type 'bool' in operation`. Specifically convert the boolean to an integer.
=> Sketcher: Resolve unsafe combination of bool and int in |

src/Mod/TechDraw/Gui/CommandCreateDims.cpp
- Fix #14038 by adding 
```
else {
references3d.clear();
}
```
to make sure no unwanted reference3d is added.
- Refactor CommandCreateDims by adding execDim to reduce code duplicity.
=> TechDraw: Fix 14038 and Refactor CommandCreateDims 

src/Mod/Sketcher/Gui/EditModeCoinManager.cpp, src/Mod/Sketcher/Gui/SketcherSettingsAppearance.ui
A tiny step towards #13318, makes the construction, external and internal alignment lines a bit more visible by default.
Before:
After:
=> Sketcher: Increase default width of dashed lines

src/Mod/Part/parttests/TopoShapeTest.py, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py, src/Mod/Sketcher/SketcherTests/TestSketcherSolver.py
The Refine property must be explicitly set as otherwise some tests will break because of different user settings
=> Tests: Make PD and Sketcher tests independent of user settings

src/Mod/AddonManager/NetworkManager.py
Errors received updating local cache in AddonManager:
```
File "/home/john/freecad-main-build781/Mod/AddonManager/NetworkManager.py", line 587, in __reply_finished
timeout_ms = request.transferTimeout()
AttributeError: 'PySide2.QtNetwork.QNetworkRequest' object has no attribute 'transferTimeout'
```
This PR fixes these errors and allows the cache update to complete.
=> [AddonManager] Fix transferTimeout AttributeError

src/Mod/Material/Gui/MaterialsEditor.ui, src/Mod/Material/Gui/ModelSelect.ui
Having only `*`, `+` & `-` as reference is not intuitive. Tooltips help users to know what each button does.
Also marked symbols as not translatable as they appear on CrowdIn.
=> Materials: Add tooltips to buttons

src/Gui/TaskView/TaskDialog.cpp, src/Gui/TaskView/TaskDialog.h, src/Gui/TaskView/TaskDialogPython.cpp, src/Gui/TaskView/TaskDialogPython.h, src/Gui/TaskView/TaskView.cpp, src/Gui/TaskView/TaskView.h
* Add TaskDialog::autoClosedOnDeletedDocument()
* Add option to automatically close task dialog when document is deleted
* Expose autoClosedOnDeletedDocument() to Python
* Expose autoClosedOnTransactionChange() to Python
* Change ControlPy::showDialog() to directly return the task dialog wrapper
* Change TaskView::slotDeletedDocument() to close task dialog if requested
=> Gui: Extend TaskDialog

src/Base/BaseClass.h, src/Base/Type.cpp, src/Base/Type.h, src/Gui/DlgAddProperty.cpp
Fixes #15159: Dialog for adding properties allows property types that give exceptions
=> Core: In dialog to add property only list types that can be instantiated

src/App/Application.cpp, src/App/PropertyLinks.cpp, src/App/PropertyLinks.h
This PR is adding a PropertyXLinkSubHidden property. Which is just a PropertyXLinkSub with the hidden scope.
This addition is needed to solve the assembly 'getGlobalPlacement' (https://github.com/FreeCAD/FreeCAD/issues/15090) where  PropertyXLinkSub cannot be used because it cause dependency loops.
@wwmayer is this change ok for you? If so it would be great if this can be merged as soon as possible because this change requires almost a full rebuild, so everytime I checkout from my 15090-branch (which is a huge work so i'll be at it for long), I have to rebuild almost the whole project which takes more than 30 minutes on my machine. And currently I have 15 opened PR to maintain so this is bound to be very tedious. Also this change is very trivial.
Thanks!
=> Core: Add App::PropertyXLinkSubHidden

src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_GeometricHatch.svg
This change was made upon requesting that the PAT text be more readable. It was known that the pat text was not legible before, but it stood there like a stain, making a difference. This was done to prevent the hantch icon from being covered. Because the priority of this icon is to show the hatch. However, the desired change was made. I find the previous one more accurate.
It is my first attempt with PAT written on it. The second and third one is the suggestion given by the @kadet1090.
=> [Icons]TechDraw_GeometricHatch.svg fix

src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_PageTemplate.svg
It was made based on the following topic in the forum: [techdraw: a new symbol is heavily misleading](https://forum.freecad.org/viewtopic.php?t=88910)
I'm not sure it completely solves the problem, but it's definitely an attempt. Other attempts are as follows:
=> [Icons]TechDraw_PageTemplate.svg fix

cMake/FreeCAD_Helpers/CopyLibpackDirectories.cmake, cMake/UseLibPack3.cmake
Make sure the DLLs are all going into bin. This leaves a (possibly vestigial) copy of Boost going into lib as well. That can probably be removed in another PR (but needs to be tested with Libpack2).
=> cMake: Fix LibPack3 install target DLL locations

src/Mod/AddonManager/addonmanager_freecad_interface.py, src/Mod/AddonManager/addonmanager_preferences_defaults.json, src/Mod/AddonManager/addonmanager_workers_installation.py, src/Mod/AddonManager/addonmanager_workers_startup.py
Reduce the number of GitHub fetches when rebuilding the local addon cache by using a remote cache stored on FreeCAD's servers.
Intended to mitigate the Addon Manager hitting GitHub's rate limiters.
Addresses, but does not fully close, #15059
=> Addon manager: Reduce fetches from GitHub

src/Mod/Fem/Gui/DlgSettingsFemInOutVtk.ui
Removes an empty item from the drop-down list in Preferences --> Import-Export --> VTK --> Which object to import into
=> FEM: Remove empty preference list item

src/Gui/CMakeLists.txt, src/Gui/CommandView.cpp, src/Gui/Workbench.cpp, src/Mod/Measure/Gui/AppMeasureGui.cpp, src/Mod/Measure/Gui/CMakeLists.txt, src/Mod/Measure/Gui/Command.cpp, src/Mod/Measure/Gui/TaskMeasure.cpp, src/Mod/Measure/Gui/TaskMeasure.h, src/Mod/Measure/Gui/WorkbenchManipulator.cpp, src/Mod/Measure/Gui/WorkbenchManipulator.h
This is an attempt to solve #15125 by moving the measure command (Std_Measure) and task dialog to the measure module. They were moved to the core at some point because the command should be globally available in all workbenches. With this PR the command is inserted into the "View" toolbar at startup.
Note: This currently removes the command from the "Tools" menu which might be a showstopper. I was able to add it there as well but i didn't manage to have it persist. There is some information on that topic [here](https://forum.freecad.org/viewtopic.php?t=30761&start=10) but it seems outdated.
Closes #15125
=> MeasureGui: Fix measure dependency violation

src/Mod/Part/App/TopoShapePy.xml, src/Mod/Part/App/TopoShapePyImp.cpp, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
As discussed with @bgbsww [here:](https://github.com/FreeCAD/FreeCAD/issues/15095#issuecomment-2204279479)
The python shape function getElement does not handle TNP names. 
This is one of the reasons that causes issues with App::propertyLinkSub as mentioned in  #15095
When testing on LS3 this function indeed supports TNP long names.
The fix is basically using LS3 implementation.
A unit test function wad added as well.
=> [TNP] Fix python get element. partially fixes #15095

src/Gui/DlgAddPropertyVarSet.cpp, src/Gui/DlgAddPropertyVarSet.h
In the VarSet dialog, we can create an editor after the name and type has been determined.  However, if the name is changed after an editor has been created, the editor is invalid because the underlying property has been removed.  In that case, the function `onNamePropertyDetermined()` should clean up the invalid editor and this happens in most cases. Unfortunately, it cannot handle the case in which a click happens on the invalid editor itself.  This click should result in `onNamePropertyDetermined()` but since the editor is already invalid, `onNamePropertyDetermined()` is triggered too late.
The current commit solves this by listening for every change in the name of the property and handle the editors accordingly.
Closes #15157
=> Gui: Prevent invalid editors in VarSet dialog

src/Mod/CAM/Path/Main/Gui/SimulatorGL.py, src/Mod/CAM/Path/Post/scripts/generic_post.py, src/Mod/CAM/PathSimulator/AppGL/SimShapes.cpp
Cleans code, doesn't touch translations.
=> Path (and PathSimulator): Trim trailing newlines

src/Mod/Assembly/CommandInsertLink.py
Prevent insertion of parent objects that cause dependency loop and crash.
Fix https://github.com/FreeCAD/FreeCAD/issues/15221
=> Assembly: Prevent insertion of parent objects that cause dependency loop

src/Mod/Sketcher/Gui/SketcherSettings.cpp, src/Mod/Sketcher/Gui/SketcherSettings.h, src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensionsImp.cpp, src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensionsImp.h
- add SketcherSettings::resetSettingsToDefaults to reset correctly some settings.
- add DlgPrefsTechDrawDimensionsImp::resetSettingsToDefaults to reset correctly some settings
fix https://github.com/FreeCAD/FreeCAD/issues/14107
=> Sketcher/Techdraw: add resetSettingsToDefaults to reset correctly dimension tool settings

src/Gui/InventorAll.h, src/Mod/Measure/App/MeasureDistance.cpp, src/Mod/Measure/App/MeasureDistance.h, src/Mod/Measure/Gui/AppMeasureGui.cpp, src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp, src/Mod/Measure/Gui/ViewProviderMeasureBase.h, src/Mod/Measure/Gui/ViewProviderMeasureDistance.cpp, src/Mod/Measure/Gui/ViewProviderMeasureDistance.h
As [requested](#13741), this adds back the ability to display the X, Y and Z components of a measured distance. This PR adds the following:
- DistanceX, DistanceY, DistanceZ properties on the MeasureDistance feature
- The previously removed PartGui::DimensionLinear nodekit (now in the MeasureGui namespace)
- ShowDelta property on the ViewProviderMeasureDistance which is set to false by default
- The three component dimensions with a value text and colored in the axis colors
To see the components the user currently has to create a distance constraint and manually set the view property "Show Delta" to true.
fixes #13741
=> MeasureGui: Add MeasureDistance X, Y and Z components back

src/Mod/Fem/App/FemTools.cpp, src/Mod/Fem/App/PreCompiled.h, src/Mod/Fem/Gui/DlgSettingsFemGeneralImp.cpp, src/Mod/Fem/Gui/Workbench.cpp
I think the original intention is to check if the mentioned executable exists in system path. Original method only checks if the given *full path*(absolute or relative) exists or not, and is not actually searching the executable in system path.
This patch switches to `QStandardPaths::findExecutable` to find a desired executable in system path.
There's a note caught my attention in QT's doc though:
> On Windows, the usual executable extensions (from the PATHEXT environment variable) are automatically appended. For example, the findExecutable("foo") call finds foo.exe or foo.bat if present.
=> Fem: fix searching 3rd-party binaries in system path

src/Mod/Material/Gui/MaterialTreeWidget.cpp, src/Mod/Material/Gui/MaterialTreeWidget.h
Sets a minimum size for the material tree since it can't be resized when used in a task panel.
fixes #14686
=> Materials: Set MaterialTreeWidget minimum size

src/Mod/Part/App/TopoShape.h, src/Mod/Part/App/TopoShapeExpansion.cpp, src/Mod/PartDesign/App/Feature.cpp, src/Mod/PartDesign/App/Feature.h
Fix #15054  Add the necessary property to hold the pre-suppression shape so that it can be restored when unsuppressed.  Correct the Feature code to use it.
=> Toponaming: Missing suppress property and code

src/Mod/Measure/Gui/QuickMeasure.cpp
Quickmeasure: disable for sketch in edit mode due to incorrect behavior : 
Fixes https://github.com/FreeCAD/FreeCAD/issues/15120
It seems quite difficult to make it work in sketch edit mode.
=> Measure: Quickmeasure: disable for sketch in edit mode

src/Gui/Stylesheets/Dark theme.qss, src/Gui/Stylesheets/Light theme.qss, src/Mod/Start/Gui/StartView.cpp
This adds ability to target New File buttons via `#CreateNewRow > QPushButton` selector.
This issue is related to problem with QSS resetting the minimum width of a widget. It is well known problem: https://stackoverflow.com/questions/56035625/setting-minimum-width-of-qpushbutton-while-keeping-default-minimumsizehint-behav and the simplest solution is to simply not set minimum width via QSS for widgets. minimum width is however required for some QPushButtons so we need a way to target only buttons in this specific row of Start View.
After
Before
Fixes https://github.com/FreeCAD/FreeCAD/issues/14347
=> Gui: Ability to target new file buttons via QSS.

src/Mod/BIM/nativeifc/ifc_commands.py
makes Save divert to SaveAs if the file hasn't been saved before
fixes #15362
=> BIM: Fix save tool

src/Gui/propertyeditor/PropertyEditor.cpp, src/Gui/propertyeditor/PropertyEditor.h
This forces background to be rendered using `itemBackground` QProperty.
This can be done like so:
```
Gui--PropertyEditor--PropertyEditor {
qproperty-itemBackground: white;
}
```
After:
Before:
Fixes: #15263
FYI: @obelisk79 @MisterMakerNL
=> Gui: Fix background of non-alternate rows of Property View

src/Gui/ViewParams.h, src/Gui/ViewProviderDragger.cpp, src/Gui/ViewProviderLink.cpp, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
The size can now be configured using `User parameter:BaseApp/Preferences/View/DraggerScale` parameter.
In code value of this parameter is exposed as convenience function `SoFCCSysDragger::getScaleFromUserParameters` which adds dependency from `Gui` to `Application.h`. I'm not sure if this is ok - @wwmayer if it is not please point to a better place for such function.
Before:
After:
Fixes: #13853
=> Gui: Reduce Transform Dragger size

src/Mod/Material/Gui/MaterialTreeWidget.cpp
When the UUID is set to a non-existent material, it was Catching Materials::ModelNotFound instead of Materials::MaterialNotFound
=> Materials: Catch correct error

src/Base/BaseClass.h, src/Base/Type.cpp, src/Base/Type.h, src/Gui/DlgAddProperty.cpp, src/Gui/DlgAddPropertyVarSet.cpp, src/Gui/DlgAddPropertyVarSet.h
This PR makes a better distinction between property types that should not be supported because they are more for internal use, for example as base classes, such as `App::Property` and `App::PropertyLinkBase`.
It also loads font data for `App::PropertyFont`
Closes #15156
Note that there are other issues related as well. For example, https://github.com/FreeCAD/FreeCAD/issues/15159 has a similar problem with properties that result in exceptions.
=> Gui: Handle various property types better in VarSet dialog

src/Mod/Sketcher/Gui/CommandConstraints.cpp
Fix right click/esc so that it dismiss the dimension before exiting the tool.
Fix https://github.com/FreeCAD/FreeCAD/issues/13940
=> Sketcher: Dimension: Fix right click/esc so that it dismiss the dim

src/Gui/CallTips.cpp, src/Gui/CallTips.h
See #15236, thanks @Jookia!
Shiboken 6.4.0 to 6.8.0 and newer crash when using getAttr on their objects. On these versions and newer, use a wrapper function to call getattr.
Fixes https://github.com/FreeCAD/FreeCAD/issues/14101
Obsoletes PR https://github.com/FreeCAD/FreeCAD/pull/14864
Obsoletes PR #15236
=> GUI: Work around Shiboken 6 bug for CallTips

src/Gui/TaskView/TaskImage.cpp
Fix one of the case where taskbox does not close if document is closed.
This is one of the things found in : 
https://github.com/FreeCAD/FreeCAD/issues/9297
=> Core: Image taskbox : close if document is closed.

src/Mod/Sketcher/Gui/DrawSketchHandlerRotate.h, src/Mod/Sketcher/Gui/DrawSketchHandlerTranslate.h
Fix https://github.com/FreeCAD/FreeCAD/issues/12034
Please @Roy-043 check the screenshot above and let me know if this phrasing is better.
Note the 2 missing spaces are added.
=> Sketcher: Rotate: correct the name of the checkbox

src/Base/Reader.cpp, src/Base/Reader.h
This is the first in a series of incremental code transfers to solve the save/restore errors with objects with element maps..
=> Expand reader getAttribute calls to accept a default value

src/Mod/Part/App/AppPart.cpp, src/Mod/Part/App/GeometryMigrationExtension.cpp, src/Mod/Part/App/GeometryMigrationExtension.h, src/Mod/Part/App/PartFeature.cpp, src/Mod/Part/App/PartFeature.h, src/Mod/Sketcher/App/ExternalGeometryExtension.cpp, src/Mod/Sketcher/App/ExternalGeometryExtension.h, src/Mod/Sketcher/App/ExternalGeometryFacade.cpp, src/Mod/Sketcher/App/ExternalGeometryFacade.h, src/Mod/Sketcher/App/GeometryFacade.cpp, src/Mod/Sketcher/App/GeometryFacade.h, src/Mod/Sketcher/App/SketchGeometryExtension.cpp, src/Mod/Sketcher/App/SketchGeometryExtension.h
Third in series of incremental code transfers to solve the save/restore errors with objects with element maps..
=> Toponaming: refactor getExportElementName to separate method

src/Mod/Part/App/AppPart.cpp, src/Mod/Part/App/GeometryMigrationExtension.cpp, src/Mod/Part/App/GeometryMigrationExtension.h, src/Mod/Sketcher/App/ExternalGeometryExtension.cpp, src/Mod/Sketcher/App/ExternalGeometryExtension.h, src/Mod/Sketcher/App/ExternalGeometryFacade.cpp, src/Mod/Sketcher/App/ExternalGeometryFacade.h, src/Mod/Sketcher/App/GeometryFacade.cpp, src/Mod/Sketcher/App/GeometryFacade.h, src/Mod/Sketcher/App/SketchGeometryExtension.cpp, src/Mod/Sketcher/App/SketchGeometryExtension.h
Second in series of incremental code transfers to solve the save/restore errors with objects with element maps..
=> Add RefIndex to ExternalGeometryReference and new migration types

src/App/MeasureManager.cpp, src/App/MeasureManager.h, src/Mod/Measure/App/MeasureAngle.cpp, src/Mod/Measure/App/MeasureArea.cpp, src/Mod/Measure/App/MeasureBase.h, src/Mod/Measure/App/MeasureDistance.cpp, src/Mod/Measure/App/MeasureLength.cpp, src/Mod/Measure/App/MeasurePosition.cpp, src/Mod/Measure/App/MeasureRadius.cpp, src/Mod/Measure/Gui/TaskMeasure.cpp, src/Mod/Part/App/MeasureClient.cpp
As described in #14559 measurements don't properly work with the integrated assembly workbench. This PR adds checks for App::Link types and resolves them to get the responsible module and fixes the retrieval of the located shapes.
Closes #14559
=> Measure: Fix measure issues in assemblies

src/Gui/PythonWrapper.cpp
- Shiboken headers need to be included first to get MAJOR/MINOR version flags. Without them the code would still compile, but fail the version check a few lines below assuming Shiboken is always older than 5.12
- Fix typo in cast when HAVE_SHIBOKEN_TYPE_FOR_TYPENAME is defined and remove the conditional: we have to assume typeForTypeName() always results in a valid name, as for the other implementations. There's no error handling of any kind in callers.
This fixes the build on debian unstable with shiboken 5.15.
=> Gui: Fix Shiboken version detection and compilation error

src/Mod/Assembly/CommandCreateView.py, src/Mod/Assembly/CommandExportASMT.py
Assign E key for Exploded view instead of V that is used by core commands.
Remove E key shortcut of Export ASMT as this tool is mostly for debug it does not need a shortcut.
Fix https://github.com/FreeCAD/FreeCAD/issues/15386
=> Assembly: Fix conflicting shortcut for Exploded view

src/Mod/AddonManager/AddonManagerTest/app/test_git.py
The previous technique for skipping these tests did not work (and LibPack 3 does not provide git). Try a different way.
=> Addon Manager Tests: Skip all git tests if git is not present

src/Mod/CAM/Tools/README.md
Fixed a misspelling, added some commas, changed all occurrences of PDN (PartDesignNext) or PD to PartDesign to improve readability. (And update the text, since PartDesignNext was new in version 0.17 or so, and stable is now 0.21.2. )
=> [CAM] Minor fixes to improve README.md file readability

src/Mod/PartDesign/TestPartDesignGui.py
In Qt6, attempting to close a modal dialog that has a `QDialogButtonBox` by searching it for `QPushButton`s does not work (the buttons are not guaranteed to be of that particular class). This PR updates the test code to simply call the `accept()` slot on the dialog. It also renames the `diag` variable to `dialog`, and the check function from `CallableCheckDialog` to `CallableCheckDialogWasClosed`.
Fixes #14840.
=> PD/Tests: Correct TestPartDesignGui for Qt6

src/Mod/PartDesign/Gui/TaskChamferParameters.cpp, src/Mod/PartDesign/Gui/TaskDraftParameters.cpp, src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp, src/Mod/PartDesign/Gui/TaskDressUpParameters.h, src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp, src/Mod/PartDesign/Gui/TaskFeatureParameters.cpp, src/Mod/PartDesign/Gui/TaskFeatureParameters.h, src/Mod/PartDesign/Gui/TaskFilletParameters.cpp, src/Mod/PartDesign/Gui/TaskHelixParameters.cpp, src/Mod/PartDesign/Gui/TaskHelixParameters.h, src/Mod/PartDesign/Gui/TaskHoleParameters.cpp, src/Mod/PartDesign/Gui/TaskHoleParameters.h, src/Mod/PartDesign/Gui/TaskLoftParameters.cpp, src/Mod/PartDesign/Gui/TaskLoftParameters.h, src/Mod/PartDesign/Gui/TaskPadParameters.cpp, src/Mod/PartDesign/Gui/TaskPadParameters.h, src/Mod/PartDesign/Gui/TaskPipeParameters.cpp, src/Mod/PartDesign/Gui/TaskPipeParameters.h, src/Mod/PartDesign/Gui/TaskPocketParameters.cpp, src/Mod/PartDesign/Gui/TaskPocketParameters.h, src/Mod/PartDesign/Gui/TaskPrimitiveParameters.cpp, src/Mod/PartDesign/Gui/TaskPrimitiveParameters.h, src/Mod/PartDesign/Gui/TaskRevolutionParameters.cpp, src/Mod/PartDesign/Gui/TaskRevolutionParameters.h, src/Mod/PartDesign/Gui/TaskSketchBasedParameters.cpp, src/Mod/PartDesign/Gui/TaskThicknessParameters.cpp, src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp, src/Mod/PartDesign/Gui/TaskTransformedParameters.h, src/Mod/PartDesign/Gui/ViewProvider.cpp, src/Mod/PartDesign/Gui/ViewProviderHole.cpp
* Fix possible crashes in dress-up task panels
* Fix possible crash in primitive dialog
* Add template helper functions to safely access feature or view provider
* In subclasses of TaskFeatureParameters use the new helper functions and check for null pointer.
* Replace helper functions in subclasses of TaskDlgFeatureParameters with a template function
This fixes #15453
=> Fix possible crashes in PD task panels

.gitignore, CMakePresets.json
Modify CMakePresets.json to use -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON in all the presets.
The compile_commands.json file can be used by tools like clangd to get autocompletion and go-to-definition.
This patch also adds compile_commands.json to the .gitignore, as often you need to symlink the compile_commands.json from the build directory into the source directory for it to be picked by tools. That is the case with clangd at least.
=> Generate compile_commands.json

src/Mod/CAM/Path/Main/Gui/PreferencesJob.py, src/Mod/CAM/Path/Main/Stock.py, src/Mod/CAM/Path/Tool/Gui/BitLibrary.py
Various bug fixes for bughunt issues reported to Ondsel.
1) The migration of CAM to use the new material system left behind some logic that created an old dedicated stock material property.
This commit removes that property
2) a dead function call in the tool library system
=> [CAM]  Fixes for multiple errors in CAM system that give red ink in the console

src/Mod/Fem/App/FemVTKTools.cpp, src/Mod/Fem/App/PreCompiled.h
Fixes #15541
@FEA-eng now is possible export Fem mesh 1D elements to vtk and import the vtk file as Fem mesh.
=> Fem: Import/export 1D elements from mesh to vtk - fixes #15541

src/App/ComplexGeoData.h, src/App/GeoFeature.h, src/App/PropertyExpressionEngine.cpp, src/App/PropertyLinks.cpp, src/App/PropertyLinks.h, src/Base/Bitmask.h, src/Mod/Part/App/PartFeature.cpp, src/Mod/Part/App/PartFeature.h, src/Mod/Part/App/TopoShape.h, src/Mod/Part/App/TopoShapeExpansion.cpp, src/Mod/Part/App/TopoShapePyImp.cpp, src/Mod/Spreadsheet/App/PropertySheet.cpp, tests/src/Mod/Part/App/TopoShapeExpansion.cpp
Fifth in series of incremental code transfers to solve the save/restore errors with objects with element maps..  Support multiple options in support of a future sketcher InternalShape port.
=> Toponaming: update findSubShapesWithSharedVertex

src/Mod/Spreadsheet/Gui/SheetTableView.cpp
Fixes #15023. On macOS a different shortcut is defined for the 'Delete' key
=> Spreadsheet: Delete key doesn't clear contents in selected cells

src/Mod/PartDesign/App/FeatureLoft.cpp, src/Mod/PartDesign/PartDesignTests/TestLoft.py
Patch and test to Fix #15138.  Part of a pattern of places with TopoShape() that should potentially have a tag and be TopoShape(0) that will be investigated seperately.  Remaining question of if the parent volumes should be correct.
=> Toponaming: Fix #15138

src/App/GeoFeature.cpp, src/App/GeoFeature.h, src/Mod/Part/App/TopoShape.h, src/Mod/Part/App/TopoShapeExpansion.cpp, src/Mod/Sketcher/App/SketchObject.cpp, src/Mod/Sketcher/App/SketchObject.h
Seventh in series of incremental code transfers to solve the save/restore errors with objects with element maps..
=> Toponaming: bring in getHigherElements code

src/Mod/BIM/ArchSpace.py
The code to handle the ShapeColor no longer executed in V0.22 and everything works fine without it.
Additionally: Changing the transparency to/from 100% now changes the DisplayMode of existing space objects. Changing the transparency of `self.fmat` (the `coin.SoMaterial`) already happens automatically.
=> BIM: Space: Remove superfluous ShapeColor code, Improve DisplayMode handling

src/Mod/BIM/Resources/ui/dialogWelcome.ui
Old links to www.freecadweb.org, including BIM_Start_Tutorial which no longer exists and I assume should now be BIM_ingame_tutorial.
=> BIM: Fix Welcome dialog wiki links

src/Gui/Application.cpp, src/Gui/GuiApplication.cpp, src/Gui/GuiApplication.h, src/Gui/MainWindow.cpp, src/Gui/MainWindow.h, src/Gui/StartupProcess.cpp, tools/build/WindowsInstaller/setup/configure.nsh
Closes #15433.
Note that the last commit adds the `--single-instance` to the Windows installer but unfortunately I'm not in a position to test this.
The fix is a switch from using QDataStream/QByteArray to QTextStream/QString combined with explicitly setting the encoding for transfer, adding newlines per message and reading lines on the other side of the socket. Additionally, I switched from explicitly waiting for a read to react on the `readyRead` signal because the first attempt on trying to read always fails on Windows after which a second one succeeds. I cannot explain this, but reacting to a `readyRead` signal is in my opinion the best way to handle this small issue.
The PR doesn't include tests because two FreeCAD instances are needed to test the behavior. 
To test, first start …
=> Core: Fix single instance windows

src/Mod/Assembly/App/AssemblyObject.cpp, src/Mod/Assembly/App/AssemblyObject.h, src/Mod/Assembly/AssemblyTests/TestCore.py, src/Mod/Assembly/CommandCreateJoint.py, src/Mod/Assembly/CommandCreateView.py, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp, src/Mod/Assembly/Gui/ViewProviderAssembly.h, src/Mod/Assembly/JointObject.py, src/Mod/Assembly/UtilsAssembly.py
This is changing the properties of the joint objects from 'Obejct1/2' and 'Part1/2' to a single PropertyXLinkSubHidden 'Reference1/2' that store the full path to the object. With the full path to the object we can now get the real getGlobalPlacement.
This will solve the global placement issues where two identical objects could not be differentiated.
Fix https://github.com/FreeCAD/FreeCAD/issues/15090
Fix https://github.com/FreeCAD/FreeCAD/issues/14706
Fix https://github.com/FreeCAD/FreeCAD/issues/14923
=> [Assembly] Properties rework for Global placement

src/Gui/propertyeditor/PropertyItem.cpp
In v0.21 changing the color using the property editor reset the per face colors. This recreates that behavior when setting the appearance.
fixes #15170
=> Materials: Reset per face appearance when using property editor

src/Mod/TechDraw/App/DrawView.cpp, src/Mod/TechDraw/App/DrawViewPart.cpp
This PR implements a fix for a problem reported here: https://forum.freecad.org/viewtopic.php?t=89413.
The checkfit and autoscale methods were were calculating page size differently causing a loop.
=> [TD]fix autoscale loop

src/Gui/DlgPreferencesImp.cpp, src/Gui/PreferencePages/DlgSettingsNavigation.ui, src/Gui/PropertyPage.cpp, src/Gui/PropertyPage.h, src/Gui/Tree.cpp, src/Mod/AddonManager/AddonManagerOptions.ui, src/Mod/BIM/Resources/ui/preferences-ifc-export.ui, src/Mod/BIM/Resources/ui/preferences-ifc.ui, src/Mod/Draft/Resources/ui/preferences-dxf.ui, src/Mod/Material/Gui/DlgSettingsDefaultMaterial.ui, src/Mod/Material/Gui/DlgSettingsMaterial.ui, src/Mod/Part/Gui/DlgExportStep.ui, src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui, src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui, src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui, src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui
This PR fixes various small cosmetic problems with preferences, like wrong padding, inconsistent alignment, horizontal scrollbar that should not be present etc.
Examples of before and after:
| -- | -- |
|![image](https://github.com/user-attachments/assets/5427b969-42d3-4113-a2cf-e40026967e06) | ![image](https://github.com/user-attachments/assets/99b8f864-2c8f-4e66-b4ca-81cc4d636288) |
| ![image](https://github.com/user-attachments/assets/f4bbe80c-fb74-4290-979c-18d5519f8b96) | ![image](https://github.com/user-attachments/assets/07b21733-3e77-4dca-90d6-7a0aff4e3e5d) |
| ![image](https://github.com/user-attachments/assets/e8f83feb-3ec2-44d7-8fbe-5be2947085a1) |![image](https://github.com/user-attachments/assets/68a5f1c1-ed8c-4292-803d-ad9f7532c2e8) |
| …
=> Gui: Cosmetic Fixes

src/Mod/BIM/ArchWall.py
At the corners of the base wire the joint width was wrongly added.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=89504
=> BIM: Fix calculation of wall blocks

src/Mod/Sketcher/App/SketchObject.cpp
Missed code after external Geo switchover.  Fixes deletion of external geometry to work again.
=> Toponaming: bring in code to fix delExternal breakage.

.github/workflows/CI_master.yml, .github/workflows/sub_buildUbuntu2204CondaQt6.yml, cMake/FreeCAD_Helpers/SetupShibokenAndPyside.cmake, conda/conda-env-qt6.yaml, conda/environment-qt6.devenv.yml, conda/setup-environment-qt6.sh
Adds Python 3.12 and Qt6 build to CI.
TODO:
I believe this could be performed by installing both Qt5 and Qt6 within the `devenv` and selecting the version of python when establishing the environment.  Use of Qt6 would may be performed by using the `-DFREECAD_QT_VERSION=6` CMake configuration option.
Qt6 depends upon several libraries provided by `mesa` that are not available using the `conda-forge` libraries currently installed.  Qt5 dependencies are satisfied without requiring these packages to be installed in the host environment, and it is unclear as to why.  When installing the `conda-forge` package `mesa-libegl-devel-cos7-*` the libraries are installed as `libEGL_mesa.so.0` instead of `libEGL.so.1` as expected by Qt6.
* `libegl1`
* `libgl1`
* `libglx0`
* `libopengl0`
To get the build …
=> CI: Add Conda Python 3.12 Qt6 to CI.

.github/ISSUE_TEMPLATE/PROBLEM_REPORT.yml, README.md
While trying to narrow down TNP @bgbsww mentioned that is would be very helpful if users could record a macro when recreating issues.
This PR adds text to readme and the issue template that the user should record a macro when recreating the issue and sharing this macro in the issue.
Also, updated old links from master branch to main in the readme and issue template.
=> Add text to readme and the issue template to record macros for bugs

.github/labels.yml
Added the functionality for the labeler to recognize Stylesheet related PRs. Also annotated file to differentiate different types of labels (as opposed to sorting them all alphabetically).
=> labels.yml: Add Stylesheets + Differenitate between Mod and Topic labels

cMake/FreeCAD_Helpers/SetupShibokenAndPyside.cmake
The target used in the original version of the clause does not exist when using the LibPack, but the setting is also irrelevant because the LibPack has already prevented Shiboken from setting the limited API.
=> cMake: ensure the Shiboken target exists before using it

src/Gui/StartupProcess.cpp
ThemeSearchPaths option was originally introduced in: c420de0f9b ("Option to opt-out from using a Linux desktop icon theme.", 2020-01-26)
It was set on by default in:
dc6456caf9 ("Gui: Use FreeCAD supplied icons on Linux by default", 2024-06-26)
The key effect of the option is to select the FreeCAD-default icon theme. The code also unnecessarily resets QIcon::themeSearchPaths, ":\icons" is always included in the default search paths [1], when when using QAdwaitaDecorations causes window frame control icons not to be displayed:
(qt.qpa.qadwaitadecorations) Failed to find an svg icon for  "window-close-symbolic.svg"
(qt.qpa.qadwaitadecorations) Failed to find an svg icon for  "window-minimize-symbolic.svg"
(qt.qpa.qadwaitadecorations) Failed to find an svg icon for …
=> Remove icon ThemeSearchPaths option on Linux

.clang-tidy, .github/workflows/sub_lint.yml, src/Mod/Sketcher/App/SketchObject.cpp
As discussed at the last developer meeting, some of the current default linter warnings are wrong or misleading. This PR silences some of the major culprits in an attempt to make the CI lint run more useful (e.g. we don't develop the bad habit of just ignoring the linter because it's noisy).
The Sketcher file edit is just to demonstrate and exercise the linter, and can be dropped from the final merge if desired.
=> CI: Linter error tweaks

src/Mod/Fem/Gui/TaskPostBoxes.cpp
Fixes #13694.
Point is selected with left click and cancelled with right click for both Data At point clip filter and Line clip filter.
@maxwxyz @FEA-eng
=> Fem: Remove callback on right click during point marker selection - fixes #13694

.github/labels.yml
Any changes to `cMake/` are packaging related and therefore label can be applied.
=> labels.yml: Add 'Packaging/building' label for CMake related changes

src/App/ComplexGeoData.cpp, src/App/ComplexGeoData.h, src/App/Document.cpp, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
Match behavior before ElementMaps refactored out of ComplexGeoData.
=> Toponaming: make sure TopoShapes have Hashers

src/Mod/PartDesign/App/FeatureHelix.cpp, src/Mod/PartDesign/App/FeatureHelix.h, src/Mod/PartDesign/PartDesignTests/TestHelix.py
Reverts FreeCAD/FreeCAD#15678 -- the CI was passing at the time it was created, but something in the interim is now causing it to fail. It looks like the tests themselves are good, so this probably does represent a real failure in the helix code.
=> Revert "[PD] Revert 316506f, back to shell algo for some helix cases"

src/Mod/Draft/draftguitools/gui_snapper.py
The get_cursor_with_tail function was rewritten to match the Sketcher cursor code. Hopefully this fixes the scaling issue.
Related issue:
#13696
Related forum topic:
https://forum.freecad.org/viewtopic.php?t=89494
@maxwxyz
Can you check if this code fixes the issue? Apart from the size the 'hot' pixel should be checked. If you approach a vertical line from the left or right it should get highlighted at the same distance.
=> Draft: Fix cursor scaling

src/Mod/TechDraw/Gui/CommandCreateDims.cpp, src/Mod/TechDraw/Gui/TaskProjGroup.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/15764
Also fix : 
- Dimension disappear when view is upgraded to proj group. (described in https://github.com/FreeCAD/FreeCAD/issues/15765)
- Scale and ScaleType were no re-appearing when downgrade from group to view
=> TechDraw: fix dimension being active at wrong times.

src/App/ComplexGeoData.cpp, src/App/ComplexGeoData.h, src/Mod/Part/App/TopoShapeExpansion.cpp
Address comment in https://github.com/FreeCAD/FreeCAD/issues/15102#issuecomment-2227793929
Gets rid of the idiom to force existence of elementMap by adding a new ensureElementMap() method to do this.  Doesn't change existing elementMap() method because it would require removing const and the subsequent large set of changes to accommodate that.
Not urgent.
=> Toponaming:  Refactor out duplicated code using elementMap()

src/Mod/AddonManager/AddonManager.py
Use the full static member access to get the icons for the dialog.
=> Addon Manager: Fix Qt6 button name

src/Mod/Assembly/Gui/ViewProviderAssembly.cpp, src/Mod/Assembly/Gui/ViewProviderAssembly.h
Fix bug where double-clicking on a joint would unselect the underlying edge.
Fix https://github.com/FreeCAD/FreeCAD/issues/15718
=> Assembly: Fix bug where double-clicking on a joint would unselect edge

src/Mod/Assembly/App/AssemblyObject.cpp, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
Make sure that when a components is deleted its joints are too.
This is a regression reported in https://github.com/Ondsel-Development/FreeCAD/issues/127
Fix https://github.com/Ondsel-Development/FreeCAD/issues/127
=> Assembly: Fix joints not being deleted when component removed.

src/Mod/Part/App/TopoShapeExpansion.cpp
=> Toponaming: Match findSubShapesWithSharedVertex exception suppression

.github/workflows/CI_master.yml
This reverts commit 77167d81670c73892e01b94b65ebc5d76b278a21.
=> Revert "CI: Disable Windows conda due to mamba bug."

src/Mod/CAM/CMakeLists.txt, src/Mod/CAM/Path/Post/Command.py, src/Mod/CAM/Path/Post/Utils.py, src/Mod/CAM/Tests/FilePathTestUtils.py, src/Mod/CAM/Tests/TestPathPost.py
Previously, if the user didn't set a default gcode path, the file was saved to getcwd. Now, it attempts to take the active document's path first.
I would like suggestions about what the standard behaviour should we use, but in general, this needed to be fixed as in Windows at least, it was saving to the same `freecad.exe` folder!
=> FIX: empty filename in CAM workbench saves to the current project folder

src/Mod/Material/CMakeLists.txt, src/Mod/Material/Resources/Materials/Machining/AluminumCastAlloy.FCMat, src/Mod/Material/Resources/Materials/Machining/AluminumWroughtAlloy.FCMat, src/Mod/Material/Resources/Materials/Machining/AusteniticStainlessSteel.FCMat, src/Mod/Material/Resources/Materials/Machining/GrayCastIron.FCMat, src/Mod/Material/Resources/Materials/Machining/LowAlloySteel.FCMat, src/Mod/Material/Resources/Materials/Machining/MalleableCastIron.FCMat, src/Mod/Material/Resources/Materials/Machining/MildSteel.FCMat
This PR extends @sliptonic's #14460, where the "machinability" model was introduced. There, as sample data, the legacy material cards from the ["feeds and speeds" addon](https://github.com/dubstar-04/FeedsAndSpeeds) were added and (partly) converted to the new format. However, due to copyright concerns, unclear semantics and unknown source of the data, the values required for cutting force calculations have been removed.
This PR adds material cards with complete machining model data for various classes of metals. The data comes from the German standard work ["Tabellenbuch Zerspantechnik"](http://www.europa-lehrmittel.de/14733), ISBN 978-3-7585-1315-2, 5. Edition 2022.
Usage of this data for our purpose is legal as facts are not protected by copyright according to German law. 
A …
=> Material: Add metal cards with machining model

src/Gui/Assistant.cpp, src/Gui/PythonConsole.cpp, src/Gui/SoFCCSysDragger.cpp, src/Gui/ToolHandler.cpp
Attempt to fix #15904 -- maybe on the Conda build system the macros are defined differently?
ETA: tested with a local Conda build and this does solve the transform problem.
=> MacOS: Modify OS detection macro

src/Mod/PartDesign/PartDesignTests/TestLinearPattern.py, src/Mod/PartDesign/PartDesignTests/TestPolarPattern.py, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
If in the user settings the refinement is switched off several PD tests will fail. This change explicitly sets the Refine property to True to guarantee correct behaviour
=> PD: Make PD tests more robust

src/Gui/DlgKeyboardImp.cpp
This should resolve #9639.
At least on macOS, it seems that setting nontrivial shortcuts only works when the shortcut is converted to `PortableText`, rather than `NativeText`.
Before, it was impossible to map, eg, the backspace key or CMD-T to an action. Now this appears to work.
Happy to make any changes to this PR if needed :)
=> Use portable text to set shortcut

src/Mod/AddonManager/addonmanager_installer.py
Fixes #14200 by always deleting the old version before unzipping the new one.
=> Addon Manager: Fix ZIP installation

CMakePresets.json
Python is not provided with debug libraries, so debug builds are not possible. Building as RelWithDebInfo will build debug information for the binary, while using the available release libraries.
=> CMake: Use RelWithDebInfo for Conda Windows Debug builds.

src/Mod/Measure/App/MeasureDistance.cpp, src/Mod/Part/App/MeasureClient.cpp
This addresses the issue described in #13718 where the drawing of a distance measurement doesn't correctly update when the underlying geometry moves or is changed.
Fixes #13718
=> [MeasureGui] Fix measure distance viewprovider update

src/Mod/Measure/Gui/TaskMeasure.cpp, src/Mod/Measure/Gui/TaskMeasure.h, src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp
This solves the problem described in #13808 where the initial placement of simple label measurements was returned globally instead of relative to the root position. Also this PR adds a change to trigger the initial placement explicitly as the attach method (where it is currently triggered) is not the right place.
Fixes #13808
=> MeasureGui: Fix inital label placement

src/Gui/FileDialog.cpp
Fixes #15908 -- the list of possible suffixes was including the "(" in the first suffix, which would then never match with anything, and when checking the list later, the `FileInfo::suffix()` does not include the "*.", so would again never match anything.
=> Gui: Correct repeated extension

src/App/Document.cpp, src/App/Document.h, src/Mod/Part/App/PartFeaturePy.xml, src/Mod/Part/App/PartFeaturePyImp.cpp
Missing items to make https://github.com/realthunder/FreeCAD_assembly3/wiki/Topological-Naming-Algorithm#hashing-element-name instructions work in a main executable ( which is very useful)
=> Toponaming:  Support disabling hashing; getting element history

src/Mod/Part/App/FeaturePartFuse.cpp, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
Address https://github.com/FreeCAD/FreeCAD/pull/15897#issuecomment-2295329179 by restoring and modifying Multifuse code, which is a different path than Boolean Fuse in main.
=> Fix shape color / materials issues in fuse

src/Mod/Measure/Gui/TaskMeasure.cpp
Adds missing whitespace before opening brackets (observed in #15907 and should be merged after it is accepted).
=> Measure: fix linting TaskMeasure.cpp

src/Gui/PreferencePages/DlgSettingsLightSources.cpp, src/Gui/PreferencePages/DlgSettingsLightSources.h, src/Gui/PreferencePages/DlgSettingsLightSources.ui
@maxwxyz, @chennes, this pull request:
- Loads lightning settings when user opens _Preferences_ (yes, the settings were not loaded before this commit). Closes #15793
- Adds spinboxes to adjust the light direction using XYZ and orientation quaternion notations
- Removes the code that is supposed to adjust settings on-the-fly (it does not work anyway. If I make it work (by moving _View3DSettings_ variable into the class), _NaviCube_ shows up every time user presses the _Apply_ button. I could not find a way to make it go away). The code did not work because _View3DSettings_ object was created on the stack; in this case it is deleted after going out of its scope. 
- @adrianinsaval, this commit fixes showing up the dialog twice.
The code has been lightened, rewritten in _Qt_ way, now it is …
=> Reimplementation of Light source dialog

src/Mod/Part/App/PartFeaturePyImp.cpp
-/permissive does not allow the original unwrapped call to ParseTupleAndKeywords
=> Part: Fix compilation with Qt6/MSVC

src/Mod/AddonManager/AddonManager.py
The old code worked in Qt5, but Qt6 no longer supports this style of constant reference. The new code will work in Qt5 and Qt6.
=> Addon Manager: Adjust button reference for Qt6 compatibility

src/Mod/Fem/App/FemConstraint.cpp
`slotChangedObject` must be disconnected if the constraint is destroyed, for example in a transaction process.
```
App.ActiveDocument.openTransaction()
App.ActiveDocument.addObject("Fem::Constraint")
App.ActiveDocument.abortTransaction() # here the constraint is destroyed
App.ActiveDocument.openTransaction()
App.ActiveDocument.addObject("Fem::FemPostPipeline")
App.ActiveDocument.abortTransaction() # posible crash or exception raised since the slot is still connected.
```
=> Fem: Disconnect slot when destroying Constraint object

tests/src/Mod/Part/App/PartFeatures.cpp, tests/src/Mod/Part/App/TopoShapeMakeElementRefine.cpp
=> Part/Toponaming: use TopoShape::getShape() in some Toponaming tests

src/Mod/PartDesign/App/FeatureHelix.cpp, src/Mod/PartDesign/App/FeatureHelix.h, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
Try to fix with
- breaking the path at each turn for cylindrical helix so the OCC bug with boolean operation doesn't occur anymore
- keeping a single element path in case of conical helix in order to keep the solid shape generation (quicker than the shell algo)
- don't recreate a face from wire but use getVerifiedFace
- fix tests according to these changes
Related issues #15791 #14852 #14851
EDIT: #14901 is not fixed by this PR, the issue is really due to a previous operation and not to the helix.
=> [PD] helix fix

src/Gui/propertyeditor/PropertyEditor.cpp
On macOS, when closing a persistent property editor, Qt switches the MDIView active tab to the first one, regardless of which you are currently editing. This adds a workaround that records the active tab and explicitly sets it after closing the editor. Because there is no redraw in between these events, the switch is not visible.
Fixes #14350
=> Gui: Workaround for #14350

src/Mod/PartDesign/Gui/TaskHoleParameters.ui
The hole ui currently has an issue with the dropdown being too small, this fixes it.
i cherry-picked this from my current work at #15744
Current:
Fix:
=> fix(PD): threadtype combobox too small for metric fine

src/Gui/Action.cpp
This boiled down to conflict of using `data` attribute of the QAction in ActionGroup and ToolBarManager. I reworked ActionGroup here to not use the data attribute but this is not a proper solution - but it should be working well enough.
Proper solution would be to leave the data for the specific usecases (like index) and store the command name in some other place. It would however require us to subclass the QAction which is not something that should be done so late in the release cycle.
More information here: https://github.com/FreeCAD/FreeCAD/issues/13243#issuecomment-2295016166
Fixes: #13243
=> Gui: Fix issue with missing icons in sketcher

src/Mod/BIM/ArchCommands.py
The line `t = t.encode("utf8")` returns a bytes object which does not make sense in the context of the rest of the code. It is probably a copy-paste error. Removing the line fixes the problem.
To test the bug:
1. open the file attached to this forum post: https://forum.freecad.org/viewtopic.php?t=89012#p770224
2. Make the rectangles visible.
3. Start the Survey command and box select all objects in the 3D view.
=> BIM: Arch_Survey: Fix concatenate bytes bug

src/Gui/CommandView.cpp
Fix for https://github.com/FreeCAD/FreeCAD/issues/15981.
doSelect() loops over document's object vector.  It can happen that, within the loop, Gui::Selection().addSelection() gets called and that ends up calling App::Document::addObject() which pushes an object to the vector that the loop is traversing.  If the vector is full, its storage is reallocated and this means that later iterations of the loop are using invalid iterators. Thus, one ends up with a bogus obj pointer and there will be a crash within getGroupOfObject().  The problem was observed when using Arch Survey.
=> Fix crash when using box selection with Arch Survey (issue #15981)

src/Mod/Material/CMakeLists.txt, src/Mod/Material/Resources/Materials/Appearance/Wood.FCMat, src/Mod/Material/Resources/Materials/Machining/BalsaWood.FCMat, src/Mod/Material/Resources/Materials/Machining/HardWood.FCMat, src/Mod/Material/Resources/Materials/Machining/MDF.FCMat, src/Mod/Material/Resources/Materials/Machining/ParticleBoard.FCMat, src/Mod/Material/Resources/Materials/Machining/SoftWood.FCMat, src/Mod/Material/Resources/Materials/Standard/Wood/Wood-Generic.FCMat
This is a follow up to #15910, which introduced machining model data for various classes of metals. This PR now provides data for various types of woods and engineed wood products.
I got the data from the German text book ["Zerspanung von Holz und Holzwerkstoffen"](https://www.hanser-fachbuch.de/fachbuch/artikel/9783446477698), ISBN 978-3-446-47769-8, 2. Edition 2023. However, the author did not perform the cutting experiments but again cites "Sägen Fräsen Hobeln Bohren, Die Spanung von Holz und ihre Werkzeuge" from Bernhard Ettelt; DRW-Verlag Stuttgart; 1987".
Usage of this data for our purpose is legal as facts are not protected by copyright according to German law.
A comprehensive summary is published by the German federal ministry of education an research: [“Urheberrecht in der …
=> Material: Add wood cards with machining model

src/Gui/DlgPreferencesImp.cpp, src/Gui/DlgPreferencesImp.h
This will ensure that the width of preferences dialog is resized to fit all pages properly but not take more than 80% of screen.
=> Gui: Ensure minimum size of preferences dialog

src/Mod/TechDraw/App/Geometry.cpp, src/Mod/TechDraw/App/Geometry.h
This PR implements a fix for issue #15979.  It implements more rigourous checks in isCircle/getCircleParms
to avoid falsely treating bsplines as circles.
=> [TD]fix false positives in isCircle (fix #15979)

src/Mod/Part/App/PrimitiveFeature.cpp
Fix #15599.
The failure is actually in cone, and represents a bug in 7.7.2 but not 7.6.3 and not 7.8.x.  Angle values of 360.0 fail completely, 359.9999 and 359.999 partially, and 359.99 results in an ugly fix.
If it isn't clear, I hate this code, but it seems like the pragmatic best choice; the alternative is FreeCADs with 7.7.2 don't work with cones of 360 degrees.  I'm gonna take a bath now.
=> Horrible hack to work around bug in OCCT7.7.2

src/Gui/PreferencePacks/FreeCAD Classic/FreeCAD Classic.cfg
This replaces the current config file applied when setting FreeCAD to classic. It was discussed that resolving the config file by clearing out settings in order to regain the Classic (default) appearance was cumbersome. This creates 'Classic' as a true theme, and the hard coded values become failsafes in the event of some unexpected error. It will make future adjustments to the Classic theme easier through modification of this config file instead of digging through code to find and modify scattered values.
=> Fix FreeCAD Classic cfg file to explicitly reassign theme defaults.

src/Gui/GraphvizView.cpp, src/Gui/ImageView.cpp, src/Gui/OverlayWidgets.cpp, src/Gui/SplitView3DInventor.cpp, src/Gui/View3DInventor.cpp, src/Mod/Drawing/Gui/DrawingView.cpp, src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp, src/Mod/Start/Gui/StartView.cpp, src/Mod/Start/Gui/StartView.h, src/Mod/TechDraw/Gui/MDIViewPage.cpp
This ensures that overlay panels cannot be shown in the Start page which created ugly artifacts:
=> Gui: Do not show overlay panels in Start

src/Mod/Assembly/UtilsAssembly.py
Make sure the subnames index are valid before trying to access the Edges/Faces/Vertexes vectors of the shapes. Else it would crash if the index is out of bound.
For example if the user manually edit the subname from edge1 to edge10 and the shape has only 5 edges, then it would crash.
@sliptonic
=> Assembly: Make sure the subnames index are valid

src/Mod/Import/Resources/ui/preferences-import.ui, src/Mod/Part/Gui/DlgImportStep.ui
If checked, no Compound merge will be done --> If checked, Compound merge will be done
Fixes #16126
Might be good to have it for 1.0 since the tooltip here is really misleading as it suggests the opposite of what it should.
=> Fix incorrect Compound merge tip

src/Mod/Fem/femcommands/commands.py
The _UseNonCcxIterationParam_ property is mistakenly treated as Int when reading its value from Preferences (thus, the value can't be read) while the actual type should be Bool.
=> FEM: Fix UseNonCcxIterationParam preference property type

src/Gui/PreferencePages/DlgSettingsNavigation.ui
Fixes problem when user has fonts with long names that causes the combobox to be resized to maximum length and no longer fit in the dialog causing horizontal scrollbars:
=> Gui: Add maximum width for font picker in navigation settings

src/Mod/Draft/Resources/ui/TaskPanel_SetStyle.ui, src/Mod/Draft/Resources/ui/dialog_AnnotationStyleEditor.ui
Without this max value the spinbox stops at 99.99. The max value is the same as in preferences-drafttexts.ui.
=> Draft: Fix max value of Scale multiplier in ui files

src/Mod/Sketcher/App/planegcs/Constraints.cpp
=> [planegcs] Fix error gradient check in `ConstraintTangentCircumf`

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/Gui/TaskDlgMeshShapeNetgen.cpp, src/Mod/Fem/Gui/ViewProviderFemMesh.cpp, src/Mod/Fem/Gui/ViewProviderFemMesh.h, src/Mod/Fem/Gui/ViewProviderFemPostPipeline.cpp, src/Mod/Fem/Gui/ViewProviderFemPostPipeline.h, src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femcommands/manager.py, src/Mod/Fem/femtaskpanels/base_femtaskpanel.py, src/Mod/Fem/femtaskpanels/task_constraint_bodyheatsource.py, src/Mod/Fem/femtaskpanels/task_constraint_centrif.py, src/Mod/Fem/femtaskpanels/task_constraint_currentdensity.py, src/Mod/Fem/femtaskpanels/task_constraint_electrostaticpotential.py, src/Mod/Fem/femtaskpanels/task_constraint_flowvelocity.py, src/Mod/Fem/femtaskpanels/task_constraint_initialflowvelocity.py, src/Mod/Fem/femtaskpanels/task_constraint_initialpressure.py, src/Mod/Fem/femtaskpanels/task_constraint_magnetization.py, src/Mod/Fem/femtaskpanels/task_constraint_sectionprint.py, src/Mod/Fem/femtaskpanels/task_constraint_tie.py, src/Mod/Fem/femtaskpanels/task_element_fluid1D.py, src/Mod/Fem/femtaskpanels/task_element_geometry1D.py, src/Mod/Fem/femtaskpanels/task_element_geometry2D.py, src/Mod/Fem/femtaskpanels/task_element_rotation1D.py, src/Mod/Fem/femtaskpanels/task_material_common.py, src/Mod/Fem/femtaskpanels/task_material_reinforced.py, src/Mod/Fem/femtaskpanels/task_mesh_boundarylayer.py, src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py, src/Mod/Fem/femtaskpanels/task_mesh_group.py, src/Mod/Fem/femtaskpanels/task_mesh_region.py
Currently transactions are only aborted for C++ Constraints objects.
The first commit is to use the `pyViewObject` member of the `Gui::ViewProvider` base class in `getPyObject` methods.
My recollection is that the `Gui::ViewProvider` destructor is responsible for leaving the system in the correct state via the `pyViewObject` member when removing an object, for example when a transaction is aborted.
Using any other member as is currently the case leads to undefined behavior.
With the second commit, the transaction is aborted by pressing the Cancel button to undo the creation of the object.
@FEA-eng
=> Fem: Undo Python object creation by pressing cancel button

src/Mod/Part/App/TopoShape.h, src/Mod/Part/App/TopoShapeExpansion.cpp, src/Mod/PartDesign/App/FeatureRevolution.cpp, src/Mod/PartDesign/App/FeatureRevolution.h, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
Make element maps refer to history correctly; test for it.
=> Correct element map support in Revolution

src/Gui/Application.cpp
Fixes https://github.com/FreeCAD/FreeCAD/issues/15803
Remove version "v0.21" from the old backup format warning message.
@chennes touches strings but only removes the hardcoded old version info
=> Remove version "v0.21" from the old backup format warning message

cMake/FreeCAD_Helpers/CompilerChecksAndSetups.cmake
Add recognition of the C++23 standard specification. Note that FreeCAD cannot yet be compiled with this enabled (see #6272).
=> cMake: Add option to use C++23

src/Mod/Part/BOPTools/__init__.py
BOPFeatures was not being imported, since it was missing in the BOPTools' __init__.py . All BOPTools modules were being imported except this one.
BOPFeatures has been included in the __init__.py file, as it can be seen in the linked commit.
=> add BOPFeatures to BOPTools __init__.py

src/Mod/Fem/femmesh/gmshtools.py, src/Mod/Fem/femtest/data/elmer/group_mesh.geo
Currently, if a mesh group has different element types, the physical group is not created, for example:
Create a Part cube.
Create a Fem analysis, a Gmsh mesh object and a Fem mesh group.
Add two different element types from the Part cube to the group, for example an edge and a face.
Try to mesh -> Error reported as the `.geo` file generated has incorrect items id in the physical group.
Generated shape2mesh.geo file:
```
// group data
Physical Line("MeshGroup") = {6, Face3};
```
This bug is now fixed.
Since each physical group expect to have a unique element type, the physical group is spli based on the element types it contains and one group is created per element type.
Generated shape2mesh.geo file:
```
// group data
Physical Surface("MeshGroup_Surface") = {3};
Physical …
```
=> Fem: Use regex to search gmsh groups items and fix physical group item id

src/Mod/Sketcher/App/ConstraintPyImp.cpp, src/Mod/Sketcher/App/PythonConverter.cpp, src/Mod/Sketcher/App/SketchObject.cpp, src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h
Fix https://github.com/FreeCAD/FreeCAD/issues/15771
Fix 2 of the errors described in https://github.com/FreeCAD/FreeCAD/issues/15653
1 - Points being forced to construction when added to sketch (so on copy paste)
For this we simply have to remove a limitation that was here for unknown purpose. Apparantly to ensure legacy code would work (considered legacy 9 years ago).
2 - Driving and activated status of constraints not ported when copy pasted.
=> Sketcher: Fix copy paste errors

src/Mod/Measure/App/MeasureArea.cpp, src/Mod/Measure/App/MeasureArea.h, src/Mod/Measure/App/MeasureBase.h, src/Mod/Measure/App/MeasureLength.cpp, src/Mod/Measure/App/MeasureLength.h, src/Mod/Measure/App/MeasurePosition.cpp, src/Mod/Measure/App/MeasurePosition.h, src/Mod/Measure/App/MeasureRadius.cpp, src/Mod/Measure/App/MeasureRadius.h
This fixes the crash when a referenced element of a measurement is deleted as described in #16183.
Also the "recompute***" methods are removed so that errors can be returned from the execute method.
=> Measure: Fix crash when removing referenced element

src/Mod/TechDraw/Gui/QGIViewDimension.cpp, src/Mod/TechDraw/Gui/QGIViewDimension.h
Partially fixes #15103
I have no idea, why the bounding rect was offset with 4 times linewidth. Might need to check if removing this has any side effects.
=> [TechDraw] Make dimension labels centered

src/Mod/BIM/bimcommands/BimLibrary.py, src/Mod/BIM/bimcommands/BimPreflight.py, src/Mod/BIM/bimcommands/BimWindows.py
As of 73cb5bafe0, the click on the respective buttons in BIM panel causes the error mentioned bellow. After applying the patch it the dialogs open as expected.
`<class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'StandardButton'`
* OS: Arch Linux
* Python: 3.12.5
=> BIM: fix invalid converesion of button to int

src/Mod/Sketcher/Gui/TaskSketcherConstraints.ui, src/Mod/Sketcher/Gui/TaskSketcherElements.cpp, src/Mod/Sketcher/Gui/TaskSketcherElements.ui
This should fix issues described in #12265. 
For strange icon scaling I forced 24px icon size - this should ensure that icons have proper sizing. I however could not reproduce the issue in any way on my setup so it is blind fix. We need someone to test if it does indeed work.
For the issue with dimmed out icons I made them opaque unless the (pre)selection is partial. That way normally icons are fully opaque and only when hovered or something is selected they become semi-transparent.
Before:
After:
Fixes: #12265
=>  Gui: Fix issues with icons in sketcher elements panel

src/Mod/Draft/draftguitools/gui_snapper.py
This fixes a regression introduced in V0.19 (!) when the type of linear dimensions was changed from "Dimension" to "LinearDimension".
Forum topic:
https://forum.freecad.org/viewtopic.php?t=90292
=> Draft: fix snapping to endpoints of dimension lines (V0.19 regression)

src/Gui/DlgMaterialProperties.ui, src/Gui/DlgMaterialPropertiesImp.cpp, src/Gui/DlgMaterialPropertiesImp.h, src/Mod/Material/Gui/DlgInspectAppearance.cpp
Add missing UI elements to support per face transparencies:
- Setting per face transparencies
- show transparency information in the appearance inspector
- expose alpha channel in color selector dialog
=> Materials: UI updates for transparency

src/Mod/Measure/Gui/QuickMeasure.cpp
I cannot see the reason for additional processing of objects by QuickMeasure that aren't needed and therefore assist performance.
CC @WandererFan
=> [Measure] Disable QuickMeasure for TechDraw, Spreadsheet, Part Container and Origin objects

src/Doc/CONTRIBUTORS, src/Gui/PreferencePacks/FreeCAD Classic/post.FCMacro, src/Gui/PreferencePacks/FreeCAD Dark/FreeCAD Dark.cfg, src/Gui/PreferencePacks/FreeCAD Light/FreeCAD Light.cfg, src/Gui/Splashscreen.cpp, src/Gui/StartupProcess.cpp
Fixes #16272
```
Stylesheet/Theme/QtStyle: Behave-dark.qss/FreeCAD Classic/Fusion
```
For testing, you might have to manually copy the changed preference packs
=> [Gui] Add style, theme and qtstyle info to clipboard about info

src/Gui/OverlayManager.cpp
The hideTab is of type bool, which is primitive type and is thus unitialized if new instance of the class is created. The exception would be to for static instance of the class, but that is not the case (only the pointer to the instance is static).
It was originaly initialized, but the initialization was removed in 9d5390ed833.
I'm not sure but this variable actually looks unused, mey-be there is somethink missing here, otherwise the code contains dead paths.
=> OverlayManager: fix unititialized hideTab variable

src/App/Metadata.cpp, src/App/MetadataPyImp.cpp, src/App/ProjectFile.cpp, src/App/ProjectFile.h, src/Base/InputSource.cpp, src/Base/InputSource.h, src/Base/Parameter.cpp, src/Base/Parameter.h, src/Base/Reader.cpp, src/Base/Reader.h, src/Base/XMLTools.cpp, src/Base/XMLTools.h, src/Mod/Mesh/App/Core/IO/Reader3MF.cpp, src/Mod/Mesh/App/Core/IO/Reader3MF.h, tests/src/App/Metadata.cpp, tests/src/Base/Reader.cpp
The goal of this PR is to be able to manage the current and latest version of Xerces-C++ . Currently, the version required and mostly used by FreeCAD is older from 2 to 4 years than the latest commit in the Xerces-C++ repository (see [Xerces-C++ tags](https://github.com/apache/xerces-c/tags)).
In order for FreeCAD to continue to use the latest version of Xerces-C++, this PR aims to prepare Xerces-C++ bump version. The bump will be performed in another PR **after** the fixes described in the last line of this PR comment.
It also allows developers like me to use the latest version of Xerces-C++ and compile it in debug mode and then investigate memory leaks, such as described and found in #16316  with Valgrind.
The new version do not contain the following macros:
- …
=> PD: Xerces-C++ - Prepare for the latest version (backward compatible)

src/Gui/PreferencePacks/FreeCAD Dark/FreeCAD Dark.cfg, src/Gui/PreferencePacks/FreeCAD Light/FreeCAD Light.cfg
Fixes selection colors to the below colors:
https://github.com/FreeCAD/FreeCAD/issues/16262#issuecomment-2327186149
=> Updated selection colors to be better visible.

src/Mod/BIM/Arch.py
Fixes: #16286
This PR simply appends an underscore (`_`) at the end of the profile name's label. This means that the numerical sequence when adding multiple structures with a profile will be:
1. `$PROFILE`_ (e.g. 22x100_)
1. `$PROFILE`_ (e.g. 22x100_001)
1. `$PROFILE`_ (e.g. 22x100_002)
1. Notice that the first profile will only have an underscore suffix. The expectation here might be to either have no underscore, or (for more consistency) to start the sequence with the `_000` suffix. However, the assumption (to be corrected if wrong) is that adding the increasing numerical suffix to multiple identically-named labels is done outside of the BIM module, in FreeCAD's core. This PR seeks to fix the original bug in the least intrusive way (without changing the core), even if not perfect.
2. …
=> [BIM] Separate profile name from label number

src/Mod/Spreadsheet/CMakeLists.txt, src/Mod/Spreadsheet/importXLSX.py, src/Mod/Spreadsheet/test_importXLSX.py
The operators `<>`, `<=`, and `>=` excel formulas causes xlsx import to fail.
The issue can be tested on the current version with the generated xlsx file created with the following code (needs to install openpyxl for it to work):
```python
import openpyxl
wb = openpyxl.Workbook()
ws = wb.active
ws['A1'] = "=IF(1<>2,1,0)"
wb.save("testcase.xlsx")
print("testcase.xlsx created successfully")
```
Traceback:
```
File "<string>", line 5, in <module>
File "/Users/nauck/projects/freecad/build-debug/Mod/Spreadsheet/importXLSX.py", line 434, in open
handleWorkSheet(myDom, theSheet, stringList)
File "/Users/nauck/projects/freecad/build-debug/Mod/Spreadsheet/importXLSX.py", line 319, in handleWorkSheet
handleCells(row.getElementsByTagName("c"), actSheet, strList) …
```
=> Spreadsheet XLSX import: Fix bug causing xls import failing for some operators

src/Gui/NavigationAnimation.cpp, src/Gui/NavigationStyle.cpp, src/Gui/NavigationStyle.h, src/Gui/View3DInventorViewer.cpp
This PR replaces #11279 when compiling with Coin 4.0.3+. As of Coin 4.0.3 there is a fix build into Coin for the orthographic camera clipping. This also fixes https://github.com/FreeCAD/FreeCAD/issues/12162#issuecomment-2045927219 and #16223 when compiled with Coin 4.0.3+.
=> Gui: Use Coin 4.0.3 fix for orthographic camera clipping

src/Gui/NavigationStyle.cpp
This fixes #16223 when using Coin versions before 4.0.3.
=> Gui: Fix orthographic camera standard views in an empty scene

src/App/ComplexGeoData.cpp
related to #15778
uses the recently introduced method `ComplexGeoData::ensureElementMap()` to avoid the SIGSEGV exception reported in the issue above
=> App/Toponaming: Call ensureElementMap() in ComplexGeoData::readElements()

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.h
Previously AutoColor property forced reinitialization of all subscribed parameters. It was mostly fine as most of them should stay in sync with user settings but it also affected grids.
Fixes: #16202
=> Sketcher: AutoColor should update only colors

src/Mod/Fem/femmesh/gmshtools.py, src/Mod/Fem/femtaskpanels/task_mesh_group.py, src/Mod/Fem/femtest/data/elmer/group_mesh.geo
https://github.com/FreeCAD/FreeCAD/pull/16076 basically breaks Elmer solver due to inconsistent references names between constraints and mesh groups.
Since both `gmsh` and `salome smesh` work with only one element type per group, instead of add a suffix to the group name as is done in #16076, just disallow adding multiple types directly from the GUI in the `MeshGroup` task panel.
@FEA-eng , @chennes
=> Fem: Allow only one shape type per mesh group - Partially revert #16076

src/Mod/Measure/Gui/TaskMeasure.cpp, src/Mod/Measure/Gui/TaskMeasure.h
When using the measurement currently it is only possible to enable the delta's by saving the measurement and turning the option on.
With this MR the delta option is already available in the TaskMeasure to see the deltas also in the interactive mode (if possible). The delta option is stored in the  measurement so when saving the measurement, the option is also applied
https://github.com/user-attachments/assets/21bf0048-59ce-4ae4-921a-a290f924f6a0
=> Measure: Show delta option also in interactive mode

src/Gui/FileDialog.cpp, src/Gui/FileDialog.h
This PR aims to resolve #16299, while taking into account https://github.com/FreeCAD/FreeCAD/issues/15908 and https://github.com/FreeCAD/FreeCAD/issues/15203 as well.
It simplifies the code and the regression happened because the regex was not clear to me initially and later also not to @chennes (I believe). I initially assumed the regex was meant to match all the suffixes in the description and probably @chennes took over this assumption because my code used it as such. However, I now understand that the regex was only meant to match the first extension in the list to add this first extension when an extension was missing. 
Because of https://github.com/FreeCAD/FreeCAD/issues/15203, the current code extracts the suffixes from `filterSearch` and uses that to determine whether fileInfo has …
=> Core: Fix duplicated extensions (see #16299)

.github/workflows/actions/linux/generateCacheKey/action.yml, .github/workflows/actions/windows/getCcache/action.yml, .github/workflows/actions/windows/getLibpack/action.yml, .github/workflows/sub_buildUbuntu2004.yml, .github/workflows/sub_buildUbuntu2204Conda.yml, .github/workflows/sub_buildUbuntu2204CondaQt6.yml
ci is often (always?) taking very long because the conda linux qt6 workflow can't find it's compiler cache and the conda linux qt5 sometimes wrongly fetches the qt6 cache which is useless for it. Hopefully this fixes it going forward, since the cache key format is being modified results will not be fully seen until everything is rebased on this
=> CI: fix buggy caching

src/Gui/PreferencePages/DlgSettingsLightSources.ui
This commit polishes the dialog that seemed to be perfection by removal of some strings from translation.
=> [GUI] Make some strings untranslatable in Light Sources dialog

src/Mod/TechDraw/Gui/QGCustomText.cpp, src/Mod/TechDraw/Gui/QGCustomText.h, src/Mod/TechDraw/Gui/QGIViewBalloon.cpp, src/Mod/TechDraw/Gui/QGIViewBalloon.h
I got annoyed by the off-centered balloon label.
Before
After
TODO: massively simplify balloon logic. Way overcomplicated.
=> [TechDraw] Fix uncentered balloon label

src/Mod/BIM/bimcommands/BimSetup.py
FreeCAD currently has 19 standard licenses. BIM_Setup could only handle the first 10.
Forum post:
https://forum.freecad.org/viewtopic.php?p=781578#p781535
=> BIM: fix BIM_Setup license issue

src/Mod/Start/Gui/StartView.cpp
Fixes #16047: FreeBSD: Segfault in StartView::firstStartWidgetDismissed
=> StartPage: Make sure to pass a container widget to the QScrollArea

src/Mod/Draft/importDXF.py
Fixes #16435. With this change, the legacy DXF importer can now import dimensions.
Notes:
1. <strike>As far as I can tell, the layer class does not have an `addObject()` method, or at least I did not find any documentation. I added the check nevertheless, as it was done in other places of the module. It would be great to have confirmation from a maintainer if it's needed.</strike> Update: I think I can answer myself the question, thanks to a comment in the code: `For old style layers, which are just groups `. So the check for `addObject()` is necessary for backwards compatibility, if I understand it correctly.
2. There are other entities in the file that call `lay.addObject(newobj)` and will fail as well without this fix. I prefer to keep the scope limited to the dimensions bug fix. I can …
=> DXF importer (Python): allow importing dimensions

src/Mod/Sketcher/App/SketchObject.cpp, src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
related to https://github.com/FreeCAD/FreeCAD/issues/13177#issuecomment-2307792664
the imported code restores the synchronization of the selection of external edges between the 3D view and the Task Panel
as for https://github.com/FreeCAD/FreeCAD/issues/16422#issuecomment-2344255862, this PR fixes #16422
=> Sketcher/Toponaming: import SketchObject::checkSubName() from LS3

src/Mod/BIM/ArchGrid.py
Other similar text uses "of". Changing this odd "for" to match.
=> consistent preposition

src/Gui/Splashscreen.cpp
FIxes #16391
```Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default```
=> [Gui] Handle unset style preferences in clipboard about info

src/Gui/MainWindow.cpp, src/Gui/Splashscreen.cpp, src/Gui/ToolBarManager.cpp, src/Gui/View3DPy.cpp, src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.cpp, src/Mod/Spreadsheet/Gui/SheetTableView.cpp
* QColor::setNamedColor is deprecated since Qt 6.6
* Several methods of QMouseEvent are deprecated since Qt 6.0
* QLocale::countryToString and QLocale::country() are deprecated since Qt 6.6
=> Fix Qt6 warnings

src/Gui/MainWindow.cpp
freecad couldn't launch if only one splashscreen image is available as can be the case when the branding system is used
=> fix splashscreen for single image

src/Mod/BIM/ArchMaterial.py, src/Mod/BIM/Resources/ui/ArchMaterial.ui
this PR basically do 3 things:
since BIM is merge into Arch and use the Mod name "BIM", there is no Arch WB anymore, if still keep the name Arch in UI, maybe cause the new user get confused.
(Line 431, 435)
after BIM merge into Arch, the import path is moved, fix the import path of  BimClassification and its icon 
```bash
18:34:37  registerMetaMethodGetIndex: Cannot add dynamic method "currentIndexChanged(QString)" (1) to QComboBox(0x572d08fcb000, name = comboBox_MaterialsInDir): No Wrapper found.
18:34:37  registerMetaMethodGetIndex: Cannot add dynamic method "currentIndexChanged(QString)" (1) to QComboBox(0x572d0bc0f4e0, name = comboFather): No Wrapper found.
```
some warning occur in console,  re-write the signal in a more up-to-date way
-------
some other question :
1. are we going to …
=> [BIM] fix arch material task panel bug

src/Mod/Draft/draftguitools/gui_trackers.py
Draft trackers yielded an error when invoked and the current view is not a 3D view.
This might still leave trackers on if user switches views in the middle of a Draft command, but it's of low impact, and it was so already before this PR, only now there is no error message.
=> Draft: Fixes error in Draft trackers when not on a 3D view

CMakeLists.txt
Sets the development tree back to the `dev` build suffix.  This will ensure that the untagged weekly-builds do not mistakenly get referred to as RC1 release candidates leading to further version confusion.
=> Version: set development branch back to 'dev' suffix.

src/Gui/Tree.cpp
The tree can change shape during handling the mousePressEvent() event, because some part of the tree can be (un)folded. This might lead to shift of the three (up or down). The position of items in tree change relatively to the position of mouse (which stays in place). If the visibility click is handled after mousePressEvent, the shift in position can lead to cursor beeing over visibility icon and the click is handled like if the visibility icon vas clicked, which is unexpected.
Handling the visibility click first fixes this. The setAccepted(true), was removed, it is left to the subroutine to set it.
Fixes #16463 
NOTE: I have no idea what the issues mentioned in the removed comment were, do they relate to the removed return and setAccepted?
=> GUI: Fix tree visibility click issue

src/Base/Parameter.cpp
Extremely minor thing encountered while debugging a local build issue related to `fmt`.
=> Base: switch header include type for consistency with codebase.

CMakePresets.json
For reasons still unknown to me, CMake would search the Homebrew paths of `{/usr/local/homebrew,/opt/homebrew}/{bin,include,lib,...}` for dependencies.  This behavior is undesired as they are often incompatible with the dependencies installed from `conda-forge` resulting in either build-time errors or run-time errors.
Adding these paths to the variable `CMAKE_IGNORE_PREFIX_PATH` instructs CMake to avoid searching them for dependencies and eliminates the concerns about compatibility.
=> CMake: conda-macos-* do not search Homebrew for dependencies.

cMake/FreeCAD_Helpers/SetGlobalCompilerAndLinkerSettings.cmake
As per @mdrost's suggestion in #16369, this change will add debugging symbols to the `FreeCAD.exe` binary and not just the shared libraries.
=> Windows: Make FreeCAD.exe debuggable on PDB builds.

src/App/DocumentObject.h, src/App/GeoFeature.cpp, src/App/GeoFeature.h, src/App/Link.cpp, src/App/Link.h, src/Base/Tools.cpp, src/Base/Tools.h, src/Gui/View3DInventorViewer.cpp, src/Mod/Assembly/App/AssemblyObject.cpp, src/Mod/Assembly/App/AssemblyObject.h, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
Partially fixes #14576.
The alignment direction was not correct for objects with a transformation. For example, making a simple box in Part Design and then using the transform tool on the body to rotate the box resulted in wrong alignment directions. This is fixed by considering the orientation of the object. With this fix, the files provided in #14576 now align the view with the selected faces. 
However, it does not work properly yet when the assembly contains linked objects, like in AssemblyExample.FCStd. After using the transform tool to rotate the assembly, selecting a face and trying to align does not align with the selected face. The view is instead aligned with the face of the linked object which has another orientation. I don´t know why that happens but I will look into it another …
=> Move getGlobalPlacement() and fix alignment direction for transformed objects

src/Gui/BitmapFactory.cpp, src/Gui/BitmapFactory.h, src/Gui/StartupProcess.cpp
This should fix the issue with FreeCAD icons leaking to system dialogs. Icons loaded with BitmapFactory (almost all) will respect the new user parameter `UseIconTheme` under `BaseApp/Preferences/Bitmaps/Theme` group. Setting this parameter to true will force Qt to use icons from icon theme - by default the system one. Icon theme can be overriden via `Name` parameter. The default is false so FreeCAD will use the default icons. It does not touch Qt icon theme mechanisms so system dialogs, buttons etc should still use the icons from system theme.
Fixes: https://github.com/FreeCAD/FreeCAD/issues/16020
=> Gui: Use FreeCAD Theme only for FreeCAD stuff

src/Mod/BIM/ArchMaterial.py
in last commit   
when rewrite  
`QtCore.QObject.connect(self.form.comboBox_MaterialsInDir, QtCore.SIGNAL("currentIndexChanged(QString)"), self.chooseMat)`
to
`self.form.comboBox_MaterialsInDir.currentIndexChanged.connect(self.chooseMat)`
it supposed to return the material name at first
but after fix,  only return the comboBox Index
so need to add one more line to catch the materail name in seleted comboBox 
to continue load the material from cards
=> [BIM]  fix Material TaskPanel Load Preset not working bug

src/Mod/Sketcher/App/SketchObject.cpp
The variable seems to be uninitialized, valgrind complais about it.
The `git grep geoHistoryLevel` and the code ispection suggest it is never set. If initialized to zero, most of the related code is never used, which can point to the fact there is either another bug or part of the code is dead.
The variable was introduced in 42bf92ad12.
The initialization to 0 ensures stable, predictable behavior, @realthunder might have a suggestion what is going on here?
=> Sketcher: initialize geometry history limit variable

src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.cpp
Probably solves: [This problem](https://forum.freecad.org/viewtopic.php?p=778342#p778342)
Might also solve Wayland problem, issue #15665 
EDIT: instead of hard coded number of samples,  Anti Alias samples is now taken from Display preferences.
=> [Cam Simulator][1.0] Limit anti alias samples for better compatibility. 

src/App/Document.cpp, src/App/Document.h, src/Gui/Application.cpp, src/Gui/Application.h, src/Gui/Document.cpp, src/Mod/CAM/Tests/TestCAMSanity.py, src/Mod/CAM/Tests/TestPathAdaptive.py, src/Mod/CAM/Tests/TestPathDrillable.py, src/Mod/CAM/Tests/TestPathOpUtil.py, src/Mod/CAM/Tests/TestPathPost.py, src/Mod/CAM/Tests/TestPathProfile.py, src/Mod/CAM/Tests/TestPathToolController.py, src/Mod/Part/App/PropertyTopoShape.cpp, src/Mod/PartDesign/PartDesignTests/TestInvoluteGear.py, src/Mod/PartDesign/PartDesignTests/TestMultiTransform.py
This should eliminate the huge number of recompute warnings on older files without element maps.
It is a UI change, so a decision on whether to 1.0 or 1.1 this needs to be made.  If we do decide on 1.0 I expect the most stringent possible review, and to have to adjust to the results.  Please question everything.
=> Transfer dialog for recompute on older files and disable warning

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/Gui/Resources/ui/MeshGmsh.ui, src/Mod/Fem/femmesh/gmshtools.py, src/Mod/Fem/femtaskpanels/base_femmeshtaskpanel.py, src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py
Gmsh now runs in a subprocess on a separate thread.
* Pressing `Cancel` button while meshing, stop the process.
* Pressing `Ok` or `Apply` button while meshing raise a notification accordingly.
* The timer is fixed.
* Input fields replaced by quantity spin boxes in the task panel.
There is small code duplication in GmshTools just to avoid any problem in other sectors.
@FEA-eng
=>  Fem: Enable cancel meshing for Gmsh - fixes #5914 

src/Mod/Fem/App/FemMeshPy.xml, src/Mod/Fem/App/FemMeshPyImp.cpp, src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/Gui/CMakeLists.txt, src/Mod/Fem/Gui/Resources/ui/MeshNetgen.ui, src/Mod/Fem/Gui/Workbench.cpp, src/Mod/Fem/ObjectsFem.py, src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femmesh/netgentools.py, src/Mod/Fem/femobjects/mesh_netgen.py, src/Mod/Fem/femtaskpanels/base_femmeshtaskpanel.py, src/Mod/Fem/femtaskpanels/task_mesh_netgen.py, src/Mod/Fem/femtest/app/test_object.py, src/Mod/Fem/femviewprovider/view_mesh_netgen.py
Currently meshing with Netgen is done through a plugin in salomemesh. This plugin is broken and does not work on Linux.
The C++ class FemMeshShapeNetgenObject that depends on this plugin is only available if FreeCAD is compiled with Netgen as a dependency.
The proposal of this pull request is to use the FemMesh python feature and generate the meshing through the Netgen Python bindings, making Netgen an external tool and avoiding the dependency when compiling.
@FEA-eng  Could you do some tests? You need to have the python bindings for Netgen installed.
Netgen must be compiled with `USE_PYTHON=ON` and `USE_OCC=ON` (which is the default)
It is marked as draft since I still have to work on the code.
* This new implementation exposes all the meshing parameters available in Netgen.
* It …
=> Fem: New implementation of FemMesh Netgen object

src/Mod/Sketcher/Gui/TaskSketcherElements.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
related to https://github.com/FreeCAD/FreeCAD/pull/16355#issuecomment-2344246162
This PR should fix some errors that may trigger while selecting Sketcher geometries in Gui.
It is based on the following `#define` from LS3
https://github.com/realthunder/FreeCAD/blob/631044ad5b898b8142cdd54f9f8452ae46c51dd1/src/Mod/Sketcher/Gui/ViewProviderSketch.cpp#L1016
=> Sketcher/Toponaming: call SketchObject::convertSubName() in Gui selections

src/Gui/PreferencePages/DlgSettingsNavigation.ui
Thix fixes visual artifact in the Preferences/Navigation/Navigation cube/Font name dialog. The default value for this field is 0 (at least for some Qt versions), which does not make sense, because the element would be invisible.
Also the element is actually invisible when editing the UI file in QtCreator.
Using the default "max" value set for other fields"
=> Gui: fix size of ComboBox in Preferences/Navigtion

src/Main/MainCmd.cpp, src/Main/MainGui.cpp
FreeCAD advertizes itself too noisy way which brings no usefull infomation. Unify banner for commandline and GUI application and drop unicode '(C)' character.
Most users, at least those who start FreeCAD from their desktop do not see it anyway. Those, who start commandline version are probably more interested in usefull output and those extra 7 lines of a FreeCAD banner are no help here.
Developers running FreeCAD during debugging do not even need to see copyright notice...
Those, who wishes more fancy stuff, could still do so via branding and pick something from [ascii art](https://forum.freecad.org/viewtopic.php?t=6602) forum thread. This way different kinds of official builds can be differentiated.
=> Main: simplify banner

src/App/GeoFeature.cpp
@chennes forgot to cherry pick this commit from #15262.
(cherry picked from commit 8db7191084352cc83e908b3819cec3612058ccd2)
=> [Backport] App: Return root object placement if target and root object are the same in getGlobalPlacement

src/Base/Reader.cpp
The patch auto closes opened character stream when reaching the end or start of an element. Failing to do that may trigger `Recursive character stream` exception in `XMLReader::beginCharStream()` when opening a new stream.
=> Base: fix XMLReader non-closing character stream

src/Mod/Measure/Gui/Command.cpp, src/Mod/Measure/Gui/TaskMeasure.cpp
Auto close measure task when the document is closed.
Fixes #16424
=> MeasureGui: Auto close task on document deletion

src/Mod/AddonManager/Addon.py, src/Mod/AddonManager/addonmanager_workers_installation.py, src/Mod/AddonManager/addonmanager_workers_startup.py
Wrap all metadata reads in try/except blocks and gracefully bail out if the data is bad. Fixes #16643.
=> Addon Manager: Don't crash on bad XML

src/Mod/Spreadsheet/importXLSX.py
closes https://github.com/FreeCAD/FreeCAD/issues/13487
Recap:
There was a ticket created because a fixme comment in the xlsx importer looked important and overlooked.
@JonasVgt looked at the schema for xlsx files and verified that the current behaviour is correct (`t` is optional and the default is `n`).
For reference, the line JonasVgt refered to:
> `    <xsd:attribute name="t" type="ST_CellType" use="optional" default="n"/>`
Is available here:
[c071691_ISO_IEC_29500-1_2016_Electronic_inserts.zip](https://standards.iso.org/ittf/PubliclyAvailableStandards/c071691_ISO_IEC_29500-1_2016_Electronic_inserts.zip)/`OfficeOpenXML-XMLSchema-Strict/sml.xsd:2265`
=> Spreadsheet: Removes unnecessary fixme comment and closes issue

src/Mod/Material/App/PropertyMaterial.cpp
The ShapeMaterial variable was not being properly restored. It's UUID was restored but the material was not being loaded and set
=> Materials: ShapeMaterial not properly restored

src/Mod/Part/App/PartFeatures.cpp, src/Mod/Part/App/TopoShapeExpansion.cpp
Address issue found during #16634 investigation. Provides backwards compatibility with the implementation of Ruled Surface prior to toponaming changes.
=> Part: fix ruled surface

src/Gui/Widgets.cpp
As background is fixed yellow, then make text fixed black until a proper solution is provided to make it theme-able.
=> Issue 16454 workaround: PropertyEditor selection colors

src/Mod/Part/Gui/TaskLoft.cpp, src/Mod/Part/Gui/TaskSweep.cpp
Fixes #16572 
Part Workbench's Sweep and Loft options were erroneously including Std_Part planes and axes in the list. The TopoDS_Shape class has an Infinite() method, and I check to make sure that's not set before including an object.
=> Filter out infinite objects from Part Loft and Sweep

src/Gui/PreferencePages/DlgSettingsLightSources.ui
Closes #16587.
Perfection is a state in which any change can make only worse. I thought that _Light Sources dialog_ finally reached it, but @FEA-eng has found a way to improve even further. This commit moves the push in and pull out buttons to the left side of the viewport, allowing user to see the axes I deliberately covered before.
The screenshot below shows how the dialog looks now.
<details><summary>Screenshot</summary>
</details>
=> [GUI] Move the Push In and Pull Out buttons to the left side

src/App/Application.cpp, src/Base/PyObjectBase.cpp, src/Base/PyObjectBase.h, src/Ext/freecad/CMakeLists.txt, src/Ext/freecad/module_io.py, src/Gui/Application.cpp, src/Mod/Import/Gui/AppImportGuiPy.cpp
Fix for #16282 "Core: Import STEP: Cancel button does not cancel".
This is achieved by throwing a python exception when the STEP options dialog is cancelled (`dlg.exec()` returns 0).
=> Core: Import STEP: Cancel button does not cancel

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
related to #15918
Performs the override draw style code only if there's actually a 3D view
=> Sketcher/Gui: check if there's a 3D view while executing ViewProviderSketch::unsetEdit()

src/Gui/PreferencePages/DlgSettingsCacheDirectory.ui
QtCreator, when the file is opened, reports reference to .qrc filewhich does not exists. It looks like a missing piece from ccb9d7faeb.
=> Gui: Fix path to QRC file in PreferencePages UI file

src/App/PropertyStandard.cpp, src/App/PropertyStandard.h, src/Mod/Part/Gui/ViewProviderExt.cpp
Migrate the transparency from the DiffuseColor alpha channel to the transparency color attribute. This allows the alpha channel to be used as designed
fixes #14938
=> Materials: Set transparency from DiffuseColor

src/Gui/CommandDoc.cpp
closes https://github.com/FreeCAD/FreeCAD/issues/16656
There's a mapping issue between mac and non-mac keyboard layout. And while Qt tries to solve it, it fails to give the users what they expect (see old bug here: https://bugreports.qt.io/browse/QTBUG-1616)
Apple calls the keys "Forward/Backward Delete" instead of "Delete" and "Backspace" ("Backward Delete" is some often just called "Delete", even though it has the same functionality as backspace in windows).
Apple's laptops doesn't come with a "delete"/"forward delete" key as only their external keyboard with numeric keypad has that.
Since apple don't include a forward delete key on most of their keyboards, they have mapped Fn+Backspace to that function. And this is the key that Qt maps QKeySequence::Delete to (see …
=> Use backspace as default to delete on mac

src/Mod/Measure/Gui/TaskMeasure.cpp, src/Mod/Measure/Gui/TaskMeasure.h
This solves #16565 which was introduced in #15122 where the local measureType variable was moved to a class member. 
With this PR the measure type is stored locally again and the measurement label is retrieved from the mode dropdown when saving the measurement.
Fixes #16565
=> [MeasureGui] Store measure type as local variable

src/Mod/Draft/importDXF.py
Accumulates the contents of each layer in a local Python list, then at the end assigns all the objects at once into the layer. This avoids a very slow process of traversing the objects so far and (re-)updating their properties each time a new object is added. Fixes #16604
Also see #15732 for more analysis on the same problem in the C++ DXF importer.
=> DXF: Remove O(n^2) time on DXF import with the legacy importer

src/Mod/BIM/Resources/ui/dialogProjectManager.ui
Until now not defined explicitly, using tab jumps through boxes in order in which they were created in qtCreator, which is really bumpy experience.
=> BIM: Fix tabstop order for Project Manager dialog

src/Mod/Fem/App/FemConstraint.cpp
For trimmed surfaces, the algorithm to find reference points used by constraint symbols may fail. In that case points on the outer wire of the Face are used.
For this second case to work correctly the underlying surface must be transformed with the global placement of the reference face.
The following file shows the current incorrect behavior:
With the Sketch using the XZ plane as attachment support, the algorithm fails to generate points to place the Fem Constraint symbol because the global placement of the outer wire of the reference face is different from the placement of the underlying surface geometry.
If the attachment support is changed to the XY plane, the constraint symbols are generated. In this case the algorithm works because the placement of the outer wire of the face and the …
=> Fem: Use reference subshape transformation on the underlying geometry when finding points for constraint symbols

src/Mod/Fem/Gui/ViewProviderFemMesh.cpp
There is a flickering between the wireframe and the faces in the FemMesh view.
Adding the SoPolygonOffset node with default values fixes this.
The default line width is changed to 1.0 because the current value seems to be too wide due the offset correction.
@FEA-eng
=> Fem: Fix flickering between faces and wireframe in FemMesh view provider

src/Mod/Fem/femmesh/netgentools.py
If the shape to be meshed is inside a container, the generated mesh must reflect the global placement of the shape.
Example (using new Mesh Netgen implementation):
Create a PartDesing Body with some shape (or a Part shape inside a Part container)
Change the Body placement (or Part container placement)
Regenerate the mesh -> new mesh doesn't reflect global placement of the shape.
@FEA-eng
=> Fem: Use shape global placement in Mesh Netgen new implementation

src/Mod/Material/Gui/CMakeLists.txt, src/Mod/Material/MaterialEditor.py
Correct the installation paths affecting builds on various systems while still maintaining the old material editor required for backwards compatibility
=> Materials: Correct installation paths

src/Mod/Help/Help.py
Unfortunately, not all documentation is translated. When using `What's this?` command it can be showed nonexistent webpages that don't redirect/have link to the English version of the documentation.
Instead of presenting to the user 404 code error pages is preferable to show the documentation on English.
Status codes 200 and 404 are assumed as requests response.
=> Help: Don't open 404 documentation pages

src/Mod/CAM/InitGui.py
Fixes #16533
Attempting to import camotics in the appimage raises an InvalidVersion error which we weren't testing for.
This version catches other exceptions and should fail more gracefully.
=> CAM Catch other exceptions with Camotics on import.

src/Mod/CAM/Gui/Resources/panels/TaskCAMSimulator.ui, src/Mod/CAM/PathSimulator/AppGL/Shader.cpp
Edit: fixes Issue #16707 as well.
This is not a critical bug, but still is a bug.
Minor shader fix.
Maintainers - up to you if it should enter 1.0.
Before (harsh and with noisy stripes):
After (much smoother):
=> [Cam Simulator][1.0] Fix minor Ambient Occlusion bug.

src/Mod/Sketcher/App/SketchObject.cpp
This fixes a category of TNP bugs that occur when you split the edge in a sketch ( which completely renumbers the geometry ) that is being used to create faces that are referenced (attached to) by something else.
Brings our code and opcode tagging into line with LS3 by placing the sketch opcode on the wire(s) inside the compound instead of on the compound containing the wires.
This then allows the comment about use in getElementName to apply.
Also confirms clause to force map creation is required by our restructuing, so TODO removed.
Basically these are updating early-TNP process code to final state matching LS3.
=> Toponaming: Match LS3 opcodes for sketch shape

src/Mod/Fem/Gui/TaskFemConstraint.cpp, src/Mod/Material/Gui/Array2D.cpp, src/Mod/Material/Gui/MaterialSave.cpp, src/Mod/PartDesign/Gui/TaskBooleanParameters.cpp, src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp, src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp, src/Mod/PartDesign/Gui/TaskLoftParameters.cpp, src/Mod/PartDesign/Gui/TaskPipeParameters.cpp, src/Mod/PartDesign/Gui/TaskShapeBinder.cpp, src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp, src/Mod/Surface/Gui/TaskSections.cpp
This pull request is not finished as I haven't tested all code paths yet, but I would like to get some feedback on my suggested way of fixing the issue.
--- 
This is a fix for a bug reported in a comment of another issue here: https://github.com/FreeCAD/FreeCAD/issues/9639#issuecomment-2336005447
I haven't seen this issue reported separately, so nothing to close.
While it is possible to assign any shortcut to the Std_Delete command, that command isn't used in these places.
From a users point of view, I think it is expected that these uses the same shortcut.
---
I changed the all instances where an action was hardcoded to delete, but I haven't been able to find all places where they are used yet.
The marked checkboxes in this list has been tested:
=> Reuse Std_Delete shortcut instead of hardcoding Delete

src/App/DocumentPy.xml, src/App/DocumentPyImp.cpp, src/App/GeoFeature.cpp, src/Gui/Application.h, src/Gui/ApplicationPy.cpp, src/Mod/Assembly/CommandCreateAssembly.py, src/Mod/Assembly/CommandCreateBom.py, src/Mod/Assembly/CommandCreateJoint.py, src/Mod/Assembly/CommandCreateView.py, src/Mod/Assembly/CommandExportASMT.py, src/Mod/Assembly/CommandInsertLink.py, src/Mod/Assembly/CommandSolveAssembly.py, src/Mod/Assembly/JointObject.py, src/Mod/Assembly/UtilsAssembly.py
Added support code to core to allow getting python objects back from python commands.
Added necessary wrappers and code to Assembly to provide console logs and Macro info for all commands executed.
Feedback requested, ~and this might best be a post 1.0 change, unless it gets a lot of attention.~  Feeling confident in it now, and it changes the game with reporting problems with Assembly since we can see what's going on.
@PaddleStroke Apologies for what this does to pristine code.  If there's another way, I'm all ears.
=> Assembly: Support macros and console logs in Assembly

src/Main/MainGui.cpp
Initialising Qt with native LC_NUMERIC affects XML import on CLI (freecad -c) This causes sketch constraints and potentially other components relying on numeric constants to break or have incorrect values. Forcing LC_NUMERIC to C avoids this issue and enforces reproducible behaviour on all locales. This does not affect the number format displayed in the GUI, as set in preferences.
=> CLI: Enforce LC_NUMERIC=C on Posix systems (#16724)

src/Mod/BIM/bimcommands/BimViews.py
Fix error starting BIM Wb in certain scenarios:
```
11:21:36  Traceback (most recent call last):
11:21:36    File "/home/username/freecad-daily-build-coin403/Mod/BIM/bimcommands/BimViews.py", line 270, in update
11:21:36      i = QtGui.QTreeWidgetItem([v.Label, ""])
11:21:36                                 ^^^^^^^
11:21:36  AttributeError: 'list' object has no attribute 'Label'
```
=> [BIM] Fix error starting BIM Wb for certain new users

src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp
The spreadsheet has its icon hardcoded in the view provider source file.
This isn't the normal case for icons and makes it difficult to improve on the look and feel.
As a side effect of using a low res pixmap icon, other icons on the same tree item seem to become the same resoultion. (as can be seen on the eye-icon).
Left is before and right is after the change:
The icon is the same as the one for creating a new spreadsheet:
=> Swaps out the hard coded icon to the standard svg icon

src/Mod/Part/App/TopoShape.h
this PR attempts to resolve build issue on macos homebrew regarding missing include per the issue opened with #15329 and per the request of @luzpaz
=> #15329 add missing include to resolve build error

src/Mod/Measure/App/Measurement.cpp
( Fix #16794 )
The measurement code did not handle mixed selections of known and unknown types correctly. Although a unknown selected object would leave the type at Invalid, selecting both known and unknown objects would have the type determined by the known object type and treat the unknown as the same. This causes exceptions and - worst case a segmentation fault.
This fix introduces a new category "other" which - if present in a selection always forces type to Invalid. This should be forward compatible in case new types are introduced in the future.
=> Measurement: Correctly handle unknown selections to avoid segfaults ( Fix #16794 )

src/Mod/Draft/draftobjects/shapestring.py
The `faces.concatenate` function can return a Face or a Compound. The code did not take that into account.
=> Draft: ShapeString Fuse caused single face string to lose fill

src/Mod/Material/Gui/MaterialTreeWidgetPyImp.cpp
The MaterialTreeWidget was not working in QT6 due to a type check for a QT5 widget
=> Materials: Fix QT6 error

src/Mod/Measure/App/Measurement.cpp
(Fix  #16820)
Returning a null shape would have triggered an exception in the bottom branch but not in the top one - which later leads to a segfault - solution - raise an exception. OOC doesn't like null shapes.
=> Measurement: Avoid null shapes to be returned in all code branches

src/Gui/MainWindow.cpp
Remembering a similar issue in the past, inspiration came from https://github.com/FreeCAD/FreeCAD/commit/48ca8d5
@kadet1090 thoughts, is this too much of a hack upon a hack?
Fixes https://github.com/FreeCAD/FreeCAD/issues/16792
If accepted, please backport to 1.0
Tested with clean configs using:
```
OS: EndeavourOS (KDE/plasmax11)
Version: 1.1.0dev.38835 (Git)
Branch: main
Hash: 256ad7a01aa2753ef7b8925ede93dd9448d80a82
Python 3.12.4, Qt 6.7.2, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/breeze
Installed mods: 
* Behave-Dark-Colors 0.1.1
* FreeCAD-themes 2024.7.24
```
=> [Gui] Qt6 OpenGLWidget - move black rectangle off screen

src/Mod/Assembly/App/AssemblyObject.cpp, src/Mod/Assembly/App/AssemblyObject.h, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp, src/Mod/Assembly/Gui/ViewProviderAssembly.h
- Bundle fix joints together when dragging to make things simpler for solver. 
- Show and redraw only the movingJoint during dragging. 
- Do not recompute joints during dragging.
This together make the dragging steps much faster.
Fix https://github.com/FreeCAD/FreeCAD/issues/16771
=> Assembly: Fix lag during dragging of large assemblies.

src/Mod/TechDraw/App/Preferences.cpp, src/Mod/TechDraw/App/Preferences.h, src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui, src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvancedImp.cpp, src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvancedImp.h, src/Mod/TechDraw/Gui/QGIView.cpp, src/Mod/TechDraw/Gui/QGIViewBalloon.cpp, src/Mod/TechDraw/Gui/QGIViewBalloon.h, src/Mod/TechDraw/Gui/QGSPage.cpp, src/Mod/TechDraw/Gui/QGSPage.h
This PR implements a fix for issue #15388.
The change includes 
- changes to obscure variable names
- replacement of hard coded modifier key definitions with preferences
- changes to the handling of modifiers in QGIBalloonLabel
- support functions added to QGSPage
- changes to advanced preference tab.
=> [TD]Balloon origin drag modifiers (fix #15388)

src/Mod/AddonManager/Widgets/addonmanager_widget_readme_browser.py, src/Mod/AddonManager/addonmanager_macro.py, src/Mod/AddonManager/addonmanager_macro_parser.py, src/Mod/AddonManager/addonmanager_workers_startup.py, src/Mod/BIM/ArchAxis.py, src/Mod/BIM/ArchBuildingPart.py, src/Mod/BIM/ArchRebar.py, src/Mod/BIM/ArchReference.py, src/Mod/BIM/ArchSectionPlane.py, src/Mod/BIM/ArchSite.py, src/Mod/BIM/bimcommands/BimClassification.py, src/Mod/BIM/bimcommands/BimLibrary.py, src/Mod/BIM/bimcommands/BimPreflight.py, src/Mod/BIM/bimcommands/BimSetup.py, src/Mod/BIM/bimcommands/BimTutorial.py, src/Mod/BIM/importers/importIFClegacy.py, src/Mod/BIM/nativeifc/ifc_psets.py, src/Mod/BIM/utils/buildPsets.py, src/Mod/CAM/Path/Post/Utils.py, src/Mod/CAM/Path/Post/scripts/gcode_pre.py, src/Mod/CAM/Path/Tool/Gui/BitEdit.py, src/Mod/Draft/draftguitools/gui_trackers.py, src/Mod/Draft/importDXF.py, src/Mod/Draft/importSVG.py, src/Mod/Import/App/SCL/Part21.py, src/Tools/generateBase/generateTools.py
Python 3.6 deprecated certain escapes in strings that happen to be common in regex expressions.  Python 3.12 made this a hard syntax error.  After running into a couple using the start page BIMExample, I've decided to pull out the howitzer and blanket change all the python RE strings I can find into raw strings to avoid future problems.
=> BIM: Make python Regex Strings raw to avoid py3.12 SyntaxError

src/Ext/freecad/module_io.py
The python file `module_io.py` accidentally uses the c++ exception name instead of the python exception name.
This bug was introduced here: https://github.com/FreeCAD/FreeCAD/commit/f763425b4f64bd36ce5e184becca62be29fcccab
The bug writes the following in the console:
```
10:40:17  pyException: Traceback (most recent call last):
File "D:\Tools\FreeCAD_1.0.0RC2-conda-Windows-x86_64-py311\bin\Lib\site-packages\freecad\module_io.py", line 12, in OpenInsertObject
except PyExc_FC_AbortIOException:
^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'NameError'>: name 'PyExc_FC_AbortIOException' is not defined
```
This fix is related to [this issue](https://github.com/FreeCAD/FreeCAD/issues/16835), but it doesn't solve that it.
=> Fix `name 'PyExc_FC_AbortIOException' is not defined`

src/Mod/PartDesign/App/FeatureExtrude.cpp
PadDesign: Work around issue #16690
This is a stopgap measure, I don't know if the underlying issue is fully understood - but this prevents it from happening in the given test case.
By overriding the base for the pocket prism, which is a trick also applied by TopoShape::makeElementPrismUntil() if the prism creation fails on first try, the bug where said prism goes to the wrong shape is avoided - this on its own would however break a pad in the inverse case, so we only do that when pocketing
=> PadDesign: Work around issue 16690

src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
Similar to https://github.com/FreeCAD/FreeCAD/pull/16714, in this case for pipelines and filters.
Flickering is more noticeable on curved surfaces and using flat color for the wireframe (view property `PlaneColorOnSurface = True`)
@FEA-eng
=> Fem: Fix flickering between faces and wireframe in FemPostObject view provider

src/App/ApplicationPy.cpp
When you generate python stubs from the libraries, you discover three doc strings that it can't understand.  This fixes them, eliminates all warnings and makes those three appear in code completion.
@oursland FYI.
=> Core: Tiny doc format changes to make pybind11_stubgen happy

src/Mod/Part/App/TopoShapeExpansion.cpp
Do not allow loft where the segment shapes are too close ( fix #5855 )
A loft or pocket only makes sense if the segments used for it have some minimum separation. Having the shapes identical causes segfaults in OCCT
Checking for CoG is a hack. Identical shapes have identical CoG - but an identical CoG does not necessarily mean identical shapes - however it can be argued that a shape that is not offset at least somewhat in the direction of the loft doesnt make a valid shape for a loft (it will typically freeze OCCT instead of crashing it) and a sufficiently suitable shape will have a different CoG
throwing the exception will make it easy to identify if there ever is a case where this is a bad thing - and exceptions are better than segfaults.
=> Part: Do not allow loft where base and first segment are too close

src/Mod/TechDraw/Gui/QGIHighlight.cpp
This PR implements a fix for an issue with continuous lines in detail highlights as reported here: https://forum.freecad.org/viewtopic.php?t=90933
=> [TD]fix continuous line detail highlight not shown

src/Gui/TaskView/TaskImage.cpp, src/Gui/TaskView/TaskImage.ui
The restored Euler angles of a rotation may significantly differ from the input Euler angles so that determining the plane isn't very reliable. To get the plane reliably multiply (0,0,1) with the rotation and use this as reference normal of the plane.
Do not set to XY plane by default if the rotation of the image doesn't match.
Fixes https://github.com/FreeCAD/FreeCAD/issues/16735
=> Core: Fix resetting placement of transformed image

src/Gui/MainWindow.cpp, src/Gui/StartupProcess.cpp, src/Gui/StartupProcess.h
Hello, I am submitting here a rollback of 9b409da. Due to reported regressions in some platforms.
References:
https://github.com/FreeCAD/FreeCAD/issues/16798
https://github.com/FreeCAD/FreeCAD/issues/16264
Reverted Commits:
9b409da
Effects:
This restores the splash screen to its previous state, so it appears for a ridiculous short time in all platforms but allows the fragile startup process to continue without interference on all platforms.
=> Revert 9b409da due to a regression in some platforms

src/Build/CMakeLists.txt
Prevous Version.h was not regenerated after it was initially created. This prevented an accurate commit hash in the About dialog when incrementally building from source.
Now the file is always rewritten when it's content is changed.
Fixes #16871
=> Regenerate Version.h if the git hash changes

src/Gui/GuiApplication.cpp
This is a first step to fix https://github.com/FreeCAD/FreeCAD/issues/16905.
While the situation might work on some platforms, it will cause a crash on other platforms (confirmed on macOS).
Adding this message informs developers (on all platforms) that they just witnessed a situation that would cause a crash (on some platforms).
This hopefully makes them investigate the issue further and create a fix for it.
=> Include a warning to developers for unhandled exceptions in GUIApplication::notify

src/Mod/Part/Gui/TaskCheckGeometry.cpp
https://github.com/FreeCAD/FreeCAD/issues/16625
Crash occurs when expanding Origin object in Part Design and attempting to run Part workbench CheckGeometry on the X-axis object when the too small edge option is enabled.
This PR bypassing checking such objects by checking boundbox diagonal length > 1e100.  A warning is displayed in the report view on skipping these objects, and also a warning is shown when skipping objects with null shapes or no shapes, such as spreadsheet objects.
=> [Part CheckGeometry] prevent crash when attempting to check origin axis

src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp
This adds a SoSwitch to the globalSeparator of ViewProviderMeasureBase and connects it to the pcModeSwitch.
Fixes #16213
=> MeasureGui: Also hide delta measurements

src/Mod/Fem/Gui/Resources/translations/Fem_it.ts
An error in the Italian translation added an extra '{}' to the translation string resulting in a dump when formatting.
This has also been updated in CrowdIn but as it's causing a crash is also beiung changed via this PR. It should updated correctly when doing the next translation pull.
Fixes #16704
=> FEM: Translation error causing a crash

src/Gui/DlgExpressionInput.cpp
Closes https://github.com/FreeCAD/FreeCAD/issues/16946.
Disconnect the VarSet signal handlers in the destructor of the expression editor dialog.
It appeared (also clear in the stacktrace in the issue) that on destruction of the dialog, a QComboBox is deconstructed with a QTreeModel. In this destructor, the model is reset and that sends some signal. The signal handlers of the logic handling the VarSets don't anticipate that it can receive signals while destructing. 
I disconnected the signal handlers in the deconstructor to fix this. I did not add the other signal handlers as no issues have been reported with them. However, disconnecting signal handlers could be considered good practice, so I'm happy to disconnect them as well in this PR.
=> Gui: Fix segfault in Expression Editor/VarSet

src/App/PropertyStandard.cpp, src/App/PropertyStandard.h, src/Mod/Material/CMakeLists.txt, src/Mod/Material/InitGui.py, src/Mod/Material/TestMaterialsGui.py, src/Mod/Material/materialtests/TestMaterialDocument.py, src/Mod/Part/Gui/ViewProviderExt.cpp, src/Mod/Part/Gui/ViewProviderPartExtPyImp.cpp
Custom attributes were modified to maintain the behaviour of setting transparencies using the DiffuseColor alpha channels
fixes #14938
=> Materials: Correct DiffuseColor custom attribute

src/Mod/Measure/Gui/QuickMeasure.cpp
As described in https://github.com/FreeCAD/FreeCAD/issues/16905, macos crashes when exceptions are reaching qt.
The crash this PR fixes is described this comment: https://github.com/FreeCAD/FreeCAD/issues/16888#issuecomment-2381031659
The reason why FreeCAD crashes is:
1. OCCT throws an exception [here](https://github.com/FreeCAD/FreeCAD/blob/6e2cd4e73303f817e4bf5e908abe39030b7c5fb3/src/Mod/Measure/App/Measurement.cpp#L361)
2. The exception is not caught in `QuickMeasure::processSelection()`
This PR adds a catch for OCCT exceptions as well as a generic for unknown exceptions.
Note, this doesn't fix the bug, but it fixes the crash.
=> Measurement: Fix macos crashes caused by unhandled exceptions reaching qt

src/App/Graphviz.cpp
Fixes two problems with the dependency graph.
* #16878
* #16879
Nested `GeoFeatureGroupExtension` are always shown nested independent of their creation order
Depencency edges for `GeoFeatureGroupExtension` are only ommited if the dependency is a child of the group
=> Fix nested groups and dependency edges for groups in the dependency graph

src/Mod/Measure/Gui/QuickMeasure.cpp, src/Mod/Measure/Gui/QuickMeasure.h
Fix https://github.com/FreeCAD/FreeCAD/issues/16888
Fix https://github.com/FreeCAD/FreeCAD/issues/16961
Potential fix for https://github.com/FreeCAD/FreeCAD/issues/16844 but as the report is missing information I can't be sure.
=> QuickMeasure: Prevent crash by limiting selection to Part::Features

src/Mod/AddonManager/addonmanager_preferences_defaults.json, src/Mod/AddonManager/package_list.py
Default filter should be not filter at all. It makes discover-ability of addons easier for new users.
=> [AddonManager] Set default filter to ANY package type

src/App/GeoFeature.h, src/App/GeoFeaturePy.xml, src/App/GeoFeaturePyImp.cpp, src/Mod/Assembly/UtilsAssembly.py
This PR adds python binding to the new getGlobalPlacement. You can now do: 
`App.GeoFeature.getGlobalPlacementOf(targetObj, rootObj, subname)`
This PR also remove the reimplementation of getGlobalPlacement in python and use instead the cpp python binding.
Fix the comment : https://github.com/FreeCAD/FreeCAD/pull/15262#issuecomment-2371447889
=> Core: getGlobalPlacement : add python binding

.github/workflows/sub_lint.yml
Working on tweaking the cpplint settings to give less noise. Transition to explicitly listing out all warning categories so they are easier to remove. Modification to a Sketcher file that is very lint-heavy to see the output from the linters.
Note that our current CI runs three separate linters on the C++ code: cpplint, clang-tidy, and clazy.
=> CI: cpplint exclusions update

src/Gui/Placement.ui
Fixes #16944
Unless the custom tabstops in this UI were deliberate, they should be removed as per this PR. The default order is the desired order.
=> Placement Dialog: Use default tab order (Fix #16944)

src/Gui/PreferencePages/DlgSettingsLightSources.ui
Already defined at line 239. Emits warning during compilation (Qt6)
=> Gui: fix warning with duplicate name in DlgSettingsLightSources

src/Mod/PartDesign/App/FeatureAddSub.cpp, src/Mod/PartDesign/App/FeatureAddSub.h, src/Mod/PartDesign/App/FeatureHelix.cpp
Consider refinement not critical for Helix operation.
If the Refine property is set but its process fails it only warns and the feature is not put in an error state.
ref: https://github.com/FreeCAD/FreeCAD/issues/16081#issuecomment-2378786627
=> [PD Helix] allow the operation to succes even with a failing refine

src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
Ideally there would be an additional constraint replacing the spurious tangency, but that falls in feature territory for 1.0.
=> [Sketcher] Fix #16321.

src/Mod/Draft/DraftGui.py
Fixes #17027.
The `DraftTaskPanel.reject()` function can be called multiple times if Esc is pressed during a fast mouse move. We need to prevent multiple calls to `draftToolBar.escape()` as this will lead to multiple calls to `gui_utils.end_all_events()` which results in a crash.
=> Draft: Stop draftToolBar.escape() executing multiple times

src/Mod/Draft/draftutils/gui_utils.py
Fix #16332.   ~std::queue is not thread safe, and QTApplication timer delays can go out on another thread.  I didn't bother to fully analyze the thread behavior, I just brute forced a mutex around every likely problem area.  This could probably be refined, but I'm not sure there would be much benefit.  Building or finding a thread safe queue to use instead would likely be prettier, but this is hopefully a clear, minimal change solution to deal with bug for now.~
Replaced with suggestion from Roy-043
=> Core: Disallow end_all_events in Gesture Nav Style

src/Mod/Measure/Gui/QuickMeasure.cpp
fix #16888
QuickMeasurement should not measure while tool dialogs are open this includes but is not limited to editing sketches also changed several other sanity checks to be opt-in vs opt-out, as discussed.
=> Changed QuickMeasurement to be conservative

src/Mod/Material/App/Materials.cpp
This PR fixes issue #17035.
Though it looks like its just a cosmetic code change, I found out that it also fixes something I noticed that lately it takes several seconds till freecad start responding after startup (Example, start freecad, start new document, select part work bench, then click on the cube. it takes about 2 seconds to appear)
After this fix it takes a fraction of a second.
it looks like the std exceptions when loading the material library outputs the errors to the log, and with about ~12K of such messages it slows down freecad.
=> [Material][1.0] Fix issue #17035

src/Mod/PartDesign/App/FeaturePrimitive.cpp
2276ffb fix the body movement when the AttachementOffset property is edited.
22131b3 fix the misplaced shape when the subtractive doesn't remove anything. Fix #12072 
A misplaced shape still occurs when a pattern is applied to a subtractive which doesn't remove material.
I think the error comes from `TopoShape::getSubTopoShape`. As I understand when the shape is not modified it returns the ancestor but the AttachementOffset is applied. @bgbsww @chennes @realthunder would you analyze this?
=> PartDesign: Fix primitive placement

src/Mod/TechDraw/Gui/TaskProjGroup.cpp
This fixes the compiler warning: unused parameter 'mode' [-Wunused-parameter]
It's a regression of #16889 to not initialize the class member m_createMode any more that causes UB, i.e. whenever m_createMode is accessed it may return an unexpected value.
=> TD: Fix compiler warnings

src/Mod/Start/Gui/FirstStartWidget.cpp, src/Mod/Start/Gui/StartView.cpp
This is a small adjustment to the First Start page, so the BoxLayout is centered vertically and horizontally with no "extended/stretched" area.
Before:
After:
I could only test on :
```
OS: GNU/LInux Ubuntu 22.04 LTS (DE:Gnome/pop)
Version: 1.1.0dev.38844 +1 (Git)
Branch: first-start-layout-tweak
Hash: bc81bdff670f93ca099e20857ea35911a222b1f6
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk , OCC 7.6.3
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```
Let me know if it is OK too for Qt6 and other configs =D
=> Start: little layout tweak to First Start Region

src/Gui/Application.cpp
https://forum.freecad.org/viewtopic.php?t=90816&start=10#p783801
To reproduce the issue try to import a step file with a filename containing non-latin characters.  I used a file named: δοκιμή.stp (which I believe to mean "test.stp" in Greek, but it's all Greek to me.  I cannot upload it here because the file extension is not supported.
I could not import the file in the current build, but was able to import after applying this PR.  I was also able to import other files that did not contain non-latin characters in step format and in other formats, too.
I believe the Base::Tools::escapedUnicodeFromUtf8() function is a holdover from python2 support and is probably no longer needed, but I'm not 100% certain of this.
There might be another, better way to fix this issue.
=> [Step Import] fix issue with non-latin characters in import path

src/Mod/Fem/Gui/Resources/ui/MeshGmsh.ui, src/Mod/Fem/Gui/Resources/ui/MeshNetgen.ui
At the current size, the quantity spin boxes are cropped  (may depend on resolution and stylesheet used).
=> Fem: Use default size for mesh task panel quantity spin boxes

src/Mod/Assembly/JointObject.py
Fix https://github.com/FreeCAD/FreeCAD/issues/16722
If you try to migrate an old file with a joint that does not have reference (Object1 or Object2 = None) then you get some error messages. This PR patches this issue
=> Assembly: Fix migrationScript2 error with bad joints

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
Fix double click of wire and remove selection that was not working.
Fix https://github.com/FreeCAD/FreeCAD/issues/16953
=> Sketcher: Fix double click of wire and remove selection

src/Mod/BIM/ArchStructure.py, src/Mod/BIM/bimcommands/BimWall.py, src/Mod/BIM/bimcommands/BimWindow.py
=> BIM: Remove calls to end_all_events to avoid Linux crash

src/Gui/Application.cpp
On macOS, we can get a state where the splashscreen is shown on top of a dialog.
Since dialogs pauses FreeCAD, the splashscreen never closes.
For the user, this looks like FreeCAD stops responding. 
The severity is equal to a crash in my opinion.
---
This behavior can be seen when opening FreeCAD with an old file from closed state (double click a FreeCAD document or drag a document to FreeCAD.app). Then the recompute required warning will pop up under the splasher.
This behavior can only be seen when FreeCAD is built as a bundle. I haven't been able to reproduce the exact scenario on a "naked" dev binary build.
The issue has been discussed in this thread (though that started as a crash which has been fixed):
https://github.com/FreeCAD/FreeCAD/issues/16828#issuecomment-2380554810 …
=> Make sure splasher is stopped before showing recompute dialog

src/Gui/DlgAddPropertyVarSet.cpp, src/Gui/DlgAddPropertyVarSet.h
Closes https://github.com/FreeCAD/FreeCAD/issues/16776.
After some research, it turns out that it is very difficult to prevent a QComboBox with a QLineEdit from sending only one signal.  Clicking the triangle in the combo box results in two editFinished signals and this can be mitigated by using event filters that detect whether the dropdown menu is shown.  However, typing in a string that matches one of the items and then pressing tab to go to the next field, issues a QLineEdit::editingFinished event and a QComboBox::currentIndexChanged event and both make sense.
This means that the best way to deal with this is to record some state if one of such events is being handled and act accordingly.
This PR makes the signalling more elegant (because logically, we want to act on the …
=> Gui: Fix showing multiple dialogs when adding properties to VarSet 

src/Gui/Stylesheets/FreeCAD Dark.qss, src/Gui/Stylesheets/FreeCAD Light.qss
This fixes:
https://github.com/FreeCAD/FreeCAD/issues/17230
The button with the purple:
=> Fixing the checked toolbutton issue in Qsint

src/Mod/CAM/PathSimulator/AppGL/Shader.cpp
This issue was reported on the forum [Here :](https://forum.freecad.org/viewtopic.php?p=786746#p786746)
```
18:33:37  Error compiling Blur fragment shader: 0:15(42): error: parameter `in offset' must be a constant expression
0:15(9): error: type mismatch
```
its a small shader fix and should be safe.
=> [Cam simulator][1.0] Fix shader compilation error on linux.

src/Mod/Fem/femexamples/constraint_centrif.py, src/Mod/Fem/femexamples/constraint_contact_solid_solid.py
`constraint_centrif` and `contact_solid_solid` examples are broken if Part workbench preference `Automatically refine model after boolean operation` is not checked.
=> Fem: Fix examples affected by Part workbench preference parameter

src/Mod/Part/App/PropertyGeometryList.cpp
Write all XML attributes of the Geometry element into a single line.
Currently the XML output looks:
```
<Geometry type="Part::GeomLineSegment"
id="-1" migrated="1">
```
With the fix it will be:
`                        <Geometry type="Part::GeomLineSegment" id="-1" migrated="1">`
=> Part: Fix XML output of PropertyGeometryList::Save

src/Gui/Application.cpp, src/Gui/Application.h, src/Gui/MainWindow.cpp, src/Mod/Test/Document.py
Close #16616 
The Qt6 (up to Qt 6.7.3 now) contains bug, which can lead, under specific circumstances, to crash of the application, when the MDI window is closed. The circumstances are:
* at least 2 MDI windows needs to be open
* stylesheet must set different size (border, margin) for activated and un-activated tabBar tab
* the closed window must be inactive, but created before the window now active and open
* race condition must occur betwee the closing and resize event handlers for the tabBar (see qt bug for details)
So this bug only occures with Qt6 with the Dark or Light styles selected (no classic) and only if specific sequence of steps is followed during opening and closing the MDI windows.
The bug is in Qt code path executed when QMdiArea::ActivationHistoryOrder is set.
The other …
=> Gui: Workaround for crash on close of MDI window

src/Gui/DlgAddPropertyVarSet.ui
Fixes #17067
Tested/compiled on Windows 11 23H2.
=> Fix tab order in Add Property Dialog (VarSets)

src/Gui/Splashscreen.cpp
There is several bugs in FreeCAD which are related to platform (eg wayland/X11/...), the hope is this will make it easier to identify the dependence of bug on the platform
Example:
```
OS: Arch Linux (KDE)
Version: 1.1.0dev.38943 (Git)
Branch: makepkg
Hash: b63c0e15919af5a967b043a141a7163c6c241b6d
Python 3.12.6, Qt 6.7.3, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Platform: wayland
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
```
=> Gui: add Qt Platform name to splashscreen information dump

src/Mod/TechDraw/App/DrawViewDimension.cpp, src/Mod/TechDraw/App/DrawViewDimension.h, src/Mod/TechDraw/Gui/QGIViewDimension.cpp, src/Mod/TechDraw/Gui/QGIViewDimension.h
This PR implements a fix for issue #17189.  The dimension reference autocorrect process was overly strict in dealing with changed geometry.
=> [TD]throttle over aggressive dimension autocorrect (fix #17189)

src/Mod/Spreadsheet/App/Sheet.cpp
#16940
If field values contain a delimiter character, the values will be enclosed with quotation character in exported CSV file.
This change does not affect the default behavior in TAB delemited CSV file.
=> Change to enclose field values ​​with quotation character in exported CSV file if they contain delimiters in Spreadsheet workbench

src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp, src/Mod/Start/Gui/StartView.cpp
fixes #17056 
This PR does the following:
* Combines open and insert spreadsheet to reduce code duplication
* Creates new document on import of docName does not exist as required by [MainWindow](https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/MainWindow.cpp#L2415):
> `// if the passed document name doesn't exist the module should create it, if needed`
* Let recent file cards in start open files instead of importing them. This also makes start open the recent files in the same way as [CmdStdOpen](https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/CommandDoc.cpp#L158) and [RecentFilesAction](https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/Action.cpp#L916)
By doing this it avoids two crashes on macos (and most likely error messages on windows and linux)
=> Fix crashes when importing and opening .csv files on macOS

src/Gui/TextDocumentEditorView.cpp, src/Gui/TextDocumentEditorView.h
Store changes made in TextDocumentEditorView immediately to TextDocument. This fixes the issue reported in https://forum.freecad.org/viewtopic.php?p=786175#p786175
=> Core: Directly store text changes made in text object

src/Gui/FreeCADGuiInit.py
Multiple places in code, asserts for bad types would trigger SIGABRT. This is not just limited to #16316 with SoZoomTranslation, but multiple more places, not described in issue, but I experienced myself. Fixes #16316
=> [Gui] Fix isBad asserts by removing old monkey patch

conda/environment-qt6.devenv.yml, conda/environment.devenv.yml, src/Mod/BIM/bimcommands/BimIfcExplorer.py
we dropped python2 support a long time ago so this is not needed
=> Bim remove py2 compatibility code

src/Mod/TechDraw/App/Geometry.cpp
Fix for error as reported on forum https://forum.freecad.org/viewtopic.php?p=787095#p787095:
```
[ 75%] Building CXX object src/Mod/Inspection/Gui/CMakeFiles/InspectionGui.dir/Workbench.cpp.o
/opt/freecad-source/src/Mod/TechDraw/App/Geometry.cpp: In member function ‘void TechDraw::Vertex::createNewTag()’:
/opt/freecad-source/src/Mod/TechDraw/App/Geometry.cpp:1403:19: error: ‘mt19937’ in namespace ‘boost’ does not name a type
1403 |     static boost::mt19937 ran;
|                   ^~~~~~~
/opt/freecad-source/src/Mod/TechDraw/App/Geometry.cpp:1409:9: error: ‘ran’ was not declared in this scope; did you mean ‘tan’?
1409 |         ran.seed(static_cast<unsigned int>(std::time(nullptr)));
|         ^~~
|         tan
/opt/freecad-source/src/Mod/TechDraw/App/Geometry.cpp:1412:56: error: …
```
=> [TechDraw] Fix error for some compilers

src/Mod/Sketcher/App/SketchObject.cpp
SketchObject::buildShape() used the geometries as they were created by the user. However, they are not accurate enough in order to create a closed wire. Instead the geometries after running the solver must be used because they are guaranteed to be accurate.
=> Sketch: Fix creating the shape of a sketch

src/Mod/Fem/femtools/femutils.py
Fixes #17255.
Now the mesh processes are running in another thread. Therefore, calling widgets directly from main thread results in undefined behavior.
@wwmayer
=> Fem: Do not use main window widget from another thread - fixes #17255

src/Gui/PreferencePages/DlgSettingsEditor.cpp
Fixes #11681.
Qt >=5.2 offers a built-in function to determine the system's preferred fonts. This function should be used to determine the default fixed-width font used for the Python editor settings (and hence the Report View).
=> Use Qt built-in to determine the system's preferred fixed-width font

src/Mod/BIM/bimcommands/BimLeader.py
Probably due to changes in gui_lines `self.call` was no longer ended.
Fixes #17283.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=91413
=> BIM: Fix BIM_Leader callback bug

src/Mod/Draft/draftfunctions/svg.py, src/Mod/Draft/draftviewproviders/view_layer.py
The fix in #16212 only checks the LayerContainer for layers. Since we do not stop users from moving layers out of that container, we should search the whole document instead.
Fixes: #16201.
=> Draft: Improve layer drag-drop fix.

src/Gui/DlgAddPropertyVarSet.cpp, src/Gui/DlgAddPropertyVarSet.h
Closes #17133.
The signal handlers act when the editing has finished. They assume that a new property is created and act on that assumption. When the user presses cancel or escape, the transaction is aborted which removes the newly created property. This of itself is not a problem but it turns out that after cancelling, signals can still arise and activate the signal handler that acts under the assumption that a new property has been created. This results in the new property not to be found and the segfault.
This PR disconnects the signal handlers in `reject()` because it makes no sense to allow any more signals when we reach this state.
=> Core: Fix VarSet add property dialog Esc segfault

src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
=> Fix uptoshape crash when selecting a face without assigned shape

src/Gui/GraphvizView.cpp
not tested on ~windows or~ mac yet, the dialog asking for installation path should probably be updated to give the option to reset the configured graphviz path in case of a bad config so that it can be looked up in PATH again. Currently you need to manually go to the parameter editor and remove the parameter
=> Gui: try calling graphviz binaries from PATH by default [fix #15224]

src/Mod/Sketcher/App/SketchObject.cpp
IMHO the Geometry History contains more `public` members that it should. This MR makes all those member private.
=> Sketch: refactor GeoHistory, make more members private

src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femmesh/netgentools.py, src/Mod/Fem/femobjects/base_fempythonobject.py, src/Mod/Fem/femobjects/mesh_netgen.py, src/Mod/Fem/femtaskpanels/task_mesh_netgen.py
~To be merged after https://github.com/FreeCAD/FreeCAD/pull/17170 just to avoid conflicts (The first two commits come from that pull request).~
Currently, the first and last mesh steps are defined by integer values. More meaningful enumeration values ​​are now used.
Fineness has a few predefined values ​​(`VeryCoarse`, `Coarse`, etc.) and `UserDefined` which is used to set custom parameter values. The predefined values ​​basically set a few parameters and leave all others as Netgen internal defaults, which makes all remaining properties obsolete. Now, only explicit parameters set by predefined fineness values ​​are set, while the rest can be defined by the user.
@FEA-eng
=> Fem: Netgen meshing parameters improvements

src/Mod/Part/Gui/ViewProviderExt.cpp
fix #17183
Part: Disable tesselation limit in ViewProviderGUI to prevent large parts from freezing FreeCAD
took this from #17214
required for work on #9377
@ Triage see https://github.com/FreeCAD/FreeCAD/pull/17214#issuecomment-2411342073 - assign for 1.0 ?
=> Part: Disable tesselation limit in ViewProviderGUI to prevent large parts from freezing FreeCAD

src/Mod/Part/App/PrimitiveFeature.cpp, src/Mod/PartDesign/App/FeaturePrimitive.cpp
The cone features in Part and PartDesign automatically create a cylinder if top and bottom radius are identical. However, the algorithm ignores the angle and always creates a full cylinder.
=> Part/PD: Fix cone creation if both radii are equal

src/Gui/CommandDoc.cpp
Currently, if the user chooses to overwrite the proposed filename in the export dialog, the new filename becomes the new default even after opening a different file.
This PR fixes that by detecting that the active file has been changed, and then suggesting the default again.
Fixes #16839
=> Export Dialog:Switch back to default filename 

src/Gui/Application.cpp, src/Gui/GuiApplication.cpp
Fixes #17280
TL;DR
Files are loaded before main window is loaded, things go kaboom.
Delay the load event a bit fixes the issue
Please, don't squash this PR, one of the commit reverts an earlier attempt, it makes sense to keep that revert that change in a separate commit.
Only backport the second commit "Repost QFileOpenEvent event to avoid an undefined state", as the previous attempt was never backported.
---
When the user double clicks a `.FCStd` file in Finder when FreeCAD isn't open, FreeCAD will start and get an event from Qt immediately.
This event will be processed when the event loop is started, which by design is done when the main window has been loaded as evident in `Gui::Application::runApplication()`.
Normally loading files are postponed and handled in `delayedStartup` but if …
=> Workaround for macOS crash when loading FreeCAD by opening a `.FCStd` file from Finder

src/Gui/Application.cpp
=> Core: Set unit scheme when switching between unsaved documents

src/Mod/Part/App/FeatureChamfer.cpp, src/Mod/Part/App/FeatureCompound.cpp, src/Mod/Part/App/FeatureFillet.cpp, src/Mod/Part/App/FeatureMirroring.cpp, src/Mod/Part/App/FeaturePartBoolean.cpp, src/Mod/Part/App/FeaturePartCommon.cpp, src/Mod/Part/App/FeaturePartFuse.cpp, src/Mod/Part/App/PartFeature.cpp, src/Mod/Part/App/PartFeature.h, src/Mod/PartDesign/App/Body.cpp, src/Mod/PartDesign/App/Feature.cpp, src/Mod/PartDesign/App/Feature.h, src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp, src/Mod/PartDesign/Gui/ViewProviderBody.cpp, src/Mod/PartDesign/Gui/ViewProviderBody.h
Inherit the material from the parent object when creating a new object, such as during a boolean operation, or when extruding a sketch.
fixes #15503
=> Materials: Child ignoring parent material

src/Gui/SoFCUnifiedSelection.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/16920
To fix this we just needed to return true in the case of deselection as it was before https://github.com/FreeCAD/FreeCAD/pull/16203.
=> Core: Fix Ctrl-deselection issue

src/Gui/Application.cpp
filter out:
-qt.qpa.wayland
-kf.config.core
-kf.kio.widgets
-kf.service.sycoca
-kf.solid.backends.udisks2
all the kf messages come from kde components usually when using the file open dialog so I don't think they are relevant to us. Should fix #16687 but I couldn't reproduce to actually test it
=> Gui: extend warning filters

src/Mod/Tux/InitGui.py
os.listdir() raises an exception if modpath does not exist.
---
This causes a red message in the Report view that tells the user "Please look into the log file for further information"
=> Tux: Avoid warning on startup when BIM is not installed

src/Mod/PartDesign/Gui/Command.cpp, src/Mod/PartDesign/Gui/CommandBody.cpp, src/Mod/PartDesign/Gui/CommandPrimitive.cpp, src/Mod/PartDesign/Gui/SketchWorkflow.cpp, src/Mod/PartDesign/Gui/SketchWorkflow.h, src/Mod/PartDesign/Gui/Utils.cpp, src/Mod/PartDesign/Gui/Workbench.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/15655
That crash was due to the migration scripts.
As @FEA-eng mentioned in the forum (https://forum.freecad.org/viewtopic.php?t=89431#p773404) the migration checks are very obsolete.
This PR removes those checks.
=> PartDesign: Remove legacy/modern workflow checks.

src/Mod/PartDesign/App/FeatureExtrude.cpp
This fixes regression introduced with TNP fix. It removes code responsible for centering the extrusion when symmetry was checked, this is exactly how it was done in 0.21. 
No UI changes are necessary since UI was already in a good condition. Migration code is also not necessary since it only aligns toponaming aware code with one that is not.
Fixes: #16072
=> PD: Fix TwoLengths and Midplane both enabled

src/Gui/Application.h
The fix is also in 6.5.8+, but honestly I would not bother ...
Consider also backport to 1.0 version
=> Disable Qt bug 129596 workeround for Qt >= 6.8.1

src/Mod/Sketcher/App/SketchObject.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/13943
Fix https://github.com/FreeCAD/FreeCAD/issues/17442
We could change the Constraint::copy() function not to copy the name, but I'm not confident that would not generate issues.
=> Sketcher: Symmetric: Do not copy names of constraints

src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/17387
https://github.com/FreeCAD/FreeCAD/pull/16985 fixed an issue with ellipse that had an unwanted tangent. But by doing so the case of circle to circle was now entering the `if (constr.Type == Sketcher::Tangent` and then was adding no auto-constraint because `hitShapeDir.length` is 0. While before it was skipping this if block and was adding the tangent correctly.
This PR makes sure the if block is entered only if preselection is a line.
=> Sketcher: Fix circle tangent issue

src/Mod/TechDraw/Gui/MDIViewPage.cpp, src/Mod/TechDraw/Gui/MDIViewPage.h, src/Mod/TechDraw/Gui/PagePrinter.cpp
This PR implements a fix of some minor issues raised in issue #17403 - specifically the act of printing marking the document as modified and a missing redraw to the screen after printing.
The main issue raised in #17403 will need changes to QtSvg to support clipping.  It might be possible to use the new pattern support in Qt6.7 as a replacement for the missing clipping support but this has not yet been investigating.
=> [TD]do not mark document as changed after print

src/Mod/TechDraw/Gui/QGSPage.cpp, src/Mod/TechDraw/Gui/QGSPage.h
This PR implements a fix for issue #17519 where items were being "unselected" by the mouseReleaseEvent method.
=> [TD]remove spurious mouseReleaseEvent (fix #17519)

src/Gui/NavigationStyle.cpp
A follow up of #17341. This PR tries to fix the slow rotation amount caused by #17341. There may still be another regression caused by #17341.
=> Gui: Correct spin sensitivity

src/Mod/Sketcher/App/PythonConverter.cpp, src/Mod/Sketcher/Gui/DrawSketchHandlerRotate.h
Fix https://github.com/FreeCAD/FreeCAD/issues/14769
Fix https://github.com/FreeCAD/FreeCAD/issues/15547
There were 2 issues actually : 
- "bad" arcs would be added by the python converter without fixing the CCW. Exploding the sketch
- The distance X and Y were being copied. And if you rotate a sketch that's obviously bad.
We could actually handle DistanceX/Y when rotating 90 or 180, but it appears that DistanceX/Y are finicky so that's another project. I left a comment with the necessary code for when DistanceX/Y's issues are fixed.
=> Sketcher: Rotate : Fix exploding sketches when rotating.

src/Mod/Assembly/App/AppAssembly.cpp, src/Mod/Assembly/App/AssemblyLink.cpp, src/Mod/Assembly/App/AssemblyLink.h, src/Mod/Assembly/App/AssemblyLinkPy.xml, src/Mod/Assembly/App/AssemblyLinkPyImp.cpp, src/Mod/Assembly/App/AssemblyObject.cpp, src/Mod/Assembly/App/AssemblyObject.h, src/Mod/Assembly/App/CMakeLists.txt, src/Mod/Assembly/App/JointGroup.cpp, src/Mod/Assembly/CMakeLists.txt, src/Mod/Assembly/CommandInsertLink.py, src/Mod/Assembly/Gui/CMakeLists.txt, src/Mod/Assembly/Gui/Resources/Assembly.qrc, src/Mod/Assembly/Gui/Resources/icons/Assembly_AssemblyLink.svg, src/Mod/Assembly/Gui/Resources/icons/Assembly_AssemblyLinkRigid.svg, src/Mod/Assembly/Gui/Resources/panels/TaskAssemblyCreateJoint.ui, src/Mod/Assembly/Gui/Resources/panels/TaskAssemblyInsertLink.ui, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp, src/Mod/Assembly/Gui/ViewProviderAssemblyLink.cpp, src/Mod/Assembly/Gui/ViewProviderAssemblyLink.h, src/Mod/Assembly/Gui/ViewProviderJointGroup.cpp, src/Mod/Assembly/Gui/ViewProviderJointGroup.h, src/Mod/Assembly/JointObject.py, src/Mod/Assembly/SoSwitchMarker.py, src/Mod/Assembly/UtilsAssembly.py
This introduce 'AssemblyLink' document object. These are not deriving from App::Link, but in fact deriving from App::Part.
Instead of linking to an assembly like a link would do, it is populating itself with links to the various components. Enabling to have different component placements between each instance of AssemblyLink.
Fix https://github.com/FreeCAD/FreeCAD/issues/15208
Fix https://github.com/FreeCAD/FreeCAD/issues/16436
builds on top of https://github.com/FreeCAD/FreeCAD/pull/16317 so that one needs to merge first.
=> Assembly: Flexible sub-assemblies.

src/Gui/DlgMacroExecuteImp.cpp, src/Gui/DlgToolbarsImp.cpp, src/Gui/DlgToolbarsImp.h
In the Macros Execute dialog there is a toolbar button.  Clicking that with a macro selected takes the user to a toolbar installation walkthrough.  This function creates a modified version of the customize dialog with instructions tailored specifically for adding a macro to a custom toolbar.  Because some of the functions needed to be called were protected, QMetaObject::invokeMethod() was used to call those functions.  The problem is this uses a string to name the method to call, and thus did not produce a compile time error when those methods were subsequently renamed in a later commit.  To avoid this problem happening again I have made those functions public and called them directly rather than using invokeMethod().
The methods that weren't being called were supposed to be selecting the …
=> [Macros Dialog] Fix broken toolbar walkthrough

src/Mod/Fem/femsolver/elmer/tasks.py, src/Mod/Fem/femsolver/z88/tasks.py, src/Mod/Fem/femtools/ccxtools.py
`femutils.startProgramInfo` returns `None` if the system is not Windows.
=> Fem: Remove unnecessary system name check

src/Mod/Part/BOPTools/ToleranceFeatures.py
In the previous iteration, the Part->Compound->Tolerance tool allowed to set a minimum tolerance for a part which sets all vertices, edges and shape tolerances to at least that high.
This is useful to allow OCCT to move these shapes around when it performs booleans, camfers, skins, etc... which can make operations succeed that normally wouldn't
However repeated use of the tool can make tolerances get too large, which leads to "edge too short" errors (that basically happens every time an edge is shorter than the tolerance of the neighboring vertices or faces)
With this patch, its now possible to also limit the maximum tolerance (which only takes effect if maxTolerance>0) and as such effectively reduce the imprecision of a part. This is not always possible and can cause shapes to become …
=> Updated Tolerance feature to optionally restrict maximum tolerance and repair shapes

src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h
=> Sketch: Make sure that variable 'ActiveSketch' is defined in macro

src/App/DocumentObjectPy.xml, src/App/DocumentObjectPyImp.cpp, src/Mod/Draft/draftguitools/gui_edit.py
* expose isAttachedToDocument to Python
* change DocumentObjectPy::getName() to return None instead of throwing an exception if object is not part of a document
=> Core: Extend DocumentObjectPy

src/Gui/CommandStructure.cpp, src/Gui/DlgAddPropertyVarSet.cpp, src/Gui/DlgAddPropertyVarSet.h, src/Gui/ViewProviderVarSet.cpp
Also tracks its own transactions to prevent interfering with other transactions.
This attempts to fix #17475, but I can't reproduce that anymore, so I'm not sure about that. When I was still on the configuration that triggered the bug, this PR did not show the same behavior.
This fixes #17486.
I see two viable solutions for #17486. One is using a transaction lock, but with a non-modal dialog, this can block other transactions that may lead to unexpected behavior for the user. The other one is making the dialog modal, which is what I chose in the end. The dialog tracks the transaction ID to prevent it to interfere with other transactions. A concrete example is opening a sketch. Using the API in `App::Document` would allow canceling this dialog to close the transaction of the Sketch which …
=> Gui: Make VarSet dialog modal

src/Gui/ViewProviderGeometryObject.cpp, src/Gui/ViewProviderGeometryObject.h
Change the appearance only if the appearance hasn't been set explicitly. A cached material appearance is used to see if the current appearance matches the last material. It is also compared against an empty material to see if the saved material value has been initialized.
This solves the problem of material changes overwriting appearance changes
=> Materials: Selectively apply appearances when changing materials

src/Mod/BIM/importers/exportIFC.py
Fix #17459 
in origin code
there is only "ElevationWithFlooring"  "Elevation" two attributes will run multiple the scale
however in IFC Schema have other kind of Elevation
eg:  IfcSite has RefElevation
eg: IfcBuilding has ElevationOfTerrain & ElevationOfRefHeight
there might be other else
but I think all of them will including the "Elevation" string in the attributes name
so I think this fix might work
=> [BIM] Fix IFC export elevation with wrong unit

src/Gui/Application.cpp, src/Gui/Application.h, src/Gui/EditableDatumLabel.h, src/Gui/MDIView.cpp, src/Gui/TaskView/TaskDialog.cpp, src/Gui/TaskView/TaskDialog.h, src/Gui/TaskView/TaskImage.cpp, src/Gui/TaskView/TaskView.cpp, src/Gui/TaskView/TaskView.h, src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp, src/Mod/Sketcher/Gui/TaskDlgEditSketch.h
Fix https://github.com/FreeCAD/FreeCAD/issues/16702
This PR enables task dialogs to associate a view, and can be set to be closed when the view is closed.
For Sketcher's task dialogs this enable to associate them to the sketchObject's 3dView. And if this 3dview is closed, then the sketch edit and task dialog are closed. Thus preventing the 3 crashes that  were reported in #16702
=> Core: Enable TaskDialogs to associate view

src/Mod/Help/Help.py
Basically surfing across links inside the Wiki was not possible because of the error.
**Should be backported.**
Is expected that you can navigate freely on the web? The Wiki is fine but you can click links that go outside the Wiki that not always load correctly for example errors like:
```python
14:07:58  (js) Access to font at 'https://forum.freecad.org/assets/fonts/fontawesome-webfont.ttf?v=4.7.0' from origin 'https://forum.freecadweb.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Collateral damage from #16621
=> Help: Fix function return to avoid error when clicking URL on built-in browser

src/Mod/Part/App/PartFeature.cpp
fix #17578 
it's just one character, what could possibly go wrong?
=> Fix Segfault Crash in TopoNaming

src/Mod/BIM/Arch.py, src/Mod/BIM/ArchSite.py, src/Mod/BIM/ArchSpace.py
When creating [IfcSpatialStructureElement](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcSpatialStructureElement.htm) objects such as Site, Building, Storey, and Space, their CompositionType attribute, which is of type [IfcElementCompositionEnum](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcElementCompositionEnum.htm), defaults to the first alphabetic option, `COMPLEX`. However, according to IFC standards, the intended default value should be `ELEMENT`.
Most of the time, we should be using ELEMENT for CompositionType. Only in specific cases, like creating split-level houses, would we use a combination of COMPLEX and PARTIAL.
=> BIM: Fix Ifc Spatial Element Default Composition Type should be 'Element'

src/Mod/Material/Gui/MaterialsEditor.cpp
The right click context menu in the materials editor was implemented as a place holder but is currently non-functional. It should be disabled for 1.0. This will be revisited post 1.0 as all editor functionality is reviewed and improved.
Fixes #17110
=> Materials: Disable editor right click menu

src/Mod/Start/Gui/CMakeLists.txt, src/Mod/Start/Gui/PreCompiled.h, src/Mod/Start/Gui/ThemeSelectorWidget.cpp, src/Mod/Start/Gui/ThemeSelectorWidget.h
This is a workaround for the broken default style "classic" on macOS when in dark mode (system settings).
When using dark mode on macOS FreeCAD, in classic, looks like this:
While it would be nice with a working classic theme, as a last resort for 1.0 this might be a solution to give new users a good first impression.
The issue has been reported on windows 11 as well.
The workaround does the following (if running on macOS, Windows, or has qt 6.4+):
* hides classic button in the start welcome screen (can still change to it in preferences)
* if the user has never selected a style, it auto-selects light or dark depending on system dark/light mode setting - default to light mode if it can't auto detect system setting (only works on macOS and qt6.4+). …
=> macOS+win+qt6.4+: Hide classic and auto choose light or dark mode depending on os setting

src/Gui/DAGView/DAGModel.cpp, src/Gui/DAGView/DAGModelGraph.cpp, src/Gui/DAGView/DAGModelGraph.h
to avoid a possible failing assert().
Fixes #17572
=> DAG: Add method hasRecord() and use it in Model::slotChangeObject

src/Gui/NavigationStyle.cpp, src/Gui/NavigationStyle.h
Fixes #17619 which is a second regression caused by #17341 and also fixes a regression in turntable navigation speed caused by #17466.
This is the behavior after this PR gets merged:
https://github.com/user-attachments/assets/9634e5c4-8aac-4f2d-9dcb-47d314538a6c
The behavior in build 38991 and 39092 can be seen here: https://forum.freecad.org/viewtopic.php?p=789527#p789527.
With this PR the behavior is more like it was in build 38991 but with slightly different behavior when the mouse starts a rotation while above an object. This is to fix the original issue #17246.
=> Gui: Fix camera behavior when rotation center is far from object

src/Mod/TechDraw/App/DrawGeomHatch.cpp, src/Mod/TechDraw/App/DrawGeomHatch.h
This PR implements a fix for a problem with rotated PAT hatch patterns on faces that are significantly wider than they are tall.  The problem was reported here: https://forum.freecad.org/viewtopic.php?t=91600
=> [TD]handle short&wide hatch area

src/Mod/Fem/femmesh/gmshtools.py, src/Mod/Fem/femmesh/netgentools.py, src/Mod/Fem/femtaskpanels/base_femmeshtaskpanel.py, src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py, src/Mod/Fem/femtaskpanels/task_mesh_netgen.py
@FEA-eng
This fixes #17594 and print the messages in real-time.
The meshing process is divided into two parts, one for preparation (run in its own thread) and one for meshing (run as a subprocess)
In the preparation phase the process cannot be stopped.
It can be noticeable in Gmsh if the process spends some time manipulating groups (for example using the shared project in https://github.com/FreeCAD/FreeCAD/issues/17427)
=> Fem: Print real-time log messages in mesher task panels - fixes #17594

src/Mod/BIM/ArchCommands.py, src/Mod/BIM/importers/importDAE.py, src/Mod/BIM/importers/importIFClegacy.py, src/Mod/BIM/importers/importOBJ.py
Fixes the excessive pruning of the export selection inside Arch.PruneIncluded. This was caused by the function not checking correctly for (Sub-)ShapeBinders when determining whether an object was a top level object or not, affecting the DAE exporter, and legacy IFC and OBJ exporters.
The fix includes adding a check for these object types, as well as enabling "strict" mode for PruneIncluded, which makes the pruning only take place if the parent object is also included in the selection. This latter aspect of the fix also makes these exporters able to export non-tip features, which brings it more inline with e.g. the stl exporter.
If pruning does still happen, the log-level for this event has been raised from "Log" (not shown by default) to "Warning" such that the user knows why their object …
=> Fix excessive selection pruning in dae exporter for PartDesign Objects (#17529)

src/Mod/PartDesign/Gui/ViewProviderBoolean.cpp, src/Mod/PartDesign/Gui/ViewProviderBoolean.h
Make sure that by default display mode is set to 'Flat Lines' instead of 'Group' as otherwise it won't show the result object
=> PD: Fix default display mode of ViewProviderBoolean

src/App/Application.cpp, src/App/PreCompiled.h
Using Qt's QCoreApplication::applicationPid() doesn't always give a unique ID so that multiple FreeCAD instances cannot be executed at the same time. This fixes #17678
=> Core: Generate a static random number in Application::applicationPid()

src/Mod/Draft/draftutils/todo.py
The doTasks function is called multiple times when using Draft tools. In some cases the ToDo.commitlist belonging to a previous call was not fuly processed, resulting in the same list being processed twice. To avoid this the list is stored as a local variable and then immediately reset.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=91832
=> Draft: avoid race condition in todo code

src/Mod/Part/App/FeaturePartFuse.cpp, src/Mod/Part/Gui/Command.cpp, tests/src/Mod/Part/App/FeaturePartFuse.cpp
fix #17468  recursively unpack compounds for boolean fuse
OCCT can boolean fuse multiple shapes in a compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
...
but FreeCAD wouldn't let it because it only checks the topmost layer
sadly multi-recursive compounds can be created from brep export+import …
=> Part: bugfix #17468 recursively unpack compounds for boolean fuse

src/Mod/Import/App/dxf/dxf.cpp
There is a missing "\n" and breaking the formatting in Report view
=> Update dxf.cpp with missing new line character

src/Mod/Measure/App/Measurement.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/17624
This is actually a small PR, appears big because it changed indentation of a large section.
Code explanation : 
Replace the way we find solid which was : 
```
if (strcmp((*subEl).c_str(), "") == 0) {
vols++;
}
```
Because empty subname is in fact not necessarily a solid (example Part::Line).
Instead we add a case for vols : 
```
case TopAbs_SOLID: {
vols++;
} break;
```
This enables stand-alone Part::Line to be detected correctly (which was why the bug happened only when the Part::Line was in a App::Part).
Remove  `|| names.back() == ""` from the if  in getShape which was wrong since it was forcing the shape to be the rootObj even if there was a subobject.
=> Measure: Fix quickmeasure problem with Part::Line objects

src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
another  small fix to the ui
current behaviour lets thread size and fit enabled when creating a new hole:
This shouldn't be enabled when the profile is None, so it should be like this on initialization:
To further confirm that is the expected behaviour you can select a thread profile and then select back none and you will see that both combo-boxes will be disabled now, further confirming that it's an initialization issue
=> fix(PD): initialization of thread class and fit

src/Gui/GraphvizView.cpp
- `-Granksep=2` lets increase the separation between groups (nodes), ideally should depend on graph size. **Sometimes a value of 2 is not enough.**
- `-Goutputorder=edgesfirst` lets place the edges first to allocate more space for them
- `-Gsplines=ortho` changes the edges from curves to straight, orthogonal lines
The current `dot` command uses default values, cause of this when you have medium/big projects the lines /edges) that connect the elements (nodes) overlap each other.
A while a go I mentioned some flags in https://github.com/FreeCAD/FreeCAD/issues/10207#issuecomment-1760205932 that works fine which lead us to this PR which is a simplification of that.
The only problem of using flags is that affect the entire graph. A better approach is to add properties in a subgraph basis …
=> DependencyGraph: Tweak dot flags to prevent overlaped edges

src/Gui/QuantitySpinBox.cpp, src/Gui/QuantitySpinBox.h
Fix https://github.com/FreeCAD/FreeCAD/issues/16810
The way the minimum size was defined, is that it set the value of the quantity to maximum. Then truncated the string to 18 characters. Then calculating the size.
This PR does 2 things : 
- Change truncate value from 18 to 12. Ensuring a more reasonable width.
- Refactor the code as sizeHint and minimumSizeHint were copy-pastes.
Example, minimum size of Placement dialog with 12 :
=> Core: QuantitySpinbox: Reduce minimum width.

src/Gui/Placement.ui
Placement dialog is extremely wide and invasive. The main reason being the size of the spinboxes (see https://github.com/FreeCAD/FreeCAD/issues/16810).
However there is also some unecessary ':' in the labels of groupboxes and of spinboxes. Cluttering unecessary the dialog and increasing a little the width.
=> Core: Remove unecessary ':' cluttering Placement.ui

src/Mod/BIM/ArchCurtainWall.py
Found regression when Sketch is used as Base and OverrideEdges is specified.
=> [ArchCurtainWall]  Bug-fix Sketch as Base

src/Mod/Import/App/dxf/dxf.cpp, src/Mod/Import/App/dxf/dxf.h
=> DXF: Change C++ DXF import to ignore type 999 (comment) records

src/Gui/PreferencePages/DlgSettingsNotificationArea.cpp
Fixes: #15187
Before:
_Notification width enabled_
After:
_Notification width disabled_
Not addressed:
- Improved grouping of settings in groupboxes
- Labels not being greyed out
- Unchecked `Enable non-intrusive notifications` checkbox should make its associated settings non-editable
=> Fix enabling/disabling notificationWidth

src/Mod/Part/Gui/Command.cpp
Replace _View --> Color per face_ with _Appearance per face_
Fixes #15327
I wouldn't change the command itself for now but the menu name is indeed inconsistent with the tool:
=> Replace inconsistent Color per face with Appearance per face

src/Gui/CommandDoc.cpp, src/Mod/Spreadsheet/Gui/Command.cpp
Adds hotkeys for Bold, Italic and Underline in Spreadsheet.
Ctrl+I was taken by File/Import... This patch remaps that to Ctrl+Shift+I.
=> Add Ctrl+{B,I,U} to Spreadsheet; remap File/Import

src/Gui/CommandStd.cpp
FreeCAD doesn't have a shortcut for Preferences.
As far as I know there is no established standard for Preferences. I chose Ctrl+, as that is used by a number of applications, like VS Code, nautilus and gedit.
=> Add shortcut: Ctrl+,: Preferences

src/Gui/BitmapFactory.cpp, src/Gui/BitmapFactory.h
No longer used since:
6ca8b2daae ("update hardcoded XPMs to .svg files. Updated .svg icons for clarity.", 2024-03-23)
=> Remove xpmMap from BitmapFactory

src/Mod/Draft/draftfunctions/svgtext.py
There was an unhandled svg text rotation when the text rotation axis was not standard, that defaulted to zero. With this PR that case is now properly handled
=> Draft: Implement unhandled svg text rotation

src/Mod/BIM/Resources/Arch.qrc, src/Mod/BIM/Resources/create_qrc.py, src/Mod/BIM/Resources/icons/IFC/IfcBeam.svg, src/Mod/BIM/Resources/icons/IFC/IfcBuilding.svg, src/Mod/BIM/Resources/icons/IFC/IfcBuildingStorey.svg, src/Mod/BIM/Resources/icons/IFC/IfcColumn.svg, src/Mod/BIM/Resources/icons/IFC/IfcCovering.svg, src/Mod/BIM/Resources/icons/IFC/IfcDoor.svg, src/Mod/BIM/Resources/icons/IFC/IfcFooting.svg, src/Mod/BIM/Resources/icons/IFC/IfcMember.svg, src/Mod/BIM/Resources/icons/IFC/IfcPile.svg, src/Mod/BIM/Resources/icons/IFC/IfcPlate.svg, src/Mod/BIM/Resources/icons/IFC/IfcRailing.svg, src/Mod/BIM/Resources/icons/IFC/IfcRamp.svg, src/Mod/BIM/Resources/icons/IFC/IfcRoof.svg, src/Mod/BIM/Resources/icons/IFC/IfcSite.svg, src/Mod/BIM/Resources/icons/IFC/IfcSlab.svg, src/Mod/BIM/Resources/icons/IFC/IfcStair.svg, src/Mod/BIM/Resources/icons/IFC/IfcWall.svg, src/Mod/BIM/Resources/icons/IFC/IfcWindow.svg, src/Mod/BIM/nativeifc/ifc_viewproviders.py
NativeIFC objects will now look for an icon matching their class before using the default one.
Fixes #14427
This should be merged after 1.0
=> BIM: Specific IFC icons

src/Base/Reader.cpp
This error was detected after loading a valid 0.21 file, making a modification to a fillet deep inside the model, close & saving the file and then reopening the same model. The model was quite complex at 119 objects and a size of 13.7Mb.
Original error and subsequent warnings:
```
11:15:03  Reading failed from embedded file: StringHasher.Table.txt (75249 bytes, 4129 bytes compressed)
11:15:03  <ElementMap> <string>(1): No hasherRef
11:15:03  <ElementMap> <string>(1): No hasherRef
11:15:03  <ElementMap> <string>(1): No hasherRef
11:15:04  <ElementMap> <string>(1): No hasherRef
11:15:04  <ElementMap> <string>(1): No hasherRef
```
=> [Base] [Post 1.0] Give constructive user feedback on failing to read StringHasherTable

src/Mod/Fem/Gui/Resources/ui/MeshGmsh.ui, src/Mod/Fem/Gui/Resources/ui/MeshNetgen.ui, src/Mod/Fem/femobjects/mesh_gmsh.py
* Minor changes in MeshGmsh task panel
* Currently if a mesh property is modified without regenerating the mesh, the object is left in a state of inconsistency between the property value and the existing mesh.  The reason behind the name change of the mesh property group is to implement (in the future) a mechanism so that it is reported when one of the mesh properties has been modified, requesting a recomputation of the mesh.
@FEA-eng
=> Fem: Minor change to MeshGmsh task panel and renaming mesh properties group

src/Gui/Workbench.cpp, src/Mod/Start/Gui/Manipulator.cpp
Moved items in the Help bar for V1.0. No text changes or translations needed. Based off discussion in DWG channel.
Separate PR for text changes (post V1.0?).
Currently draft status, looking for feedback. See images for comparison.
| Before (V1.0RC2) | After |
---------|-------
| ![Screenshot 2024-10-24 025109](https://github.com/user-attachments/assets/b2d6affe-6001-4222-89d5-d260d243682b) | ![Screenshot 2024-10-24 005817](https://github.com/user-attachments/assets/23256325-f9d4-4b3f-8c99-9621159aeeb0) |
=> Moved items in the Help menubar

src/Mod/Assembly/UtilsAssembly.py
As mentioned on https://github.com/FreeCAD/FreeCAD/issues/17198#issuecomment-2408418974
- Print the object name that triggers the error, so that the user can pinpoint the offending object
- Add missing newline character
- Makes the error description more concise
=> Reword error log to be more verbose

src/Gui/CommandStd.cpp, src/Gui/OnlineDocumentation.cpp, src/Mod/Start/Gui/Manipulator.cpp
Maybe post V1. Requires text translations. Makes status bar tips more clear. Based on feedback from DWG channel.
Draft status. Looking for more feedback and potentially more changes.
Does not include shifting items around. That is found in #17449.
| Before (V1.0RC2) | After |
|--------------------|-------|
| ![Screenshot 2024-10-24 005817](https://github.com/user-attachments/assets/b5c6741e-4eae-4aa3-9de3-c4b39ff899e3) | ![Screenshot 2024-10-24 034244](https://github.com/user-attachments/assets/f1234b7c-74ae-4325-9043-db7e630ee9ca) |
| Before (V1.0RC2) |
|--------------------|
| ![Help-Before](https://github.com/user-attachments/assets/f5ce777b-1514-4a52-aebd-1e9440471827) |
| After |
|-------|
| ![Help-After](https://github.com/user-attachments/assets/a0941fcc-1ff5-42f9-a891-39f4a19780b0) …
=> Modified text of all items on help menu

src/App/Document.cpp, src/App/private/DocumentP.h, src/Base/Reader.cpp, src/Base/Reader.h
Remove implementation details of the Document class from the XMLReader class. Instead keep an array of failed files and check them in the calling instance.
=> Core: Fix flaw in XMLReader class

src/Mod/AddonManager/addonmanager_package_details_controller.py, src/Mod/AddonManager/change_branch.py
Edit: want html tags to show branches on _italic_?
Fix #12969
=> Addon Manager: Show involved branches' names on branch change operation

src/Mod/AddonManager/Widgets/addonmanager_widget_package_details_view.py, src/Mod/AddonManager/addonmanager_metadata.py, src/Mod/AddonManager/addonmanager_package_details_controller.py
@maxwxyz, is this what you were thinking?
~~Draft because links are not opened.~~
As you can see translation is being reused.
Fix: #14777
=> Addon Manager: Show repository URL if it exists on the metadata

src/Mod/Spreadsheet/Gui/SpreadsheetDelegate.cpp, src/Mod/Spreadsheet/Gui/SpreadsheetDelegate.h
Qt handles resize to content on double clicking the separator in the header, by default. However this does not work in FreeCAD.
The reason why this doesn't work is due to the method `QStyledItemDelegate::sizeHint(...)` is overloaded to return an empty `QSize` in the class `SpreadsheetDelegate`. By returning a zero size, the cell sizes doesn't increase when double clicking the separator.
This can be tracked all the way back to the [initial commit of the spreadsheet module](https://github.com/FreeCAD/FreeCAD/commit/383ffa6e157f136128a390d82abcacc255102d79#diff-1d69e1ee7f42eff95fffdf9a5c7c8d18412254ccb4f5e71273387d7501923791R75).
There are no comments on why this was done, if this method was a place holder, meant to fix a bug somewhere or if the behavior was unwanted at the time.
I'm …
=> Spreadsheet: Double click separator/handle to resize column to content

src/Mod/Assembly/App/AssemblyObject.cpp, src/Mod/Assembly/App/AssemblyObject.h
Store DocumentObject instead of mbdPart for the dragged parts. Fixing the bug where doDragStep was 50% of time failing to find the correct DocumentObject due to bundling.
Fix https://github.com/FreeCAD/FreeCAD/issues/17694
=> Assembly: fix drag problem with fixed joints

cMake/FreeCAD_Helpers/InitializeFreeCADBuildOptions.cmake
cmake version is always greater than 3.4.3
The verification is done in the cmakefile in the root folder
=> [cmake]  clean InitializeFreeCADBuildOptions.cmake

src/App/ProjectFile.cpp, src/App/ProjectFile.h, src/Mod/Start/App/DisplayedFilesModel.cpp, src/Mod/Start/App/PreCompiled.h
It's basically a port of #10951 to the new start page implementation.
Note: Icon files are not removed but re-used instead.
The commit adds some new functions:
* getThumbnailsImage()
Returns the name of the PNG inside a project file
* getThumbnailsName()
Returns the directory name containing the image files
* getThumnailsParentDir()
Returns the parent directory of the directory containing the image files
* getThumbnailsDir()
Returns the path to the thumbnail directory. There is no need to always create a unique directory
after each restart because it doesn't harm if the thumbnail directoy contains deprecated files.
* createThumbnailsDir()
Creates the thumbnail directoy if it doesn't exist yet.
* getSha1Hash
Helper function to compute a SHA-1 hash of a given path. If the same path is …
=> Start: fixes #17857: Icon-files of the startup screen are not removed from /tmp

src/Mod/Assembly/CommandCreateBom.py
#16940
Add help message that file format customization can be done in the Spreadsheet Workbench settings.
=> Add help message about customizing BOM export file format in Assembly workbench

src/Gui/DlgAddPropertyVarSet.cpp
This commit removes superflous newline that disrupts the flow of the sentence displayed in the VarSet dialog. See https://github.com/FreeCAD/FreeCAD/issues/16776#issuecomment-2371188438
Fixes this dialog:
=> Gui: Remove newline from dialog string

src/Mod/Fem/App/FemMeshShapeNetgenObject.cpp
Fixes crash reported in #17814
=> Fem: Avoid legacy Netgen meshing if there is no referenced shape - fixes #17814

src/Mod/Draft/InitGui.py, src/Mod/Draft/draftutils/init_draft_statusbar.py
Fixes #16832.
In V1.0 the two Draft status bar widgets appear as checkboxes without label in the toolbar area context menu. They should not be listed in that menu, as was the case in V0.21. Their visibility is controlled via preferences.
Additionally, in case the Draft WB is only preloaded, the widgets would display in another workbench. This is prevented by using a delay.
=> Draft: avoid listing status bar widgets in toolbar area context menu

src/Mod/Draft/draftguitools/gui_stretch.py
Feature Improvement discussed at FreeCAD Forum :
- https://forum.freecad.org/viewtopic.php?t=92124#p792118  (Draft_Stretching the whole rectangle creates a new wire)
Currently, 3 cases in general, proposed PR improve Case 3 below :
1. The original object is a Rectangle, if after stretching it is no longer a rectangle, it makes a copy turning it into a Wire which reflect the result of stretching.
- Current behanviour is good for user, no change.
2. If after stretching it is still a rectangle, the code just resize the original.
- Current behanviour is good for user, no change.
3. **Now, if the user 'stretch' the whole rectangle, the code creates a copy as DWire in the 'stretched location'.**  
- *** **Users find this not intuitive, better just move the whole rectangle**.
=> [Draft Gui_Stretch] Improve Stretch Rectangle Behaviour

src/Mod/Sketcher/App/SketchObject.cpp, src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
Enable offset tool and transform tools to use external geometries as input
Fix https://github.com/FreeCAD/FreeCAD/issues/12461
Fix https://github.com/FreeCAD/FreeCAD/issues/17616
=> Sketcher: Offset & tranforms: enable external geos input.

src/Mod/Material/App/MaterialFilter.cpp, src/Mod/Material/App/MaterialFilter.h, src/Mod/Material/App/Materials.cpp, src/Mod/Material/App/Materials.h, src/Mod/Material/Gui/DlgMaterialImp.cpp, src/Mod/Part/App/PartFeature.cpp, src/Mod/Part/App/PartFeature.h
Add dynamic attributes to report the physical attributes of a part that are automatically recalculaated when the shape or material changes. These values are accessible from the part data display and as attributes within Python
=> Materials: Physical property attributes

src/Mod/BIM/ArchComponent.py
I have managed to trigger this a couple of times. Can't work out exactly how but seems clear.
```
Closing Sketch editpyException: Traceback (most recent call last):
File "/usr/lib64/freecad/Mod/BIM/ArchComponent.py", line 1646, in addSelection
FreeCADGui.activateWorkbench("ArchWorkbench")
<class 'KeyError'>: "No such workbench 'ArchWorkbench'"
```
=> BIM: Replace use of ArchWorkbench in ArchSelectionObserver

src/App/Application.cpp, src/App/FreeCADInit.py, src/Gui/FreeCADGuiInit.py
Closes https://github.com/FreeCAD/FreeCAD/issues/15710
As discussed in issue linked above, there's a need to easily disable addons for debugging.
This pull requests adds two possibilities to disable addons:
* By adding a command line argument `--disable-addon <addon>`
* And by creating a `ALL_ADDONS_DISABLED` file in the mod root of the addons to disable
The first one works in the same way as creating a stop file "DISABLE_ADDON", but from the command line. 
The second one expands on how stop files works, by allowing a whole parent directory to be stopped from loading.
Cavets:
* There are quite a lot of code duplication in the python files before the changegs, so I followed the same pattern. I've contained the bulk of the changes in a function (in both files) to make it easier to maintain …
=> Add options to disable addons

src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
It seems that Base has very handy helpers for converting between various types. This simplifies code of `ViewProviderAssembly::get/setDraggerPlacement` a lot.
@PaddleStroke You will be interested :)
This is for post 1.0.
=> Assembly: Refactor get/setDraggerPlacement

src/Mod/Mesh/App/WildMagic4/Wm4TRational.inl
Qt6 adds the `/permissive-` option to the MSVC++ command line, resulting in build failures due to WM4.  These changes bring the code into compliance and permit building for Windows with Qt6.
=> Fixes to Mesh: WildMagic4 to build on Windows MSVC++

src/Mod/Start/App/DisplayedFilesModel.cpp, src/Mod/Start/App/PreCompiled.h
as specified here: https://specifications.freedesktop.org/thumbnail-spec/0.8.0/
The changes are:
* use MD5 as hashing algorithm
* write thumbnails to ~/.cache/thumbnails/normal
=> Start: Implement Thumbnail Managing Standard

src/Gui/DlgPreferencePackManagementImp.cpp, src/Gui/PreferencePackManager.cpp, src/Gui/PreferencePackManager.h
Use paths passed with `--module-path` argument to search for preference packs
I'am [working](https://github.com/NixOS/nixpkgs/pull/347776) on process of introducing the "NIX-way" of configuration of freecad. I'am trying to introduce the `modules` configuration option which allows to pass the downloaded by nix modules to freecad in nix pure way. I'am using the `--module-path` argument for that. It works ok with python modules with `Init.py` fine out the box, but does not work with Preferences Packs, like OpenTheme. 
This patch adds loading Preferences Packs and temlates from paths passed by `--module-path` arguments.
=> Gui: take in account module-path argument

src/Gui/DlgPreferencePackManagementImp.cpp, src/Gui/DlgPreferencePackManagementImp.h, src/Gui/PreferencePackManager.cpp, src/Gui/PreferencePackManager.h
This PR does some code refactoring and reduces repetitive code.
* Add the method getSavedPreferencePacksPath()
* Add the method getResourcePreferencePacksPath()
* Move getPacksFromDirectory() from DlgPreferencePackManagementImp to PreferencePackManager to reduce imposing implementation details of PreferencePackManager
* Using the above new methods in DlgPreferencePackManagementImp fix another two unicode issues.
* Fix one more unicode issue in DlgPreferencePackManagementImp by calling Base::FileInfo::pathToString.
=> Gui: Refactor PreferencePackManager & DlgPreferencePackManagementImp

src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp, src/Mod/PartDesign/Gui/TaskDressUpParameters.h, src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
When loading a project it suffices to open the pad or pocket dialog to touch the document and mark it as modified even if the user cancels the dialog without changing anything.
=> PD: Avoid touching the document when opening pad or pocket dialog

src/Gui/CMakeLists.txt, src/Gui/Inventor/SoFCTransform.cpp, src/Gui/Inventor/SoFCTransform.h, src/Gui/SoFCDB.cpp, src/Gui/ViewProvider.cpp
In its doAction() method it only sets the model matrix if it's not the identity matrix. This improves the issue #7606
=> Core: Implement SoFCTransform node

src/Mod/BIM/ArchWall.py
Now, user can create :
-  Variant Layout / combination of ArchWall, CurtainWall, Slab based on same ArchSketch, with another PropertySet
-  Variant Properties / layer of ArchWall on same ArchSketch with different Width, Offset, Material, Height etc. to create Layers, Composite walls etc. (Layout, Layer, Combination, Composite, Elemented etc.)
FreeCAD Forum Discussion:
- https://forum.freecad.org/viewtopic.php?p=784622#p784622
- https://forum.freecad.org/viewtopic.php?p=785583#p785583
=> [ArchWall] Variant PropertrySet Support in ArchSketch

src/Mod/Draft/draftfunctions/split.py, src/Mod/Draft/draftguitools/gui_split.py
Fixes #16210.
Note that `Draft.format_object` is called from gui_split.py (in the commit). This is not consistent with other tools where this is handled in the `make_*` functions. In this case the new object is formatted twice. The 1st time by the `make_wire` code which (wrongly) applies the current default props.
=> Draft: Draft_Split: apply original view props to split off object

src/Mod/Draft/draftviewproviders/view_array.py
If `get_diffuse_color` returned a list with a single color, the list was wrongly multiplied. Regression introduced in V0.21, but in that version the error was masked by how Core handled the diffuse color.
Fixes #17052.
=> Draft: fix color of arrays

src/Gui/Macro.cpp
Recorded FC macros are always saved with the header line `# -*- coding: utf-8 -*`.
But the `QTextStream` class in Qt5 does not always use the utf-8 encoding for saving that macro file.
With this PR, the encoding will be set explicitly.
This explicit setting of the codec is also used in other places in the FreeCAD repo, e.g.:
https://github.com/FreeCAD/FreeCAD/blob/6f8abe880c07ad0d2d39122b7f697f78da60e1d9/src/Gui/AutoSaver.cpp#L152-L155
related discussion and problem description:
https://forum.freecad.org/viewtopic.php?t=92146
=> Gui: use utf-8 encoding for saving recorded macros

src/Gui/Document.cpp, src/Gui/Document.h, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/17948
Fix https://github.com/FreeCAD/FreeCAD/issues/16238
When you start editing a sketch from an assembly, it unset the assembly edit. Which is very annoying for assembly top-down design.
The proposed solution is to add the possibility for VP to ask for restore. If a VP does this, and is unset by another vp setting, then when this other vp unset, it set back the previous vp.
This has the advantage of also solving the same when user use the transform tool. After transform is finish the assembly is reactivated.
https://github.com/user-attachments/assets/be8431ed-0a6b-49c2-8e81-ab9721d0b960
@wwmayer please comment if this solution seems acceptable to you.
=> Core / Assembly: Add a way for vp edit modes to be restored.

src/Mod/Draft/DraftGui.py, src/Mod/Draft/draftguitools/gui_offset.py, src/Mod/Draft/draftguitools/gui_trimex.py
Fixes #16249.
The input did receive the focus, but the existing value was not selected.
The circle, arc, trim and offset tools had a related issue. The whole radius/distance value, including the unit string, was selected, instead of just the numerical portion.
=> Draft: fix focus behavior of radius input

src/Mod/TechDraw/App/Preferences.cpp, src/Mod/TechDraw/App/Preferences.h, src/Mod/TechDraw/Gui/AppTechDrawGuiPy.cpp, src/Mod/TechDraw/Gui/Command.cpp, src/Mod/TechDraw/Gui/CommandDecorate.cpp, src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui, src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvancedImp.cpp, src/Mod/TechDraw/Gui/MDIViewPage.cpp, src/Mod/TechDraw/Gui/MDIViewPage.h, src/Mod/TechDraw/Gui/PagePrinter.cpp, src/Mod/TechDraw/Gui/PagePrinter.h, src/Mod/TechDraw/Gui/ViewProviderPage.cpp, src/Mod/TechDraw/Gui/ViewProviderPage.h
This PR implements a fix for issue #16672.
Background
Issue #16672 is caused by use of stale pointer to switch to a closed/hidden tab in the Ui.
Similar problem affects static printAll function when it attempts to use a closed tab.
Known Issues to be solved
TechDraw: Insert view > Segfault #16672 
Replaces PR #17688
Corrects PR #17488
Solution
Remove print and context-switch behaviour with dependencies on MDIViewPage since it is not always available.
MDIViewPage will continue to handle tree selection, message dispatch and widget functions.
Access printing functions through the view provider, since it is always available when the gui is up and 
knows about the QGraphicsScene already.
Change context-switch behaviour to use standard show() method instead of manipulating the mdiview directly. …
=> [TD}Fix crash on no mdi (fix #16672)

src/Gui/BitmapFactory.cpp
Fixes #18213: Sketcher constraints have black box backgrounds
=> Gui: Do not ignore alpha channel when converting QImage to SoSFImage

src/Mod/BIM/OfflineRenderingUtils.py
Trying to run `OfflineRenderingUtils.getGuiData("./examples/BIMExample.FCStd")` on the example file fails with:
```trace
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[10], line 1
----> 1 OfflineRenderingUtils.getGuiData("./examples/BIMExample.FCStd")
File ~/micromamba/envs/jupytercad-freecad/Mod/BIM/OfflineRenderingUtils.py:223, in getGuiData(filename)
221 for propname in properties.keys():
222     if properties[propname]["type"] == "App::PropertyColorList":
--> 223         df = zdoc.open(guidata[key][propname]["value"])
224         buf = df.read()
225         df.close()
File ~/micromamba/envs/jupytercad-freecad/lib/python3.9/zipfile.py:1519, in ZipFile.open(self, name, mode, …
```
=> Fixing OfflineRenderingUtils.guidata on BIMExample.FCstd

src/Mod/Spreadsheet/Gui/Workbench.cpp
=> Spreadsheet: use 'text' instead of 'foreground' in tooltip

src/App/Property.h
Compare:
https://github.com/FreeCAD/FreeCAD/blob/ef2156d0f6d116b1642a5531a2d44fc6b7d17042/src/App/PropertyContainer.h#L53
=> App: Property.h correct comment for NoRecompute status

.github/stale_issues
Adding the actions/stale to help keep the GitHub repository organized and automatically identify/close stale issues.
Two actions to be implemented:
1. Check for issues without any feedback (comment) in the last **90 days** (confirmed bugs, high priority issues and feature requests are not touched by this) to check for relevance. 
This checks all issues but not the ones with the labels https://github.com/FreeCAD/FreeCAD/labels/Status%3A%20Confirmed, https://github.com/FreeCAD/FreeCAD/labels/Priority%3A%20High, https://github.com/FreeCAD/FreeCAD/labels/Priority%3A%20Critical, https://github.com/FreeCAD/FreeCAD/labels/Blocker, https://github.com/FreeCAD/FreeCAD/labels/Type%3A%20Feature
2. Check for issues where feedback was requested but no feedback was provided in the last **20 days**
This …
=> GitHub: add actions/stale to keep the GitHub backlog tidy

src/Mod/Sketcher/Gui/CommandSketcherTools.cpp, src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfHyperbola.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfParabola.h, src/Mod/Sketcher/Gui/DrawSketchHandlerLineSet.h
This removes `/**< enum value ----. */` comments left from probably auto-generated IDE enums.
=> Sketcher: remove auto-generated 'enum value' comments

src/Mod/Part/App/Geometry.cpp, src/Mod/Part/App/Geometry.h, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py, src/Mod/Sketcher/App/Constraint.cpp, src/Mod/Sketcher/App/Constraint.h, src/Mod/Sketcher/App/GeometryFacade.cpp, src/Mod/Sketcher/App/GeometryFacade.h, src/Mod/Sketcher/App/SketchObject.cpp, src/Mod/Sketcher/App/SketchObject.h, tests/src/Mod/Sketcher/App/SketchObject.cpp
Done as [a grant by the FPA](https://github.com/FreeCAD/FPA-grant-proposals/issues/6).
Adds some tests for `split` and `trim` functions in `SketchObject`, and refactors them. Plenty of changes are still needed after this, especially in `trim`: not all necessary tests are added, and the cognitive complexity is only reduced from 233 to 92. However, the many corner cases and constraint combinations in `trim` make this a significantly difficult task. The method has been almost completely rewritten, so this needs thorough testing.
=> [Sketcher] Round 1 of refactors

src/Mod/BIM/nativeifc/ifc_viewproviders.py
Cause of the Issue
In the setupContextMenu function (ifc_viewproviders.py), the QAction objects were being created without specifying the menu as their parent. Without an explicit parent, the actions were not correctly linked to the menu, which caused them to be omitted from the context menu.
Proposed Fix
Updated the setupContextMenu function to include the menu parameter as the parent for all QAction objects.
Ensured consistency across all action creation to avoid similar issues in the future.
=> Fix: Ensure IFC context menu actions are displayed correctly

src/Mod/Draft/importDXF.py
Fixes #16550.
Fixes #16552.
* Layer blocks receive a name with the "LayerBlock_" prefix.
* They are put in a layer if the "Use layer" import option is checked.
* If Draft or Sketch objects are created a Part_Compound instead of a Draft_Block is created. This was done because a Draft_Block does not claim its children. I am not sure about this change. Maybe the behavior of the Draft_Block should be changed instead.
@yorikvanhavre: do you know why a Draft_Block does not claim its children?
=> Draft: Legacy DXF importer: fix layer block behavior

src/Gui/PreferencePages/DlgSettingsDocument.ui
Default compression level was changed a year ago by [this commit](https://github.com/FreeCAD/FreeCAD/commit/f1a6a9e3a6ff61d716bc7f8415a0a7bb8e5456e5) but the text still says "default=3"
The following issue should be closed as "no compression" is already implemented and seem to be working. 
https://github.com/FreeCAD/FreeCAD/issues/9432
=> Fix incorrect displayed default compression level in preferences

src/Mod/Draft/draftguitools/gui_circulararray.py, src/Mod/Draft/draftguitools/gui_edit.py, src/Mod/Draft/draftguitools/gui_orthoarray.py, src/Mod/Draft/draftguitools/gui_points.py, src/Mod/Draft/draftguitools/gui_polararray.py, src/Mod/Draft/draftguitools/gui_snapper.py, src/Mod/Draft/drafttaskpanels/task_circulararray.py, src/Mod/Draft/drafttaskpanels/task_orthoarray.py, src/Mod/Draft/drafttaskpanels/task_polararray.py
Forum topic:
https://forum.freecad.org/viewtopic.php?p=794746#p794746
This PR (after the 2nd commit) also improves several issues reported in #17952. But the task panel of most commands (except Draft_Edit) stays open when the document is closed during a command.
=> Draft: Fix finish behavior of commands on doc close

src/Mod/Draft/draftmake/make_point.py
PR #12226 accidentally removed the handling of the color argument of the make_point function. My bad.
=> Draft: Fix make_point color regression

src/Mod/BIM/CMakeLists.txt, src/Mod/BIM/Resources/Arch.qrc, src/Mod/BIM/Resources/ui/dialogConvertType.ui, src/Mod/BIM/nativeifc/ifc_objects.py, src/Mod/BIM/nativeifc/ifc_tools.py, src/Mod/BIM/nativeifc/ifc_types.py, src/Mod/BIM/nativeifc/ifc_viewproviders.py
Support for [types](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcTypeProduct.htm) in NativeIFC:
* All IFC objects now have a `Type` property
* When expanding an IFC object, its types get loaded as a type object
* Type objects get gathered in a `Types` folder
* Right-clicking any IFC object allows to convert it into a type. That's currently the method to add a new type
* When converting an object to a type one can choose to keep the original object or not
=> BIM: NativeIFC: Support for types

src/Mod/Fem/femtools/checksanalysis.py
is --> are, matrinx --> matrix
=> FEM: Correct typos in error messages

src/Mod/Draft/draftguitools/gui_trimex.py
Fixes #14826.
If the point for the extrusion height is co-planar with the face, the normal of the face is used for the direction of the extrusion. The user can then enter a positive or negative value in the task panel. It is probably not the ideal solution, but better than what we have now I think.
=> Draft: allow point for Trimex extrusion to be co-planar with the face

src/Mod/PartDesign/Gui/Utils.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/17949
by reverting :
1 - https://github.com/FreeCAD/FreeCAD/commit/c09ef943f76a9693af6a045220070f685847e458 by @adrianinsaval
2 - https://github.com/FreeCAD/FreeCAD/commit/a3c4f4bb01f5201daf666852444a8f9c5adbda8d by @wwmayer
https://github.com/FreeCAD/FreeCAD/commit/c09ef943f76a9693af6a045220070f685847e458 was fixing a bug introduced by https://github.com/FreeCAD/FreeCAD/commit/a3c4f4bb01f5201daf666852444a8f9c5adbda8d which was fixing the bug https://github.com/FreeCAD/FreeCAD/issues/9538
However after reverting both commits, the issue https://github.com/FreeCAD/FreeCAD/issues/9538 cannot be reproduced anymore. So it must have been fixed by something else since.
=> PartDesign: revert c09ef94 and a3c4f4b to fix 17949

src/Mod/PartDesign/Gui/Workbench.cpp
Fix [#14144](https://github.com/FreeCAD/FreeCAD/issues/14144)
Right-click menu before and after:
=> Gui: Added SendToPythonConsole item in PartDesign tree view right-click menu.

src/Mod/Sketcher/Gui/Command.cpp
Now the order of sketches in sketch attaching tool is defined by when they were added into the list of documents. (no particular order) Sorting them alphabetically makes IMHO much easier to find a sketch by user, compared to current state, especially in large and complex projects with lot of sketches. Of cuser thix expects the user use sensible names for the sketches.
I have used plain `strcmp` which will not produce best results for non-ASCII characters. Hint to use better comparison function is wellcomed. I have avoided conversion to QString or more complex design for a start intentionally.
=> [PartDesign]: Sort sketches in Attach sketch tool alphabetically

src/App/DocumentObject.cpp, src/Gui/CommandDoc.cpp, src/Gui/CommandFeat.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
Fix #12829 
Ping @maxwxyz 
**a 'freezed' object now prevent the document to be saved.**
**linked objects are 'freezed' / 'unfreezed' when the state changes**
**Part_Chamfer create a new ('unfreezed') object, the nested Body is still 'freezed' and 'unfreezable'**
Also reproduceable with nested object which are frozen inside of a group (e.g. walls in an arch group)
**It acts on the object state not on a property. The object is not modified. Not sure it's needed**
**Can not reproduce**
**Fixed** 
Proposals: Exclude from recompute, Lock current state,
=> [Core] Fix for frozen status

src/Mod/Assembly/JointObject.py
Several additional issues have been identified in the Assembly functions migrationScript4 and migrationScript2, beyond those fixed in patch 71f0104bb2e88670f20b9889148999f8e684461a.
One common problem is that the Joint property Reference1 or Reference2 can be set to an invalid format. For example, user can manually cause this issue by assigning an incorrect reference (e.g., the Z-axis) to these properties via the FreeCAD GUI.  When this happens, internal errors (exceptions and their corresponding Python call stack) are reported in the Report View.  However, such information is not helpful for the user to fix their 3D model.
- Lack of Type Validation for Reference1 and Reference2:
The script does not check whether joint.Reference1[1] or joint.Reference2[1] is a sequence. If this condition …
=> Assembly: migrationScript2 and migrationScript4 improved and refactored

src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femresult/resulttools.py
fixes #13889 - quite annoying issue where one cannot easily delete all the results because pipelines and their filters are not affected by the ResultsPurge tool
=> FEM: ResultsPurge - delete all results objects including pipelines and filters

src/Mod/PartDesign/App/ShapeBinder.cpp
'Copy on change' properties propagated to SubShapeBinder can be changed there and then updated in the base body (support). But they also might be used as a variable in calculation of some other 'copy on change' properties of the base body which are propagated to the same SubShapeBinder as well. It is expected to see all the 'copy on change' properties in the SubShapeBinder recalculated based on the modified values of propagated properties and using the expressions defined in the base (support) body.
Here's an example project (seems I can't attach "*.FCStd" file, will describe it here thoroughly).
It contains **Body1** with three user-defined properties: ***Base_Depth*** (set to 200 mm), ***Base_Width*** (with expression `= Base_Depth * 3`) and ***Base_Thickness*** (with expression …
=> Apply result of calculations with copy on change properties

src/Mod/Material/Gui/MaterialTreeWidget.cpp
=> Materials: Check if m_uuid is empty before adding to recents

src/Mod/Fem/App/FemPostPipeline.cpp, src/Mod/Fem/App/FemPostPipeline.h, src/Mod/Fem/Gui/Command.cpp, src/Mod/Fem/Gui/TaskPostBoxes.cpp
The pipeline object should inherit directly from the FemPostObject class, not from FemPostFilter.
In fact, the Input property inherited from FemPostFilter is never used for pipelines.
=> Fem: Fix FemPostPipeline base class

src/Mod/BIM/ArchBuildingPart.py, src/Mod/BIM/ArchComponent.py
* Switched Component code to new Comp=True version of code.
* Made the Placement code in both files identical. This also solves that rotating a BuildingPart was not propagated to children.
=> BIM: Improve onChanged Placement code

src/Mod/BIM/ArchStructure.py
[ Similar to https://github.com/FreeCAD/FreeCAD/pull/18057 ]
Now, user can create :
- Variant Layout / combination of ArchStructure (Slab) in addition to ArchWall and CurtainWall based on same ArchSketch, with another PropertySet
- Variant Properties / layer of ArchWall on same ArchSketch with different Width, Offset, Material, Height etc. to create Layers, Composite walls etc. (Layout, Layer, Combination, Composite, Elemented etc.)
FreeCAD Forum Discussion:
- https://forum.freecad.org/viewtopic.php?t=87721&start=130#p794785
=> [ArchStructure] Variant PropertrySet Support in ArchSketch

src/Mod/TechDraw/App/Preferences.cpp, src/Mod/TechDraw/App/Preferences.h, src/Mod/TechDraw/App/ShapeExtractor.cpp, src/Mod/TechDraw/App/ShapeExtractor.h, src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui, src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvancedImp.cpp
This PR implements a tool for support and debugging.  The HLR algo does not handle geometry errors well which leads to failures and/or incorrect results.   Finding the offending source object can be time consuming.  This PR provides an option to pass each source shape through BRepCheck_Analyzer with the offending shape(s) identified, but not passed to further processing.  Optionally the brep of the offending shape is saved.
=> [TD]add shape validation tool for debugging

src/Gui/Tree.cpp
This adds a `DynamicQLineEdit` dynamic class for the model Tree so that the edit field can grow with what is being typed during renaming. This fixes #17747 .
https://github.com/user-attachments/assets/615bcedf-70ba-4437-a2b3-51b77f897d21
I am not sure if this merits an new class or if it should have been added to `ExpLineEdit`.  (I didn't want to disturb the existing class).
=> Gui: allow LineEdit to grow with text - fixes #17747

src/Mod/TechDraw/Gui/QGIViewPart.cpp
This PR implements a fix for issue #18050.
=> [TD]fix #18050 hidden line color

src/Mod/PartDesign/Gui/Workbench.cpp, src/Mod/PartDesign/InitGui.py, src/Mod/PartDesign/InvoluteGearFeature.py, src/Mod/PartDesign/SprocketFeature.py
Every time the InvoluteGearFeature python module was imported, and we're in GUI context, the command "PartDesign_InvoluteGear" was registered. On the 2nd (3rd, ...) time, this was reported as an error in the console, like "error: Command.cpp(1841): duplicate command PartDesign_InvoluteGear"
The first import happens when the PartDesign FreeCAD Module is loaded, via `InitGui.py`. Subsequent imports may happen when e.g. executing the involute gear command or when running it's tests via FC's Test WB.
This change now registers the command only then the PartDesign WB is set up in InitGui, not when importing the python module. The same fix is applied for sprocket, where the same pattern for command registration was used.
In addition, the import error catch was removed, which seems to be a copy …
=> PD: Fix error "duplicate command PartDesign_InvoluteGear"

src/Mod/Part/App/PartFeature.cpp, src/Mod/Part/App/TopoShape.h, src/Mod/Part/App/TopoShapeExpansion.cpp, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
If we're about to tag a reference with a ? missing prefix, look to see if the plane of the referenced element matches one and only one plane of the elements in the shape.  If so, substitute the name of that element into the reference.
Also roughed out to work with edges ( like you would find in a sketch external reference ), but only if they are completely unchanged.  A future version of the code can explore if collinear edges should be supported, which would tend to match the user expectation.  But we need a collinear utility method first.
This should address the common remaining TNPs arising from edge changes in a sketch.
This needs a good amount of human testing.
=> Toponaming: Add a plane matching based heuristic to TNP mitigation

src/Mod/Assembly/JointObject.py
This adapts the UI after connection all of the properties, fixing #17964, #17797 and #18163 where the radius were zero for gears but displayed 1 in the GUI.
Also fixes #17798 where  reversed / non revered checkbox was not updated and editing existing joint.
Edit  : found another issue that should be resolved
@PaddleStroke for review ?
=> Assembly: fix gears created with null radius and de-sync

src/Mod/BIM/ArchAxis.py, src/Mod/BIM/ArchSectionPlane.py, src/Mod/BIM/CMakeLists.txt, src/Mod/BIM/bimcommands/BimSectionPlane.py, src/Mod/BIM/bimcommands/BimTDView.py, src/Mod/BIM/importers/exportIFC.py, src/Mod/BIM/importers/importIFCHelper.py, src/Mod/BIM/nativeifc/ifc_export.py, src/Mod/BIM/nativeifc/ifc_generator.py, src/Mod/BIM/nativeifc/ifc_objects.py, src/Mod/BIM/nativeifc/ifc_status.py, src/Mod/BIM/nativeifc/ifc_tools.py, src/Mod/Draft/draftfunctions/svg.py, src/Mod/Draft/draftobjects/shape2dview.py
This is support for 2D objects in NativeIFC. Corresponds to item 6.A from https://github.com/yorikvanhavre/FreeCAD-NativeIFC/blob/main/doc/roadmap2024.md
With this, one is now able to embed 2D objects (linework, texts, dimensions) inside IFC files, as well as handle such entities produced by other BIM apps (Basically BlenderBIM/Bonsai), and define "Drawings", which are basically a section plane inside a group, which can contain other 2D entities too that compose the drawing.
One can now create groups inside IFC documents and place section planes inside, and these are interpreted correctly by BlenderBIM/Bonsai too.
=> BIM: NativeIFC 2D support

src/Mod/BIM/bimcommands/BimTutorial.py
Loading the images into the BIM tutorial is still broken. This patch fixes this issue.
=> fixed loading of bim tutorial images

src/Mod/Part/App/AppPartPy.cpp, src/Mod/Part/App/TopoShapeExpansion.cpp
Type 'struct EdgePoints' violates the C++ One Definition Rule because it's defined in two different translation units
=> Part: Fix compiler warnings [-Wodr]

src/Gui/3Dconnexion/navlib/NavlibInterface.h, src/Gui/3Dconnexion/navlib/NavlibNavigation.cpp, src/Gui/3Dconnexion/navlib/NavlibPivot.cpp
Hello,
The following changes address some issues with the new integration, which were recently found:
- Fixed an crash occuring if QuickZoom is used on geometry clipped by the view volume,
- Fixed a bug causing an center of rotation stop updating it's position in ortho view,
- Fixed QuickZoom for high DPI screens (support for variable scaling)
=> Update for 3Dconnexion NavLib integration

src/Mod/Sketcher/App/SketchObjectPy.xml, src/Mod/Sketcher/App/SketchObjectPyImp.cpp
* The syntax of type hints in Python is 'argument name: argument type'.
For more details see: https://docs.python.org/3/library/typing.html
* Use PyArg_ParseTuple's support of optional arguments than doing it with several calls of PyArg_ParseTuple
with different arguments.
This is error-prone, leads to convoluted code logic and may even fail because once the error indicator is set
PyArg_ParseTuple may unexpectedly fail.
=> Fix SketchObjectPy::addExternal

src/Gui/Action.cpp, src/Gui/Application.h, src/Gui/CommandDoc.cpp, src/Gui/CommandFeat.cpp, src/Gui/CommandLink.cpp, src/Gui/CommandMacro.cpp, src/Gui/CommandStd.cpp, src/Gui/CommandView.cpp, src/Gui/CommandWindow.cpp, src/Gui/DocumentRecovery.cpp, src/Gui/OnlineDocumentation.cpp, src/Gui/Workbench.cpp, src/Mod/Material/Gui/Command.cpp, src/Mod/Part/Gui/Command.cpp, src/Mod/PartDesign/Gui/CommandBody.cpp, src/Mod/Spreadsheet/Gui/Command.cpp, src/Mod/Start/Gui/Manipulator.cpp
I use menu accelerators fairly often, so I find it very frustrating when they are missing, or worse, they don't work due to the same letter being assigned to several commands.
I don't mind making a patch like this fixing lots of them, and more to come... but I worry about the impact of this on UI translations.
Do we have a way to update them so that translations don't break? Or should I just not touch the .cpp files at all and instead fix the accelerators in the English translation files, leaving the mistakes frozen forever in the C++ strings?
=> Fix and add menu accelerators

src/Mod/Part/App/TopoShapeExpansion.cpp, src/Mod/PartDesign/PartDesignTests/TestTopologicalNamingProblem.py
This is parity change with LS3: https://github.com/realthunder/FreeCAD/blob/a9810d509a6f112b5ac03d4d4831b67e6bffd5b7/src/Mod/Part/App/TopoShapeEx.cpp#L3357
I don't know if this fixes any existing issue, but without it faces joined by refine are wrongly marked as generated. 
Change is extracted from https://github.com/FreeCAD/FreeCAD/pull/17249#issuecomment-2412988261
=> TopoNaming: Refine - mark joined faces as modified not generated

src/Mod/Fem/Gui/DlgSettingsFemCcx.ui, src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py
Fixes #18339
Set preference value to zero to automatically use the maximum number of available cores.
@FEA-eng
=> Fem: Make it possible to run CalculiX with one core - fixes #18339

src/Mod/Spreadsheet/Gui/CMakeLists.txt, src/Mod/Spreadsheet/Gui/DlgSettings.ui, src/Mod/Spreadsheet/Gui/DlgSettingsImp.cpp, src/Mod/Spreadsheet/Gui/Sheet.ui, src/Mod/Spreadsheet/Gui/SheetTableView.cpp, src/Mod/Spreadsheet/Gui/SheetTableView.h, src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp, src/Mod/Spreadsheet/Gui/ZoomableView.cpp, src/Mod/Spreadsheet/Gui/ZoomableView.h
This commit implements zoom in _Spreadsheet WB_, making it look like any other spreadsheet editor. So far, the code looks like a dirty hack; to make it beautiful one needs huge amount of efforts, I estimate it at one month of work.
In the meantime, this is a patch. The commit creates a _QGraphicsView_ descendant and shows the table in viewport. _QGraphicsView_ allows magnification and animation, the latter can be added in the future. The commit adds an option for default zoom in settings.
The following items have to be considered by testers:
- I don't have an opportunity to test the commit on _Windows_ and _MacOS_. So far, I have tried it on _KUbuntu 22.04.4 LTS (Jammy Jellyfish)_ with _Qt 5.15.14_ and _Qt 6.7.2_.
- I don't have an opportunity to check the behavior with …
=> [Spreadsheet] Enable zoom in Spreadsheet

src/App/Application.cpp, src/App/Application.h, src/App/Document.cpp, src/App/Document.h, src/App/DocumentObject.cpp, src/App/DocumentObject.h, src/App/DynamicProperty.cpp, src/App/DynamicProperty.h, src/App/Extension.cpp, src/App/Extension.h, src/App/ExtensionContainer.cpp, src/App/ExtensionContainer.h, src/App/PropertyContainer.cpp, src/App/PropertyContainer.h, src/App/PropertyStandard.cpp, src/App/private/DocumentP.h, src/Base/Reader.cpp, src/Base/Reader.h, src/Base/Tools.cpp, src/Base/Tools.h, src/Base/Writer.cpp, src/Base/Writer.h, src/Gui/Document.cpp, src/Gui/ViewProviderLink.cpp, src/Gui/ViewProviderLink.h, src/Mod/Spreadsheet/App/Sheet.cpp, src/Mod/Spreadsheet/App/Sheet.h, tests/src/Base/Tools.cpp
As described in #16849, the existing Tools::getUniqueName method requires calling code to form a vector of existing names to be avoided.
This leads to poor performance both in the O(n) cost of building such a vector and also getUniqueName's O(n) algorithm for actually generating the unique name (where 'n' is the number of pre-existing names).
This has particularly noticeable cost in documents with large numbers of DocumentObjects because generating both Names and Labels for each new object incurs this cost. During an operation such as importing this results in an O(n^2) time spent generating names.
The other major cost is in the saving of the temporary backup file, which uses name generation for the "files" embedded in the Zip file. Documents can easily need several such "files" for each …
=> Address the poor performance of the existing unique-name generation

src/Gui/Tree.cpp
Currently setting the tree font size only applies to that current session even though it is written to the user.cfg. this PR loads the setting on initialization.
Fixes https://github.com/FreeCAD/FreeCAD-Bundle/issues/343
IMHO this should be backported to the 1.0 branch.
=> [Gui] Tree, set FontSize on start of application

src/Base/CMakeLists.txt, src/Base/ServiceProvider.cpp, src/Base/ServiceProvider.h, tests/src/Base/CMakeLists.txt, tests/src/Base/ServiceProvider.cpp
This PR introduces the concept of `Services` (if you have a better name - please go ahead and suggest one!). `Services` are meant to be small, well-defined interfaces that provide some functionality.
This is intended to be used for inter-module communication. Modules can specify service interfaces that are then implemented by other modules. This way, we can use features from, for example, the Part module in Core without relying on the Part module explicitly.
Base does provide Service interface  – which is basically an abstract class with pure virtual methods. This service then can be implemented in other modules and accessed at runtime via the `ServiceProvider` class that stores all implementations.
`ServiceProvider` does store multiple implementations so, in theory, it is possible to use …
=> Base: Add Services and ServiceProvider

src/Mod/Sketcher/App/planegcs/Geo.cpp
There is an underflow of an unsigned int in the calling instance that sets the parameter 'p' to 2**32-1. But the size of the passed vector is 0. To fix the crash first check if p is less then the size of the vector.
See: https://forum.freecad.org/viewtopic.php?t=92815
=> Sketch: Fix possible crash in BSpline::splineValue

src/Mod/CAM/App/Area.cpp, src/Mod/CAM/Gui/Resources/panels/PageOpProfileFullEdit.ui, src/Mod/CAM/Path/Op/Gui/Profile.py, src/Mod/CAM/Path/Op/Profile.py
Implementation of #16623, multi-pass support for profile operations. [Forum link](https://forum.freecad.org/viewtopic.php?t=90247)
I was surprised to discover that the C++ back end for this feature largely already exists. Specifically, there are already area offset parameters "Stepover" and "ExtraPasses", and an implementation for generating extra passes based on those values. As best I can tell, these features are unused before this PR.
As [dimitrios2 mentioned](https://forum.freecad.org/viewtopic.php?p=780268#p780268), profile operations handle open and closed paths separately, so this PR makes changes to implement the feature in both pipelines.
This screenshot shows the feature in action. Of note:
- In the left panel, there are new options "Number of Passes" and "Pass Stepover" in the …
=> [CAM] implement multipass profile operations

src/Mod/BIM/nativeifc/ifc_viewproviders.py
NativeIFC objects shape would not load when ShapeType is None
Fixes #18391
=> BIM: Fixed shape loading

src/Mod/Sketcher/Gui/DrawSketchHandlerLineSet.h
This fixes #13939 where two right mouse buttons were needed to exit the polyline tool after the creation of a closed shape.
=> Sketcher: Fix double RMB to quit polyline after closed shape

.clang-tidy
As discussed in the PR Review Meeting this morning, this removes the `readability-identifier-length` automated check, which creates more noise than it is worth. We plan to instead rely on code reviewers to encourage good variable naming, which will often (though not always) include using longer names.
=> CI: Remove readability-identifier-length check

cMake/FreeCAD_Helpers/InitializeFreeCADBuildOptions.cmake
FLANN_INCLUDE_DIRS was added in:
58a7be992b ("Intergrate Werners PCL Triangulation patch and upgrade it to PCL 1.7", 2014-08-26)
cMake/UseLibPack10x.cmake was removed in:
e0220e7830 ("Remove unused cMakes", 2022-02-22)
---
As far as I can see there is no current use of FLANN - but please be sure!
=> Remove mentions of FLANN

src/Gui/View3DInventor.cpp
Windows.h defines 'near' and 'far' macros, and they are actually used in the Inventor codebase (so we can't just undefine them).
=> Gui: Rename variable to eliminate macro conflict

src/App/Datums.cpp
The encoding was not UTF-8, so Stefan Tröger was mis-rendered in some editors (and the compiler complained).
=> App: Fix encoding of Datums.cpp

cMake/FreeCAD_Helpers/InitializeFreeCADBuildOptions.cmake
As per comment on https://github.com/FreeCAD/FreeCAD/issues/13676#issuecomment-2539978468 and https://github.com/FreeCAD/FreeCAD/issues/13676#issuecomment-2541325750
In summary, the Debian package version of zipios++ seems to contain a bug when used in FreeCAD to write thumbnails. For Debian packages, this change enables building the zipios sources bundled with FreeCAD.
The snap package has been fixed via https://github.com/FreeCAD/FreeCAD-snap/pull/139 and has been tested to work.
Fixes https://github.com/FreeCAD/FreeCAD/issues/13676
=> Disable external zipios usage for Debian builds

src/Mod/BIM/ArchReference.py
Due to TNP code Document.xml can contain (for example)` <Part ElementMap="0.4" file="Box001.Shape.brp"/>` instead of `<Part file="Box001.Shape.brp"/>`.
=> BIM: Fix ArchReference problem caused by TNP code

src/Mod/Fem/App/AppFem.cpp, src/Mod/Fem/App/FemPostFilter.cpp, src/Mod/Fem/App/FemPostFilter.h, src/Mod/Fem/Gui/TaskPostBoxes.cpp, src/Mod/Fem/Gui/TaskPostBoxes.h, src/Mod/Fem/Gui/TaskPostContours.ui
Add an optional Laplacian smoothing filter to the contour filter, to get a smoother result when the generated isosurfaces are too coarse.
Below are two example images with filter disabled and filter enabled, respectively.
@FEA-eng
=> Fem: Add smoothing filter extension to contours filter

src/Mod/PartDesign/App/FeatureHole.cpp, src/Mod/PartDesign/PartDesignTests/TestHole.py, src/Mod/Sketcher/SketcherTests/TestSketcherSolver.py
related to #17124
During the import of the Toponaming code, the call to `FeatureAddSub::refineShapeIfActive()` in `PartDesign::Hole::execute()` was accidentally removed as it isn't present in https://github.com/realthunder/FreeCAD/blob/a9810d509a6f112b5ac03d4d4831b67e6bffd5b7/src/Mod/PartDesign/App/FeatureHole.cpp#L1971 but was present in https://github.com/FreeCAD/FreeCAD/blob/b9bfa5c5507506e4515816414cd27f4851d00489/src/Mod/PartDesign/App/FeatureHole.cpp#L1901
Acorrding to https://github.com/FreeCAD/FreeCAD/issues/17124#issuecomment-2517662019 this modification helps fixing one of the case files of that issue, together with other code imported from LS3 that will be added in a future PR.
Regardless for that, as for my https://github.com/FreeCAD/FreeCAD/issues/17124#issuecomment-2525716196 …
=> [PartDesign] Hole: restore missing call to FeatureAddSub::refineShapeIfActive()

src/Mod/AddonManager/Addon.py, src/Mod/AddonManager/AddonManagerTest/data/depends_on_all_workbenches.xml
Update name that Addon authors can use to assert a dependency on an internal WB.
=> Addon Manager: Arch->BIM in list of known internal WBs

src/Mod/TechDraw/Gui/PagePrinter.cpp, src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
This PR implements a fix for #18443.  It also restores the use of PDF/A-1b format for pdf in TechDraw which was removed due to issues in Qt which now appear to be fixed,
=> [TD]Fix transparent area in pdf (fix #18443)

src/Mod/AddonManager/AddonManager.py, src/Mod/AddonManager/AddonManagerTest/app/test_utilities.py, src/Mod/AddonManager/AddonManagerTest/gui/gui_mocks.py, src/Mod/AddonManager/AddonManagerTest/gui/test_python_deps_gui.py, src/Mod/AddonManager/CMakeLists.txt, src/Mod/AddonManager/addonmanager_freecad_interface.py, src/Mod/AddonManager/addonmanager_python_deps_gui.py, src/Mod/AddonManager/addonmanager_utilities.py
Two refactorings and a bug fix:
1) `communicate()` has to be called after a final `kill()` to get the output. Also adds unit tests for the function. Related to #18380.
2) Renames and starts a refactoring/testing pass on the Python dependencies GUI. This needs considerably more refactoring, but this is a start.
=> Addon Manager: Correct run_interruptable_subprocess

src/Mod/Sketcher/App/SketchObject.cpp, src/Mod/Sketcher/App/SketchObject.h
Keep code almost 1:1 with LS3 branch, just ensure the variable is initialized and code is documented
Follow-up for #16337
=> Sketcher: clean-up geometry history configuation

src/Mod/Part/App/PartFeature.cpp
Calling ShapeType() on a null shape is not allowed and causes a segmentation fault. So, check beforehand if the shape is not null.
Fixes #18537
=> Part: Fix segmentation fault in Feature::getExportElementName

src/Mod/TechDraw/Gui/QGIViewDimension.cpp
When `TolSizeAdjust` user preference set to small value, font size could be rounded down to zero flooding log with thousands
```
QFont::setPixelSize: Pixel size <= 0 (0)
```
so set minimal font height to 1.
=> TechDraw: Ensure tolerance font size is > 0

src/Base/Placement.cpp
The recent placement toString function had a fmt formating issue, which is making build failing on some machines. (cf https://forum.freecad.org/viewtopic.php?p=798145#p798145)
@chennes we probably want to get this in as soon as possible since it's breaking build.
=> Placement::tostring Fix fmt expression

pixi.toml
Windows requires running from an installed FreeCAD, not simply the build environment.  This commit performs the install and execution from the installation environment.
=> pixi: Add run freecad configuration for Windows.

src/Mod/BIM/ArchSite.py, src/Mod/BIM/nativeifc/ifc_diff.py, src/Mod/BIM/nativeifc/ifc_export.py, src/Mod/BIM/nativeifc/ifc_status.py, src/Mod/BIM/nativeifc/ifc_tools.py
Fixes #17862
The main problem was actually just a stupid radians/degrees conversion...
Also fixed export units and other small details.
Introduces also an alternative conversion method that writes the IFC contents to a temp file then reloads it, but that methods ended up not useful anymore (it's also way slower) and is not used by current code. But I kept it as it can be useful for debugging at some point...
=> BIM: Several fixes to nativeIFC lock/unlock system

src/App/PropertyUnits.cpp, src/App/PropertyUnits.h, src/Mod/Material/App/MaterialLoader.cpp, src/Mod/Material/App/MaterialValue.cpp, src/Mod/Material/App/MaterialValue.h, src/Mod/Material/App/Materials.cpp, src/Mod/Material/App/Materials.h, src/Mod/Material/Gui/ArrayModel.cpp, src/Mod/Material/materialtests/TestMaterialCreation.py, src/Mod/Material/materialtests/TestMaterials.py, src/Mod/Part/App/PartFeature.cpp, tests/src/Mod/Material/App/TestMaterials.cpp
The default display type of quantity objects is fixed point resulting in insufficient accuracy when changing unit systems, or when the values are small. This fix changes the default format from 'Fixed' to the more apt 'Default' format. This allows the displayed values to scale as appropriate.
Fixes #18149
=> Materials: Change display of Quantity values

src/Mod/Assembly/JointObject.py
Assembly: Joint creation presolve: move part2 rather than part1 when both are unconnected.
Fix https://github.com/FreeCAD/FreeCAD/issues/18369
=> Assembly: Joint creation presolve: fix #18369

src/Mod/Fem/App/AppFemPy.cpp, src/Mod/Fem/App/FemMesh.cpp, src/Mod/Fem/App/FemMesh.h, src/Mod/Fem/App/FemVTKTools.cpp, src/Mod/Fem/App/FemVTKTools.h, src/Mod/Fem/Gui/DlgSettingsFemInOutVtk.ui, src/Mod/Fem/Gui/DlgSettingsFemInOutVtkImp.cpp, src/Mod/Fem/Gui/DlgSettingsFemInOutVtkImp.h
If a Fem mesh is exported to vtk file formats, only the highest dimensional elements will be exported.
For example:
Create a Fem mesh containing edge, face and volume elements.
Export the object to .vtu mesh format.
Import the object back as a Fem mesh -> Edge and face elements are lost.
@FEA-eng
=> Fem: Fix mesh export to vtk formats

src/Gui/Application.cpp, src/Gui/Application.h, src/Gui/ApplicationPy.cpp, src/Gui/ApplicationPy.h
This reduces build time when adding new Python functions because only one file must be compiled. Handles also many linter warnings.
=> Gui: Move Python functions from Application to ApplicationPy

src/Gui/Application.cpp, src/Gui/StartupProcess.cpp
[Qt 6.7.3 changed default based on platform](https://github.com/qt/qtbase/commit/a2aa1f81a81) which made macOS hide all icons. This as Apple's guidelines says that menus shouldn't include icons.
We already set this attribute (`AA_DontShowMenuIcons`) to `false` in bootup, but this is reset when application is loaded as Qt sets it in [init_platform](https://github.com/qt/qtbase/commit/a2aa1f81a81#diff-6ce1c6c83aa4b5db78a6748c8a9eec19620a10a2e2a495fd9053fdf391a9863aR1360). To fix this, I've moved the old workaround for linux from `StartupProcess::setupApplication()` to `Application::runApplication()`.
=> Show menu icons on macOS on Qt6.7.3+

src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
ThreadSize can be enabled when Threaded and when not threaded(clearance hole)
=> fix(PD): size should be enabled if profile is not none

src/Mod/Part/App/MeasureInfo.h, src/Mod/TechDraw/App/DimensionAutoCorrect.cpp, src/Mod/TechDraw/App/DimensionAutoCorrect.h
While preparing the Debian package update, while doing copyright review I've found those three  SPDX headers not aligning to the code.
This MR fixes the SPDX headers, assuming the license comment block  is authoritative.
(@WandererFan FYI)
=> Fix SPDX Identifier to match license

PRIVACY_POLICY.md
Small formatting cleanup (whitespaces, italic for reference instead of list bullet) of the Privacy Policy, accessible from the menu Help > About FreeCAD > Privacy Policy.
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
=> GUI: cleanup Privacy Policy formatting

src/Mod/BIM/Resources/ui/preferences-sh3d-import.ui, src/Mod/BIM/TestArch.py, src/Mod/BIM/importers/importSH3DHelper.py
As suggested in https://github.com/FreeCAD/FreeCAD/pull/17165#issuecomment-2551291883 the IFC project created by default during import is not used in BIM and only make sense when working with IFC files.
This PR aims to remove that element, while letting the user import it if he/she so wishes.
=> SH3DImporter: Removing IFC project by default

src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
Fixes small typos in the Advanced tab of the TD Preferences (tooltips).
=> Fix typos in TechDraw advanced preferences - tooltips

src/Gui/PreferencePages/DlgSettingsEditor.ui, src/Gui/PythonConsole.cpp, src/Gui/PythonConsole.h, src/Gui/PythonEditor.cpp, src/Gui/PythonEditor.h, src/Gui/TextEdit.cpp, src/Gui/TextEdit.h
Since migrating to python3, which does not tolerate mixing spaces and tabs, the default should now be set to convert tabs into spaces for this editor.
=> [PythonEditor] Make converting tabs to spaces the default

src/Mod/Spreadsheet/App/PropertySheet.cpp, tests/src/Mod/Spreadsheet/App/PropertySheet.cpp
Alias validation was broken in one of my previous PR's.  This fixes the issue introduced in https://github.com/FreeCAD/FreeCAD/pull/17315
Incorrectly, I previously thought the re matching was only looking for valid address strings, but it was also looking for invalid characters, such as spaces or quote characters in the alias name.  The relevant re search was moved back into isValidAlias().
I also added an alias named with spaces and another with a leading single quote character to the unit tests.  I am not entirely sure these tests are actually being run. @chennes can you have a look?  I tried adding one of the invalid names to the valid names list, but it did not trigger the expected test failure.  Instead, all tests passed when that one should have failed.  Method to run was from the …
=> [Spreadsheet] fix isValidAlias()

src/Gui/Tree.cpp
In older versions it was possible to copy elements with drag and drop by holding the CTRL key. Since v0.20 or v0.21 this wasn't possible any more so that elements are always moved.
Note: Copying is only allowed for elements that have a parent object.
=> Gui: Fix copying elements in the tree view by holding CTRL key

.clang-tidy
Deprecated in clang-tidy 16 and removed in clang-tidy 18.
=> Clang-Tidy: Remove AnalyzeTemporaryDtors

src/Mod/AddonManager/Widgets/addonmanager_widget_filter_selector.py
Cleans up a bit of a mess with the import fallback code.
=> Addon Manager: Add fallbacks for PySide to WidgetFilterSelector

.github/workflows/actions/runCPPTests/runAllTests/action.yml
The current structure of the CI system explicitly lists the tests to run, and several recently-added test executables were not included in the list.
=> CI: Add missing C++ tests to CI run

src/Mod/Sandbox/Gui/GLGraphicsView.cpp, src/Mod/Sandbox/Gui/Overlay.cpp
(found while searching for the build error on armhf/armel on Debian buildds, once resolved will make an additional PR for that.)
$grep -r GL_MULTISAMPLE src/
yields:
src/Mod/Sandbox/Gui/Overlay.cpp: #ifndef GL_MULTISAMPLE
src/Mod/Sandbox/Gui/Overlay.cpp: #define GL_MULTISAMPLE  0x809D
src/Mod/Sandbox/Gui/GLGraphicsView.cpp:#ifndef GL_MULTISAMPLE
src/Mod/Sandbox/Gui/GLGraphicsView.cpp:#define GL_MULTISAMPLE  0x809D
-> The defines are defined, but never used in the compilation unit
=> Remove unused ifndefs for GL_MULTISAMPLE

src/Mod/Robot/CMakeLists.txt
(Background is issue #18622)
CMake errors out when the Kuka files are removed with:
```
CMake Error at cMake/FreeCadMacros.cmake:79 (ADD_CUSTOM_COMMAND):
ADD_CUSTOM_COMMAND called with wrong number of arguments.
Call Stack (most recent call first):
src/Mod/Robot/CMakeLists.txt:47 (fc_target_copy_resource)
```
The problem is that while the CMake code checks whether /src/Mod/Robot/Lib/Kuka is there befor setting Robot_Resources, but then later still uses the variable, even if it hasn't been set.
The patch just guards the failing fc_target_copy_resource with another if that checks whether the variable has been defined.
CMake install would also fail when Lib is empty, so another guard is required for the `INSTALL( DIRECTORY Lib` … section.
=> Fix compilation issue if KuKa files have been removed.

src/Mod/BIM/ArchStairs.py
Stairs can do without Base.  Base validity is tested in code.
EnsureBase() is remarked out.
=> [ArchStairs] Regression-fix : EnsureBase prevent creation

src/Mod/Draft/Draft.py, src/Mod/Draft/draftfunctions/move.py, src/Mod/Draft/draftfunctions/rotate.py, src/Mod/Draft/draftfunctions/scale.py, src/Mod/Draft/draftutils/utils.py
The related functions were introduced in V0.19. They should not be also available under CamelCase names.
=> Draft: Remove unnecessary CamelCase names

src/Mod/Draft/drafttests/test_modification.py
Fixes #18315.
In the issue discussion the more obvious solution (change the MakeFace property of the Draft_Wires) was missed.
=> Draft: Make test_modification tests independent of fillmode

src/Mod/Draft/CMakeLists.txt, src/Mod/Draft/drafttests/test_airfoildat.py, src/Mod/Draft/drafttests/test_base.py, src/Mod/Draft/drafttests/test_creation.py, src/Mod/Draft/drafttests/test_draftgeomutils.py, src/Mod/Draft/drafttests/test_dwg.py, src/Mod/Draft/drafttests/test_dxf.py, src/Mod/Draft/drafttests/test_import.py, src/Mod/Draft/drafttests/test_import_gui.py, src/Mod/Draft/drafttests/test_import_tools.py, src/Mod/Draft/drafttests/test_modification.py, src/Mod/Draft/drafttests/test_oca.py, src/Mod/Draft/drafttests/test_pivy.py, src/Mod/Draft/drafttests/test_svg.py
=> Draft: Introduce base classes for Draft tests

src/Mod/Draft/TestDraft.py
Some Draft test files contain only dummy tests (`aux.fake_function`). Running them will just open a new file and then immediately close it. This can result in issues with code that is called with a delay. See #18679. Disabling these tests by commenting them out avoids this.
=> Draft: comment out 3 test files with only dummy tests

src/Mod/BIM/Arch.py, src/Mod/BIM/ArchStairs.py, src/Mod/BIM/bimcommands/BimStairs.py
Refer to discussion at -
https://github.com/FreeCAD/FreeCAD/pull/18864
https://github.com/FreeCAD/FreeCAD/pull/18651
https://github.com/FreeCAD/FreeCAD/issues/16409
Like Wall, Stairs should do without Base. Base validity tested in execute() prevented the desired and documented behaviour.
With this improvement, EnsureBase() is now only to be run when there is Base. If there is no Base, or Base is not valid, Stairs would be created as declared.
=> [ArchStairs]  Improve Stairs Creation and ensureBase

src/Mod/BIM/ArchWall.py
Refer to discussion at -
https://github.com/FreeCAD/FreeCAD/pull/18651
https://github.com/FreeCAD/FreeCAD/issues/16409
Wall should do without Base. Base validity tested in execute() prevented the desired and documented behaviour.
EnsureBase() is remarked out in execute() and to be run in getExtrusionData().  With this fix, if there is no Base, or Base is not valid, Wall would be created as declared.
=> [ArchWall] Fix Regression - EnsureBase prevent creation without Base

src/Mod/BIM/ifc_objects.py, src/Mod/BIM/ifc_viewproviders.py, src/Mod/BIM/nativeifc/ifc_commands.py, src/Mod/BIM/nativeifc/ifc_diff.py, src/Mod/BIM/nativeifc/ifc_export.py, src/Mod/BIM/nativeifc/ifc_generator.py, src/Mod/BIM/nativeifc/ifc_geometry.py, src/Mod/BIM/nativeifc/ifc_import.py, src/Mod/BIM/nativeifc/ifc_layers.py, src/Mod/BIM/nativeifc/ifc_materials.py, src/Mod/BIM/nativeifc/ifc_objects.py, src/Mod/BIM/nativeifc/ifc_observer.py, src/Mod/BIM/nativeifc/ifc_openshell.py, src/Mod/BIM/nativeifc/ifc_performance_test.py, src/Mod/BIM/nativeifc/ifc_psets.py, src/Mod/BIM/nativeifc/ifc_selftest.py, src/Mod/BIM/nativeifc/ifc_status.py, src/Mod/BIM/nativeifc/ifc_tools.py, src/Mod/BIM/nativeifc/ifc_tree.py, src/Mod/BIM/nativeifc/ifc_types.py, src/Mod/BIM/nativeifc/ifc_viewproviders.py
For some reason I cannot remember, the nativeIFC files where licensed under GPL3 instead of LGPL2+. This PR fixes it.
issue #18622
=> BIM: Fixed nativeIFC license

src/Mod/Draft/draftmake/make_sketch.py
A sketch object has its own methods to add coincident, horizontal and vertical constraints. Using those methods allows to simplify the make_sketch.py code. The new code applies the mentioned constraints to the whole sketch,  instead of per object. The old code would not add coincident constraints between seperate, but connected, objects. the new code does.
Note that the code for point objects (not changed in this PR) does not work properly.
=> Draft: make_sketch.py: Use sketcher methods to add constraints

src/Mod/Sketcher/Gui/CommandCreateGeo.cpp, src/Mod/Sketcher/Gui/DrawSketchHandlerExternal.h, src/Mod/Sketcher/Gui/SketcherSettings.cpp, src/Mod/Sketcher/Gui/SketcherSettings.ui
There are many complaints about the new behaviour to add ext. geometry according to the current construction mode.
In the past the default was to always add it as reference.
With this option the user can restore the old behaviour.
=> Sketcher: Add an option to always add ext. geometry as reference

src/Mod/TechDraw/App/Preferences.cpp, src/Mod/TechDraw/App/Preferences.h, src/Mod/TechDraw/Gui/QGIViewSymbol.cpp, src/Mod/TechDraw/Gui/QGIViewSymbol.h
This PR implements a fix for issue #14400.  Previously, Svg symbols inserted onto a  page were scaled incorrect.  This fix sets 1 Svg px = 1 scene unit (0.1mm) on the page and 1 Svg mm to 1 mm on the page.
The original behaviour is available by setting General/LegacySvgScaling to true.  The is no Gui update for this parameter, as it will only be changed in rare circumstances.
=> [TD]Symbol scaling (fix #14400)

src/Mod/Part/App/PartFeature.cpp, src/Mod/Part/App/PartFeature.h
Reverts PR #17438
The PR experienced sever performance issues when the file contained objects with errors. This PR removes the physical properties attributes and its associated calculations.
It retains changes to the material filter funtions which were not affected by the errors.
=> Materials: Physical properties reversion

src/App/Application.cpp, src/App/FreeCADInit.py, src/Gui/DlgMacroExecuteImp.cpp, src/Gui/DlgMacroExecuteImp.h
This introduce new option `-E [ --macro-path]` to specify extra system paths of macros. The macro found in this paths will appear in `Macros` dialog at `System macros` tab.
Will fix #18343
=> Macro: allow to specify extra system paths for macro

src/Mod/Spreadsheet/Gui/SheetTableView.cpp
There seem to be a de facto standard in spreadsheet applications to center text both in column and row headers, however in qt, default seem to be to left align row header text.
This PR changes the alignment so it matches other spreadsheet applications such as google sheets, excel, numbers, excel, open office (even lotus 1-2-3 for windows).
As mentioned in [this other PR comment](https://github.com/FreeCAD/FreeCAD/pull/18719#issuecomment-2561970566), centering text needs to be done in code rather than in style sheets. By doing it in code, it is also fixes it in Classic.
Before (classic 1.0):
Before (classic 1.1.0dev head+qt6-this modification):
After (classic 1.1.0dev head+qt6+this modification):
=> Center text in spreadsheet vertical headers

src/Mod/Part/BOPTools/BOPFeatures.py
=> Part: copy_visual_attributes did not handle Draft Link arrays

src/Mod/Fem/femsolver/calculix/solver.py, src/Mod/Fem/femsolver/calculix/write_step_equation.py
Adds _BucklingAccuracy_ parameter - in some cases, it might be necessary to lower this default value: https://github.com/Dhondtguido/CalculiX/issues/57
=> FEM: Add accuracy parameter for CalculiX buckling analysis

src/Mod/Draft/draftobjects/base.py
The new material related properties (Density, Volume and Mass) must be ignored by the `props_changed_placement_only` function.
Without this moving a Draft_Point will fail for example.
=> Draft: props_changed_placement_only should ignore material props

src/Mod/Draft/draftobjects/base.py, src/Mod/Draft/draftobjects/facebinder.py
Fixes #13816.
The `makeOffsetShape` method that creates the extruded shape is quite picky. For example, it will work for a pyramidal shell (4 triangles) with a square floorplan, but not if the floorplan is slightly rectangular. To get closed corners the `Sew` property of the Facebinder must be set to `True`. If extruding does not work properly, the code will retry with `Sew` disabled.
There is also some code that tries to convert flat B-spline faces created between the main offset faces into planar faces. In some cases that code will fail (the results of `makeOffsetShape` can already contain errors). If that is the case the original shape created by `makeOffsetShape` is used.
=> Draft: Closed corners for extruded Facebinders

src/Mod/BIM/importers/importWebGL.py
Hi,
I was using the webgl exporter which works great for simple shapes but once the objects become more complicated the compression step takes a long time because of the nested for loops.
In the first commit I have taken the opportunity while I was in the file to refactor it slightly and split some functionality out into standalone functions.
With the second commit I have used numpy to avoid some of the python nested for loops used in compression. For me this makes the saving of more complex shapes nearly instantaneous.
=> BIM: Speedup and refactor WebGL exporting

src/Mod/BIM/ArchSpace.py
Refer to discussion at -
https://github.com/FreeCAD/FreeCAD/issues/18917
Like Wall and Stairs, Space should do without Base. Base validity tested in execute() prevented the desired and documented behaviour.
EnsureBase() is remarked out in execute() and to be run in getShape(). With this improvement, if there is no Base, or Base is not valid, Space would be created if it could be defined by obj.Boundaries.
=> [ArchSpace]  Improve Space Creation and ensureBase

src/App/Datums.cpp, src/App/Datums.h, src/App/Origin.h, src/Gui/CommandDoc.cpp, src/Gui/ViewProviderLine.cpp, src/Mod/Fem/App/FemConstraint.cpp, src/Mod/Part/App/PartFeature.cpp, src/Mod/PartDesign/App/FeatureLinearPattern.cpp, src/Mod/PartDesign/App/FeatureMirrored.cpp, src/Mod/PartDesign/App/FeaturePolarPattern.cpp, src/Mod/PartDesign/App/FeatureSketchBased.cpp, src/Mod/Test/Document.py
Add the methods DatumElement::getBasePoint() and DatumElement::getDirection() to hide implementation details and guarantee consistent behaviour.
Using the methods fixes several regressions in:
* Constraint::getDirection
* LinearPattern::getTransformations
* PolarPattern::getTransformations
=> App: Add methods to get base and direction of datum element

src/Base/CMakeLists.txt, src/Base/UniqueNameManager.cpp, src/Base/UniqueNameManager.h, tests/src/Base/CMakeLists.txt, tests/src/Base/UniqueNameManager.cpp
This PR is part 1 of a series of two which address #16849, and replaces defective PR #17944 (defects causing issues #18512 and #18504).
As described in Issue #16849, the existing `Tools::getUniqueName` method requires calling code to form a vector of existing names to be avoided.
This leads to poor performance both in the O(n) cost of building such a vector and also `getUniqueName`'s O(n) algorithm for actually generating the unique name (where 'n' is the number of pre-existing names).
This has  particularly noticeable cost in documents with large numbers of `DocumentObject`s because generating both Names and Labels for each new object incurs this cost. During an operation such as importing this results in an O(n^2) time spent generating names.
The other major cost is in the saving of the …
=> Address the poor performance of the existing unique-name generation (part 1)

src/Mod/TechDraw/Templates/A0_Landscape_ISO5457_advanced.svg, src/Mod/TechDraw/Templates/A0_Landscape_ISO5457_minimal.svg, src/Mod/TechDraw/Templates/A1_Landscape_ISO5457_advanced.svg, src/Mod/TechDraw/Templates/A1_Landscape_ISO5457_minimal.svg, src/Mod/TechDraw/Templates/A2_Landscape_ISO5457_advanced.svg, src/Mod/TechDraw/Templates/A2_Landscape_ISO5457_minimal.svg, src/Mod/TechDraw/Templates/A3_Landscape_ISO5457_advanced.svg, src/Mod/TechDraw/Templates/A3_Landscape_ISO5457_minimal.svg, src/Mod/TechDraw/Templates/A4_Landscape_ISO5457_advanced.svg, src/Mod/TechDraw/Templates/A4_Landscape_ISO5457_minimal.svg, src/Mod/TechDraw/Templates/A4_Portrait_ISO5457_advanced.svg, src/Mod/TechDraw/Templates/A4_Portrait_ISO5457_minimal.svg, src/Mod/TechDraw/Templates/ISO 5457/ISO7200_titleblock_1_minimal.svg, src/Mod/TechDraw/Templates/ISO 5457/ISO7200_titleblock_2.svg, src/Mod/TechDraw/Templates/ISO 5457/ISO7200_titleblock_3_advanced.svg, src/Mod/TechDraw/Templates/ISO 5457/ISO7200_titleblock_4.svg, src/Mod/TechDraw/Templates/ISO 5457/ISO7200_titleblock_5_maximal.svg
Presumably Component Drawings are more common as opposed to Assembly Drawing's therefore FreeCAD's default should reflect this.
find src/Mod/TechDraw/Templates -iname "*.svg" -exec sed -i 's#Assembly Drawing#Component Drawing#g' "{}" \;
=> TechDraw: Component Drawing as default document type

src/Mod/PartDesign/PartDesignTests/TestInvoluteGear.py
When enabling the experimental "Allow multiple solids in Part Design Body by default" some involute gear tests broke. As a quick measure, `AllowCompound` was disabled for the respective body; see #17364. This commit now makes the tests independent of this setting and removes the workaround.
=> PD: Make InvoluteGearTests independent of "single solid" setting

src/Mod/TechDraw/Gui/QGCustomText.cpp, src/Mod/TechDraw/Gui/QGCustomText.h, src/Mod/TechDraw/Gui/QGIViewDimension.cpp
This PR implements a fix for the clipping problems raised in issue #11452.
The problems of glyph placement within the text bounding rectangle will have to be addressed in another PR, likely one that addresses issue #16975.
=> [TD]Dimension font clipping (fix #11452)

src/Gui/Stylesheets/FreeCAD Dark.qss, src/Gui/Stylesheets/FreeCAD Light.qss
When you put a toolbar in the menubar (corner widget), then the background is of the toolbar is light gray (dark theme) and not dark gray like the menu bar.
Removing the color definition for the toolbars fix this it seems.
@MisterMakerNL can you please check?
=> Stylesheet toolbar background

src/Mod/Measure/App/ShapeFinder.cpp
This PR is an alternative to PR #19007.  
This PR corrects the slow transform in ShapeFinder.
PR #19007 reverts the TD changes for handling long form sub element names in dimension references from  PR #18641.
=> [TD]use transformShape instead of transformGeometry

src/Mod/BIM/ArchComponent.py
Allows FreeCAD BIM module to load without TechDraw module compiled.
=> BIM: Only import `TechDraw` when its actually needed.

cMake/FreeCAD_Helpers/CheckInterModuleDependencies.cmake
This makes it much easier to notice the error, previously it was just printed as a regular message and lost in the output.
=> CMake: Issue a non-fatal error when module dependency is not found.

src/Mod/AddonManager/NetworkManager.py
Hi, I've made improvements to the proxy handling in NetworkManager. Specifically, I replaced the simple `str.rpartition(':')` approach with `urllib.parse.urlparse` for parsing proxy URLs, which provides more robust and accurate parsing. Additionally, I've enhanced the error messaging to make it more informative.
This is my first contribution to FreeCAD, so please don't hesitate to point out any issues or areas for improvement. I'm eager to learn and make this contribution as effective as possible.
=> Addon Manager: Improve proxy URL parsing & enhanced the error messaging

src/Mod/BIM/ArchWall.py
The movePoint function is no longer available in V1.1.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=93879
=> BIM: ArchWall use moveGeometry to move sketch point

src/Mod/Draft/draftobjects/clone.py
B-spline faces can be avoided if the absolute values of the scaling factors are the same. The `transformShape` method can handle this if two additional arguments are provided.
=> Draft: Clone: avoid B-spline faces in more cases

src/Gui/RemoteDebugger.py
Typically users use the same debugger repeatedly. The current dialog required users to change tabs each time the debugger is launched. This change saves the last used debugger tab and sets that as the selected tab when relaunching the debugger.
=> Macros: Save last used debugger

src/Gui/View3DSettings.cpp
This gets caught in the debugger at startup, in this case its easy to avoid it.
=> Gui: Avoid unnecessary exception in `View3DSettings::OnChange`.

src/Mod/Assembly/CommandCreateJoint.py
Ok once more. I learned about localisation (new topic to me). As I understood from the wiki/forum the `*.ts` are somehow created by admins and I don't have to do anything?!
Nevertheless, I checked locally with my personal build `Tools/updatets.py Assembly` and it does fix the typo.
=> fixed small typo 

CONTRIBUTING.md
As discussed over the developer meeting, this adds list item for the contribution requirements to ensure that each breaking change is handled properly and documented.
=> Contributing: Add information about breaking changes

src/Mod/BIM/nativeifc/ifc_export.py
Context can never be None when creating IFC entities, so we need to create one if none is found in the file
=> BIM: Make sure we have a context when exporting to IFC

src/Mod/Part/Gui/ViewProvider2DObject.cpp, src/Mod/Part/Gui/ViewProvider2DObject.h, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
This adds utility that allows users to see plane that sketch is based on. For now it is enabled only explicitly via view property but in the future we should enable it automatically when:
- User edits attachment of 2D object
- User transforms 2D object
- As preference when sketch is selected
- As preference when sketch is preselected
- maybe other scenarios
=> Gui: Add Show Plane utility to 2D Objects

src/App/PropertyStandard.cpp, src/Mod/Fem/femobjects/mesh_netgen.py
The first commit adds an option to set the limits of `PropertyFloatConstraint` and `PropertyIntegerConstraint` via a Python dict with optional values ​​for the limits and steps using the keywords `"value"`, `"min"`, `"max"`, `"step"`.
Also the use of `numeric_limits::min()` is changed to `numeric_limit::lowest` since for floating point values ​​`numeric_limits::min()` returns the minimum positive value.
The second commit adds the use of constraints to some integer and float properties of the mesh Netgen object.
@FEA-eng
=> Fem: Use property constraints on mesh netgen object

src/Gui/PythonEditor.cpp, src/Gui/PythonEditor.h
This PR adds the ability to send selected code from the python editor to be executed in the python console.  Usage: select a block of code in the python editor, press Alt+Shift+P (or select Execute in console from the context menu).  Selected block of code will be executed in the python console.
Often there is an issue with indentation, for example, if we wish to execute a block of code that is within a function definition or class definition.  This PR will attempt to normalize the indentation level so that it can be executed in the console.  The method used is to find the leading whitespace of the first selected line, and then remove that leading whitespace from all the lines in the selected block, thus preserving the indentation relative to the first selected line.
Note that the …
=> [Python console] add Execute in console context menu item

src/App/GeoFeature.cpp
This fixes a case when in case of rootObj being Link placement was not calculated correctly due to not changing of the document. While for original use it was fine as this was mostly used in case where there was defined non-link root for general case Links can be root objects of the document.
partial fix for https://github.com/FreeCAD/FreeCAD/issues/18093
@PaddleStroke FYI
This could use backport.
=> App: Fix GeoFeature::getGlobalPlacement when rootObj is Link

src/Gui/DlgPreferencePackManagementImp.cpp, src/Gui/DlgPreferencePackManagementImp.h
Closes #18725. The cause of the crash is a direct invocation of `QDialog::showEvent(QShowEvent *event)` with `nullptr`, leading to the segmentation fault. [^1] Simple minuscule refactoring fixes it.
[^1]: https://github.com/qt/qtbase/blob/d89cef439f5c1a58aeff879a12d9a33292764b7f/src/widgets/dialogs/qdialog.cpp#L851-L860
=> Fix the crash in the interface for managing preference packs

src/Gui/WorkbenchSelector.h
As explained in https://github.com/FreeCAD/FreeCAD/issues/18484#issuecomment-2572430803 named buttons were introduced only for newer versions of Qt. I am not aware about any other method that allows us to scroll it programmatically so this simply prevents the crash.
Fixes #18484
=> Gui: Fix crash on scrolling workbench tab bar in Qt < 5.15.6

src/Gui/Inventor/So3DAnnotation.cpp, src/Gui/Inventor/So3DAnnotation.h, src/Gui/SoFCDB.cpp, src/Gui/View3DInventorViewer.cpp, src/Gui/ViewProviderDatum.cpp
This PR Fixes rendering order of datum planes. It achieves it by modifying `So3DAnnotation` to include separate delayed render queue that is rendered after the scene with cleared depth buffer. Depth buffer was previously cleared for every So3DAnnotation instance independently. Basically it introduces ability to draw annotations on separate layer.
This PR does NOT fix picking order - as far as I know it is not possible to do without modifying coin itself as it would require to introduce not only rendering, but also picking layers (or priorities) into SoRayPickAction. 
Someone more knowledgeable in the area (@wwmayer) may know some way - if we would be able to extract all shapes intersected with ray and their priorities we could in theory implement it on our side.
The way that it is …
=> Gui: Fix render order of datum planes

tools/build/Docker/ubuntu.sh
Add libyaml-cpp-dev to Docker ubuntu.sh dependencies
I tried following the [tools/build/Docker/README.rst](https://github.com/FreeCAD/FreeCAD/blob/main/tools/build/Docker/README.rst) instructions for building a Ubuntu Docker image with FreeCAD, but it fails due to a missing dependency on `libyaml-cpp-dev`. This PR adds  libyaml-cpp-dev to the dependencies script `ubuntu.sh`, to fix this.
=> Add libyaml-cpp-dev to Docker ubuntu.sh dependencies

contrib/.vscode/launch.json, contrib/debugger/qt_pretty_printers_gdb.py, contrib/debugger/qt_pretty_printers_lldb.py
In an attempt to make debugging life easier, I've created QT pretty printers for both GDB and LLDB that will pretty print QString objects in your debugger of choice (future support can be added for other QT types if required.)
Note that there may be variances between different operating systems and/or build configurations in how QString data is stored internally.  I've tried to account for this in the code but we may discover other cases once more people start to use these.  We can fix if and when we encounter any issues.
I've also modified the repositories vscode launch config to incorporate these pretty printers.
QString in GDB Debugger in vscode
QString in GDB console
```console
x@fcdev:~/freecad-source/build/debug/bin$ gdb ./FreeCAD
GNU gdb (Debian 13.1-3) 13.1
Copyright (C) 2023 Free …
```
=> GDB/LLDB debugger pretty printers w/QString support and vscode launch config

src/Mod/Sketcher/Gui/Command.cpp
Fix for issue #14603
Fixed an issue in the Sketcher where attempting to create a sketch while a group is selected caused a mapping error. Now, when a sketch is created with a group selected, the sketch will be placed inside the group.
- When the selection contains only a group, the sketch is created inside the group.
- When the selection contains a group and other objects, a warning ("Too many objects selected") is displayed to the user.
- In all other cases, the behavior remains unchanged.
=> Sketcher: Fixed mapping error when attempting to create a sketch inside a group.

src/Mod/Sketcher/App/Constraint.h
When using 'typeToString()' or even getting the 'Type' of a constraint, the name and index would always be off by one as `"Coincident"` was missing.
=> Fix missing constrain type in 'type2str'

src/Mod/Draft/Draft.py, src/Mod/Draft/DraftGui.py, src/Mod/Draft/draftfunctions/join.py, src/Mod/Draft/draftfunctions/move.py, src/Mod/Draft/draftfunctions/rotate.py, src/Mod/Draft/draftfunctions/scale.py, src/Mod/Draft/draftfunctions/svg.py, src/Mod/Draft/draftguitools/gui_move.py, src/Mod/Draft/draftguitools/gui_rotate.py, src/Mod/Draft/draftguitools/gui_scale.py, src/Mod/Draft/draftguitools/gui_trackers.py, src/Mod/Draft/draftobjects/clone.py, src/Mod/Draft/draftobjects/dimension.py, src/Mod/Draft/draftobjects/layer.py, src/Mod/Draft/drafttaskpanels/task_scale.py, src/Mod/Draft/drafttests/test_modification.py, src/Mod/Draft/draftutils/gui_utils.py, src/Mod/Draft/draftutils/utils.py, src/Mod/Draft/draftviewproviders/view_text.py
Fixes #12836.
Fixes #15681.
These changes are presented as a single ('big') PR because the mentioned commands have several similarities. Working on them seperately would have made less sense.
The commands have been made 'link-aware' meaning they can now handle Links and objects in linked containers.
This required several changes in the following main files. For each command all options are handled by a single function now (the `move`, `rotate` and `scale` functions). This was the only reasonable solution to correctly handle nested placements. As a result there is no longer a need to build very complex 'cmd' strings in the gui_*.py files (which is a good thing IMO).
Main files:
* move.py
* rotate.py
* scale.py
* gui_move.py
* gui_rotate.py
* gui_scale.py
* gui_trackers.py
The following …
=> Draft: make move, rotate and scale commands link-aware

src/Mod/Part/Gui/TaskAttacher.cpp, src/Mod/Part/Gui/TaskAttacher.h, src/Mod/Part/Gui/ViewProviderAttachExtension.cpp, src/Mod/Part/Gui/ViewProviderAttachExtension.h, src/Mod/PartDesign/Gui/SketchWorkflow.cpp
This PR adds a parameter `Preferences/Mod/PartDesign/NewSketchUseAttachmentDialog `
If set to true, the command 'create new sketch' in part design will open the attachment dialog instead of the 'feature pick' dialog.
It is false by default. ie the current workflow is not changed.
The reason it is false is that the workflow with the attachment dialog is not smooth enough to be the default imo. Reasons : 
- In feature pick a single click on a base plane validates. With attachment dialog it needs to select first, then click OK. We could set the attachment dialog to auto-complete on first selection. But then you cannot do more complex attachment (set offset for instance).
- The attachment dialog is not good enough and throws error in all directions.
@pierreporte @maxwxyz
=> PartDesign New sketch : Open attachment dialog

src/Mod/PartDesign/Gui/SketchWorkflow.cpp
A change in API in an earlier PR broke @PaddleStroke's PR.  This restores the functionality.
=> Fix call to setTemporaryVisibility() post API change.

src/Mod/Sketcher/App/SketchObject.cpp
A small bit of C++20 code was mistakenly included in an earlier PR: this refactors to remove it until we switch to C++20 as our required standard (not supported on Ubuntu 20.04 LTS).
=> Sketcher: Refactor C++20 code

src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
When clicking on a constraint in Sketcher, that constraint is now automatically scrolled to in the Constraints listview. If selecting multiple constraints, the last one is scrolled to. Closes #17361
=> Auto scroll to constraint on click

src/Mod/BIM/Resources/ui/preferences-sh3d-import.ui, src/Mod/BIM/importers/importSH3DHelper.py, src/Mod/Part/App/BRepOffsetAPI_MakePipeShellPy.xml, src/Mod/Part/App/BRepOffsetAPI_MakePipeShellPyImp.cpp
As suggested in [#19010](https://github.com/FreeCAD/FreeCAD/pull/19010#issuecomment-2604708078) opening this PR from a branch instead of main. 
-Adding Arch::Space for each room, and group furniture in these spaces
- Fixed baseboard import: the baseboard import was broken and did not create the baseboards along the bottom edge of the wall.
- Allow creation of reference ground mesh @z=0. This is controlled by a setting in the preference page.
- Avoid gap between floors: The floors' slab were extrudes to -z which left a gap between the walls of each level.
- As mentioned in https://github.com/FreeCAD/FreeCAD/pull/17165#issuecomment-2506655439 the "Join Wall" hits some strange bug in the Part::Sweep (https://github.com/FreeCAD/FreeCAD/issues/18658).
It solves the problem for straight wall by …
=> SH3DImporter: Miscellaneous improvements

src/Gui/CallTips.h, src/Gui/PythonConsole.cpp, src/Gui/PythonConsole.h, src/Gui/TextEdit.cpp, src/Gui/TextEdit.h
Now autocomplete is in all TextEdit objects. Fixes #12850
=> [Gui] Make autocompletion global

src/Gui/PreferencePages/DlgSettingsEditor.ui, src/Gui/PreferencePages/DlgSettingsNavigation.ui, src/Gui/PreferencePages/DlgSettingsSelection.ui, src/Gui/PreferencePages/DlgSettingsViewColor.ui, src/Mod/CAM/Gui/DlgSettingsPathColor.ui, src/Mod/CAM/Gui/Resources/preferences/PathDressupHoldingTags.ui, src/Mod/Draft/Resources/ui/preferences-svg.ui, src/Mod/Fem/Gui/DlgSettingsFemCcx.ui, src/Mod/Fem/Gui/TaskFemConstraintHeatflux.ui, src/Mod/Part/Gui/DlgSettingsObjectColor.ui, src/Mod/Sketcher/Gui/SketcherSettingsAppearance.ui, src/Mod/Sketcher/Gui/SketcherSettingsGrid.ui
Ensure units have a space, ex: " px"
FEM: Don't mark units for translation
Fixed mm -> px
=> Add units to some spinboxes on preferences pages

src/Mod/Sketcher/Gui/Command.cpp
Backport version of PR https://github.com/FreeCAD/FreeCAD/pull/18971
Fix for issue https://github.com/FreeCAD/FreeCAD/issues/14603
Fixed an issue in the Sketcher where attempting to create a sketch while a group is selected caused a mapping error. Now, when a sketch is created with a group selected, the sketch will be placed inside the group.
-   When the selection contains only a group, the sketch is created inside the group.
-   When the selection contains a group and other objects, a warning ("Too many objects selected") is displayed to the user.
-   In all other cases, the behavior remains unchanged.
=> Backport version. Sketcher: Fixed mapping error when attempting to create a sketch inside a group.

src/Mod/AddonManager/addonmanager_utilities.py
Hi, when I'm using AddonManager Developer Tool, it returns wrong readme url like: `https://github.com/author/project.git/raw/main/README.md`. And it will lead to a 404 error like this:
In order to get the right url, I added `.rstrip('.git')`.
=> [AddonManager] Fix construct_git_url return urls with '.git'.

src/Mod/BIM/Resources/ui/preferences-sh3d-import.ui, src/Mod/BIM/importers/importSH3DHelper.py
This PR aims to fix a certain number of problems with surfaces decoration and floors' slab.
When decorating walls, the `wall.ViewObject.DiffuseColor` attribute was used. The issue was that after the doors and windows, the face would change. The solution involves delaying the wall surface decoration after the addition of doors and windows, then create a `Draft.Facebinder` on each side (with therefore the doors and windows cutout included) and apply color to that instead.
The same has been added for floor and ceilings
The result is a much more accurate import of visual elements.
Slabs were creating for each rooms (i.e. each `Arch.Space`), with the side effect that they did not cover the whole `Arch.Floor` and would therefore leave a gap under the walls. The solution involves delaying the …
=> SH3DImporter: surface decoration and slab improvments
