src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
src/Mod/Assembly/Gui/ViewProviderAssembly.h
src/Mod/Assembly/Gui/ViewProviderAssemblyPy.xml
src/Mod/Assembly/Gui/ViewProviderAssemblyPyImp.cpp
src/Mod/Assembly/UtilsAssembly.py

Fix https://github.com/FreeCAD/FreeCAD/issues/16617
Fix https://github.com/FreeCAD/FreeCAD/issues/15706 also!

Assembly: Fix context menu 'Activate object' not working and causing crash

---

src/Mod/Fem/femtools/ccxtools.py

Fem: Remove highlighted nodes if ccx finish without error - fixes #14855

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/App/AssemblyObjectPyImp.cpp
src/Mod/Assembly/JointObject.py

Fix https://github.com/FreeCAD/FreeCAD/issues/17180
This may fix https://github.com/FreeCAD/FreeCAD/issues/17144 as well but we'll need confirmation from OP
@chennes commits can be squashed.

Assembly: Fix crash on empty joint flip

---

src/Mod/Fem/Gui/Resources/ui/MeshGmsh.ui
src/Mod/Fem/Gui/Resources/ui/MeshNetgen.ui

@chennes
From https://github.com/FreeCAD/FreeCAD/pull/16900

Fem: Use default height for mesh task panel quantity spin boxes

---

src/Mod/PartDesign/App/FeatureLoft.cpp

[PartDesign] Disable closed Loft for less than 3 profiles

---

src/Mod/BIM/importers/exportIFC.py
src/Mod/BIM/nativeifc/ifc_status.py

BIM: Fixed missing object creation in IFC document conversion

---

src/Mod/TechDraw/App/Geometry.cpp
src/Mod/TechDraw/App/GeometryMatcher.cpp

This PR implements a fix for issue #16980.  It also removes some spurious error messages issued by GeometryMatcher that we discovering in developing the fix.

[TD]Fix bad circles (fix #16980)

---

src/Mod/Start/Gui/PreCompiled.h

See https://github.com/FreeCAD/FreeCAD/issues/17257

Start: Fix build failure with enabled PCH

---

src/Mod/CAM/Path/Post/scripts/marlin_post.py

final returned at line 461 in  `src/Mod/CAM/Path/Post/scripts/marlin_post.py `

Marlin Post Processor not able to write to disk - PR

---

src/Mod/PartDesign/Gui/TaskFeatureParameters.cpp

PartDesign: Fix body shape not updated

---

src/Mod/Assembly/JointObject.py
src/Mod/Assembly/UtilsAssembly.py

See problem description in https://github.com/FreeCAD/FreeCAD/pull/16726#issuecomment-2414166608
This fixes it. @maxwxyz could you give this a go?

Assembly: Fix regressions of #16726

---

src/Mod/Assembly/JointObject.py

Fix https://github.com/FreeCAD/FreeCAD/issues/17287
@chennes small fix here

Assembly: Fix limits disappearing on edit

---

src/Gui/Action.cpp
src/Gui/CMakeLists.txt
src/Gui/MainWindow.cpp
src/Gui/ModuleIO.cpp
src/Gui/ModuleIO.h
src/Mod/Start/Gui/StartView.cpp

* Use ModuleIO in RecentFilesAction & RecentMacrosAction
* Use ModuleIO in MainWindow::loadUrls
* Use ModuleIO in StartView::fileCardSelected
Fixes #17250

Core: Add convenience class ModuleIO to open files

---

src/Mod/Part/Gui/TaskAttacher.cpp

Fix regression of https://github.com/FreeCAD/FreeCAD/pull/17013
@wwmayer confirms it works.

Part: Task attacher : Fix datum not being cancelled

---

src/Gui/NavigationStyle.cpp

Fixes #17246.
https://github.com/user-attachments/assets/2a73a41f-5b79-49aa-942b-1551aa8db639

Gui: Set spin projector sphere depending on rotation center

---

src/Mod/Fem/femmesh/gmshtools.py
src/Mod/Fem/femtools/femutils.py

Fixes #17298
@donovaly could you confirm?

Fem: Set startupinfo for gmsh subprocess - fixes #17298

---

src/Mod/Draft/draftobjects/patharray.py

See forum topic:
https://forum.freecad.org/viewtopic.php?t=91517

Draft: suppress patharray offset warnings if values are already zero

---

src/Mod/Part/App/PrimitiveFeature.cpp

This reverts commit 60640fa4415548ebfa19c1f929ea2da7e4980fe7 from PR #15931

Revert "Horrible hack to work around bug in OCCT7.7.2"

---

.github/ISSUE_TEMPLATE/PROBLEM_REPORT.yml
README.md

Add safe mode description to issue template and guide in readme.
@chennes FYI, not sure if this needs a backport

Add safe mode description to issue template and guide in readme

---

src/Mod/Draft/drafttests/draft_test_objects.py

* Label property TextSize should be FontSize.
* Added missing recomputes.

Draft: fix errors in draft_test_objects.py

---

src/Gui/DlgAddPropertyVarSet.cpp
src/Gui/DlgAddPropertyVarSet.h

Gui: Fix tooltip/documentation in VarSet dialog

---

src/Mod/Assembly/CommandInsertLink.py

Fix https://github.com/FreeCAD/FreeCAD/issues/14990
Objects that are hidden in the tree view does not appear in the insert tool.
You can right click on empty space to show them.

Assembly: CommandInsertLink: Hide hidden objects

---

src/Gui/Tree.cpp

Core: Handle possible nested calls of TreeWidget::onUpdateStatus()

---

src/Mod/Fem/femcommands/commands.py

Legacy Netgen does not have the `EndStep` property.
@FEA-eng

Fem: Do not try to set EndStep property for legacy Netgen

---

src/Mod/Tux/NavigationIndicatorGui.py

Tux: Remove Qt 4 translate function

---

src/Mod/TechDraw/Gui/QGIEdge.cpp
src/Mod/TechDraw/Gui/QGIEdge.h

This PR implements a fix for issue #17494.

[TD]fix line style regression from #17331 (fix #17494)

---

src/Gui/PreferencePacks/FreeCAD Classic/FreeCAD Classic.cfg
src/Gui/PreferencePacks/FreeCAD Dark/FreeCAD Dark.cfg
src/Gui/PreferencePacks/FreeCAD Light/FreeCAD Light.cfg
src/Mod/Start/Gui/FileCardDelegate.cpp
src/Mod/Start/Gui/StartView.cpp
src/Mod/Start/Gui/StartView.h

Fixes #15756. Similar implementation to that already in FileCardDelegate.cpp.

[Gui] Make styles update on paint

---

src/Mod/Draft/draftguitools/gui_trimex.py

Draft: Fixed trimex bug when snapping to itself

---

src/Mod/BIM/importers/exportIFC.py

BIM: Fixed export of boolean IFC properties

---

src/Mod/Draft/draftguitools/gui_trimex.py

Draft: Warn user if using trimex on unsupported curve type

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/12688
https://github.com/user-attachments/assets/bf4e2889-906f-43f8-838b-b1da7778a8c8

Sketcher: Dimension: Handle case of vertical/horizontal lines

---

src/Mod/OpenSCAD/OpenSCADTest/app/test_importCSG.py

If this test failed it also made all subsequent tests fail because it didn't reset the working dir properly

Fix OpenSCAD test failing when using pipe transfer mechanism

---

src/Gui/Application.cpp

second attempt at fixing #16687, first was #17381

Gui: use wildcard for some warnings filters. Fix #16687

---

src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp

This is a 1.0 version of https://github.com/FreeCAD/FreeCAD/pull/17084
The code for start page was refactored after the PR 17084 and backported.
This PR drops the change in the colliding file.
The linked issue mentions:
* drag and drop csv file
* clicking a csv file in the start window under recent files
Without the PR drag and drop won't work, with it will
In addition to the problems above, I've also tried:
* opening a csv file from file->open
* opening a csv file from file->open recent
* importing a csv file from file->import
All these works with this fix.

[1.0] Fix crashes when importing and opening .csv files on macOS (#17084)

---

src/Gui/AboutApplication.ui
src/Gui/Splashscreen.cpp

Gui: show cpu architecture in version info instead of word size

---

src/Gui/DlgAddPropertyVarSet.cpp
src/Mod/PartDesign/Gui/Command.cpp
src/Mod/PartDesign/Gui/CommandPrimitive.cpp
src/Mod/Sketcher/App/SketchObject.cpp

The commit that caused  most of these warnings went into 1.0 too and they all apply.

[backport] Fix compiler warnings

---

src/Mod/Fem/femmesh/gmshtools.py

Fem: fix Gmsh analysis mesh groups - fixes #17427

---

src/Mod/TechDraw/Gui/QGIFace.cpp

This PR implements a fix for #17276.

[TD]fix scaling of large hatch tiles (fix #17276)

---

src/Mod/BIM/bimcommands/BimIfcExplorer.py
src/Mod/BIM/importers/importIFClegacy.py

Three criticals, a tidy-up and a minor improvement. More in the commit messages.
Closes #17627.

BIM: IFC explorer Qt 6 compatibility and other fixes

---

src/Mod/BIM/bimcommands/BimLibrary.py

Fixing a bug discovered in #17400 :)

BIM: Fixed case bug in library tool

---

src/App/Application.cpp

Fixes issue #17580 
Updated as per discussion. Any feedback/suggestions welcomed.
Thanks,
James

Safe mode message added as per #17580

---

src/Mod/Assembly/JointObject.py

Fix https://github.com/FreeCAD/FreeCAD/issues/12771
Requires https://github.com/FreeCAD/FreeCAD/pull/16317 to merge first.

Assembly: Allow entering expressions in joint task panel

---

src/App/Application.cpp
src/App/Application.h
src/App/Document.cpp
src/Gui/Application.cpp
src/Gui/DocumentRecovery.cpp

Core: Don't freeze application if lock file already exists

---

src/App/Document.cpp
src/App/Graphviz.cpp
src/Mod/PartDesign/CMakeLists.txt
src/Mod/PartDesign/Gui/SketchWorkflow.cpp
src/Mod/PartDesign/PartDesignTests/TestSketch.py
src/Mod/PartDesign/TestPartDesignApp.py

* Tests: Add unit test to demonstrate failure of #17553
* Fixes #17553
* If needed open another transaction for sketch creation

Fixes #17553

---

src/Mod/Assembly/JointObject.py

Fix https://github.com/FreeCAD/FreeCAD/issues/17622

Assembly: Fix double click of joints error

---

src/Mod/BIM/ArchCommands.py
src/Mod/BIM/OfflineRenderingUtils.py
src/Mod/BIM/bimcommands/BimIfcExplorer.py
src/Mod/BIM/bimcommands/BimLibrary.py

Turns out there are more of these as found in  #17649.

BIM: Fix imports of Python importers

---

src/Mod/BIM/importers/exportIFC.py
src/Mod/BIM/importers/exportIFCHelper.py

BIM: Fixed imports of IfcOpenShell 0.8

---

src/Mod/Fem/femmesh/meshtools.py
src/Mod/Fem/femtools/checksanalysis.py

fix #17561
only tested with MeshGroups so far
probably needs retesting once #17427 is fixed <-- edit: retested, done, works

FEM: Allow assigning materials to compounds to avoid having to assign the same material by hand to all subsolids

---

src/Mod/BIM/importers/importIFClegacy.py
src/Mod/CAM/CAMTests/TestPathPost.py
src/Mod/CAM/Path/Post/scripts/gcode_pre.py
src/Mod/Draft/importAirfoilDAT.py
src/Mod/Draft/importOCA.py

Resolve Python invalid escape sequence warnings

---

src/Mod/Import/App/ExportOCAF.cpp

Import: Fix index error with legacy STEP export

---

src/Mod/Fem/femtaskpanels/base_femmeshtaskpanel.py

In some situations, the timer might stop at the transition between the end of the preparation thread and the start of meshing process.
This pull request is a complement to #17666

Fem: Prevent race condition between signals in timer update

---

src/Mod/Assembly/CommandExportASMT.py
src/Mod/Assembly/CommandSolveAssembly.py

Fix https://github.com/FreeCAD/FreeCAD/issues/17662
@chennes small 2-lines assembly fix here.

Assembly: Fix joint group after deletion of active assembly

---

src/Mod/Assembly/CommandCreateView.py
src/Mod/Assembly/JointObject.py
src/Mod/Assembly/UtilsAssembly.py

Fix issues of exploded views introduced by #16671
Fix https://github.com/FreeCAD/FreeCAD/issues/17196
Fix https://github.com/FreeCAD/FreeCAD/issues/17194
Fix https://github.com/FreeCAD/FreeCAD/issues/17208
Fix https://github.com/FreeCAD/FreeCAD/issues/15344

Assembly: Fix exploded view regressions

---

src/Mod/Material/App/Exceptions.h
src/Mod/Material/App/ModelLoader.cpp
src/Mod/Part/App/PartFeature.cpp

Material: Replace YAML::LoadFile() with YAML::Load()

---

src/Mod/Fem/femmesh/netgentools.py
src/Mod/Fem/femobjects/mesh_netgen.py

The `AnalyzeGeometry` step doesn't generate a mesh.
@FEA-eng

Fem: Fix exception if last step in Netgen mesher is geometry analysis

---

src/Mod/Draft/draftutils/params.py

Draft: Fix _param_observer_callback_scalemultiplier error

---

src/Mod/Draft/draftguitools/gui_shape2dview.py

The Draft_Shape2DView command did not finish properly if no object was selected.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=92031

Draft: Fix Shape2DView finish bug

---

src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h
src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
src/Mod/Assembly/Gui/ViewProviderAssembly.h

Unhandled std exception dragging Cylindrical joint

---

src/Mod/Fem/Gui/Resources/ui/Material.ui
src/Mod/Fem/femobjects/material_common.py
src/Mod/Fem/femtaskpanels/task_material_common.py
src/Mod/Material/Gui/MaterialTreeWidget.cpp

This is an intermediate step until fully migrating Fem to the use of the new material system.
The combo box with the list of materials is replaced by the material tree widget.
@FEA-eng

 Fem: Use new material editor in materials task panels - fixes #16814

---

src/Mod/Draft/draftguitools/gui_annotationstyleeditor.py

Draft: Fix AnnotationStyleEditor delete last style error

---

src/Mod/Assembly/Gui/ViewProviderAssembly.h
src/Mod/CAM/libarea/Adaptive.cpp
src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp

* CID 350633
* CID 512344
* CID 514343

Coverity scan: Uninitialized scalar variable

---

src/App/Color.cpp
src/App/Color.h
src/App/ColorModel.h
src/App/Part.cpp
src/App/PropertyStandard.h
src/Gui/TaskElementColors.cpp
src/Gui/Tools/color_traits.h
src/Mod/Mesh/App/Core/MeshIO.cpp
src/Mod/Mesh/Gui/ViewProviderCurvature.cpp
src/Mod/Part/Gui/ViewProvider.cpp
src/Mod/Test/Document.py
tests/src/App/Color.cpp

* Fix issues with alpha value <> transparency
* Use type traits to convert between different color classes (fixes #14515)

Core: Extend Color API

---

src/Mod/TechDraw/Gui/Command.cpp
src/Mod/TechDraw/Gui/TaskSectionView.cpp

This PR implements fixes for translation issues #317 and #335.  
The correction will only become apparent after another translation cycle as the wrong context is stored in the translation files.

[TD] Translation fixes (fix #317 fix #335)

---

src/Gui/CommandDoc.cpp
src/Gui/PreferencePages/DlgSettingsMacro.ui
src/Gui/SelectionView.cpp
src/Gui/TextureMapping.cpp
src/Mod/AddonManager/AddonManagerOptions.ui
src/Mod/AddonManager/addonmanager_git.py
src/Mod/AddonManager/addonmanager_workers_startup.py
src/Mod/CAM/Gui/Resources/panels/DlgJobTemplateExport.ui
src/Mod/CAM/Gui/Resources/panels/DressupPathBoundary.ui
src/Mod/CAM/Gui/Resources/panels/PageBaseGeometryEdit.ui
src/Mod/CAM/Gui/Resources/panels/PageBaseHoleGeometryEdit.ui
src/Mod/CAM/Gui/Resources/panels/PageOpProfileFullEdit.ui
src/Mod/CAM/Gui/Resources/panels/PageOpVcarveEdit.ui
src/Mod/CAM/Gui/Resources/panels/PathEdit.ui
src/Mod/Draft/Resources/ui/TaskShapeString.ui
src/Mod/Draft/Resources/ui/preferences-draftinterface.ui
src/Mod/Fem/Gui/DlgSettingsFemCcx.ui
src/Mod/OpenSCAD/importCSG.py
src/Mod/Part/Gui/DlgExtrusion.ui
src/Mod/Part/Gui/TaskSweep.cpp
src/Mod/Sketcher/Gui/TaskSketcherValidation.cpp
src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawColors.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui
src/Mod/TechDraw/Gui/TaskActiveView.ui
src/Mod/TechDraw/Gui/TaskCosmeticCircle.ui
src/Mod/TechDraw/Gui/TaskCosmeticLine.ui
src/Mod/TechDraw/Gui/TaskDimension.ui

Some strings use uppercase, other use lowercase. I think it's better to unify all in one style, uppercase preferrred.

TechDraw: Fix capitalization of 2D and 3D

---

src/Mod/Assembly/Gui/Resources/panels/TaskAssemblyInsertLink.ui

Reword rigid/flexible sub-assemblies tooltip.

---

src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp

Fem: Adapt FemPostObject transparency to changes made in #ffa3fa5b5a

---

src/Mod/Draft/draftobjects/hatch.py

Draft: Fix extra_scale error in hatch.py

---

src/Mod/Draft/draftobjects/shape2dview.py
src/Mod/Draft/draftviewproviders/view_dimension.py

- more tolerance on faultly solids in shape2Dview
- fixed display of dimensions in arch override unit

Draft: minor fixes

---

src/Mod/Draft/DraftGui.py

Draft: fix tray construction mode button for Light and Dark themes

---

src/Mod/BIM/bimcommands/BimLeader.py
src/Mod/Draft/draftguitools/gui_beziers.py
src/Mod/Draft/draftguitools/gui_lines.py
src/Mod/Draft/draftguitools/gui_splines.py

BIM: Optimized leader UI

---

src/Mod/BIM/bimcommands/BimTutorial.py

BIM: Fixed image loading of the tutorial

---

src/Mod/Part/App/FeaturePartBoolean.cpp
src/Mod/Part/App/FeaturePartCommon.cpp
src/Mod/Part/App/FeaturePartFuse.cpp
src/Mod/PartDesign/App/Feature.cpp
src/Mod/PartDesign/App/FeatureAddSub.cpp
src/Mod/PartDesign/App/FeatureBoolean.cpp
src/Mod/PartDesign/App/FeatureTransformed.cpp
src/Mod/PartDesign/App/ShapeBinder.cpp

This is to avoid code duplication.

Part: move model check to separate function

---

src/Gui/SoFCUnifiedSelection.cpp

This fixes #17965: Measurement: Crash when clicking on COM label

Core: Fix dangling pointer in SoFCUnifiedSelection::setSelection

---

src/Mod/BIM/ArchWall.py

Forum Discussion - https://forum.freecad.org/viewtopic.php?p=768634#p768634

[ArchWall] Bug-fix import ArchSketchObject & add ArchSketchEdges groundwork

---

src/Mod/BIM/nativeifc/ifc_tools.py

Additional support for additions / subtractions
fixes #16631

BIM: Support for additions/subtractions in NativeIFC

---

src/Gui/DlgAddPropertyVarSet.cpp
src/Gui/DlgAddPropertyVarSet.h

Gui: Improve localization support in VarSet dialog

---

src/Mod/Fem/femcommands/commands.py
src/Mod/Fem/femmesh/netgentools.py
src/Mod/Fem/femobjects/mesh_netgen.py
src/Mod/Fem/femviewprovider/view_mesh_netgen.py

Both features work with the same workflow as in Gmsh meshing.
@FEA-eng

Fem: Add local refinement and second order linear for Netgen meshing

---

src/Mod/Assembly/Gui/ViewProviderAssembly.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/17822

Assembly: Pressing Esc while a task is active will not escape edit mode

---

src/Mod/Part/App/Geom2d/ArcOfCircle2dPy.xml
src/Mod/Part/App/Geom2d/ArcOfConic2dPy.xml
src/Mod/Part/App/Geom2d/ArcOfEllipse2dPy.xml
src/Mod/Part/App/Geom2d/ArcOfHyperbola2dPy.xml
src/Mod/Part/App/Geom2d/ArcOfParabola2dPy.xml
src/Mod/Part/App/Geom2d/BSplineCurve2dPy.xml
src/Mod/Part/App/Geom2d/BezierCurve2dPy.xml
src/Mod/Part/App/Geom2d/Circle2dPy.xml
src/Mod/Part/App/Geom2d/Conic2dPy.xml
src/Mod/Part/App/Geom2d/Curve2dPy.xml
src/Mod/Part/App/Geom2d/Ellipse2dPy.xml
src/Mod/Part/App/Geom2d/Geometry2dPy.xml
src/Mod/Part/App/Geom2d/Hyperbola2dPy.xml
src/Mod/Part/App/Geom2d/Line2dPy.xml
src/Mod/Part/App/Geom2d/Line2dSegmentPy.xml
src/Mod/Part/App/Geom2d/Parabola2dPy.xml

In ../src/Mod/Part/App/Geom2d/ I found 17 XML files, 16 of which needed repair as per the GitHub issue. I repaired the tabbing on those 16 files to the 4-spaces no-tab-chars method. Also other minor changes as needed.

Repair XML Files - fixes #10730

---

src/Gui/PythonTracing.cpp

This commit improves the performance of Python code from FreeCAD macros by:
* using the chrono C++ stdlib header instead of QTime
* checking for the elapsed time ONLY every 1000th Python opcode execution
And this commit fixes time measurement by using a monotonic time source instead of a normal one.
The previous implementation using QTime would give a negative time duration if the start time is 23:59:59 and the end time is 00:00:01.
related commit: e78f74b01a44bce0853a847252ec5f33294e1c36

Gui: improve performance of macro execution and fix time measurement

---

src/Mod/Fem/Gui/DlgSettingsFemGmsh.ui
src/Mod/Fem/Gui/DlgSettingsFemGmshImp.cpp
src/Mod/Fem/Gui/DlgSettingsFemGmshImp.h
src/Mod/Fem/femmesh/gmshtools.py

Fixes #17673
Set default value to 3.
@FEA-eng

Fem: Add preference entry to set Gmsh log verbosity - fixes #17673

---

src/App/PropertyStandard.h

App: Set PropertyColor to opaque by default

---

src/Mod/BIM/ArchFence.py

The length  and placement of fence sections was only correct if they were cut to size.
Fixes #16287.

BIM: Fix calculation of fence sections

---

src/Mod/Fem/femmesh/meshtools.py

Fem: Check empty remaining femelements array - fixes #17570

---

src/Mod/Assembly/Gui/ViewProviderAssembly.cpp

Fix joints not being deleted when subassembly is deleted.
Fix https://github.com/FreeCAD/FreeCAD/issues/17929

Assembly: Fix joints not being deleted when subassembly is deleted.

---

src/Mod/Draft/draftgeoutils/fillets.py
src/Mod/Draft/draftguitools/gui_fillets.py

Draft: Allow selection of subelements for Draft_Fillet

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Remove unecessary updateColor and applyCursor.
While doing https://github.com/FreeCAD/FreeCAD/pull/15160 I noticed that some applyCursor and updateColor were unecessary.

Sketcher: ViewProviderSketch remove unecessary updateColor and applyCursor

---

src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h
src/Mod/Sketcher/Gui/EditModeCoinManager.cpp
src/Mod/Sketcher/Gui/EditModeCoinManager.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.h

Squashed and rebased #12319
Fix #8675

[Feature] Sketcher infinite axes

---

src/Gui/Icons/Std_Axis.svg
src/Gui/Icons/Std_Point.svg
src/Gui/Icons/resource.qrc

@chennes
Update Std_Axis.svg as it had poor visibility in dark themes: planes and axis looked both like planes.
Add std_Point.svg for coming points.

Core Datum : Card 1 : icons

---

src/Gui/DlgAbout.cpp

Hi, this should address #15561 .
Let me know if there are any questions.
Thanks!

Change button text to confirm copy.

---

src/App/GeoFeature.cpp

Part 3 of https://github.com/FreeCAD/FreeCAD/pull/16675
Fix a problem of getGlobalPlacement. Nothing to test as the problem happens in later card.

Core: Core datum: Card 3:  GetGlobalPlacement issue

---

src/Gui/PreferencePackManager.cpp

Fixes https://forum.freecad.org/viewtopic.php?p=792813#p792813

Core: Fix unicode path names under Windows

---

src/Gui/propertyeditor/PropertyEditor.h
src/Gui/propertyeditor/PropertyItem.cpp
src/Gui/propertyeditor/PropertyItem.h
src/Gui/propertyeditor/PropertyModel.cpp

Avoid back and forth conversion between std::string and QString

Gui: propertyeditor: minor cleanup

---

src/Base/Tools.cpp
src/Base/Tools.h
src/Ext/freecad/CMakeLists.txt
src/Ext/freecad/utils_zip.py
src/Mod/Mesh/App/Core/MeshIO.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/11189

Mesh: Workaround to load 3mf files not supported by zipios library

---

src/Gui/ActiveObjectList.cpp
src/Mod/PartDesign/CMakeLists.txt
src/Mod/PartDesign/PartDesignTests/TestActiveObject.py
src/Mod/PartDesign/TestPartDesignGui.py

https://forum.freecad.org/viewtopic.php?t=91823

Core: Fix crash active object list

---

src/Mod/Start/App/DisplayedFilesModel.cpp

Fixes https://forum.freecad.org/viewtopic.php?t=92250

Start: Fix extracting thumbnails on Windows

---

src/Gui/ViewProviderFeaturePython.cpp
src/Gui/ViewProviderFeaturePython.h

https://forum.freecad.org/viewtopic.php?t=92468

Gui: Allow to override onBeforeChange in view objects

---

src/Gui/ViewProviderImagePlane.cpp

https://forum.freecad.org/viewtopic.php?t=92438

Gui: Add a new display mode for image without shading

---

src/Gui/BitmapFactory.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/18154

Gui: Support of converting 64-bit images

---

src/Mod/Draft/draftguitools/gui_groups.py

Draft: Sort AutoGroup dropdown menu alphabetically

---

src/Mod/Draft/draftfunctions/svg.py

Forum topic:
https://forum.freecad.org/viewtopic.php?t=92476
For LinkGroups and Links to Std_Groups that do not have a default placement, a temporary hidden document is used to handle the placement of their children. This is a bit of a hack of course.

Draft: fix handling of Links in TD DraftViews

---

src/Mod/Draft/draftguitools/gui_snapper.py

Forum topic:
https://forum.freecad.org/viewtopic.php?t=92281
Apparently the extra scaling for the "xcb" platform is wrong.

Draft: Fix cursor scaling for xcb platform

---

src/Mod/PartDesign/Gui/SketchWorkflow.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/17950

PartDesign: Fix newSketch not working when editing a body an external file

---

src/Mod/Sketcher/Gui/DrawSketchController.h

Fix https://github.com/FreeCAD/FreeCAD/issues/18040

Sketcher: OVP were drawn at wrong position when editing a sketch from link

---

src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_Intersection.svg
src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_Intersection_Constr.svg
src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_Projection.svg
src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_Projection_Constr.svg
src/Mod/Sketcher/Gui/Resources/icons/pointers/Sketcher_Pointer_External.svg
src/Mod/Sketcher/Gui/Resources/icons/pointers/Sketcher_Pointer_External_Intersection.svg

as part of https://github.com/FreeCAD/FreeCAD/pull/17736#issuecomment-2480480362 discussed in merge meeting 2024-11-25

Update Sketcher external icons and cursors

---

src/Mod/Draft/draftguitools/gui_fillets.py
src/Mod/Draft/draftmake/make_fillet.py

In #17945 the delete option of the command results in an error if subobjects are selected.

Draft: Draft_Fillet: fix error in #17945

---

.github/workflows/sub_buildUbuntu2004.yml
.github/workflows/sub_lint.yml
tools/build/Docker/debian.sh
tools/build/Docker/ubuntu.sh

Remove  gts lib

---

src/Gui/MainWindow.cpp

Clean MainWindow.cpp

---

src/Base/PyObjectBase.h

Disable python2 compatibility support.
https://cxx.sourceforge.net/PyCXX-Python2.html

Disable python2 support

---

src/Mod/Draft/draftguitools/gui_hatch.py
src/Mod/Draft/draftutils/params.py

Draft: Display default file and pattern in hatch task panel

---

src/Mod/BIM/ArchComponent.py
src/Mod/BIM/ArchCurtainWall.py
src/Mod/BIM/ArchEquipment.py
src/Mod/BIM/ArchFrame.py
src/Mod/BIM/ArchPanel.py
src/Mod/BIM/ArchPipe.py
src/Mod/BIM/ArchRebar.py
src/Mod/BIM/ArchRoof.py
src/Mod/BIM/ArchSpace.py
src/Mod/BIM/ArchStairs.py
src/Mod/BIM/ArchStructure.py
src/Mod/BIM/ArchTruss.py
src/Mod/BIM/ArchWall.py
src/Mod/BIM/ArchWindow.py

BIM: ensure the Base has the correct type

---

src/Mod/BIM/nativeifc/ifc_tools.py

Small additional fix according to https://github.com/FreeCAD/FreeCAD/pull/16948#issuecomment-2497789211
Fixes #16948

BIM: Set opening name

---

src/Mod/Assembly/CommandCreateView.py

Make ExplodedView: a group extension. So that we don't mimick group. Fixing the delete exploded view group issue. Fixes  https://github.com/FreeCAD/FreeCAD/issues/17902

Assembly: Fix explosion view group deletion issue.

---

tools/build/WindowsInstaller/setup/configure.nsh

Entry is recommended to support the silent uninstall process without knowing the arguments.
https://nsis.sourceforge.io/Add_uninstall_information_to_Add/Remove_Programs#Recommended_values

feat(win): add registry for silent uninstall

---

src/Gui/DlgAddPropertyVarSet.cpp

Fixes #17873.
It has been tested on all property types.

Gui: Fix VarSet dialog 2 digit problem

---

src/Mod/Assembly/CMakeLists.txt
src/Mod/Assembly/CommandInsertLink.py
src/Mod/Assembly/CommandInsertNewPart.py
src/Mod/Assembly/InitGui.py
src/Mod/Assembly/JointObject.py
src/Mod/Assembly/UtilsAssembly.py

Fix https://github.com/FreeCAD/FreeCAD/issues/14464
Video demo : 
https://github.com/user-attachments/assets/60472d64-06ab-47a8-a0ab-2092eea6c39e

Assembly: Insert new part

---

src/Mod/BIM/nativeifc/ifc_import.py

BIM: Fixed lock-unlock mode when opening IFC files

---

src/Mod/BIM/bimcommands/BimArchUtils.py
src/Mod/BIM/importers/exportIFC.py
src/Mod/BIM/nativeifc/ifc_diff.py
src/Mod/BIM/nativeifc/ifc_tools.py

BIM: Added NativeIFC support to Add/remove tools

---

src/Mod/Draft/Resources/ui/TaskPanel_SetStyle.ui
src/Mod/Draft/Resources/ui/dialog_AnnotationStyleEditor.ui
src/Mod/Draft/Resources/ui/preferences-drafttexts.ui

Draft: change position of 'Scale multiplier' field in UI

---

src/Mod/Sketcher/App/SketchObject.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/18304
@maxwxyz trivial fix here I think you can merge it directly.

Sketcher: Fix first external geo deletion failure.

---

src/Mod/Draft/draftguitools/gui_trimex.py

Draft: make Trimex extrude mode link-aware

---

src/App/Color.h
src/Gui/TaskElementColors.cpp

* Also set/get alpha value in setValue/asValue
* Add new static method fromValue

App: Extend/change color API:

---

src/Mod/Fem/Gui/Resources/ui/ElementGeometry1D.ui
src/Mod/Fem/ObjectsFem.py
src/Mod/Fem/femobjects/element_geometry1D.py
src/Mod/Fem/femsolver/calculix/write_femelement_geometry.py
src/Mod/Fem/femtaskpanels/task_element_geometry1D.py

Fem: Add box and elliptical beam section types - fixes #12614

---

src/Mod/Part/JoinFeatures.py

[Mod] clean JoinFeatures.py

---

src/Mod/Import/App/ImportOCAF2.cpp

Clean ElementMap.h

---

src/Mod/CAM/CAMTests/TestCAMSanity.py

imghdr is not used, so do not import it

cam: remove imghdr import

---

src/Mod/BIM/nativeifc/ifc_status.py

BIM: Fixed lock button with no doc

---

.github/workflows/auto-close_stale_issues_and_pull-requests.yml

Add exception for actions/stale to not check and close issues and PRs with the 'no-auto-close' label
Just add the https://github.com/FreeCAD/FreeCAD/labels/no-auto-close label to issues or pull requests and these are ignored by the action. 
@luzpaz @Roy-043 @chennes FYI

Add exception for actions/stale for `no-auto-close` label

---

src/Mod/BIM/ArchBuildingPart.py
src/Mod/BIM/ArchCurtainWall.py
src/Mod/BIM/ArchPanel.py
src/Mod/BIM/ArchWall.py
src/Mod/BIM/ArchWindow.py
src/Mod/BIM/importers/importIFC.py
src/Mod/BIM/importers/importIFCHelper.py
src/Mod/BIM/nativeifc/ifc_tools.py
src/Mod/Draft/draftutils/gui_utils.py

Arch/Draft: Fix transparency vs. alpha issues

---

src/Mod/BIM/nativeifc/ifc_psets.py

BIM: Fixed copy-paste bug in nativeifc psets

---

src/Gui/SoDatumLabel.cpp

Fix Arc length look for angle > pi

---

src/Mod/PartDesign/PartDesignTests/TestHelix.py

PartDesign: fix testGiantHelix*

---

src/Mod/Fem/Gui/DlgSettingsFemElmer.ui
src/Mod/Fem/Gui/DlgSettingsFemElmerImp.cpp
src/Mod/Fem/femcommands/commands.py
src/Mod/Fem/femsolver/elmer/solver.py
src/Mod/Fem/femsolver/elmer/writer.py
src/Mod/Fem/femtest/data/elmer/box_static_0_mm.sif
src/Mod/Fem/femtest/data/elmer/ccxcantilever_faceload_0_mm.sif
src/Mod/Fem/femtest/data/elmer/ccxcantilever_faceload_1_si.sif
src/Mod/Fem/femtest/data/elmer/ccxcantilever_nodeload_0_mm.sif
src/Mod/Fem/femtest/data/elmer/ccxcantilever_prescribeddisplacement_0_mm.sif

Fixes #17569
Add feature request from #17569 as an entry in the properties panel and preferences page.
Also add a property to set the output file as binary or ASCII. With https://github.com/FreeCAD/FreeCAD/pull/16394 it was hard coded as ASCII due to a bug in some third-party library, but is now optional.
@FEA-eng

Fem: Add options for Elmer solver output file - fixes #17569

---

src/Mod/AddonManager/AddonManager.py
src/Mod/AddonManager/AddonManagerTest/gui/test_widget_progress_bar.py
src/Mod/AddonManager/Widgets/addonmanager_widget_progress_bar.py
src/Mod/AddonManager/addonmanager_workers_installation.py
src/Mod/AddonManager/addonmanager_workers_startup.py
src/Mod/AddonManager/package_list.py

This is a small part of a much larger project to pull apart the monolithic main class of the Addon Manager, and to get more of its code under test. This is work towards resolving #7747.

Addon Manager: Refactor progress reporting

---

src/Mod/Fem/femmesh/meshtools.py

FEM: Allow shell faces for tie constraint

---

src/Gui/CMakeLists.txt
src/Gui/Inventor/SoAxisCrossKit.cpp
src/Gui/SoDevicePixelRatioElement.cpp
src/Gui/SoDevicePixelRatioElement.h
src/Gui/SoFCDB.cpp
src/Gui/View3DInventorViewer.cpp
src/Gui/ViewProviderDatum.cpp
src/Gui/ViewProviderLine.cpp
src/Gui/ViewProviderPlane.cpp
src/Gui/ViewProviderPoint.cpp
src/Mod/Assembly/JointObject.py
src/Mod/Assembly/SoSwitchMarker.py
src/Mod/CAM/Gui/ViewProviderPath.cpp
src/Mod/CAM/Path/Dressup/Gui/Tags.py
src/Mod/CAM/Path/Main/Gui/Job.py

@wwmayer 
Fix https://github.com/FreeCAD/FreeCAD/issues/18382

Core: SoShapeScale fix scale issues

---

src/Mod/BIM/nativeifc/ifc_generator.py
src/Mod/BIM/nativeifc/ifc_tools.py

Fixes remaining issues coming from recent transparency/alpha changes and #18298

BIM: Fixes appearance defects

---

src/App/Application.cpp
src/App/PropertyUnits.cpp
src/App/PropertyUnits.h
src/Base/Unit.cpp
src/Base/Unit.h
src/Base/UnitsSchemaInternal.cpp
src/Base/UnitsSchemaMKS.cpp

Necessary to work with magnetic vector potential.

Base: Add electromagnetic potential unit

---

src/Mod/PartDesign/App/FeatureExtrude.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/18425

PD: Fix possible crash in up to shape

---

src/Mod/Assembly/App/AssemblyObject.cpp

[Mod]  Clean AssemblyObject.cpp

---

src/Gui/View3DInventor.h

Gui: Add missing header <optional>

---

src/Base/Tools.cpp
src/Base/Tools.h
src/Gui/View3DInventor.cpp
src/Mod/Spreadsheet/Gui/SheetTableView.cpp

* Fix [-Wsign-compare]
* Fix [-Wc++20-designator]: designated initializers are a C++20 extension
* Fix [-Wunused-parameter]

Fix several compiler warnings:

---

src/Mod/AddonManager/addonmanager_workers_startup.py

Addon Manager: Support case of repo=None in worker

---

src/App/Application.cpp
src/App/Application.h
src/App/Document.cpp
src/App/Document.h
src/App/DocumentObject.cpp
src/App/DocumentObject.h
src/App/DynamicProperty.cpp
src/App/DynamicProperty.h
src/App/Extension.cpp
src/App/Extension.h
src/App/ExtensionContainer.cpp
src/App/ExtensionContainer.h
src/App/PropertyContainer.cpp
src/App/PropertyContainer.h
src/App/PropertyStandard.cpp
src/App/private/DocumentP.h
src/Base/Reader.cpp
src/Base/Reader.h
src/Base/Tools.cpp
src/Base/Tools.h
src/Base/Writer.cpp
src/Base/Writer.h
src/Gui/Document.cpp
src/Gui/ViewProviderLink.cpp
src/Gui/ViewProviderLink.h
src/Mod/Spreadsheet/App/Sheet.cpp
src/Mod/Spreadsheet/App/Sheet.h
tests/src/Base/Tools.cpp

This reverts commit 83202d8ad67a719cb62e29d9dc3496a076999f1f (https://github.com/FreeCAD/FreeCAD/pull/17944) which is causing issues.
Looks like more work needs to be done before we can include it in main branch, see: https://github.com/FreeCAD/FreeCAD/issues/18504
Conflicts:
src/Base/Tools.cpp
src/Base/Tools.h
Kept as Draft until verified to compile (was conflicts)

Revert "Address the poor performance of the existing unique-name generation (#17944)"

---

src/App/Datums.cpp
src/App/Datums.h
src/App/Document.h
src/Gui/CommandDoc.cpp
src/Gui/ViewProviderCoordinateSystem.cpp
src/Gui/ViewProviderCoordinateSystem.h

https://github.com/FreeCAD/FreeCAD/pull/18332/files#r1885663470

Core: Move LCS migration warning to Std_Open command

---

src/Gui/Application.h
src/Gui/ApplicationPy.cpp
src/Gui/DlgPreferencesImp.cpp
src/Gui/DlgPreferencesImp.h
src/Mod/BIM/importers/exportIFC.py
src/Mod/BIM/importers/importIFCHelper.py
src/Mod/Draft/importDXF.py

Original index method retained so any addons are not affected adversely.
See forum report https://forum.freecad.org/viewtopic.php?t=92924
As this was logged by a 1.0 user, please backport.
FYI @Roy-043 @yorikvanhavre

[Gui] Show Preferences page by name rather than index

---

src/Mod/CAM/Path/Post/Processor.py

* Added various docstrings
* Fixed a typo
Merge after #18538

CAM: Linting Path/Post/Processor.py

---

src/Mod/TechDraw/App/DrawLeaderLine.cpp
src/Mod/TechDraw/App/DrawLeaderLine.h
src/Mod/TechDraw/Gui/QGIDecoration.cpp
src/Mod/TechDraw/Gui/QGILeaderLine.cpp
src/Mod/TechDraw/Gui/QGILeaderLine.h
src/Mod/TechDraw/Gui/QGITile.cpp
src/Mod/TechDraw/Gui/QGITile.h
src/Mod/TechDraw/Gui/QGIWeldSymbol.cpp
src/Mod/TechDraw/Gui/QGIWeldSymbol.h
src/Mod/TechDraw/Gui/TaskLeaderLine.cpp
src/Mod/TechDraw/Gui/TaskLeaderLine.h

This PR implements a fix for issue #18094.

[TD]Leader and Welding Symbol (fix #18094)

---

src/Mod/Draft/draftguitools/gui_subelements.py
src/Mod/Draft/draftguitools/gui_trackers.py
src/Mod/Draft/draftutils/gui_utils.py
src/Mod/Draft/draftviewproviders/view_base.py

Fixes #18523.
`find_coin_node` code taken from #18429.

Draft: Fix handling of coin nodes

---

src/Mod/BIM/Arch.py

BIM: add docstrings to Arch.py

---

src/Mod/Fem/Gui/CMakeLists.txt
src/Mod/Fem/Gui/Resources/symbols/ConstraintElectrostaticPotential.iv
src/Mod/Fem/femviewprovider/view_constraint_electrostaticpotential.py

Fem: Add electrostatic constraint symbol

---

src/Mod/BIM/ArchStructure.py

BIM: Fixed structures calculation mode

---

tests/src/App/Property.cpp
tests/src/Base/Reader.cpp
tests/src/Mod/Mesh/App/Importer.cpp

Fixes #18549
Initialize xerces sub-system in order to parse XML files

Test: Support of parallel execution of reader tests

---

src/Mod/Drawing/App/DrawingExport.cpp

[Mod] clean code

---

src/Mod/BIM/Resources/ui/dialogWelcome.ui

Puts the texts in a scrollable frame
supersedes #17393

BIM: Added frame to welcome dialog

---

src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp

smesh: Fix build failure with vtk 9.4

---

src/Mod/Fem/CMakeLists.txt
src/Mod/Fem/Gui/DlgSettingsFemCcx.ui
src/Mod/Fem/Gui/DlgSettingsFemCcxImp.cpp
src/Mod/Fem/Gui/DlgSettingsFemGmsh.ui
src/Mod/Fem/Gui/DlgSettingsFemGmshImp.cpp
src/Mod/Fem/Gui/Resources/ui/DlgSettingsNetgen.ui
src/Mod/Fem/InitGui.py
src/Mod/Fem/femmesh/gmshtools.py
src/Mod/Fem/femmesh/netgentools.py
src/Mod/Fem/femobjects/mesh_netgen.py
src/Mod/Fem/fempreferencepages/__init__.py
src/Mod/Fem/fempreferencepages/dlg_settings_netgen.py
src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py

There are 6 levels of verbosity, the same as those in Netgen graphical interface.
The code is also executed in a temporary script using the Python executable directly instead of the FreeCAD interpreter. This generates a small speed-up in the process since it avoids loading the Fem modules.
@FEA-eng

Fem: Add preference entry to set Netgen (new implementation) log verbosity and number of threads for meshing

---

src/Mod/TechDraw/Gui/QGIDecoration.cpp
src/Mod/TechDraw/Gui/QGISectionLine.cpp
src/Mod/TechDraw/Gui/TaskSectionView.cpp
src/Mod/TechDraw/Gui/TaskSectionView.h

This PR implements a fix for issue #17831.

[TD]Section line and rotation fix 17831

---

src/Mod/TechDraw/App/Preferences.cpp

This PR implements a fix for issue #18694) reported here: https://forum.freecad.org/viewtopic.php?t=93205

[TD]fix highlight style preference (fix #18694)

---

src/Mod/Fem/femtools/checksanalysis.py

define a shell thicknesses -->  define shell thicknesses

FEM: Fix small typo in another error message

---

src/Mod/Measure/App/AppMeasurePy.cpp
src/Mod/Measure/App/CMakeLists.txt
src/Mod/Measure/App/Measurement.cpp
src/Mod/Measure/App/ShapeFinder.cpp
src/Mod/Measure/App/ShapeFinder.h
src/Mod/Measure/App/SubnameHelper.cpp
src/Mod/Measure/App/SubnameHelper.h
src/Mod/TechDraw/App/DimensionAutoCorrect.cpp
src/Mod/TechDraw/App/DimensionReferences.cpp
src/Mod/TechDraw/App/DimensionReferences.h
src/Mod/TechDraw/App/DrawViewDimension.cpp
src/Mod/TechDraw/App/DrawViewDimension.h
src/Mod/TechDraw/App/ShapeExtractor.cpp
src/Mod/TechDraw/App/ShapeExtractor.h
src/Mod/TechDraw/Gui/DimensionValidators.cpp
src/Mod/TechDraw/Gui/DimensionValidators.h

This PR implements a fix for issue #13375.

[TD]Long and link dim refs (fix #13375)

---

src/Gui/ViewProviderCoordinateSystem.cpp
src/Gui/ViewProviderCoordinateSystem.h
src/Gui/ViewProviderDatum.cpp
src/Gui/ViewProviderDatum.h
src/Gui/ViewProviderLine.cpp
src/Gui/ViewProviderLine.h
src/Gui/ViewProviderPlane.cpp
src/Gui/ViewProviderPlane.h
src/Mod/Part/parttests/ColorTransparencyTest.py
src/Mod/PartDesign/Gui/TaskFeaturePick.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/18337
https://github.com/user-attachments/assets/5290eb29-6d1d-4c11-80c8-4c4c46a7fa36

Core datums: Rework to improve new sketch.

---

src/Mod/BIM/ArchRebar.py

Fixes: https://github.com/amrit3701/FreeCAD-Reinforcement/issues/223

BIM: fixes stirrups placement in ifc export

---

src/Gui/Stylesheets/FreeCAD Dark.qss
src/Gui/Stylesheets/FreeCAD Light.qss

Stylesheets spreadsheets visual fix.

---

src/Mod/Fem/App/FemMeshObject.cpp
src/Mod/Fem/App/FemMeshObject.h
src/Mod/Fem/Gui/ViewProviderFemMesh.cpp
src/Mod/Fem/Gui/ViewProviderFemMesh.h
src/Mod/Fem/femmesh/gmshtools.py
src/Mod/Fem/femmesh/netgentools.py
src/Mod/Fem/femobjects/base_femelement.py
src/Mod/Fem/femobjects/base_femmeshelement.py
src/Mod/Fem/femobjects/material_common.py
src/Mod/Fem/femobjects/material_mechanicalnonlinear.py
src/Mod/Fem/femtools/checksanalysis.py
src/Mod/Fem/femtools/membertools.py
src/Mod/Fem/femviewprovider/view_base_femelement.py
src/Mod/Fem/femviewprovider/view_base_femmaterial.py
src/Mod/Fem/femviewprovider/view_base_femmeshelement.py

Fem: Add suppressible extension to objects - fixes #12115

---

src/Mod/OpenSCAD/OpenSCAD2Dgeom.py

Clean OpenSCAD2Dgeom.py

---

src/Gui/DlgPreferencesImp.cpp

It still must be checked if the crash in #18747 will be fixed.

Gui: Check for exising layout before accessing it

---

src/Mod/TechDraw/App/DrawViewAnnotation.cpp
src/Mod/TechDraw/App/DrawViewAnnotation.h
src/Mod/TechDraw/App/DrawViewImage.cpp
src/Mod/TechDraw/App/DrawViewImage.h
src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp
src/Mod/TechDraw/App/DrawViewSpreadsheet.h
src/Mod/TechDraw/Gui/CMakeLists.txt
src/Mod/TechDraw/Gui/Command.cpp
src/Mod/TechDraw/Gui/CommandAnnotate.cpp
src/Mod/TechDraw/Gui/CommandDecorate.cpp
src/Mod/TechDraw/Gui/CommandHelpers.cpp
src/Mod/TechDraw/Gui/CommandHelpers.h
src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
src/Mod/TechDraw/Gui/QGSPage.cpp
src/Mod/TechDraw/Gui/QGSPage.h
src/Mod/TechDraw/Gui/ViewProviderBalloon.cpp
src/Mod/TechDraw/Gui/ViewProviderBalloon.h
src/Mod/TechDraw/Gui/ViewProviderDimension.cpp
src/Mod/TechDraw/Gui/ViewProviderDimension.h
src/Mod/TechDraw/Gui/ViewProviderLeader.cpp
src/Mod/TechDraw/Gui/ViewProviderProjGroup.cpp
src/Mod/TechDraw/Gui/ViewProviderProjGroup.h
src/Mod/TechDraw/Gui/ViewProviderRichAnno.cpp
src/Mod/TechDraw/Gui/ViewProviderRichAnno.h
src/Mod/TechDraw/Gui/ZVALUE.h

This PR implements a fix for issue #18283.   It also includes similar fixes for image, simple annotation and spreadsheet views.

[TD]Fix RichText parent in scene (fix #18283)

---

src/Mod/Draft/draftmake/make_sketch.py

Fixes #18713.
The code follows the suggestion by imm/webmite:
https://forum.freecad.org/viewtopic.php?p=799014#p799014
@webmite Thank you.

Draft: fix axis calculation in make_sketch

---

src/Mod/Draft/DraftGui.py

See:
https://forum.freecad.org/viewtopic.php?t=93682

Draft: fix selection for FacebinderTaskPanel

---

src/Mod/Part/Gui/Command.cpp

Part: Rename new datum commands

---

src/Gui/PreferencePacks/Dark behave/Dark behave.cfg
src/Gui/PreferencePacks/FreeCAD Classic/FreeCAD Classic.cfg
src/Gui/PreferencePacks/FreeCAD Dark/FreeCAD Dark.cfg
src/Gui/PreferencePacks/FreeCAD Light/FreeCAD Light.cfg
src/Mod/Draft/Resources/ui/preferences-draftsnap.ui

Draft (and Pref Packs): fix snapcolor

---

src/Mod/BIM/importers/importDAE.py

There was some mention of color in the original code but it was not working on my system. The first commit fixes this.
Can be tested with [blue_cube.dae.zip](https://github.com/user-attachments/files/18360265/blue_cube.dae.zip).
The following commits improve the code by different manners and are not completely related. I can split them away if required.

BIM: Colors in DAE import + code improvements

---

src/Mod/BIM/ArchRoof.py

Fixes #19013.
* Check direction of plane axis with a tolerance.
* Check the produced solids. Notably check for a min. volume. Required for solids created from non-planar faces.
* Apply placement to created compound.

BIM: improve roof getSubVolume function

---

src/App/Branding.cpp
src/Main/MainGui.cpp

This was used by Ondsel. But it looks like it could benefit others as well.
@adrianinsaval can you please confirm or not? Feel free to close if this should not be in main.

Extend branding options

---

src/Mod/Sketcher/Gui/DrawSketchController.h
src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h

* Handle exceptions in onViewValueChanged
* Handle undefined values in calculateThroughPointMinorAxisParameters

Fix issues in ellipse creation

---

src/Mod/BIM/importers/exportIFC.py

BIM: Fixed late global declaration

---

src/Gui/CMakeLists.txt
src/Gui/NavigationStyle.cpp
src/Gui/NavigationStyle.h
src/Gui/NavigationStylePy.xml
src/Gui/NavigationStylePyImp.cpp
src/Gui/View3DViewerPy.cpp
src/Gui/View3DViewerPy.h

As is, it's not very useful, but a following PR will introduce functionality.

Gui: Bind `NavigationStyle` to Python.

---

src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h
src/Mod/Sketcher/App/planegcs/GCS.cpp
src/Mod/Sketcher/App/planegcs/GCS.h
tests/src/Mod/Sketcher/App/SketchObject.cpp

Done as [a grant by the FPA](https://github.com/FreeCAD/FPA-grant-proposals/issues/6).
Refactors some more methods with tests. Some other changes are relatively straightforward so I'm willing to let them be merged without tests.

 [Sketcher] Round 2 of refactors 

---

src/Mod/PartDesign/Gui/Workbench.cpp

@maxwxyz 
Fix https://github.com/FreeCAD/FreeCAD/issues/19095

PartDesign: replace part design datum commands by the core ones

---

src/Gui/NavigationStyle.cpp

Fixes #18909.
Could be back ported.

Gui: Fix camera position shift when starting rotation

---

src/Mod/Fem/Gui/Resources/ui/MaterialReinforcement.ui
src/Mod/Fem/femexamples/rc_wall_2d.py
src/Mod/Fem/femobjects/material_common.py
src/Mod/Fem/femobjects/material_reinforced.py
src/Mod/Fem/femtaskpanels/task_material_common.py
src/Mod/Fem/femtaskpanels/task_material_reinforced.py

Fem: Use new material editor in Reinforced material task panel - fixes #18692

---

src/Gui/ViewProviderCoordinateSystem.cpp
src/Gui/ViewProviderCoordinateSystem.h
src/Gui/ViewProviderPlane.cpp
src/Gui/ViewProviderPlane.h
src/Mod/PartDesign/Gui/TaskFeaturePick.cpp
src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
src/Mod/PartDesign/Gui/TaskLinearPatternParameters.cpp
src/Mod/PartDesign/Gui/TaskMirroredParameters.cpp
src/Mod/PartDesign/Gui/TaskPolarPatternParameters.cpp
src/Mod/PartDesign/Gui/TaskPrimitiveParameters.cpp
src/Mod/PartDesign/Gui/TaskRevolutionParameters.cpp

* const correctness in ViewProviderPlane
* Reduce code duplication in ViewProviderCoordinateSystem
* Reduce cognitive complexity of ViewProviderCoordinateSystem::setTemporaryVisibility
* Use bitmask instead of three booleans in setTemporaryVisibility to improve readability

Datum fixes

---

src/Mod/Draft/importDXF.py

Draft: DXF export: add handling of text justification

---

src/Mod/Part/App/Datums.cpp

Part: Fix wrong attachment of datum lines

---

src/Mod/Draft/DraftGui.py

* The updateSnapper function did not work properly.
* Added display_point_active attribute to prevent the displayPoint function from triggering the changeXValue etc. functions. This would lead to a loss of accuracy as the displayed rounded values would be read from the inputboxes.

Draft: DraftGui.py fix updateSnapper and implement display_point_active

---

src/Mod/BIM/ArchSchedule.py

BIM: Fix BIM Schedule

---

src/Mod/BIM/bimcommands/BimLayers.py
src/Mod/Draft/draftguitools/gui_layers.py

The code should not add the LinePrintColor property. That should be done elsewhere.

Draft and BIM: Layer manager minor code improvements

---

src/Mod/Fem/femviewprovider/view_constraint_bodyheatsource.py
src/Mod/Fem/femviewprovider/view_constraint_centrif.py
src/Mod/Fem/femviewprovider/view_constraint_currentdensity.py
src/Mod/Fem/femviewprovider/view_constraint_electrostaticpotential.py
src/Mod/Fem/femviewprovider/view_constraint_flowvelocity.py
src/Mod/Fem/femviewprovider/view_constraint_initialflowvelocity.py
src/Mod/Fem/femviewprovider/view_constraint_initialpressure.py
src/Mod/Fem/femviewprovider/view_constraint_magnetization.py
src/Mod/Fem/femviewprovider/view_constraint_sectionprint.py
src/Mod/Fem/femviewprovider/view_constraint_tie.py
src/Mod/Fem/femviewprovider/view_element_fluid1D.py
src/Mod/Fem/femviewprovider/view_element_geometry1D.py
src/Mod/Fem/femviewprovider/view_element_geometry2D.py
src/Mod/Fem/femviewprovider/view_material_common.py
src/Mod/Fem/femviewprovider/view_material_reinforced.py
src/Mod/Fem/femviewprovider/view_mesh_boundarylayer.py
src/Mod/Fem/femviewprovider/view_mesh_group.py
src/Mod/Fem/femviewprovider/view_mesh_region.py
src/Mod/Fem/femviewprovider/view_result_mechanical.py
src/Mod/Fem/femviewprovider/view_solver_ccxtools.py

@chennes, @maxwxyz Could any of you please merge this? It resolves the assertion reported in https://github.com/FreeCAD/FreeCAD/pull/19011#issuecomment-2607022774
@FEA-eng

Fem: return from Python setEdit methods

---

src/Mod/Draft/DraftGui.py

Draft: DraftGui.py fix displayPoint

---

src/Mod/OpenSCAD/importCSG.py

Clean  importCSG.py

---

src/Mod/Sketcher/App/planegcs/GCS.cpp

Sketcher: fix seg-fault on loading sketch with redundant constraints

---

src/Gui/PreferencePacks/FreeCAD Classic/FreeCAD Classic.cfg

PrefPacks: Add spreadsheet colors to classic theme

---

src/Mod/BIM/ArchWall.py

Forum Discussion
- https://forum.freecad.org/viewtopic.php?t=93610&start=10#p806296
Github Issues
- https://github.com/FreeCAD/FreeCAD/issues/19147#issuecomment-2607946858

[ArchWall]  Fix Regression Single-edge Wall w/ Multi-Material

---

src/Mod/TechDraw/Gui/TaskProjGroup.cpp
src/Mod/TechDraw/Gui/ViewProviderProjGroup.cpp
src/Mod/TechDraw/Gui/ViewProviderProjGroup.h

This PR implements a fix for issue #19085.

[TD]fix front view position in projection group (fix #19085)

---

src/Gui/MainWindow.cpp

Resolves https://github.com/FreeCAD/FreeCAD/issues/18820

Gui: show tooltips when window is not focused

---

src/Base/UnitsSchemaMeterDecimal.cpp

This PR implements a fix for issue #18839.

[Units]fix bad length multiplier in MeterDecimal

---

src/Mod/Draft/importDXF.py

The Group property of the 'new' layer object is not an attribute of its Proxy.

Draft: remove faulty code from importDXF.py

---

src/Mod/Draft/Resources/ui/preferences-draftsnap.ui

Draft: Increase max value for gridEvery in ui.

---

src/Mod/Draft/draftfunctions/svg.py

Draft: fix handling of annotation Links in TD DraftViews

---

src/Mod/PartDesign/App/FeatureHelix.cpp

Fixed typo/spelling error in tooltip.

Helix tooltip spelling update in FeatureHelix.cpp

---

src/Ext/freecad/utils.py

The comment was not updated when this method was moved out of the AddonManager. No code change.

Ext: Correct user preference specified in comment

---

contrib/clion/pixi/pixi-default.bash
contrib/clion/pixi/pixi-default.bat

@oursland, I have added my CLion toolchain script and some instructions as you requested :smiley:. For now I only have a script for Linux but it should work similar on other systems.

Add CLion pixi toolchain script

---

src/Gui/Inventor/SoAxisCrossKit.cpp
src/Gui/NaviCube.cpp
src/Gui/NaviCube.h
src/Gui/PreferencePackTemplates/View.cfg
src/Gui/PreferencePages/DlgSettings3DView.ui
src/Gui/PreferencePages/DlgSettings3DViewImp.cpp
src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h
src/Gui/View3DSettings.cpp
src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.cpp
src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h

Partiarlly fixes #12208
Make axis colors user definable

[Gui] Axis colors changeable

---

src/Mod/BIM/importers/importWebGL.py

Hi, 
This PR closes #18792 with the encoding fix on write. 
Also I think its fast enough (in my previous PR too) to close #9805 .
In the first commit I upgrade threejs to its latest version as of writing (0.172.0)
In the second commit I've added the ability to show/hide objects based on either a tick box or double clicking which removes a TODO in the code
In the third commit I fix the non compressed reading of the data in javascript which wasnt caught before.
Thanks, and any changes you would like please let me know

BIM: Webgl threejs upgrade , add hiding shape option, fix uncompressed read

---

src/Mod/Draft/DraftGui.py

Draft: Avoid setRadiusValue error message

---

src/Mod/AddonManager/addonmanager_python_deps_gui.py

Replaces #18634 so may fix #18645

Addon Manager: Use FreeCAD QUiLoader wrapper when available

---

src/Mod/AddonManager/AddonManagerTest/app/test_dependency_installer.py
src/Mod/AddonManager/addonmanager_dependency_installer.py
src/Mod/AddonManager/addonmanager_installer_gui.py
src/Mod/AddonManager/addonmanager_python_deps_gui.py
src/Mod/AddonManager/addonmanager_utilities.py

Also fixes some UI issues when installing dependencies fails, and increases the pip installation timeout to two minutes (user-interruptable before then).

Addon manager: pip on snap fix

---

src/Mod/Draft/draftobjects/shape2dview.py

Git-hub issues : https://github.com/FreeCAD/FreeCAD/issues/16363#issuecomment-2619643946
"Problem description
In a group of closed walls, the entire interior is completely filled, which should not be the case."

[Draft_shape2dview]  Fix Bug : Closed Wall Wrong Fill

---

src/Mod/Fem/femsolver/calculix/write_femelement_material.py

Fixes #19375
@maxwxyz Without this check, thermal analysis is unusable.
@FEA-eng

Fem: Check reference temperature - fixes #19375

---

src/Gui/QSint/actionpanel/actionpanel.cpp
src/Gui/QSint/actionpanel/freecadscheme.cpp
src/Gui/QSint/actionpanel/freecadscheme.h

This reverts commit 537ad0fd7ac70df626053ad2539114f5ec50f549.
As discussed here: https://github.com/FreeCAD/FreeCAD/pull/19261#issuecomment-2620251106
@alfrix @adrianinsaval  FYI

Revert classic change backport

---

src/Mod/Draft/draftobjects/hatch.py

Draft: improved handling of 'crazy' edges in hatch

---

src/Base/Interpreter.cpp
src/Gui/Selection/Selection.h
src/Gui/View3DInventorViewer.cpp
src/Gui/ViewProvider.cpp
src/Gui/ViewProvider.h
src/Gui/ViewProviderExtension.h
src/Gui/ViewProviderLink.cpp
src/Gui/ViewProviderLink.h
src/Mod/BIM/ArchBuildingPart.py
src/Mod/BIM/bimcommands/BimViews.py
src/Mod/Draft/draftguitools/gui_trackers.py

Just some code cleanups that don't deserve their own PR

Gui: General code cleanups

---

src/Mod/Material/CMakeLists.txt
src/Mod/Material/Resources/Materials/Standard/Thermoplast/PC-Molded.FCMat

Addition of the polycarbonate material physical property. Before, there was no such material property.

Material: Add the polycarbonate material physical property #19431

---

src/Mod/Draft/draftobjects/wire.py

Draft: Fix line length input issue

---

src/Mod/AddonManager/AddonManagerTest/gui/test_change_branch.py
src/Mod/AddonManager/addonmanager_freecad_interface.py
src/Mod/AddonManager/addonmanager_package_details_controller.py
src/Mod/AddonManager/addonmanager_utilities.py
src/Mod/AddonManager/change_branch.py

Add some error checking and handling to the branch change process. Also implements a few tests for the GUI flow to ensure the dialogs open when expected, and the signal gets emitted. Lots of room for more tests here.

Addon manager: change branch cleanup

---

src/Mod/Draft/draftobjects/shapestring.py

Draft: add some checks for font file of shapestring

---

src/Gui/CommandDoc.cpp

This commit merely fixes the crash.

Assembly: Fix the crash described in #18475

---

src/Mod/BIM/ArchPanel.py
src/Mod/BIM/nativeifc/ifc_viewproviders.py

https://forum.freecad.org/viewtopic.php?t=94657

BIM: Panel does not require a Base

---

src/Mod/Draft/draftfunctions/downgrade.py
src/Mod/Draft/draftobjects/array.py
src/Mod/Draft/draftobjects/draftlink.py
src/Mod/Draft/draftobjects/patharray.py
src/Mod/Draft/draftobjects/pathtwistedarray.py
src/Mod/Draft/draftobjects/pointarray.py

Fixes #13085.
This PR adds the `PlacementList` property to non-link arrays.

Draft: make arrays explodable

---

src/Mod/Sketcher/App/SketchObject.cpp

Code clean 
small optimization

clean SketchObject.cpp

---

src/Mod/TechDraw/App/DrawUtil.cpp
src/Mod/TechDraw/App/DrawUtil.h
src/Mod/TechDraw/Gui/AppTechDrawGui.cpp
src/Mod/TechDraw/Gui/CMakeLists.txt
src/Mod/TechDraw/Gui/CommandAlign.cpp
src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
src/Mod/TechDraw/Gui/DrawGuiUtil.h
src/Mod/TechDraw/Gui/QGIVertex.cpp
src/Mod/TechDraw/Gui/QGIVertex.h
src/Mod/TechDraw/Gui/QGIView.cpp
src/Mod/TechDraw/Gui/QGIView.h
src/Mod/TechDraw/Gui/Workbench.cpp

[TechDraw] Align points to direction by rotation

---

src/Mod/Draft/drafttaskpanels/task_scale.py

See:
https://forum.freecad.org/viewtopic.php?t=94748

Draft: task_scale.py fix circular imports

---

src/Mod/BIM/bimcommands/BimTDPage.py

See: https://github.com/FreeCAD/FreeCAD/issues/19466#issuecomment-2648176158
Fixes: https://github.com/FreeCAD/FreeCAD/issues/19466

BIM: fix ability to cancel file dialog on BIM_TDPage command

---

src/App/ComplexGeoDataPy.xml
src/App/DocumentObjectPy.xml
src/App/DocumentPy.xml
src/App/GroupExtensionPy.xml
src/App/MetadataPy.xml
src/App/MetadataPyImp.cpp
src/App/PropertyContainerPy.xml
src/App/StringIDPy.xml

Just some cleanups to XML binding files in App, mostly documentation whitespace and typing issues.

App: Clean up XML bindings.

---

src/Mod/TechDraw/App/Preferences.cpp

TechDraw: Set symbol dir

---

src/Mod/CAM/App/Area.cpp
src/Mod/Part/App/FuzzyHelper.cpp
src/Mod/Part/App/FuzzyHelper.h

Fixes https://github.com/FreeCAD/FreeCAD/issues/17748

CAM: Fix finish passes by avoiding fuzzy in Area.cpp

---

src/Gui/QSint/actionpanel/freecadscheme.cpp

while testing, i found that i have broken the transparency feature with [#19261](https://github.com/FreeCAD/FreeCAD/pull/19261)
setting the background color fixes it
sorry for the inconvenience

fix: linux Freecad classic hotfix

---

src/Gui/LinkViewPy.xml
src/Gui/ViewProviderGeometryObjectPy.xml
src/Gui/ViewProviderPy.xml

Just some cleanups to XML binding files in Gui, mostly documentation whitespace and typing issues.

Gui: Clean up XML bindings.

---

src/Mod/Part/App/FCBRepAlgoAPI_BooleanOperation.cpp
src/Mod/Part/App/FCBRepAlgoAPI_BooleanOperation.h
src/Mod/Part/parttests/TopoShapeTest.py

Closes https://github.com/FreeCAD/FreeCAD/pull/17530
This is same PR but with one commit that remove lint warnings

Part: OCCWrapper: Fix compound cuts

---

src/Mod/Part/App/ArcOfParabolaPy.xml
src/Mod/Part/App/AttachExtensionPy.xml
src/Mod/Part/App/BRepOffsetAPI_MakeFillingPy.xml
src/Mod/Part/App/BRepOffsetAPI_MakePipeShellPy.xml
src/Mod/Part/App/BSplineCurvePy.xml
src/Mod/Part/App/BSplineCurvePyImp.cpp
src/Mod/Part/App/BSplineSurfacePy.xml
src/Mod/Part/App/BezierCurvePy.xml
src/Mod/Part/App/BezierSurfacePy.xml
src/Mod/Part/App/ConePy.xml
src/Mod/Part/App/ConicPy.xml
src/Mod/Part/App/CylinderPy.xml
src/Mod/Part/App/EllipsePy.xml
src/Mod/Part/App/GeometryCurvePy.xml
src/Mod/Part/App/GeometryPy.xml
src/Mod/Part/App/GeometrySurfacePy.xml
src/Mod/Part/App/HyperbolaPy.xml
src/Mod/Part/App/ParabolaPy.xml
src/Mod/Part/App/RectangularTrimmedSurfacePy.xml
src/Mod/Part/App/TopoShapeEdgePy.xml
src/Mod/Part/App/TopoShapeFacePy.xml
src/Mod/Part/App/TopoShapePy.xml
src/Mod/Part/App/TopoShapeShellPy.xml
src/Mod/Part/App/TopoShapeSolidPy.xml
src/Mod/Part/App/TopoShapeSolidPyImp.cpp
src/Mod/Part/App/TopoShapeWirePy.xml

Just some cleanups to XML binding files in Part, mostly documentation whitespace and typing issues.

Part: Clean up XML bindings.

---

src/Base/Parameter.h

[ Doxygen ] Improved Param Group Subgroup Methods

---

src/Gui/CMakeLists.txt
src/Gui/Inventor/SoFCTransform.cpp
src/Gui/Inventor/SoFCTransform.h
src/Gui/SoFCDB.cpp
src/Gui/ViewProvider.cpp

Backports https://github.com/FreeCAD/FreeCAD/pull/17800
Collisions where only imports and cmake file paths.
If CI works it should be good to go
Have not tested it, as I need pixi to build locally

Backport: Core: Implement SoFCTransform node

---

src/Mod/BIM/bimcommands/BimSetup.py

That was not nice of BIM :confounded:
Fixes #19163

BIM: Do not change important pref options without user's consent

---

README.md

The current link is invalid. I found a working one on reddit and changed it https://www.reddit.com/r/FreeCAD/comments/1g94gec/discord_server/

readme: fix discord invite

---

cMake/FindOCC.cmake
cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake

Remove OpenCascade Community Edition

---

src/Mod/AddonManager/addonmanager_utilities.py

Take two (or maybe three?). Trying to work with @furgo16 and @Syres916 to come up with a solution that covers Snaps and AppImages. I think this does it...

Addon Manager: Fix pip usage on Snap and Appimage

---

src/Mod/TechDraw/Gui/QGIViewDimension.cpp
src/Mod/TechDraw/Gui/ViewProviderDimension.cpp
src/Mod/TechDraw/Gui/ViewProviderDimension.h

This PR implements a fix for issue #19476.

[TD]Default arrow style overrides feature

---

src/Mod/TechDraw/Gui/ViewProviderPage.cpp
src/Mod/TechDraw/Gui/ViewProviderPage.h

This PR implements a fix for issue #19434.

[TD]Fix page maximized on insert view

---

src/Mod/TechDraw/Gui/DlgPageChooser.cpp
src/Mod/TechDraw/Gui/DlgPageChooser.h
src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
src/Mod/TechDraw/Gui/DrawGuiUtil.h

This PR implements a fix for issue #19657.

[TD]Warn on no page for insert view

---

src/Mod/TechDraw/Gui/QGSPage.cpp

-removed unused variable
-clean code

clean QGSPage.cpp

---

src/Mod/Fem/App/AppFemPy.cpp
src/Mod/Fem/App/FemVTKTools.cpp
src/Mod/Fem/App/FemVTKTools.h

Create `vtkMutiBlockDataSet` `.vtm` file from `.frd` CalculiX result file.
each step/frame and type of analysis is saved in an `vtkUnstructuredGrid`.
It remains to add predefined calculations (principal stresses, etc...).
@FEA-eng , @ickby

Fem: Add frd format converter to VTK

---

src/Base/Parameter.h

[ Doxygen ] Improved Parameter Group - Copy & Insert

---

src/3rdParty/json/single_include/nlohmann/json.hpp
src/3rdParty/json/single_include/nlohmann/json_fwd.hpp

-Serialize empty tuple into '[]'
-Optimize binary get_number implementation by reading multiple bytes at once 
-fix integer parsed as float when EINTR set in errno

updated json lib

---

tools/build/AppImage/build-with-conda.sh

Fix freecad version into  build-with-conda.sh

Conda:Update  freecad  version 

---

src/Gui/NaviCube.cpp
src/Gui/Navigation/NavigationAnimation.cpp
src/Gui/Navigation/NavigationAnimation.h
src/Gui/Navigation/NavigationStyle.cpp
src/Gui/Navigation/NavigationStyle.h
src/Gui/View3DInventorViewer.cpp
src/Gui/View3DInventorViewer.h

Fixes #17396 
https://github.com/user-attachments/assets/1f437dd4-35c8-4c91-8fbe-077b8339a608

Gui: Accumulate orientation for NaviCube flat button animations

---

src/Gui/Selection/SelectionObserverPython.cpp
src/Gui/Selection/SelectionObserverPython.h

Introduced in https://github.com/FreeCAD/FreeCAD/pull/19084

Gui: Fix regression in `SelectionObserverPython::removeObserver`.

---

src/3rdParty/3Dconnexion/inc/SpaceMouse/CCookieCollection.hpp
src/Mod/TechDraw/Gui/QGIDatumLabel.cpp

TD: Adding missing PCH include

---

src/Mod/Draft/draftguitools/gui_base_original.py

My bad. Goes to show that even 'simple' PRs must be tested.

Draft: Fix error in #19738

---

src/Mod/AddonManager/AddonManagerTest/app/test_dependency_installer.py
src/Mod/AddonManager/addonmanager_dependency_installer.py
src/Mod/AddonManager/addonmanager_freecad_interface.py
src/Mod/AddonManager/addonmanager_installer_gui.py
src/Mod/AddonManager/addonmanager_utilities.py
src/Mod/AddonManager/manage_python_dependencies.py

Also fixes various issues with dependency updater. V1.0.1 backport of #19766 and #19384.

Addon Manager (1.0 backport): Fix pip on Snap and AppImage

---

src/Mod/BIM/nativeifc/ifc_tools.py

Clean ifc_tools.py

---

src/Mod/BIM/bimcommands/BimShape2DView.py

GitHub Issue - https://github.com/FreeCAD/FreeCAD/issues/18947

[BimShape2DView]  Bug-Fix : Shape2DCut Not Working

---

src/Mod/Fem/CMakeLists.txt
src/Mod/Fem/Gui/Command.cpp
src/Mod/Fem/Gui/Resources/Fem.qrc
src/Mod/Fem/Gui/Resources/icons/FEM_EquationStaticCurrent.svg
src/Mod/Fem/Gui/Resources/ui/CurrentDensity.ui
src/Mod/Fem/ObjectsFem.py
src/Mod/Fem/femcommands/commands.py
src/Mod/Fem/femobjects/constraint_currentdensity.py
src/Mod/Fem/femsolver/elmer/equations/staticcurrent.py
src/Mod/Fem/femsolver/elmer/equations/staticcurrent_writer.py
src/Mod/Fem/femsolver/elmer/writer.py
src/Mod/Fem/femsolver/equationbase.py
src/Mod/Fem/femtaskpanels/task_constraint_currentdensity.py
src/Mod/Fem/femtest/app/test_object.py

Add support for Elmer static current solver.
A new property `NormalCurrentDensity` is added to the CurrentDensity boundary condition.
By setting property `HeatSource` to `True` this solver can work in combination with the heat equation using the Joule heating as heat source.
Fixes #11895
@FEA-eng

Fem: Add support for Elmer static current solver - fixes #11895

---

src/App/CMakeLists.txt
src/App/Document.cpp
src/App/DocumentObject.cpp
src/App/DocumentObject.h
src/App/PropertyLinks.cpp
src/App/Transactions.cpp
src/App/private/DocumentP.h

Does not compile due to a syntax error in the code anyway, so I guess no one cares about it.

App: Remove old DAG implementation.

---

src/Mod/Spreadsheet/TestSpreadsheet.py

This is a continuation of @bofdahof's PR. In addition of those changes, this also splits up the setup code into the tests to improve clarity of the tests.
Closes https://github.com/FreeCAD/FreeCAD/pull/19269

Spreadsheet: Break down large tests into smaller units

---

src/Mod/Draft/draftguitools/gui_edit.py

Draft: fix Draft_Edit issue with Gesture navigation

---

src/Gui/Inventor/SoFCPlacementIndicatorKit.cpp
src/Mod/Spreadsheet/App/Sheet.cpp

A couple of recently-merged PRs interacted in unexpected ways, creating compilation failures. These two commits address those.

Misc. compilation fixes

---

src/Gui/QtAll.h

Fixes MSVC compilation after merge of #19626

Gui: Add QOpenGLWidget to QtAll.h

---

src/Mod/Draft/DraftGui.py

Fixes #19961
Regression caused by #19179.

Draft: fix polar coords regression

---

src/Mod/Draft/draftguitools/gui_rotate.py

Fixes #19690
The issue was caused by a zero distance between the center and the point picked for the rotation angle.

Draft: fix NaN issue with Draft_Rotate

---

src/Mod/Spreadsheet/Gui/ZoomableView.h

This is a cherry-pick from https://github.com/FreeCAD/FreeCAD/pull/19934

[Spreadsheet] Fix unset zoom level

---

src/Mod/TechDraw/App/DrawBrokenView.cpp
src/Mod/TechDraw/App/DrawBrokenView.h

This PR implements a fix for issue #19647.

Broken view no compress19647

---

src/Mod/TechDraw/App/PreCompiled.h

TD: Add missing Boost headers to PCH

---

src/Mod/Draft/draftguitools/gui_trimex.py

Draft: fix Trimex visibility change

---

src/Mod/AddonManager/update_all.ui

@maxwxyz can you see if this fixes #19973?

Addon Manager: Adjust use of QDialogButtonBox

---

.github/workflows/sub_lint.yml
tools/lint/generic_checks.py
tools/lint/utils.py

This PR introduces utilities for linting and converts the generic checks we have to Python.

CI: Refactor generic whitespace checks linting setup.

---

.github/workflows/CI_master.yml

Required to force CI run on merge queue

CI: Add merge_group as trigger

---

src/Mod/Fem/CMakeLists.txt
src/Mod/Fem/femexamples/equation_staticcurrent_elmer.py

adds new FEM Example - Joule heating with the newly implemented static current conduction solver

FEM: Add Joule heating to FEM Examples

---

src/Mod/Fem/Gui/Resources/symbols/ConstraintCurrentDensity.iv
src/Mod/Fem/femsolver/elmer/equations/staticcurrent.py
src/Mod/Fem/femsolver/elmer/equations/staticcurrent_writer.py

Change direction of static current symbol since positive means entering the body.
Add nonlinear parameters to Elmer static current solver.
@maxwxyz, @FEA-eng

Fem: Some changes in static current features

---

src/Gui/TextDocumentEditorView.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/20018

Core: Text object: Fix icon of the tab.

---

src/Mod/Assembly/UtilsAssembly.py

Fix https://github.com/FreeCAD/FreeCAD/issues/19060

Assembly: Fix use of datum axis in joints

---

src/Mod/Assembly/UtilsAssembly.py

Make it possible to select LCS elements when the LCS is in a body during joint creation.
Fix https://github.com/FreeCAD/FreeCAD/issues/20027
Fix https://github.com/FreeCAD/FreeCAD/issues/19429

Assembly: Make it possible to select LCS elements when the LCS is in a body

---

src/Mod/Fem/Gui/Resources/ui/Magnetization.ui
src/Mod/Fem/femexamples/equation_magnetodynamics_elmer.py
src/Mod/Fem/femexamples/equation_magnetostatics_2D_elmer.py
src/Mod/Fem/femobjects/constraint_magnetization.py
src/Mod/Fem/femsolver/elmer/equations/magnetodynamic2D_writer.py
src/Mod/Fem/femsolver/elmer/equations/magnetodynamic_writer.py
src/Mod/Fem/femtaskpanels/task_constraint_magnetization.py

Unify disabled/disabled properties.
Task panel harmonization.
@FEA-eng

Fem: Improve magnetization

---

src/Mod/Fem/CMakeLists.txt
src/Mod/Fem/femexamples/ccx_rigid_body.py

adds new FEM Example - rigid body constraint with CalculiX

FEM: Add ccx rigid body constraint example

---

src/App/FeaturePythonPyImp.h
src/App/FeaturePythonPyImp.inl
src/Base/Interpreter.cpp
src/Base/PyObjectBase.cpp
src/Base/PyTools.c
src/Gui/PythonConsole.cpp
src/Gui/PythonDebugger.cpp
src/Gui/WidgetFactory.cpp
src/Mod/CAM/App/VoronoiPyImp.cpp

removed references to old python <3.10

removed old python code <3.10

---

src/Mod/Fem/Gui/Resources/ui/MeshGmsh.ui

Fem: Use left alignment in Gmsh task panel

---

src/Mod/Fem/femguiutils/selection_widgets.py
src/Mod/Fem/femsolver/elmer/equations/equation.py

@FEA-eng 
Also, clean up the selector widget by moving the description to the button tooltip.

Fem: Use disambiguation for solid references in Elmer equation task panels

---

src/App/Application.cpp

Further to comments in #19727 trying @chennes proposal 2.

[App] Application remove some using namespace

---

src/Mod/Fem/Gui/Command.cpp
src/Mod/Fem/Gui/TaskFemConstraintHeatflux.cpp
src/Mod/Fem/Gui/TaskFemConstraintHeatflux.h
src/Mod/Fem/Gui/TaskFemConstraintHeatflux.ui

Fem: Change from radio buttons to combo box to reduce space in heat flux task panel

---

src/App/PropertyContainer.h

This hopefully fixes the PPA: https://github.com/FreeCAD/FreeCAD/issues/19681

Refactor static type checks

---

src/Gui/ViewProviderLink.cpp

App::Link : deleting it deletes its elements if it has any
Fix https://github.com/FreeCAD/FreeCAD/issues/19529

App::Link : deleting it deletes its elements if any

---

src/Gui/Stylesheets/FreeCAD Dark.qss
src/Gui/Stylesheets/FreeCAD Light.qss
src/Mod/BIM/Resources/ui/dialogIfcProperties.ui
src/Mod/BIM/bimcommands/BimIfcProperties.py

Replaces https://github.com/FreeCAD/FreeCAD/pull/20070
Fixes #19858
@semhustej has tested this PR and has given positive feedback, (see screenshot in the comment previous to) https://github.com/FreeCAD/FreeCAD/issues/19858#issuecomment-2710631042 for screenshot in French
FYI @yorikvanhavre

[BIM] Correct styling of DeleteIFCProperties button and add GroupBox for the two lower comboboxes and the button

---

src/Gui/NaviCube.cpp

Use `devicePixelRatio()` to scale the size of the NaviCube for HiDPI / Retina displays.
See the discussion on https://github.com/FreeCAD/FreeCAD/issues/19887
This only fixes a small part of #19887 though.

Gui: HiDPI NaviCube fix

---

src/Mod/CAM/CAMTests/TestSnapmakerPost.py
src/Mod/CAM/CMakeLists.txt
src/Mod/CAM/Path/Post/scripts/snapmaker_post.py
src/Mod/CAM/TestCAMApp.py

Following PR #19818 that was accidentally closed, this PR adds a CAM postprocessor for the Snapmaker machines with CNC capabilities.

CAM: add Snapmaker postprocessor

---

cMake/FreeCAD_Helpers/SetupPython.cmake

https://github.com/FreeCAD/FreeCAD/pull/19635#issuecomment-2725612407
cc @dzid26 can you test?

Fix regression in Python setup with old Shiboken.

---

src/Gui/CMakeLists.txt

clean  Gui/CMakeLists.txt

---

src/Mod/BIM/ArchSpace.py

Allow to use any of the Space object properties in the displayed text. Fixes #20126

BIM: Fixed space text display

---

src/Mod/Sketcher/Gui/SketcherSettings.cpp
src/Mod/Sketcher/Gui/SketcherSettings.ui
src/Mod/Sketcher/Gui/Workbench.cpp

Sketcher: Add parameter "Preferences/Mod/Sketcher/Commands/UnifiedLineCommands" to combine line and polyline
Fix https://github.com/FreeCAD/FreeCAD/issues/14492

Sketcher: Add parameter to combine line and polyline

---

src/Mod/BIM/Resources/ui/dialogIfcElements.ui

Fixes https://github.com/FreeCAD/FreeCAD/issues/20100 
Width changed to 800px
Changed text capitalization in dialogue
I did not build FreeCAD and test myself.
Lines 51 and 61 were changed by QtCreator

Change IfcElements window width

---

src/App/Document.cpp
src/App/private/DocumentP.h
src/Gui/Command.cpp
src/Gui/Command.h
src/Gui/CommandDoc.cpp
src/Mod/Part/Gui/TaskAttacher.cpp
src/Mod/PartDesign/Gui/Command.cpp
src/Mod/PartDesign/Gui/TaskFeatureParameters.cpp
src/Mod/PartDesign/Gui/ViewProviderTransformed.cpp
src/Mod/PartDesign/Gui/ViewProviderTransformed.h
src/Mod/TechDraw/Gui/TaskBalloon.cpp
src/Mod/TechDraw/Gui/TaskDimension.cpp
src/Mod/TechDraw/Gui/TaskLeaderLine.cpp

As title says, just some minor refactors in this code.

Core: Refactor code around document and feature recompute

---

src/Mod/CAM/Path/Main/Gui/JobDlg.py

This PR is a response to #19441, following up #11851. While there is no bug in a technical sense, I think we can still improve the text of improper unit warning, to not guide our users into the wrong direction:
The previous text suggested to change the scheme in the preferences, however, the preferences only take effect for new documents. Now, that we have the "ProjectUnitSystem" in place, the setting for the *current* document needs to be changed.
I also removed some explicit newlines, which seem to be counterproductive as the dialog already does automatic line breaks.
Previously:
With this PR:
*edit*: update image to latest changes

CAM: Improve warning text for improper unit scheme

---

src/3rdParty/salomesmesh/CMakeLists.txt

removed commited code.
Netgen always > then 6.2.2004

Clean Salome Cmake

---

src/Gui/SoDatumLabel.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/20098
@FlachyJoe please check it out to make sure I have not broken anything else. (though it seems to work file in my test)

Sketcher: Fix negative angle rendering negative bug

---

src/Mod/Measure/Gui/QuickMeasure.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/20035

QuickMeasure: Do not measure datums

---

src/Mod/Assembly/Gui/ViewProviderAssembly.cpp

Select datum or a sketch within a body should not show dragger.
Fix https://github.com/FreeCAD/FreeCAD/issues/20047

Assembly: Fix: Select datum should not show dragger.

---

src/App/PropertyStandard.cpp

Fix crash while taking measurement

---

src/Mod/TechDraw/Gui/QGVNavStyleTouchpad.cpp

Backports https://github.com/FreeCAD/FreeCAD/pull/20177 to v1.0

TechDraw: Backported the fix for flickering cursor issue

---

src/Base/StackWalker.cpp
src/Base/Tools.h
src/Gui/Dialogs/DlgPreferencePackManagementImp.cpp
src/Gui/SoDatumLabel.cpp
src/Gui/View3DInventor.cpp
src/Gui/View3DInventorViewer.cpp
src/Gui/ViewProviderPlane.cpp
src/Mod/CAM/libarea/pyarea.cpp
src/Mod/Fem/App/FemVTKTools.cpp
src/Mod/Mesh/App/Core/MeshKernel.cpp
src/Mod/Spreadsheet/App/PropertySheet.cpp
src/Mod/TechDraw/App/Geometry.cpp
src/Mod/TechDraw/Gui/DimensionValidators.cpp
tests/src/Base/Reader.cpp
tests/src/Mod/Part/App/FuzzyBoolean.cpp

These are all based on compiling using MSVC with the following warning settings:
```
-DCMAKE_CXX_FLAGS="-DFC_DEBUG /W3 /w14189 /w14062 /w14264 /w14296 /w14289 /w14388 /w14774 /w14777 /w15038 /w15041 /w15042 /w15233 /w15259 /w15263 /w15264 /w15266"
```

FreeCAD: Compiler warning fixes

---

src/Mod/Draft/draftguitools/gui_snapper.py

Fixes: #19553.
Additionally:
* Removed 2 unused attributes (`self.lastSnappedObject` and `self.active`).
* Improved the readability of `snapToObject` a little bit.
* Made the return value of that function consistent (vector or None).

Draft: make Near snap obey 'Always snap' setting

---

src/Mod/BIM/ArchStairs.py
src/Mod/BIM/bimcommands/BimStairs.py

FC Forum Discussion:-
https://forum.freecad.org/viewtopic.php?p=814274#p814274
ArchSketch Support, PropertySet, and Refactoring to enable more complex Stairs shape.

[ArchStairs] ArchSketch Support and Refactoring Phase 1

---

src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h

Sketcher: Remove unecessary if in DrawSketchHandlerArc.h

---

src/Mod/PartDesign/Gui/Command.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/20020
@Roy-043 thoughts on the wording? If you have ideas of improvement don't hesitate. It could be nice to have something to help people differentiate with App::Link perhaps.

PartDesign: clone tooltip

---

src/App/Document.cpp
src/Base/Writer.cpp
src/Base/Writer.h

Core: raise exception when no space left on disk at document save

---

src/Base/Console.h

Silence do-while warning at source

Base: Silence do-while warning at source

---

src/App/PropertyLinks.cpp
src/App/PropertyStandard.cpp
src/Gui/WorkbenchManipulatorPython.cpp
src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.cpp
src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.h
src/Mod/Fem/App/FemVTKTools.cpp
src/Mod/Mesh/App/Core/MeshKernel.cpp
src/Mod/Part/App/Geometry.cpp
src/Mod/Part/App/PropertyTopoShape.h
src/Mod/Part/App/modelRefine.cpp
src/Mod/PartDesign/App/FeatureHole.cpp
src/Mod/Sketcher/App/AppSketcherPy.cpp
src/Mod/Sketcher/Gui/Command.cpp
src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp
src/Mod/TechDraw/App/EdgeWalker.cpp
src/Mod/TechDraw/App/EdgeWalker.h

Each commit here is independent, and generally addresses one issue identified by Coverity and indicated as a "high impact" issue. I don't think any of these actually escalate to quite  that level, although a couple of them are close. Of the 50 identified "high impact" issues, only these 16 actually seem to represent real issues (and some are pretty marginal!). The others are mostly failures of the static analysis to parse reference-counted objects.
For the more complicated changes, the commit messages explain the details of what's going on, so it's probably simplest to review per commit.

Coverity fixes 2025-03-20

---

src/Mod/TechDraw/Gui/TaskProjGroup.cpp

This PR implements a fix for issue #19968.

[TD]fix view loses dimensions (fix #19968)

---

src/Mod/PartDesign/Gui/Command.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/20021

PartDesign : Subshapebinder tooltip

---

src/Mod/BIM/bimcommands/BimProjectManager.py

Fixes #20288
I left the original name inside the stored file, so older ones stay compatible...

BIM: Fixed project manager's save/restore

---

src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h

Fix https://github.com/FreeCAD/FreeCAD/issues/20265
https://github.com/user-attachments/assets/b718ef88-172e-46ea-b7c6-4e25b4179f34

Sketcher: Line tool: Enforce correctly when angle is set

---

src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h

Fix https://github.com/FreeCAD/FreeCAD/issues/20268
Same as https://github.com/FreeCAD/FreeCAD/pull/20267 which has a video to explain

Sketcher: Slot tool: Enforce correctly when angle is set

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/JointObject.py

superseed https://github.com/FreeCAD/FreeCAD/pull/20188
in fixing https://github.com/FreeCAD/FreeCAD/issues/19904

Assembly: ignore joints in error

---

src/Gui/AutoSaver.cpp

Gui: Check return value

---

src/Mod/Part/Gui/DlgExportHeaderStep.ui
src/Mod/Part/Gui/DlgImportStep.ui

Added margin=0. Same as in DlgExportStep.ui:
https://github.com/FreeCAD/FreeCAD/blob/718ac63365cd93f1800e2bdfcbe3d0b0dc807230/src/Mod/Part/Gui/DlgExportStep.ui#L17-L19

Part: remove rogue margins from ui file

---

src/Mod/TechDraw/App/Geometry.cpp
src/Mod/TechDraw/App/Geometry.h
src/Mod/TechDraw/Gui/DimensionValidators.cpp
src/Mod/TechDraw/Gui/DimensionValidators.h

This PR implements a fix for issue #20347.
It also includes fixes for 2 minor issues encountered in development of the fix for 20347:
. a reversed boolean preventing some dimensions from being created
. lint cleanup

[TD] Spline as circle yet again  (fix 20347)

---

src/XDGData/org.freecad.FreeCAD.desktop

Follow-up to https://github.com/FreeCAD/FreeCAD-translations/issues/199

Linux: Add Spanish translation to desktop file

---

src/Mod/TechDraw/Gui/QGTracker.cpp

Clean  QGTracker.cpp

---

src/Mod/Fem/App/PreCompiled.h

I missed these in the earlier round.

Fem: Add missing VTK headers from PCH

---

src/Mod/TechDraw/Gui/QGIDimLines.cpp

Fixes #20418. Regression by commit 998f713c97fe870a845c566eb7597520ce26d6fd

TechDraw: arc dimensions should not have fill

---

src/Mod/BIM/bimcommands/BimProjectManager.py

BIM: Remove calls to obsolete Draft.getParam

---

src/Mod/Draft/draftutils/init_draft_statusbar.py

Fixes #17044.
See:
https://github.com/FreeCAD/FreeCAD/issues/17044#issuecomment-2757637750

Draft: fix status bar widgets display timing issue

---

src/Base/UnitsSchemaInternal.cpp

Better handling of electrical quantities for the standard units system.

Base: Improve internal schema translation for electrical units

---

src/Gui/Quarter/QuarterWidget.cpp
src/Gui/SoTextLabel.cpp
src/Gui/View3DInventorViewer.cpp
src/Gui/ViewProviderAnnotation.cpp
src/Mod/Sandbox/Gui/GLGraphicsView.cpp

ubuntu 22.04 use libcoin v 4. https://launchpad.net/ubuntu/jammy/+package/libcoin-dev

Remove old Coin code <=3

---

src/Mod/Fem/App/AppFem.cpp
src/Mod/Fem/App/FemPostFilter.cpp
src/Mod/Fem/App/FemPostFilter.h
src/Mod/Fem/App/PreCompiled.h
src/Mod/Fem/Gui/AppFemGui.cpp
src/Mod/Fem/Gui/CMakeLists.txt
src/Mod/Fem/Gui/Command.cpp
src/Mod/Fem/Gui/PreCompiled.h
src/Mod/Fem/Gui/Resources/Fem.qrc
src/Mod/Fem/Gui/Resources/icons/FEM_PostFilterCalculator.svg
src/Mod/Fem/Gui/TaskPostBoxes.cpp
src/Mod/Fem/Gui/TaskPostBoxes.h
src/Mod/Fem/Gui/TaskPostCalculator.ui
src/Mod/Fem/Gui/ViewProviderFemPostFilter.cpp
src/Mod/Fem/Gui/ViewProviderFemPostFilter.h
src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
src/Mod/Fem/Gui/ViewProviderFemPostObject.h
src/Mod/Fem/Gui/Workbench.cpp

Add calculator filter.
@FEA-eng 
To be merged after https://github.com/FreeCAD/FreeCAD/pull/19610

Fem: Add calculator filter

---

src/Mod/Assembly/App/AssemblyLink.cpp
src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/App/AssemblyObject.h
src/Mod/Assembly/App/AssemblyUtils.cpp
src/Mod/Assembly/App/AssemblyUtils.h

[Mod] assembly clean

---

src/Mod/TechDraw/App/DrawView.cpp
src/Mod/TechDraw/App/DrawViewClip.cpp
src/Mod/TechDraw/App/DrawViewPart.cpp
src/Mod/TechDraw/App/ShapeExtractor.cpp
src/Mod/TechDraw/Gui/CommandHelpers.cpp
src/Mod/TechDraw/Gui/QGSPage.cpp

Fixes #20131
Cleans up and replaces #20314

TechDraw: remove double type checking

---

src/Mod/Draft/draftgeoutils/faces.py

1. Face fuse per segment (original code has a whole face/segment disappear when a face is self-intersecting or reversed)
2. Return warning if face is self-intersecting Or reversed
Github Issue:
- https://github.com/FreeCAD/FreeCAD/issues/19721#issuecomment-2744738019 FreeCAD Forum:
- https://forum.freecad.org/viewtopic.php?p=816758#p816758
- https://forum.freecad.org/viewtopic.php?p=813062#p813062

[Draft-Faces] Bind: Improve fuse and warning

---

src/App/PropertyLinks.cpp

App: Change element name warning to log

---

src/Mod/Fem/App/FemPostPipeline.cpp

Fem: Update modifcation time for FemFrameSourceAlgorithm - fixes #20543

---

src/Mod/AddonManager/addonmanager_utilities.py

Fixes https://github.com/FreeCAD/FreeCAD-Telemetry/issues/13

Fix home_dir regression in addonmanager

---

src/Mod/OpenSCAD/InitGui.py
src/Mod/OpenSCAD/OpenSCADCommands.py
src/Mod/OpenSCAD/OpenSCADUtils.py
src/Mod/OpenSCAD/colorcodeshapes.py
src/Mod/OpenSCAD/expandplacements.py
src/Mod/OpenSCAD/exportCSG.py
src/Mod/OpenSCAD/importCSG.py
src/Mod/OpenSCAD/prototype.py

MOD: OPENSCAD clean

---

src/Mod/Sandbox/App/DocumentProtectorPy.cpp
src/Mod/Sandbox/Gui/AppSandboxGui.cpp
src/Mod/Sandbox/Gui/TaskPanelView.cpp
src/Mod/Sandbox/Gui/Workbench.h
src/Mod/Sandbox/exportDRAWEXE.py

MOD: SANDBOX clean

---

src/Mod/ReverseEngineering/App/BSplineFitting.cpp
src/Mod/ReverseEngineering/App/SurfaceTriangulation.cpp

clean code .
removed old code pcl lib is alwais >then  1.7 (ubuntu 20.04 use pcl v 1.10)

MOD: ReverseEngineering clean

---

src/Mod/Sketcher/App/CMakeLists.txt
src/Mod/Sketcher/App/Constraint.pyi
src/Mod/Sketcher/App/ExternalGeometryExtension.pyi
src/Mod/Sketcher/App/ExternalGeometryExtensionPy.xml
src/Mod/Sketcher/App/ExternalGeometryFacade.pyi
src/Mod/Sketcher/App/ExternalGeometryFacadePy.xml
src/Mod/Sketcher/App/GeometryFacade.pyi
src/Mod/Sketcher/App/GeometryFacadePy.xml
src/Mod/Sketcher/App/Sketch.pyi
src/Mod/Sketcher/App/SketchGeometryExtension.pyi
src/Mod/Sketcher/App/SketchObject.pyi
src/Mod/Sketcher/App/SketchObjectPy.xml
src/Mod/Sketcher/App/SketchObjectSF.pyi
src/Mod/Sketcher/App/SketchPy.xml
src/Mod/Sketcher/Gui/CMakeLists.txt
src/Mod/Sketcher/Gui/ViewProviderSketchGeometryExtension.pyi

This converts the existing Sketcher XML binding files to the new Python bindings generator model.

Sketcher: Convert XML binding files to Python API bindings model.

---

src/Mod/Draft/WorkingPlane.py

Forum topic:
https://forum.freecad.org/viewtopic.php?t=96058

Draft: make Draft_SelectPlane recognize the new Part_DatumPlane object

---

src/Mod/Draft/draftutils/gui_utils.py

Corrected source variable name so it wouldn't show up in codespell check

Draft: fix source typo

---

src/Mod/Mesh/App/Mesh.cpp
src/Mod/MeshPart/App/MeshAlgos.cpp

Modified so it wouldn't show up in codespell results.

Mesh: Fix source typo

---

src/App/Application.cpp

This is a cherry-pick (and conflict-resolution) from #19727 after #19977 was merged
Included are:
- [Const](https://github.com/FreeCAD/FreeCAD/pull/19727/commits/6e51bce82496047f0b8214fe3dded84c21a1cefc)
- [Removed redundant qualifier](https://github.com/FreeCAD/FreeCAD/pull/19727/commits/b09244a84710d1607e6a3ed84c9bc2baf63988be)
The latter one still keeps qualifier in `Application::initTypes()`. If you want them removed, drop me a note.

Application tidy up (two more)

---

src/Gui/SoDatumLabel.cpp

As mentioned in https://github.com/FreeCAD/FreeCAD/pull/20496#discussion_r2030090484
Thanks @3x380V

Gui: Fix operator mistake in previous c++constant refactoring

---

src/Mod/BIM/bimcommands/BimProjectManager.py

Fixes: https://github.com/FreeCAD/FreeCAD/issues/20291
See caveat on where to add the `ifc_tools` import: https://github.com/FreeCAD/FreeCAD/pull/20368#issuecomment-2751137333

BIM: add missing ifc_tools import

---

src/Mod/TechDraw/Gui/CommandHelpers.cpp
src/Mod/TechDraw/Gui/CommandHelpers.h
src/Mod/TechDraw/Gui/PATPathMaker.cpp
src/Mod/TechDraw/Gui/PATPathMaker.h

TechDraw: Removed unused functions

---

src/Mod/Tux/NavigationIndicatorGui.py

https://github.com/FreeCAD/FreeCAD/pull/20401#pullrequestreview-2748768874

[TUX] Fix typo in PR #20401

---

src/Mod/PartDesign/Gui/SketchWorkflow.cpp

Fix https://github.com/FreeCAD/FreeCAD/pull/20453#issuecomment-2785804779

PartDesign : New sketch: Fix regression

---

src/Doc/CMakeLists.txt

See https://github.com/FreeCAD/FreeCAD/pull/20479#issuecomment-2787332467.

[Doc] Fix a hard requirement in CMake for FEM

---

CMakeLists.txt
CMakePresets.json

This reverts commit 307a4661aff0974f90adbedae148543de85a463f.

Revert "Build:add maximum cmake compatible version"

---

src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h

Fixes the issue in this comment:
https://github.com/FreeCAD/FreeCAD/pull/20476#issuecomment-2758401350.

Sketcher: Refactor and fix `DrawSketchDefaultHandler.h`

---

src/Mod/Assembly/App/AssemblyLink.cpp
src/Mod/Assembly/AssemblyTests/TestTEMPLATE.py
src/Mod/Assembly/CommandCreateSimulation.py
src/Mod/Assembly/CommandCreateView.py
src/Mod/Assembly/CommandExportASMT.py
src/Mod/Assembly/CommandInsertLink.py
src/Mod/Assembly/CommandSolveAssembly.py
src/Mod/Assembly/UtilsAssembly.py

MOD: assembly clean

---

src/Mod/PartDesign/Gui/TaskFeaturePick.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/20756#issuecomment-2796572524

PartDesign: TaskFeaturePick : Fix LCS temporary visibility

---

src/Mod/Spreadsheet/Gui/SheetTableView.cpp
src/Mod/Spreadsheet/Gui/SheetTableView.h

[Spreadsheet] Add usage of override cursor in SheetViewHeader

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Adding a GitHub template for pull requests.

Add a GitHub template for Pull Requests

---

src/App/Application.cpp
src/Base/Console.cpp
src/Base/Console.h

Remove unused code: verbosity

---

src/Mod/CAM/PathSimulator/AppGL/SimDisplay.cpp

Sometimes not enough move area with zoom in to see everything on piece
Increased _MoveEye_ area 
https://streamable.com/8n8m5j
https://github.com/user-attachments/assets/19d5f964-cc11-47a6-ba41-88e41db8d4a7

CAM: Increased moveEye in New Simulator

---

src/Mod/Draft/draftutils/utils.py
src/Mod/Draft/importAirfoilDAT.py
src/Mod/Draft/importDXF.py
src/Mod/Draft/importOCA.py
src/Mod/Draft/importSVG.py

The testing of the fix for #20608 highlighted that the fixes for this and the sketch alignment in SVG and DXF export had not been backported which is the reason for this PR.

Backport of PR19377 and PR19765 to releases/1.0 branch

---

src/Base/Type.h
src/Mod/BIM/Arch.py
src/Mod/BIM/bimcommands/BimWall.py
src/Mod/BIM/bimtests/TestArchSpace.py
src/Mod/Draft/draftobjects/facebinder.py
src/Mod/Draft/importDXF.py
src/Mod/Fem/femmesh/meshtools.py
src/Mod/Part/App/PartFeaturePyImp.cpp
src/Mod/TechDraw/App/ShapeExtractor.cpp

Core: Part::PartFeature should be Part::Feature

---

src/App/Document.pyi
src/App/DocumentPyImp.cpp

Add `locked` keyword to Document::addProperty

---

src/App/PropertyContainer.h
src/Mod/CAM/Path/Op/Adaptive.py
src/Mod/Draft/SVGPath.py
src/Mod/Material/App/MaterialAPI/MaterialManagerExternal.py

Misc: Fix various typos

---

src/Mod/BIM/bimcommands/BimDimensions.py
src/Mod/BIM/bimcommands/BimImagePlane.py
src/Mod/BIM/bimcommands/BimLibrary.py
src/Mod/BIM/bimcommands/BimNudge.py
src/Mod/BIM/bimcommands/BimProjectManager.py
src/Mod/BIM/bimcommands/BimSetup.py
src/Mod/BIM/bimcommands/BimSketch.py
src/Mod/BIM/bimcommands/BimViews.py

Some code stemming from the old BIM external workbench still used `FreeCAD.DraftWorkingPlane`.

BIM: Update working plane related code

---

src/Mod/BIM/ArchStairs.py

Phase 2 Subsequent to https://github.com/FreeCAD/FreeCAD/pull/20069
FC Forum Discussion:-
https://forum.freecad.org/viewtopic.php?p=814274#p814274
ArchSketch Support, PropertySet, and Refactoring to enable more complex Stairs shape.

[ArchStairs] ArchSketch Support and Refactoring Phase 2

---

src/Gui/Navigation/GestureNavigationStyle.cpp
src/Gui/Navigation/MayaGestureNavigationStyle.cpp
src/Gui/Navigation/NavigationStyle.h

Fixes #20900.
Note: the zooming behavior changes are based on the description and video by @celdorwow. I don´t have Maya so I cannot confirm that this is indeed the default behavior in Maya.

Gui: MayaGesture navigation fixes

---

src/Mod/Sketcher/App/SketchObject.cpp

Yet another attempt at fixing #19425 and friends.

Sketcher: Avoid an unnecessary geometry update when trimming

---

src/Gui/Selection/SoFCSelection.cpp

clean SoFCSelection.cpp

---

src/Gui/Selection/SelectionFilter.h

Removed unused function

---

.github/workflows/sub_weeklyBuild.yml

Rename release from "Weekly Build weekly-<date>" to "Development Build weekly-<date>".
None
N/A

CI: rename Weekly Build weekly-<date> to Development Build weekly-<date>.

---

src/Mod/Fem/femobjects/constraint_electricchargedensity.py
src/Mod/Fem/femsolver/elmer/equations/electrostatic_writer.py
src/Mod/Fem/femsolver/elmer/equations/magnetodynamic2D_writer.py
src/Mod/Fem/femsolver/elmer/equations/magnetodynamic_writer.py
src/Mod/Fem/femsolver/elmer/sifio.py

Remove use of the round function and write quantity values ​​to the solver input file using a format string `{value:.13g}` with the same significant digits as the CalculiX writer.
@FEA-eng
fixes #20938

 Fem: Use string format to round Elmer quantity values - fixes #20938 

---

src/Mod/CAM/Path/Post/scripts/KineticNCBeamicon2_post.py
src/Mod/CAM/Path/Post/scripts/snapmaker_post.py

While working on CAM I got bugged by being flooded from errors when running the tests, so I fixed the two worst offenders. Interestingly while these printed tons of errors to stderr, they did not make any tests fail.
In any case, this should fix the issues.

CAM: fix postprocessor errors

---

src/Mod/CAM/PathSimulator/AppGL/GuiDisplay.cpp
src/Mod/CAM/PathSimulator/AppGL/GuiDisplay.h

This PR Replaces PR #20885. 
Its a GUI change proposed by @tarman3, that makes the progress slider adapt to the window size.
Also, add tool-tips to GUI buttons.
Commits should be squashed.
Replaces PR #20885
before:
After:
Add Tool-tips:

[CAM Simulator] Auto resizing of simulator slider based on window size

---

src/Mod/Draft/draftviewproviders/view_dimension.py

Draft: fix dim unit override for Building US unit system

---

src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h

Nothing major though
CIDs are available in the commit messages
Let me know if you'd like these commits constructed in another way.

Sketcher: Fix some of the coverity issues in SketchObject.cpp

---

src/Mod/TechDraw/Gui/QGIEdge.cpp
src/Mod/TechDraw/Gui/QGIEdge.h

This PR implements a fix for issue #20962.   It restores the hidden line behaviour that was broken by PR #19788.

[TD]fix hidden line regression

---

src/App/Property.cpp
src/App/Property.h

This PR improves the doc comments of App::Property. 

Doc: Improve App::Property documentation

---

src/Mod/Sketcher/Gui/EditModeCoinManager.cpp
src/Mod/Sketcher/Gui/EditModeCoinManager.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.h
src/Mod/Sketcher/Gui/ViewProviderSketchCoinAttorney.h

Improves on PR #19929 for issue #19887. See comment at: https://github.com/FreeCAD/FreeCAD/issues/19887#issuecomment-2845895843

Gui: HiDPI fixes for Sketcher (tweaks to tringenbach's PR)

---

src/App/Property.h

PR #21155 introduced some warnings that are fixed in this PR.

Doc: Fix warnings App::Property

---

src/Mod/BIM/Arch.py

The final goal is for the Arch API to be fully documented. This PR first addresses the top Arch module, and adds docstrings for all public functions there. The numpy formatting style has been adopted for consistency with existing docstrings and the Draft module.
Related, but not strictly necessary, whitespace has been added between parameters and operators for improved readability.
The changes are broken down in two commits to make review easier: first whitespace changes, then docscrings.

BIM: add docstrings for all functions in the Arch module, refactor whitespace

---

src/Mod/BIM/ArchRoof.py

Fixes: #21137.
Note that the list values in the Property editor are unitless. Therefore lengths are still in mm there.

BIM: show units in Arch_Roof task panel

---

src/Mod/PartDesign/App/FeatureHole.cpp

When using a threaded hole, the code which finds the closest matching thread size would not take the thread pitch into account, leading to the user's selection being quietly changed and the model actually having a hole of the wrong pitch even though the preview and the Hole dialog pitch drop-down showed the correct value. Now the pitch is taken into account and preserved.
Closes #20579

Fixes hole thread pitch

---

src/App/ExtensionContainer.cpp
src/App/ExtensionContainer.h

This PR improves the doc comments of App::ExtensionContainer.

Doc: Improve App::ExtensionContainer documentation

---

src/Mod/TechDraw/App/CosmeticExtension.cpp
src/Mod/TechDraw/App/DrawRichAnno.cpp
src/Mod/TechDraw/App/DrawTile.cpp
src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp

I didn't rebase https://github.com/FreeCAD/FreeCAD/pull/21099 before merging... which broke the build because the spelling of console functions changed recently.

TD: Fix capitalization of Console calls

---

src/Gui/Document.cpp
src/Gui/MainWindow.cpp
src/Gui/MainWindow.h

Add switching to the document when closing FreeCAD

---

src/App/Extension.h
src/App/ExtensionContainer.h

This PR improves the doc comments of App::Extension.
It also fixes a couple of small warnings in App::ExtensionContainer.

Doc: Improve App::Extension documentation

---

src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.cpp

CAM: Simulator window title

---

src/Gui/Dialogs/DlgMacroExecute.ui
src/Gui/Dialogs/DlgMacroExecuteImp.cpp
src/Gui/Dialogs/DlgMacroExecuteImp.h

Macro: Button to open folder with macros

---

src/Mod/CAM/PathSimulator/AppGL/DlgCAMSimulator.cpp

Special for @xtemp09 ))
[21223#issuecomment-2869787438](https://github.com/FreeCAD/FreeCAD/pull/21223#issuecomment-2869787438)

CAM: Simulator - Add document name to title

---

src/Mod/CAM/Path/Dressup/Boundary.py

Try to implement parameter **KeepToolDown** in **DressupPathBoundary**
This can be useful to keep time if not need to raise the tool to a safety height between parts of path
https://forum.freecad.org/viewtopic.php?t=96340

CAM: Keep tool down in DressupPathBoundary

---

src/Mod/BIM/ArchBuildingPart.py

Activating working planes is such a common operation while working on BIM models, that arguably the ability to activate by double-clicking on a level should be enabled by default. This is what this PR does.
Fixes: https://github.com/FreeCAD/FreeCAD/issues/20988

BIM: set DoubleClickActivates property true by default

---

src/Mod/Fem/Gui/DlgSettingsFemCcx.ui

Fixes small typos in the new CalculiX preferences

FEM: Fix typos in the newly refactored CalculiX solver preferences

---

src/Mod/BIM/InitGui.py

As requested at https://github.com/FreeCAD/FreeCAD/pull/21157#issuecomment-2872254735. PR #21157 must be merged first.

BIM: change Snapping menu order for workplane commands

---

src/Mod/CAM/PathSimulator/AppGL/SimDisplay.cpp

https://forum.freecad.org/viewtopic.php?t=96939

CAM: Simulator - Improve camera limits

---

src/Mod/BIM/bimcommands/BimWindow.py

Improvement to User Interactive Experience:
- The Window Interactive Tool would check if SketchArch-addon is enabled by user, i.e. if ArchSketckLock is checked.
- If not, the conventional creation behaviour is used, SketchArch properties would not be added to Window object.
- It also check if Base of Wall is ArchSketch or not.
Github Discussion:
- https://github.com/paullee0/FreeCAD_SketchArch/issues/27#issuecomment-2837652351
Fixes: #github.com/paullee0/FreeCAD_SketchArch/issues/27

[BimWindow] Interactive Creation Tool: Check if SketchArch is Enabled (ArchSketchLock)

---

src/Mod/BIM/ArchStairs.py

Phase 3 Subsequent to #21025 + Regression Fix
FC Forum Discussion:-
https://forum.freecad.org/viewtopic.php?p=814274#p814274
ArchSketch Support, PropertySet, and Refactoring to enable more complex Stairs shape.

[ArchStairs] ArchSketch Support and Refactoring Phase 3 + Regression

---

src/Mod/Fem/CMakeLists.txt
src/Mod/Fem/femmesh/meshsetsgetter.py
src/Mod/Fem/femmesh/meshtools.py
src/Mod/Fem/femobjects/solver_calculix.py
src/Mod/Fem/femsolver/calculix/calculixtools.py
src/Mod/Fem/femsolver/calculix/solver.py
src/Mod/Fem/femsolver/calculix/write_constraint_electricchargedensity.py
src/Mod/Fem/femsolver/calculix/write_constraint_electrostatic.py
src/Mod/Fem/femsolver/calculix/write_femelement_material.py
src/Mod/Fem/femsolver/calculix/write_step_equation.py
src/Mod/Fem/femsolver/calculix/write_step_output.py
src/Mod/Fem/femsolver/calculix/writer.py
src/Mod/Fem/femsolver/writerbase.py
src/Mod/Fem/femtools/membertools.py

Solve electrostatic systems with CalculiX (new implementation) by analogy with the steady-state heat equation.
A new `electromagnetic` analysis type and the `ElectromagneticMode` property have been added (currently only `electrostatic` is available).
The Result  consist of  `Potential` (in $mV$) and `Electric Flux Density` $D$ (in $\frac{C}{mm^2}$) fields.
It works in both 3D and 2D (by selecting the appropriate model space), supports electrostatic loads (`Dirichlet` and `Neumann`), charge densities in the form of distributed loads, and supports `Gmsh` and `Netgen` meshers.
The eigenmode limits and time steps properties have been changed from float values ​​to frequency and time quantities, respectively.
Still is needed add support for concentrated loads (also in `Elmer`), improved …

Fem: Solve electrostatic systems with CalculiX

---

src/App/Document.cpp
src/App/Document.h
src/App/private/DocumentP.h

This is the #19726 rebased with conflicts fixed.

Document tidyup

---

src/Base/UnitsApiPy.cpp
src/Base/UnitsSchema.cpp
src/Base/UnitsSchemas.cpp
src/Base/UnitsSchemasData.h
tests/src/Base/SchemaTests.cpp

Fixes: #21172
Fixes: #21209
Fixes: #21245
Fixes: #21316
Fixes: #21317

Base: fix Unit scheme management regressions

---

src/Mod/TechDraw/Gui/QGIFace.cpp

TechDraw: fix face color not working

---

src/Gui/ElideCheckBox.cpp

This fixes #21158 and also some special states that weren't draw like hover and focus

Gui: fix ElideCheckbox

---

src/Mod/Draft/draftutils/params.py

Draft: params.py: do not report missing UI files

---

src/Base/QuantityPyImp.cpp
src/Base/UnitsSchemasData.h
tests/src/Base/SchemaTests.cpp

Fixes: #21317
Fixes: #21353
Fixes: #21373
Fixes: #21394

Base: fix more Unit schema management regressions

---

src/Mod/CAM/CMakeLists.txt
src/Mod/CAM/Gui/Resources/Path.qrc
src/Mod/CAM/Gui/Resources/icons/CAM_ShapeTC.svg
src/Mod/CAM/InitGui.py
src/Mod/CAM/Path/GuiInit.py
src/Mod/CAM/Path/Op/Gui/PathShapeTC.py

CAM: PathShape with Tool Controller
This feature create PathShape object inside Job with Tool Controller
This allows to use some modifiers, array and path Simulator
Based on macro from [Russ4262](https://forum.freecad.org/viewtopic.php?p=806678#p806678)
https://streamable.com/nuhpiy
https://forum.freecad.org/viewtopic.php?t=93896
https://github.com/user-attachments/assets/fa84b444-3385-4c48-ac05-54c5c660854e

CAM: PathShape with Tool Controller

---

src/App/Application.cpp

Add Navigation Style/Orbit Style/Rotation Mode to About info

---

src/Mod/Fem/App/FemPostFilter.cpp

Add support for VTK < 9.1 in calculator filter .
@edi271 
#21346

Fem: Add support for VTK < 9.1 in calculator filter - fixes #21346

---

src/Mod/Fem/Gui/Resources/ui/TaskPostGlyph.ui
src/Mod/Fem/femobjects/post_glyphfilter.py

Adds a few more VTK glyph types for the new Glyph filter: Cone, Cylinder, Line, Sphere
@ickby FYI

FEM: Add more glyph types for the Glyph filter

---

src/Mod/Material/App/MaterialLibrary.cpp
src/Mod/Material/App/MaterialManager.h
src/Mod/Material/App/Materials.cpp
src/Mod/Material/App/ModelManager.h

This PR makes ModelManager from Materials no longer possible to copy or move as it should be Singleton. It fixes issue of triggering the destructor multiple times which in turn tried to detach not attached listener, that should not happen.
@davesrocketshop FYI
Fixes https://github.com/FreeCAD/FreeCAD/issues/21285

Materials: Fix ModelManager being copied on getInstance()

---

src/Mod/Part/App/TopoShape.cpp
src/Mod/Part/App/TopoShape.h
src/Mod/Part/App/TopoShape.pyi
src/Mod/Part/App/TopoShapePyImp.cpp

oldFuse is deprecated since OCC 7.3

Remove oldFuse funcion

---

src/Base/Interpreter.cpp
src/Base/Interpreter.h

Removed empty functions

---

src/Mod/Spreadsheet/App/PropertySheet.cpp
src/Mod/Spreadsheet/App/Sheet.cpp
src/Mod/Spreadsheet/App/Sheet.h

observer is no longer required as PropertySheet is now derived from  PropertyLinkBase and will handle all the link related behavior

SpreadSheet: remove function

---

src/App/MeasureManager.h
src/Mod/Measure/App/MeasureArea.cpp
src/Mod/Part/App/MeasureClient.cpp

Fixes #20802 by returning a more generic surface element type (MeasureElementType::Surface) instead of the invalid type.

Measure: Add MeasureElementType::Surface

---

src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp
src/Mod/Measure/Gui/ViewProviderMeasureBase.h
src/Mod/Measure/Gui/ViewProviderMeasureDistance.cpp

This solves #18996 by correctly hooking up the text size properties from ViewProviderMeasureBase->DimensionLinear->SoFrameLabel.
- Add font size field to ViewProviderMeasureBase which connects to other fields
- Remove dead code in DimensionLinear which internally is using FrameLabel
- Connect FrameLabels's fontsize property to DimensionLinear's property
fixes #18996
Before:
After:

Measure: Fix delta label text size scaling

---

src/Base/UnitsApiPy.cpp
tests/src/Base/SchemaTests.cpp

While testing https://github.com/FreeCAD/FreeCAD/pull/21365 I created some tests to verify the behavior and also found some small things to clean up. Instead of delaying that PR I saved the changes to create a new one.
The commits are structured to be kept

Base: Add some tests for units and minor fixes

---

src/Mod/Start/Gui/GeneralSettingsWidget.cpp

Start: fix restoring of user saved Unit schema

---

src/Mod/Draft/draftmake/make_sketch.py

Draft: avoid redundant constraints in make_sketch.py (improved)

---

src/Gui/ViewProviderGeometryObject.cpp

Core: Typo in ViewProviderGeometryObject.cpp

---

src/Mod/Draft/draftguitools/gui_trackers.py

Minor improvement for the `setOrigin` and `update` functions of the class.

Draft: Tweak polygonTracker code

---

src/Mod/BIM/importers/importOBJ.py

Lines from obj files are imported as Draft::Wire objects and grouped with an  App:Part object so that the lines contained in the obj file  are included in the corresponding object definition.
Lines defined in the obj file within a block are converted into a non-closed polyline if the second point of a line matches the first point of the following line.
A samples file has been added. 
fixes #21326

BIM: Add support to import lines from obj files

---

src/Mod/BIM/nativeifc/ifc_status.py

When switching from native to non-native IFC mode in a BIM model, a number of IFC-related properties need to be deleted. Those properties are originally defined with `locked=True` so that the user cannot delete them via the UI. When they are attempted to be removed at runtime, the operation correctly fails with an error, since they are non-removable. Yet the expected behaviour is that removal works.
This PR effectively resets `locked=False` for those properties at the point of deletion, so that they can be removed programmatically.
Unrelated, when switching from native to non-native IFC mode, I'm getting this error:
```
Error: No IFC file attached to this project: _IfcProjectError: No IFC file attached to this project: _IfcProject
```
Fixes: #21474

BIM: allow deleting locked IFC properties when needed

---

src/Mod/Draft/Resources/ui/dialogHatch.ui
src/Mod/Draft/draftguitools/gui_hatch.py
src/Mod/Draft/draftmake/make_hatch.py
src/Mod/Draft/draftutils/params.py
src/Mod/Draft/draftviewproviders/view_hatch.py

PR implements `Align to face` checbox in Hatch task panel, as suggested in referenced Issue.
As agreed in PR comments, this checkbox sets `.Translate` property of `Hatch` during creation.
Closes https://github.com/FreeCAD/FreeCAD/issues/18033
Before:
After:

Draft: Implementation of 'Align to face' checkbox in Hatch task panel

---

src/Mod/Material/Resources/Models/Mechanical/ReducedPolynomialN1.yml
src/Mod/Material/Resources/Models/Mechanical/ReducedPolynomialN2.yml
src/Mod/Material/Resources/Models/Mechanical/ReducedPolynomialN3.yml

Some models had simple spelling errors

Materials: Correct model spelling errors

---

src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Spreadsheet/App/PropertySheet.cpp

Sketcher: Remove unused variables

---

src/Mod/BIM/ArchWall.py

fix #21357 error message problem
Github issue and discussion:
https://github.com/FreeCAD/FreeCAD/issues/21357
https://github.com/FreeCAD/FreeCAD/issues/21357#issuecomment-2886010914
ArchWall return error when Base Sketch has external(projected) geometry.
External projected geometry has TNP-problem, until the feature is TNP-tolerant,  support of external(projected) geometry at ArchWall is not encouraged. The reported error message is fixed in the meantime in this PR.

[ArchWall] Fix SetLength Error When Base Sketch has External Geometry

---

src/Mod/TechDraw/Gui/QGISVGTemplate.cpp

TechDraw: fix incorrect transform of editable fields

---

src/Mod/Start/Gui/FileCardDelegate.cpp

Start: fix thumbnails not keeping aspect ratio

---

src/Mod/CAM/Path/Op/Base.py
src/Mod/CAM/Path/Op/Gui/Array.py

Code taken from file `Mod/CAM/Path/Op/Base.py`

CAM: Added property CycleTime to old Array

---

src/Mod/Sketcher/Gui/EditModeCoinManager.cpp

fixes #21663
The bug came from this PR: https://github.com/FreeCAD/FreeCAD/pull/21098
The viewScalingFactor was not applied anymore from the preferences.

Sketcher: Fix use of viewScalingFactor

---

src/Mod/PartDesign/App/FeatureHole.cpp
src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
src/Mod/PartDesign/PartDesignTests/TestHole.py

feat(PD): ISO tyre valve threads

---

src/App/Document.cpp
src/App/Document.h

This PR concatenates all Document::addObject[s] functions into calls to Document::_addObject whose behavior is now expanded and controlled with flags to reduce code duplication.
Some code segments are not in the same order as they were, but it should not affect the behavior of the functions.
There is some gymnastics around setPartialStatus and unsetPartialStatus, because I was not sure if unsetting the partial bit it was equivalent to not setting it in this context, but it can easily be changed.
It also supresses dupplicate logic for the Document::removeObject function and Document::_removeObject function

App::Document addObject and removeObject code reuse

---

src/App/Expression.cpp
src/App/FeatureTest.cpp
src/App/PropertyGeo.cpp
src/App/PropertyUnits.cpp
src/Base/Quantity.cpp
src/Base/Quantity.h
src/Base/QuantityPyImp.cpp
src/Base/Unit.cpp
src/Base/Unit.h
src/Base/UnitPyImp.cpp
src/Base/UnitsSchema.cpp
src/Base/UnitsSchemasData.h
src/Gui/Dialogs/DlgExpressionInput.cpp
src/Gui/Dialogs/DlgUnitsCalculatorImp.cpp
src/Gui/InputField.cpp
src/Gui/QuantitySpinBox.cpp
src/Gui/propertyeditor/PropertyItem.cpp
src/Mod/Fem/App/FemPostPipeline.cpp
src/Mod/Sketcher/Gui/EditDatumDialog.cpp
src/Mod/Spreadsheet/App/Cell.cpp
src/Mod/Spreadsheet/App/Sheet.cpp
src/Mod/Spreadsheet/Gui/SheetModel.cpp
tests/src/App/ExpressionParser.cpp
tests/src/Base/Quantity.cpp
tests/src/Base/SchemaTests.cpp
tests/src/Base/Unit.cpp

This just a  #18844 rebased on the top of #20540. Units were _not_ moved to `Units` namespace as it introduced a lot of changes everywhere. Still might be done later. The rest of changes are based on review comments and testing.

Units rework II

---

src/Gui/PreferencePages/DlgSettingsSelection.ui

This PR is followup for #21035 to align the result with DWG feedback.
| ![image](https://github.com/user-attachments/assets/f29ff892-3db2-4364-8a01-c5a7698e3988) | ![image](https://github.com/user-attachments/assets/a513e1aa-d626-4cdd-992e-267a13eab9b8) |

Preferences: Better grouping for Selection page

---

src/Gui/Tree.cpp

Remove tree preselect delay when selecting an item - resolves https://github.com/FreeCAD/FreeCAD/issues/18924

Gui: Do not preselect after selection

---

src/Mod/BIM/ArchRoof.py

BIM: Roof add tolerance to parallel check

---

src/Gui/InputHintWidget.cpp
src/Gui/InputHintWidget.h

Reducing hint icon size slightly to match the status bar elements for consistency.
Also fixes the issue where the status bar expands and contracts vertically when hints are shown.
Top is before, bottom with PR:

Gui: adjust hint icon size

---

.github/workflows/auto-close_stale_issues_and_pull-requests.yml

Update GitHub stale action and fix typo

Update GitHub stale action and fix typo

---

src/Mod/BIM/importers/importOBJ.py

When importing an obj file into an existing document, the imported objects are now stored below a new group object in order to improve the structure and avoid flooding the top level with imported objects.
Fixup for #21349

BIM: Add top level group when importing obj file into active document

---

src/Gui/propertyeditor/PropertyItemDelegate.cpp

Fixes https://github.com/FreeCAD/FreeCAD/issues/21904
@Syres916 this is how i would do it

Gui: fix double-click on checkboxes locking the properties

---

src/Mod/BIM/Arch.py

The ArchPipe's view provider was not initialized correctly, an error introduced with https://github.com/FreeCAD/FreeCAD/pull/21342. This PR fixes that.
Generally, Arch* objects (e.g. `ArchPipe`) follow a standard naming pattern for their view objects (`_ViewProvider` + `ArchObjectName`). Thus if the `baseClassName` parameter is given to the `_initializeArchObject()` function, it can guess the view provider name even if not explcitly given.
For `ArchPipe` this is not the case. Instead of the expected `_ViewProviderArchPipe` it is `_ViewProviderPipe`.  Since `ArchPipe` does not follow the standard object naming as most of the Arch* objects, let's specify the `viewProviderName` parameter explicitly.
The new unit tests failed to detect this, as ViewProvider is set up if and when the GUI is …

BIM: fix ArchPipe's view provider initialization

---

src/Mod/Spreadsheet/Gui/DlgSettingsImp.cpp
src/Mod/Spreadsheet/Gui/SheetTableView.cpp
src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp

Spreadsheet: Re-enable zooming and fix cursor change

---

src/Mod/BIM/Resources/ui/dialogConvertType.ui
src/Mod/BIM/Resources/ui/preferencesNativeIFC.ui
src/Mod/BIM/nativeifc/ifc_types.py

As the title says - this adds a new option to the dialog to `never ask again` as well user can customize both settings through preferences.
@semhustej pls check, tia
https://github.com/user-attachments/assets/c8303d6c-4444-40f8-b4ae-4c0800f59438
Resolves: https://github.com/FreeCAD/FreeCAD/issues/21931

BIM: Allow user to skip dialog during type conversion

---

src/Gui/Stylesheets/overlay/Dark Theme + Dark Background.qss
src/Gui/Stylesheets/overlay/Dark Theme + Light Background.qss
src/Gui/Stylesheets/overlay/Light Theme + Dark Background.qss
src/Gui/Stylesheets/overlay/Light Theme + Light Background.qss
src/Gui/TaskView/TaskView.cpp
src/Gui/TaskView/TaskView.h

Gui: Tasks: fix in place close and ok buttons (remove them from the scrollable area)

---

src/Gui/CommandView.cpp
src/Gui/Icons/Std_DockOverlayToggleBottom.svg
src/Gui/Icons/Std_DockOverlayToggleLeft.svg
src/Gui/Icons/Std_DockOverlayToggleRight.svg
src/Gui/Icons/Std_DockOverlayToggleTop.svg
src/Gui/Icons/resource.qrc

Adds icons for toggle overlay panel commands, previously they all had an X
fixes https://github.com/FreeCAD/FreeCAD/issues/13904

Gui: Add toggle overlay icons

---

src/Base/Matrix.cpp
src/Base/Matrix.h
tests/src/Base/Matrix.cpp

Cherry picked @wwmayer's Matrix4D changes from [main-dev](https://github.com/wwmayer/FreeCAD/commits/main-dev/) branch.

Matrix4D fixes

---

src/Mod/Spreadsheet/Gui/SheetTableView.cpp
src/Mod/Spreadsheet/Gui/SheetTableView.h
src/Mod/Spreadsheet/Gui/ZoomableView.cpp

This method seems to be working. Closes #22081.
Tested on _KUbuntu 24.04.1 LTS (KDE/plasma/xcb)_, _Qt 5.15.13_.

[Spreadsheet] Replace override cursor with QGraphicsItem::setCursor

---

src/Mod/Sketcher/Gui/CommandConstraints.cpp

fixes #21391
The Selection SelVertexOrRoot is ignored if there is a Selection that fits better (SelRoot or SelVertex in this case) See comment on line 985 in CommandConstraints.cpp. So for each SelVertexOrRoot where an option exists with a specific selection i splitted it to the specific selections

Sketcher: 3 Point Symmetry fixed if root is selected first (and simplify and fix the selection logic)

---

src/Mod/BIM/ArchProfile.py

BIM: fix ArchProfile update issues

---

src/Mod/BIM/ArchMaterial.py

BIM: fix transparency propagation of BIM material

---

src/Mod/Sketcher/App/planegcs/Constraints.cpp
src/Mod/Sketcher/App/planegcs/Constraints.h

Remove code duplication
and implicit `inline`

Sketcher: refactor planecgs/Constraints

---

src/Gui/propertyeditor/PropertyItem.cpp

remove unused parameter ‘method’

fix unused variable

---

src/Mod/CAM/InitGui.py
src/Mod/CAM/Path/Op/Slot.py

I've refactored slot for readability.  Core algorithm is unchanged.
Fixed a minor but with toolType / ShapeName which is post BTL regression.
Slot has been around for quite a while.  I think it's time to move it out of experimental features
@Russ4262 This could use a review.

Refactor slot op.

---

src/Gui/EditableDatumLabel.cpp

Clean EditableDatumLabel.cpp

---

src/Mod/OpenSCAD/OpenSCADCommands.py
src/Mod/OpenSCAD/Resources/ui/openscadprefs-base.ui
src/Mod/OpenSCAD/prototype.py
src/Mod/OpenSCAD/replaceobj.py

OpenSCAD: Update UI strings for consistency

OpenSCAD: Update UI strings for consistency

---

src/Mod/Inspection/App/AppInspection.cpp
src/Mod/Inspection/App/InspectionFeature.cpp
src/Mod/Inspection/Gui/AppInspectionGui.cpp
src/Mod/Inspection/Gui/Command.cpp
src/Mod/Inspection/Gui/ViewProviderInspection.cpp

Inspection: Update UI strings for consistency

Inspection: Update UI strings for consistency

---

src/Mod/Mesh/App/AppMeshPy.cpp
src/Mod/Mesh/App/MeshPy.xml
src/Mod/Mesh/Gui/AppMeshGui.cpp
src/Mod/Mesh/Gui/Command.cpp
src/Mod/Mesh/Gui/DlgEvaluateMesh.ui
src/Mod/Mesh/Gui/DlgEvaluateMeshImp.cpp
src/Mod/Mesh/Gui/DlgEvaluateSettings.ui
src/Mod/Mesh/Gui/DlgRegularSolid.ui
src/Mod/Mesh/Gui/DlgSettingsImportExport.ui
src/Mod/Mesh/Gui/DlgSettingsMeshView.ui
src/Mod/Mesh/Gui/DlgSmoothing.ui
src/Mod/Mesh/Gui/MeshEditor.cpp
src/Mod/Mesh/Gui/RemeshGmsh.cpp
src/Mod/Mesh/Gui/RemeshGmsh.ui
src/Mod/Mesh/Gui/RemoveComponents.ui
src/Mod/Mesh/Gui/Segmentation.ui
src/Mod/Mesh/Gui/SegmentationBestFit.cpp
src/Mod/Mesh/Gui/SegmentationBestFit.ui
src/Mod/Mesh/Gui/Selection.ui
src/Mod/Mesh/Gui/SoFCIndexedFaceSet.cpp
src/Mod/Mesh/Gui/ViewProvider.cpp
src/Mod/Mesh/Gui/ViewProviderCurvature.cpp
src/Mod/Mesh/Gui/Workbench.cpp

Mesh: Update UI strings for consistency

Mesh: Update UI strings for consistency

---

src/Mod/ReverseEngineering/App/AppReverseEngineering.cpp
src/Mod/ReverseEngineering/App/RegionGrowing.cpp
src/Mod/ReverseEngineering/Gui/AppReverseEngineeringGui.cpp
src/Mod/ReverseEngineering/Gui/Command.cpp
src/Mod/ReverseEngineering/Gui/FitBSplineCurve.ui
src/Mod/ReverseEngineering/Gui/FitBSplineSurface.cpp
src/Mod/ReverseEngineering/Gui/FitBSplineSurface.ui
src/Mod/ReverseEngineering/Gui/Segmentation.ui
src/Mod/ReverseEngineering/Gui/SegmentationManual.ui
src/Mod/ReverseEngineering/Gui/Workbench.cpp

ReverseEngineering: Update UI strings for consistency

ReverseEngineering: Update UI strings for consistency

---

src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp
src/Mod/Spreadsheet/Gui/Command.cpp
src/Mod/Spreadsheet/Gui/DlgBindSheet.cpp
src/Mod/Spreadsheet/Gui/DlgBindSheet.ui
src/Mod/Spreadsheet/Gui/DlgSettings.ui
src/Mod/Spreadsheet/Gui/DlgSheetConf.ui
src/Mod/Spreadsheet/Gui/LineEdit.cpp
src/Mod/Spreadsheet/Gui/PropertiesDialog.ui
src/Mod/Spreadsheet/Gui/Sheet.ui
src/Mod/Spreadsheet/Gui/SheetTableView.cpp
src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp
src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp
src/Mod/Spreadsheet/Gui/Workbench.cpp
src/Mod/Spreadsheet/Gui/ZoomableView.cpp

Spreadsheet: Update UI strings for consistency

Spreadsheet: Update UI strings for consistency

---

.github/codespellignore

Added `InvertIn, LeadIn, linez`
ref: https://github.com/FreeCAD/FreeCAD/pull/22137/files

codespell: add 3 false positives to ignore list

---

tests/src/App/Property.cpp

Fixes an issue that non-deterministically crashes the tests. See https://github.com/FreeCAD/FreeCAD/pull/21975#issuecomment-3028110833 for why this is necessary.

Core: Fix property rename test

---

src/Mod/Fem/Gui/Command.cpp
src/Mod/Fem/Gui/TaskPostFrames.ui
src/Mod/Fem/femcommands/commands.py

Small cleanup after #22234
Ressonance frequencies --> Resonant frequencies
Clears the mesh of an FEM mesh object --> Clears the mesh of a FEM mesh object
Spring Constraint --> Spring Boundary Condition

FEM: UI string consistency cleanup

---

src/Mod/TechDraw/TechDrawTools/TaskFillTemplateFields.py

`QCheckBox` `setChecked` => `setCheckState` , I'll review the rest of the code and if found, raise PR(s) as required.
Fixes #22353

[TechDraw] Fix Qt6 compatability of FillTemplateFields tool

---

src/Mod/Sketcher/Gui/EditDatumDialog.cpp

A radius or diameter label's position is an angle so it should not be scaled like a line label position.
Implements a fix for: #22285

Sketcher: Autoscale: do not scale dimension's position if it is a radius or diameter

---

src/Mod/BIM/ArchCommands.py

Fixes #21668.
This PR adds an `OutListRecursive` check to `addComponents` function.
Additionally:
* Miscellaneous fixes.
* Helper function `_usedForAttachment` for attachment checks.

BIM: check OutListRecursive in addComponents

---

src/Mod/Draft/draftutils/gui_utils.py

PR the improve the if-else logic of the `autogroup` function.

Draft: gui_utils.py minor improvement for autogroup

---

src/Mod/CAM/Path/Post/scripts/fanuc_post.py
tests/src/App/Property.cpp

This PR Updates the Fanuc post-processor to search for tool attributes that actually exist.
#14016

CAM: Fix for Fanuc Post-Processor

---

src/Mod/BIM/ArchWindowPresets.py

Further to Bug-fix Changing Sill _&_ SketchArch Support Sill Property
- https://github.com/FreeCAD/FreeCAD/pull/21726 , minor fix to make ensure tracking of sill works upon window creation.

[ArchWindowPresets]  Further Fix Sill Change

---

src/Mod/BIM/ArchPipe.py

Fixes #22361
Fixes #22362 
#22362 also requires #22376.

BIM: fix Height and Width inversion for rectangular pipes

---

src/Mod/BIM/ArchWindow.py

Fix #21640
BIM: Automatic hole depth for windows issue (new window depth algorithm cannot determine the width of the wall when using multimaterial)

[ArchWindow]  subVolume Support Multi-Material (bug fix)

---

src/Mod/TechDraw/App/DrawViewDetail.cpp
src/Mod/TechDraw/App/DrawViewDetail.h
src/Mod/TechDraw/App/DrawViewPart.cpp
src/Mod/TechDraw/App/DrawViewPart.h
src/Mod/TechDraw/App/DrawViewSection.cpp
src/Mod/TechDraw/App/DrawViewSection.h

This PR implements a fix for issue #22329.  Specifically it reverses the property type changes introduced in PR #19941.

[TD]Revert property type changes (fix #22329)

---

src/Gui/CMakeLists.txt
src/Gui/Inventor/Draggers/SoLinearDragger.cpp
src/Gui/Inventor/Draggers/SoLinearDragger.h
src/Gui/Inventor/Draggers/SoRotationDragger.cpp
src/Gui/Inventor/Draggers/SoRotationDragger.h
src/Gui/Inventor/Draggers/SoTransformDragger.cpp
src/Gui/Inventor/Draggers/SoTransformDragger.h
src/Gui/Inventor/SoToggleSwitch.cpp
src/Gui/Inventor/SoToggleSwitch.h
src/Gui/SoFCDB.cpp
src/Gui/Utilities.h

This PR improves the `SoRotationDragger` class and also introduces the new `SoRotationDraggerContainer` class. This is a continuation of my work for the GSOC (see https://github.com/FreeCAD/FreeCAD/pull/21451).
Note: This is a draft because the activeColor is not working i.e the color of the dragger is not changing while dragging. Also, the commented lines need to be removed before merging.

Gui: refactor SoRotationDragger

---

src/Mod/Part/App/PartFeature.cpp

PR #21257 included broad refactoring of call sites of Part::Feature::getTopoShape and two of them were misconverted which introduced weird behavior in techdraw reported on discord
@oursland does it fix #22291?

Part: Fix regression introduced by #21257

---

src/Mod/Measure/Gui/TaskMeasure.cpp

This PR has been created specifically at the request of @hyarion see https://github.com/FreeCAD/FreeCAD/issues/22434#issuecomment-3066718777
Fixes #22434

[Measure] Revert one specific piece of code from PR19142

---

src/Mod/Assembly/App/AssemblyObject.cpp
src/Mod/Assembly/App/AssemblyObject.h

Fix https://github.com/FreeCAD/FreeCAD/issues/20614
see the issue for description.

Assembly: Fix crash 20614

---

src/Mod/Fem/App/FemConstraintContact.cpp
src/Mod/Fem/App/FemConstraintContact.h
src/Mod/Fem/femsolver/calculix/write_constraint_contact.py

fixes #22512
Adds a new Hard Contact property that, when enabled, changes the default linear contact to hard contact.

FEM: Add hard contact with CalculiX

---

src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h
src/Mod/Sketcher/Gui/EditDatumDialog.cpp

Pretty much the title, if a user edits a datum that is not scale defining, the scale action should not be triggered.
Implements a fix for #22411

Sketcher: Only autoscale if the datum being edited is the scale defining datum

---

src/Mod/Assembly/JointObject.py

Assembly: Fix error message flexible assembly #22561

---

src/Gui/InputHint.h
src/Mod/Sketcher/Gui/DrawSketchHandler.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfHyperbola.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfParabola.h
src/Mod/Sketcher/Gui/DrawSketchHandlerArcSlot.h
src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h
src/Mod/Sketcher/Gui/DrawSketchHandlerCarbonCopy.h
src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h
src/Mod/Sketcher/Gui/DrawSketchHandlerExtend.h
src/Mod/Sketcher/Gui/DrawSketchHandlerExternal.h
src/Mod/Sketcher/Gui/DrawSketchHandlerFillet.h
src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h
src/Mod/Sketcher/Gui/DrawSketchHandlerLineSet.h
src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h
src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h
src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h
src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h
src/Mod/Sketcher/Gui/DrawSketchHandlerRotate.h
src/Mod/Sketcher/Gui/DrawSketchHandlerScale.h
src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h
src/Mod/Sketcher/Gui/DrawSketchHandlerSplitting.h
src/Mod/Sketcher/Gui/DrawSketchHandlerSymmetry.h
src/Mod/Sketcher/Gui/DrawSketchHandlerTranslate.h
src/Mod/Sketcher/Gui/DrawSketchHandlerTrimming.h
tests/src/Gui/CMakeLists.txt
tests/src/Gui/InputHintTest.cpp

This PR refactors tool hints in Sketcher to not repeat the hint table logic that much.
First commit introduces a generic, reusable HintTable system for GUI input hints: it adds comparison operators to InputHint and its nested InputSequence, defines templated StateHints and HintTable containers, and implements a lookupHints helper that replaces the previous ad-hoc lookup logic; accompanying unit tests (tests/src/Gui/InputHintTest.cpp) exercise both single-state and composite-state scenarios
Later ones implement that mechanism for all tools in Sketcher.
The last commit uses `Q_DECLARE_TR_FUNCTIONS` in the DrawSketchHandler so it is easier to write and read.
CC @longrackslabs

Sketcher: Refactor Tool Hints

---

src/Gui/SoDatumLabel.cpp
src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.h

fixes #22268
This PR adds a second arc helper to the diameter constraint if the second side of the diameter arrow doesn't point directly on the arc.
Also removed some duplicate code since glDrawArc does the same as the part where the helpers where drawn before.
Before:
After:

Sketcher: Add second arc helper on diameter constraint

---

src/Gui/Inventor/Draggers/SoLinearDragger.cpp
src/Gui/Inventor/Draggers/SoRotationDragger.cpp
src/Gui/StyleParameters/Parser.cpp

Fix some MSVC compiler warnings.

Gui: Fix compiler warnings

---

src/Mod/Draft/draftguitools/gui_snapper.py

Fixes #22367.
Instead of processing all points several times, just use the single unprojected snap point. Note that there is still a significant delay when snapping to the point cloud mentioned in the issue. It is ca. 5 seconds, much better than 50 minutes, but still unworkable.

Draft: fix hang on snapping to large point cloud

---

src/Mod/Assembly/App/AssemblyObject.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/22642

Assembly: Fix unconnected Joints always touched

---

src/Mod/PartDesign/App/FeatureHole.cpp

Add a migration tag to PartDesign code that does migration. This PR serves as an example of https://github.com/FreeCAD/FreeCAD/issues/22648.
Part of https://github.com/FreeCAD/FreeCAD/issues/22648

PartDesign: Add migration tag

---

src/Mod/Spreadsheet/App/CMakeLists.txt
src/Mod/Spreadsheet/App/PropertyColumnWidthsPy.pyi
src/Mod/Spreadsheet/App/PropertyRowHeightsPy.pyi
src/Mod/Spreadsheet/App/PropertySheetPy.pyi
src/Mod/Spreadsheet/App/SheetPy.pyi
src/Mod/Spreadsheet/Gui/CMakeLists.txt
src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheetPy.pyi
src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheetPy.xml

Creation of the python interface stubs for Spreadsheet.
https://github.com/FreeCAD/FreeCAD/issues/21784

Core: Generation of Spreadsheet interface bindings

---

src/Mod/Mesh/App/CMakeLists.txt
src/Mod/Mesh/App/EdgePy.pyi
src/Mod/Mesh/App/FacetPy.pyi
src/Mod/Mesh/App/MeshFeaturePy.pyi
src/Mod/Mesh/App/MeshFeaturePy.xml
src/Mod/Mesh/App/MeshPointPy.pyi
src/Mod/Mesh/App/MeshPy.pyi
src/Mod/Mesh/App/MeshPy.xml
src/Mod/Mesh/Gui/CMakeLists.txt
src/Mod/Mesh/Gui/ViewProviderMeshPy.pyi

Creation of the python interface stubs for Mesh
https://github.com/FreeCAD/FreeCAD/issues/21784

Core: Generation of Mesh interface bindings

---

src/Mod/Part/App/FeatureOffset.cpp
tests/src/Mod/Part/App/FeatureOffset.cpp

Replace PR #22645 
Switch API call of Feature Offset2D from makeOffset2D to makeElementOffset2D
fixes #22563

Part: Feature Offset2D fix #22563

---

.github/codespellignore

codespell: add 'DocumentIn' to list

---

src/Gui/ApplicationPy.cpp

This replaces https://github.com/FreeCAD/FreeCAD/pull/22196, and fixes #22414 (and probably #22377).
#22196 was designed to fix a serious bug that resulted in a circular import because the use of the `inspect.stack()` could cause imports to occur. If the `sAddCommand` function was being called as part of an import itself, this could result in the errors described starting [here](https://github.com/FreeCAD/FreeCAD/pull/21981#issuecomment-3003613054).
Unfortunately, the original solution, to use the `traceback` module, caused #22414.
To work around both of these issues, this PR proposes to use a much lower-level Python functionality, `sys._getframe()`.

Gui: Replace use of traceback with sys._getframe()

---

src/Mod/Assembly/CommandInsertLink.py

Fix https://github.com/FreeCAD/FreeCAD/issues/22676
Fix https://github.com/FreeCAD/FreeCAD/issues/22674
Two birds one small stone

Assembly: Fix insert sub-assemblies positioning issues

---

src/Mod/Sketcher/App/SketchObject.cpp

Sketcher: Avoid crash when using trim as described in #22352

---

src/Gui/ApplicationPy.cpp

This PR replaces an instance of Py::Int which was introduced in [d49b94f0ca1940813e8ff46aed13cb2e7d8dbeb8](https://github.com/FreeCAD/FreeCAD/commit/d49b94f0ca1940813e8ff46aed13cb2e7d8dbeb8) by Py::Long. This fixes the build on my machine (ubuntu 25.04),
Py::Int is used nowhere else in the codebase, but Py::Long is, so I think it's fine to use it

Fix build error on ubuntu

---

src/Mod/BIM/bimcommands/BimLayers.py
src/Mod/BIM/importers/importWebGL.py
src/Mod/Sketcher/SketcherTests/TestSketcherSolver.py

Fix various source comment typos

---

src/Mod/Assembly/UtilsAssembly.py

Tiny thing that was forgotten after datum PR merged.

Assembly: utils: tiny fix

---

src/Mod/PartDesign/App/FeatureHole.cpp
src/Mod/PartDesign/App/FeatureHole.h

If the base profile of the hole is a cylindrical surface, set the hole direction to the cylinder's axis rather than taking the normal of the face. Throws when trying to build a hole from a non-cylindrical surface.
Implements a fix for #22307

PartDesign: Hole: get direction from cylindrical surface rather than normal

---

src/Mod/Sketcher/Gui/EditModeCoinManager.cpp
src/Mod/Sketcher/Gui/EditModeCoinManager.h
src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.cpp
src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h
src/Mod/Sketcher/Gui/Utils.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

This pr uses the isConstructionMode() function to change the EditCurvesDrawStyle in the drawEdit() function to match the style of either the construction curves or the defining curves.
#22288 
https://github.com/user-attachments/assets/455d8e39-a656-4706-9187-ecf4ea28e828

Sketcher: Change the style of the curves in creation to match the construction/defining flag

---

src/Mod/Import/App/CMakeLists.txt
src/Mod/Import/App/StepShapePy.pyi
src/Mod/Measure/App/CMakeLists.txt
src/Mod/Measure/App/MeasureBasePy.pyi
src/Mod/Measure/App/MeasurementPy.pyi
src/Mod/Measure/Gui/CMakeLists.txt
src/Mod/Measure/Gui/QuickMeasurePy.pyi
src/Mod/Points/App/CMakeLists.txt
src/Mod/Points/App/PointsPy.pyi
src/Mod/Points/App/PointsPy.xml
src/Mod/Robot/App/CMakeLists.txt
src/Mod/Robot/App/Robot6AxisPy.pyi
src/Mod/Robot/App/RobotObjectPy.pyi
src/Mod/Robot/App/RobotObjectPy.xml
src/Mod/Robot/App/TrajectoryPy.pyi
src/Mod/Robot/App/TrajectoryPy.xml
src/Mod/Robot/App/WaypointPy.pyi
src/Mod/Surface/App/Blending/BlendCurvePy.pyi
src/Mod/Surface/App/Blending/BlendCurvePy.xml
src/Mod/Surface/App/Blending/BlendPointPy.pyi
src/Mod/Surface/App/Blending/BlendPointPy.xml
src/Mod/Surface/App/CMakeLists.txt

Creation of the last of the interface bindings to complete the associated issue. This consists of bindings for:
- Measure
- Import
- Points
- Robot
- Surface
To clarify, this is the last of the PR's to close out the associated issue.
https://github.com/FreeCAD/FreeCAD/issues/21784

Core: Generation of misc interface bindings

---

src/Mod/CAM/App/AreaPy.pyi
src/Mod/CAM/App/AreaPy.xml
src/Mod/CAM/App/CMakeLists.txt
src/Mod/CAM/App/CommandPy.pyi
src/Mod/CAM/App/CommandPy.xml
src/Mod/CAM/App/FeatureAreaPy.pyi
src/Mod/CAM/App/FeaturePathCompoundPy.pyi
src/Mod/CAM/App/PathPy.pyi
src/Mod/CAM/App/VoronoiCellPy.pyi
src/Mod/CAM/App/VoronoiEdgePy.pyi
src/Mod/CAM/App/VoronoiPy.pyi
src/Mod/CAM/App/VoronoiVertexPy.pyi

Description
Creation of the python interface stubs for CAM.
https://github.com/FreeCAD/FreeCAD/issues/21784

Core: Generation of python bindings for CAM

---

src/Mod/Draft/draftguitools/gui_trimex.py

This PR adds a dotted lineTracker in Trimex extrude mode. This tracker connects the center of mass of the face with the picked point. It is intended to inform the user how the extrusion length is determined if the picked point is co-planar with the face.
See:
https://github.com/FreeCAD/FreeCAD/issues/19531#issuecomment-2650573210

Draft: show dotted lineTracker in Trimex extrude mode

---

src/Mod/TechDraw/TechDrawTools/TaskFillTemplateFields.py

Backport of #22355 to Releases/FreeCAD-1-0 branch
FYI @adrianinsaval

[1.0] [TechDraw] Fix Qt6 compatability of FillTemplateFields tool

---

src/Mod/Points/Gui/Command.cpp

Backport of #22449 
FYI @adrianinsaval

[1.0] [Points] Add e57 to import file extensions

---

src/Gui/SoDatumLabel.cpp
src/Gui/SoDatumLabel.h

This is a backport of https://github.com/FreeCAD/FreeCAD/commit/65f737e
FYI @adrianinsaval

[1.0] [GUI] Remove dark fringe around letters

---

.github/workflows/sub_buildPixi.yml
.github/workflows/sub_buildUbuntu.yml

* Correct the cache key name for Ubuntu
* Synchronize the `ccache` configuration on pixi
* None
N/A

CI: ccache fix

---

src/Mod/Part/Gui/Workbench.cpp

Part: Remove redundant Part Import and Export tools from the menu

---

src/Gui/SoDatumLabel.cpp

n/a
Fixes the drawing of angle constraints that go beyond the centerpoint of an arc or have negative value.
Was fixed in #22651 but got lost in #21920
Before:
After:

Sketcher: Fix drawing of angle constraints

---

src/App/Extension.cpp
src/App/Extension.pyi
src/App/ExtensionPyImp.cpp
src/App/ExtensionPython.h
src/Mod/Test/Document.py

Fix parameter replacement by using stringizing.
Add scope resolution to Property pointers to be able to use the macro in modules other than App.
Currently, the macro doesn't work, making it impossible to run methods of the Python Proxy object instead of those of the C++ class.
Also fixed the silently failing unit test.

App: Fix ExtensionPython macro

---

src/Mod/Fem/femguiutils/data_extraction.py

The change in modules is from VTK 9.3 inclusive.
@ickby

Fem: Fix VTK submodule import

---

src/Gui/PropertyView.cpp
src/Gui/PropertyView.h
src/Gui/propertyeditor/PropertyEditor.cpp
src/Gui/propertyeditor/PropertyEditor.h
src/Gui/propertyeditor/PropertyItem.cpp
src/Gui/propertyeditor/PropertyItem.h
src/Gui/propertyeditor/PropertyModel.cpp
src/Gui/propertyeditor/PropertyModel.h

This PR introduces a "rename property" item in the Property View context menu that allows you to rename a property.
Closes [#16222](https://github.com/FreeCAD/FreeCAD/issues/16222).

Gui: Add support for renaming properties

---

src/Mod/Draft/InitGui.py
src/Mod/Draft/draftguitools/gui_snapper.py
src/Mod/Draft/draftutils/init_draft_statusbar.py

Draft: toolbar names to title case

---

src/Mod/Measure/App/Measurement.cpp
src/Mod/Measure/App/Measurement.h

This PR allows the Measure class to give itself a hint on what type of shape it expects so that compound shape can be reduced to a subshape of the right type.
Fix #22686

Measure: resolve compound shapes in some cases

---

src/Mod/CAM/Path/Op/Base.py

Fix #22720
https://forum.freecad.org/viewtopic.php?t=98572

CAM: Fix seach tool controller in Operations group

---

src/App/DocumentObject.cpp
tests/src/App/Property.cpp

Adds a test and logic for a property rename that obtains its value from an expression.
Closes #22984

Core: Fix renaming a property with an expression

---

src/App/Expression.cpp
tests/src/App/Expression.cpp

This PR fixes expression simplification for expression functions. For example a simplify on expression `sqrt(4)` would crash.
The PR contains several tests for this as well in a first commit. Without the second commit, running the test case segfaults.
Closes #22766

Core: Fix expression function simplify

---

src/Base/Color.cpp
src/Base/Color.h
src/Gui/Dialogs/DlgThemeEditor.cpp
src/Gui/StyleParameters/ParameterManager.cpp
src/Gui/StyleParameters/ParameterManager.h
src/Gui/StyleParameters/Parser.cpp
src/Gui/StyleParameters/Parser.h
src/Mod/PartDesign/Gui/CMakeLists.txt
src/Mod/PartDesign/Gui/StyleParameters.h
src/Mod/PartDesign/Gui/ViewProvider.cpp
src/Mod/PartDesign/Gui/ViewProviderDressUp.cpp
tests/src/Gui/StyleParameters/ParameterManagerTest.cpp
tests/src/Gui/StyleParameters/ParserTest.cpp

This PR introduces theme-configurable colors, transparency levels and other properties for the transparent previews, replacing hardcoded values with entries in the Style Parameters system. That PR does not introduce many functional changes, mostly small refactor of Style Parameters introducing better API to obtain parameters via code.
- **Style Parameters** now use `Base::Color` instead of `QColor` for consistent color handling across the codebase.
- Added new way to define parameters in code using `ParameterDefinition<T>` struct. Examples of use can be found under `PartDesignGui::StyleParameters`:
- **Base::Color** updated to be `constexpr`-constructible, enabling compile-time defaults. 
This allows preview appearance—colors, transparency, and line width—to be easily customized via …

Gui: Add theming abilities to Transparent Previews

---

src/Mod/BIM/bimcommands/BimLeader.py
src/Mod/Draft/Resources/ui/TaskPanel_SetStyle.ui
src/Mod/Draft/Resources/ui/dialog_AnnotationStyleEditor.ui
src/Mod/Draft/Resources/ui/preferences-drafttexts.ui
src/Mod/Draft/draftfunctions/svg.py
src/Mod/Draft/draftguitools/gui_annotationstyleeditor.py
src/Mod/Draft/draftguitools/gui_setstyle.py
src/Mod/Draft/draftmake/make_dimension.py
src/Mod/Draft/draftobjects/dimension.py
src/Mod/Draft/draftobjects/draft_annotation.py
src/Mod/Draft/draftobjects/label.py
src/Mod/Draft/draftobjects/text.py
src/Mod/Draft/draftobjects/wire.py
src/Mod/Draft/drafttests/draft_test_objects.py
src/Mod/Draft/draftutils/gui_utils.py
src/Mod/Draft/draftutils/utils.py
src/Mod/Draft/draftviewproviders/view_dimension.py
src/Mod/Draft/draftviewproviders/view_draft_annotation.py
src/Mod/Draft/draftviewproviders/view_label.py
src/Mod/Draft/draftviewproviders/view_wire.py

Fixes #7573
This PR adds the properties `ArrowTypeStart`, `ArrowTypeEnd` and all the code/settings/ui needed to manage these new two properties.

[Feature Request] [Draft] [UI/UX] Allow to turn dimension arrows on/off individually

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

Fixes #20917
This PR removes the Option "Edit Value" for non dimensional Constraints from the right click menu if you click on a constraint in the 3d view. 
Before the option was displayed for all constraints but only worked for dimensional constraints like length or angle.
I removed the option for non dimensional types of constraints.
Before:
After:

Sketcher: Remove Edit Value Option from Right Click Menu for non dimensional Constraints

---

src/Mod/PartDesign/App/FeatureHole.cpp

PartDesign: Hole: fallback to getProfileNormal on flat surface

---

src/Mod/Part/Gui/CrossSections.cpp
src/Mod/Part/Gui/CrossSections.h

This fixes crash that can happen due to uncaught exception in Cross Sections computation. It does not make the cross sections compute properly but gracefully handles that case.
Fixes: #18456

Part: Prevent crash on cross-section of invalid object

---

src/Mod/TechDraw/Gui/CommandAnnotate.cpp

TechDraw: Fix tooltip in Gui/CommandAnnotate.cpp

---

src/Mod/Fem/femobjects/solver_calculix.py

@FEA-eng We forgot this in https://github.com/FreeCAD/FreeCAD/pull/22912
@chennes

Fem: Fix module import in solver CalculiX object

---

src/Mod/Draft/draftguitools/gui_labels.py

Draft: Make Draft_Label tooltip consistent

---

src/Mod/CAM/Roadmap/Epics/Circular Holes Improvement.md
src/Mod/CAM/Roadmap/README.md

This adds an epic for improving the circular hole gui and logic.

CAM: Roadmap epic for circular hole improvements

---

src/Mod/CAM/Roadmap/README.md

I didn't add a detail page for this, because the pain points are already described in the main README. I just think there should be an epic for this, since we are prioritizing changes that fit within an epic

[CAM] Add roadmap epic for fixing user pain points

---

src/Mod/BIM/bimcommands/BimSpace.py

BIM: change shortcut for Arch_Space

---

src/Mod/PartDesign/Gui/ViewProviderHole.cpp

This PR prevents hole from claiming other features as children by introducing additional check that is also present in Sketch Based features.
Fixes: #22115

PartDesign: Prevent Hole from claiming other features as children

---

src/Mod/Fem/feminout/writeFenicsXDMF.py

fixes #22760
@violettinged FYI

FEM: Fix xdmf export of second-order meshes

---

src/Mod/Part/App/FCBRepAlgoAPI_BooleanOperation.cpp

The current solution checked shapes before allowing boolean operation to happen. That meant that even small error with model in an unrelated place could prevent the boolean from being computed, even if it would compute fine and create valid shape. It seems like overkill as it can prevent users from achieving the goal. 
This commit changes that behavior so the tool at least tries to compute the results.
Fixes: #18456 - It will actually compute fine with that patch.

Part: Relax boolean requirements

---

src/Gui/DocumentRecovery.ui
src/Gui/Stylesheets/FreeCAD.qss

This fixes looks of document recovery screen getting rid of wasted space. It also should properly react to resize.
Fixes #21194
| <img width="570" height="590" alt="image" src="https://github.com/user-attachments/assets/7d568637-b2a8-4fae-8bac-00c78d12aa31" /> | <img width="560" height="434" alt="image" src="https://github.com/user-attachments/assets/2a96a950-ea97-4306-9e44-9549b86b79e3" /> |

Gui: Fix Document Recovery screen

---

src/Mod/Assembly/JointObject.py

As the title says - root cause of this problem was imprecise reference matching by moving_part and TNP string processing incosistencies, so the solution is to give enhanced matching and TNP string mapping for reliable deletion.
Also added context menu with keyboard shortucs so user is able to delete stuff with right click.
Demo:
https://github.com/user-attachments/assets/d32fa333-15e8-4e35-acf9-fd21efa8a4cd
Resolves: https://github.com/FreeCAD/FreeCAD/issues/23078

Assembly: Allow editing joint references

---

src/Gui/SoDatumLabel.cpp

Removed unused variables. 
Removed dead code (thanks @matthiasdanner) 
fix [-Wunused-variable]

Clean SoDatumLabel.cpp

---

src/Mod/BIM/ArchWindow.py

Problems / Course of Developement:
1. Allow changing Sill feature was added in
- https://github.com/FreeCAD/FreeCAD/pull/21005
2. Bug fix was added in
- https://github.com/FreeCAD/FreeCAD/commit/f6bba5d58ec7788c37977b97d7db40ef1e1ff499
3. Further Problems were identified as discused in
- https://github.com/FreeCAD/FreeCAD/pull/21005#issuecomment-3010959162
'New Observation-
1. Clone or Link to a Window does not work and return error
2. This PR/Commit (21005) translate the Base Sketch when Sill property is changed, to change the final disposition of a Window object; however, it will also shift the disposition of a Clone and Link as a result (with error message above fixed). This is apparently not an expected behaviour.
(Sidenote- When SketchArch Addon is installed and parametric placement …

[ArchWindow]  Clone and Link to Support Sill Change

---

src/Gui/Stylesheets/FreeCAD Dark.qss
src/Gui/Stylesheets/FreeCAD Light.qss
src/Gui/Stylesheets/FreeCAD.qss

This set minimal height for QTableView in tasks panel for content to become visible.
fixes  #22957 
Before (classic, light, dark themes)
<details>
</details>
After (~classic~, light, dark themes)
> classic theme is not included here, more on  that in separate comment below
<details>
</details>

CAM: QTableView height too small in tasks panel

---

src/Mod/PartDesign/App/FeatureExtrude.cpp
src/Mod/PartDesign/App/FeatureLoft.cpp
src/Mod/PartDesign/App/FeaturePipe.cpp

follow up on #23286 - turns out there are more such messages per feature so I updated the missed ones

PartDesign: Update missed error message about multiple solids

---

src/Mod/BIM/ArchStructure.py

Fix #22822
See discussion and example model file in github :- https://github.com/FreeCAD/FreeCAD/issues/22822

[ArchStructure]  Fix Regression : FaceMaker

---

src/Mod/Fem/App/FemMesh.cpp

@chennes @FEA-eng not acquiring the GIL before executing Python code from C++ is undefined behavior. Can you check if this resolves the crash reported in #23380  on Windows?

Fem: Acquire the GIL before running Python code

---

src/Mod/Part/Gui/ViewProviderPreviewExtension.cpp
src/Mod/PartDesign/Gui/ViewProviderTransformed.cpp

- Fixes https://github.com/FreeCAD/FreeCAD/issues/23146
- https://github.com/FreeCAD/FreeCAD/issues/23250

Gui: Do not compute preview while restoring

---

src/Mod/Mesh/Gui/Command.cpp

Mesh: Change 1 missed dialog title to Title Case

---

src/Mod/Draft/draftgeoutils/intersections.py
src/Mod/Draft/draftguitools/gui_snapper.py
src/Mod/Draft/draftutils/params.py

Intersection snap only worked between edges. This PR enables edge-face intersection snap.

Draft: Add edge-face intersection snap

---

src/Base/CoordinateSystem.cpp
src/Mod/CAM/Path/Dressup/Array.py
src/Mod/CAM/Path/Main/Stock.py
src/Mod/CAM/Path/Op/Gui/Array.py
src/Mod/CAM/Path/Op/Probe.py
src/Mod/Draft/Resources/ui/TaskPanel_OrthoArray.ui
src/Mod/Draft/Resources/ui/TaskSelectPlane.ui
src/Mod/Draft/Resources/ui/preferences-draftsnap.ui
src/Mod/Draft/draftobjects/array.py
src/Mod/Draft/draftobjects/patharray.py
src/Mod/Fem/App/FemConstraintDisplacement.cpp
src/Mod/Fem/App/FemConstraintRigidBody.cpp
src/Mod/Fem/femobjects/constraint_flowvelocity.py
src/Mod/Fem/femobjects/constraint_initialflowvelocity.py
src/Mod/Fem/femobjects/result_mechanical.py
src/Mod/Measure/App/MeasureDistance.cpp
src/Mod/Part/App/AttachExtension.cpp
src/Mod/Part/App/FeatureScale.cpp
src/Mod/Part/AttachmentEditor/TaskAttachmentEditor.ui
src/Mod/Part/Gui/DlgRevolution.ui
src/Mod/PartDesign/App/FeaturePrimitive.cpp
src/Mod/PartDesign/Gui/TaskPrimitiveParameters.ui

Update UI strings from Crowdin reports for consistency

Update UI strings from Crowdin reports for consistency

---

src/Mod/PartDesign/App/FeatureExtrude.cpp
src/Mod/PartDesign/App/FeatureExtrude.h
src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/23408
Fix https://github.com/FreeCAD/FreeCAD/issues/23404

PartDesign: Fix symmetric regression & LengthAlongSketchNormal

---

src/Gui/Selection/SoFCUnifiedSelection.h

Fix https://github.com/FreeCAD/FreeCAD/issues/23447
@kadet1090 can you please check if this is the correct fix?

Link: MaterialOverride: fix transparency inversion

---

src/Mod/Fem/Gui/TaskFemConstraintContact.cpp
src/Mod/Fem/Gui/TaskFemConstraintHeatflux.cpp
src/Mod/Fem/Gui/TaskFemConstraintPressure.cpp
src/Mod/Fem/femmesh/meshsetsgetter.py
src/Mod/Fem/femmesh/meshtools.py
src/Mod/Fem/femsolver/calculix/write_constraint_bodyheatsource.py
src/Mod/Fem/femsolver/calculix/write_constraint_contact.py
src/Mod/Fem/femsolver/calculix/write_constraint_electricchargedensity.py
src/Mod/Fem/femsolver/calculix/write_constraint_electrostatic.py
src/Mod/Fem/femsolver/calculix/write_constraint_heatflux.py
src/Mod/Fem/femsolver/calculix/write_constraint_pressure.py
src/Mod/Fem/femsolver/calculix/write_constraint_tie.py
src/Mod/Fem/femtaskpanels/task_constraint_tie.py
src/Mod/Fem/femtest/data/calculix/box_static.inp
src/Mod/Fem/femtest/data/calculix/constraint_sectionprint.inp
src/Mod/Fem/femtest/data/calculix/constraint_transform_beam_hinged.inp
src/Mod/Fem/femtest/data/calculix/material_multiple_tensionrod_twoboxes.inp
src/Mod/Fem/femtest/data/calculix/material_nonlinear.inp

Add support for 2D loads for CalculiX to:
* Tie constraint
* Contact constraint
* Pressure constraint
* Heat Flux constraint
* Body Heat Source constraint
Edges and faces behave like faces and solids in 3D models, respectively.
2D thermal analysis should be tested with the new CalculiX solver (the old one does not load heat flux values ​​correctly).
TODO: The orientation of the symbols for the 2D case remains to be corrected. Currently, they point along the normal direction to the surface.
@FEA-eng 
fixes #13280, fixes #12778

Fem: Add support for 2D loads with CalculiX

---

src/Mod/Fem/App/FemConstraintContact.cpp
src/Mod/Fem/App/FemConstraintContact.h
src/Mod/Fem/femsolver/calculix/write_constraint_contact.py

fixes #23326
Introduces a new Surface Behavior property to toggle between Linear (default), Hard and Tied surface behavior types.

FEM: Add tied contact with CalculiX

---

src/Gui/Command.cpp
src/Gui/Command.h
src/Mod/Points/App/Points.cpp
src/Mod/Points/App/Points.h
src/Mod/Points/App/PointsGrid.h
src/Mod/Points/Gui/Command.cpp

This PR brings in Point related changes from @wwmayer's [branch](https://github.com/wwmayer/FreeCAD/tree/main-dev).

Points: Speed up translation of imported points

---

src/Mod/PartDesign/App/FeatureExtrude.cpp

Removed from src/Mod/PartDesign/App/FeatureExtrude.cpp

PartDesign: remove trailing whitespace

---

src/Mod/Draft/draftguitools/gui_snaps.py

I forgot to update the tooltip in #23352.

Draft: update intersection snap tooltip

---

src/Mod/Part/Gui/ViewProviderPreviewExtension.cpp
src/Mod/Part/Gui/ViewProviderPreviewExtension.h
src/Mod/PartDesign/App/FeatureBoolean.cpp
src/Mod/PartDesign/App/FeatureBoolean.h
src/Mod/PartDesign/Gui/StyleParameters.h
src/Mod/PartDesign/Gui/TaskBooleanParameters.cpp
src/Mod/PartDesign/Gui/TaskBooleanParameters.h
src/Mod/PartDesign/Gui/ViewProvider.cpp
src/Mod/PartDesign/Gui/ViewProviderBoolean.cpp
src/Mod/PartDesign/Gui/ViewProviderBoolean.h
src/Mod/PartDesign/Gui/ViewProviderDressUp.cpp

That PR implements missing preview for booleans in PartDesign. It depends on #23019 so should be merged after.
Closes: #11214 
https://github.com/user-attachments/assets/61bad5dc-ab21-4115-a9ad-309768584d5a

PartDesign: Implement preview for Booleans

---

src/Mod/Part/App/BRepOffsetAPI_MakePipeShell.pyi
src/Mod/Part/App/BSplineSurface.pyi
src/Mod/Part/App/BezierSurface.pyi
src/Mod/Part/App/FCBRepAlgoAPI_BooleanOperation.cpp
src/Mod/Part/App/Geom2d/BSplineCurve2d.pyi
src/Mod/Part/App/Geom2d/BezierCurve2d.pyi
src/Mod/Part/App/Geom2d/Circle2d.pyi
src/Mod/Part/App/Geom2d/Curve2d.pyi
src/Mod/Part/App/Geom2d/Ellipse2d.pyi
src/Mod/Part/App/Geom2d/Line2dSegment.pyi
src/Mod/Part/App/MeasureClient.cpp
src/Mod/Part/App/ShapeFix/ShapeFix_EdgeConnect.pyi
src/Mod/Part/App/ShapeFix/ShapeFix_FixSmallFace.pyi
src/Mod/Part/App/ShapeFix/ShapeFix_FreeBounds.pyi
src/Mod/Part/App/ShapeFix/ShapeFix_ShapeTolerance.pyi
src/Mod/Part/App/ShapeUpgrade/UnifySameDomain.pyi
src/Mod/Part/App/TopoShape.pyi
src/Mod/Part/App/TopoShapeEdge.pyi
src/Mod/Part/App/TopoShapeFace.pyi
src/Mod/Part/App/TopoShapeShell.pyi
src/Mod/Part/App/TopoShapeSolid.pyi
src/Mod/Part/App/TopoShapeWire.pyi
src/Mod/Part/Gui/TaskCheckGeometry.cpp
src/Mod/Part/Gui/TaskThickness.cpp
src/Mod/Part/Gui/ViewProviderPartExt.pyi

Removes trailing whitespace from several Part wb files

Part: remove trailing whitespace

---

src/App/PropertyStandard.cpp
src/Base/Persistence.cpp
src/Base/Persistence.h
src/Base/PreCompiled.h
src/Mod/Test/Document.py
tests/src/Base/Reader.cpp

From @wwmayer https://github.com/wwmayer/FreeCAD/tree/issue_22123
Fixes https://github.com/FreeCAD/FreeCAD/issues/22123
Replaces https://github.com/FreeCAD/FreeCAD/pull/23211

Fix STEP import with bad string behavior

---

src/Mod/TechDraw/App/DrawView.cpp
src/Mod/TechDraw/App/DrawView.h
src/Mod/TechDraw/App/DrawViewPart.cpp
src/Mod/TechDraw/App/DrawViewSection.cpp
src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/QGIFace.cpp
src/Mod/TechDraw/Gui/QGIFace.h
src/Mod/TechDraw/Gui/TechDrawHandler.cpp
src/Mod/TechDraw/Gui/ViewProviderViewPart.h

This PR brings in TechDraw related changes from @wwmayer's [branch](https://github.com/wwmayer/FreeCAD/tree/main-dev).
Fixes: #14238

TechDraw: random fixes

---

src/Mod/Fem/Gui/DlgSettingsFemZ88.ui

small fix for one Z88 preference tooltip

FEM: Fix typo in Z88 preference tooltip

---

src/Mod/Part/Gui/DlgSettingsGeneral.cpp
src/Mod/Part/Gui/DlgSettingsGeneral.ui
src/Mod/PartDesign/Gui/StyleParameters.h
src/Mod/PartDesign/Gui/ViewProviderSketchBased.cpp
src/Mod/PartDesign/Gui/ViewProviderSketchBased.h

This adds highlight for sketches etc that are used to create certain
featuires.
Depends on #23062

PartDesign: Highlight profile for profile based features 

---

src/Gui/propertyeditor/PropertyEditor.cpp
src/Gui/propertyeditor/PropertyEditor.h

This PR adds a binding for the delete key to remove one or more properties from a property container. On Mac, the backspace functions as delete key as is normal on Mac.
It also fixes a bug with multiple Copy entries in the menu, something that interfered with this PR and was therefore resolved in this PR.
Closes https://github.com/FreeCAD/FreeCAD/issues/15560.
Partially solves https://github.com/FreeCAD/FreeCAD/issues/23135 (item 4).

Gui: Add a binding for the Delete key to remove a property

---

src/Gui/Inventor/SoFCPlacementIndicatorKit.h
src/Gui/View3DInventorViewer.cpp

Makes axis cross visible on top of all shapes and use the new style including labels.
- Fixes https://github.com/FreeCAD/FreeCAD/issues/23314

 Gui: Show Axis Cross on top 

---

src/Mod/TechDraw/Gui/AppTechDrawGui.cpp
src/Mod/TechDraw/Gui/CommandCreateDims.cpp
src/Mod/TechDraw/Gui/QGIFace.cpp
src/Mod/TechDraw/Gui/QGIFace.h
src/Mod/TechDraw/Gui/QGIPrimPath.cpp
src/Mod/TechDraw/Gui/QGIViewPart.cpp
src/Mod/TechDraw/Gui/QGIViewSection.cpp
src/Mod/TechDraw/Gui/TaskSectionView.cpp
src/Mod/TechDraw/Gui/TaskSectionView.h

TechDraw: Remove unused functions

---

src/Mod/Part/Gui/TaskAttacher.ui

@chennes these were missed in https://github.com/FreeCAD/FreeCAD/commit/9cae60a70f14167b4e41beae4ee2355e7262de69

Fix missed string update

---

.github/codespellignore

Added several more typos for codespell to ignore.

CI: Add new entries to codespellignore file

---

src/Mod/Part/App/Attacher.cpp

Part: Make dragger attach to the midpoint / axis for circular edges and faces.
Currently it only works for closed circles or cylinders.
Fixes https://github.com/FreeCAD/FreeCAD/issues/19273
Before, then after:
https://github.com/user-attachments/assets/6a13f79a-ad34-4426-97a7-3fc5f3ea605e

Part: Make dragger attach to the midpoint / axis

---

src/Mod/Part/Gui/ViewProviderPreviewExtension.cpp
src/Mod/Part/Gui/ViewProviderPreviewExtension.h

This fixes bug with previews rendered incorrectly. To be honest, I have no idea why it works - but there seems to be a problem with calculating near and far planes when using SoTransform. Using SoMatrixTransform fixes the issue and as a bonus code is cleaner.
@Rexbas FYI, maybe you will have some idea why that can be the case.
- Fixes https://github.com/FreeCAD/FreeCAD/issues/23577

Gui: Fix preview rendering issues

---

src/Mod/CAM/Path/Tool/Controller.py

[CAM] change default TC name to 5mm endmill

---

src/Mod/CAM/Path/Post/Processor.py

Fixes #21657 
In summary, two tool controllers can have the same tool number but different spindle speeds. When we generate gcode, we execute a TC operation only if it is required. However, as a bug, this was implemented by checking the TC's tool number only. This means that if the user switches to a new TC with the same tool (number) but a different spindle speed, we fail to execute the TC change command.
I fix this by also checking for changes in spindle speed and direction.
As a note, if the tool (number) does not change, we don't actually need to issue a M3/M4 command to change tools, only a speed change command. However, we do not currently have infrastructure for that (no information about the old TC is passed to the relevant function and I'm just looking to fix a bug for the …

[CAM] fix to ensure tool change command is issued for SpindleSpeed changes

---

src/Gui/Selection/SoFCUnifiedSelection.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/23443
By doing a check the trans value being 0.0 was interpreted as false by the if check.

Link: Fix MaterialOverride 0.0 transparency bug

---

src/Mod/Sketcher/App/SketchAnalysis.cpp
src/Mod/Sketcher/App/SketchObject.cpp
src/Mod/Sketcher/App/SketchObject.h
src/Mod/Sketcher/App/SketchObject.pyi
src/Mod/Sketcher/App/SketchObjectPyImp.cpp
src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
src/Mod/Sketcher/Gui/CommandSketcherTools.h
src/Mod/Sketcher/Gui/DrawSketchHandlerScale.h
src/Mod/Sketcher/Gui/EditDatumDialog.cpp

This PR deletes constraints before adding them back in sketcher's scale tool which is used by the autoscale feature. It also adds a way to skip solve on deletion of geometry/constraints which was necessary to fix a rendering bug. To do so a new enum DeleteOption has been created for deletion functions of SketchObject and some additional parameters have been exposed to the python API
Fixes: #22954
Fixes: #22808
Fixes: #22248 
Fixes: #22247

Sketcher: fix invalid constraint on first dimension

---

src/Mod/Fem/femmesh/meshsetsgetter.py
src/Mod/Fem/femsolver/calculix/write_constraint_centrif.py
src/Mod/Fem/femtaskpanels/task_constraint_centrif.py

Next step is to update the selection panel to accept datum geometries.
@FEA-eng

Fem: Add support for 2D geometries to Centrif constraint

---

src/Mod/Fem/Gui/DlgSettingsFemCcx.ui
src/Mod/Fem/Gui/DlgSettingsFemCcxImp.cpp
src/Mod/Fem/femcommands/commands.py
src/Mod/Fem/femexamples/thermomech_bimetal.py
src/Mod/Fem/femobjects/solver_calculix.py
src/Mod/Fem/femobjects/solver_ccxtools.py
src/Mod/Fem/femsolver/calculix/write_step_equation.py
src/Mod/Fem/femtest/data/calculix/thermomech_bimetal.inp

This prevents overriding user-defined time increment values ​​when running steady state thermo-mechanical analyses.
With the new Calculix framework, this function runs in a separate thread. Changing object properties from a separate thread should be avoided, as this generates the following warnings:
```
QObject::startTimer: Timers cannot be started from a separate thread
QObject::killTimer: Timers cannot be stopped from a separate thread
```
@FEA-eng

Fem: Use default CalculiX time increments for thermo-mechanical steady state analysis

---

src/Mod/Fem/femobjects/element_geometry1D.py
src/Mod/Fem/femobjects/element_geometry2D.py

Old `ElementGeometry2D` object doesn't have the `Offset` property.
@FEA-eng

Fem: Update old ElementGeometry*D with new properties

---

src/Base/FileInfo.cpp
src/Base/FileInfo.h
tests/src/Base/CMakeLists.txt
tests/src/Base/FileInfo.cpp

I started this more than a year ago as mentioned in https://github.com/FreeCAD/FreeCAD/pull/12066#discussion_r1461916858 but never finished, so @wwmayer had to save my day with his refactor. Code comes from [Codeberg's](https://codeberg.org/wwmayer/FreeCAD11) now non existent modernize_fileinfo branch (now part of [cherrypicks](https://codeberg.org/wwmayer/FreeCAD11/commits/branch/cherrypicks)) and was rebased on top of main.

Core: Modernize Fileinfo

---

src/Mod/Draft/draftobjects/shapestring.py

PR to improve the ShapeString execute function.
* Clearer logic.
* Added call to `self.props_changed_clear()` in case of file errors.

Draft: Improve ShapeString execute function

---

src/Mod/Draft/DraftGui.py

Draft: fix focus on Length input behavior

---

src/Mod/Part/App/FeatureOffset.cpp
src/Mod/Part/App/FeatureOffset.h
src/Mod/Part/Gui/TaskOffset.cpp
src/Mod/Part/Gui/TaskOffset.ui

Reverts FreeCAD/FreeCAD#23465 as it still had an issue which needed to be fixed before merge

Revert "Part: Remove mode from Offset, keep in Offset2D"

---

src/Gui/Icons/button_rotate.svg
src/Gui/Icons/resource.qrc

Fix https://github.com/FreeCAD/FreeCAD/issues/23780
Please squash

Core: Add btn_rotate.svg

---

src/Mod/PartDesign/App/FeatureExtrude.cpp
src/Mod/PartDesign/App/FeaturePad.cpp
src/Mod/PartDesign/App/FeaturePocket.cpp
src/Mod/PartDesign/PartDesignTests/TestPad.py

Fix https://github.com/FreeCAD/FreeCAD/issues/23612
@kadet1090

PartDesign: Extrude: Fix twoLength/uptoshape broken

---

src/Mod/Sketcher/Gui/EditModeCoinManager.cpp
src/Mod/Sketcher/Gui/EditModeCoinManager.h
src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
src/Mod/Sketcher/Gui/ViewProviderSketch.h

Sketcher: Coin resize when screen change. Fix #23267

---

src/Mod/Material/CMakeLists.txt
src/Mod/Material/Resources/Materials/Standard/Thermoplast/POM-Copolymer-Generic.FCMat
src/Mod/Material/Resources/Materials/Standard/Thermoplast/POM-Homopolymer-Generic.FCMat

Adds a new Generic material to FreeCAD for both POM-Homopolymer and POM-Copolymer.
Before pulling, please do double-check my numbers.
Note, the description is the first line from the wikipedia page, with some language adapted from the ABS material added.

Materials: Add POM-(Homopolymer|Copolymer)-Generic

---

src/Mod/Sketcher/Gui/Command.cpp

Change text to "Do not attach" (same as elsewhere in the file).

Sketcher change "don't attach"

---

src/Mod/BIM/ArchAxisSystem.py

Solves the same issue as https://github.com/FreeCAD/FreeCAD/issues/23749, but for ArchAxisSystem.

BIM: ArchAxisSystem, fix double click both editing label and opening task panel

---

src/Mod/Sketcher/Gui/TaskSketcherElements.cpp

Sketcher: context menu of Elements section in task panel to Title Case

---

src/Mod/TechDraw/Gui/CommandAnnotate.cpp

Updated missed UI strings to Title Case in TechDraw.

TechDraw: Update missed UI strings to Title Case

---

src/Mod/Material/CMakeLists.txt
src/Mod/Material/Resources/Materials/Standard/Metal/Aluminum/Aluminum-7075-T6.FCMat

This adds a new Aluminum material, data comes from the SourceURL.
Description was taken from the pre-existing 6016-T6 material.

Materials: Add Aluminum-7075-T6

---

src/Mod/Material/Resources/Materials/Standard/Metal/Aluminum/Aluminum-6061-T6.FCMat

The pre-existing 6061-T6 material has no SourceURL defined...
This brings the 6061-T6 material up to the same standard as the new 7075-T6 material in #23976.

Materials: Update Aluminum-6061-T6

---

src/Mod/Material/CMakeLists.txt
src/Mod/Material/Resources/Materials/Standard/Thermoplast/PMMA-Generic.FCMat

This adds a new generic material for PMMA (Acrylic).

Material PMMA generic

---

src/Mod/Sketcher/App/SketchObject.cpp

PR https://github.com/FreeCAD/FreeCAD/pull/23024 changed booleans for flags in delete functions of SketchObject and some flags where ill assigned.
I tried building a unit test for the issue, but could not get it to crash, if someone has more experience with c++ tests in FreeCAD
Fix: #23882

Sketcher: Fix trim regression

---

src/Gui/Dialogs/DlgPropertyLink.cpp

In some cases FreeCAD can segfault when signals to the selection model aren't blocked.
closes https://github.com/FreeCAD/FreeCAD/issues/23990

Gui: Fix segfault DlgPropertyLink

---

src/Mod/PartDesign/Gui/SketchWorkflow.cpp

PartDesign: fix crash when creating new sketch (#24019)

---

src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h

Fix https://github.com/FreeCAD/FreeCAD/issues/23576
By making sure arcs generated by offset are not reversed

Sketcher: Offset: fix bad arcs

---

src/Mod/Draft/WorkingPlane.py

Draft: fix working plane tooltip

---

src/App/ApplicationDirectoriesPyImp.cpp

Copy-and-paste error in the original code.

App: Fix the Python wrapper for isVersionedPath

---

src/Mod/BIM/ArchCurtainWall.py

Fix https://github.com/FreeCAD/FreeCAD/issues/23945
"Arch_CurtainWall results in an error when trying to create it based on a sketch consisting of spline or arc."
This fixes the regression introduced in -
https://github.com/FreeCAD/FreeCAD/commit/147e97d40740230e59f17397652cc8811ed98344#diff-b4849bbc0941a0f60f25d13c40d4bfeca94171f55bd78a6196362343c3fdcf6fR287

[ArchCurtainWall] Fix Regression Curve Support

---

src/Mod/PartDesign/App/FeatureHole.cpp

Avoid user confusion by printing an error when the hole operation does not find an axis (e.g when a non circular edge or face is used as base)
https://github.com/user-attachments/assets/e69bd979-cd41-42df-b26a-6f36f2ccaeb7

PartDesign: Hole: Print error when no axis was found

---

src/Gui/Dialogs/DlgExpressionInput.cpp
src/Gui/Dialogs/DlgExpressionInput.h
src/Gui/Dialogs/DlgExpressionInput.ui

Fixes four things:
- Prevents cyclic dependencies when referencing a property from the object
- Unclear reference to the original object or VarSet, https://github.com/FreeCAD/FreeCAD/issues/23632
- Ok button that is enabled while there is still an error, https://github.com/FreeCAD/FreeCAD/issues/23382
- Tooltip for "Store in VarSet...", https://github.com/FreeCAD/FreeCAD/issues/23638
Closes https://github.com/FreeCAD/FreeCAD/issues/23382
Closes https://github.com/FreeCAD/FreeCAD/issues/23632
Closes https://github.com/FreeCAD/FreeCAD/issues/23638

Gui: Fix issues with Expr dialog with VarSets

---

src/Gui/ViewProviderDragger.cpp
src/Gui/ViewProviderLink.cpp

This changes link forwarding logic to look traverse the sub object paths from the most nested object and try to find first link that is in the edited document.
- Fixes https://github.com/FreeCAD/FreeCAD/issues/23512

Gui: Fix transform of link sub-elements

---

src/Mod/Assembly/Gui/ViewProviderAssembly.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/24160

Assembly: Fix subassembly linkgroups not moving with dragger

---

cMake/FreeCAD_Helpers/SetupBoost.cmake

fix issue #23829 build with boost v1.89 and greater

---

src/Mod/Fem/App/CMakeLists.txt
src/Mod/Fem/App/FemPostPipeline.cpp
src/Mod/Fem/App/FemPostPipeline.h
src/Mod/Fem/App/PreCompiled.h
src/Mod/Fem/App/VTKExtensions/CMakeLists.txt
src/Mod/Fem/App/VTKExtensions/vtkCleanUnstructuredGrid.cxx
src/Mod/Fem/App/VTKExtensions/vtkCleanUnstructuredGrid.h
src/Mod/Fem/App/VTKExtensions/vtkFemFrameSourceAlgorithm.cpp
src/Mod/Fem/App/VTKExtensions/vtkFemFrameSourceAlgorithm.h
src/Mod/Fem/App/VTKExtensions/vtkSMPTools.h
src/Mod/Fem/Gui/DlgSettingsFemElmer.ui
src/Mod/Fem/Gui/DlgSettingsFemElmerImp.cpp
src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
src/Mod/Fem/Gui/ViewProviderFemPostObject.h
src/Mod/Fem/Gui/ViewProviderFemPostPipeline.cpp

Currently, an Elmer preference parameter (`Filter results`) is used to merge shared boundaries when loading a parallel VTU file (.pvtu) (generated, for example, when performing an analysis with Elmer using parallelization).
The current implementation introduces a deep dependency on a Fem ViewProvider base class in Elmer preferences.
This change removes that dependency and uses one of the VTK filters specific to that task.
This functionality is available through a new Pipeline property `MergeDuplicate`.

Fem: Remove dependency of the ViewProviderFemPostObject class on user parameters

---

src/Mod/Fem/femmesh/netgentools.py
src/Mod/Fem/femtaskpanels/base_femlogtaskpanel.py

Better error handling in logging task panels (Netgen, Elmer, CalculiX)
For example, if the process cannot start because the executable file does not exist, then report the error and stop the timer.
@FEA-eng

Fem: Better error handling in task panels with logging

---

src/Mod/Fem/Gui/ViewProviderFemPostPipeline.cpp
src/Mod/Fem/Gui/ViewProviderFemPostPipeline.h

In fact, the fix is ​​partial. It is still reproducible in certain cases with the Elmer-generated pipeline, because SolverElmer uses `App::GroupExtension`.
For a complete fix, #23983 is required.
partial fixes issue #23466

Fem: Remove pipeline from analysis highlighter - fixes #23466

---

src/Mod/Sketcher/Gui/DrawSketchHandlerScale.h
src/Mod/Sketcher/Gui/EditDatumDialog.cpp

This PR makes the scale tool (and autoscale) handle dimension of a single line
Fix: https://github.com/FreeCAD/FreeCAD/issues/24064

Sketcher.Scale: Add case for distance of a single curve

---

src/Gui/Tree.cpp
src/Mod/Sketcher/Gui/CommandConstraints.cpp
src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
src/Mod/TechDraw/Gui/Command.cpp
src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui
src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui

This PR addresses a few problems identified by translators on CrowdIn.

GUI: Fix some translatable text

---

src/Mod/Fem/App/FemPostFilter.cpp

Currently the calculator filter does not use the components of the symmetric tensors, if they exist.
@FEA-eng

Fem: Add tensor components to calculator variables

---

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp

This updates the logic that had special handling for planes for the temporary visibility feature of sketcher which was mishandled after move to core datums.
The logic only handles planes, as it originally did. However we should probably think about changing it from "Show everything that is not plane" to "Show everything that is geometry". But that should be a different PR and different issue.
- Fixes https://github.com/FreeCAD/FreeCAD/issues/24268

Sketcher: Do not force visibility of planes on edit

---

src/Gui/EditableDatumLabel.h
src/Mod/Sketcher/Gui/DrawSketchController.h
src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h
src/Mod/Sketcher/Gui/DrawSketchHandlerScale.h

Fix https://github.com/FreeCAD/FreeCAD/issues/22129
Fix https://github.com/FreeCAD/FreeCAD/issues/21741

Sketcher: Force OVP visibility for offset and scale.

---

src/Mod/BIM/ArchStairs.py

Fix #24065
Fix #24051
1. Blondel Ratio is not calculated, this if fixed now.  Blondel Ratio property is changed to Length following wiki's descripition.
2. Winders is not implemented as commented in wiki.  The property is not added at the moment until it is implemented.

[ArchStairs] Fix Blondel Ratio and Winders

---

src/MacAppBundle/CMakeLists.txt
src/Tools/MakeMacBundleRelocatable.py

this PR will fix the mac app bundling issues with homebrew when generating a FreeCAD.app bundle on macOS.
this PR was created to finish the below FPA grant proposal,
https://github.com/FreeCAD/FPA-grant-proposals/issues/28
this PR will resolve several issues posted on the homebrew-freecad repo.
NA

ipatch: fix mac app bundling with homebrew

---

src/Mod/BIM/bimcommands/BimMaterial.py

BIM: fix BimMaterial dialog regression

---

src/Mod/TechDraw/Gui/TaskWeldingSymbol.ui

copied the settings of the "symbol" button to "delete" and  "Flip sides" buttons.
Fixes #24288 
Before:
After:

TechDraw: Make TaskWeldingSymbol buttons resizeable (fixes #24288)

---

src/Mod/CAM/Path/Dressup/Gui/LeadInOut.py

CAM: LeadInOut - Fix SafeHeight

---

src/Gui/Command.cpp

Code is from @depthoffocus and fixes #23769.

Gui: Ensure menus don't get moved inadvertently

---

src/App/License.h

I added GPL-3.0-or-later license to the list of licenses.

Added GPL-3.0-or-later to the list of licenses

---

LICENSE

Fixes / updates the license text to 
LGPLv2.1 which FreeCAD goes by.

Fix & update license to LGPLv2.1

---

src/Mod/Assembly/Gui/ViewProviderAssembly.cpp

Fix https://github.com/FreeCAD/FreeCAD/issues/24359

Assembly: Fix dragger when assembly is transformed
