src/Mod/CAM/Path/Op/Adaptive.py
This pull request changes how stock is calculated for generating Adaptive toolpaths. Currently, there are two cases:
- Generated cylinder, in which case a cylinder is used as the stock
- Every other case, in which case the bounding box of stock model is used (including if an externally-generated cylinder is used as stock)
This results in inefficient toolpaths where a lot of air-cutting can occur even if the stock is modeled correctly. This change causes the stock boundary to always be calculated from the stock model by projecting the stock to the XY plane then taking the outside edges of the result. The general method was copied from here, with slight tweaks: https://forum.freecad.org/viewtopic.php?t=69976
Example of a model/stock combo exhibiting this issue:
Result after this change: …
=> [CAM] Make adaptive operations use actual stock outline

src/App/PropertyStandard.cpp, src/Mod/Material/App/MaterialPy.xml, src/Mod/Material/App/MaterialPyImp.cpp
The first commit generalizes how to set the Python object for `App::PropertyMap` properties by using objects with mapping protocol (basically objects that behave like a dictionary with key-value pairs).
The second commit adds support for sequence and mapping protocol to `Material::MaterialPy` class, so Python `Materials.Material` objects behave like a dict using material properties:
```
import Materials
mat = Materials.MaterialManager().getMaterial("90bbd8ef-8623-4d78-b3bf-e0bdb9b74dd3")
for key in mat:
mat[key] --> get properties values
mat["Name"] --> get "Name" property
"Density" in mat --> True/False 
dict(mat) --> get dict of properties from the material
```
This changes adds backwards compatibility with `App::MaterialObject` and simplifies the code in cases where it is necessary to …
=> App: Use mapping protocol in App::PropertyMap and add the protocol to Materials.Material objects

src/App/Application.cpp, src/App/PreCompiled.h, src/Main/MainGui.cpp
When in console mode, some messages from CLI interaction still resulted in popup dialogs. This is becasue those information are communicated via exceptions and those exceptions prevented the console mode from being properly set. By using a scope guard the console mode flag is now evaluated in all cases. The code to display those messages got refactored into dedicated methods which now also take care of console mode.
The change does not cover all cases, though: When encountering unknown or invalid arguments, the parser itself throws and in this case the console mode flag is not propagated. However, for regular use, e.g. the for `--help`, `--dump-config` or `--version`, the output is now placed in the console when `--console` was specified.
I also noted a wild mix of `toLatin1`/`fromLatin1` …
=> Main: Avoid Popups in Console Mode

src/Gui/EditableDatumLabel.cpp, src/Gui/EditableDatumLabel.h
`EditableDatumLabel` uses `activate`/`deactivate` methods for showing or hiding its widgets in the scene.
However, `activate`/`deactivate` methods can end up being called as part of a scene graph / Coin action (`SoAction`) handler, in the context of `SoFCUnifiedSelection`, and this ended up in a Coin warning and eventual crash due to the scene graph being manipulated (nodes being removed) during traversal, which Coin has checks for in debug mode:
```
Coin error in SoGroup::removeChild(): tried to remove non-existent child
0x5555579c5290 (Annotation)
```
Fix this issue by using a `SoSwitch` node instead and by controling the child visibility using it instead.
This manifested itself when creating a new sketch and adding a line, by the way.
=> Gui: Fix invalid scene graph mutation in `EditableDatumLabel`.

src/Mod/CAM/Path/Main/Gui/Job.py
eliminate some error messages when a Job is not fully loaded
(or when not properly constructed via scripting)
TESTED ON V0.21 -- code hasn't changed since then
=> CAM: improved checks in `Path/Gui/Jobs.py/claimChildren`

src/Mod/TechDraw/App/AppTechDrawPy.cpp
Fixes https://github.com/FreeCAD/FreeCAD/issues/12601
Basically a few TechDraw operations fail to account for single-edge wires, which either fails to find an outline when one should exist, or finds the wrong outline if there are any other closed wires provided. I found 3 functions that had this issue, though it's possible there are some I missed.
Somebody who knows better what's going on here should check if this is more a bandage than a proper fix- eg, if the call to `DrawProjectSplit::scrubEdges` is actually the root problem or something.
Test case showing the issue (works correctly with the pull request applied):
```
import TechDraw
r = Part.makePolygon([(-0.5,-0.5,0), (0.5,-0.5,0), (0.5,0.5,0), (-0.5,0.5,0), (-0.5,-0.5,0)])
c = Part.makeCircle(1)
f = Part.makeFace([r,c])
w = …
```
=> TechDraw: Fix finding outlines consisting of a single closed edge

src/Mod/BIM/bimcommands/BimTDView.py, src/Mod/TechDraw/App/DrawView.cpp, src/Mod/TechDraw/App/DrawViewArch.cpp, src/Mod/TechDraw/Gui/Command.cpp
Only the texts in the Property Panel, the Menus, Tooltips and default label for new created BIM views are changed.
The internal names (ArchView), messages in the Report/Console too, files (Cpp and SVG icons) are kept.
They can be changed if wanted too, let me know.
Also, the Join Arch property is kept for now.
=> TechDraw: rename user-facing strings Arch to BIM

src/Gui/VectorListEditor.cpp
See https://github.com/FreeCAD/FreeCAD/pull/17851
That PR added the copy table and paste table functionality to the table context menu for the vector list property editor.  It was noted that some precision was being list during the copy to clipboard process, since the precision was based on the user decimals preference (default:2).  This sets the precision to be used to the greater of decimals or 12.  I decided on 12 because as a test I exported a draft wire as a step file and examined the file to find 12 was the highest number of digits to the right of the decimal being used.
Note that if the user requires more precision then he can set decimals = 15, for example, and then the precision of 15 would be used.
=> [VectorListEditor] Set precision to 12 digits when copying table data

src/Mod/CAM/CAMTests/TestPathVcarve.py, src/Mod/CAM/Path/Op/Vcarve.py, src/Mod/Sketcher/App/GeometryFacade.cpp
Finishing pass logic for Vcarve operation was commented by mistake as it was using old cutting API. Reworked and enabled again.
=> CAM: Fix finishing pass

src/Mod/TechDraw/Gui/QGCustomText.cpp, src/Mod/TechDraw/Gui/QGIViewDimension.cpp, src/Mod/TechDraw/Gui/QGIViewDimension.h
Fixes issue #19121 "dimension numbers placed lower than normal".
**Before**
**After**
QGCustomText has a new method `aligmentRect` which can optionaly return a `tightBoundingRect` instead of the regular `boundingRect`. The `alignmentRect` is used for laying out the `QGIDatumLabel`, however `QGraphicsItemGroup::childrenBoundingRect` use the children's `boundingRect` and knows nothing of `alignmentRect`. The result is an improperly sized label, frame and observed misalignment. Additinoaly `childrenBoundingRect` calculations includes hidden views, so even though the `m_tolTextOver` and `m_tolTextUnder` are hidden they still affect the bounding rect size.
1. Implement new method `QGIDatumLabel::tightBoundingRect` this
calculates the bounding rect using the subview's
`aligmentRect` if there is …
=> TechDraw: Fix dimension aligment issue.

src/App/Application.cpp, src/App/PropertyUnits.cpp, src/App/PropertyUnits.h, src/Base/Unit.cpp, src/Base/Unit.h, src/Base/UnitsSchemaInternal.cpp, src/Base/UnitsSchemaMKS.cpp, src/Mod/Fem/Gui/Resources/ui/ElectrostaticPotential.ui, src/Mod/Fem/femexamples/equation_magnetodynamics_elmer.py, src/Mod/Fem/femobjects/constraint_electrostaticpotential.py, src/Mod/Fem/femsolver/elmer/equations/electrostatic_writer.py, src/Mod/Fem/femsolver/elmer/equations/magnetodynamic_writer.py, src/Mod/Fem/femtaskpanels/task_constraint_electrostaticpotential.py
@maxwxyz @FEA-eng 
This pull request rebases and squashes the changes from https://github.com/FreeCAD/FreeCAD/pull/15005.
Also fixes the vector potential unit and changes the boundary condition type from boolean to the `[Dirichlet, Neumann]` enumeration.
The scalar potential still needs to be fixed because it is currently set equal to the potential (in Elmer they are independent quantities).
Work on the task panel is still in progress.
=> Fem: Electromagnetic boundary condition

src/Mod/Draft/Resources/Draft.qrc, src/Mod/Draft/Resources/icons/Draft_Layers.svg, src/Mod/Draft/draftviewproviders/view_layer.py
The current Draft_Layer.svg icon shows multiple layers. It is used for the Draft_Layer command but also for the LayerContainer. This is confusing. There should be separate icons, one with a single layer and one with multiple layers.
=> Draft: introduce new Draft_Layers icon

src/Mod/Draft/draftobjects/layer.py, src/Mod/Draft/draftviewproviders/view_layer.py
Fixes #17844.
1. When an object is put in a layer it always adopts the properties of that layer.
2. Properties of the object that are subsequently changed are considered overrides.
3. When the properties of the layer, or the object in the layer, are then changed so that they match again, there is no longer an override, and properties are synced again.
4. The layer and the layer container object get an extra Tree view context menu option "Reassign properties of layer"/"Reassign properties of all layers".
=> Draft: allow objects in layers to have overrides

src/Gui/SceneInspector.cpp, src/Gui/SceneInspector.ui
As title says, adds bounding box data to scene inspector. This helps with some debugging scenarios.
I've also organized the UI a little bit by adding columns for caching data as well as for bounding box, as previously everything was going to the `Data` column, and it was getting cluttered and hard to visually parse the info.
=> Gui: Add bounding box data to scene inspector.

src/Mod/Draft/importSVG.py
#18458
Force encoding=utf8 when opening file if encoding is not specified.
=> #18458 Fix SVG import error at non-utf8 native environment.

src/Gui/PreferencePacks/FreeCAD Classic/FreeCAD Classic.cfg
Some themes define a tree view font size different than the default `0`. When selecting those themes and then switching back to Classic, that custom font size remains, which might make the tree view look out of place.
This PR adds the tree view's `FontSize` parameter default to the FreeCAD Classic configuration, so that it is reset to defaults when choosing the FreeCAD Classic theme.
=> PrefPacks: reset tree view font size in FreeCAD Classic theme

src/Gui/Dialogs/DlgMacroExecuteImp.cpp, src/Gui/MainWindow.cpp, src/Gui/Stylesheets/FreeCAD Dark.qss, src/Gui/Stylesheets/FreeCAD Light.qss
Fixes #19333 
After fix applied:
Also fixed two typos in FreeCAD Light which also fixes #19332
=> [Gui] Fix Close without Saving button size

src/Mod/Fem/Gui/TaskFemConstraintTransform.cpp
Update of the error message shown when selecting a face without displacement boundary condition or force load - the latter wasn't included in the message since support for it was added later.
=> FEM: Constraint transform - selection error message update

src/Mod/PartDesign/App/FeatureHole.cpp, src/Mod/PartDesign/App/FeatureHole.h, src/Mod/PartDesign/PartDesignTests/TestHole.py
refactor to get the designations from the ThreadDescription instead of having a bunch of arrays duplicating the same thing
also added a test for threadtype change to check that is working properly
=> refactor(PD): ThreadSize enum simplification

src/App/Application.cpp, src/App/Application.h, src/App/ApplicationPy.cpp, src/Gui/Application.cpp, src/Mod/Import/App/ImportOCAF2.cpp, src/Mod/PartDesign/App/ShapeBinder.cpp
Just a little explanation, I am working on a workbench, which distributes some geometry/sketch inside an FCStd file.
I would like to load it in the background, access the sketch, extrude a shape, and then close the document.
In C++ there is this temporary doc flag which seems to work for what I need (doesn't show the document in the tree).
This PR adds support to set it while opening a document from Python, most of the changes are just a refactoring to the C++ API to pass a struct around with all the flags, instead of just adding more flag parameters.
=> App: Provide temporary document creation flag to Python `App.loadDocument`.

src/App/Application.cpp, src/App/Application.h, src/App/PreCompiled.h, src/Gui/ApplicationPy.cpp, src/Gui/EditorView.cpp, src/Gui/MDIView.cpp, src/Gui/MainWindow.cpp, src/Gui/View3DInventor.cpp, src/Mod/Drawing/Gui/DrawingView.cpp, src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp, src/Mod/TechDraw/Gui/PagePrinter.cpp
Currently FreeCAD does not set a PDF creator tag. And (almost) all PDF generating applications do set this tag.
Practically speaking, it can be useful for debugging being able to see which version of FreeCAD generated a particular PDF, without being dependent on a user remembering/reporting it correctly.
=> Add proper PDF creator metadata

src/Gui/PrefWidgets.cpp, src/Gui/PrefWidgets.h
This commit mollifies the issue #17684 by making the PrefWidgets receive mouse wheel events only when they have both focus and the mouse pointer at the widget.
=> Change FocusPolicy of some PrefWidgets to StrongFocus

src/Mod/Draft/draftutils/utils.py, src/Mod/Draft/importAirfoilDAT.py, src/Mod/Draft/importDXF.py, src/Mod/Draft/importOCA.py, src/Mod/Draft/importSVG.py
Move import.SVG pyopen with encoding to draftutils.utils.
and modify DRAFT importing library that use open function to use open with encoding=utf8.
With this change, DXF OCA AirfoilDAT always read as utf-8.
I'm not sure. it's need this change.because I don't have such a example of OCF or DXF or AirfoilDAT.
I think it's more better checking encoding of files before importing than force encoding=utf8.
=> * Move pyopen with encoding to utils.

src/Mod/Draft/DraftGui.py
Fixes #19305.
Fixes #19324.
Issues above caused by #19179.
Also removes automask code as it did not work properly in several cases. For example if the working plane was set to Front and the Global option was checked only the X coordinate could be entered.
=> Draft: fix three issues with DraftGui.py

src/Mod/BIM/Resources/ui/dialogClassification.ui, src/Mod/BIM/bimcommands/BimClassification.py
- Connect "only visible" checkbox signal to slot
- Create corresponding "onVisible" slot
- Remember the status of checkbox between dialog launches (store status as a parameter)
Since they were small, this PR also introduces some minor changes, mostly visual:
- Change default ui dialog `Dialog` name to `bimDialogClassification` to make debugging easier
- Add icons to classification dropdown box. Before, some items were indented to accomodate an (inexistent) icon, some others were not
| --- | --- |
| ![Captura de pantalla de 2025-01-23 13-33-47](https://github.com/user-attachments/assets/83b3a140-0de5-44cd-874a-e32cc29ddc5a) | ![Captura de pantalla de 2025-01-23 13-31-55](https://github.com/user-attachments/assets/e60ad872-9ceb-4a36-b6c5-985b2cc9dcc9) |
Notes:
- :bulb: …
=> BIM: Connect "only visible" checkbox signal to corresponding slot

src/Mod/BIM/nativeifc/ifc_tools.py
This PR improves the imports of IfcOpenShell in `ifc_tools.py`, I've had this in my tree for a while so I cannot remember anymore how to trigger this, but I was having some crashes here while loading BIM without IfcOpenShell installed.
=> BIM: Improve checking of IfcOpenShell imports in `ifc_tools.py` .

src/Mod/BIM/nativeifc/ifc_tools.py
Needs to be thoroughly tested.
Fixes: #19340
=> BIM: fix unassigned variable reference

src/Mod/BIM/ArchSchedule.py
This PR adds functionality to the BIM Schedule command to detect and expand array elements, so that they can be further processed. Before, array elements were ignored.
:information_source: Notes:
1. It covers the array type in the test case file provided in #16719. Element(s) belonging to a single ortho Link array, with `expanded=False`.
1. It has also been successfully tested with:
- Regular arrays
- Link arrays with `expanded=True`
1. There might be other cases to cover, but as long as this PR does not break them, they can be addressed in subsequent PRs
1. The approach to expand arrays is nearly the same as what BimIfcQuantities uses. This ensures reusing (yet duplicating) proven code, but there might be a more elegant approach for BIM Schedule. I'm more than open to suggestions.
1. The …
=> BIM: add support for array elements in BIM Schedule

src/Gui/Dialogs/DlgAbout.cpp
- Add IfcOpenShell version to the information copied into the clipboard when opening the <kbd>Help</kbd> > <kbd>About FreeCAD</kbd> dialog and pressing the <kbd>Copy to clipboard</kbd> button
- If IfcOpenShell is not found in the system, a  log message is issued to the user: ` No module named 'ifcopenshell' (safe to ignore, unless using the BIM workbench and IFC).` to notify them. The copy to clipboard still succeeds, it simply does not contain the IfcOpenShell version text. Log message reporting is disabled by default, so for most users not having if openshell installed and copying the about info will be a silent operation.
Fixes: https://github.com/FreeCAD/FreeCAD/issues/18650
=> Core: add Ifcopenshell version in about info clipboard

src/Mod/Draft/draftobjects/patharray.py
Implements #19016 
Some missing quality-of-life features in Path Array:
1. A setting to reverse path
I noticed sketches have arbitrary directions, especially when selecting different sub-elements from one sketch for multiple path arrays. Sometimes two very similar arcs have opposite directions and it's annoying to find workarounds. I read in the forums that reversing paths is not really doable, so I propose a "reverse path" setting to walk the paths in reverse when placing Path Array objects. This also reverses normals, offsets, etc.
2. An align mode that uses rotations instead of tangent vectors
It is difficult conceptually to orient objects around paths by inputting a tangent vector. I propose an align mode where you start with the default "Tangent" orientation and enter angles rather …
=> Draft: New path array features - reverse path, etc

src/Mod/Start/Gui/StartView.cpp, src/Mod/Start/Gui/StartView.h
See https://forum.freecad.org/viewtopic.php?t=94485
There exists a ShowExamples parameter in BaseApp/Preferences/Mod/Start but it is currently ignored.  This PR implements this parameter and disables the display of the Example files if ShowExamples is set to false.
=> [Start page] Implement ShowExamples parameter

src/Gui/GuiApplicationNativeEventAware.cpp
If we aren't using the legacy space mouse code, we shouldn't call the init method. This is a second round of fixes for space mouse on the Mac. Follow-up to #19226
=> Gui: Disable spacemouse init if not legacy

src/Mod/BIM/ArchPipe.py
=> BIM: PipeConnector does not require a Base

.github/workflows/sub_lint.yml
Our coding standard specifies a max line length for Python of 100 chars, enforced by `pre-commit` via `black` for modules that are run through pre-commit. However, the CI is running `black` without any line length specified, so effectively using `black`'s default of 80. This results in nearly every Python file generating a spurious CI linter warning that `black` would reformat the file. This PR syncs the CI with the pre-commit.
=> CI: Make black line length match pre-commit

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/femguiutils/disambiguate_solid_selection.py, src/Mod/Fem/femguiutils/selection_widgets.py
Enable selection of solids which are enclosed within an outer solid.  
If the selected face or edge belongs to multiple solids provide a popup to allow the user to select which solid they wish to add.
Closes https://github.com/FreeCAD/FreeCAD/issues/5913
[demo.webm](https://github.com/user-attachments/assets/b8ee8c9f-84c6-49b0-bc67-3cacd0db56e8)
=> Fem: Display popup menu when MeshGroup solid selection is ambiguous

.github/workflows/sub_lint.yml
Addresses some of the issues identified in #19500 -- disables some linter noise, and attempts to make the Clazy output more useful by limiting the run to only changed cpp files (and excluding the analysis of `#include`-ed header files).
=> CI: Adjust linter settings

src/Mod/BIM/ArchBuildingPart.py, src/Mod/BIM/Resources/ui/dialogProjectManager.ui, src/Mod/BIM/bimcommands/BimProjectManager.py, src/Mod/BIM/importers/exportIFC.py, src/Mod/BIM/nativeifc/ifc_export.py, src/Mod/BIM/nativeifc/ifc_generator.py, src/Mod/BIM/nativeifc/ifc_objects.py, src/Mod/BIM/nativeifc/ifc_observer.py, src/Mod/BIM/nativeifc/ifc_tools.py, src/Mod/BIM/nativeifc/ifc_viewproviders.py
This is an upgrade of the BIM Project Manager tool to support Native IFC projects.
It needs support for 2D entities, so it needs to be merged after #16629
=> Bim project manager upgrade

src/Mod/BIM/bimcommands/BimViews.py
Fixes: https://github.com/FreeCAD/FreeCAD/issues/18559
=> BIM: fix error on double-clicking on non-IFC objects

src/Mod/Draft/drafttaskpanels/task_scale.py, src/Mod/Draft/draftviewproviders/view_clone.py
Fixes #13324.
The Edit option is available from the Tree view context menu, but you can also double-click the clone in the Tree view.
The task panel is based on that of the Draft Scale command. The "Uniform scaling" checkbox is (un)checked depending on the current scaling of the clone.
=> Draft: Introduce Edit option for Draft Clone scaling

src/Mod/PartDesign/App/FeatureHole.cpp, src/Mod/PartDesign/App/FeatureHole.h, src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
Currently when changing from Metric to Metric-Fine the designation is only correct if the change is done in the Task-panel, but not from CLI or the Properties panel, since the code is in the UI side, in the taskpanel specifically.
This versions move the logic to the Feature code fixing that issue.
And it's now even better since it will search for the closest designation when changing standards, for example when selecting M6 in Metric and changing into UNC it will auto-select 1/4"
I've provided the appropriate test code.
This PR is based on #18682 so i don't have to rebase due to the test. (i'm assuming it will get merged, otherwise i will have to modify this)
=> feat(PD): Auto find closest size when changing thread standards

src/Gui/View3DInventorViewer.cpp
As title says, checks if document exists in `View3DInventorViewer::setOverrideMode`.
Fixes a crash that can happen in some cases.
=> Gui: Check if document exists in `View3DInventorViewer::setOverrideMode`.

CMakeLists.txt, cMake/FreeCAD_Helpers/SetupCoin3D.cmake
When working with a custom Coin3D build, it's very easy to end up with a mismatched Pivy version being picked up from the system.
Prevent this by catching for mismatched versions at CMake configuration time.
=> CMake: Improve Pivy Coin3D version mismatch checking.

src/App/DocumentPy.xml, src/App/DocumentPyImp.cpp
This updates the `Document.copyObject` Python API by allowing for keyword arguments and aligning the documentation with the C++ API.
This can make the Python code more readable, by using the keywords form:
```python
document.copyObject(obj, recursive=True, return_all=False)
```
vs. the previous less readable form:
```python
document.copyObject(obj, True, False)
```
Previous keyword-less version tested and still working for backwards compatibility.
=> App: Improve `Document.copyObject` Python API.

src/App/Metadata.cpp, src/App/ProjectFile.cpp, src/Base/Parameter.cpp, src/Base/XMLTools.h, src/Mod/Mesh/App/Core/IO/Reader3MF.cpp
This PR improves DXF import performance; in my case it improves 5% of execution time (sorry I cannot provide dxf data due to confidential project).
This PR minimize call of `XMLString::transcode` by comparing string in `xercesc` space; it reduces conversion cost since `Name` and `Type` are invariant during iteration in contrast of converting node name/value in each iteration.
I profiled with perf(1); just D&D dxf file and close FreeCAD:
baseline
```
$ perf report --symbol-filter FindElement
6.06%     0.06%  FreeCAD  libFreeCADBase.so  [.] ParameterGrp::FindElement(xercesc_3_2::DOMElement*, char const*, char const*) const
|                                                                                                          
--6.00%--ParameterGrp::FindElement(xercesc_3_2::DOMElement*, …
```
=> Base: Improved FindElement performance by reducing call of transcode

src/Gui/View3DInventorViewer.cpp
Should fix the symptoms of #8341 and #6177 .
Workaround for inconsistent QT behavior related to handling custom OpenGL widgets that leave non opaque alpha values in final output.
On wayland that can cause window to become transparent or blurry trail effect in the parts that contain partially transparent objects.
At the end of rendering clear alpha value, so that it doesn't matter how rest of the compositing stack at QT and desktop level would interpret transparent pixels. There might be a cleaner solution by changing some Qt options but I wasn't able get that working.
* https://bugreports.qt.io/browse/QTBUG-110014
* https://bugreports.qt.io/browse/QTBUG-132197 (here you can also find links to Cura and OpenScad having similar issue)
* https://bugreports.qt.io/browse/QTBUG-119214
Amount of …
=> Workaround for transparency problems on wayland.

src/Mod/PartDesign/App/FeatureHole.cpp
=> PartDesign: fix crash when opening a file with a metric hole

src/Mod/Draft/draftutils/gui_utils.py, src/Mod/Draft/draftutils/utils.py
PR #18795 changed the select function to also handle tuples. This PR adds a check to ensure the referenced objects in the tuple still exist before calling `Gui.Selection.addSelection()`.
=> Draft: gui_utils.py fix error in select function

src/Mod/BIM/ArchSketchObject.py
Currently, Links of Window's Hosts property (and in generall all properties other than e.g. Placement) is shared with its Linked Window object, i.e. all Windows Links instances can only has a common Host(s) which is not flexible for the purpose of Links.
AND, at the same time, Links in linked document suffer from the 'scope' of the original Linked Window, which is in the external Document.
This commit adds feature to support:
1/ each Links instance of Windows has their own individual setting of Hosts, and
2/ it see the 'scope' of the Links in its document (rather than the Linked Window in the external document, if inserted from the latter)
FreeCAD Forum:
- https://forum.freecad.org/viewtopic.php?p=808569#p808569
FreeCAD GitHub:
- https://github.com/FreeCAD/FreeCAD/issues/19361
=> [ArchSketchObject / Window]  Links of Window to support Individual Hosts

src/Gui/PreferencePages/DlgSettingsDocument.ui, src/Gui/PreferencePages/DlgSettingsDocumentImp.cpp
It's impossible to click on the link because the tooltip fades away, from ~30 attempts none worked. `Preferences > General > Document`
I used a `Gui::UrlLabel` from the FreeCAD's custom Qt elements, **is preferred a simple Label with hyperlink?** Qt Designer 5 used, it moved lots of lines but only one element was added.
=> Core: Remove link from tooltip

src/Mod/PartDesign/App/FeatureDraft.cpp
Fix #19532
Changes staged in:
src/Mod/PartDesign/App/FeatureDraft.cpp
Modified the `Constrains`'s `LowerBound` to accept the negative angles
=> PartDesign: Allow Draft negative angles

src/XDGData/CMakeLists.txt
cmake version is always greater than 3.8.
=> Xdgdata: clean CMakeLists.txt

src/Mod/Fem/femmesh/netgentools.py, src/Mod/Fem/femobjects/mesh_netgen.py, src/Mod/Fem/femtaskpanels/base_femmeshtaskpanel.py
With Netgen's zrefine function it is possible to create first-order meshes hexa dominated (using `QuadDominated` property) or with pentahedron elements from solid shapes based on extrusions.
There are two modes in `ZRefine` property for z-refinement: `Regular` (all elements have the same height) and `Custom` (the height of each element must be specified). This height is given as a fraction of the total height in the `ZRefineSize` property.
It is also possible to refine in custom directions (`ZRefineDirection` property) if the shape is extruded in a direction other than the Z axis.
Note that in general meshing will be successful only for first-order elements (unless the generated elements are all hexahedrons).
@FEA-eng
=> Fem: Add Z-refinement support for Netgen

src/Mod/CAM/CAMTests/TestRefactoredTestPostGCodes.py, src/Mod/CAM/Path/Post/UtilsParse.py
This fixes #18491.
Added tests and code to fix the F parameter handling when only rotary axes are used with F feed rates.
That required adding the entire "parameters" argument to all of the parameter handling routines because the F parameter handling routine needed to see what other parameters were used in the command.
=> CAM:  Fixed F parameter handling for only rotary axes, with tests

src/Mod/TechDraw/App/DimensionFormatter.cpp, src/Mod/TechDraw/App/DimensionFormatter.h
Add a `"r"` type field to the format specifier. The decimal value specifies the step to round to.
Example:
with `"%0.5r"`
- 13.235 mm will become 13.0 mm
- 56.322 mm will become 56.5 mm
- 22.680 mm will become 22.5 mm
- 0.78 mm will become 1.0 mm
with `"%0.25r"`
- 13.235 mm will become 13.25 mm
- 56.322 mm will become 56.50 mm
- 22.680 mm will become 22.75 mm
- 0.78 mm will become 1.00 mm
https://forum.freecad.org/viewtopic.php?p=808983
EDIT: a step > 1 is allowed too
=> TechDraw: Add a format spec. to round a value 

.gitignore
Its pretty helpful when developing to have multiple build directories for different branches.
This adds such pattern to .gitignore to be able to have a sane Git experience.
=> Git: Ignore extra suffixed build directories.

src/Mod/Spreadsheet/Gui/ZoomableView.cpp, src/Mod/Spreadsheet/Gui/ZoomableView.h
The issue #16987 and #19357 are caused by _FocusOut_ event. When I implemented _ZoomableView_, I missed the fact that _FocusOut_ event of _QGraphicsView_ is different from that of _QWidget_.
_ExpressionCompleter_ creates a popup, making _QGraphicsView_ lose focus. If _QGraphicsView_ loses focus, the scene loses focus too,[^1] which in turn, causes _FocusOut_ event of the _ExpressionCompleter_, leading to _editingFinished_ signal, thus closing the editor.
This commit implements a dummy _FocusOut_ event, preventing the propagation of _FocusOut_ event, thus closing #16987.
CC @benj5378
[^1]: https://github.com/qt/qtbase/blob/84e09e060bedd37d8de7cded7e430371e335c029/src/widgets/graphicsview/qgraphicsview.cpp#L3108-L3114
=> [Spreadsheet] Fix popup close issue

src/Mod/Fem/femguiutils/disambiguate_solid_selection.py
The popup menu uses a disabled menu item to hold the user prompt.  This change adds a check that we are not trying to set a highlighting for this "dummy" menu item.
Addresses #19527 
What is a bit mysterious is that I could only reproduce the behaviour by commenting the line of code which sets the label as [disabled](https://github.com/FreeCAD/FreeCAD/blob/d044d3da84298c4a6cfe831aebe5df322182cc8b/src/Mod/Fem/femguiutils/disambiguate_solid_selection.py#L148).  Unless I did this it did not fire a hover event.  Could this somehow be platform specific?
=> Fem: Add check that the solid_name is valid

src/Gui/Dialogs/DlgAbout.cpp
`openExternalLinks` and `openLinks` of some QTextBrowsers were incorrectly set, causing functionality of links in Libraries tab of About dialog to be disabled. This PR fixes it, and removes redundant set calls.
=> Fixed #16423: Links in DlgAbout

cMake/FreeCadMacros.cmake
Closes #19708
The function was intended to add dependencies to a target, however this is an unsupported use.  Recent CMake versions have switched from silently ignoring the unsupported use to loudly informing the user that it has no effect.  This PR removes the effect-free function from macros.
=> CMake: Remove unsupported CMake function from macros causing warnings.

src/Gui/Dialogs/DlgExpressionInput.ui
=> [Gui] Expression dialog OK button capitalised and Alt+O shortcut applied

.github/workflows/actions/runCPPTests/runAllTests/action.yml
seems like there was a copy paste error at #18686?
=> CI: fix assembly unit tests executable name

src/Mod/Assembly/CommandCreateJoint.py, src/Mod/Assembly/CommandInsertNewPart.py
Menu texts in the Assembly WB are in title case without articles.
The following menu texts did not follow that 'standard':
* Insert a new part
* Create a Fixed Joint
=> Assembly: Make 2 menu texts more consistent

.git-blame-ignore-revs, src/Gui/Command.cpp, src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
Fix for issue #18159
- Rearranged `CommandCreateGeo.cpp` functions to logical order to improve readability.
- Added rearrangement commit to blame ignore file.
- Updated rectangle, polygon and spline group commands to use group command class.
- Added `setShortcut` to `GroupCommand::Setup()` function.
- Initialized Sketcher's group command shortcuts.
More detailed explanation in here: https://github.com/FreeCAD/FreeCAD/issues/18159#issuecomment-2569797531
=> Sketcher: Fixed Inconsistency between button tooltips and labeling for shortcuts.

src/Mod/AddonManager/addonmanager_utilities.py
- Enables specifying a list of pip options to be removed
- Removes the `--path` option to the pip call. `--path` is not compatible with the `--user` option implicitly used by pip on the snap package
As a side note, and not addressed on this PR: the custom `PipFailed` exception should probably be reworked to forward the error from the parent exception. It is currently masking any error (such as the ones on https://github.com/FreeCAD/FreeCAD/issues/19556 and https://github.com/FreeCAD/FreeCAD/issues/19812) with a "pip timed out" message to the user, which is misleading.
Fixes: https://github.com/FreeCAD/FreeCAD/issues/19812
=> Add-On Manager: generalize removal of non-compatible pip options for the snap package

src/Gui/Tree.cpp, src/Gui/Tree.h
Fixes #12801 
~TODO:~
1. Right click on model and select option:
2. File opens up in explorer:
=> Gui: "Open File Location/Reveal in Finder" in Tree view

src/Gui/StartupProcess.cpp
QT version is always greater than version 5.14.
The oldest supported version of Ubuntu is 22.04 which uses QT 5.15.3
=> Clean StartupProcess.cpp

src/App/Material.cpp, src/Base/Builder3D.cpp, src/Base/Builder3D.h, src/Base/Tools.h, src/Gui/Dialogs/DlgMaterialPropertiesImp.cpp, src/Gui/PreferencePages/DlgSettings3DView.ui, src/Gui/PreferencePages/DlgSettings3DViewImp.cpp, src/Gui/PreferencePages/DlgSettingsLightSources.cpp, src/Gui/PreferencePages/DlgSettingsLightSources.h, src/Gui/PreferencePages/DlgSettingsLightSources.ui, src/Gui/Utilities.h, src/Gui/View3DInventorViewer.cpp, src/Gui/View3DInventorViewer.h, src/Gui/View3DSettings.cpp, src/Gui/View3DSettings.h, src/Gui/ViewProviderGeometryObject.cpp, src/Gui/propertyeditor/PropertyItem.cpp, src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp, src/Mod/Material/App/MaterialManager.cpp, src/Mod/Mesh/Gui/ViewProvider.cpp, src/Mod/Part/Gui/ViewProvider.cpp, src/Mod/Part/Gui/ViewProviderExt.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
This PR adds 3 point lighting setup to FreeCAD. Work in progress, submitted mostly for people to play with and find good defaults :)
| ![image](https://github.com/user-attachments/assets/418249e1-86a9-46af-9d98-1eea770535b1) | ![image](https://github.com/user-attachments/assets/af22a52f-241d-4ad4-805b-4d491a9c269d) |
Lighting preferences also got updated. As we have right now multiple lights I decided to ditch the light dragger as it would be pretty hard to make it work for that scenario. 
| ![image](https://github.com/user-attachments/assets/1bd717bd-2a5f-4753-a3c6-4ae3e8cb87c1) | ![image](https://github.com/user-attachments/assets/8b77f447-891e-4aaf-aadc-829afcc93f1d) |
- Restore some kind of interactive …
=> Add three-point lighting

src/Gui/Selection/Selection.cpp, src/Gui/Selection/SelectionObserverPython.cpp, src/Gui/Selection/SelectionObserverPython.h, src/Gui/ViewProvider.h, src/Gui/ViewProviderFeaturePython.cpp, src/Gui/ViewProviderFeaturePython.h
Adds support for Python-based selection callbacks to `ViewProviderFeaturePython` objects.
It follows the same conventions as `SelectionObserverPython`, here is an example that can be used for testing:
```python
import FreeCAD, FreeCADGui, Part
from pivy import coin
class Molecule:
def __init__(self, obj):
''' Add two point properties '''
obj.addProperty("App::PropertyVector","p1","Line","Start point")
obj.addProperty("App::PropertyVector","p2","Line","End point").p2=FreeCAD.Vector(5,0,0)
obj.Proxy = self
def execute(self, fp):
''' Print a short message when doing a recomputation, this method is mandatory '''
fp.Shape = Part.makeLine(fp.p1,fp.p2)
def loads(self, state):
return None
def dumps(self):
return None
class ViewProviderMolecule:
def __init__(self, vobj):
''' Set this object to the …
```
=> Gui: Provide `ViewProviderFeaturePython` selection callbacks

src/Mod/Surface/App/FeatureGeomFillSurface.cpp
Trim B-Spline or Bezier if it created by casting from Geom_Curve. In all other cases resulted curve got trimmed one way or another.
=> Fixes "Surface - Fill boundary curves not honor SplitCurve edge if it's part of BSpline" #19581

src/Mod/Part/App/PropertyTopoShape.cpp
`_Ver` can contain "?" after loading and in some circumstances this is not cleared (often by `setValue()`) before saving (`MultiPattern` children or empty `Part::Feature`). When saved the same "?" is then written again to the file causing the recomputing dialog to pop up again and again.
This not only checks for an empty `_Ver` but also explicitly for "?" and then regenerating the version if necessary.
Fixes #16958 for the provided test file and the mentioned MultiPattern case.
This should be reviewed by someone with knowledge about the element maps. 
This should also be backported to 1.0 as this seems to be triggered by older files, most likely from dev versions.
=> Always update the element map version if it's not valid or unknown

src/Mod/AddonManager/addonmanager_utilities.py
Follow-up to https://github.com/FreeCAD/FreeCAD/pull/19816, as suggested by @chennes. It should make the user-visible installation path string in the Python dependencies installation dialog easier to read. Via [os.path.normpath](https://docs.python.org/3/library/os.path.html#os.path.normpath).
=> Add-On Manager: collapse up-level vendor_path reference for better legibility

src/Mod/Fem/App/PreCompiled.h
Build broken on visual studio because of missing header in precompiled of FEM
After https://github.com/FreeCAD/FreeCAD/commit/5042b944630b3bb64a7e1ba4c84cc1bf11868f2c
=> FEM Update PreCompiled.h to fix build

src/Base/Tools2D.h, src/Base/Vector3D.h, src/Gui/CMakeLists.txt, src/Gui/Inventor/SoFCPlacementIndicatorKit.cpp, src/Gui/Inventor/SoFCPlacementIndicatorKit.h, src/Gui/SoFCDB.cpp, src/Gui/SoTextLabel.cpp, src/Gui/SoTextLabel.h, src/Gui/ViewProviderDragger.cpp, src/Gui/ViewProviderDragger.h, src/Mod/Part/Gui/ViewProvider2DObject.cpp, src/Mod/Part/Gui/ViewProvider2DObject.h
This is follow up on the https://github.com/FreeCAD/FreeCAD/pull/18910 PR. That adds the "Show Placement" utility that shows, well, the placement (or origin) of the object the same way as Assembly connectors are rendered. This is also useful for sketches (and other as it shows the center point, normal direction and axes of the sketch).
It also fixes issue with plane rendering not working for empty sketches.
Fixes https://github.com/FreeCAD/FreeCAD/issues/19206
Fixes https://github.com/FreeCAD/FreeCAD/issues/19205
Fixes https://github.com/FreeCAD/FreeCAD/pull/12296
=> Gui: Add Show Placement helper 

cMake/FreeCAD_Helpers/SetupOpenGL.cmake
Functionally this reverts 16ac5f0a5025ed97cf1ffee0a23accd43a390dd7, though I'm putting this OpenGL-specific code in the SetupOpenGL file instead of the make CMakeLists file. Eventually it would be good to narrow the list of systems this actually applies to so we know where we need to test if we eventually want to remove it.
=> CMake: Force OpenGL to use legacy

src/Gui/Dialogs/DlgAbout.cpp
If I understand it correctly, as `ifcopenshellVerAsStr` is not a PyObject, there is no need to decrease reference counting. See also the [PyUnicode_AsUTF8 API documentation](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUTF8).
Fixes #19829
=> Do not decrease reference counting for string

src/Mod/Spreadsheet/Gui/SheetTableView.cpp
This commit removes an apostrophe if it is the first symbol in the cell content when it is copied to clipboard.
Relevant PR is #9667. Perhaps, @0penBrain might want to comment this PR.
Closes #10058.
=> [Spreadsheet] Remove prepended apostrophe if cell content is copied into clipboard

src/Mod/BIM/ArchAxis.py
Fixes #19577
Apparently the ViewObject can be updated before the Shape of the objects has been changed. To catch this the number of edges is checked in the `onChanged` method of the ViewObject.
There was an additional index error if the Limit property was not zero.
=> BIM: fix ArchAxis index errors

src/Mod/Tux/NavigationIndicatorGui.py
#19568 adds the SolidWorks navigation style. In the Gui the new style appeared at the bottom of the list below 'Touchpad'. This PR restores the A-Z order of the list.
=> Gui: put SolidWorks navigation style in A-Z order

src/Mod/AddonManager/Addon.py, src/Mod/AddonManager/AddonManagerTest/app/test_addon.py, src/Mod/AddonManager/AddonManagerTest/app/test_metadata.py, src/Mod/AddonManager/AddonManagerTest/data/bundle_only.xml, src/Mod/AddonManager/AddonManagerTest/data/combination.xml, src/Mod/AddonManager/AddonManagerTest/data/other_only.xml, src/Mod/AddonManager/CMakeLists.txt, src/Mod/AddonManager/Widgets/addonmanager_widget_filter_selector.py, src/Mod/AddonManager/addonmanager_devmode_add_content.py, src/Mod/AddonManager/addonmanager_metadata.py, src/Mod/AddonManager/package_list.py
Two new types of content that the Addon Manager will support (actually, only minor tweaks on existing content):
1) "bundle" -- A content item that only declares dependencies on other addons, basically a meta-package for installing a collection of addons all at once.
2) "other" -- An explicit statement that this is *not* a workbench, but just a collection of files used for... whatever.
=> Addon Manager: Add <bundle> and <other>

src/Mod/AddonManager/AddonManagerTest/gui/test_update_all_gui.py, src/Mod/AddonManager/addonmanager_update_all_gui.py, src/Mod/AddonManager/update_all.ui
Adds two columns to the "Update All" dialog, showing the version currently installed, and then (if the update succeeds) the version after the update. No functional changes.
Here's what it looks like in-process:
https://github.com/user-attachments/assets/8c5fcad5-5fc3-4af1-9ef4-2fd9829b5b51
=> Addon Manager: Show versions in update all

.github/labels.yml
Currently PRs against the Start page sources are not automatically labeled as other parts of the code. This PR adds the `Mod: Start` label.
=> Add Start label for Start page PRs

src/Mod/Start/Gui/StartView.cpp, src/Mod/Start/StartMigrator.py
Follow up to https://github.com/FreeCAD/FreeCAD/pull/19473#issuecomment-2671207632
- There is already a location for all migration-related code for the Start page. This PR moves the C++ migration code introduced with https://github.com/FreeCAD/FreeCAD/pull/19473 to this location. Before, the `showCustomFolder` was written and then deleted by the C++ migration, on every FreeCAD start.
- The added benefit as well is that when in the future the full Start page migration is removed, it can be done from a single location 
- Code converted from C++ to Python
- Address lack of support for multiple path specification. The pre-1.0 Start Page with `showCustomFolder` featured the specification of multiple custom folder paths separated by `;;`. This is currently not supported, so if …
=> Start: move showCustomFolder parameter migration to right location

src/Mod/Start/Gui/AppStartGui.cpp, src/Mod/Start/Gui/CMakeLists.txt, src/Mod/Start/Gui/DlgStartPreferences.ui, src/Mod/Start/Gui/DlgStartPreferencesImp.cpp, src/Mod/Start/Gui/DlgStartPreferencesImp.h, src/Mod/Start/Gui/Resources/Start.qrc, src/Mod/Start/Gui/Resources/icons/preferences-start.svg
Follow up to https://github.com/FreeCAD/FreeCAD/pull/19473 and https://github.com/FreeCAD/FreeCAD/pull/19473#issuecomment-2644363171 to add GUI support for modifying the location of the custom folder, and other associated Start page preferences. Before, the existing parameters had to be specified through the Parameter Editor. The motivation for this PR is to make it easier and more intuitive for the user to modify those as settings in the standard Preferences dialog.
1. When changing the preferences, they are not reflected on the Start page until after a restart. This is the same behavior as the original Start workbench with FreeCAD 0.21. Is there a best practice recommendation as to how/when show the "Restart required" dialog?
1. In FreeCAD 0.21, it was possible to specify more than one …
=> Start: add initial preferences page

src/Mod/Part/App/AppPartPy.cpp
Python version is always greater than 3.9
=> Clean AppPartPy.cpp

src/App/Application.cpp, src/Base/Console.h, src/Mod/Spreadsheet/App/Cell.cpp, src/Mod/Spreadsheet/App/DisplayUnit.h, src/Mod/Spreadsheet/App/PropertySheet.cpp, src/Mod/Spreadsheet/App/Sheet.cpp, src/Mod/Spreadsheet/Gui/DlgBindSheet.cpp, src/Mod/Spreadsheet/Gui/ZoomableView.h
Our most recent Coverity scan pointed out a couple of things that I've started addressing:
* With the use of `fmt::sprintf` in things like `Console().Warning()`, it's now possible for those console calls to raise an exception, which means they really shouldn't get used in a destructor (destructors are `noexcept` by definition). To avoid this warning from Coverity, instead of raising an exception, make the actual console output the error message from `fmt`.
* In many place in our code, we create a resource (like a `std::string`), and then as a final step *copy* it into some storage location. Of course, these copies can all be `std::move` instead. This PR cleans up `App/Application.cpp` and `Mod/Spreadsheet` in this regard.
There were many others, but rather than cram everything into one …
=> Base: Coverity fixes from February 2025 run (round 1)

.github/workflows/sub_buildUbuntu.yml, package/ubuntu/install-apt-packages.sh
This provides a few benefits, as regular users can just call this script as well and not need to copy this from the CI files to know which packages to install.
=> CI: Extract `apt` packages installation into a script.

src/Mod/Draft/draftguitools/gui_edit.py
Fixes #19939
The `isAttachedToDocument` method only works in certain circumstances.
https://forum.freecad.org/viewtopic.php?t=94709
=> Draft: fix Draft_Edit isAttachedToDocument issue

src/Base/PreCompiled.h
Rebased today and get build errors : 
Base/Color.cpp : setfill not defined in std
Apparantly this header 
`#include <iomanip>`
Is needed and is not in precompiled.h
@chennes
=> Fix precompiled build

src/Mod/Fem/Gui/CMakeLists.txt, src/Mod/Fem/Gui/Resources/symbols/ConstraintCurrentDensity.iv, src/Mod/Fem/Gui/Resources/ui/CurrentDensity.ui, src/Mod/Fem/Gui/ViewProviderFemConstraint.cpp, src/Mod/Fem/Gui/ViewProviderFemConstraint.h, src/Mod/Fem/femexamples/equation_magnetodynamics_2D_elmer.py, src/Mod/Fem/femobjects/constraint_currentdensity.py, src/Mod/Fem/femsolver/elmer/equations/magnetodynamic2D_writer.py, src/Mod/Fem/femsolver/elmer/equations/magnetodynamic_writer.py, src/Mod/Fem/femsolver/elmer/equations/staticcurrent_writer.py, src/Mod/Fem/femtaskpanels/task_constraint_currentdensity.py, src/Mod/Fem/femviewprovider/view_constraint_currentdensity.py
Depending on the equation used, the current density can be defined either as a body force (using Elmer's terminology) by defining the current density vector that flows through a solid, or as a boundary condition defining the normal component of current density that flows through a surface.
Therefore, the `ConstraintCurrentDensity` object is modified by adding the `Mode` enumeration property `[ "Custom", "Normal"]` to indicate the operating mode associated with the direction of the current density vector.
The `MagnetoDynamics2D(Harmonic)` equation uses the current density normal to the surface as the body force. Now, to work with this equation, the current value must be indicated by setting the mode to `"Normal"` and specifying the real and imaginary components (only valid for the harmonic …
=> Fem: Improve current density boundary condition

src/Mod/TechDraw/App/CMakeLists.txt, src/Mod/TechDraw/App/CenterLine.cpp, src/Mod/TechDraw/App/CenterLine.h, src/Mod/TechDraw/App/CenterLinePyImp.cpp, src/Mod/TechDraw/App/Cosmetic.cpp, src/Mod/TechDraw/App/Cosmetic.h, src/Mod/TechDraw/App/CosmeticEdgePyImp.cpp, src/Mod/TechDraw/App/CosmeticVertex.cpp, src/Mod/TechDraw/App/CosmeticVertex.h, src/Mod/TechDraw/App/CosmeticVertexPyImp.cpp, src/Mod/TechDraw/App/GeomFormatPyImp.cpp, src/Mod/TechDraw/App/Geometry.cpp, src/Mod/TechDraw/App/Geometry.h, src/Mod/TechDraw/App/PreCompiled.h, src/Mod/TechDraw/App/Tag.cpp, src/Mod/TechDraw/App/Tag.h
- Reuses code
- Avoids heavy boost uuid headers in files
- Makes `Tag` a base class
- Classes needing tag inherits `Tag` class
=> TechDraw: centralize tag functionality

cMake/FreeCAD_Helpers/CompilerChecksAndSetups.cmake
Adds some colors with makes it much easier to parse/navigate compiler output.
=> CMake: Add GCC/Clang `-fdiagnostics=color` compiler option.

src/Mod/BIM/nativeifc/ifc_openshell.py
- Use Python `packaging`'s methods to compare semver version numbers. It's a dependency installed by default for the CAM workbench. This needs to be checked on different platforms/packages
- Allow upgrading packages by specifying the `--upgrade` option. Before, upgrade did not work if a version of IfcOpenShell was already installed on the system.
- Use `addonmanager_utilities`'s newly changed `create_pip_call` method. This allows the call to run on confined packages (snap) and the AppImage as well.
Other minor changes:
- Remove the now obsolete original method to compare versions
- The check for whether the pip version starts with "v" has also been removed. This no longer seems to be the case with recent releases: https://pypi.org/project/ifcopenshell/#history
- On Windows occasionally …
=> BIM: make ifcopenshell version upgrade more robust

src/Mod/Start/Gui/FileCardView.cpp
if for whatever reason the viewport failed to resize let qt add the scrollbars
fixes #15113
if #19901 gets merged this will be very unlikely to happen, to my understanding it's an issue caused by lag between render and viewport realization, with the utilization of painter and styled delegate i couldn't reproduce the issue anymore, still this should be added as safeguard in case it happens to someone
=> Start: fix fileview use scrollbars as needed

src/Gui/Application.cpp, src/Gui/Application.h, src/Gui/CommandDoc.cpp
Replaces https://github.com/FreeCAD/FreeCAD/pull/18951
@tritao regarding previous feedback, I can confirm testing a 0.21.x file there is a single `checkForRecomputes` triggered for both Drag & Drop and File > Open
Also tested a version 1.0 file to ensure that there wasn't a Recompute triggered, as well as a Step and a DXF file, all worked as I would expect.
I've left the checks in Application primarily because I tried and failed to compile it any other way. With Werner creating them as separate checks I'm not inclined to combine them at this stage.
@wwmayer would you mind reviewing please.
Fixes #18889
=> [Gui] Trigger the same checks for Drag & Dropping files as File > Open

src/Mod/Sketcher/App/SketchObject.cpp
Eternal defining vertex wasn't added to the resulting shape compound. This PR fixes that. The only thing I not sure is elements mapping, but looks like it works fine.
=> fix #18356 Sketcher: External reference line defaults to geometry, but vertex does not

src/App/Application.cpp
This is a cherry-pick (and conflict-resolution) from #19727 consisting of the dozen commits from that PR that were obviously good to merge. 
The ones that I *did not* include here are:
* [Const](https://github.com/FreeCAD/FreeCAD/pull/19727/commits/6e51bce82496047f0b8214fe3dded84c21a1cefc)
* [Removed redundant qualifier](https://github.com/FreeCAD/FreeCAD/pull/19727/commits/b09244a84710d1607e6a3ed84c9bc2baf63988be)
* [Inconsistent name](https://github.com/FreeCAD/FreeCAD/pull/19727/commits/63070d276af276329df09234709b9146fa36dfff)
* [Implicit conversion](https://github.com/FreeCAD/FreeCAD/pull/19727/commits/6d9893f3e4651f67dee324c8660cc9fd69cac962)
These were not included not because they were wrong, or unacceptable, but because there were multiple solution paths and there was some …
=> Application tidy up (the easy ones)

src/Gui/PreferencePages/DlgSettingsLightSources.cpp, src/Gui/PreferencePages/DlgSettingsLightSources.h, src/Gui/View3DSettings.cpp
* Move configuration for light sources into a new group (no reused settings anymore)
* Clear reused settings if found, making 1.0 get default values when loaded next time
Fixes https://github.com/FreeCAD/FreeCAD/issues/19879
=> Fixes light direction configuration issues between 1.0 and 1.1dev

src/Gui/Dialogs/DlgAbout.cpp
This is related to https://github.com/FreeCAD/FreeCAD/issues/19887
For HiDPI scaling, what Qt uses internally, and what FreeCAD uses in some places, is the `devicePixelRatio` variable. How it turns the actual ratio of logical to physical pixels into this value (and what kind of rounding it does) is platform dependent, and also somewhat controllable. 
Anyway, I think this is the important number to capture.
This still only shows it for the primary screen, and so might be misleading for folks with multiple monitors.
=> Add devicePixelRatio to about info

src/Mod/Start/App/CustomFolderModel.cpp, src/Mod/Start/App/CustomFolderModel.h, src/Mod/Start/Gui/DlgStartPreferences.ui, src/Mod/Start/Gui/PreCompiled.h, src/Mod/Start/Gui/StartView.cpp, src/Mod/Start/StartMigrator.py
Brings back the same functionality from 0.21: the ability to specify multiple custom folders whose contents will be shown as a combined set of files in the "Custom Folder" file card on the Start page.
Multiple folder paths are specified using the `;;` separator (e.g. `/home/me/folder1;;/home/me/folder2`), in the file chooser entry on the Start page's preference dialog.
1. The code to split paths has been adapted from https://stackoverflow.com/a/14266139/25233079 using standard C++. Using Qt classes could have been another alternative.
2. If any of the paths specified is not readable or does not exist, a warning is shown to the user. Entries from that location are not subsequently shown in the Custom Folder file card.
3. If none of the paths specified are correct as validated by the …
=> Start: enable multiple custom folder paths

src/App/Document.cpp, src/App/PropertyStandard.cpp
Fixes #19980
PR #18676 changed the management of Label uniqueness. A bug in that change meant that if a DrawingObject were created, then deleted, in the same transaction, the record of its Label would remain, and subsequent attempts to use the same Label might find the intended Label changed to make it unique.
The Measure tool is quite insistent that the Label of its object be of the form "some text: actual measurement". If it attempts to set this but uniqueness forces the text to be "some text: actual measurement001", it will, in the Change notification for the Label property again try to set "some text: actual measurement", which again instead sets "some text: actual measurement001", generating an infinite recursion of these notifications and futile Label changes.
It is also possible to …
=> Fix the Measure Tool which will crash the app with a stack overflow if you measure the same amount twice

src/Tools/bindings/templates/templateClassPyExport.py
* Removes warnings while building.
* Avoids manually if-defing fields based on python version
Note: unnamed fields are zero-initialized (`0`, `nullptr` etc.), only the order matters
=> Python bindings: Use designated initializers and remove zero-initialized fields

src/Gui/Stylesheets/FreeCAD Dark.qss, src/Gui/Stylesheets/FreeCAD Light.qss, src/Mod/Start/Gui/FileCardDelegate.cpp, src/Mod/Start/Gui/FileCardDelegate.h, src/Mod/Start/Gui/FileCardView.cpp, src/Mod/Start/Gui/FileCardView.h, src/Mod/Start/Gui/StartView.cpp
fixes #15758
fixes #16843
due to the removal of render() and the refactor probably fixes this two
#17771
#19749
=> Start: fix text visbility

src/Tools/bindings/templates/templateClassPyExport.py
Suppress GCC-specific warning for feature allowed in C++20.
=> Suppress erroneous warnings for GCC in python template

src/App/Application.cpp, src/App/Application.h
This unifies the names of the parameters between the *.h and *.cpp files, making clang-tidy happier, and names them all the same thing when used in the same way across different calls, making *me* happier. Note that this file is not currently covered by our clang-format policy, so any formatting changes here are incidental.
=> App: Cleanup parameter names in Application.*

src/Gui/ExpressionBinding.cpp
fix https://github.com/FreeCAD/FreeCAD/issues/20004
This stylesheet modification is done in 
```
void ExpressionSpinBox::showIcon()
{
int frameWidth = spinbox->style()->pixelMetric(QStyle::PM_SpinBoxFrameWidth);
lineedit->setStyleSheet(QStringLiteral("QLineEdit { padding-right: %1px } ").arg(iconLabel->sizeHint().width() + frameWidth + 1));
iconLabel->show();
}
```
already
=> QuantitySpinbox: Fix right padding when not bound

src/Mod/PartDesign/App/FeaturePolarPattern.cpp
Fix App::Line as ref for polar pattern position ignored.
Fix https://github.com/FreeCAD/FreeCAD/issues/19401
=> PartDesign: Fix App::Line as ref for polar pattern

src/App/Application.cpp, src/App/Application.h, src/App/ApplicationPy.cpp, src/Gui/Application.cpp, src/Mod/Import/App/ImportOCAF2.cpp, src/Mod/PartDesign/App/ShapeBinder.cpp
So a couple things going down on this one:
The main changes are these two, which are fairly simple to review in isolation:
[App: Fix memory leak regression in ApplicationPy::newDocument.](https://github.com/FreeCAD/FreeCAD/commit/d6510061b3a5be68b1dbad7d91d26b7d69df1d37)
[App: Fix regression when creating new document coming from the main document.](https://github.com/FreeCAD/FreeCAD/commit/9685a1a6efaf4d8bd4b62ac940c609b1f18c3a8c) 
Then it does some code quality changes, using C++20 designed initializers for simpler initialization, and renames `DocumentCreateFlags` to `DocumentInitFlags` as it's used both for creation and opening, so I think that name fits better.
Closes https://github.com/FreeCAD/FreeCAD/issues/19482
Fixes regression from  https://github.com/FreeCAD/FreeCAD/pull/19136.
=> App: Fix regression for document creation requests coming from the main document.

cMake/FreeCAD_Helpers/SetupCoin3D.cmake
In recent versions of CMake, Coin3D's support for using older versions of CMake causes a fairly noisy deprecation warning. Coin's support for old CMake doesn't seem to cause any problems (at least in the CMake 3.x line) so I think it is reasonably safe to silence this warning.
=> CMake: Silence Coin3D deprecation warning

src/Mod/TechDraw/App/CenterLine.cpp, src/Mod/TechDraw/App/Cosmetic.cpp, src/Mod/TechDraw/App/DimensionGeometry.cpp, src/Mod/TechDraw/App/DrawBrokenView.cpp, src/Mod/TechDraw/App/DrawComplexSection.cpp, src/Mod/TechDraw/App/DrawGeomHatch.cpp, src/Mod/TechDraw/App/DrawUtil.cpp, src/Mod/TechDraw/App/DrawUtil.h, src/Mod/TechDraw/App/DrawViewDimension.cpp, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/App/DrawViewSection.cpp, src/Mod/TechDraw/App/Geometry.cpp, src/Mod/TechDraw/App/GeometryMatcher.cpp, src/Mod/TechDraw/App/ShapeUtils.cpp, src/Mod/TechDraw/Gui/CommandExtensionPack.cpp, src/Mod/TechDraw/Gui/DimensionValidators.cpp, src/Mod/TechDraw/Gui/TaskComplexSection.cpp
Fixes https://github.com/FreeCAD/FreeCAD/issues/18886
I have duplicated the specialization of vec_traits for gp_Pnt and co in DrawUtil.h because I wasn't sure if I should include the Tool.h header from Part workbench that also defines these. If you want I can create another public header that defines these and include it wherever needed to avoid the code duplication. Let me know which approach should I take.
=> TechDraw: removed gp_* conversion code from TechDraw workbench

src/Mod/BIM/Arch.py
Fixes: https://github.com/FreeCAD/FreeCAD/issues/20106
Note: I see quite a few functions on the Arch module, and a TODO note to migrate the `ArchStructure` import. Does this mean that a curated selection of methods from a given module (e.g. `ArchSpace` or `ArchStructure`) need to be moved to the `Arch` module instead of doing a full import? If so, happy to do it. But it might be worth merging this to unblock users who work with spaces in the meantime. And it might be a simpler backport as well.
=> BIM: fix adding/removing boundaries to BIM Spaces

src/Mod/Draft/draftguitools/gui_snapper.py
Fixes #15017.
Currently Near snap overrides all other 'on-object' snaps such as Midpoint snap and Endpoint snap. With this PR Near snap no longer 'wins' if a different snap point is within snapRange of the cursor.
=> Draft: Correct Near snap override behavior

src/Mod/Draft/draftmake/make_dimension.py, src/Mod/Draft/draftutils/params.py, src/Mod/Draft/draftviewproviders/view_dimension.py
Fixes #19993.
* To determine the `FlipText` value the normal (either the working plane Z axis or its reverse) and the working plane X axis are used.
* A new fine-tuning parameter `DimAutoFlipText` can be used to disable the functionality. Its default value is `True`.
* The `FlipText` property did not work for angular dimensions and the `TextSpacing` property of angular dimensions was not multiplied by `ScaleMultiplier`. This has been corrected.
=> Draft: Implement Dim Auto Flip Text

src/Mod/Assembly/Gui/PreCompiled.h, src/Mod/Cloud/Gui/PreCompiled.h, src/Mod/Import/Gui/PreCompiled.h, src/Mod/Material/Gui/PreCompiled.h, src/Mod/Measure/Gui/PreCompiled.h, src/Mod/Mesh/Gui/Command.cpp, src/Mod/Mesh/Gui/PreCompiled.h, src/Mod/Part/Gui/PreCompiled.h, src/Mod/PartDesign/Gui/PreCompiled.h, src/Mod/Sketcher/Gui/PreCompiled.h, src/Mod/Spreadsheet/Gui/PreCompiled.h, src/Tools/_TEMPLATE_/Gui/PreCompiled.h
before including the library, it is uselessly checked if the variable __QtAll__ and __InventorAll__ have been defined. The same check is performed again once the library is included
=> Remove unnecessary check (duplicated)

src/Mod/TechDraw/App/CosmeticExtension.cpp
=> TechDraw: Fix double free when resetting line formats

src/Gui/propertyeditor/PropertyItem.cpp, src/Gui/propertyeditor/PropertyItem.h, src/Mod/Sketcher/Gui/PropertyConstraintListItem.cpp, src/Mod/Sketcher/Gui/PropertyConstraintListItem.h
I have no idea why the return type of `toString` was ever `QVariant`
I'm not even sure why there are so many `toString` functions implemented - I don't think they are ever used?
=> Gui: clean up PropertyItem::toString

src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp, src/Mod/Sketcher/Gui/TaskDlgEditSketch.h
This PR is based on @PaddleStroke's https://github.com/FreeCAD/FreeCAD/pull/19849 but only contains the part of moving the function from the h file to the cpp file.
I've credited paddle as the author in this commit due to the code was created in his PR, though the commit splitting was done by me.
While this will create a collision for astocad currently, I believe it will make it easier for paddle to rebase his fork in the future.
=> Sketcher: Move getStandardButtons to cpp file

src/Mod/Part/App/FCBRepAlgoAPI_BooleanOperation.cpp, src/Mod/Part/App/FCBRepAlgoAPI_BooleanOperation.h
With the changes made in #19468, when the tool is a compound with one shape, there is an infinite recursion happening in `FCBRepAlgoAPI_BooleanOperation::Build()`. The code looks like it was ment to call the base class after restoring the original state. I'm not sure if all calls to `Build()` should go to the base class?
@hyarion could you maybe have a look at this?
=> Part: fix infinite recursion in boolean cut

src/Mod/Sketcher/App/SketchObject.cpp
It appears that BRepOffsetAPI_NormalProjection not able to project not only B-Spline from perpendicular plane, but from parallel too. This PR fixes that by porting part of Linkstage3 code with some minor tweaks.
=> fix #19831 Sketcher: Create external Intersection geometry not working with complex surfaces

src/Mod/Mesh/Gui/PreCompiled.h
This was inadvertently deleted in a recent cleanup PR.
=> Mesh: Fix mistaken deletion of #include <Gui/InventorAll.h>

src/Mod/Draft/draftguitools/gui_snapper.py
The code in #20118 would fail if only Near snap was active.
=> Draft: Fix error in #20118

src/Mod/Sketcher/App/ExternalGeometryExtension.cpp, src/Mod/Sketcher/App/SketchGeometryExtension.cpp, src/Mod/Sketcher/App/planegcs/Constraints.h
* numpoints from double to int
* Remove redundant out-of-line definition for constexpr static data member
=> Sketcher: Clean up compiler warnings

cMake/FreeCAD_Helpers/InitializeFreeCADBuildOptions.cmake, src/3rdParty/CMakeLists.txt, src/App/CMakeLists.txt, src/App/Document.cpp, src/Base/CMakeLists.txt, src/Base/Profiler.h, src/Gui/Application.cpp, src/Gui/CMakeLists.txt, src/Gui/Quarter/QuarterWidget.cpp, src/Gui/Quarter/SoQTQuarterAdaptor.cpp, src/Gui/View3DInventorViewer.cpp, src/Mod/Part/CMakeLists.txt, src/Mod/Part/Gui/CMakeLists.txt, src/Mod/Part/Gui/SoBrepFaceSet.cpp
This PR adds initial support for frame profiling via the Tracy profiler: https://github.com/wolfpld/tracy
> A real time, nanosecond resolution, remote telemetry, hybrid frame and sampling profiler for games and other applications.
Here is a small example of a profiling section, showing the functions running in each frame, in this case `SoGetBoundingBoxAction` and `SoBoxSelectionRenderAction`, where most of the frame was spent in that particular scene:
For such detailed output, manual instrumentation of the code is necessary, the initial FreeCAD parts are done in this PR (for rendering and selection), but additional instrumentation will be necessary for other parts of the code, like geometry/OCC-related code.
To get truly good output, some instrumentation changes to Coin3D were also …
=> Base: Add Tracy frame profiling support.

src/Mod/Measure/Gui/Resources/translations/Measure_es-ES.ts, src/Tools/updatets.py
Before this change when compiling this message appeared:
- _RCC: Warning: No resources in '/opt/FreeCAD/src/Mod/Measure/Gui/Resources/Measure_translation.qrc'._
After I manually created file for Spanish translation:
```txt
[88/348] Generating Resources/translations/Measure_es-ES.qm
Updating '/opt/FreeCAD/src/Mod/Measure/Gui/Resources/translations/Measure_es-ES.qm'...
Generated 33 translation(s) (33 finished and 0 unfinished)
```
> [!NOTE]
> Changes must be pushed to Crowdin with `./updatecrowdin.py gather && ./updatecrowdin.py update`
And translations work
Except on strings for measure task where context is `Gui::TaskMeasure` but class is named 
https://github.com/FreeCAD/FreeCAD/blob/33631507f61c30ba0007728983496e16015e19e5/src/Mod/Measure/Gui/TaskMeasure.cpp#L63
Add Spanish translation …
=>  Measure: add translation source file for uploading to Crowdin

src/Mod/Sketcher/Gui/DrawSketchDefaultHandler.h
Fix https://github.com/FreeCAD/FreeCAD/issues/17722
Currently when a DrawSketchHandler (circle tool for instance) was finishing, the following was done : 
```
bool finish()
{
...
if (sugConstraints.size() > 0) {
generateAutoConstraints();
beforeCreateAutoConstraints(); //OVP's constraints added here
createAutoConstraints();
}
}
```
Which basically was giving priority to autoconstraint over OVP (onViewParameters)'s constraints. Since first the autoconstraints were generated, then OVP constraints were added only if they did not conflicts.
IMO this is not correct. If the user has typed in a dimension, the dimension should have the priority.
So this PR suggest first adding the OVP's constraints. Then try to add the auto-constraints if they are not redundant/conflicting.
=> Sketcher: DSH: add OVP constraints before AutoConstraints.

src/Gui/PreferencePackTemplates/Sketcher_Colors.cfg, src/Mod/Sketcher/Gui/EditModeCoinManager.cpp, src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.cpp, src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h, src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp, src/Mod/Sketcher/Gui/SketcherSettings.cpp, src/Mod/Sketcher/Gui/SketcherSettingsAppearance.ui
Since I working a lot with projecting and using external geometry in my project I struggle a lot with differentiation between defining and reference geometry. Pattern helps a bit, but there are 2 problems with it:
1) pattern applies only to curves - there is no way to see right away where is reference point and where defining
2) pattern look awful when used on external geometry, since under projected geometry is always a line of source geometry, so to see it clearly I have to hide underlining sketch or rotate current one, so lines not overlaps.
My suggestion is addition of defining geometry color that will work for curves and vertices. If someone do not need aid of color, it could be set the same as for not defining geometry.
Here is an example how it looks with this PR:
Defining geometry …
=> Sketcher: Preference color added for External defining geometry

src/Mod/BIM/Resources/ui/dialogClassification.ui
=> BIM: Fixed classification dialog's Cancel button

src/Mod/TechDraw/Gui/PATPathMaker.cpp, src/Mod/TechDraw/Gui/PATPathMaker.h, src/Mod/TechDraw/Gui/QGCustomText.cpp, src/Mod/TechDraw/Gui/QGCustomText.h, src/Mod/TechDraw/Gui/QGIArrow.cpp, src/Mod/TechDraw/Gui/QGIBreakLine.cpp, src/Mod/TechDraw/Gui/QGICMark.cpp, src/Mod/TechDraw/Gui/QGICMark.h, src/Mod/TechDraw/Gui/QGICenterLine.cpp, src/Mod/TechDraw/Gui/QGIDecoration.cpp, src/Mod/TechDraw/Gui/QGIDecoration.h, src/Mod/TechDraw/Gui/QGIDimLines.cpp, src/Mod/TechDraw/Gui/QGIEdge.cpp, src/Mod/TechDraw/Gui/QGIEdge.h, src/Mod/TechDraw/Gui/QGIFace.cpp, src/Mod/TechDraw/Gui/QGIFace.h, src/Mod/TechDraw/Gui/QGIHighlight.cpp, src/Mod/TechDraw/Gui/QGIPrimPath.cpp, src/Mod/TechDraw/Gui/QGIPrimPath.h, src/Mod/TechDraw/Gui/QGISectionLine.cpp, src/Mod/TechDraw/Gui/QGITile.cpp, src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
Previously, all data styling has been saved twice.
First in a local member variable - and then before painting, the QPen will be synchronized with the local variables. This causes great confusion when editing code and can cause bugs. It makes code harder to read and debug as well.
There are no reason to have two copies.  Let's save all styling data directly in QPen.
I have to the best of my abilities tested the changes - though there might be a few bugs introduced. These should be fixed in other ways than reintroducing state. In the long run, these changes will ensure less bugs from being introduced.
=> TechDraw: remove unneeded state, part 1

src/App/Extension.cpp, src/App/Extension.h, src/App/ProjectFile.cpp, src/App/PropertyContainer.h, src/App/PropertyStandard.cpp, src/Base/BaseClass.cpp, src/Base/BaseClass.h, src/Base/BaseClassPyImp.cpp, src/Base/Type.cpp, src/Base/Type.h, src/Base/TypePyImp.cpp, src/Gui/DAGView/DAGFilter.cpp, src/Gui/DAGView/DAGModel.cpp, src/Gui/Dialogs/DlgAddPropertyVarSet.cpp, src/Gui/Dialogs/DlgExpressionInput.cpp, src/Gui/Selection/Selection.cpp, src/Mod/Measure/App/MeasureDistance.cpp, src/Mod/Part/App/GeometryDefaultExtension.h, src/Mod/Part/App/GeometryPyImp.cpp, src/Mod/Sketcher/App/ExternalGeometryFacadePyImp.cpp, src/Mod/Sketcher/App/GeometryFacadePyImp.cpp, src/Mod/Sketcher/Gui/CommandConstraints.cpp, src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
This PR includes:
* add documentation for public functions
* change functions to use pass-by-value instead of -by-reference for parameters, as intended for this class
* add `static_cast`s to ensure size doesn't grow to the point where passing Type by value is slower than by reference.
* use `BadType` constant instead of `badType()`.
* use `isBad()` instead of `==operator` (should be more lightweight and align better with the intent)
=> Refactor Base::Type

src/Gui/CommandStd.cpp, src/Gui/Dialogs/DlgMacroExecuteImp.cpp, src/Gui/Dialogs/DlgPreferencesImp.cpp, src/Gui/Placement.cpp, src/Gui/TaskView/TaskDialog.cpp, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp, src/Mod/Fem/Gui/ViewProviderFemPostFunction.cpp, src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp, src/Mod/PartDesign/Gui/Command.cpp, src/Mod/PartDesign/Gui/SketchWorkflow.cpp, src/Mod/PartDesign/Gui/TaskDatumParameters.cpp, src/Mod/PartDesign/Gui/ViewProvider.cpp, src/Mod/PartDesign/Gui/ViewProviderBoolean.cpp, src/Mod/PartDesign/Gui/ViewProviderDatum.cpp, src/Mod/PartDesign/Gui/ViewProviderHole.cpp, src/Mod/PartDesign/Gui/ViewProviderPrimitive.cpp, src/Mod/PartDesign/Gui/ViewProviderShapeBinder.cpp, src/Mod/Points/Gui/Command.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp, src/Mod/TechDraw/Gui/Command.cpp, src/Mod/TechDraw/Gui/CommandExtensionDims.cpp, src/Mod/TechDraw/Gui/TemplateTextField.cpp
Unparented popups can easily get lost in backround, but they still block top level event loop when run with ::exec() thus preventing interactions with main window. This can lead to very frustrating experience where you can't interact with main window and don't know why. Setting the parent ensures they are always kept on top and reasonably positioned.
I did my best to test most of them except all the copy pasted ""A dialog is already open in the task panel" stuff.
This mainly affects wayland. But even when running with QT_QPA_PLATFORM=xcb it can sometimes be a problem. For example macro window toolbar guide gets kept on top of main window but not the macro window so it can still get lost between the two.
There are probably quite a few other similar instance, but this seemed like reasonable …
=> Add missing parent for messagbox and other popups.

src/Mod/CAM/Tools/Bit/30degree_Vbit.fctb, src/Mod/CAM/Tools/Bit/45degree_Vbit.fctb, src/Mod/CAM/Tools/Bit/90degree_Vbit.fctb, src/Mod/CAM/Tools/Library/Default.fctl
Change default V-bit tip diameter to 0.1 mm to avoid confusion and reports about VCarve engraving above the stock.
This diameter also matches most commercial bits anyway.
PR also adds other popular v-bits: 30, 45 and 90 degrees to spare users creating their own tools as the tool bit UI is broken and frustrating.
Fixes: https://github.com/FreeCAD/FreeCAD/issues/16701
cc: @sliptonic
=> [CAM] Change VBit tip diameter to 0.1 mm.

src/Mod/TechDraw/Gui/QGVNavStyleTouchpad.cpp
The cursor flickers (changes between the picker cursor and the normal one) in techdraw workbench while picking a cosmetic vertex using the picker. This problem is can be reproduced only using the touchpad control scheme. This PR aims to solve that by preventing the continuous calls to stopPan and stopZoom (both of these functions set the cursor to normal).
Here is the video showing how to reproduce the issue:
https://github.com/user-attachments/assets/9aab8325-a006-4b97-9a91-585a6002057a
Ideally, calls to stopPan and stopZoom shouldn't be needed at all there since the handleKeyReleaseEvent should be handling that gracefully. But for some reason releasing the shift key isn't registered from time to time.
Actually, that can be reproduced as a separate problem in techdraw. Start panning, …
=> TechDraw: Fix flickering cursor issue

src/Mod/Draft/draftguitools/gui_edit.py
Fixes #20193.
The key down events can be claimed by shortcuts from other workbenches. Detecting both the down and up events does not seem to cause problems.
=> Draft: make Draft_Edit also detect key up events

src/App/Application.cpp
This pull request fixes the MacOS build mentioned in #20068 by reverting commit 8ff4b1b and improving the comments so that the same issue hopefully doesn't happen again
=> [App] fix MacOS build reported in #20068

src/Mod/CAM/CAMTests/TestRefactoredGrblPost.py, src/Mod/CAM/CAMTests/TestRefactoredTestPost.py, src/Mod/CAM/CAMTests/TestRefactoredTestPostGCodes.py, src/Mod/CAM/Path/Post/UtilsArguments.py, src/Mod/CAM/Path/Post/UtilsParse.py
The refactored* postprocessor shared code base has many configuration choices that don't have command line options.
This PR adds three command line options along with their corresponding tooltip info and tests.
This PR is the first of several to keep the PR from getting too big.
Please assign this to me.  Thanks!
=> CAM:  Added three command line options to the refactored postprocessors code base, with tests

src/App/Branding.cpp, src/App/ComplexGeoData.cpp, src/App/ComplexGeoData.h, src/App/Document.cpp, src/App/DocumentObject.cpp, src/App/DocumentObjectPyImp.cpp, src/App/ElementMap.cpp, src/App/Expression.cpp, src/App/ExpressionTokenizer.cpp, src/App/GeoFeature.cpp, src/App/GeoFeatureGroupExtension.cpp, src/Gui/DAGView/DAGRectItem.cpp
Most of the fixes are trivial (use of `std::move`), but a couple of them are more subtle and need careful review. No functional changes are intended. The most serious of these is the fixed iterator invalidation on the expression parsing: everything else is basically just performance.
=> Coverity fixes 2025.03.02

src/App/PropertyLinks.cpp
#19900 has a typo, this commit fixes it. Closes #20212.
CC @tritao
=> [App] Fix the crash reported in #20212

src/Mod/BIM/Arch.py, src/Mod/BIM/TestArch.py, src/Mod/BIM/bimcommands/BimSpace.py
Fixes: https://github.com/FreeCAD/FreeCAD/issues/20137
- When clicking on an object, it is assumed to be a single object that does not define boundaries if:
- it has no subelements (e.g. clicked from the Tree View) OR
- if it has only one subelement (e.g. clicked a face from the 3D window to select the object).
- In the cases above, the whole object will be converted to an Arch.Space and no boundaries will be used.
- All other cases where the number of subelements is > 1 will be considered to define boundaries. In these cases, Arch Space will be created from the boundaries defined as subelements. 
- Adds a unit test for this feature. The unit test can run both with CLI (tests parameter passing) and GUI (tests and replicates user selection in the UI).
To test the feature:
1. Start FreeCAD …
=> BIM: allow boundaries to be defined from a single object (e.g. wall)

src/Gui/Stylesheets/FreeCAD Dark.qss, src/Gui/Stylesheets/FreeCAD Light.qss
Let the layout engine computes the size of all QPushButton by unset the minimalSize value set by "min-width" QSS property in themes.
Fix #18019.
**Before**
**After**
=> fix dialogs button size in case of long text (fix for #18019)

src/Tools/bindings/generate.py, src/Tools/bindings/model/generateModel_Python.py
When this was introduced it caused a few failures (see https://github.com/FreeCAD/FreeCAD-snap/issues/178).
The problem was a faulty comparison, that was looking for the first index of `src`, when it should be the last index.
Fix it and re-enable the comparison. If there are no more build failures, we can think of removing the XML files for Base in a follow up PR.
=> Tools: Re-enable XML comparison mode in Python API bindings generator.

src/Mod/BIM/TestArch.py
Adds a unit test to check that boundaries can be added to an [Arch Space](https://wiki.freecad.org/Arch_Space) object via the [Arch Add](https://wiki.freecad.org/Arch_Add) command. It was originally intended as a regression test for https://github.com/FreeCAD/FreeCAD/issues/20106, but it was not ready at the time.
To test on Linux:
```shell
./build/bin/FreeCAD --console --run-test TestArch.ArchTest.test_addSpaceBoundaries
```
~The original intention was to make the test CLI only, but the `addSpaceBoundaries()` method takes a list of selection objects as the second argument. The only way (I know of) to pass such a list is by using `getSelectionEx()`, which is only defined in `FreeCADGui`. Thus this test requires the FreeCAD GUI to run.~ => This has been addressed.
=> BIM: add unit test for addSpaceBoundaries

src/Mod/BIM/Arch.py, src/Mod/BIM/ArchSpace.py
Follow-up to https://github.com/FreeCAD/FreeCAD/pull/20108.
- Move the `addSpaceBoundaries` and `addSpaceBoundaries` definitions to the `Arch` module.
- Make the top level function definition consistent between the two methods.
- Update and expand docstrings.
=> BIM: move add/removeSpace boundaries implementation to Arch module

src/Mod/BIM/Resources/ui/dialogClassification.ui, src/Mod/BIM/bimcommands/BimClassification.py
fixes https://github.com/FreeCAD/FreeCAD/issues/20176
1. Changed text "Prefix with class name when applying"
to
"Prefix with classification system name"
2. Changed button tooltip from "Use this class as material name"
to
"Use this class as object name"
3. Changed to tooltip of the `BIM_Classification` tool from "Manage how the different materials of this documents use classification systems"
to
"Manage classification systems and apply classification on objects"
Before state:
=> BIM_Classification dialgue - change tooltips and text to better represent their functions

src/Gui/ExpressionBinding.cpp, src/Gui/QuantitySpinBox.cpp, src/Gui/SpinBox.cpp, src/Gui/SpinBox.h
The size and location of the fx icon is very inconsistent across themes, with various issues like vertical misalignment, smaller size than the font size and text going under the icon.
this should fix those issues and provide a more reliable experience
classic
opendark (notice the vertical misalgnment)
there are more severe examples shown by @benj5378  but i cannot reproduce them in my machine
and the margin tweak:
=> Gui: fix fx size and location

src/Ext/freecad/CMakeLists.txt, src/Mod/CAM/libarea/CMakeLists.txt
can be removed now that we dropped support for ubuntu 20.04
=> cmake: remove distutils usage for python < 3.10

src/Gui/ExpressionCompleter.cpp, src/Gui/ExpressionCompleter.h, src/Mod/Spreadsheet/Gui/LineEdit.cpp, src/Mod/Spreadsheet/Gui/LineEdit.h
This pull request fixes input in expression editor in _Spreadsheet_. Tested on _KUbuntu 24.04.1 LTS_.
Closes #19804.
=> [Spreadsheet] Fix input in expression editor

src/Mod/Mesh/Gui/Workbench.cpp
_I'm not a Qt expert so I don't know if this is the proper solution or a dirty hack._
I tested by adding the translations on `src/Mod/Mesh/Gui/Resources/translations/Mesh_es-ES.ts` file on `QObject` context, recompiled and it works.
Fix https://github.com/FreeCAD/FreeCAD-translations/issues/233
=> Mesh: change context for strings on task panel

src/Gui/View3DInventorViewer.cpp
Fixes #14775.
Previously, the align to selection tool always rotated to one specific orientation for a given face/edge. This could result in a very wild disorienting rotation. Now it looks at the current camera orientation and chooses between one of four orientations to reduce the amount of rotation. It is now also more likely that a straight edge is aligned horizontally or vertically but it is not guaranteed. In another PR I want to do horizontal or vertical alignment based on the longest straight edge in a face. But that is still work in progress.
=> Gui: Align to selection using a smaller rotation

src/Mod/TechDraw/App/AppTechDrawPy.cpp, src/Mod/TechDraw/App/DrawUtil.cpp, src/Mod/TechDraw/App/DrawUtil.h, src/Mod/TechDraw/App/DrawViewDetail.cpp, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/App/DrawViewSection.cpp
This PR implements a fix for issue #20024.  
In headless mode, the program will not receive a notification that the separate threads for long running OCCT methods, and processing will not continue after the completion of the thread.
This PR implements a check for the availability of the Gui (and its event loop) and does not start separate threads if the Gui is not available, but runs those methods in the main thread.
=> [TD]Headless view creation (fix #20024)

src/Mod/Start/Gui/FileCardDelegate.cpp, src/Mod/Start/Gui/FileCardDelegate.h
some themes are rendering the filecards with black background, this should fix it
@benj5378
@Syres916
=> Start: fix filecards black background under some themes

cMake/FindOCC.cmake
PR https://github.com/FreeCAD/FreeCAD/pull/20084 broke the daily snap builds
<details>
https://github.com/FreeCAD/FreeCAD-snap/actions/runs/14003413007/job/39213830371#step:4:1163
```
:: -- Could NOT find OCC (missing: OCC_INCLUDE_DIR)
:: CMake Error at cMake/FreeCAD_Helpers/SetupOpenCasCade.cmake:4 (message):
::   ================================================================
::
::   OpenCASCADE not found!
::
::   ================================================================
::
:: Call Stack (most recent call first):
::   CMakeLists.txt:87 (SetupOpenCasCade)
::
::
:: -- Configuring incomplete, errors occurred!
Failed to run the build script for part 'freecad'.
:: + cmake /home/runner/work/FreeCAD-snap/FreeCAD-snap/parts/freecad/src -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX=/usr …
```
=> Do not specify a version in FindOCC.cmake

src/Mod/Spreadsheet/Gui/SheetModel.cpp, src/Mod/Spreadsheet/Gui/SheetModel.h
The _headerData_ function is called every time user scrolls. It generates labels on-the-fly through string concatenation, and I noticed it was invoked four thousand times just while scrolling horizontally to the end of the sheet! This approach is excessive and poorly optimized.
I've refactored the code to make it more logical and readable. Now, the function returns predefined value instead of generating strings dynamically. This change should improve performance and readability.
=> [Spreadsheet] Code base update in SheetModel.cpp

src/App/PropertyLinks.cpp, src/App/PropertyPythonObject.cpp
Coverity issues 251332 and 356538. These destructors call methods that could throw exceptions. Catch them and convert to console print statements to prevent calls to `terminate()`. An argument could be made that actually calling `terminate()` would be fine here since these exceptions should be basically impossible to hit, but I think it's best to at least attempt to recover gracefully from whatever terrible thing has happened.
=> App: Prevent exceptions in destructors

src/Mod/Fem/Gui/Command.cpp
Move the variable inside the commented-out `TODO` block.
=> Fem: remove unused variable in Command

src/Mod/Fem/App/FemMesh.cpp, src/Mod/Fem/App/FemMesh.h
Put guards not just around its use, but also its creation. Alternate solution would be to annotate it as `[[maybe_unused]]`, but my feeling is that would make it "sticky" and we'd tend not to remove it later on when it was truly unneeded. This way a search for the appropriate SMESH version check will lead to its eventual elimination. I'm happy to code this the other way if preferred.
=> FEM: myStudyId not needed when SMESH >= 9

src/Mod/Draft/DraftGui.py
Without this delay the Tray may not display if Draft is the start-up workbench.
When the Draft workbench is autoloaded the Tray is shown and then immediately hidden. Because of this, hiding the tray must also happen with a delay.
=> Draft: show and hide Tray with delay

src/Mod/Start/Gui/CMakeLists.txt, src/Mod/Start/Gui/FlowLayout.cpp, src/Mod/Start/Gui/NewFileButton.cpp, src/Mod/Start/Gui/NewFileButton.h, src/Mod/Start/Gui/StartView.cpp
in classic if one of the buttons wraps 3 lines, since my patch it doesn't cut the label, but it will be a different size:
and more broken are some themes are breaking the newfile buttons like this
so i've split the buttons into new widgets to use minimumSizeHint override and modified the flowlayout to set the sizing
=> Start: fix newbuttons vertical sizing

src/Gui/TaskCSysDragger.cpp
Per clang: "implicit capture of 'this' with a capture default of '=' is deprecated"
=> GUI: Eliminate implicit capture of this via =

src/Mod/PartDesign/App/FeatureHole.cpp
I looked around to see if there was any indication that this counter was actually needed and not being used by accident, but I didn't see anything obvious. More pairs of eyes would be appreciated.
=> PD: Eliminate unused variable in FeatureHole

src/Base/PyObjectBase.cpp
This field is undocumented at https://docs.python.org/3.13/extending/newtypes.html, but exists in the source code for 3.13 (see https://github.com/python/cpython/blob/3.13/Include/cpython/object.h#L232) and gives a compiler warning if left uninitialized.
=> Base: Initialize tp_versions_used in PyTypeObject (3.13)

src/Base/PyObjectBase.cpp
Deprecated in Py 3.13 (slated for removal in Py 3.15).
=> Base: Eliminate use of deprecated PyWeakref_GetObject

src/Gui/ViewProviderLink.cpp
Coverity issue 251377. Every other use of this method follows this idiom, update the last call to match. It is unlikely to matter since it is itself protected by a call to `isLinked()`, but for the sake of consistency I propose we update.
=> Gui: Check return value from getDetail()

src/Tools/freecad-thumbnailer.in, src/XDGData/CMakeLists.txt, src/XDGData/FreeCAD.thumbnailer, src/XDGData/FreeCAD.thumbnailer.in
Currently the file `src/XDGData/FreeCAD.thumbnailer` gets installed, but the associated `freecad-thumbnailer` script isn't. Install the script, too.
While here, have the paths to the default icon and `freecad-thumbnailer` script follow `${CMAKE_INSTALL_DATAROOTDIR}` and `${CMAKE_INSTALL_BINDIR}` respectively.
=> XDG: Configure and install thumbnailer

src/Mod/Draft/Draft.py, src/Mod/Draft/draftutils/utils.py
The same functionality is already implemented in src/Mod/Draft/draftutils/params.py from draftutils which solves the problem way more elegant. 
Only a small wrapper resides to preserve identical results.
the functions in question were solely used internally in the Draft module, namely to support the get/set_param doublette in src/Mod/Draft/draftutils/utils.py. I haven't found any call from extern to this function. 
If the API should be preserved I could add a commit that uses the mechanism in src/Mod/Draft/draftutils/param.py to provide the same functionality.
This Pull Request is a first preparation for an independent svg import update PR that will make svg import more robust and narrows the gap between svg representation and import result in FreeCAD.
=> Refactoring: remove get_paramType/getParamType from Draft Module and get rid of get/set_param doublette in Draft utils

src/Mod/AddonManager/AddonCatalog.py, src/Mod/AddonManager/AddonManagerTest/app/test_addoncatalog.py, src/Mod/AddonManager/CMakeLists.txt
This is the first step in addressing the most glaring problem in the Addon Manager: it has no provisions to deal with varying compatibility of addons with different versions of FreeCAD. The new class introduced here is intended to describe a new JSON file format that will replace (really, *augment*) the `.gitmodules` file.
Although the Addon Manager appears to use git submodules, in reality it does not. It uses the `.gitmodules` file to get a list of addons and their main branches, but it actually clones (or downloads) the latest version of the addon, *not* the submodule-specified hash. The use of the .gitmodules file is predominantly historical, though it does provide some small benefit in terms of the GitHub display of addons. The format of that file is not under our control, so in …
=> Addon Manager: Create AddonCatalog class

src/Mod/CAM/CAMTests/TestRefactoredMassoG3Post.py, src/Mod/CAM/Path/Post/Processor.py, src/Mod/CAM/Path/Post/scripts/refactored_centroid_post.py, src/Mod/CAM/Path/Post/scripts/refactored_grbl_post.py, src/Mod/CAM/Path/Post/scripts/refactored_linuxcnc_post.py, src/Mod/CAM/Path/Post/scripts/refactored_mach3_mach4_post.py, src/Mod/CAM/Path/Post/scripts/refactored_masso_g3_post.py, src/Mod/CAM/Path/Post/scripts/refactored_test_post.py, src/Mod/CAM/Path/Post/scripts/snapmaker_post.py
This PR fixes #19909.
Now that the refactored* postprocessors are much more "object-oriented", this PR takes advantage of inheritance to simplify the refactored* postprocessors even more.
It adds a new "UtilsPostBase.py" file which contains a "base" class for all of the refactored* postprocessors.
The refactored* postprocessors have been refactored to become even simpler than they were before.  
The refactored Masso G3 postprocessor now inherits from the refactored LinuxCNC postprocessor, which simplifies it down to not much more than the one variable setting that it needs.   It also makes it obvious that it depends on the refactored LinuxCNC postprocessor while making it easy to see just what the differences are.
This will simplify the maintenance of all of the refactored* postprocessors …
=> CAM:  Used inheritance to simplify the refactored postprocessors even more

src/Mod/PartDesign/Gui/TaskHoleParameters.cpp, src/Mod/PartDesign/Gui/TaskHoleParameters.h
Can't rely purely on `TaskHoleParameters::threadDiameterChanged` to update it since the signal is intentionally blocked while syncing state to GUI.
Closes #19744
=> PartDesign: Update counterbore min size in reaction to diameter changes

src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_Quadrangle_2D.cpp, src/App/PropertyContainer.cpp, src/Doc/CMakeLists.txt, src/Gui/Language/Translator.cpp, src/Mod/CAM/App/ParamsHelper.h, src/Mod/Fem/feminout/convert2TetGen.py, src/Mod/Fem/femsolver/fenics/fenics_tools.py, src/Mod/Fem/femsolver/mystran/solver.py, src/Mod/Fem/femsolver/z88/solver.py, src/Mod/Robot/App/kdl_cp/kdl.hpp
Closes https://github.com/FreeCAD/FreeCAD/issues/20366
All listed problems are solved with this PR with the exception of
```
Preprocessing freecad-main/src/3rdParty/json/single_include/nlohmann/json.hpp:24029: warning: unbalanced grouping commands
freecad-main/src/3rdParty/json/single_include/nlohmann/json.hpp:24176: warning: unbalanced grouping commands
```
This one is solved by using a configuration file that matches the Doxygen version, see https://github.com/FreeCAD/FreeCAD/issues/20365.
=> Fix doxygen structural warnings

cMake/FindEigen3.cmake, cMake/FreeCAD_Helpers/SetupEigen.cmake
ubuntu 22.04 use eigen 3.4. The minimum eigen version is raised to 3.4. Old cmake eigen  code is also removed.
=> Update Eigen Requirement

src/Base/Console.h, src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp, src/Mod/Inspection/Gui/ViewProviderInspection.cpp, src/Mod/Mesh/Gui/ViewProviderCurvature.cpp
Coverity flags destructors that call methods that can throw exceptions. In these three cases, while unlikely, it is at least sort of possible that is true. To resolve this without simply swallowing all of the exceptions invisibly, this PR introduces a new console output statement that is `noexcept` -- that method will `abort()` (via `assert`) in debug mode, but silently fail in release. This can be used to safely print to the console in a destructor.
=> Coverity fixes: three medium-priority destructor exceptions

cMake/FreeCAD_Helpers/InitializeFreeCADBuildOptions.cmake, package/ubuntu/install-apt-packages.sh
as mentioned in https://github.com/FreeCAD/FreeCAD/pull/20248#issuecomment-2735216005 ubuntu CI wasn't building with pcl, it seems that pcl is reasonably available nowadays so it should be ok to enable by default, this should also encourage downstream packagers to include this and they can always choose to disable this if it's not available in their platform.
=> Enable pcl by default on non windows systems

src/Mod/CAM/Path/Post/scripts/estlcam_post.py
Fix estlcam postprocessor file handling and return value. Depending on system (Win/MacOS) it was crashing on file write in different places.
Reported bug: https://github.com/FreeCAD/FreeCAD/issues/20323
=> [CAM] fix estlcam postprocessor file saving issues

src/Mod/Draft/draftguitools/gui_trackers.py
The checked state of the grid button was not updated when the grid was only displayed during Draft commands.
=> Draft: Update checked state of grid button when switching the grid

src/Gui/ViewProviderLink.cpp
Test file and report https://forum.freecad.org/viewtopic.php?p=818525#p818504
This PR fixes the current seg fault when deleting a Link Array introduced by https://github.com/FreeCAD/FreeCAD/commit/dcaddb94889c33932df7f82286f83fd07ddb65bf :
```
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/x86_64-linux-gnu/libc.so.6(+0x45330) [0x72b856e45330]
#1  0x72b859ef2214 in App::PropertyInteger::getValue() const from /home/username/freecad-daily-build/lib/libFreeCADApp.so+0x4
#2  0x72b85ae4f6d1 in Gui::ViewProviderLink::onDelete(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) from …
```
=> [Gui] Fix Seg Fault when deleting a Link Array

src/Mod/TechDraw/Gui/Widgets/CompassWidget.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/20412
by removing the `setKeyboardTracking` as it does not look like it's really of any use
Also removes custom formating of the spinbox. Better use same formating accross the application.
Also removes min/max: they bring nothing. Why prevent user from inputing 423 ? He may have done a calculation that gives him this amount and don't want to modulus it.
Add connection so that changing the spinbox value updates the widget directly. Note it does not update the view since that still needs you to click on update.
@kadet1090 @WandererFan
=> TechDraw: Section task: Fix spinbox

src/App/Application.cpp, src/App/PropertyUnits.cpp, src/App/PropertyUnits.h, src/Base/Unit.cpp, src/Base/Unit.h, src/Base/UnitsSchemaInternal.cpp, src/Base/UnitsSchemaMKS.cpp, src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/Gui/CMakeLists.txt, src/Mod/Fem/Gui/Command.cpp, src/Mod/Fem/Gui/Resources/Fem.qrc, src/Mod/Fem/Gui/Resources/icons/FEM_ConstraintElectricChargeDensity.svg, src/Mod/Fem/Gui/Resources/symbols/ConstraintElectricChargeDensity.iv, src/Mod/Fem/Gui/Resources/ui/ElectricChargeDensity.ui, src/Mod/Fem/Gui/Resources/ui/ElectrostaticPotential.ui, src/Mod/Fem/Gui/Workbench.cpp, src/Mod/Fem/ObjectsFem.py, src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femobjects/constraint_electricchargedensity.py, src/Mod/Fem/femobjects/constraint_electrostaticpotential.py, src/Mod/Fem/femsolver/elmer/equations/electrostatic_writer.py, src/Mod/Fem/femsolver/elmer/writer.py, src/Mod/Fem/femtaskpanels/task_constraint_electricchargedensity.py, src/Mod/Fem/femtaskpanels/task_constraint_electrostaticpotential.py, src/Mod/Fem/femtest/app/test_object.py, src/Mod/Fem/femviewprovider/view_constraint_electricchargedensity.py
Add object to define electric charge densities.
There are four modes to define densities: `Source`, `Interface`, `Total Interface`, `Total Source`.
* `Source` defines free volume charge density $\rho_{free}$ for assignment to solids in 3D problems and to surfaces in 2D problems.
* `Interface` defines free surface charge density $\sigma_{free}$ to be assigned to surfaces in 3D problems (edges in 2D problem) to define boundary conditions and charge at interfaces, allowing modeling of charged layers.
* `Total Interface` and `Total Source` are analogous to the previous modes but define the total charge distributed across the selected objects (the charge density is computed internally as $\frac{Total\ Charge}{Total\ Size}$). 
A symbol has been added for the electric charge density object. …
=> Fem: Add electric charge density object

src/Tools/freecad-thumbnailer.in
The newly added XDG installable script fails `brp-mangle-shebangs`. Fixing ambiguity by giving explicit python version, i.e. 3.
=> Fixing ambiguous python shebang in installed script freecad-thumbnailer [skip ci]

src/Base/swigpyrun.cpp, src/Mod/Part/App/GeometryMigrationExtension.cpp, src/Mod/Sketcher/App/ExternalGeometryExtension.cpp, src/Mod/Sketcher/App/SketchGeometryExtension.cpp, src/Mod/Sketcher/App/SolverGeometryExtension.cpp, src/Mod/Sketcher/Gui/ViewProviderSketchGeometryExtension.cpp
GNUC version is always greater than 4
=> Revomed old code " GNUC<8"

src/App/Application.cpp, src/Base/Interpreter.cpp, src/Base/Interpreter.h, src/Main/MainCmd.cpp, src/Main/MainGui.cpp
Replace it with a piece of code that replicates the functionality. Also eliminate the round-trip through `char *` that this function was using (the final variable is stored as a `std::string` anyway).
=> Base: Remove deprecated Py_GetPath call

src/Doc/mainpage.dox.in
For the web version, the main page has improved with more information about the organization with respect to the topics.  The most important topics are listed prominently on the main page as well.
Related to #20503.
=> [Doc] Improve the main page for WebDoc

src/Gui/PreferencePages/DlgSettingsLightSources.ui, src/Gui/View3DSettings.cpp, src/Gui/View3DSettings.h
As it seems the dialog saved settings in old place and because listener listened for the old place also the lights were updated only when applied through settings. Now it should be correct.
Fixes: #20159
=> Gui: Fix saving light sources

src/Mod/Fem/App/FemPostBranchFilter.h, src/Mod/Fem/App/FemPostPipeline.h
This unused variable is a little concerning because there's a pattern here that seems suspicious: the base class also has a private variable with this name and type, and a spot check indicates that other derived classes do as well. @marioalexis84 do you know what's going on here? This strikes me as an unusual design.
=> Fem: Remove unused variables in FemPost*

src/Mod/Draft/draftmake/make_dimension.py
When checking angles Dim Auto Flip Text did not consider that angles can be almost -180 degrees and should then be treated the same as 180 degree angles.
=> Draft: fix Dim Auto Flip Text angle checks

src/Mod/BIM/Resources/ui/dialogClassification.ui
The tooltip changed from:
_Apply the selected class to selected material_
to
_Apply the selected class to selected objects_
to better describe the functionality.
=> BIM: adjust BIM_Classification tooltip

src/Gui/InputField.cpp, src/Gui/InputField.h
fixes #19156
this is the difference between master and this PR:
here is an overlap of this PR comparing it to the fx icon in master:
=> Gui: fix Inputfield valid/invalid icon placement and size

src/Gui/3Dconnexion/navlib/NavlibNavigation.cpp, src/Gui/3Dconnexion/navlib/NavlibPivot.cpp
A few unused variables, an incorrectly-ordered initialization sequence, and a couple of cases where clang would prefer it be made clear that an initializer is initializing two separate sub-objects, rather than using a flat list.
=> Navlib: Eliminate compiler warnings

src/Mod/Material/App/MaterialLibrary.cpp
fixes #20005 :
Updated info.baseName() to info.fileName().remove(QStringLiteral(".FCMat"), Qt::CaseInsensitive) in MaterialLibrary.cpp to ensure that only the ".FCMat" extension is removed from the file name.
Previously, the implementation removed everything after the first dot, which could unintentionally modify file names when saving a material. This fix ensures that only the specific ".FCMat" extension is stripped while preserving the rest of the file name.
@davesrocketshop
=> Mod: Fix Material Library naming issue

src/Mod/Draft/importDXF.py, src/Mod/Import/App/dxf/ImpExpDxf.cpp, src/Mod/Import/App/dxf/ImpExpDxf.h, src/Mod/Import/App/dxf/dxf.cpp, src/Mod/Test/CMakeLists.txt, src/Mod/Test/Document.py, src/Mod/Test/TestData/DXFSample.dxf
Fixes Issue #20195
The non-GUI DXF importer was referring to properties on an object that had no such properties using `PyObject_SetAttrString` in the Python C API. This would result in an AttributeException posted to the python state.
This was happening for each new Layer found in the LAYER table of the DXF file.
The cause was confusion between Python `None` and a C null pointer when referring to the View object for the Layer (of which there is none in non-gui mode)
Depending on what else was in the DXF file, this error state might get wiped away (e.g. if there is a Draft object being created because `PyObject_CallMethod` seems to clear out pre-existing exceptions), might generate a confusing error message apparently from the lazy module loader (if subsequent DXF content did a …
=> Correct non-gui DXF C++ importer to not generate pending python exceptions

src/Mod/Fem/Gui/Resources/ui/Material.ui
Change the Expansion Reference Temperature label, so as not to crop the box quantities when trying to shrink the material panel.
A tooltip has been added to clarify that this is the expansion reference temperature.
Before:
After:
@FEA-eng
=> Fem: Simplify label in material task panel

src/Mod/CAM/Path/Op/Vcarve.py
Increase speed by about 30-50% when generating vcarve paths on complex faces.
https://forum.freecad.org/viewtopic.php?t=95532
https://forum.freecad.org/viewtopic.php?t=95535
As isInside() method in OCCT is slow, this patch moves colorExterior operation to be the last after all other edges are already colored as twin/collinear, etc - so we have much less vertices to check.
Also:
- migrate from isInside method to isPartOfDomain, which seems to be 20-30% faster
-  increase discretization deflection to 0.25 to significantly reduce number of edges (both in voronoi and resulting g-code). This still meets tolerances usually expected from vcarving so we should be fine (even increase it in the future).
- fix issues with restoring operation settings from saved files
=> [CAM] Improve Vcarve path generation speed on complex shapes

src/Mod/Fem/App/FemPostPipeline.cpp, src/Mod/Fem/App/FemPostPipeline.h, src/Mod/Fem/App/FemPostPipelinePy.xml, src/Mod/Fem/App/FemPostPipelinePyImp.cpp
Add function to rename pipeline fields,
Use case: Since it is now possible to load `.vtm` files created from `.frd` CalculiX result files, this function is useful for assigning a more meaningful name to fields:
`pipeline.renameArrays({"T":"Temperature", "FLUX": "Heat Flux"})`
@FEA-eng
=> Fem: Add method to rename pipeline VTK data arrays

src/Gui/OverlayManager.cpp
See https://github.com/FreeCAD/FreeCAD/pull/19929#issuecomment-2766802830
My last HiDPI Navicube fix introduced an issue with the Task Panel. This should correct that issue.
Because regular Qt widgets operate in logical pixels, but OpenGL operates using phsyical pixels, and because NaviCube is OpenGL, the Overlay Manager had some logic to convert it from device pixels to logical pixels in order to align the task panel above or below it.
But once I made NaviCube HiDPI aware, the size it returns is now in logical units, and so Overlay Manager no longer needs to scale it.
I also renamed the local variable to indicate it includes the padding.
=> fix: Task overlay HiDPI vertical alignment

src/Mod/Draft/draftviewproviders/view_dimension.py
Forum post (issue 3):
https://forum.freecad.org/viewtopic.php?t=95898#p819131
The `invert` value of dim arrows should always be `False` for the 1st and `True` for the 2nd. It should not depend on their X coords.
=> Draft: fix alignment of dim arrows

.github/workflows/sub_buildUbuntu.yml, .github/workflows/sub_buildWindows.yml
GitHub just changed CMake version on their CI that kabooms everyones CIs.
- https://github.com/actions/runner-images/issues/11926
Installing CMake with `apt install` doesn't override the path used in the CMake. So let's use https://github.com/marketplace/actions/actions-setup-cmake and fix the CI for now.
=> Build: force CMake to 3.31.6 version in CI

src/Gui/CommandFeat.cpp
Previously, the `StdCmdToggleFreeze` command only unfroze objects using `getInListRecursive()`, meaning that unfreezing an element would only affect itself or the elements that contained it.
This caused issues when using Toggle Freeze for a Body object, as it made it difficult to identify all frozen elements in a project, and the presence of frozen elements prevented the project from being saved.
Cause of the Bug
The unfreeze operation only considered outward dependencies, meaning that elements further down the hierarchy (inward dependencies) were not properly unfrozen.
Fix Implementation
Updated the `StdCmdToggleFreeze` command, so that objects are properly unfrozen when toggling freeze state.
Fix #18806
=> GUI: Fix Toggle Freeze Behavior

src/Gui/3Dconnexion/navlib/NavlibCmds.cpp
I have added a missing sanity check for the action pointer, which is used to invoke an application's command by 3Dconnexion device.
=> 3Dconnexion - Fixed crashing on some commands

src/Gui/BitmapFactory.cpp, src/Gui/BitmapFactory.h, src/Gui/CommandView.cpp, src/Gui/ToolHandler.cpp, src/Gui/Tree.cpp, src/Gui/ViewProviderLink.cpp, src/Mod/Sketcher/Gui/CommandConstraints.cpp, src/Mod/Sketcher/Gui/DrawSketchHandler.cpp, src/Mod/TechDraw/Gui/CommandCreateDims.cpp, src/Mod/TechDraw/Gui/QGVPage.cpp, src/Mod/TechDraw/Gui/QGVPage.h
Partially fixes https://github.com/FreeCAD/FreeCAD/issues/17602#issuecomment-2721420581
These arrow icons appear to be PNGs so this PR doesn't fix their scaling issue.
=> Gui: make BitmapFactory::pixmapFromSvg dpi aware

src/Gui/View3DPy.cpp
Under certain unusual circumstances getSceneGraph can be called when the scene is null, causing a native exception when the scene's reference count is incremented. This changes the code to return python None in this condition, allowing the calling code to handle the no-scene case itself.
Fixes #18679
At least it fixes the immediate cause of the issue. It does not address the whole issue of the use of the delay mechanism.
=> Check for a null scene object

src/Gui/Dialogs/DlgAddPropertyVarSet.cpp, src/Gui/Dialogs/DlgAddPropertyVarSet.h, src/Gui/propertyeditor/PropertyItem.cpp, src/Gui/propertyeditor/PropertyItem.h
Closes #15557
@FreeCAD/code-quality-working-group. I made a small refactor in `PropertyItem.cpp` in https://github.com/FreeCAD/FreeCAD/commit/4bbc59d3094a109b7fa8945375f98725675e841f for some code that puzzled me a bit when reading. What do you think of the way I return the column count in this enum?
=> [Core] Show units in the VarSet add property dialog

src/Gui/PreferencePages/DlgSettingsAdvanced.cpp
Deleted a line in DlgSettingsAdvanced.cpp that made the label move after selecting a animation curve type. Fixes #18376.
=> Preferences: Fixed a bug in 'Animation curve type' label position

CMakeLists.txt
Fixes #20673
The reason I make this change is because when I start to setup this project, I download the latest cmake 4.0 gui application. 
And then spend quite some time to find out why cmake configure always fail.
It turns out cmake 4.0 is not available for FreeCAD, since Compatibility with versions of CMake older than 3.5 is removed
=> Build: add maximum cmake compatible version

src/Doc/CMakeLists.txt
Closes https://github.com/FreeCAD/FreeCAD/issues/20478
I removed the commands that reconfigure cmake and delete the cache. Instead of regenerating it while ensuring that the GUI and FEM modules are on, I simply check for it and throw a fatal error.
I removed a comment that explained that the reconfigure is needed to have all source files generated from xml (and .pyi). I tried to make it such without doing a reconfigure but this makes a significant change to how dependencies are checked. I believe that if someone is changing xml files, then the best practice is to have a C++ build in parallel as well that updates the source files based on the xml files.
I've added a comment in the CMake file to explain this.
=> [Doc] Fix CMake issues for documentation

src/Mod/Surface/Gui/TaskGeomFillSurface.cpp, src/Mod/Surface/Gui/TaskSections.cpp
Small convenience change to "Fill boundary curves" and "Sections" surface tools. 
This PR make em behave same as Filling tool. After activating tool no need to click on "Add edge" button - you can select edges strait away. When open existing surface for edit - selection mode disabled as before the change, so it affect only initial tool activation.
=> Automatically switch to the edge selection mode when creating a surface

cMake/FreeCAD_Helpers/SetGlobalCompilerAndLinkerSettings.cmake
Corresponds to anything earlier than VS 2022. That is probably too conservative, it's not clear that this option was needed as far back as 2018. See https://forum.freecad.org/viewtopic.php?p=249569#p249569. This is necessary for a LibPack compiled with C++20 support.
=> CMake: Only set /NODEFAULTLIB for MSVC < 19.30

src/Base/PyObjectBase.h, src/Tools/bindings/templates/templateClassPyExport.py
Also cleans up Python includes in `PyObjectBase.h`.
=> Tools: Add PyCXX includes to generated Python binding files.

src/Gui/Selection/SelectionFilter.cpp, src/Gui/Selection/SelectionFilter.l, src/Gui/Selection/SelectionFilter.lex.cpp
So as title says, this renames generated lexerfiles from `SelectionFilter.l` to use the suffix `.lex.cpp`, instead of the `lex.SelectionFilter.c` naming.
=> Gui: Rename generated lexer files use .lex.cpp suffix .

src/Mod/Draft/DraftVecUtils.py
Now all vector related functions can be called with a dedicated precision parameter that controls the amount of fractional digits that are taken into account (in fact one can even state a negative precision which will result in rounding to digits BEFORE the comma).
The whole PR is backward compatible.
This is a second preparation PR for an independent svg import update PR that will make svg import more robust and narrow the gap between svg representation and import result in FreeCAD.
=> parametrize Draft vector utils precision

src/Mod/CAM/CAMTests/TestPathDressupArray.py, src/Mod/CAM/CMakeLists.txt, src/Mod/CAM/InitGui.py, src/Mod/CAM/Path/Dressup/Array.py, src/Mod/CAM/Path/Dressup/Base.py, src/Mod/CAM/Path/Dressup/Gui/Array.py, src/Mod/CAM/Path/GuiInit.py, src/Mod/CAM/Path/Tool/Bit.py
https://github.com/FreeCAD/FreeCAD/issues/20275
https://github.com/FreeCAD/FreeCAD/issues/20257
Creating an "Array" as a dressup to only allow having one base and avoiding conflicts with different tool and coolant settings. In the future all dressups should inherit from `Dressup.Base` class to properly expose settings to postprocessors. 
Old Array operation now shows a warning message about need to migrate and potential CNC errors when using it.
What is tested:
- array dressup itself
- nested array dressup properly exposing coolant mode and tool for postprocessor
=> [CAM] Replace Array operation with array dressup

src/Gui/QuantitySpinBox_p.h, src/Gui/SpinBox.cpp
margin refactoring aimed to fix #20680
margins are different depending on whether there is an icon or not
=> Gui: fix Quantity spinbox margin without an icon

src/Mod/CAM/Path/Post/scripts/KineticNCBeamicon2_post.py, src/Mod/CAM/Path/Post/scripts/dynapath_4060_post.py, src/Mod/CAM/Path/Post/scripts/dynapath_post.py, src/Mod/CAM/Path/Post/scripts/estlcam_post.py, src/Mod/CAM/Path/Post/scripts/fangling_post.py, src/Mod/CAM/Path/Post/scripts/fanuc_post.py, src/Mod/CAM/Path/Post/scripts/grbl_post.py, src/Mod/CAM/Path/Post/scripts/jtech_post.py, src/Mod/CAM/Path/Post/scripts/linuxcnc_post.py, src/Mod/CAM/Path/Post/scripts/mach3_mach4_post.py, src/Mod/CAM/Path/Post/scripts/marlin_post.py, src/Mod/CAM/Path/Post/scripts/rrf_post.py, src/Mod/CAM/Path/Post/scripts/smoothie_post.py, src/Mod/CAM/Path/Post/scripts/uccnc_post.py, src/Mod/CAM/Path/Post/scripts/wedm_post.py
This changes allow to use `\n` with `--postamble` and `--preamble` arguments with old postprocessors
Example:
`--postamble='M5\nG17 G54 G40 G49 G80 G90\nM2\nM0\nM47'`
Result gcode output before changes:
```
(begin postamble)
M5\nG17 G54 G40 G49 G80 G90\nM2\nM0\nM47
```
Result g-code output after changes:
```
(begin postamble)
M5
G17 G54 G40 G49 G80 G90
M2
M0
M47
```
https://forum.freecad.org/viewtopic.php?t=28579
https://forum.freecad.org/viewtopic.php?t=96157
https://forum.freecad.org/viewtopic.php?t=86950
=> CAM: Multiline POSTAMBLE and PREAMBLE arguments in old postprocessors

src/Mod/Import/App/SketchExportHelper.h, src/Mod/TechDraw/Gui/CommandHelpers.h
Before this commit, these doc strings were unassociated, which means that the can appear at random places.  They are now associated with their namespace an class.
The doc output before this commit where you can see that these doc strings were included in the namespace app documentation:
Related to #20503
=> [Doc] Fix unassociated doc strings

src/Gui/ViewProviderDragger.cpp, src/Gui/ViewProviderDragger.h, src/Mod/Part/Gui/ViewProviderExt.cpp, src/Mod/Part/Gui/ViewProviderExt.h, src/Mod/PartDesign/Gui/ViewProvider.cpp, src/Mod/PartDesign/Gui/ViewProviderBody.cpp
This PR fixes #19894:
1. Indicator is now visible only when object is visible
2. Indicator is now shown on top of the object
3. Indicator is not not available for features of body as body is one object.
=> Gui: Show Placement Indicator - several fixes

pixi.toml
pixi sets a variety of environment variables, which unfortunately includes compiler optimization flags. This PR unsets the compiler flags for parity with other environments.
A consequence of this is that debug builds are no longer build with high optimization, which is a desirable outcome.
=> pixi: Unset CFLAGS, CXXFLAGS, DEBUG_CFLAGS, and DEBUG_CXXFLAGS.

src/Mod/CAM/Path/Op/Gui/Array.py
Old Array feature is still very useful
With each change in the parameters of the old Array, a warning is displayed
This is a little annoys
It is enough that the warning is displayed when creating new Array
=> CAM: Less warning with new Array Dressup

src/Mod/BIM/bimcommands/BimLeader.py
If the BIM_Leader command was escaped without clicking a point, or after clicking only 1 point, a Draft_Wire object would still be created.
=> BIM: BIM_Leader would create a wire with fewer than 2 points

src/Gui/FreeCADGuiInit.py, src/Gui/Tree.cpp, src/Gui/ViewProvider.cpp, src/Gui/ViewProvider.h, src/Gui/ViewProvider.pyi, src/Gui/ViewProviderPyImp.cpp, src/Gui/ViewProviderVarSet.cpp, src/Mod/Fem/Gui/ViewProviderAnalysis.cpp, src/Mod/Fem/Gui/ViewProviderAnalysis.h, src/Mod/Fem/Gui/ViewProviderSolver.cpp, src/Mod/Fem/Gui/ViewProviderSolver.h, src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp, src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.h
Fixes https://github.com/FreeCAD/FreeCAD/issues/16816.
This is an alternative to https://github.com/FreeCAD/FreeCAD/pull/20573. Instead of basing toggling visibility on the DisplayMode, this PR extends the ViewProvider API to allow for viewproviders to disable toggling visibility.
This PR has a C++ and Python interface. Disabling toggling visibility in Python can be done in the following way:
```python
class ViewProviderMyObject(object):
def __init__(self, vobj):
vobj.ToggleVisibility = ToggleVisibilityMode.NoToggleVisibility
...
```
I believe the proposed interface is idiomatic for FreeCAD and all is implemented with enums for readability.
=> [Core] Allow setting visibility toggling in the ViewProvider

src/Mod/BIM/ArchComponent.py
Forum topic:
https://forum.freecad.org/viewtopic.php?t=95973
This was fixed by using `Part::FaceMakerCheese`.
=> BIM: HorizontalArea prop did not detect islands

src/App/Datums.cpp, src/App/Datums.h, src/App/GeoFeature.cpp, src/App/GeoFeature.h, src/Gui/View3DInventorViewer.cpp, src/Mod/Part/App/PartFeature.cpp, src/Mod/Part/App/PartFeature.h
As mentioned in #20088, this PR implements the use of the longest straight edge in a face for horizontal or vertical alignment when using the align to selection tool.
=> Use longest edge in face for horizontal/vertical alignment

src/Mod/BIM/ArchSchedule.py
Fixes #20723.
The clearAll method resets the column widths of the sheet. The code now stores the old widths and restores them after calling the method.
The old problem that the method would remove the custom property no longer occurs so that code was removed.
=> BIM: fix Arch_Schedule column width handling

src/Mod/Material/App/CMakeLists.txt, src/Mod/Material/App/ExternalManager.cpp, src/Mod/Material/App/ExternalManager.h, src/Mod/Material/App/Library.cpp, src/Mod/Material/App/Library.h, src/Mod/Material/App/MaterialAPI/MaterialManagerExternal.py, src/Mod/Material/App/MaterialManagerLocal.cpp
The ExternalManager class calls python functions in an external module to create, read, update, and delete material definitions. The API provided by the modules must conform to that defined in the MaterialManagerExternal.py file.
All communications with the external module is routed through this class.
=> Material: Interface with an external module

src/Base/Tools.h
Some compilers didn't optimize the toRadians properly (found by Jesse on discord) and due to a https://github.com/FreeCAD/FreeCAD/pull/20476#discussion_r2033239535 I dive down this rabbit hole.
This refactoring seem to work as far as I can see and stuff like `Base::toRadians(3.0)` _always_ compiles to a constant if a constant.
In addition to this I made sure `Base::toRadians(3)` doesn't compile as that would just return `0`. If this is something we want by design, it is possible to call it explicitly `Base::toRadians<int>(3)`.
Yet another thing I've done here is to make the `sgn` function without branches. I think it is quite readable too, but I'm open for discussion.
I also tighten up so the functions can't be called with the wrong types.
=> Tighten up types in Base/Tools.h math functions

CMakePresets.json, cMake/FreeCAD_Helpers/CompilerChecksAndSetups.cmake
When using Ninja build system, CMake can specify job pools for number of concurrent compilers and concurrent linkers.  This PR employes the heuristic of max number of compilers as available physical ram / 1 GiB and a single linker instance to prevent using excessive RAM.  Modern linkers are multithreaded and should not be run concurrently due to risk of resource exhaustion.
=> CMake: use job pools to restrict number of concurrent compilers and linkers.

src/Gui/InputField.cpp
as we talked in discord a while ago, only an invalid icon should be provided
this also should have better performance, and fixes the resizing and moving bug that @benj5378 shown, due to not having to re-set the pixmap
=> Gui: inputfield only show invalid states

src/Mod/Part/App/Geometry.cpp, src/Mod/Part/App/Geometry.h, src/Mod/Sketcher/App/SketchObject.cpp
Refactor `SketchObject::Fillet()` such that the complete arc creation is handled by Part::createFilletGeometry
Then SketchObject::Fillet just handles trimming and chamfer case. This enable creating fillet edges outside of the tool. And also make things a bit clearer.
Note I removed the many debugging logs of the fillet function. It made the function particularly hard to read. And we usually do not keep those around.
Aside from refactoring, I have added : 
```
if (fmod(fabs(range), 2 * M_PI) < Precision::Approximation()) {
return nullptr;
}
```
To fix https://github.com/FreeCAD/FreeCAD/issues/20587
=> Sketcher: Refactor SketchObject::Fillet()

src/Gui/Stylesheets/FreeCAD Dark.qss, src/Gui/Stylesheets/FreeCAD Light.qss
Fixes: https://github.com/FreeCAD/FreeCAD/issues/19372
Thanks to @MisterMakerNL for providing the original patch. I've modified it to apply to both Dark and Light themes, and I've added him as a co-author in the git commit to credit the original authorship.
=> Stylesheets: fix undo button arrows on Light and Dark themes

.github/workflows/sub_weeklyBuild.yml
This reverts commit 0747a4f4a167b1f54df0ec6694d45ce01e4e20fd.
The weekly builds will take place Monday evening at 18:42 PM UTC.  This is more than 3 hours after the weekly PR meeting to give opportunity to accept PRs before the weekly build.
=> Enable Weekly Builds

.github/workflows/actions/windows/getLibpack/action.yml
Changes from 3.1.0 are that all libraries are compiled with the C++20 standard enabled, and versions are updated as follows:
* boost 1.86.0 → 1.87.0
* harfbuzz 10.1.0 → 10.4.0
* ifcopenshell 0.8.0 → 0.8.1.post1
* libpng 1.6.40 → 1.6.47
* libE57Format added
* pcre2 10.44 → 10.45
* Python 3.12.7 → 3.12.10
* Qt and Pyside 6.8.1 → 6.8.3
* vtk 9.3.1 → 9.4.1 (Python support added)
* zlib 1.3 → 1.3.1
Note that after merging this may require the GitHub cache of the LibPack to be cleared in order to actually force download of the new one.
=> CI: Update to LibPack 3.1.1

src/Mod/CAM/Path/Post/scripts/KineticNCBeamicon2_post.py, src/Mod/CAM/Path/Post/scripts/centroid_post.py, src/Mod/CAM/Path/Post/scripts/dynapath_4060_post.py, src/Mod/CAM/Path/Post/scripts/dynapath_post.py, src/Mod/CAM/Path/Post/scripts/estlcam_post.py, src/Mod/CAM/Path/Post/scripts/fablin_post.py, src/Mod/CAM/Path/Post/scripts/fangling_post.py, src/Mod/CAM/Path/Post/scripts/fanuc_post.py, src/Mod/CAM/Path/Post/scripts/grbl_post.py, src/Mod/CAM/Path/Post/scripts/jtech_post.py, src/Mod/CAM/Path/Post/scripts/linuxcnc_post.py, src/Mod/CAM/Path/Post/scripts/mach3_mach4_post.py, src/Mod/CAM/Path/Post/scripts/marlin_post.py, src/Mod/CAM/Path/Post/scripts/rrf_post.py, src/Mod/CAM/Path/Post/scripts/smoothie_post.py, src/Mod/CAM/Path/Post/scripts/uccnc_post.py, src/Mod/CAM/Path/Post/scripts/wedm_post.py
Default **PREAMBLE** and **POSTAMBLE** arguments contains line break in the end
E.g. mach3 will pass last line if not finished by line break `\n`
So need to insert `\n` in the end of custom arguments
=> CAM: Fix postprocessors Help arguments --postamble and --preamble

src/Mod/PartDesign/App/Feature.cpp, src/Mod/PartDesign/App/Feature.h
Fix #20205
Keep trace of the original placement and restore it when the feature is unsuppressed.
=> PartDesign: Fix #20205 where Placement changes at Suppression

src/Mod/BIM/Resources/ui/dialogSetup.ui
This PR changes the default size of the BIM_Setup dialogue, so that all objects in the dialogue are fully visible.
Original width 588px:
New width 640px:
Note: I did not compile a test the changes myself
=> BIM change BIM_Setup dialogue default width

src/Gui/Dialogs/DlgActions.ui
I just added a _QSplitter_ and adjusted _sizePolicy_. There is little visual change on _KUbuntu 24_ (Qt 5.15), therefore, there is no need in a screenshot.
Closes #20821.
=> [GUI] Layout fixes in DlgActions.ui

src/App/Application.cpp
The Qt version gating for determining OS version for the About FreeCAD dialog resulted in a loss of information. This PR uses the legacy approach which retains the version information details.
Fixes #20836.
=> App: Use the legacy macOS version functionality for About FreeCAD dialog

src/Mod/BIM/ArchStructure.py, src/Mod/BIM/bimcommands/BimBeam.py, src/Mod/BIM/bimcommands/BimColumn.py, src/Mod/BIM/bimcommands/BimPanel.py, src/Mod/BIM/bimcommands/BimWall.py, src/Mod/Draft/DraftGui.py, src/Mod/Draft/draftguitools/gui_dimensions.py, src/Mod/Draft/draftutils/params.py
**Draft:**
Currently, if we select `"Continue"` mode for Draft, it retriggers the command for
almost every command but not for `Dimension` command. Also, if we select `"Continue"` in
one of the tools, it is cached globally for every single one of them instead of
being cached separately.
So, those series of patches introduce series of things:
- changes `Continue` option name to `Chained Mode`, but leaves
the option with new behavior for `Dimension` command.
- changes caching of this option, so every tool has it enabled
separately, i.e. we enable for `Dimension` - it's not enabled for Rectangle
- `Continue` option for `Dimension` now retriggers the command, whereas
for `Chained Mode` it keeps old behavior.
Short demo Draft:
https://github.com/user-attachments/assets/5daf9e5a-541d-44b5-bbfb-d …
=> Draft/BIM: Change Continue behavior and caching among commands

src/Gui/ViewProviderDragger.h
Removed the assignment to nullptr because we can't forward declare with that in the header. And boost::instrusive_ptr already does that internally in the default constructor.
=> Gui: forward declare SoTransformDragger in ViewProviderDragger.h

src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp, src/Mod/Sketcher/Gui/TaskSketcherElements.cpp, src/Mod/Sketcher/Gui/Utils.h
Currently if user selects a geometry element on sketch, listview is not scrolling to it.
So, this patch moves the previously added logic to constraints into a separate helper function call and calls it for Geometry Elements as well, resulting in scrolling in both lists - constraints and elements.
Demo:
https://github.com/user-attachments/assets/84b11d57-6070-4ef4-8559-549b33667063
Resolves: https://github.com/FreeCAD/FreeCAD/issues/20842
=> Sketcher: Auto-scroll to selected geometry elements

.github/workflows/actions/windows/getLibpack/action.yml
Corrects missing Python VTK module.
=> CI: Update to LibPack 3.1.1.2

src/Mod/Draft/CMakeLists.txt, src/Mod/Draft/InitGui.py, src/Mod/Draft/draftguitools/gui_arcs.py, src/Mod/Draft/draftguitools/gui_base.py, src/Mod/Draft/draftguitools/gui_circulararray.py, src/Mod/Draft/draftguitools/gui_orthoarray.py, src/Mod/Draft/draftguitools/gui_polararray.py, src/Mod/Draft/draftguitools/gui_shapestrings.py, src/Mod/Draft/drafttaskpanels/task_shapestring.py, src/Mod/Draft/draftutils/doc_observer.py
Related: #17952.
This PR introduces a document observer to close task panels on doc close.
For now it is for the Draft Workbench only. The BIM Workbench will be dealt with in a future PR.
The basic code is simple, but to make things works some additional things were addressed:
* gui_base.py: the GuiCommandBase class was enhanced to handle App.activeDraftCommand, self.doc, self.view and self.planetracker. Strictly speaking only the first 2 are required for this PR.
* gui_base.py: self.command_name was changed to self.featureName for compatibility with gui_base_original.py. Not required for this PR.
* gui_arcs.py, gui_circulararray.py, gui_polararray.py and gui_orthoarray.py: updated in relation to the GuiCommandBase class.
* gui_arcs.py Arc_3Points: The command now has a ui property and …
=> Draft: close task panels on doc close

src/Mod/CAM/CAMTests/TestPathAdaptive.py, src/Mod/CAM/Gui/Resources/panels/PageOpAdaptiveEdit.ui, src/Mod/CAM/Path/Op/Adaptive.py, src/Mod/CAM/Path/Op/Gui/Adaptive.py
This pull request implements four main things.
1. Intelligent 2.5D projection of the model and stock for all adaptive operations. This accounts for the model above the region being machined and prevents attempting to cut areas that are inaccessible due to overhanging geometry. So if you select the top opening of a pocket with steps in it, the steps will be respected instead of blindly projecting the contour to the selected depth. Similarly, it avoids cutting air where there's no stock to be machined away.
2. One-click "adaptive roughing" of the entire model. I currently have this set up to happen when no regions are selected 
for machining- this implies the user wants to rough the entire model. In this mode, the inside and outside regions to machine at every stepdown are calculated and …
=> [CAM] Adaptive roughing/overhang detection

src/Mod/CAM/InitGui.py
It is not convenient to add _Dressup_ tools to custom toolbar since all of them have one icon
Now there is a convenient access to these tools
=> CAM: Dressup combined menu in toolbar

src/Mod/PartDesign/App/FeatureHole.cpp, src/Mod/PartDesign/App/FeatureHole.h, src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
motivation: in spanish `Close` has been translated to `Cerrar` which is correct in some places, but not in this particular one and there it seems no way to untangle this translation
=> refactor: add disambiguation to clearance hole names and use names from the standard

src/Mod/Fem/femexamples/ccx_cantilever_prescribeddisplacement.py, src/Mod/Fem/femexamples/constraint_transform_beam_hinged.py, src/Mod/Fem/femexamples/rc_wall_2d.py, src/Mod/Fem/femtest/data/calculix/ccx_cantilever_prescribeddisplacement.inp, src/Mod/Fem/femtest/data/calculix/constraint_transform_beam_hinged.inp
ConstraintDisplacmentPrescribed → ConstraintDisplacementPrescribed  
FemConstraintDisplacment → FemConstraintDisplacement
This has not been tested. Unsure if this is a breaking change.
=> FEM: fix source typos

src/Mod/Sketcher/Gui/EditDatumDialog.cpp, src/Mod/Sketcher/Gui/EditDatumDialog.h, src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
Whenever a constraint name contains a space (for example), it becomes impossible to reference it by name in an expression.
I added checks to ensure that constraint names only contain alphanumericals and underscores so that they can always be used in expressions.
Fixes: https://github.com/FreeCAD/FreeCAD/issues/19767
=> Sketcher: Prevent bad constraint names

src/Mod/Fem/App/AppFemPy.cpp, src/Mod/Fem/App/FemSolverObject.cpp, src/Mod/Fem/App/FemSolverObject.h, src/Mod/Fem/App/FemVTKTools.cpp, src/Mod/Fem/App/FemVTKTools.h, src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/Gui/CMakeLists.txt, src/Mod/Fem/Gui/DlgSettingsFemCcx.ui, src/Mod/Fem/Gui/DlgSettingsFemCcxImp.cpp, src/Mod/Fem/Gui/Resources/ui/SolverCalculiX.ui, src/Mod/Fem/Gui/TaskPostBoxes.cpp, src/Mod/Fem/Gui/TaskPostDisplay.ui, src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp, src/Mod/Fem/Gui/ViewProviderFemPostObject.h, src/Mod/Fem/Gui/Workbench.cpp, src/Mod/Fem/ObjectsFem.py, src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femmesh/meshsetsgetter.py, src/Mod/Fem/femobjects/solver_calculix.py, src/Mod/Fem/femsolver/calculix/calculixtools.py, src/Mod/Fem/femtaskpanels/base_femlogtaskpanel.py, src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py, src/Mod/Fem/femtaskpanels/task_mesh_netgen.py, src/Mod/Fem/femtaskpanels/task_solver_calculix.py, src/Mod/Fem/femtest/app/test_object.py, src/Mod/Fem/femtest/app/test_open.py, src/Mod/Fem/femtest/gui/test_open.py, src/Mod/Fem/femviewprovider/view_solver_calculix.py
Fixes #20541.
This pull request contains a complete refactoring of the SolverCalculiX object, so that the result is imported as a pipeline from the VTK file generated from the .frd result file, without generating a `FemResultObject`.
A `Result as pipeline` option has now been added to the CalculiX preferences to select the result import mode. This allows the unified command `FEM_SolverCalculiX` to choose between the previous solver, which loads data as a `FemResultObject`, or the refactored object, which loads data as a `FemPostPipeline`.
This option is disabled by default.
The task panel of the new solver object behaves like the task panel for meshers (the base class for task panels has been renamed and adapted to be used by solvers as well).
Two properties have been added to solver …
=> Fem: SolverCalculiX refactor - Add option to import results as pipeline - Fixes #20541

src/Mod/Part/Gui/ViewProviderExt.cpp
Apparently the culprit for export color/transparency is this hardcoded line that sets transparency to 100%. I tested the change in my local build and it works, but to be honest I don't know if this affects other things.
ref: #20621 
@davesrocketshop
=> [Core] Fix Color transparency misinterpretation

src/App/CMakeLists.txt
build is failing with error
```
Building CXX object src/App/CMakeFiles/FreeCADApp.dir/Application.cpp.o
cd /builddir/build/BUILD/FreeCAD-rpkg.0.git.11300.b0f98acd-build/FreeCAD/build/src/App && /usr/bin/g++ -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DDOCDIR=\"/usr/share/doc/FreeCAD\" -DFMT_SHARED -DFreeCADApp_EXPORTS -DHAVE_CONFIG_H -DLIBRARYDIR=\"lib64\" -DPYCXX_6_2_COMPATIBILITY -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_XML_LIB -DRESOURCEDIR=\"/usr/share/FreeCAD\" -D_OCC64 -I/builddir/build/BUILD/FreeCAD-rpkg.0.git.11300.b0f98acd-build/FreeCAD/build/src/App/FreeCADApp_autog …
```
=> fix: fedora build

src/App/ExpressionParser.h, src/App/FeaturePython.h, src/App/Metadata.h, src/App/ProgramOptionsUtilities.h, src/App/Property.h, src/App/PropertyContainer.cpp, src/App/PropertyContainer.h, src/App/core-app.dox, src/Base/Persistence.h
This PR (mainly) improves the documentation of `App::PropertyContainer` and some related concepts in other files. A more high level description is provided as well, but this is not finished yet. To keep this PR somewhat smaller, I will submit a follow-up PR that documents more of the underlying logic for the property sytem.
=> [Doc] Improve documentation App::PropertyContainer

src/Gui/Tree.cpp
Doing "Add dependent objects to selection" in the context menu of an object that has cyclic dependencies triggered an infinite recursive loop.  This has been solved by using the function to get an outlist recursively.
Fixes https://github.com/FreeCAD/FreeCAD/issues/20859
=> [Gui] Fix "Select dependent objects" with cycles

src/Gui/Dialogs/DlgAddPropertyVarSet.cpp, src/Gui/propertyeditor/PropertyItem.cpp, src/Gui/propertyeditor/PropertyItem.h, src/Mod/Fem/Gui/PropertyFemMeshItem.cpp, src/Mod/Fem/Gui/PropertyFemMeshItem.h, src/Mod/Mesh/Gui/PropertyEditorMesh.cpp, src/Mod/Mesh/Gui/PropertyEditorMesh.h, src/Mod/Part/Gui/PropertyEnumAttacherItem.cpp, src/Mod/Part/Gui/PropertyEnumAttacherItem.h, src/Mod/Sketcher/Gui/PropertyConstraintListItem.cpp, src/Mod/Sketcher/Gui/PropertyConstraintListItem.h
Fixes #14632 
This PR contains two commits. The first ensures that editors can be created with a frame. The second makes use of that functionality in the Add Property VarSet dialog.
=> [Core] Add a frame for the value field in the Add Property dialog for VarSets.

src/Mod/TechDraw/Gui/QGISVGTemplate.cpp, src/Mod/TechDraw/Gui/QGISVGTemplate.h, src/Mod/TechDraw/Gui/QGITemplate.h
As the title says. I've noticed during reproducing of https://github.com/FreeCAD/FreeCAD/issues/18921, that
after in `PagePrinter::renderPage` we call `setTemplateMarkers`
twice, which results in deleting `childItems` allocated memory
(in `setTemplateMarkers`->`setMarkers`->`updateView`->`clearClickHandles`),
and then we are calling `setTemplateMarkers` (also in `PagePrinter::renderPage`) second time,
accessing `textFields` in `setMarkers` method, which still contain hanging pointers
from the previous deallocation. This results in segfaults as we iterate through `textFields`.
So, instead of keeping sychronization between childs of QGISVGTemplate
and textFields vector - this patch removes this variable at all and uses
childs directly to return text fields.
FYI @benj5378
=> TechDraw: Return text fields directly as childs of QGISVGTemplate

src/Gui/Dialogs/DlgAddPropertyVarSet.cpp, src/Gui/Dialogs/DlgAddPropertyVarSet.h
The value field would only appear if a name was provided resulting in a strange user experience.  This commit fixes this and simplifies the logic of the dialog. It is now possible to assign a value first and then come up with a name. 
This PR is a major rewrite of the dialog but it is now much simpler and robust. It is still necessary to create a property, but I now create a temporary property that I can delete after the PropertyItem has been created and the data of the editor has been set.
Closes #16189
Closes #17474
=> Gui: Fix value field for DlgAddPropertyVarSet

src/App/ElementMap.cpp
An operator precedence error in new sanity checking code within ElementMap::restore() causes <X>.Shape.Map.txt files with more than 2 element maps to be rejected as invalid.  This silently corrupts projects upon loading, potentially unrecoverably.
The preexisting code comment is still appropriate if ironic.
=> Core: Fix to sanity checking of ElementMap::restore()

.github/workflows/actions/windows/getLibpack/action.yml
Adds the `cxxstd=20` compiler option to `boost`, enabling compilation of #20449 when using the LibPack.
=> CI: Update to LibPack 3.1.1.3

cMake/FreeCadMacros.cmake, src/Base/CMakeLists.txt, src/Gui/CMakeLists.txt
It fixes an issue with source files generated from .pyi files not being regenerated which required cleaning build directory and in consequence full rebuild. One line with .pyi sources was missing for the Base module.
=> Base: Rebuild .cpp/.h files from .pyi on build

.github/pull_request_template.md
If PR consists of one commit with long description, github does put it as the first lines of PR so above our header, it can result in inconsistencies. The header is also needlessly duplicated in every PR preview, reducing its usability.
| ![image](https://github.com/user-attachments/assets/3d62a186-86e4-42e1-9df2-236c88168ce2) | ![image](https://github.com/user-attachments/assets/b0a018b1-f44d-4013-bc9e-066e3bac1d05) |
=> github: Remove description header

src/App/PropertyStandard.cpp
For some reason `PropertyEnumeration` in our type information system was said to be inherited from `App::PropertyInteger`, which is not the case. This commit fixes that mistake.
=> App: Fix inheritance information for PropertyEnumeration

src/Mod/BIM/bimcommands/BimBox.py, src/Mod/BIM/bimcommands/BimCurtainwall.py, src/Mod/BIM/bimcommands/BimImagePlane.py, src/Mod/BIM/bimcommands/BimPanel.py, src/Mod/BIM/bimcommands/BimProfile.py, src/Mod/BIM/bimcommands/BimTruss.py, src/Mod/BIM/bimcommands/BimWindow.py
The updated commands did not handle the 2 grid options ("always", "only during commands") correctly. The proposed code follows the example of BimWall.py and ArchStructure.py where this issue has already been addressed.
Additionally: updated workingplane code in BimBox.py
=> BIM: Improve grid handling for some commands

src/Mod/BIM/ArchComponent.py
If a window is a variant Link there will be a hidden source object in the document. That hidden object shares properties with the visible Link object. The Hosts property may be one of them, yet the hidden object should never be hosted.
Forum topics:
https://forum.freecad.org/viewtopic.php?p=817743#p817743 (sample file)
https://forum.freecad.org/viewtopic.php?t=96115 (code discussion)
To test the code:
1. Open the mentioned sample file.
2. Change the Hosts property of  Window001 to Wall.
3. Recompute.
=> BIM: Hidden objects used for variant Links should not be hosted

src/Gui/propertyeditor/PropertyModel.cpp
The index for `bottomRight` appears to have been incorrect for a long time, if the number of children was five then the index would be _0 to 4_ not _0 to 5_ as it is currently.
fixes #20940
_Has the PR been considered for backporting to the latest release branch?_ A backport PR will follow this PR immediately
=> [Gui] Fix warning in Qt6.9.0 due to invalid index

src/Mod/Assembly/App/BomObject.cpp, src/Mod/Assembly/App/BomObject.h, src/Mod/Assembly/CommandCreateBom.py
In Assembly Bill Of Materials (BOM), provide custom columns with the ability to automatically list the value of a given property. For this to work, the column must be named starting with a dot, followed by the name of the property
This is more or less an MVP to be reviewed, commented on, and possibly to make the minimum functionality available already. On a subsequent iteration, there should probably be a dialog for individually setting the column name and its associated property.
_Dynamic properties as a source_
_Column names with `.PropertyName` notation in the BOM settings_
_BOM output with autopopulated columns based on properties_
Fixes: https://github.com/FreeCAD/FreeCAD/issues/20730
- Unless the property names themselves are translated, the dot column names are not translatable
- …
=> Assembly: enable BOM columns to be autopopulated with given properties 

src/Base/AxisPyImp.cpp, src/Base/BaseClassPyImp.cpp, src/Base/BoundBoxPyImp.cpp, src/Base/CoordinateSystemPyImp.cpp, src/Base/MatrixPyImp.cpp, src/Base/PersistencePyImp.cpp, src/Base/PlacementPyImp.cpp, src/Base/PrecisionPyImp.cpp, src/Base/QuantityPyImp.cpp, src/Base/RotationPyImp.cpp, src/Base/TypePyImp.cpp, src/Base/UnitPyImp.cpp, src/Base/VectorPyImp.cpp
This PR comes to repair embarrassing flaw found after #20983 was merged.
- sort includes and consistently explain where the generated ones come from
- implicitly include needed ones
- explicit `Base` namespace-name is used randomly across PyImp sources and as they are `using namespace Base` remove it.
=> Base: PyImp cleanup

src/Gui/ApplicationPy.cpp, src/Gui/CMakeLists.txt, src/Gui/EditorView.cpp, src/Gui/MDIView.cpp, src/Gui/PreferencePages/DlgSettingsPDF.cpp, src/Gui/PreferencePages/DlgSettingsPDF.h, src/Gui/PreferencePages/DlgSettingsPDF.ui, src/Gui/View3DInventor.cpp, src/Gui/resource.cpp, src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp, src/Mod/TechDraw/Gui/PagePrinter.cpp
Currently, we only have hardcoded exporting to one pdf version, which leads to (as in one of the below issues) to problems, such as non-transparent layers, which are by default not supported in PDF/A-1b.
So, this patch adds an option to the user to select their preferred PDF version by introducing new dialog under Import-Export in Preferences, and allowing to update that version before exporting.
NOTE: I know the dialog is small, although I await your suggestions, maybe I can add some more options to it?
Also, I will probably try to get down to more PDF issues, so this is only basic sketch that will lead to more
improvements to this dialog.
Demo:
https://github.com/user-attachments/assets/4b92f079-a3a9-46b7-b322-6b6157702b09
Since the main problem in issue #18921 is the pdf version, this …
=> Core: Introduce PDF Import-Export dialog

src/Mod/Material/App/CMakeLists.txt, src/Mod/Material/App/ExternalManager.cpp, src/Mod/Material/App/Library.cpp, src/Mod/Material/App/Library.h, src/Mod/Material/App/MaterialManager.cpp, src/Mod/Material/App/ModelLibrary.cpp, src/Mod/Material/App/ModelLibrary.h, src/Mod/Material/App/ModelLoader.cpp, src/Mod/Material/App/ModelLoader.h, src/Mod/Material/App/ModelManager.cpp, src/Mod/Material/App/ModelManager.h, src/Mod/Material/App/ModelManagerExternal.cpp, src/Mod/Material/App/ModelManagerExternal.h, src/Mod/Material/App/ModelManagerLocal.cpp
Implement the ModelManagerExternal class for the external Materials interface.
This is part of the ongoing merges of code to support external material interfaces. In this PR the ModelManagerExternal class is implemented, along with changes to supporting classes required for this class.
=> Materials: Model Manager External Interface

src/Mod/CAM/Path/Op/Gui/Array.py
Associated with #20765
Added `self.FirstRun` to `onDocumentRestored()`
to resolve error `Array: 'ObjectArray' object has no attribute 'FirstRun'`
after reopen file
PS
It is worth considering the possibility of deleting a warning about the old implementation of **Array**
'Old' **Array** is useful and can not be replaced by **DressupArray**
=> CAM: Fix array warning 2

src/Mod/Draft/Resources/ui/TaskShapeString.ui, src/Mod/Draft/drafttaskpanels/task_shapestring.py
This PR adds the Global mode option to the ShapeString task panel.
Additionally:
* Rounding of coordinates caused by reading values from the task panel is avoided.
* Improved task panel layout: Height input above String input.
* Some code reformatting.
=> Draft: Add Global mode to ShapeString task panel

contrib/clion/pixi/pixi-default.bash
Previous version works on linux but not Mac. See also #19119
=> Amend Pixi environment bash script so that it also works on macOS

src/Mod/BIM/ArchCommands.py
Currently user has no possibility to insert Window to the host, if the host is a Curtain Wall.
Solution is simple - just populate the array of acceptable hosts that haven't been extended.
NOTE: Although this feels wrong, I've noted to change it as having some kind of an internal flag allowing for add/remove for the host, since extending this array looks like a really bad approach.
Demo:
https://github.com/user-attachments/assets/f87e07d5-b268-4567-8da7-df2a7ac49592
Resolves: https://github.com/FreeCAD/FreeCAD/issues/20920
=> BIM: Allow CurtainWall to have Window being assigned upon Remove/Add ops

src/Gui/propertyeditor/PropertyModel.cpp
This is a backport PR for #20990 as Arch based distros are already shipping 1.0 with Qt6.9.0
=> [1.0] [Gui] Fix warning in Qt6.9.0 due to invalid index

src/Gui/CMakeLists.txt, src/Gui/TaskTransform.cpp, src/Gui/TaskTransform.h, src/Gui/TaskTransform.ui, src/Gui/ViewProviderDragger.cpp, src/Gui/ViewProviderLink.cpp
This is a follow up PR of https://github.com/FreeCAD/FreeCAD/pull/20667. The SoFCCSysDragger class was renamed to SoTransformDragger so it also makes sense to rename TaskCSysDragger.
=> Gui: rename TaskCSysDragger to TaskTransformDragger

src/Mod/BIM/ArchPanel.py
Due to the use of an incorrect exponentiation operator the following exception was triggered when changing attributes of a wave profile:
TypeError: Unsupported operand type(s) for ^: 'float' and 'float'
fixes #21048
Before: Changing the attribute “wavelength” has no effect, but leads to the exception mentioned.
After: The change to the “Wavelength” attribute is displayed accordingly.
=> BIM: Fix Python syntax error

src/Mod/Material/App/AppMaterial.cpp, src/Mod/Material/App/CMakeLists.txt, src/Mod/Material/App/ExternalManager.cpp, src/Mod/Material/App/MaterialLibrary.cpp, src/Mod/Material/App/MaterialLibrary.h, src/Mod/Material/App/MaterialManager.cpp, src/Mod/Material/App/MaterialManager.h, src/Mod/Material/App/MaterialManagerExternal.cpp, src/Mod/Material/App/MaterialManagerExternal.h, src/Mod/Material/App/MaterialPyImp.cpp, src/Mod/Material/App/MaterialValue.h, src/Mod/Material/App/ModelLibrary.h, src/Mod/Material/App/ModelManagerLocal.cpp, src/Mod/Material/Gui/AppMatGui.cpp, src/Mod/Material/Gui/CMakeLists.txt, src/Mod/Material/Gui/Command.cpp, src/Mod/Material/Gui/DlgSettingsExternal.cpp, src/Mod/Material/Gui/DlgSettingsExternal.h, src/Mod/Material/Gui/DlgSettingsExternal.ui, src/Mod/Material/Gui/TaskMigrateExternal.cpp, src/Mod/Material/Gui/TaskMigrateExternal.h, src/Mod/Material/Gui/TaskMigrateExternal.ui, src/Mod/Material/materialtests/TestMaterialFilter.py
The final PR for the external module feature that allows materials to be stored in an external datastore, webservice, etc.
This includes the final material manager classes, and the UI support in the form of commands and preference pages.
Closes #10898
The only UI change is the addition of a preference page that allows the user to enable/disable external modules, as well as view some basic caching stats.
=> Materials: External Module Support

src/App/PropertyContainer.h, src/App/core-app.dox
This PR improves the App::PropertyContainer documentation. Both auxiliary classes/structs have been commented and the general property framework overview.
This is a follow up to https://github.com/FreeCAD/FreeCAD/pull/20781 and can be related to issue https://github.com/FreeCAD/FreeCAD/pull/20781.
=> Doc: Improve App::PropertyContainer documentation

src/Gui/CommandFeat.cpp
Updates the freeze/unfreeze behavior to remove the soft dependency on `PartDesign::Body`, which was previously used as a workaround due to unclear behavior expectations.
The new approach still improves the original logic by properly dependencies without referencing extension modules like `PartDesign`. 
Related to #20442
=> GUI: Refactor - removed soft dependency from freeze toggle

.github/workflows/sub_weeklyBuild.yml, .github/workflows/weekly-build-notes.md
Adds notes to the weekly releases with usage instructions.
The file `.github/workflows/weekly-build-notes.md` contains the build notes to be used for the weekly release.  We could add templating if we want to provide customization to each release.
Addresses request in https://github.com/FreeCAD/FreeCAD/pull/21053
N/A
=> CI: Add weekly build notes.

.github/workflows/sub_weeklyBuild.yml, package/rattler-build/linux/create_bundle.sh, package/rattler-build/osx/create_bundle.sh, package/rattler-build/windows/create_bundle.sh
Multiple locations for creating the GitHub release were in the codebase and run on build.  It was believed that the later invocations would fail (they do), but it was not anticipated that they had the side-effect of overwriting the release notes.
This PR unifies the creation of the release to the workflow's tagging job, reducing redundancy and providing a single source of truth for release creation.
None
N/A
=> CI: unify the location of GitHub release creation.

src/Gui/Camera.cpp, tests/CMakeLists.txt, tests/src/Gui/CMakeLists.txt, tests/src/Gui/Camera.cpp
It was not obvious how the hard coded values for the isometric, dimetric and trimetric values was calculated.
While there was comments about it, you had to verify manually that this was indeed correct.
This transforms the code in the comment to actual tests so it's easier to follow how and why the values looks like they do.
In addition to convert the manual verification to code, I've also verified with the CWG that the views looks as expected comparing with other CAD applications and noted this in the comments.
> [!NOTE]
> This adds `FreeCADGui` to the unit test suite in `tests/src/Gui/CMakeLists.txt`. This is needed to access functions and data from Gui library. It still runs in head less mode though.
=> Gui: Create tests for the hardcoded axonometric rotations

.github/workflows/sub_lint.yml, tools/lint/codespell.py
Adds missing command line arguments to `tools/lint/codespell.py` that were breaking the CI linting process.
https://github.com/FreeCAD/FreeCAD/issues/21121
N/A
=> CI: add missing command line args to codespell.py.

src/Mod/TechDraw/App/DrawComplexSection.cpp, src/Mod/TechDraw/App/DrawComplexSection.h, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/App/DrawViewPart.h, src/Mod/TechDraw/App/DrawViewSection.cpp, src/Mod/TechDraw/App/DrawViewSection.h, src/Mod/TechDraw/Gui/QGIViewPart.cpp, src/Mod/TechDraw/Gui/TaskComplexSection.cpp, src/Mod/TechDraw/Gui/TaskComplexSection.h
This PR is an attempt to fix issue #20155.  [Related forum post](https://forum.freecad.org/viewtopic.php?t=95606)
AFAICT, the issue is due to attempting to use an invalid coordinate system (gp_Ax2).  The error comes in a number of flavours:  a) XDirection = (0, 0, 0), b) Direction != SectionNormal and c) choosing an inauspicious SectionNormal vector.
a) is the likely cause of the crash, but I was not able to recreate the crash in a new file.
b) and c) are responsible for the mirroring and inversion errors.
=> [TD]Complex section crash (fix #20155)

cMake/FreeCAD_Helpers/SetGlobalCompilerAndLinkerSettings.cmake
Optimization of any level eliminates macros from the resulting binary.  As the FreeCAD typing system relies heavily on macros, this eliminates a vital source of debugging information.
This PR sets the optimization to `-O0` on debug builds to ensure that the macros are not optimized away.
https://github.com/FreeCAD/FreeCAD/pull/20780#issuecomment-2821239890
N/A
=> CMake: Do not optimize debug builds.

src/Mod/BIM/ArchStructure.py, src/Mod/BIM/InitGui.py, src/Mod/BIM/bimcommands/BimBox.py, src/Mod/BIM/bimcommands/BimCurtainwall.py, src/Mod/BIM/bimcommands/BimImagePlane.py, src/Mod/BIM/bimcommands/BimPanel.py, src/Mod/BIM/bimcommands/BimProfile.py, src/Mod/BIM/bimcommands/BimTruss.py, src/Mod/BIM/bimcommands/BimWall.py, src/Mod/BIM/bimcommands/BimWindow.py, src/Mod/Draft/draftguitools/gui_arcs.py, src/Mod/Draft/draftutils/doc_observer.py
Fixes #17952.
This PR is a continuation of #20719.
It mainly involves adding `self.doc`. This new attribute is then also used in the rest of the modified classes. In some cases code was slightly reordered for consistency.
The `_finish_command_on_doc_close` function has been modifief to also handle `Gui.Snapper.ui.escape` and the code in gui_arcs.py has been updated accordingly.
Additionally:
Removed the `done` and `spacedone` variables in BimWall.py by tweaking the code.
=> BIM: close task panels on doc close

src/Mod/BIM/InitGui.py
The BIM workbench is one of the most extensive workbenches in terms of the number of commands (buttons) on the toolbar area. This PR attempts to reduce the cognitive load and toolbar area real state usage by logically grouping commands with similar functionality (and icons) from one area: the annotation toolbar.
The additional benefit is that the user can also be better guided through the [typical document production workflow](https://yorik.uncreated.net/?blog%2F2024-011-freecad-news-25).
The <kbd>2D Drawing</kbd> (`BIM_DrawingView`) command is the default one on the group, so that in the typical workflow the dropdown does not need to be expanded.
Before:
After:
Typical document production workflow:
1. Section plane
2. 2D Drawing container with views from section plane. No need to expand …
=> BIM: group 2D view creation commands

src/Mod/Draft/Resources/ui/TaskShapeString.ui, src/Mod/Draft/draftobjects/shapestring.py, src/Mod/Draft/draftutils/params.py
* To help novice users supply an actual font file from the OS as the default for ShapeStringFontFile.
* The Draft code blocked the use of TTC font files. `Part.makeWireString()` can however handle them (although only the first font in the file can be used).
Additonally:
In a previous PR the bottom spacer was removed from the task panel. This PR brings it back as it is required in some cases. Without it  the "..." button of the file selector can become huge.
=> Draft: ShapeString: use an actual font file as default, allow TTC files

src/Mod/BIM/ArchSite.py
Currently, if user selects `Site` object in the Model tree, and hides it while having `Compass` property selected to `true` and then unhides it, the Compass is not appearing even though the property still remains to be true.
This is because for the `Compass` property itself and `Visibility` property we're using two different object types. For `Compass` property we're using View provider geometry object, whereas for the `Visibility` property we're using `Part::Feature` object. Since `Part::Feature` object doesn't have compass attribute and Compass directly under it, we're never hitting the logic to show the compass.
So, this patch just changes the object type that is being passed to `updateCompassVisibility` during change of `Visibility` property, to match the same object type passed …
=> BIM: Pass correct object for Compass while updating Visibility property

src/Base/BaseClass.h
Returns `nullptr` instead of `0` in Base.
None
N/A
=> Base: use nullptr instead of 0 in Base.

src/Gui/Navigation/NavigationStyle.cpp
Fix the warning
```
src/Gui/Navigation/NavigationStyle.cpp: In member function ‘virtual SbVec3f FCSphereSheetProjector::project(const SbVec2f&)’:
src/Gui/Navigation/NavigationStyle.cpp:125:33: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
125 |                 /* Do nothing */;
|                                 ^
src/Gui/Navigation/NavigationStyle.cpp:132:29: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
132 |             /* Do nothing */;
| 
```
While there also guard similar debug messages instead of commenting them out.
Fixes: #20535
=> Gui: fix warning in NavigationStyle

.github/workflows/sub_weeklyBuild.yml
CI: add missing token to fix weekly build.
Also adds the `on:workflow_dispatch` so that a weekly build may be manually triggered, as needed.
None, yet!
N/A
=> CI: add missing token to fix weekly build.

.gitmodules
This will point our existing submodule to the newly forked OndselSolver into FreeCAD/OndselSolver.
Syncing and update submodule should work, but if it doesn't then the following will reset it (+ remove all local changes):
```sh
git submodule deinit -f src/3rdParty/OndselSolver
git submodule update --init --recursive src/3rdParty/OndselSolver
```
=> Point OndselSolver to FreeCAD's organization's repo

package/rattler-build/osx/launcher/FreeCAD.cpp
macOS: Do not force LANG=UTF-8, which is not valid.  Assuming that the user's locale is a valid UTF-8 locale, this will remove warnings that Qt is not able to detect a valid locale and substituting a different one.
None.
None.
=> macOS: Do not force LANG=UTF-8, which is not valid.

package/rattler-build/osx/launcher/FreeCAD.cpp
macOS: Remove QT_MAC_WANTS_LAYER=1, which is no longer valid.
This removes annoying terminal messages that this setting is no longer supported.
None.
N/A
=> macOS: Remove QT_MAC_WANTS_LAYER=1, which is no longer valid.

src/Gui/StartupProcess.cpp
Gui: use 'C.UTF-8' for locale as Qt requires UTF-8.
* https://github.com/FreeCAD/FreeCAD/issues/15061
N/A
=> Gui: use 'C.UTF-8' for locale as Qt requires UTF-8.

src/Mod/CAM/PathSimulator/AppGL/MillSimulation.cpp
If set speed > 1 than right position of the thumb can be incorrect
Before:
https://github.com/user-attachments/assets/e3590f88-96d8-4dd3-ad59-d198ab871c4a
After:
https://github.com/user-attachments/assets/11f1357a-080a-459b-a73d-4d784f922227
=> CAM: Simulator Fix thumb right position with speed > 1

src/App/ObjectIdentifier.cpp, src/App/ObjectIdentifier.h, src/App/PropertyExpressionEngine.cpp, src/App/PropertyLinks.cpp, src/App/PropertyLinks.h
This PR improves the doc comments of App::ObjectIdentifier.
This PR consists of 2 commits. The first commit simply moves the documentation that was inside ObjectIdentifier.cpp to ObjectIdentifier.h. The second commit improves that documentation and adds more documentation.
=> Doc: Improve App::ObjectIdentifier documentation

package/rattler-build/linux/AppDir/AppRun
Linux: Force QT_QPA_PLATFORM=xcb for Wayland compatibility.
* https://github.com/FreeCAD/FreeCAD/issues/19352
* https://github.com/FreeCAD/FreeCAD/issues/20238
* https://github.com/FreeCAD/FreeCAD/issues/17982
* https://github.com/FreeCAD/FreeCAD/issues/18036
* https://github.com/FreeCAD/FreeCAD/issues/18242
* https://github.com/FreeCAD/FreeCAD/issues/8341
N/A
=> Linux: Force QT_QPA_PLATFORM=xcb for Wayland compat.

src/Mod/TechDraw/App/DrawView.cpp, src/Mod/TechDraw/App/DrawView.h, src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp, src/Mod/TechDraw/Gui/ViewProviderDrawingView.h
This PR implements a fix for issue #20768.
Views such as Symbols (or DraftView, BIMView,...) that do not display a shape (anything not derived from DrawViewPart) were not envisioned as having children.  This PR allows these views to claim their children.
=> [TD]Allow non-shape views to have children (#20768)

src/Mod/Fem/App/FemMesh.cpp, src/Mod/Fem/Gui/CMakeLists.txt, src/Mod/Fem/feminout/importCcxFrdResults.py, src/Mod/Fem/femtest/app/test_common.py, src/Mod/Fem/femtest/app/test_object.py
It seems I introduced a failing FEM test for the case  BUILD_FEM_VTK_PYTHON=OFF with my latest commits. This pull request fixes this.
Additionally:
- Fixes FEM build with BUILD_FEM_VTK=OFF
- Fixes FEM tests with BUILD_FEM_VTK=OFF
I tested all locally and should work fine now.
Thanks HighwayStar for reporting and helping with fixing it.
=> FEM: Fix test if VTK or VTK python is not available

.github/workflows/sub_weeklyBuild.yml
During the weekly build, a commit is added to remove updating the `Version.h` file and then generates the file based upon current commit information and uploads the aggregate FreeCAD source to the github release.  Later builds were based on clean checkouts, which does not include the `Version.h` and instead re-build it independently.
This PR uses the same source that was uploaded, including the generated `Version.h` artifact.
https://github.com/FreeCAD/FreeCAD/issues/20437
N/A
=> CI: use the exact same source for weekly builds.

package/rattler-build/scripts/make_version_file.py
This PR overrides the version suffix from `dev` to `-${BUILD_TAG}` for the weekly builds.  This will set the title bar to `FreeCAD 1.1.0-weekly-2025.05.12`, for example, which would permit easy distinguishing of the exact version being run.
https://github.com/FreeCAD/FreeCAD/issues/20437
N/A
=> CI: use the weekly build tag in title bar of main window.

src/Mod/CAM/Path/Op/Adaptive.py
Correctly handle regions contained entirely within the stock to avoid recutting them multiple times. Root cause was regions fully contained within the stock not being correctly computed as "the same", resulting in them being re-computed, along with the region at every lower depth, resulting in a factorial(ish) number of duplicate cuts.
Fixes #21086.
N/A
=> CAM: Fix adaptive repeating cuts excessively at various depths

src/Mod/CAM/Path/Post/scripts/opensbp_post.py
Updates the opensbp post to work with the current version of Processor.py.  In particular it now understands a file name of "-" and "does the right thing".
I manually tested that the opensbp postprocessor now creates reasonable output in a file instead of throwing an exception.
This fixes #20671.
=> CAM:  updated opensbp post to work with current Processor.py

src/Mod/CAM/Gui/Resources/Path.qrc, src/Mod/CAM/Gui/Resources/icons/CAM_StartPoint.svg, src/Mod/CAM/InitGui.py, src/Mod/CAM/Path/Op/Gui/Base.py
_PickStartPoint_ tool useful for select start point of the Path in 3dView
Get error while try to use it
<details>
<summary>Errors</summary>
```
21:39:29  Cannot find icon: CAM_StartPoint
21:39:29  Cannot find icon: Test1
21:39:32  Cannot find icon: CAM_StartPoint
21:39:38  Cannot find icon: CAM_StartPoint
21:39:46  <class 'IndexError'>
21:39:46  Traceback (most recent call last):
21:39:46    File "/home/user/freecad_build/FreeCAD/build/Mod/Draft/draftguitools/gui_snapper.py", line 1418, in click
accept()
~~~~~~^^
21:39:46    File "/home/user/freecad_build/FreeCAD/build/Mod/Draft/draftguitools/gui_snapper.py", line 1441, in accept
callback(self.pt, obj)
~~~~~~~~^^^^^^^^^^^^^^
21:39:46    File "/home/user/freecad_build/FreeCAD/build/Mod/CAM/Path/Op/Gui/Base.py", line 1309, in setpoint
obj = …
```
=> CAM: Fixes PickStartPoint

src/Mod/Draft/drafttests/test_airfoildat.py, src/Mod/Draft/drafttests/test_dwg.py, src/Mod/Draft/drafttests/test_dxf.py, src/Mod/Draft/drafttests/test_modification.py, src/Mod/Draft/drafttests/test_oca.py, src/Mod/Draft/drafttests/test_svg.py
The `aux.fake_function` is used in the Draft unit tests as a substitute for functions that, in most cases, do not yet exist. But in test_modification.py it would overwrite Draft.extrude leading to issues with BIM unit tests.
See:
https://github.com/FreeCAD/FreeCAD/pull/21134#issuecomment-2869178563
=> Draft: aux.fake_function should not overwrite functions

src/Mod/BIM/bimcommands/BimLibrary.py
Fixes #21179.
This PR uses the built-in solution to close the task panel.
I was not aware of this feature before. My 2 previous PRs related to the closing of task panels, #20719 and #21073, will (largely) have to be reverted/redone in favor of this solution.
=> BIM: close BIM_Library task panel on doc close

src/Mod/BIM/bimcommands/BimViews.py
Currently there's no option for selecting active working plane other than selecting `DoubleClickActivates` property on a BIM Level.
So, this patch adds an additional button for the submenu that BIM Views provides - to activate working plane of the selected item.
Demo:
https://github.com/user-attachments/assets/febb7ebb-02a8-46a1-82fe-842e2d23abb8
Resolves: https://github.com/FreeCAD/FreeCAD/issues/20887
=> BIM: Introduce Activate for BIM Views

src/Mod/CAM/Path/Op/Adaptive.py
Fixes #21192 
[Forum post](https://forum.freecad.org/viewtopic.php?t=96900) with lengthy description of the problem and illustrative screenshots
First commit fixes a UI bug that prevents the user from requesting helix angles between 0 and 1 degrees (important for cutting steel!)
Second commit deletes a buggy implementation (see issue, forum) of conical helices, and replaces it by adding cone support to the existing implementation of cylindrical helices.
Third commit adds a new feature to spiral out at the end of a conical helix to reach the full helix radius before handing off to the adaptive path which assumes that radius is already cleared.
=> [CAM] Adaptive helix fixes

src/Mod/TechDraw/Gui/ViewProviderHatch.cpp
Commit 1155f0d7 changed `UnitsApi::getDecimals()` from `int` to `size_t`, which changes the meaning of the negation since it is now unsigned. Cast it to an integer before the negation to restore the old behavior.
=> TD: Fix hatch size constraint

src/App/FreeCADInit.py
As part of the investigation into issues with the new Unit System in 1.1dev, I noticed that `MeterDecimal` was missing from the Scheme Enum in FreeCADInit.py - 1.0 branch.
=> [1.0] [App] add MeterDecimal to Unit Scheme Enum

src/Gui/Selection/SelectionFilter.cpp
`std::shared_ptr` default-initializes to `nullptr`, so there is no need to do it manually, and in the current code the initialization is in the wrong order (so generates a compiler warning).
=> Gui: Remove default init of shared_ptr

src/Gui/CommandView.cpp
Eliminate a compiler warning about an unused variable by making the variable more local to the point-of-use.
=> Gui: Make variable more local

src/Gui/Dialogs/DlgCustomizeSpaceball.cpp
There are multiple possible conversion paths for a QPixmap to QVariant, which results in a compiler warning. Explicitly specify the path we intend to silence the warning.
=> Gui: Manually specify correct QVariant conversion

package/rattler-build/osx/create_bundle.sh, package/rattler-build/scripts/fix_macos_lib_paths.py
Since macOS 15.4, these duplicate `RPATH`s cause a failure to load libraries, resulting in an inability to import `numpy`, breaking many workbenches and macros.
This PR removes the duplicate `RPATH`s that are sometimes installed by `pixi`.
https://github.com/FreeCAD/FreeCAD-Bundle/issues/375#issuecomment-2869174616
N/A
=> macOS: Remove duplicate RPATHs

.github/workflows/sub_weeklyBuild.yml
The source must be checked out prior to installing pixi.  This PR decompresses the release source tarball to be built prior to installing pixi.
None
N/A
=> CI: checkout source prior to installing pixi on weekly builds.

src/Gui/Inventor/SoFCPlacementIndicatorKit.h, src/Gui/SoDatumLabel.cpp, src/Gui/View3DInventorViewer.cpp
Our GUI code uses a mix of floats and doubles to represent floating point numbers, and in a few places interchanges them in a way that causes an invisible loss of precision, and a compiler warning about that loss. Change the double precision "default" values to float defaults, and use the appropriate value for pi.
This PR makes no attempt to "correct" any usage of float or double for the base values, but only updates the calculations of those values to use consistent precision. In particular, when the final value uses a double precision number, the values used in its calculation are retained in double precision. Only when the final value is a float are the values changed to floats.
In none of these cases is the use of double versus float expected to have any perceivable consequence.
=> Gui: Eliminate double->float truncations

.github/workflows/sub_weeklyBuild.yml, package/rattler-build/scripts/make_version_file.py
Fix weekly builds:
* Restore checking out the `git` source.  Attempts to build from the uploaded source tarball revealed a bug in `rattler-build` that prevented builds.
* Update the `Version.h` file with the tag information. 
* Apply patch to prevent CMake from overwriting `Version.h`
* Fix formatting of `make_version_file.py` 
None
N/A
=> CI: fix weekly builds.

src/Mod/CAM/Path/Main/Gui/Job.py
Due to a Qt signal setup, the clone object for Existing Stock stock type was recreated every time the Job properties dialog was opened (during the stock candidates list population).
This fix blocks the Qt signal from being emitted during the dropdown population.
- Fixes #20926
=> CAM: Fix Existing Stock from resetting

src/Mod/BIM/bimcommands/BimViews.py
Currently if user selects an item and does `Isolate` operation on it in BIM, everything is being hidden if the item was inside another container (like Building).
This is because we are prioritizing on hiding parents of current object if they are not the selected ones, which is causing the child of the parent to be hidden as well (duh).
So, this patch fixes isolate method to hide all other parents and their childs. If they are not a parent of our child under selection -> hide them and proceed further. If we are processing parent of our selection, just hide anything on current level that is not our selection while leaving parent intact.
Demo:
https://github.com/user-attachments/assets/2154df5b-b386-4b2d-86fe-e65c599abfb3
FYI: @semhustej @furgo16 
Resolves: …
=> BIM: Hide all objects that aren't selected during Isolate

src/Mod/BIM/ArchWindow.py, src/Mod/BIM/ArchWindowPresets.py, src/Mod/BIM/bimcommands/BimWindow.py
User has no possibility to change Sill parameter upon adding Window, it is only possible while creating Window for the first time.
So this patch adds this parameter, and changing it moves the *BASE* coordinate of the object in Z direction.
Demo:
https://github.com/user-attachments/assets/50340633-b829-4230-bb4e-371241b5426f
Resolves: https://github.com/FreeCAD/FreeCAD/issues/20882
=> BIM: Allow changing Sill parameter in Properties for Window

src/Mod/Draft/DraftGui.py, src/Mod/Draft/draftguitools/gui_dimensions.py
As the title says - currently, if user deselects Chained Mode, they can't exit it without using ESC key for example, as the old behavior of ContinueMode is kept under it.
So, this patch finishes the command if user has deselected it, at the same time finishing previous chain.
FYI @semhustej. Is that what you meant?
Demo:
https://github.com/user-attachments/assets/54b30923-edfe-413d-b45e-e32002649d46
=> Draft: Finish command if user deselected Chained Mode

tools/lint/generic_checks.py
This got broken due to applying some review suggestions without proper testing.
This reverts commit 5e72c0afe508a698cadb209af190102b12774005.
Closes https://github.com/FreeCAD/FreeCAD/issues/21231.
=> Fix regressions in CI linting generic checks.

package/fedora/freecad.spec
[![Copr build status](https://copr.fedorainfracloud.org/coprs/filippor/freecad/package/freecad/status_image/last_build.png)](https://copr.fedorainfracloud.org/coprs/filippor/freecad/package/freecad/)
the build is completed successfully I don 't know wy the badge remain processing
this PR only change the way to package and retrieve the sources in the rpm
rlated to 
PR  #20857  #20300 #20810
=> Fix copr use standard macro to packages sources

src/Mod/Fem/Gui/Resources/ui/TaskPostGlyph.ui, src/Mod/Fem/femobjects/post_glyphfilter.py
Fixes some Glyph filter typos, including one task panel option and swapped tooltips.
@ickby FYI
=> FEM: Fix Glyph filter typos

src/Gui/SpinBox.cpp
`std::numeric_limits<int>::max()` can losslessly be cast to an `unsigned int` to silence the compiler warning about comparison of signed to unsigned.
=> Gui: Eliminate signed-to-unsigned comparison

src/Mod/Material/App/MaterialLoader.cpp, src/Mod/Material/Gui/MaterialDelegate.cpp
Updated error messages no longer refer to the exception object, resulting in compiler warnings.
=> Materials: Clean up unused variables

src/Gui/PreferencePages/DlgSettingsPDF.ui, src/Gui/TaskView/TaskAppearance.ui, src/Mod/BIM/Resources/ui/preferences-arch.ui, src/Mod/BIM/Resources/ui/preferences-archdefaults.ui, src/Mod/BIM/Resources/ui/preferences-dae.ui, src/Mod/BIM/Resources/ui/preferences-ifc-export.ui, src/Mod/BIM/Resources/ui/preferences-ifc.ui, src/Mod/BIM/Resources/ui/preferences-sh3d-import.ui, src/Mod/CAM/Gui/Resources/preferences/PathJob.ui, src/Mod/Draft/Resources/ui/preferences-draft.ui, src/Mod/Draft/Resources/ui/preferences-draftinterface.ui, src/Mod/Draft/Resources/ui/preferences-draftsnap.ui, src/Mod/Draft/Resources/ui/preferences-drafttexts.ui, src/Mod/Draft/Resources/ui/preferences-draftvisual.ui, src/Mod/Draft/Resources/ui/preferences-dwg.ui, src/Mod/Draft/Resources/ui/preferences-dxf.ui, src/Mod/Draft/Resources/ui/preferences-oca.ui, src/Mod/Draft/Resources/ui/preferences-svg.ui, src/Mod/Import/Resources/ui/preferences-import.ui, src/Mod/OpenSCAD/Resources/ui/openscadprefs-base.ui, src/Mod/Part/Gui/DlgBlock.ui
This function dates back to Qt3, and was removed in Qt4. Modern Qt no longer uses this ui file entry, and in some circumstances the uic complains about its presence.
=> UI: Remove qPixmapFromMimeSource pixmap function

src/Base/PreCompiled.h, src/Base/XMLTools.cpp, src/Base/XMLTools.h
Xerces default memory manager is deleted before destructing static local variable and segfault.
This bug is introduced in #18594, reported at #19632.
closes: #19632
=> Base: Fixed segfault on destructing cached string

src/Mod/PartDesign/Gui/TaskHoleParameters.ui
move the profile types to the top and keep it aligned
the bottom of the group is intended for thread options, so profile types was out of place
changed the label to be able to ellipsize since it can be long in translations
=> PD: Move hole base profiles types to the top

src/Mod/Draft/draftviewproviders/view_wpproxy.py
=> Draft: use different color for WPProxy to avoid BIM dependency

src/App/Document.cpp
Revert change from 9d6f1ad37c1d ("App: Align Document to best practices")
Fixes #21414
=> App: fix exported object dynamic property type identifier

src/Mod/TechDraw/App/Geometry.cpp
This exception clause does not ever refer to the exception object, resulting in a compiler warning since the object was given a name. Remove the name to silence the warning. An alternative would be to print the text of the exception message as part of the error. It's also not clear to me why this error message is a `message` and not an `error`, @WandererFan.
=> TD: Remove unused variable

src/Mod/TechDraw/Gui/CommandAnnotate.cpp
Unless I am mistaken, the code of the `TechDraw_DecorateLine` activated was wrong.
First it used `selection[0].getObject()` as base object then browsed the rest of the selection for other drawviewparts. Which makes no sense. Because why making sure the first is a DVP if after that you browse the rest of the selection and select the last one?
I guess the original intent was to browse all the selection to find at least one drawviewpart. Which makes more sense.
=> TechDraw: decorateLine fix

src/Mod/CAM/Path/Dressup/Array.py
Array dressups before commit 24c32c9 did have their own CoolantMode and ToolControler property. When loading a file that contains such an Array dressup we need to remove those properties. Otherwise if the user changes the CoolantMode or ToolController of the base operation, the one that is still specified in the Array dressup might be used. Even worse, if the Array dressup was applied to another dressup, those two properties might be empty resulting in no tool change being emitted. Even if those files might be rare since the Array dressup didn't exist for long before the mentioned commit, we should still check for it because it can crash peoples machines and ruin their parts... ask me how I know... 🤦
=> CAM: fix loading Array dressup with unused properties

src/Mod/BIM/bimcommands/BimClassification.py
As the title says, if user selects `OK` button and has no Classification selected (which can happen only if the list is empty I think), then they get a traceback since we're trying to access list of selections directly.
So this patch adds a small QMessageBox that will remind the user to populate `Classification` directory and exits safely instead of throwing a traceback.
Demo: 
https://github.com/user-attachments/assets/382ba09f-9bd4-44ce-a192-4be8d2a3869d
@semhustej Maybe a message box is a bad choice here, let me know what you think. I've found about this traceback accidentally when playing with IFC features.
=> BIM: Avoid traceback if there is no Classification selected

src/App/Document.cpp, src/App/Document.h, src/App/private/DocumentP.h, src/Gui/Document.cpp, src/Gui/Document.h
Historically, `App::Document::recompute()` ran entirely on the main (GUI) thread and directly emitted `signalBeforeRecompute()`.
* Add-ons like Assembly3 depend on that signal for setup/teardown hooks before any recompute work begins.
* After offloading `recompute()` into a background worker thread to keep the UI responsive, calling `signalBeforeRecompute()` directly from the worker would break thread-affinity rules and silently break compatibility with those add-ons.
**Solution**
1. Introduce a precompute hook (`PreRecomputeHook`) in `App::Document`:
* It is `std::function<void()>` that, if set, is invoked at the very start of `recompute()`.
2. Wire up the hook in `Gui::Document`:
* In the GUI wrapper’s constructor, install a hook that calls `callSignalBeforeRecompute()`.
* …
=> App: Invoke `signalBeforeRecompute()` on the GUI thread

src/Mod/CAM/CAMTests/TestRefactoredTestPost.py, src/Mod/CAM/Path/Post/Command.py, src/Mod/CAM/Path/Post/UtilsArguments.py, src/Mod/CAM/Path/Post/UtilsExport.py, src/Mod/CAM/Path/Post/UtilsParse.py, src/Mod/CAM/Path/Post/scripts/snapmaker_post.py
Adds command line arguments for coolant, machine specific commands, and end-of-line-characters to the refactored* code base.  Those capabilities were already present but didn't have the ability to use command line arguments.
Also includes corresponding tests.
When I was adding the command line arguments for end-of-line-characters I realized the existing capability had been broken around the 0.21 time frame when we changed where the gcode file was written out from the postprocessor to higher level code (Command.py).  I didn't notice because we didn't have any tests for this capability :-(  With this PR we will have tests :-)
To fix this I had to change the code to stop putting newlines at the ends of lines in many places and add the appropriate end-of-line characters just before returning …
=> CAM:  added three command line arguments, with tests

src/Base/UnitsSchemasData.h
Several units were merged out of order. This corrects the ordering.
=> Core: Correct unit merge errors

src/Gui/OverlayWidgets.cpp, src/Gui/QSint/actionpanel/actionbox.cpp, src/Gui/QSint/actionpanel/actiongroup.cpp, src/Gui/QSint/actionpanel/actiongroup.h, src/Gui/QSint/actionpanel/actionlabel.cpp, src/Gui/QSint/actionpanel/actionlabel.h, src/Gui/QSint/actionpanel/actionpanel.cpp, src/Gui/QSint/actionpanel/actionpanelscheme.cpp, src/Gui/QSint/actionpanel/actionpanelscheme.h, src/Gui/QSint/actionpanel/taskgroup_p.cpp, src/Gui/QSint/actionpanel/taskgroup_p.h, src/Gui/QSint/actionpanel/taskheader_p.cpp, src/Gui/Stylesheets/overlay/Dark Theme + Dark Background.qss, src/Gui/Stylesheets/overlay/Dark Theme + Light Background.qss, src/Gui/Stylesheets/overlay/Light Theme + Dark Background.qss, src/Gui/Stylesheets/overlay/Light Theme + Light Background.qss
This fixes the taskpanel issues to transition from light to dark when the system changes
fixes the double icon mentioned in #21036
fixes #20585
should fix the taskpanel part of #15346
[Videocaptura de pantalla_20250511_162917.webm](https://github.com/user-attachments/assets/c3177404-9066-40a8-8450-b76a4d28f8b1)
=> Gui: fix light/dark switch when on classic

src/Mod/Sketcher/App/SketchObject.cpp
=> Sketcher: remove surplus push_back to shapes (fixes #21499)

src/Mod/Draft/draftobjects/shapestring.py
Fixes #21501.
For some fonts `Part.makeWireString()` returns characters that are much smaller than the given height. This would lead to a false positive for the 'sticky font' check (which checks the area of the "L" character).
=> Draft: ShapeString fix sticky font check for small character

src/Mod/BIM/bimcommands/BimViews.py, src/Mod/Help/Help.py
Currently, for both Help and BIM Views panels we can get a traceback about incorrect casting if we move the panel.
This is because the QFlag of DockWidgetArea that is being passed, as it is not able to be parsed down to an int. Most probably some historical change either in Qt or FC.
This error also caused to not write current BIM Views/Help panel setup to config, resulting in the position being resetted every run.
Resolves: https://github.com/FreeCAD/FreeCAD/issues/21368
=> BIM/Help: Access DockWidgetArea QFlag enum correctly

src/Mod/BIM/bimcommands/BimViews.py
This patch introduces a few things:
- changes Activate button to be first in the list
- puts it in bold text, also adding (Default) to point it is default action
- removes all of the hiding logic upon double click and leaving Activate by default to be called after double-clicking a BuildingPart
Note that this counter-acts Yorik's decision to change Visibility of objects upon double click, as per: https://github.com/FreeCAD/FreeCAD/pull/15836, and it looks like a non-accidental decision
Demo: 
https://github.com/user-attachments/assets/71e0af37-a924-4273-815e-5c303cc7ecf0
Resolves: https://github.com/FreeCAD/FreeCAD/issues/21153
=> BIM: Additional improvements for Activate button in BIM Views

src/Mod/BIM/importers/exportIFC.py, src/Mod/BIM/importers/exportIFCHelper.py
Currently users by default have transparent window frames and doors.
Turns out that at some point there was a switch from RGBT to RGBA, which means last transparency element differs in the range of transparency that it specifies (RGBT, where 1 - fully visible, RGBA where 1 - fully transparent). As the changed happened, all of the windows and door became transparent.
This patch changes that, from RGBT to RGBA so we will map transparency properly, as well as adding a possibility to set transparency through material.
A bit lengthy demo but it shows a couple of scenarios:
https://github.com/user-attachments/assets/0df7475d-ee9c-4273-a6d3-3b111343c507
Resolves: https://github.com/FreeCAD/FreeCAD/issues/19138
=> BIM: Change from RGBT to RGBA for IFC

src/Mod/Draft/draftguitools/gui_arcs.py
This PR corrects a minor typo in the Draft workbench input hint for arc creation.
- Replaces "staring angle" with "starting angle" for clarity
- No behavioral or functional changes
N/A — this is a minor typo fix with no associated issue.
This is the input hint text displayed when drawing an arc in the Draft workbench.
N/A — the change affects a text string, not the GUI layout.
Before:
After:
---
Thanks to @hyarion for the related Draft hint logic — and helping me get started with my first contributions.
=> Draft: Fix typo in arc input hint ("staring" → "starting")

src/Mod/Draft/draftguitools/gui_arcs.py, src/Mod/Draft/draftguitools/gui_beziers.py, src/Mod/Draft/draftguitools/gui_circles.py, src/Mod/Draft/draftguitools/gui_dimensions.py, src/Mod/Draft/draftguitools/gui_ellipses.py, src/Mod/Draft/draftguitools/gui_lines.py, src/Mod/Draft/draftguitools/gui_move.py, src/Mod/Draft/draftguitools/gui_offset.py, src/Mod/Draft/draftguitools/gui_polygons.py, src/Mod/Draft/draftguitools/gui_rectangles.py, src/Mod/Draft/draftguitools/gui_rotate.py, src/Mod/Draft/draftguitools/gui_scale.py, src/Mod/Draft/draftguitools/gui_splines.py, src/Mod/Draft/draftguitools/gui_texts.py, src/Mod/Draft/draftguitools/gui_trimex.py
The 'CTRL to snap' option is not the default, it should therefore not be included in the tooltips.
Additionally:
* Some obsolete info was removed.
* Some minor improvements,
=> Draft: remove 'CTRL to snap' from tooltips

src/Mod/TechDraw/Gui/QGIDatumLabel.cpp, src/Mod/TechDraw/Gui/QGIDatumLabel.h, src/Mod/TechDraw/Gui/QGIViewDimension.cpp
- Positioning was calculated using `boundingRect` while `transformOriginPoint` was set according to `tightBoundingRect`, causing mismatch when `QGIDatumLabel` contains more than text (eg. shapes around text). Now `transformOriginPoint` and positioning calculated according to `tightBoundingRect`, and setting `transformOriginPoint` of `QGIDatumLabel` are handled by itself. This fixes an issue where the gap between dimension lines and text varied depending on dimension's angle.
- `m_lineWidth` was set in multiple locations, causing confusion and bug introduction
- If `X` or `Y` property changed, the remaining changed properties were not handled due to using `if else` rather than `if` for property change checking. This became an issue due the above mentioned simplification of `m_lineWidth` …
=> TechDraw: fix positioning and state handling of dimension

src/Mod/CAM/PathSimulator/AppGL/SimDisplay.cpp
Add the `F` suffix to ensure that constants are using single-precision rather than double-precision values on initialization (since we are initializing floats). Eliminates compiler warning about truncation.
=> CAM: Ensure float constants are single-precision

src/Gui/StartupProcess.cpp
setting the qstyle to fusion fixes various margins and issues across OSs, it seems that the Basic Style of Qt6 is not good enough
here is a comparison under Debian Trixie using Qt6
| Basic | Fusion |
|-|-|
| ![Basic_style](https://github.com/user-attachments/assets/39ff837c-eeb8-4e4c-81a9-e013bc7296a8) | ![Fusion_style](https://github.com/user-attachments/assets/0fda6e11-1a1b-4d29-b34c-9bfa6bf280b1) |
this should fix #21262
=> Gui: Set QStyle to Fusion if not set

src/Mod/CAM/CAMTests/TestRefactoredTestPost.py, src/Mod/CAM/Path/Op/Gui/Custom.py, src/Mod/CAM/Path/Post/UtilsArguments.py, src/Mod/CAM/Path/Post/UtilsParse.py, src/Mod/CAM/Path/Post/scripts/KineticNCBeamicon2_post.py, src/Mod/CAM/Path/Post/scripts/centroid_post.py, src/Mod/CAM/Path/Post/scripts/dynapath_4060_post.py, src/Mod/CAM/Path/Post/scripts/fablin_post.py, src/Mod/CAM/Path/Post/scripts/fangling_post.py, src/Mod/CAM/Path/Post/scripts/fanuc_post.py, src/Mod/CAM/Path/Post/scripts/jtech_post.py, src/Mod/CAM/Path/Post/scripts/linuxcnc_post.py, src/Mod/CAM/Path/Post/scripts/mach3_mach4_post.py, src/Mod/CAM/Path/Post/scripts/opensbp_post.py, src/Mod/CAM/Path/Post/scripts/philips_post.py, src/Mod/CAM/Path/Post/scripts/uccnc_post.py, src/Mod/CAM/Path/Post/scripts/wedm_post.py
When having empty lines in the Custom operation, some postprocessors crash. E.g. refactored postprocessors in UtilsParse.py on line 723 (`if command[0] == "(":`) since `command` is empty. Afacit FreeCAD never produces empty lines on its own so I fixed it in Custom.
(Side note: it works if you save and load a file without recomputing since `Toolpath::RestoreDocFile` replaces newlines anyway).
=> CAM: allow empty lines in Custom operation

src/Mod/Draft/DraftGui.py
This PR fixes a V1.1 regression.
The default for the last point should be the origin of the working plane if Global mode is off.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=97452
=> Draft: DraftGui.py correct handling of last point

src/Mod/BIM/Arch.py
non-trivial typo that would affect translations
=> BIM: fix typo in Arch.py

src/Mod/CAM/libarea/clipper.cpp
This file was encoded in ISO-8859-1, but contained characters that were illegal in that encoding (superscripts). Convert to UTF-8.
=> CAM(libarea): Fix encoding of clipper.cpp

package/rattler-build/recipe.yaml
The `openifc` package in `conda-forge` does not declare a runtime requirement of `typing_extensions`.  This PR brings in `typing_extensions` for the weekly builds to ensure it is present.
https://github.com/FreeCAD/FreeCAD/issues/19051
None.
=> CI: add typing_extensions to runtime dependency for weekly build.

src/Gui/propertyeditor/PropertyItemDelegate.cpp
fixes #21675 if the initial popup is canceled and the editor is left active, the combo will popup again-
regarding the regression before you needed a first click to activate the editor, then you can popup the list and hold the click
now the list will popup directly, the amount of clicks i'ts the same so there is no hold needed now, i don't consider this a regression
regarding the scroll on combo, it's incompatible with the approach of clicking an item on the list and directly applying the property directly, if wheel needs to be supported then we need to re-add the click outside to apply.
=> Gui: Property editor combobox fix not popping up if the user canceled

src/App/ProjectFile.cpp, src/Mod/Start/Gui/StartView.cpp
As soon as a FCStd file that is in the Recent Files list gets corrupted loading the Start page makes the application almost unusable. Steps to reproduce:
1. Create a simple FCStd file and load it
2. Close FreeCAD
3. Replace the FCStd file with random e.g. a text file
4. Start FreeCAD and try to open the Start page
Exception is repeatedly thrown and not much can be done:
```
[ ] C++ exception thrown (Unable to find zip structure: End-of-central-directory)
[ ] C++ exception thrown (Unable to find zip structure: End-of-central-directory)
...
[ ] C++ exception thrown (Unable to find zip structure: End-of-central-directory)
```
Although FreeCAD can be still closed, sometimes it crashes various ways, for example:
```
Program received signal SIGSEGV, Segmentation fault.
#0 …
```
=> Start: Fix crash

src/Mod/CAM/PathSimulator/AppGL/GCodeParser.cpp, src/Mod/CAM/PathSimulator/AppGL/GCodeParser.h, src/Mod/CAM/PathSimulator/AppGL/MillMotion.h
At this moment new **Simulator** not take in to account Retract mode (G98/G99) while drilling
- RetractMode = G99 - retract to the position specified by the R word of the canned cycle 
- RetractMode = G98 - retract to the position that axis was in just before this series of one or more contiguous canned cycles was started (`ClearanceHeight`)
In any case **Simulator** draw path for mode G99 (use retract from R of drill operation)
[drill.zip](https://github.com/user-attachments/files/20521081/drill.zip)
https://forum.freecad.org/viewtopic.php?p=829657#p829657
After this commit **Simulator** draw correct Path for drilling operation with G98 or G99 Retract mode
Added extra property `mode` to structure `MillMotion`
Probably this property can be used for some other cases
**Note**:
I am not C++ …
=> CAM: Simulator - Drilling - RetractMode G98/G99

src/Mod/CAM/Path/Dressup/DogboneII.py
In certain cases the Dogbone dressup created dogbones between two travel moves. Depending on the geometry of the travel those could also get extremely long.
[dogbone_on_travel_moves.zip](https://github.com/user-attachments/files/20402663/dogbone_on_travel_moves.zip)
=> CAM: prevent dogbones between two travel moves

src/Mod/BIM/Arch.py, src/Mod/BIM/ArchCommands.py, src/Mod/BIM/ArchSectionPlane.py, src/Mod/BIM/bimcommands/BimPreflight.py, src/Mod/BIM/importers/exportIFC.py, src/Mod/BIM/nativeifc/ifc_export.py, src/Mod/Draft/draftfunctions/fuse.py, src/Mod/Draft/draftfunctions/upgrade.py, src/Mod/Draft/draftguitools/gui_subelements.py, src/Mod/Draft/draftmake/make_bezcurve.py, src/Mod/Draft/draftmake/make_block.py, src/Mod/Draft/draftmake/make_bspline.py, src/Mod/Draft/draftmake/make_clone.py, src/Mod/Draft/draftmake/make_wire.py, src/Mod/Draft/draftobjects/base.py, src/Mod/Draft/importAirfoilDAT.py, src/Mod/Draft/importDXF.py
Fixes: #7387.
See comment: https://github.com/FreeCAD/FreeCAD/issues/7387#issuecomment-2915599566
PR to change the base object of BezCurve, BSpline and Wire to `Part::FeaturePython`. This will only affect new objects. So code will have to also keep handling the old object type (`Part::Part2DObjectPython`).
The modification of BimPreflight.py needs to be verified. The steps in the old code lacked logic IMO. But I may have misunderstood.
=> Draft/BIM: change BezCurve, BSpline and Wire to Part::FeaturePython

src/Mod/CAM/Path/Op/Area.py
At this moment determination of side for profile performed only for selected `Face`
For selected `Edges` every time by default offer Side = `Inside`
Also for open Edges must be Side = `Outside` every time, but offer `Inside` 
Which is not correct if after apply **Dressup LeadInOut**
**Before**
**After**
=> CAM: Offer correct side for Profile

src/Mod/CAM/Path/Op/Adaptive.py
Fixes the Adaptive toolpath helix entry start height calculation to correctly account for the operation start height and the stock boundaries. Previously naive math was done that could result in an entry from excessive height if a large stepdown was used.
Fixes #21058
Before, with large stepdown (helix starts at end depth + large stepdown, far above stock):
After (helix start is clamped to top of stock):
=> CAM: Adaptive: Fix helix entry start height (fix #21058)

src/Mod/CAM/Path/Main/Gui/Job.py
Toggle visibility for `Job` working incorrect along time
Each time manually hide all sub elements inside `Job`
There was a solution by macro
https://forum.freecad.org/viewtopic.php?p=809400#p809400
This commit must fix strange behavior of toggleVisibility of `Job`
State of sub-elements saved to memory before hide
So this state will be restored after `Job` will be unhidden
- Operations
- Models
- Stock
- ToolBits
_Note:_
Visibility state not saved between restore (close and open) document
So If you save document with some hidden elements, also saved visibility state of this elements will be `hidden`
Fix issues #12453 #16005 #18906
=> CAM: Fix Job toggleVisibility

src/App/Application.h, src/Base/CMakeLists.txt, src/Base/ProgressIndicator.cpp, src/Base/ProgressIndicator.h, src/Mod/Part/App/FCBRepAlgoAPI_BooleanOperation.cpp, src/Mod/Part/App/FCBRepAlgoAPI_BooleanOperation.h, src/Mod/Part/App/OCCTProgressIndicator.h, src/Mod/Part/App/TopoShape.cpp, src/Mod/Part/App/TopoShapeExpansion.cpp, src/Mod/PartDesign/App/FeatureTransformed.cpp
This PR adds end-to-end support for OCCT-style progress reporting and user-abort handling across Base, Part, PartDesign and boolean/shape builders:
Most of the code here was originally done by @jes, I've only separated into multiple commits, added some documentation around the commits and fixed an issue with workaround for old OCCT versions in Ubuntu CI.
This work will be used by follow-up work for asynchronous operations with progress and user cancellation support.
**1. New `Base::ProgressIndicator`**
* Introduces `ProgressIndicator` base class with no-op default implementation
* Registers `ProgressIndicator.h` in `src/Base/CMakeLists.txt`.
**2. OCCT adapter & boolean/shape builds**
* Creates `OCCTProgressIndicator` adapter (`Part/App/OCCTProgressIndicator.h`) inheriting from …
=> Part: Introduce `OCCTProgressIndicator` and port operations to support it.

src/Gui/Tree.cpp
Fixes: #20859
Although #20915 claims to fix #20859, it does not select anything. Instead it throws:
```
Unhandled Base::Exception caught in GUIApplication::notify.
The error message is: DocumentObject::getOutListRecursive(): cyclic dependency detected!
```
=> Gui: Fix TreeWidget::addDependentToSelection

src/Base/ProgressIndicator.cpp
The new ProgressIndicator feature that was merged broke building with precompiled headers enabled on Windows.
Reference: #21427
=> Fix compiling ProgressIndicator with precompiled headers

src/Gui/PreferencePages/DlgSettingsEditor.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/10514
This change blacklists the cursor.pcf font from being background saved into the preferences serialization file.
When this font is loaded, extents cannot be computed, and Freecad freezes at 100% cpu, with errors streamed to stderr.
A proposed workaround, that involves manually editing ~/.config/FreeCAD/user.cfg, to clear the cursor.pcf field when modified, only goes so far.
Since some actions that trigger the behavior - such as DXF import and export - don't provide any opportunity to save work, before one has to perform the pkil, and re-edit the user.cfg, so it is not possible to progress the design.
I believe this change is low risk, since it follows https://github.com/FreeCAD/FreeCAD/pull/10555
tested on nixos with freecad v1.0.1. …
=> fix #10514

src/Mod/CAM/CAMTests/TestPathVcarve.py, src/Mod/CAM/Path/Op/Vcarve.py
https://forum.freecad.org/viewtopic.php?t=96919
**Vcarve** operation get `zStart` from the first model in `Model` group of the `Job`,
which no way connected with the **Vcarve** operation and `ShapeString` object
If you change order of the objects in `Model` group for some reason, your `Vcarve` operation will suddenly change
https://github.com/FreeCAD/FreeCAD/blob/41c750be477c70dcbc16972d3a6aca315e465500/src/Mod/CAM/Path/Op/Vcarve.py#L503
https://github.com/FreeCAD/FreeCAD/blob/41c750be477c70dcbc16972d3a6aca315e465500/src/Mod/CAM/Path/Op/Vcarve.py#L208
Probably this is incorrect
For workaround can move clone of `ShapeString` object in `Model` group to the top or change `Placement` of **Vcarve** operation
After this commit `zStart` get form the first `BaseShapes` of the **Vcarve** operation …
=> CAM: Vcarve - fix zStart

src/Gui/propertyeditor/PropertyItem.cpp, src/Gui/propertyeditor/PropertyItemDelegate.cpp
After my lastest commit i added direct click to toggle and a label that should support translations, (the lines should appear after an lupdate)
[checkbox.webm](https://github.com/user-attachments/assets/d750f1df-5e97-443a-8f58-f0a9405ad236)
it has one quirk, clicking anywhere in the cell will toggle the checkbox due to the use of the focusIn event (the one that usually opens the editor)
closes #20763
=> Gui: Property editor use a checkbox instead of a combobox for booleans

src/Mod/PartDesign/Gui/TaskHoleParameters.cpp, src/Mod/PartDesign/Gui/TaskHoleParameters.h, src/Mod/PartDesign/Gui/TaskHoleParameters.ui
Motivation 
I had to explain more than once how the hole feature works in regards to threads, it's clearly a problem and even after I've rewritten the wiki, we talked with @benj5378  on Discord that this is not enough
The idea revolves around the fact that this solution is more self-explanatory
* Clearance / passthrough
Previously Not threaded and Not modeled, the bolt threads will not have contact, or at least it's threads will not engage.
* Tap Drill (To Be Threaded)
Previously Threaded but Not modeled; the hole is intended to be tapped, in woodworking it would be called pilot hole 
^ This one should get the cosmetic thread
* Modeled thread
Previously Threaded and Modeled; fully modeled thread probably for 3D printing.
this proposal is visual and the internal booleans and properties are …
=> PD: hole change the task panel threaded and model thread checkboxes into a combo/dropdown 

src/Mod/Fem/femguiutils/vtk_module_handling.py
Fixes a minor grammatical error in a warning message shown when VTK Python modules are mismatched.
Changed "then" → "than" in `src/Mod/Fem/femguiutils/vtk_module_handling.py` to improve grammar.
N/A – This is a minor typo fix and not linked to a specific issue.
N/A
This is my first ever pull request. This small grammatical change was suggested by the FreeCAD dev team to learn how to do a PR. Please let me know if I have made any mistakes!
=> Fem: Fix grammer in VTK module warning: 'then' -> 'than'

src/Mod/Material/App/Array2DPyImp.cpp, src/Mod/Material/App/Array3DPyImp.cpp
When setting quantity formats, the default format is not actually the default. Instead fixed format is, which causes issues for very small and very large values. This was fixed for C++ but arrays created in Python were not setting the format correctly.
=> Materials: Set array quantity format

package/rattler-build/pixi.lock, package/rattler-build/recipe.yaml
This is a followup to
- #21641
Includes fixed typo in package name and an updated lock file.
I am waiting for my local build verifying the fix to finish at which point I turn off the Draft option here.
=> Fix typing extensions

src/Mod/Spreadsheet/importXLSX.py
This fix was proposed by pageeddie on https://github.com/FreeCAD/FreeCAD/issues/19757
The solution to the bug was proposed in the ticket, but there are not a PR provided
I give credit to pageeddie (the author) in the commit message
https://github.com/FreeCAD/FreeCAD/issues/19757
Before:
The image show FreeCad opening the spreadsheet
=> Avoid error importing spreadsheet with deleted sheet (#19757)

src/Mod/Sketcher/Gui/DrawSketchHandlerScale.h
=> Sketcher: fix typo in source comment

src/Mod/CAM/CAMTests/TestPathPreferences.py, src/Mod/CAM/Path/Preferences.py
This fixes the issue found in #21735
The default directory used to store CAM assets was incorrect. This PR fixes the issue.
Old:
`<config-base-dir>/Mod/CAM/Tools`
New:
`<config-base-dir>/CamAssets`
=> CAM: fix default asset directory

src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h
This PR refactors the `Point` tool's input hint logic in Sketcher to use the direct-return pattern adopted for single-state tools. It removes unnecessary lookup tables and simplifies `getToolHints()` to return a single, localized hint directly.
This matches the declarative style used in tools like `Offset` and `Symmetry` and improves maintainability while preserving behavior.
---
N/A — architectural cleanup
---
**Before:**  
The `Point` tool used an internal hint table and lookup function to return a single hint.
**After:**  
The hint is now returned directly in `getToolHints()`, eliminating indirection and reducing code size by 30+ lines.
---
- The Point tool has only one operational state, making the previous table-driven architecture unnecessary.  
- This direct-return pattern is now …
=> Sketcher: Refactor Point tool to direct-return input hint pattern

src/Mod/CAM/CMakeLists.txt, src/Mod/CAM/Tools/Bit/3.175mm_Endmill.fctb, src/Mod/CAM/Tools/Library/Default.fctl
While being a metric guy, i still have to admit, that 3.175mm (or 1/8 inch as someone might say) is one of the most common endmill diameters due to wide availability/compatibility even outside of the imperial world. It's very popular among hobby CNC users and PCB manufacturers. It's also often a default diameter in many kinds of CAM related software.
Therefore i took the liberty of including it in default FreeCAD CAM tool library to welcome new users with familiar toolbit.
=> CAM: Add 3.175mm endmill to default tool library as it's extremely common size

.github/workflows/sub_buildUbuntu.yml
Currently parts of the BIM workbench and the IFC importer/exporter code cannot be tested during the CI builds as they depend on `ifcopenshell` being installed.
This PR installs `ifcopenshell` in the Ubuntu native build as it's probably the easiest platform to install it on. Once installed, then we'll be able to execute unit tests that exercise IFC operations for the BIM workbench. The tests can be written so that they can be skipped when run on a CI workflow that doesn't have `ifcopenshell` installed.
With recent fixes in the pixi builds (https://github.com/FreeCAD/FreeCAD/pull/21641, https://github.com/FreeCAD/FreeCAD/pull/21714), I believe `ifcopenshell` should already be installed there. This means, tests could eventually be executed for the pixi builds, and Ubuntu native builds. Then …
=> CI: add ifcopenshell to Ubuntu native builds

src/Gui/BitmapFactory.cpp, src/Gui/BitmapFactory.h, src/Gui/InputHintWidget.cpp
This adds empty(QSize) method to bitmap factory that creates empty pixmap. This may seem useless, but after creating bitmap one needs to remember to clear it and to properly set DPR - BitmapFactory will take care of it.
@maxwxyz FYI
=> Gui: Add BitmapFactory::empty method

src/Mod/BIM/bimcommands/BimViews.py
While carrying out some testing in BIM I moved and deleted the `BIMViewArea` dockwidget and managed to create this attribute error in the Report View:
```
20:46:49  Traceback (most recent call last):
20:46:49    File "/home/john/freecad-daily-build/Mod/BIM/bimcommands/BimViews.py", line 535, in onDockLocationChanged
20:46:49      PARAMS.SetInt("BimViewArea", area.value)
20:46:49                                   ^^^^^^^^^^
20:46:49  AttributeError: 'PySide2.QtCore.Qt.DockWidgetArea' object has no attribute 'value'. Did you mean: 'values'?
```
This PR is to prevent the error being generated in future.
=> [BIM] Fix Attribute Error when user moves and then deletes the BimViewArea dock widget

src/Mod/Draft/importSVG.py
Fix #19422 SVG: use tag create wrong size object
Fix #19072 SVG: import \<defs\> keyword as object without \<use\>
and Fix bug that not reported, \<symbol\> keyword imported as object without \<use\>
and Fix bug that not reported, nested use keyword not import correctly.
and Fix bug that not reported, use tag that referenced not symbol ID is not imported. 
To do this. I make pre-processor that replace use tag to it's referenced object.
and remove symbol tag and defs tag from loaded svg.
there is a subeffect, name of imported object that related to symbol tag is changed.
=> Fix several SVG import bugs

src/Mod/TechDraw/App/Geometry.cpp
In PR ##21374, an element name in Vertex::Restore is misnamed.  This causes document loads to fail if they contain a CosmeticVertex.
This PR corrects the element name.
=> [TD]fix bad element name in Vertex::Restore

src/Mod/Part/App/AppPart.cpp, src/Mod/Part/App/FaceMakerBullseye.cpp, src/Mod/Part/App/FaceMakerBullseye.h, src/Mod/Sketcher/App/SketchObject.cpp
This is adding FaceMakerRing subclass from Realthunder's branch.
This is a necessary step to support RealThunder's "MakeInternals" option of sketches.
This feature adds faces to closed wires of sketches. Then letting the user selecting the faces he wants to extrude. This feature request has been asked many many times.
With this PR I think the APP part of the feature is ready. Now we are just missing the GUI side which appears to be more difficult to port.
=> Part: FaceMakerRing from RealThunder's branch.

src/Mod/CAM/CAMTests/TestPathToolShapeIcon.py, src/Mod/CAM/Path/Tool/shape/models/icon.py, src/Mod/CAM/Path/Tool/toolbit/ui/editor.py
Note the abbreviations behind the labels.
Old label: Length
New label: Length (L)
=> CAM: Show abbreviation on each label to match input value to shape image on the UI

src/Mod/TechDraw/Gui/TaskProjGroup.cpp
Old functionality: 
Adjusting spacing between views had no preview and required clicking "Apply" to view changes each time a value was changed
New functionality:
Each time a value is adjusted, the view is updated on the page instantly. When clicking "Cancel", views are restored to their old positions. 
Fixes #21779
**Note: if clips don't automagically load, right-click on the clip and 'Open in new tab'** *--luzpaz edit*
Before: 
https://github.com/user-attachments/assets/c8d66a4d-3ab3-4abd-b6cc-4660357d4f45
After:
https://github.com/user-attachments/assets/5f801e3a-2d35-449d-87c8-c821de1bd2d2
Relevant discussion in Discord -> ux-topics -> TechDraw: Add support for updating preview when adjusting spacing between drawing views
This is my first time making a functional code change to any …
=> Techdraw: Add spacing preview

src/Gui/ViewProviderCoordinateSystem.cpp, src/Gui/ViewProviderCoordinateSystem.h
Cherry pick (with cleanup) of @wwmayer's fix in 3e578cb
From commit:
> This is a left-over of the regressions introduced with PR 18126.
> Thanks to some moderinization of the code base and replacing static with dynamic casts undefined behaviour
> has changed to well-defined behaviour but now unchecked null pointers.
> 
> This change does some extra null pointer checks and uses the now correct types for down casting.
> 
> Hint: Upstream still uses many static casts here that already cause undefined behaviour when creating a LCS.
> This could be the reason for the possible crashes when deleting a LCS as described in #20261
=> Gui: Fix crash when creating a LCS

src/Mod/Import/App/dxf/dxf.cpp
When importing the attached file ([test_codepage.zip](https://github.com/user-attachments/files/20669977/test_codepage.zip), uncompress first), the C++ DXF importer fails with this error:
```
Error reading DXF file: <built-in method readDXF of tuple object at 0x7efdc35bd240> returned a result with an exception set
```
The file is a simplified header-only version for testing purposes. The real file I initially had troubles with is much larger.
This PR fixes that error in two stages:
1. Improve exception handling to pinpoint the exact cause (9de117846d33b92d9f0d24ea9ee0cf1082ba9fc5 and 42c78729c31713c56d32e1f1c2d2701f475fea40). Then the error becomes much clearer:
```python
File "<string>", line 2, in <module>
File …
```
=> Import: DXF, handle non-standard 8859_1 encoding

src/Gui/MainWindow.cpp, src/Gui/PreferencePages/DlgSettingsReportView.ui, src/Gui/ReportView.cpp, src/Gui/Stylesheets/FreeCAD Dark.qss, src/Gui/Stylesheets/FreeCAD Light.qss
In discussion with @FreeCAD/design-working-group 
Currently two obtrusive notification systems are shown to the user in parallel.
This PR sets the default so that the report view panel does not pop up if the user has not enabled it and centers the notification label which was touching the border in the status bar button.
Before:
=> Gui: Center notification label and disable show report view by default

src/Mod/Sketcher/Gui/DrawSketchHandlerCarbonCopy.h, src/Mod/Sketcher/Gui/DrawSketchHandlerExtend.h, src/Mod/Sketcher/Gui/DrawSketchHandlerExternal.h, src/Mod/Sketcher/Gui/DrawSketchHandlerFillet.h, src/Mod/Sketcher/Gui/DrawSketchHandlerSplitting.h, src/Mod/Sketcher/Gui/DrawSketchHandlerTrimming.h
This PR extends the `InputHints` system to Sketcher's **edit tools**, continuing the integration pattern introduced in [PR #21632](https://github.com/FreeCAD/FreeCAD/pull/21632) and expanded in Phase 2 for constraint tools. It provides in-canvas, contextual prompts for all major editing operations based on internal tool state.
Tools now covered include:
- **Fillet**
- **Chamfer**
- **Trim**
- **Split**
- **Extend**
- **External Geometry**
- **Carbon Copy**
Each handler uses a localized hint table keyed by tool state or mode, delivering real-time guidance to users as they interact.
---
N/A — this is part of the ongoing integration of the InputHints framework into Sketcher
---
**Before:**  
Sketcher edit tools provided no contextual feedback. Users had to rely on trial-and-error to …
=> Sketcher: Add contextual input hints to edit tools (InputHints Phase 3)

src/Gui/PrefWidgets.cpp, src/Gui/PrefWidgets.h, src/Gui/PropertyPage.cpp, src/Gui/resource.cpp, src/Mod/BIM/Resources/ui/preferences-ifc-export.ui, src/Mod/Draft/draftutils/params.py
Create a custom widget (`Gui::PrefCheckableGroupBox`), in the style of `Gui::PrefCheckBox` for checkable QGroupBoxes. This new widget enables developers to use QGroupBoxes to both save/restore parameters as all other custom FreeCAD preference widgets, and to conditionally enable/disable the widgets they contain.
It's a general approach and a prerequisite to fix the linked issue. There, the IFC Exporter preference page uses this new widget to conditionally control the status of group export preferences, depending on whether groups are ignored or not at export time.
Before, the parameter associated with the groups setting was not saved to disk, and functioned out of sheer luck. This was because of the fact that the default setting worked through masking an error by negating the parameter's …
=> Gui, Draft, BIM: Add PrefCheckableGroupBox, use it in IFC exporter preferences page

src/App/Application.cpp
By using regex we can remove prefix and suffix more securely as we can’t assume all navigation styles are formatted the same (mistakes can happen)
Code speaks for itself.
=> App: Trim “Gui::” and “NavigationStyle” more securely

src/Mod/BIM/Arch.py
Regressed from previous behavior - there was Arch's refactor and the base element that `SectionPlane` was inheriting from was `App::FeaturePython`, not `Part::FeaturePython`. This changes a lot, since `Part::FeaturePython` has predefined color (black in this case), which later on - during property set of `SectionPlane` in properties caused skipping of preferred setup of color.
Caused-by: https://github.com/FreeCAD/FreeCAD/pull/21342
FYI @furgo16 
Demo:
https://github.com/user-attachments/assets/cfab79f2-d78e-4a75-bd2e-28d38538ce63
Resolves: https://github.com/FreeCAD/FreeCAD/issues/21875
=> BIM: Fix Arch_SectionPlane having incorrect display style upon init

src/Mod/Sketcher/App/Sketch.h
Just a minor cleanup
The change consists of:
- Fix comment for mid-point
- Use in-class member initializers instead of constructor
- Remove redundant default constructor (got redundant after initializers)
- Made comments doxygen compatible
=> Sketcher: Refactor GeoDef and ConstrDef structs

src/Gui/Tree.cpp
This patch fixes crashes that we've noticed during migration from Qt5 to Qt6 in recent months.
If you select items in a tree in a specific direction or range (all, or from bottom to top) and delete them, there is a high change user will experience a crash in `testStatus` function. This problem arises because we're getting into use-after-free situation.
Looking at the callstack there are a lot of calls to `itemSelectionChanged` during deletion, which takes over item creation after deletion in `TreeWidget::_slotDeleteObject`. This in turn causes `DocumentObjectItem::testStatus` to be called prematurely when we have dangling pointers in object map still. `itemSelectionChanged` signal is being transmitted because the selection range is changing as we're constantly deleting and readding …
=> Core: Fix crashes during item deletion in specific selection order

src/Mod/BIM/nativeifc/ifc_objects.py
As the title says, this is simple fix - basically right now anytime user changed Link property to point to proper IFC type, we weren't writing to the IFC file buffer to finally write it to the file if user would save it.
So this patch makes sure we write to this buffer by calling appropriate function, and making ifc object have proper pointer to IFC type.
@semhustej fyi pls check, tia
Demo:
https://github.com/user-attachments/assets/f038dca3-50de-4d82-980c-04e5d1912daa
Resolves: https://github.com/FreeCAD/FreeCAD/issues/21928
=> BIM: Fix IFC type assignment not being saved to file

src/Mod/Draft/draftgeoutils/offsets.py
Remove the somewhat-confusing redundant assignment. Closes https://github.com/FreeCAD/FreeCAD/security/code-scanning/3944
=> Draft: Eliminate redundant assignment to self

src/Gui/Dialogs/DlgPropertyLink.cpp
As the title says, currently it is:
ObjName (Label), this patch changes it to Label (ObjName) to be more user friendly.
@semhustej pls check, tia
Demo:
https://github.com/user-attachments/assets/e1a102fb-7a4c-4164-93fb-f4c301780db1
Resolves: https://github.com/FreeCAD/FreeCAD/issues/21930
=> Gui: Change ordering of names in Link property

src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h, src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
As the title says - since there is pending PR for better SoDatumLabel constraints interactivity, this patch now prioritizes geometry lines over constraints, so constraints will be rendered below lines.
This patch changes rendering order of constraint lines to be below geometry lines, so now selection and rendering will be prioritized for geometry lines instead of constraints.
This is done by changing depth buffer values and removal of SoAnnotation node which was disabling depth buffer checks on constraints at all.
NOTE:
This should be merged before https://github.com/FreeCAD/FreeCAD/pull/21920, there are still some parts to resolve regarding text order and arrowheads, but I will do it in 21920 separately, as it touches `SoDatumLabel.cpp` parts of code, so just to avoid unnecessary …
=> Sketcher: Prioritize rendering geometry lines rendering over constraints

.github/workflows/CI_master.yml, .github/workflows/sub_lint.yml, .github/workflows/sub_prepare.yml, tools/lint/changed_lines.py, tools/lint/clang_tidy.py
This PR limits GitHub lint output to the lines changed in a PR.  
The other linters shall be addressed by later PRs as this will assist in cutting down on the noise in PRs.
TODO:
=> Limit lint to changed lines

.github/workflows/sub_prepare.yml
Attempting to identify the changed files of a PR was being triggered on push events, which would fail as there is no PR associated on merges to `main`.
=> CI: only lint on PRs.

src/Mod/Part/App/PartFeatures.cpp, src/Mod/Part/App/PartFeatures.h
There is a malformed method in PartFeatures.h that was leftover from the TNP merge: it didn't matter that it was malformed because in the end we didn't need any of these methods. See https://github.com/FreeCAD/FreeCAD/pull/12511 for context.
=> Part: Remove remnants of code from TNP merge

src/Mod/Sketcher/App/SketchObject.cpp
Closes https://github.com/FreeCAD/FreeCAD/security/code-scanning/5306 by completely removing the code block, which was no longer needed.
=> Sketcher: Remove dead code

src/Mod/Sketcher/App/SketchObject.cpp
Two `GeoId` checks are redundant (one was always true and the other always false). Remove the extra checks. Also cleanup missing curly braces in the two clauses affected. Closes https://github.com/FreeCAD/FreeCAD/security/code-scanning/5307 and https://github.com/FreeCAD/FreeCAD/security/code-scanning/5308.
=> Sketcher: Remove redundant checks

src/Mod/Measure/App/Measurement.cpp
Closes https://github.com/FreeCAD/FreeCAD/security/code-scanning/5313 -- no need for this check, we already know that `edges > 0` from the check two lines above, so the measurement type is indeed invalid if there are both edges and more than one point selected.
=> Measure: Remove redundant check for edges > 0

src/Mod/CAM/Path/Main/Gui/Job.py
@tarman3 already improved the behaviour when changing the visibility of a Job in #21694. However there were two issues:
a) when restoring a file with a hidden Job containing hidden operations/models, showing that job would not show the operations/models
b) when hiding a Job, then showing operations/models in that Job and then showing the Job, the previously shown operations/models would hide again
This PR addresses those issues.
=> CAM: improve Job toggleVisibility

src/Mod/CAM/PathScripts/PathUtilsGui.py
This change helps choosing the right CAM Job when the document has multiple jobs, and something is already selected inside a job. The original behavior is to select the current job only if that is the only one selected. However, it would be more intuitive to go up in the model chain to detect the appropriate job.
Also, there was a minor case of indentitis in the same method.
I couldn't find any relevant issues to this problem.
There is no GUI changes, apart from the fact the "Choose a CAM Job" dialog pops up less often.
=> CAM: find job in parent chain when adding a new operation

src/App/GroupExtension.pyi, src/App/GroupExtensionPyImp.cpp, src/Gui/ActiveObjectList.cpp, src/Gui/ActiveObjectList.h, src/Gui/CommandStructure.cpp, src/Gui/MDIView.h
As the title says, if right now there is Arch type active (like Level, Building, etc. etc.), then it's not possible to assign Group to it automatically (it's being created on root level of the document).
So this patch adds autogroup functionality, if no object is no active -> no harm, the function will check that and insert Group in the root document object, if there is active object -> it will insert the Group under it.
Demo:
https://github.com/user-attachments/assets/6f3dccf6-b021-488f-80aa-6434b0b36aaf
Resolves: https://github.com/FreeCAD/FreeCAD/issues/21380
=> Core: Allow users to add groups to active objects

src/Gui/Dialogs/DlgPreferences.ui, src/Gui/Dialogs/DlgPreferencesImp.cpp, src/Gui/Dialogs/DlgPreferencesImp.h
This PR introduces search box in preferences.
Features:
* supports left click on the result, taking user to the result
* clicking anywhere cancels searching and closes popup box, same with ESC key
* double click on the result closes the popup too (same behavior as enter)
* supports enter (although if you are on the position you are already on it so enter just closes the popup basically)
* you can navigate through the list with mouse
* support fuzzy search so stuff like "OVP" is being matched to "On-View-Parameters"
* there is hierarchical display (tab/page/setting)
* some of the results are prioritized but fuzzy search prioritizing is the most important
* highlights found item
* goes into found item
* if the pop-up box won't fit next to the right side of the screen, it is added underneath …
=> Core: Introduce searching in Preferences

src/Gui/SoDatumLabel.cpp, src/Gui/SoDatumLabel.h
Closes #12394. I have read too much of literature, tried many things, but so far, I cannot say why exactly this works.
`glBlendFunc(GL_ONE, GL_ONE_MINUS_SRC_ALPHA);` is the right way to blend colors with alpha channel, however, it gives blur with single-colored background, so conversion just ARGB32 without pre-multiplication gives good-looking result.
Just ARGB32 without pre-multiplication with unchanged blending parameters gives dark fringe anyway.
It would be good if somebody tests it on _Windows_ with Line Smoothing/Antialiasing on.
=> [GUI] Remove dark fringe around letters

src/Mod/Part/App/PartFeature.cpp
Add support to align selection to curve normal direction. This fixes a sub-item of #11234. @maxwxyz, please test.
=> Part: Align to planar curves normal direction

src/Gui/ViewProviderDragger.cpp, src/Gui/ViewProviderDragger.h
Links require different placement property (`LinkPlacement`) to be used, otherwise it breaks the transform.
Fixes: #20776
=> Gui: Use proper placement property for Link

src/Mod/BIM/ArchCurtainWall.py
Fix #21845
Curtain wall vertical/horizontal mullion mix-up
- https://github.com/FreeCAD/FreeCAD/issues/21845
Support/Feature #21866
Swap Horizontal Vertical does not work #21866
-  https://github.com/FreeCAD/FreeCAD/issues/21866
=> [ArchCurtainWall]  Fix Vert-Horiz Mullion Mix-up & Support Swap

src/Mod/BIM/ArchSchedule.py
Fixes: #20639
AFAICT the issue was caused by:
`self.form.setWindowFlags(self.form.windowFlags() | QtCore.Qt.WindowStaysOnTopHint)`
And I have just removed that line.
=> BIM: avoid display of Arch_Schedule dialog over other applications

src/Mod/CAM/Path/Op/EngraveBase.py
Sort tool paths for Engrave and Deburr operation. I haven't used the Engrave operation much so it would be nice if someone could give it a try.
The sorting is not very sophisticated. It only uses the center point of the wires, similar to what Area.py is doing. However, for many small wires this should be fine and for larger wires, the time spent travelling will be small compared to the time spent milling anyway.
without sorting:
with sorting:
[sort_engrave_deburr_test.zip](https://github.com/user-attachments/files/20403424/sort_engrave_deburr_test.zip)
=> CAM: sort tool paths for Engrave and Deburr operation

src/Mod/Measure/App/MeasurePosition.cpp
This PR is to fix the seg fault reported on the [forum](https://forum.freecad.org/viewtopic.php?t=97756) only when Measurement is started before selection of vertices.
Regression tested pre-selection of vertices with PR successfully.
Fixes #20329 
Fixes #20194 
@hlorus FYI
=> [Measure] Fix seg fault in MeasurePosition::execute if subElements is empty

src/Mod/TechDraw/App/DrawViewDetail.cpp, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/App/DrawViewPart.h, src/Mod/TechDraw/App/Preferences.cpp, src/Mod/TechDraw/App/Preferences.h, src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui, src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneralImp.cpp, src/Mod/TechDraw/Gui/QGIHighlight.cpp, src/Mod/TechDraw/Gui/QGIViewPart.cpp, src/Mod/TechDraw/Gui/TaskDetail.cpp, src/Mod/TechDraw/Gui/TaskDetail.h, src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp, src/Mod/TechDraw/Gui/ViewProviderViewPart.h
This PR implements a fix for issue #21828.  Specifically, it:
- eliminates the conflict between the dragable highlight on base views and the update process in TaskDetail
- uses DrawView::isProjGroupItem() instead of dynamic_cast or isDerivedFrom<>() to determine if a views belongs to a projection group.  This eliminates the spurious "ProjectionGroup is confused" message.
- implements snapping of highlights to the closest vertex in the TaskDialog drag highlight process.
=> [TechDraw]Detail highlight drag (fix #21828)

src/Gui/PythonWrapper.cpp
Qt 6.9 deprecated wildcard disconnects it seems, and for main window we did a lot of disconnects like this. 
@xtemp09 FYI
Fixes https://github.com/FreeCAD/FreeCAD/issues/21903 - this does not get rid of _all_ warnings mentioned in comments, only the one that is most obnoxious i.e. the one from the description.
=> Gui: Fix wildcard call disconnects warnings Qt6.9

src/Gui/EditableDatumLabel.cpp, src/Gui/EditableDatumLabel.h, src/Mod/Sketcher/Gui/DrawSketchController.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArcSlot.h, src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h, src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h, src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h, src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h, src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h, src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h, src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h, src/Mod/Sketcher/Gui/DrawSketchHandlerRotate.h, src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h, src/Mod/Sketcher/Gui/DrawSketchHandlerTranslate.h
This patch adds/changes a couple of things:
* if you press enter on a label now, it moves you to another label and adds the label and lock on the previous label, instead of previous behavior where it was accepting whole dimension
* if you press enter and have lock state on both labels then you move to next stage
* if you press ctrl+enter it's as is if you'd press enter on both labels (the object becomes constrained with whatever dimensions that were in both labels)
* tab still works the same way
* you can remove "Lock" state from the label by typing something additional or removing the dimension at all
* and of course mouse works independently from this update 
Demo:
https://github.com/user-attachments/assets/012b5365-fb83-4731-a5d5-2c03da8b43d7
Resolves: …
=> Sketcher: Change enter behavior on OVP to put OVP in lock state only

src/Gui/ExpressionCompleter.cpp, src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp, src/Tools/plugins/widget/customwidgets.cpp, src/Tools/plugins/widget/customwidgets.h, src/Tools/plugins/widget/plugin.cpp
Fixes #21914
This also includes a related commit that adds ExpressionLineEdit to QtDesigner plugin by @wwmayer.
After:
https://github.com/user-attachments/assets/8dc6d107-96d8-4a40-9f27-010df509d720
Not obvious from video, but the = is still suppressed in the normal expression editor dialog
=> Spreadsheet Fix '=' regression in spreadsheets

src/Gui/ViewProviderDragger.cpp
`getExtensionByType` requires `true` as parameter to not throw if extension is not found, I did not know that :)
Fixes: #22166
=> Gui: Use no_except=true for getExtensionByType in ViewProviderDragger

src/Gui/Command.cpp, src/Gui/Command.h, src/Mod/Part/Gui/Command.cpp, src/Mod/PartDesign/Gui/Command.cpp
As far as I understand it, the method `Command::adjustCameraPosition()` repositions an orthographic camera if the camera is within the bounding sphere of the scene. It then moves the camera to the edge of the bounding sphere and sets the `nearDistance`, `farDistance` and `focalDistance`. Setting the `nearDistance` and `farDistance` is not needed as this is adjusted by Coin automatically. Setting the `focalDistance` is not needed too because with #21798 this is always set to 1 ( `nearDistance` and `farDistance` adjusted by Coin again). Furthermore, the method `Command::adjustCameraPosition()` does not reposition the camera along the camera Z axis but by the difference between the camera position and the bounding sphere center. This could cause the camera to move in a bit of a random …
=> Remove Command::adjustCameraPosition()

src/Mod/PartDesign/App/FeatureChamfer.cpp, src/Mod/PartDesign/App/FeatureExtrude.cpp, src/Mod/PartDesign/App/FeatureFillet.cpp, src/Mod/PartDesign/App/FeatureGroove.cpp, src/Mod/PartDesign/App/FeatureLoft.cpp, src/Mod/PartDesign/App/FeaturePipe.cpp, src/Mod/PartDesign/App/FeatureRevolution.cpp
cherry-picked f2117d4088, 8961dea5ce89 and a40610fdc695
Fixes: #19002
Fixes: #18977
For several PD features the single-solid check fails. The regression is caused by PR 13960. The reason for the failure is that the first solid of the output shape is retrieved and then checked for a single solid. This test will always pass, of course.
The single-solid is fixed for these features:
* Pad
* Pocket (never worked there)
* Fillet
* Chamfer
* Groove (never worked there)
* Revolution (never worked there)
* Loft
Fixes: 935bdf9a0f1a ("PartDesign: Refactor single-solid rule enforcement")
=> PD: Fix regression about single-solid check

src/Mod/Draft/Resources/ui/TaskPanel_CircularArray.ui, src/Mod/Draft/Resources/ui/TaskPanel_OrthoArray.ui, src/Mod/Draft/Resources/ui/TaskPanel_PolarArray.ui, src/Mod/Draft/Resources/ui/TaskShapeString.ui
As the title says. We had a discussion that those QGroupBoxes (global one and additional one around the button and radio buttons for Ortho Array) are completely redundant, and the panel would look better if we'd remove them.
So they got removed + removed icons from the panels as they are already visible in the panel's tab.
FYI @kaiwas @PaddleStroke 
Showcase:
BEFORE:
===========================
AFTER:
============================
=> Draft: Remove redundant QGroupBoxes from some of the array panels

src/Mod/Fem/App/PreCompiled.h
Missing VTK entries in PreCompiled.h cause build failures when using PCH (the default on MSVC).
=> FEM: Fix missing VTK headers in PreCompiled.h

src/Gui/DocumentObserver.h
MSVC warning 4251 is emitted when a class that is exported from a DLL has a member that doesn't itself have a proper DLL interface -- Boost specifically (and intentionally) does not export `scoped_connection`. But for our use this doesn't matter because when compiling FreeCAD, all DLLs are built at the same time, with the same compiler, with the same Boost headers and settings, and we're not exposing `scoped_connection` in any exported symbols (it's a private data member). So the theoretical ABI-compatibility problems this code might present cannot manifest themselves. Disable this warning (but only for this particular piece of code, since the warning itself might apply elsewhere).
=> Gui: Selectively disable MSVC 4251 warning

src/Mod/Fem/Gui/Resources/ui/PostHistogramFieldAppEdit.ui, src/Mod/Fem/Gui/Resources/ui/PostLineplotFieldAppEdit.ui, src/Mod/Fem/femviewprovider/view_post_histogram.py
One field for each frames --> One field for each frame
Also fixes one more typo: "If be the bars" --> "If the bars"
=> FEM: Fix data extraction checkbox typo

src/3rdParty/salomesmesh/inc/SMDS_UnstructuredGrid.hxx, src/3rdParty/salomesmesh/src/SMDS/SMDS_Mesh.cpp, src/3rdParty/salomesmesh/src/SMDS/SMDS_MeshNode.cpp, src/3rdParty/salomesmesh/src/SMESH/SMESH_MeshEditor.cpp
This patch fixes freecad build with VTK 9.5 (but may break older versions since I did not add version guards and did not test it).
Replacing `vtkUnstructuredGrid::GetCellLinks` with `vtkUnstructuredGrid::GetLinks` is necessary since the former has been deprecated in VTK 9.3 and silently removed in 9.5:
https://gitlab.kitware.com/vtk/vtk/-/blob/master/Documentation/release/9.3.md
Also since salomesmesh is in the 3rdParty directory I have no idea if this should be actually patched in this repo or pulled from somewhere else :shrug:
=> Core: Fix build with VTK 9.5

CONTRIBUTING.md
This adds requirement for new PRs to contain proper attribution in description and commits if PR is made by non-author.
=> Contributing: Add requirement to clearly mark ownership for cherry-picked PRs

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
The "Esc can leave sketch edit mode" setting was working, but it's state wasn't properly refreshed after changes (requiring a restart for it to take effect).
All the required code was already there just a small mistake in property name. Seems like the wrong name was there from the time it was introduced in 92e6094 . I am guessing it was a placeholder/copy paste error which wasn't properly tested due to being part of giant refactoring commit.
Test plan:
* enable "esc can leave sketch edit mode" sketcher option
* restart FreeCad (just to be sure, technically not needed after the fix)
* create sketch
* press esc -> should exit sketch
* create second sketch (keep opened)
* open preferences and disable "esc can leave"
* press esc -> should not exit sketch
* exit sketch using mouse
* open first …
=> Sketcher: fix Esc can leave setting synchronization

src/Mod/Draft/importDXF.py, src/Mod/Import/App/AppImportPy.cpp, src/Mod/Import/App/dxf/ImpExpDxf.cpp, src/Mod/Import/App/dxf/ImpExpDxf.h, src/Mod/Import/App/dxf/dxf.cpp, src/Mod/Import/App/dxf/dxf.h, src/Mod/Import/Gui/AppImportGuiPy.cpp
Add a console DXF statistics reporter for the FreeCAD C++ importer. Help both users and developers understand the content of DXF files and the importer's behaviour.
> [!NOTE]
> This PR does not change the functionality of the DXF importer. It simply adds reporting capabilities to it.
Goals:
- Provide more feedback to the user. DXF import is a complex process: there are two importers currently and each supports a set of features. More information removes uncertainty from the process.
- Provide more context for reporting bugs. In particular, the import settings have been included in the report, so that they can be pasted on issue reports.
- Provide the user more context on what the optimal import settings are. There are currently multiple settings and setting combinations that lead to …
=> Import: add DXF statistics reporter

src/Gui/Application.cpp
The next version of Coin has some EGL support which can be enabled by setting `COIN_EGL`. This PR sets that environment variable if we are running on Wayland (not XWayland). It is not perfect, it doesn't work when using NVIDIA proprietary drivers (at least for me) so we should default set `QT_QPA_PLATFORM=xcb` for releases. However, non NVIDIA proprietary driver users may benefit from setting `QT_QPA_PLATFORM=wayland` manually.
When the new Coin version is released we also need to add `qt6-wayland` to pixi.
=> Inform Coin to use EGL when on Wayland

src/Mod/Fem/Gui/Command.cpp
=> FEM: Correct "Qquations" typo in the menu

src/Mod/Material/Gui/BaseDelegate.cpp, src/Mod/Material/Gui/ImageEdit.cpp, src/Mod/Material/Gui/MaterialsEditor.cpp
Adds support for file types other than PNG to embedded images in materials. Adds checks to prevent crashing when an unsupported image type is used.
This uses the built in Qt function features to detect image type instead of forcing a PNG image type. It also checks the results before trying to set the preview, which was the cause of the crash.
Fixes #22292
=> Materials: Add support for embedded images

src/Gui/PreferencePages/DlgSettingsLightSources.ui
Removes the tooltip that has been superfluous since the introduction of 3 point lighting.
=> Core: Remove outdated tooltip from light source preferences

src/Mod/Material/App/MaterialLoader.cpp, src/Mod/Material/App/Materials.cpp, src/Mod/Material/App/Materials.h
Adds import/export support for unimplemented material fields.
This includes reference source and URLs, and tag fields. Tag support remains unimplemented in the editor, but is supported by a number of materials in the FCMat files. They can be accessed in both C++ and Python.
=> Materials: Add import for unimplemented fields

src/Mod/Draft/DraftGui.py
Follow-up of #22199.
PR to replace remaining `QtCore.QObject.connect` code to make the file consistent.
Entirely removed the following lines as they were non-functional:
```python
QtCore.QObject.connect(self.baseWidget,QtCore.SIGNAL("resized()"),self.relocate)
QtCore.QObject.connect(self.baseWidget,QtCore.SIGNAL("retranslate()"),self.retranslateUi)
```
Also removed the `relocate` function.
=> Draft: DraftGui.py replace QtCore.QObject.connect

src/Gui/CommandView.cpp, src/Gui/MainWindow.cpp, src/Gui/propertyeditor/PropertyItem.cpp, src/Mod/CAM/PathSimulator/AppGL/GuiDisplay.cpp, src/Mod/CAM/PathSimulator/AppGL/MillSimulation.h, src/Mod/Fem/Gui/TaskPostBoxes.h, src/Mod/TechDraw/Gui/QGIViewPart.cpp, src/Mod/TechDraw/Gui/QGIViewSection.cpp, src/Mod/TechDraw/Gui/ViewProviderViewPart.h
Each commit in this PR addresses one particular compiler warning, kept separate for easy rollback if one turns out to be faulty.
@marioalexis84 could you please check https://github.com/FreeCAD/FreeCAD/commit/0faeed100da8f9e580377d1db50e5426957bf71c ?
@WandererFan could you please check https://github.com/FreeCAD/FreeCAD/commit/c864b29cd408152b4b86048aaa2bb9bd00a1f747 ?
The rest of them are basically rote fixes (though I decided to add designated initializers to the structs based on a discussion with @kadet1090, which might be a more controversial change, and isn't required to fix the compiler warnings about omitted initializers).
=> Compiler warning cleanup

src/Gui/ViewProviderLink.cpp
Like #22345 it fixes issue with too small arrow on high DPI displays. The problem was that the code in ViewProviderLink used width that is already multiplied by DPR as size for icon that expects not premultiplied size, which was messing with proportions.
@maxwxyz can you test that it works as it should?
Closes #22345
Fixes #6765
| ![image](https://github.com/user-attachments/assets/7d1f2761-2432-4878-9d79-ab27be367a17) |![image](https://github.com/user-attachments/assets/802aeb36-833d-4842-83d8-a4003722f5e1)  | 
Not sure why I get pixelated icons in that case, but I had it also before so probably some issue with my way of testing HighDPI stuff.
=> Gui: Fix too small link icon on high dpi

src/Base/Tools.h, src/Gui/Application.cpp, src/Gui/Application.h, src/Gui/CMakeLists.txt, src/Gui/CommandStd.cpp, src/Gui/Dialogs/DlgThemeEditor.cpp, src/Gui/Dialogs/DlgThemeEditor.h, src/Gui/Dialogs/DlgThemeEditor.ui, src/Gui/OverlayManager.cpp, src/Gui/PreCompiled.h, src/Gui/PreferencePackManager.cpp, src/Gui/PreferencePages/DlgSettingsUI.cpp, src/Gui/PreferencePages/DlgSettingsUI.h, src/Gui/PreferencePages/DlgSettingsUI.ui, src/Gui/StyleParameters/ParameterManager.cpp, src/Gui/StyleParameters/ParameterManager.h, src/Gui/StyleParameters/Parser.cpp, src/Gui/StyleParameters/Parser.h, src/Gui/Tools.h, tests/src/Gui/CMakeLists.txt, tests/src/Gui/StyleParameters/ParameterManagerTest.cpp, tests/src/Gui/StyleParameters/ParserTest.cpp, tests/src/Gui/StyleParameters/StyleParametersApplicationTest.cpp
This PR introduces a powerful, extensible system for defining and managing UI theme parameters, enabling dynamic styling and user-driven customization across FreeCAD’s interface. The highlight is the new Theme Editor, offering a user-friendly way to create, modify, and preview visual tokens such as colors, lengths, and expressions.
- **Parameter-Based Styling Infrastructure**:
- Introduces a simle expression language for QSS variables (e.g. `@PrimaryColor`, `@Padding * 2`).
- Supports typed values (lengths, colors, strings), arithmetic and color expressions.
- Includes syntax support for basic math and color transformations (e.g. `darken()`, `lighten()`).
- Adds `ParameterManager` for consistent resolution of nested expressions with dependency tracking.
- **User-Editable Theme Tokens**:
- …
=> Gui: Add Style Parameter Manager to contain theme parameters

src/Mod/BIM/ArchStructure.py, src/Mod/BIM/bimcommands/BimProfile.py, src/Mod/Draft/draftutils/params.py
Fixes #22215.
Arch_Profile should not have an 'empty' option in the profile categories list.
Preset is stored in a dedicated parameter: ProfilePreset.
Additonally:
Minor change of ArchStructure.py.
=> BIM: fix profile selection

src/Mod/BIM/ArchComponent.py
Fixes #19595.
PR to make the visibility of objects hosted by additions depend on the visibility of the parent. This solution is preferable to changing Hosts properties. The latter solution would be hard to undo in case additions are removed.
=> BIM: fix visibility handling of objects hosted by additions

src/Mod/CAM/Path/Op/Gui/Array.py
Lets show warning for "old" Array only while create new one
Not every time after open document and recompute
https://github.com/user-attachments/assets/b91aebd9-c817-4fa9-a7a9-134f4e34262a
In this example Array used not like array, but for combine several operations and place each copy in different place
=> CAM: Changes in warnings of old Array

src/Mod/Draft/draftfunctions/downgrade.py
Part Lofts and Sweeps were not recognized as parametric objects and therefore immediately split into faces instead of being de-parametrized first.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=98271
=> Draft: 1st downgrade of lofts and sweep should be de-parametrization

src/Mod/Draft/importDXF.py, src/Mod/Import/App/dxf/ImpExpDxf.cpp, src/Mod/Import/App/dxf/ImpExpDxf.h, src/Mod/Import/App/dxf/dxf.cpp, src/Mod/Import/App/dxf/dxf.h, src/Mod/Import/Gui/AppImportGuiPy.cpp, src/Mod/Import/Gui/dxf/ImpExpDxfGui.cpp, src/Mod/Import/Gui/dxf/ImpExpDxfGui.h
This pull request introduces an enhancement to the C++ DXF importer, adding structured support for `BLOCK` and `INSERT` entities. 
*   **Nested block support:** the importer now handles nested block definitions (blocks that contain `INSERT`s of other blocks). It preserves the parametric hierarchy by creating `Part::Compound` objects for block definitions which, in turn, contain `App::Link`s to their nested components. [Learn more about BLOCKs and INSERTs](https://wiki.freecad.org/DXF#BLOCKs_and_INSERTs).
*   **Parametric/flattened import selection:** the existing **"Group layers into blocks"** import preference controls how blocks and assemblies are imported:
1.  **Parametric block assembly (unchecked):** creates reusable, hidden block definitions (`Part::Compound`) and represents …
=> Import: improve DXF C++ importer support for BLOCK and INSERT entities

pixi.lock, pixi.toml
Recent changes to `pixi.toml` were incompatible with older versions of `pixi` installed on some developers' machines.  Running `pixi self-update` updates the `pixi` version on the developer's machine, resolving the issue.
This PR adds `requires-pixi = ">=0.48"` to alert the user when they need to perform an upgrade to maintain compatibility.
* None.  Several developers noted the issue on Discord.
None.
=> Add requires-pixi to pixi.toml to specify minimum pixi version needed.

src/Mod/TechDraw/App/DimensionFormatter.cpp
As reported on the forum https://forum.freecad.org/viewtopic.php?t=98341 there was a regression in PR #19502 with regard to the plus/minus symbol having `Â` before it. This PR fixes that so it shows correctly as:
=> [TechDraw] fix regression from PR19502

src/Mod/Fem/App/FemConstraintContact.cpp, src/Mod/Fem/App/FemConstraintContact.h, src/Mod/Fem/femsolver/calculix/write_constraint_contact.py
fixes #22120
Adds two new properties to FEM Constraint contact. One to enable thermal contact and one to define its properties - a list of gap conductance values (optionally) paired with contact pressure and temperature. Due to the tabular nature of this definition, the same approach is used as for plasticity definition in FEM Material nonlinear - a string list property allowing direct definition using CalculiX syntax for this advanced feature.
=> FEM: Add thermal contact with CalculiX

src/Gui/NaviCube.cpp
In https://forum.freecad.org/viewtopic.php?p=835495#p835495 there are reports of FreeCAD crashing after idle or sleep. I have not been able to reproduce it but it may be related to the NaviCube frame buffer being invalid. So I added some code that recreates the frame buffer if it is invalid.
=> Gui: NaviCube recreate frame buffer if invalid

src/Gui/ToolBarManager.cpp, src/Gui/ToolBarManager.h
Fix https://github.com/FreeCAD/FreeCAD/issues/13927
The issue came from this line 
https://github.com/FreeCAD/FreeCAD/blame/1881686e7233da28da105885c931d02c30f25593/src/Mod/Sketcher/Gui/Workbench.cpp#L207
The fix is to save only if the value has changed. This way we avoid saving the 'Sketcher' toolbar visibility, which was triggering a 100ms timer and which set the toolbar back to visible.
=> Sketcher: Fix #13927

src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp, src/Mod/Sketcher/Gui/TaskSketcherConstraints.h
Fixes #9476 and #9373
It fixes the problem, that "Special Filters" of constraints are not applied correctly.
To reproduce the bug see https://github.com/FreeCAD/FreeCAD/issues/9476#issuecomment-2017384091
The problem was when initializing the filters all special filters were initialized and the first special filter (selected constraints) disabled the second filter (associated constraints). Then the second filter was initialized (which was disabled) and reset the specialFilterMode variable to none. However the selected constraints checkbox stayed checked but the filtermode for selected constraints was not enabled..
While testing I found another problem. The show only filtered constraints checkbox from the settings button also doesn't work correctly. If there are no filtered constraints and …
=> Sketcher: Fix Constraint Filter Handling

src/Mod/Sketcher/App/planegcs/Constraints.cpp, src/Mod/Sketcher/SketcherTests/TestSketcherSolver.py
Fix https://github.com/FreeCAD/FreeCAD/pull/22023#issuecomment-3009830019
Negative distances are allowed again but act as positives.
=> Sketcher: manage legacy negative circle-line distance

package/rattler-build/recipe.yaml
I missed the weekly build dependencies in #22322.
This PR aligns the weekly build with VFX Reference Platform:
* numpy==1.26
* Qt==6.8
#22497
N/A
=> CI: Update weekly build dependencies for VFX Reference Platform.

src/Mod/CAM/Path/Op/Drilling.py
Copied initial change from #22299. Also see [my comment](https://github.com/FreeCAD/FreeCAD/pull/22299#issuecomment-3035171299).
TLDR: this results in an extra move down if `KeepToolDown = False` and is redundant in all cases since there is still a move to clearance height after this move from Base.py (L790-L792).
=> CAM: remove redundant move after drilling

src/Mod/Part/App/PartFeature.cpp
Fixes: non-planar faces of https://github.com/FreeCAD/FreeCAD/issues/11234
Implement align to selection for a single non-planar face selection.
@Rexbas could you please take a look?
=> Part: Align to selection - implement for 1 non-planar face selection

src/Gui/PreferencePacks/FreeCAD Dark/FreeCAD Dark.cfg, src/Gui/Stylesheets/FreeCAD.qss
Changed the TreeActiveColor value in the FreeCAD Dark preference pack for improved visibility. Set the QTabBar background color to use @PrimaryColor in the stylesheet for fixing drawbase issues.
Tabbar fix:
Treeview fix:
How it is now:
too:
=> [Stylesheet] Update dark theme tree color and tab bar background

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.h
Fix https://github.com/FreeCAD/FreeCAD/issues/10027
replace Mode = XXX by the setter setSketchMode.
Add testActive to setSketchMode so that the commands show the correct activation state
Now we have the intended behavior from Abdullah's code. The tools get deactivated when you start a box selection, or when you drag something. And more importantly the bug is gone.
Now having said that this looks kind of like a christmas tree to have the icons blinking activated / deactivated... So I am not sure we actually really want this.
=> Sketcher: Fix random gray icon

src/Base/Tools.cpp
`toTimeSpec` was deprecated in Qt 6.9 in favor of `toTimeZone` (added in Qt 5.14).
=> Base: Switch from toTimeSpec to toTimeZone for Qt 6.9 compatibility

src/Mod/BIM/bimcommands/BimBox.py
PR to make the handling of the mentioned inputs consistent with that of the X, Y and Z inputs: check for in-command shortcuts. and select only the numerical portion of the text on focus change.
=> BIM: BimBox: improve length, width and height inputs

src/Mod/CAM/Path/Op/Adaptive.py
Fixes #22073
Apparently there's some imprecision in `BoundBox.ZMax`, so the naive check of `depth < x.BoundMox.ZMax` is insufficient to ensure that slicing at `depth` will result in a valid shape- sometimes off by O(1e-14). This PR changes that check to use the operation tolerance to ensure a valid shape is returned when we try to slice the stock.
=> CAM: Adaptive: Fix NULL input shapes when top of stock equals top of model

src/Mod/TechDraw/App/CenterLine.cpp
In C++ `new` doesn't return a `nullptr` when it fails, it throws a `badalloc` exception. So the check for a null result here is misleading, it's never true. If the allocation fails, an exception is thrown, presumably to be handled by a very high level method that ultimately shuts FreeCAD down (if this allocation fails we are basically out of memory).
=> TD: Remove incorrect allocation failure handler

src/Gui/Action.cpp, src/Gui/Action.h, src/Mod/Start/Gui/StartView.cpp
Related to #12842.
This commit adds:
- The "_Clear Recent files_" item to the list of recent files in the menu
- A signal, notifying that the list of recent files has been changed
- Connects _StartView_ with this signal, so whenever a file is loaded, the _StartView_ widget is updated accordingly.
The thing here is that when the workbench is created, the menu is still on the way. I set a timer to connect to this signal later. If somebody knows a better option, let me know.
=> Add "Clear Recent files list" item

src/Mod/CAM/PathSimulator/AppGL/GuiDisplay.h, src/Mod/CAM/PathSimulator/AppGL/MillSimulation.cpp
Silence compiler warnings about missing these fields.
=> CAM: Add missing initializers

tests/src/App/Application.cpp, tests/src/App/Expression.cpp, tests/src/Base/Axis.cpp, tests/src/Gui/Assistant.cpp, tests/src/Gui/Camera.cpp, tests/src/Mod/Material/App/TestMaterialFilter.cpp, tests/src/Mod/Mesh/App/Mesh.cpp, tests/src/Mod/MeshPart/App/MeshPart.cpp, tests/src/Mod/Part/App/TopoDS_Shape.cpp, tests/src/Mod/Part/App/TopoShapeCache.cpp, tests/src/Mod/Sketcher/App/Constraint.cpp
We've had an intermittent CI failure: using ASAN I was able to track it down to some tests that weren't initializing the application before running. While not 100% of these tests actually need to initialize the typesystem, etc., it's safer to just do so.
I also added the code needed to save and restore the Materials preferences so that those tests don't depend on the state of the user's preferences. This didn't affect CI, but could affect local runs.
=> Fix test initialization failure

src/Mod/BIM/ArchStairs.py
Related to #22436 and #22445.
It makes sense to also hide the base of the  stair railings.
=> BIM: hide base of railings

src/Base/Parameter.cpp
Fixes CWE-611, guards against XML external entity attacks.
=> Base: Disable default entity resolution

src/Mod/Assembly/App/AssemblyObject.cpp, src/Mod/Assembly/App/AssemblyObject.h, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
Fix #19319
The issue is that getUpstreamMovingPart was entering an infinite loop where the same joint would be selected over and over. I'm not sure why this happened only in the case of sub-assemblies as it sounds like something that should happen quite often.
Anyway it's fixed by making sure a joint is not traversed twice.
Also removes old & unused getUpstreamParts
=> Assembly: Fix infinite loop with subassembly. Fix #19319

src/Gui/CommandView.cpp, src/Gui/Document.cpp, src/Gui/Document.h, src/Gui/MDIView.cpp, src/Gui/MDIView.h, src/Gui/MainWindow.cpp, src/Gui/MainWindow.h, src/Gui/PreferencePages/DlgSettingsGeneral.cpp, src/Gui/TextureMapping.cpp, src/Gui/View3DInventor.cpp, src/Gui/View3DInventor.h, src/Gui/ViewProvider.cpp, src/Mod/TechDraw/Gui/ViewProviderPage.cpp, src/Mod/TechDraw/Gui/ViewProviderPage.h
Split from #22204 as that PR evolved out of the original scope. The discussion over there might still be relevant.
Currently the 3D viewer can be undocked and set to fullscreen, either via shortcut ("V, U" or "F11") or via "View" -> "Document window". This PR enables this functionality for all MDI widgets (Spreadsheet, TechDraw, Dependency Graph, Start Page, ...)
Edit:
closes #14545
=> Gui: Allow undocking and fullscreen for all MDI windows

package/rattler-build/conda_build_config.yaml, package/rattler-build/recipe.yaml, package/rattler-build/variants.yaml
Despite claims of compatibility with 'conda_build_config.yaml', rattler-build does not support all of the necessary capabilities to set the minimum macOS version. Converting the 'conda_build_config.yaml' to the rattler-build 'variants.yaml' corrects the issue.
* #22501 
None.
=> CI: fix macOS on x86_64 weekly builds

src/Mod/Part/App/TopoShapeExpansion.cpp
Fix #22733 by making sure that the resolved `Geom_Curve` is valid before checking if it is linear. There are several alternative places where we could be checking this, and/or handling the exception that is raised if we fail to check this. I picked what seemed to be the least intrusive option.
=> Part: Add error handling to TopoShape::isLinearEdge

src/Gui/Application.cpp, src/Gui/ViewProviderFeaturePython.cpp, src/Gui/ViewProviderFeaturePython.h, src/Mod/Assembly/App/AssemblyObject.cpp, src/Mod/Assembly/Gui/ViewProviderAssembly.cpp, src/Mod/Assembly/Gui/ViewProviderAssembly.h, src/Mod/Assembly/JointObject.py
Fix https://github.com/FreeCAD/FreeCAD/issues/22643
use the same icon overlay as the Part 'unnatached'.
See the joints icons in the screenshot :
The warning is then removed.
=> Assembly: unconnected joints: icon overlay instead of annoying warning.

src/Gui/TaskView/TaskView.cpp, src/Gui/TaskView/TaskView.h
Add a framework to be able to add a permanent taskbox that does not impact the active dialog.
This way we can add a taskbox that does not conflicts with tools.
For example when an object is in edit we can add a taskbox. Then remove it when the object is not in edit anymore.
This is a pre-requisit to fix the DoF report in assembly (https://github.com/FreeCAD/FreeCAD/issues/18406)
=> TaskView: Add 'Permanent task box' framework.

src/Gui/Icons/Std_SelectGroupContents.svg, src/Gui/Icons/resource.qrc, src/Gui/ViewProviderDocumentObjectGroup.cpp, src/Gui/ViewProviderDocumentObjectGroup.h
Adds a context menu item globally for groups, to be able to select their contents at once.
This is especially useful for groups containing hundreds of objects that scroll past the tree view's viewport. But also for smaller groups, it reduces the operation to two pointer device clicks (as opposed to having to use the keyboard additionally to do a multi-selection).
There was some prior implementation of this feature via the [Draft_SelectGroup](https://wiki.freecad.org/Draft_SelectGroup) command. This PR enhances the behaviour by:
- Making the command available globally to all workbenches, not only Draft and BIM
- Selecting items recursively: if a group where the command is executed upon contains subgroups, the subgroups' items will be selected as well
Fixes: …
=> Gui: add 'Select group contents' context menu item

src/Gui/ApplicationPy.cpp, src/Gui/ApplicationPy.h, src/Gui/WaitCursor.cpp, src/Gui/WaitCursor.h, src/Mod/Draft/CMakeLists.txt, src/Mod/Draft/DxfImportDialog.py, src/Mod/Draft/Resources/Draft.qrc, src/Mod/Draft/Resources/ui/preferences-dxf-import.ui, src/Mod/Draft/Resources/ui/preferences-dxf.ui, src/Mod/Draft/importDXF.py, src/Mod/Import/App/dxf/ImpExpDxf.cpp, src/Mod/Import/App/dxf/ImpExpDxf.h, src/Mod/Import/App/dxf/dxf.cpp, src/Mod/Import/App/dxf/dxf.h, src/Mod/Import/Gui/AppImportGuiPy.cpp
This is yet another step towards achieving feature parity with the DXF legacy importer, with the ultimate goal of deprecating it and having only one importer.
Goals:
- Improve the UX for importing DXF files
- Streamline the options for import: both from a user (simplify import process), and developer POV (simplify code and maintainability) 
- Narrow down the feature gap between modern and legacy importer
Changes:
- Redesigns, enhances and simplifies import modes and settings
- Adds dedicated DXF import dialog to avoid loading the full settings page. Shows UI warning if the imported file exceeds a given entity count threshold, combined with a higher fidelity import mode
- Adds Part primitives import mode, as a middle ground between performance and import fidelity
- Adds Draft objects …
=> Redesign DXF import UI, add Part primitives and Draft object import modes

src/Mod/Draft/draftguitools/gui_arcs.py, src/Mod/Draft/draftguitools/gui_beziers.py, src/Mod/Draft/draftguitools/gui_ellipses.py, src/Mod/Draft/draftguitools/gui_mirror.py, src/Mod/Draft/draftguitools/gui_offset.py, src/Mod/Draft/draftguitools/gui_points.py, src/Mod/Draft/draftguitools/gui_polygons.py, src/Mod/Draft/draftguitools/gui_rectangles.py, src/Mod/Draft/draftguitools/gui_rotate.py, src/Mod/Draft/draftguitools/gui_snapper.py, src/Mod/Draft/draftguitools/gui_splines.py, src/Mod/Draft/draftguitools/gui_trimex.py
The MouseDelay sets a point value to None. In some cases this point was then still used resulting in attribute errors.
See:
https://github.com/FreeCAD/FreeCAD/issues/19531#issuecomment-2651341711
=> Draft: fix handling of MouseDelay

src/Mod/TechDraw/App/DrawBrokenView.cpp, src/Mod/TechDraw/App/DrawBrokenView.h
This PR implements a fix for issue #22632.  It allows BrokenView to handle Shells, Faces, Wires and Edges in addition to the Solids (and aggregates such as Compounds).
=> [TD]fix BrokenView does not handle shells

src/Mod/Assembly/Gui/CMakeLists.txt
A PathGui was in the assembly cmakelists.
To be honest I am not sure what this line is about. But it would not make sense for it to be PathGui.
@chennes perhaps you know better?
=> AssemblyGui: CmakeLists typo

package/rattler-build/osx/create_bundle.sh, package/rattler-build/pixi.lock, package/rattler-build/recipe.yaml, package/rattler-build/scripts/fix_macos_lib_paths.py
There were two issues affecting importing `numpy`:
1. RPATHs were not being fixed up due to not passing `-r` to fix-up recursively
2. Missing symbols in `libcblas.dylib`
The Apple Accelerate BLAS libraries do not provide symbols that `numpy` attempts to use.  Switching to OpenBLAS will resolve this issue, although the BLAS routines are substatially less performant on Apple silicon.
Ideally, in the future, the Accelerate libraries containing the CBLAS symbols will be available.
* #22497
None.
=> Fix numpy on macOS Weekly Builds

src/Mod/Assembly/App/AssemblyObjectPyImp.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/22815
The bug was caused by the unsuspecting https://github.com/FreeCAD/FreeCAD/pull/22711
The reason is that in the isActive it's doing getJointsOfType. Which is doing assembly.Joints. Which is calling through the python interface assembly->getJoints().
The issue is that getJoints by default recompute the joints which triggered some sort of update loop.
@chennes
=> Assembly: Fix 22815

src/Gui/Dialogs/DlgAddPropertyVarSet.cpp, src/Gui/Dialogs/DlgAddPropertyVarSet.h
This PR adds supports for adding enum items directly in the VarSet add property dialog.
Closes #15553.
It was not possible to add a value to an enumeration property. It was necessary to create the property, then go to the property view, show the hidden properties and then edit the `Enum` property.
https://github.com/user-attachments/assets/db0f7646-35d5-49f3-8700-57be60e20739
The VarSet add property dialog shows the editor for the Enum property immediately and it is possible to create enum items there.
https://github.com/user-attachments/assets/c951b0ae-7529-44bf-b8a8-8725c7521d1b
Note, that it is not possible to select the value of the property; that still needs to be done in the property view. Adding support for that, would be a considerable change to the dialog so for now I consider …
=> Gui: Support enum editor in VarSet dialog

src/Mod/Spreadsheet/Gui/SheetTableView.cpp
This pull request simplifies the code and adds icons to the context menu. Now it looks like this:
If somebody has icons to add to the menu, I can amend this commit.
=> [Spreadsheet] Add icons to the context menu

src/Mod/Part/Gui/DlgSettingsGeneral.cpp, src/Mod/Part/Gui/DlgSettingsGeneral.ui
As the title says. No clue why this variable was not available in preferences, but giving it to users allow them to stop Part Design workbench to switch to Tasks tab by default, everytime they switch workbench, which users claim to be annoying.
So this patch adds this preference under Part/Part Design.
Demo:
https://github.com/user-attachments/assets/5f14e0f5-0b82-4b33-b39d-9a6fe1050b16
Resolves: https://github.com/FreeCAD/FreeCAD/issues/13322
=> Part: Enable SwitchToTask as a preference

src/Gui/SoDatumLabel.cpp, src/Gui/SoDatumLabel.h
Fear not reviewers! This is mostly refactor task, as the logic for drawing constraints contained all the necessary stuff to extract it for selection additionally.
As the title says, this patch aligns selectability to what we actually draw, so from now on extension lines and arrowheads will be also selectable.
Basically moved part of the logic that draw<constraint> function had into separate functions and updated bounding boxes that Coin uses and selection geometry to also contain arrowheads and extension lines.
Demo:
https://github.com/user-attachments/assets/8c4bb5ca-6676-4643-98e6-c12ae30906b8
Resolves: https://github.com/FreeCAD/FreeCAD/issues/13132
=> Sketcher: Make SoDatumLabel constraints more interactable

src/Mod/PartDesign/App/FeatureLoft.cpp, src/Mod/PartDesign/PartDesignTests/TestLoft.py
Inspired by a9100c1425
Fixes #19183
Also reported in the forum:
https://forum.freecad.org/viewtopic.php?p=806495
https://forum.freecad.org/viewtopic.php?t=88234
The actual reason for the failure is that the new code uses `FaceMakerBullseye` method which expects coplanar wires.
The code was using `FaceMakerCheese` previously which changed in LinkStage with their commit [PD: use FaceMakerBullseye for feature Loft](https://github.com/realthunder/FreeCAD/commit/93ce3edfe7ff714d24fdfea3a0ae1dde10714f19) and was imported here with TNP mitigations.
As changing it back would cause different regressions, lets try different facemakers until one succeeds.
=> PD: Fix loft between curved faces

src/Mod/PartDesign/App/FeatureHelix.cpp
Sometime the helix shape is invalid due to self-intersecting or degenerated edges. The OCC ShapeFix_Solid is able to improve the shape quality so use it when the shape is detected invalid by the BRepCheck_Analyser.
Fix #22294
=> PartDesign: Try to auto-fix any invalid generated helix

src/Mod/BIM/ArchPanel.py
The parameter name has been changed from FontFile to ShapeStringFontFile. See #21054.
=> BIM: ArchPanel: FontFile parameter name has changed

src/Mod/Draft/draftguitools/gui_snapper.py
If snapping was off, and after clicking the first point of a new line (for example), the cursor would be a default arrow instead of the intended cross-shaped cursor.
Note that the arrow cursor is still displayed for a fraction of a second after this fix.
Related to #16559.
=> Draft: fix display of cross-shaped cursor

src/Base/Parameter.cpp, src/Base/PreCompiled.h
Even after adding `parser->setDisableDefaultEntityResolution(true);`, CodeQL flags a security warning about entity resolution, so the main work of this PR is to add an explicitly no-op entity resolver to completely block any problematic entity resolution. While modifying that method, I also switched from raw pointers to `std::unique_ptr`, and fixed a typo in a variable name.
=> Base: Clean up ParameterManager::LoadDocument

src/Mod/Draft/Resources/ui/dialogHatch.ui
Fixes #22790.
To keep the file button at the correct size a vertical bottom spacer is required.
=> Draft: fix size of file button in Hatch task panel

src/Gui/Dialogs/DlgAbout.cpp
Merge of #18599 accidentally didn't drop change to DlgAbout path. Nothing sets AboutImageDev congfig key, so partially revert it.
Fixes: #18599
=> Gui: Fix about image path

CMakePresets.json
Recent changes to 3Dconnexion SpaceMouse support requires setting the appropriate configuration to `FREECAD_3DCONNEXION_SUPPORT`.  This adds the the appropriate settings for macOS and Windows, which will fix support on the weekly builds.
* None
* N/A
=> CMake: add FREECAD_3DCONNEXION_SUPPORT to CMakePresets.json

src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp
I noticed that the bounding box depth in an empty scene with just a sketch did not always adjust to the highlight depth when a point was highlighted, causing the point to disappear because it was outside the coin clipping volume. I think there was a missing `finishEditing()` so I added it. This apparently triggers the bounding box to have the correct depth. Basically fixing #22216 again but in a better way. The original workaround (#22343) that adds more slack is still relevant for the axis cross and dimensions.
=> Sketcher: Add missing finishEditing() for points

src/Gui/StyleParameters/ParameterManager.cpp
Current output:
`Requested non-existent design token 'UserHighlight1Color'.Requested non-existent design token 'UserHighlight1Color'.Requested non-existent design token 'ToolbarButtonsPadding'.Requested non-existent design token 'ToolbarButtonsPadding'.`
versus with PR:
```
Requested non-existent design token 'ToolbarButtonsPadding'.
Requested non-existent design token 'ToolbarButtonsPadding'.
Requested non-existent design token 'UserHighlight1Color'.
Requested non-existent design token 'UserHighlight1Color'.
```
=> [Gui] Add carriage return to ParameterManager warnings

src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
Fixes #22758 and #22769
Reverts the fix for #9373 from #22072
The Option for only displaying constraints which are filtered in the constraint list and the button to switch some or all displayed constraints pursue conflicting goals. On the one hand you have some rules which constraints are displayed (the filtered list) and on the other hand the user can choose which constraints are displayed.
I reverted the fix for the filtered constraints to mitigate the crash.
In my opinion the option for the filtered constraints has to be removed or changed into a button where you display the filtered constraints in just the moment the button is pressed. 
n/a
=> Sketcher: Fix crash on set constraints to virtual space

src/Gui/View3DInventorViewer.cpp
This is the first step in fixing the issue https://github.com/FreeCAD/FreeCAD/issues/22317
The issue that is fixed here is that the original viewAll function was not excluding the SoSkipBoundingGroup in the first test.
Because the code that deactivate the SoSkipBoundinggroup : 
```
for (int i = 0; i < pathlist.getLength(); i++) {
SoPath* path = pathlist[i];
auto group = static_cast<SoSkipBoundingGroup*>(path->getTail());  // NOLINT
group->mode = SoSkipBoundingGroup::EXCLUDE_BBOX;
}
```
Was called after the initial check for empty bounding box.
So let's say you have an empty sketch in edit. The coin scene has the 2 axis which are in a SoSkipBoundingGroup. BUT the initial call to boundingbox finds a non-empty box. And so the function proceeds. Then the SoSkipBoundingGroup are hidden. And so …
=> Core: Fit all : Do not process SoSkipBoundingGroup

src/Mod/TechDraw/App/DrawComplexSection.cpp, src/Mod/TechDraw/App/DrawComplexSection.h, src/Mod/TechDraw/App/DrawViewDetail.cpp, src/Mod/TechDraw/App/DrawViewDetail.h, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/App/DrawViewPart.h, src/Mod/TechDraw/App/DrawViewSection.cpp, src/Mod/TechDraw/App/DrawViewSection.h, src/Mod/TechDraw/App/GeometryObject.cpp, src/Mod/TechDraw/App/GeometryObject.h, src/Mod/TechDraw/Gui/QGIViewPart.cpp
This PR implements a number of fixes to ComplexSection.  Specifically, it 
- improves handling of profile not orthogonal (+/-) to section normal
- fixes handling of profile not on same plane as section normals
- fixes the direction of section line arrows.
=> TechDraw: ComplexSection fixes

src/Mod/TechDraw/Gui/QGISVGTemplate.cpp, src/Mod/TechDraw/Gui/TemplateTextField.cpp, src/Mod/TechDraw/Gui/TemplateTextField.h
This PR implements a fix for issue #21855.  It corrects a situation where 
click handles were displayed when view frames were displayed, and when printing or exporting.
=> [TD]fix editable fields click handles

src/Mod/Sketcher/Gui/EditModeCoinManager.cpp, src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h, src/Mod/Sketcher/Gui/EditModeGeometryCoinConverter.cpp, src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp
This is second step in fixing https://github.com/FreeCAD/FreeCAD/issues/22317 (see first step https://github.com/FreeCAD/FreeCAD/pull/22873)
It moves the origin from the point set to it's own SoSkipBoundingGroup
This way fit all does not take it into account. And so it fixes https://github.com/FreeCAD/FreeCAD/issues/22317
It also fix https://github.com/FreeCAD/FreeCAD/issues/14005
=> Sketcher: Move root point to a SoSkipBoundingGroup

src/Mod/OpenSCAD/OpenSCADCommands.py
"tree view" should be "Tree View" considering all GUI elements are referenced in Title Case now.
=> OpenSCAD: tweak tooltips

src/Mod/OpenSCAD/OpenSCADUtils.py
When `openscadexecutable` parameter is empty some operations (like Mesh workbench -> Union, which uses OpenSCAD workbench internally) fail. You may see how it fails in screenshots section.
In OpenSCAD utils there was multiple places where `openscadexecutable` was loaded to get executable path. I've made it more consistent by using `getopenscadexe` function which was already there.
I don't know about any open issues on that topic, but I've found similar forum post https://forum.freecad.org/viewtopic.php?style=1&t=75375
Here is a screenshot with error when I try to apply Union operation to two mesh objects:
<details>
</details>
Here is the screenshot with patch applied, where Union operation succeeds:
<details>
</details>
=> OpenSCAD: fix executable path lookup

src/Gui/ToolHandler.cpp, src/Mod/Sketcher/Gui/CommandConstraints.cpp, src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
fixes https://github.com/FreeCAD/FreeCAD/issues/21926 and https://github.com/FreeCAD/FreeCAD/issues/23128
As seen from the image (at 200% scaling) neither the grouped constraints nor the tool indicator is cropped
This should fix the regressions introduced by https://github.com/FreeCAD/FreeCAD/pull/20594
=> Sketcher: fix cropping of some icons on hidpi screens

src/Mod/Part/Gui/DlgSettingsGeneral.ui, src/Mod/PartDesign/App/Body.cpp
Sets the default value for new bodies to allow multiple solids.
I am not aware of any issues with this preference enabled which was already in the stable 1.0 release. There are more issues with users trying to create features with multiple solids in a body where they just need to enable the property.
@kadet1090 let me know if this closes the issue https://github.com/FreeCAD/FreeCAD/issues/9747
=> PartDesign: Change default preference to enable compounds for PD bodies

src/Mod/PartDesign/Gui/CommandBody.cpp
"Select body" -> "Select Body":
=> PartDesign: Change 1 missed dialog title to Title Case

src/Gui/EditableDatumLabel.cpp
Simple fix for such a simple error I didn't see. Basically, `valueChanged` signal can result in EditableDatumLabel being deleted (for example, when we are on the last OVP and all of the OVPs have been accepted). This could result in crashes as reported in previous issues, because just after emitting this signal we were trying to use `this` pointer, which wasn't available anymore as we deleted EditableDatumLabel obj that was attached to it, so in essence we were dereferencing some random address.
Fix for that is simple - move the check for `hasFinishedEditing` flag to check locked appearance in `validateAndFinish` lambda, as it already does validation and this way we will avoid referencing internals (which could be deallocated) after emitting this signal.
@chennes @lagnat @ElementW is it …
=> Gui: Don't use this pointer after valueChanged in EditableDatumLabel

src/Mod/Sketcher/Gui/EditModeCoinManager.cpp
Revert https://github.com/FreeCAD/FreeCAD/pull/22941
After a long search on DPI, it appears that that PR was based on a wrong assumption and should be reverted. The `* 72 / dpi` was correct, it was turning pixels into points. While the other `* 96.0f / dpi` was indeed not needed. So https://github.com/FreeCAD/FreeCAD/pull/21098 did the correct job in leaving that while removing the other.
@chennes sorry for the back and forth
=> Sketcher: Revert DPI adjustment error #22941

src/Mod/Spreadsheet/Gui/PropertiesDialog.cpp
The crash happens because the UnitExpression is null and thus segfaults when trying to access the unit and scalar value. This fixes https://github.com/FreeCAD/FreeCAD/issues/23222
=> Sheet: Verify that UnitExpression is valid

src/Mod/Part/App/WireJoiner.cpp
When the the code for WireJoiner was copied over from RT's fork, it had a lint-warning and the decision was to replace the custom assertCheck with the standard assert: https://github.com/FreeCAD/FreeCAD/pull/12535#discussion_r1526647457
What the discussion missed was that RT used this to throw an exception which was then later caught to handle some errors. By substituting this custom assert-like-but-throw-exception-macro with the standard assert, this bailout mechanism instead terminates the program in debug and is completely missing in release.
While I agree with the previous review that we should try to remove this macro, I don't think it can be substituted with the other type of assert.
=> Part: Fix WireJoiner error handling

src/Mod/PartDesign/App/FeatureBoolean.cpp, src/Mod/PartDesign/App/FeatureChamfer.cpp, src/Mod/PartDesign/App/FeatureDraft.cpp, src/Mod/PartDesign/App/FeatureExtrude.cpp, src/Mod/PartDesign/App/FeatureFillet.cpp, src/Mod/PartDesign/App/FeatureGroove.cpp, src/Mod/PartDesign/App/FeatureHole.cpp, src/Mod/PartDesign/App/FeatureLoft.cpp, src/Mod/PartDesign/App/FeaturePipe.cpp, src/Mod/PartDesign/App/FeatureRevolution.cpp, src/Mod/PartDesign/App/FeatureTransformed.cpp
The "Result has multiple solids: that is not currently supported" error message has to be updated to reflect that it's currently possible to have multiple solids in a Body with proper settings.
The new text is: "Result has multiple solids: enable compounds in a Body"
=> PartDesign: Update error message about multiple solids

src/Mod/Draft/draftutils/params.py
In PR #22452 `import init_draft_statusbar` was removed from the head of the file and localized in a function. It was overlooked that two other function need that import as well.
=> Draft: fix regression in params.py

src/Gui/PreferencePages/DlgSettingsWorkbenchesImp.cpp
Change default WB list and default preferences to not include the highlighted WBs (can be activated in the preferences).
Without that, e.g.  a "<none>" Workbench shows up when restarting FreeCAD in safe mode, without menu, toolbars or WB switcher:
=> Gui: Change default WB list and default preferences

src/Mod/Fem/App/FemPostFilter.cpp, src/Mod/Fem/App/FemPostFilter.h
Adds a check if data is available in a pipeline before extracting it in onChanged calls. This prevents the vtk error observed in issue #22193 
@FEA-eng FYI
This fixes the occurrence of the bug with data at point mentioned in the issue report. The other mentioned issues with the contour filter I was unable to reproduce, hence not sure if it is affected.
=> FEM: Extract postprocessing data only if available. Fixes #22193

src/Gui/TaskView/TaskDialogPython.cpp
From @wwmayer https://github.com/wwmayer/FreeCAD/tree/issue_22863
Inside TaskDialogPython::clearForm() the interpreter may execute a lot of things where at the some point the GIL must be hold.
This very likely fixes https://github.com/FreeCAD/FreeCAD/issues/22863
=> Gui: Hold the GIL when clearing the form attribute

src/Mod/TechDraw/Gui/QGIViewPart.cpp, src/Mod/TechDraw/Gui/QGIViewPart.h
This PR implements a fix to issue #23175.
It removes an unnecessary signal for selection change and uses childItems() to track vertices instead of a local vector of pointers that may go stale.
=> [TD]fix crash in vertex show/hide

src/Mod/Material/App/CMakeLists.txt, src/Mod/Material/App/Exceptions.cpp, src/Mod/Material/App/Exceptions.h, src/Mod/Material/Gui/MaterialTreeWidget.cpp
This fixes #18168 and #18170. The former issue was worked around with #18271, but it can be reverted now.
Credits go to @wwmayer who initially thought that this could be the issue in https://github.com/FreeCAD/FreeCAD/issues/18168#issuecomment-2521716247.
=>  Split Material Exceptions.h into source and header

src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
Currently if user tries to use box selection while having transformed normal line to a construction line, the line becomes solid unless it gets moved or new geometry is created.
The root cause of that is the `draw(true, false)` call which uses outdated solver geometry where construction=false is being specified. Solver updates lazily, which results in construction lines in normal sublayer instead of construction.
So, this patch changes it to `draw(false, false)` after box selection. This ensures the redraw uses current SketchObject geometry with up-to-date construction flags. This should be safe, as box selection is purely visual and we do not need geometry calculations in this operation.
Demo before:
https://github.com/user-attachments/assets/1a784669-0be2-4e0b-ad58-37ec055fae8c
Demo …
=> Sketcher: Fix construction lines becoming solid after box selection

src/Mod/Fem/femsolver/calculix/write_step_output.py
Adds writing of result displacements from REF NODE and ROT NODE of rigid body constraint to ccx_dat_file. This is particularly useful when simulating torsion - to check the angle of twist.
=> FEM: Print rigid body reference point displacements

src/Mod/Material/MaterialEditor.py
Loading QIcon directly from bytes is not supported in Qt6 it seems, so this patch changes it to load it to pixmap first and then to QIcon directly.
Plus add some alternative options to avoid tracebacks for compatibility, as it seems that in Qt5 it either failed gracefully, or was able to load directly from string/bytes.
Demo:
https://github.com/user-attachments/assets/5e4d717b-fec0-47a6-90ba-620abe801155
Would be cool if somebody with qt5 at hand would test it.
Resolves: https://github.com/FreeCAD/FreeCAD/issues/23220
=> BIM: Load QIcon for Material Editor from bytes

src/Doc/CONTRIBUTORS, src/Doc/LICENSE.html, src/Gui/Dialogs/DlgAbout.cpp, src/Main/FreeCADGuiPy.cpp, src/Main/MainGui.cpp
- Removes the 1.0 addition and updates the contributors list.
- Changes main link in the about dialog to the main site (freecad.org) instead of Wiki Main_Page
- Apply text guidelines to the about dialog files
=> Gui: Update header in about dialog before the 1.1 release

src/Mod/Mesh/App/MeshPyImp.cpp
From @wwmayer https://github.com/wwmayer/FreeCAD/tree/issue_18823
Fixes https://github.com/FreeCAD/FreeCAD/issues/18823
=> Mesh: Fix crash MeshPy::setPoint & MeshPy::movePoint

src/Mod/Assembly/JointObject.py
Fix https://github.com/FreeCAD/FreeCAD/issues/23025
This way the label is updated even if the joint type is changed in the property view.
=> Assembly: Move label change logic to onChange

src/Mod/Draft/draftguitools/gui_selectplane.py
Fixes #23306.
The Report View message was changed to `_toolmsg`.  It will therefore only display for users who have enabled that preference.
Fixes #23307.
The selection issue was due to a timing problem. The mouse DOWN event triggered the Python code before the selection was updated, therefore the previous selection instead of the new selection was checked. To solve this the action was switched to the mouse UP event. This event does not trigger after a mouse click that results in a selection, the user has to finalize the command by clicking in an empty 3D View area (which is how it should work according to the documentation). Added advantage is that the user does not receive a warning after every selection change.
=> Draft: fix 2 issues with Draft_SelectPlane

src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
Fix https://github.com/FreeCAD/FreeCAD/issues/22267
By moving the constraint to the mouse position after validation.
=> Sketcher: Circle DSH: move diameter constraint. Fix #22267

src/App/Application.cpp, src/App/PropertyLinks.cpp, src/App/PropertyLinks.h, src/Mod/Part/App/WireJoiner.cpp
This will fix: https://github.com/FreeCAD/FreeCAD/issues/23249
This call is causing issue with PD bodies because when something like a sketch is checking it's references to other parts, it might error since the document isn't fully loaded yet
PropertyXLinks do not have this issue because the geometry it is referencing has already been loaded (it typically references linked geometry)
this isn't a perfect fix, i just don't want migration issues.
in the future we need to update propertylinks after all of the documents have been loaded. does anyone have any ideas on how to do this?
=> Toponaming: Remove updateElementReferences call in PropertyLinkSub

src/Gui/PreferencePages/DlgSettingsUI.ui, src/Mod/Part/Gui/DlgSettingsGeneral.ui
fix these warnings:
```
AutoUic: /home/runner/work/FreeCAD/FreeCAD/src/Gui/PreferencePages/DlgSettingsUI.ui: Warning: The name 'gridLayout' (QGridLayout) is already in use, defaulting to 'gridLayout2'.
AutoUic: /home/runner/work/FreeCAD/FreeCAD/src/Mod/Part/Gui/DlgSettingsGeneral.ui: Warning: The name 'verticalLayout_3' (QVBoxLayout) is already in use, defaulting to 'verticalLayout_31'.
```
=> Fix autouic warnings about duplicate names in ui files

src/Gui/FileDialog.cpp, src/Mod/Fem/Init.py
1. Fix crash in FileDialog::getSaveFileName
2. Fix file suffixes in FEM module
This fixes https://github.com/FreeCAD/FreeCAD/issues/23353
=> Exporting mesh to Z88 format no longer breaks all export and configs

src/Mod/PartDesign/App/Feature.cpp, src/Mod/PartDesign/App/FeatureBase.cpp
In versions prior to 1.0 there was never the requirement that the shape of a FeatureBase must contain a solid. This has changed with 7a4bc95d47 for no obvious reason. This requirement should be dropped again.
In versions prior to 1.0 the method Feature::getBaseShape() was used within the Pad feature to check if the base feature has a solid. This method throws an exception if the shape doesn't have a solid. Since version 1.0 the new method Feature::getBaseTopoShape() is used. As parameter a boolean is passed to either throw an exception or silently return a null shape in case of an error. The implementation of this function is inconsistent: If the parameter is false it throws an exception if the base feature's shape has no solid but if the parameter is true it doesn't check if the shape …
=> PD: Fix creation of pad from base feature

src/Gui/CommandDoc.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
As the title says, this allows selecting all geometries on the sketch with CTRL + A shortcut, plus also allows to select "Select All" option from Edit menu.
Demo:
https://github.com/user-attachments/assets/1aef2b64-c4d7-4028-b0be-57987ebd93a7
Resolves: https://github.com/FreeCAD/FreeCAD/issues/12746
=> Sketcher: Introduce Select All (Ctrl + A)

src/Mod/Mesh/App/PreCompiled.h
Mesh compilation fails on MSVC with PCH enabled because `boost::starts_with` is defined in a header not previously included in the PCH file.
=> Mesh: Add boost/agorithm/string.hpp to PCH

src/Mod/Draft/draftmake/make_hatch.py
As the title says - this patch adds autogroup to hatch, so when created it will be put in active group.
Before:
https://github.com/user-attachments/assets/f4f32f52-7a81-4447-989e-206c28fb15c8
After:
https://github.com/user-attachments/assets/3a09d599-3a36-4921-b647-0969dd35654a
Resolves: https://github.com/FreeCAD/FreeCAD/issues/23089
=> Draft: Call autogroup in make_hatch to put hatch in active group if any

src/Mod/Sketcher/Gui/CMakeLists.txt, src/Mod/Sketcher/Gui/StyleParameters.h, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
As the title says. I think it was missing, so currently right to left motion makes the box selection in Sketcher green with dashed lines, whereas motion from left to right makes it blue with solid lines.
Demo:
https://github.com/user-attachments/assets/7f0def32-cd0d-4db1-88db-257dc156084b
Resolves: https://github.com/FreeCAD/FreeCAD/issues/19248
=> Sketcher: Use different colors for touch/window selection

src/Gui/Selection/SoFCUnifiedSelection.cpp
I'm not sure this is suitable modification but, `SoNode::traversal` is bottle neck of mouse hover operation in importing DXF, like following.
As you can see the worst bottle neck is digging down `SoNode` tree, but I think that digging down does nothing since the selection is already done by `SoFCUnifiedSelection::handleEvent` (similar to selection). If so, mark the action handled to skip digging down and performance bottle neck is moving to ray pick action like this.
I opened this PR as draft because I'm not familiar with FreeCAD and Coin3D. Please tell me if the modification will break any feature.
rel: #17185
sa: https://github.com/coin3d/coin/issues/542 (ray pick action performance)
=> Gui: Mark mouse move action handled to skip digging nodes

src/Mod/Draft/draftguitools/gui_arcs.py, src/Mod/Draft/draftmake/make_arc_3points.py, src/Mod/Draft/draftmake/make_circle.py
See:
https://github.com/FreeCAD/FreeCAD/issues/22913#issuecomment-3152054244
The placement of 3 point arcs very often was unexpected and typically did not match the placement of circles created on the same working plane.
This PR updates the code to use the placement of the working plane to adjust the placement of the created arc.
Additonally:
* Avoided code duplication by just passing the edge from make_arc_3points to make_circle.
* Removed inconsistent map_mode argument from make_arc_3points and the cryptic code related to it. The handling of the support property is something that has to be reviewed for all Draft commands at some point though.
=> Draft: more logical placement for 3 point arcs

src/Mod/Sketcher/Gui/CMakeLists.txt, src/Mod/Sketcher/Gui/DrawSketchHandlerRotate.h, src/Mod/Sketcher/Gui/DrawSketchHandlerScale.h, src/Mod/Sketcher/Gui/DrawSketchHandlerTranslate.h, src/Mod/Sketcher/Gui/SketcherTransformationExpressionHelper.cpp, src/Mod/Sketcher/Gui/SketcherTransformationExpressionHelper.h
As the title says. Currently we do not copy expressions that were assigned to constraints to the geometry if we use sketcher tools like rotate or translate. So this patch adds it, by copying them and then reconstructing upon added geometry.
Demo:
https://github.com/user-attachments/assets/75e69185-b478-4220-83ec-886cb0292b64
Resolves: https://github.com/FreeCAD/FreeCAD/issues/22253
=> Sketcher: Copy expressions when rotating/moving geometry

src/Mod/TechDraw/Gui/QGIViewClip.cpp, src/Mod/TechDraw/Gui/ViewProviderViewClip.cpp, src/Mod/TechDraw/Gui/ViewProviderViewClip.h
This PR implements a fix for a situation where views that belong to a clip group may become impossible to drag if they are moved outside the clip rectangle.
The fix adds a property to ViewProviderViewClip that controls whether or not to display child views outside of the clip rectangle.
Current:
With fix and ClipChildren false:
=> [TD]allow finding child view outside clip rectangle

src/Gui/Navigation/BlenderNavigationStyle.cpp, src/Gui/Navigation/CADNavigationStyle.cpp, src/Gui/Navigation/InventorNavigationStyle.cpp, src/Gui/Navigation/NavigationStyle.cpp, src/Gui/Navigation/OpenCascadeNavigationStyle.cpp, src/Gui/Navigation/OpenSCADNavigationStyle.cpp, src/Gui/Navigation/RevitNavigationStyle.cpp, src/Gui/Navigation/SolidWorksNavigationStyle.cpp, src/Gui/Navigation/TinkerCADNavigationStyle.cpp, src/Gui/Navigation/TouchpadNavigationStyle.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.h
Fixes #22931 and similar problems in other navigation styles.
Fixes #18015.
Postpones resetting `hasPanned`, `hasDragged` and `hasZoomed` until the navigation mode changes from IDLE to something else or if all mouse buttons have been released. This preserves information about the last navigation action while in IDLE mode until all mouse buttons have been released. This is needed for the blender style because when panning with LMB and RMB if LMB is released the mode goes to IDLE. But to prevent showing the context menu after releasing RMB we must know if the user has panned before IDLE mode.
To prevent showing the context menu after rubber band selection in sketcher mode I added a boolean that if set, prevents showing the context menu until RMB is pressed down again. So if RMB is held down …
=> Navigation: Prevent showing context menu after panning or rubber band selection

src/App/Datums.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/23437
=> Core: Datums: Make getDirection and getBasePoint aware of LCS position

src/Mod/BIM/ArchStructure.py
Removes check on function parameters for height & length (first introduced in commit 5217b24), relying on values assigned in "obj".
If those params are present, they're assigned to "obj" anyway, so the check is redundant.
Fixes #22585
My first contribution to FreeCAD.
I couldn't see how the code this commit removes had any relevance to the pref added in 5217b24, and wondered if it was just an accidental inclusion from some other change @yorikvanhavre was working on at the time.
Naturally I'm happy to be corrected if I've missed something. 
Fixes #22585
=> BIM: Remove wrong IfcType for Column/Beam

src/Mod/Part/App/Attacher.cpp, src/Mod/PartDesign/Gui/SketchWorkflow.cpp, src/Mod/PartDesign/Gui/SketchWorkflow.h
Fix https://github.com/FreeCAD/FreeCAD/issues/22888
1 - The New Sketch command now detect if a sketch was selected. And if so it attach the new sketch to the selected one with ObjectXY mode.
2 - Before it was not possible to attach to an empty sketch (or body). But this is wrong because an empty sketch has a placement. So we should still have the modes 'ObjectXY' and so on available. This PR fixes that.
=> PartDesign: Enable selecting a sketch as base plane of another sketch

src/Mod/Mesh/Gui/RemeshGmsh.cpp, src/Mod/Mesh/Gui/RemeshGmsh.ui
fix #18801 by just calling `gmsh` so the user doesn't need to manually provide the executable path, we provide gmsh with most (all?) of our distributions so this gives a better user experience
=> Mesh: fix #18801 - simply call `gmsh` if gmsh executable path is empty

.clang-tidy
While the advice is good, the overwhelming majority of "do-while" warnings that come up in our codebase are macros using a standard pattern using a do-while loop to encapsulate the macro's work. Maintainers can manually address any actual use of `do...while` during code review.
=> Update clang-tidy checks to remove avoid-do-while

src/Mod/CAM/Path/Op/Vcarve.py
Under certain conditions (rotated model) the vcarve expression can output weird geometry:
[vcarve_issue.zip](https://github.com/user-attachments/files/22036290/vcarve_issue.zip)
The issue is the use of `Path.Command(... Z{}".format(..., newPosition.z))` in Vcarve.py. When `newPosition.z` is a very small value, e.g. -1.776357e-15, the E-15 is interpreted as a parameter instead of an exponent, resulting the following clearly wrong GCode:
```
G1 E-15.000000 F0.000000 X45.432000 Y5.000000 Z-1.776357
```
The solution is simple: use the dictionary constructor just as every other operation.
=> CAM: use dict constructor for Command in VCarve

src/Gui/Workbench.cpp, src/Mod/Measure/Gui/Command.cpp, src/Mod/Measure/Gui/QuickMeasure.h
* Clear status bar when switching off quick measure
* Activate quick measure by default
* Remove command from toolbar as there is currently no icon
Replace https://github.com/FreeCAD/FreeCAD/pull/23390
=> Measure: Fix quick measure command

src/Mod/CAM/Path/Post/Command.py
Probably in some places was changed case of strings
Added `casefold()` to fix #23516
=> CAM: Fix missed gcode save dialog

src/Mod/CAM/Path/Post/scripts/uccnc_post.py
UCCNC post-processor skip parameters for G2 and G3 commands
Fix #23185
=> CAM: Fix uccnc postprocessor for G2|G3

src/App/Application.cpp, src/App/ApplicationDirectories.cpp, src/App/ApplicationDirectories.h
The recent change to a versioned app directory broke Safe Mode because `mConfig` is no longer the source of truth for app directories. In the long term, safe mode should probably be directly integrated into the `ApplicationDirectories` class, but we are at an interim stage in the implementation of that class, where using `mConfig` directly is still supported (and used in various places). For 1.1 that is the intended behavior. Following the release further work is planned to *only* access directory information via the `ApplicationDirectories` class.
This also fixes a bug/misunderstanding between the definitions of "user home" and "app home".
Fixes #23566
=> App: Fix safe mode and home directory

src/Mod/Part/Gui/DlgSettingsGeneral.ui, src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp, src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
Hides the draggers when the type of the pad/pocket is not dimension and sets the correct dragger length after changing hole depth type.
This PR also removes a duplicate checkbox in the preferences menu that I added by mistake during a rebase.
=> PartDesign: fix the draggers for pad type and hole

src/Mod/Fem/App/FemConstraintInitialTemperature.cpp, src/Mod/Fem/App/FemConstraintInitialTemperature.h, src/Mod/Fem/femsolver/calculix/write_amplitude.py, src/Mod/Fem/femsolver/calculix/write_constraint_finaltemperature.py
follow-up on #23277
adds amplitude support for final temperature in the same way as done for multiple other constraints previously (last one was rigid body constraint in #22898)
=> FEM: Amplitude support for final temperature field

src/Mod/PartDesign/App/FeaturePolarPattern.cpp
When you have 3 occurences, you should have 2 spacings.
Currently you have 3 and the first one is ignored.
This was fixed in linear pattern, but somehow got forgotten to fix in Polar pattern.
=> PartDesign: Polar pattern: Spacings off by one.

src/Mod/Part/Gui/DlgExtrusion.cpp, src/Mod/Part/Gui/DlgRevolution.cpp
Do not copy visual of sketch when making an extrusion or revolution.
Fix https://github.com/FreeCAD/FreeCAD/issues/20076
Fix https://github.com/FreeCAD/FreeCAD/issues/23644
=> Part: do not copy visual of sketch

src/Gui/Dialogs/DlgExpressionInput.cpp, src/Gui/Dialogs/DlgExpressionInput.h, src/Gui/Dialogs/DlgExpressionInput.ui, src/Gui/ExpressionCompleter.cpp, src/Gui/ExpressionCompleter.h, src/Gui/QuantitySpinBox.cpp, src/Gui/SpinBox.cpp, src/Gui/Stylesheets/FreeCAD.qss, src/Gui/Widgets.cpp
**'Expression editor' usage is enhanced with better resize behavior. Expression input is changed from _line edit_ to _text edit_.**
'Expression editor' uses _line edit_ as input, which is not convenient for longer formulas. In practice, resizing the dialog works only horizontally:
When formula is longer, the dialog resizes horizontally, even out of screen. The same situation is with 'Result' label:
Instead of _line edit_, now fully resizable _text edit_ is used for input. It allows to resize input size if needed. Also, if formula gets longer, its text is being wrapped. 'Result' message was moved below input widget.
Similar mechanism is provided for 'Result' message. Long text is being wrapped. To avoid oversizing the dialog, 'Result' text is elided up to ~3 newlines.
Input completer was …
=> Core: Enhance 'Expression editor' input and resize behavior

src/Mod/Fem/App/AppFemPy.cpp, src/Mod/Fem/Gui/DlgSettingsFemExportAbaqus.ui, src/Mod/Fem/Gui/DlgSettingsFemExportAbaqusImp.cpp, src/Mod/Fem/femobjects/mesh_gmsh.py
This PR changes some defaults for mesh export:
1. GroupsOfNodes property of the Gmsh mesher enabled by default (without it, node sets are not getting exported which can be confusing)
2. "Which mesh elements to export" preference set to FEM by default (it is usually expected that only the elements used for FEM analyses are exported)
3. "Export group data" preference enabled by default (it's really confusing that other formats get mesh groups exported by default while INP needs explicit setting for it)
=> FEM: Better defaults for mesh export

src/Mod/TechDraw/Gui/DimensionValidators.cpp, src/Mod/TechDraw/Gui/DimensionValidators.h
This PR corrects a situation where the check for horizontal/vertical dimensions gave the wrong result in some cases.
The check has been factored out of the various reference type cases, and all cases call the same code.
=> [TD]fix horizontal/vertical test for dimensions

src/Mod/Draft/draftguitools/gui_scale.py, src/Mod/Draft/drafttaskpanels/task_scale.py
Fixes  #19596
PR to remove the "Working plane orientation" checkbox from the 2nd task panel of the Draft_Scale command. This option does not work properly. There also does not seem to be a high demand for this feature as the current buggy implementation has gone unnoticed for several years.
See also:
https://github.com/FreeCAD/FreeCAD/issues/19596#issuecomment-3263689135
=> Draft: Remove relative to WP option from Draft_Scale

src/Mod/TechDraw/Gui/Workbench.cpp
Follow-up to #21483 -- there were a few places where these two commands were being added to the GUI and throwing warnings.
=> TD: Finish removal of Link and Landmark from GUI

src/Gui/Selection/SoFCSelectionContext.cpp, src/Gui/TaskElementColors.cpp
Reported in https://github.com/FreeCAD/FreeCAD/issues/23444#issuecomment-3241268211
There is a bug with transparency / alpha and it's getting switched back and forth. See bug in video : 
https://github.com/user-attachments/assets/428d086c-ccc8-4989-bcda-0ad3d0f47962
The reason is that since Base::Color is now ALPHA based, the colors need to be converted before packing for coin.
@kadet1090
=> Core: Fix alpha-transparency issue in face color override.

src/Mod/Sketcher/Gui/DrawSketchHandlerSymmetry.h
Removes unnecessary title case from here:
=> Sketcher: Remove redundant title case from task panel option of the Mirror tool

src/Mod/TechDraw/Gui/QGSPage.cpp
The TechDraw selections were not clearing due to the ProjGroup bounding rect absorbing clicks that should otherwise go to the sheet.
This PR adds QGIVProjGroup to list in QGSPage::itemClearsSelection() as per suggestion from @WandererFan in https://github.com/FreeCAD/FreeCAD/issues/23456#issuecomment-3242598144
Fix #23456
=> TechDraw: Fix selections not clearing

src/Mod/TechDraw/Gui/TaskDimension.cpp, src/Mod/TechDraw/Gui/TaskDimension.h, src/Mod/TechDraw/Gui/TaskDimension.ui
This PR adds 2 new options to the TechDraw dimension task panel.
1) A spinbox to adjust the number of decimal places in the dimension
2) A checkbox to make the dimension a reference ()
This PR also shuffles some of the 2 upper Group Boxes to be more logical in their arrangement. See before and after images.
Closes #23460
Before
After
This video demos the robustness of the tools. They are able to work around suffixes and prefixes
https://github.com/user-attachments/assets/c1a8b7e7-11e8-4ffd-8380-1ad242a878c8
This PR doubles on functionality from the commands "Increase/Decrease Decimals". However, the dimension task panel can only edit one dimension at a time. So commands should not be removed yet.
=> TechDraw: Add number decimals and reference dimension options to dimension task panel

src/Mod/CAM/Gui/Resources/panels/PageBaseHoleGeometryEdit.ui
Select by row instead of individal cells in the drilling panel:
=> CAM: select rows instead of cells in drilling panel

src/Mod/CAM/Path/Post/scripts/snapmaker_post.py
There is a bug in the library import of the snapmaker postprocessor. Without it line 814 will fail (https://github.com/FreeCAD/FreeCAD/blob/817ffc5782097bbd6534118178bc4d52a8b3c123/src/Mod/CAM/Path/Post/scripts/snapmaker_post.py#L814)
=> CAM: fix library import in snapmaker postprocessor

src/Mod/CAM/Path/Op/Adaptive.py
@sliptonic regression fix for the release
Fixes #22074 
I think this fix is comparable to the one @RiccaDS proposed and @dbtayl rejected (I'm not certain because it's hard to read the diff on the Adaptive.py zip file; I'm not sure what version to compare against). I developed this change from scratch, reading @dbtayl's PR that introduced model awareness and broke the adaptive profile feature.
In any case, I think this fix should be accepted. @dbtayl objected to Ricca's fix with "Above proposal doesn't respect model geometry, so it's not a drop-in solution as presented." and a screenshot of undesirable behavior when the profile is applied to a sloped surface. That objection applies equally to this PR, but I think this is the wrong way to see this outcome. As I see it, adaptive profile mode …
=> [CAM] regression fix: re-enable adaptive profile mode

.github/scripts/run_gui_tests.py, .github/workflows/sub_buildUbuntu.yml
**Summary**: ensure that on the GUI tests CI steps only GUI tests are run
The steps to run GUI unit tests on CI were unexpectedly running the full test suite, CLI and GUI, via this command:
https://github.com/FreeCAD/FreeCAD/blob/29dc9ebcdb8687299d8a3122a2695957514d9d55/.github/workflows/sub_buildUbuntu.yml#L209-L210
The `-t 0` argument is a shorthand for `TestApp.All`, which pulls all test modules, CLI and GUI. FreeCAD's test runner makes no distinction whether it's run in a CLI or GUI environment, it will run the full 1700+ tests suite.
This leads to unforeseen results with CLI tests running in a fully initialized GUI environment. For instance, getting ViewObjects attached when not expected. This can also be observed in any of the GUI tests logs and the multitude of exceptions and …
=> CI: run exclusively GUI tests in the GUI test steps

src/App/ApplicationDirectories.cpp, src/App/ApplicationDirectories.h, tests/src/App/ApplicationDirectories.cpp
Conda sometimes appends `\0` characters to paths: this explicitly looks for those nulls and truncates the string at them. This eliminates the somewhat mysterious-looking pass-through-c-string mechanism that was previously used in favor of a clearer (but probably slower) mechanism.
=> App: Sanitize all paths for null characters

src/Gui/ViewProviderFeaturePython.cpp, src/Gui/ViewProviderFeaturePython.h
This PR adds the python interface for beforeDelete for featurepythons.
I thought I needed it, but beforeDelete is actually called too late to fix the issue I had.
But since I wrote the thing might as well get it in.
=> Core: Add beforeDelete python interface.

src/Mod/CAM/Path/Dressup/Gui/Dragknife.py
The CAM dragknife dressup calculates the angles between subsequent paths and determines if it needs to maneuver the cutter around in order to make sharp corners.
The code calculates the vectors between any 2 movements (line vectors or arc tangent vectors) and subtracts them to determine how "sharp" the angle is.  Consider a vector at 350 degrees and the subsequent vector at 10 degrees.  The angle between them is 20 degrees however the existing code calculates it as 350 - 10 = 340 which is incorrect.  When the resulting calculation is greater than 180, it means it calculated in the wrong direction around the circle.
Fixes #21533
=> CAM: Dragknife dressup adds unnecessary maneuvers

src/Mod/CAM/Path/Dressup/Gui/LeadInOut.py
Fixes bug reported by @jffmichi in the [comments of another PR](https://github.com/FreeCAD/FreeCAD/pull/22669#issuecomment-3262169292)
That PR change properties on the LeadInOut dressup and provided migrations from the properties of the last stable version, but accidentally dropped a migration path from a newer version. This PR adds that migration path.
=> [CAM] add missing migration from intermediate version for lead in/out dressup

src/Mod/CAM/Path/Op/PocketShape.py
Currently the PocketShape operation defaults to a ZigZag Pattern, which I'm guessing isn't giving the result most people would expect (ZigZag leaves a wavy edge).
Change the default operation to the Offset Pattern does gives the expected results (Offset leaves a clean edge).
Similarly currently PocketShape defaults to a 100% StepOver, which is rarely if ever what anybody would want. Default to a value of something along the lines of 50% would be a bit more sensible.
Both these changes may prevent some confusion in new users.
Partially closes https://github.com/FreeCAD/FreeCAD/issues/23458
=> CAM: PocketShape defaults to Offset and 50% StepOver

src/Mod/Sketcher/App/SketchObject.cpp
Proposal to improve the `MakeInternals` property tooltip from Sketch objects for clarity.
Other suggestions welcome.
=> Sketcher: improve Make Internals property tooltip

src/Mod/Sketcher/Gui/DrawSketchController.h, src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
Fix https://github.com/FreeCAD/FreeCAD/pull/22862#issuecomment-3237460391
Instead of positioning at 1.3 * radius, we just use prevCursorPosition which is the last known mouse position.
=> Sketcher: Improve circle constraint position

src/Mod/Draft/draftguitools/gui_snapper.py
Fixes #24013.
If `update=True` the `WorkingPlane.get_working_plane()` function is too slow to be called repeatedly via `_get_wp`.
=> Draft: fix snapper lagging

src/App/ElementMap.cpp
Fixes: https://github.com/FreeCAD/FreeCAD/issues/14720
This stops the ElementMap file from adding extra sections like H,E when the amount of subElements in a face or wire increases to be more than or equal to 5
Also an issue in LS3
=> Toponaming: Don't add empty tags past the threshold.

src/Mod/CAM/Gui/Resources/panels/PathEdit.ui, src/Mod/CAM/Path/Main/Gui/Job.py
@sliptonic I put together a PR to reorder the job tabs to put the setup tab first. I'm not very invested in this, but if you want it, I think this PR works.
The ui file diff is hard to read because the diff algorithm is overzealous; what I actually did was move the "setup" tab to the beginning of QTabWidget's children. Besides for that, I updated QTabWidget's initial `currentIndex`, and updated indices in the corresponding python file so they still point at the same tabs.
=> [CAM] reorder job tabs to put Setup first

src/Mod/PartDesign/App/FeatureHole.cpp
when changing profile from none to for example iso metric, the find closest designation function has an issue where if the current thread pitch is 0 (true if profile is None) then it will select the lowest pitch designation, that is usually not what we want, instead in that case we should use the diameter only.
=> PD: hole prefer finding closest diameter if pitch is 0

src/Gui/Dialogs/DlgMacroExecuteImp.cpp, src/Gui/Dialogs/DlgPreferencePackManagementImp.cpp, src/Gui/PreferencePages/DlgSettingsGeneral.cpp, src/Gui/Workbench.cpp, src/Mod/Start/Gui/ThemeSelectorWidget.cpp
If the Addon Manager was not included in the build, was intentionally disabled, or failed to load, don't attempt to show the Addon Manager commands in the various places in the UI where it appears. This quiets down a stream of errors in the report view, and results in a better UX if the AM was disabled intentionally.
=> Gui: Remove references to the Addon Manager if no Std_AddonMgr

src/Mod/CAM/Path/Dressup/Gui/LeadInOut.py
Get error If path without rapid move in the end
=> CAM: LeadInOut - Fix for rapid move in end

src/Gui/ViewProviderLink.cpp, src/Mod/Part/Gui/ViewProviderExt.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/23444
@realthunder can you please evaluate this ?
The idea here is that it changes the MaterialOverride behavior. Instead of doing the limited general override, it's using the per-face mechanism on all faces.
=> Link: make OverrideMaterial use the per-face override.

src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp, src/Mod/Sketcher/Gui/CommandSketcherOverlay.cpp, src/Mod/Sketcher/Gui/CommandSketcherTools.cpp, src/Mod/Sketcher/Gui/Utils.cpp, src/Mod/Sketcher/Gui/Utils.h
Fix https://github.com/FreeCAD/FreeCAD/issues/19059
- Tools that need only constraint (select associate geometry)
- Tools that need only geometry (copy/cut/rotate/array...)
- Tools that need only bspline selection
- Tools that need only bspline knot selection (increase/decrease multiplicity).
Are now all active when they should
=> Sketcher: Fix is active.

src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
Fix crash on constraint selection generated by https://github.com/FreeCAD/FreeCAD/pull/24124
@chennes @kadet1090 this needs to get in ASAP as currently freecad crashes on constraint selection.
=> Sketcher: Fix crash on constraint selection

src/3rdParty/PyCXX/CXX/Python3/Config.hxx, src/3rdParty/PyCXX/CXX/Python3/Objects.hxx, src/3rdParty/PyCXX/CXX/Python3/cxxsupport.cxx, src/App/FeaturePythonPyImp.h, src/App/FeaturePythonPyImp.inl
Fixes (by @wwmayer):
```
In file included from src/3rdParty/PyCXX/CXX/cxxsupport.cxx:42:
src/3rdParty/PyCXX/CXX/Python3/cxxsupport.cxx:49:33: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
49 | Py_UNICODE unicode_null_string[1] = { 0 };
|                                 ^
In file included from /usr/include/python3.13/unicodeobject.h:1014,
from /usr/include/python3.13/Python.h:79,
from src/3rdParty/PyCXX/CXX/WrapPython.h:58,
from src/3rdParty/PyCXX/CXX/cxxsupport.cxx:37:
/usr/include/python3.13/cpython/unicodeobject.h:10:37: note: declared here
10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
|                                     ^~~~~~~~~~
```
and:
```
In file included from src/Mod/Part/App/PrimitiveFeature.cpp:48:
src/App/FeaturePythonPyImp.h:67:5: warning: missing …
```
=> Py3.13: fix warnings

src/Mod/Assembly/JointObject.py
Fixes: https://github.com/FreeCAD/FreeCAD/issues/23792
- Qt5: https://doc.qt.io/archives/qtforpython-5/PySide2/QtWidgets/QAction.html#PySide2.QtWidgets.PySide2.QtWidgets.QAction.setShortcut
- Qt6: https://doc.qt.io/qtforpython-6/PySide6/QtGui/QAction.html#PySide6.QtGui.QAction.setShortcut
The fix should work for both Qt5 and Qt6.
The Ubuntu CI job runs on Qt5, so I'm puzzled as to why [this test](https://github.com/FreeCAD/FreeCAD/blob/8e7e9c4bbc226917c328f67f653e42769b36b03e/src/Mod/Assembly/AssemblyTests/TestCore.py#L100) did not trigger the issue. @PaddleStroke happy to extend the test either on this PR or on a follow up, but I'd welcome some guidance.
=> Assembly: fix delete shortcut parameter mismatch

src/Gui/Stylesheets/FreeCAD.qss
And also on toolbar button hover.
Fixes: https://github.com/FreeCAD/FreeCAD/issues/22747
Restores the 1.0 behavior. See the 1.0 video in the linked issue for comparison.
https://github.com/user-attachments/assets/d77ff7e3-f24d-4613-a590-8d77ed112f30
[light.webm](https://github.com/user-attachments/assets/3885f9b9-f98b-49b6-9a3d-d54adf700254)
[dark.webm](https://github.com/user-attachments/assets/dead7933-da6b-4747-9698-0303f4c97e34)
=> Theme: bring back visual feedback on toolbar button press and hover

src/Mod/Fem/femcommands/commands.py
Fixes a small title case typo/inconsistency - all should be capitalized here despite being a 3-letter word
=> FEM: Fix small title case typo with "all"

src/App/ComplexGeoDataPyImp.cpp, src/Mod/Part/parttests/TopoShapeTest.py
https://github.com/FreeCAD/FreeCAD/issues/24204
Before: Failing test: `testPartCompoundCut2` due to Refine defaulted to True
After: Test pass
Also fixed `getElementReverseMap` (used in the tests)
=> Fix Refine in Cut Compound test

src/Mod/PartDesign/Gui/ViewProviderSketchBased.cpp
In some cases where placement of profile and feature was mismatched the profile was rendered in wrong orientation or place. This ensures that it is rendered in proper coordinate space.
| <img width="1228" height="968" alt="image" src="https://github.com/user-attachments/assets/dc46cb42-c02f-4d14-9258-0e2d265b86a3" /> | <img width="1109" height="1017" alt="image" src="https://github.com/user-attachments/assets/e2e87a26-7165-46c9-b0de-5241af42c489" /> |
=> Gui: Render profile preview in proper coordinate space

src/Mod/BIM/bimcommands/BimLibrary.py
Fixes #22437.
The task panel of the BIM_Library command would be linked to the active document, which would be the temporary Viewer document if that option was checked. Closing that document in the `insert` function would therefore also close the task panel resulting in errors for following code.
Additionally:
The code to close the temporary Viewer document was moved to the `reject` function. Otherwise that document would stay open if the task panel was closed without inserting.
=> BIM: fix linked document of BIM_Library task panel

src/Mod/TechDraw/Gui/QGILeaderLine.h, src/Mod/TechDraw/Gui/QGIView.cpp, src/Mod/TechDraw/Gui/QGIView.h
This PR implements a fix for a condition where a leader is displaced after an edit not involving position.
Current result of opening and closing the leader dialog:
Fix result:
=> [TD]fix uncommanded leader position change

src/Mod/PartDesign/App/FeatureLinearPattern.cpp, src/Mod/PartDesign/App/FeaturePolarPattern.cpp
Fix GCC warnings:
```
src/Mod/PartDesign/App/FeatureLinearPattern.cpp: In member function ‘void PartDesign::LinearPattern::updateSpacings(PartDesign::LinearPatternDirection)’:
src/Mod/PartDesign/App/FeatureLinearPattern.cpp:477:35: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
477 |     else if ((int)spacings.size() > targetCount) {
|              ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
src/Mod/PartDesign/App/FeaturePolarPattern.cpp: In member function ‘void PartDesign::PolarPattern::updateSpacings()’:
src/Mod/PartDesign/App/FeaturePolarPattern.cpp:329:35: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
329 |     else if …
```
=> PartDesign: Fix warnings

src/Gui/Icons/Std_SelectGroupContents.svg, src/Mod/Draft/Resources/icons/Draft_AddConstruction.svg, src/Mod/Draft/Resources/icons/Draft_AddNamedGroup.svg, src/Mod/Draft/Resources/icons/Draft_AddToGroup.svg, src/Mod/Draft/Resources/icons/Draft_AddToLayer.svg, src/Mod/Draft/Resources/icons/Draft_Construction.svg, src/Mod/Draft/Resources/icons/Draft_NewLayer.svg, src/Mod/Draft/Resources/icons/Draft_SelectGroup.svg
Part of [Draft/BIM - Icon updates task ](https://github.com/FreeCAD/FreeCAD/issues/13895) and [Draft: implement Draft_AddToLayer](https://github.com/FreeCAD/FreeCAD/pull/19427).
Icons used for the Draft Group and Layers are updated and simplified:
- `Draft_AddNamedGroup` is updated to use the similar Folder element as other Group icons.
- `Draft_SelectGroup` is updated to use the same element, with a cursor arrow and a green element like Box selection.
- `Draft_AddToGroup` is updated to use the same element, with plus and minus signs as this Tool can do both.
- `Draft_AddConstruction` and `Draft_AddToLayer` are slightly updated to be closer to the above.
- `Draft_NewLayer` is updated to use a similar plus sign as the New Document, New Techdraw Page and the updated `Draft_AddNamedGroup`. …
=> Draft: update Group icons

src/Gui/Application.cpp
The next version of Coin (4.0.6+) will be able to automatically detect GLX or EGL. So we don't need to explicitly inform Coin to use EGL anymore when on Wayland. https://github.com/coin3d/coin/pull/582. By automatically detecting GLX or EGL, Coin prevents accidentally mixing GLX and EGL which causes SIGSEGV like #23534 and #22695.
This basically reverts #21917. When using Coin 4.0.4 or 4.0.5 it is still needed to explicitly inform Coin to use EGL.
=> Don't inform Coin to use EGL for Coin 4.0.6+

src/Mod/Fem/Gui/TaskFemConstraintContact.cpp, src/Mod/Fem/Gui/TaskFemConstraintContact.ui, src/Mod/Fem/Gui/TaskFemConstraintDisplacement.cpp, src/Mod/Fem/Gui/TaskFemConstraintDisplacement.ui, src/Mod/Fem/Gui/TaskFemConstraintFixed.cpp, src/Mod/Fem/Gui/TaskFemConstraintFixed.ui, src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.cpp, src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.ui, src/Mod/Fem/Gui/TaskFemConstraintForce.cpp, src/Mod/Fem/Gui/TaskFemConstraintForce.ui, src/Mod/Fem/Gui/TaskFemConstraintHeatflux.cpp, src/Mod/Fem/Gui/TaskFemConstraintHeatflux.ui, src/Mod/Fem/Gui/TaskFemConstraintPlaneRotation.cpp, src/Mod/Fem/Gui/TaskFemConstraintPlaneRotation.ui, src/Mod/Fem/Gui/TaskFemConstraintPressure.cpp, src/Mod/Fem/Gui/TaskFemConstraintPressure.ui, src/Mod/Fem/Gui/TaskFemConstraintRigidBody.cpp, src/Mod/Fem/Gui/TaskFemConstraintRigidBody.ui, src/Mod/Fem/Gui/TaskFemConstraintSpring.cpp, src/Mod/Fem/Gui/TaskFemConstraintSpring.ui, src/Mod/Fem/Gui/TaskFemConstraintTemperature.cpp, src/Mod/Fem/Gui/TaskFemConstraintTemperature.ui, src/Mod/Fem/Gui/TaskFemConstraintTransform.cpp, src/Mod/Fem/Gui/TaskFemConstraintTransform.ui, src/Mod/Fem/femguiutils/selection_widgets.py
Last contributions moved long details about geometry selection to tooltip, which is good solution.
However, no visible text at all makes dialogs aesthetic and not very convienient.
See #21480 for more details.
Single line about type of selectable geometry was added. 
Longer details about selection are still shown in tooltip, when 'Add' button is hovered.
FEM Tasks, where geometry is to be selected, were harmonized to have same 'selection hint phrase'.
fixes #21480
=> FEM: Restore and harmonize FEM Task selection hints

src/Mod/Assembly/CommandCreateBom.py, src/Mod/Assembly/CommandCreateJoint.py, src/Mod/Assembly/CommandCreateSimulation.py, src/Mod/Assembly/CommandCreateView.py, src/Mod/Assembly/CommandInsertLink.py, src/Mod/Assembly/CommandInsertNewPart.py, src/Mod/Assembly/CommandSolveAssembly.py
Fix #24033
Strings created with `QT_TRANSLATE_NOOP` cannot ever be broken down into multiple calls because of the way that the translation system works. Any code that needs to use the `NOOP` call must produce a single translation string.
=> Assembly: Fix translatable strings

src/Mod/CAM/Path/Tool/shape/doc.py, src/Mod/CAM/Path/Tool/toolbit/models/base.py
Changing the Spindle Direction or Material in the tool library editor didn't work correctly.  You select the option and save, and option wouldn't stick.  The toolbit file would be updated correctly, but the UI wouldn't reflect the proper value.  This PR fixes this.
Also change the missing property log message from warning to debug.
Fixes: https://github.com/FreeCAD/FreeCAD/issues/22972
=> CAM: Fix SpindleDirection and Material not updating from toolbit files; reduce log noise

src/Mod/TechDraw/Gui/QGIView.cpp
Fix selections not clearing when subelements are also selected.
Fix #23998
https://github.com/user-attachments/assets/70684c78-b565-4dcf-93ef-0e97eef0f5ae
=> TechDraw: Fix selections not clearing when subelements are also selected

src/Mod/CAM/Gui/ViewProviderPath.cpp
This increases the default size.  Also checks for a float parameter in BaseApp → Preferences → Mod → CAM
DefaultArrowScale to allow customizing.
No preference has been added to the gui and this has not been tested on HiDPI.
@FreeCAD/design-working-group
=> CAM: increase direction arrow size.   Fixes #11163

src/Mod/Assembly/App/AssemblyObject.cpp
Fix https://github.com/FreeCAD/FreeCAD/issues/23901
Following @aiksiongkoh recommandations, to just assemble we should use the `runPreDrag` function. And it is actually redundant in our `AssemblyObject::preDrag` function
Tested and confirm it fixes the issue. The assembly solves without the warning.
=> Assembly: Fix errors on solve when limits

src/Mod/PartDesign/Resources/Hole/iso10642-fine.json
Reported on the forum:
https://forum.freecad.org/viewtopic.php?t=96250
Compare iso10642.json:
https://github.com/FreeCAD/FreeCAD/blob/efbe579e25b993a9a26ef45491387a19b14d1f59/src/Mod/PartDesign/Resources/Hole/iso10642.json#L8-L13
=> PartDesign: iso10642-fine.json wrong M5 diameter

package/rattler-build/build.bat
It contains the ThirdPartyLibraries.html file. Fixes #22989.
=> Build: Don't remove the doc directory

src/Mod/Sketcher/Gui/DrawSketchController.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArcSlot.h, src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h, src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h, src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h, src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h, src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h, src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h, src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h, src/Mod/Sketcher/Gui/DrawSketchHandlerRotate.h, src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h, src/Mod/Sketcher/Gui/DrawSketchHandlerTranslate.h
As the title says, currently if user tries to type "0", nothing gets typed because the OVP automatically invalidates the "0" as an invalid value in most of the cases.
The solution to that is to only validate it if user has finished editing OVP, not earlier when they are only typing.
Demo:
https://github.com/user-attachments/assets/c6a3bff1-90f8-40b6-99a4-1c1be8996479
Resolves: https://github.com/FreeCAD/FreeCAD/issues/22545
=> Sketcher: Unset labels that are below confusion point before enforcing

src/Mod/TechDraw/App/AppTechDrawPy.cpp, src/Mod/TechDraw/App/DrawPagePyImp.cpp, src/Mod/TechDraw/Gui/QGIProjGroup.cpp, src/Mod/TechDraw/Gui/ViewProviderPageExtension.cpp, src/Mod/TechDraw/Gui/ViewProviderViewClip.cpp
This PR implements a fix for #24052.
The PR also applies the isProjGroupItem() fix to the remaining uses of isDerivedFrom<DrawProjGroupItem>() which is no longer reliable after changes related to the "smart" view creation functions.
=> [TD]fix no dimension in DXF export

src/Mod/CAM/Path/Dressup/Gui/LeadInOut.py, src/Mod/CAM/PathPythonGui/simple_edit_panel.py
`Retract Threshold` in Task panel do not change property value
Fixed this
Also there is a mistake in `Mod/CAM/PathPythonGui/simple_edit_panel.py`
instead of `App:PropertyFloat` should be `App::PropertyFloat`
missed `:`
=> CAM: LeadInOut - Fix RetractThreshold in Task panel

src/Gui/CMakeLists.txt, src/Gui/InputHintWidget.cpp, src/Gui/MainWindow.cpp, src/Gui/MainWindow.h, src/Gui/StatusBarLabel.cpp, src/Gui/StatusBarLabel.h, src/Gui/Workbench.cpp, src/Mod/Measure/Gui/AppMeasureGui.cpp, src/Mod/Measure/Gui/Command.cpp, src/Mod/Measure/Gui/QuickMeasure.cpp
This makes it possible to toggle quick measure and input hints directly from status menu's context menu.
It also makes it possible to toggle status bar widgets when right clicking on a label in the status bar to make it easier for the user.
These changes was outlined in https://github.com/FreeCAD/FreeCAD/pull/23399#issuecomment-3235709419
fyi @wwmayer
=> Gui: Toggle quick measure and input hints from status bar context menu

src/Mod/BIM/bimcommands/BimViews.py
Fixes #17415
Fixes #17868
To avoid unnecessarily updating the trees an `oldData` list is used.
=> BIM: fix update behavior of BIM views panel

src/Mod/Sketcher/Gui/Workbench.cpp, src/Mod/Sketcher/Gui/Workbench.h
Fix https://github.com/FreeCAD/FreeCAD/issues/23931 by removing the edit tool toolbar as per @Roy-043 's preference
=> Sketcher: remove edit tools from toolbar

src/Gui/Dialogs/DlgActions.ui
Use folder icon as suggested in #24260. If the icon is not found, the fallback text now is "Choose ..." with the
button correctly sized.
Also renamed Pixmap to Icon
Fixes: https://github.com/FreeCAD/FreeCAD/issues/24260
=> Gui: Fix unreadable button in Customize Dialog

src/Mod/Part/Gui/ViewProvider.cpp, src/Mod/PartDesign/Gui/ViewProvider.cpp, src/Mod/PartDesign/Gui/ViewProviderBase.cpp
Somewhere in or around the switch from `FCMD_SET_EDIT` to `Gui::cmdSetEdit`, the setting of the current user edit mode was lost. This restores it (leaving any discussion about whether we *want* `userEditMode` for another time). Fixes #23777.
=> Part/PD: Send user edit mode to cmdSetEdit

src/Gui/TaskView/TaskAppearance.cpp, src/Gui/TaskView/TaskAppearance.h, src/Gui/TaskView/TaskDialog.cpp, src/Gui/TaskView/TaskDialog.h, src/Gui/TaskView/TaskDialogPython.cpp, src/Gui/TaskView/TaskDialogPython.h, src/Gui/TaskView/TaskEditControl.cpp, src/Gui/TaskView/TaskEditControl.h, src/Gui/TaskView/TaskSelectLinkProperty.cpp, src/Gui/TaskView/TaskSelectLinkProperty.h, src/Gui/TaskView/TaskSolverMessages.cpp, src/Gui/TaskView/TaskSolverMessages.h, src/Gui/TaskView/TaskView.cpp, src/Gui/TaskView/TaskView.h, src/Gui/TaskView/TaskWatcher.cpp, src/Gui/TaskView/TaskWatcher.h
Added missing / fixed existing SPDX license identifiers.
Didn't find any conflicting licenses.
Didn't touch the `.ui` files as I couldn't 
find a good way to specify it there.
=> SPDX [ 2 ][ Src / GUI / TaskView ]

src/Gui/QSint/actionpanel/actionbox.cpp, src/Gui/QSint/actionpanel/actionbox.h, src/Gui/QSint/actionpanel/actiongroup.cpp, src/Gui/QSint/actionpanel/actiongroup.h, src/Gui/QSint/actionpanel/actionlabel.cpp, src/Gui/QSint/actionpanel/actionlabel.h, src/Gui/QSint/actionpanel/actionpanel.cpp, src/Gui/QSint/actionpanel/actionpanel.h, src/Gui/QSint/actionpanel/actionpanelscheme.cpp, src/Gui/QSint/actionpanel/actionpanelscheme.h, src/Gui/QSint/actionpanel/qsint_global.h, src/Gui/QSint/actionpanel/taskgroup_p.cpp, src/Gui/QSint/actionpanel/taskgroup_p.h, src/Gui/QSint/actionpanel/taskheader_p.cpp, src/Gui/QSint/actionpanel/taskheader_p.h, src/Gui/QSint/include/QSint
Added missing SPDX license identifiers.
SourceForge project page only specifies 
`LGPLv3` not whether its `only` or `or-later`.
-> Went with the safe option ( `only` )
https://sourceforge.net/projects/qsint/
=> SPDX [ 8 ][ Src / GUI / QSint ]
