FreeCAD/FreeCAD

- src/Mod/Draft/WorkingPlane.py
- src/Mod/Draft/draftguitools/gui_selectplane.py
> Draft: possibility to set the working plane to an App::Part placement

- src/Mod/TechDraw/App/DrawProjGroup.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewPart.h
- src/Mod/TechDraw/App/GeometryObject.cpp
- src/Mod/TechDraw/Gui/QGIView.cpp
- src/Mod/TechDraw/Gui/QGIViewPart.cpp
> [TD]DPG spacing for oblique views

- src/Mod/TechDraw/Gui/QGISectionLine.cpp
> [TD]Section line symbol rotation

- src/Mod/Draft/CMakeLists.txt
- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftmake/make_text.py
- src/Mod/Draft/draftobjects/draft_annotation.py
- src/Mod/Draft/draftutils/gui_utils.py
- src/Mod/Draft/draftutils/units.py
- src/Mod/Draft/draftviewproviders/view_dimension.py
- src/Mod/Draft/draftviewproviders/view_label.py
- src/Mod/Draft/draftviewproviders/view_text.py
Various improvements in style, PEP8, spacing, docstrings.
The functions `getDefaultUnit`, `makeFormatSpec`, `displayExternal` are used to get the default unit schema for lengths and angles, and display a string with a particular format.
They aren't used in `DraftGui.py`, but are used by the viewprovider of the Dimension objects. Therefore, they are moved into a separate module, `draftutils/units.py`, so that they can be imported without using the entire `DraftGui` module.
In `ViewProviderDimensionBase` use methods to set up the properties. As the dimension object has 16 properties, these properties are assigned using three methods corresponding to text, units, and graphics properties.
In `ViewProviderLinearDimension` various improvements in style, PEP8, spacing, docstrings. In particular …
> Draft: improvements on the viewproviders for Dimension objects

- src/Gui/MainWindow.cpp
Forum thread: https://forum.freecadweb.org/viewtopic.php?t=36307  
Fixes #4372
> Fix regression SpaceBall model rotation stops when focus leaves 3D view panel

- src/Base/Quantity.cpp
> Fix comment in Quantity.cpp

- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
> [TD]makeCosmeticLine Y inversion

- src/Mod/PartDesign/Gui/Command.cpp
Allows making binder to another binder.
Requested https://forum.freecadweb.org/viewtopic.php?p=381858#p381858
> PartDesign: change SubShapeBinder make command

- src/Mod/Path/PathScripts/PathDressupZCorrect.py
> [Path] unhide the property for the interpolation surface

- src/Mod/Arch/ArchWall.py
Forum Discussion - https://forum.freecadweb.org/viewtopic.php?f=23&t=48275
---
> [ArchWall]  Fix #0004400 - Archwall creation from certain wire fails.

- src/Mod/TechDraw/Gui/QGIViewPart.cpp
> [TD]multiple faces in GeomHatch

- src/Mod/Arch/ArchWall.py
FC Forum Discussion -
https://forum.freecadweb.org/viewtopic.php?f=23&t=48668&sid=ba6dd68ad32eefbad6ae95d8fadc30e6#p416779
---
> [ArchWall] Failed if Sketch as Base has Point, now OK

- src/Mod/OpenSCAD/InitGui.py
- src/Mod/OpenSCAD/OpenSCADCommands.py
- src/Mod/OpenSCAD/OpenSCADFeatures.py
- src/Mod/OpenSCAD/OpenSCADUtils.py
- src/Mod/OpenSCAD/Resources/OpenSCAD.qrc
- src/Mod/OpenSCAD/Resources/icons/OpenSCAD_MirrorMeshFeature.svg
- src/Mod/OpenSCAD/exportCSG.py
https://forum.freecadweb.org/viewtopic.php?f=3&t=48736
---
> [Openscad] add new mirror mesh feature command, fix refine shape command

- src/Mod/Arch/ArchWindow.py
> Arch: fixed door open plan symbol  and make makeWindow use name parameter

- src/Mod/Fem/femguiutils/migrate_gui.py
- src/Mod/Fem/femsolver/writerbase.py
- src/Mod/Fem/femtools/migrate_app.py
> FEM: small changes

- src/Mod/Path/PathScripts/PathSurfaceSupport.py
> [Path] fix two never ending while loops in PathSurfaceSupport

- src/App/Document.h
- src/App/PropertyLinks.cpp
- src/App/PropertyLinks.h
- src/Mod/Cloud/App/AppCloud.cpp
- src/Mod/Cloud/App/AppCloud.h
- src/Mod/Cloud/CMakeLists.txt
ONLY enabled if the Cloud Module is compiled into FreeCAD
ALL files must be saved into a Cloud Based storage
Add a Signal to the PropertyLink to enable support of external storage
Signed-off-by: Jean-Marie Verdun <jmverdun3@gmail.com>
---
> Add App::Link support to Cloud module

- src/Mod/Arch/ArchAxis.py
> Arch: touch Axis when key property change

- src/Mod/Path/PathScripts/PathSurface.py
> coverity issue cid 305102

- src/Tools/offlinedoc/buildpdf.py
> coverity cid 192591 (fix typo)

- src/Mod/TechDraw/App/DrawGeomHatch.cpp
- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/DrawUtil.h
> [TD]fix misaligned PAT hatch on section

- src/Mod/TechDraw/Gui/CommandCreateDims.cpp
Add 2 shortcuts for dimensions as discussed here: https://forum.freecadweb.org/viewtopic.php?f=35&t=48980
> [TD] add 2 shortcuts for dimensions

- src/Mod/TechDraw/Gui/MDIViewPage.cpp
- src/Mod/TechDraw/Gui/QGIFace.cpp
- src/Mod/TechDraw/Gui/QGIFace.h
- src/Mod/TechDraw/Gui/QGIProjGroup.cpp
- src/Mod/TechDraw/Gui/QGIProjGroup.h
- src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
- src/Mod/TechDraw/Gui/QGIViewBalloon.h
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
> [TD]fix Dimension Selection issue + LGTM issues

- src/Mod/Path/PathScripts/PathPocketShape.py
- src/Mod/Path/PathScripts/PathPocketShapeGui.py
> [Path] handle makeOffset2D exception in path pocket operation

- src/Mod/TechDraw/Gui/MDIViewPage.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.h
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
> [TD]Dim blocks selection of geometry

- src/Mod/TechDraw/Gui/MDIViewPage.cpp
> [TD]Correct font size on PDF export

- src/App/DocumentPyImp.cpp
- src/Gui/DocumentPyImp.cpp
inspired by the changes made with https://github.com/FreeCAD/FreeCAD/commit/dc65b055e514
> [App/Gui] improve coding style

- src/Mod/Arch/importSHP.py
- src/Mod/TechDraw/Templates/zh_CN/landscape/A1_Landscape_CN_CLIP.svg
- src/Mod/TechDraw/Templates/zh_CN/landscape/A1_Landscape_CN_NO_CLIP.svg
https://crowdin.com/translate/freecad/6766/en-fr#6582288
> Crowdin - Fix typos found by translators + Random typos [skip-ci]

- src/Mod/PartDesign/Gui/TaskLinearPatternParameters.cpp
- src/Mod/PartDesign/Gui/TaskLinearPatternParameters.h
- src/Mod/PartDesign/Gui/TaskLinearPatternParameters.ui
- src/Mod/PartDesign/Gui/TaskMirroredParameters.cpp
- src/Mod/PartDesign/Gui/TaskMirroredParameters.h
- src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp
- src/Mod/PartDesign/Gui/TaskMultiTransformParameters.h
- src/Mod/PartDesign/Gui/TaskMultiTransformParameters.ui
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.cpp
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.h
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.ui
As discussed here: https://forum.freecadweb.org/viewtopic.php?f=27&t=48998#p420352
The pattern dialogs need a feature to change the order of the features to be patterned
> [PD] allow to change feature order in patterns

- src/Mod/PartDesign/App/FeatureTransformed.cpp
Reported in https://forum.freecadweb.org/viewtopic.php?f=3&t=48938
> PartDesign: fix pattern transformation

- src/Mod/TechDraw/App/DrawDimHelper.cpp
> [TD]Fix extent dim for edge collection

- src/Mod/Part/App/FaceMakerBullseye.cpp
Copy the shape to work around OCC circular edge transformation bug
Problem reported at https://forum.freecadweb.org/viewtopic.php?p=420252#p420252
> Part: fix FaceMakerBullseye plane finding

- package/fedora/freecad.spec
Signed-off-by: Elliot Lee <elliot.c.lee@gmail.com>
Tested-by: Przemo Firszt <przemo@firszt.eu>
- [N/A] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [N/A] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists
---
> Fix COPR rawhide builds

- src/Mod/TechDraw/App/DrawViewPartPy.xml
- src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
> [TD]add py getEdgeBySelection

- src/Mod/Part/Gui/ViewProvider2DObject.cpp
- src/Mod/Part/Gui/ViewProvider2DObject.h
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
> [GUI/Sketcher] Add option to disable grid auto-sizing based on shape boundbox

- src/Gui/ViewProviderPythonFeature.cpp
> Gui: fix ViewProviderPythonFeature::getLinkedViewProvider

- src/Base/CMakeLists.txt
- src/Base/UnitsApi.cpp
- src/Base/UnitsSchema.h
- src/Base/UnitsSchemaFemMilliMeterNewton.cpp
- src/Base/UnitsSchemaFemMilliMeterNewton.h
- src/Gui/DlgSettingsUnitsImp.cpp
- src/Mod/Fem/femsolver/elmer/writer.py
https://forum.freecadweb.org/viewtopic.php?f=10&t=48642
> Base: new FEM unit schema

- src/Tools/plugins/widget/customwidgets.cpp
- src/Tools/plugins/widget/customwidgets.h
- src/Tools/plugins/widget/plugin.cpp
as discussed here: https://forum.freecadweb.org/viewtopic.php?f=10&t=49315&p=422648#p42264
> [Tools] add PrefQuantitySpinBox to designer plugins

- src/Mod/Part/Gui/DlgProjectionOnSurface.cpp
Improve the projection on surface algorithm. For now the first possible solution was taken. If several solution exists, this leads to a miss match.
Now check the distance of the projection shape and the original shape and the take the projection with the smallest distance.
Discussion can be found here: https://forum.freecadweb.org/viewtopic.php?f=8&t=49341&p=422925#p422925
> Improve the projection on surface algorithm. see https://forum.freecadweb.org/viewtopic.php?f=8&t=49341&p=422925#p422925

- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewPart.h
- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/DrawViewSection.h
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
> [TD]fix showSectionEdge preference

- src/Mod/Draft/draftgeoutils/offsets.py
> [Draft - geoutils.offsets]  Fix Arc Circle Offset Direction and make Sketch works in Gui Draft Offset

- src/Mod/Draft/getSVG.py
> [Draft] Fix placement of rebar wires in Draft.getSVG.py

- src/Mod/Arch/exportIFC.py
- src/Mod/Arch/importIFC.py
- src/Mod/Arch/importIFCHelper.py
Continuation of #3756; small fixes and cleanup.
---
> Arch: small cleanup of IFC importer and exporter

- src/Mod/TechDraw/App/DrawGeomHatch.cpp
- src/Mod/TechDraw/App/DrawGeomHatch.h
- src/Mod/TechDraw/App/DrawHatch.cpp
- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/Gui/PreferencesGui.cpp
> [TD]handle bad preferences in AppImage temp dir

- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewPartPy.xml
- src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
- src/Mod/TechDraw/Gui/CMakeLists.txt
- src/Mod/TechDraw/Gui/CommandAnnotate.cpp
- src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
- src/Mod/TechDraw/Gui/Resources/icons/actions/techdraw-line2points.svg
- src/Mod/TechDraw/Gui/TaskCosmeticLine.cpp
- src/Mod/TechDraw/Gui/TaskCosmeticLine.h
- src/Mod/TechDraw/Gui/TaskCosmeticLine.ui
- src/Mod/TechDraw/Gui/Workbench.cpp
> [TD]draw line through 2 points

- src/Base/UnitsSchemaImperial1.cpp
- src/Mod/TechDraw/Gui/CommandCreateDims.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
> [TD]Angle Dim Format, Edge/Edge Dims, Degree Symbol

- src/App/GeoFeatureGroupExtension.cpp
- src/App/OriginGroupExtension.cpp
- src/App/OriginGroupExtension.h
Reported in https://forum.freecadweb.org/viewtopic.php?f=3&t=49753
> App: report error on copying OriginGroup without dependency

- src/Mod/TechDraw/App/DrawViewDimension.cpp
> [TD]fix V2E DistanceX,Y

- src/App/Application.cpp
- src/App/PropertyLinks.cpp
- src/Gui/Document.cpp
Reported in https://forum.freecadweb.org/viewtopic.php?f=20&t=40403&e=1&view=unread#p426321
Related to Zolko-123/FreeCAD_Assembly4#95
> App: fix PropertyXLink handling on symlink file path

- src/Mod/Mesh/App/Core/MeshIO.h
- [x ] Branch rebased on latest master `git pull --rebase upstream master`
- [ x] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
---
> fix build on Win

- src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp
> [TD]Allow single line S/S view

- src/Mod/AddonManager/addonmanager_workers.py
> [AddonManager] fix bug in CheckSingleWorker

- src/Mod/Draft/CMakeLists.txt
- src/Mod/Draft/Draft.py
- src/Mod/Draft/Resources/Draft.qrc
- src/Mod/Draft/Resources/icons/Draft_PathTwistedArray.svg
- src/Mod/Draft/Resources/icons/Draft_PathTwistedLinkArray.svg
- src/Mod/Draft/draftgeoutils/geo_arrays.py
- src/Mod/Draft/draftguitools/gui_arrays.py
- src/Mod/Draft/draftguitools/gui_pathtwistedarray.py
- src/Mod/Draft/draftmake/make_patharray.py
- src/Mod/Draft/draftobjects/patharray.py
- src/Mod/Draft/draftobjects/pathtwistedarray.py
- src/Mod/Draft/draftviewproviders/view_array.py
- src/Mod/Draft/draftviewproviders/view_draftlink.py
It takes a shape and replicates it around a path, while at the same time adding a rotation to each copy. This can be used to create a twisted "ribcage" from a frame-like object, which can be used in a more complicated shape, for example, a tunnel or bridge.
Forum thread: [PowerCopy in FreeCAD?](https://forum.freecadweb.org/viewtopic.php?f=23&t=49617)
---
> Draft: new PathTwistedArray object

- src/App/Document.cpp
- src/Gui/Command.cpp
- src/Gui/propertyeditor/PropertyEditor.cpp
- src/Gui/propertyeditor/PropertyEditor.h
Reported https://tracker.freecadweb.org/view.php?id=4265#c14271.
This PR also include a another transaction related fix.
> Fix transaction on view object changes

- src/Mod/Arch/ArchRebar.py
Fix issue reported here: https://forum.freecadweb.org/viewtopic.php?f=23&t=44580&start=290#p427770
---
---
> [Arch] Calculate length of rebar derived from Part::Helix

- src/Mod/Draft/draftfunctions/offset.py
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&p=427678#p336685
> Draft: Fix wire placement issue if Copy=False.

- src/Mod/Arch/ArchComponent.py
Fixes amrit3701/FreeCAD-Reinforcement#81
And it eventually will fix issue of this thread:
https://forum.freecadweb.org/viewtopic.php?f=23&t=49481
---
> [Arch] Skip rebar shape to be subtracted from structure

- src/Mod/Draft/draftfunctions/scale.py
The object should not be moved along the Placement.Base vector during the scale operation.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=38318&p=426390#p426372
> [Draft] Update scale.py

- src/Mod/Arch/ArchWall.py
- src/Mod/Arch/importIFClegacy.py
- src/Mod/Draft/CMakeLists.txt
- src/Mod/Draft/draftfunctions/offset.py
- src/Mod/Draft/draftguitools/gui_edit.py
- src/Mod/Draft/draftguitools/gui_edit_arch_objects.py
- src/Mod/Draft/draftguitools/gui_edit_base_object.py
- src/Mod/Draft/draftguitools/gui_edit_draft_objects.py
- src/Mod/Draft/draftguitools/gui_edit_part_objects.py
- src/Mod/Draft/draftguitools/gui_snapper.py
- src/Mod/Draft/draftutils/utils.py
> Draft: provide the possibility to extend support for Draft Edit in every object

- src/Gui/DlgPropertyLink.cpp
- src/Gui/ExpressionCompleter.cpp
- src/Gui/ExpressionCompleter.h
- src/Gui/Tree.cpp
- src/Gui/Tree.h
Reported in https://forum.freecadweb.org/viewtopic.php?f=3&t=49953
> Gui: allow change ExpressionCompleter filter mode

- src/Mod/OpenSCAD/OpenSCADCommands.py
- src/Mod/OpenSCAD/OpenSCADUtils.py
- src/Mod/OpenSCAD/exportCSG.py
- src/Mod/OpenSCAD/importCSG.py
---
Fixes OpenSCAD module import failures in a headless build.
> [OpenSCAD] consistent FreeCADGui imports, fixes headless CSG import

- src/Mod/Path/Gui/Resources/panels/PageBaseGeometryEdit.ui
> [Path] Enable for selection of multiple objects in Base Geometry list

- src/Mod/Draft/DraftVecUtils.py
Correct the Pythonic style for the changes made in ea16bb9394.
---
> Draft: small fixes to the closest function.

- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.h
- elements in the list of edges/spines/sections can now be deleted by pressing DEL and there is a context menu for this action
see https://forum.freecadweb.org/viewtopic.php?f=19&t=50222&p=431021#p431021
> [PD] add context menus to sweep Dialog

- src/Mod/Cloud/App/AppCloud.cpp
- src/Mod/Cloud/App/CMakeLists.txt
> Fix MacOS build with boost 1.73 and updated Homebrew packages

- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
See https://forum.freecadweb.org/viewtopic.php?p=432021#p432021
> HiDPI: Change Sketcher crosshair hot spot xy

- src/Mod/Sketcher/App/SketchObject.cpp
Implementation when circle plane orthogonal to projection plane.
Actually, 2 fails, 1 error, but not related to my changes... :+1: 
======================================================================
ERROR: test_pyimport_all_FEM_modules (femtest.app.test_common.TestFemCommon)
----------------------------------------------------------------------
File "/home/shermelin/src/freecad-build/Mod/Fem/femtest/app/test_common.py", line 143, in test_pyimport_all_FEM_modules
im = __import__("{0}".format(mod))
File "/home/shermelin/src/freecad-build/Mod/Fem/femsolver/elmer/equations/fluxsolver.py", line 41, in <module>
class Proxy(linear.Proxy, …
> Sketcher: Projections of arcs of circle, orthogonal case

- src/App/Application.h
- src/App/Document.cpp
- src/App/Document.h
Problem reported from [here](https://github.com/realthunder/FreeCAD/issues/46).
> App: fix recursive App::getLinksTo()

- src/Mod/Draft/draftguitools/gui_snapper.py
Forum thread: https://forum.freecadweb.org/viewtopic.php?p=433621#p433621
> HiDPI cursors: Support Qt < 5

- src/Mod/Path/App/AppPath.cpp
- src/Mod/Path/App/CMakeLists.txt
- src/Mod/Path/App/Voronoi.cpp
- src/Mod/Path/App/Voronoi.h
- src/Mod/Path/App/VoronoiCell.cpp
- src/Mod/Path/App/VoronoiCell.h
- src/Mod/Path/App/VoronoiCellPy.xml
- src/Mod/Path/App/VoronoiCellPyImp.cpp
- src/Mod/Path/App/VoronoiEdge.cpp
- src/Mod/Path/App/VoronoiEdge.h
- src/Mod/Path/App/VoronoiEdgePy.xml
- src/Mod/Path/App/VoronoiEdgePyImp.cpp
- src/Mod/Path/App/VoronoiPy.xml
- src/Mod/Path/App/VoronoiPyImp.cpp
- src/Mod/Path/App/VoronoiVertex.cpp
- src/Mod/Path/App/VoronoiVertex.h
- src/Mod/Path/App/VoronoiVertexPy.xml
- src/Mod/Path/App/VoronoiVertexPyImp.cpp
- src/Mod/Path/CMakeLists.txt
- src/Mod/Path/Gui/Resources/Path.qrc
- src/Mod/Path/Gui/Resources/icons/Path-Vcarve.svg
- src/Mod/Path/Gui/Resources/panels/PageOpVcarveEdit.ui
- src/Mod/Path/InitGui.py
- src/Mod/Path/PathScripts/PathGuiInit.py
- src/Mod/Path/PathScripts/PathSelection.py
- src/Mod/Path/PathScripts/PathVcarve.py
- src/Mod/Path/PathScripts/PathVcarveGui.py
> [Path] Feature/vcarve  using new PathVoronoi from mlampert.  Needs testing

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
Forum thread:
https://forum.freecadweb.org/viewtopic.php?p=435468#p435468
> HiDPI: Hot point scaling is only required for X11

- src/Mod/Draft/draftguitools/gui_snapper.py
> Proper check for Qt version

- src/Mod/Path/App/Voronoi.h
- src/Mod/Path/App/VoronoiCellPyImp.cpp
- src/Mod/Path/App/VoronoiEdgePyImp.cpp
- src/Mod/Path/App/VoronoiVertexPyImp.cpp
> PATH: Dealing with 32bit compile error of Voronoi interface.

- src/Mod/Path/PathScripts/PathSurfaceSupport.py
> [Path] fix 3Dsurface with countersink tools

- src/Mod/AddonManager/addonmanager_macro.py
- src/Mod/AddonManager/addonmanager_workers.py
---
Followup to #3868. Fixes https://forum.freecadweb.org/viewtopic.php?f=10&t=50778
> AddonManager: Fix python imports

- src/Gui/Application.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=50793
---
> [File Import] add import to document transaction for undo/redo

- src/Mod/Image/ImageTools/_CommandImageScaling.py
> [Image] Very minor improvement to Report View..

- src/Mod/Path/Gui/Resources/panels/PageDepthsEdit.ui
- src/Mod/Path/Gui/Resources/panels/SurfaceEdit.ui
> Path:  change final step down label for clarity fixes #4439

- src/Mod/Path/PathScripts/post/grbl_post.py
Ensure fast retraction and then plunge to just short off previous drilled depth at G0.  Fixes painfully slow air drilling which makes peck drilling impracticable.
https://forum.freecadweb.org/viewtopic.php?f=15&t=25604&p=435639#p435639
---
> PATH: G0 retraction and return speeds for grbl_post G83 expand 

- src/Mod/Path/Gui/Resources/Path.qrc
- src/Mod/Path/Gui/Resources/panels/PageDiametersEdit.ui
- src/Mod/Path/PathScripts/PathOp.py
- src/Mod/Path/PathScripts/PathOpGui.py
- src/Mod/Path/PathScripts/PathSelection.py
This PR adds some base features to the path workbench to allow development of the Turning features as a FreeCAD Addon. 
https://github.com/dubstar-04/FreeCAD_Turning_Addon
The intention is to allow users to install the Turning addon through the FreeCAD addon installer, allowing simple access to test and contribute to the development of the Turning features without needing to build FreeCAD from source. Development of Turning features has currently stalled, I hope that easy access to the addon will encourage myself and other to move it forward. 
Forum Thread: https://forum.freecadweb.org/viewtopic.php?f=15&t=30563
---
> [Path] - Add Turning / Lathe Base Support

- src/MacAppBundle/CMakeLists.txt
Add WebEngine required files to the bundle
Signed-off-by: Jean-Marie Verdun <jmverdun3@gmail.com>
---
> Update MacAppBundle to work properly with Qt5 and updated homebrew

- src/Mod/Arch/ArchBuildingPart.py
Found by user PMac in https://forum.freecadweb.org/viewtopic.php?f=3&t=51049
> Arch: fix typo in ArchBuildingPart.py [skip-ci]

- src/Mod/Path/Gui/Resources/Path.qrc
- src/Mod/Path/Gui/Resources/panels/AxisMapEdit.ui
- src/Mod/Path/Gui/Resources/panels/DragKnifeEdit.ui
- src/Mod/Path/PathScripts/PathDressupAxisMap.py
- src/Mod/Path/PathScripts/PathDressupDragknife.py
- src/Mod/Path/PathScripts/PathDressupZCorrect.py
- src/Mod/Path/PathScripts/PathSurface.py
- src/Mod/Path/PathScripts/PathWaterline.py
> [PATH]  Task panel for dragknife and axismap dressups.  fixes #2840

- src/Mod/Path/PathScripts/PathDeburr.py
- src/Mod/Path/PathScripts/PathDeburrGui.py
- src/Mod/Path/PathScripts/PathEngraveBase.py
- src/Mod/Path/PathScripts/PathOpTools.py
- src/Mod/Path/PathScripts/PathSelection.py
> [Path] Deburr bug fixes

- .travis.yml
> Travis update - re-enable MacOS build

- src/Mod/Part/CMakeLists.txt
- src/Mod/Part/TestPartApp.py
- src/Mod/Part/parttests/regression_tests.py
This is a test for a regression caused by a6c55acdb.
See https://forum.freecadweb.org/viewtopic.php?f=10&t=50651.
```
a6c55acdb1cb92a4e0172ccc0241d861104ea85f is the first bad commit
commit a6c55acdb1cb92a4e0172ccc0241d861104ea85f
Author: wmayer <wmayer@users.sourceforge.net>
Date:   Sun Sep 27 23:34:45 2020 +0200
Part: improve Python interface
+ rename getCurve2dFromGeom2d to makeFromCurve2d
+ add function makeFromCurve and makeFromTrimmedCurve like makeFromSurface
+ implement OffsetCurve.BasisCurve
+ fix memory leak in BRepOffsetAPI_MakePipeShellPy
src/Mod/Part/App/BRepOffsetAPI_MakePipeShellPy.xml |   3 +-
src/Mod/Part/App/Geom2d/OffsetCurve2dPyImp.cpp     |   2 +-
src/Mod/Part/App/Geometry.cpp                      | 140 ++++++++++++++++++
src/Mod/Part/App/Geometry.h …
```
> Part: Add regression test for issue #4456 (skipped for now)

- src/Mod/OpenSCAD/OpenSCADFeatures.py
- [x ] Branch rebased on latest master `git pull --rebase upstream master`
---
> fix import, OpenSCAD isn't namespace workbench

- src/Mod/Part/parttests/regression_tests.py
Now that issue 4456 is fixed, we don't need to skip this test anymore.
---
> Part: Enable test for issue 4456

- src/Mod/Path/PathScripts/PathSanity.py
> Path: handle missing target directory in Path-Sanity

- src/Mod/Path/Gui/Resources/panels/PageOpSurfaceEdit.ui
- src/Mod/Path/PathScripts/PathSurfaceGui.py
> PATH: add boundary enforcement to the task panel

- src/Mod/Draft/draftobjects/draftlink.py
Forum thread https://forum.freecadweb.org/viewtopic.php?f=23&t=48997
> Draft: support object without shape in DraftLink

- src/Mod/Path/PathScripts/post/grbl_post.py
Path: grbl_post G83 expansion , G1 on initial move to retract_Z height to allow retraction height to remain inside hole. This can be useful to avoid widening hole entrance with multiple drill re-entries.moves
---
> [Path] Add files via upload

- src/Mod/AddonManager/AddonManager.py
https://forum.freecadweb.org/viewtopic.php?f=13&t=51346
---
> fix for failing addon-manager

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
> [Sketcher] Allow selection of 2 vertices for horizontal/vertical constraint in continuous mode

- src/Mod/Draft/DraftGeomUtils.py
- src/Mod/Draft/draftgeoutils/edges.py
- [*] Branch rebased on latest master `git pull --rebase upstream master`
---
> Draft: Fix logical error in is_line function

- src/Mod/Path/PathScripts/PathDeburr.py
- src/Mod/Path/PathScripts/PathDressupZCorrect.py
fixes an issue with deburr direction
fixes an issue with probe files containing blank lines
fixes an issue with zdressupcorrect filenames
---
> [PATH]  Minor bugfixes

- src/Mod/Path/PathScripts/PathProfile.py
This could use some additional testing.  I ran two separate successful tests, apart from the Profile operation in the file submitted with the ticket.
---
> Path: Fixes ticket #4471

- src/Mod/Show/SceneDetails/ClipPlane.py
Forum discussion: https://forum.freecadweb.org/viewtopic.php?f=10&t=51545
> [Sketcher] Fix ClipPlane placement

- src/Mod/Part/App/Geometry.cpp
- src/Mod/Part/App/Geometry.h
- src/Mod/Part/App/GeometryPyImp.cpp
- src/Mod/Sketcher/App/AppSketcher.cpp
- src/Mod/Sketcher/App/CMakeLists.txt
- src/Mod/Sketcher/App/ExternalGeometryExtension.cpp
- src/Mod/Sketcher/App/ExternalGeometryExtension.h
- src/Mod/Sketcher/App/ExternalGeometryExtensionPyImp.cpp
- src/Mod/Sketcher/App/ExternalGeometryFacade.cpp
- src/Mod/Sketcher/App/ExternalGeometryFacade.h
- src/Mod/Sketcher/App/ExternalGeometryFacadePy.xml
- src/Mod/Sketcher/App/ExternalGeometryFacadePyImp.cpp
- src/Mod/Sketcher/App/GeometryFacade.cpp
- src/Mod/Sketcher/App/GeometryFacade.h
- src/Mod/Sketcher/App/GeometryFacadePy.xml
- src/Mod/Sketcher/App/GeometryFacadePyImp.cpp
- src/Mod/Sketcher/App/SketchGeometryExtension.h
- src/Mod/Sketcher/App/SketchGeometryExtensionPyImp.cpp
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
- src/Mod/Sketcher/App/SketchObjectPy.xml
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
Mainly:
Development of Sketcher Geometry extensions and creation of Facade objects to handle geometry and sketcher extensions seamlessly.
This PR does not change the behaviour of SketchObject and is intended to bring extensions to a level where they can be used to extend SketchObject functionality (in future PRs).
Related thread:
https://forum.freecadweb.org/viewtopic.php?f=10&t=51716&sid=1e0a2d8ffabc89b7805fb01636ac9f86
> SketchGeometryFacade and ExternalGeometryFacade

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- also update profile changing method since fraction diameters no longer end with a '0' in profile ISO coarse
> [PD] hole - fix typo

- .travis.yml
> CI: Fix MacBuild

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
`Sketcher/Gui/CommandConstraints.cpp` will now be parsed for translation. Based on https://github.com/FreeCAD/FreeCAD/pull/3993#issuecomment-715906238  
( ref. Issue #4473 )
> Issue #4473: Expose openCommand() CommandConstraints.cpp to translation

- README.md
This commit didn't make it in to f33ca4607661
> README: minor nitpick [skip ci]

- src/Mod/PartDesign/App/FeatureHole.cpp
see:
https://forum.freecadweb.org/viewtopic.php?p=445186&sid=45bd75e3ab8c4d830decf91e946f7391#p443362
---
> [PD] fixes bug not enabling ui-elements

- src/Mod/Path/PathScripts/post/marlin_post.py
Modified grbl_post.py into marlin_post.py.
Tested marlin_post.py extensively by milling actual parts
on a three axis milling machine running Marlin 2.0.7.bugfix
> Path: Add marlin_post.py

- src/Mod/Path/PathScripts/PathCircularHoleBase.py
> [Path] Fix Typo - Stock object requires uppercase 'S'

- .travis.yml
> increase osx timeout limit

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
also add comment for better understanding
> [Sketch] remove now unused variable

- src/Mod/Draft/App/dxf.cpp
- src/Mod/Import/App/dxf.cpp
Fixed wrong DXF scale factor for inches. 1/25.4 was wrongly used
> Import DXF: Fixed wrong DXF scale factor for inches.

- src/Mod/Draft/draftguitools/gui_selectplane.py
> Draft: Enable offset for working plane aligned with current view

- src/Mod/Sketcher/App/ExternalGeometryExtension.cpp
- src/Mod/Sketcher/App/ExternalGeometryExtension.h
- src/Mod/Sketcher/App/ExternalGeometryExtensionPyImp.cpp
- src/Mod/Sketcher/App/ExternalGeometryFacade.h
- src/Mod/Sketcher/App/ExternalGeometryFacadePyImp.cpp
- src/Mod/Sketcher/App/GeometryFacade.h
- src/Mod/Sketcher/App/SketchGeometryExtension.h
- Make explicit private inheritance of the interface
- Correct inheritance of ExternalGeometryFacade
- Correct inheritance of ExternalGeometryExtension
- Better document the inheritance choice
---
> Sketcher: GeometryFacade inheritance correctness

- src/Mod/Path/PathScripts/PathSelection.py
> [Path] Update Turning Selection Gates

- .travis.yml
Signed-off-by: Jean-Marie Verdun <jmverdun3@gmail.com>
---
> Gentle exit if gtimeout reached end of time as to fill up build cache

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.ui
- propose cut values also for UTS profiles
- the UTS defines coarse and fine while for ISO it is regular and fine, thus fix the name
- for the dialog: set minimum values to zero (angles etc. cannot be negative)
Forum: https://forum.freecadweb.org/viewtopic.php?f=19&t=51491&p=447471#p447471
> [PD] hole UTS fixes

- src/Mod/Draft/draftguitools/gui_dimensions.py
- src/Mod/Draft/draftviewproviders/view_dimension.py
Also fix FlipText functionality for text on planes other than XY.
https://tracker.freecadweb.org/view.php?id=4293
---
> Draft: Fixes #0004293: Vertical dimensions can't be created in XZ and YZ working plane

- src/Mod/Part/BasicShapes/TaskTube.ui
- remove vertical whitespace
With this PR:
Currently:
> [Part] improve tube dialog

- src/Mod/PartDesign/Gui/Workbench.cpp
use Part's measure tools also for PartDesign
forum: https://forum.freecadweb.org/viewtopic.php?f=10&t=52054&p=447454#p447454
> [PD] add measure tools

- src/Mod/PartDesign/Gui/CommandBody.cpp
https://tracker.freecadweb.org/view.php?id=3968
Don't set the tip to features that cannot hold the tip.
> [PD] fix issue 3968

- src/Mod/TechDraw/Gui/Workbench.cpp
> TechDraw: minor cosmetic readability change in Gui/Workbench.cpp

- src/App/DocumentObserverPython.h
the same as in https://github.com/FreeCAD/FreeCAD/pull/4053
> [App] get rid of MSCV compiler warning

- src/Mod/Draft/draftguitools/gui_trackers.py
When the size of the text is similar to or greater than the length of the aid dimension line, there is an annoying overlap of both that makes reading difficult.
This change prevents this behavior by moving the text to an external position when necessary.
Also, avoid accessing inventor node fields on each function call acording to https://forum.freecadweb.org/viewtopic.php?f=10&t=26784&start=30#p219409
---
> Draft: Change archDimTracker text position depending on distance and scale values

- src/Mod/Points/Gui/Command.cpp
- src/Mod/Points/Gui/Resources/Points.qrc
- src/Mod/Points/Gui/Resources/icons/Points_Convert.svg
- src/Mod/Points/Gui/Resources/icons/Points_Merge.svg
- src/Mod/Points/Gui/Resources/icons/Points_Structure.svg
- src/Mod/Points/Gui/Workbench.cpp
Point Icons (Convert, Merge, and Structure) designed by @bitacovir  
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=34&t=52394
> Point: Add missing icons to the GUI

- src/Mod/Arch/ArchCommands.py
> [Arch] Fixed bug: Importing IFC in Console raises error because it linked with FreeCADGui module.

- src/Mod/Path/Gui/Resources/panels/PageOpVcarveEdit.ui
- src/Mod/Path/PathScripts/PathVcarve.py
- src/Mod/Path/PathScripts/PathVcarveGui.py
> Path: Fix help text for vcarve filter control

- src/Mod/Path/Gui/Resources/preferences/PathJob.ui
- src/Mod/Path/PathScripts/PathToolBitGui.py
- src/Mod/Path/PathScripts/PathToolBitLibraryGui.py
help user create toolbit working location
---
> [path]  make toolbit reject invalid filenames and prompt user for valid toolbit working location

- src/Mod/AddonManager/Resources/AddonManager.qrc
- src/Mod/AddonManager/Resources/icons/POV-Ray-Rendering_workbench_icon.svg
I added the workbench icon and the path in the qrc file.
I will put the link to the other PR for the Addon Manager repo here if I'm ready.
> New POV-Ray-Rendering Workbench to Addon Manager

- src/Mod/Path/PathScripts/PathVcarve.py
Operation now sets start/final depth more reasonably.
Will not violate the finaldepth.
---
> [PATH] Add finaldepth property.

- src/Mod/TechDraw/App/DrawViewDimension.cpp
- [*] Branch rebased on latest master `git pull --rebase upstream master`
- [*] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [*] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [*] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586) …
> Remove unused variable in DrawViewDimension.cpp

- src/Mod/TechDraw/App/DrawPage.cpp
- src/Mod/TechDraw/App/DrawPage.h
- src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp
The 1st commit fixes a TechDraw Spreadsheet bug reported here: https://forum.freecadweb.org/viewtopic.php?f=35&t=51994&p=449807  The bug caused certain Spreadsheet column ranges to fail in TechDraw due to alphabetical order comparison instead of index number comparison.  The 2nd commit fixes an unreported bug, which makes the DrawViewSpreadsheet to fail TechDraw redraw commands due to missing refresh logic in DrawPage::updateAllViews() …
> [TD] TechDraw DrawViewSpreadsheet fix

- src/Mod/AddonManager/Resources/AddonManager.qrc
> AddonManager: Sort .qrc file

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draft.dox
- src/Mod/Draft/draftfunctions/rotate.py
- src/Mod/Draft/draftguitools/gui_patharray.py
- src/Mod/Draft/draftmake/make_patharray.py
- src/Mod/Draft/draftobjects/patharray.py
- src/Mod/Draft/draftutils/init_draft_statusbar.py
- src/Mod/Draft/draftutils/init_tools.py
> Draft: fix header uniformity + trailing whitespace

- src/Mod/Part/App/GeometrySurfacePy.xml
- src/Mod/Part/App/GeometrySurfacePyImp.cpp
> [Part] make GeomSurface.toBSpline() arguments optional  

- src/Main/FreeCADGuiPy.cpp
- src/Main/MainCmd.cpp
- src/Main/MainGui.cpp
- src/Main/MainPy.cpp
- src/Main/core-main.dox
> Main: fix header uniformity + trailing whitespace

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
https://forum.freecadweb.org/viewtopic.php?f=10&t=51716&sid=d469aaf654946813912b9419f4fc529f&start=60#p456814
> [Sketcher] Fix dragging of Weight constraint

- src/Mod/Arch/ArchWall.py
- [] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists
---
> [ARCH] Make ArchWall use Sketcher GeometryFacade

- src/Mod/TechDraw/App/DrawViewDimension.cpp
fixes the issue reported here: https://forum.freecadweb.org/viewtopic.php?f=35&t=52545&start=40#p454483
> [TD] treat dimensions the same way, no matter if with unit or not

- src/Mod/Path/PathScripts/PathToolControllerGui.py
…updated using ToolControllerDlg
Fixing bug 4479
---
> Path: Added missing signal-connection causing spindle speed not to be updated using ToolControllerDlg Bug 4479

- .travis.yml
> Switch off mac builds - temporary travis fix

- src/Mod/Path/PathScripts/PathGui.py
- src/Mod/Path/PathScripts/PathToolBit.py
- src/Mod/Path/PathScripts/PathToolBitEdit.py
- src/Mod/Path/PathTests/TestPathCore.py
issue: https://tracker.freecadweb.org/view.php?id=4500
discussion: https://forum.freecadweb.org/viewtopic.php?f=10&t=52246
also fixes the latest gcc7 issue: https://forum.freecadweb.org/viewtopic.php?f=10&t=53303&p=458691#p458691
> Path: Bugfix/issue 4500 segfault

- src/Mod/Path/Gui/Resources/panels/DlgJobTemplateExport.ui
- src/Mod/Path/PathScripts/PathJobCmd.py
- src/Mod/Path/PathScripts/PathJobDlg.py
- src/Mod/Path/PathScripts/PathSetupSheet.py
> fixes 4466  Path Template Saving incorrect attributes

- src/Mod/Path/App/Path.cpp
- src/Mod/Path/Gui/DlgSettingsPathColor.cpp
- src/Mod/Path/Gui/DlgSettingsPathColor.ui
- src/Mod/Path/InitGui.py
- src/Mod/Path/PathScripts/PathDeburr.py
- src/Mod/Path/PathScripts/PathMillFace.py
- src/Mod/Path/PathScripts/PathOp.py
- src/Mod/Path/PathScripts/PathPreferences.py
- src/Mod/Path/PathScripts/PathSelection.py
- src/Mod/Path/PathScripts/PathUtils.py
- src/Mod/Path/PathScripts/post/centroid_post.py
- src/Mod/Path/PathScripts/post/dumper_post.py
- src/Mod/Path/PathScripts/post/dynapath_post.py
- src/Mod/Path/PathScripts/post/example_post.py
- src/Mod/Path/PathScripts/post/fablin_post.py
- src/Mod/Path/PathScripts/post/grbl_post.py
- src/Mod/Path/PathScripts/post/jtech_post.py
- src/Mod/Path/PathScripts/post/linuxcnc_post.py
- src/Mod/Path/PathScripts/post/mach3_mach4_post.py
- src/Mod/Path/PathScripts/post/marlin_post.py
- src/Mod/Path/PathScripts/post/opensbp_post.py
- src/Mod/Path/PathScripts/post/rml_post.py
- src/Mod/Path/PathScripts/post/smoothie_post.py
- src/Mod/Path/PathTests/TestPathDeburr.py
Giving users the option to suppress some of the noisier warnings issued by Path.
> Path: Feature/suppress warnings preferences

- src/Mod/Path/CMakeLists.txt
- src/Mod/Path/PathScripts/PathGeom.py
- src/Mod/Path/PathScripts/post/dxf_post.py
> [PATH] Post-process a job to a dxf file with layers

- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
Several fixes.
These included:
https://tracker.freecadweb.org/view.php?id=4514
https://forum.freecadweb.org/viewtopic.php?f=10&t=51716&p=459343#p459283
---
> [Sketcher] Several fixes

- src/Mod/Sketcher/App/GeometryFacade.cpp
- src/Mod/Sketcher/App/GeometryFacade.h
- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/planegcs/GCS.cpp
- src/Mod/Sketcher/App/planegcs/GCS.h
Thread:
https://forum.freecadweb.org/viewtopic.php?p=459312#p459581
> [Sketcher] Blocked constraint improvements 

- src/Mod/Draft/Resources/ui/TaskPanel_SetStyle.ui
https://crowdin.com/translate/freecad/548/en-eu?filter=basic&value=3#6585264
> Fix typo found via Crowdin [skip ci]

- src/Mod/Sketcher/App/SketchObject.cpp
This is a PR that addresses multiple issues in the SketchObject::trim method. 
**Issues addressed:**
- exception when trimming a loose end of a Arc of circle
- conflicting constraints when trimming
- loss of tangency when trimming arcs tangent to lines or other curves
- incorrect trimming when the intersecing geometry has a PointOnObject constraint to the arc, but also another intersection og geometry.
**Fixes:**
https://tracker.freecadweb.org/view.php?id=4066
https://tracker.freecadweb.org/view.php?id=3910
Also see forum discussion
https://forum.freecadweb.org/viewtopic.php?f=10&t=53299
**Selected demos**
Before PR (loss of tangency)
After:
Before PR (constraints modified wrongly)
After PR
Before PR (uncaught exception and loss of constraint)
After PR
Before PR (trim results in …
> Sketcher: Fix several issues in SketchObject::trim

- src/Mod/Part/App/TopoShape.cpp
- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObjectPy.xml
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
- src/Mod/Sketcher/Gui/CommandAlterGeometry.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
> [Sketcher] Defining point (non-construction point)

- src/Tools/fcinfo
> fcinfo: support backup files

- src/Mod/TechDraw/App/DrawViewDimension.cpp
as reported here: https://forum.freecadweb.org/viewtopic.php?f=35&t=53473
my commit cbcf45a4b977 introduced a regression because now units are no longer converted when the unit is displayed.
This PR fixes this.
> [TD] fix unit conversion for dimensions

- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/planegcs/GCS.cpp
> [Sketcher] Several fixes for new block constraint

- src/Mod/Arch/importWebGL.py
- src/Mod/Draft/draftguitools/gui_draft2sketch.py
- src/Mod/Path/PathScripts/PathSlot.py
- src/Mod/Path/PathScripts/post/heidenhain_post.py
- src/Mod/Sketcher/App/SketchObject.cpp
Found via `codespell v2.1.dev0`
> Fix typos [skip ci]

- src/Gui/PythonConsole.cpp
---
The changes have been discussed here: https://forum.freecadweb.org/viewtopic.php?f=10&t=53406
> [PythonConsole] Fixed pasting using middle mouse button on Linux

- src/Mod/Sketcher/App/planegcs/GCS.cpp
> Sketcher: Fix typos and code linting [skip ci]

- src/Mod/Part/App/GeometryPyImp.cpp
- src/Mod/Part/App/TopoShape.cpp
- src/Mod/Sketcher/App/ExternalGeometryFacadePyImp.cpp
- src/Mod/Sketcher/App/GeometryFacadePyImp.cpp
> Fix some GCC warnings

- src/Mod/TechDraw/App/DrawViewDimension.cpp
* angular as reported here: https://forum.freecadweb.org/viewtopic.php?f=35&t=53473&start=10#p461507
* small values: since we convert to e.g. mm, we must then not output e.g. 'µm'
* also a code optimization, fix a typo, removal of a meanwhile misleading comment
> [TD] fix bug with angular and small values

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
============================================
Fixes:
https://forum.freecadweb.org/viewtopic.php?p=461600#p461517
---
> Sketcher: Fix lock constraint reference mode

- src/Mod/Path/libarea/pyarea.cpp
> [PATH]: Added missing attribute for adaptive

- src/Mod/Path/PathScripts/post/centroid_post.py
Centroid post processor update for metric/inch
https://forum.freecadweb.org/viewtopic.php?f=15&t=53725
> [PATH] Updated centroid post

- src/Mod/Path/PathScripts/PathUtils.py
https://forum.freecadweb.org/viewtopic.php?f=15&t=53887
The file attached in the forum demonstrates the issue.
> [Path]: Check for CuttingEdgeAngle existance before using it for drill tip calculation

- src/Gui/CommandStd.cpp
- src/Gui/Workbench.cpp
Discussion https://forum.freecadweb.org/viewtopic.php?f=8&t=53578
> Gui: add 'Donate' to Help menu

- src/Mod/Path/PathScripts/PathAdaptive.py
> [Path] fix bug with adaptive path gouging at start of movement

- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathJobCmd.py
- src/Mod/Path/PathScripts/PathJobDlg.py
- src/Mod/Path/PathScripts/PathJobGui.py
- src/Mod/Path/PathScripts/PathSanity.py
- src/Mod/Path/PathScripts/PathToolControllerGui.py
- src/Mod/Path/PathScripts/PathUtils.py
- src/Mod/Path/PathTests/TestPathHelix.py
Moves all TCs into a group underneath the job to clean up the tree view. No functional change.
> [Path]: Feature/job tool group

- src/Mod/Part/App/PropertyGeometryList.cpp
- src/Mod/Part/App/PropertyGeometryList.h
- src/Mod/Sketcher/App/SketchObject.cpp
Forum post https://forum.freecadweb.org/viewtopic.php?p=462629#p462629
> Part/Sketcher: improve list property update efficiency

- src/Mod/Arch/ArchComponent.py
> Arch: deal with missing DiffuseColor attributes on obj.CloneOf.ViewObject

- src/Mod/Part/Gui/TaskDimension.cpp
the arrow heads are much too large so that the feature use quite useless:
The PR fixes this to make the arrow heads as large as for linear dimensions.
It also slightly increase the arrow head size since. This is the result:
> [Part] fix angular measurement

- src/Mod/AddonManager/Resources/AddonManager.qrc
- src/Mod/AddonManager/Resources/icons/Pyramids-and-Polyhedrons_workbench_icon.svg
---
This pull request aims to insert the workbench Pyramids-and-Polyhedrons into the addon manager.
The workbench is on
https://github.com/eddyverl/FreeCAD-Pyramids-and-Polyhedrons
It is also already included in the list of external workbenches and the wiki.
https://wiki.freecadweb.org/External_workbenches
Awaiting your decision
Regards
Eddy Verlinden
> Pyramids and polyhedrons

- src/Mod/Arch/ArchComponent.py
> [ArchComponent] Link of Window get opening now

- src/Mod/Path/CMakeLists.txt
Also alphabetized the list.
---
> Path: Add missing reference to thread cutter bit

- src/App/PropertyContainerPy.xml
- src/App/PropertyContainerPyImp.cpp
- src/Mod/TemplatePyMod/DocumentObject.py
- src/Mod/Test/Document.py
need this in a new feature for Path.
> [App]: Expose PropertyEnumeration values list to python.

- src/App/Part.cpp
- src/App/Part.h
Reported from https://forum.freecadweb.org/viewtopic.php?f=3&t=54150
> App: fix Part::getPartOfObject()

- src/Mod/Part/App/TopoShapePyImp.cpp
See https://forum.freecadweb.org/viewtopic.php?f=10&t=54190
---
> Part: Prevent crash when calling SubShapes of empty shape from Python

- src/Mod/Path/Gui/Resources/panels/PathEdit.ui
- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathSetupSheet.py
- src/Mod/Path/PathScripts/PathSetupSheetGui.py
https://forum.freecadweb.org/viewtopic.php?f=15&t=54418
---
> [Path] fix persistence of fixtures, split, and orderby to templates

- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/Sketch.h
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
- src/Mod/Sketcher/App/planegcs/Constraints.cpp
- src/Mod/Sketcher/App/planegcs/Constraints.h
- src/Mod/Sketcher/App/planegcs/GCS.cpp
- src/Mod/Sketcher/App/planegcs/GCS.h
- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
- src/Mod/Sketcher/Gui/SketcherSettings.cpp
- src/Mod/Sketcher/Gui/SketcherSettingsColors.ui
- src/Mod/Sketcher/Gui/TaskSketcherMessages.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
Thread:
https://forum.freecadweb.org/viewtopic.php?f=8&t=53466&start=40#p464168
> [Sketcher] Partial redundant notification and new solver equal distance constraint

- src/App/OriginGroupExtension.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=49753&start=10#p427342
> App: auto create Origin in OriginGroup if copied without dependency

- src/Mod/TechDraw/App/QDomNodeModel.cpp
The recent PR #4309 by @donovaly brought to light a bug in TechDraw's handling of imported SVG files.
The XML standard stipulates:
> The prefix xml is by definition bound to the namespace name http://www.w3.org/XML/1998/namespace. It MAY, but need not, be declared, and MUST NOT be bound to any other namespace name. Other prefixes MUST NOT be bound to this namespace name, and it MUST NOT be declared as the default namespace.
This PR introduces a few lines of code to ensure that if the document does not explicitly include this namespace, it is added. This prevents errors due to the use of the namespace in some imported SVG files. In debug builds those errors emit warning messages, and in Windows debug builds those errors cause an `abort()` to be called. Neither behavior is correct, as the …
> [TD] Add the standard-defined "xml" namespace if it is not specified

- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui
as requested here: https://forum.freecadweb.org/viewtopic.php?f=35&t=54718#p470334 and following
> [TD] show by default center marks

- src/Mod/Arch/ArchSchedule.py
> [Arch] Fixed typo in Arch_Schedule

- src/Mod/Path/App/CommandPy.xml
- src/Mod/Path/App/CommandPyImp.cpp
> Path: fix unnecessary copy on read for Command.parameters dict

- src/Mod/Path/PathScripts/PathToolBitLibraryGui.py
> [Path] fix index bug in toolbit directory creation

- src/Mod/Path/PathScripts/post/philips_post.py
You can't compare dict with an integer.
---
> [PATH] Update philips_post.py

- src/Mod/Path/PathScripts/post/fanuc_post.py
probably useful for other Fanuc controllers
I couldn't run the tests.  They always failed with 
FreeCAD: /home/user/dev/external/FreeCAD/src/Mod/Part/Gui/TaskDimension.cpp:1312: static void PartGui::ArcEngine::initClass(): Assertion `SoEngine::getClassTypeId() != SoType::badType()' failed.
Aborted (core dumped)
Though I highly doubt it's related to the new file getting added. 
I started by copying the mach2 post processor.  A few simple programs have been run on a real machine.  I have not yet tried the Rigid tapping on a real machine, but the generated code looks about right.
> [PATH] First pass at a post processor for Fanuc

- src/Mod/Start/StartPage/EnableDownload.py
- src/Mod/Start/StartPage/LoadMRU.py
- src/Mod/Start/StartPage/StartPage.js
- src/Mod/Start/StartPage/StartPage.py
Using the results of the vulnerability scan at lgtm.com, some very minor changes were made to Start. First, all Python exception handling now explicitly catches `Exception`, rather than `BaseException` (which would include `SystemExit` and `KeyboardInterrupt`). Second, unused imports were removed. Third, a couple of unnecessary or unused assignments were addressed. Finally, the JavaScript was modified to explicitly declare the local `ddiv` variable when needed.
---
- No tracker ticket has been filed.
> [Start] Minor tweaks recommended by LGTM

- src/Mod/Path/PathScripts/PathSimpleCopy.py
> Path: Fix creating simple copy

- src/Gui/Action.cpp
- src/Gui/Action.h
Forum thread https://forum.freecadweb.org/viewtopic.php?f=22&t=53852
> Gui: sync recent action file list from external modification

- src/Mod/TechDraw/Gui/QGIPrimPath.cpp
This PR fixes issue C reported here: https://forum.freecadweb.org/viewtopic.php?f=35&t=55008#p472939
-> the changed color must also be applied to the dimension line and arrows
> [TD] fix color change for dimensions

- src/Mod/PartDesign/Resources/Hole/iso7046.json
This mistake was introduced by me in commit 4ab3c955
> [PD] fix typo in iso7046.json

- src/Mod/Draft/draftfunctions/draftify.py
- src/Mod/Draft/draftgeoutils/geometry.py
- src/Mod/Draft/draftgeoutils/offsets.py
- src/Mod/Draft/draftgeoutils/wires.py
- src/Mod/Draft/draftmake/make_line.py
- src/Mod/Draft/draftobjects/patharray.py
https://lgtm.com/projects/g/FreeCAD/FreeCAD/alerts/?mode=tree&ruleFocus=7900090
> Draft: fix LGTM 'Testing for None should use the 'is' operator' alerrts

- src/Mod/Path/PathScripts/PathAdaptive.py
- src/Mod/Path/PathScripts/PathAdaptiveGui.py
Added support for conical entry helix
> [PATH] Adaptive improve helix entry

- lgtm.yml
Removed superfluous double-quote char. (7add058dc)
> Fix typo in previous commit 7add058dc

- src/Mod/Draft/draftgeoutils/cuboids.py
> Draft: Fix bug in getCubicDimensions function

- src/Mod/Path/PathScripts/PathAreaOp.py
- src/Mod/Path/PathScripts/PathProfile.py
> [Path] Remove `Expand Profile` feature from Profile op

- src/Mod/Spreadsheet/App/Spreadsheet_legacy.py
ref: https://lgtm.com/projects/g/FreeCAD/FreeCAD/snapshot/ddeaa48851bcffa636eb2160f5a74e217b86e88e/files/src/Mod/Spreadsheet/App/Spreadsheet_legacy.py#x687bc63f783c60bd:1
> LGTM: remove redundant variable assignment

- src/Mod/Path/PathScripts/PathGetPoint.py
- src/Mod/Path/PathScripts/PathOpGui.py
https://tracker.freecadweb.org/view.php?id=4557
> [Path]: bugfix/issue 4557

- src/Mod/Path/PathScripts/PathSlot.py
This corrects which end of the slot Extend Slot Start/End are applied; error with Extend lengths between 0 and 1  and direction of extension on arc slots ( neg. is shorten ). 
Some renaming to make code more readable and self documenting.
Consolidates earlier PR which has several commits.
https://forum.freecadweb.org/viewtopic.php?f=15&t=53866&view=unread&sid=b8378b178104431838d95a9ea0050f86#p464311
---
> [Path]: fix several minor bugs in arc slot ops

- src/Gui/3Dconnexion/3DConnexion.xml
This pull request adds a device button map for the 3Dconnexion SpaceMouse Pro device.
I did not create an issue for this; if needed even for such trivial changes I can of course create one. I did a manual test of all the buttons present on the device (I don't think there is an automated one for this).
The lines containing empty descriptions are slightly weird, the customize dialog however needs them as otherwise it is confused and does not display _keycodes_ past 15, which is the number of buttons. The C++ code handling this probably mixes the indices with keycodes somewhere. I might look at that in a separate PR and/or create an issue later; for now I wanted to have my device supported like the other models are.
And please remember to update the Wiki with the features added or changed …
> 3DConnexion: Adds 3DConnexion SpaceMouse Pro Button Map

- src/Mod/TechDraw/Gui/CommandAnnotate.cpp
- src/Mod/TechDraw/Gui/Workbench.cpp
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=34&t=55382
> TechDraw: Expose strings in Workbench.cpp to translators

- src/Mod/Sketcher/Gui/Workbench.cpp
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=34&t=55381  
and several whitespace fixes
> Sketcher: Add 'Sketcher B-spline tools' to translation [skip ci]

- src/Mod/Fem/femtools/femutils.py
---
forum: https://forum.freecadweb.org/viewtopic.php?f=13&t=55226#p474702
> [FEM] Clipping plane: Fix handling of shapeless document objects

- src/Mod/Path/PathScripts/PathAdaptive.py
Added onDocRestore method for adaptive op as discussed with @sliptonic
> [0.19][PATH] Added onDocRestore method for adaptive op

- src/Mod/Path/PathScripts/PathPropertyBagGui.py
> LGTM: Removes unused import in PathPropertyBagGui.py

- src/Mod/Spreadsheet/App/Sheet.cpp
Forum topic : https://forum.freecadweb.org/viewtopic.php?f=3&t=55486
Tracker : http://freecadweb.org/tracker/view.php?id=4563
> [SpreadSheet] Fixes #4563 exported range issue

- src/Mod/Draft/draftguitools/gui_orthoarray.py
- src/Mod/Draft/drafttaskpanels/task_circulararray.py
Fixes regressions introduced in https://github.com/FreeCAD/FreeCAD/commit/43feb585ad73adf5b7b64604829d6a34e7bc1059
Forum:
https://forum.freecadweb.org/viewtopic.php?f=10&t=55546
@yorikvanhavre or @wwmayer I think this is for you
> Draft: Fix regressions in Draft array

- src/Mod/Path/PathScripts/PathSlot.py
> Path: fix typos in comments [skip ci]

- src/Mod/Part/App/PrimitiveFeature.cpp
- src/Mod/Part/Gui/DlgPrimitives.cpp
https://forum.freecadweb.org/viewtopic.php?f=8&t=55449
> Part: Allow helix primitive with negative Angle

- src/Mod/Arch/ArchSectionPlane.py
Forum Discussion  :  [ Link in Arch/BIM -- 4 ] Link of Door : Swing Not Shown in ArchView/TechDraw
- https://forum.freecadweb.org/viewtopic.php?f=23&t=55526
---
> [ArchSectionPlane]  Fix Swing for Windows(Doors) Link in ArchView/TD

- src/Mod/Path/CMakeLists.txt
- src/Mod/Path/Gui/DlgSettingsPathColor.cpp
- src/Mod/Path/Gui/DlgSettingsPathColor.ui
- src/Mod/Path/Gui/Resources/Path.qrc
- src/Mod/Path/Gui/Resources/preferences/Advanced.ui
- src/Mod/Path/InitGui.py
- src/Mod/Path/PathScripts/PathPreferences.py
- src/Mod/Path/PathScripts/PathPreferencesAdvanced.py
https://forum.freecadweb.org/viewtopic.php?f=15&t=49591&p=475339#p475332
> [Path]: Expose experimental feature flag in preferences - with warning.

- src/Gui/Stylesheets/Behave-dark.qss
- src/Gui/Stylesheets/Dark-blue.qss
- src/Gui/Stylesheets/Dark-contrast.qss
- src/Gui/Stylesheets/Dark-green.qss
- src/Gui/Stylesheets/Dark-orange.qss
- src/Gui/Stylesheets/Darker-blue.qss
- src/Gui/Stylesheets/Darker-green.qss
- src/Gui/Stylesheets/Darker-orange.qss
- src/Gui/Stylesheets/Light-blue.qss
- src/Gui/Stylesheets/Light-green.qss
- src/Gui/Stylesheets/Light-orange.qss
Fixes #0004559
https://tracker.freecadweb.org/view.php?id=4559
> Gui: Stylesheet fix applied to all shipped stylesheets [skip ci]

- src/Mod/Start/StartPage/StartPage.js
as per discussion https://forum.freecadweb.org/viewtopic.php?f=8&t=55623
---
> [Start] Enable hyperlink for installed Addons

- src/Mod/Path/InitGui.py
- src/Mod/Path/PathScripts/PathPreferences.py
- src/Mod/Path/PathScripts/PathToolController.py
- src/Mod/Path/PathScripts/PathToolLibraryEditor.py
- src/Mod/Path/PathTests/TestPathToolController.py
There was a bug in the TC creation if the preferences were set to use legacy tools. This PR cleans up that logic by removing all "tribools" and adding an explicit parameter if a default tool should be created or not.
https://forum.freecadweb.org/viewtopic.php?f=15&t=55600
> [Path]: Bugfix/path unit tests

- src/Mod/Path/App/Voronoi.cpp
https://forum.freecadweb.org/viewtopic.php?f=10&t=55295&p=478726#p478688
> [Path]: bugfix PVS detected redundant check

- src/Mod/Fem/Gui/Command.cpp
> FEM: Fix typo in filter function tooltip

- src/Mod/AddonManager/Resources/AddonManager.qrc
- src/Mod/AddonManager/Resources/icons/Maker_workbench_icon.svg
Add MakerWorkbench icon to the qrc file and the icon folder.
Correction of previous Pull Request with comments from @luzpaz
> Addon Manager: Add MakerWorkbench icon

- src/Gui/Stylesheets/CMakeLists.txt
- src/Gui/Stylesheets/ProDark.qss
forum thread: https://forum.freecadweb.org/viewtopic.php?f=34&t=55134
Created a Proffessional dark theme that follows the trend colours and theming of the popular apps such as Blender, Affinity suite, Adobe etc. The theme corrects many small visual issues present in the current shipping great styesheets to give a polished look.
> Gui: Add new stylesheet ProDark-FreeCAD-theme

- src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
- src/Mod/TechDraw/Gui/QGIViewBalloon.h
as reported in https://forum.freecadweb.org/viewtopic.php?f=10&t=55109&start=30#p478147
dragging a balloon pollutes the undo steps destroying working with undo and drawings.
> [0.19] [TD] fix dragging of balloons

- src/Mod/PartDesign/App/FeatureHelix.cpp
When writing the intial code for Helix, the sweep code was heavily inspired from the Pipe tool. Also some stuff that is not needed was copied. This PR cleans this up.
> PartDesign: Mild code cleanup of Helix

- src/Mod/PartDesign/App/FeatureHelix.cpp
Fix for issue 1 from here:
https://forum.freecadweb.org/viewtopic.php?f=3&t=55759
> [0.19] PartDesign: fix helix occ740

- src/Mod/Path/Gui/Resources/panels/PropertyCreate.ui
- src/Mod/Path/Gui/Resources/preferences/PathJob.ui
- src/Mod/Path/PathScripts/PathDressupTag.py
- src/Mod/Path/PathScripts/PathPreferences.py
- src/Mod/Path/PathScripts/PathPreferencesPathJob.py
- src/Mod/Path/PathScripts/PathPropertyBag.py
- src/Mod/Path/PathScripts/PathPropertyBagGui.py
- src/Mod/Path/PathScripts/PathToolBitLibraryCmd.py
- src/Mod/Path/PathScripts/post/gcode_pre.py
> [PATH]  Bug fixes for several minor issues, lgtm flags and input sanitizing.

- src/Mod/PartDesign/App/FeatureSketchBased.cpp
Forum post:
https://forum.freecadweb.org/viewtopic.php?f=3&t=55825&p=480225#p480218
> [0.19] PartDesign: Fix through all distance when used together with midplane option

- src/Mod/Path/PathScripts/PathAdaptive.py
- src/Mod/Path/PathScripts/post/heidenhain_post.py
> [PATH]  Small fixes to Adaptive op and Heidenhain post processor

- src/Mod/Path/InitGui.py
> [PATH] move slot op to experimental status

- src/Mod/Path/PathScripts/PathProfile.py
Each commit in this PR addresses an error in the Profile operation.
1. The DraftGeomUtils module is moved to LazyLoader usage
2. The `HandleMultipleFeatures` default value is changed to `Collectively` in order to maintain 0.18 Profile Faces behavior in detecting loops of vertical faces.
3. The fix for profiling open edges using micro bits
4. The fix for the undefined `profileshape` variable when using `HandleMultipleFeatures` is set to `Collectively`
5. A fix for improper filtering/processing of faces and edges when both types are included in the selection
Forum discussion available at [0.19 Profile Op fixes](https://forum.freecadweb.org/viewtopic.php?f=15&t=55740).
There is a testing-purposes-only PR, #4483 that tests these bug fixes in a newly proposed Profile op test module that is …
> [Path] Fixes for Profile operation [0.19]

- src/Mod/Draft/draftobjects/pathtwistedarray.py
This fixes a bug reported 
https://forum.freecadweb.org/viewtopic.php?f=3&t=55861
The bug was introduced here: 43feb585ad7
> [0.19] Draft: Fix regression in PathTwistedArray

- src/Mod/Mesh/Gui/Command.cpp
ref: https://crowdin.com/translate/freecad/561/en-en?filter=basic&value=0#6585564
> Mesh: Crowdin fix typo in translation [skip ci]

- src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
Fixes bug that dragging while pressing CTRL does not work anymore, see https://forum.freecadweb.org/viewtopic.php?f=35&t=55863
> [0.19] [TD] fix balloon dragging regression

- src/Mod/Arch/exportIFC.py
- [x ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas …
> Arch: ifc export, save guid to obj attribute

- src/Gui/DlgSettings3DView.ui
Remove trailing whitespace  
ref: https://crowdin.com/translate/freecad/549/en-en?filter=basic&value=0#6577482
> Crowdin: Gui: fix DlgSettings3DView.ui tooltip [skip ci] 

- src/Mod/Path/PathScripts/PathDeburr.py
- src/Mod/Path/PathScripts/PathPocketShape.py
- src/Mod/Path/PathScripts/PathPropertyBagGui.py
- src/Mod/Path/PathScripts/PathThreadMilling.py
- src/Mod/Path/PathScripts/PathToolBit.py
> [PATH]  Bug/translation issues

- src/Gui/Document.cpp
ref: https://crowdin.com/translate/freecad/549/en-en?filter=basic&value=0#6584664
> Crowdin: Gui: fix user-facing typo in Document.cpp [skip ci]

- src/Gui/DlgSettingsNavigation.ui
ref: https://crowdin.com/translate/freecad/549/en-en?filter=basic&value=0#6577470
> Crowdin: fix trailing whitespace [skip ci]

- src/Mod/Draft/draftguitools/gui_arcs.py
- src/Mod/Draft/draftguitools/gui_circles.py
- src/Mod/Draft/draftguitools/gui_dimensions.py
- src/Mod/Draft/draftguitools/gui_edit.py
- src/Mod/Draft/draftguitools/gui_subelements.py
- src/Mod/Draft/draftguitools/gui_wire2spline.py
- src/Mod/Draft/importSVG.py
Identified by LGTM. The top-level superclass does initialize one data member to an empty array, but this didn't appear to cause any problems.
---
- No ticket
> [DRAFT] Add call to super().__init__ where missing

- src/Mod/Tux/NavigationIndicatorGui.py
> Tux: fixes #0004565: Status bar text runs under Navigation Button

- src/Mod/Start/Gui/DlgStartPreferences.ui
- src/Mod/Start/Gui/Resources/translations/StartPage.ts
Ticket 0004578  
ref: https://crowdin.com/translate/freecad/7254/en-en?filter=basic&value=0#6572932
> Crowdin: StartPage - remove obsolete translation [skip ci]

- src/Tools/ArchiveNameFromVersionHeader.py
- src/Tools/DistTools.py
- src/Tools/FCFileTools.py
- src/Tools/LicenseChecker.py
- src/Tools/MakeApp.py
- src/Tools/MakeAppTools.py
- src/Tools/MakeMacBundleRelocatable.py
- src/Tools/MemoryLeaks.py
- src/Tools/PythonToCPP.py
- src/Tools/SubWCRev.py
- src/Tools/WinVersion.py
- src/Tools/catfiles.py
- src/Tools/dir2qrc.py
- src/Tools/doctools.py
- src/Tools/fcbt.py
- src/Tools/freecad-thumbnailer
- src/Tools/generate.py
- src/Tools/makedist.py
- src/Tools/pythondoc.py
- src/Tools/updatecrowdin.py
- src/Tools/updateppa.py
- src/Tools/wiki2qhelp.py
This commit addresses issues identified by LGTM for the various independent (and mostly-independent) files in the Tools subdirectory. The vast majority of the issues are trivial, and are things like unused imports or catching `BaseException`. There was one true bug identified, a global variable being changed in a function where it was not marked global, but it only affected output quantity (the variable is named "VERBOSE"). A couple of other issues identified variables that appear to represent no-longer-existing options in the code. The options were left, but a deprecation printout replaces the variable in the event the option is provided. In one file a mix of spaces and tabs was found: the tabs were replaced by four spaces.
---
> [Tools] Fix static analysis issues

- src/Tools/offlinedoc/buildpdf.py
- src/Tools/offlinedoc/buildqhelp.py
- src/Tools/offlinedoc/buildwikiindex.py
- src/Tools/offlinedoc/downloadwiki.py
- src/Tools/offlinedoc/update.py
LGTM identified a number of minor issues (mostly unused imports) in the offline docs code. This commit addresses those, plus tweaks some output formatting to include missing spaces, makes a regex more rigorously safe by escaping some periods, and updates the use of a `get()` function which appears to have changed since it was first written.
---
> [Offline Docs] Fix static analysis issues

- src/Mod/PartDesign/App/FeaturePolarPattern.cpp
- src/Mod/PartDesign/App/FeatureSketchBased.cpp
- src/Mod/PartDesign/Gui/ReferenceSelection.cpp
- src/Mod/PartDesign/Gui/ReferenceSelection.h
- src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.cpp
- src/Mod/PartDesign/Gui/TaskRevolutionParameters.cpp
- src/Mod/PartDesign/Gui/TaskSketchBasedParameters.cpp
- src/Mod/PartDesign/Gui/TaskSketchBasedParameters.h
- src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp
- src/Mod/PartDesign/Gui/TaskTransformedParameters.h
Forum discussion
https://forum.freecadweb.org/viewtopic.php?f=19&t=55573
Demo:
Demo2:
> [0.20] PartDesign: Allow use of circle edge as axis in PolarPattern and Sketchbased

- .travis.yml
To avoid to get tons of warnings because of -Wpedantic the clang build should use C++17, too
---
> travis: OCCT 7.5.1 uses [[nodiscard]] that is a C++17 feature.

- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/App/FeatureHelix.h
at the moment it is possible by a click to set e.g. -1 turn which would cause an error
> [PD] set constraints for helix properties

- src/Mod/PartDesign/Gui/TaskChamferParameters.cpp
- src/Mod/PartDesign/Gui/TaskDraftParameters.cpp
- src/Mod/PartDesign/Gui/TaskPrimitiveParameters.cpp
based on Werner's work yesterday, this PR takes care of the missing PD features to use the constraints already defined in App.
> [PD] set App constraints for their Gui counterparts

- src/Mod/Part/App/BodyBase.cpp
- src/Mod/Part/App/BodyBase.h
> [PartDesign] Add Material property to Body

- src/WindowsInstaller/README.md
- src/WindowsInstaller/Settings.nsh
> Win installer update for FC 0.20dev

- src/WindowsInstaller/README.md
- src/WindowsInstaller/Settings.nsh
Update Win installer for the 0.19 release
> update Win installer for FC 0.19.0

- src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py
- src/Mod/Fem/femtools/ccxtools.py
error = sys.exc_info()[0].strip()
<class 'AttributeError'>: type object 'RuntimeError' has no attribute 'strip'
Furthermore reporting "value" instead of "type" gives more useful error messages …
> [FEM] fixes not handled exception in "task_mesh_gmsh.py"

- src/Mod/Fem/femtools/ccxtools.py
> [FEM] ccx dat file object readonly

- src/Gui/Stylesheets/ProDark.qss
forum thread: https://forum.freecadweb.org/viewtopic.php?f=34&t=55134
LineEdit, QComboBox ans QListView color enhancements for easier editing useablity. Bim View Manager Icon separation and background transparency. HyperLinks color changed in line of https://forum.freecadweb.org/viewtopic.php?f=34&t=55844&start=10
---
> Gui: Update usability enhancements to ProDark theme

- src/Mod/Fem/femmesh/gmshtools.py
> [FEM] improve error message if gmsh.exe not found

- src/Mod/OpenSCAD/InitGui.py
- src/Mod/OpenSCAD/OpenSCADFeatures.py
- src/Mod/OpenSCAD/OpenSCADUtils.py
- src/Mod/OpenSCAD/colorcodeshapes.py
- src/Mod/OpenSCAD/expandplacements.py
- src/Mod/OpenSCAD/exportCSG.py
- src/Mod/OpenSCAD/importCSG.py
LGTM fixes that don't affect the run, plus one fix that ensures all resources are closed when using `Popen` to get the version.
---
> [OpenSCAD] Minor fixes from LGTM analysis

- cMake/FindMatplotlib.cmake
- cMake/FreeCAD_Helpers/SetupMatplotlib.cmake
- cMake/FreeCAD_Helpers/SetupPython.cmake
In CMake 3.13.4 on Debian system, the module FindPython3 fails to set the variable PYTHONINTERP_FOUND from the deprecated module FindPythonInterp. Backward and fordward compatibility is added for PYTHONINTERP_FOUND and Python3_Interpreter_FOUND variables.
**Note**: If you don't have wiki access, then please mention your contribution on the …
> CMake: Fix find Matplotlib

- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femobjects/mesh_gmsh.py
- src/Mod/Fem/femtest/data/elmer/group_mesh.geo
> [FEM]implement Gmsh mesh property "MeshSizeFromCurvature"

- src/Mod/Fem/femcommands/commands.py
- src/Mod/Fem/femtools/femutils.py
> Fem test overallboundbox

- src/Mod/Fem/Gui/Resources/ui/MeshGmsh.ui
- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py
> [FEM] get Gmsh version

- src/Mod/Draft/draftguitools/gui_snaps.py
Fix regression generated in pull request https://github.com/FreeCAD/FreeCAD/pull/4544 which breaks the Snap toolbar functionality.
---
> Draft: Fix regression in sync_snap_toolbar_button function

- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py
forum: [https://forum.freecadweb.org/viewtopic.php?f=18&t=56650](url)
> [FEM] improve get_gmsh_version

- src/Gui/Stylesheets/ProDark.qss
Fixes for showstopper bugs in all fix grid layout Addons
https://forum.freecadweb.org/viewtopic.php?f=34&t=55134&start=100#p487278
Cleaned up code to scale easier
---
> [Stylesheet] ProDark: major bugfix for add-ons

- src/Mod/Part/App/Geometry.cpp
- src/Mod/Part/App/Geometry.h
- src/Mod/Part/App/Part2DObject.cpp
- src/Mod/Part/App/Part2DObject.h
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
Thread:
https://forum.freecadweb.org/posting.php?mode=quote&f=10&p=471260#pr471100
I have mostly rewritten the whole trimming support. If this is to go in v0.19, a lot of testing before merge will be needed not to delay the release. Otherwise, it is to go with v0.20.
Anyway, I welcome testing and feedback.
> [0.20] [Sketcher] Heavily refactored Trim support

- src/Mod/Material/CMakeLists.txt
- src/Mod/Material/FluidMaterial/Air.FCMat
- src/Mod/Material/FluidMaterial/Argon.FCMat
- src/Mod/Material/FluidMaterial/Nitrogen.FCMat
- src/Mod/Material/FluidMaterial/Water.FCMat
also add electrical conductivity for air and water
To be merged after #4648 and #4647 are in.
> [FEM] add material cards for gases

- src/Mod/Path/PathScripts/PathDressupDogbone.py
- src/Mod/Path/PathTests/TestPathDressupDogbone.py
https://forum.freecadweb.org/viewtopic.php?f=15&t=56647
> [Path]: Bugfix/dogbone on straight edges and noop moves

- src/Mod/Material/CMakeLists.txt
This fixes issue 1. reported here: https://forum.freecadweb.org/viewtopic.php?f=18&t=56912#p489666
> [FEM] add missing material cards to CMakeLists.txt

- lgtm.yml
Add some additional files to the LGTM exclusions: these are either templates, or legacy code.
> LGTM: Remove some additional legacy files

- src/Ext/freecad/CMakeLists.txt
https://stackoverflow.com/a/40006251
recently this was failing for conda-osx. The proposed changes fix the site-package-dir detection.
---
> cmake: update command to find python-site-packages

- package/fedora/freecad.spec
- [N/A]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [N/A]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes …
> [Packages] Add missing files to fedora.spec

- src/Mod/Path/PathScripts/post/grbl_post.py
> [Path] post procesing for GRBL with option "--translate_drill" should also suppress G99

- src/Mod/Path/PathScripts/PathDressupDogbone.py
https://tracker.freecadweb.org/view.php?id=2839
https://forum.freecadweb.org/viewtopic.php?f=15&t=56647
> [Path]: Bugfix/issue 2839 dogbone visualisation

- src/Mod/Arch/ArchAxis.py
- src/Mod/Arch/ArchBuilding.py
- src/Mod/Arch/ArchBuildingPart.py
- src/Mod/Arch/ArchComponent.py
- src/Mod/Arch/ArchCurtainWall.py
- src/Mod/Arch/ArchCutPlane.py
- src/Mod/Arch/ArchEquipment.py
- src/Mod/Arch/ArchFence.py
- src/Mod/Arch/ArchFloor.py
- src/Mod/Arch/ArchFrame.py
- src/Mod/Arch/ArchIFC.py
- src/Mod/Arch/ArchNesting.py
- src/Mod/Arch/ArchPanel.py
- src/Mod/Arch/ArchPipe.py
- src/Mod/Arch/ArchPrecast.py
- src/Mod/Arch/ArchProject.py
- src/Mod/Arch/ArchRebar.py
- src/Mod/Arch/ArchRoof.py
- src/Mod/Arch/ArchSchedule.py
- src/Mod/Arch/ArchSectionPlane.py
- src/Mod/Arch/ArchSite.py
- src/Mod/Arch/ArchSpace.py
- src/Mod/Arch/ArchStairs.py
- src/Mod/Arch/ArchTruss.py
- src/Mod/Arch/Dice3DS/dom3ds.py
- src/Mod/Arch/importGBXML.py
- src/Mod/Arch/importSH3D.py
- src/Mod/Arch/importWebGL.py
Removes unused imports as reported by LGTM.
There are exceptions: `import Arch_rc` is shown as an alert, but has side effects.  It's not clear what the best thing to do in those cases is, so I've left them for now. …
> Arch: removes unused imports

- src/Mod/Draft/draftutils/gui_utils.py
This PR removes the python 2 code path in Draft's load_texture function.
It also simplifies the code now when we don't need to bother with backwards compatibility with python 2
Here are some files that can be used for testing (grayscale, grayscale+a, rgb, rgba) [test_files.zip](https://github.com/FreeCAD/FreeCAD/files/6118365/test_files.zip)
---
> Draft: Simplify load_texture after py3 requirement

- src/App/FreeCADInit.py
> App: add system32 to Python's search paths

- src/Mod/Material/CMakeLists.txt
- src/Mod/Material/StandardMaterial/Graphite.FCMat
> [FEM] add a Graphite material card

- src/Mod/PartDesign/fcsprocket/fcsprocket.py
- src/Mod/PartDesign/fcsprocket/fcsprocketdialog.py
- src/Mod/PartDesign/fcsprocket/sprocket.py
Removes unnecessary variable assignments and unused imports. Renames one unused variable to silence the warning.
---
> [PD] Misc. small LGTM fixes to Sprocket

- src/Mod/PartDesign/App/FeatureHelix.cpp
Related forum thread : https://forum.freecadweb.org/viewtopic.php?f=3&t=57128
I think this fix may need to be included in a future 0.19.2
---
> PartDesign Helix: update NbTurns in Pitch-Height-Angle mode

- src/Mod/Part/App/TopoShapeCompSolidPy.xml
- src/Mod/Part/App/TopoShapeCompoundPy.xml
- src/Mod/Part/App/TopoShapeEdgePy.xml
- src/Mod/Part/App/TopoShapeFacePy.xml
- src/Mod/Part/App/TopoShapePy.xml
- src/Mod/Part/App/TopoShapeShellPy.xml
- src/Mod/Part/App/TopoShapeSolidPy.xml
- src/Mod/Part/App/TopoShapeWirePy.xml
Format UserDocu to follow the template:
```
Description
method(args) -> return
--
More infos
```
> [Part] Improve Part.Shape methods python documentation

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
For Werner review (only the second commit. It is just two lines).
Thread:
https://forum.freecadweb.org/viewtopic.php?f=10&t=56550
Reason:
The proposed fix appears to solve the bug, but I do not understand why. I do not know why it might be necessary to switch the render type to image and back to native. Not doing it appears to fix the bug.
> [Sketcher] Box corrections 

- src/Gui/NaviCube.cpp
fixes a copy/paste issue of commit f525904c1b
> [Gui] fix a NaviCube Corner

- src/Gui/Control.cpp
- src/Gui/DockWindowManager.cpp
- src/Gui/PythonConsole.cpp
- src/Gui/Quarter/Mouse.cpp
- src/Mod/Image/Gui/ImageView.cpp
- src/Mod/TechDraw/Gui/QGVPage.cpp
- src/Mod/Web/Gui/BrowserView.cpp
> Remove some Qt5 deprecation warnings

- src/Mod/TechDraw/Gui/Command.cpp
- src/Mod/TechDraw/Gui/CommandAnnotate.cpp
- src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
- src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ActiveView.svg
- src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_FaceCenterLine.svg
- src/Mod/TechDraw/Gui/TaskActiveView.cpp
- src/Mod/TechDraw/Gui/TaskActiveView.ui
- src/Mod/TechDraw/Gui/TaskCenterLine.cpp
- src/Mod/TechDraw/Gui/TaskCenterLine.ui
Renamed SVGs, saved as plain SVG, updated appropriate areas in the source code
//cc @bitacovir
> [TD] icon uniformity for ActiveView and FaceCenterLine commands

- src/Mod/Draft/draftobjects/shapestring.py
User request : https://forum.freecadweb.org/viewtopic.php?f=8&t=57455
I don't know Draft WB structure very well, so I am not sure this change is enough, or if it needs changes elsewhere ? …
> Draft.ShapeString : add option to choose wires or faces output

- src/Mod/PartDesign/SprocketFeature.py
- src/Mod/PartDesign/SprocketFeature.ui
* as the title says.
(The other UI file changes were made by Qt's designer.)
* also try to fix that the property "SprocketReference" is not an enum
forum thread: https://forum.freecadweb.org/viewtopic.php?f=22&t=44525&p=494517#p494517
> [PD] sort entries in sprocket feature

- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femobjects/mesh_gmsh.py
- src/Mod/Fem/femtest/data/elmer/group_mesh.geo
- src/Mod/MeshPart/Gui/Tessellation.cpp
There are 4 optimizers available while we only supported 1. This PR adds support for all.
> [FEM] proper support for Gmsh HighOrder optimization

- src/Gui/Stylesheets/Behave-dark.qss
- src/Gui/Stylesheets/Dark-blue.qss
- src/Gui/Stylesheets/Dark-contrast.qss
- src/Gui/Stylesheets/Dark-green.qss
- src/Gui/Stylesheets/Dark-orange.qss
- src/Gui/Stylesheets/Darker-blue.qss
- src/Gui/Stylesheets/Darker-green.qss
- src/Gui/Stylesheets/Darker-orange.qss
- src/Gui/Stylesheets/Light-blue.qss
- src/Gui/Stylesheets/Light-green.qss
- src/Gui/Stylesheets/Light-orange.qss
Work by @turn211, forums discussion here: https://forum.freecadweb.org/viewtopic.php?f=34&t=57427
> [GUI] Stylesheet fix for icons in Qt file dialog

- vagrant/Xenial/generate_yaml.sh
- vagrant/generate_yaml.sh
This change only modifies the yaml files to enable access to external storage
> adding the removable-media plug

- src/Gui/Icons/Std_MarkToRecompute.svg
- src/Gui/Icons/resource.qrc
- src/Gui/Tree.cpp
> [GUI] new icon to mark for recomputation

- src/Mod/TechDraw/Gui/CommandAnnotate.cpp
> [TD] Fix typo in Gui/CommandAnnotate.cpp [skip ci]

- src/Gui/Stylesheets/ProDark.qss
Fixes no icons showing in QT File Dialogs
forum thread: https://forum.freecadweb.org/viewtopic.php?f=34&t=57427
Should go into the 0.19.2 Release
---
> [Gui] ProDark Stylesheet Icon Fix

- src/Mod/TechDraw/Gui/TaskCenterLine.cpp
forum thread: https://forum.freecadweb.org/viewtopic.php?f=35&t=57783
---
> TD: fix center line style settings

- src/Mod/Draft/draftguitools/gui_trimex.py
See comments at https://github.com/FreeCAD/FreeCAD/pull/4546
---
> Draft: Fix regression in trimex command

- src/Mod/Arch/importWebGL.py
Several improvements to the javascript in the template:
* Render on demand rather than continuously
* Support high-DPI displays
* Fix the frustum depth for both cameras
* Deal correctly with the browser window being resized
* Only show controls for objects with geometry
Also some changes made for code clarity:
* Use `const` and `let` instead of `var`, as appropriate
* Use for...of and `.map()` instead of iterating over arrays using a loop counter
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=23&t=56755&p=488402
---
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't …
> Arch: Improve WebGL export javascript template

- src/Mod/Import/stepZ.py
This PR is allowing to export stepZ files on different drivers
os.rename() doesn't move its actual data on the disk
shutil.move() method allows to transfer files between two different drives
- [*]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several …
> allowing to export stpZ files on different disk drivers

- cMake/FreeCAD_Helpers/SetupQt.cmake
- src/Base/CMakeLists.txt
- src/Gui/CMakeLists.txt
- src/Mod/Drawing/Gui/CMakeLists.txt
- src/Mod/Fem/Gui/CMakeLists.txt
- src/Mod/Image/Gui/CMakeLists.txt
- src/Mod/Inspection/Gui/CMakeLists.txt
- src/Mod/Mesh/Gui/CMakeLists.txt
- src/Mod/MeshPart/Gui/CMakeLists.txt
- src/Mod/Part/Gui/CMakeLists.txt
- src/Mod/PartDesign/Gui/CMakeLists.txt
- src/Mod/Path/Gui/CMakeLists.txt
- src/Mod/Points/Gui/CMakeLists.txt
- src/Mod/Raytracing/Gui/CMakeLists.txt
- src/Mod/ReverseEngineering/Gui/CMakeLists.txt
- src/Mod/Robot/Gui/CMakeLists.txt
- src/Mod/Sketcher/Gui/CMakeLists.txt
- src/Mod/Spreadsheet/Gui/CMakeLists.txt
- src/Mod/Start/Gui/CMakeLists.txt
- src/Mod/Surface/Gui/CMakeLists.txt
- src/Mod/TechDraw/Gui/CMakeLists.txt
- src/Mod/Test/Gui/CMakeLists.txt
- src/Mod/Web/App/CMakeLists.txt
- src/Mod/Web/Gui/CMakeLists.txt
qt5_make_output_file is not part of the official API, and might be removed in Qt 6.
Only tested with:
- Qt 5.15.2
- CMake 3.18.4
- Debian Linux
Cheers,
Mateusz
---
> [Build system] Fix CMake warning

- src/Mod/Draft/draftutils/init_draft_statusbar.py
From time to time when switching to other workbenches snap_widget changes
orientation to vertical. Make sure it stays horizontal.
Signed-off-by: Łukasz Stelmach <stlman@poczta.fm> …
> Draft: Ensure horizontal orientation of snap_widget

- src/Mod/OpenSCAD/OpenSCADFeatures.py
Correct a mistake I introduced in 7eec10def.
> [OpenSCAD] Fix regression with angle specification

- src/Mod/Arch/ArchMaterial.py
Provide currently set color as initial value for getColor() to enable
convenient incremental changes.
Do not change the colour if the Cancel buton was pressed.
Signed-off-by: Łukasz Stelmach <stlman@poczta.fm> …
> Arch: Fix material color pickers

- src/Mod/Path/PathScripts/PathInspect.py
> [Path] adjust tool position during inspect

- src/MacAppBundle/FreeCAD.app/Contents/Info.plist
CFBundleVersion is used by the system to identify app versions, and the build currently populates that, but CFBundleShortVersionString is what Finder shows about the app when using the Get Info screen. Having the version available there makes it easer to check app versions without launching FreeCAD.
With the CFBundleShortVersionString left blank (current behavior), the application version shown in Finder is "--"
Example of FreeCAD app bundle with version copied to both Info.plist entries: …
> MacAppBundle: Add human readable version to mac app bundle

- src/Mod/Sketcher/Gui/SketcherSettings.cpp
- src/Mod/Sketcher/Gui/SketcherSettingsDisplay.ui
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
> [Sketcher] Visibility automation : add ability to open sketch in Section View mode

- src/Mod/OpenSCAD/OpenSCADCommands.py
> OpenSCAD - Add element ( Load | Save | Refresh )

- src/Mod/Test/Document.py
Solves an issue with the test module when running test-suite
as described in
https://forum.freecadweb.org/viewtopic.php?f=10&t=58099
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net> …
> [Test] fix failing test in Test module

- src/Mod/Arch/ArchRebar.py
> [Arch]: allow Rebar OffsetStart and OffsetEnd in negative also

- src/Mod/Draft/draftmake/make_ellipse.py
The face argument was not used and therefore "filled mode" did not work in the GUI.
> Draft: Fixed make_ellipse.py: the face argument was not used

- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femtools/femutils.py
> [FEM] patch LGTM alerts

- src/Mod/AddonManager/addonmanager_workers.py
Updates the macros URLs in addonmanager_workers.py.
> AddonManager: Fix Macros URL

- src/Mod/Arch/exportIFCStructuralTools.py
I did my best (I'm a programming novice) to understand the code and to improve the IFC export for slabs.
ATM for every slab all contour edges are exported as IFCSTRUCTURALCURVEMEMBER except the last closing one (see forum thread https://forum.freecadweb.org/viewtopic.php?f=39&t=54286).
This changes aim to also add the last closing edge for slabs.
And please remember to update the Wiki with the features added or changed once this PR is …
> Improve IFC export (structural analysis) for slabs

- src/Mod/Path/PathScripts/PathPocketShape.py
- src/Mod/Path/PathScripts/PathPocketShapeGui.py
Fix bug identified by MLampert.  This fix addresses extensions for circular faces that have non-extended holes in the face.
.
Unlike polygon extensions that only need one wire to define the extension shape, some circular extensions require two wires (a face would be better) to define the extension area.  
A part of the problem is that the current `Extensions` code returns an extension area using a single wire; however, some extension areas need two wires to be correctly defined.  This fix makes use of a new method to identify the circular extension region using a `Part.Face()` shape to allow for the two wires that are necessary to define the circular extension.
Forum discussion at [PR fixes for PocketShape: 4615, 4617](https://forum.freecadweb.org/viewtopic.php?f=15&t=56667).  Bug was …
> [Path] Fix outside `Extensions` of circular faces with inner holes

- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathJobGui.py
When adding tool controllers from the job dialog, it will now
try to match the toolbit file with the currently selected library
and add use the toolnumber from there.  If no match is found,
it will autoincrement from the existing tool controllers
in the job
**Note**: If you don't have wiki access, then please mention your contribution on …
> [PATH] fix bug adding TC from job dialog.

- src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp
Hello,
This is a pull request related to the issue described here:
https://forum.freecadweb.org/viewtopic.php?f=35&t=58563
The solution of this pull request has minimized the added code.
Regards,
> Fix TechDraw View Spreadsheet with merged cells, 2

- src/Mod/Path/Gui/Resources/panels/PageOpDrillingEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpPocketFullEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpProfileFullEdit.ui
- src/Mod/Path/PathScripts/PathAreaOp.py
- src/Mod/Path/PathScripts/PathCircularHoleBase.py
- src/Mod/Path/PathScripts/PathDrilling.py
- src/Mod/Path/PathScripts/PathDrillingGui.py
- src/Mod/Path/PathScripts/PathHelix.py
- src/Mod/Path/PathScripts/PathMillFace.py
- src/Mod/Path/PathScripts/PathPocketBaseGui.py
- src/Mod/Path/PathScripts/PathPocketShape.py
- src/Mod/Path/PathScripts/PathProfile.py
- src/Mod/Path/PathScripts/PathProfileGui.py
- src/Mod/Path/PathScripts/PathThreadMilling.py
- src/Mod/Path/PathScripts/PathWaterline.py
This PR is a preparatory PR in that it removes current rotational-related code and functionality from Path workbench to allow for new rotational indexing work to begin.  Users wanting to work with rotation after this PR will need to use 0.19 until the newer rotational features are functional and merged.
This PR will be a draft until all modules touched by rotation have been properly cleaned and simplified to a level acceptable for project advancement as it pertains to re-integration of a better, more refined and maintainable rotational indexing feature.
Some prior discussion on the matter of rotational integration and the Path workbench is available at [Discussion for detanglement of rotatioal code from existing ops](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=52024).
Thank …
> [Path] Remove rotational code from Path modules

- src/Mod/Material/StandardMaterial/Graphite.FCMat
See discussion https://forum.freecadweb.org/viewtopic.php?f=3&t=58892
---
> [Material] Change Graphite File encoding to UTF-8

- src/Mod/Path/PathScripts/post/fanuc_post.py
- src/Mod/Path/PathScripts/post/heidenhain_post.py
- src/Mod/Path/PathScripts/post/linuxcnc_post.py
- src/Mod/Path/PathScripts/post/mach3_mach4_post.py
- src/Mod/Path/PathScripts/post/philips_post.py
https://forum.freecadweb.org/viewtopic.php?f=15&t=56982
---
> [PATH]  Fix proxy error bug that occurs when postprocessing 

- src/Mod/Path/PathScripts/PathPost.py
> [path] fix minor bug when cancelling post process

- src/Mod/Draft/draftmake/make_text.py
Fixed 3 small issues in make_text that came up while working on make_label (pull request #4801). Also adapted the docstring to match the actual behavior.
> Draft: make_text fixed 3 small issues

- src/Mod/Draft/draftguitools/gui_fillets.py
> Draft: Add shortcut to fillet command

- src/Mod/Path/PathScripts/PathGuiInit.py
Reverts FreeCAD/FreeCAD#4817
related to reverted camotics PR
> Revert "[Path] Handle unavailability of Camotics library/module"

- src/Mod/Path/PathScripts/PathGuiInit.py
> Path cleanup PathGuiInit

- src/Mod/Tux/NavigationIndicatorGui.py
> [Tux] Prevent updating timer to trigger errors if navigation indicator widget is deleted

- src/Mod/Arch/exportIFCStructuralTools.py
when trying to export structures to IFC2X3 there are some problems due to the fact, that the actual code uses functions not suitable for IFC2X3
this commit fixes this issues
see forum post: https://forum.freecadweb.org/viewtopic.php?f=39&t=54286&start=30#p507877
**Note**: If you don't have wiki access, then please mention your contribution …
> [Arch] Fix errors when exporting structures to IFC2X3 format

- src/Mod/Draft/draftguitools/gui_edit_sketcher_objects.py
- src/Mod/Draft/draftutils/gui_utils.py
Reference to https://forum.freecadweb.org/viewtopic.php?f=23&t=59155&p=508132#p508132
---
> Draft: fix Autogroup to fix Draft_OrthoArray crash when using active Std_Part.

- src/Mod/Part/Gui/TaskOffset.cpp
Currently, the Fill property of Part.Offset2D is not recorded by macro.
Related forum [topic](https://forum.freecadweb.org/viewtopic.php?f=22&t=59230)
---
> [Part] add Fill property to Offset2D macro recording

- src/Mod/PartDesign/Gui/Workbench.cpp
This makes the formatting of the code more uniform and readable.
> PartDesign: tweaks to Gui/Workbench.cpp formatting

- src/Mod/Arch/exportIFCStructuralTools.py
See forum discussion: https://forum.freecadweb.org/viewtopic.php?f=39&t=54286&p=509311#p509233
and commit comments
> [Arch] Improve structural IFC export of structural connections (IfcStructuralCurveConnectionLine & IfcStructuralPointConnectionVertex) 

- src/Mod/TechDraw/Templates/A4_IRAM4504.svg
IRAM (Argentine Institute for Materials Rationalization)
---
> Add A4 format template according to IRAM standard

- src/Mod/Path/PathScripts/PathPost.py
> [Path] bug splitting gcode by Fixture

- src/Mod/Fem/feminout/importCcxFrdResults.py
> [FEM] typos

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/SketcherSettings.cpp
- src/Mod/Sketcher/Gui/SketcherSettingsDisplay.ui
[Forum discussion](https://forum.freecadweb.org/viewtopic.php?f=3&t=57584&p=509588#p509485)
> [Sketcher] Radiam is new default tool + bugfix

- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/Workbench.cpp
- missing menu entry for centered rectangle
- typo
- uniform word casing
- duplicated accel key
- remove superfluous comment
> [Sketch] fix these issues:

- src/Mod/TechDraw/Templates/A4_IRAM4504.svg
we had several times problems with template SVGs containing Inkscape-special code, thus save the template as plain SVG
> [TD] save new template as plain SVG

- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateSlot.svg
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateSlot_Constr.svg
change the slot icons to reflect the new selection/definition behavior
(the were part of my original PR but where lost by resolving a merge conflict)
> [Sketch] change slot icons

- src/Mod/Draft/draftviewproviders/view_label.py
https://forum.freecadweb.org/viewtopic.php?f=3&t=34696
Arrow rotations are fixed in the update_arrow method.
Also, is corrected the ocurrence of several marks when using "Circle" as Arrow type.
This is due to add as child the SoMarkerSet object in the SoSwitch object.
See numPoints member: https://coin3d.github.io/Coin/html/classSoPointSet.html#a1a74a03a73e24dc5c603f06b85e9916c
and https://coin3d.github.io/Coin/html/classSoMarkerSet.html#details …
> Draft: Fix rotations and Circle marker in ViewProviderLabel - fixes #0003987

- src/Mod/Arch/ArchSite.py
Use the value of tz parameter to set a timezone instead of -3 constant.
Make updates to TimeZone property trigger redrawing of a solar diagram.
---
> Arch: Draw solar diagrams for timezones other than UTC and UTC-3

- src/Mod/Arch/ArchWall.py
In the execute method block joints were put on the wrong side of the offset which lead to the first block in each row being larger than intended.
---
> Arch: Fix Arch_Wall: block joints where put on the wrong side of offset

- src/Mod/Draft/draftutils/units.py
The display_external function in units.py did not handle decimals=0 properly. As a result Draft_Dimensions with the Decimals property set to zero would show decimals.
See forum topic: https://forum.freecadweb.org/viewtopic.php?f=23&t=60160 …
> Draft: fix dimensions with decimals=0 problem

- src/Mod/Path/PathTests/TestPathAdaptive.py
- src/Mod/Path/TestPathApp.py
> [Path] Cleanup Adaptive unit test code and re-enable Path unit tests

- src/Mod/Path/PathScripts/PathAdaptive.py
- src/Mod/Path/PathScripts/PathFeatureExtensionsGui.py
This PR maintains new Extensions capability when users selects faces.  It does not allow Extensions usage for edges included in Base Geometry.
---
> [Path] Restore edge processing to Adaptive as in 0.19 release

- src/Mod/Path/PathScripts/PathJobDlg.py
Not all operating systems use the same path scheme - the slash direction.  The issue fixed with this commit exists in other parts of the Path workbench, in ToolBit modules.
Forum identification and discussion at [Default template is never the default](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=60474).
**Note**: If you don't …
> [Path] Fix multi-OS path issue for Job templates

- src/Mod/Draft/draftguitools/gui_edit_draft_objects.py
"mset first angle" should be "set first angle".
---
> Draft: Fix spelling gui_edit_draft_objects.py

- src/Mod/Draft/draftgeoutils/geometry.py
- src/Mod/Draft/draftguitools/gui_offset.py
geometry.py:
The findDistance function did not work properly for arcs that crossed the 9 o'clock point.
gui_offset.py:
The ghost of an arc with a start angle that is larger than the end angle would be wrong. …
> Draft: Fix arc offset problem

- src/Mod/Draft/draftobjects/patharray.py
If the user selects edges for the path of a patharray the edges need to be sorted before creating a Part.Wire from them. Otherwise edges that are in the wrong order will be dropped. …
> Draft: Fix patharray edge sort issue

- src/Mod/Draft/draftfunctions/move.py
The X, Y and Z property of Draft_Point objects have units. The x, y and z components of the movement vector do not. So they cannot be added without some conversion.
---
> Draft: Fixed units mismatch when moving Draft_Point objects.

- src/Mod/Draft/draftguitools/gui_planeproxy.py
Draft_SetWorkingPlaneProxy should be Draft_WorkingPlaneProxy
---
> Draft: Fixed wrong cmd names in gui_planeproxy.py

- src/Mod/Path/Tools/Bit/45degree_chamfer.fctb
Fixes an issue reported in https://forum.freecadweb.org/viewtopic.php?f=15&t=54307.
> Error loading tool: 45degree_chamfer.fctb : Expecting property name enclosed in double quotes: line 12 column 3 (char 298) …
> Path: fix invalid JSON in 45degree_chamfer.fctb tool bit

- src/Mod/Path/PathScripts/post/grbl_post.py
---
Discussion in forum: https://forum.freecadweb.org/viewtopic.php?f=15&t=60450
> Path: fix grbl --return-to placement

- src/Mod/Path/PathCommands.py
- src/Mod/Path/PathScripts/PathArray.py
New class is `obj` independent allowing for greater scripting capability.
Added missing `onDocumentRestored()` method to ObjectArray class to handle property visibility and edit modes, per standard Path operations on document restoration. …
> [Path] Refactor path array algorithm into independent `PathArray` class

- src/Mod/Path/PathScripts/PathPocket.py
This PR catches some missing return value adjustments related to recent rotational code purge.  The issue is identified in the forum at [Re: G-Code generation bug](https://forum.freecadweb.org/viewtopic.php?style=3&p=513738#p513738).
The second commit is just removal of dead code blocks that were already commented out for historical record.
And please remember to update the Wiki with the features added or changed once this PR is merged. …
> [Path] Fix 3D Pocket tuple lengths in return values

- src/Mod/Arch/ArchFrame.py
Align profile's Y axis with lyouts normal vector so the profile is always
upright regardles of the direction of extrusion. See [1] for more details.
[1] https://forum.freecadweb.org/viewtopic.php?f=3&t=59725 …
> Arch: Align profile's Y with layout's normal vector

- src/Mod/ReverseEngineering/App/SurfaceTriangulation.cpp
---
I am using Debian 11 bullseye to build FreeCAD (with master:0a388722a70de516), with VTK9, I need to use PCL-1.12.0, but it doesn't seem to be compatible with …
> ReverseEngineering: compile with PCL-1.12.0

- src/Mod/Fem/femsolver/calculix/write_step_output.py
- src/Mod/Fem/femtest/data/calculix/ccx_cantilever_prescribeddisplacement.inp
- src/Mod/Fem/femtest/data/calculix/frequency_beamsimple.inp
discussed: https://forum.freecadweb.org/viewtopic.php?f=18&p=523685&sid=a53678cc7da1a39cbde317c1cc7b20a2#p523685
> FEM:request for ccx reaction forces on Constraint displacement

- src/Mod/PartDesign/Scripts/FilletArc.py
- src/Mod/PartDesign/Scripts/Gear.py
- src/Mod/PartDesign/Scripts/Spring.py
- src/Mod/PartDesign/WizardShaft/WizardShaft.py
- src/Mod/PartDesign/WizardShaft/WizardShaftTable.py
Addressing .py files in `Mod/PartDesign/Scripts` and `Mod/PartDesign/WizardShaft`
> [PartDesign] Linting and cleaning superfluous whitespace

- src/Mod/PartDesign/WizardShaft/WizardShaft.py
- src/Mod/PartDesign/WizardShaft/WizardShaftTable.py
Expose missing PD WizardShaft strings to crowdin
> [PartDesign] Expose WizardShaft/ strings to translation

- src/Mod/Part/App/BSplineSurfacePyImp.cpp
> [Part] BugFix BSplineSurfacePyImp.cpp

- src/Base/UnitsApi.cpp
- src/Gui/propertyeditor/PropertyItem.cpp
- src/Mod/PartDesign/Gui/TaskPrimitiveParameters.cpp
See discussion : https://forum.freecadweb.org/viewtopic.php?f=3&t=61044
---
> [Base/Gui] Bugfix Property Item formatting

- src/Mod/Draft/draftgeoutils/geo_arrays.py
- src/Mod/Draft/draftobjects/draftlink.py
Draft_PointArray and Draft_TwistedArray have Count problems:
1. Draft_PointArray: Count is always zero.
2. Draft_PathTwistedArray: Number of items is Count+1.
3. Draft_PathTwistedLinkArray: Count is increased whenever object is recomputed.
Also the first item in a twisted array should be unrotated. …
> Draft: Fix Draft_PointArray and Draft_TwistedArray Count problems

- package/fedora/freecad.spec
- [N/A]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
---
> [skip ci] fedora spec: Add %{?dist} to Release

- src/App/ExpressionParser.l
- src/App/FreeCADInit.py
- src/Base/Quantity.cpp
- src/Base/Quantity.h
- src/Base/QuantityLexer.c
- src/Base/QuantityParser.l
- src/Base/Unit.cpp
- src/Base/Unit.h
- src/Base/UnitsSchemaImperial1.cpp
- src/Base/UnitsSchemaInternal.cpp
- src/Base/UnitsSchemaMKS.cpp
- src/Gui/DlgUnitsCalculatorImp.cpp
- src/Mod/Material/StandardMaterial/TEMPLATE.FCMat
- src/Mod/Material/Templatematerial.yml
Added stiffness units to FreeCAD and updated lexer
> Base: Adding stiffness units

- src/Mod/Fem/femsolver/calculix/write_step_output.py
- src/Mod/Fem/femtest/data/calculix/constraint_transform_beam_hinged.inp
Fixes two errors introduced in/due to c6697bbc78786ced31e4dc01f5a3ec22b578954d. Further description in commit.
---
> [FEM] Change reference files to avoid failed tests

- src/Gui/Command.cpp
ref. forum discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=58747
---
> Gui: Improved tooltips

- src/Mod/PartDesign/Gui/TaskPadParameters.cpp
- src/Mod/PartDesign/Gui/TaskPadParameters.ui
PartDesign: Hide the custom direction fields if no custom direction is used
This is a minor UI-only patch to unclutter the PartDesign Pad UI. It hides the direction fields if no custom direction is used.
see https://forum.freecadweb.org/viewtopic.php?style=5&p=507878#p507852 for (no) discussions and screenshots. …
> PartDesign: Hide the custom direction fields in Pad if no custom direction is used

- src/Gui/Command.cpp
Following previous improvements, this fix allows also Grouped Actions to have the new tooltip.
Thanks to @Roy-043 for spotting it.
---
> Gui: Improved tooltips for grouped commands

- package/fedora/freecad.spec
- package/fedora/rpkg.macros
This is to fix:
WARNING: No disttag found in prebuilt packages
INFO: Use --define DISTTAG to set proper dist. e. g. --define DISTTAG fc21.
ERROR: 'No disttag in package and no DISTTAG flag. Use --define DISTTAG to set proper dist e. g., --define DISTTAG=fc21.' (logs in /var/lib/copr-rpmbuild/workspace/workdir-wgba9jrq/.cache/fedora-review.log)
Also adding option to git_commint_no suppressing new line prevents
breaking line in Release tag. …
> [COPR] Restore dist in Release

- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=60596&p=520217#p520209
> [Sketcher] 3-pt circle : allow tangent constraint for any click

- src/Mod/Path/PathScripts/PathAdaptive.py
- src/Mod/Path/PathScripts/PathCustom.py
- src/Mod/Path/PathScripts/PathCustomGui.py
- src/Mod/Path/PathScripts/PathDeburrGui.py
- src/Mod/Path/PathScripts/PathDressupDogbone.py
- src/Mod/Path/PathScripts/PathDressupHoldingTags.py
- src/Mod/Path/PathScripts/PathDressupLeadInOut.py
Only LGTM cleanup of:
* PathAdaptive
* PathCustom
* PathCustomGui
* PathDeburrGui
* PathDressupDogbone
* PathDressupHoldingTags
* PathDressupLeadInOut
---
> [Path] LGTM cleanup

- src/Mod/Path/PathScripts/PathPocketShapeGui.py
> [Path] Remove unused imports per LGTM in PathPocketShapeGui module

- src/Mod/Path/PathScripts/PathCircularHoleBase.py
- src/Mod/Path/PathScripts/PathEngrave.py
- src/Mod/Path/PathScripts/PathHelix.py
- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathJobGui.py
- src/Mod/Path/PathScripts/PathOp.py
- src/Mod/Path/PathScripts/PathProfile.py
> [PATH] purge archpanel support

- package/fedora/freecad.spec
> [skip ci][COPR] Bump version in spec file to 0.20pre

- src/Mod/Draft/importAirfoilDAT.py
... as an error therefore Report Console doesn't attract their attention to why there's nothing in the folder on import of faulty dat file.
See discussion: https://forum.freecadweb.org/viewtopic.php?f=3&t=59628 …
> [Draft] Airfoil Import - User feedback not shown..

- src/Mod/Draft/draftutils/init_tools.py
Removed from the Utilities menu because they already occur in the Modification menu:
Draft_FlipDimension
Draft_Edit
Draft_Slope
Removed from the Utilities menu because calling the command from there instead of from the Draft Tray does not make sense:
Draft_AutoGroup
Removed from the "Draft utility tools" toolbar because the command is very rarely used:
Draft_Heal
And please remember to update the Wiki with the features added or changed …
> Draft: Small cleanup of Utilities menu and utility toolbar

- src/Gui/DlgExpressionInput.ui
[Forum discussion](https://forum.freecadweb.org/viewtopic.php?f=3&t=61866)
> [Expression] Fix 'Clear' is activated when it has focus and 'Enter' is pressed

- src/Mod/Spreadsheet/importXLSX.py
Spreadsheet importXLSX: Added floor and ceil functions. Fixed aliasRef is None issue.
See https://forum.freecadweb.org/viewtopic.php?f=3&t=61807&p=530473#p530413
Test file:
[floor-ceil-test-alias.xlsx](https://github.com/FreeCAD/FreeCAD/files/7119763/floor-ceil-test-alias.xlsx) …
> Spreadsheet importXLSX: Added floor and ceil functions.

- src/Mod/Draft/draftguitools/gui_labels.py
Similar to https://tracker.freecadweb.org/view.php?id=4562
Step to reproduce:
1- Change the working plane using the working plane setup dialog.
2- Create a Label object using the label command.
3- Run any Creator or Modification Draft command.
Result: The working plane is restored to the previous position. …
> Draft: Prevent working plane from restoring after label command

- src/Gui/DlgSettingsLazyLoaded.ui
Small language tweak (thanks, @Roy-043). See  [forums post](https://forum.freecadweb.org/viewtopic.php?p=531373&sid=b6c44e7bd9b361dfb32e34e674fdbe2c#p531373).
---
> [GUI] Change name of workbenches tab

- src/Mod/Draft/draftguitools/gui_groups.py
- src/Mod/Draft/draftmake/make_hatch.py
- src/Mod/Path/PathScripts/PathJobGui.py
> Path: Fix PathScripts/PathJobGui.py typo bug 

- src/Gui/CommandView.cpp
- src/Gui/MouseSelection.cpp
- src/Gui/MouseSelection.h
- src/Gui/NavigationStyle.cpp
- src/Gui/NavigationStyle.h
- src/Gui/View3DInventorViewer.cpp
- src/Gui/View3DInventorViewer.h
- src/Gui/ViewProvider.cpp
- src/Gui/ViewProviderMeasureDistance.cpp
- src/Gui/ViewProviderMeasureDistance.h
Consolidates ViewBoxZoom, BoxSelection, BoxElementSelection, MeasureDistance in the aspect of:
- Change the cursor
- Abort via ESC
---
> [v0.20][Gui] Consolidate Std view modes

- src/Gui/Workbench.cpp
Closes https://github.com/FreeCAD/FreeCAD-translations/issues/63
> Crowdin: Expose View -> 'Standard views' -> 'Axonometric' to translation

- src/Mod/Mesh/App/Core/Degeneration.cpp
- src/Mod/Mesh/App/Core/TopoAlgorithm.cpp
- src/Mod/Mesh/App/Core/TopoAlgorithm.h
Addressing the issue discussed here:
https://forum.freecadweb.org/viewtopic.php?f=8&t=62108
> Mesh: Infinite loop when repairing mesh facet indices

- src/Gui/CommandDoc.cpp
> [Gui] Edit/Placement not active when no object selected

- src/Mod/TechDraw/Gui/CommandCreateDims.cpp
- src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
- src/Mod/TechDraw/Gui/Resources/icons/TechDraw_LinkDimension.svg
- src/Mod/TechDraw/Gui/TaskLinkDim.cpp
TechDraw housekeeping: Icon name and sWhatsThis for TechDraw_LinkDimension command were wrong. Changed TechDraw_Dimension_Link to TechDraw_LinkDimension.
---
> TechDraw: Changed "TechDraw_Dimension_Link" -> "TechDraw_LinkDimension"

- src/Mod/PartDesign/App/FeatureChamfer.cpp
- src/Mod/PartDesign/App/FeatureDressUp.cpp
- src/Mod/PartDesign/App/FeatureDressUp.h
- src/Mod/PartDesign/App/FeatureFillet.cpp
- src/Mod/PartDesign/App/FeaturePipe.cpp
- src/Mod/PartDesign/App/FeaturePipe.h
> PartDesign: Fix typo in function getContiniusEdges->getContinuousEdges

- src/App/Document.cpp
- src/Base/Exception.cpp
- src/Base/Exception.h
- src/Gui/Document.cpp
- src/Gui/MainWindow.cpp
- src/Gui/MainWindow.h
> [Core] (Partially?) Fix data loss on dir rename

- src/Mod/PartDesign/Gui/CMakeLists.txt
- src/Mod/PartDesign/Gui/Command.cpp
- src/Mod/PartDesign/Gui/CommandPrimitive.cpp
- src/Mod/PartDesign/Gui/DlgActiveBody.cpp
- src/Mod/PartDesign/Gui/DlgActiveBody.h
- src/Mod/PartDesign/Gui/DlgActiveBody.ui
- src/Mod/PartDesign/Gui/Utils.cpp
- src/Mod/PartDesign/Gui/Utils.h
Small QoL improvement which helps avoid having to back-and-forth between model and tasks view to activate body in case there is none.
---
> PartDesign: Add new need active body dialog with option to choose body

- src/Mod/Sketcher/App/SketchObject.cpp
LGTM complains about using `continue` statements inside a loop whose condition is always false. In addition, the C++ core guidelines recommend against using the `do...while` construct, and in this case it was really serving as a `goto`, just hiding the actual `goto` keyword. This PR replaces the loop and continue structure with simple conditionals.
I should note that the commit looks like a much larger change than it is due to the indentation change when removing the loop... I really only replaced the conditionals with the continue statements.
---
> [Sketcher] Refactor split code

- src/Mod/AddonManager/addonmanager_workers.py
See discussion https://forum.freecadweb.org/viewtopic.php?f=10&t=62265
Please consider backporting to 0.19 branch
---
> [AddonManager] Handle stderr from git status

- src/Mod/Draft/draftutils/init_draft_statusbar.py
The scale_to_label function did not handle scale 5:1, 10:1 or 20:1 properly.
Forum post: https://forum.freecadweb.org/viewtopic.php?f=23&t=60398
The cause of the problem:
```
>>> (1/20).as_integer_ratio()
(3602879701896397, 72057594037927936)
>>> (1/10).as_integer_ratio()
(3602879701896397, 36028797018963968)
>>> (1/5).as_integer_ratio()
(3602879701896397, 18014398509481984)
```
And please remember to update the Wiki with the features …
> Draft: Fix annotation scale to label issue.

- src/Mod/Mesh/App/Core/MeshIO.cpp
The genesis of this PR is silencing an LGTM warning about an empty block: the block in question was the high-precision GRID element, "GRID*". Previously ignored, this element is now supported by the Mesh NASTRAN importer (it was already supported by the Fem importer). This implementation conforms rigidly to the NASTRAN95 documentation: in particular, it supports numbers that run together in a single line, e.g.:
```
GRID*    706                            13.0000019073486-10.
*        0.
```
Each number occupies exactly 16 characters, and no separation between them is required. 
A few other small efficiency improvements are included as well.
---
> [Mesh] Implement high-precision NASTRAN GRID* element

- src/Gui/PythonWrapper.cpp
@wwmayer could you please have a look at this as build is currently broken at least on some configurations ? Thx
> [BUILDFIX] Add missing includes

- src/Mod/Draft/draftviewproviders/view_layer.py
Transparency should be "App::PropertyPercent"
Also fixed a typo.
Forum post: https://forum.freecadweb.org/viewtopic.php?f=23&t=60893
Did not add the migrate function proposed on the forum. Seems overkill. …
> Draft: fix wrong type for layer transparency

- src/Mod/Draft/draftutils/gui_utils.py
Two issues with Draft Dimension arrows were fixed:
1. The Circle Arrow Type had a fixed size (relative to the screen) and ignored the Arrow Size property.
This was fixed by creating a 24 sided polygon instead. Note that this does not affect TechDraw Draft Views.
2. The top of Tick Arrow Type was black and only the bottom was colored.
This was fixed by adding SoShapeHints.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=61093 …
> Draft: fix dim symbol issues

- src/Mod/Draft/Resources/patterns/hatch45L.svg
- src/Mod/Draft/Resources/patterns/hatch45R.svg
- src/Mod/Draft/draftviewproviders/view_base.py
2 issues were fixed:
1. SVG patterns in the list were not sorted A-Z.
2. Two patterns (hatch45L.svg and hatch45R.svg) had the wrong pattern id and therefore did not appear in the pattern list.
Forum post: https://forum.freecadweb.org/viewtopic.php?f=23&t=61097
**Note**: If you don't have wiki access, then please mention your contribution on …
> Draft: fix 2 SVG pattern issues

- src/Mod/Draft/draftutils/init_tools.py
Draft_AddNamedGroup before Draft_AddToGroup, same as in the toolbar.
---
> Draft: move Draft_AddNamedGroup in menu

- src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
Typo: "center line(s)" should be "centerline(s)". Same as in the name of the submenu: "Extensions: centerlines and threading".
---
> TechDraw: typo in menu extension pack

- src/Mod/PartDesign/App/FeaturePad.cpp
- src/Mod/PartDesign/App/FeaturePad.h
- src/Mod/PartDesign/App/FeatureSketchBased.cpp
- src/Mod/PartDesign/Gui/Command.cpp
- src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
- src/Mod/PartDesign/Gui/TaskPadParameters.cpp
- src/Mod/PartDesign/Gui/TaskPadParameters.h
- src/Mod/PartDesign/Gui/TaskPadParameters.ui
This was requested by users in the forum and is indeed very valuable for the usability.
also fix minor UI logic issues
Here is the new feature in action:
> [PD] add feature to select pad direction via an edge

- src/Mod/Path/PathScripts/PathProfile.py
Focused LGTM cleanup of PathProfile module per details at [LGTM Source root/src/Mod/Path/PathScripts/PathProfile.py](https://lgtm.com/projects/g/FreeCAD/FreeCAD/latest/files/src/Mod/Path/PathScripts/PathProfile.py?sort=name&dir=ASC&mode=heatmap#V680).
**Note**: If you don't have wiki access, then please mention your contribution on the …
> [Path] LGTM cleanup of PathProfile module

- src/Mod/Sketcher/Gui/Command.cpp
- src/Mod/Sketcher/Gui/CommandAlterGeometry.cpp
- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
- src/Mod/Sketcher/Gui/CommandSketcherVirtualSpace.cpp
This request should remove more than 100 duplicate translations from Sketcher. ts. It is needed to reduce the number of duplicates in Crowdin. And for group many identical strings to translate into one string. Remarks is welcome.
Discussion on forum: https://forum.freecadweb.org/viewtopic.php?f=10&t=62499
This pull needs rebuild of Crowdin sources after merge
>  Request for remove more than 100 duplicate translations from Sketcher.ts

- src/Mod/Spreadsheet/App/Sheet.cpp
- src/Mod/Spreadsheet/App/Sheet.h
- src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp
- src/Mod/Spreadsheet/Gui/CMakeLists.txt
- src/Mod/Spreadsheet/Gui/Command.cpp
- src/Mod/Spreadsheet/Gui/DlgSettings.ui
- src/Mod/Spreadsheet/Gui/DlgSettingsImp.cpp
- src/Mod/Spreadsheet/Gui/DlgSettingsImp.h
- src/Mod/Spreadsheet/Gui/Resources/Spreadsheet.qrc
- src/Mod/Spreadsheet/Gui/Resources/icons/preferences-spreadsheet.svg
Creates preference page and adds 3 new import/export parameters for the delimiter, escape character, and the quote character.
---
> [Spreadsheet] add preference page and 3 import/export parameters

- src/Mod/Arch/ArchAxis.py
- src/Mod/Arch/ArchCommands.py
- src/Mod/Arch/ArchComponent.py
- src/Mod/Arch/ArchCurtainWall.py
- src/Mod/Arch/ArchCutPlane.py
- src/Mod/Arch/ArchIFC.py
- src/Mod/Arch/ArchMaterial.py
- src/Mod/Arch/ArchNesting.py
- src/Mod/Arch/ArchReference.py
- src/Mod/Arch/ArchSectionPlane.py
- src/Mod/Arch/ArchSite.py
- src/Mod/Arch/ArchStairs.py
A number of small fixes addressing complaints from the LGTM static analyzer.
> [Arch] Fix LGTM warnings

- src/Mod/PartDesign/Gui/TaskPadParameters.cpp
- src/Mod/PartDesign/Gui/TaskPadParameters.ui
- handle custom direction like all other directions
- allow to view the direction vector for all directions, but only to edit for custom
- fix enabling of the length alongNormal option
- also fix a translation issue
> [PD] fixes for padding along edge

- src/Mod/Path/PathScripts/PathPocketShape.py
This PR reinstates the envelope buffer that was in place prior to PR #4798 .  This version is a little more tidy.  This PR also includes a second commit solely dedicated to application of `Black` code formatting for the touched module file.
Forum identification of the problem, and discussion for this PR is at[Path pocket issue in recent AppImage versions](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=62510).
And please …
> [Path] Reinstate fix for intermittent PocketShape finish pass

- src/Mod/Path/PathScripts/PathSanity.py
fixes bug with PathSanity not finding job object.
https://forum.freecadweb.org/viewtopic.php?f=15&t=62533
---
> [PATH] Fix bug with job object not found.

- ci/.gitlab-ci.yml
- ci/Dockerfile
- src/Mod/Path/PathTests/TestPathDeburr.py
- src/Mod/Test/UnitTests.py
> Free cad 0 19

- src/Mod/Draft/draftutils/units.py
The Decimals property did not work for angular Draft Dimensions.
Forum topic: https://forum.freecadweb.org/viewtopic.php?f=23&t=62615
---
> Draft: fix decimals for angular dims

- src/Mod/Spreadsheet/Gui/DlgSettings.ui
- add missing layouts (Qt's designer warns too)
- add spacer to assure a compact layout on all screens
> [Spreadsheet] fix preferences UI

- src/Mod/Sketcher/Gui/ConstraintMultiFilterDialog.ui
- src/Mod/Sketcher/Gui/TaskSketcherConstrains.ui
as described here: https://forum.freecadweb.org/viewtopic.php?f=17&t=60569&p=537615#p537615
> [Sketch] Constraint selection UI improvements

- src/Mod/Draft/Resources/ui/preferences-draftsnap.ui
- src/Mod/Draft/draftguitools/gui_trackers.py
ref forum: https://forum.freecadweb.org/viewtopic.php?f=23&t=61455
Several improvements to Working plane and Grid. See commits for more details.
---
> Draft: Working Plane improvements

- src/Mod/Arch/InitGui.py
- src/Mod/Draft/InitGui.py
- src/Mod/Draft/draftutils/init_tools.py
To solve the issue of shortcuts not working in menus:
1. New command list format (with strings and tuples) and functions to handle them.
2. There are some duplicate list functions for now. The Arch and BIM workbenches will be updated in separate PRs.
More:
1. Separate list functions for the utilities toolbar and the utilities menu.
2. The order of the utilities toolbar and menu has been improved.
3. The `init_draft_toolbars` and `init_draft_menus` functions have been removed. They were not used anywhere.
As already mentioned this is the first of several PRs. When the Arch and BIM WB have been updated some cleanup will be done in one or more additional PRs.
Forum topic: https://forum.freecadweb.org/viewtopic.php?f=23&t=56804
Thank you for creating a pull request to contribute to FreeCAD! …
> Draft: fix shortcuts in menus and more

- src/Mod/Draft/draftguitools/gui_dimensions.py
If the end points of the selected edges for an angular dimension were (almost) coincident with their intersection, random angles could be calculated. In essence a floating point accuracy issue.
Additionally:
Renamed `self.pts` to `self.angles` since the variable stores a list of angles.
Forum topic: https://forum.freecadweb.org/viewtopic.php?f=3&t=63239
And please remember to update the Wiki with the features added or changed once this PR …
> Draft: Fix angle dimension issue

- src/Mod/Draft/draftviewproviders/view_layer.py
The "Merge layer duplicates" Tree view context menu option for LayerContainers did not work.
Additionally:
- Using `openTransaction` and `commitTransaction` is required for the `merge_by_name` function but also for the `add_layer` function. Otherwise undo-redo does not work properly.
- Have replaced `translate("Draft", ...)` with `_tr(...)`.
Forum topic: https://forum.freecadweb.org/viewtopic.php?f=23&t=60843
And please remember to update …
> Draft: Fix merge layers

- src/Mod/Mesh/App/Core/Approximation.h
- src/Mod/Mesh/App/Core/Elements.cpp
Bringing uniformity to documenting FreeCAD
> Mesh: Convert comments from DE->EN

- src/Gui/OpenSCADNavigationStyle.cpp
Holding down SHIFT is not required when zooming with the MMB.
---
> Std: Fix OpenSCAD navigation string

- src/Mod/PartDesign/Gui/TaskLoftParameters.cpp
- src/Mod/PartDesign/Gui/TaskLoftParameters.h
> [PartDesign] Fix typo in method name

- src/Mod/PartDesign/Gui/TaskLoftParameters.cpp
- src/Mod/PartDesign/Gui/TaskLoftParameters.h
- also two automatic style fixes made by MSVC
> [PD] simplify Loft code

- src/Mod/PartDesign/Gui/TaskLoftParameters.cpp
- src/Mod/PartDesign/Gui/TaskLoftParameters.h
- the PR fixes the issue reported here: https://forum.freecadweb.org/viewtopic.php?f=3&t=63252
- (also a MSVC code formatting fix)
> [PD] fixes loft visibility on creation and modification

- src/Mod/TechDraw/Gui/Workbench.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/85
> TechDraw: Fix typo in Tool Attributes command + expose to translation

- src/Mod/Draft/importDWG.py
The getTeighaConverter function did not work on Windows. We don't deal with the actual TeighaFileConverter anymore so there is no need to check for that file. Although the name of the function and the name of the parameter have been kept. …
> Draft: fix getTeighaConverter

- src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp
- src/Mod/Spreadsheet/Gui/CMakeLists.txt
- src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp
- src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.h
- src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheetPy.xml
- src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheetPyImp.cpp
---
The main objective of this PR is to give a way to Python users to know the selected cells. To this end I added the Python stuff to the View Provider, which I …
> [Spreadsheet] Expose the selected cells to Python

- src/Mod/Draft/draftgeoutils/edges.py
The findMidpoint function (used by Draft_Snap_Midpoint) only worked for straight and circular edges. With this revision the midpoint of all edges can be found.
Forum topic: https://forum.freecadweb.org/viewtopic.php?f=22&t=63541
---
> Draft: revise findMidpoint function

- src/Gui/View3DInventor.cpp
Currently A4 and Landscape are hard-coded.  With this PR when the user selects a paper size and orientation in the File menu -> Print Preview -> Page Setup dialog these settings will be saved as ints to user parameter/BaseApp/Preferences/View/ with:
DefaultPageSize
DefaultPageOrientation
https://forum.freecadweb.org/viewtopic.php?f=3&t=63473
And please remember to update the Wiki with the features added or changed once …
> [Print Preview] Save paper size and orientation to user parameters

- src/Mod/PartDesign/Gui/TaskPadParameters.cpp
- src/Mod/PartDesign/Gui/TaskPadParameters.h
- src/Mod/PartDesign/Gui/TaskPocketParameters.cpp
- src/Mod/PartDesign/Gui/TaskPocketParameters.h
- then the profile of a pad/pocket was a face, the direction handling was completely broken
fixes issue 0004785
(I am not sure my check for a face it too ambitious. Maybe less code is necessary?)
> [PD] fix issue 0004785

- src/Mod/Path/CMakeLists.txt
- src/Mod/Path/Generators/drill_generator.py
- src/Mod/Path/PathTests/TestPathDrillGenerator.py
- src/Mod/Path/TestPathApp.py
Refactoring the drilling operation.  This creates a new 'generator' for creating drilling gcode.  It introduces full testing for the generator but does not affect the current drill operation yet. …
> [PATH] Drilling refactor part 1 - Generator and testing

- src/Mod/Path/PathScripts/PathProfile.py
Added logic to compare hashCodes()
https://forum.freecadweb.org/viewtopic.php?f=13&t=50567
---
> [Path] face outerwires aren't always the first wire in the Wires list.

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
fixes #4790
https://forum.freecadweb.org/viewtopic.php?f=3&t=63909
> [Sketcher][Bugfix] Fix crash when applying 'Constrain internal alignment' on contraints

- src/Mod/Path/PathScripts/PathUtils.py
- src/Mod/Path/PathTests/TestPathDepthParams.py
> [PATH]  depthparams handles negative steps and finish step correctly. Unit tests

- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/Gui/SketchOrientationDialog.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=63956
> [Sketcher] XZ plane mapping + parallel/align check in carbon copy

- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.h
Triggered by pressing Ctrl key when creating the slot
Extra constraint is added in case snapping is enabled
> [Sketcher] Ability to snap slot horizontal/vertical

- src/Gui/DocumentRecovery.cpp
- [ *]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ *]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas …
> Replace deprecated qt functions toList() & toSet()

- src/Mod/Draft/draftguitools/gui_setstyle.py
- src/Mod/Draft/draftviewproviders/view_layer.py
Draft_SetStyle and Draft_Layer did not handle PointColor and PointSize.
Additionally:
`gui_setstyle.py`:
* Fixed the `DisplayMode` code which did not work as `vobj.Proxy.getDisplayModes(vobj)` returns an empty list for some reason.
* Also set the `DefaultShapeVertexColor` parameter to the `LineColor`. This parameter works since #4954. It is not used by the Draft WB. But updating the parameter does make sense from the perspective of the user I think.
`view_layer.py`:
* Changed wrong use of `_tr` to `translate` as discussed in #5130.
* Removed `FontColor` as it is not used anywhere in the FreeCAD code.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=59604
**Note**: If you don't …
> Draft: Draft_SetStyle and Draft_Layer did not handle PointColor and PointSize.

- src/Tools/fcbt/CreatePyModule.py
> Tools: small bug fix

- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
Fix segfault introduced in 834ae29ad00b2
> [Sketcher][Bugfix] Slot: fix segfault accessing empty vector

- src/Gui/DlgSettingsMacro.ui
> [Gui] Preferences - Change macro path selection from File to Folder

- src/Mod/Path/Generators/rotation_generator.py
- src/Mod/Path/PathTests/TestPathRotationGenerator.py
> [PATH] rotation generator and tests

- src/Gui/3Dconnexion/3DConnexion.xml
Adding back the defaults I created for the SpaceExplorer.  I somehow managed to delete them last time when adding the SpaceNavigator afterwards.
> GUI: Added back defaults for SpaceExplorer

- src/Mod/PartDesign/App/FeatureHelix.cpp
the current routine fails for the growth mode.
This PR fixes this by handling this case separately from the other modes.
> [PD] fix calculation of possible Helix intersections

- src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp
- src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp
- src/Mod/PartDesign/Gui/TaskTransformedParameters.h
- src/Mod/PartDesign/Gui/ViewProviderMultiTransform.cpp
- src/Mod/PartDesign/Gui/ViewProviderMultiTransform.h
> PD: 0004582: Multi-transformation dialog cannot be cancelled

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftguitools/gui_edit.py
- src/Mod/Draft/draftguitools/gui_points.py
- src/Mod/Draft/draftguitools/gui_polygons.py
- src/Mod/Draft/draftguitools/gui_texts.py
This PR fixes a number of task panel issues:
Draft_Line:
Undo button had no purpose.
Draft_Arc, Draft_Circle, Draft_Polygon and Draft_Point:
Relative toggle had no purpose.
Draft_Text:
Relative toggle had no purpose.
Continue toggle was missing on the first task panel.
The "T" shortcut for the Continue toggle on the second task panel should not be shown.
Additionally:
In gui_edit.py `self.ui.isRelative.show()` was removed as was is superfluous.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=58234
Note that this PR does not address all issues mentioned in the topic. …
> Draft fix task panel issues

- src/Mod/Path/PathScripts/PathPreferences.py
- src/Mod/Path/PathScripts/PathThreadMilling.py
- src/Mod/Path/PathScripts/PathThreadMillingGui.py
- src/Mod/Path/PathScripts/PathVcarve.py
- src/Mod/Path/PathScripts/PathVcarveGui.py
- src/Mod/Path/PathScripts/PathWaterline.py
- src/Mod/Path/PathScripts/PathWaterlineGui.py
- src/Mod/Path/PathSimulator/App/PathSim.cpp
- src/Mod/Path/PathTests/TestPathThreadMilling.py
- src/Mod/Path/PathTests/TestPathVcarve.py
and also correct typo in author's name
> Path: fix file header uniformity

- src/Gui/DockWindowManager.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=64517
> [Gui] Ensure dockwidget is stacked on top when activated

- src/Mod/ReverseEngineering/App/ApproxSurface.cpp
For the purpose of making the source documentation uniform, source comments in this file were translated to english.
> ReverseEngineering: translate doxygen from DE to EN

- src/Mod/Cam/App/AppCamPy.cpp
- src/Mod/Cam/App/BRepAdaptor_CompCurve2.cxx
- src/Mod/Cam/App/BRepAdaptor_CompCurve2.h
- src/Mod/Cam/App/best_fit.cpp
- src/Mod/Cam/App/best_fit.h
- src/Mod/Cam/App/deviation.cpp
- src/Mod/Cam/App/deviation.h
- src/Mod/Cam/App/routine.cpp
- src/Mod/Cam/App/routine.h
For the purpose of making the source documentation uniform, source comments in this file were translated to english.
More PRs to follow
> Cam: translate doxygen from DE/FR to EN

- src/Mod/Path/PathScripts/PathOpGui.py
- src/Mod/Path/PathScripts/PathProfile.py
- src/Mod/Path/PathScripts/PathProfileGui.py
This is a a fix for the issue described here: https://forum.freecadweb.org/viewtopic.php?f=15&t=64336
This is a limited implementation of several translation fixes and just for the profile op/gui.  The same changes will need to be applied across much of Path.
The specific things addressed here:
translation uses QtCore.QT_TRANSLATE_NOOP
Combobox enums are defined in the operation code
Suggestion for how to regularize translation across path are very welcome. …
> [PATH]  Bug/translation

- src/Mod/Arch/ArchWindow.py
FreeCAD Forum Discussion :
- on Intuitive Automatic Windows/Doors Placement
- https://forum.freecadweb.org/viewtopic.php?f=23&t=50802
---
> [ArchWindow] add SketchArch attachment support (2nd attempt)

- src/Mod/Arch/ArchEquipment.py
FreeCAD Forum Discussion :
- on Intuitive Automatic Windows/Doors Placement
- https://forum.freecadweb.org/viewtopic.php?f=23&t=50802
---
> [ArchEquipment] add SketchArch attachment support (3rd attempt)

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- actually use specified thread depth, fixes issue reported here: https://github.com/FreeCAD/FreeCAD/pull/4274#issuecomment-997787744
- fixes 2 UI enabling issues
- the thread depth cannot be longer than the hole depth
- the hole cannot be deeper than the through-all depth
> [PD] fix several hole thread issues

- src/Mod/Mesh/App/Core/Algorithm.cpp
- src/Mod/Mesh/App/Core/Elements.h
- src/Mod/Mesh/App/Core/Grid.cpp
For the purpose of making the source documentation uniform, source comments in this file were translated to english.
> Mesh: translate doxygen from DE to EN

- src/Base/BoundBox.h
- src/Base/Tools2D.cpp
For the purpose of making the source documentation uniform, source comments in this file were translated to english.
> Base: translate doxygen from DE/FR to EN

- src/Mod/Sketcher/App/Sketch.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=64599
https://tracker.freecadweb.org/view.php?id=4621
Set as Draft PR while getting community feedback about new behavior in the forum (link above)
> [Sketcher] Ensure reference angle constraint is always positive

- src/Mod/Cam/App/path_simulate.cpp
Fix mistranslation introduced in 1c83d8feddd
> Cam: fix previously mistranslated source comment

- src/Gui/MainWindow.cpp
See https://forum.freecadweb.org/viewtopic.php?p=556465#p556465
---
> [Gui] MainWindow New Doc camera position bugfix

- src/Mod/Sketcher/App/GeoEnum.cpp
- src/Mod/Sketcher/App/GeoEnum.h
- src/Mod/Sketcher/App/GeoList.cpp
- src/Mod/Sketcher/Gui/PreCompiled.h
> Sketcher: fix build failures with MSVC

- src/Mod/Draft/importAirfoilDAT.py
The `importAirfoilDAT.py` code could not handle several *.dat files posted in a forum topic.
The old code did not handle:
* Blank lines.
* Total number of upper and lower points on the 2nd line.
* Negative X coordinates ('officially' not allowed, but they do occur).
Additionally:
* `doc.recompute()` was moved to the `open` and `insert` functions.
* `doc.Label` in the `open` function stripped 4 characters from the name, but the extension was already removed.
* The wire was not placed in the created group in the `insert` function.
Forum links:
https://forum.freecadweb.org/viewtopic.php?p=558032#p558032
https://forum.freecadweb.org/viewtopic.php?p=557753#p557753 …
> Draft: fix several issues with importAirfoilDAT.py

- src/MacAppBundle/CMakeLists.txt
> Fix MacBundle relocation

- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathJobGui.py
Fixes bug #4645.
This PR adds a simple `integrityCheck()` method to Job object class.  The method is called on the Gui side before openning the task panel to edit the job.  The same method is also called upon document restoration.
A small amount of refactoring was needed in the Job object class to accommodate the new `integrityCheck()` method.
Forum discussion at [Ticket #4645 - Add python exceptions to PathJob.py](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=61563).
All Path WB unit tests are passing.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for …
> [Path] Fixes #4645

- .github/codespellignore
@wwmayer 
Next time the Codespell workflow runs, it will be ignored.
> Codespell: add rady to the ignorelist

- src/Mod/Path/Gui/Resources/panels/PageOpProfileFullEdit.ui
- src/Mod/Path/InitGui.py
- src/Mod/Path/PathCommands.py
- src/Mod/Path/PathScripts/PathArray.py
- src/Mod/Path/PathScripts/PathCollision.py
- src/Mod/Path/PathScripts/PathComment.py
- src/Mod/Path/PathScripts/PathCopy.py
- src/Mod/Path/PathScripts/PathCustom.py
- src/Mod/Path/PathScripts/PathCustomGui.py
- src/Mod/Path/PathScripts/PathDressupDragknife.py
- src/Mod/Path/PathScripts/PathFixture.py
- src/Mod/Path/PathScripts/PathGeom.py
- src/Mod/Path/PathScripts/PathHop.py
- src/Mod/Path/PathScripts/PathIconViewProvider.py
- src/Mod/Path/PathScripts/PathPlane.py
- src/Mod/Path/PathScripts/PathPropertyEditor.py
- src/Mod/Path/PathScripts/PathSanity.py
- src/Mod/Path/PathScripts/PathStock.py
- src/Mod/Path/PathScripts/PathStop.py
- src/Mod/Path/PathScripts/PathUtil.py
- src/Mod/Path/PathScripts/PathUtils.py
> Path Translation cleanup part 2 [PATH]

- src/Mod/Path/PathScripts/PathSetupSheet.py
- src/Mod/Path/PathScripts/PathSetupSheetGui.py
- src/Mod/Path/PathScripts/PathSetupSheetOpPrototypeGui.py
- src/Mod/Path/PathScripts/PathSimpleCopy.py
- src/Mod/Path/PathScripts/PathSimulatorGui.py
Translation cleanup for setupsheet, simplecopy and simulation files.
---
> [PATH] Bug/translation setupsheet

- src/Mod/Path/PathScripts/PathPost.py
- src/Mod/Path/PathScripts/PostUtils.py
- src/Mod/Path/PathScripts/post/gcode_pre.py
- src/Mod/Path/PathScripts/post/grbl_post.py
- src/Mod/Path/PathScripts/post/marlin_post.py
Additional translation cleanup for path workbench.  this focuses on files related to postprocessing and preprocessing (importing) gcode.
---
> [Path] Bug/translation post

- src/Mod/Draft/draftguitools/gui_trackers.py
- src/Mod/Draft/drafttaskpanels/task_shapestring.py
Static declared variable which should be non-static. The same variable is created as a mistake with self.
This is related to the discussion
https://forum.freecadweb.org/viewtopic.php?f=22&t=64727
> Draft: change static to non-static declared variables

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- add missing constraint for hole diameter
- add missing sets of angle constraints in the task dialog
> [PD] add missing hole constraint

- src/Mod/PartDesign/App/FeatureHole.cpp
fixes the issue reported here: https://forum.freecadweb.org/viewtopic.php?f=10&t=65035
> [PD] Hole: fix call of onChanged on restoration

- src/Mod/Draft/draftguitools/gui_snapper.py
Draft_Snap_Angle only worked for circular edges on a plane parallel to the XY plane of the global coordinate system.
Apart from `snapToAngles` function the related `snapToCenter` function also has been updated.
---
> Draft: make Draft_Snap_Angle work in 3D

- src/Mod/Path/PathScripts/PathSurface.py
This PR addresses and argument error in 3D Surface related to the OptimizeStepOverTransitions property.
Forum thread that served as an investigation is [3dSurface path goes back over already cut material](https://forum.freecadweb.org/viewtopic.php?f=15&t=64761).
Steps to reproduce using zipped file that follows:
[3D_Pocket_test_3.zip](https://github.com/FreeCAD/FreeCAD/files/7775550/3D_Pocket_test_3.zip)
1. Open Path workbench.
2. Select Shape object in tree.
3. Create Job using toolbar icon, clicking OK with all default values.
4. Select top face of model.
5. Create 3D Surface op using toolbar icon.
6. Set Final Depth to 10.0 mm
7. Set Layer Mode to Multi-pass.
8. Enable Optimize StepOver Transitions
9. Click OK to create op.
10. Errors thrown in report view.
Screenshot before fix, with …
> [Path] Fix 3D Surface OptimizeStepOverTransitions property error

- src/Mod/Fem/App/CMakeLists.txt
- src/Mod/Fem/App/FemMesh.cpp
- src/Mod/Fem/femmesh/meshtools.py
---
Possibly fixes some race conditions introduced in PR #4759.
Rebased and made a new draft instead of making a PR in that branch because it wasn't compiling without a rebase.
> [FEM] Same Optimizations from PR#4759 + Race Condition Fix

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- all 3 angles cannot be >= 180°
- also add missing minimum in UI for taper angle
> [PD] Hole: fix angle constraints

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftguitools/gui_trackers.py
> Draft: Use super() to call base class methods

- src/Mod/PartDesign/App/FeatureTransformed.cpp
Remove several report view messages that are not necessary for everyday use.
By request from the forum: 
https://forum.freecadweb.org/viewtopic.php?f=3&t=64900&start=20#p558962
> PartDesign: Silence noisy FeatureTransformed

- src/Mod/Part/App/Geometry.cpp
- src/Mod/Part/App/Geometry.h
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
- src/Mod/Sketcher/App/SketchObjectPy.xml
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
- src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
- src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_BSplineInsertKnot.svg
- src/Mod/Sketcher/Gui/Workbench.cpp
PR for adding knots in existing b-splines. The insertion itself uses `Geom_BSplineCurve::InsertKnot()` in the back-end.
Note: Please do not squash. The commits have changes in multiple workbenches.
> [Sketcher] [Part] Support for inserting knots in B-Spline

- src/Tools/_TEMPLATEPY_/Resources/icons/_TEMPLATEPY_Workbench.svg
Replacing inkscape svg by plain svg in addition to the same replacing [with this PR](https://github.com/FreeCAD/FreeCAD/commit/e4c2cc3c76cc3ca7e754cffbc879ec675083cc1b).
> Retaining best practice: replacing inkscape svg by plain svg

- src/Mod/Draft/draftguitools/gui_groups.py
The behavior of the Draft_SelectGroup command was a bit cryptic. Layers were also regarded as groups. And the selection result was not the same if a nested object, instead of the group that object was in, was selected. The new version selects all objects in the `Group` property of the selected groups (or group-like objects). Nested groups are selected, but their contents is not.
Additionally:
Fixed issues with `_tr` and `QT_TRANSLATE_NOOP`.
Reduced the comments in the `SelectGroup` class.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=60252 …
> Draft: fix Draft_SelectGroup

- src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
- src/Mod/PartDesign/Gui/TaskExtrudeParameters.h
- src/Mod/PartDesign/Gui/TaskPadParameters.cpp
- src/Mod/PartDesign/Gui/TaskPocketParameters.cpp
> [PD] sort out more Pad/Pocket code

- src/Mod/Path/PathScripts/PathSimulatorGui.py
- src/Mod/Path/PathScripts/post/dxf_post.py
> [Path]  bug fixes for dxf_post and simulator 

- src/Mod/Path/CMakeLists.txt
- src/Mod/Path/Gui/Resources/panels/DressUpLeadInOutEdit.ui
- src/Mod/Path/PathPythonGui/simple_edit_panel.py
- src/Mod/Path/PathScripts/PathDressupLeadInOut.py
Continuing after #5262 translation fixes for dressup operations.
---
> [PATH] Translation fixes for dressup operations

- src/Mod/Part/App/FeatureExtrusion.cpp
more code that is used twice into a subroutine
> [Part] Extrude: avoid code duplication

- src/Mod/Path/PathScripts/PathAreaOp.py
- src/Mod/Path/PathScripts/PathPocketBase.py
- src/Mod/Path/PathScripts/PathProfile.py
> [PATH] Add property to split arcs into G1/G0 segments

- src/Mod/Part/App/Attacher.cpp
- src/Mod/Part/App/Geometry.cpp
- src/Mod/Part/App/Tools.cpp
- src/Mod/Part/App/Tools.h
- src/Mod/Part/App/TopoShapeFacePyImp.cpp
For some surfaces (BSpline surface for example) the partial derivatives used to calculate the normal could be null, so the normal can't be computed using the cross product between the first partial derivatives on the parameters of the surface at this point. Another similar situation is ∂S/∂u parallel to ∂S/∂v.
To deal with this case an alternative method is added to compute the normal using second order derivatives.
An example is trying to attach a plane to the sphere poles. At this point  tangentU is not defined and ∂S/∂u is null, then the current code fails to do the attachment.
Note: In the sphere case, `LProp_SLProps::Normal()` still compute the normal at the poles (tangentU is null), but this is completly accidental due to diferences in the internal precision of the methods.
See …
> Part: Fix TangentPlane mode of attachment

- src/Mod/TechDraw/App/DrawViewDimension.cpp
Add new non-standard format spec '%w' to truncate trailing zeros from dimension values.  There is a [forum thread](https://forum.freecadweb.org/viewtopic.php?f=35&t=65507)
where I initiated discussion about the enhancement, and explained why it would be a good feature to have. …
> [TD] Add new non-standard format spec '%w' to truncate trailing zeros

- src/Mod/Path/PathScripts/PathPreferences.py
- src/Mod/Path/PathScripts/PostUtils.py
- src/Mod/Path/PathTests/TestPathPost.py
- src/Mod/Path/TestPathApp.py
A helper function in PostUtils.  This might be useful for postprocessors that can't handle arc (g2/g3) gcode.  Otherwise does not affect current functionality
---
> [Path] Feature/split arcs helper

- src/Mod/TechDraw/Gui/CommandAnnotate.cpp
> TechDraw: fix typos in CommandAnnotate.cpp

- src/Mod/Path/PathTests/TestPathPost.py
> [Path] Unit test breaks due to tolerance issue.  Disable this test

- src/Mod/Path/PathScripts/PathDeburr.py
- src/Mod/Path/PathScripts/PathDeburrGui.py
- src/Mod/Path/PathScripts/PathFixture.py
- src/Mod/Path/PathScripts/PathInspect.py
- src/Mod/Path/PathScripts/PathProbe.py
- src/Mod/Path/PathScripts/PathProbeGui.py
translation cleanup for deburr, fixture, inspect
---
> [Path] Bug/translate deburr, fixture, inspect, probe

- src/Mod/Path/Generators/helix_generator.py
- src/Mod/Path/Gui/Resources/panels/PageOpHelixEdit.ui
- src/Mod/Path/PathFeedRate.py
- src/Mod/Path/PathScripts/PathGui.py
- src/Mod/Path/PathScripts/PathHelix.py
- src/Mod/Path/PathScripts/PathHelixGui.py
- src/Mod/Path/PathTests/TestPathHelixGenerator.py
Refactor the helix operation to use new generator.
I found several problems with the helix code and resolved the.  I also added an extraoffset property similar to other operations.
I touched the base helix algorithm more than I expected so I'm marking this PR as draft.   I would appreciate any testing and reviews.  
---
> [Path] Feature/helix refactor

- src/Mod/TechDraw/Gui/TaskActiveView.cpp
- src/Mod/TechDraw/Gui/TaskCenterLine.cpp
- src/Mod/TechDraw/Gui/TaskCosVertex.cpp
- src/Mod/TechDraw/Gui/TaskCosmeticLine.cpp
- src/Mod/TechDraw/Gui/TaskDetail.cpp
- src/Mod/TechDraw/Gui/TaskLeaderLine.cpp
- src/Mod/TechDraw/Gui/TaskRichAnno.cpp
- src/Mod/TechDraw/Gui/TaskSectionView.cpp
- src/Mod/TechDraw/Gui/TaskWeldingSymbol.cpp
The 9 dialogs re-check existence of parameters that were already checked in the calling command.  This code is redundant. 
---
> [TD]remove redundant edits from 9 Task dialogs

- src/Mod/Path/PathScripts/PathDressupAxisMap.py
- src/Mod/Path/PathScripts/PathDressupZCorrect.py
- src/Mod/Path/PathScripts/PathDrilling.py
- src/Mod/Path/PathScripts/PathDrillingGui.py
- src/Mod/Path/PathScripts/PathVcarve.py
- src/Mod/Path/PathScripts/PathVcarveGui.py
Additional translation cleanup work
---
> Bug/translation dressup, drilling, vcarve

- src/Mod/Spreadsheet/App/PropertySheet.cpp
Reported in https://forum.freecadweb.org/viewtopic.php?p=564502&sid=9c9d40b0ae23c6ebd9429a7540ea8252#p564502
> Spreadsheet: fix dependency calculation on external spreadsheet

- src/Mod/OpenSCAD/Init.py
- src/Mod/OpenSCAD/InitGui.py
- src/Mod/OpenSCAD/OpenSCAD2Dgeom.py
- src/Mod/OpenSCAD/OpenSCADCommands.py
- src/Mod/OpenSCAD/OpenSCADFeatures.py
- src/Mod/OpenSCAD/OpenSCADTest/app/test_importCSG.py
- src/Mod/OpenSCAD/OpenSCADTest/gui/test_dummy.py
- src/Mod/OpenSCAD/OpenSCADUtils.py
- src/Mod/OpenSCAD/TestOpenSCADGui.py
- src/Mod/OpenSCAD/colorcodeshapes.py
- src/Mod/OpenSCAD/expandplacements.py
- src/Mod/OpenSCAD/exportCSG.py
- src/Mod/OpenSCAD/importCSG.py
- src/Mod/OpenSCAD/prototype.py
- src/Mod/OpenSCAD/replaceobj.py
- src/Mod/OpenSCAD/tokrules.py
This PR is *slightly* less cumbersome :sweat_smile:  if you hide whitespace via the Github UI
> OpenSCAD: pep8-ified + removed superfluous whitespace + uniform headers

- src/Mod/Path/Gui/Resources/Path.qrc
- src/Mod/Path/Gui/Resources/panels/PageOpAdaptiveEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpThreadMillingEdit.ui
- src/Mod/Path/InitGui.py
- src/Mod/Path/PathScripts/PathAdaptive.py
- src/Mod/Path/PathScripts/PathAdaptiveGui.py
- src/Mod/Path/PathScripts/PathPreferencesAdvanced.py
- src/Mod/Path/PathScripts/PathSelection.py
- src/Mod/Path/PathScripts/PathThreadMilling.py
- src/Mod/Path/PathScripts/PathThreadMillingGui.py
- src/Mod/Path/PathScripts/PathToolBit.py
- src/Mod/Path/PathScripts/PathToolBitCmd.py
- src/Mod/Path/PathScripts/PathToolBitEdit.py
- src/Mod/Path/PathScripts/PathToolBitGui.py
- src/Mod/Path/PathScripts/PathToolBitLibraryCmd.py
- src/Mod/Path/PathScripts/PathToolBitLibraryGui.py
- src/Mod/Path/PathScripts/PathToolController.py
- src/Mod/Path/PathScripts/PathToolControllerGui.py
- src/Mod/Path/PathScripts/PathToolLibraryEditor.py
- src/Mod/Path/PathScripts/PathToolLibraryManager.py
More translation cleanup. 
Task panel in adaptive moved to .ui file. 
---
> [PATH] Bug/translation  (threadmill, tools, toolcontroller, adaptive)

- src/3rdParty/libE57Format/src/CheckedFile.cpp
- src/3rdParty/libE57Format/src/ImageFileImpl.cpp
> libE57Format: Fix warnings -Wignored-qualifiers and -Wcomment

- src/Mod/Path/Gui/Resources/panels/PageOpPocketFullEdit.ui
- src/Mod/Path/InitGui.py
- src/Mod/Path/PathScripts/PathEngrave.py
- src/Mod/Path/PathScripts/PathEngraveBase.py
- src/Mod/Path/PathScripts/PathEngraveGui.py
- src/Mod/Path/PathScripts/PathMillFace.py
- src/Mod/Path/PathScripts/PathMillFaceGui.py
- src/Mod/Path/PathScripts/PathPocket.py
- src/Mod/Path/PathScripts/PathPocketBase.py
- src/Mod/Path/PathScripts/PathPocketBaseGui.py
- src/Mod/Path/PathScripts/PathPocketGui.py
- src/Mod/Path/PathScripts/PathPocketShape.py
- src/Mod/Path/PathScripts/PathPocketShapeGui.py
- src/Mod/Path/PathScripts/PathSelection.py
> [PATH] translation cleanup (engrave, millface, pocket)

- src/Gui/DlgEditor.ui
- src/Gui/DlgEditorImp.cpp
- src/Gui/DlgGeneral.ui
- src/Gui/DlgGeneralImp.cpp
- src/Gui/PythonConsole.cpp
- src/Gui/TextEdit.cpp
Also set the line number font in the text editor acording to the font in use.
---
> Gui: Add functionality to enable/disable block shape cursor in text editor and console

- src/Mod/Path/Gui/Resources/panels/PathEdit.ui
- src/Mod/Path/PathScripts/PathDressupDogbone.py
- src/Mod/Path/PathScripts/PathDressupHoldingTags.py
- src/Mod/Path/PathScripts/PathDressupPathBoundary.py
- src/Mod/Path/PathScripts/PathDressupPathBoundaryGui.py
- src/Mod/Path/PathScripts/PathDressupRampEntry.py
- src/Mod/Path/PathScripts/PathDressupTag.py
- src/Mod/Path/PathScripts/PathDressupTagGui.py
- src/Mod/Path/PathScripts/PathDressupTagPreferences.py
- src/Mod/Path/PathScripts/PathFeatureExtensions.py
- src/Mod/Path/PathScripts/PathFeatureExtensionsGui.py
- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathJobCmd.py
- src/Mod/Path/PathScripts/PathJobDlg.py
- src/Mod/Path/PathScripts/PathJobGui.py
- src/Mod/Path/PathScripts/PathPreferencesPathDressup.py
- src/Mod/Path/PathScripts/PathProfileContourGui.py
- src/Mod/Path/PathScripts/PathProfileEdgesGui.py
- src/Mod/Path/PathScripts/PathProfileFacesGui.py
> [PATH] More translation cleanup (job, profile, dressups)

- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/DrawUtil.h
- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/App/DrawViewDimension.h
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.h
- src/Mod/TechDraw/Gui/TaskDimension.cpp
- src/Mod/TechDraw/Gui/TaskDimension.h
- src/Mod/TechDraw/Gui/TaskDimension.ui
replacement for PR #5441 with correct version of TaskDimension.ui.
This PR adds the ability to override the layout of dimension and extension lines in linear dimensions. …
> [TD]Allow override of dimension line angles

- src/Mod/TechDraw/Init.py
- src/Mod/TechDraw/InitGui.py
- src/Mod/TechDraw/TestTechDrawApp.py
- src/Mod/TechDraw/moveViews.py
Refractoring root files of the TechDraw directory by 1) removing unused modules and variables and 2) formatting in black code style. I'm a bit more unsure about this one: there are sometimes weird imports in some of the init files that are unused in the file itself, but seem to be meant to be there... So this PR should definetely be tested before merging.
And please remember to update the Wiki with the features added or changed once this …
> [TechDraw] Refractor root files

- src/Mod/TechDraw/TDTest/DHatchTest.py
- src/Mod/TechDraw/TDTest/DLeaderRText.py
- src/Mod/TechDraw/TDTest/DProjGroupTest.py
- src/Mod/TechDraw/TDTest/DVAnnoSymImageTest.py
- src/Mod/TechDraw/TDTest/DVBalloonTest.py
- src/Mod/TechDraw/TDTest/DVDimensionTest.py
- src/Mod/TechDraw/TDTest/DVPartTest.py
- src/Mod/TechDraw/TDTest/DVSectionTest.py
Refractoring `TDTest` in TechDraw by 1) removing unused modules and variables and 2) formatting in black code style. The code should be tested before merging.
---
> [TechDraw] Refractor TDTest

- src/Mod/TechDraw/Gui/QGTracker.cpp
https://forum.freecadweb.org/viewtopic.php?f=35&t=65733
> [TD] Prevent crash when snapping leader line

- src/Gui/propertyeditor/PropertyItem.cpp
> Qt::TextColorRole is obsolete. Use ForegroundRole instead.

- src/Mod/TechDraw/InitGui.py
missing import in initGui preventing start of workbench
---
> [TD]restore missing import statement

- src/Mod/TechDraw/App/AppTechDraw.cpp
- src/Mod/TechDraw/App/AppTechDrawPy.cpp
- src/Mod/TechDraw/App/CMakeLists.txt
- src/Mod/TechDraw/App/FeatureProjection.cpp
- src/Mod/TechDraw/App/FeatureProjection.h
- src/Mod/TechDraw/App/ProjectionAlgos.cpp
- src/Mod/TechDraw/App/ProjectionAlgos.h
- src/Mod/TechDraw/App/TechDrawExport.cpp
- src/Mod/TechDraw/App/TechDrawExport.h
- src/Mod/TechDraw/Gui/CMakeLists.txt
- src/Mod/TechDraw/Gui/Command.cpp
- src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
- src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ProjectShape.svg
- src/Mod/TechDraw/Gui/TaskProjection.cpp
- src/Mod/TechDraw/Gui/TaskProjection.h
- src/Mod/TechDraw/Gui/TaskProjection.ui
- src/Mod/TechDraw/Gui/Workbench.cpp
- src/Mod/TechDraw/TDTest/TDPyTest.py
The Drawing Workbench is marked as "deprecated" since v0.17.  There are functions related to projections that exist only in Drawing.  This PR moves these functions to the TechDraw Workbench.   …
> [TD]migrate DrawingWB projection functions to TechDrawWB

- src/Mod/TechDraw/App/Geometry.cpp
- src/Mod/TechDraw/App/Geometry.h
- src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
- src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
- src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg
- src/Mod/TechDraw/Gui/Workbench.cpp
The first commit adds the new tool AreaAnnotation which calculates the area of selected faces.
The second commit introduces a new method Intersection calculating the intersections of line-line, line--circle and circle--circle into the DrawUtil class.
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 …
> [TD] Tech draw extensions04

- src/Mod/Part/App/FeatureExtrusion.cpp
- src/Mod/Part/App/FeatureExtrusion.h
this is a PR to make Extrude handle inner wires of sketches.
Forum thread for this PR: https://forum.freecadweb.org/viewtopic.php?f=10&t=65171
> [Part] handle inner wires for Extrude

- src/Mod/Part/App/AppPartPy.cpp
See discussion here:
https://forum.freecadweb.org/viewtopic.php?f=10&t=65781
> Part.show() python return the new document object instead of None

- src/Mod/TechDraw/App/FeatureProjection.cpp
- src/Mod/TechDraw/App/ProjectionAlgos.cpp
- src/Mod/TechDraw/App/ProjectionAlgos.h
- src/Mod/TechDraw/Gui/TaskProjection.h
Fix header uniformity  
Fix grammar  
Fix trailing whitespace
> TD: cleanup after #5457

- package/fedora/freecad.spec
- package/fedora/rpkg.conf
- package/fedora/rpkg.macros
- [N/A]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [N/A]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`
And please remember to update the Wiki with …
> CI/packaging: COPR fix v41

- rpkg.macros
- [N/A]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [N/A]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes …
> ci/packaging: add missing rpkg.macros

- src/Mod/Arch/Presets/profiles.csv
North America Lumber set of dimensions contained some error.
---
> Arch: Fix some dimensions in profiles.csv

- src/Mod/Draft/Resources/ui/preferences-draftsnap.ui
https://forum.freecadweb.org/viewtopic.php?f=8&t=26277
> [Draft] Grid size as quantity rather than double

- src/Mod/Draft/draftobjects/pointarray.py
https://forum.freecadweb.org/viewtopic.php?f=3&t=65709
Draft PointArray Count property is always 0.  This fixes it to contain the number of elements in the point array.
> Draft: pointarray set Count property during execute

- src/Mod/TechDraw/App/DrawProjGroup.cpp
- src/Mod/TechDraw/App/DrawProjGroup.h
- src/Mod/TechDraw/Gui/TaskProjGroup.cpp
I am a very unexperinced C++ developer, so please look through, that I got pointers and adresses correct.
---
> [TechDraw] Improve code simplicity/readability of DrawProjGroup.cpp

- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/DrawUtil.h
- src/Mod/TechDraw/App/DrawViewDetail.cpp
- src/Mod/TechDraw/App/DrawViewDetail.h
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
- src/Mod/TechDraw/Gui/QGIMatting.cpp
- src/Mod/TechDraw/Gui/TaskDetail.cpp
This PR is a collection of fixes for the Detail view.  The biggest change is to fix issue 4486 detail view of non-solids.   There are also small fixes for matting size, a bad preference path and avoiding a segfault. …
> [TD]Detail View Fixes

- src/Mod/TechDraw/Gui/SymbolChooser.cpp
- src/Mod/TechDraw/Gui/SymbolChooser.h
- Resizing of weld symbol selection dialog, fixes # 0004386
- Only update weld dialog on directory change
- Refactor
---
> Improvement and bug fixes of weld symbol selection

- src/Mod/Path/PathScripts/PathSurface.py
- src/Mod/Path/PathScripts/PathToolBitGui.py
- src/Mod/Path/PathScripts/PathToolBitLibraryGui.py
- src/Mod/Path/PathScripts/PathToolLibraryEditor.py
- src/Mod/Path/PathScripts/PathUtils.py
- src/Mod/Path/PathScripts/PathWaterline.py
Fix bug with disambiguation string being None.
---
> [Path] Remove unnecessary third argument from translate() calls

- src/Mod/Draft/Resources/ui/preferences-draftsnap.ui
Fixes issue introduced in #5427
> [Draft] Fix widget property in preference UI

- .github/workflows/codespell.yml
Correction of a typo i made in the codespell workflow that results in no file being checked
> [Github] typo in codespell workflow

- src/Gui/ApplicationPy.cpp
In the code `NULL` is replaced by `nullptr`, the macro `Py_Return` is introduced.
In `createViewer()` the argument `views` is limited to positive values, otherwise an exception is raised.
In `sAddPreferencePage` duplicate code is removed. …
> Gui: Improve the docstrings and clean up code in ApplicationPy.cpp

- src/Mod/TechDraw/Gui/QGVPage.cpp
Some TechDraw templates still contain Inkscape-centric SVG.  When exporting a Page, the exported SVG doesn't not include namespace definition for "sodipodi" (predecessor of Inkscape).  This PR adds the missing namespace definition.  …
> [TD]Add sodipodi namespace to exported SVG

- src/Mod/TechDraw/CMakeLists.txt
CMake fc_target_copy_resource and install commands for gui only components are not protected when build_Gui switch is off.
---
> [TD]fix CMakeLists.txt to allow no-Gui build

- src/Base/MatrixPyImp.cpp
https://forum.freecadweb.org/viewtopic.php?f=10&t=65941
> Base: fix bug in matrix multiplication (Python API)

- src/Gui/Workbench.cpp
- src/Mod/Part/Gui/CMakeLists.txt
- src/Mod/Part/Gui/Command.cpp
- src/Mod/Part/Gui/SectionCutting.cpp
- src/Mod/Part/Gui/SectionCutting.h
- src/Mod/Part/Gui/SectionCutting.ui
* one aim is to have a feature to make real cuts, not hollow ones like with clipping
* the second one is to have a persistent view, so an object in the tree that can be further exported, meshed etc.
For a detailed description with examples see https://forum.freecadweb.org/viewtopic.php?f=17&t=52441
> [Part] feature to make persistent section cut views

- src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
as suggested recently by @chennes
@chennes , when this is correct, please merge (compiles for me, but I want to have a double-check)
> [PD] Extrude: modernize SignalSlot connection

- src/Mod/Path/PathMachineState.py
- src/Mod/Path/PathScripts/PathToolControllerGui.py
Fix toolcontroller import bug
remove dataclass usage.
---
> [PATH]  Toolcontroller import startup bug

- src/Base/Matrix.cpp
Those function was used by a commented code, hence never called.
Since it don't have been change for a long time,
it should be safe to remove them.
---
> Base: Remove old unused C-style function

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
https://forum.freecadweb.org/viewtopic.php?f=10&t=65499
> [Sketcher] Fix check for fixed items in tangent+perpendicular

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=65549
> [Sketcher] Fix section mode automation

- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
Gives some context to where the knot is going to be inserted w.r.t. other knots in the b-spline.
> [Sketcher] Give knot information in insert knot command

- src/Gui/Workbench.cpp
- src/Mod/Part/Gui/Command.cpp
- src/Mod/Part/Gui/Workbench.cpp
Since the command alters the document, `AlterDoc`is masked to 1.
---
> Part: Move Part_SectionCut command to Part menu item list

- src/Gui/Widgets.cpp
- src/Mod/Part/Gui/SectionCutting.cpp
- src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
This commit converts Qt5 C++11 compatible signal/slot connection to Qt5 >C++14 way, which is more readable.
> Modernize signal/slot connection for real :)

- src/Mod/Path/InitGui.py
Submenu titles are still not getting translated.  Fixed context strings.
---
> [Path] Workbench context for menus

- README.md
requested in forum: https://forum.freecadweb.org/viewtopic.php?p=570177#p570177
> Update README.md installation info

- src/Mod/TechDraw/App/ShapeExtractor.cpp
- src/Mod/TechDraw/App/ShapeExtractor.h
Shells within compounds were not being handled correctly in the shape extraction process. 
---
> [TD]fix handling of composite shapes

- src/Mod/Image/Gui/Command.cpp
to overwrite random color.
https://forum.freecadweb.org/viewtopic.php?f=8&t=66270
> [Image] Set ImagePlane ShapeColor white at creation

- src/Mod/Part/Gui/SectionCutting.cpp
- src/Mod/Part/Gui/SectionCutting.h
all changes as suggested in https://github.com/FreeCAD/FreeCAD/pull/4118/files/05a9c88ab2dad40d4393203bed5aa861e5587d8d
> [Part] improve SectionCutting code

- src/Gui/DocumentPy.xml
- src/Gui/DocumentPyImp.cpp
In `toggleTreeItem()` the logic is changed to return `nullptr` if `PyArg_ParseTuple` fails.
---
> Gui: Improve docstrings and clean up code in Python Gui.Document class

- src/Mod/Part/Gui/Command.cpp
> Part: Part_SectionCut command active only if view is View3DInventor class

- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
See https://forum.freecadweb.org/viewtopic.php?f=19&t=64962&p=569081#p568723.
~This PR will stay as a draft until the issue is created and discussed.~ See #6324
> [Sketcher] Fix segfault inserting knot in old b-spline

- src/Gui/Splashscreen.cpp
Adds some Mod installation info to the string you get when you click "Copy to clipboard" in the About FreeCAD dialog. Version info is pulled from package.xml, so is only available for Addons that provide that metadata file. I tried to tighten up the display of the other version info so this didn't get too long, but I still think the major downside here is that if you have a lot of addons it's going to get lengthy. You can always edit when you paste it, of course.
Fixes https://github.com/FreeCAD/FreeCAD-addons/issues/199
> Gui: Add Mod info to copied About string

- src/Mod/Path/Gui/Resources/preferences/Advanced.ui
- src/Mod/Path/InitGui.py
- src/Mod/Path/PathScripts/PathPreferences.py
- src/Mod/Path/PathScripts/PathPreferencesAdvanced.py
> [Path] Warn user if current schema doesn't generate proper velocity (unit/min)

- src/Mod/Tux/NavigationIndicatorGui.py
https://forum.freecadweb.org/viewtopic.php?f=8&t=26277&start=10#p565344
Ping @yorikvanhavre :)
> Tux: get rid of timer usage to update navigation style

- src/Mod/TechDraw/Gui/CMakeLists.txt
- src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
- src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
- src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg
- src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCustomizeFormat.svg
- src/Mod/TechDraw/Gui/TaskCustomizeFormat.cpp
- src/Mod/TechDraw/Gui/TaskCustomizeFormat.h
- src/Mod/TechDraw/Gui/TaskCustomizeFormat.ui
- src/Mod/TechDraw/Gui/Workbench.cpp
This PR includes 3 commits:
1) Force tree update when dimensions are created
2) Some icons and ui-files
3) The new extension tool: customize format.  Description will follow soon in wiki. …
> [TD] Techdraw new tool and improvements

- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.h
- src/Mod/Sketcher/Gui/EditModeCoinManager.cpp
- src/Mod/Sketcher/Gui/EditModeCoinManager.h
- src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h
- src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
- src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.h
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
https://forum.freecadweb.org/viewtopic.php?f=10&t=65465
Set as Draft PR time it's tested
> [Sketcher] Disable constraints selection when geometry/constraint handler is active

- src/Mod/PartDesign/App/FeaturePocket.cpp
..removed by https://github.com/FreeCAD/FreeCAD/commit/61d54b60786a0b7cefc44f965cf5d179726a8d20
Tested against : 
OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Version: 0.20.27663 (Git)
Branch: master
Hash: 5007c8358c21f2da5a08684f1e00247c1a842d7d
Python 3.6.9, Qt 5.9.5, Coin 4.0.0a, OCC 7.3.0
Locale: English/UnitedKingdom (en_GB)
and
OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Version: 0.20.27663 (Git)
Branch: master
Hash: 5007c8358c21f2da5a08684f1e00247c1a842d7d
Python 3.6.9, Qt 5.9.5, Coin 4.0.0a, OCC 7.6.0.beta
Locale: English/UnitedKingdom (en_GB)
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests …
> [PartDesign] OCC7.3 regression replace include..

- src/Gui/DlgPreferencesImp.cpp
based on [commit](https://github.com/Syres916/FreeCAD/commit/b1effe2250dd17fbf632b0b65f94a9f60d0533ca)
forum thread [thread](https://forum.freecadweb.org/viewtopic.php?f=8&t=66410)  
This PR replaces #6398
> [GUI] Adjust Preferences dialog display position to be fully visible.

- src/Mod/Spreadsheet/Gui/LineEdit.cpp
Reported in https://forum.freecadweb.org/viewtopic.php?f=3&t=66395
> Spreadsheet: fix auto completer triggering

- src/Mod/Draft/App/DraftDxf.cpp
- src/Mod/Draft/draftfunctions/array.py
- src/Mod/Draft/draftguitools/gui_array_simple.py
- src/Mod/Draft/draftmake/make_array.py
- src/Mod/Draft/draftmake/make_copy.py
- src/Mod/Draft/importSVG.py
This PR is a continuation of https://github.com/FreeCAD/FreeCAD/pull/6337
Should be the last one...
---
> Draft: Housekeeping: call 'make' functions with new name (4)

- src/Mod/Draft/draftfunctions/dxf.py
- src/Mod/Draft/draftfunctions/svg.py
- src/Mod/Draft/draftfunctions/svgshapes.py
- src/Mod/Draft/draftobjects/shape2dview.py
- src/Mod/Draft/importDXF.py
> Draft: Replace Drawing functions with TechDraw functions

- src/Gui/DlgAddProperty.cpp
- src/Gui/PropertyView.cpp
- src/Gui/PropertyView.h
- src/Gui/ViewParams.h
- src/Gui/propertyeditor/PropertyEditor.cpp
- src/Gui/propertyeditor/PropertyEditor.h
- src/Gui/propertyeditor/PropertyItem.cpp
- src/Gui/propertyeditor/PropertyItem.h
- src/Gui/propertyeditor/PropertyItemDelegate.cpp
- src/Gui/propertyeditor/PropertyItemDelegate.h
- src/Gui/propertyeditor/PropertyModel.cpp
- src/Gui/propertyeditor/PropertyModel.h
Forum post: https://forum.freecadweb.org/viewtopic.php?f=10&t=46388&p=403983#p403983
> Gui: improve PropertyEditor refresh

- src/App/Document.cpp
- src/App/Document.h
- src/App/DocumentObject.cpp
- src/App/DocumentObject.h
- src/App/Property.cpp
- src/App/PropertyContainer.h
- src/App/Transactions.cpp
- src/App/Transactions.h
- src/Gui/Document.cpp
- src/Gui/ViewProviderDocumentObject.cpp
- src/Gui/ViewProviderDocumentObject.h
- src/Mod/Part/App/PartFeature.cpp
- src/Mod/Part/Gui/ViewProviderExt.cpp
- src/Mod/Part/Gui/ViewProviderExt.h
Related #0004265
See https://tracker.freecadweb.org/view.php?id=4265#c14271
> App: fix property ordering problem when undo/redo

- src/Gui/DlgEditorImp.cpp
> Gui: Change the editor preferences preview to Python 3

- src/App/Application.cpp
- src/App/Application.h
- src/App/ApplicationPy.cpp
> [App] Application: remove unused includes

- src/Mod/TechDraw/PAT/FCPAT.pat
A new diagonal hatch type (flipped) is added to default patterns for the TechDraw GeometricHatch tool. Very useful for technical drawings involving assemblies, compound parts and different materials.
Forum discussion: https://forum.freecadweb.org/viewtopic.php?f=35&t=66517 …
> [TD] Add new diagonal hatch (flipped)

- src/Mod/Robot/App/Trajectory.cpp
- src/Mod/Robot/App/TrajectoryDressUpObject.cpp
- src/Mod/Robot/App/Waypoint.cpp
- src/Mod/Robot/App/Waypoint.h
- src/Mod/Robot/App/WaypointPyImp.cpp
- src/Mod/Robot/App/kdl_cp/chainfksolver.hpp
- src/Mod/Robot/App/kdl_cp/treefksolver.hpp
- src/Mod/Robot/Gui/AppRobotGui.cpp
- src/Mod/Robot/Gui/CommandTrajectory.cpp
- src/Mod/Robot/Gui/TaskTrajectory.cpp
- src/Mod/Robot/Gui/TrajectorySimulate.cpp
- Accelaration -> Acceleration
- plus some style fixes done by MSVC
> [Robot] fix typo reported by spellchecker CI

- src/Tools/wiki2qhelp.py
I hope this has no unforeseen side-effects
> [Tools] rename a variable to silence the spellchecker CI

- src/Mod/AddonManager/NetworkManager.py
The code that followed redirects was resulting in a double-download of the data. This corrects the problem by manually re-queueing a new network request for each redirect, instead of trying to tell the QNetworkAccessManager to follow them automatically.
> Addon Manager: Fix corrupted ZIP downloads

- src/Mod/Arch/ArchComponent.py
- src/Mod/Arch/ArchPanel.py
- src/Mod/Arch/ArchSectionPlane.py
- src/Mod/Arch/ArchSite.py
> Arch: Replace Drawing functions with TechDraw functions

- src/Mod/TechDraw/Gui/TaskWeldingSymbol.ui
Improve weld task tool tips, partially fixes #0004838.
---
> [TechDraw] Improve weld task tool tips

- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
New tool(s):
- Press "D" to open a dialog to set the degree.
> [Sketcher] Some tools for more control over b-splines at creation

- src/Mod/TechDraw/App/EdgeWalker.h
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawColors.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawColorsImp.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneralImp.cpp
- src/Mod/TechDraw/Gui/PreferencesGui.cpp
- src/Mod/TechDraw/Gui/PreferencesGui.h
- src/Mod/TechDraw/Gui/QGVPage.cpp
- src/Mod/TechDraw/Gui/QGVPage.h
- src/Mod/TechDraw/Gui/ViewProviderDrawingView.h
- src/Mod/TechDraw/Gui/ViewProviderPage.cpp
- src/Mod/TechDraw/Gui/ViewProviderPage.h
This PR adds an alignment grid function to Pages and adds associated preferences.
---
> [TD]add alignment grid to page

- src/Mod/Import/App/dxf.cpp
This PR fixes issue #6461 where mm to inch calculation was performed twice for certain values of MEASUREMENT and INSUNITS variables in the imported DXF file.
---
> [Import]Fix #6461 MEASUREMENT/INSUNITS

- src/Mod/AddonManager/addonmanager_utilities.py
Will especially work better if dark mode comes from OS settings.
> AddonManager: improve dark mode heuristic

- src/Mod/Spreadsheet/App/PropertySheet.cpp
> fix uninitialized variables

- src/Mod/Path/Gui/Resources/preferences/Advanced.ui
- src/Mod/Path/InitGui.py
- src/Mod/Path/PathScripts/PathPreferences.py
- src/Mod/Path/PathScripts/PathPreferencesAdvanced.py
> [Path] Fix bug with velocity warning.

- src/Gui/Action.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=65081#p564743
Set as Draft time it's discussed and tested.
@mwganson may you have a look ?
> [RecentMacros] Check and warn for shortcut conflicts + small fixes/improvements

- src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=66713
> [BUGFIX] PartDesign: fix crash in MultiTransform if moving on empty list

- src/Mod/Spreadsheet/Gui/SheetModel.cpp
> Code clean

- src/Mod/Arch/ArchPipe.py
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=66754
---
> Arch: Fix Arch_PipeConnector for pipes with non-zero wall thickness

- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/DrawDimHelper.cpp
- src/Mod/TechDraw/App/DrawGeomHatch.cpp
- src/Mod/TechDraw/App/DrawProjectSplit.cpp
- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/DrawViewDetail.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewPart.h
- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/GeometryObject.cpp
This PR fixes a misplaced section line due to a wrong bbox center.  Fix to use BRepBndLib::AddOptimal applied to other bbox calculations within TD as part of this PR.
- BRepBndLib::Add results in wrong bbox center.
- replaced with BRepBndLib::AddOptimal
**Note**: If you don't have wiki access, then please mention your contribution on the …
> [TD]fix misplaced section line

- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/App/Preferences.h
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvancedImp.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensionsImp.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneralImp.cpp
- src/Mod/TechDraw/Gui/PreferencesGui.cpp
- src/Mod/TechDraw/Gui/PreferencesGui.h
- src/Mod/TechDraw/Gui/QGVPage.cpp
- src/Mod/TechDraw/Gui/QGVPage.h
- src/Mod/TechDraw/Gui/ViewProviderPage.h
This PR has 2 parts.  The first makes the new page grid unit aware.  The second moves dimension format spec preference from Advanced tab to Dimension tab.
---
> [TD]Make grid unit aware + dimension preferences

- src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
This PR update menu text and tool tip format to match standards.  This is a follow on to PR #6382.
---
> [TD]update menu text and tip to standard

- src/Mod/TechDraw/Gui/ViewProviderPage.cpp
This PR fixes an issue with the page grid.  A temporary variable was declared as int instead of double.
---
> [TD]fix integer grid step variable to double

- src/Base/UnitsSchemaInternal.cpp
- src/Base/UnitsSchemaMKS.cpp
- src/Mod/Test/UnitTests.py
---
The first patch extends the unit test output, which helped to find the issue.
The second patch is the actual fix.
> Base: Fix character encoding for micro siemens

- src/Gui/propertyeditor/PropertyModel.cpp
Issue reported in https://forum.freecadweb.org/viewtopic.php?f=10&t=66810
> Gui: fix property view synchronization of property status

- src/Mod/Raytracing/App/RayProject.cpp
See discussion https://forum.freecadweb.org/viewtopic.php?f=4&p=577109#p577109
---
> [Raytracing] Bugfix for compiling with OCC 7.6.x

- src/App/AutoTransaction.h
as discussed here: https://github.com/FreeCAD/FreeCAD/commit/c96f61b0a1e3ab15cc2cb198fdbe58ce4a5d8c59#commitcomment-68066635
> [App] add a missing return statement

- src/App/AutoTransaction.h
as proposed here: https://github.com/FreeCAD/FreeCAD/pull/6519#discussion_r820641762
> [App] AutoTransaction: a change to silence MSVC compiler

- src/Gui/CMakeLists.txt
- src/Gui/PreCompiled.h
- src/Gui/QtAll.h
- src/Mod/Assembly/Gui/PreCompiled.h
- src/Mod/Cam/Gui/PreCompiled.h
- src/Mod/Cloud/Gui/PreCompiled.h
- src/Mod/Drawing/Gui/PreCompiled.h
- src/Mod/Fem/Gui/PreCompiled.h
- src/Mod/Image/Gui/PreCompiled.h
- src/Mod/Import/Gui/PreCompiled.h
- src/Mod/Inspection/Gui/PreCompiled.h
- src/Mod/Mesh/Gui/PreCompiled.h
- src/Mod/MeshPart/Gui/PreCompiled.h
- src/Mod/Part/Gui/PreCompiled.h
- src/Mod/PartDesign/Gui/PreCompiled.h
- src/Mod/Path/Gui/PreCompiled.h
- src/Mod/Points/Gui/PreCompiled.h
- src/Mod/Raytracing/Gui/PreCompiled.h
- src/Mod/ReverseEngineering/Gui/PreCompiled.h
- src/Mod/Robot/Gui/PreCompiled.h
- src/Mod/Sketcher/Gui/PreCompiled.h
- src/Mod/Spreadsheet/App/PreCompiled.h
- src/Mod/Spreadsheet/Gui/PreCompiled.h
- src/Mod/Start/Gui/PreCompiled.h
- src/Mod/Surface/Gui/PreCompiled.h
- src/Mod/TechDraw/Gui/PreCompiled.h
- src/Mod/Test/Gui/PreCompiled.h
- src/Mod/Web/Gui/PreCompiled.h
- src/Tools/_TEMPLATE_/Gui/PreCompiled.h
As discussed here: https://github.com/FreeCAD/FreeCAD/pull/6503#issuecomment-1060394106
> [Gui] rename the Qt header list

- src/Gui/DAGView/DAGFilter.cpp
- src/Gui/DAGView/DAGModel.cpp
- src/Gui/DAGView/DAGModel.h
- src/Gui/DAGView/DAGModelGraph.cpp
- src/Gui/DAGView/DAGModelGraph.h
- src/Gui/DAGView/DAGRectItem.cpp
- src/Gui/DAGView/DAGRectItem.h
- src/Gui/DAGView/DAGView.cpp
- src/Gui/DAGView/DAGView.h
mainly the headers are just sorted
> [Gui] DAGView: remove few includes

- src/Mod/Arch/ArchStructure.py
I accidentally created a bug in the PR #3229 (sorry!), the code checked for the existance of the `BaseMirror` property and not if it's value was `true`. As a result, the structure base was always mirrored, even if the property was set to `false`.
Warning: The fix will change the geometry of some existing `ArchStructure` objects (those with `BasePerpendicularToTool = true`, `BaseMirror = false` and non symmetrical `Base`) on recompute. Since the property is not yet documented in the wiki it shoudn't affect a lot of users.
> And please remember to update the Wiki with the features added or changed once this PR is merged.  
> **Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=561 …
> Arch: fix BaseMirror property

- src/Mod/TechDraw/Gui/PreferencesGui.cpp
This PR changes the default setting for the ShowGrid property to OFF.
---
> [TD]Change grid default to OFF

- src/Mod/Part/Gui/Command.cpp
as discussed here: https://forum.freecadweb.org/viewtopic.php?p=577536#p577536
> [Part] change sGroup for Section Cut

- src/Mod/Part/CompoundTools/Explode.py
- src/Mod/Part/CompoundTools/_CommandExplodeCompound.py
> Part: Check geometry in Part_ExplodeCompound command

- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp
Forum discussions: https://forum.freecadweb.org/viewtopic.php?f=10&t=66908, https://forum.freecadweb.org/viewtopic.php?f=10&t=66957.
> [Sketcher] Fix occasional crash after deleting last pole in b-spline creation mode

- src/Gui/propertyeditor/PropertyItem.cpp
Reported in https://forum.freecadweb.org/viewtopic.php?f=10&t=66992
> Gui: fix crash on editing PropertyVectorList in property view

- src/Mod/Draft/draft.dox
> Minor Spelling Corrections to Draft.Dox

- src/Mod/TechDraw/App/DrawViewDimension.cpp
Angle dimensions sometimes provide supplementary angle instead of desired angle.  [Forum discussion](https://www.forum.freecadweb.org/viewtopic.php?f=35&t=66945)
---
> [TD]fix Dim text on wrong side

- src/Mod/Path/PathScripts/PathDressupRampEntry.py
This commit corrects an incorrect dictionary key in the enumeration dictionary updated with recent translation fixes.
Forum identification and discussion at [RampEntryDressup bugged](https://forum.freecadweb.org/viewtopic.php?f=15&t=66971). …
> Path: Fix enumeration dictionary error [Bug]

- src/Mod/Path/PathScripts/PathDressupLeadInOut.py
Add missing "Z" and "K" parameters for arc commands to appease Path simulator.
Forum identification at [Path Simulator : TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'](https://forum.freecadweb.org/viewtopic.php?f=15&t=66700).
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 …
> Path: Fix Leadin-Leadout dressup simulation related to arcs [Bug]

- src/Mod/TechDraw/App/DrawView.cpp
This PR fixes a condition where the scale for a new view is set incorrectly.
---
> [TD]fix getScale should be Scale.getValue

- src/Mod/PartDesign/App/ShapeBinder.cpp
- src/Mod/PartDesign/App/ShapeBinder.h
Reported in https://forum.freecadweb.org/viewtopic.php?f=8&t=67003
> PD: fix SubShapeBinder 'Fuse' function

- src/Mod/TechDraw/App/DrawViewDimension.cpp
This PR fixes the handling of a special case in 2 Edge Angle Dimensions. 
---
> [TD]fix 2 edge angle Dim special case

- src/Mod/Assembly/App/opendcm/core/constraint.hpp
- src/Mod/Assembly/App/opendcm/core/imp/clustergraph_imp.hpp
- src/Mod/Assembly/App/opendcm/core/imp/constraint_holder_imp.hpp
- src/Mod/Assembly/App/opendcm/core/imp/kernel_imp.hpp
- src/Mod/Assembly/App/opendcm/core/imp/system_imp.hpp
- src/Mod/Assembly/App/opendcm/core/kernel.hpp
- src/Mod/Assembly/App/opendcm/core/scheduler.hpp
- src/Mod/Assembly/App/opendcm/core/system.hpp
- src/Mod/Assembly/App/opendcm/module3d/module.hpp
- src/Mod/Assembly/App/opendcm/module3d/solver.hpp
- src/Mod/Assembly/App/opendcm/modulePart/module.hpp
all found by the spellchecker CI
> [Assembly] fox typos in element names

- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
Some deleted GeoIds can stay in selection and GeoIds can change as some objects
are deleted.
> [Sketcher] Fix "toggle internal geo" on multi-selection

- src/Gui/NavigationStyle.cpp
- src/Gui/ViewProvider.cpp
- src/Gui/ViewProvider.h
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
https://forum.freecadweb.org/viewtopic.php?p=578857#p578857
> Redraw constraints on wheel event

- src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py
issue #6371
Apply multi-thread configuration when Calculix is started via the task panel.
> Multi-thread support for Calculix taskpanel

- src/Gui/UiLoader.cpp
code by @wwmayer
as discussed here: https://forum.freecadweb.org/viewtopic.php?f=4&t=66137&p=570597
and here: https://forum.freecadweb.org/viewtopic.php?p=578860#p578860
> [Gui] UiLoader: fix compiler warning

- src/Gui/Inventor/MarkerBitmaps.cpp
- src/Gui/Inventor/SoAutoZoomTranslation.h
- src/Gui/InventorAll.h
- src/Gui/SoFCBackgroundGradient.cpp
- src/Gui/SoFCBackgroundGradient.h
- src/Gui/SoFCBoundingBox.cpp
- src/Gui/SoFCBoundingBox.h
- src/Gui/SoFCCSysDragger.cpp
- src/Gui/SoFCCSysDragger.h
- src/Gui/SoFCColorBar.cpp
- src/Gui/SoFCColorBar.h
- src/Gui/SoFCColorGradient.cpp
- src/Gui/SoFCColorGradient.h
- src/Gui/SoFCColorLegend.cpp
- src/Gui/SoFCColorLegend.h
- src/Gui/SoFCDB.cpp
- src/Gui/SoFCDB.h
- also sort out some headers for precompiled headers
> [Gui] So headers: remove some unused includes

- src/Mod/TechDraw/App/DrawViewDetail.cpp
- src/Mod/TechDraw/App/DrawViewDetail.h
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/App/Preferences.h
- src/Mod/TechDraw/Gui/PreferencesGui.cpp
- src/Mod/TechDraw/Gui/PreferencesGui.h
- src/Mod/TechDraw/Gui/QGIHighlight.cpp
- src/Mod/TechDraw/Gui/QGIMatting.cpp
- src/Mod/TechDraw/Gui/QGIMatting.h
This PR corrects a condition where a detail highlight is wrongly added to a detail view if the view is referenced in an expression in another detail view. 
[Forum discussion](https://www.forum.freecadweb.org/viewtopic.php?f=35&t=67068) …
> [TD]fix detail highlight on detail view

- src/Mod/Path/PathScripts/PathDressupAxisMap.py
- src/Mod/Path/PathScripts/PathDressupDogbone.py
- src/Mod/Path/PathScripts/PathDressupDragknife.py
- src/Mod/Path/PathScripts/PathDressupLeadInOut.py
- src/Mod/Path/PathScripts/PathDressupPathBoundaryGui.py
- src/Mod/Path/PathScripts/PathDressupRampEntry.py
- src/Mod/Path/PathScripts/PathDressupTagGui.py
- src/Mod/Path/PathScripts/PathDressupZCorrect.py
This commit removes the automatic committal of transactions when activated with GUI command.  The committal of the transaction is executed with the `accept()` and `reject()` methods of the respective task panel.
issue #6149 
fixes #6149 
No related forum thread found via "dressup cancel" search.
**Note**: If you don't have wiki access, then …
> Path: Fix automatic `commitTransaction()` calls, issue #6149 [Bug]

- src/Mod/TechDraw/App/DrawPage.cpp
- src/Mod/TechDraw/App/DrawPage.h
- src/Mod/TechDraw/App/DrawProjGroupItem.cpp
- src/Mod/TechDraw/App/DrawView.cpp
- src/Mod/TechDraw/Gui/ViewProviderPage.cpp
This PR fixes the KeepUpdated and UpdateWith3D update suppression logic. 
---
> [TD]fix update suppression logic

- src/Mod/Draft/draftguitools/gui_trackers.py
> [Draft] Don't take grid into account when View_FitAll

- src/Mod/TechDraw/App/DrawView.cpp
This PR fixes a condition where the default scale for a new view was set incorrectly if ScaleType is Page.
---
> [TD]fix default scale

- src/Mod/Part/Gui/SectionCutting.cpp
- src/Mod/Part/Gui/SectionCutting.h
- src/Mod/Part/Gui/SectionCutting.ui
- the color was not handled at all, leading to a lot of manual work
> [Part] Section cut: add missing color handling for the cut faces

- src/Mod/PartDesign/App/AppPartDesign.cpp
- src/Mod/PartDesign/App/AppPartDesignPy.cpp
- src/Mod/PartDesign/App/PreCompiled.h
- src/Mod/PartDesign/Gui/AppPartDesignGui.cpp
- src/Mod/PartDesign/Gui/PreCompiled.h
> [PD] remove Python.h from headers

- src/Mod/Part/App/AppPart.cpp
- src/Mod/Part/Gui/AppPartGui.cpp
- src/Mod/Part/Gui/BoxSelection.cpp
- src/Mod/Part/Gui/DlgFilletEdges.cpp
- src/Mod/Part/Gui/DlgPrimitives.cpp
- src/Mod/Part/Gui/DlgRevolution.cpp
- src/Mod/Part/Gui/DlgSettings3DViewPartImp.cpp
- src/Mod/Part/Gui/Mirroring.cpp
- src/Mod/Part/Gui/PreCompiled.h
- src/Mod/Part/Gui/SoBrepEdgeSet.cpp
- src/Mod/Part/Gui/SoBrepFaceSet.cpp
- src/Mod/Part/Gui/SoBrepPointSet.cpp
- src/Mod/Part/Gui/TaskCheckGeometry.cpp
- src/Mod/Part/Gui/TaskDimension.cpp
- src/Mod/Part/Gui/ViewProvider2DObject.cpp
- src/Mod/Part/Gui/ViewProviderCurveNet.cpp
- src/Mod/Part/Gui/ViewProviderHelixParametric.cpp
- src/Mod/Part/Gui/ViewProviderMirror.cpp
- src/Mod/Part/Gui/ViewProviderPython.cpp
- src/Mod/Part/Gui/ViewProviderReference.cpp
- src/Mod/Part/Gui/ViewProviderSpline.cpp
> [Part] remove Python.h from headers

- src/Mod/Path/PathScripts/PathOpTools.py
ref: https://lgtm.com/rules/910088/
---
> Path: remove superfluous 'pass' per LGTM

- src/Mod/Inspection/App/AppInspection.cpp
- src/Mod/Inspection/App/CMakeLists.txt
- src/Mod/Inspection/App/InspectionFeature.cpp
- src/Mod/Inspection/App/InspectionFeature.h
- src/Mod/Inspection/App/PreCompiled.h
- src/Mod/Inspection/Gui/AppInspectionGui.cpp
- src/Mod/Inspection/Gui/CMakeLists.txt
- src/Mod/Inspection/Gui/Command.cpp
- src/Mod/Inspection/Gui/PreCompiled.h
- src/Mod/Inspection/Gui/ViewProviderInspection.cpp
- src/Mod/Inspection/Gui/VisualInspection.cpp
- src/Mod/Inspection/Gui/VisualInspection.h
- src/Mod/Inspection/Gui/Workbench.cpp
- also sort our some includes to PreCompiled.h
> [Inspection] remove unused headers and Xerces

- src/Mod/Mesh/App/AppMesh.cpp
- src/Mod/Mesh/App/CMakeLists.txt
- src/Mod/Mesh/App/PreCompiled.h
- src/Mod/Mesh/Gui/CMakeLists.txt
- src/Mod/Mesh/Gui/PreCompiled.h
- src/Mod/MeshPart/App/AppMeshPart.cpp
- src/Mod/MeshPart/App/CMakeLists.txt
- src/Mod/MeshPart/App/PreCompiled.h
- src/Mod/MeshPart/Gui/AppMeshPartGui.cpp
- src/Mod/MeshPart/Gui/CMakeLists.txt
- src/Mod/MeshPart/Gui/CrossSections.cpp
- src/Mod/MeshPart/Gui/PreCompiled.h
> [Mesh] remove Python.h from headers

- src/Mod/Sketcher/App/AppSketcher.cpp
- src/Mod/Sketcher/App/CMakeLists.txt
- src/Mod/Sketcher/App/PreCompiled.h
- src/Mod/Sketcher/Gui/AppSketcherGui.cpp
- src/Mod/Sketcher/Gui/CMakeLists.txt
- src/Mod/Sketcher/Gui/PreCompiled.h
> [Sketch] remove Python.h from headers

- src/Mod/TechDraw/App/AppTechDraw.cpp
- src/Mod/TechDraw/App/AppTechDrawPy.cpp
- src/Mod/TechDraw/App/CMakeLists.txt
- src/Mod/TechDraw/App/PreCompiled.h
- src/Mod/TechDraw/App/TechDrawExport.cpp
- src/Mod/TechDraw/Gui/AppTechDrawGui.cpp
- src/Mod/TechDraw/Gui/AppTechDrawGuiPy.cpp
- src/Mod/TechDraw/Gui/CMakeLists.txt
- src/Mod/TechDraw/Gui/PreCompiled.h
> [TD] remove Python.h from headers

- src/Mod/Path/App/AppPath.cpp
- src/Mod/Path/App/AppPathPy.cpp
- src/Mod/Path/App/CMakeLists.txt
- src/Mod/Path/App/PreCompiled.h
- src/Mod/Path/Gui/AppPathGui.cpp
- src/Mod/Path/Gui/AppPathGuiPy.cpp
- src/Mod/Path/Gui/CMakeLists.txt
- src/Mod/Path/Gui/PreCompiled.h
- src/Mod/Path/Gui/ViewProviderPath.cpp
> [Path] remove Python.h and Xerces

- src/Mod/Path/InitGui.py
- src/Mod/Path/PathScripts/PathArray.py
- src/Mod/Path/PathScripts/PathGui.py
- src/Mod/Path/PathScripts/PathJobGui.py
- src/Mod/Path/PathScripts/PathOpGui.py
- src/Mod/Path/PathScripts/PathPocket.py
- src/Mod/Path/PathScripts/PathPost.py
- src/Mod/Path/PathScripts/PathPreferencesAdvanced.py
- src/Mod/Path/PathScripts/PathStock.py
- src/Mod/Path/PathScripts/PathSurface.py
- src/Mod/Path/PathScripts/PathUtils.py
- src/Mod/Path/PathScripts/post/philips_post.py
Fixes for two long standing issues & formatting.
> PATH: Bugfix/bag of minor isssues

- src/Mod/Draft/draftfunctions/svg.py
- src/Mod/Draft/draftobjects/shape2dview.py
- src/Mod/Draft/draftviewproviders/view_label.py
These are just a few small fixes or improvements to the draft code that I still had lying around from earlier. These are mostly based on reviewing the code, rather than from observed problems.
> Draft: Misc fixes
