- src/Mod/Path/PathScripts/PathPocketShape.py
Forum identification and discussion at [Pocket path generated only on face depth if object is reversed or origin moved](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=49513).
---
> [Path] PocketShape - fix improper path generation

- src/Mod/Path/PathScripts/PathProfileGui.py
`Cut Side` value was hard-coded to reset when Base Geometry was empty.  This disallowed retention of the current value with changes to selected Base Geometry involving the clearing thereof.
Also restored fixed visibility to `Cut Side` option in Task panel editor per forum mention.
Fixes #4433
Forum discussion at [Ticket #4433 - profile operation cut side reset](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=49459) …
> [Path] Fixes #4433 - `Cut Side` reset with certain Base Geometry changes

- src/Mod/Part/App/PrimitiveFeature.cpp
- src/Mod/Part/App/PrimitiveFeature.h
- src/Mod/Part/Gui/DlgPrimitives.cpp
- src/Mod/PartDesign/App/FeaturePrimitive.cpp
- src/Mod/PartDesign/App/FeaturePrimitive.h
- src/Mod/PartDesign/Gui/TaskPrimitiveParameters.cpp
the UI and the property is not consistent. In the dialog we use the term angle upon user feedback while the property still has the name "skew" in it.
I simply forgot this change in my PR that implemented skew prisms.
This is now corrected by this PR.
> [PD] fix wording for skew prisms

- src/Mod/Draft/drafttests/test_modification.py
The added functions are test_scale_part_feature_arcs, test_scale_part_feature_lines, test_scale_rectangle, test_scale_spline and test_scale_wire.
When comparing vectors and floats a tolerance of 1e-8 is used, but only for the midpoints of the arcs in test_scale_part_feature_arcs is this tolerance required. Scaling a part feature is not possible with the Draft_Scale command, but Draft.scale does support it.
> Draft: added 5 scale unit tests to test_modifications

- src/Mod/Arch/ArchWall.py
- src/Mod/Arch/TestArch.py
A multi-segment wall did not support left/right alignment as well as a multi-material.
ArchWall.py has been edited.
A new unit test has been added to TestArch.py: testWallMultiMatAlign. I have kept the existing testWall test. I have changed the code in TestArch.py to 'import FreeCAD as App'.
> Arch: ArchWall fix multi-material align bug + new unit test

- src/Mod/PartDesign/Gui/TaskLoftParameters.cpp
- src/Mod/PartDesign/Gui/TaskLoftParameters.h
- src/Mod/PartDesign/Gui/TaskLoftParameters.ui
- src/Mod/PartDesign/Gui/TaskMirroredParameters.ui
- allow to sort loft sections by dragging: https://forum.freecadweb.org/viewtopic.php?f=19&t=50222
- fix bug of uninitialized options: https://forum.freecadweb.org/viewtopic.php?f=19&t=50221
- use better code for the context menu of the listWidget (the same we use in other placed of PD)
> [PD] make loft sections sortable

- src/Gui/propertyeditor/PropertyEditor.cpp
Only auto recompute if closing the transaction that is opened by the property editor.
> Gui: fix property editor transaction closing

- src/Mod/Part/App/BSplineSurfacePy.xml
- src/Mod/Part/App/BSplineSurfacePyImp.cpp
- src/Mod/Part/App/BezierSurfacePy.xml
- src/Mod/Part/App/BezierSurfacePyImp.cpp
- src/Mod/Part/App/ConePy.xml
- src/Mod/Part/App/ConePyImp.cpp
- src/Mod/Part/App/CylinderPy.xml
- src/Mod/Part/App/CylinderPyImp.cpp
- src/Mod/Part/App/GeometrySurfacePyImp.cpp
- src/Mod/Part/App/PlanePy.xml
- src/Mod/Part/App/PlanePyImp.cpp
- src/Mod/Part/App/RectangularTrimmedSurfacePy.xml
- src/Mod/Part/App/RectangularTrimmedSurfacePyImp.cpp
- src/Mod/Part/App/SpherePy.xml
- src/Mod/Part/App/SpherePyImp.cpp
- src/Mod/Part/App/ToroidPy.xml
- src/Mod/Part/App/ToroidPyImp.cpp
Following PR #3845, remove other overridden uIso() and vIso() methods.
I treated [RectangularTrimmedSurface](https://github.com/FreeCAD/FreeCAD/pull/3845#issuecomment-689447967) in a separate commit, to allow a revert, but IMHO, after code inspection, I think it is safe to include it too.
---
> Part: use uIso() and vIso() methods from base Surface object

- src/Mod/Draft/draftfunctions/dxf.py
- src/Mod/Draft/draftfunctions/svg.py
Following #3749 and #3851, this pull request further organizes the SVG code.
Code inside the `get_text` and `get_path` functions are externalized to smaller functions, `_get_text_techdraw`, `_get_text_header`, `_get_path_circ_ellipse`, `_get_path_bspline`. This makes it easier to read the code, detect errors, and provide additional modifications. In the future, some of these functions can be placed in submodules.
---
> Draft: update svg module, split code into more subfunctions

- src/Mod/Draft/draftguitools/gui_arrays.py
The previous request #3815 contains a conflict that produces a Python syntax error (wrong indentation and non-matching parenthesis), which makes the Draft Workbench fail when loading the Draft Array commands and the rest of the commands. This request fixes the issue.
Forum thread: [freecad-daily PPA - startup failure - indent in gui_arrays.py](https://forum.freecadweb.org/viewtopic.php?f=3&t=50420)
---
> Draft: fix loading of arrays and workbench tools

- src/Gui/Quarter/QuarterWidget.cpp
This allows compilation with the latest Coin3D library revision. While the latest version of Coin3D hasn't been released yet, it supports Wayland. As such, with this change, compiling FreeCAD with the latest Coin3D enables functional Wayland support.
> Include Inventor/SbByteBuffer.h in QuarterWidget.cpp.

- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.h
- src/Mod/PartDesign/Gui/TaskHoleParameters.ui
- 1. reported here: https://forum.freecadweb.org/viewtopic.php?p=432936#p432851
also unthreaded holes can have a close or standard fit
- 2. reported here: https://forum.freecadweb.org/viewtopic.php?p=432936#p432944
the thread direction is always left. The reason is that this property is an enum but the dialog returns a bool.
- also fix an UI issue with the spin boxes (automatically found and repaired by Qt's designer, thus the many changes in the UI file)
- also remove a superfluous spacer from the UI file
> [PD] fix 2 hole dialog bugs

- src/Mod/Part/BasicShapes/Shapes.py
- src/Mod/Part/Gui/Workbench.cpp
This follows the style of the other Part commands which don't have the word `Make` just the name of the noun, `Box`, `Cylinder`,
`Sphere`, etc.
---
> Part: change command name Part_MakeTube to Part_Tube

- build_unix_dev_conda.sh
build_unix_dev_conda.sh fails to activate the freecad_dev
environment. This is issue #7980 on the conda github. This has
one of the suggested work arounds added.
---
> Conda doesn't export functions to subshells

- src/Mod/Draft/draftutils/utils.py
**Bug detail:** When we have clone object that is clone of clone another object, then in export IFC file object are displaced because `Draft.get_clone_base` not return correct base object.
```python
>>> Draft.get_clone_base(App.ActiveDocument.Clone).Label
'Base'
>>> Draft.get_clone_base(App.ActiveDocument.Clone001).Label
'CloneOfBase'  # Should also return `Base`
>>> Draft.get_clone_base(App.ActiveDocument.Clone).Label
'Base'
>>> Draft.get_clone_base(App.ActiveDocument.Clone001).Label
'Base'
```
[bug.zip](https://github.com/FreeCAD/FreeCAD/files/5262407/bug.zip)
> Fixed bug: In `Draft.get_clone_base` function.

- src/Mod/Draft/Draft.py
- src/Mod/Draft/draftutils/gui_utils.py
- src/Mod/Draft/importSVG.py
Normally the bounding box is taken from `Shape.BoundBox`. Certain objects don't have a `Shape`, like `App::FeaturePython` such as Draft Dimension and Draft Text, so the bounding box is calculated from the corresponding viewprovider, that is, from `ViewObject.RootNode`. This new function, `Draft.get_bbox`, only works in GUI mode.
In `importSVG.export` the bounding box of each exported object is used to determine the size of the SVG page. Using `get_bbox`, now Draft Dimensions and Draft Text are also included in this calculation.
---
> Draft: method to get the bounding box of objects that don't have a Shape

- src/Gui/Stylesheets/Behave-dark.qss
- src/Gui/Stylesheets/CMakeLists.txt
Modified stylesheet based on one of the "darker" stylesheets to fit the Behave color theme
---
See the [dev repo here](https://github.com/Chrismettal/FreeCAD-Behave-dark) and maybe the [forum post here](https://forum.freecadweb.org/viewtopic.php?f=34&t=50379).
Adds a new dark stylesheet fitting the behave theme that you can already get for multiple text editors, KiCAD etc.
> [Stylesheet] Add new "behave" dark stylesheet

- src/Mod/Path/PathScripts/PathProfile.py
This PR fixes a rotational usage error discovered while troubleshooting recent Pocket_Shape errrors.  It also removed the FinalDepth limitation imposed that is requested to be removed in the forum at [Profiling below depth of face](https://forum.freecadweb.org/viewtopic.php?f=15&t=50341)
I added a comment and a couple debug items.
---
> Path: Profile - Fix rotation error and remove FinalDepth limit

- src/Gui/DlgSettings3DView.ui
- src/Gui/DlgSettings3DViewImp.cpp
- src/Gui/DlgSettingsViewColor.cpp
- src/Gui/DlgSettingsViewColor.ui
Screencast showing where Pick Radius is located in the m Preferences https://i.imgur.com/N7MFELX.mp4
This is not a 'Color' issue. It's a mouse-related issue.
Case arguing for change:
https://forum.freecadweb.org/viewtopic.php?f=8&t=39650&p=336939#p336932
https://forum.freecadweb.org/viewtopic.php?f=3&t=39161
Forum thread to poll the community for the desired location => https://forum.freecadweb.org/viewtopic.php?f=8&t=39655
> @arijeetbaruah moved 'Pick Radius' from 'Color' to '3D View' fixes #0004147

- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathPost.py
- src/Mod/Path/PathScripts/PathSanity.py
- src/Mod/Path/PathScripts/PathStock.py
The setup report is an overhaul of the experimental feature Path-Sanity.  Path-Sanity has been broken for some time now and largely unused.  
The new path-sanity works differently.  It requires a job to be selected.  It then parses through the job, operations, stock, tools, and related objects building up details about them.  It then writes the details in a .asciidoc format to the disk.  If asciidoctor is installed, it will generate a local .html file with the results and open it in a browser.  The report is intended to document all assumptions made by the CAM programmer so the operator of the machine can set up the machine correctly.
This is still an experimental feature and feedback is requested.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please …
> Path Feature:  Setup Report

- src/Mod/Arch/ArchRoof.py
- src/Mod/Arch/TestArch.py
1. Removed unnecessary use of FreeCAD.Vector. Renamed some functions and variables for clarity (in this description the new names are used). Reformatted the code. Moved imports to the top of the file. Updated the tooltips. Tweaked the title text "Parameters ...".
2. Fixed the length of list properties bug.
3. Flip direction did not work properly. The adopted solution is to reverse the edges the roof is based on.
4. Added support for consecutive parallel edges.
5. Added support for zero angle roof segments.
6. The code now handles zero length runs without throwing an error.
7. To handle triangular roofs with a zero length eave, "eave" (egde) has been turned into "eavePtLst" (list of points).
8. The ridges of opposite parallel roof segments (if they do not use a relative profile) are …
> Arch: ArchRoof bug fix and update

- src/Mod/Arch/ArchSectionPlane.py
- src/Mod/Draft/draftobjects/draft_annotation.py
By looking at this recent commit 69fa329223, I realized the older `'DraftText'` objects are not handled by the Arch SectionPlane.
After the reorganization of the Draft Workbench, the `'DraftText'` objects are now of Proxy.Type `'Text'`. In the `DraftAnnotation` class the `__setstate__` method was defined to automatically migrate the Type.
The `Arch SectionPlane` only handles `'Text'` objects. If for some reason there is still an old `'DraftText'` object which has not been migrated to the new Type, it won't be found. This is corrected by adding `'DraftText'` to the list of objects to process.
---
> Arch: consider DraftText objects in the section plane for compatibility

- src/Mod/Draft/draftfunctions/dxf.py
The name of the argument in the old function doesn't match the new function which would cause an error. However, it's hard to trigger this problem because this code is essentially not used any more.
Found by LGTM: [Draft WB LGTM Analysis](https://forum.freecadweb.org/viewtopic.php?f=23&t=50946)
---
> Draft: fix mismatch of arguments in get_dxf function

- src/Mod/Show/Containers.py
The class `NotAContainerError` is used as an exception. Where it is used it is initialized with an argument, but the definition didn't accept one; now we accept an argument in the constructor.
Reported by LGTM: [Mod/Show/Containers.py LGTM alert](https://forum.freecadweb.org/viewtopic.php?f=8&t=50961)
---
---
> Show: add argument to NotAContainerError class constructor

- src/Mod/Path/App/VoronoiCellPyImp.cpp
- src/Mod/Path/App/VoronoiEdgePyImp.cpp
- src/Mod/Path/App/VoronoiVertexPyImp.cpp
> PATH: 32bit build bugfix - Using python type conversion to return voronoi element color

- src/Mod/PartDesign/Gui/TaskLinearPatternParameters.cpp
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.cpp
…elected to remove in linear and polar pattern dialog
same change proposed in PR #3919  applied to LinearPattern and PolarPatern.
- [*] Branch rebased on latest master `git pull --rebase upstream master`
---
> [PartDesign] Prevent crash when pressing delete key without feature selected to remove in linear and polar pattern dialog

- src/App/Application.cpp
---
The "Random color" command was producing the same sequence of colors every startup, so the first object i colored in a new file would always be barf green, then light brown, then another green. This happened because `srand()` was never called before the `rand()` calls in the random color command.
As `rand()` is used in more places we should seed the randomizer on application startup.
> Fix "Random color" not random - Seed randomizer on application init

- src/Mod/Part/AttachmentEditor/Commands.py
- src/Mod/Part/AttachmentEditor/FrozenClass.py
- src/Mod/Part/AttachmentEditor/TaskAttachmentEditor.py
- src/Mod/Part/BOPTools/GeneralFuseResult.py
- src/Mod/Part/BOPTools/JoinAPI.py
- src/Mod/Part/BOPTools/JoinFeatures.py
- src/Mod/Part/BOPTools/SplitFeatures.py
- src/Mod/Part/CompoundTools/CompoundFilter.py
- src/Mod/Part/CompoundTools/Explode.py
- src/Mod/Part/CompoundTools/_CommandCompoundFilter.py
- src/Mod/Part/CompoundTools/_CommandExplodeCompound.py
- src/Mod/Part/Gui/Resources/icons/booleans/Part_CompoundFilter.svg
- src/Mod/Part/InitGui.py
Several edits to the Python modules.
* Add empty line to the end of Python files.
* Clean up `InitGui.py`.
* Clean up spacing for the compound tools, `CompoundFilter`, `ExplodedCompound`, boolean tools `BooleanFragments`, `Slice to compound`, `Slice apart`, `Boolean XOR`, and join tools `JoinConnect`, `JoinEmbed`, `JoinCutout`.
* Update icon `Part_CompoundFilter.svg` to follow better our Artwork guidelines, line thickness, highlights.
* Many long lines (150 characters) are broken into smaller 80 to 100 character lines.
* Revise and clean up the docstrings of the commands, functions, and property tooltips.
* For the `CompoundFilter` object various checks are added in case the object doesn't have the correct values for the properties (`Stencil` and `items`) for a given filter …
> Part: clean up Python files of the workbench

- src/Mod/Part/Gui/Command.cpp
- src/Mod/Part/Gui/TaskDimension.cpp
Improve the tooltips of `Part_Measure_Linear`, `Part_Measure_Angular`, `Part_Measure_Refresh`, `Part_Measure_Clear_All`, `Part_Measure_Toggle_All`, `Part_Measure_Toggle_3D`, `Part_Measure_Toggle_Delta`.
See also, [Move or remove "View_Measure_Toggle_All" and "View_Measure_Clear_All"](https://forum.freecadweb.org/viewtopic.php?f=10&t=51075).
Also update the text of the buttons in the `TaskDimension` task panel.
Remove tabs in the source code, as there was a mix of tabs and spaces. Further cleaning is necessary as the indentation is inconsistent and mostly 2 spaces instead of 4 spaces.
---
> Part: improve tooltip of measure commands

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
* Change the formula to calculate maximum distance for merging of constraint icons.
* Ignore z coordinate while calculating the distance between icons. It is irrelevant but can slightly differ between icons.
* Choose first icon from the group of nearby icons as a location of the composite icon, instead of choosing icon closest to the average position. Fixes jittering of the icon while one of the constraints is moved. See [forum thread](https://forum.freecadweb.org/viewtopic.php?f=17&t=51165) for more detailed description.
> [Sketcher] Changes to drawing of constraint icons.

- src/Mod/Path/PathScripts/PathUtils.py
function is unused at this time.  It should be used by preprocessor scripts like gcode_pre to
convert radius mode arcs to IJ mode.
---
> [PATH] Add RtoIJ function to PathUtils.  fixes #2606

- src/Mod/Draft/DraftGeomUtils.py
- src/Mod/Draft/draftgeoutils/edges.py
- src/Mod/Draft/draftgeoutils/geometry.py
- src/Mod/Draft/draftgeoutils/offsets.py
- src/Mod/Draft/draftgeoutils/wires.py
- src/Mod/Draft/draftguitools/gui_draft2sketch.py
- src/Mod/Draft/draftmake/make_sketch.py
- src/Mod/Draft/draftobjects/patharray.py
Motivated by https://tracker.freecadweb.org/view.php?id=4416
Now the draft2sketch operation works more correctly on custom planes other than XY.
The previous implementation had the following drawbacks:
Fails to check coplanarity.
Fails with three collinear points wires and doesn't convert isolated points.
Sometimes, shapes in unexpected location, as reflected or rotated.
Mixed conversion between planes.
Only first piece is converted for bezier curves.
Splines and bezier curves are projected to xy plane instead of being converted.
The previous functions isLine and getSplineNormal may fail in symetrics splines or straight splines with multiple control points.
In fact, the bug reported is related to the latter.
Also geometrical functions are modified to use the Part.Shape.findPlane method …
> Draft: Improve make_sketch and geometric related functions

- src/Mod/MeshPart/Gui/Command.cpp
- src/Mod/MeshPart/Gui/Resources/MeshPart.qrc
- src/Mod/MeshPart/Gui/Resources/icons/MeshPart_CurveOnMesh.svg
- src/Mod/MeshPart/Gui/TaskCurveOnMesh.ui
- src/Mod/Surface/Gui/Command.cpp
- src/Mod/Surface/Gui/TaskFilling.ui
This continues #3927 with improving the tools of the Surface Workbench.
* The long tooltip for `CurveOnMesh` is moved to the task panel.
* The "curvature" word is removed.
* A new icon is provided for `CurveOnMesh` for the MeshPart Workbench. It is the same as the one for the Surface Workbench but on a green tone.
---
> Surface: update on tools, taskpanels, and icons

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- initialization: if a threaded, the fit must not be enabled
- when changing the profile type setReadOnly for the fit and class according to if threaded or not
- when changing if threaded or not, setReadOnly accordingly for the fit and class
> [PD] fix hole thread UI bugs

- src/Mod/AddonManager/addonmanager_macro.py
I believe this code is currently incorrect, as it makes references to code outside the "if code" block, where it can not be ensured that code is a string. Moving the code processing into this block avoids this issue.
I experienced a stuck Addon Manager, which was caused by an exception
```
File "/usr/share/freecad/Mod/AddonManager/addonmanager_macro.py", line ..., in fill_details_from_wiki
FreeCAD.Console.PrintWarning(translate("AddonsInstaller", "Unable to clean macro code: ") + code + '\n')
TypeError: can only concatenate str (not "list") to str
```
which is fixed by these changes.
OS: Ubuntu 20.04.1 LTS
Word size of OS: 64-bit
Version: 0.18.4.
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.3.0
Locale: …
> Fix macro code processing

- src/Gui/CommandDoc.cpp
- src/Gui/Icons/Std_Alignment.svg
- src/Gui/Icons/Std_DuplicateSelection.svg
- src/Gui/Icons/resource.qrc
Two Std commands do not have icons for the FreeCAD UI (Menu Edit): Std DuplicateSelection, Std_Alignment.
This commit adds SVG files with icons for these commands. Also, it makes the necessary changes on CommandDoc.cpp and resource.qrc files.
The discussion with the proposal for SVG icons can be found in the UX/UI Design FreeCAD Forum:
Icon for Std Alignment
https://forum.freecadweb.org/viewtopic.php?f=34&t=50688
Icon for Std DuplicateSelection
https://forum.freecadweb.org/viewtopic.php?f=34&t=50791
> Add SVG icons for two Std commands

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.ui
- initialization: thread direction only sensible if there is a thread
- initialization: hole diameter can only be changed if there is no profile
- initialization: only enable allowed hole cut parameters
- also for the ISO profiles it is allowed to countersink/bore deeper/less deep
- UI file: add some tooltips (the other changes were done automatically by Qt's designer)
> [PD] more hole fixes

- src/Mod/Part/Gui/Resources/icons/tools/Part_Thickness.svg
This is the same icon as `PartDesign_Thickness` but without the red highlights in order to match the rest of the Part icons.
---
---
> Part: update the Part_Thickness icon

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
The reason for this behaviour is that root point (origin) and axes are not treated as fixed geometry. Every external geometry has negative ID which is at most GeoEnum::RefExt defined as -3 in the file src/Mod/Sketcher/App/SketchObject.cpp. Ids of root point and axes are also defined in this file with id -1 for root point and horizontal axis, and -2 for vertical axis. To fix the problem, GeoEnum::RefExt id was replaced by root point id in the condition checking for the largest id of fixed geometry.
[Ticket](https://tracker.freecadweb.org/view.php?id=4399)
[Forum thread](https://forum.freecadweb.org/viewtopic.php?f=19&t=48344)
> Sketcher: Fix ticket #4399

- src/Mod/Path/App/Voronoi.h
- src/Mod/Path/App/VoronoiCellPy.xml
- src/Mod/Path/App/VoronoiCellPyImp.cpp
- src/Mod/Path/App/VoronoiEdgePy.xml
- src/Mod/Path/App/VoronoiEdgePyImp.cpp
- src/Mod/Path/App/VoronoiPyImp.cpp
- src/Mod/Path/App/VoronoiVertexPy.xml
- src/Mod/Path/App/VoronoiVertexPyImp.cpp
- src/Mod/Path/CMakeLists.txt
- src/Mod/Path/PathScripts/PathVcarve.py
- src/Mod/Path/PathTests/TestPathVoronoi.py
- src/Mod/Path/TestPathApp.py
Voronoi changes:
* Changed `toGeom` api to `toPoint` for vertices and to `toShape` for edges in order to easier deal with segmenting an edge (although it was not required in the end).
* Added a second optional z-value to the `toShape(z0, z1)` call so that the voronoi implementation can return the correct edge with an in/decline.
Vcarve changes:
* Voronoi point based wire detection, easier to determine connected edges than using geometries or shapes.
* Added sorting algorithm for wires to connect an end point with the closest wire starting point
* Allow flipping a voronoi wire if its end point is closest to the end point of the previous wire.
> Path: Feature/path voronoi vcarve refactor

- src/Mod/Draft/draftguitools/gui_dimensions.py
Linked geometry was not handled if the selected edge started or ended at vertex zero.
> Draft: Draft_Dimension_linked_geometry_fix

- src/Mod/Path/PathScripts/PathOp.py
- src/Mod/Path/PathScripts/PathSelection.py
> [Path] Add selection gate and set default turning diameter

- src/App/PropertyStandard.cpp
- src/App/PropertyStandard.h
- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/App/FeatureHole.h
- src/Mod/PartDesign/App/json.hpp
- src/Mod/PartDesign/App/json_fwd.hpp
- src/Mod/PartDesign/CMakeLists.txt
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- src/Mod/PartDesign/Resources/Hole/din7984.json
- src/Mod/PartDesign/Resources/Hole/iso10642.json
- src/Mod/PartDesign/Resources/Hole/iso14583.json
- src/Mod/PartDesign/Resources/Hole/iso14583part.json
- src/Mod/PartDesign/Resources/Hole/iso4762.json
- src/Mod/PartDesign/Resources/Hole/iso4762_7089.json
- Make countersink and counterbore on metric holes freely definable by user.
- Fixed the Naming of M1.6, M2, M2.5 and M3.5
- Added constructor for custom enums from Enums to PropertyEnumeration
- Put definitions of cut-types (counterbore/countersink) for screwtypes into json-files for easy modification.
- Allow users to put its own definitions in json-files in [UserDir]/Mod/PartDesign/Resources/Hole
- Contains several examples of cut-type definition json-files that are propably not production-ready.
This uses a local copy of nlohmann::json¹ to read json-files.
Includes pullrequest #3990
Forum-Threads: 
- https://forum.freecadweb.org/viewtopic.php?t=51491
- https://forum.freecadweb.org/viewtopic.php?t=51403
- https://forum.freecadweb.org/viewtopic.php?t=50978
__________
¹ This is a very …
> [PartDesign] Dynamic hole cut-types

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/CommandConstraints.h
- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
- src/Mod/Sketcher/Gui/TaskSketcherConstrains.cpp
Fixes #4478: Active constraint tool blocks sidebar tasks from working.
Many Sketcher commands are interrupted by the existence of a handler. Rather than having these commands silently cancel, purge the handler if a command executes that does not need it. Forums discussion [here](https://forum.freecadweb.org/viewtopic.php?f=10&t=51833).
This fix is in three parts: first, `isSketcherAcceleratorActive()` is modified to allow `Mode==STATUS_SKETCH_UseHandler` in addition to `Mode==STATUS_NONE`.
Second, each Sketcher command that depends on isSketcherAcceleratorActive() to determine its availability, but that does not ever use `ActivateAcceleratorHandler()` is modified to call a new `ReleaseHandler()` function prior to that command's execution. This new function determines whether there is an …
> [Sketcher] Fix #4478 - Release handler in commands where not needed

- src/Mod/Part/Gui/DlgPrimitives.cpp
I added this comment when I read the dialog state fro the index of the type combobox, now we read the primitive's TypeID so the comment is misleading
> [part] remove a now misleading comment

- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
- src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
- src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_BSplinePoleWeight.svg
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
When working with weights, it is a huge improvement to see the weights immediately when changing the pole circle radius.
This PR adds an option to display the weights.
Here is how it works:
Since the endpoints can have a displayed multiplicity, I placed the weight info behind it, but maybe one should then better display it right below the multiplicity.
> [Sketch] add option to display spline weights

- src/Mod/Draft/draftguitools/gui_offset.py
The offset operation for polylines and b-splines in planes other than XY usually produces erroneous results. This is solved by specifying the normal of the WorkingPlane.
The distance input field in the offset dialog for bsplines is fixed. (Previously it didn't work).
- [*] Branch rebased on latest master `git pull --rebase upstream master`
---
> Draft: Fixes in gui_offset

- src/Mod/Draft/draftguitools/gui_trackers.py
Currently, the visual aid dimension only works correctly in the XY plane.
With these changes, dim lines and labels are projected on the working plane in use and the distances are calculated correctly.
---
> Draft: Improve archDimTracker class

- src/Mod/AddonManager/addonmanager_workers.py
see forum disscussion:
https://forum.freecadweb.org/viewtopic.php?f=8&t=52007
It worked for some AddOns, but I do not know if this will result in a regression in other AddOns.
> AddOn manager, use default branch instead of master branch

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/App/FeatureHole.h
Allow cut-profiles with identical names for different threads.
see:
https://forum.freecadweb.org/viewtopic.php?f=19&t=51491&start=60#p446854
https://forum.freecadweb.org/viewtopic.php?f=19&t=51491&start=60#p446902
---
> [PD] cut-profiles with identical names for different threads

- src/Mod/Path/PathScripts/PathSurface.py
- src/Mod/Path/PathScripts/PathSurfaceSupport.py
- src/Mod/Path/PathScripts/PathWaterline.py
Issue reported in forum at, [Re: Separate 3D Surface and Waterline (new feature) [Merged]](https://forum.freecadweb.org/viewtopic.php?f=15&t=44473&p=441615#p412303)
---
> Path: 3D Surface fix to apply `CutMode` when `CutPattern = Offset`; and LGTM cleanup

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.ui
- fix bug that custom angles were overwritten
- the norms only define screw heads, not the cut for them, so also a custom angle is possible to sink a metric screw
- use better step in UI since one changes the presets only in fractions of a millimeter (otherwise it would be a different hole size)
- handle case of no cut
- calculate change in diameter when adding depth to countersinks
Forum: https://forum.freecadweb.org/viewtopic.php?f=19&t=51491&p=447712#p447712
> [PD] Hole countersink angle work

- src/Gui/DocumentObserverPython.h
Since months I got this:
`>D:\FreeCADGit\src\Gui\DocumentObserverPython.h(80,20): warning C5208: unnamed class used in typedef name cannot declare members other than non-static data members, member enumerations, or member classes`
The reason is that since C++17 nameless typedefs are restricted, see for example here:
https://en.cppreference.com/w/cpp/language/typedef
, therefore the warning.
By naming it, the warning vanishes.
> [Gui] get rid of MSCV compiler warning

- src/Mod/Part/Gui/DlgPrimitives.cpp
- src/Mod/Part/Gui/DlgPrimitives.ui
- there is no reason to hide it and even a bit tiring to open it manually since most no new primitives should be at the origin
- give the combobox to select the primitive type a reasonable name, this helps to understand the code better
> [Part] show location dialog when creating a Primitive

- src/Mod/Arch/ArchRoof.py
In ArchRoof.py the processSubShapes function was called without providing the placement argument.
> Arch: Fix for ArchRoof. When processing a roof's subshapes the placement of the roof was ignored.

- src/Mod/Path/PathScripts/PathAreaOp.py
- src/Mod/Path/PathScripts/PathPocketShape.py
It seems a group of recent FinalDepth and rotational issues were sharing a common set of code errors.  This PR attempts to address them collectively.  I have tested models submitted in the following forum threads pertaining to Pocket_Shape and this PR correctly pockets each model presented with an error.
- [pocket path below selected plane.](https://forum.freecadweb.org/viewtopic.php?f=15&t=50493)
- [1.5mm stepdown issue](https://forum.freecadweb.org/viewtopic.php?f=15&t=50453)
- [Pocket path generated only on face depth if object is reversed or origin moved](https://forum.freecadweb.org/viewtopic.php?f=15&t=49513)
- [[RESOLVED] Path Pocket generating wrong code](https://forum.freecadweb.org/viewtopic.php?f=15&t=50263)
- [Ticket #4411 - Can only generate pocket once for this shape, then …
> Path: Pocket_Shape - Improved fixes for FinalDepth and rotational issues

- src/Gui/CommandDoc.cpp
- src/Gui/CommandStd.cpp
- src/Gui/CommandView.cpp
- src/Gui/Icons/Std_DemoMode.svg
- src/Gui/Icons/Std_DependencyGraph.svg
- src/Gui/Icons/Std_DlgParameter.svg
- src/Gui/Icons/Std_ProjectUtil.svg
- src/Gui/Icons/Std_SceneInspector.svg
- src/Gui/Icons/resource.qrc
Five Std Tool commands do not have icons for the FreeCAD UI (Menu Tools): Std SceneInspector, Std DependencyGraph, Std ProjectUtil, Std DemoMode, Std DlgParameter
This commit adds SVG files with icons for these commands. Also, it makes the necessary changes on CommandStd.cpp, CommandDoc.cpp, CommandView.cpp and resource.qrc files. 
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=51502
> Add SVG icons for five Std Tool commands

- src/App/ObjectIdentifier.cpp
Reported from realthunder/FreeCAD_Assembly3#328
`ObjectIdentifier::relativeTo()` uses the wrong base owner object, causing the expression to display as local property reference. The expression can still evaluate to the correct result, but error will occur when the document is saved, restored, and the object is recomputed.
> App: fix ObjectIdentifier::relativeTo()

- src/Mod/Path/PathScripts/PathSlot.py
This PR addresses a bug with the Slot operation regarding arc paths.  The error is reported in the forum at [wrong gcode for sketched arc](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=52424).
This PR also addresses a bug with the existing internal debugging code and simplifies the debugging code a little.
---
> Path: Fix arc slotting direction in Slot operation

- src/Mod/Draft/DraftGeomUtils.py
- src/Mod/Draft/draftfunctions/upgrade.py
- src/Mod/Draft/draftgeoutils/faces.py
Related to [0004460: Draft Upgrade - Incorrect result](https://tracker.freecadweb.org/view.php?id=4460)
The reported bug is due a error in isCoplanar function, which is now fixed. For a more detailed explanation, see https://forum.freecadweb.org/viewtopic.php?f=23&t=51200&p=440821#p440821
The expected functionality in the report is out of the scope of current implementations of joinFaces and concatenate functions, which only work on flat shapes.
The bug [0004462: Upgrade from shell to solid failed - UnboundLocalError](https://tracker.freecadweb.org/view.php?id=4462) is fixed.
The bug [0004080: Draft upgrade make face fails with a sketch contatining multiple closed loops](https://tracker.freecadweb.org/view.php?id=4080) is fixed.
Now, joinFaces can deal with faces which generates internal …
> Draft: Some fixes in upgrade function

- src/Gui/Thumbnail.cpp
This changes the size of the FreeCAD icon that is overlayed on the thumbnails. This smaller size is less intrusive but still can be recognized, and makes the thumbnail preview more generally useful.
> Reduce appicon size when generating thumbnail

- src/Mod/Start/StartPage/StartPage.py
> Start: encode basename to avoid crashes on non-ascii file names 

- src/Mod/TechDraw/App/AppTechDrawPy.cpp
- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/App/DrawViewDimension.h
- src/Mod/TechDraw/App/DrawViewDimensionPyImp.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
This pull request fixes dimension tolerance label construction problems by combining the code with the construction of main dimension label construction code.  It contains three commits.  (1) Refactor dimension label string construction into generic value processing part and specific dimension-value processing part.  (2) Make tolerance label construction to use the same generic value processing part.  This solves problems with different unit schemas and different decimal separators, as these problems were already solved for main dimension value, but not for the tolerance values.  (3) Finally, add the same user-editable per-dimension formatting strings (e.g. "%.2g") for tolerance values that previously existed only for the main value.
This should fix several issues raised on the FC …
> [TD] Dimension tolerance label string fixes, uses the same mechanism as main dimension value 

- src/Mod/Path/PathScripts/PathCircularHoleBase.py
- src/Mod/Path/PathScripts/PathDrilling.py
This PR addresses numerous problems that existed in the rotational use of the Drilling Op.  The issues were brought to light in the forum, [4th axis tool orientation not right in G-Code](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=52262).
There are many changes to the rotational-related code in this PR, but they are necessary to make the existing rotational feature more usable in 0.19 since the feature is available.  A large portion of the changes pertain to simplifying the rotational integration code to align it more with the integration found in the PocketShape module.
Some of the changes are simply to synchronize (update) existing rotational methods with identical methods that initiated in the PathAreaOp module.  Eventually (in the next release after 0.19), this set of …
> Path: Fix Drilling Op issues when using rotation feature

- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/LineGroup.cpp
- src/Mod/TechDraw/App/LineGroup.h
- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/App/Preferences.h
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.h
- src/Mod/TechDraw/Gui/TaskCenterLine.cpp
- src/Mod/TechDraw/Gui/TaskLeaderLine.cpp
- src/Mod/TechDraw/Gui/TaskRichAnno.cpp
- src/Mod/TechDraw/Gui/ViewProviderBalloon.cpp
- src/Mod/TechDraw/Gui/ViewProviderDimension.cpp
- src/Mod/TechDraw/Gui/ViewProviderGeomHatch.cpp
- src/Mod/TechDraw/Gui/ViewProviderLeader.cpp
- src/Mod/TechDraw/Gui/ViewProviderRichAnno.cpp
- src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
At the moment one has to specify the LineGroup as string. But one doesn't know what groups exist. So one has to check the Wiki, learn there where the groups are defined and then open the definition file with a text editor.
This PR simplifies this by reading the existing groups out of the definition file and fill the combobox accordingly.
It also give the user info what the selected LineGroup defines via the tooltip.
A nice side effect is that no typos can occur since you don't have to enter the LineGroup name as text.
Here is how the dialog looks now:
> [TD] make LineGroup selectable

- src/Mod/Path/PathScripts/PathMillFace.py
Fix for rounding issue exposed in forum thread, [Face Milling Bug? ... Facing Rabbets](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=52729).  This fix increases the vertical removal shape envelope buffer by 0.1 mm and then translates that envelope down by the same value.
Also instates usage of `obj.removalshape` for debugging purposes.
---
> Path: Millface fix - Address rounding issue

- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp
in other/existing elements of line width we speak of "width", so do the same for line groups
> [TD] uniform wording

- src/App/FeaturePythonPyImp.h
Clang warnings are already disabled.
This PR suppresses warnings like the following:
```
[ 52%] Building CXX object src/Mod/Part/App/CMakeFiles/Part.dir/PrimitiveFeature.cpp.o
[ 52%] Building CXX object src/Gui/CMakeFiles/FreeCADGui.dir/TransactionObject.cpp.o
In file included from /home/shiftee/FreeCAD/src/Mod/Part/App/PrimitiveFeature.cpp:66:
/home/shiftee/FreeCAD/src/App/FeaturePythonPyImp.h:57:5: warning: missing initializer for member ‘_typeobject::tp_print’ [-Wmissing-field-initializers]
57 |     }; \
|     ^
/home/shiftee/FreeCAD/src/Mod/Part/App/PrimitiveFeature.cpp:117:5: note: in expansion of macro ‘PYTHON_TYPE_IMP’
117 |     PYTHON_TYPE_IMP(PrimitivePy, PartFeaturePy)
|     ^~~~~~~~~~~~~~~
[ 52%] Building CXX object src/Mod/Part/App/CMakeFiles/Part.dir/FeatureGeometrySet.cpp.o …
```
> Suppress gcc warnings also in FeaturePythonPyImp.h

- src/Gui/CommandDoc.cpp
- src/Gui/CommandStd.cpp
- src/Gui/CommandWindow.cpp
- src/Gui/Icons/Std_CloseActiveWindow.svg
- src/Gui/Icons/Std_CloseAllWindows.svg
- src/Gui/Icons/Std_Export.svg
- src/Gui/Icons/Std_Import.svg
- src/Gui/Icons/Std_MergeProjects.svg
- src/Gui/Icons/Std_PrintPdf.svg
- src/Gui/Icons/Std_RecentFiles.svg
- src/Gui/Icons/Std_Revert.svg
- src/Gui/Icons/Std_SaveAll.svg
- src/Gui/Icons/Std_SaveCopy.svg
- src/Gui/Icons/resource.qrc
Ten Std File Menu commands do not have icons for the FreeCAD UI (Menu Tools): Std_CloseActiveWindow, Std_CloseAllWindows, Std_Export, Std_Import, Std_MergeProjects, Std_PrintPdf, Std_RecentFiles,Std_Revert, Std_SaveAll, Std_SaveCopy
This commit adds SVG files with icons for these commands. Also, it makes the necessary changes on CommandDoc.cpp, CommandWindow.cpp, CommandStd.cpp and resource.qrc files.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=52624
> Add SVG icons for ten Std File Menu Commands

- src/Gui/DlgMacroExecuteImp.cpp
- src/Gui/DlgParameterImp.cpp
- src/Gui/DlgToolbarsImp.cpp
- src/Gui/DlgUnitsCalculator.ui
- src/Gui/MainWindow.cpp
- src/Gui/TextDocumentEditorView.cpp
- src/Mod/Mesh/Gui/Command.cpp
- src/Mod/Part/Gui/CommandSimple.cpp
- src/Mod/PartDesign/Gui/CommandBody.cpp
- src/Mod/Points/Gui/Command.cpp
- src/Mod/Raytracing/Gui/ViewProvider.cpp
- src/Mod/Robot/Gui/CommandTrajectory.cpp
- src/Mod/Sketcher/Gui/Command.cpp
- src/Mod/TechDraw/Gui/mrichtextedit.cpp
Add the optional `Qt::MSWindowsFixedSizeDialogHint` parameter to all uses of the `QInputDialog::getX` static functions to silence a Qt/Windows debug mode warning, "QWindowsWindow::setGeometry: Unable to set geometry." Increase the size of the unit calculator to eliminate the same warning. Finally, call `adjustSize()` on the "Unsaved Changes" dialogs to silence their warning.
Forums discussion topic here: https://forum.freecadweb.org/viewtopic.php?p=456437
> Silence Qt/Windows setGeometry Warning

- src/App/MergeDocuments.cpp
- src/Gui/CoinRiftWidget.cpp
- src/Gui/Icons/Std_DependencyGraph.svg
- src/Gui/NavigationStyle.cpp
- src/Gui/Tree.h
- src/Gui/ViewProvider.h
- src/Gui/ViewProviderPythonFeature.h
- src/Mod/MeshPart/App/MeshFlattening.h
- src/Mod/Sketcher/App/ExternalGeometryFacadePy.xml
- src/Mod/Sketcher/App/GeometryFacadePy.xml
- src/Mod/Sketcher/App/SketchGeometryExtensionPy.xml
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
Found via `codespell v2.1.dev0`  
```
codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,apoints,ba,beginn,behaviour,bloaded,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,ist,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oder,orgin,orginx,orginy,ot,pard,pres,programm,que,recurrance,rougly,seperator,serie,sinc,strack,substraction,te,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./src …
```
> Fix various typos [skip ci]

- src/Mod/TechDraw/App/DrawViewBalloon.cpp
- src/Mod/TechDraw/App/DrawViewBalloon.h
- src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
There were 2 TechDraw Balloon feature requests made in https://forum.freecadweb.org/viewtopic.php?f=35&t=51869 requiring adding two App::PropertyType properties.  Since any new properties would be added to the FreeCAD file format, too, care should be taken to select the property names, in order to avoid future inconsistencies should the property names be later changed between FreeCAD versions.  The 1st proposed commit adds into Balloon an App::PropertyType property "EndTypeScale" with (default 1.0), which scales the existing property "EndType" of the Balloon (arrow, circle, etc.).  The 2nd proposed commit adds into Balloon an App::PropertyType property "LineVisible" (default true), which draws the Balloon with line if true, and the Balloon without line if false.
There is no changes in …
> [TD] TechDraw Balloon improvements with two new App::PropertyType properties

- src/Mod/Draft/draftfunctions/upgrade.py
- src/Mod/Draft/drafttests/test_modification.py
With these changes, a list of objects conformed by edges (without faces) will be sorted and converted to wires.
Objects with dependencies will not be removed, only visibility will be changed to false.
For a eclectic example, see https://forum.freecadweb.org/viewtopic.php?f=8&t=52583
---
> Draft: Improve makeWires in upgrade function

- src/Mod/TechDraw/Gui/AppTechDrawGuiPy.cpp
When exporting a hidden TechDraw::Page with exportPageAs[Pdf|SVG] a
Segmentation Fault occured.
The return value of getMDIViewPage() was only checked for the first call, but
not for the second call. showMDIViewPage() silently returns, when the
TechDraw::Page is hidden and does not load the page.
---
No new failures - all errors also happen with master branch:
Run test, errors=3 - not regarding this change
- ERROR: test_known_quantity_units (femtest.app.test_material.TestMaterialUnits)
- ERROR: test_material_card_quantities (femtest.app.test_material.TestMaterialUnits)
- ERROR: test_tetra10_yml (femtest.app.test_mesh.TestMeshEleTetra10)
- FAIL: testApplyFiles …
> [TD] Check return value of getMDIViewPage() a second time

- src/Mod/Part/App/TopoShape.cpp
Make the returned plane normal consistent with the underlying face geometry. The face orientation problem is causing trouble with SheetMetal workbench unfolding operation, and is discussed at https://forum.freecadweb.org/viewtopic.php?f=3&t=11303&start=240#p445674
> Part: improve TopoShape::findPlane()

- src/Mod/Path/PathScripts/PathEngraveBase.py
Fixes #4458
This is intended to fix bug #4458. The problem is, that edges are not sorted after dividing and therefore two edges may follow after each other which do not have an equal point at all. Inserting an additional sorting line fixes the problem. I also removed the split by "rebaseWire"-Method, as an additional split already exits in the function. It is not clear to me what is the intended behavior if both StartVertex are given and parameter start_idx is given. Now StartVertex has a higher priority if set. Only PathDeburr is using start_idx, which has no StartVertex-feature. So, there should be no problem rising. I tested deburr and engrave. Both are working in a short test.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the …
> [Path] Sort edges before splitting at selected vertex

- src/Tools/fcinfo
Small changes in the fcinfo script in order to run with both python2 and python3. Some systems now default the system `python` command to run as python3 so this script currently fails on those systems.
> Update fcinfo script for py3 compatibility

- src/Mod/PartDesign/Gui/TaskHoleParameters.ui
This drop-down box contains long names and did not use the space of
the dialog.
See: https://forum.freecadweb.org/viewtopic.php?f=19&t=51491&p=458596#p458596
---
> make the hole-cut-type dropdown-box wider

- src/Mod/TechDraw/App/DrawViewBalloon.cpp
- src/Mod/TechDraw/App/DrawViewBalloon.h
- src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
- src/Mod/TechDraw/Gui/ViewProviderBalloon.cpp
- src/Mod/TechDraw/Gui/ViewProviderBalloon.h
This pull request fixes minor refresh bugs in TechDraw Balloon, and changes the order of the Properties in UI.  This fixes problems discussed in a FreeCAD [Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=35&t=51869).
---
> [TD] Balloon fixes, change places of Properties in UI, fix refresh bugs

- src/Mod/Path/PathScripts/PathSurfaceSupport.py
Fixes erroneous reference to cutting edge angle identified in forum thread: [Tool controller breakage: 'cuttingEdgeAngle'](https://forum.freecadweb.org/viewtopic.php?f=15&t=53365).
The class variable name was not corrected with previously committed changes.
The correct cutting edge variable name is located in the __init__() constructor method.
---
> Path: Fix reference to cutting edge angle in OCL_Tool() class

- src/Mod/Sketcher/Gui/Command.cpp
Eliminate the Windows debug-mode warning on creating a new sketch by making `SketchOrientationDialog` adjust its size before displaying.
> [Sketcher] Eliminate Windows debug-mode warning

- src/Mod/Sketcher/App/SketchObject.cpp
This closes:
https://tracker.freecadweb.org/view.php?id=4510
https://forum.freecadweb.org/viewtopic.php?f=8&t=53240
After PR:
Before PR:
> Sketcher: Delete Equal constraints on LineSegments in SketchObject::trim

- src/Mod/Path/PathScripts/PathSlot.py
This PR addresses bugs and shortcomings identified at [Remove the check for parallel edges for the slot operation](https://forum.freecadweb.org/viewtopic.php?style=3&f=15&t=53317).
This PR does the following:
- Fixes path generation for selection of two non-parallel edges.
- Fixes path generation for selection of single, bottom face of slot with two non-parallel ends.
- Fixes path generation for selection of two parallel, bottom bounding edges of slot.
- Adds docStrings to some methods for improved documentation.
- Addresses two LGTM items. …
> Path: Fixes to Slot op

- src/Mod/Sketcher/App/SketchObject.cpp
This fixes issue
https://tracker.freecadweb.org/view.php?id=4513
https://forum.freecadweb.org/viewtopic.php?f=22&t=53346
addSymmetric will now only transfer Vertical and Horizontal constraints if the reference axis is either
- the HAxis
- the VAxis
- a Vertical line
- a Horizontal line
**Before:**
**After:**
> Sketcher: Fix issue #4513 - SketchObject::addSymmetric

- src/Gui/Action.cpp
- src/Gui/Command.cpp
- src/Gui/CommandStd.cpp
See issue reported [here](https://github.com/realthunder/FreeCAD_assembly3/issues/388).
`QAction` defaults menu role to `TextHeuristicRole`, which causes qt to guess the menu role based on action title. And titles start with 'Config', 'Options', 'Settings', etc. will be considered as preference menu. It seems some non-english translation causes the wrong action be chosen as preference, such as 'Treeview actions'.
This commit just applied a temporary fix to default to `QAction::NoRole` for `GroupCommand`. If there is ever some `GroupCommand` need to be a system menu item on macos, we could add some command bit flag for that purpose.
> Gui: temporary fix of preference menu in MacOS

- src/Mod/Sketcher/Gui/SketcherSettingsColors.ui
- as discussed here: https://forum.freecadweb.org/viewtopic.php?f=10&t=53587&start=10#p460768
the wording "datum color" does not make clear what it is about. It is in fact the color for dimensional constraints, thus name it as such
- also fix the dialog height (found and automatically corrected by Qt Designer)
> [Sketch] improve wording for a color

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/EditDatumDialog.cpp
- src/Mod/Sketcher/Gui/InsertDatum.ui
- add missing class to UI file (found and automatically added by Qt Designer)
- add more sensible stepsize - you are dealing in practice with rations in the range 1.2 - 1.6 thus a stepsize of 1.0 is not helpful
> [Sketch] fix SnellsLaw dialog

- src/Mod/Path/PathScripts/PathAdaptive.py
- src/Mod/Path/PathScripts/PathAdaptiveGui.py
- src/Mod/Path/libarea/Adaptive.cpp
- src/Mod/Path/libarea/Adaptive.hpp
- src/Mod/Path/libarea/PythonStuff.cpp
- src/Mod/TechDraw/App/DrawViewBalloon.cpp
> Path: Adaptive work

- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/Sketch.h
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
- src/Mod/Sketcher/App/planegcs/GCS.cpp
- src/Mod/Sketcher/App/planegcs/GCS.h
- src/Mod/Sketcher/App/planegcs/Geo.cpp
- src/Mod/Sketcher/App/planegcs/Geo.h
- src/Mod/Sketcher/Gui/TaskSketcherSolverAdvanced.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
Basically:
- ViewProviderSketch no longer has r/w access to the solver. It has r/o access and has to go through SketchObject for r/w operations.
- GCS uses const correctness to increase the r/o interface (also uses override).
- Fixes bug that a line with a single reference constraint would be detected as fully-constraint sketch.
- Fixes a bug that on toggling construction the Element's widget is not updated.
- Fixes a crash on renaming a constraint: https://github.com/FreeCAD/FreeCAD/pull/4183
**Note**: If you don't have wiki access, then please mention your contribution on the …
> [Sketcher] SketchObject takes over r/w management of Sketch - Several fixes

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/CommandConstraints.h
==============================================================
Previously construction points was used to code bspline knots.
Now construction points are normal sketcher points, which can be
made defining.
This commit renames and adapts the checks for fixed geometry.
fixes:
https://forum.freecadweb.org/posting.php?mode=quote&f=3&p=461472#pr461472
---
> [Sketcher] check for BSpline knot instead of construction point

- src/Mod/PartDesign/App/FeatureLinearPattern.cpp
When using linear pattern with expression, this can be usefull to have only one
occurence (the original one), which can't be done with the following
implemenation. This commit change this behaviour by allowing this value.
> LinearPattern: Support 1 occurrence

- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/Sketch.h
- src/Mod/Sketcher/App/planegcs/GCS.cpp
- src/Mod/Sketcher/App/planegcs/GCS.h
========================================
Previous versions relied on a heuristic that proved insufficient for cummulative use of the Block constraint.
The effect is that Block constraints stopped blocking, which is a major bug, as it lead to inadvertedly moving
geometry that was supposed to be blocked.
Fixes:
https://forum.freecadweb.org/viewtopic.php?f=13&t=53515&start=30#p461215
(Thanks Chaospilot)
Know problems with old block constraint (v0.18):
1. If driving constraints were present, they were ignored if inserted before the block constraint (to avoid
redundancy/conflicting). They resulted in
Principles of Working of the new block constraint:
1. Handling of the new block constraint is based two processes, a pre-analysis and a post-analysis. Pre-analysis
works *before* diagnosing the …
> Sketcher/GCS: New Block constraint fixes

- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvancedImp.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotation.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawColors.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensionsImp.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneral.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawGeneralImp.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawHLR.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawScale.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawScaleImp.cpp
as discussed here: https://forum.freecadweb.org/viewtopic.php?f=35&t=53680&p=461356#p461349
* change default tolerance text scale to 0.8
* the tolerance scale is directly applied, thus it must have non-italic label
* move tolerance scale to "Dimensions" tab
* move Fuzz settings to "Advanced" tab
* add a note for the label font that this is also used for dimensions and that it there only has an effect for new ones
* use more useful step size of 0.1 for some scaling spinboxes
* sort UI fields in the C++ code to avoid doubled or missing entries (there were 2 doubled entries)
> [TD] cleanup preferences

- src/Gui/CommandView.cpp
- src/Gui/Icons/Std_SetAppearance.svg
- src/Gui/Icons/Std_ViewIvStereoInterleavedColumns.svg
- src/Gui/Icons/Std_ViewIvStereoInterleavedRows.svg
- src/Gui/Icons/Std_ViewIvStereoOff.svg
- src/Gui/Icons/Std_ViewIvStereoQuadBuff.svg
- src/Gui/Icons/Std_ViewIvStereoRedGreen.svg
- src/Gui/Icons/resource.qrc
Six Std View Menu commands have similar ad not representative icons in the FreeCAD UI (Menu View - Stereo ): Std SetAppearance, and the five ViewIvStereo tools. Using similar icons is confuse. 
This commit replaces these SVG files with more representative icons for these commands. Also, it makes the necessary changes on CommandView.cpp and resource.qrc files.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=53119&start=20#p460992 https://forum.freecadweb.org/viewtopic.php?f=34&t=53119&start=30#p461058
> Replace SVG icons of six Std View commands

- src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
as reported here: https://forum.freecadweb.org/viewtopic.php?f=35&t=53664 the balloon text separation no longer works.
The regression was introduced by commit 05577c267 . The mistake thereby was that the textHeight is already handled before the separators and that rectangular balloons behave differently because of the separator feature.
> [TD] fix regression for balloon text separators

- src/Mod/Path/PathScripts/post/centroid_post.py
Some items in `objectList` do not contain a `Proxy` child and cause a fatal error in post processing with this post module.
---
> Path: Centroid post - Fix isinstance() `item.Proxy` error

- src/Mod/Path/PathScripts/PathIconViewProvider.py
Many `Path` object forward its editing operation to the job object. It is possible that some editing option change may lead to removing of the editing object (e.g. changing stock type) causing crash. It is possible to just open the task panel without setting any editing object by returning `False` in `ViewProvider.setEdit()`.
Reported at realthunder/FreeCAD_Assembly3#393
> Path: fix crash on edit

- src/Gui/GraphvizView.cpp
- src/Gui/View3DInventor.cpp
- src/Mod/Drawing/Gui/DrawingView.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.cpp
QPrinter::paperRect() and QPrinter::pageRect() are obsolete.
---
Cheers,
Mateusz
> Fix Qt deprecation warnings.

- src/Mod/Path/App/Area.cpp
- src/boost_geometry.hpp
> Fix build warnings from deprecated Boost headers (1.74)

- src/Mod/TechDraw/App/DrawViewBalloon.cpp
- src/Mod/TechDraw/Gui/TaskBalloon.cpp
- src/Mod/TechDraw/Gui/TaskBalloon.h
- src/Mod/TechDraw/Gui/TaskBalloon.ui
- src/Mod/TechDraw/Gui/ViewProviderBalloon.cpp
2 weeks ago the properties EndTypeScale and LineVisible were added by @aapo-aapo but not to the dialog.
This PR adds them to the balloon dialog.
I also took the opportunity to cleanup the code:
- add missing tooltips
- uniform tooltips in App and Gui
- uniform the UI element names
This is the updated dialog:
> [TD] update balloon dialog

- src/Gui/GraphvizView.cpp
- src/Gui/View3DInventor.cpp
- src/Mod/Drawing/Gui/DrawingView.cpp
- src/Mod/Drawing/Gui/DrawingView.h
- src/Mod/TechDraw/Gui/MDIViewPage.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.h
QPrinter::orientation() and QPrinter::setOrientation() are obsolete.
---
Cheers,
Mateusz
> Fix Qt deprecation warnings. 

- src/Gui/Document.cpp
The crash is reported at https://forum.freecadweb.org/viewtopic.php?f=19&t=52221&start=50#p460591
The crash is triggered by assertion failure in DAG view, because it cannot find the editing object. The root cause is because it is an external linked object, so the editing document (which is the owner of the top parent object) is different from the owner document of the editing object. This PR makes sure to use the owner document of the editing object to fire the signal.
> Gui: fix potential external edit reset crash

- src/Mod/Draft/draftmake/make_copy.py
always copy with dependencies when copying App::Part and PartDesign::Body
https://forum.freecadweb.org/viewtopic.php?f=23&t=53940&p=463601#p463601
https://forum.freecadweb.org/viewtopic.php?f=3&t=49753&start=10
.
> Draft: change in default Draft.makeCopy

- src/Mod/Draft/draftguitools/gui_array_simple.py
- src/Mod/Draft/draftguitools/gui_clone.py
- src/Mod/Draft/draftguitools/gui_downgrade.py
- src/Mod/Draft/draftguitools/gui_draft2sketch.py
- src/Mod/Draft/draftguitools/gui_facebinders.py
- src/Mod/Draft/draftguitools/gui_join.py
- src/Mod/Draft/draftguitools/gui_offset.py
- src/Mod/Draft/draftguitools/gui_patharray.py
- src/Mod/Draft/draftguitools/gui_pathtwistedarray.py
- src/Mod/Draft/draftguitools/gui_pointarray.py
- src/Mod/Draft/draftguitools/gui_shape2dview.py
- src/Mod/Draft/draftguitools/gui_split.py
- src/Mod/Draft/draftguitools/gui_upgrade.py
See https://tracker.freecadweb.org/view.php?id=4243 and https://tracker.freecadweb.org/view.php?id=3971
The reported crash is reproducible in most Draft modification functions (even interleaving them) by following the steps indicated in a higher number of repetitions. In my particular case I had to perform 4 or more loops. Sometimes a freeze occurs prior to crash.
The problem is due to a double attempt to remove the Coin callback.
Removing the call to the removeEventCallback method in the draftguifunctions and leaving only the call made in the inherited self.finish method is enough to resolve the bug.
And please remember to update the Wiki with the features added or changed …
> Draft: Fix multiple crashes when using modification functions - fixes #0004243, #0003971

- src/Mod/Draft/draftfunctions/draftify.py
- src/Mod/Draft/draftfunctions/upgrade.py
See https://forum.freecadweb.org/viewtopic.php?f=3&t=53389
The reported behavior is due to a bug in Part.getSortedClusters, so the function is replaced by Part.sortEdges.
The draftify function can now deal with circular arc objects and some minor changes are added to the update function.
---
> Draft: Replace Part.getSortedClusters by Part.sortEdges in draftify function

- src/Gui/CommandView.cpp
- src/Gui/Icons/Std_HideObjects.svg
- src/Gui/Icons/Std_HideSelection.svg
- src/Gui/Icons/Std_SelectVisibleObjects.svg
- src/Gui/Icons/Std_ShowObjects.svg
- src/Gui/Icons/Std_ShowSelection.svg
- src/Gui/Icons/Std_ToggleObjects.svg
- src/Gui/Icons/Std_ToggleVisibility.svg
- src/Gui/Icons/Std_ViewIvIssueCamPos.svg
- src/Gui/Icons/resource.qrc
Seven Std View Menu commands don't have icons and one has an inadequate icon (Std ViewIvIssueCamPos) in the FreeCAD UI.
This commit adds 8 SVG files with new icons for these commands (and replaces Std ViewIvIssueCamPos icon). Also, it makes the necessary changes on CommandView.cpp and resource.qrc files.
Forum discussion: 
https://forum.freecadweb.org/viewtopic.php?f=34&t=53119&start=20#p460977
https://forum.freecadweb.org/viewtopic.php?f=34&t=53119&start=30#p462660
> Add last SVG icons for eight Std View commands

- src/Gui/Tree.cpp
- src/Gui/ViewProvider.cpp
- src/Gui/ViewProvider.h
- src/Gui/ViewProviderDocumentObjectGroup.cpp
- src/Gui/ViewProviderExtension.h
- src/Gui/ViewProviderPythonFeature.h
- src/Mod/Part/Gui/ViewProviderAttachExtension.cpp
- src/Mod/Part/Gui/ViewProviderAttachExtension.h
- src/Mod/PartDesign/Gui/ViewProvider.cpp
- src/Mod/PartDesign/Gui/ViewProvider.h
- src/Mod/PartDesign/Gui/ViewProviderLoft.cpp
- src/Mod/PartDesign/Gui/ViewProviderPipe.cpp
- src/Mod/PartDesign/Gui/ViewProviderPrimitive.cpp
- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/Sketch.h
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
- src/Mod/Sketcher/App/SketchObjectPy.xml
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
- src/Mod/Sketcher/Gui/TaskSketcherMessages.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
- src/Mod/Sketcher/Gui/Workbench.cpp
- src/Mod/TechDraw/Gui/ViewProviderCosmeticExtension.cpp
- src/Mod/TechDraw/Gui/ViewProviderCosmeticExtension.h
- Show attachment overlay icon for Sketch.
- Allow a developer to select whether to use overlay icons that will deactivate when visibility is lost, or overlay icons that remain colorful when visibility is lost.
- Sketch will show an overlay icon if it is not fully constrained (at bottom-right position)
- Treat malformed constraints as errors (shown in sketcher messages and causing the sketch to error on recompute)
- Improve deletion of geometry from the UI - Fix report view errors when deleting geometry having internal geometry
- Expose deletion of multiple geometries at once to Python
- Remove Internal Alignment constraint from toolbar.
> [Sketcher] Colorful status flags and other Sketcher improvements

- src/Mod/OpenSCAD/tokrules.py
[OpenSCAD] fix parser error for numbers with positive exponent >= 6
see forum: https://forum.freecadweb.org/viewtopic.php?f=3&t=54044
---
> [OpenSCAD] fix parsing error for numbers with positive exponent >= 6

- src/Gui/CommandView.cpp
in commit 7587658ae3 the icon was not also added to the used Std_AxisCross menu entry
> [GUI] fix missing Std_AxisCross icon

- src/Mod/PartDesign/App/FeatureChamfer.cpp
- src/Mod/PartDesign/App/FeatureFillet.cpp
- src/Mod/PartDesign/App/FeaturePipe.cpp
Related to issue https://tracker.freecadweb.org/view.php?id=3927
---
> [PartDesign]: Fix refine boolean not being obeyed at multiple places

- src/Gui/SelectionObjectPy.xml
- src/Gui/SelectionObjectPyImp.cpp
A crash occurs when trying to access the Document and Object attributes of a SelectionObject.
Steps to reproduce the crash:
Create any object on the tree and select it.
create a SelectionObject from the command line:
sel_obj, = Gui.Selection.getSelectionEx()
Delete the object from the tree.
Try to access the sel_obj.Document or sel_obj.Object attributes.
---
> Gui: Prevent crash when trying to access a deleted object from a SelectionObject

- src/Mod/Sketcher/App/SketchObject.cpp
The variable newVals can't be used after std::move, fetch it from the constraint instead it if an error occurs.
Since this bug [just got merged into master](https://github.com/FreeCAD/FreeCAD/pull/4257/files#diff-b9dbc09c2c4b8417d6df9b1640fe0b24441cf026658dd5220d8917aa1ebcf356R365), I hope that we can get this resolved rather quickly.
---
---
> [Sketcher] Fix crash in SketcherObject::setDatum

- src/Mod/Part/App/Geometry.cpp
- src/Mod/Part/App/GeometryDefaultExtension.cpp
- src/Mod/Part/App/GeometryDefaultExtension.h
- src/Mod/Part/App/GeometryExtension.cpp
- src/Mod/Part/App/GeometryExtension.h
- src/Mod/Part/App/GeometryMigrationExtension.cpp
- src/Mod/Part/App/GeometryMigrationExtension.h
- src/Mod/Sketcher/App/ExternalGeometryExtension.cpp
- src/Mod/Sketcher/App/ExternalGeometryExtension.h
- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/SketchGeometryExtension.cpp
- src/Mod/Sketcher/App/SketchGeometryExtension.h
- src/Mod/Sketcher/App/SolverGeometryExtension.cpp
- src/Mod/Sketcher/App/SolverGeometryExtension.h
- src/Mod/Sketcher/Gui/ViewProviderSketchGeometryExtension.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketchGeometryExtension.h
The API of Geometry Extensions regarding copy, save and restore did not make effective use of code reuse and was error-prone.
For all extensions:
- Regarding copy, a new virtual method copyAttributes() ensures that all the geometry extension hierarchy is called to copy its members.
For GeometryPersistentExtensions:
- similarly saveAttributes() and restoreAttributes virtual functions ensure that members in the hierarchy are called for save and restore.
Addition for all extensions:
- A notify Attachment trigger, notifying an extension that has been attached to a new geometry object, providing as argument a pointer to the geometry object. This ensures that an extension has a valid pointer to the geometry, enabling it to extend properties and functionalities of the Part::Geometry object.
> [Part/Sketcher] Geometry extensions refactor copy save restore notification 

- src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
- src/Mod/TechDraw/Gui/TaskBalloon.cpp
- src/Mod/TechDraw/Gui/TaskBalloon.h
When adding GD&T statements as described in
https://wiki.freecadweb.org/TechDraw_Geometric_dimensioning_and_tolerancing#Geometrical_Tolerancing
you will quickly get a lot of balloons and it is then very tiring to be forced to first select a balloon with a single-click in the drawing, then go to the model tree and there double-click to get the dialog.
With this PR you can directly double-click in the drawing to open the dialog directly.
This PR also removes unused includes from the dialog code.
> [TD] show balloon dialog on double-clicking

- src/Mod/Start/CMakeLists.txt
- src/Mod/Start/InitGui.py
- src/Mod/Start/StartPage/StartPage.py
- src/Mod/Start/TestStart/TestStartPage.py
- src/Mod/Start/TestStartGui.py
The real purpose of this PR is to fix a single missing replacement line from the Start page's generated HTML: the CSS for the shadow behind the file cards was not getting replaced, leaving the word "SHADOW" in the final CSS instead. a0aaae7ea corrects that, adding a single line to src/Mod/Start/StartPage/StartPage.py.
However, currently Start does not have any unit tests, so fcdd44115 adds the test framework to Start (without adding any tests), and d18a76e9b adds a complete test for all expected replacements. It's broken up into three tests, one for each component of the final web page: the CSS, the JS, and the HTML. The CSS test will fail unless a0aaae7ea is applied. 
Thanks to @hyarion in the FreeCAD forums for the suggested commit structure.
> [Start] Shadow fix and add unit tests

- src/Mod/Spreadsheet/App/PropertySheet.cpp
- src/Mod/Spreadsheet/App/PropertySheet.h
- src/Mod/Spreadsheet/App/Sheet.cpp
- src/Mod/Spreadsheet/TestSpreadsheet.py
This fixes [0004492: Spreadsheet deleted value remains in database](https://tracker.freecadweb.org/view.php?id=4492)
Previously, when removing a row in a spreadsheet which had an assigned alias, the
alias will not be removed from the list of dynamic properties.
This made it impossible to create a new alias which used the same name
even though the original was removed with the row or column.
See testcases in TestSpreadsheet.py for more information on the issue.
Here is the forum post discussing this issue: https://forum.freecadweb.org/viewtopic.php?f=8&t=52116
---
**Note**: If …
> [Spreadsheet] Remove alias from dynamic properties on removeRows/Columns

- src/Mod/Path/PathScripts/PathOpGui.py
Error was thrown if FreeCADGui.Selection list had more than one item.  Solution is to clear selection before adding  selection from import operation.  I also removed the `for` loop since the selection should be singular.
---
> Path: Fix `Import` feature of Base Geometry

- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
as discussed here: https://forum.freecadweb.org/viewtopic.php?f=35&t=54218
when a value is theoretically exact, it must not have a tolerance
This PR
* fixes this
* also fixes the bug that OverTolerance must not be negative if the tolerances are equal
> [TD] don't allow tolerances for exact values

- src/Mod/Arch/ArchComponent.py
Enable Link of Window to be created with Hosts empty, otherwise ArchWall will return error in original code.
Subsequent to forum discussion [ Link of Window Not Creating Hole](https://forum.freecadweb.org/viewtopic.php?f=23&t=50364)
---
> [ArchComponent] Fix Link Of Window Hosts if empty got error as Wall Child

- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/Gui/CMakeLists.txt
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.h
- src/Mod/TechDraw/Gui/QGVPage.cpp
- src/Mod/TechDraw/Gui/TaskDimension.cpp
- src/Mod/TechDraw/Gui/TaskDimension.h
- src/Mod/TechDraw/Gui/TaskDimension.ui
- src/Mod/TechDraw/Gui/ViewProviderDimension.cpp
- src/Mod/TechDraw/Gui/ViewProviderDimension.h
The dimension object is the only one in TechDraw not having a dialog. This PR add this.
It can either be called by double-clicking on a dimension in the model tree or by double-clicking directly onto a dimension in the drawing. (The latter is a real boost in productivity since one usually has dozens of dimensions and every time first single-click on one in the drawing, then going to the model tree, the double-click needs is with the time tiring/annoying.)
There is how the dialog looks:
Maybe some more settings should appear there, however, for now it is important to have at least a dialog.
I also changed with the PR some wording.
The PR contains already the fixes I made in PR #4263 to avoid merge conflicts.
> [TD] add dialog to modify some dimension settings

- src/Mod/PartDesign/App/FeaturePipe.cpp
- src/Mod/PartDesign/App/FeaturePipe.h
- Previously a subtractive pipe on a body with no solids would create a solid. Now Pipe will generate an error.
- Fix incorrect property header. Previously Pipe was identifying itself as Pad (copy paste error)
> PartDesign: Fix small bugs in the Pipe feature

- src/Gui/SelectionObjectPyImp.cpp
Identical to #4228 but when trying to access the SubObjects attribute.
---
> Gui: Prevent crash when trying to access sub-objects of a deleted object from a SelectionObject

- src/Mod/TechDraw/Gui/TaskActiveView.cpp
- src/Mod/TechDraw/Gui/TaskActiveView.h
- src/Mod/TechDraw/Gui/TaskBalloon.cpp
- src/Mod/TechDraw/Gui/TaskBalloon.h
- src/Mod/TechDraw/Gui/TaskCenterLine.cpp
- src/Mod/TechDraw/Gui/TaskCenterLine.h
- src/Mod/TechDraw/Gui/TaskCosVertex.cpp
- src/Mod/TechDraw/Gui/TaskCosVertex.h
- src/Mod/TechDraw/Gui/TaskCosmeticLine.cpp
- src/Mod/TechDraw/Gui/TaskCosmeticLine.h
- src/Mod/TechDraw/Gui/TaskDetail.cpp
- src/Mod/TechDraw/Gui/TaskDetail.h
- src/Mod/TechDraw/Gui/TaskGeomHatch.cpp
- src/Mod/TechDraw/Gui/TaskGeomHatch.h
- src/Mod/TechDraw/Gui/TaskHatch.cpp
- src/Mod/TechDraw/Gui/TaskHatch.h
- src/Mod/TechDraw/Gui/TaskLeaderLine.cpp
- src/Mod/TechDraw/Gui/TaskLeaderLine.h
- src/Mod/TechDraw/Gui/TaskLineDecor.cpp
- src/Mod/TechDraw/Gui/TaskLineDecor.h
- src/Mod/TechDraw/Gui/TaskLinkDim.cpp
- src/Mod/TechDraw/Gui/TaskLinkDim.h
- src/Mod/TechDraw/Gui/TaskProjGroup.cpp
- src/Mod/TechDraw/Gui/TaskProjGroup.h
- src/Mod/TechDraw/Gui/TaskRichAnno.cpp
- src/Mod/TechDraw/Gui/TaskRichAnno.h
- src/Mod/TechDraw/Gui/TaskSectionView.cpp
- src/Mod/TechDraw/Gui/TaskSectionView.h
- src/Mod/TechDraw/Gui/TaskWeldingSymbol.cpp
- src/Mod/TechDraw/Gui/TaskWeldingSymbol.h
as noted in https://github.com/FreeCAD/FreeCAD/pull/4271#discussion_r554673632
the pointer to the UI should be a unique pointer.
This PR does this for all TD dialogs that don't already use a unique_ptr.
> [TD] make pointers to the UI a std::unique_ptr

- src/Mod/Part/Gui/Command.cpp
- src/Mod/Part/Gui/Resources/Part.qrc
- src/Mod/Part/Gui/Resources/icons/tools/Part_MakeFace.svg
- src/Mod/Part/Gui/Resources/icons/tools/Part_MakeSolid.svg
Two Part commands do not have icons for the FreeCAD UI: MakeFace, MakeSolid
This commit adds SVG files with icons for these commands. Also, it makes the necessary changes on Command.cpp and Part.qrc files.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=54349
> [UI] Add SVG icons for two Part commands

- src/Mod/Arch/ArchRoof.py
A relative profile can now be used if it references itself. This fixes a compatibility issue with the V0.18 version of ArchRoof, where the first profile initially always references itself.
---
> ArchRoof.py: Fix for self referencing relative profile issue

- src/Mod/PartDesign/Gui/CommandBody.cpp
- src/Mod/PartDesign/Gui/Resources/PartDesign.qrc
- src/Mod/PartDesign/Gui/Resources/icons/PartDesign_Migrate.svg
- src/Mod/PartDesign/Gui/Resources/icons/PartDesign_MoveFeature.svg
- src/Mod/PartDesign/Gui/Resources/icons/PartDesign_MoveFeatureInTree.svg
Three PartDesign commands do not have icons for the FreeCAD UI: PartDesign Migrate, MoveFeature, MoveFeatureInTree
This commit adds SVG files with icons for these commands. Also, it makes the necessary changes on CommandBody.cpp and PartDesign.qrc files.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=54041
> [UI] Add SVG icons for three PartDesign commands

- src/Mod/OpenSCAD/Resources/icons/OpenSCAD_MirrorMeshFeature.svg
- src/Mod/OpenSCAD/Resources/icons/OpenSCAD_ScaleMeshFeature.svg
Two OpenSCAD commands have icons that contain PNG images: OpenSCAD_MirrorMeshFeature
OpenSCAD_ScaleMeshFeature
This commit replaces the SVG files with full vector icons for these commands.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=54040
> [UI] Replacement of 2 SVG icons for OpenSCAD commands

- src/Mod/Draft/draftguitools/gui_lines.py
When create a Draft polyline, if the third point close the wire with the first point, the edge created in this step overlap the first edge. The command create a single-edge wire but sets it as closed.
---
> Draft: Prevent Draft_Wire from setting a single-edge wire as closed

- src/Gui/CommandWindow.cpp
- src/Gui/Icons/Std_Windows.svg
- src/Gui/Icons/resource.qrc
Std Windows command does not have icon for the FreeCAD UI (Menu windows).
This commit adds a SVG file with icon for this command. Also, it makes the necessary changes on CommandWindow.cpp and resource.qrc files.
The new SVG icon follow the FreeCAD Artwork Guidelines and was saved as Plain SVG format.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=54028
> Add SVG icon for Std Windows command

- src/App/Document.cpp
- src/App/Document.h
- src/Gui/CommandDoc.cpp
- src/Mod/Web/Gui/BrowserView.cpp
Summary:
If the restore of Document.xml results in invalid Document.xml (because unhandled exceptions occurred), the
document status Document::restoreError is set. The GUI or Mod/Web if a link was clicked, show a pop-up indicating
this situation.
This commit also shows an appropriate pop-up for the partialRestore when opening from the menu, that before only
appeared when opening by clicking a link.
> App/Gui: New restoreError Document status and Gui pop-up

- src/Mod/Path/Gui/Resources/panels/PageBaseGeometryEdit.ui
- src/Mod/Path/PathScripts/PathOp.py
- src/Mod/Path/PathScripts/PathOpGui.py
- src/Mod/Path/PathScripts/PathVcarve.py
- src/Mod/Path/PathScripts/PathVcarveGui.py
fixes issue https://forum.freecadweb.org/viewtopic.php?f=15&t=54726 by
* processing BaseShapes
* allowing multiple models and base objects
* only fall back to job model if no Base and no BaseShapes are set
* only call the base addBaseGeometry() once
This also disables the base geometry list widget resizing because it ends up way too small to be usable on HPD monitors - and I needed to see what I'm doing in order to fix this issue.
> [Path]: Bugfix/vcarve selection and feature processing

- src/Mod/Path/PathScripts/PathDressupTagGui.py
self.obj.Base can be None which raises an exception on deletion so the dressup can never be deleted. This small change fixes that.
---
> [Path] Fix AttributeError on deleting corrupt dressup

- src/Mod/Draft/draftguitools/gui_snapper.py
The code would only find a center snap on the face with index=0 of solids.
In V0.19 Part.getShape was introduced (line 399). But not all consequences were not fully implemented.
In the '# we are snapping to an edge' section (line 411) the code could be cleaned up. There is no need to check if the index of the edge is correct for the parent object since we are no longer dealing with a parent object. That portion was effectively dead code.
The '# we are snapping to a face' section (line 429 in the revised code) has been modified accordingly, which fixes the bug.
https://forum.freecadweb.org/viewtopic.php?f=23&t=54747
> [Draft] Fix snap to center of faces of solids

- src/Gui/Inventor/MarkerBitmaps.cpp
These changes makes the round markers symmetric horizontally, vertically and on the diagonal.
The changes to the round markers, that are used in sketcher, are shown in the screenshot below.
The circle versions has similar changes applied.
This forum post highlighted, unintentionally the issue: https://forum.freecadweb.org/viewtopic.php?p=470763#p470763
---
- ~Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists~ …
> [Gui] Make inventor markers symmetric

- src/Mod/Part/Gui/ViewProviderExt.cpp
For some invalid shapes, there may be faces with null mesh. In this case, Part::ViewProviderExt may produce an invalid SoBrepFaceSet::partIndex.
> Part: fix ViewProviderExt::updateVisual() on incomplete mesh

- src/Mod/Sketcher/Gui/TaskSketcherGeneral.h
The generated ui_TaskSketcherGeneral.h defines the class in the
SketcherGui namespace.
Fixes #4529
---
> Fix ODR violation, correct Ui_TaskSketcherGeneral namespace

- src/Mod/MeshPart/App/Mesher.cpp
It doesn't make sense to check `minLen` and then call `SetMinSize` with `maxLen`,
hence, this must be a copy-paste error.
Introduced in https://github.com/FreeCAD/FreeCAD/commit/f681b86abdddd55e2dcb80bc4612251570cc9b8b
With code submitted in issue #0004426
Found with Coverity.
---
---
> [MeshPart] Fix copy-paste error

- src/App/Extension.h
- src/App/ExtensionContainerPy.xml
- src/App/ExtensionContainerPyImp.cpp
- src/Gui/ViewProviderExtension.h
- src/Mod/Arch/ArchBuildingPart.py
- src/Mod/Arch/ArchProject.py
- src/Mod/Arch/ArchSite.py
- src/Mod/Draft/draftmake/make_clone.py
- src/Mod/Draft/draftobjects/draftlink.py
- src/Mod/Fem/femsolver/solverbase.py
- src/Mod/Part/BasicShapes/Shapes.py
- src/Mod/Part/BasicShapes/ViewProviderShapes.py
- src/Mod/Test/Document.py
This fixes #0004534
The solution is to be decided by discussion: [Forum](https://forum.freecadweb.org/viewtopic.php?f=10&t=54370)
The approach used in this pull request is the one with the most elegant outcome, but also with the largest changes regarding API breakage. It fully removes the ExtensionProxy property and uses the default Proxy property for overriding extension methods. This means that extensions can be added to all FreeCAD objects, however, method overriding only for Pythons Features, as only those have the Proxy property
> Remove ExtensionProxy and rely on default Python proxy for extensions

- lgtm.yml
FreeCAD as a whole is too large for LGTM to analyze the entire codebase: the operation times out after three hours. By focusing only on the core code, this patch allows the automated testing framework there to analyze our C++ code, in addition to the Python and JavaScript analysis it was already doing. 
---
> Enable LGTM analysis of core C++ source code

- src/Mod/PartDesign/Resources/Hole/iso10642.json
- src/Mod/PartDesign/Resources/Hole/iso7046.json
I was able to get the norms and could update the definitions accordingly.
For example in the ISO 10462, sizes smaller than M3 are not defined and your definition files should only contain what is really defined.
> [PD] correct hole cut definitions

- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/App/DrawViewDimension.h
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
- src/Mod/TechDraw/Gui/TaskDimension.cpp
- src/Mod/TechDraw/Gui/TaskDimension.h
- src/Mod/TechDraw/Gui/TaskDimension.ui
This PR fixes two bugs:  The new equilateral tolerances are missing a degree sign for angles. Also, arbitrary under/overtolerances have somehow lost the possibility to be set separately.  E.g. "std project tolerance" for under, and "as tight as possible" for upper.  The bugs were reported [here](https://forum.freecadweb.org/viewtopic.php?f=35&t=54740)
---
> [TD] Fix equilateral angular tolerance missing degree unit char, fix arbitary under/overtolerances

- src/Gui/Application.cpp
Corrects a merge issue from an earlier PR: the removed lines are redundant, they are repeated immediately below within the conditional.
> [GUI] Remove extraneous lines from export

- src/Mod/Surface/Gui/TaskFilling.cpp
- src/Mod/Surface/Gui/TaskFillingEdge.cpp
- src/Mod/Surface/Gui/TaskFillingVertex.cpp
The Delete key shortcut of the three different panels in the Surface Workbench TaskFilling sidebar conflicted between the panels if multiple were showing. This is resolved by making the QAction's context the widget, rather than the window.
Discussion here: https://forum.freecadweb.org/viewtopic.php?f=8&t=55037
Thanks to @0penBrain for figuring out the problem and proposing this fix.
---
- No associated tracker ticket
> [Surface] Fix task panel Delete shortcut use to use Widget context

- src/Mod/Start/StartPage/StartPage.html
- src/Mod/Start/StartPage/StartPage.py
- src/Mod/Start/TestStart/TestStartPage.py
To ensure the best possible rendering of the Start page (and to try to eliminate a bug encountered in the JavaScript while developing another PR), this PR makes a number of minor changes to the HTML generation, based on the recommendations of the W3C HTML validator at https://validator.w3.org/nu/#file .
The items fixed are:
* Missing DOCTYPE specification
* Missing language setting on the body of the document
* Deprecated attributes set for the style and script tags
* Image tags require alt text
* List tags can only contain list items
* All file:/// URLs must not contain backslashes, even on Windows
Unit tests are added for these items by integrating a call to the W3C validator in the GUI tests for Start.
---
- No issue ID
> [Start] Modify generated HTML to comply with W3C Validator Recommendations

- src/Mod/Draft/importDXF.py
- src/Mod/OpenSCAD/OpenSCAD2Dgeom.py
As discussed in https://forum.freecadweb.org/viewtopic.php?f=3&t=54842, if OpenSCAD creates a DXF with no layers in it, the code that is supposed to handle that in FreeCAD has a minor type error in it that prevents the import from working. For example, loading the OpenSCAD workbench and entering the following code will fail without this change:
```
minkowski(){
square( [10,10] );
circle( d=2 );
}
```
The first failure is due to the color of the default layer being created as an array instead of a tuple -- this PR changes the type to a tuple. The second failure is due to the layer object not having the required removal function. This PR checks for the existence and callability of that function before calling it.
---
- No tracker ticket has been filed
> [Draft] OpenSCAD/DXF error: fix DXF import with no layers

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.h
- src/Mod/PartDesign/Gui/TaskHoleParameters.ui
This PR is the first in a series of 3 PRs to fix known hole dialog bugs. (PR #4344 and PR #4347 depend on this PR)
This one fixes:
- the .ui file issues
- readonly status issues of some widgets/properties (e.g. when the hole is through all, disable drill point settings)
- the bug that updateHoleCutParams() overwrote the previously correctly determined hole diameter
- the missing check that the counterbore/sink diameter must not be <= than the hole diameter
- just a trifle: change a function name to fit into the naming scheme
Here is the changed dialog as it looks for me:
> [PD] hole dialog UI fixes

- src/Mod/PartDesign/Gui/TaskFeaturePick.cpp
- src/Mod/PartDesign/Gui/TaskFeaturePick.h
Small UI improvement. Allow the user to pick the sketch plane by double clicking instead of click to select followed by click on OK. 
https://forum.freecadweb.org/viewtopic.php?f=8&t=54876#p471829
Thanks to @0penBrain for solving the only real difficulty with this PR.
> PartDesign: Select sketching plane by double click in picker dialog

- src/MacAppBundle/CMakeLists.txt
That has to be considered in MacAppBundle.
- [x ] Branch rebased on latest master `git pull --rebase upstream master`
> Temporarily qt5 fixes for Apple Silicon need to disable the qtweb.

- src/Mod/Sketcher/Gui/TaskSketcherConstrains.cpp
- src/Mod/Sketcher/Gui/TaskSketcherConstrains.h
- src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
- src/Mod/Sketcher/Gui/TaskSketcherElements.h
- src/Mod/Sketcher/Gui/TaskSketcherGeneral.cpp
- src/Mod/Sketcher/Gui/TaskSketcherGeneral.h
- src/Mod/Sketcher/Gui/TaskSketcherMessages.cpp
- src/Mod/Sketcher/Gui/TaskSketcherMessages.h
- src/Mod/Sketcher/Gui/TaskSketcherSolverAdvanced.cpp
- src/Mod/Sketcher/Gui/TaskSketcherSolverAdvanced.h
Same as PR #4293, just for Sketcher
as noted in https://github.com/FreeCAD/FreeCAD/pull/4271#discussion_r554673632
the pointer to the UI should be a unique pointer.
This PR does this for all Sketcher dialogs that don't already use a unique_ptr.
> [Sketcher] make pointers to the UI std::unique_ptr

- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/PreCompiled.h
Restrict the hotspot multiplication on unix platforms to X11 (xcb platform)
---
hopefully the PreCompiled change is correct?
> Sketcher: [skip ci] fix computing of hotspot of sketcher icons on Wayland

- src/Mod/Part/App/TopoShape.cpp
- src/Mod/PartDesign/App/AppPartDesign.cpp
- src/Mod/PartDesign/App/Body.cpp
- src/Mod/PartDesign/App/Body.h
- src/Mod/PartDesign/App/CMakeLists.txt
- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/App/FeatureHelix.h
- src/Mod/PartDesign/App/FeatureSketchBased.cpp
- src/Mod/PartDesign/App/FeatureSketchBased.h
- src/Mod/PartDesign/Gui/AppPartDesignGui.cpp
- src/Mod/PartDesign/Gui/CMakeLists.txt
- src/Mod/PartDesign/Gui/Command.cpp
- src/Mod/PartDesign/Gui/Resources/PartDesign.qrc
- src/Mod/PartDesign/Gui/Resources/icons/PartDesign_Additive_Helix.svg
- src/Mod/PartDesign/Gui/Resources/icons/PartDesign_Subtractive_Helix.svg
- src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
- src/Mod/PartDesign/Gui/TaskHelixParameters.h
- src/Mod/PartDesign/Gui/TaskHelixParameters.ui
- src/Mod/PartDesign/Gui/ViewProviderHelix.cpp
- src/Mod/PartDesign/Gui/ViewProviderHelix.h
- src/Mod/PartDesign/Gui/ViewProviderSketchBased.h
- src/Mod/PartDesign/Gui/Workbench.cpp
New feature proposal for the PartDesign WB.
This feature allows for simple creation of a helical sweeps from within PartDesign.
Sample application is threads, springs, coils, augers, etc.
https://forum.freecadweb.org/viewtopic.php?f=8&t=53714
Icon discussion
https://forum.freecadweb.org/viewtopic.php?f=34&t=53820
Workflow with new tool is similar to the Revolve/Groove tool. Code is based  primarily on on the Pipe feature in PartDesign.
For additive Helix we start with a sketch (the construction line is one way to defines the axis)
We click the Additive Helix icon in the toolbar
Dialog and result:
For subractive helix we start with the stock
Followed by the sketch:
Press the icon in the toolbar:
And set up the helix
**Todo list**
**Wont fix**
- Up to face (usecase not so …
> PartDesign: New features AdditiveHelix and SubtractiveHelix

- lgtm.yml
Ref: https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
> LGTM: exclude zipios++ and kdl (orocos) libraries from analysis

- src/Mod/Arch/ArchPanel.py
Even though this is ignored per the docs[1], LGTM complains[2] about it. This commit adds the superfluous param. Note: there is precedent in ArchReference.py[3] and ArchWall.py[4].
[1] https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Draft/draftutils/translate.py#L73-L78  
[2] https://lgtm.com/projects/g/FreeCAD/FreeCAD/snapshot/17db14c9700ae65d042d3548ef07f9518a115ba4/files/src/Mod/Arch/ArchPanel.py#L32  
[3] https://github.com/FreeCAD/FreeCAD/blob/45dd1a7f608f822aaab4dc52d2308edb977a3f5a/src/Mod/Arch/ArchReference.py#L39  
[4] https://github.com/FreeCAD/FreeCAD/blob/45dd1a7f608f822aaab4dc52d2308edb977a3f5a/src/Mod/Arch/ArchWall.py#L42
> [0.19][ARCH] Arch: Fix LGTM warning of missing param for translate() in ArchPanel.py

- src/Gui/DlgPreferencesImp.cpp
- src/Gui/DlgSettingsLazyLoadedImp.cpp
This fixes three issues with the new Workbench Loader preferences panel reported by users:
* Some icons were not being properly scaled to the new 48x48 size
* Some text was being incorrectly cut off, despite fitting in the column
* The sort order of the workbenches was incorrect when external workbenches were added
---
- No tracker tickets filed
> [GUI] Fix minor issues with Workbenches preference panel

- src/Mod/TechDraw/Gui/SymbolChooser.h
- src/Mod/TechDraw/Gui/TaskLineDecor.cpp
- src/Mod/TechDraw/Gui/TaskLineDecor.h
addendum to PR #4293
(as noted in https://github.com/FreeCAD/FreeCAD/pull/4271#discussion_r554673632
the pointer to the UI should be a unique pointer.
This PR does this for remaining TD dialogs that don't already use a unique_ptr.)
> [TD] make more pointers to the UI std::unique_ptr

- src/Mod/Spreadsheet/App/Cell.cpp
- src/Mod/Spreadsheet/TestSpreadsheet.py
This commit only changes the user interaction with spreadsheet and does
not affect backwards compatibility (as valid cell expressions are
prefixed with '=' when serialized).
This fixes [#4156](https://tracker.freecadweb.org/view.php?id=4156),
which is discussed in the forum thread:
https://forum.freecadweb.org/viewtopic.php?f=3&t=39665
There has been additional logic added to handle numbers and simple
fractions without using '='.
The behaviour is what is expected by the spreadsheet test cases
and in line with how other spreadsheet software works.
The '-prefix can still be used to force number input to be handled as
as string instead.
Example of numbers and fractions handled are:
* 3
* 2mm
* 1/8
* 1mm/2
* 1/2mm
* 2/m
* 1mm/2s
More complex expressions are not handled without '=' and will be …
> [Spreadsheet] Only evaluate cell values when prefixed with '='

- src/Mod/Part/Gui/CrossSections.cpp
- src/Mod/Part/Gui/CrossSections.h
- src/Mod/Part/Gui/DlgBooleanOperation.cpp
- src/Mod/Part/Gui/DlgBooleanOperation.h
- src/Mod/Part/Gui/DlgExtrusion.cpp
- src/Mod/Part/Gui/DlgExtrusion.h
- src/Mod/Part/Gui/DlgRevolution.cpp
- src/Mod/Part/Gui/DlgRevolution.h
- src/Mod/Part/Gui/DlgSettingsGeneral.cpp
- src/Mod/Part/Gui/DlgSettingsGeneral.h
- src/Mod/Part/Gui/Mirroring.cpp
- src/Mod/Part/Gui/Mirroring.h
- src/Mod/Part/Gui/TaskAttacher.cpp
- src/Mod/Part/Gui/TaskAttacher.h
Same as PR #4293, just for Part
as noted in https://github.com/FreeCAD/FreeCAD/pull/4271#discussion_r554673632
the pointer to the UI should be a unique pointer.
This PR does this for all Part dialogs that don't already use a unique_ptr.
> [Part] make pointers to the UI std::unique_ptr

- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/App/FeatureHelix.h
Fix bug reported here:
https://forum.freecadweb.org/viewtopic.php?f=8&t=53714&p=474585#p474514
Previously the internal helix spine had a radius calculated as the minimum distance of the profile to the helix axis. When significant cone angle was selected this method sometimes causes the helix to start win the wrong place. 
Now the internal helix spine has radius calculated as the middle of the profile bounding box.
> PartDesign: [Helix] Fix helix starting point bug

- src/Mod/PartDesign/App/FeatureHelix.cpp
Fix a regression that snuck in in #4374. A special case got lost for when the helix axis is along the normal of the sketch. 
In this PR this special case is added back.
> PartDesign: fix regression in Helix introduced in #4374

- lgtm.yml
This PR corrects the exclusion of zipios, and adds several additional tags that are excluded from analysis.
* **library** is a build-in LGTM tag which now explicitly includes 3rdParty and zipios
* **template** is a built-in LGTM tag which lists code intended purely as templates. I added the first one I found, but there are others we can add over time.
* **unmaintained** is a list of the Workbenches included in our source tree that do not have a maintainer right now, so are excluded from analysis.
* **legacy** is a list of the Workbenches in our tree that are no longer updated, so are now excluded from the analysis.
I've included the exclusions that I was pretty sure about: this PR and/or commit can easily be modified to include other things that should be excluded from the analysis. The …
> Modify LGTM config to exclude legacy/unmaintained

- src/Mod/PartDesign/App/FeatureHelix.cpp
Yet another small error in Helix that unfortunately was not caught by testing. This bug caused a false "self intersecting" error message.
> PartDesign: Fix sign error in Helix

- src/Mod/Mesh/App/AppMeshPy.cpp
- src/Mod/Mesh/App/Exporter.cpp
- src/Mod/Mesh/App/Exporter.h
Fixing problem reported https://forum.freecadweb.org/viewtopic.php?f=3&t=53405
The patch uses the API `DocumentObject::getSubObjects()` to enumerate group children, `DocumentObject::getSubObject()` to obtain `ComplexGeoData` with accumulated transformation, and `DocumentObject::getLinkedObject()` for the linked object.
> Mesh: refactor mesh exporter for better support of Link and group

- src/Base/PyObjectBase.h
LGTM complains about this construct leaking memory. Commit 13927b2465 eliminated the parts of FreeCAD that throw those strings. This commit eliminates the catch block.
> LGTM: Remove catch block for plain C strings

- src/Mod/Fem/Gui/Resources/icons/FEM_ConstraintElectrostaticPotential.svg
- src/Mod/Fem/Gui/Resources/icons/FEM_EquationElectricforce.svg
This fixes these warnings that are printed to the log window when FEM WB is loaded
```
<input>:66:16: Could not add child element to parent element because the types are incorrect.
<input>:78:369: Could not add child element to parent element because the types are incorrect.
<input>:78:462: Could not add child element to parent element because the types are incorrect.
```
https://forum.freecadweb.org/viewtopic.php?t=44423
Fix involved opening the icons in Inkscape, converted the text to a path, and saved.
> FEM: Fix svg icons that causes warning messages

- src/Mod/Mesh/App/MeshProperties.cpp
LGTM warns on this allocation because it can't find a deallocation in the same class. It's a reference-counted object that may be held in Python code even after the C++ class instance is destroyed, the lack of deallocation is correct (at least, according to the comment in this class's destructor!).
> LGTM: Silence incorrect LGTM warning

- src/Mod/Mesh/App/Core/MeshIO.cpp
When specifying per-vertex colors in an Asymptote surface, the loop currently has an off-by-one error in its comma-insertion logic. As currently written, the conditional is never false. This commit corrects the output, removing the extra comma after the third RGB triplet. Asymptote documentation can be found here: https://asymptote.sourceforge.io/asymptote.pdf.
Found via LGTM.
---
- No tracker ticket filed.
> LGTM: Remove extra comma in Asymptote surface color definition

- src/Mod/Mesh/Gui/Command.cpp
- src/Mod/Mesh/Gui/Resources/Mesh.qrc
- src/Mod/Mesh/Gui/Resources/icons/Mesh_SplitComponents.svg
Mesh SplitComponents command does not have icon for the FreeCAD UI (Menu Meshes).
This commit adds a SVG file with icon for this command. Also, it makes the necessary changes on Command.cpp and Mesh.qrc files.
The new SVG icon follows the FreeCAD Artwork Guidelines and was saved as Plain SVG format.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=47494&start=50#p464476
> [UI] Add SVG icon for Mesh SplitComponents

- src/Mod/Draft/draftguitools/gui_scale.py
See https://forum.freecadweb.org/viewtopic.php?p=331467#p330738
---
> Draft: Fixes #0004113: When Clone is used in Draft/Scale, the cloned part placement is always set to origin whatever is the reference point

- src/Mod/Draft/draftfunctions/svg.py
- src/Mod/Draft/drafttests/test_svg.py
An AttributeError is raised when `direction=Vector(0,0,0)` and obj is an Arch::Space on line: https://github.com/FreeCAD/FreeCAD/blob/bead9bb9381d039d6dda438b07e30dace7cf33ae/src/Mod/Draft/draftfunctions/svg.py#L799
This patch checks early on if the direction vector is a zero vector and raises a ValueError with a description of what has gone wrong.
A caveat with this solution is that this new behaviour might break old code which depends on that invalid directions can be used.
Forum thread is here: https://forum.freecadweb.org/viewtopic.php?f=23&t=55006
(Found with Coverity)
---
-  ~Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated …
> [0.19] [Draft] Add better error message in get_svg for direction

- src/Mod/Part/App/TopoShapeSolidPyImp.cpp
This conditional always evaluates to true if the previous two branches are false, so the condition is redundant. Commented out rather than removed for documentation purposes.
---
> LGTM: Remove superfluous conditional

- src/Mod/Path/PathScripts/PathOpGui.py
This is a small change to hide an op by default, make it visible while it is being edited and restore the previous visibility afterwards. Typically the generated Path of the op is still visible through the visibility of the Job object.
The reason for this change is the many confusion and annoyance the double display of an op's path causes for users, especially newer users.
> [Path]: Set operation Visibility to False, and turn it back on while editing.

- src/Mod/PartDesign/Gui/TaskChamferParameters.cpp
- src/Mod/PartDesign/Gui/TaskDraftParameters.cpp
- src/Mod/PartDesign/Gui/TaskFilletParameters.cpp
- src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
- src/Mod/PartDesign/Gui/TaskThicknessParameters.cpp
In some PartDesign task dialogs, the destructors call functions that may throw exceptions. If that occurs and the exception is uncaught, this will ususally end up terminating the program. This commit adds try-catch blocks around each instance of that (identified by Coverity) and handles the Python exception in the normal reporting workflow.
---
> [PD] Catch Python exceptions in dtors (Coverity)

- src/Mod/Arch/Resources/ui/ArchSchedule.ui
This PR updates reference to an older version of LibreOffice (5.x) UI path with the latest one (6.x). This was 1st brough to attention by translators on crowdin. Ref: https://crowdin.com/translate/freecad/6766/en-en?filter=basic&value=0#6576778
---
> Arch: update tooltip reference to LibreOffice version within ArchSchedule

- lgtm.yml
Remove PyCXX from LGTM's analysis.
---
- Minor change.
- No ticket.
> LGTM: Don't check PyCXX

- src/Mod/Mesh/App/Core/Grid.cpp
LGTM complains if this calculation is done from inside the `sqrt()` call because it sees multiplication of two floats and assumes that `sqrt()` is intended to take a double, thus resulting in a potential overflow of the float before the cast to double by `sqrt()`. By performing the multiplication separately and assigning it to a float, it should be clear both to the analyzer and to future readers that no conversion to double is expected.
---
> LGTM: Eliminate float-to-double overflow warning

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/App/FeatureHole.h
The `angle` variable was not being initialized in any of the constructors for the `CutDimensionSet`, and nothing was being initialized by the default constructor. This commit adds `angle` as an optional final argument to the parameterized constructors, defaulting to 0.0, and adds default values to the default constructor using the first of each enum and 0.0 for the angle. The default constructor is required elsewhere in the code so cannot be trivially removed. Issue identified by Coverity.
---
> [PD] Add missing CutDimensionSet constructor variable initialization (Coverity)

- src/Gui/ViewProviderLink.cpp
- src/Mod/Part/Gui/DlgProjectionOnSurface.cpp
- src/Mod/Part/Gui/TaskCheckGeometry.cpp
- src/Mod/Part/Gui/TaskDimension.cpp
Catch and report exceptions in destructors to prevent them from propagating out. Found via Coverity.
---
- Small fix
- No ticket
> [Part] Coverity: dtors can't throw

- src/Mod/Sketcher/App/SketchObject.cpp
This issue is harmless as the field is always written to before it is read. So this will never cause an issue with the current implementation.
Fixes Coverity issue:
CID 316539 (1 of 1): Uninitialized scalar field (UNINIT_CTOR)
uninit_member: Non-static class member lastHasPartialRedundancies is not initialized in this constructor nor in any functions that it calls.
---
-  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` …
> [0.19] Sketcher: Fix uninitialized scalar field in ctor

- src/App/FreeCADInit.py
LGTM flagged several redundant imports, which this commit removes. It also flagged a superfluous `else` clause in a `for` loop: the loop contains `return`s, not `break`s, so the `else` clause is _always_ hit if the loop runs to completion. The `else` can be removed entirely, leaving just the code it executed at the termination of the loop.
---
- Small fix
- No ticket
> LGTM: Minor fixes to FreeCADApp.py

- src/Mod/OpenSCAD/OpenSCADCommands.py
- src/Mod/OpenSCAD/Resources/OpenSCAD.qrc
- src/Mod/OpenSCAD/Resources/icons/OpenSCAD_Edgestofaces.svg
- src/Mod/OpenSCAD/Resources/icons/OpenSCAD_ExpandPlacements.svg
- src/Mod/OpenSCAD/Resources/icons/OpenSCAD_ResizeMeshFeature.svg
Two OpenSCAD commands have the same icons and one does not have: OpenSCAD Edgestofaces, OpenSCAD ExpandPlacements, OpenSCAD ResizeMeshFeature.
This commit provides the SVG files with new icons for these commands. Also, it makes the necessary changes on OpenSCADCommands.py and OpenSCAD.qrc files.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=54040
> [UI] Replacement of 3 SVG icons for OpenSCAD commands

- src/App/Document.cpp
LGTM points out that the construct use in the loop here "does nothing" -- that is, it is a conditional whose result is never used. It is apparently being used simply to ensure that the next() function is called on each loop iteration, but because sequence may be null, it is shoehorned into a trinary :? operator. To clarify the intent and ensure that later readers (including LGTM) do not misunderstand it, this code is broken out into a more standard conditional construct at the end of each loop iteration.
---
> LGTM: Move seq->next out of loop control

- src/Mod/Path/PathScripts/PathToolBit.py
lgtm.com showed unused imports in PathToolBit.py.  This patch removes them.  The tests in TestPathApp still pass.
> Path: Removes unused imports from PathToolBit.py

- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py
**Before this PR:**
Even when Gmsh is not installed, everything looks fine:
**After PR:**
Also ensure that any unexpected exception is also shown in the Gmsh dialog log
> FEM: Improve Gmsh log, when Gmsh is not installed

- src/Mod/PartDesign/Gui/ViewProviderHelix.cpp
- src/Mod/PartDesign/Gui/ViewProviderLoft.cpp
- src/Mod/PartDesign/Gui/ViewProviderPipe.cpp
- src/Mod/PartDesign/Gui/ViewProviderPrimitive.cpp
This fixes some cases that were missed in commit 2834075d6abcd36b9e
> [0.19] PartDesign: Fix outdated icon filenames

- src/Mod/Mesh/App/Core/TopoAlgorithm.cpp
The function `SplitFacet()` appears to be unused (it has a "FIXME: Implement" note at the top), but LGTM has identified a reasonably clear error in it, which this commit resolves in the interest of making someone's life easier in the future (and shutting LGTM up). In calculations of a minimum distance, the variable `minDist` is initialized to `FLOAT_MAX`, and then later is compared to see if it is _less than_ some other value, which cannot ever be true. The sense of the comparison has been reversed.
Found via LGTM.
---
- No tracker ticket filed.
> [0.19] [Mesh] LGTM: Correct minimum distance calculation in SplitFacet

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/InitGui.py
- src/Mod/AddonManager/addonmanager_workers.py
Removes all the unused imports in the AddonManager module as flagged by LGTM.
---
> AddonManager: removes unused imports

- src/Mod/Path/PathScripts/PathAdaptive.py
- src/Mod/Path/PathScripts/PathAdaptiveGui.py
This PR isolates the addition of the `UseOutline` feature to the Adaptive operation at found in PR #4324 .  The feature is cloned from PocketShape.
I recommend consideration of PR #4345 as a possible chaser.  It adds a simple Adaptive test framework to the Path workbench test suite and is already coded for testing this `UseOutline` feature.
---
> [0.19] [Path] Add `UseOutline` feature to Adaptive op [1 of 3 per dev conversation]

- src/Mod/Path/PathScripts/PathGeom.py
- src/Mod/Path/PathTests/TestPathGeom.py
The segmentation algorithm for arbitrary edges used the distance between start and end point to estimate a good value for the # segments required for the segmentation. Since the ellipse is a closed shape the distance was (nearly) 0 leading to a very, very large number of segments. Changed that faulty logic of past self to use `discretize` method - much simpler and more robust.
> [Path]: bugfix/cmdsForEdge for ellipse edge

- src/Mod/Path/PathScripts/PathGeom.py
- src/Mod/Path/PathTests/TestPathGeom.py
gitter user found error when using deburr - seems a new type of curve is not supported for flipping, which was required in this case.
> [Path]: Added support for Part.OffsetCurve to flipEdge.

- src/Mod/Arch/ArchPipe.py
Fix for ArchPipe: getProfile returned Shape instead of Wire
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=55401
> [Arch] Fix for ArchPipe: getProfile returned Shape instead of Wire

- src/Mod/PartDesign/App/FeatureHelix.cpp
The current initial proposed parameters (pitch and height) can cause self intersection if the selects a different helix axis. In this PR the diagonal of the bounding box is used, guaranteeing that the pitch and height parameters never lead to self intersecting. 
Current behavior was identified in a YouTube tutorial here: https://youtu.be/G6aPsFPGPDQ?t=68
> [0.19] PartDesign: Improve Helix parameter proposals

- src/Mod/Path/PathScripts/PathSurfaceSupport.py
fix improperly passed arguments, trigger assert() in OCL, which causes an ugly core dump.
---
> [PATH] fix conecutter core dumps #4561

- src/Mod/PartDesign/App/FeatureLoft.cpp
Previously Subtractive loft would create a shape if there is no base
object. This is because the code is shared with Additive Loft, where
that is the right thing to do. Now we check for this, and return error
if there is nothing to subtract from.
In 0.19, this behavior has already been corrected in the Helix, and the Pipe features. Therefore it is logical if it is fixed for Loft also in 0.19 so there is consistency. 
Forum:
https://forum.freecadweb.org/viewtopic.php?f=3&t=55634
> [0.19] PartDesign: Subtractive Loft. Raise error when base is null.

- src/Gui/3Dconnexion/GuiNativeEventLinux.cpp
- src/Gui/3Dconnexion/GuiNativeEventLinuxX11.cpp
This commit simply demystifies the warning that most users will see when they boot in to FreeCAD "Couldn't connect to spacenav daemon." by adding 
"Please ignore if you don't have a spacemouse."
> 3Dconnexion: Clarify ambivalent console output warning [skip ci]

- src/Mod/Path/PathScripts/PathOp.py
- src/Mod/Path/PathScripts/PathOpGui.py
currently if the base geometry of an op becomes invalid the op cannot be edited to fix the base geometry because it throws an exception during task panel initialisation which prevents the event handlers to be registered - rendering the task panel mostly unresponsive (OK and Cancel still works though).
This change checks the base geometry and resets it if it is found invalid, allowing the task panel to be created successfully and let the user fix the base geometry.
> [Path]: bugfix/invalid base geometry robustness

- src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
- src/Mod/PartDesign/Gui/TaskHelixParameters.h
- src/Mod/PartDesign/Gui/TaskSketchBasedParameters.cpp
- src/Mod/PartDesign/Gui/TaskSketchBasedParameters.h
There was a bug where the base object became invisible in the preview after the select reference axis option was used. This fixes this.
Current behavior was highlighted as "slightly annoying" in a YouTube tutorial here: https://youtu.be/G6aPsFPGPDQ?t=502
> [0.19] PartDesign: Fix preview bug in Helix

- src/Mod/TechDraw/Templates/A0_Landscape_ISO7200_Pep.svg
- src/Mod/TechDraw/Templates/A1_Landscape_ISO7200_Pep.svg
- src/Mod/TechDraw/Templates/A2_Landscape_ISO7200_Pep.svg
- src/Mod/TechDraw/Templates/A4_Landscape_ISO7200_Pep.svg
- src/Mod/TechDraw/Templates/A4_Portrait_ISO7200Pep.svg
Modify all of the TechDraw ISO7200_Pep templates so that the DOCUMENT_TYPE area is fully editable, allowing the user to overwrite the default contents entirely instead of just adding to it. Bug reported by mattbaker.digital in https://forum.freecadweb.org/viewtopic.php?f=3&t=55652
---
> [0.19] [TD] Fix error in editable status of DOCUMENT_TYPE

- src/Mod/Arch/ArchRoof.py
The check if a relative profile in turn references a relative profile has been improved. Added: run or angle of profilRel must be zero.
> [Arch] ArchRoof: Improved compatibility fix

- src/Mod/PartDesign/Gui/Utils.cpp
As reported by @donovaly , if you try to move a pipe that does not have an auxiliary spine, the code segfaults. This commit adds a check to ensure that not only does the property exist (which in this case it always does), but also that it does not contain a null. That is a valid value for the property to have, but cannot be itself interrogated for moveability by the `isFeatureMovable` recursive call. This fix is also applied to the other similar conditions in that function to ensure they never yield the same segmentation fault.
Forums topic: https://forum.freecadweb.org/viewtopic.php?p=479388#p479388
---
> [0.19] [PD] [Crash] Fix isFeatureMovable() to check null status of property

- src/Gui/VectorListEditor.cpp
VectorListEditor allows row-by-row creation of a list of three-component vector values. Values are manipulated using spinboxes. The previous behavior was that the spinboxes only affected the existing rows: when creating a row the contents of the spinboxes were ignored. This commit modifies that behavior so that a new row gets the contents of the spinboxes. In addition, in the original code the "Accept" button was enabled even when there was no row to edit, making it unclear whether a user needed to click the add row button or the accept button. Clicking the accept button did nothing if there was no existing row, and if compiled in debug mode, an assertion was raised.
---
- No ticket
> [GUI] Modify behavior of VectorListEditor

- src/Mod/Fem/Gui/Resources/icons/FEM_ConstraintElectrostaticPotential.svg
- src/Mod/Fem/Gui/Resources/icons/FEM_ConstraintFlowVelocity.svg
- src/Mod/Fem/Gui/Resources/icons/FEM_ConstraintInitialFlowVelocity.svg
Three FEM WB icons do not follow the FC art guide lines and they do not look good with dark themes.
FEM ConstraintElectrostaticPotential
FEM ConstraintFlowVelocity
FEM ConstraintInitialFlowVelocity
This commit replaces SVG files with new icon designs. The new SVG icons follow the FreeCAD Artwork Guidelines and were saved as Plain SVG format.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=55426
> [UI] 0.19 Replace 3 FEM WB icons

- src/Mod/PartDesign/App/FeatureAddSub.cpp
In attached model, the refine=true will cause a surface to fail, and the resulting model is no longer a solid, and since there is no check the user will have a broken model without any error notification.
[refine.zip](https://github.com/FreeCAD/FreeCAD/files/6001495/refine.zip)
In this PR we introduce a check in refine, and fall back to the old shape if required. 
Question: Should we issue a warning as well?
Forum thread:
https://forum.freecadweb.org/viewtopic.php?f=8&t=53714&start=80#p479421
This also partially fixes this issue:
https://forum.freecadweb.org/viewtopic.php?f=3&t=55583
> [0.19] PartDesign: Check closedness in AddSub refine function

- src/Gui/ExpressionCompleter.cpp
- src/Gui/ExpressionCompleter.h
- src/Mod/Spreadsheet/Gui/LineEdit.cpp
I consider this to be a bug fix since the current behaviour will just confuse people.
I think it will be easier to review this change when it's just one PR even though it touches both Spreadsheet and Gui.
I can split it if needed.
After pull request #4215 it doesn't make much sense helping the user to write expressions without leading '=', as that content will be parsed as a string and not as an expression as it was before.
This change adjusts the behaviour in SpreadsheetGui's LineEdit to avoid popping up the ExpressionCompleter when no leading equal sign is used.
Some cleaning has also been preformed on the code as a separate commit.
---
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which …
> [0.19] Spreadsheet: Don't autocomplete when writing strings in cells

- src/Mod/Mesh/Gui/Workbench.cpp
Mesh WB toolbar displays only a few icon commands.
This commit add more commands of the Mesh workbench to the toolbar. Additionally, it arranges these tools in 6 groups (following the current Mesh_Tool_Navi arrangement of the wiki). 
Forum discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=47494&start=60#p475594
> [UI] Add commands to Mesh WB toolbar

- src/Mod/Path/PathScripts/PathToolBitLibraryGui.py
The currently exported tool table for LinuxCNC results in the following warning:
"Requested tool 1 not found in the tool table"
The debug output provides:
"File: default_tool_table.tbl Unrecognized line skipped: \
T1 P X0 Y0 Z0 A0 B0 C0 U0 V0 W0 D4.00 I0 J0 Q0;      \
4mm_2F_Compression_Carbide_Endmill"
This is due to a missing/blank P (pocket) entry.
Signed-off-by: Lee Jones <lee.jones@linaro.org>
> PathToolBitLibraryGui: Fix LinuxCNC tool table format

- src/Mod/Part/Gui/DlgPrimitives.cpp
For FC 0.19 we added bindings to the PD primitives but we forgot the Part primitives
I think this is trivial enough to go in for 0.19 and it improves the usability.
For the future also the primitive location parameters should be bound (reported as bug https://tracker.freecadweb.org/view.php?id=4573).
> [0.19] [Part] add missing bindings

- src/Mod/Part/Gui/Location.ui
For some reason the horizontal alignment got broken. This PR replaces the different grids with each on grid per groupbox
Until December die dialog looked like this: https://wiki.freecadweb.org/images/6/63/Part_Placement-primitive-dialog.png
With current master it looks like this for me:
I cannot see a change that caused this other than that I compile meanwhile using Qt 5.15.
However with the fix it looks correct again:
> [0.19] [Part] fix regression in location dialog layout

- src/Mod/TechDraw/App/DrawViewDimension.cpp
These 3 lines fix a regression in TechDraw, reported in [FreeCAD forum](https://forum.freecadweb.org/viewtopic.php?f=35&t=55864).  It'd quite nice to get this fix still into v0.19, as it affects correct loading of v0.18 TechDraw files.  The problem was that Arbitrary labels for Dimensions were not correctly printed, if "Equal Tolerance=true", which it defaults to.
And please remember to update the Wiki with the features added or changed …
> [TD] [v0.19] Hotfix for Dimension label Arbitrary value regression in DrawViewDimension.cpp

- src/Mod/PartDesign/Gui/Resources/translations/PartDesign.ts
Uncertain to why but lupdate is not removing obsolete strings from `PartDesign.ts`. This PR manually removes obsoletes strings from it.
ref:
https://crowdin.com/translate/freecad/564/en-de?filter=basic&value=0#6500474
https://crowdin.com/translate/freecad/564/en-en?filter=basic&value=0#6500475
> Crowdin: removing obsolete strings from PartDesign.ts [skip ci]

- src/Mod/TechDraw/App/DrawViewPart.cpp
These few lines fix a crash in TechDraw, reported in [FreeCAD forum](https://forum.freecadweb.org/viewtopic.php?f=8&t=55973).  It'd quite nice to get this fix still into v0.19, as it fixes a hard crash. …
> [TD] [v0.19] DrawViewPart.cpp: Fix a crash when user sets the PropertyVector Direction to zero

- src/Mod/OpenSCAD/importCSG.py
When importing OpenSCAD models, colors sometimes disappear, especially when using for loops and dxf imported polygons with linear extrude.
This commit fixes that, I don't know if its the best way, but basically it saves every set color, then loops over all groups, and if a group member doesn't have any set colors yet, it will change the color to the groups, then it hides the group the prevent single faces having the wrong colors.
Demo files are available in this [gist](https://gist.github.com/helaslo/074259a2c7b6d0b0f89025080dfc33a9)
Here it is how they shall render according to OpenSCAD
Here it is how they render with the latest version of FreeCAD
And here it is how they render with the patches applied
> [OpenSCAD] Fix colors not working correctly when polygons are extruded

- src/Mod/PartDesign/App/FeatureTransformed.cpp
Other PD commands have the refine property listed under the "Part Design" category in the property viewer. Rather silly, Transformed lists Refine under Sketchbased. Even though Transformed does not even inherit from Sketchbased. 
This fixes this minor issue.
> PartDesign: Transformed. Fix "property category" of Refine

- src/Mod/PartDesign/fcgear/fcgear.py
- src/Mod/PartDesign/fcgear/fcgeardialog.py
- src/Mod/PartDesign/fcgear/involute.py
- src/Mod/PartDesign/fcgear/svggear.py
LGTM has identified a number of minor issues with the FCGear Part Design script, used for the 2D involute gear creation (and not to be confused with the Workbench of the same name). This commit addresses each of the identified issues, and also corrects two minor spelling errors in the dialog. That dialog does not appear to be used in the base FreeCAD code, and none of the errors or their fixes are expected to result in changes to the functionality of the scripts.
---
> [PD] Fix minor static analysis issues in FCGear

- src/Mod/Part/AttachmentEditor/TaskAttachmentEditor.py
If the import of TempoVis fails, TaskAttachmentEditor creates s dummy function to replace the real TempoVis function. That function's signature did not match the real TempoVis. Caught by LGTM.
---
> [Part] Fix signature of TempoVis dummy function

- src/Tools/fcbt/CreateModule.py
- src/Tools/fcbt/CreatePyModule.py
- src/Tools/fcbt/DistBin.py
- src/Tools/fcbt/DistSetup.py
- src/Tools/fcbt/DistSrc.py
- src/Tools/fcbt/DistTools.py
- src/Tools/fcbt/FileTools.py
Static analysis showed some unused variables and imports, and running the code in Python 3.9 revealed a few invalid escapes (previous versions of Python silently "fixed" these, so the code change here will not affect the results).
Many of the unused variables followed the same sequence (things like getting the path separator in every function): it's not clear to me if it would have been more appropriate to comment them out instead, if they had some use that was not clear from the code.
---
> [FCBT] Clean up various LGTM-flagged items

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/App/FeatureHole.h
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.h
- src/Mod/PartDesign/Gui/TaskHoleParameters.ui
This PR adds possibility to make true threaded holes  with the Hole feature (possible to e.g 3D print). 
https://forum.freecadweb.org/viewtopic.php?f=34&t=54240
It should work for all supported thread types
Todo
> [0.20] PartDesign: Add true threads to the Hole feature

- LibraryVersions.h.cmake
- src/Gui/Splashscreen.cpp
There was a "FIXME" in Splashscreen.cpp suggesting that we should include other library version information in LibraryVersions.h -- this implements that suggestion. Not all libraries are supported right now: several don't have version information available to CMake, though it's possible that is due to our older CMake facilities which could be updated.
---
> [GUI] Add library versions to LibraryVersions.h

- src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.cpp
- fixes regression bug 4581
See the first issue reported here:
https://forum.freecadweb.org/viewtopic.php?f=3&t=56093#p482553
- also fix issue that one could set 1 occurrence for polar patterns despite 2 are required at least
- also fix potential dereferencing null pointer (reported by MSVC)
When this goes in, it should also go in for FC 0.19.1
> [PD] fix multi-transform view

- src/Mod/PartDesign/App/FeatureDraft.cpp
using e.g. 89.999 as angle works. It might not be useful in real life, but the 89.99 seem arbitrary.
> [PD] attempt to use more reasonable angle limit for drafts

- src/Mod/PartDesign/App/FeatureChamfer.cpp
- src/Mod/PartDesign/App/FeatureChamfer.h
- src/Mod/PartDesign/App/FeaturePolarPattern.cpp
- src/Mod/PartDesign/App/FeaturePolarPattern.h
the MSVC IDE warned me about different floatAngle definitions in PD
> [PD] make constraints static class member

- src/Mod/PartDesign/App/FeatureHole.cpp
Path for user-defined hole-cut-types now is UserAppDataDir()/PartDesign/Hole.
see: https://forum.freecadweb.org/viewtopic.php?f=19&t=51403&start=20#p482574
---
> [PD] fixes problem with the path for user-defined hole-cut-types

- src/Gui/Splashscreen.cpp
As suggested by FreeCAD forums member neildarlow, this modifies the wording of the Credits screen to use the words "Individuals" and "Organizations". It also exposes the three necessary strings to translation (omitting any formatting marks).
See discussion: https://forum.freecadweb.org/viewtopic.php?f=21&t=56233
---
> [GUI] Tweak wording and translatability of Credits

- src/Mod/Sketcher/Gui/Resources/icons/constraints/Constraint_Block.svg
The existing icon for the sketcher constraint for "constraint block" is easily confused with the icon for the diameter constraint. A small modification to add a 2nd cross bar will visually distinguish it (especially at smaller icon sizes).
> Gui: Update icon for Sketcher Constraint Block

- src/Mod/PartDesign/App/FeatureHelix.cpp
All other PD features use a step size of 1.0 for angles.
(Personally also for me a step of 5 is not convenient)
@davidosterberg , OK for you as well?
> [PD] use same helix angle step as for other features

- src/Mod/Draft/draftguitools/gui_edit.py
- src/Mod/Draft/draftguitools/gui_edit_draft_objects.py
LGTM identified an instance where a function was defined twice: in this case, one version was intended to take a list of items and the second version just a single item. Because they share the same name and number of arguments, the second definition overrode the first. This causes no problems in the current code because the version that takes a list is never used. However, for consistency with the analogous `globalize_vectors` and `globalize_vector` functions, the `localize*` versions are changed to match that pattern. All calls are converted to the singular use.
---
> [Draft] Fix localize_vectors double definition

- src/Tools/updatets.py
The regular expressions that are used to remove the Python directories from the list of Mods was accidentally catching PartDesign in its regex for Part. This one-character patch forces the regex to be at the end of the line.
> Fix regex in translation extraction script

- src/App/Expression.cpp
- src/App/Expression.h
- src/App/ExpressionParser.h
- src/App/PreCompiled.h
- src/Gui/ExpressionCompleter.cpp
- src/Gui/PreCompiled.h
- src/Mod/Part/App/PreCompiled.h
- src/Mod/Part/Gui/TaskCheckGeometry.cpp
- src/Mod/Part/Gui/TaskCheckGeometry.h
std::tuple was introduced in c++11 from boost.
This removes yet another boost dependency
---
-  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`
And please remember to update the Wiki with the …
> Replace boost::tuple with std::tuple

- src/App/Application.cpp
Just a few Python checks here, plus removed no-longer-necessary Boost dependencies.
---
---
> [Base] Remove deprecated Application.cpp code for 0.20

- src/Gui/Application.cpp
The first commit removes any code that was `#ifdef`-protected and required Qt <5.9 or Python<3.6. The second migrates from `boost::bind` to `std::bind`.
Note that one of the `#ifdef`s referred to Qt 5.10, but this was actually a mistake, and should have referred to Qt 5.1 -- it was a minor issue related to an anti-aliasing feature.
---
> [GUI] Update GUI Application.cpp for 0.20

- cMake/FreeCAD_Helpers/SetupPython.cmake
I missed a backwards-compatibility variable in the code handling CMake >=3.12 Python executables. This adds it.
---
> [CMake] Add missing backwards-compatibility var

- cMake/FindPySide2Tools.cmake
resolves #0004588  
ticket: https://tracker.freecadweb.org/view.php?id=4588
> CMake: correct non-POSIX friendly 'sed-i' arg in FindPySide2Tools.cmake

- src/Mod/PartDesign/App/FeatureHole.cpp
With PR #4274, the hole feature can be very slow if thread modeling is enabled for a large hole pattern. 
This PR contains some performance optimization. With debug build the performance improvement is about 30%. 
  | Build type | Debug |   |  
-- | -- | -- | -- | --
  | Test case | Hole pattern 6 x M10x25 |   |  
  |   |   |   |  
Commit | Variant | time (average of 10) |   | Improvement
db9525e7d7 | Original Hole | 3,1325 | s | 0,00 %
6f63b105da | Compound then cut | 2,22 | s | 29,13 %
354ab5528 | remove unused code | 2,19 | s | 30,09 %
A note about changes in behavior.
Previously it was posssible for the holes to overlap each other. Now this is no-longer supported as this would be more computationally demanding. If it is seen as needed to support overlapping holes, support for …
> [0.20] PartDesign: Hole performance improvements

- src/Mod/Web/Gui/BrowserView.cpp
The screen scale adjustment code here should not be necessary when using the Chromium-based QtWebView widget, which correctly handles logical vs. device px units. The scaling causes poor font size choice when used on ultrawide monitors, as reported in https://forum.freecadweb.org/viewtopic.php?p=485431
---
> [0.19][Web] Remove HiDPI fix when using QTWEBVIEW

- src/Mod/Draft/draftguitools/gui_snaps.py
LGTM objected to the re-use of the loop variable `a` in the original algorithm. Upon closer inspection, the algorithm in this function could be modified to match the algorithm in `sync_snap_statusbar_button` (which does the same thing to the statusbar that this does to the toolbar). This change eliminates the double-use, and does not affect the functionality of the routine.
A second (purely optional) commit makes a small optimization to the two routines, returning once the requested button has been found and handled.
> [DRAFT] Refactor sync_snap_toolbar_button

- src/Mod/OpenSCAD/OpenSCADFeatures.py
- src/Mod/OpenSCAD/OpenSCADTest/app/test_importCSG.py
- src/Mod/OpenSCAD/importCSG.py
OpenSCAD's linear_extrude function accepts both a twist angle and a scale parameter -- prior to this commit the scale was unimplemented. This adds it by repurposing the twist code and making a small modification to include the closing section in the pipe creation, and scaling that section. This commit includes a unit test to identify future regressions. 
---
> [OpenSCAD] Add scale parameter to linear_extrude

- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathPost.py
if output is split by operation spindle should restart when next file is loaded
---
> [PATH] Fix bug with spindle not restarting

- src/Mod/Path/PathScripts/PathPocketShape.py
Forum mention at [Many (238) Pockets](https://forum.freecadweb.org/viewtopic.php?f=15&t=56040&start=10#p482382).
---
> [Path] PocketShape: Remove 'verify final depth' warning

- src/Gui/Stylesheets/Behave-dark.qss
---
Most input boxes were blending in some dialogs since not all dialogs use the same backgrounds. The preferences dialog for example has various hue overlays depending …
> [Stylesheet] Increase behave-dark contrast on input boxes

- src/Mod/Material/FluidMaterial/Air.FCMat
- also adjust values slightly according to various sources
Since a factor 1000 is a big mistake and air is the most common gas, please commit this also for FC 0.19
> [FEM] fix specific heat of air

- src/Mod/Path/PathScripts/PathPocketShape.py
Identified by MLampert.  If multiple faces are selected at varying Z-heights, the `combineConnectedShapes()` method fails to connect them due to offset Z-heights.  This fix places all input faces for that method into the same working plane.
Forum discussion at [PR fixes for PocketShape: 4615, 4617](https://forum.freecadweb.org/viewtopic.php?f=15&t=56667).  This is a simple bug fix and was identified in Gitter chat.
And please remember to …
> [Path] Fix connected multi-face clearing bug

- src/Mod/Fem/Gui/Resources/ui/MeshGmsh.ui
- src/Mod/Fem/femobjects/mesh_gmsh.py
- src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py
- also set default to 1st order mesh
The PR is with the code from user johnwang: https://forum.freecadweb.org/viewtopic.php?f=18&t=55608#p454510
I just updated it to the latest master.
I change the default to 1st order since in many cases it is important to get a mesh at all. You can increase the order now quickly/directly in the dialog.
> [FEM] add GMSH mesh order setting to dialog

- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femobjects/mesh_gmsh.py
- src/Mod/Fem/femtest/data/elmer/group_mesh.geo
- Gmsh has since a while 2 new mesh algorithms
- on the other hand the two algorithms "Frontal Delaunay" and "Frontal Hex" are deprecated and not listed anymore in the docs: https://gmsh.info/doc/texinfo/gmsh.html#index-Mesh_002eAlgorithm3D
and indeed all attempts with these 2 algorithms fail
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=18&t=56971
> [FEM] add mesh algorithms

- src/Mod/Fem/Gui/Resources/ui/MeshGmsh.ui
- the property has the name "Element order" thus the dialog should use the same name to avoid confusions
- also uniform naming for the element dimension and remove the redundant "Mesh" (is already in the UI groupBox heading
> [skip ci] [FEM] fix typo

- src/Mod/Fem/femviewprovider/view_mesh_gmsh.py
it is very annoying that the mesh is hided when closing the task dialog because one often has to play with the Gmsh properties and need to see the mesh.
See also https://forum.freecadweb.org/viewtopic.php?f=18&t=56401&start=10#p489734
> [skip ci] [FEM] don't hide Gmsh mesh by default

- src/Gui/PropertyView.cpp
On Windows the lower tabs of the PropertyView were being set to triangular, which breaks stylesheets. This removes that code, so they now take on whatever the standard shape is on the system. Fixes [#0004599](https://tracker.freecadweb.org/view.php?id=4599).
---
> [GUI] Remove explicit triangle styling from tabs

- src/Mod/PartDesign/App/FeaturePad.cpp
- src/Mod/PartDesign/App/FeaturePad.h
- src/Mod/PartDesign/Gui/TaskPadParameters.cpp
- src/Mod/PartDesign/Gui/TaskPadParameters.h
- disable 2 properties when no custom direction is used
- rename a property because its name is the opposite of what it is doing
> [PD] some fixes for the new pad length feature

- src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_BSplineDecreaseDegree.svg
- src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_BSplineDecreaseKnotMultiplicity.svg
- src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_BSplineDegree.svg
- src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_BSplineIncreaseDegree.svg
- src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_BSplineIncreaseKnotMultiplicity.svg
- src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_BSplineKnotMultiplicity.svg
Some icons of Sketcher WB are too similar and under small resolution are difficult to identify. A design improvement was requested.
Sketcher_BSplineDegree
Sketcher_BSplineKnotMultiplicity
Sketcher_BSplineDecreaseDegree
Sketcher_BSplineDecreaseKnotMultiplicity
Sketcher_BSplineIncreaseDegree
Sketcher_BSplineIncreaseKnotMultiplicity
This commit replaces SVG files with new icons for these commands.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=56468&sid=697c86a2dfb2cfd944bc8ab91d5c43d8
> [UI] Replace SVG icons for Sketcher commands

- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAnnotationImp.h
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawColorsImp.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawColorsImp.h
- src/Mod/TechDraw/Gui/TaskDimension.cpp
- src/Mod/TechDraw/Gui/TaskHatch.cpp
- src/Mod/TechDraw/Gui/TaskHatch.h
All other source files are either plain ascii or utf-8, this converts the last few iso-8859 files to utf-8.
---
> TechDraw: convert source files from iso-8859 to utf-8

- src/Mod/Part/Gui/Workbench.cpp
at the moment the sorting is confusing, the sorting in the menu differs from the toolbars and some features even belong in the menu to another category than in the toolbars and one feature has not yet a toolbar entry
This PR implements a uniform sorting for the menu and toolbar and adds the missing toolbar icon
> [Part] uniform feature sorting

- src/Mod/Part/Gui/Resources/icons/tools/Part_MakeFace.svg
The other Part icons have red lines indicating wires, only the new make faces ion does not. The PR changes this to use the same for all icons.
> [Part] change icon to math the other Part icon scheme

- src/Mod/OpenSCAD/OpenSCADTest/app/test_importCSG.py
- src/Mod/OpenSCAD/importCSG.py
The resize code must recompute some kinds of objects prior to requesting their bounding box, or the bounding box can be invalid.
---
> [OpenSCAD] Fix bug in resize code

- src/Mod/OpenSCAD/OpenSCADFeatures.py
- src/Mod/OpenSCAD/OpenSCADTest/app/test_importCSG.py
In `linear_extrude()`, modify the auxiliary spine to be a true helix, resulting in a much smoother extrusion when a twist angle is applied. This also corrects a bug in the scaling during linear extrusion, where non-uniform scaling was not handled correctly.
Several unit tests are modified to use an analytical volume calculation for comparison, and unit tests are added for simple (slice) projections.
Finally, a few minor PEP8 changes were applied.
---
> [OpenSCAD] Improve helical extrusion, fix scaling

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/Resources/ui/preferences-draftinterface.ui
- src/Mod/Draft/draftguitools/gui_base_original.py
- src/Mod/Draft/draftguitools/gui_beziers.py
- src/Mod/Draft/draftguitools/gui_dimensions.py
- src/Mod/Draft/draftguitools/gui_ellipses.py
- src/Mod/Draft/draftguitools/gui_lines.py
- src/Mod/Draft/draftguitools/gui_mirror.py
- src/Mod/Draft/draftguitools/gui_move.py
- src/Mod/Draft/draftguitools/gui_points.py
- src/Mod/Draft/draftguitools/gui_polygons.py
- src/Mod/Draft/draftguitools/gui_rectangles.py
- src/Mod/Draft/draftguitools/gui_rotate.py
- src/Mod/Draft/draftguitools/gui_scale.py
- src/Mod/Draft/draftguitools/gui_shapestrings.py
- src/Mod/Draft/draftguitools/gui_splines.py
- src/Mod/Draft/draftguitools/gui_stretch.py
Fixes [#0004108- Coordinate input not always relative to current working plane](https://tracker.freecadweb.org/view.php?id=4108)
A global mode is added for entering point coordinates in functions that use pointUi method.
The possible working modes are the following four (4):
Coordinates referred to the coordinate system of the work plane (Local x, y, z) with the possibility of reference relative to the last entered point (Local Δx, Δy, Δz).
Coordinates referred to the global coordinate system (Global x, y, z) with the possibility of relative reference to the last point entered (Global Δx, Δy, Δz).
Some code style changes are also made.
The first commit is to use the specific icons of each Draft function in the taskbar. 
And please remember to update the Wiki with the features added or …
> [0.20] [Draft] Add global mode to enter points - Fixes #0004108

- src/Mod/AddonManager/addonmanager_workers.py
If a non-github repository is added to the addon manager, the intention was to use the markdown library to render the README.md if available; otherwise it reverts to displaying it in plain text. (See the discussion in https://github.com/FreeCAD/FreeCAD/pull/3868 )
However it seems that during a reformatting in commit dde64d4a0a4db04804297ee539b461bf7f01151f  this logic was inadvertently reversed, and now it tries to use the markdown library only if it was not found. This is fixed in this pull request.
> AddonManager: Fixed minor logic glitch affecting non-github addons

- src/Mod/Draft/importDXF.py
Bug reported by forums member tarrox -- the importDXF code assumes the existence of the GUI, but does not actually need it (a `FreeCAD.GuiUp` check suffices to protect the one line of code that was using the view provider).
---
> [Draft] Eliminate required GUI for importDXF

- src/Mod/Draft/drafttaskpanels/task_scale.py
When entering a scale factor, if uniform scaling is on, the current code keeps appending zeroes as you type, forcing you to delete them before entering your next digit. This commit fixes that by ensuring that the widget that you are currently editing is not updated continuously.
Fixes [#0004601](https://tracker.freecadweb.org/view.php?id=4601).
---
> [Draft] Fix bug in data entry on scale w/ uniform scaling on

- src/Mod/Draft/draftviewproviders/view_base.py
The "Transform" and "Set Colors..." context menu items did not work on most Draft objects because the base Draft View Provider has a `setEdit()` function, which overrides any edit action provided at a higher level (e.g. by Part). This commit checks the mode of the edit, and if it is not zero, behaves as though the `setEdit()` function does not exist, allowing Part to provide the required context menu behavior. This can be overridden by subclasses if needed.
---
> [Draft] Enable Transform context menu item

- src/Mod/Arch/importWebGL.py
Fix the "View Top" and "View Front" buttons on pages generated with the WebGL exporter to select the same views as the FreeCAD Navigation Cube.
Prior to this change, "View Top" was showing the back and "View Front" was showing the top of the model, as mentioned in the forum thread at https://forum.freecadweb.org/viewtopic.php?f=23&t=56755
> Fix camera position buttons in WebGL export

- src/Mod/Fem/femexamples/elmer_nonguitutorial01_eigenvalue_of_elastic_beam.py
- src/Mod/Fem/femtaskpanels/task_material_common.py
- src/Mod/PartDesign/App/FeatureHole.cpp
Found via
```
codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,apoints,ba,beginn,behaviour,bloaded,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,ist,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oder,orgin,orginx,orginy,ot,pard,pres,programm,que,recurrance,rougly,seperator,serie,sinc,strack,substraction,te,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./src/Mod/Robot/App/kdl_cp,./ …
```
> Fixed misc. typos [skip ci]

- src/Mod/Arch/Dice3DS/dom3ds.py
LGTM identified a few minor issues in the Dice3DS code -- none of them appear to be real errors, so the changes here should not affect the behavior of the code. (Note that it appears that this library is no longer maintained outside of FreeCAD, so I'm treating it like it's part of our codebase, rather than as a 3rd party library -- we could also choose to exclude it from analysis, if that's preferred).
---
> [Arch] LGTM issues in Dice3DS

- src/Mod/Part/App/Part2DObject.h
- src/Mod/Path/PathScripts/post/uccnc_post.py
- src/Mod/Sketcher/App/SketchObject.h
Found via  codespell v2.1.dev0
```
codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,apoints,ba,beginn,behaviour,bloaded,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,ist,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oder,orgin,orginx,orginy,ot,pard,parms,pres,programm,que,recurrance,rougly,seperator,serie,sinc,strack,substraction,te,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./ …
```
> fix source comment typos [skip ci]

- src/Mod/Sketcher/Gui/SketcherSettingsDisplay.ui
- all other option text use consequently lowercase letters
- also set dialog to a more sensible sensible size
- the other changes were automagically done by Qt Creator
> [Sketch] fix a typo in preferences dialog

- src/Gui/Workbench.cpp
I was wondering why we only offer this tool in the context menu. I tested and cannot see a drawback in having it also in the edit menu.
> [Gui] add Std_TransformManip to Edit menu

- src/Doc/LICENSE.html
- src/Gui/AboutApplication.ui
- src/Gui/Splashscreen.cpp
- src/Gui/Splashscreen.h
Removes old Qt code, restores the conditional inclusion of the 3Dconnexion license information, shortens the displayed hash, and links the hash to its repo.
---
> [GUI] Refactoring and cleanup of the About window

- src/WindowsInstaller/include/declarations.nsh
- src/WindowsInstaller/setup/uninstall.nsh
- fix missing removal of the *.FCStd extension for local users
- FC-specific file extensions might appear in the Windows registry. The aim of the uninstaller is to leave a clear registry without traces of FC.
> [0.19 and master] [Win installer] improve uninstalling

- src/Gui/Icons/Geofeaturegroup.svg
This PR changes the icon of the Part container.
Motivation:
The new icon makes it clear that the Part object can contain multiple objects of different type making it suitable for assemblies etc. 
Disclosure: This icon is actually the current logo for the Assembly 4 workbench. Used for this purpose with the permission of @Zolko-123 
Original forum thread:
https://forum.freecadweb.org/viewtopic.php?f=8&t=56055
Icon specific forum thread
https://forum.freecadweb.org/viewtopic.php?f=34&t=56253
> Gui: Change the Part icon

- src/Gui/Application.cpp
By default (on platforms that support it, X11 and Windows currently) QT
applies compression for high frequency events (mouse move, touch, window
resizes) to keep things smooth even when handling the event takes a
while (e.g. to calculate snapping).
However, tablet pen move events (and mouse move events synthesised from
those, which is what FreeCAD uses) are not compressed by default (to
allow maximum precision when e.g. hand-drawing curves), leading to
unacceptable slowdowns using a tablet pen.
This commit enable compression for tablet events here to solve that and
make use of a tablet just as smooth as a mouse with FreeCAD.
This can (and likely will) lead to some movement events being dropped,
but since there is no freeform curve drawing tool, that should not be
problematic (and if it is …
> Gui: Enable compression of tablet motion events

- src/Mod/Start/CMakeLists.txt
Fix bug identified by @PrzemoF -- actual fix by @sgrogan. Case error in the installation location of the Start Page test suite.
---
> [Start] Correct TestStart installation location

- src/Mod/OpenSCAD/OpenSCADFeatures.py
- src/Mod/OpenSCAD/importCSG.py
b18caba forces a full-document recompute prior to applying a matrix transformation if the part being transformed is still null after a simple object recompute.
fbd6b04 is an attempt to fix a bug reported by @wwmayer where the linear_extrude() with a rotation angle was failing with OCC 7.3. This restores a bit of the logic of the older version of the code, using a piecewise-linear approximation to the helix as the auxiliary spine. @wwmayer, please let me know if this resolves the issue for you (running the OpenSCADApp test suite should tell us) -- if not I'll install OCC 7.3 locally and do some more debugging. Thanks!
---
> [OpenSCAD] Minor bug fixes in importing CSG

- src/Mod/Draft/draftguitools/gui_edit_draft_objects.py
Currently when editing a closed wire, it tries to use the plane defined by the Shape of this object to project the edited point (which is not necessary if the object is on the WorkingPlane). This is not correctly implemented since it does not take into account the difference in coordinates between the Points attribute of the object and the Vertex of the Shape, generating the reported result in https://forum.freecadweb.org/viewtopic.php?f=23&t=56661
In addition, if the edited object is not on the WorkingPlane, the result is inconsistent with the trackers (which projects the points onto the WorkingPlane) and with the behavior of the Edit command on open wires.
The proposal is to disable these lines of code until a consistent implementation is made between closed wires, trackers and the open …
> Draft: Make Edit closed wires consistent with open wires and tracker

- src/Mod/Draft/draftviewproviders/view_array.py
- src/Mod/Draft/draftviewproviders/view_clone.py
When creating arrays of colors, the color information is often created to be the same length as some array of objects. In three instances this was achieved with a loop over that list of objects, even though the objects themselves are never used. This commit eliminates those loops and creates the required number of color instances directly.
Identified by LGTM.
---
> [Draft] Eliminate unused loop iteration variables

- src/Mod/Arch/exportIFC.py
LGTM complains about the unused variable in a loop that is really only using the variable to iterate a set number of times. This replaces that loop with a multiplication by the length of the array, eliminating the unused iteration variable and clarifying the intent of the code.
---
> [Arch] Refactor to eliminate unused variable

- src/Mod/Draft/draftguitools/gui_trimex.py
LGTM is concerned about the unused loop variable in this algorithm. While there was nothing wrong here, to eliminate the alarm the loop was removed entirely, since Python allows the use of the multiplication operator here to achieve the same effect.
---
> [DRAFT] Remove unused loop variable

- src/Mod/OpenSCAD/OpenSCADFeatures.py
- src/Mod/OpenSCAD/importCSG.py
OCCT 7.3 did not work well when using a very large projection plane, so this commit reduces the plane size to the minimum required for the cut operation. It also performs some minor refactoring in anticipation of the implementation of the true projection feature, and it removes the previous attempted fix, which proved unnecessary.
See further details in the discussion on https://github.com/FreeCAD/FreeCAD/pull/4635
---
> [OpenSCAD] Fix projection for OCCT 7.3

- src/Base/TimeInfo.cpp
- src/Base/Tools.h
- src/Base/Translate.cpp
This PR removes any code from the base module that was only included for Qt < 5.9, the current minimum required version. 
---
> [Base] Remove deprecated Qt < 5.9 code

- src/Main/FreeCADGuiPy.cpp
- src/Main/MainGui.cpp
This PR removes any code from the main module that was only included for Qt < 5.9, the current minimum required version. 
---
> [Main] Remove deprecated Qt < 5.9 code

- src/Mod/Test/Gui/UnitTestImp.cpp
This PR removes any code from the Unit Test module that was only included for Qt < 5.9, the current minimum required version. 
---
> [Test] Remove deprecated Qt < 5.9 code

- src/Mod/Spreadsheet/Gui/SheetTableView.h
- src/Mod/Spreadsheet/Gui/qtcolorpicker.cpp
This PR removes any code from the Spreadsheet module that was only included for Qt < 5.9, the current minimum required version. 
---
> [Spreadsheet] Remove deprecated Qt < 5.9 code

- src/Mod/Part/Gui/DlgFilletEdges.cpp
- src/Mod/Part/Gui/TaskCheckGeometry.cpp
This PR removes any code from the Part module that was only included for Qt < 5.9, the current minimum required version. 
---
> [Part] Remove deprecated Qt < 5.9 code

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/TaskSketcherConstrains.cpp
- src/Mod/Sketcher/Gui/TaskSketcherGeneral.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
This PR removes any code from the Sketcher module that was only included for Qt < 5.9, the current minimum required version. 
---
> [Sketcher] Remove deprecated Qt < 5.9 code

- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/Gui/Grabber3d.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.h
- src/Mod/TechDraw/Gui/QGVPage.cpp
- src/Mod/TechDraw/Gui/TaskRichAnno.cpp
- src/Mod/TechDraw/Gui/TemplateTextField.cpp
This PR removes any code from the TechDraw module that was only included for Qt < 5.9, the current minimum required version. 
NOTE: While working on this PR I ran across a bug in `MDIViewPage::printPdf(std::string file)`, around src/Mod/TechDraw/Gui/MDIViewPage.cpp line 811 in the original code. There is an unused local variable there -- I believe its scope is wrong. A fix for that seemed inappropriate to include in this PR, so I left a note there that should be revisited once this is merged.
---
> [TD] Remove deprecated Qt < 5.9 code

- src/Gui/QuantitySpinBox.cpp
- src/Gui/QuantitySpinBox_p.h
- src/Gui/SpinBox.cpp
- src/Gui/Widgets.cpp
As suggested by @luzpaz, this adds a tooltip to the f(x) icon of all of the widgets that use it: `QuantitySpinBox`, `UIntSpinBox`, `IntSpinBox`, `DoubleSpinBox`, and `ExpLineEdit`. These five classes are divided across three files, and all five classes duplicate the same basic code. In the existing code, no tooltip is shown if there is no expression. If there is an expression, it (alone) is used as the tooltip.
This commit modifies that behavior to have explanatory text as the tooltip when there is no expression, and when there is, to prepend a short string to the beginning.
To reduce further code duplication, this is implemented by adding a new function to `ExpressionLabel` allowing the text of the expression to be set. It checks that text and if it's empty, uses a preset default string …
> [0.20] [GUI] Add tooltip to f(x) when there is no expression

- src/Mod/Spreadsheet/Gui/SheetTableView.cpp
- src/Mod/Spreadsheet/Gui/SheetTableView.h
Improves the UX for the spreadsheet header context menus.
* Add support for better translations (using pluralizations)
* Add support for inserting rows/columns after the selection
* Informs the user that it will insert rows/cols above/under/left/right of the selection
* Informs the user how many rows/cols that will be inserted
---
> Spreadsheet: Fix UI issues when trying to insert rows/cols

- src/Mod/TechDraw/Gui/Command.cpp
- src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
- src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_RedrawPage.svg
TechDraw RedrawPage icon is too similar with Std_Refresh icon and it could be difficult to identify. A design improvement was requested.
This commit replaces SVG file with new icon design for this command. Also, it makes the necessary changes on Command.cpp and TechDraw.qrc files, following the FC convention for file names.
The new SVG icon follows the FreeCAD Artwork Guidelines and was saved as Plain SVG format.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=57139&start=10#p492312
> [UI] Replace SVG icon of TechDraw RedrawPage

- src/Mod/Part/App/PrimitiveFeature.cpp
since we have now 3 angles for cylinders, make clear the angle property is for the rotation
> [Part] [skip ci] add a word in description

- src/Gui/CommandDoc.cpp
- src/Gui/Icons/Std_TransformManip.svg
- src/Gui/Icons/resource.qrc
Std TransformManip command does not have icon for the FreeCAD UI (Menu Edit). An icon was requested.
This commit adds SVG icon for this command. Also, it makes the necessary changes on CommandDoc.cpp and resource.qrc files.
The new SVG icon follows the FreeCAD Artwork Guidelines and was saved as Plain SVG format.
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=57139#p491862
> [UI] Add SVG icon for Std TransformManip command

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/DraftVecUtils.py
There are three bug report on the forum:
https://forum.freecadweb.org/viewtopic.php?f=23&t=57302
https://forum.freecadweb.org/viewtopic.php?f=23&t=57303
https://forum.freecadweb.org/viewtopic.php?f=23&t=57306
The first is solved reseting the coordinates-related attributes on each call to the commands.
The second and third are solved syncing the input fields on the task panel and updating the coordinates-related attributes (x, y, z, avalue, lvalue). The new attribute pvalue is intended to be used in future pull request as the polar angle theta while avalue will be the azimuthal angle phi.
To reduce the number of calls to the coordinate update functions, these are called only once when the input field is in focus. 
Two new functions are added to DraftVectUtils.py to transform from Cartesian …
> Draft: Sync input fields in task panel

- src/Mod/Arch/ArchWindow.py
Signed-off-by: Łukasz Stelmach <stlman@poczta.fm>
---
> Arch: Parse window opening modes with more than one digit

- src/Mod/AddonManager/addonmanager_workers.py
This pull request fixes AddonManager to work with encrypted Ubuntu home dir with ecryptfs. Ecryptfs has internal limitation of path lenght to 140 characters only, but AddonManager respects only 260 chars limitation of normal filesystems.
> AddonManager cannot download anything if working dir is on ecryptfs (aka ubuntu's encrypted home)

- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_Split.svg
- src/Mod/Sketcher/Gui/Resources/icons/pointers/Sketcher_Pointer_Splitting.svg
Two icons of Sketcher WB are not Plain SVG format. An update was requested.
This commit replaces SVG files with new SVG saved as Plain format.
Discussion: https://github.com/FreeCAD/FreeCAD/pull/4420#issuecomment-826155143
> [UI] Replace SVG icon files for Plain SVG format

- src/Base/PyObjectBase.cpp
- src/Tools/generateTemplates/templateClassPyExport.py
seems python changed the object slots again and replaced a pointer with an offset ...
> [build]: Fix generation and build of python classes for 3.9

- src/Mod/Draft/draftguitools/gui_arcs.py
- src/Mod/Draft/draftguitools/gui_ellipses.py
- src/Mod/Draft/draftguitools/gui_points.py
If UsePartPrimitives is True Draft.autogroup(...) is part of _cmd_list, therefore Draft module must be available. Since the Draft module imports the Part module, there is no need to load the latter separately.
> Draft: Fixed 3 gui_*.py files that did not execute Gui.addModule("Draft") if UsePartPrimitives is True

- src/Mod/Arch/ArchStairs.py
- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftguitools/gui_edit.py
- src/Mod/Draft/draftguitools/gui_scale.py
- src/Mod/Draft/draftmake/make_arc_3points.py
- src/Mod/Draft/importDWG.py
- src/Mod/Draft/importDXF.py
- src/Mod/Draft/importOCA.py
- src/Mod/Fem/femguiutils/selection_widgets.py
- src/Mod/OpenSCAD/exportCSG.py
- src/Mod/Part/Gui/TaskCheckGeometry.cpp
- src/Mod/Path/Gui/Resources/translations/Path.ts
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Start/Gui/Resources/translations/StartPage.ts
- src/Mod/TechDraw/Gui/Command.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.cpp
- src/Mod/TechDraw/Gui/mrichtextedit.cpp
Removing possible whitespace from strings lead to more accurate translations
> Crowdin: represent whitespace in code instead of in string

- src/Mod/Arch/ArchSectionPlane.py
- src/Mod/Draft/draftutils/groups.py
I noticed a problem where the draft section view sometimes renders invisible objects when it should not. It turns out that for groups that only contain flat objects, all contained objects are rendered in the section view an additional time, without looking at visibility. This means visible objects are rendered *twice*, and invisible objects are rendered *once*.
Here is a file with a testcase: 
[Flat groups test.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/6447908/Flat.groups.test.FCStd.zip)
Which renders like this. Note that the top line is slightly more bold than the bottom one:
With this PR applied, it renders as expected.
See the commit message for a detailed description of the problem and the fix. I think this is a pragmatic fix with minimal code changes, but I also have the …
> Arch: Fix section view duplicate rendering of items in groups with only flat objects

- .github/PULL_REQUEST_TEMPLATE.md
Trivial commit to update the release notes forum link in the pull request template, I just noticed it still points to the 0.19 thread, but there is a 0.20 thread already.
> Update link to changelog thread in pull request template

- src/Mod/Sketcher/Gui/SketcherSettings.cpp
- src/Mod/Sketcher/Gui/SketcherSettingsDisplay.ui
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
This is only available & operational when 'Restore camera' is enabled
[Forum discussion](https://forum.freecadweb.org/viewtopic.php?f=22&t=44747)
> [Sketcher] Visibility automation : add option to force orthographic view when entering edit mode

- src/Mod/Draft/Resources/ui/preferences-dxf.ui
ref: https://crowdin.com/translate/freecad/548/en-en?filter=basic&value=13#6577122
> Crowdin: fix mistake in Draft Preferences text [skip ci]

- src/Mod/Draft/draftmake/make_arc_3points.py
ref: https://crowdin.com/translate/freecad/548/en-en?filter=basic&value=2#6587168
> Crowdin: remove superfluous whitespace from translation 

- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/Cosmetic.h
- src/Mod/TechDraw/Gui/TaskCenterLine.cpp
- src/Mod/TechDraw/Gui/TaskCenterLine.h
- src/Mod/TechDraw/Gui/TaskCenterLine.ui
the PR fixes the following things:
- change the way centerlines between 2 lines are calculated. The current implementation leads to many bugs and even crashes (e.g. when the 2 selected lines are parallel ones of a square). There are different forum threads from the last 1.5 years.
The new endpoint line sorting is the one described here: https://forum.freecadweb.org/viewtopic.php?f=35&start=20&t=44255&sid=989a668890f954c13ef81e4a04ee6912#p501179
- as consequence the erroneous and misleading line end flipping can go and is removed (only used internally)
- when creating a new centerline, you see it immediately
- when creating a new or editing an existing centerline and press Cancel, the creation/editing is aborted
- fix crash when the 2 selected lines are bot horizontal and one tries to …
> [TD] fix centerline crashes and bugs

- src/Mod/OpenSCAD/importCSG.py
Extruded 2d geometry was not being hidden, per forums discussion https://forum.freecadweb.org/viewtopic.php?f=8&t=57410&start=30
---
> [OpenSCAD] Fix missing hide() on linear extrude

- src/Mod/Path/PathScripts/PathDrilling.py
- src/Mod/Path/PathScripts/PathUtils.py
Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=15&t=58306&sid=1eea82eb33515fc35e70affd64fbbe70
Bug: https://tracker.freecadweb.org/view.php?id=4652
Changes:
- Start drilling operations from OpStartDepth + SafeHeightOffset rather than StockTop + SafeheightOffset
- Enable the use of tipoffset when using toolbits. Display an unsupported warning if using legacy tools. Toolbits FTW!
- Set the retract height relative to the operations startDepth + SafeHeightOffset.
> [Path] Fixes for drilling operation

- src/Mod/Path/PathScripts/PathJob.py
In a few locations, python objects are used without checking if they exist and are non-null, which throws missing attribute exceptions. The` fix is to simply check first. This fixes [Issue 4645](https://tracker.freecadweb.org/view.php?id=4645).
> Path: check for empty before using - fixes #4645

- src/Mod/Path/PathScripts/PathSlot.py
This PR includes the following fixes:
- Path: Set `CustomPoint2` and `CustomPoint1` defaults equal
- Path: Add check for `CustomPoint` input
- Path: Fix error when no `obj.Base` features selected
- Path: Fix variable naming to use lowercase
- Path: Fix comment syntax
- Path: Improve horizontal-planar and curved face handling
Forum discussion at  [0.19 Slot Op fixes](https://forum.freecadweb.org/viewtopic.php?f=15&t=56004).
And please …
> [Path] Stability fixes for experimental Slot operation

- src/Mod/Path/PathScripts/PathPocketShapeGui.py
Fix the bug hindering update of the Default Length spin box in the Extensions tab after editing and change of focus. 
With the fix, the spin box updates after change of focus, as do other spin boxes in the Path workbench.
Used method found in PathDrillingGui module.
I cannot locate the forum thread(s) where this is mentioned; if I do find one, I will add it here.  I did not find an open mantis ticket.  This has needed to be fixed for a long time. …
> [Path] Fix update of Extensions `Default Length` GUI spin box

- src/Mod/Path/PathScripts/PathVcarve.py
Depths were being calculated incorrectly due to MIC distance getting
divided by scaling factor rather than multiplied by it.
The scaling factor is the inverse of the tan of half the cutting tool
angle, so for a 30 degree bit (say), the scaling factor would be
1 / tan(30/2), or 3.7320.
When given an MIC (which is a radius) of 3.175 (say), and cutting to the
same width with a 30 degree bit, the depth should be 3.175 * 3.7320
(11..849), not 3.175 / 3.7320 (0.8509) as it is currently.
My apologies if I haven't complied with the expected PR standards. I have not built the code, but have checked that the calculated depths are correct by modifying the .py file in the version of code running on my system.
It appears that the existing tests check that the 'scale' factor is correct, but they don't …
> Path: vcarve - Fix depth calculation

- src/Mod/Draft/draftguitools/gui_groups.py
The code that was intended to handle this preference looked inside
Mod/BIM instad of Mod/Draft for the preference. This seems to have been
broken since the preference was first introduced in commit 507c40669d
(Draft: Turned autogroup button into layers selector (added pref option
to restore old groups-based system)).
This also removes a stray "-" that was probably a leftover from a merge
conflict, introduced in commit 68119de02f (Draft: move Draft_AutoGroup to
gui_groups module). Since -True is still true and -False is still false,
this did not actually break the code, though.
See https://forum.freecadweb.org/viewtopic.php?t=42018 for related
discussion.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull …
> Draft: Fix "Show groups in layer list drop-down button" preference

- src/Mod/Arch/ArchComponent.py
- src/Mod/Draft/draftobjects/circle.py
- src/Mod/Draft/draftobjects/wire.py
This is a small PR containing a few small simplifications to the draft & arch code, that help readability (and maybe a tiny bit of performance). This is just a pilot PR containing a few such simplifications I noticed while reading the code. If this is welcomed, I might submit more.
This PR makes no changes to FreeCAD's behavior, it only replaces code with simpler but equivalent code.
See also https://forum.freecadweb.org/viewtopic.php?f=10&t=58611 for some previous discussion about these kind of changes.
- [X  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
> Draft & Arch: Python code simplifications

- src/Mod/Draft/draftutils/groups.py
This caused the original object to be moved when using the Draft move
tool to move a link object, when the original object has MoveWithHost
set (e.g. a Window). There was already a similar exception for clones,
so it makes sense to extend this for links too.
Note that there seem to be more problems with the "MoveWithHost"
mechanism and fixing them might completely refactor this code, but until
then, this is a simple and targeted fix that at least makes moving
links to windows work as expected.
See https://forum.freecadweb.org/viewtopic.php?f=23&t=57223 for
discussion of this bug, its fix and the additional problems mentioned.
> Draft: Do not move children of App::Link objects

- src/Mod/Draft/draftfunctions/mirror.py
Removes closing parenthesis from the string.  
Please review the code since I have not compiled to test this change. Thx!
ref: https://crowdin.com/translate/freecad/548/en-en?filter=basic&value=2#6587132
> Crowdin: fix Draft mirror code typo

- src/Mod/Draft/draftmake/make_label.py
The make_label function should accept a list of strings for custom_text. Compare the make_text function. The new code was mostly taken from there.
> Draft: Fixed make_label to accept list of strings for custom_text

- src/Mod/Path/PathScripts/PathGuiInit.py
This PR touches one module, PathGuiInit.  It alphabetizes the import list and handles the error created by the unavailability of the  Camotics library/module.
---
> [Path] Handle unavailability of Camotics library/module

- src/Mod/Sketcher/Gui/SketcherSettingsDisplay.ui
- they were too long for smaller screens
- the other UI file changes were automatically made by Qt Designer
> [Sketch] fix too long tooltips

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
As a consequence :
Remove message box when several arcs/circles are selected and enforce creation of equality constraints in this case
Former existing option of adding a dimensional constraint to each circle encouraged improper constraining
[Forum thread](https://forum.freecadweb.org/viewtopic.php?f=3&t=57584)
I made the minimal changes. I saw other things that may be discussed but will poll community and do another PR if needed.
> [Sketcher] Fix 'Reference' checkbox not working for radius/diameter

- src/Mod/Draft/draftguitools/gui_edit.py
- src/Mod/Draft/draftguitools/gui_edit_arch_objects.py
- src/Mod/Draft/draftguitools/gui_edit_base_object.py
- src/Mod/Draft/draftguitools/gui_edit_draft_objects.py
- src/Mod/Draft/draftguitools/gui_edit_part_objects.py
- src/Mod/Draft/draftguitools/gui_edit_sketcher_objects.py
Reference to post by @matthijskooijman: https://forum.freecadweb.org/viewtopic.php?f=23&t=58643&start=10#p505619
---
> Draft: Edit improvements to context menu and code organization

- src/Mod/Draft/draftguitools/gui_stretch.py
If a wire is created to replace a rectangle, the MakeFace property of the wire should match that of the rectangle.
> Draft: Fix gui_stretch

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
This PR fixes the same bug as PR #4744 where diameter was forget (only radius implemented)
> [Sketcher] Fix 'Reference' checkbox not working for diameter

- src/Mod/Arch/exportIFCStructuralTools.py
This pull request replaces this one: https://github.com/FreeCAD/FreeCAD/pull/4823
Regarding to this minor code improvements have been made which were validated through performed tests.
(see dedicated forum thread: https://forum.freecadweb.org/viewtopic.php?f=39&t=54286&start=30#p508306)
As @Bernd suggested I split it into two commits:
First commit:
- does only code formating for better readability
Second commit
- IFC export for StructuralSurfaceMembers (ATM only slabs with their thickness)
- IFC export for RelConnectsStructuralMember [connection between structural members (linear/surface) and structural connection (punctual/linear)]
> [Arch] IFC (structural view) export for slabs (new pull request)

- src/Mod/Draft/draftviewproviders/view_array.py
The code wrongly used the PointList property to detect a Draft_PointArray. PointObject should be used instead.
For consistency also changed the code to detect a Draft_PathTwistedArray to use the RotationFactor property.
> Draft: Fix wrong tree icon for Draft_PointArray

- src/Mod/Draft/WorkingPlane.py
- src/Mod/Draft/draftgeoutils/geometry.py
- src/Mod/Draft/draftguitools/gui_selectplane.py
Currently, alignToSelection works only on a face object. With this changes, the method works on any list of Part.Shape objects.
If this objects define a plane, the working plane is set to it even if the list exceeds the number of objects needed to define the plane.
First, the method check the geometric property of the selection according to https://forum.freecadweb.org/viewtopic.php?f=10&t=49939&p=429457#p429469. Then, checks coplanarity, set the WorkingPlane's normal and the position at the center of mass of the selection objects.
With the changes on gui_selectplane.py, the methods handle and alignToSelection are only executed if a list of objects is selected. If not, the task panel is launched. Also, checks if there is a active draft command and finish it when the SelectPlane button is …
> Draft: Improve alignToSelection method on WorkingPlane

- src/Mod/Spreadsheet/Gui/CMakeLists.txt
- src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp
- src/Mod/Spreadsheet/Gui/SpreadsheetViewPy.xml
- src/Mod/Spreadsheet/Gui/SpreadsheetViewPyImp.cpp
The goal of the PR is to provide a sure way to get a pointer to a spreadsheet based on its MDIView.
As of today, only guessing from the window (tab) title is possible but it's limited.
Typical usage is `FreeCADGui.ActiveDocument.ActiveView.getSheet()`
ATM it returns a DocumentObject. For consistency, it would probably be better to return a ViewProviderObject, but I'm not sure there is a simple way to achieve this. I'll open a topic in the forum and update the PR if I can find a solution there.
> [Spreadsheet] Expose SpreadsheetView::getSheet to Python

- src/Mod/TechDraw/Gui/CMakeLists.txt
- src/Mod/TechDraw/Gui/MDIViewPage.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.h
- src/Mod/TechDraw/Gui/MDIViewPagePy.xml
- src/Mod/TechDraw/Gui/MDIViewPagePyImp.cpp
This PR adds a new 'getPage' functions in TechDraw ViewProviderPage.
It uses this function to add a 'getPage' Python API that returns from a TechDraw MDIView that DrawPage being displayed
> [TechDraw] Add 'getPage' Python API ; returns page from view

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
- src/Mod/Sketcher/Gui/Resources/icons/constraints/Constraint_Radiam.svg
- src/Mod/Sketcher/Gui/Resources/icons/constraints/Constraint_Radiam_Driven.svg
- src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
- src/Mod/Sketcher/Gui/TaskSketcherElements.h
- src/Mod/Sketcher/Gui/Workbench.cpp
'Radiam' applies :
- Radius constraint to arcs
- Weight constraint to BSpline poles
- Diameter constraint to complete circles (that aren't BSpline poles)
It supports multi-selecting in the same way radius & diameter constraints do.
> Add sketcher 'Radiam' tool that autoconstraints radius/diameter depending on object type

- src/Mod/Draft/DraftGui.py
Currently, the method for checking special characters uses a list of specific input fields.
With this change, the input field used is the one focused inside the base widget "draftToolBar". The attributes to modify and their units are read from the input_fields attribute dictionary. In this way, other workbenches that use other input fields within draftToolBar can use the method to check characters by simply adding the name of the widget and the corresponding attribute to the input_fields dictionary and connecting the Qt signal.
See https://forum.freecadweb.org/viewtopic.php?f=23&t=59352&sid=cf698f878b1630039b741ffe49a14188
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all …
> Draft: Check special characters using focused input field

- src/Mod/Draft/draftguitools/gui_edit_base_object.py
- src/Mod/Draft/draftguitools/gui_selectplane.py
- src/Mod/Path/PathScripts/PathFeatureExtensions.py
- src/Mod/Path/PathScripts/PathFeatureExtensionsGui.py
- src/Mod/Path/PathScripts/PathGeom.py
Found via `codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,apoints,ba,beginn,behaviour,bloaded,bottome,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,ist,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oder,ontop,orgin,orginx,orginy,ot,pard,parms,pres,programm,que,recurrance,rougly,seperator,serie,sinc,strack,substraction,te,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./src/Mod/Ro …
> Fix source comment typos

- src/Mod/Path/PathScripts/PathSanity.py
[Path] PathSanity now outputs fillename for the report the same as the postprocessor job
Output fillename for the report is now the same as the postprocessor job (job.PostProcessorOutputFile), this way the setup file will be autoloaded in LinuxCNC qtDraggon ui and others based on probe-basic.
There is some error checking missing, the check to see if the job.PostProcessorOutputFile is not empty is not there for example. But since the report can/should only be generated when there is a postprocessor file this is not a big problem.
> [Path] PathSanity.py now outputs fillename for the report the same as the postprocessor job

- src/Mod/Sketcher/Gui/CommandAlterGeometry.cpp
- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateOblong.svg
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateOblong_Constr.svg
- src/Mod/Sketcher/Gui/Resources/icons/pointers/Sketcher_Pointer_Oblong.svg
- src/Mod/Sketcher/Gui/Workbench.cpp
while constructing I miss often that one cannot insert directly rounded rectangles. As it is, one needs first to insert a rectangle, then go to fillet mode, then click 8 times, then set equal constraint, then often also replace the vertical/horizontal constraints since a rectangle must not necessarily be parallel to a sketch axis
As solution this PR adds rounded rectangles in one step. This saves a lot of time since this object is e.g. often used for milled rectangular pockets, for 3D-printed pads etc.
Since the slot is a special case of a rounded rectangle and the use cases are similar as well, I grouped the lot and rounded rectangle.
Here is a screencast how I implemented it:
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=17&t=59210
(The code beautification in this PR of …
> [Sketch] add new sketch object rounded rectangle

- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateRectangle_Center.svg
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateRectangle_Center_Constr.svg
- src/Mod/Sketcher/Gui/Resources/icons/tools/Sketcher_RemoveAxesAlignment.svg
As the title says.
To assure that every browser and SVG display program can display the SVGs correctly, we should remove the Inkscape-specials by saving the SVG strictly according to the SVG specifications
> [Sketch] save new icons as plain SVG

- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/Workbench.cpp
in practical work it turned out that the slot command is not as convenient as it should because one cannot snap to a proper endpoint and one is restricted to work perpendicular to the sketch axes
This PR fixes this by setting the second snap point to the center of the second arc and removing the perpendicularity.
Benefits:
- when you want to get the slot at a line, edge or sketch axis, set the two center points accordingly. The line does not have to be parallel to one of the sketch axes
- when you want to define the slot using 2 points in the sketch you can do this now
Here is a screencast how it works:
Forum thread: https://forum.freecadweb.org/viewtopic.php?f=17&t=59243
(The code cosmetics in this PR was kindly automatically done by MSVC.)
> [sketch] rework the slot command

- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
all other menu entries use lower case letters, thus do so also for the new tool
> [Sketch] fix menu entry wording

- src/Mod/Draft/draftguitools/gui_base_original.py
- src/Mod/Draft/draftguitools/gui_edit.py
To reproduce the reported error, two BuildingParts must be activated consecutively, so that the DraftWorkingPlane.save method is executed and overwrite the DraftWorkingPlane.stored attribute with the information from the previous working plane.
This behavior is not limited to the edit command. The same happens with the rest of the modification commands in Draft but when they are executed twice.
Removing the call to DraftWorkingPlane.restore in draftguitools's finish method solve the problem.
https://tracker.freecadweb.org/view.php?id=4562
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, …
> Draft: Fixes #0004562: Active working plane changes when I close Draft Edit panel

- src/Mod/Draft/draftgeoutils/offsets.py
The direction of the offset could be faulty if Draft precision=6. Since we are only interested in the side the pointer is on, working with a high precision does not make sense.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=59052
- [*]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need …
> Draft: Fix offsets.py problem with direction if precision=6

- src/Mod/AddonManager/addonmanager_workers.py
Parses addonflags.json with the python json-module instead of using
regular expressions.
---
> AddonManager: parse addonflags.json with json module

- src/Mod/Path/PathScripts/PathOpGui.py
Path operations were being recalculated even if the panel was opened and closed without any modification. 
This caused avoidable delays particularly with complex 3D surface operations.
The accept call back was checking "isDirty" which always returned "True".
It was changed to call "isDirty()" instead which correct reflects the isdirty state of the pages.
--------------------------
---
> Path: Fixed incorrect usage of isDirty() in the accept button call back.

- src/Mod/Fem/femsolver/writerbase.py
- src/Mod/Material/importFCMat.py
Found via `codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,apoints,ba,beginn,behaviour,bloaded,bottome,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,inout,ist,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oder,ontop,orgin,orginx,orginy,ot,pard,parms,pres,programm,que,recurrance,rougly,seperator,serie,sinc,strack,substraction,te,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./src/ …
> Fix FEM and Material typos

- src/Mod/Draft/DraftTools.py
The default value for defaultWP in DraftTools.py did not match the value in DraftGui.py and preferences-draft.ui.
See forum topic: https://forum.freecadweb.org/viewtopic.php?f=8&t=57909&p=513411#p513411 …
> Draft: Fix wrong default value for defaultWP

- src/Mod/Draft/draftguitools/gui_groups.py
- src/Mod/Draft/draftutils/groups.py
Fix 3 issues with the Draft Tray layer list:
The layer list should display even if there are no layers so that the "Add new Layer" option can be selected.
"Project" and "BuildingPart" objects should be added to the list (depending on "AutogroupAddGroups" of course).
The "LayerContainer" object should not be added to the list. Although it is in fact a group, it is just too confusing.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=59563 …
> Draft: Fix 3 issues with the Draft Tray layer list

- src/Mod/Draft/importDWG.py
Directly calling subprocess.Popen without checking the presence of the
program is the optimal solution because:
1) Avoids race condition, where the program disappears between the
check and the Popen call.
2) Popen will raise exception if the program is absent anyway,
no race condition here.
> Draft: Some shutil don't have the .which method.

- src/Mod/Draft/draftguitools/gui_tool_utils.py
When a modification command is executed without objects selected, a dumb task dialog opens. With these changes it is possible to select/deselect multiple objects by holding down the Ctrl key.
Since the selection of objects is implicitly effective when they are clicked during the execution of the event callback, the use of the Python function Gui.Selection.addSelection is unnecessary. In fact, using this function or Gui.Selection.removeSelection to add/remove objects generates unnecessary multiple calls to the SelectionSingleton::addSelection and SelectionSingleton::rmvSelection functions respectively since these last two are used directly by the selection mechanism.
Also, the definition of the activeDraftCommand.component attribute is removed since it is not used by any command.
Thank you …
> Draft: Enable multiple selection for dumb task dialog in Modification commands

- src/Mod/Draft/draftguitools/gui_base_original.py
- src/Mod/Draft/draftguitools/gui_selectplane.py
First commit:
The modifications imposed in https://github.com/FreeCAD/FreeCAD/pull/4492/commits/76c7aa314d253f49814f8e5f851b897e89158791 generate a regression in the functioning of the working plane since by eliminating the call to DraftWorkingPlane.restore in the finish method of the commands, and because the next call of the working plane dialog run the restore method, the working plane returns to the previous working plane used.
To reproduce this bug:
1.Run any Creator command (Line, Polyline, Circle, etc).
2.Change the working plane using the working plane setup dialog.
3.Run again any Creator command.
Result: the working plane return to the previous plane.
To solve this, the DraftWorkingPlane.restore method is reenabled in finish method.
Now, back to solve the original bug: …
> Draft: Fix regression on WP and fixes #0004562

- src/Mod/Path/PathScripts/PathGeom.py
- src/Mod/Path/PathScripts/PathJobDlg.py
- src/Mod/Path/PathScripts/PathSlot.py
- src/Mod/Path/PathScripts/post/nccad_post.py
- src/Mod/Path/PathScripts/post/uccnc_post.py
- src/Mod/Path/PathTests/TestPathAdaptive.py
- src/Mod/Path/Tools/README.md
Found via `codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,apoints,ba,beginn,behaviour,bloaded,bottome,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,inout,ist,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oder,ontop,orgin,orginx,orginy,ot,pard,parms,pres,programm,que,recurrance,rougly,seperator,serie,sinc,strack,substraction,te,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./src/ …
> Path: fix various typos and superfluous whitespace

- src/Mod/Path/PathScripts/PathProfile.py
The profile operation is forcing  cut side to `Outside` when profiling whole models.  This change in code also allows for profiling `Inside` of entire models.  Apart from limiting profiling capabilities of entire models, this override could cause problems with profiling in very specific use cases.  Also, this fix removes the property assignment of a key control property within the execution code, which should not happen, apart from feedback properties.
Tracker bug 4433 occurred some time ago and was deemed to be resolved with PR #3861.  However, the single line of code removed in this PR likely needed to be removed with that original PR.
The forum user that originally identified bug 4433 has recently bumped the original forum post, [Ticket #4433 - profile operation cut side …
> [Path] Remove `Side` assignment to `Outside` for full model profiles

- src/Mod/TechDraw/App/Cosmetic.cpp
add missing info to understand the new centerline behavior as introduced with commit b981f905
> [TD] comment the new centerline behavior

- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/Gui/CommandAnnotate.cpp
- src/Mod/TechDraw/Gui/TaskCosVertex.cpp
- src/Mod/TechDraw/Gui/TaskCosmeticLine.cpp
This pull request fixes missing Undo/Redo for TechDraw's Add Cosmetic Vertex and Add Cosmetic Line functionality, as reported in this TechDraw forum section topic: [https://forum.freecadweb.org/viewtopic.php?f=35&t=59529](https://forum.freecadweb.org/viewtopic.php?f=35&t=59529)
> TechDraw - Undo for Cosmetics Vertices and Lines

- src/Mod/Path/PathScripts/PathGui.py
- src/Mod/Path/PathScripts/PathOpGui.py
- src/Mod/Path/PathScripts/PathPocketShape.py
Three issues are fixed in this PR that are more ease-of-use fixes (not new features) for behaviors that are expected, but not occurring:
* Fix readonly GUI spin boxes when no expression is used.  Currently when the expression is cleared, the spin box behaves as readonly, forcing the user to enter their new value in the popup expression editor.
* Fix incorrect values in GUI spin boxes in Task Panel upon initial creation of operation.  To reproduce, simply create simple cube 20x20x20.  Select the top face and then create either a Profile or Pocket op.  Look at the values in the Depths and Heights tabs; the values likely do not reflect correct values based on the selected face and stock of the model.  This PR corrects this deceiving behavior.  Currently, the values will be corrected after …
> [Path] Fix GUI issues and minor code cleanup

- src/Mod/Path/PathScripts/PathAdaptive.py
- src/Mod/Path/PathScripts/PathCustom.py
- src/Mod/Path/PathScripts/PathDeburr.py
- src/Mod/Path/PathScripts/PathDressupPathBoundary.py
- src/Mod/Path/PathScripts/PathDrilling.py
- src/Mod/Path/PathScripts/PathEngrave.py
- src/Mod/Path/PathScripts/PathHelix.py
- src/Mod/Path/PathScripts/PathJobGui.py
- src/Mod/Path/PathScripts/PathMillFace.py
- src/Mod/Path/PathScripts/PathOp.py
- src/Mod/Path/PathScripts/PathOpGui.py
- src/Mod/Path/PathScripts/PathPocket.py
- src/Mod/Path/PathScripts/PathPocketShape.py
- src/Mod/Path/PathScripts/PathProbe.py
- src/Mod/Path/PathScripts/PathProfile.py
- src/Mod/Path/PathScripts/PathProfileContour.py
- src/Mod/Path/PathScripts/PathProfileEdges.py
- src/Mod/Path/PathScripts/PathProfileFaces.py
- src/Mod/Path/PathScripts/PathSetupSheet.py
- src/Mod/Path/PathScripts/PathSimulatorGui.py
- src/Mod/Path/PathScripts/PathSlot.py
- src/Mod/Path/PathScripts/PathSurface.py
- src/Mod/Path/PathScripts/PathThreadMilling.py
- src/Mod/Path/PathScripts/PathVcarve.py
- src/Mod/Path/PathScripts/PathWaterline.py
This PR makes some useful changes to the existing operations to ease scripting with GUI support for the Path WB.  This improvement is done by relocating the creation of the `PathOpGui.CommandResources` object from being an object inside the `PathOpGui.SetupOperation()` function to each GUI operation module, and passing this independent resource object to the `PathOpGui.SetupOperation()` function in place of the original arguments that were used to create the same resource object.  With this relocation, the ability to disable the initial Task Panel GUI interaction is added.  This means users can script with GUI/view-provider support without having to interact with the Task Panel for new operations or jobs.  The good news is that the normal/existing ability to edit operations and jobs with …
> [Path] GUI scripting support and other improvements

- src/Mod/OpenSCAD/importCSG.py
Fixes #4684.
For some reason colors of "base" and "tool" need to be set in order for the cut
to have colors as well, just like fuse and multifuse.
Also tidied up the relevant code portions a little.
Some testing might be needed. …
> [OpenSCAD] Fixes cut color while importing CSG

- src/Gui/Widgets.h
- src/Mod/TechDraw/Gui/QGIRichAnno.cpp
- src/Mod/TechDraw/Gui/QGIRichAnno.h
- src/Mod/TechDraw/Gui/QGIViewAnnotation.cpp
- src/Mod/TechDraw/Gui/QGIViewAnnotation.h
- src/Mod/TechDraw/Gui/mrichtextedit.cpp
- src/Mod/TechDraw/Gui/mrichtextedit.h
This pull request adds a way to invoke simple and rich text annotation editors by double-click on the view items. Also gives a possibility to store rich text editor changes by pressing Ctrl+Enter as string list property editor already does.
> TechDraw - Edit annotations via double-click

- src/Mod/Arch/ArchWall.py
Forum Discussion - https://forum.freecadweb.org/viewtopic.php?f=23&t=60771
---
> [ArchWall]  Fix MakeBlocks to work if Base is Sketch

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftguitools/gui_trimex.py
gui_trimex:
The redraw function was changed to return a list [dist, ang] if the real argument is not True. With this list the action function 'knows' which units to display. This also made it possible to move the "self.ui." related stuff that was in the redraw function to the action function.
I have also changed two tooltip texts by removing the article "The". This is more in keeping with other tooltips.
DraftGui.py
The tooltip text in this file was changed to match one of the tooltips in gui_trimex.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the …
> Draft: Draft_Trimex: Fix wrong angle units in task panel

- src/Mod/PartDesign/Gui/TaskPadParameters.cpp
- src/Mod/PartDesign/Gui/TaskPocketParameters.cpp
While useless 'Midplane' was still visible
Bug introduced in commit cf11f388, not fixed by commmit b4b1cbed
Also fixing some typos
> [PartDesign] Fix 'Reversed' no more available in Pad 'toFirst/toLast' + Pocket '2dims'

- src/App/Link.cpp
- src/App/Link.h
The patch fixes Link.LinkMode becoming ineffective after restore. It is brought to my attention with thread https://forum.freecadweb.org/viewtopic.php?f=3&t=52772
> App: fix LinkMode enforcement in Link on restore

- src/Gui/MainWindow.cpp
So macros/add-ons can eventually restore things
> [Gui] Send 'mainWindowClosed' signal before window settings are saved

- src/Mod/OpenSCAD/OpenSCADTest/app/test_importCSG.py
- src/Mod/OpenSCAD/importCSG.py
When not using the GUI, bounding box calculations can sometimes use the B-spline representation in OCCT, which can in some cases give incorrect results. To correct for this, explicit calls to tessellate() are added to ensure that the bounding box calculation uses the true shape, even if the GUI is not running.
Fixes #[4622](https://tracker.freecadweb.org/view.php?id=4622) - OpenSCAD/OpenSCADTest/app/test_importCSG.py assertion failure
---
> [OpenSCAD] Fix OpenSCAD bounding box calculations

- src/Mod/Fem/Gui/Resources/ui/Material.ui
- src/Mod/Start/StartPage/StartPage.py
Image filenames should be encoded as URI before being hashed.
Also assume that filenames are already utf8 because the community has been advertiseing utf8 usage since the beginning of this centry AFAIK.
Calling .encode("utf8") on strings that are already in utf8 simply raises exception:
```
UnicodeDecodeError: 'ascii' codec can't decode byte ...
for non-ascii (already utf8) strings.
```
It's in fact impossible to precisely determine pathname encoding because different components within the path may have different encodings, e.g. a utf8 directory name followed by an mbcs filename is valid on Linux native filesystems. It's the user's responsibility to keep the iocharset consistent.
> Start: Properly hash thumbnail filenames

- src/Mod/Start/StartPage/StartPage.py
Reverts FreeCAD/FreeCAD#4931 -- in Python 3 `quote` is now located in the `urllib.parse` module, and not directly in `urllib`. It also takes an optional `encoding` parameter, which I think is necessary in this case since the hash function requires unicode be encoded prior to execution.
> Revert "Start: Properly hash thumbnail filenames"

- src/App/Application.cpp
Use of "exit()" function can prevent the core dump handler to be activated on Linux when crashing (especially with segmentation fault).
This is nice for normal user but it definitely needed for coders, so this PR uses "abort()" instead -- only when compiling in debug mode -- so a core dump is correctly generated.
> [Core] exit() can prevent core dumping, use abort() instead on debug mode

- src/Mod/Start/StartPage/StartPage.py
Image file names need to be quoted before hashing to generate thumbnail file names.
This is related to pull requests #4931 and #4972, so please refer to discussions therein.
> Start: Correct hash for thumbnail filename

- src/Mod/Arch/OfflineRenderingUtils.py
- src/Mod/Arch/importSH3D.py
- src/Tools/generateBase/generateModel_Module.py
LGTM complains about some missing parent class inits -- I've added them in this PR. They don't actually do anything, those parent initializers are empty, but it makes LGTM happy (I hope).
---
> [Arch] Add missing inits

- src/Mod/AddonManager/AddonManager.py
Currently when a user first uses the Addon Manager a dialog popup prompts them about how FC is not liable for the code plugin authors provide. It stores the binary response in a `readWarning` boolean  within the user.cfg file.  
This commit changes the location of said boolean from `User parameter:Plugins` to `User parameter:Addons`
In other words changing:  
```
<FCParamGroup Name="Plugins">
<FCParamGroup Name="addonsRepository">
<FCBool Name="readWarning" Value="1"/>
</FCParamGroup>
</FCParamGroup>
``` 
to:   
```
<FCParamGroup Name="Addons">
<FCParamGroup Name="addonsRepository">
<FCBool Name="readWarning" Value="1"/>
</FCParamGroup>
</FCParamGroup>
```
Edit: in other words, it makes sense to me to consolidate Addon related preferences all in once place. This PR the first step to doing …
> AddonManager: Consolidate preference in user.cfg from Plugins to  Addons

- src/Gui/Command.cpp
- src/Gui/Command.h
When compiled in debug mode, this PR adds code to check for conflicting accelerator keys when a command is created. This can help developers ensure that their default accelerator key selections don't conflict. The actual check function is publicly accessible from the `CommandManager`, so other code that wants to change or update accelerators can call it to verify that a choice is valid and non-conflicting. This code detects both complete conflicts, as well as "blockers" (that is, a key combination that will prevent another from working).
---
> [Core] Add checks for conflicting accelerators

- src/Gui/3Dconnexion/3DConnexion.xml
These keycodes matches what my device generate using
spacenavd in Fedora 33.
The old xml definition define two operations on the same KeyCode, one
for short press and one for long press. That doesn't work at all on my
system and the SpacePilot Pro device generate separate KeyCodes for
short presses and long presses.
https://forum.freecadweb.org/viewtopic.php?f=8&t=60265
> Set default keycodes for 3dconnexion SpacePilot Pro

- src/Mod/PartDesign/App/FeatureDraft.cpp
- src/Mod/PartDesign/App/FeatureDraft.h
- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/App/FeatureHelix.h
- src/Mod/PartDesign/App/FeatureLinearPattern.cpp
- src/Mod/PartDesign/App/FeatureLinearPattern.h
- src/Mod/PartDesign/App/FeaturePolarPattern.cpp
- src/Mod/PartDesign/Gui/TaskHelixParameters.h
- Helix: the property Turns has the App::PropertyFloatConstraint thus also the pointer to it must have the same property
- LinearPattern and Helix: make constraints static class member (forgot this in commit 3704ad68)
- Draft: make the constraint const
- PolarPattern and LinearPattern assure that the header file is loaded at last to avoid potential troubles
> [PD] fix property issues

- src/Mod/Draft/draftguitools/gui_snaps.py
Draft toolbar and statusbar can be activated also when no document is active, because Snap is not related to active document.
> Draft: fixed Snap behaviour when no document is active.

- src/Mod/Sketcher/Gui/SketcherSettings.cpp
- src/Mod/Sketcher/Gui/SketcherSettings.ui
- src/Mod/Sketcher/Gui/SketcherSettingsDisplay.ui
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- add checkbox for display parameter in settings gui
- save display option in settings
- add constraint name to presentation string
See initial idea https://forum.freecadweb.org/viewtopic.php?f=3&t=59498
Forum post for improvement discussions of this feature: https://forum.freecadweb.org/viewtopic.php?t=61153 …
> Sketcher: display dimensional constraint name - fixes #0004686

- src/Mod/Path/PathScripts/post/grbl_post.py
---
In the last commit ( https://github.com/FreeCAD/FreeCAD/commit/d2c170a929dbde55f5bb8bb3d18d70d9bd50b1bd ) I didn't add a newline which can lead to output like
``` …
```
> Path: Add missing newline to return-to statement in grbl postprocessor

- src/Mod/Draft/draftguitools/gui_move.py
Draft_Move Alt copy mode was fixed. The modifications were taken from gui_rotate.py.
---
> Draft: Fix Draft_Move Alt copy mode

- src/Mod/Draft/draftguitools/gui_edit.py
The poles in the resetTrackersBezier function are in the CS of the geometric parent of the curve. Before using `p = obj.getGlobalPlacement().multVec(p)` the nodes have to be translated to the CS of the curve. Otherwise the effects of the curve's Placement are added twice. See discussion: https://github.com/FreeCAD/FreeCAD/pull/4889
And please remember to update the Wiki with the features added or changed once this PR is merged. …
> Draft: Fix misplaced Draft_Edit nodes for BezCurve 2nd version

- src/Mod/Part/Gui/TaskAttacher.cpp
It is annoying because error-prone, that on opening e.g. primitives the reference selection mode is always on. You then e.g. click in the model and get a new attachment. But when opening existing primitives you don't always want to change the attachment (often only the parameters). And even if you want to change the attachment, you want to select which one and you like to know when you are in selection mode.
> [PD] fix bug that reference selection is always on

- src/Mod/Draft/draftguitools/gui_trimex.py
In extrude mode, the Trimex command raise  an "UnboundLocalError: local variable 'ang' referenced before assignment" 
---
> Draft: Fix variable referenced before assignment

- src/Gui/CommandView.cpp
With this tooltip isn't updated with the current item value
but instead keeps the general command tooltip text which more explanatory
> [Gui] Declare Std_DrawStyle as being a 'Mode' command

- src/Mod/Mesh/App/Core/Elements.cpp
Fixes issue #4732.
Within the code, a different algorithm is used for intersection checks when
faces are found to be coplanar. That algorithm does not return the "intersection
line", which is used to remove false-positives. This however results in
false-negatives.
--- …
> [Mesh] Avoid false negatives during self-intersection checks

- src/Mod/Sketcher/Gui/SketcherSettingsDisplay.ui
Closes https://github.com/FreeCAD/FreeCAD-translations/issues/59  
Thanks @jakub-swierk for the patch!  
@yorikvanhavre the next crowdin push is tomorrow, this fix should be merged before that. Thanks!
> Sketcher: fix mislabeled .ui cstring tag 

- src/Gui/DlgSettingsNavigation.cpp
- src/Gui/DlgSettingsNavigation.ui
Renamed `CheckBox_UseAutoRotation` to `checkBoxUseAutoRotation` to match the preexisting naming syntax
> Gui: Make DlgSettingsNavigation methods conform to naming standard 

- src/Gui/Language/Translator.cpp
Three changes to make it easier to test new translations:
When creating the original list of locales available to FreeCAD, also scan the supported external directories and add those entries to the list of locales. The additional languages will now appear in the Language preferences drop-down.
Add a hidden preference, `BaseApp/General/Preferences/AdditionalLanguageDomainEntries`, that will allow translators to add an entirely new language to FreeCAD via user preferences, without requiring modification of the FreeCAD source code. The format is "Language Name 1"="code1";"Language Name 2"="code2";... For example,
```
<FCText Name="AdditionalLanguageDomainEntries">"Esperanto"="eo";"Polish"="pl";</FCText>
```
Add a hidden preference, `BaseApp/General/Preferences/AdditionalTranslationsDirectory`, …
> [GUI] Add prefs for translators

- src/Base/Rotation.cpp
- src/Gui/Placement.ui
+ fix Euler representation string on GUI
[Forum discussion](https://forum.freecadweb.org/viewtopic.php?f=8&t=62046)
> [Core] Rotation : fix gimbal lock handling

- src/Base/Exception.cpp
- src/Base/Exception.h
In some circumstances, FileExceptions are constructed empty, then have a filename assigned to them, but the error message in these scenarios is left as the default "unknown" one, which is missing both the exception message and the filename.
This change fixes that by re-calculating both when an except is updated with a `PyObject`. In addition, I consolidated that logic into a private method so that construction & later-updating stay consistent over time.
To verify, I tried to save a project after deleting its containing dir. Before this change:
After change:
This doesn't fix [Issue 4098](https://tracker.freecadweb.org/view.php?id=4098), but it helps with the error msg.
> [Base] Fix lost filename in err msg

- src/Mod/Fem/femexamples/material_nl_platewithhole.py
- src/Mod/Fem/femobjects/material_mechanicalnonlinear.py
- src/Mod/Fem/femsolver/calculix/write_femelement_material.py
String List instead of String should allow for arbitrarily many entries,
theoretically.
Note the defaults previously in `YieldPoint1` an `YieldPoint2` were arbitrary.
Now the list is kept empty by default.
Fixes issue #4720.
--- …
> [FEM] Add tools for more yield points in simple hardening materials

- src/Gui/Document.cpp
Currently, a failure during a document save can return `true` in some cases, which among other possible problems, can cause the App to exit despite not successfully saving the document, resulting in data loss (eg [Issue 4098](https://tracker.freecadweb.org/view.php?id=4098)). This change causes the method to return `false` to properly communicate the failure, which the app-quit process already handles by aborting. 
Steps to reproduce / verify fix:
1. Create a document in its own dir & save it
2. Without closing the document or the app, delete the containing dir
3. Quit the app
**Before this change**: app asks you to save, which fails, but the app exits anyway
**After this change**: app asks you to save, which fails, but the app aborts exit, giving you the chance to "save as" somewhere …
> [Gui] Fix app quitting despite failing to save project

- src/Mod/PartDesign/App/FeatureChamfer.cpp
- src/Mod/PartDesign/App/FeatureDressUp.cpp
- src/Mod/PartDesign/App/FeatureDressUp.h
Improved Part Design chamfer behaviour when faces are selected and non equal chamfer types are used. 
(Distance Distance or Distance Angle)
See  [Forum discussion](https://forum.freecadweb.org/viewtopic.php?f=19&t=62084) for background.
_This is resubmission of #5029 with clean commit history and review feedback addressed._
**Note**: If you …
> Part Design: Improved chamfer behaviour when faces are selected and non equal chamfer types are used

- src/App/Link.cpp
LGTM complains that the use of "obj" as the loop variable here hides the parameter "obj". To silence the warning, rename the loop variable.
> [App] LGTM fix - rename loop variable

- src/App/Expression.cpp
- src/App/ObjectIdentifier.cpp
- src/App/PropertyLinks.cpp
In several instances local variables are created whose name is the same as a parameter, which LGTM warns about: this commit renames the local variables with non-conflicting names.
> [App] Fix LGTM warning decl hides param

- src/Mod/Draft/draftguitools/gui_snapper.py
ref. https://forum.freecadweb.org/viewtopic.php?f=23&t=62274&sid=4c9d07255e4f0db219b661c345768319
If the cursor is over a Face and no SnapCenter is active, the snapToObject method returns the current cursor point instead of None. Doing so the snap() method does not check for extension and grid snaps.
It seems this is a bug since the snap() already contains the deleted code.
One note: the no snaps case was moved before the lastObj setting, since if no snap point was found, it's not right to set it to a non snapped object.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to …
> Draft: fix Snapper GridSnap not working over a face

- src/App/Document.cpp
While applying a `BackupPolicy` during a `Document` save, there are two error cases where the project's file will not contain the latest changes, but only a warning was being logged, while the save was considered successful. Not only is that technically incorrect, but it can lead to data loss, such as on app quit.
This fix addresses that by throwing an exception, which will abort the save, inform the user, and give them a chance to take alternate action.
1. Create a test directory and save a project in there (empty is fine)
2. Make some change in the project, but don't yet save, and leave it open in FreeCAD
3. Set the sticky bit of the dir, and change owner (eg `chmod +t <dir> && sudo chown root <dir>`)
4. Lock the main project file by changing its ownership, while retaining read …
> App: Abort save when unable to finish

- src/Mod/Draft/draftviewproviders/view_wpproxy.py
View properties of a WP proxy should not appear in the "Arch" group. Changed "Arch" to "Draft".
Note that existing WP proxies are not updated. But creating code for that would be over the top IMO. …
> Draft: fix wpproxy view properties group

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
See https://forum.freecadweb.org/viewtopic.php?f=22&t=60370
1st commit is code cleaning that can be cherry-picked if feature change is rejected
2nd commit is feature change, default angle set to 15°, can be changed by user with 'BaseApp/Preferences/Mod/Sketcher/RadiusDiamConstraintDispAngle' -- will document in wiki once/if PR is merged
https://user-images.githubusercontent.com/48731257/126631504-531e81f7-6e1b-47ec-b073-40d498fc820c.mp4
> [Sketcher] Display radius/diameter constraints with some angle (+ code cleaning)

- src/Mod/Draft/draftviewproviders/view_base.py
2 edit mode issues were fixed:
1. Double clicking a Draft object in the Tree would result in an error if the Draft WB was not loaded. Now there is a warning.
2. The introduction of Std_UserEditMode means that edit mode can be non-zero. This required a modification of the unsetEdit function.
Forum discussion about issue 1: https://forum.freecadweb.org/viewtopic.php?f=23&t=59179
@0penBrain Can you have a look at the unsetEdit function? Maybe there is a better way to do this? …
> Draft: fix 2 edit mode issues

- src/Gui/Application.cpp
- src/Gui/GuiApplication.cpp
- src/Gui/GuiApplication.h
More details in the commit message
> [Gui] Allow dot as decimal separator for locales not using it as thousand separator

- src/Base/Rotation.cpp
Following PR #5027, some cases are still wrongly handled (see forum discussion on previous PR).
Tolerance used for this PR is the one used in OCC for the same computation. I didn't find any rational for it, nor did I make any incertitude computation to check it.
> [Core] Rotation : improve gimbal lock handling

- src/Mod/Path/PathScripts/PathMillFace.py
The four included commits are well organized and defined.  This PR fixes usage of `Face Region` boundary shape paths, leaving an existing collision problem intact.  The fix addresses application of `Clear Edges` toggle and `Exclude Raised Areas` when using `Face Region` as the boundary shape.  Other commits are LGTM and documentation purposed.
This PR is initiated by a prompt from @luzpaz  in the gitter.im/FreeCAD/Path chatroom about LGTM cleanup for the module.  While addressing the LGTM, I addressed the `Face Region` problem identified and added some documentation in the code.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you …
> [Path] Fix `Face Region` boundary shape usage and LGTM cleanup

- src/Mod/Path/PathScripts/PathDressupRampEntry.py
This PR has two commits.
- The first fixes the issue.  It adds a `Base.Active` check to determine if the Base is Active.  If the Base is Inactive, the new code sets the `obj.Path` property to the same inactive message used in PathOp module and the `execution()` method returns immediately, stopping further execution.
- The second is purely a Black code formatting application, which makes the PR much larger than the actual fix.
And please …
> [Path] Fix for inactive ramp dressup base operation

- src/Mod/AddonManager/addonmanager_utilities.py
The URLs used to detect whether a repo is at github, gitlab, or framagit could potentially be mis-detected by a maliciously-crafted URL, resulting in incorrect detection of the README file, etc. To silence the LGTM warning about this, proper URL sanitization and comparison is now used.
---
> [Addon Manager] Silence LGTM warnings about urls

- src/Mod/Mesh/App/Core/MeshIO.cpp
- src/Mod/Mesh/App/MeshTestsApp.py
- src/Mod/Mesh/App/TestData/NASTRAN_Test_GRID_CTRIA3.bdf
- src/Mod/Mesh/CMakeLists.txt
Add a test for the CTRIA3 element, and add code to check the used nodes and cancel the file load if they don't all exist.
---
> [Mesh] Improve Nastran unit tests

- src/App/Document.cpp
Files opened by running `freecad xxxx.FCStd` or similar relative paths could not
be saved because of new code introduced to create parent directories. See
https://github.com/FreeCAD/FreeCAD/pull/4996#issuecomment-922370077 and
https://forum.freecadweb.org/viewtopic.php?f=13&t=62319&p=534156#p534156.
--- …
> [App] Fix regression introduced by PR #4996

- src/Mod/OpenSCAD/OpenSCADTest/app/test_importCSG.py
- src/Mod/OpenSCAD/OpenSCADUtils.py
- src/Mod/OpenSCAD/Resources/ui/openscadprefs-base.ui
In 2021.01 OpenSCAD added the ability to read from stdin and write output to stdout: this allows us to communicate with an OpenSCAD process that does not have read/write access to the same directories that FreeCAD does (for example, if one or the other is installed via a Snap package).
This commit adds an additional preference to the OpenSCAD workbench allowing the user to choose between communication methods, as well as to optionally specify their own temporary directory for the data transfer, for use in cases where their version of OpenSCAD is installed via Snap, etc., but does not yet support the piped input and output.
---
> [OpenSCAD] Add ability to communicate over stdin/stdout (to support Snaps, etc.)

- src/Mod/Draft/DraftGui.py
Also fixed misspelled related in-command shortcuts.
Forum topic: https://forum.freecadweb.org/viewtopic.php?f=23&t=60579
---
> Draft: prevent negative snaprange

- src/Mod/Mesh/App/CMakeLists.txt
- src/Mod/Mesh/App/Core/MeshIO.cpp
- src/Mod/PartDesign/App/json.hpp
Pop 'mesh' library c++ stranderd to c++17
Add required <string_view> header
Without this `gcc:11` complains about `std:string_view` being an undefined reference:
```cpp
/build/freecad-git/src/FreeCAD/src/Mod/Mesh/App/Core/MeshIO.cpp:1686:35: note: ‘std::string_view’ is only available from C++17 onwards
/build/freecad-git/src/FreeCAD/src/Mod/Mesh/App/Core/MeshIO.cpp:1688:31: error: ‘string_view’ is not a member of ‘std’
1688 |             auto xView = std::string_view(&line[8+16+16], 16);
|                               ^~~~~~~~~~~   
```
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, …
> Fix linux build: undefined std:string_view

- src/Mod/PartDesign/Gui/ViewProviderLoft.cpp
- src/Mod/PartDesign/Gui/ViewProviderLoft.h
- src/Mod/PartDesign/Gui/ViewProviderPipe.cpp
- src/Mod/PartDesign/Gui/ViewProviderPipe.h
Double-click is already handled by PartDesign::ViewProvider::doubleClicked()
Overridings in Loft & Pipe brings no specific behavior
By removing overridings, behavioral consistency is improved both in ...
... undo commands & body activation management when PartDesign items ...
... are double-clicked
> [PartDesign] Remove useless function overriding

- src/App/Application.cpp
- src/App/Application.h
- src/App/Document.cpp
- src/App/Document.h
- src/App/DocumentObserver.h
- src/App/PropertyLinks.cpp
- src/Gui/Document.cpp
- src/Gui/ViewProviderDocumentObject.cpp
- src/Mod/Part/Gui/ViewProviderExt.cpp
Forum thread https://forum.freecadweb.org/viewtopic.php?p=495078#p495078
The problem happens when partial loading is enabled. If document A contains a link to some object in document B, it will load B as partial document with only that object and its necessary dependencies. But if document A contains another link to some object in document C which also has a link to some object in document B, the link in document C may not be restored, because document B is partially loaded without the linked object. This patch will check for this case and reload document B for more objects.
> Fix external document loading

- src/Mod/PartDesign/Gui/Workbench.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/6
These commands are already translated but for some reason we need to add them again to `Workbench.cpp` so they will be in fact translated.
> PD: Expose missing commands to translation in Measure dropdown menu

- src/Mod/Sketcher/Gui/TaskSketcherValidation.ui
This PR refactors the Validate Sketch UI to avoid confusion regarding 'Highlight open vertexes' following https://forum.freecadweb.org/viewtopic.php?f=8&t=62936&start=10#p540189
Precisely it separates this function from 'Missing coincidences' ones.
Also it adds tooltips so more information is provided to the user
> [Sketcher] Validate Sketch : UI refactoring to avoid confusion

- src/App/Application.h
- src/Mod/Fem/femtaskpanels/task_material_common.py
Found via `codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,apoints,ba,beginn,behaviour,bloaded,bottome,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,inout,ist,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oder,ontop,orgin,orginx,orginy,ot,pard,parms,pres,programm,que,recurrance,rougly,seperator,serie,sinc,strack,substraction,te,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Base/swig*,./src/ …
> Fix typos in source comments [skip ci]

- src/Mod/Part/Gui/ViewProvider2DObject.cpp
- src/Mod/Part/Gui/ViewProvider2DObject.h
- src/Mod/Sketcher/Gui/TaskSketcherGeneral.cpp
Problem has been reported [here in the forum](https://forum.freecadweb.org/viewtopic.php?f=10&t=63210)
From user point of view, it makes the sketcher grid disappear when a sketch is saved while in Edit mode.
The reason is that when entering edit mode, the sketch is made not visible so that its "TopoShape" doesn't duplicates the sketch geometry on screen.
However the grid shall always been shown in Edit mode --if enabled-- (and in normal mode, only if ShowOnlyInEditMode is false).
> [ViewProvider2DObject=>Sketcher] Fix grid visibility management

- src/Mod/MeshPart/App/AppMeshPart.cpp
- src/Mod/MeshPart/App/AppMeshPartPy.cpp
- src/Mod/MeshPart/App/CurveProjector.cpp
- src/Mod/MeshPart/App/CurveProjector.h
- src/Mod/MeshPart/App/MeshAlgos.cpp
- src/Mod/MeshPart/App/MeshAlgos.h
- src/Mod/MeshPart/App/PreCompiled.cpp
- src/Mod/MeshPart/App/PreCompiled.h
- src/Mod/MeshPart/Gui/AppMeshPartGui.cpp
- src/Mod/MeshPart/Gui/Command.cpp
- src/Mod/MeshPart/Gui/MeshFlatteningCommand.py
- src/Mod/MeshPart/Gui/PreCompiled.cpp
- src/Mod/MeshPart/Gui/PreCompiled.h
- src/Mod/MeshPart/Init.py
- src/Mod/MeshPart/InitGui.py
Adding some uniformity to the headers of the `src/Mod/MeshPart`. I'm not sure if the `blame` info for some of the files is accurate since the source code wasn't originally on github and some of that history is not available.
> MeshPart: fix header uniformity + remove superfluous whitespace

- src/Mod/PartDesign/App/FeatureLoft.cpp
- src/Mod/PartDesign/App/FeatureLoft.h
- src/Mod/PartDesign/App/FeaturePipe.cpp
- src/Mod/PartDesign/App/FeaturePipe.h
- src/Mod/PartDesign/Gui/TaskLoftParameters.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
- src/Mod/PartDesign/Gui/TaskSketchBasedParameters.cpp
- src/Mod/PartDesign/Gui/TaskSketchBasedParameters.h
With these changes, one face per solid can be added as either the first
"profile" or subsequent sections in loft and pipe.
These changes depend on `App::PropertyXLinkSubList` preserving the order in which
sections are added.
A minor change this also adds is that when a solid's face is selected that face
is mentioned in the fields instead of the solid (eg `Box:Face1` instead of
`Box`).
> [PD] Support adding solid faces for loft and pipe sections

- src/Mod/TechDraw/Gui/Workbench.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/82  
The dropdown `TechDraw > Extensions: centerlines and threading` (submenu) is too long and superfluous. Renamed to: `Extensions: Centerlines/Threading`. Also exposed to translation.
> TechDraw: Renames submenu command + exposes to translation

- src/Gui/Workbench.cpp
Related to https://github.com/FreeCAD/FreeCAD-translations/issues/51 and https://github.com/FreeCAD/FreeCAD-translations/issues/16
> Gui: expose the 'Link Actions' toolbar icon to translation

- src/Mod/PartDesign/Gui/TaskLoftParameters.cpp
- src/Mod/PartDesign/Gui/TaskLoftParameters.h
- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.h
Without this, when you press, for example, the "Add Section" button, do nothing, then press "Remove Section" button, the first button remains pressed.
> [PD] Clear other taskbox buttons in loft and pipe when one pressed

- src/Mod/PartDesign/Gui/ViewProviderAddSub.cpp
`ViewProviderAddSub::updateData` assumed that the property provided was named.
> [PD] Check if property is named before `strcmp`

- src/Mod/PartDesign/App/FeatureLoft.cpp
- src/Mod/PartDesign/App/FeatureLoft.h
- src/Mod/PartDesign/App/FeaturePipe.cpp
- src/Mod/PartDesign/App/FeaturePipe.h
- this was missing in PR #5155
This should be correct, but it crashes FreeCAD. The reason for the crash is line https://github.com/FreeCAD/FreeCAD/blob/master/src/App/PropertyLinks.cpp#L4322
When I uncomment it, it does not crash, but it does also not to the property value restoration.
@realthunder Can you please have a look? I cannot find the cause.
> [PD] handle changed property for loft and pipe

- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.h
Currently:
- only sweep path is toggled correctly in its visibility, the profile is never shown
- the sections are always shown
This PR fixes this inconsistency reported here: https://forum.freecadweb.org/viewtopic.php?f=19&t=63544
> [PD] fix sweep visibility bug

- src/Gui/CommandView.cpp
- src/Gui/Document.cpp
- src/Gui/Tree.cpp
- src/Gui/Tree.h
- src/Gui/ViewProviderDocumentObject.cpp
- src/Gui/ViewProviderDocumentObject.h
- src/Gui/ViewProviderExtension.h
- src/Gui/ViewProviderOrigin.h
- src/Gui/ViewProviderOriginGroupExtension.h
- src/Mod/Part/Gui/ViewProviderBoolean.h
- src/Mod/Part/Gui/ViewProviderMirror.h
- src/Mod/PartDesign/Gui/ViewProviderLoft.h
- src/Mod/PartDesign/Gui/ViewProviderPipe.h
- src/Mod/Test/CMakeLists.txt
- src/Mod/Test/InitGui.py
- src/Mod/Test/TreeView.py
This pull request gives the user a possibility to reorder the document tree view items.
For more implementation details please see my contribution to the dedicated forum topic:
[Ticket #3923 - change order in tree view](https://forum.freecadweb.org/viewtopic.php?f=3&t=35316)
> [Gui] Issue #3923 - Add arbitrary Tree View item ordering

- src/Mod/PartDesign/App/FeaturePocket.cpp
- src/Mod/PartDesign/App/FeaturePocket.h
- src/Mod/PartDesign/Gui/TaskPocketParameters.cpp
- src/Mod/PartDesign/Gui/TaskPocketParameters.h
- src/Mod/PartDesign/Gui/TaskPocketParameters.ui
This PR adds the functionality of pads to pad along either a custom direction or along an edge to pockets.
So with this PR Pad and Pocket are on the same level of functionality.
Here is a screencast of what packet can now do:
> [PD] add feature to set direction for pockets

- src/Mod/PartDesign/Gui/Command.cpp
Support for solid faces while building loft by pre-selecting profile and sections was missing in PR #5155.
> [PD] Allow body faces when making loft by pre-selection

- src/Gui/GuiApplication.cpp
This PR improves the decimal point substitution mechanism that allows it to be conform to locale settings (introduced in PR #3256), when it is entered from the numerical pad : 
* The PR simplifies the mechanism. The current one is a bit weird because at the time I did it I observed a strange behavior of Qt modifiers() value. It happens that this weirdness comes from the OS, so it doesn't have to be fixed in Qt. Fixes exists in OS
* Following @wwmayer [post here](https://forum.freecadweb.org/viewtopic.php?f=8&t=62546&start=20#p544339), the mechanism has been extended to cope with substitution in a more general way
The algorithm is now simple : 
If comma or period key event coming from numerical keypad, compare with locale decimal point value. If different, tamper the event substituting …
> [Core] Improve decimal point substitution mechanism

- src/App/Document.cpp
- src/App/DynamicProperty.cpp
- src/App/DynamicProperty.h
- src/App/Enumeration.cpp
- src/App/Expression.cpp
- src/App/Expression.h
- src/App/ExpressionParser.h
- src/App/ObjectIdentifier.cpp
- src/App/ObjectIdentifier.h
- src/App/Property.cpp
- src/App/PropertyContainer.h
- src/App/PropertyContainerPy.xml
- src/App/PropertyContainerPyImp.cpp
- src/App/PropertyExpressionEngine.cpp
- src/App/PropertyExpressionEngine.h
- src/App/PropertyLinks.cpp
- src/App/PropertyLinks.h
- src/App/PropertyStandard.cpp
- src/App/PropertyStandard.h
- src/App/Range.h
- src/Gui/ViewProviderDocumentObject.cpp
- src/Gui/propertyeditor/PropertyEditor.cpp
- src/Gui/propertyeditor/PropertyEditor.h
- src/Gui/propertyeditor/PropertyItem.cpp
- src/Gui/propertyeditor/PropertyItem.h
- src/Mod/Spreadsheet/App/PropertySheet.cpp
This is the second stage of cherry-picking commits from @realthunder's PR #2862 -- Configuration Table using Spreadsheet. The main work of this set of commits is to introduce the `HIDDENREF()` function (formerly the `HREF()` function). To borrow from [realthunder's documentation](https://github.com/realthunder/FreeCAD_assembly3/wiki/Expression-and-Spreadsheet#href):
> `hiddenref()` stands for hidden reference, which accepts a single argument containing an property reference. This function hides any object reference inside the argument to work around cyclic dependency error. You need to be careful when using `hiddenref()` because skipping dependency checking may result in unstable recomputing order, and thus given unexpected result. As a rule of thumb, it will be safe if `hiddenref()` is …
> App: Merge realthunder PR 2862, stage 2

- src/Mod/Draft/importDXF.py
To avoid a warning in the Report view importDXF.py should use make_layer.
---
> Draft housekeeping: importDXF.py should use make_layer

- src/Mod/Tux/NavigationIndicatorGui.py
- the PR adjusts the size of the navigation style status bar so that it is wide enough to contain the text + the space for the combobox button
- also sort the entries since as it is, it just reflects the order the styles were added in the development
With the fix:
Without the fix:
The size adjustment is done using Qt's adjustSize() command and the space consumed be the combobox dropdown indicator is done by adding two spaces to the button text since on different OSes the necessary space might be different.
> [Tux] fix navigation status bar width

- src/Mod/PartDesign/App/FeatureLoft.h
- src/Mod/PartDesign/App/FeaturePipe.h
- src/Mod/PartDesign/Gui/TaskLoftParameters.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
This change is necessary since we restrict part-design features to only use
other features from the same body.
> [PD] Use `PropertyLinkSubList` for loft and sweep sections

- src/App/DynamicProperty.cpp
- src/App/PropertyContainer.cpp
- src/Mod/Path/PathTests/TestPathStock.py
- src/Mod/Test/Document.py
Do not auto rename when adding dynamic property with an invalid or existing name, but throw exception instead, because there is no easy way for Python code to find out the auto selected name. Parameter `BaseApp/Preferences/Document/AutoNameDynamicProperty` can be used to revert back to old behavior.
@chennes This is splitted out from #2758. I'll see if I can split out others.
> Do not auto rename when adding dynamic property

- src/Mod/Spreadsheet/App/PropertySheet.cpp
This PR contains 3 commits :
* First 2 are small fixes/improvements not directly related to bug
* Last one is the real, that solves the issue by rejecting alignment change on merge cells (except primary top-left one)
This is done according community poll : https://forum.freecadweb.org/viewtopic.php?f=3&t=62925
> [Spreadsheet][Bugfix] Solves issue when changing alignment of merged cells

- src/Mod/PartDesign/App/FeatureLoft.cpp
- src/Mod/PartDesign/Gui/Command.cpp
- src/Mod/PartDesign/Gui/TaskLoftParameters.cpp
The `BRepOffsetAPI_ThruSections` method that forms the crux of loft supports the first and the last sections to be vertices instead of wires.
Addresses issue#4607.
> [PD] Support for point sections in loft

- src/App/PropertyLinks.cpp
Problem reported [here](https://github.com/realthunder/FreeCAD_assembly3/issues/928)
> App: fix subname encoding when saving property links

- src/Gui/CommandPyImp.cpp
- src/Gui/Document.cpp
Avoids possible translation mistakes by only exposing non-whitespace strings.
> Gui: remove superfluous whitespace from translation string

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
Standard symbol \u2300 currently used generates text misalignment/cutout on some environments
Replaced with \uD8 (capital O with stroke) that solves the issue -- and looks better
https://forum.freecadweb.org/viewtopic.php?f=10&t=63041&start=10#p547303
> [Sketcher] Change diameter symbol used in presentation string, fixes #4779

- src/Mod/Draft/draftguitools/gui_shapestrings.py
The S,S shortcut was used twice: for Draft_ShapeString and Draft_SetStyle. I suppose Draft_SetStyle will be used more often and have therefore removed the shortcut for Draft_ShapeString.
---
> Draft housekeeping: SS-shortcut used twice

- src/Mod/Draft/draftobjects/draftlink.py
When the shape of a Draft_Point or Part_Vertex is copied the Placement of the copy does not match that of the original shape. Resetting the Placement is then problematic. We need to use transformGeometry.
Forum topics:
https://forum.freecadweb.org/viewtopic.php?f=3&t=63591
https://forum.freecadweb.org/viewtopic.php?f=22&t=63672
---
> Draft: fix array issue with Draft_Point and Part_Vertex.

- src/Mod/PartDesign/App/FeaturePipe.cpp
- src/Mod/PartDesign/Gui/Command.cpp
Similar changes to PR #5170, except uses `BRepOffsetAPI_MakePipeShell` instead.
Not ready for merge, but in good enough condition for tests. Certain bugs exist which I will describe in comments as I find them.
>  [PD] Support for point sections in pipe/sweep

- src/Mod/PartDesign/App/FeatureDressUp.cpp
- src/Mod/PartDesign/App/FeatureLinearPattern.cpp
- src/Mod/PartDesign/App/FeatureLoft.cpp
- src/Mod/PartDesign/App/FeatureMirrored.cpp
- src/Mod/PartDesign/App/FeaturePipe.cpp
- src/Mod/PartDesign/App/FeaturePolarPattern.cpp
- src/Mod/PartDesign/App/FeatureSketchBased.cpp
- src/Mod/PartDesign/Gui/Command.cpp
- src/Mod/PartDesign/Gui/ReferenceSelection.cpp
- src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
- src/Mod/PartDesign/Gui/ViewProviderShapeBinder.cpp
Used when finding subelements of a feature. Many of the comparisons used to also
check for string lengths, but as far as I can tell they are not strictly
necessary (see https://www.cplusplus.com/reference/string/string/substr/) and
just `substr` can be used without them. However, `compare` explicitly is for
comparing, and does not make a new object that `substr` does.
> [PD] Use `compare` to compare strings instead of `substr`

- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
- src/Mod/PartDesign/Gui/TaskHelixParameters.ui
Previously, only the vertical and horizontal axis of the profile was
selectable in the task panel of the additive/subtractive helix. Now the
profile's normal axis can be selected, too. This now allows to create
helical extrusions or "twisted pockets".
The order of the GUI entries was chosen to be in line with the order of
axis selection of the multi-transform parameters.
The actual feature's implementation needed adaption for this special case
as in some places a unit vector (`gp_Dir`) was derived from the cross-
product of axis and profile normal -- a null-vector when the axis *is*
the normal. This caused the gp_Dir's ctor to throw.
**Note**: If you don't have wiki access, then please …
> [PD] Helix: Offer profile's normal as axis

- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.h
- src/Mod/PartDesign/Gui/TaskPipeScaling.ui
Now that we have the feature that sweeps can have vertices as end or begin of a sweep, there is the need for the feature to move sections. For example vertices may only be the last section.
Here is a use case:
> [PD] allow to move sweep sections

- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/App/FeatureHelix.h
- src/Mod/PartDesign/Gui/TaskHelixParameters.h
Helices that become smaller with every turn are geometrically perfectly valid. Therefore we cannot forbid this.
(For example when creating a helix from a face you often cannot move it so that you can apply a positive growth.)
Here is a use case: [Helix-Tests.zip](https://github.com/FreeCAD/FreeCAD/files/7614657/Helix-Tests.zip)
> [PD] allow negative helix growth

- src/Mod/Draft/draftguitools/gui_snapper.py
1. Draft_Snap_Parallel only worked beyond the endpoints of the edge.
2. It was very hard to select an edge for Draft_Snap_Parallel if no other snaps were active.
3. Only two snap objects were stored.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?p=547723#p547723
The main change is the last. The `self.lastObj` list now has a length of 0-8 items and is cleared in the `off` function. Having the list hold more than 2 items alleviates the problem where accidentally hovering too long over two random edges would mean that the edge selected for Draft_Snap_Parallel was no longer available. Using 8 as the max. length for the list is debatable, but that can easily be changed later.
**Note**: …
> Draft: fix 3 snap issues

- conda/build.sh
- src/Gui/CommandView.cpp
- src/Gui/GestureNavigationStyle.cpp
Make all mentions of `spacemouse` in the code a single word (with no whitespace) so we can parse the source code more accurately to find mentions of it if necessary.
> Use correct name `spacemouse` so it's uniform and searchable in our code

- src/Mod/Draft/draftobjects/draftlink.py
This PR fixes a regression introduces with #5180.
See forum topic:
https://forum.freecadweb.org/viewtopic.php?f=3&t=64246
---
> Draft: fix regression draftlink.py

- src/Mod/Draft/draftfunctions/offset.py
- src/Mod/Draft/draftgeoutils/offsets.py
The Draft_Offset command did not work with Part_Lines.
Additionally (offset.py):
`"Draft.offset: Unable to create an offset"` message was printed even if `newobj` was created.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=64346
> Draft: Fix Part_Line offset issue

- src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp
> Fix Qt deprecation warning. QPrinter::setOrientation() is obsolete.

- src/Mod/Draft/draftguitools/gui_arcs.py
This PR fixes the following Draft_Arc_3Points task panel issues:
1. Wrong title and icon.
2. Continue toggle missing.
The command uses `Gui.Snapper.getPoint` and does not have a dedicated task panel. I have therefore worked with `Gui.Snapper.ui` for the desired changes.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=58234
Note that this PR does not address all issues mentioned in the topic.
---
> Draft: fix Draft_Arc_3Points task panel issues

- src/Mod/PartDesign/App/FeatureHelix.cpp
Up to now the property descriptions (e.g. shown as tool tip in the property grid) just repeat the property's name, which was not very helpful. With this PR most strings are based on descriptions from the [wiki](https://wiki.freecadweb.org/PartDesign_AdditiveHelix). Some have been extended where I saw need (once accepted, I can adapt the wiki, too). Note that I'm not a native speaker, though.
I also plan to make those property descriptions [translatable](https://tracker.freecadweb.org/view.php?id=0002524) and use them as tooltip in the helix' task panel. As you seem to prefer several smaller PRs I did not include this here. It may also requires some more discussion.
> PD: Enhance the helix property docs

- src/Gui/ToolBarManager.cpp
forum topic:
https://forum.freecadweb.org/viewtopic.php?f=34&t=64528
Adds the name of the toolbar as a tooltip to the toolbar in between braces.  Example, if toolbar name is File, then the tooltip is [File].  Can be disabled in user parameters:  BaseApp/Preferences/MainWindow/ToolBarNameAsToolTip (boolean, default = true).
> [MainWindow] Add toolbar name as toolbar's  tooltip

- src/3rdParty/libE57Format/src/E57XmlParser.h
Some system have trouble to building the e57 library. Details will you found here: 
[Build failure because of E57XmlParser.cpp](https://forum.freecadweb.org/viewtopic.php?f=4&t=64567)
> 3rdParty/E57Lib: Include limits to header

- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
Depending on the input mode, either `Growth` or `Angle` is used to create a conical or flat spiral. The respective other can easily be calculated to give consistent view. This is already done for the other properties, e.g. `Height` is calculated from `Pitch` and `Turns`.
With this PR, the same is done for `Angle` and `Growth`.
> PD: Fix assignment of helix' Angle/Growth properties

- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/App/FeatureHelix.h
With this PR minor tweaks are done to the additive/subtractive helix' properties:
- The `HasBeenEdited` property is only used internally to check wether to
fill certain other parameters with initial values. So there is no need
show it in the property grid at all.
- The `Outside` property is only used in the subtractive helix and thus
hidden for the additive helix.
- Those properties which are calculated according to the current input mode (i.e. not directly entered by the user) are now set read-only. Previously they have been writable but their value was ignored and overwritten at the next recompute
- The input mode and reference axis have been placed further up in the list of properties to become more prominent.
This is a bundle of three independent commits, so I suggest to review them …
> PD: Fix helix property visibility/writability

- src/Mod/Path/PathScripts/PathAdaptive.py
Discretize of 0.0001 is okay for inches, but for metric <1microns would be quite small, this fixes some issues when generating paths for curves that look inward.
Since the internal unit is mm 0.0001 must have been set when having inch in mind.
I found following post in the forum: https://forum.freecadweb.org/viewtopic.php?f=15&t=42755
I have experienced similar issues with other curves in my object.
This is a sample where I use bsplines for creating extensions to a face (I also had that issue when generating adaptive paths - with the updated accuracy it does not happen anymore):
https://streamable.com/jfbin6
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items …
> [PATH] change discretize value to fix issues

- src/Mod/Draft/draftviewproviders/view_label.py
This PR fixes the bug where the boundingbox of the text was not correct. This resulted in misplaced texts and frames.
Additionally:
* The color and drawstyle of the leader are also applied to the frame.
* `setDisplayMode` function was renamed to `getDisplayMode`.
* The `updateData` and `onChanged` functions did not work properly. There was an error if a document with a Draft_Label with a frame was opened. Changing some properties would not result in an immediate update of the viewobject.
* If the `DisplayMode` is `"2D text"` no frame is created and `TextAlignment` is ignored.
* The  `draw_frame` function was renamed to `update_frame`.
Note that the handling of the `Justification` property is a bit peculiar. It is linked to the `StraightDistance` property. I have ignored that property in …
> Draft: fix Draft_Label viewprovider

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftguitools/gui_labels.py
- src/Mod/Draft/draftmake/make_label.py
- src/Mod/Draft/draftobjects/label.py
The label type list for Draft_Labels was not consistently implemented. Instead of updating a hard-coded list in several files I have decided to create a function `get_label_types` in `label.py`.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=58234
---
> Draft: Draft_Label fix label type list

- src/App/ObjectIdentifier.cpp
Reported in forum thread [here](https://forum.freecadweb.org/viewtopic.php?f=10&t=64718&sid=a720fe8c793e26c1625f2eab0539cd7f) and [here](https://forum.freecadweb.org/viewtopic.php?f=3&t=64699&start=10)
The exception is thrown by `access()` because it does not support getting value from `Property::getPathValue()`, to prevent recursive (some property overrides `getPathValue()` to call `ObjectIdentifier::getPyValue()` which in turn calls `access()`).
> App: catch Base::Exception in ObjectIdentifier::getDep()

- src/Mod/Sketcher/App/SketchObject.cpp
When new control points are created in a b-spline in a sketch, do not constrain
their weights to be equal to the first, unless they are already equal. This way
if we have unequal weights to begin with and OCC has computed the appropriate
weights so that the new spline is closer to the original, the weights are not
disturbed.
> [Sketcher] Constrain new B-spline pole weight only if equal to first

- src/Mod/Mesh/Gui/RemeshGmsh.cpp
- src/Mod/Mesh/Gui/RemeshGmsh.ui
- src/Mod/MeshPart/Gui/Tessellation.cpp
I was informed that Gmsh names itself with a capital G. I had a look and in FEM it is already named Gmsh, but not in the Mesh WB. Therefore this PR.
(The other UI file changes than the pure renaming were automatically done by Qt's designer.)
> [Mesh] rename gmsh -> Gmsh

- src/Gui/DlgReportView.ui
- src/Gui/ReportView.cpp
I introduced FreeCAD to several people and see that especially newbies are confused with all the warnings they get but cannot understand.
The solution was to change that the report view panel is not automatically shown on every warning.
This PR does this.
More experienced users can anytime enable the option. Thus this PR has not much impact but obviously makes life easier for beginners.
> [GUI] don't show report view on warnings by default

- src/Mod/Sketcher/Gui/EditModeInformationOverlayCoinConverter.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
Found via `codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,apoints,ba,beginn,behaviour,bloaded,bottome,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childrens,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,inout,ist,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oder,ontop,orgin,orginx,orginy,ot,pard,parm,parms,pres,programm,que,recurrance,rougly,seperator,serie,sinc,strack,substraction,te,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm,./src/CXX,./src/zipios++,./src/Ba …
> Sketcher: fix source comment typos

- src/Gui/GestureNavigationStyle.cpp
- src/Gui/MayaGestureNavigationStyle.cpp
Sent when trying to set rotation center without an object under the cursor and can be annoying if report view is set to show with warnings. Would it be ok to just remove the message entirely? I think other navigation modes (besides gesture and maya that are adressed in this PR) don't show it. Also, why do we even need an object under the cursor?
> Mouse navigation: change unnecesary warnings to messages

- src/App/PropertyExpressionEngine.h
Since the Spreadsheet: support cell binding commit, I got trouble by building freecad. I didn't find similar reports in install/compile forum. So I will only use the old version of typedef for macos. Better solutions are welcome.
See [trouble details](https://github.com/FreeCAD/FreeCAD/commit/68fca409833ca0c8c3811ad4efddcfcc3e2e4255#commitcomment-62364932)
> Spreadsheet: Fix trouble with clang and MacOS

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/AddonManager.ui
- src/Mod/AddonManager/AddonManagerOptions.ui
- src/Mod/AddonManager/CMakeLists.txt
- src/Mod/AddonManager/addonmanager_macro.py
- src/Mod/AddonManager/addonmanager_utilities.py
- src/Mod/AddonManager/addonmanager_workers.py
- src/Mod/AddonManager/first_run.ui
- src/Mod/AddonManager/package_details.py
- src/Mod/AddonManager/package_list.py
This PR adds an option to download and display macro metadata. Doing so will also make it searchable using the filter box. The first-launch dialog is expanded to display the most important options, including this one. Note that this will make that dialog re-display for everyone, even those who had already seen the old version of the warning.
> Addon Manager: download and display Macro metadata

- src/Mod/Draft/draftguitools/gui_move.py
- src/Mod/Draft/draftguitools/gui_rotate.py
- src/Mod/Draft/draftguitools/gui_scale.py
Commands when acting on subelements did not load the Draft module. This would lead to an error of the Draft module was not already loaded by another command.
---
> Draft: Commands acting on subelements did not load the Draft module

- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
- src/Mod/PartDesign/Gui/TaskHelixParameters.h
- src/Mod/PartDesign/Gui/TaskHelixParameters.ui
By reusing the property docs as tooltip we avoid maintaining the same information in two places. The property descriptions have been made translatable, too, to ensure a fully translatable UI.
If we agree on this in general, I can adapt the other PartDesign features/taskpanels as well. However, before putting more work into this, I want to hear your comments.
I followed the methodology @wwmayer and @yorikvanhavre have introduced long time ago, cf. [Issue 0002524](https://tracker.freecadweb.org/view.php?id=0002524). It is used at least in the Arch, Draft and Path WBs and I think (not only) the PartDesign WB can benefit from this work, too.
----------
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull …
> PD: Make helix property descriptions translatable and reuse them as task panel tooltips

- src/Mod/PartDesign/Scripts/Spring.py
Part.Wire.makePipeShell() now takes boolean arguments instead of integer arguments.
To use the script: in the python console enter:
```
from Scripts import Spring
Spring.makeMySpring()
```
> [PartDesign::Scripts::Spring.py] update old example script

- src/Mod/Path/PathScripts/PathSanity.py
use subprocess.Popen() to avoid executing arbitrary code
---
> [PATH] fix #4810

- .github/labels.yml
- .github/workflows/labeler.yml
This workflow will triage newly created or reopened PR and apply the label(s) based on the paths that are modified in the PR.
The Labels are defined in the `.github/labels.yml` file.
For more information, see: https://github.com/actions/labeler
It can be tested in my Github Repo https://github.com/Floriansimmer/FreeCAD
> Github: Automatically label new pull requests based on the paths of files being changed

- src/Mod/PartDesign/App/FeatureTransformed.cpp
This fixes the bug identified in
https://forum.freecadweb.org/viewtopic.php?f=3&t=64900
The original was mistakenly included in the pattern. It is important to not include the original in the pattern because the original might not be at the tip of the feature tree. Including the original will interfere with changes that occur further down in the feature tree
> PD: Fix bug in FeatureTransformed

- src/Mod/PartDesign/App/FeaturePad.cpp
- src/Mod/PartDesign/App/FeaturePocket.cpp
The CI compiler outputs this warning:
`FeaturePad.cpp:101:20: warning: variable 'obj' set but not used [-Wunused-but-set-variable]`
This PR is to see if the CI compiler warning vanishes.
> [PD] get rid of a CI compiler warning

- src/Mod/Path/PathScripts/post/grbl_post.py
This PR updates grbl_post to detect machine controller-specific commands in commends, and include them literally in the output.
This is useful for including in a job custom commands that a machine controller supports (but that aren't valid gcode).
Usage: add comments to Custom Ops using the format "(MC_RUN_COMMAND: my-custom-command)". The output file will contain a line with "my-custom-command".
> Path: Grbl_post: Allow controller-specific/non-standard gcode commands

- src/Mod/Draft/draftfunctions/scale.py
The `copy_scaled_edge` function should return a wire, not an edge. The `join_wires` function, called in `copy_scaled_edges`, can only handle wires.
---
> Draft: fix scale.py copy_scaled_edge

- src/Mod/Draft/draftutils/groups.py
For consistency the `get_group_contents` function should use `is_group` to identify groups. The code dedicated to Site objects and Drawing pages was removed. Site objects should be handled the same as other groups and the Drawing workbench is obsolete.
Additionally:
1. The recursive call to `get_group_contents` did not receive all arguments from the initial call. This made no sense.
2. Updated the `is_group` function: Space objects should also be considered groups (they can contain equipment f.e.). And identifying LayerContainers by their 'type' is more reliable.
3. Fixed issues with `_tr`. …
> Draft: improve get_group_contents function in groups.py

- src/Mod/Plot/Plot.py
Closes https://github.com/FreeCAD/FreeCAD-translations/issues/60
Also relies on https://github.com/FreeCAD/FreeCAD/pull/5037 to add Plot to the Crowdin `updatets.py` script
> Plot: Expose src/Mod/Plot strings to translation

- src/Mod/Path/PathScripts/PathWaterline.py
This commit fixes the error reported in the forum at [Re: Waterline milling update](https://forum.freecadweb.org/viewtopic.php?f=15&t=33121&start=50#p537787).
This error was introduced when a contributor replaced the `extractFaceOffset()` method from the PathSurfaceSupport.py module with an improved `getOffsetArea()` function in the PathUtils.py module.  The two instances of the improved `getOffsetArea()` calls here in this fix did not get corrected (updated argument lists) when that improvement was originally made.  This fix corrects the argument lists in the two function calls.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you …
> [Path] Fix Waterline error due to invalid arguments in `getOffsetArea()` calls

- src/Mod/Fem/Gui/CMakeLists.txt
- src/Mod/Fem/Gui/TaskFemConstraint.cpp
- src/Mod/Fem/Gui/TaskFemConstraint.h
- src/Mod/Fem/Gui/TaskFemConstraintDisplacement.cpp
- src/Mod/Fem/Gui/TaskFemConstraintDisplacement.h
- src/Mod/Fem/Gui/TaskFemConstraintDisplacement.ui
- src/Mod/Fem/Gui/TaskFemConstraintFixed.cpp
- src/Mod/Fem/Gui/TaskFemConstraintFixed.h
- src/Mod/Fem/Gui/TaskFemConstraintFixed.ui
- src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.cpp
- src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.h
- src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.ui
- src/Mod/Fem/Gui/TaskFemConstraintForce.cpp
- src/Mod/Fem/Gui/TaskFemConstraintForce.h
- src/Mod/Fem/Gui/TaskFemConstraintForce.ui
- src/Mod/Fem/Gui/TaskFemConstraintHeatflux.cpp
- src/Mod/Fem/Gui/TaskFemConstraintHeatflux.h
- src/Mod/Fem/Gui/TaskFemConstraintHeatflux.ui
- src/Mod/Fem/Gui/TaskFemConstraintOnBoundary.cpp
- src/Mod/Fem/Gui/TaskFemConstraintOnBoundary.h
- src/Mod/Fem/Gui/TaskFemConstraintPressure.cpp
- src/Mod/Fem/Gui/TaskFemConstraintPressure.h
- src/Mod/Fem/Gui/TaskFemConstraintPressure.ui
- src/Mod/Fem/Gui/TaskFemConstraintSpring.cpp
- src/Mod/Fem/Gui/TaskFemConstraintSpring.h
- src/Mod/Fem/Gui/TaskFemConstraintSpring.ui
- src/Mod/Fem/Gui/TaskFemConstraintTemperature.cpp
- src/Mod/Fem/Gui/TaskFemConstraintTemperature.h
- src/Mod/Fem/Gui/TaskFemConstraintTemperature.ui
With these changes applied, if nothing is selected while a constraint is being edited, pressing the add/remove button will put the user in an add/remove mode so that on clicking a face/edge in the viewport, that edge/face will be added to/removed from the list of entities to be constrained with the given FEM constraint.
Currently restricted to displacement constraints. I plan to add this to the rest of the constraints and make the behavior consistent with task-views in other workbenches which add/remove boundary entities.
> [FEM] Allow modal adding/removal of geometric entities to constraints

- src/Mod/Path/PathScripts/post/grbl_post.py
The python standard library includes 're' but not 'regex'.  'regex' has features that don't benefit here but has to be installed separately.  So, prefer 're', since it is available everywhere.
> Path: PathArray: use python library 're' instead of 'regex'

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/AddonManagerRepo.py
- src/Mod/AddonManager/CMakeLists.txt
- src/Mod/AddonManager/addonmanager_metadata.py
- src/Mod/AddonManager/addonmanager_utilities.py
- src/Mod/AddonManager/addonmanager_workers.py
- src/Mod/AddonManager/dependency_resolution_dialog.ui
- src/Mod/AddonManager/package_list.py
The main work of this PR is to add a basic dependency checker that will tell the user installing a package what missing dependencies they have. It does not currently offer to install them, just presents them in a list that can either be ignored (installing the package anyway) or cancelled (cancelling the installation).
As a secondary function, this PR cleans up various display items:
1) it checks for an internet connection on startup, and presents a (hopefully clear) error message if one is not found
2) The packages list is correctly filtered on the first refresh
3) The packages list should flicker less during its initial load
4) Very long lists of failed and succeeded updates are consolidated so they don't exceed maximum dialog size
> Addon manager dependency resolver

- src/Mod/PartDesign/Gui/CMakeLists.txt
- src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
- src/Mod/PartDesign/Gui/TaskExtrudeParameters.h
- src/Mod/PartDesign/Gui/TaskPadParameters.cpp
- src/Mod/PartDesign/Gui/TaskPadPocketParameters.ui
- src/Mod/PartDesign/Gui/TaskPocketParameters.cpp
Pad and Pocket share the same UI file therefore change the name to make this clear that changes in that file must be handled for Pad and Pocket
> [PD] rename a UI file

- src/Mod/Draft/draftutils/gui_utils.py
- src/Mod/Draft/draftutils/utils.py
Removed calls to the `_tr` function from two remaining Draft files. Also fixed some issues with the use of the `translate` function in those files.
The `_tr` function is still used in `gui_groups.py`, but this previous PR already takes care of that: https://github.com/FreeCAD/FreeCAD/pull/5301
---
> Draft: fix issues with _tr

- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/App/FeatureHelix.h
Until now FeatureHelix is using Frenet for orienting the profile along the sweep. 
As identified in the forum
https://forum.freecadweb.org/viewtopic.php?f=3&t=65136
this does not give expected results for helices with cone angle for example when constructing a tapered thread, because the thread profile is not consistent (see example below). 
By using an auxiliary helix that is axially offset as a guide we get an improved behavior. 
**Before**
**After**
**Before**
**After**
Results will be the same as before when cone angle is 0.
> PartDesign: Improve orientation behaviour for conical helices

- src/Mod/AddonManager/addonmanager_workers.py
It is possible for an Addon to work in one version of FreeCAD, and not in a later version: to support this idea, the original "Obsolete" list from the FreeCAD-Addons repo was expanded to include a new "Deprecated" list that allows a package to be deprecated "as_of" a particular version of FreeCAD. For example, this enables FreeCAD 0.19 to continue to locate and load the Autoload Addon, but FreeCAD 0.20 won't list it (by default), because that Addon is deprecated in 0.20.
> Addon Manager: Add version-based Addon deprecation

- src/Mod/Draft/WorkingPlane.py
see https://forum.freecadweb.org/viewtopic.php?f=23&t=59903&sid=b6fcc8f0fae011760ddf1cd858ba354a
---
> Draft: Fix projectPoint method

- src/Gui/PythonConsolePy.cpp
Steps to reproduce the crash:
import sys
sys.stderr.write()
#same using sys.stdout.write()
---
> Gui: Prevent crash when calling stderr.write and stdout.write without arguments

- src/Mod/TechDraw/App/DrawPagePy.xml
- src/Mod/TechDraw/App/DrawPagePyImp.cpp
- src/Mod/TechDraw/App/DrawProjGroupItem.cpp
- src/Mod/TechDraw/App/DrawProjGroupItem.h
- src/Mod/TechDraw/App/DrawView.cpp
- src/Mod/TechDraw/App/DrawView.h
- src/Mod/TechDraw/Gui/MDIViewPage.cpp
Although not intended in the design, it is possible for a user to assign a View to multiple Pages by using Std_Copy/Std_Paste and/or Duplicate_Selection.  In the past this caused issues with multiple deletes of QGraphicsItems.
https://github.com/FreeCAD/FreeCAD/pull/5013 and https://github.com/FreeCAD/FreeCAD/pull/5016 solved the multiple delete problem for many cases.  This PR extends that work to handle more cases.
[Additional background here](https://www.forum.freecadweb.org/viewtopic.php?p=559781#p559781)
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help …
> [TD]Improve Handling of View in Multiple Pages

- src/Mod/Arch/ArchAxis.py
- src/Mod/Arch/ArchPanel.py
- src/Mod/Arch/ArchPipe.py
- src/Mod/Arch/ArchStructure.py
- src/Mod/Arch/InitGui.py
PR to fix multiple translation issues. Mostly caused by the wrong context.
---
> Arch: Fix translation issues

- src/Mod/Draft/InitGui.py
- src/Mod/Draft/draftguitools/gui_annotationstyleeditor.py
- src/Mod/Draft/draftguitools/gui_arcs.py
- src/Mod/Draft/draftguitools/gui_arrays.py
- src/Mod/Draft/draftguitools/gui_circulararray.py
- src/Mod/Draft/draftguitools/gui_fillets.py
- src/Mod/Draft/draftguitools/gui_orthoarray.py
- src/Mod/Draft/draftguitools/gui_polararray.py
- src/Mod/Draft/draftguitools/gui_snapper.py
- src/Mod/Draft/draftutils/init_draft_statusbar.py
- src/Mod/Draft/draftutils/init_tools.py
PR to fix multiple translation issues. Mostly caused by the wrong context.
---
> Draft: Fix translation issues

- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.h
Replaces PR #5189 to use `GUI::ButtonGroup` introduced in 792277a848c5bb5d5cfbdf592e8c9991b7fa4889 instead of creating a new one.
> [PD] Use a custom button group in pipe task to allow no button pressed

- src/Mod/PartDesign/Gui/ReferenceHighlighter.h
Correction in `PartDesignGui::ReferenceHighllighter`
> [PD] Correct include guard name

- src/Tools/fcbt/CreatePyModule.py
'CreatesPyModule.py' generates an error when executed with the fcbt-Tool. With this fix the code is the same as in 'CreateModule.py' and works fine.
> Tools: small bug in CreatePyModule.py

- src/Mod/PartDesign/CMakeLists.txt
- src/Mod/PartDesign/PartDesignTests/TestInvoluteGear.py
- src/Mod/PartDesign/TestPartDesignApp.py
There are some basic tests to cover the gear profile and its parameters and some integration tests for the interaction with PD Pad and Pocket.
I followed the same pattern as the other PartDesign tests, e.g. not using PEP8 style method names. Eventually some helper methods could be extracted and moved to the common base framework in Mod/Test, but that's another step.
--------
And please remember to update the Wiki with the features added …
> PD: Add tests for InvoluteGear

- src/App/Document.cpp
- src/App/DocumentPyImp.cpp
- src/App/DynamicProperty.cpp
- src/Base/Type.cpp
- src/Base/Type.h
- src/Base/TypePyImp.cpp
Attempting to delete through a pointer to Base::BaseClass result in undefined behavior for those classes which don't inherit from Base::BaseClass.
Example for reproduce a crash from Python command line:
App.ActiveDocument.addObject("App::DocumentObjectExtension")
#segmentation fault.
In the Python implementation of Base::Type, calls to getPyObject() from classes that don't have the method also generates segmentation fault, for example:
e = App.Base.TypeId.fromName("App::LinkExtensionPython")
e.createInstance()
#segmentation fault
A new function "Type::getTypeIfDerivedFrom" is created to return the given named type if is derived from the specified class, otherwise return Type::badType.
The strategy to prevent these crashes is as follows:
use getTypeIfDerivedFrom to check the Type. If this …
> App: Prevent crash when trying to delete pointer to BaseClass

- src/Gui/ViewProviderLine.cpp
- src/Gui/ViewProviderPlane.cpp
Currently one has to precisely pick inside the font shape. With this PR, the whole label bounding box allows picking.
https://forum.freecadweb.org/viewtopic.php?f=19&t=65020
> [GUI] Allow origin plane/axis selection with entire label bounding box

- src/App/FreeCADInit.py
- src/Mod/AddonManager/ALLOWED_PYTHON_PACKAGES.txt
- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/AddonManagerOptions.ui
- src/Mod/AddonManager/AddonManagerRepo.py
- src/Mod/AddonManager/CMakeLists.txt
- src/Mod/AddonManager/addonmanager_metadata.py
- src/Mod/AddonManager/addonmanager_utilities.py
- src/Mod/AddonManager/addonmanager_workers.py
- src/Mod/AddonManager/dependency_resolution_dialog.ui
This PR implements FreeCAD and Python dependency installation when using the Addon Manager to install an Addon. 
To test: first, make sure you re-cache the Addon Manager's data. Next, you need to install a workbench that has dependencies! InventorLoader has quite a few ("xlutils", "xlwt", "olefile", and "xlrd"), and SteelColumn has one ("ezdxf"). InventorLoader is a good test case because it's easy to tell if your system found the installed dependencies: if it did not, InventorLoader tries to install them itself the next time you launch FreeCAD. If that happens, something when wrong with the Addon Manager, please report it below (you will want to turn on logging when you run FreeCAD, a fair bit of debugging information is currently being written at a log-level output).
For historical and …
> Addon manager: install dependencies

- src/Mod/TechDraw/Gui/CommandCreateDims.cpp
The initial position of dimension text is set at the top left of the bounding rectangle.  The text should be positioned to the centre of the bounding rectangle.
---
> [TD]Adjust initial placement of dim text

- src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
Was enabled but not visible.
Hopefully last time I fix it. :)
> Display Midplane checkbox with Pocket/ThroughAll

- src/Mod/PartDesign/App/FeaturePad.cpp
- src/Mod/PartDesign/App/FeaturePocket.cpp
the goal of the recent Pad/Pocket code refactoring was to handle Pad and Pocket the same, therefore:
- the default Pad was 10 long, Pocket only 5 -> uniform this to 10
- the initialization of the length was different than the default set in Command.cpp
- it is annoying that the default 2nd length was 10 and 20 times the default for the 1st length -> uniform and take the same than the 1st length
> [PD] uniform default Pad/Pocket lengths

- src/Gui/DocumentPyImp.cpp
The error message is cleared by PyErr_Clear.
Some curly braces are added to if-else blocks.
---
> Gui: Remove unused error message

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftfunctions/scale.py
- src/Mod/Draft/draftguitools/gui_mirror.py
- src/Mod/Draft/draftguitools/gui_move.py
- src/Mod/Draft/draftguitools/gui_rotate.py
- src/Mod/Draft/draftguitools/gui_scale.py
- src/Mod/Draft/draftguitools/gui_stretch.py
- src/Mod/Draft/draftguitools/gui_trackers.py
- src/Mod/Draft/drafttaskpanels/task_scale.py
This PR fixes several task panel related issues for the following Draft modifier commands: Draft_Move, Draft_Rotate, Draft_Scale, Draft_Mirror and Draft_Stretch.
For the Draft_Scale command I have opted for the most practical solution:
* Except for the Global toggle, all toggles were removed from the 1st task panel.
* There is no longer a Continue toggle. It seems unlikely that Draft_Scale will ever be used in Continue mode. This mode is actually also unlikely for the other modifier commands.
When changing to and from Subelement mode the ghosts are now updated. But there is still a lot of work that has to be done in relation to this mode. It now only work for Draft_Wires and Draft_Lines. And f.e. a Draft_Wire that is filleted will already cause problems.
Forum topic: …
> Draft: fix task panel related issues

- src/Mod/Arch/ArchWall.py
The `onBeforeChange` method in the `ArchWall` class did not call `onBeforeChange` from its parent class. This blocked the 'MoveWithHost' behavior of windows placed in walls.
---
> Arch: Fix ArchWall onBeforeChange

- src/Gui/Action.cpp
- src/Gui/DlgSettingsMacro.ui
- src/Gui/DlgSettingsMacroImp.cpp
- src/Gui/Widgets.cpp
- src/Gui/Widgets.h
https://forum.freecadweb.org/viewtopic.php?t=65081
@mwganson could you please have a look at this ?
> Use a key catcher line edit to get modifier(s) for recent macros + small fixes

- src/Mod/AddonManager/AddonManager.py
Add a confirmation dialog before removing an addon (accidentally uninstalling Part Library would be very unfortunate, for example!).
> Addon Manager: Confirm delete

- src/App/Part.cpp
- src/App/Part.h
App::Part Material property type is currently App::PropertyMap, but to be consistent with other domains using materials (like Arch, especially), it should rather be an App::PropertyLink, in order to link to a Material card.
Please note this standardization is requested for Render Workbench, in order to be able to use Material rendering features with Part objects, as discussed in [this thread](https://github.com/FreeCAD/FreeCAD-render/issues/123). 
---
> [Part] Set App::Part's Material property type to App::PropertyLink (instead of App::PropertyMap)

- src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
- src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
- src/Mod/TechDraw/Gui/Workbench.cpp
PR to make the GUI texts of the extension tools more consistent.
* Title case for all menu texts. This is consistent with most TechDraw menus.
* Linebreaks in tooltips should be `<br>`.
* Displaying the text of multiline tooltips in the statusbar does not work. So the menu text is now used for the statusbar text.
Additionally:
The order of the tools in the menu did not match the order in the toolbar. This was corrected.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=35&t=65436
---
> TechDraw: Ext. Tools: Improve menu texts and tooltips

- src/Mod/Path/PathScripts/post/marlin_post.py
The marlin post is outputting mm/s gcode.  Gcode is always mm/min.   Changing the default.
---
> [Path] fix default unit string for mm/min

- src/Mod/AddonManager/AddonManager.py
When an Addon is uninstalled, it is examined for the presence of a file called "uninstall.py" in its root directory. If that file exists, it is loaded and run by the Python interpreter. This is intended to allow an addon to clean up after itself (e.g. remove any cached data, etc.).
> Addon Manager: Run uninstall.py when uninstalling AddOn

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftguitools/gui_beziers.py
- src/Mod/Draft/draftguitools/gui_groups.py
- src/Mod/Draft/draftguitools/gui_orthoarray.py
- src/Mod/Draft/draftutils/init_tools.py
- src/Mod/Draft/draftutils/translate.py
- src/Mod/Draft/draftviewproviders/view_base.py
PR to fix several translation issues. See forum topic.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=65346
Additionally:
* Removed the faulty `_tr` and `_qtr` functions from `translate.py`. They are no longer used by the Draft or Arch WB.
* In `view_base.py`: Fixed wrong use of variables in `QT_TRANSLATE_NOOP` calls and changed the tooltips from 'hatch' pattern to 'SVG' pattern.
- x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
---
> Draft: Fix several translation issues

- src/Gui/Application.cpp
- src/Gui/DlgGeneral.ui
- src/Gui/DlgGeneralImp.cpp
The hard coded  blinking time value `-1` is the [default value used by Qt](https://github.com/qt/qtbase/blob/dev/src/gui/kernel/qstylehints.cpp#L91)
---
> Gui: Add option to enable/disable text cursor blinking

- src/Gui/Selection.cpp
The first commit gives a more detailed docstrings for the module.
The second commit change the signature of the next functions:
`updateSelection()`
`IsSelected()`
`getSelection()`
`getSelectionEx()`
`enablePickedList()`
`setVisible()`
`hasSelection()`
`pushSelStack()`
All of these functions have at least one parameter that behaves like a boolean parameter. Currently any Python object can be passed to this parameter, internally the boolean is obtained and then this boolean is used in the C++ method. This can lead to confusing situations related to the correct use of the Python function.
Now, for these parameters a boolean type check is performed.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests …
> Gui: Improve docstrings and change some signatures in Selection module

- src/App/MetadataPyImp.cpp
- src/Mod/AddonManager/AddonManagerRepo.py
- src/Mod/AddonManager/expanded_view.py
- src/Mod/AddonManager/expanded_view.ui
- src/Mod/AddonManager/package_list.py
Tags display in expanded view (right now just as a simple comma-separated list), but are searched regardless of whether they are displaying or not.
> Addon Manager: Add search and display of tags

- src/Mod/Draft/draftguitools/gui_edit.py
Entering a Y=0 coordinate when editing points caused an error.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=3&t=65855
---
> Draft: Fix-gui_edit.py Y is zero input bug

- src/Mod/Arch/ArchCutPlane.py
Fixed wrong context for the Arch_CutLine command.
Additionally:
tweaked the menu text and the tooltip of the command.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=65346
---
> Arch: Fix ArchCutPlane translation issue

- src/Mod/TechDraw/Gui/TaskSelectLineAttributes.ui
Fix text regression.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=35&t=65727
---
> TechDraw: Fix texts in TaskSelectLineAttributes.ui

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/AddonManagerRepo.py
- src/Mod/AddonManager/CMakeLists.txt
- src/Mod/AddonManager/addonmanager_utilities.py
- src/Mod/AddonManager/addonmanager_workers.py
- src/Mod/AddonManager/loading.html
- src/Mod/AddonManager/package_details.py
- src/Mod/AddonManager/package_list.py
Take Two -- some different design decisions this time. The basic idea is to use QWebEngineView (which is basically a fork of Chromium) to display the README and Macro Wiki Page content, since that content is really web-based and makes sense in a web browser. However, it is not intended as a general purpose web browser: almost all links you click on will ask the system to open its default web browser, the same way the original version did. The only exception is FreeCAD wiki pages, which this web view will render.
> Addon Manager: Switch to using QWebEngineView for README

- src/Gui/DocumentRecovery.cpp
If 'cleanup' is choosen, recovery dialog is automatically close after deletion
User can "Don't show again" on the 'operation finished' message box
https://forum.freecadweb.org/viewtopic.php?f=34&t=65329&start=10#p565981
> [Gui] Decrease click number on recovery transient deletion

- src/Mod/Arch/ArchFrame.py
A previous PR broke ArchFrame for non planar Base objects (single lines).
This PR fixes this and also simplifies the alignment algo by relying on the built-in capabilities of `FreeCAD.Rotation()`. The resulting alignments are more logical in general.
Additionally:
* The first Base Point now matches the `Placement.Base` of the profile. This makes more sense than using the `CenterOfMass` of its face.
* `Offset` is performed before `Rotation`. Again because this makes more sense.
* Replaced `obj.Profile.isDerivedFrom("Part::Part2DObject")` check with `obj.Profile.Shape.findPlane()` check. The latter is more reliable and flexible. A `Part::Part2DObject` does not have to be planar. And f.e. a Std_Part that contains a profile can now be used.
Forum topics: …
> Arch: Fix ArchFrame

- src/Mod/PartDesign/App/FeatureChamfer.cpp
- src/Mod/PartDesign/App/FeatureChamfer.h
- src/Mod/PartDesign/App/FeatureFillet.cpp
- src/Mod/PartDesign/App/FeatureFillet.h
- src/Mod/PartDesign/Gui/Command.cpp
- src/Mod/PartDesign/Gui/TaskChamferParameters.cpp
- src/Mod/PartDesign/Gui/TaskChamferParameters.h
- src/Mod/PartDesign/Gui/TaskChamferParameters.ui
- src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
- src/Mod/PartDesign/Gui/TaskDressUpParameters.h
- src/Mod/PartDesign/Gui/TaskFilletParameters.cpp
- src/Mod/PartDesign/Gui/TaskFilletParameters.h
- src/Mod/PartDesign/Gui/TaskFilletParameters.ui
Adds a new boolean property called "UseAllEdges" to Part Design fillets and chamfers.  This will make these features robust against topological naming problem if this property is set to True, because then no matter if the edges of the base object change this dressup feature will still be using all of the edges.
Pros:
- Robust against topological naming if set to True
- Convenient way to fillet/chamfer all edges instead of opening the dialog
Cons:
-If the user has set UseAllEdges to true and then tries to edit the edges in the list, then the changes to the list will have no effect, possibly confusing and frustrating some users.
There is some minor code duplication, but I think it's better not to put the code in FeatureDressup.cpp because that class is also used by Draft and Thickness, …
> [PartDesign Fillet/Chamfer] add UseAllEdges boolean property

- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
Sets the spinbox step for knot insertion dialog to 0.001.
Removes the mention of multiplicity option from the tooltip.
> [Sketcher] Fix some points mentioned in #6323

- src/Gui/ApplicationPy.cpp
Defines `PY_SSIZE_T_CLEAN` before <Python.h> include in Base/PyObjectBase.h.
This is required for modules calling `Gui.addIcon()` (e.g. Assembly3) that would otherwise fail to load.
The error reported as `Base.FreeCADError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats`.
[Python 3.10 dropped support](https://bugs.python.org/issue40943) for calling PyArg_ParseTuple with ['#' formats](https://docs.python.org/3.10/c-api/arg.html?highlight=py_ssize_t_clean#strings-and-buffers)when `PY_SSIZE_T_CLEAN` is not defined. 
[`src/Gui/ApplicationPy.cpp:1223`](https://github.com/FreeCAD/FreeCAD/blob/cafb8601e003ca3def860142fad430c824b5a191/src/Gui/ApplicationPy.cpp#L1223) is the only location where `PyArg_ParseTuple` is called with "#" format.
(As reported by `rg …
> Fix for Python3.10

- src/Mod/Arch/ArchWindow.py
Windows and doors from `parts_library` were not aligned with or inserted in a wall.
Additionally:
The existing code for `presetdir` never worked. I have solved this by treating `presetdir` the same as `librarypath`. So the same directory structure is expected in both paths. I think this makes the most sense.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=65210
---
> Arch: ArchWindow.py fix alignment of library windows

- src/Mod/Draft/draftfunctions/offset.py
- src/Mod/Draft/draftguitools/gui_arcs.py
- src/Mod/Draft/draftguitools/gui_beziers.py
- src/Mod/Draft/draftguitools/gui_splines.py
- src/Mod/Draft/draftguitools/gui_wire2spline.py
- src/Mod/Draft/draftmake/make_arc_3points.py
- src/Mod/Draft/draftmake/make_bspline.py
- src/Mod/Draft/importDXF.py
The `make` functions should be called with their new name, `make_`, in the Draft code.
Note that more PRs will follow.
- [x  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
---
> Draft: Housekeeping: call 'make' functions with new name

- src/Mod/TechDraw/App/AppTechDrawPy.cpp
- src/Mod/TechDraw/App/DrawViewDimension.cpp
The numeric part of dimension text is not included when exporting a Page as DXF.
---
> [TD]correct retrieval of dim text for DXF export

- src/Mod/Path/Gui/Resources/panels/PathEdit.ui
- src/Mod/Path/PathScripts/PathJobDlg.py
This issue was actually resolve by PR #4140.  I don't know why it was left open.  This PR removes an unnecessary error associated with path stock and also reverts an incorrectly saved tab on the job edit.
---
> [PATH]  Fixes #5904

- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
- src/Mod/Sketcher/Gui/EditModeInformationOverlayCoinConverter.cpp
The new comb allows for better display of discontinuity in curvature and tangency because of knot multiplicity.
Without the PR:
With the PR:
Some other minor change(s) included here since they are better handled in a single pr:
* Make the knot list in knot insertion dialog be displayed more properly, without the trailing comma (though that's acceptable behavior in python it's not very good to look at otherwise)
> [Sketcher] Make B-Spline curvature comb piecewise + some other improvements

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/AddonManagerOptions.ui
- src/Mod/AddonManager/CMakeLists.txt
- src/Mod/AddonManager/addonmanager_workers.py
- src/Mod/AddonManager/change_branch.py
- src/Mod/AddonManager/change_branch.ui
- src/Mod/AddonManager/package_details.py
- src/Mod/AddonManager/package_details.ui
- src/Mod/AddonManager/package_list.py
For users with git and GitPython installed, a new button is added to the details view allowing them to change the branch they are on. Some other minor UI changes are made to accommodate this new behavior.
> Addon Manager: Add branch switching GUI

- src/Mod/Arch/ArchWindow.py
When analyzing the `librarypath` and the `presetdir` items from `os.listdir()` were not checked with `os.path.isdir()` and `os.path.isfile()`.
---
> Arch: Arch_Window.py: do isdir and isfile check for librarypath

- src/Mod/Mesh/App/MeshPyImp.cpp
BoundBox3 class must have changed afterwards.  Now this test code inside #if 0 blocks does not build when enabled.
> Mesh: fix test code so it will compile when used

- src/Gui/Command.cpp
- src/Gui/Command.h
- src/Gui/CommandPy.xml
- src/Gui/CommandPyImp.cpp
- src/Gui/DlgActionsImp.cpp
- src/Gui/DlgActionsImp.h
Add two static Python commands to FreeCADGui.Command enabling Python code to add and remove custom macro commands.
@wwmayer I am not sure these are in the right place, or if there's a better place or way to achieve this -- I'd appreciate it if you could take a look. This is a bit of copy-and-paste work, I'm not that confident in my Python binding coding.
> GUI: Add Python interface to create custom actions

- src/Mod/TechDraw/App/DrawViewDraft.cpp
The `Draft.getSVG` has been renamed. Using it results in warnings in the Report view. The new function `Draft.get_svg` has the same signature.
---
> TechDraw: Use Draft.get_svg instead of Draft.getSVG

- src/Mod/PartDesign/App/FeatureSketchBased.cpp
Part does already use this FaceMaker since it can also handle islands.
The PR therefore
- uniforms the behavior of PD and Part
- fixes #6366
- enables to use nested sketches for the various PD features like Revolve
Here is an example file what becomes now possible:
[revolveExample.zip](https://github.com/FreeCAD/FreeCAD/files/8076715/revolveExample.zip)
> [PD] change default FaceMaker to Bullseye

- src/Mod/Path/PathScripts/PathDrilling.py
> [Path]  Drilling gcode bug.  Fixes #6367

- src/Mod/Path/PathScripts/PathOp.py
- src/Mod/Path/PathScripts/PathOpGui.py
- src/Mod/Path/PathScripts/PathUtils.py
Assuming a job with more than one TC but no previous op yet - the user gets presented with a dialog to select one TC for the op. If the user cancels the selection the op creation "half way fails" with an exception.
Similarly if the op to be created has tool constraints (implements `isToolSupported`) and no suitable tool is in the job's Tools group the creation fails with an exception traceback in the report view. Something about `None` not understanding some method ....
Both these cases now throw an exception which is handled in the op creation algorithm. The former case generates a legible warning since the abort was most likely user initiated anyway, and the latter results in an error telling the user what the problem is.
> Gracefully handle op creation abort when no TC is available or selected.

- src/Mod/Path/CMakeLists.txt
Removing duplicated linking of `PathCommands.py` from `Path/CMakeLists.txt`.
When trying to setup a CMake build configuration using the `cmake -G "Xcode"` option, which generates a `.xcodeproj` file for use with the Mac Xcode IDE, the setup process fails with the following message:
```zsh
CMake Error in src/Mod/Path/CMakeLists.txt:
The custom command generating
/Users/dirkolbrich/FreeCAD/freecad-build-xcode/Mod/Path/PathCommands.py
is attached to multiple targets:
PathScripts
PathTests
but none of these is a common dependency of the other(s).  This is not
allowed by the Xcode "new build system".
```
This prevents the generation of the `.xcodeproj` and leads to an abort of the `cmake` process.
---
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask …
> [Path] remove duplicate link of PathCommands.py

- src/Mod/Draft/draftguitools/gui_draft2sketch.py
- src/Mod/Draft/draftguitools/gui_lines.py
- src/Mod/Draft/draftguitools/gui_planeproxy.py
- src/Mod/Draft/draftguitools/gui_points.py
- src/Mod/Draft/draftguitools/gui_polygons.py
- src/Mod/Draft/draftguitools/gui_shape2dview.py
- src/Mod/Draft/draftguitools/gui_shapestrings.py
- src/Mod/Draft/draftmake/make_point.py
- src/Mod/Draft/draftmake/make_rectangle.py
- src/Mod/Draft/draftmake/make_shape2dview.py
- src/Mod/Draft/draftmake/make_sketch.py
- src/Mod/Draft/draftmake/make_wire.py
- src/Mod/Draft/drafttaskpanels/task_shapestring.py
- src/Mod/Draft/importAirfoilDAT.py
This PR is a continuation of https://github.com/FreeCAD/FreeCAD/pull/6337
---
> Draft: Housekeeping: call 'make' functions with new name (3)

- src/Mod/Path/PathScripts/PathAreaOp.py
forum mention at https://forum.freecadweb.org/viewtopic.php?f=15&t=64882
This fix applies a small value to start points for open edges when either the x or y start point value is roughly zero. …
> [Path] Fix open edge zero value start point

- src/App/Metadata.cpp
- src/App/Metadata.h
- src/Gui/CMakeLists.txt
- src/Gui/DlgGeneralImp.cpp
- src/Gui/DlgGeneralImp.h
- src/Gui/DlgPreferencePackManagement.ui
- src/Gui/DlgPreferencePackManagementImp.cpp
- src/Gui/DlgPreferencePackManagementImp.h
- src/Gui/PreferencePackManager.cpp
- src/Gui/PreferencePackManager.h
There are three different ways FreeCAD finds Preference Packs: they may be shipped with FreeCAD, installed by the user using the Addon Manager, and saved by the user based on their current settings. This PR adds a dialog to manage hiding/showing packs that were shipped with FreeCAD or were downloaded as part of an Addon (Addons can potentially contain more than one preference pack), as well as deleting a pack that was saved using the user-saved packs mechanism. It also provides a shortcut to open the Addon Manager with Preference Pack-containing addons displayed, so that more preference packs can easily be added, and addons that were installed and are no longer needed can be removed.
The dialog is accessed via the "Manage..." button on the main preferences dialog, underneath the region …
> Gui: Add interface for managing preference packs

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
- src/Mod/Sketcher/Gui/Utils.cpp
- src/Mod/Sketcher/Gui/Utils.h
There are certain issues that happen when points corresponding to knots of a b-spline coincide with other points, particularly the end points of the curve or control points of the spline. This PR attempts to fix them.
The commit currently in is ready to be merged but I want to add another, which would make sure the control points that can only be selected as knots can also be moved.
> [Sketcher] Fix some issues when b-spline knot points coincide with other points

- src/Mod/TechDraw/Gui/Command.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.cpp
This fix was suggested by translators on crowdin.
> TD: Substitute string 'Dxf' for 'DXF' [skip ci]

- src/App/FreeCADInit.py
- src/Gui/FreeCADGuiInit.py
- src/Mod/AddonManager/AddonManagerRepo.py
- src/Mod/AddonManager/addonmanager_workers.py
- src/Mod/AddonManager/expanded_view.py
- src/Mod/AddonManager/package_details.py
- src/Mod/AddonManager/package_list.py
This PR adds the ability to disable the loading of an Addon without actually uninstalling it. This is useful for scripted testing, as well as for disabling memory-intensive addons when they aren't needed. The mechanism is designed to be simple enough that a shell script can easily achieve it: a simple "ADDON_DISABLED" file is created in the Addon's root directory, and checked for when FreeCAD starts. The file's contents are not examined, only its existence matters. A simple GUI interface is added to the Addon Manager to create and delete this file, and the interface is updated to display a message when an Addon is disabled.
Fixes https://github.com/FreeCAD/FreeCAD-addons/issues/204
> Addon Manager: interface and backend to disable addons

- cMake/FindOCC.cmake
- src/Gui/CMakeLists.txt
- src/Gui/DlgGeneral.ui
- src/Gui/DlgGeneralImp.cpp
- src/Gui/DlgGeneralImp.h
- src/Gui/DlgRevertToBackupConfig.ui
- src/Gui/DlgRevertToBackupConfigImp.cpp
- src/Gui/DlgRevertToBackupConfigImp.h
- src/Gui/PreferencePackManager.cpp
- src/Gui/PreferencePackManager.h
- tsupdate_stderr.log
- tsupdate_stdout.log
Adds an option to the Preference Pack GUI to revert to a saved preference file.
When a preference pack is applied, FreeCAD automatically backs up the pre-pack config file. This PR adds a GUI to reverting to one of those saved backups. Right now this is a somewhat destructive process: the backup is a complete copy of the original config file, including things like "Recent Files". Reverting to the backup will thus reset your Recent Files list to whatever it was when the backup was taken.
In the future it would be best to make a more judicious backup, that only backs up the items that the preference pack affects. I submit this PR as an improvement over the current state of affairs, not as the end goal.
Testers: please make a manual backup of your user.cfg file prior to testing. To test, …
> Preference Packs: Add revert to backup option

- src/App/Property.cpp
- src/App/Property.h
- src/App/Transactions.cpp
- src/App/Transactions.h
In an transaction where dynamic property is removed, it is copied and stored. However, if there is new dynamic property added in the same transaction, it is possible for the memory allocator to reuse the just deleted memory block. This will cause hard to debug problem, because Transaction uses a map with the property pointer as key. This commit changed the key to an integer ID.
> App: fix undo/redo of dynamic property add/remove/change

- src/Mod/Path/PathScripts/PathPocket.py
Fixes address issues where incorrect paths are generated that include clearing paths below selected faces on underside of model. In forum presented at [3D pocket anomaly](https://forum.freecadweb.org/viewtopic.php?f=15&t=64111) and [Path 3D pocket removing too much material](https://forum.freecadweb.org/viewtopic.php?f=15&t=65421).
This fix also includes a fix for an unreported bug that is manifest when the user does not select any features, thus requesting to 3D Pocket the entire model.  In this case, the Final Depth was incorrectly being calculated to the top of the model, rather than the bottom.  To fix this issue, the `opUpdateDepths()` method is added.
Last, this PR includes a Black-formatting-only commit to reformat the file per recent Black standard.
Thank you for creating a pull …
> Path: Fixes 3D Pocket overcut on underside of selected faces

- src/Gui/CommandFeat.cpp
doc = document containing selected object
obj = selected object
sub = selected subobject, e.g. face, edge (renamed from elt)
subs = list of selected subobjects
All previous definitions of these objects are deleted each time the command is run.
Edit: Updated to support App::Links.
lnk = App::Link object
obj = linked object
> [Std_SendToPythonConsole] add doc, sub, and subs

- src/Gui/propertyeditor/PropertyItem.cpp
`Qt::TextColorRole` (`enum ItemDataRole`) is deprecated as of Qt 5.13 and will be removed in Qt 6:
- https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qnamespace.h?h=v5.13.0#n1511
It's replaced with `Qt::ForegroundRole` which is available since at least Qt 5.0 (FreeCAD 0.20 will require Qt 5.9 or later).
- https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qnamespace.h?h=v5.9.0
- https://wiki.freecadweb.org/0.20_Development_Cycle
Compiles and runs OK (Apple M1).
> Gui: fix use of deprecated Qt::TextColorRole

- .github/labels.yml
When choosing a specific workbench tag in the GH the current dropdown entries are scattered. By prepending `WB` to them and sorting them alphabetically will make it cleaner to select them. Due to this, the tags have been renamed.
This PR follows up the change of the tags to the GH auto-labeler action. Some extra tags were added as well like :octocat: for GH files and `Addon Manager` etc...
> Github: rename Workbench tags so they present alphabetically in GH UI

- src/Mod/Draft/draftobjects/wire.py
When changing the `Length` of a Draft_Line to f.e. 0.5 the input of the zero resulted in a zero length line.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=3&t=66586
---
> Draft: Fix Draft_Line Length is zero bug

- src/Mod/Web/Gui/BrowserView.cpp
https://forum.freecadweb.org/viewtopic.php?f=10&t=66474&p=575132#p575132
> check for nullptr in BrowserView::onLoadFinished() before calling MainWindow::showMessage() at the end of unit tests

- src/Mod/Sketcher/App/SketchAnalysis.cpp
- src/Mod/Sketcher/App/SketchAnalysis.h
https://forum.freecadweb.org/viewtopic.php?f=8&t=62936
> Sketch: Fix algorithm seeking for missing coincidences in Validate

- src/Mod/PartDesign/PartDesignTests/TestChamfer.py
- src/Mod/PartDesign/PartDesignTests/TestFillet.py
Test 1: set Base to no subobjects, with UseAllEdges = True, should be the same as if all faces were the Base subobjects.
Test 2: set Base to non-existent face (Face50) with UseAllEdges = True, tests for topological naming resilience
Test 3: set Base to only Face1 with UseAllEdges = False, should now be different from result of using all faces.
> PartDesign: Fillets / Chamfers add unit tests for UseAllEdges property

- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathJobGui.py
- src/Mod/Path/PathScripts/PathOpGui.py
This is an attempt to make the visibility of path objects a little more natural. 
Path visualization is removed from the Job node.
Operations node has been changed into a regular group.
---
> [Path] Make Job and Operation visibility more natural

- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
New tool(s):
- Press "D" to open a dialog to set the degree (already merged in #6463).
- Press "Backspace" to delete the last defined pole (this PR).
> [Sketcher] Some tools for more control over b-splines at creation (2/??)

- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
I had kept the qualifier there when developing the tool and forgot to remove it. At this time the tool is fairly well-developed.
> [Sketcher] Remove "incomplete" from insert knot command

- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
The DrawSketchHandler will otherwise give confusing error messages.
> [Sketcher] Check for b-spline before starting knot insertion "mode"

- src/Mod/TechDraw/App/DrawProjGroup.cpp
- src/Mod/TechDraw/App/DrawProjGroupItem.cpp
- src/Mod/TechDraw/App/DrawView.cpp
- src/Mod/TechDraw/App/DrawView.h
This PR corrects the behaviour of Views when the ScaleType property changes between Page, Custom and Automatic.
---
> [TD]fix ScaleType change behaviour

- src/Mod/TechDraw/App/DrawProjGroupItem.cpp
- src/Mod/TechDraw/App/DrawView.cpp
- src/Mod/TechDraw/App/DrawView.h
- src/Mod/TechDraw/Gui/TaskSectionView.cpp
- src/Mod/TechDraw/Gui/TaskSectionView.h
- src/Mod/TechDraw/Gui/TaskSectionView.ui
This PR has two parts.  The first corrects the handling of Scale/1ScaleType in old (pre v020) documents.  The second adds ScaleType to the Section dialog.
> [TD]handle ScaleType for old documents + Section dialog ScaleType

- src/Mod/AddonManager/AddonManagerTest/app/test_addon.py
Fixed via `codespell -q 3 -L aci,ake,aline,alle,alledges,alocation,als,ang,anid,anormal,apoints,ba,beginn,behaviour,bloaded,bottome,byteorder,calculater,cancelled,cancelling,cas,cascade,centimetre,childrens,childs,colour,colours,commen,connexion,currenty,dof,doubleclick,dum,eiter,elemente,ende,feld,finde,findf,freez,hist,iff,indicies,initialisation,initialise,initialised,initialises,initialisiert,inout,ist,itsel,kilometre,lod,mantatory,methode,metres,millimetre,modell,nd,noe,normale,normaly,nto,numer,oce,oder,ontop,orgin,orginx,orginy,ot,pard,parm,parms,pres,programm,que,rady,recurrance,ro,rougly,seperator,serie,sinc,strack,substraction,te,technic,thist,thru,tread,uint,unter,vertexes,wallthickness,whitespaces -S ./.git,*.po,*.ts,./ChangeLog.txt,./src/3rdParty,./src/Mod/Assembly/App/opendcm …
> AddonManager: fix typos

- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femtest/app/support_utils.py
- src/Mod/Fem/femtest/data/elmer/group_mesh.geo
This patch will add the General.NumThreads = <cpu core count> setting to the shape2mesh.geo configuration file for gmsh. This will cause gmsh to run with multiple threads (it uses OMP internally). It does not affect gmsh binaries without OMP support.
Great speedups can are had, in a project I'm working on currently the meshing takes 2,5 minutes with a single thread, reduced to only 40 seconds when multi-threaded.
> Fem: enable multi-threading for Gmsh

- src/Mod/PartDesign/App/ShapeBinder.cpp
- src/Mod/PartDesign/App/ShapeBinder.h
Adds 2D offsetting of wires, edges, and face types.
Adds new "Offsetting" group to the green Part Design SubShapeBinders.  In this group:
Offset (float) the amount of 2D offset (in mm).  If Offset = 0.0, then no offsetting is done.  Can be positive or negative (for offsetting inwards).
OffsetJoinType (enumeration).  Values are "Arcs", "Tangent", "Intersection".
OffsetFill (boolean).  If True a face is made between the original wire and the offset.  (see image below)
OffsetOpenResult (boolean).  If False when offsetting an open wire a closed wire is produced.  If True, the open result is allowed.
OffsetIntersection (boolean).  Affects the way inner wires are offset relative to parent wire, inwards or outwards.
> PartDesign::SubShapeBinder add 2D offsetting

- src/Mod/Path/PathScripts/PathArray.py
This commit makes PathArray able to discover the original base feature ToolController recursively through (nested) dressups. I've hard capped the recursion depth limit to 10 to avoid possible issues with cyclic references (if such are possible?). 
I've tested this with a nested Tag Dressup -> Ramp Dressup -> Profile and it seems to work fine.
I'd appreciate further testing from other users. I've tested this (+ ran unit tests) with Linux weekly AppImage build 27078.
Wiki page will need to be updated once this goes live.
Some discussion on this limitation 
* https://forum.freecadweb.org/viewtopic.php?t=26120 (2018)
* https://forum.freecadweb.org/viewtopic.php?f=15&t=54766 (2021)
Wiki page (section Limitations)
* https://wiki.freecadweb.org/Path_Array
> Path: Path Array dressup compatibility

- src/Mod/Path/PathScripts/PathDressupPathBoundary.py
This commit changes the feed rate of the beginning retraction from G1 at Feed to a G0 Rapid rate.  This initial command is causing a problem with the Tag Dressup due to the first move being a G1 to Safe Height.
This bug was discovered via Tag Dressup error in forum at [Boundary Dressup and Tag Dressup](https://forum.freecadweb.org/viewtopic.php?f=15&t=63433).
We should really consider adding a warning to the user in the Boundary Dressup that informs them their effective Z-boundary is higher than the base operation's Final Depth.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't …
> Path: Correct beginning retraction to safe height in Boundary Dressup, issue #6279 [Bug]

- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/App/DrawViewDimension.h
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
This PR corrects the display and positioning of units in dimension text.
---
> [TD]fix unit display to standards

- src/Mod/Path/PathScripts/PathMillFace.py
Prior to this fix, the `self.removalshapes` variable is not declared if `obj.Base` does not exist, or is empty.  This moves the declaration up in scope to the method level.
fixes #6577 
Reproduce error by:
* Create new Job, accepting defaults.
* Click MillFace icon in toolbar to initiate a new MillFace op, without selecting anything in the viewport.  This will be interpreted as milling the entire model.
* Error will be thrown.
No related forum thread.  Just found the bug working another issue here on GitHub related to FreeCAD Path workbench.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items …
> Path: Fix `self.removalshapes` declaration [Bug]

- src/Mod/Test/unittestgui.py
The module name changed from uppercase Tkinter to tkinter.
--
---
> [Test] Fix tkinter module name for python 3

- src/Mod/Draft/DraftGui.py
Angle Lock would only work if the workingplane was plane-parallel to the XY plane of the global coordinate system. The `self.angle` value (BTW: it's a vector!) was not translated from the workingplane coordinate system to the global coordinate system.
Note that I do not check for the existence of the `DraftWorkingPlane`. It always seems to be available if the GUI is up. Even if the startup workbench is Part f.e.
Elsewhere in the code we see this:
https://github.com/FreeCAD/FreeCAD/blob/c5a0db5e4736a6cd43d239e15d5e0daf7006a642/src/Mod/Draft/DraftGui.py#L1478
But I do not think that is a correct way to check for the presence of  the `DraftWorkingPlane`. You would have to use `hasattr` instead.
Forum topic: https://forum.freecadweb.org/viewtopic.php?f=23&t=66963
---
> Draft: Fix Angle Lock for non-XY workingplane

- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathPreferences.py
Warn user if opening job that contains legacy tools or enabling legacy tools
Legacy tools are deprecated and will be removed after v 0.20
---
> [Path]  Warn user if enabling legacy tools

- src/Mod/Path/PathScripts/PathJob.py
- src/Mod/Path/PathScripts/PathJobGui.py
This commit adds a simple `_jobIntegrityCheck()` method to verify that a model and tool exists within the Job object, when interacting with the Task Panel.  If either is missing, the appropriate tab is activated in the task window, and the appropriate edit window is opened for the user, with messages printed in the report view window.
Add check for existence of `SetupSheet` property of empty Job object.
These changes improve upon fixes in PR #5008 and related bug fixes.
fixes #6207 
@sliptonic I would like feedback about my use of redirects to, and opening of, appropriate Model Selection or Tool Selection windows if no job model or tool exists for any job.  The premise is that a user has deleted all children of a Job object, leaving it empty in the object tree.  This PR allows recovery …
> Path: Extend Job integrity check to GUI side, issue #6207 [Bug]

- src/Mod/AddonManager/addonmanager_workers.py
ref: https://lgtm.com/rules/910088/
> AddonManager: remove superfluous 'pass' per LGTM

- src/Mod/Fem/Gui/TaskFemConstraintDisplacement.cpp
- src/Mod/Fem/Gui/TaskFemConstraintFixed.cpp
- src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.cpp
- src/Mod/Fem/Gui/TaskFemConstraintForce.cpp
- src/Mod/Fem/Gui/TaskFemConstraintHeatflux.cpp
- src/Mod/Fem/Gui/TaskFemConstraintOnBoundary.cpp
- src/Mod/Fem/Gui/TaskFemConstraintOnBoundary.h
- src/Mod/Fem/Gui/TaskFemConstraintPressure.cpp
- src/Mod/Fem/Gui/TaskFemConstraintSpring.cpp
- src/Mod/Fem/Gui/TaskFemConstraintTemperature.cpp
- src/Mod/Fem/Gui/ViewProviderFemConstraintOnBoundary.cpp
Now the behavior is (slightly more) consistent with behavior of PD fillets, for example.
See https://forum.freecadweb.org/viewtopic.php?f=18&t=67135#p580192. In the
future it may be possible to reuse some code from there.
What isn't yet implemented:
- If opening a constraint with selection, the constraint is not applied to that selection already. I expect this will need to be done for each of the subclasses. Or possibly it can be done in the superclass itself with some NVI?
- The last element can be deleted. We may want to keep this behavior in case the user wants to select, say, edges when some faces are already selected.
> [FEM] Refactor `TaskFemConstraintOnBoundary`

- src/Mod/Arch/ArchWindow.py
Previously, just the hinge position was changed, with the rotation
direction kept unchanged, which would make the door open towards the
other side of the wall. This also inverts the rotation direction, so the
door still opens toward the same side of the wall, which is more
intuitively what you would expect.
> Arch: When inverting hinge position, keep opening direction

- src/Mod/Arch/ArchPanel.py
[Arch] Fixes Panel Width of Trapezoidal Wave. 
When adding Trapezoidal waves in an Arch Panel, the width of the wave was not the same as the one defined on the properties throughout the entire panel, there are zones that are created wider. 
This Bug was discussed in :
https://forum.freecadweb.org/viewtopic.php?f=23&t=67234&p=581570#p581570
---
> Fix Arch Panel Trapezoidal Wave Width 

- src/Gui/PreCompiled.h
tested with PCH and it seems it is really not necessary. python.h is only used n one header in [Gui] and not relevant for PCH
> [Gui] remove Python.h from PreCompiled.h

- src/Mod/Path/PathScripts/PathUtils.py
- src/Mod/Path/PathTests/TestPathDepthParams.py
Add code block to remove first of any two consecutive, roughly equal depth values (twin values).
Add two unit tests to support new code block and use cases.
This PR addresses an error in the `PathUtils.depth_params()` class that occurs when the total depth is roughly equal to a single stepdown.
Forum identification at [G-code generated twice. Why?](https://forum.freecadweb.org/viewtopic.php?f=15&t=67168&sid=818fe4ba0b7055ab736084b469599dd0).
Steps to reproduce:
* Create job with defaults.
* Create operation.
* Set Step Down value equal to total depth of cut (OpStartDepth - OpFinalDepth).
* Save operation.
* Inspect G-code for same operation, and note line count.  (This will produce one instance of the g-code.)
* Set Start Depth to say 0.00000001 mm more than existing entry (OpStartDepth + …
> Path: Fix roughly equal depth entries

- src/Mod/TechDraw/App/AppTechDrawPy.cpp
This PR fixes a condition where the unit string is displayed twice if DisplayUnits is true.
---
> [TD]fix double units in dxf page export

- src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
when the helix touches itself along a single helical edge one gets a cryptic error.
This PR gives the user feedback what is going on.
To reproduce the issue, set in this file the pitch to 1.0 mm:
[HelixTouching-bug.zip](https://github.com/FreeCAD/FreeCAD/files/8328750/HelixTouching-bug.zip)
> [PD] Helix: catch case of touching Helix

- src/Mod/Path/PathScripts/PathAreaOp.py
- src/Mod/Path/PathScripts/PathPocketBase.py
Expose PocketLastStepOver property
Property can be useful to fine tune the last stepover for some shapes.
If the default value (0) is used, current behavior is unchanged.
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135) …
> [Path] Fix # 5956.  

- src/Gui/Language/Translator.cpp
Fixes problems seen on #6364 implementation
I should say that I didn't perfectly understand what was failing, but it seems that when using `QLocale::setDefault` after application has been started, the `LocaleChange` event isn't well propagated or handled.
Sending it manually afterwards solves the issue.
> Gui: fix some weird behavior of number format option

- src/App/Document.cpp
There were two bugs in `applyTimeStamp`: a backup was created even if backups are disabled and then the saved file was immediately deleted if backups are disabled.
Please review carefully as I don't really understand any of what happens in this file but it did solve the mentioned bugs for me. The line change count is misleading as most of it are just adding indentation.
I have some doubts about `applyTimeStamp`: what's the point of having an `if (useFCBakExtension)` condition inside it when this backup policy is only set if that bool is true.
Why when failing to delete the original file the thrown error says it's the backup that can't be removed?
```
try {
fi.deleteFile();
}
catch (...) {
Base::Console().Warning("Cannot remove backup file: %s\n", fi.fileName().c_str()); …
```
> Fix #6532 file not saved if backups are disabled and FCBak ext is enabled

- src/Mod/Fem/femtools/tokrules.py
- src/Mod/OpenSCAD/importCSG.py
Writing the parsetab.py cache file provides no measurable benefit, but causes several problems, so turn it off.
Also omit the generation of any debug output files.
Fixes #6315. 
---
> Avoid writing temporary cache files from ply.yacc

- src/Gui/DlgSettingsColorGradient.ui
- src/Gui/DlgSettingsColorGradientImp.cpp
- src/Gui/DlgSettingsColorGradientImp.h
- src/Gui/SoFCColorGradient.cpp
- large numbers as they appear of most simulations were not correctly displayed
- remove non-functional help button
Stress values like 210e9 Pa are standard simulation results. However, in FC 0.19 the user gets this back:
So the 210 MPa are expanded with precision mistakes and the dialog is not wide enough for this.
This PR fixes it by using scientific notation:
> [GUI] fix color gradient dialog

- src/Mod/Path/PathScripts/PathDressupPathBoundary.py
This commit simply corrects the erroneous `onDocumentRestored()` method name spelling.
---
> Path: Correct method name spelling error in Boundary Dressup [Bug]

- src/Mod/Path/PathScripts/PathPocketBase.py
Correct case of property name used.
Forum discussion at [Bug: PocketShape reopen throws PocketLastStepOver error](https://forum.freecadweb.org/viewtopic.php?f=15&t=67678).
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135 …
> Path: Correct PocketLastStepOver name in PathPocketBase [Bug]

- src/Gui/DlgMacroExecute.ui
It may not be immediately clear to some newbies that the Addons... button is used to download macros. Suggested among the flame war in https://forum.freecadweb.org/viewtopic.php?p=580097#p580083
also added a couple of tooltips, the rest of the buttons are self explanatory IMO so I didn't add tooltips.
> [Macros] change text of Addons... button to Download to help new people

- src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
Dev IDE fixed some line return at the same time :)
> Sketcher: restore constraint filter if Multiple dialog is canceled

- src/App/PropertyContainerPyImp.cpp
- src/Base/PersistencePyImp.cpp
- src/Mod/Part/App/Geometry.cpp
- src/Mod/Part/App/TopoShapeFacePyImp.cpp
This PR fixes 2 different crashes.
1st commit fixes crashes that happens with following Python code:
```
f = Part.Face()
f.Surface.
```
As soon as last dot is entered, a crash occurs
2nd commit fixes crash that happens eg. with following Python code:
```
l = Part.LineSegment(App.Vector(0,0,0),App.Vector(10,0,0)).toShape()
f = l.extrude(App.Vector(0,0,10))
f.Surface.dumpContent()
```
Other 2 commits are improvement only.
> 2 crash fixes when dealing with Surface properties

- src/Mod/Part/App/FeatureOffset.cpp
- src/Mod/Part/App/PartFeatures.cpp
- src/Mod/Part/BasicShapes/ShapeContent.py
- src/Mod/Part/Gui/Command.cpp
- src/Mod/Part/Gui/CrossSections.cpp
- src/Mod/Part/Gui/DlgExtrusion.cpp
- src/Mod/Part/Gui/DlgRevolution.cpp
- src/Mod/Part/Gui/Mirroring.cpp
- src/Mod/Part/Gui/TaskLoft.cpp
- src/Mod/Part/Gui/TaskSweep.cpp
I accidentally closed the other PR for this, so I am creating this one.  There haven't been any changes to the code except to resolve some conflicts with a recent commit (removing some includes).
Link to closed PR: https://github.com/FreeCAD/FreeCAD/pull/6353
Link to forum discussions:
https://forum.freecadweb.org/viewtopic.php?f=10&t=66159
https://forum.freecadweb.org/viewtopic.php?f=17&t=66449
It's a fairly big PR and the feature freeze is coming, so this probably will be for 0.21.  But I think it would be nice to improve Links support in Part for 0.20, if possible.
> Part: Improve support for Links

- src/Mod/Draft/WorkingPlane.py
The reported bug actually occurs whenever time the working plane is in automatic mode and the view flips to the opposite direction (ex. from left to right, from top to bottom), because the z-axis of the working plane it doesn't change.
This is incosistent because if, for example, in the transition from top view to bottom view the plane axis is set to another direction (say, perpendicular to left view), in the last step of the transition the plane is aligned according the bottom view.
With this changes the working plane remains unchanged only if the view is currently antiparallel to z-axis of the plane.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below …
> Draft: Fix WorkingPlane setup in automatic mode - fixes #6060

- src/Gui/Tree.cpp
- src/Gui/Tree.h
https://forum.freecadweb.org/viewtopic.php?f=34&t=68000
> Gui: add parameter switch to optionally stretch 'Description' column of Tree view

- src/Mod/PartDesign/App/FeatureTransformed.cpp
- src/Mod/PartDesign/App/FeatureTransformed.h
This property became redundant after 5ab7d17f67969b12c53b7bb8715f198093fcf56b.
> [PD] Delete "Overlap" property for `FeatureTransformed`

- src/Mod/Draft/DraftGui.py
A previous PR of mine (https://github.com/FreeCAD/FreeCAD/pull/6544) introduced a problem. When the `toggleAngle` function is triggered `self.angle` can be `None` (f.e. if the cursor never entered the 3D view). The `FreeCAD.DraftWorkingPlane.getGlobalRot(self.angle)` code then fails. This is fixed by adding
```
self.update_cartesian_coords()
```
to the function.
Additonally: replaced `if b:` with `if self.alock:` for clarity.
---
> Draft: Fix Angle Lock

- src/Mod/Draft/WorkingPlane.py
- src/Mod/Draft/draftguitools/gui_lines.py
- src/Mod/Draft/draftguitools/gui_trackers.py
If the set WP button is used in the `Draft_Wire` command to reorient the work plane, closing the command does not restore the plane to the state before the button was pressed, instead it sets the plane aligned with the current view. This is because the plane is restored using the `Plane.copy` method, which ignores the attribute `weak` of the plane.
Also, after closing the command and restoring the plane, archDimTrackers stops working correctly because the instance generated by `Plane.copy` is different from the original instance used by the tracker.
Two new methods are added to the Plane class: `getParameters` to get the work plane data, and `setFromParameters` to modify the working plane without creating a new instance.
Thank you for creating a pull request to contribute to FreeCAD! To …
> Draft: Fix orientWP method used by in Draft_Line command

- src/Gui/Tree.cpp
- src/Mod/Spreadsheet/App/Sheet.cpp
The relevant log outputs take significant amount of time when recomputing large spreadsheet in debug build. See [here](https://github.com/FreeCAD/FreeCAD/pull/6779#issuecomment-1106717916).
> Reduce debug log output

- src/Mod/PartDesign/App/FeatureTransformed.cpp
Sometimes both fuse and cut need to be applied for features to work properly, for example:
1. https://forum.freecad.org/viewtopic.php?t=67716
2. https://forum.freecadweb.org/viewtopic.php?t=59260
> [PD] Do both fuse and cut in `FeatureTransformed` if applicable

- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/Cosmetic.h
- src/Mod/TechDraw/App/CosmeticExtension.cpp
- src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
This PR corrects a situation where the ExtendShorten command inadvertently converted center lines into cosmetic edges.
---
> [TD]Fix ExtendShorten handling of Center Lines

- src/Mod/Draft/drafttaskpanels/task_shapestring.py
Small issue that was missed in https://github.com/FreeCAD/FreeCAD/pull/6721.
---
> Draft: Restore DontUseNativeDialog after ShapeString edit

- src/Mod/Fem/Gui/TaskFemConstraintContact.ui
- src/Mod/Fem/Gui/TaskFemConstraintDisplacement.ui
- src/Mod/Fem/Gui/TaskFemConstraintFixed.ui
- src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.ui
- src/Mod/Fem/Gui/TaskFemConstraintForce.ui
- src/Mod/Fem/Gui/TaskFemConstraintHeatflux.ui
- src/Mod/Fem/Gui/TaskFemConstraintPlaneRotation.ui
- src/Mod/Fem/Gui/TaskFemConstraintPressure.ui
- src/Mod/Fem/Gui/TaskFemConstraintSpring.ui
- src/Mod/Fem/Gui/TaskFemConstraintTransform.ui
Minor UI improvement. The behavior had changed when the buttons were changed
from `QPushButton` to `QToolButton`.
Before this PR:
With this PR:
> [FEM] Expand Add/Remove buttons in constraint tasks

- src/Mod/Draft/draftguitools/gui_groups.py
This PR fixes two remaining translation issues. Apparently `QT_TRANSLATE_NOOP` has some restrictions.
---
> Draft: fix 2 gui_groups.py translation issues

- src/App/Link.cpp
- src/Gui/ViewProviderLink.cpp
The crash happend when testing sample file in [this](https://forum.freecadweb.org/viewtopic.php?f=17&t=42183&e=1&view=unread#p592999) post.
Download file [try5_body.FCStd](https://forum.freecadweb.org/download/file.php?id=188410). Right click the Link, choose `Setup configurable object`. Select object `Parameters`. Crash.
> Fix crash when setup Link CopyOnChange

- src/Mod/Draft/importDXF.py
- src/Mod/Draft/importOCA.py
"Passing a local variable to a del statement results in that variable being removed from the local namespace. When exiting a function all local variables are deleted, so it is unnecessary to explicitly delete variables in such cases."
ref: https://lgtm.com/rules/1506104658325/  
https://lgtm.com/projects/g/FreeCAD/FreeCAD?mode=tree&ruleFocus=1506104658325
Note: I have not tested these code changes. Please review closely.
> LGTM: Remove unnecessary deletion of local variables

- src/Gui/ViewProviderLink.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/132  
[skip ci]
> Crowdin: fix whitespace and typo in translation string

- src/Mod/Draft/InitGui.py
Related to : https://forum.freecadweb.org/viewtopic.php?f=3&t=31720
Ensures that Working Panel toolbar is deactivated before toolbars are saved by connecting to appropriate signal the `Deactivated` function.
Before PR : 
* Start FC (ensure Draft WB isn't your default WB)
* Switch to Draft WB => Working Plane toolbar is activated
* Close FC
* Start FC again => :-1: Working Plane toolbar is present ! Only way to remove is activate then deactivate Draft WB
After PR : 
* Start FC (ensure Draft WB isn't your default WB)
* Switch to Draft WB => Working Plane toolbar is activated
* Close FC
* Start FC again => :+1: Working Plane toolbar is absent
> [BugFix] Draft: ensure Working Panel toolbar is deactivated on FC closing

- src/Mod/Fem/Gui/Resources/ui/ElectrostaticPotential.ui
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/143  
[skip ci]
> FEM: [Crowdin] fix typo in ElectrostaticPotential.ui tooltip

- src/Base/UnitsSchemaMKS.cpp
In the MKS schema, this removes a typo which adds an extraneous bracket to the end of the string representation of kinematic viscosity: "m^2/s)"
> Base: Remove extraneous bracket from kinematic viscosity units

- src/Mod/Path/PathScripts/post/KineticNCBeamicon2_post.py
- src/Mod/Path/PathScripts/post/centroid_post.py
- src/Mod/Path/PathScripts/post/dxf_post.py
- src/Mod/Path/PathScripts/post/nccad_post.py
- src/Mod/Path/PathScripts/post/uccnc_post.py
1. [from #6871] Set filename to "<None>" in Post-Processors that try to read the name of the ActiveDocument even if one isn't open.
2. Changed unnecessary renaming of 'FreeCAD' to 'App' during import.
3. [from #6871] Removed print-out of "Post-Processor loaded"-message from the few Post-Processor that have it.
------
---
> #6871 - Certain PostProcessors spam errors and other output

- src/Mod/TechDraw/App/DrawProjGroup.cpp
- src/Mod/TechDraw/App/DrawProjGroupItem.cpp
- src/Mod/TechDraw/Gui/QGIView.cpp
- src/Mod/TechDraw/Gui/TaskLeaderLine.cpp
This PR fixes a situation where DrawProjGroupItems do not respect the LockPosition property.
---
> [TD]Fix group item moving when locked

- src/App/Origin.cpp
Problem reported from https://forum.freecadweb.org/viewtopic.php?f=20&t=68452
The (extention)GetSubObject() API is supposed to accumulate the transformation along the object path.
> App: fix Origin getSubObject()

- README.md
The old Travis-CI badges are about a year old. These changes replace the links with those for Gitlab-CI.
Adapted from instructions at https://docs.gitlab.com/ee/user/project/badges.html#use-custom-badge-images.
Not sure what tag to use. I can force push and re-title the commit if needed.
> [Readme] Update build status badges

- src/Mod/TechDraw/App/DrawView.cpp
- src/Mod/TechDraw/TechDrawTools/TDToolsMovers.py
This PR corrects a condition where checkFit was comparing the unscaled View against the Page size.  It should check the scaled View. 
---
> [TD]fix checkFit to use current scale

- src/Mod/PartDesign/WizardShaft/SegmentFunction.py
This PR uncomments a chunk of code that appears to have been erroneously removed based on static analysis. That code was responsible for calculating the data used to plot the translation data, and removing it broke that plot function.
> PD: Fix w[z] plot in ShaftWizard

- src/Mod/TechDraw/App/DrawView.cpp
- src/Mod/TechDraw/Gui/QGIView.cpp
- src/Mod/TechDraw/Gui/QGIViewPart.cpp
- src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp
This PR addresses performance issues with redrawing graphics when the position of a View changes.
---
> [TD]fix double draw on position change

- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/Gui/PreferencesGui.cpp
This PR addresses an issue where the wrong filename is reported as being unreadable in several error messages.
---
> [TD]fix misleading error messages
