src/Mod/PartDesign/App/FeatureHelix.cpp
Fixes #6482
The idea with the large factor, introduced in #5363 fixed real bugs, so it should not be reverted.
However we must compensate the factor at the path position movement. Otherwise we get wrong helix positions when the angle is negative.
The PR was tested with the files in the bug reports:
https://forum.freecadweb.org/viewtopic.php?f=3&t=65136
https://forum.freecadweb.org/viewtopic.php?p=572618#p572618
=> [PD] Helix: fix #6482

src/Mod/Fem/femmesh/meshtools.py
=> FEM: minor fix in warning text [skip ci]

src/Mod/Path/PathScripts/PathPocketBase.py, src/Mod/Path/PathScripts/PathPocketBaseGui.py
Remove unused and confusing spiral and triangle patterns
---
=> [Path] Fixes #5832

src/Mod/TechDraw/App/AppTechDrawPy.cpp
This PR fixes a condition where exported diameter dimensions were all aligned horizontally even if the source was at an angle.
---
=> [TD]fix diameter dim alignment in DXF

.github/codespellignore
see: https://github.com/FreeCAD/FreeCAD/pull/6464#issuecomment-1066980812
=> [Github] Add "detet" to the ignored misspellings

src/Mod/Path/PathScripts/PathProfile.py, src/Mod/Path/PathScripts/drillableLib.py
Makes profile operation detect circular holes correctly.
---
=> [Path] Fixes #6658

src/Mod/Path/PathScripts/PathMillFace.py
This fix addresses an incorrect shape variable passed when Boundary Shape is set to Face Region and there is no Base geometry - indicating entire model to be milled. …
=> Path: MillFace - Fix Face Region with no Base geometry [Bug]

src/Mod/TechDraw/App/ShapeExtractor.cpp, src/Mod/TechDraw/App/ShapeExtractor.h
This PR addresses the handling of infinite shapes which can not be projected.  Infinite shapes include datum lines, planes and LCS.
Note that this PR does not address the delivery of infinite shapes by Part::Feature::getShape, merely the handling of these shapes within TechDraw.
[Forum discussion 1](https://www.forum.freecadweb.org/viewtopic.php?f=20&t=67202)
[Forum discussion 2](https://www.forum.freecadweb.org/viewtopic.php?f=10&t=67320)
[Related issue 6655](https://github.com/FreeCAD/FreeCAD/issues/6655)
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in …
=> [TD]skip LCS infinite shapes

src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg, src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCustomizeFormat.svg, src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmCircle3Points.svg, src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionRemovePrefixChar.svg
- icons were causing an error msg from Qt.  No CI required.
---
=> [TD]Fix Extension Icons

src/Mod/Path/PathScripts/PathInspect.py
Minor tweaks to the inspect dialog.  Changed title and tooltip.
Removed text about saving changes.  Removed 'OK' button.  Only a 'Done' button now.
Changed the Notes at the bottom to make it clearer what the user is seeing.
Inspect now only becomes enabled if the user has selected an object with a Path property and the path has commands.
This means the inspect tool is not available if the user selects a job.  This is necessary since we changed the behavior of path visibility some time ago.  The job isn't a compound of the paths anymore so there's no path to show. …
=> [Path] Bug/inspecttweaks

src/Mod/Path/PathScripts/PathJobGui.py, src/Mod/Path/PathScripts/post/gcode_pre.py, src/Mod/Path/PathTests/TestPathPost.py, src/Mod/Path/TestPathApp.py
Check if Job object exists in active document.  If not, then add a Job object GUI support, but without a base model.
Fixes #6629 
Recent forum mention begins at [Re: import gCode](https://forum.freecadweb.org/viewtopic.php?f=15&t=47352&p=581585#p580528).
Steps to reproduce:
* Create new document.
* From `File` menu, select `Import`.
* Select a g-code file in the File Explorer window that is presented, and click `Open`.
* In the `Choose a processor` popup window, select the `gcode_pre` option for the Processor, and click `OK'.
* Error should occur.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items …
=> Path:  Fixes #6629 - Add missing Job for import G-code [Bug]

src/Mod/Draft/DraftVecUtils.py, src/Mod/Draft/draftguitools/gui_lines.py, src/Mod/Draft/draftguitools/gui_shapestrings.py, src/Mod/Draft/draftobjects/shapestring.py, src/Mod/Draft/drafttaskpanels/task_shapestring.py, src/Mod/Draft/draftviewproviders/view_text.py
=> Draft: Remove Python 2 type support

src/Base/Quantity.cpp, src/Gui/QuantitySpinBox.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=64261&p=584319#p584310
=> Fix quantity construction when unit as string is empty

src/Mod/Path/PathScripts/PathPocketBase.py
=> [Path] fix index error with PocketMode

src/Mod/Part/App/PrimitiveFeature.cpp
Fixes https://github.com/FreeCAD/FreeCAD/issues/6559
---
=> [Part] Fixes #6559 Helix Default Segment Length to 0.0

src/Gui/Stylesheets/Behave-dark.qss, src/Gui/Stylesheets/Dark-blue.qss, src/Gui/Stylesheets/Dark-contrast.qss, src/Gui/Stylesheets/Dark-green.qss, src/Gui/Stylesheets/Dark-orange.qss, src/Gui/Stylesheets/Darker-blue.qss, src/Gui/Stylesheets/Darker-green.qss, src/Gui/Stylesheets/Light-blue.qss, src/Gui/Stylesheets/Light-green.qss, src/Gui/Stylesheets/Light-orange.qss, src/Gui/Stylesheets/ProDark.qss, src/Gui/propertyeditor/PropertyItem.cpp, src/Gui/propertyeditor/PropertyItem.h
Forum thread https://forum.freecadweb.org/viewtopic.php?f=22&t=65633&p=569085#p569085
=> Gui: support auto grouping editing for PropertyEnumeration

src/Mod/Path/PathScripts/PathDressupHoldingTags.py, src/Mod/Path/PathScripts/PathGeom.py, src/Mod/Path/PathScripts/PathPropertyBagGui.py, src/Mod/Path/PathScripts/PathVcarve.py
Found some globals which were left over from debugging issues. Some of them resulting in a memory leak by holding on to more and more objects as path is used.
=> [PATH] - bugfix/Removed debugging globals

src/Gui/DlgExpressionInput.cpp
https://forum.freecadweb.org/viewtopic.php?t=67471
=> Gui: if expression is emptied, pressing Enter discards expression

src/Mod/TechDraw/Gui/QGIFace.cpp, src/Mod/TechDraw/Gui/QGIViewDimension.cpp
This PR addresses a situation where small artifacts are included in exported PDF files with some PDF viewers.
---
=> [TD]fix artifact in PDF export

src/Mod/Sketcher/SketcherExample.py
=> Sketcher: Replace Line with LineSegment

src/Mod/Draft/CMakeLists.txt, src/Mod/Draft/Draft.py, src/Mod/Draft/draftguitools/gui_shapestrings.py, src/Mod/Draft/draftmake/make_shapestring.py, src/Mod/Draft/drafttaskpanels/task_shapestring.py, src/Mod/Draft/draftviewproviders/view_facebinder.py, src/Mod/Draft/draftviewproviders/view_shapestring.py
With this changes, Draft ShapeString objects are editable when double-click on the model tree.
Two specific classes are added (ShapeStringTaskPanelCmd and ShapeStringTaskPanelEdit) to create the task panel used by the Draft_ShapeString command and by the view provider when the object is edited.
**Note**: If you don't have wiki access, then …
=> Draft: Make ShapeString editable by double-click - fixes #5885

src/Mod/Part/App/TopoShapePy.xml
Currently the method fails when it should return a reversed copy of the shape. 
---
=> Part: Enable reversed method in Python TopoShape class

src/Mod/Part/App/BRepOffsetAPI_MakeOffsetFix.h
=> Part: fix typo in App/BRepOffsetAPI_MakeOffsetFix.h [skip ci]

src/Mod/AddonManager/ALLOWED_PYTHON_PACKAGES.txt
Fixes https://github.com/KeithSloan/GDML/issues/92
---
=> AddonManager: Add gmsh-dev to ALLOWED_PYTHON_PACKAGES

src/App/ComplexGeoData.cpp, src/Mod/Part/App/PreCompiled.h, src/Mod/Part/App/TopoShapePyImp.cpp
The method does not set an error if the subname is invalid.
Also a valid initial substring, plus an arbitrary final one, is considered as valid, for example "Vertex4+whatever" is considered as string "Vertex4".
The regex in `ComplexGeData::getSubElementByName` is just as permissive as the current implementation, but prevent cases like the previous one.
And please remember to update the Wiki with the features added or changed once this PR …
=> Part: Fix getElement method in Python TopoShape class

src/Mod/Spreadsheet/App/PropertySheet.cpp, src/Mod/Spreadsheet/Gui/Command.cpp, src/Mod/Spreadsheet/Gui/SheetTableView.cpp, src/Mod/Spreadsheet/Gui/SheetTableView.h, src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp, src/Mod/Spreadsheet/Gui/SpreadsheetView.h
https://forum.freecadweb.org/viewtopic.php?f=3&t=67969
=> Spreadsheet: different improvements on Merge/Split functions

src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp, src/Mod/Fem/Gui/ViewProviderFemPostObject.h, src/Mod/Fem/femsolver/elmer/tasks.py
=> Fem: scale imported vtk data set

src/Mod/Part/App/PartFeatures.cpp, src/Mod/Part/Gui/Command.cpp
Followup to https://github.com/FreeCAD/FreeCAD/pull/6478 where accidentally the Reversed function was not added.
=> Part: reversed -- fix so it works with App::Links and App::Parts

src/Mod/Spreadsheet/App/Cell.cpp, src/Mod/Spreadsheet/App/PropertySheet.cpp, src/Mod/Spreadsheet/App/Sheet.cpp
https://forum.freecadweb.org/viewtopic.php?p=590151#p590151
=> Spreadsheet: fix extreme slow down with large empty cells

src/Mod/TechDraw/App/DrawGeomHatch.cpp, src/Mod/TechDraw/App/HatchLine.cpp, src/Mod/TechDraw/Gui/TaskGeomHatch.cpp
This PR fixes the selection of a different PAT file in the Geometric Hatch dialog. 
---
=> [TD]fix GeomHatch change file name

src/Mod/Part/App/TopoShapePyImp.cpp
The first commit have only some changes in code style.
The second add a `std::map` and a `std::vector` to associate the TopoShape*Py classes to the values on TopAbs_ShapeEnum,
a function `Part::ShapeTypeFromPyType` analogous to TopAbs::ShapeTypeFromString to get the shape type from a Python type and a template used in the methods TopoShapePy::get\*  to get shapes.
The function `TopoShapePy::ancestorsOfType` now raise an exception if the second paramenter isn't a Part.Shape subclass (currently accept any Python type).
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask …
=> Part: Add functions to replace indentical code structure in TopoShapePyImp.cpp

src/App/PropertyContainer.cpp
Problem reported in https://forum.freecadweb.org/viewtopic.php?f=22&t=42184&start=60#p590603
=> App: fix property conflict in App::Link restore

src/Mod/Path/InitGui.py
This is a proposed solution for a translation issue mentioned to me by @luzpaz at (https://github.com/FreeCAD/FreeCAD-translations/issues/120).
Please post any discussion or proposed changes here in this PR.
I do not see a forum thread.
I do not know how to link that issue to this PR since it is a different repo. …
=> Path: Update translated message syntax - InitGui module

src/Mod/AddonManager/AddonManager.py
Add code to attempt to fetch a remote version of the ALLOWED_PYTHON_PACKAGES.txt file from the FreeCAD-addons Github repository. If found, the file overrides the local copy.
=> Addon Manager: Fetch allowed py packages from Github repo

src/Mod/Part/Gui/ViewProviderExt.cpp
prevent ambiguous subelement names as "Face001" or "Vertex5+whatever".
---
=> Part: Use regex to match names in ViewProviderPartExt::getDetail

src/Mod/Path/PathScripts/PathPost.py
=> Path:  Added a missing "continue" to PathPost.py.

src/Mod/Mesh/Gui/DlgEvaluateMeshImp.cpp
=> Mesh: fix grammatical issue in console message string

src/Mod/Path/CMakeLists.txt
Add entries for missing post-processor modules so they are shipped with FreeCAD.
Forum identification at [How to know if a PR/commit to master is in release](https://forum.freecadweb.org/viewtopic.php?f=15&t=68388). …
=> Path: Add missing post-processor modules [bug]

src/Mod/TechDraw/App/DrawView.cpp, src/Mod/TechDraw/App/DrawView.h
This PR fixes a situation where change to X,Y properties of a DrawView object were not propagated to a second DrawView which referenced the first via expression.
[Forum discussion](https://www.forum.freecadweb.org/viewtopic.php?f=35&t=68417)
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 …
=> [TD]fix X,Y change propagation

src/Mod/Draft/draftguitools/gui_planeproxy.py
Issue:
https://github.com/FreeCAD/FreeCAD/issues/6058
Forum:
https://forum.freecadweb.org/viewtopic.php?f=23&t=46152
---
=> Draft: Fix Draft_WorkingPlaneProxy ignores Auto Working Plane

src/Mod/PartDesign/Gui/TaskDatumParameters.cpp, src/Mod/PartDesign/Gui/ViewProviderDatum.cpp, src/Mod/PartDesign/Gui/ViewProviderDatum.h
…s 
https://github.com/FreeCAD/FreeCAD-translations/issues/125
---
=> [PartDesign] Add individual QString for menu text which exposes text to translation

src/Mod/Spreadsheet/App/PropertySheet.cpp, src/Mod/Spreadsheet/App/PropertySheet.h, src/Mod/Spreadsheet/App/Sheet.cpp, src/Mod/Spreadsheet/Gui/SheetTableView.cpp
Problem reported in https://forum.freecadweb.org/viewtopic.php?f=8&t=68458
=> Spreadsheet: fix printing

src/Gui/PythonWrapper.cpp, src/Gui/PythonWrapper.h, src/Mod/TechDraw/Gui/AppTechDrawGuiPy.cpp
Some derived QGraphicsItems (ex QGraphicsSvgItem or QGraphicsTextItem) inherit from QGraphicsObject instead of directly from QGraphicsItem.  This PR adds a function to PythonWrapper to unwrap these QGraphicsObjects. …
=> Handle QGraphicsObject From Pyside

src/Mod/Path/InitGui.py
[Path] Fix python style for initial message
(now recognized by updatets.py script)
https://github.com/FreeCAD/FreeCAD-translations/issues/120
---
=> [Path] Final fix of Path - message during startup  (#43)

src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp, src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp, src/Mod/PartDesign/Gui/ViewProviderChamfer.h, src/Mod/PartDesign/Gui/ViewProviderDraft.h, src/Mod/PartDesign/Gui/ViewProviderDressUp.h, src/Mod/PartDesign/Gui/ViewProviderFillet.h, src/Mod/PartDesign/Gui/ViewProviderLinearPattern.h, src/Mod/PartDesign/Gui/ViewProviderMirrored.h, src/Mod/PartDesign/Gui/ViewProviderMultiTransform.h, src/Mod/PartDesign/Gui/ViewProviderPolarPattern.h, src/Mod/PartDesign/Gui/ViewProviderScaled.h, src/Mod/PartDesign/Gui/ViewProviderThickness.h, src/Mod/PartDesign/Gui/ViewProviderTransformed.h
https://github.com/FreeCAD/FreeCAD-translations/issues/24
---
=> [PartDesign] Fix and expose ViewProvider strings to translation

src/Mod/Spreadsheet/App/Sheet.cpp
Problem report in https://forum.freecadweb.org/viewtopic.php?p=593647#p593647
=> Spreadsheet: fix cell clearing

src/Mod/TechDraw/Gui/AppTechDrawGuiPy.cpp, src/Mod/TechDraw/Gui/TaskCenterLine.cpp, src/Mod/TechDraw/Gui/TaskCustomizeFormat.ui
This PR contains 3 small fixes - remove extra undo in TaskCenterLine cancel, cleanup of type checking in AppTechDrawGuiPy and a UI change to allow for longer translation strings. …
=> [TD]Small fixes

src/Mod/Path/PathScripts/post/grbl_post.py
- [X ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ X]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas …
=> Path: grbl_post: T, H and S GCode parameters are integers, not float numbers.

src/Mod/Path/PathScripts/post/nccad_post.py
**Mistake:** Following the build-instructions, CMake generated the VS project to use the source-code in the build-dir, which caused me to manually sync files to my git-repo. One tested change was not included in what was pushed, which caused nccad-PP to still give the same behaviour as the before the previous PR.
(I have now regenerated the VS project so that what is written & tested == what is being pushed).
---
And please remember to …
=> #6871 Use the variable 'cam_file' instead of trying to read 'activeDocument'

src/Mod/TechDraw/Gui/AppTechDrawGuiPy.cpp, src/Mod/TechDraw/Gui/CommandExtensionDims.cpp, src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionInsertSquare.svg, src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionRemovePrefixChar.svg, src/Mod/TechDraw/Gui/TaskCenterLine.cpp, src/Mod/TechDraw/Gui/TaskCustomizeFormat.ui
This PR corrects the special characters used in square and arc length dimensions and adjusts some spacing for legibility.
---
=> [TD]fix Dimension special characters

src/Mod/Path/PathScripts/PathFeatureExtensionsGui.py, src/Mod/Path/PathScripts/PathGui.py
These changes restore the extension size updating mechanism due to upstream code changes.
These changes fix the annoying requirement to apply Default Length value changes via a click to the task panel or viewport, by adding a manual signal emission.
Forum discussion at [Bug: Extensions - default length edit not updating extension sizes](https://forum.freecadweb.org/viewtopic.php?f=15&t=67699).
And please remember to update the Wiki with …
=> Path: Fix extensions updates and Default Length application [Bug]

src/App/Origin.cpp
Reported in https://forum.freecadweb.org/viewtopic.php?p=595438
@wwmayer
=> App: Fix Origin::extensionGetSubObject()

src/Mod/Test/Gui/UnitTestImp.cpp
=> [TestWB] fix source comment typo in `Gui/UnitTestImp.cpp`

src/Mod/Mesh/Init.py
Added `import FreeCAD`  
Added missing whitespace after commas  
Removed DOS line endings
=> Mesh: fix pep8 related issues in Init.py

src/Mod/TechDraw/Gui/TaskSectionView.cpp
This PR fixes an issue where the string representation of a PropertyEnumeration is used to set the property.   The translated string is not a valid value  for the enumeration and the operation fails. …
=> [TD]Fix handling of translated PropertyEnumeration

src/Mod/Draft/draftguitools/gui_trackers.py
If the grid spacing was updated in this sequence: 1 -> 0 -> 1 (or any sequence where the first and last value are equal and the second value zero), the grid would not be redrawn.
---
=> Draft: Fix grid update issue

src/Mod/Spreadsheet/Gui/SheetModel.cpp, src/Mod/Spreadsheet/Gui/SheetModel.h
See https://forum.freecadweb.org/viewtopic.php?f=8&t=68529
=> Spreadsheet: fix possible crash in SheetModel::setData

src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp, src/Mod/PartDesign/Gui/ViewProviderMultiTransform.cpp
=> PartDesign: Remove redundant comparision with null pointer

src/Base/AxisPy.xml
=> Base: Improve docstrings in AxisPy.xml

src/Mod/Part/App/FeatureExtrusion.cpp, src/Mod/Part/App/FeatureRevolution.cpp, src/Mod/Part/App/PartFeatures.cpp, src/Mod/Part/App/PartFeatures.h, src/Mod/Part/Gui/Command.cpp, src/Mod/Part/Gui/DlgExtrusion.cpp, src/Mod/Part/Gui/TaskSweep.cpp
This PR is a continuation of #6761
@mwganson 
@donovaly
=> Part: Link support 

src/Base/PlacementPy.xml
=> Base: Improve docstrings in PlacementPy.xml

src/Gui/DlgSettingsColorGradientImp.cpp
=> buttonClicked(int id) is deprecated since Qt 5.15. Use idClicked(int id) instead.

src/Base/PlacementPy.xml, src/Base/RotationPy.xml
=> Base: Improve docstrings in RotationPy.xml

src/Mod/TechDraw/App/DrawProjGroupItem.cpp, src/Mod/TechDraw/App/DrawView.cpp, src/Mod/TechDraw/Gui/QGIView.cpp, src/Mod/TechDraw/Gui/QGIView.h
The PR addresses a situation where an unnecessary  full recompute is done when views are re-positioned.
---
=> [TD]prevent spurious recompute on click/drag

src/Gui/SoFCColorBar.cpp, src/Gui/SoFCColorBar.h, src/Gui/SoFCColorGradient.cpp, src/Gui/SoFCColorLegend.cpp
=> Gui: fix number display issue of color bar

src/Mod/Draft/Resources/ui/TaskSelectPlane.ui, src/Mod/Draft/draftguitools/gui_selectplane.py, src/Mod/Draft/draftguitools/gui_trackers.py, src/Mod/Draft/draftutils/utils.py
Fixes issues introduced with #5427 // 6157147
https://forum.freecadweb.org/viewtopic.php?f=23&t=68675
=> Draft: fix issues with grid spacing parameter

src/App/Application.cpp, src/Mod/Test/TestApp.py
Without parameter all available test units will listed. I hope the hints clarify the using.
---
Closes #6809
=> App: CLI -t flag list all available unit tests

src/Mod/Part/AttachmentEditor/Commands.py, src/Mod/Part/Gui/Workbench.cpp
Add menu text "Create a copy" to translation
This may fix https://github.com/FreeCAD/FreeCAD-translations/issues/64
---
=> Part: Change contex from AttachmentEditor to Part_EditAttachment

src/Mod/Mesh/Gui/Workbench.cpp
This fix https://github.com/FreeCAD/FreeCAD-translations/issues/53
---
=> [Mesh] Add ability to translate

src/Base/AxisPyImp.cpp
=> Base: Fix bad parse argument in AxisPyImp.cpp

src/Mod/TechDraw/Gui/TaskCosVertex.cpp
This will fix https://github.com/FreeCAD/FreeCAD-translations/issues/47
---
=> [TD] Add text to translate

src/Base/TypePy.xml
=> Base: Improve docstrings in TypePy.xml

src/Mod/TechDraw/Gui/QGIView.cpp, src/Mod/TechDraw/Gui/QGIView.h, src/Mod/TechDraw/Gui/QGIViewBalloon.cpp, src/Mod/TechDraw/Gui/QGIViewBalloon.h, src/Mod/TechDraw/Gui/QGIViewDimension.cpp, src/Mod/TechDraw/Gui/QGIViewDimension.h, src/Mod/TechDraw/Gui/ViewProviderBalloon.cpp, src/Mod/TechDraw/Gui/ViewProviderDimension.cpp
This PR adds changes to Dimension/Balloon views that were omitted in commit d223d4362c / PR #6942.
---
=> [TD]fix Dimension/Balloon movement

src/Mod/Fem/Gui/Resources/translations/Fem.ts
=> Crowdin Update Fem.ts

src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp
This PR addresses an issue where changes to a shared view were only reflected on one Page instead of both Pages.
hank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!
---
=> [TD]fix updating of shared view

src/Base/PersistencePy.xml
=> Base: Improve docstrings in PersistencePy.xml

src/Mod/TechDraw/Gui/TaskBalloon.ui, src/Mod/TechDraw/Gui/TaskCenterLine.ui, src/Mod/TechDraw/Gui/TaskCosVertex.ui, src/Mod/TechDraw/Gui/TaskCustomizeFormat.ui, src/Mod/TechDraw/Gui/TaskDetail.ui
=> [TD]Fix missing vertical spacers

src/Mod/Draft/Resources/ui/preferences-draftsnap.ui
Relates to #5427 
Especially fixes https://github.com/FreeCAD/FreeCAD/pull/5427#issuecomment-1127336478
https://forum.freecadweb.org/viewtopic.php?t=69222#p600173
For those who may want to build for testing, do not forget to `touch src/Mod/Draft/Resources/Draft.qrc`
Ping @yorikvanhavre
=> Draft: fix grid spacing default initialization

src/App/GeoFeaturePy.xml
=> App: Improve docstrings in GeoFeaturePy.xml

src/Gui/AxisOriginPy.xml, src/Gui/AxisOriginPyImp.cpp
The function `getDetailPath` seems to be a copy/paste of the `ViewProviderPy::getDetailPath`, but allways returns `Py_None` since in the `AxisOrigin::getDetailPath`function  the `SoDetail` arguement is not used.
I kept the structure as-is and made the lack of implementation clear in the docstrings, in case AxisOrigin:::getDetailPath is not fully implemented yet.
In `getPlane` the parse of the paramenters is fixed to prevent an undefined behaviour.
Example:
```
a = Gui.AxisOrigin()
a.Plane = (6, 7) -> undefined behaviour
```
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate …
=> Gui: Improve docstrings in AxisOriginPy.xml

src/App/Range.cpp, src/App/Range.h, src/Mod/Spreadsheet/App/Sheet.cpp, src/Mod/Spreadsheet/Gui/DlgBindSheet.cpp
Forum post: https://forum.freecadweb.org/viewtopic.php?f=3&t=69219&p=600767#p600835
@donovaly
=> Spreadsheet: fix range checking

src/App/MetadataPy.xml, src/App/MetadataPyImp.cpp
@chennes just reformating the docstrings.
In `MetadataPy::getGenericMetadata` is fixed the bad parsing of the argument and a memory leak of the `Py::List`.
---
=> App: Improve docstrings in MetadataPy.xml and fix memory leak

src/Mod/Fem/Gui/Command.cpp
the stress linearization plot is at the moment detached from FreeCAD's main window.
This PR fixes it the same way as in https://github.com/FreeCAD/FreeCAD/commit/920e8e046
=> [FEM] fix detached plot

src/App/PropertyContainerPy.xml, src/App/PropertyContainerPyImp.cpp
=> App: Clean up code and improve docstrings in Python PropertyContainer class

src/App/Expression.cpp, src/Mod/Test/Document.py
Fixes #6948
https://forum.freecadweb.org/viewtopic.php?f=3&t=52691
Set as Draft time to add unit test and PR to be checked by some users (there's a bit of sorcery in this)
=> [Bugfix] Expression: fix precedence+associativity management in parenthesis removal

src/Mod/Spreadsheet/App/PropertySheet.cpp, src/Mod/Spreadsheet/App/PropertySheet.h, src/Mod/Spreadsheet/Gui/SheetTableView.cpp
Forum post https://forum.freecadweb.org/viewtopic.php?p=601316#p601316
@donovaly
=> Spreadsheet: fix range selection

src/Mod/Spreadsheet/App/PropertySheet.cpp, src/Mod/Spreadsheet/App/Sheet.cpp, src/Mod/Spreadsheet/Gui/SpreadsheetDelegate.cpp
Forum post https://forum.freecadweb.org/viewtopic.php?p=601612#p601612
@donovaly
=> Spreadsheet: fix binding for merged cells

src/Mod/Sketcher/Gui/Workbench.cpp
Will fix https://github.com/FreeCAD/FreeCAD-translations/issues/168
---
=> [Crowdin] Add Command to translate

src/Base/BoundBoxPy.xml, src/Base/BoundBoxPyImp.cpp
=> Base: Improve docstrings in BoundBoxPy.xml

src/Mod/Fem/App/FemVTKTools.cpp
https://forum.freecadweb.org/viewtopic.php?f=18&t=69385
---
=> Fixing principal stress plots part 1

src/Mod/Fem/femresult/resulttools.py
https://forum.freecadweb.org/viewtopic.php?f=18&t=69385
---
=> Fixing principal stress plots part 2

README.md
Update URL to HTTPS for security reasons.
=> README.md: Update URL to HTTPS

src/Mod/TechDraw/App/DrawProjGroup.cpp
This PR addresses 2 issues.  The first is an error in positioning secondary views when AutoDistribute is true.  The second is a condition where Dimensions in a DrawProjGroupItem when the scale of the parent DrawProjGroup is changed. …
=> [TD]Fix ProjectionGroups Spacing and Dimension Update

src/Mod/Fem/App/FemMesh.cpp, src/Mod/Fem/Gui/Command.cpp, src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- reported by MSVC not to cast a float to a double but as double directly
- also remove some superfluous Boolean comparisons
=> [FEM] fix a variable casting

src/Mod/Part/App/AppPartPy.cpp, src/Tools/generateTemplates/templateClassPyExport.py
=> remove unused python version<3.6 code

src/Base/Rotation.cpp
See https://forum.freecadweb.org/viewtopic.php?f=10&t=69538
---
=> Base: Set angle in Rotation::inverse function

src/Base/RotationPy.xml
=> Base: Fix wrong function name in RotationPy documentation.

src/Mod/Path/Gui/Resources/translations/Path.ts, src/Mod/Path/PathScripts/PathToolBitLibraryGui.py
This will fix https://github.com/FreeCAD/FreeCAD-translations/issues/174
---
=> [Path] Add localization for PathToolBit and update Path.ts

src/Mod/Path/Gui/Resources/panels/PathEdit.ui, src/Mod/Path/Gui/Resources/preferences/PathJob.ui
Fixes #6515
Adds additional substitution strings to the PathJob and Preference panels.  The substitution logic was recently merged in PR 6637
---
=> [Path] Enable improved output naming.

src/Gui/Stylesheets/Behave-dark.qss, src/Gui/Stylesheets/Dark-blue.qss, src/Gui/Stylesheets/Dark-contrast.qss, src/Gui/Stylesheets/Dark-green.qss, src/Gui/Stylesheets/Dark-orange.qss, src/Gui/Stylesheets/Darker-blue.qss, src/Gui/Stylesheets/Darker-green.qss, src/Gui/Stylesheets/Darker-orange.qss, src/Gui/Stylesheets/Light-blue.qss, src/Gui/Stylesheets/Light-green.qss, src/Gui/Stylesheets/Light-orange.qss, src/Gui/Stylesheets/ProDark.qss
=> Stylesheets: fix typos

src/Mod/Path/CMakeLists.txt
=> [Path] Missing camoticsgui file in the CMakelists.

src/Base/MatrixPy.xml
multiply(), determinant(), isOrthogonal(),
submatrix(), analyze() also get the const attribute
Follow-up to https://forum.freecadweb.org/viewtopic.php?f=10&t=69615&p=604341#p604341 …
=> Base: add Const attribute to many MatrixPy methods

src/Mod/Part/App/Geometry.cpp, src/Mod/Part/App/Geometry.h
Please see the [topic](https://forum.freecadweb.org/viewtopic.php?f=10&t=68838).
I will require it later for new importer. 
edit:
[cross-reference](https://github.com/ageeye/FreeCAD/blob/dxfNext/src/Mod/Import/App/dxf/fcDxfReader.cpp)
=> Part: `GeomBSplineCurve::interpolate` without tangency

src/Gui/Language/FreeCAD.ts, src/Mod/Arch/Resources/translations/Arch.ts, src/Mod/Draft/Resources/translations/Draft.ts, src/Mod/Fem/Gui/Resources/translations/Fem.ts, src/Mod/Inspection/Gui/Command.cpp, src/Mod/Inspection/Gui/Resources/translations/Inspection.ts, src/Mod/Material/Resources/translations/Material.ts, src/Mod/Mesh/Gui/Resources/translations/Mesh.ts, src/Mod/Part/Gui/Resources/translations/Part.ts, src/Mod/PartDesign/Gui/Resources/translations/PartDesign.ts, src/Mod/Path/Gui/Resources/translations/Path.ts, src/Mod/Points/Gui/Resources/translations/Points.ts, src/Mod/Robot/Gui/Resources/translations/Robot.ts, src/Mod/Sketcher/Gui/Resources/translations/Sketcher.ts, src/Mod/Spreadsheet/Gui/Resources/translations/Spreadsheet.ts, src/Mod/TechDraw/Gui/Resources/translations/TechDraw.ts, src/Tools/updatets.py
=> Crowdin Add "new" WB to translations.

src/Mod/Draft/draftmake/make_sketch.py
This PR should fix issue https://github.com/FreeCAD/FreeCAD/issues/7058
FYI: an alternative solution that also works:
```
point = shapes_list[0].Vertexes[0].Point
point = rotation.inverted().multVec(point)
base = rotation.multVec(App.Vector(0, 0, point.z))
nobj.Placement = App.Placement(base, rotation)
```
---
=> Draft: Fix Sketch Placement in make_sketch (issue #7058)

src/Mod/TechDraw/App/CMakeLists.txt
This PR removes an obsolete build dependency on the Drawing WB.
---
=> [TD]remove build depend on DrawingWB

src/App/Enumeration.cpp, src/App/Enumeration.h, src/App/FeatureTest.cpp, src/App/Link.cpp, src/App/PropertyStandard.cpp, src/App/PropertyStandard.h, src/Gui/DlgDisplayPropertiesImp.cpp, src/Gui/TaskView/TaskAppearance.cpp, src/Gui/propertyeditor/PropertyItem.cpp, src/Mod/Fem/App/FemPostFilter.cpp, src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp, src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
=> App: fix memory leaks in Enumeration class and simplify code

src/Mod/Part/App/Geometry.cpp, src/Mod/Part/App/Geometry.h
Minimal improvements for Part::Geometry.
=> Part: Geometry improvements

src/Mod/Path/PathScripts/PathDressupLeadInOut.py
Adds missing Z and K values to arc commands.
No forum discussion. Fixes #6693
---
=> Path: Fixes #6693 - Add Z and K values to arc commands

src/Mod/Draft/draftguitools/gui_selectplane.py
Fix for https://github.com/FreeCAD/FreeCAD/issues/7043
---
=> Draft: Fix align working plane to DatumPlane bug

src/Base/Builder3D.cpp, src/Base/MemDebug.cpp, src/Base/StackWalker.cpp, src/Base/StackWalker.h, src/CXX/Python3/Config.hxx, src/Main/MainGui.cpp, src/Mod/Drawing/Gui/TaskOrthoViews.cpp, src/Mod/Fem/App/FemConstraint.cpp, src/Mod/Mesh/App/WildMagic4/Wm4Platforms.h, src/Tools/thumbs/StdAfx.h
=> Remove old msc ver. Freecad 0.20 require 64 bit and windows 7 or higher. For this reason, msc libraries less than 1800 will no longer be used.

src/Mod/Part/App/GeometryCurvePy.xml, src/Mod/Part/App/GeometryCurvePyImp.cpp
Related forum thread : https://forum.freecadweb.org/viewtopic.php?style=4&f=22&t=69766
This is almost a copy/paste of the surface method : https://github.com/FreeCAD/FreeCAD/commit/9d311b2b12f563116bfb1d54ab597eeb51cd85b4 …
=> Part: add method to project point on curve

src/Mod/Sketcher/App/CMakeLists.txt, src/Mod/Sketcher/App/PythonConverter.cpp, src/Mod/Sketcher/App/PythonConverter.h
It does not add visible functionality.
Class to generate Python commands to add geometry and constraints.
=> Sketcher: Python converter

src/Mod/Path/InitGui.py, src/Mod/Path/PathScripts/PathGuiInit.py
Another import bug.  This time if --version doesn't return a patch number.
Per Gauthier Brière
---
=> [PATH] Another camotics import bug.  

src/Mod/TechDraw/App/AppTechDrawPy.cpp, src/Mod/TechDraw/App/DrawUtil.cpp, src/Mod/TechDraw/App/DrawUtil.h, src/Mod/TechDraw/App/DrawViewDimension.cpp, src/Mod/TechDraw/App/DrawViewDimension.h
=> [TD]fix Dimension export to DXF

src/Mod/TechDraw/Gui/MDIViewPage.h, src/Mod/TechDraw/Gui/QGSPage.cpp, src/Mod/TechDraw/Gui/QGSPage.h, src/Mod/TechDraw/Gui/QGVNavStyle.cpp, src/Mod/TechDraw/Gui/QGVNavStyle.h, src/Mod/TechDraw/Gui/QGVNavStyleBlender.cpp, src/Mod/TechDraw/Gui/QGVNavStyleBlender.h, src/Mod/TechDraw/Gui/QGVNavStyleCAD.cpp, src/Mod/TechDraw/Gui/QGVNavStyleCAD.h, src/Mod/TechDraw/Gui/QGVNavStyleGesture.cpp, src/Mod/TechDraw/Gui/QGVNavStyleGesture.h, src/Mod/TechDraw/Gui/QGVNavStyleInventor.cpp, src/Mod/TechDraw/Gui/QGVNavStyleInventor.h, src/Mod/TechDraw/Gui/QGVNavStyleMaya.cpp, src/Mod/TechDraw/Gui/QGVNavStyleMaya.h, src/Mod/TechDraw/Gui/QGVNavStyleOCC.cpp, src/Mod/TechDraw/Gui/QGVNavStyleOCC.h, src/Mod/TechDraw/Gui/QGVNavStyleOpenSCAD.cpp, src/Mod/TechDraw/Gui/QGVNavStyleOpenSCAD.h, src/Mod/TechDraw/Gui/QGVNavStyleRevit.cpp, src/Mod/TechDraw/Gui/QGVNavStyleRevit.h, src/Mod/TechDraw/Gui/QGVNavStyleTinkerCAD.cpp, src/Mod/TechDraw/Gui/QGVNavStyleTinkerCAD.h, src/Mod/TechDraw/Gui/QGVNavStyleTouchpad.cpp, src/Mod/TechDraw/Gui/QGVNavStyleTouchpad.h, src/Mod/TechDraw/Gui/QGVPage.cpp, src/Mod/TechDraw/Gui/QGVPage.h
This PR implements context menu handling and FC standard cursors for TD navigation styles.
---
=> [TD]Nav style context menues and standard cursors

README.md
Per donovaly in https://github.com/FreeCAD/FreeCAD/pull/7049#issuecomment-1172826186  
[skip ci]
=> TPN: added revisions to README

src/Mod/Robot/App/Robot6Axis.cpp, src/Mod/Robot/App/Robot6Axis.h
- just to please the spellchecker CI, see https://github.com/FreeCAD/FreeCAD/runs/7118611287?check_suite_focus=true
=> [Robot] fix typo in function name

src/Mod/Path/Generators/drill_generator.py, src/Mod/Path/PathScripts/PathDrilling.py, src/Mod/Path/PathTests/TestPathDrillGenerator.py
Fix for [this issue on the forum](https://forum.freecad.org/viewtopic.php?f=15&t=69186&sid=30cefe26c82478ec932bf61358854080).
This pull-request restores the Drilling Operation retract behaviour to pre 5b23af3. …
=> Path: Restore drilling op retract value to user supplied Retract Height

src/App/Document.cpp
Use the real path to the file when saving the document.
---
=> [App] Fix #5592 : Respect symbolic links

src/Mod/TechDraw/App/Preferences.cpp, src/Mod/TechDraw/App/Preferences.h, src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui, src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensionsImp.cpp, src/Mod/TechDraw/Gui/QGIViewDimension.cpp, src/Mod/TechDraw/Gui/QGIViewDimension.h, src/Mod/TechDraw/Gui/ViewProviderDimension.cpp, src/Mod/TechDraw/Gui/ViewProviderDimension.h
This PR implements adjustable gaps for extension lines (#6774).
---
=> [TD]adjustable extension line gap

src/Mod/TechDraw/TechDrawTools/TaskMoveView.py, src/Mod/TechDraw/TechDrawTools/TaskShareView.py
This PR fixes an issue reported here; https://www.forum.freecadweb.org/viewtopic.php?f=35&t=69943 where multiple copies of selection dialogs can be opened.
---
=> [TD]fix multiple open dialogs

src/Base/ConsoleObserver.h, src/Gui/BitmapFactory.cpp, src/Gui/MainWindow.cpp, src/Gui/ReportView.cpp, src/Mod/Test/BaseTests.py, src/Mod/Test/Gui/AppTestGui.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=69419
=> Gui: correctly save and restore message type enabling in report view

src/Mod/TechDraw/Gui/QGCustomBorder.cpp, src/Mod/TechDraw/Gui/QGCustomClip.cpp, src/Mod/TechDraw/Gui/QGCustomImage.cpp, src/Mod/TechDraw/Gui/QGCustomLabel.cpp, src/Mod/TechDraw/Gui/QGCustomRect.cpp, src/Mod/TechDraw/Gui/QGCustomSvg.cpp, src/Mod/TechDraw/Gui/QGCustomText.cpp, src/Mod/TechDraw/Gui/QGDisplayArea.cpp
[TechDraw] Use function overloadin and avoid code repeat
=> [TechDraw] Use function overloadin and avoid code repeat

src/Mod/TechDraw/Gui/CommandAnnotate.cpp, src/Mod/TechDraw/Gui/CommandCreateDims.cpp, src/Mod/TechDraw/Gui/CommandDecorate.cpp, src/Mod/TechDraw/Gui/CommandExtensionDims.cpp, src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
Improving readability of commands by avoiding nesting and uneeded variables.
---
---
=> [TechDraw] Improve readability of commands

src/Gui/PreferencePackTemplates/Window_Colors.cfg, src/Gui/ViewParams.h, src/Gui/ViewProviderGeometryObject.cpp, src/Mod/Part/Gui/DlgSettingsObjectColor.cpp, src/Mod/Part/Gui/DlgSettingsObjectColor.ui, src/Mod/Part/Gui/SectionCutting.ui, src/Mod/PartDesign/Gui/ViewProviderShapeBinder.cpp
- allow to specify the default  transparency for new shapes
=> [PD] add preferences setting for transparency

src/Mod/Fem/Gui/Resources/translations/Fem_de.ts
=> small corrections of German translation in FEM Gmsh

src/Mod/Draft/DraftGui.py
=> Draft: fix spacing of ToolTip text

src/Mod/TechDraw/Gui/CommandCreateDims.cpp
8c0ab46b4d contains some errors in object selection validation.  This PR corrects them.
---
=> [TD]fixes for Dimensions 

src/Mod/Fem/App/FemConstraintBearing.cpp, src/Mod/Fem/coding_conventions.md, src/Mod/Fem/femguiutils/selection_widgets.py, src/Mod/Fem/feminout/convert2TetGen.py, src/Mod/Fem/feminout/importCcxFrdResults.py, src/Mod/Fem/feminout/importZ88Mesh.py, src/Mod/Fem/feminout/importZ88O2Results.py, src/Mod/Fem/femmesh/gmshtools.py, src/Mod/Fem/femmesh/meshtools.py, src/Mod/Fem/femobjects/constraint_electrostaticpotential.py, src/Mod/Fem/femsolver/calculix/write_femelement_geometry.py, src/Mod/Fem/femsolver/elmer/writer.py, src/Mod/Fem/femsolver/z88/tasks.py, src/Mod/Fem/femtaskpanels/task_constraint_electrostaticpotential.py, src/Mod/Fem/femtaskpanels/task_material_common.py, src/Mod/Fem/femtaskpanels/task_material_reinforced.py, src/Mod/Fem/femtaskpanels/task_result_mechanical.py, src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py, src/Mod/Fem/femtest/app/support_utils.py, src/Mod/Fem/femviewprovider/view_mesh_gmsh.py, src/Mod/Fem/femviewprovider/view_result_mechanical.py
---
code formatting according https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Fem/coding_conventions.md
=> FEM: python code formatting

src/Mod/TechDraw/App/ShapeExtractor.cpp
=> [TD]fix crash on body with no shape

src/Mod/Path/App/PathSegmentWalker.cpp, src/Mod/Path/Gui/Resources/panels/PathEdit.ui, src/Mod/Path/Gui/ViewProviderPath.cpp, src/Mod/Path/PathScripts/PathFixture.py, src/Mod/Path/PathScripts/PathGuiInit.py, src/Mod/Path/PathScripts/PathJobGui.py, src/Mod/Path/PathScripts/PathSurface.py
=> [Path]  Several small bug fixes

src/Mod/Draft/Resources/ui/dialogHatch.ui
Form -> Hatch
Also added a missing colon (:).
---
=> Draft: Fix Hatch task panel title

src/Mod/TechDraw/Gui/TaskCenterLine.cpp, src/Mod/TechDraw/Gui/TaskDetail.cpp, src/Mod/TechDraw/Gui/TaskLeaderLine.cpp, src/Mod/TechDraw/Gui/TaskLinkDim.cpp, src/Mod/TechDraw/Gui/TaskProjGroup.cpp, src/Mod/TechDraw/Gui/TaskRichAnno.cpp, src/Mod/TechDraw/Gui/TaskSectionView.cpp, src/Mod/TechDraw/Gui/TaskSelectLineAttributes.cpp, src/Mod/TechDraw/Gui/TaskWeldingSymbol.cpp, src/Mod/TechDraw/Gui/TaskWeldingSymbol.h, src/Mod/TechDraw/Gui/ViewProviderBalloon.cpp, src/Mod/TechDraw/Gui/ViewProviderDimension.cpp, src/Mod/TechDraw/Gui/ViewProviderGeomHatch.cpp, src/Mod/TechDraw/Gui/ViewProviderHatch.cpp, src/Mod/TechDraw/Gui/ViewProviderLeader.cpp, src/Mod/TechDraw/Gui/ViewProviderPage.cpp, src/Mod/TechDraw/Gui/ViewProviderProjGroupItem.cpp, src/Mod/TechDraw/Gui/ViewProviderRichAnno.cpp, src/Mod/TechDraw/Gui/ViewProviderTemplate.cpp, src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp, src/Mod/TechDraw/Gui/ViewProviderViewSection.cpp, src/Mod/TechDraw/Gui/ViewProviderWeld.cpp
=> [TechDraw] Improve readability of GUI scripts

src/Mod/Fem/App/FemMesh.cpp, src/Mod/Fem/App/FemPostPipeline.cpp, src/Mod/Fem/App/FemVTKTools.cpp, src/Mod/Fem/App/PreCompiled.h, src/Mod/Fem/Gui/DlgSettingsFemElmer.ui, src/Mod/Fem/Gui/DlgSettingsFemElmerImp.cpp, src/Mod/Fem/Gui/DlgSettingsFemElmerImp.h, src/Mod/Fem/Init.py, src/Mod/Fem/femsolver/elmer/tasks.py, src/Mod/Fem/femsolver/elmer/writer.py, src/Mod/Fem/femsolver/settings.py
- this needs proper testing, especially on a non-Windows system
- note that for some tasks multi-threading requires non-standard additional solvers like MUMPS. Ideally the user should be informed about this, depending on the equations he uses. But this should not block this PR, meaning to use multi-threading in general.
=> [FEM] enable to run Elmer multi-threaded

src/Mod/TechDraw/App/Preferences.cpp, src/Mod/TechDraw/App/Preferences.h, src/Mod/TechDraw/Gui/CommandCreateDims.cpp, src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui, src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensionsImp.cpp, src/Mod/TechDraw/Gui/ViewProviderDimension.cpp
=> {TD]Fix dim gap preference

src/Mod/TechDraw/App/Cosmetic.cpp, src/Mod/TechDraw/App/Cosmetic.h
- Gather rotation calculations in a single function
- Use default parameters for LineFormat constructor
- Use constructor delegation and default parameters for CosmeticEdge
- Refactor CosmeticEdge constructors
- Improve readability of Cosmetic.cpp
- Gather rotation calculations in a single function …
=> [TechDraw] Refactor cosmetic.cpp

src/Mod/TechDraw/App/DrawUtil.cpp
=> [TechDraw] Improve readability of DrawUtil.cpp

src/Mod/Path/PathScripts/PathCamoticsGui.py, src/Mod/Path/PathScripts/PathToolBit.py, src/Mod/Path/PathScripts/PathToolBitLibraryGui.py
https://github.com/CauldronDevelopmentLLC/CAMotics/issues/335#issuecomment-1180062475
---
=> [Path] export a camotics tooltable

src/Mod/PartDesign/App/Body.cpp, src/Mod/PartDesign/App/Body.h, src/Mod/PartDesign/App/Feature.cpp, src/Mod/PartDesign/App/FeatureDraft.cpp, src/Mod/PartDesign/App/FeatureLinearPattern.cpp, src/Mod/PartDesign/App/FeatureMirrored.cpp, src/Mod/PartDesign/App/FeaturePocket.cpp, src/Mod/PartDesign/App/FeaturePolarPattern.cpp, src/Mod/PartDesign/App/FeatureSketchBased.cpp
- also Body: get rid of some nasty single-letter variables
=> [PD] App: remove superfluous nullptr checks

src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp, src/Mod/PartDesign/Gui/TaskExtrudeParameters.h, src/Mod/PartDesign/Gui/TaskPadParameters.cpp, src/Mod/PartDesign/Gui/TaskPadPocketParameters.ui, src/Mod/PartDesign/Gui/TaskPocketParameters.cpp
- this PR extends PR #7191 as described in this forum thread: https://forum.freecadweb.org/viewtopic.php?f=3&t=70327
=> [PD] improve face selection for Pad/Pocket

src/Mod/PartDesign/App/FeatureExtrude.cpp, src/Mod/PartDesign/App/FeatureExtrude.h, src/Mod/PartDesign/App/FeaturePad.cpp, src/Mod/PartDesign/App/FeaturePocket.cpp
- currently all parameters are always enabled and thus can lead to errors like the one reported here:
https://forum.freecadweb.org/viewtopic.php?f=3&t=70266
=> [PD] add parameter enabling logic for pad/pocket

src/Doc/BuildWebDoc.cfg.in, src/Doc/templates/customdoxygen.css, src/Doc/templates/doxy-boot.js, src/Doc/templates/footer.html, src/Doc/templates/header.html
- Migrate BuildWebDoc.cfg.in to doxygen 1.9.4
- Clean up footer and header for WebDoc
---
=> [Doc] Migrate WebDoc to doxygen 1.9.4 and improve layout

src/Mod/Arch/ArchAxis.py, src/Mod/Arch/ArchBuilding.py, src/Mod/Arch/ArchCommands.py, src/Mod/Arch/ArchFloor.py, src/Mod/Arch/ArchReference.py, src/Mod/Arch/ArchSite.py, src/Mod/Arch/ArchStructure.py, src/Mod/Draft/draftfunctions/upgrade.py, src/Mod/Draft/draftguitools/gui_edit_draft_objects.py, src/Mod/OpenSCAD/OpenSCADCommands.py, src/Mod/OpenSCAD/importCSG.py, src/Mod/PartDesign/Scripts/Gear.py, src/Mod/Path/PathScripts/PathDressupPathBoundary.py, src/Mod/Path/PathScripts/post/heidenhain_post.py, src/Mod/Path/PathScripts/post/philips_post.py, src/Mod/Test/Menu.py
Please have any Pythionist have a look and merge if OK.
=> Mod: remove some superfluous Boolean checks

src/Mod/TechDraw/App/DrawRichAnno.cpp, src/Mod/TechDraw/App/DrawTile.cpp, src/Mod/TechDraw/App/DrawViewAnnotation.cpp, src/Mod/TechDraw/App/DrawViewArch.cpp, src/Mod/TechDraw/App/DrawViewBalloon.cpp, src/Mod/TechDraw/App/DrawViewClip.cpp
=> [TD]rebase and review comments - replaces #7197

src/Mod/TechDraw/Gui/CMakeLists.txt, src/Mod/TechDraw/Gui/CommandAnnotate.cpp, src/Mod/TechDraw/Gui/Resources/TechDraw.qrc, src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_SurfaceFinishSymbols.svg, src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.cpp, src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.h, src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.ui, src/Mod/TechDraw/Gui/Workbench.cpp
Co-authored-by: Benjamin Bræstrup Sayoc <benj5378@outlook.com>
---
=> [TD] Add SurfaceFinishSymbol command - replaces #7220

src/Mod/TechDraw/App/DrawViewDetail.cpp, src/Mod/TechDraw/App/DrawViewDimExtent.cpp, src/Mod/TechDraw/App/DrawViewDimension.cpp, src/Mod/TechDraw/App/DrawViewDraft.cpp, src/Mod/TechDraw/App/DrawViewImage.cpp, src/Mod/TechDraw/App/DrawViewMulti.cpp
[TechDraw] Improve readability of DrawViewDimension.cpp
[TechDraw] Improve readability of DrawViewDimExtent.cpp
[TechDraw] Improve readability of DrawViewDraft.cpp
[TechDraw] Improve readability of DrawViewImage.cpp
[TechDraw] Improve readability of DrawViewMulti.cpp …
=> [TechDraw] Improve readability of DrawViewDetail.cpp replaces #7199

src/Mod/Part/App/ShapeFix/ShapeFix_ShellPy.xml, src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.h
=> Fix typos in Part and TechDraw workbenches 

.arcconfig, .gitignore
=> Git ignore hidden files with defined exceptions

src/Mod/Draft/importAirfoilDAT.py, src/Mod/Draft/importDWG.py, src/Mod/Draft/importDXF.py, src/Mod/Draft/importOCA.py
See: https://github.com/FreeCAD/FreeCAD/pull/7233
---
=> Draft: Housekeeping: import translate from correct file

src/Mod/Draft/WorkingPlane.py
The `DraftGeomUtils.getQuad` function that was used to rotate the working plane to match the global axes (if possible) can only handle quad faces. For all other faces the working plane remained unrotated. This could lead to strange results when inserting Arch_Windows. The first window in a wall would be inserted correctly (the wall face is a quad and the plane was rotated if required), but the second window could be inserted upside-down (because the wall face is no longer a quad the plane was not rotated).
Forum topic:
https://forum.freecadweb.org/viewtopic.php?p=352820#p352820
Additionally:
Some minor improvements.
---
=> Draft: Improve alignToFace in WorkingPlane.py

src/App/Range.cpp, src/App/Range.h, src/Mod/Spreadsheet/App/PropertySheet.cpp
(cherry picked from commit 0a8b875751c9469a52548730539dfd4b4fc51acc)
replaces #6916
=> Spreadsheet: Fix column number calc

src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py, src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py, src/Mod/Fem/femtest/app/test_common.py, src/Mod/Fem/femtest/app/test_open.py, src/Mod/Fem/femtest/app/test_solver_elmer.py, src/Mod/Fem/femtest/app/test_solver_z88.py, src/Mod/Fem/femtest/gui/test_open.py, src/Mod/Fem/femtools/femutils.py, src/Mod/Material/MaterialEditor.py
should be straight forward I think
=> [FEM] remove checks for Python 2

src/Mod/Part/App/BSplineSurfacePyImp.cpp
Currently, UKnotSequence and VKnotSequence fail on periodic BSpline surfaces.
Example code :
```
to = Part.Toroid()
bs = to.toBSpline()
bs.setUPeriodic()
bs.setVPeriodic()
bs.UKnotSequence
bs.VKnotSequence
```
This fix is a simple copy of the BSplineCurve method.
**Note**: If you don't have wiki access, then please mention your contribution …
=> [Part] BSplineSurface: fix KnotSequence for periodic BSpline surfaces

src/Mod/Part/App/BSplineSurfacePy.xml, src/Mod/Part/App/BSplineSurfacePyImp.cpp, src/Mod/Part/App/Geometry.cpp, src/Mod/Part/App/Geometry.h
This method allows to set the UV bounds of a BSpline Surface.
It can be used to normalize the parametric space of the surface, or to match another surface bounds.
The surface shape is unchanged. …
=> [Part] BSplineSurface: add setBounds method

src/App/ApplicationPy.cpp, src/Mod/Image/InitGui.py, src/Mod/Spreadsheet/InitGui.py
=> Remove 2 deprecated PyCFunction

src/App/Application.cpp, src/Base/Console.cpp, src/Base/Console.h
The macro `FC_PYCONSOLE_MSG` is defined to avoid code duplication.
In the function `SetStatus` now a boolean is required for the third parameter.
The function `GetObervers` is added to get the names of the current `Base::ILogger` attached to the console instance.
**Note**: If you don't have wiki access, then please mention your contribution …
=> Base: Clean up code and improve docstrings in Python Console module

src/Mod/TechDraw/App/DrawPage.cpp, src/Mod/TechDraw/App/DrawViewSymbol.cpp, src/Mod/TechDraw/App/DrawViewSymbol.h, src/Mod/TechDraw/Gui/ViewProviderSymbol.cpp, src/Mod/TechDraw/Gui/ViewProviderSymbol.h
Fix for problems reported here: https://www.forum.freecadweb.org/viewtopic.php?f=35&t=70560
---
=> [TD]Fix symbol recompute and scale

src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp, src/Mod/TechDraw/App/DrawWeldSymbol.cpp
- [[TechDraw] Improve readability of DrawViewSection.cpp](https://github.com/FreeCAD/FreeCAD/commit/3e650514753660880cf6b57736d618150e21016e) 
- [[TechDraw] Improve readability of DrawViewSpreadsheet.cpp](https://github.com/FreeCAD/FreeCAD/commit/d93f5e33067311598a03425d7487d12bf58653fe)
- [[TechDraw] Improve readability of DrawWeldSymbol.cpp](https://github.com/FreeCAD/FreeCAD/commit/e47de75e7d6f36c960de77de3a02a171e0f9f7db)
- [[TechDraw] Improve readability of DrawViewSymbol.cpp](https://github.com/FreeCAD/FreeCAD/commit/15a891b339a7a94d59ebf52880f3e77a98f5032a)
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with …
=> [TechDraw] Improve readability of App scripts, part 4

src/Mod/Draft/DraftGui.py, src/Mod/Draft/draftguitools/gui_dimensions.py, src/Mod/Draft/draftmake/make_bezcurve.py, src/Mod/Draft/draftmake/make_bspline.py, src/Mod/Draft/draftmake/make_circle.py, src/Mod/Draft/draftmake/make_ellipse.py, src/Mod/Draft/draftmake/make_polygon.py, src/Mod/Draft/draftmake/make_rectangle.py, src/Mod/Draft/draftmake/make_wire.py, src/Mod/Draft/importSVG.py
Substitute `is not None` for `!= None`
=> Draft: Fix 'testing inequality to None' syntax 

src/Mod/Arch/ArchGrid.py, src/Mod/Arch/ArchRebar.py, src/Mod/Arch/ArchSchedule.py, src/Mod/Arch/ArchVRM.py, src/Mod/Arch/OfflineRenderingUtils.py, src/Mod/Arch/importDAE.py, src/Mod/Arch/importIFClegacy.py, src/Mod/Arch/importOBJ.py
Substitute `is not None` for `!= None`
=> Arch: Fix 'testing inequality to None' syntax 

src/Gui/DlgSettingsNavigation.cpp, src/Gui/DlgSettingsNavigation.ui, src/Gui/PreferencePackTemplates/View.cfg, src/Gui/View3DInventor.cpp, src/Gui/View3DInventor.h
- at the moment some NaviCube parameters are in the general View group, some in the dedicated NaviCube group
=> [Gui] move a NaviCube parameter to the NaviCube parameter group

src/Mod/PartDesign/FeatureHole/FeatureHole.py, src/Mod/PartDesign/FeatureHole/TaskHole.py, src/Mod/PartDesign/FeatureHole/ViewProviderHole.py, src/Mod/PartDesign/TestPartDesignGui.py, src/Mod/PartDesign/WizardShaft/WizardShaft.py
Substitute `is not None` for `!= None`
=> PD: Fix 'testing inequality to None' syntax

src/Mod/PartDesign/FeatureHole/FeatureHole.py
Discovered through github action check.  
[skip ci]
=> PD: Remove unnecessary semicolons in FeatureHole.py

src/Gui/ViewProviderLink.cpp, src/Gui/ViewProviderLink.h
Fixes FreeCAD/FreeCAD#7113
Forum post https://forum.freecadweb.org/viewtopic.php?f=3&t=69860
=> Gui: fix ViewProviderLink transform with scale

src/Mod/TemplatePyMod/Commands.py, src/Mod/Test/Document.py, src/Mod/Test/TestGui.py, src/Tools/MakeMacBundleRelocatable.py, src/Tools/MemoryLeaks.py, src/Tools/SubWCRev.py, src/Tools/generateTemplates/templateClassPyExport.py
Substitute `is not None` for `!= None`
=> Fix various 'testing inequality to None' syntax issues

src/Base/ConsoleObserver.h, src/Base/GeometryPyCXX.cpp, src/Base/Interpreter.h, src/Base/Parameter.cpp, src/Base/RotationPyImp.cpp, src/Base/Tools2D.h, src/Base/TypePyImp.cpp
=> Base remove redundant void

src/Mod/Fem/Init.py, src/Mod/Fem/InitGui.py, src/Mod/Fem/femguiutils/selection_widgets.py, src/Mod/Fem/femmesh/gmshtools.py, src/Mod/Fem/femtaskpanels/task_material_common.py, src/Mod/Fem/femtaskpanels/task_material_reinforced.py, src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py, src/Mod/Fem/femtools/ccxtools.py, src/Mod/Material/Material.py, src/Mod/Material/MaterialEditor.py, src/Mod/Material/materialtools/cardutils.py
since we only support Python >=3, these checks can go
=> [FEM] remove unneeded checks for Python 3

src/App/Document.cpp
=> App: Use https

src/Mod/Draft/draftguitools/gui_edit_draft_objects.py
ref. https://forum.freecadweb.org/viewtopic.php?p=613622#p613622
Fix Bug when adding point to a BSpline.
=> [Draft] Fix Draft Edit AddPoint with BSpline

src/Mod/TechDraw/App/Cosmetic.h, src/Mod/TechDraw/App/CosmeticExtension.cpp, src/Mod/TechDraw/App/CosmeticExtension.h, src/Mod/TechDraw/App/DrawViewPartPy.xml, src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
=> [TechDraw] Remove deprecated functions

src/Mod/TechDraw/App/Cosmetic.cpp, src/Mod/TechDraw/App/DrawUtil.cpp, src/Mod/TechDraw/App/LineGroup.cpp, src/Mod/TechDraw/Gui/TaskCenterLine.cpp, src/Mod/TechDraw/Gui/TaskLeaderLine.cpp, src/Mod/TechDraw/Gui/TaskRichAnno.cpp, src/Mod/TechDraw/Gui/ViewProviderBalloon.cpp, src/Mod/TechDraw/Gui/ViewProviderDimension.cpp, src/Mod/TechDraw/Gui/ViewProviderGeomHatch.cpp, src/Mod/TechDraw/Gui/ViewProviderLeader.cpp, src/Mod/TechDraw/Gui/ViewProviderRichAnno.cpp, src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
=> [TechDraw] Simplify code getting default line weights

src/Mod/AddonManager/package_details.py
=> AddonManager: Fix source comment typos

src/Mod/OpenSCAD/importCSG.py
Get rid of SCAD-Import error in importCSG.py:
`<class 'KeyError'>: 'center'`
This Error will be raised when using newer versions of OpenSCAD,
that don't store the default (false) value for 'center'
Signed-off-by: Günter Neiß <gneiss@web.de> …
=> OpenSCAD: Get rid of SCAD-Import error in importCSG.py

src/Mod/Arch/ArchBuildingPart.py, src/Mod/Arch/ArchCommands.py, src/Mod/Arch/ArchComponent.py, src/Mod/Arch/ArchReference.py, src/Mod/Arch/ArchSchedule.py, src/Mod/Arch/ArchSpace.py, src/Mod/Arch/Dice3DS/dom3ds.py, src/Mod/Arch/Dice3DS/util.py, src/Mod/Arch/OfflineRenderingUtils.py, src/Mod/Arch/importOBJ.py
since we only support Python >=3, these checks can go
=> [Arch] remove unneeded checks for Python 3

src/Mod/Arch/Dice3DS/dom3ds.py, src/Mod/Arch/Dice3DS/util.py
as proposed: https://github.com/FreeCAD/FreeCAD/pull/7287#discussion_r937151184
and discussed: https://github.com/FreeCAD/FreeCAD/pull/7287#discussion_r937249434
=> [Arch] further code cleanup after Py2 check removal

src/App/Application.cpp, src/App/ColorModel.cpp, src/App/Document.cpp, src/App/DocumentObjectPyImp.cpp, src/App/Expression.cpp, src/App/Link.cpp, src/App/PropertyExpressionEngine.cpp, src/App/PropertyLinks.cpp
=> App: use emplace_back

src/Gui/Application.cpp, src/Gui/CommandPyImp.cpp, src/Gui/DlgPreferencesImp.cpp, src/Gui/MainWindow.cpp, src/Gui/NaviCube.cpp, src/Gui/PythonWorkbenchPyImp.cpp, src/Gui/Selection.cpp, src/Gui/SelectionObject.cpp, src/Gui/Tree.cpp, src/Gui/ViewProviderAnnotation.cpp, src/Gui/ViewProviderDocumentObject.cpp, src/Gui/ViewProviderExtern.cpp, src/Gui/ViewProviderGeoFeatureGroupExtension.cpp, src/Gui/ViewProviderInventorObject.cpp, src/Gui/ViewProviderLink.cpp, src/Gui/ViewProviderMeasureDistance.cpp, src/Gui/ViewProviderOriginFeature.cpp, src/Gui/ViewProviderPlacement.cpp, src/Gui/ViewProviderVRMLObject.cpp
=> Gui: use emplace_back

src/App/Application.cpp, src/App/ColorModel.cpp, src/App/Document.cpp, src/App/DocumentObject.cpp, src/App/DocumentObserver.cpp, src/App/Expression.cpp, src/App/FeaturePython.h, src/App/GeoFeature.cpp, src/App/Link.cpp, src/App/Link.h, src/App/ObjectIdentifier.cpp, src/App/Property.cpp, src/App/PropertyExpressionEngine.cpp, src/App/PropertyLinks.cpp, src/App/PropertyStandard.cpp, src/App/Transactions.cpp
=> App: use empty

cMake/FreeCAD_Helpers/SetupShibokenAndPyside.cmake
---
Make the success message simple, i.e. without the highlighting of a failure message
=> give success message normal prominence

src/Mod/Fem/Gui/CMakeLists.txt, src/Mod/Fem/Gui/ViewProviderFemPostPipeline.cpp, src/Mod/Fem/Gui/ViewProviderFemPostPipelinePy.xml, src/Mod/Fem/Gui/ViewProviderFemPostPipelinePyImp.cpp, src/Mod/Fem/femsolver/elmer/tasks.py
- it seems that we will need to scale result values (probably for the Elmer Eigen solver)
This PR adds the framework to do this. It is meant for Elmer but designed versatile.
=> [FEM] add framework to scale result mesh values

src/Mod/Sketcher/Gui/CommandConstraints.cpp
=> Sketcher: Fix sWhatsThis for Sketcher_CompConstrainRadDia

src/App/ApplicationPy.cpp, src/App/DocumentObject.h, src/App/Expression.cpp, src/App/Link.cpp, src/App/Link.h
=> App_redundent_void_2

src/App/DocumentObject.cpp
=> App: Redundant string initialization

src/Gui/CommandPyImp.cpp, src/Gui/Workbench.cpp
=> Gui: Redundant string initialization

src/Mod/Fem/App/FemMesh.cpp, src/Mod/Part/App/TopoShape.cpp, src/Mod/PartDesign/App/ShapeBinder.cpp, src/Mod/PartDesign/Gui/ViewProvider.cpp, src/Mod/Sketcher/App/Constraint.cpp, src/Mod/TechDraw/App/AppTechDrawPy.cpp, src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp, src/Mod/TechDraw/Gui/TaskSectionView.cpp, src/Mod/TechDraw/Gui/ViewProviderPage.cpp
=> Mod: Redundant string initialization

src/Mod/Path/PathScripts/PathOp.py, src/Mod/Path/PathScripts/PathSelection.py, src/Mod/Path/PathScripts/PathThreadMilling.py, src/Mod/Path/PathScripts/PathThreadMillingGui.py, src/Mod/Path/PathTests/TestPathThreadMilling.py
Fixes the issues discussed here: 
https://forum.freecadweb.org/viewtopic.php?f=15&t=70852
Also takes care of two minor issues - they threw exceptions but didn't impact the actual functionality.
=> PATH: Bugfix/external thread issues

src/App/DocumentObject.h, src/App/ExpressionVisitors.h, src/App/Link.cpp, src/App/Link.h
=> App: Use override etc 2

src/Gui/Icons/edit-cut.svg, src/Mod/TechDraw/Gui/Resources/icons/MRTE/edit-cut.svg
Replace 2 instances of edit-cut.svg with the version from the tango icon
library to reslove license issue. Closes #7347.
Tango Icon Library used: http://tango.freedesktop.org/releases/tango-icon-theme-0.8.90.tar.gz
Location within the tarball:
./tango-icon-theme-0.8.90/scalable/actions/edit-cut.svg …
=> [GUI,MOD] Replace edit-cut.svg

src/Mod/TechDraw/Gui/TaskProjGroup.ui
=> [TechDraw] fix up button in TaskProjGroup

src/Mod/TechDraw/App/Cosmetic.h
=> [TD]fix LineFormat ctor line color

src/Mod/Fem/femsolver/calculix/write_constraint_temperature.py
Fixes #7360  
Forum thread: https://forum.freecadweb.org/viewtopic.php?p=617376#p617376
=> [FEM] Substitute underscore for whitespace in CalculiX solver output

src/Mod/TechDraw/App/Preferences.cpp
=> [TD]fix hatch file default handling

src/Mod/TechDraw/Gui/QGIFace.h, src/Mod/TechDraw/Gui/QGIPrimPath.h
=> [TD]include clean up continued

cMake/FreeCAD_Helpers/CompilerChecksAndSetups.cmake
change boost min version to 1.65
---
=> remove unused CXX standards.

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/Gui/CMakeLists.txt, src/Mod/Fem/Gui/Resources/Fem.qrc, src/Mod/Fem/Gui/Resources/icons/FEM_ConstraintInitialPressure.svg, src/Mod/Fem/Gui/Resources/ui/InitialPressure.ui, src/Mod/Fem/Gui/Workbench.cpp, src/Mod/Fem/ObjectsFem.py, src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femobjects/constraint_initialpressure.py, src/Mod/Fem/femsolver/elmer/writer.py, src/Mod/Fem/femtaskpanels/task_constraint_initialpressure.py, src/Mod/Fem/femtest/app/test_object.py, src/Mod/Fem/femviewprovider/view_constraint_initialpressure.py
=> [FEM] add initial pressure constraint

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/Gui/CMakeLists.txt, src/Mod/Fem/Gui/Resources/Fem.qrc, src/Mod/Fem/Gui/Resources/ui/BodyHeatSource.ui, src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femobjects/constraint_bodyheatsource.py, src/Mod/Fem/femsolver/elmer/writer.py, src/Mod/Fem/femtaskpanels/task_constraint_bodyheatsource.py, src/Mod/Fem/femviewprovider/view_constraint_bodyheatsource.py
- as the name implies, it must be possible to set the heat to different bodies
- for this a selection dialog is necessary
=> [FEM] fix body heat source constraint

src/Mod/TechDraw/App/DrawViewPart.cpp
=> [TD]fix typo in message

src/Mod/TechDraw/App/DrawGeomHatch.cpp, src/Mod/TechDraw/App/DrawProjGroup.cpp, src/Mod/TechDraw/App/DrawProjGroupItem.cpp, src/Mod/TechDraw/App/DrawRichAnno.cpp, src/Mod/TechDraw/App/DrawViewDetail.cpp, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/App/DrawViewSection.cpp, src/Mod/TechDraw/Gui/DrawGuiUtil.cpp, src/Mod/TechDraw/Gui/QGSPage.cpp, src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp, src/Mod/TechDraw/Gui/ViewProviderDrawingView.h, src/Mod/TechDraw/Gui/ViewProviderPage.cpp
=> [TD]Code review changes

src/Mod/TechDraw/App/DrawLeaderLine.h, src/Mod/TechDraw/App/DrawProjGroup.h, src/Mod/TechDraw/App/DrawProjGroupItem.h, src/Mod/TechDraw/App/DrawRichAnno.h, src/Mod/TechDraw/App/DrawView.cpp, src/Mod/TechDraw/App/DrawView.h, src/Mod/TechDraw/App/DrawViewAnnotation.h, src/Mod/TechDraw/App/DrawViewArch.h, src/Mod/TechDraw/App/DrawViewBalloon.h, src/Mod/TechDraw/App/DrawViewClip.h, src/Mod/TechDraw/App/DrawViewCollection.h, src/Mod/TechDraw/App/DrawViewDetail.cpp, src/Mod/TechDraw/App/DrawViewDetail.h, src/Mod/TechDraw/App/DrawViewDimExtent.h, src/Mod/TechDraw/App/DrawViewDimension.h, src/Mod/TechDraw/App/DrawViewDraft.h, src/Mod/TechDraw/App/DrawViewImage.h, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/App/DrawViewPart.h, src/Mod/TechDraw/App/DrawViewSection.cpp, src/Mod/TechDraw/App/DrawViewSection.h, src/Mod/TechDraw/App/DrawViewSpreadsheet.h, src/Mod/TechDraw/App/DrawViewSymbol.h, src/Mod/TechDraw/App/DrawWeldSymbol.h, src/Mod/TechDraw/App/LandmarkDimension.h
=> [TD]use new style QObject::connect

src/Tools/fcinfo
Since Python 2 support has been dropped with #6143, let's have Python 3
as default interpreter on the platforms caring for it.
--- 
---
=> Use Python 3 as interpreter for fcinfo

src/Mod/Surface/App/AppSurface.cpp, src/Mod/Surface/App/Blending/BlendCurve.cpp, src/Mod/Surface/App/Blending/BlendCurve.h, src/Mod/Surface/App/Blending/BlendCurvePy.xml, src/Mod/Surface/App/Blending/BlendCurvePyImp.cpp, src/Mod/Surface/App/Blending/BlendPoint.cpp, src/Mod/Surface/App/Blending/BlendPoint.h, src/Mod/Surface/App/Blending/BlendPointPy.xml, src/Mod/Surface/App/Blending/BlendPointPyImp.cpp, src/Mod/Surface/App/Blending/FeatureBlendCurve.cpp, src/Mod/Surface/App/Blending/FeatureBlendCurve.h, src/Mod/Surface/App/CMakeLists.txt, src/Mod/Surface/Gui/AppSurfaceGui.cpp, src/Mod/Surface/Gui/Blending/ViewProviderBlendCurve.cpp, src/Mod/Surface/Gui/Blending/ViewProviderBlendCurve.h, src/Mod/Surface/Gui/CMakeLists.txt, src/Mod/Surface/Gui/Command.cpp, src/Mod/Surface/Gui/Resources/Surface.qrc, src/Mod/Surface/Gui/Resources/icons/BlendCurve.svg, src/Mod/Surface/Gui/Resources/icons/BlendSurface.svg, src/Mod/Surface/Gui/Workbench.cpp
Related forum thread :
https://forum.freecadweb.org/viewtopic.php?f=10&t=70187
this pr implements the blendpoint and blendcurve c++ classes and the blendcurve and python binding.
Reviews and comments are welcome as we are c++ beginners.
Thanks.
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 …
=> [Surface]: BlendCurve Feature

src/Mod/Import/stepZ.py
Leftover from 97ec620ff  
[skip ci]
=> stepZ.py: remove remaining mention of gzip_utf8

src/Mod/AddonManager/addonmanager_workers.py
https://forum.freecadweb.org/viewtopic.php?p=617191#p617191
---
=> [0.20] [AddonManager] Minor Bugfix with Mod folder

src/App/DocumentObserver.h
---
Turns out this one didn't cause a build fail after all
=> App: Use explicit

src/Gui/DlgSettingsUnitsImp.cpp
Fix issue https://github.com/FreeCAD/FreeCAD-translations/issues/190
=> Fix translation issue #190

src/Mod/TechDraw/Gui/QGVPage.cpp
https://www.forum.freecadweb.org/viewtopic.php?f=35&t=71430
- QGVPage was not detaching the parameter observer when
deleted, leaving a stale pointer in the list of observers. …
=> [TD]fix crash in Preferences

src/Base/Builder3D.cpp
=> Base: Fix warning -Wrange-loop-construct

src/Mod/TechDraw/App/Cosmetic.cpp, src/Mod/TechDraw/Gui/QGIViewPart.cpp
https://www.forum.freecadweb.org/viewtopic.php?f=35&t=71450
---
=> [TD]cosmetic vertex size consistency

src/Mod/TechDraw/App/DrawViewDetail.cpp, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/App/DrawViewPart.h, src/Mod/TechDraw/App/DrawViewSection.cpp
=> [TD]Prevent GO sync issue

src/Mod/TechDraw/Gui/MDIViewPage.cpp
https://www.forum.freecadweb.org/viewtopic.php?f=35&t=71499
---
=> [TD]fix too large page on print

.github/PULL_REQUEST_TEMPLATE.md
Substitute the v0.20 changelog thread for the v1.0 thread. Ref: https://forum.freecad.org/viewtopic.php?p=621016#p621016
=> github: Update PULL_REQUEST_TEMPLATE.md to v1.0 thread

src/Base/UnitsApi.cpp, src/Base/UnitsApi.h, src/Base/UnitsSchema.h, src/Base/UnitsSchemaImperial1.h, src/Mod/Sketcher/Gui/CommandSketcherTools.cpp, src/Mod/Sketcher/Gui/DrawSketchHandler.cpp, src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfHyperbola.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfParabola.h, src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h, src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h, src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h, src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h, src/Mod/Sketcher/Gui/DrawSketchHandlerLineSet.h, src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h, src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h, src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h, src/Mod/Sketcher/Gui/EditModeCoinManager.cpp, src/Mod/Sketcher/Gui/SketcherSettings.cpp, src/Mod/Sketcher/Gui/SketcherSettingsDisplay.ui, src/Mod/Sketcher/Gui/Utils.cpp, src/Mod/Sketcher/Gui/Utils.h
https://www.forum.freecadweb.org/viewtopic.php?f=3&t=71354
---
=> [Sketcher] cursor display unit awareness

src/Mod/TechDraw/App/DrawViewPart.cpp
- centerlines were being added to geometry in postHlrTasks,
but some CL depend on faces and so we move to
onFacesFinished.
---
=> [TD]fix face centerline

src/Mod/Draft/WorkingPlane.py
The `upvec` determined from the camera orientation is not very accurate. It can have an angle with the `vdir` that is not exactly 90 degrees. To work around this `self.v` is calculated from `self.axis` and `self.u`.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?p=619691#p619691
---
=> Draft: Fix workingplane auto alignment to Front view

src/Mod/Path/PathScripts/PathPost.py
Use the fullPath name when opening Output File dialog, handle cancel cleanly.
These changes fix output file file naming issues. Without them, the file dialog
shows the unprocessed substitution strings in the current working directory,
and generates errors in report view on Cancel.
Fixes #7410 
**Note**: If you don't have wiki access, then …
=> Path: Fix for gcode output file naming issues.

src/Mod/Path/PathScripts/PathDrilling.py
See discussion https://forum.freecadweb.org/viewtopic.php?f=15&p=622670#p622670
---
=> [Path] Change Default Drilling Retraction from G99 to G98

src/Gui/DlgMacroExecuteImp.cpp, src/Mod/Sketcher/Gui/EditDatumDialog.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=71556
=> [Bugfix]Gui: ensure message boxes appear and stay on top of main window

src/Mod/TechDraw/App/Geometry.cpp
=> [TechDraw] Improve readability of Geometry.cpp

src/Mod/Path/PathScripts/PostUtilsArguments.py, src/Mod/Path/PathScripts/PostUtilsParse.py, src/Mod/Path/PathScripts/post/refactored_centroid_post.py, src/Mod/Path/PathScripts/post/refactored_grbl_post.py, src/Mod/Path/PathScripts/post/refactored_linuxcnc_post.py, src/Mod/Path/PathScripts/post/refactored_mach3_mach4_post.py, src/Mod/Path/PathScripts/post/refactored_test_post.py, src/Mod/Path/PathTests/TestRefactoredTestPost.py
=> Path:  Added G73 decomposition and more refactored tests

src/Mod/Path/PathFeedRate.py
=> Fix bug when testing verticallity during PathFeedRate generation

src/Mod/TechDraw/App/DrawViewPart.cpp
> It is, in fact, somewhat slower than the current algo.
Micro improvements
---
=> [TechDraw] Microimprove new Face Finder Algorithm

src/Mod/Path/PathScripts/PathSetupSheetOpPrototype.py, src/Mod/Path/PathTests/TestPathSetupSheet.py
https://forum.freecadweb.org/viewtopic.php?f=15&t=71599
=> [PATH]: bugfix/setup-sheet-stepover

src/Mod/Draft/draftviewproviders/view_dimension.py
When calculating the alignment of the arrows the length of the arrows, in mm, was subtracted or added to a parameter in radians.
Additionally:
* When updating the `ArrowSize` or `ArrowType` the `updateData()` function is now called. Without this the dimension would need to be recomputed to see the results.
* Changed `self.updateData(obj, "Start")` to `self.updateData(obj, None)` since the function ignores the `prop` argument.
---
=> Draft: Fix alignment of angular dimension arrows

.clang-tidy
---
There doesn't seem to be any desire to enforce this option so perhaps its best to disable it for now so it stops being annoying.
=> clang-tidy disable nodiscard

src/Base/InputSource.cpp, src/Base/InputSource.h, src/Base/Parameter.cpp, src/Base/PreCompiled.h, src/Base/Reader.cpp, src/Base/Reader.h, src/Base/XMLTools.cpp
---
xerces v2 is very old and long unsupported and stated by xerces that it should not be used.
=> Remove conditionals for xerces v2

src/Mod/Show/mTempoVis.py, src/Mod/Sketcher/Gui/Command.cpp, src/Mod/Sketcher/Gui/EditModeCoinManager.cpp, src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp, src/Mod/Sketcher/Gui/EditModeGeometryCoinConverter.cpp, src/Mod/Sketcher/Gui/EditModeGeometryCoinConverter.h, src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp, src/Mod/Sketcher/Gui/EditModeInformationOverlayCoinConverter.cpp, src/Mod/Sketcher/Gui/EditModeInformationOverlayCoinConverter.h, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.h, src/Mod/Sketcher/Gui/ViewProviderSketchCoinAttorney.h
https://forum.freecadweb.org/viewtopic.php?f=3&t=71482
This achieved by a camera sensor at viewprovider level that detects side change, inverse all Z layer values used for rendering and redraws.
=> Sketcher : allow to select points & other elements from the backside view

src/Mod/TechDraw/App/DrawDimHelper.cpp, src/Mod/TechDraw/App/DrawDimHelper.h, src/Mod/TechDraw/App/DrawLeaderLine.cpp, src/Mod/TechDraw/App/DrawViewDimExtent.cpp, src/Mod/TechDraw/App/DrawViewDimExtent.h, src/Mod/TechDraw/App/DrawViewDimension.cpp, src/Mod/TechDraw/App/DrawViewDimension.h, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/Gui/CommandCreateDims.cpp, src/Mod/TechDraw/Gui/MDIViewPage.cpp, src/Mod/TechDraw/Gui/MDIViewPage.h
https://www.forum.freecadweb.org/viewtopic.php?f=35&t=71730
---
=> [TD]fix extent dimension

src/Mod/TechDraw/App/DrawViewImage.cpp, src/Mod/TechDraw/Gui/AppTechDrawGuiPy.cpp, src/Mod/TechDraw/Gui/Grabber3d.cpp, src/Mod/TechDraw/Gui/Grabber3d.h, src/Mod/TechDraw/Gui/TaskActiveView.cpp, src/Mod/TechDraw/Gui/TaskActiveView.h, src/Mod/TechDraw/Gui/TaskActiveView.ui
Previously ActiveView attempted to make a scaled Svg image of the active 3d window, but this did not produce a usable result. This version simply grabs the 3d window as a bitmap and loads it into a DrawViewImage.
- remove copyActiveViewToSvgFile
- use bitmap image instead of Svg
- upgrade Task with crop options …
=> [TD]simplify ActiveView

src/Mod/TechDraw/App/DrawProjGroup.cpp, src/Mod/TechDraw/App/DrawProjGroup.h, src/Mod/TechDraw/Gui/MDIViewPage.cpp
=> [TD]Fix printAll context menu and secondary view spacing

src/Mod/Path/PathTests/TestRefactoredTestPost.py
=> Path:  Fixed test00010 sensitivity to terminal column count.

cMake/FindSMESH.cmake, cMake/FreeCAD_Helpers/SetupSalomeSMESH.cmake
continued from https://github.com/FreeCAD/FreeCAD/pull/7299
---
=> cmake: find smesh (continued from #7299)

src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.cpp, src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h, src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=53617
=> [Bugfix]Sketcher: some user colors aren't taken into account

src/Mod/TechDraw/App/GeometryObject.cpp
=> [TD]restore missing isoparameter option

src/Mod/TechDraw/App/DrawPage.cpp, src/Mod/TechDraw/App/DrawPage.h, src/Mod/TechDraw/App/DrawProjectSplit.cpp, src/Mod/TechDraw/Gui/MDIViewPage.cpp
=> [TD]Fix scrub edges and printall

src/Mod/TechDraw/Gui/Grabber3d.cpp, src/Mod/TechDraw/Gui/Grabber3d.h, src/Mod/TechDraw/Gui/TaskActiveView.cpp
=> [TD]fix active view on windows

.clang-format
---
Currently:
auto something{somevalue}
Proposal:
auto something {somevalue}
IMHO the proposal has less cognitive overhead.
Impact on existing code will be almost nil.
=> clang-format add space before uniform initializer

src/Mod/Sketcher/App/SketchObject.cpp
=> [Sketcher] Fix Typo in comment

.clang-format
---
Current column limit = 0 (no limit).
Proposal: 80 characters (industry standard). Affects wrapping.
=> clang-format set column limit

src/Mod/TechDraw/Gui/MDIViewPage.cpp, src/Mod/TechDraw/Gui/MDIViewPage.h
=> [TD]fix printall banner page and pdf

src/Mod/TechDraw/Gui/QGVNavStyle.cpp, src/Mod/TechDraw/Gui/QGVNavStyle.h, src/Mod/TechDraw/Gui/QGVNavStyleTouchpad.cpp
=> [TD]handle high precision mice/touchpads

src/Mod/Fem/femresult/resulttools.py
Migrate to pep8 compatible docstrings
=> [FEM] tweak function docstrings in `femresult/resulttools.py`

src/Mod/TechDraw/Gui/QGVNavStyle.cpp, src/Mod/TechDraw/Gui/QGVNavStyle.h
=> [TD]limit zoom out

src/Mod/TechDraw/App/DrawView.cpp, src/Mod/TechDraw/App/DrawView.h, src/Mod/TechDraw/App/DrawViewClip.cpp
=> [TD]position view within clip group

src/Mod/Draft/draftobjects/patharray.py
This PR fixes several issues:
* The hiding/unhiding of properties was not always correct.
* "Align Mode" Frenet did not ignore "Force Vertical" and "Vertical Vector".
* A binormal vector would be calculated from two vectors that were effectively parallel.
* The "Extra Translation" property, which should be applied to each element in the array, was applied to the array as a whole.
Remarks:
* The `placements_on_path` functions calculates all placements in a single loop. This ensues that the elements in the array are created in a logical order. This is important as a link array can be expanded. The element at the end of an open path would be the 2nd element in the old code.
* The `calculate_placement` function was changed to make better use of `App.Rotation()`. There is no need to calculate …
=> Draft: Fix several path array issues

src/Gui/ViewProviderPy.xml, src/Gui/ViewProviderPyImp.cpp, src/Mod/Part/TestPartGui.py
@donovaly separate pull request acording to https://forum.freecad.org/viewtopic.php?p=625495&sid=fbd133d17eb6673b7df62527a4054cfb#p625495
Pull request related: https://github.com/FreeCAD/FreeCAD/pull/7236 …
=> Gui: Allow None parameter again in drag and drop methods in Python ViewProviderPy class

src/Mod/TechDraw/Gui/ViewProviderBalloon.cpp, src/Mod/TechDraw/Gui/ViewProviderDimension.cpp, src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp, src/Mod/TechDraw/Gui/ViewProviderLeader.cpp, src/Mod/TechDraw/Gui/ViewProviderRichAnno.cpp
=> [TD]fix StackTop and StackBottom

src/Base/Console.cpp, src/Base/Console.h
=> Base: Remove unused method

src/App/Application.cpp
=> App: Remove redundant code

cMake/FreeCAD_Helpers/ConfigureCMakeVariables.cmake
I found this necessary to build FC with C++20.
If nothing else, maybe useful later?
=> Fix for boost with C++20

src/App/ComplexGeoData.cpp, src/App/PropertyLinks.cpp, src/Base/ConsoleObserver.cpp, src/Gui/Application.cpp, src/Gui/DlgSettingsDocument.ui, src/Gui/DlgSettingsDocumentImp.cpp, src/Mod/Part/App/ExtrusionHelper.cpp, src/Mod/Part/App/FeatureExtrusion.cpp, src/Mod/Part/App/FeatureExtrusion.h, src/Mod/Sketcher/App/SketchObject.cpp
Forum thread https://forum.freecadweb.org/viewtopic.php?f=44&t=71687&sid=c92e0d2bbd2d0fadc0b6bb42a7128889&start=10#p626675
=> Topo Naming Accumulated Fix

src/Mod/Arch/importOBJ.py
Now export and import shows correct transparency
=> Issue #7510 - rectified transparency in importOBJ.py

src/Gui/Thumbnail.cpp
=> Better Thumbnail quality by oversampling hires screenshot

src/Mod/Fem/femcommands/manager.py
Bug explanation:
https://forum.freecadweb.org/viewtopic.php?f=18&t=71936&p=629585#p629585
(I commited to my master by mistake, but I guess it will not be an issue in this case)
---
=> FEM:fix remaining result object in memory in femmesh2mesh

src/App/StringHasher.cpp, src/App/StringHasher.h, src/Base/Bitmask.h
According to suggestion of @chennes
=> Topo Naming: Improve coding quality

cMake/FreeCAD_Helpers/SetupSalomeSMESH.cmake
continued from here:
https://github.com/FreeCAD/FreeCAD/pull/7475
`add_definitions(-DSALOME_USE_64BIT_IDS)` if smesh is found via `find_package(SMESH, CONFIG)`
---
=> cmake: add_definitions(-DSALOME_USE_64BIT_IDS) for smesh via config

src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
Was introduced by 634e47f31, new code only supported by Qt5
=> Sketcher : optimize code that was present for Qt4 compatibility

src/Mod/Test/Metadata.py, src/Mod/Test/TestData/basic_metadata.xml, src/Mod/Test/TestData/content_items.xml
=> Test: Add more content tag testing to Metadata tests

src/Mod/TechDraw/App/DrawUtil.cpp, src/Mod/TechDraw/App/DrawUtil.h, src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp
https://www.forum.freecadweb.org/viewtopic.php?f=35&t=72231
---
=> [TD]encode Xml characters in spreadsheet

src/Mod/AddonManager/addonmanager_workers_installation.py, src/Mod/AddonManager/addonmanager_workers_startup.py
=> Addon Manager: Make sure metadata gets parsed when downloaded

src/Mod/Sketcher/Gui/Workbench.cpp
See poll: https://forum.freecadweb.org/viewtopic.php?f=8&t=71922
---
=> SKETCHER: Remove StopOperation from toolbar. 

src/Gui/Workbench.cpp
Vote by poll: https://forum.freecadweb.org/viewtopic.php?f=8&t=71925
---
=> Remove Edit Mod from File toolbar. 

src/Gui/Workbench.cpp
Vote by poll : https://forum.freecadweb.org/viewtopic.php?f=8&t=71924
---
=> Remove copy cut print paste from File toolbar.

src/Mod/Sketcher/Gui/SketcherSettings.cpp, src/Mod/Sketcher/Gui/SketcherSettings.ui, src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp
As discussed in this topic: https://forum.freecadweb.org/viewtopic.php?f=8&t=72262
This is the step '4' of changes offered there.
This only makes the 'Edit control' widget optional, with a preference setting to enable/disable it. By default it is ENABLED, such that it doesn't change anything by default. …
=> Sketcher: Make 'Edit control' widget optional. ENABLED by default.

src/Base/VectorPy.xml
https://forum.freecadweb.org/viewtopic.php?t=72287
=> [Bugfix]Base: Python method 'isEqual' of Vector shall be Const

src/MacAppBundle/CMakeLists.txt
---
this PR should fix the issue i just opened ie. #7550
=> macos fix for #7550

src/Base/StackWalker.cpp, src/Mod/Sketcher/Gui/Utils.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
As the title says.
If someone could re-check, this would be nice.
=> [Base, Sketcher] remove redundant boolean checks

src/Mod/Sketcher/Gui/TaskSketcherGeneral.cpp, src/Mod/Sketcher/Gui/TaskSketcherGeneral.ui
https://forum.freecadweb.org/viewtopic.php?f=8&t=72426
---
=> Sketcher: In 'Edit controls' widget remove 'Grid Size' LABEL.

src/Mod/Arch/ArchBuildingPart.py, src/Mod/Arch/ArchSectionPlane.py, src/Mod/Draft/draftviewproviders/view_dimension.py, src/Mod/Draft/draftviewproviders/view_label.py, src/Mod/Draft/draftviewproviders/view_wpproxy.py
=> Draft+Arch: Fix crash related to SoBrepEdgeSet

src/Mod/Start/StartPage/LoadNew.py
Fix [FreeCAD-translations/issues/198](https://github.com/FreeCAD/FreeCAD-translations/issues/198)
---
=> [Start] Fix New document name translation

src/Mod/Part/App/GeometryDefaultExtension.cpp
- see the discussion in https://github.com/FreeCAD/FreeCAD/pull/7241
=> [Part] remove now obsolete code for Visual Studio compiler

src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ExportPageDXF.svg, src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ExportPageSVG.svg
=> [TD]update export icons

src/Mod/Path/Path/Base/Gui/GetPoint.py, src/Mod/Path/Path/Base/Gui/PropertyBag.py, src/Mod/Path/Path/Op/Profile.py, src/Mod/Path/PathTests/TestPathAdaptive.py, src/Mod/Path/PathTests/TestPathDressupDogbone.py
=> fix codespell warnings

src/Mod/Path/Path/Tool/Controller.py, src/Mod/Path/PathTests/TestPathAdaptive.py
Not sure how we got away with this for so long but since the refactor it causes problems on some platforms.
=> [PATH]: bugfix/loading-path-wb-error

src/Mod/TechDraw/Gui/Command.cpp, src/Mod/TechDraw/Gui/DrawGuiUtil.cpp, src/Mod/TechDraw/Gui/DrawGuiUtil.h, src/Mod/TechDraw/Gui/Grabber3d.cpp, src/Mod/TechDraw/Gui/Grabber3d.h, src/Mod/TechDraw/Gui/TaskActiveView.cpp
https://forum.freecadweb.org/viewtopic.php?f=35&t=72639
---
=> [TD]Allow ActiveView from different document

src/Mod/Part/App/AppPartPy.cpp, src/Mod/Sketcher/Gui/SketcherSettingsDisplay.ui, src/Mod/Sketcher/Gui/Utils.h
Fixed typos. Will need a new translation push because it fixes string that gets translated.
=> [Sketcher] [Part] Fix typos and whitespace

src/Mod/TechDraw/App/DrawViewPartPy.xml, src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
=> [TD]expose DVP projectPoint to Python

src/Mod/Spreadsheet/Gui/Workbench.cpp, src/Mod/Spreadsheet/Gui/qtcolorpicker.cpp
+ set parent when instantiating
https://forum.freecadweb.org/viewtopic.php?f=3&t=72547
=> [Bugfix]Spreadsheet: fix multi-screen management of QtColorPicker

src/App/Application.cpp, src/App/Resources/translations/App.ts, src/Gui/CommandDoc.cpp, src/Mod/Fem/App/AppFemPy.cpp, src/Mod/Import/App/AppImportPy.cpp, src/Mod/Import/Gui/AppImportGuiPy.cpp, src/Mod/Mesh/App/AppMeshPy.cpp, src/Mod/Part/App/AppPartPy.cpp, src/Mod/Path/Gui/AppPathGuiPy.cpp, src/Mod/Points/App/AppPointsPy.cpp, src/Tools/updatets.py
=> Fix of untranslated first document's name

src/Mod/Sketcher/Gui/Workbench.cpp
Removes the Select DOF tool from the toolbar. It's the same as Sketcher_SelectRedundantConstraints & Sketcher_SelectConflictingConstraints that have been removed and should have been removed at the same time.
See: https://forum.freecadweb.org/viewtopic.php?f=8&t=72495 …
=> Sketcher: remove 'select DOF' from toolbar.

src/Mod/PartDesign/App/FeatureHole.cpp
Extracted from https://github.com/FreeCAD/FreeCAD/pull/7562
---
=> PartDesign: Remove duplicate comment

src/Mod/AddonManager/addonmanager_workers_installation.py
When searching for python and pip, ensure that there is a timeout on the subprocess call. Also tweaks the exception handling. This is work towards addressing https://github.com/FreeCAD/FreeCAD-addons/issues/240
=> Addon Manager: Clean up tests for pip

src/Mod/PartDesign/App/FeatureHole.cpp
Refactoring part of https://github.com/FreeCAD/FreeCAD/pull/7562
The counterbore is basically a special case of the countersink with a countersink angle of 180 degrees and applied depth. Handling it that way elimintaes some duplicate code and adds the ability to combine countersinks and counterbore to form a counterdrill.
The sanity check on countersinkAngle can be safely dropped as it is ensured by a constraint on the property itself.
=> PartDesign: Refactor geometry creation of counersink/counterbore

src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=10&t=72825
---
=> Sketcher: Correct icon for Sketcher_CreatePointFillet in menu

src/Mod/PartDesign/App/FeatureHole.cpp
- will be necessary to push deprecated entries to the end of the combobox in the dialog (in a coming PR)
- also fix too long code line
=> [PD] FeatureHole.cpp: sort counterdrill

src/Mod/Draft/draftobjects/array.py
Setting the NumberPolar parameter to 1 in a Polar Array resulted in a ZeroDivisionError. With this PR it will be accepted and one item will be placed at start position
=> Draft: Accept 1 in NumberPolar parameter

src/Mod/Path/Gui/Resources/panels/PointEdit.ui
=> Fixes #7652  Tag creation bug

src/Mod/TechDraw/Gui/Widgets/CompassDialWidget.cpp
Fix TechDraw compilation with MSVC.
=> TechDraw: Windows compilation fix

src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
* Check Python args using `PyArg_ParseTuple`.
* Use Python Errors to rise exceptions.
* Use `Py_Return` to correct reference count of `Py_None`.
* If `PyArg_ParseTuple` return `false`, it sets a PyError. In order for the function `removeCosmeticVertex` to continue executing code, that error must be cleaned with `PyErr_Clean`, otherwise an undefined behavior is generated.
And please remember to update the Wiki with the features added or …
=> TechDraw: Improve code in Python DrawViewPartPy class

src/Mod/Sketcher/App/GeometryFacade.cpp, src/Mod/Sketcher/App/GeometryFacade.h, src/Mod/Sketcher/Gui/Resources/icons/elements/Sketcher_Element_Point_StartingPoint.svg, src/Mod/Sketcher/Gui/Resources/icons/elements/Sketcher_Element_SelectionTypeInvalid.svg, src/Mod/Sketcher/Gui/TaskSketcherElements.cpp, src/Mod/Sketcher/Gui/TaskSketcherElements.h, src/Mod/Sketcher/Gui/TaskSketcherElements.ui
See discuss here : https://forum.freecadweb.org/viewtopic.php?f=8&t=72239
---
=> Sketcher: Element widget rework.

src/Mod/TechDraw/App/PreCompiled.h, src/Mod/TechDraw/Gui/PreCompiled.h, src/Mod/TechDraw/Gui/Widgets/CompassDialWidget.cpp, src/Mod/TechDraw/Gui/Widgets/CompassWidget.cpp
Fixes a compile on windows issue reported here: https://www.forum.freecadweb.org/viewtopic.php?f=10&t=72992
---
=> [TD]Fix windows include order

src/XDGData/org.freecadweb.FreeCAD.desktop
=> Update org.freecadweb.FreeCAD.desktop with Korean localisation

src/XDGData/org.freecadweb.FreeCAD.desktop
A comment line in Polish was added.
---
=> comment in polish

src/Gui/PythonConsole.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=72321
=> Gui: remove forcefully jumping to Python Console bottom line on single LMB click

src/Mod/TechDraw/App/CenterLinePy.xml, src/Mod/TechDraw/App/CenterLinePyImp.cpp
* Format attribute now get/set from `{'style':int, 'weight':float, 'color':tuple, 'visible':bool}` `dict`.
* Type check is removed in setter functions as PyCXX already does it on `Py::Object` creation. (except in `setFlip` since `Py::Boolean` can be created from any object).
* The `get/setGeom` function is implemented to reduce code duplication in `get/setEdges`, `get/setFaces`, `get/setPoints`. Currently this function returns an incorrect list as it is initialized with the size of the vector of geometries and then the strings of the geometries names are appended, so the result is of the form [None, None, ..., " Face1", "Face2"... ]. This behavior is corrected with this commit.
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to …
=> TechDraw: Improve code in Python CenterLinePy class

src/Gui/DlgSettingsViewColor.ui, src/Gui/PreferencePacks/FreeCAD Classic Colors/FreeCAD Classic Colors.cfg, src/Gui/SplitView3DInventor.cpp, src/Gui/View3DInventor.cpp
This reverts commit 1efb0503d24350f85abbb76478dcddc6639856b7.
This brings the background color back to the one we have in FC 0.20.x
=> Revert "[Gui] background default colors"

src/Mod/PartDesign/App/FeatureHelix.cpp
In straight case the auxiliary path is not needed. Using Frenet mode is faster.
@Syres916 Ping !
=> [PartDesign] Improve Helix calculation for straight shape

CONTRIBUTING.md, CONTRIBUTING.txt
=> Policy for FreeCAD Contribution Process (FCP)

src/Mod/TechDraw/Gui/ViewProviderPage.cpp, src/Mod/TechDraw/Gui/ViewProviderPage.h
=> [TD]fix view drag and drop to page - fixes 7691

src/Mod/TechDraw/Gui/TaskDimension.ui
=> [TD]fix tooltip for Equal Tolerance - fixes 7690

src/Mod/Path/Gui/Resources/preferences/PathJob.ui, src/Mod/Path/Path/Op/Area.py, src/Mod/Path/Path/Op/Profile.py
=> Small fixes including preferences dialog 

src/Mod/Measure/App/Measurement.cpp, src/Mod/Measure/App/Measurement.h
=> [Measurement]support for 3 point angle - fixes 7689

src/Base/GeometryPyCXX.h
If a sequence of length less than 3 is passed, a Python error is set when trying to get three items, so the function should not continue normally.
An overloaded operator for `Base::Vector3d` is also added to `Py::Vector` …
=> Base: Check sequence size in getVectorFromTuple function

src/Gui/DlgGeneral.ui
=> [Typo]Gui: fix file indentation + improve tootip

src/Gui/NavigationStyle.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
This is solving the deselection problem for sketcher and for general 3D view.
https://github.com/FreeCAD/FreeCAD/issues/7673
https://forum.freecadweb.org/viewtopic.php?f=8&t=73056
https://forum.freecadweb.org/viewtopic.php?f=8&t=72435 …
=> Base: + Sketcher: disable geometry deselection when user holds Ctrl.

src/Gui/DlgGeneral.ui
- add newlines to very long tooltip
=> [Gui] DlgGeneral.ui

src/Mod/Fem/femmesh/femmesh2mesh.py
Adds the scale factor of the deformed shape to the function femmesh2mesh, as discussed:
https://forum.freecadweb.org/viewtopic.php?p=638649#p638649
=> FEM: femmesh2mesh add disp scale factor

src/Mod/AddonManager/addonmanager_workers_installation.py
When processing downloaded text-based metadata files, catch any decode exceptions that get thrown and translate them into a useful error message for developers.
=> Addon Manager: Handle UTF-8 decode failures

src/Mod/Fem/Gui/DlgSettingsFemElmerImp.cpp
- handle the case of mangles user.fcg file
=> [FEM] more safe Elmer executable path handling

src/Mod/Part/Gui/SectionCutting.cpp
- following our latest Clang coding style
=> [Part] SectionCutting: cut long lines

src/Mod/Fem/Gui/DlgSettingsFemElmerImp.cpp
- simplify and correct non-Windows case
=> [FEM] better safe Elmer executable path handling

src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreatePolyline.svg, src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreatePolyline_Constr.svg
- the same intention as https://github.com/FreeCAD/FreeCAD/pull/7588 but proposal with less strokes
=> [Sketch] change polyline icon

src/Mod/Part/parttests/regression_tests.py
=> Part: Fix typo in regression_tests.py

src/Mod/Part/TestPartApp.py
As discussed:
https://forum.freecadweb.org/viewtopic.php?f=10&t=73107
- []  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
---
=> Part: TestPartApp.py add tolerance to PartTestShapeRotate

src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
- same as https://github.com/FreeCAD/FreeCAD/commit/18781bcf6 but for Helices (fixes #7629 also for helices)
- also modernize Qt connection
=> [PD] Helix: assure source Sketch is visible when in selection mode

src/Gui/Splashscreen.cpp
- was reported as warning by our CI
=> [Gui] SplashScreen: modernize Qt connection

src/Mod/TechDraw/App/DrawPagePy.xml, src/Mod/TechDraw/App/DrawPagePyImp.cpp
* implement `PageWidth`, `PageHeight` and `PageOrientation` as read-only attributes.
* In `addView` and `removeView` methods, check for `DrawViewPy` type. (cast from `App:::DocumentObjectPy` is not safe).
* Use `PyArg_ParseTuple` to check arguments.
*  Add author and licence info. …
=> TechDraw: Improve code in Python DrawPagePy class

src/Mod/Draft/draftobjects/patharray.py
=> Draft: Make tangent vector affect ExtraTranslation

src/Mod/TechDraw/TDTest/DrawHatchTest.py
- test was erroneously adding hatch to page. Hatches only belong to DrawViewPart.
---
=> [TD]fix hatch test script

src/Mod/TechDraw/App/DrawComplexSection.cpp, src/Mod/TechDraw/App/DrawComplexSection.h, src/Mod/TechDraw/App/DrawUtil.h, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/App/DrawViewPart.h, src/Mod/TechDraw/App/DrawViewSection.cpp, src/Mod/TechDraw/Gui/TaskComplexSection.cpp, src/Mod/TechDraw/Gui/TaskComplexSection.h
The PR is the result of a report here: https://www.forum.freecadweb.org/viewtopic.php?p=638425#p638425
Two issues are addressed.  The first is to prevent the attempt to create a Complex Section with no direction set.  The second is to handle an empty compound which is not considered a null shape by OCC. …
=> [TD]fix exception on no direction set

src/Mod/TechDraw/App/CosmeticEdgePy.xml, src/Mod/TechDraw/App/CosmeticEdgePyImp.cpp
* Use Py::Vector class in `Start`, `End` and `Center` attributes.
* Format attribute now get/set from `{'style':int, 'weight':float, 'color':tuple, 'visible':bool}` dict.
* Fix some error messages. …
=> TechDraw: Improve code in Python CosmeticEdgePy class

src/Mod/Fem/femtools/femutils.py, src/Mod/Fem/femtools/membertools.py, src/Mod/TechDraw/App/DrawComplexSection.cpp, src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/Gui/QGIViewPart.cpp, src/Mod/TechDraw/Gui/TaskComplexSection.cpp
=> Fix typos in TD and FEM source comments/documentation [skip ci]

src/Mod/TechDraw/App/DrawViewSymbol.cpp
- also affects DrawViewSymbol and derivatives
---
=> [TD]fix read only scale property in DraftView

src/App/FreeCADInit.py, src/Base/GeometryPyCXX.cpp, src/Mod/Arch/ArchAxis.py, src/Mod/Arch/ArchCommands.py, src/Mod/Arch/exportIFC.py, src/Mod/Arch/importIFC.py, src/Mod/Arch/importIFCHelper.py, src/Mod/Arch/importJSON.py, src/Mod/Arch/importSHP.py, src/Mod/Arch/importWebGL.py, src/Mod/Draft/draftfunctions/svgtext.py, src/Mod/Draft/draftutils/todo.py, src/Mod/Draft/importDXF.py, src/Mod/OpenSCAD/OpenSCADUtils.py, src/Mod/Start/StartPage/StartPage.py
Clean up most remaining Python 2 compatibility code. Closes #6413.
=> Remaining py2 removal

src/Mod/Arch/importWebGL.py
Should be rebased and merged after #7740 is merged
=> Arch: remove trailing whitespace in importWebGL.py

src/Mod/PartDesign/Gui/TaskRevolutionParameters.cpp, src/Mod/PartDesign/Gui/TaskRevolutionParameters.h
- reported here: https://github.com/FreeCAD/FreeCAD/pull/7667/commits/f0a0e563
@wwmayer , I don't know what to do with the first 2 warnings there. Can you please have a look?
=> [PD] TaskDlgRevolutionParameters: fix some CI warnings

src/Mod/Mesh/App/AppMesh.cpp, src/Mod/Mesh/App/AppMeshPy.cpp, src/Mod/Mesh/App/Edge.cpp, src/Mod/Mesh/App/Edge.h, src/Mod/Mesh/App/EdgePyImp.cpp, src/Mod/Mesh/App/Exporter.cpp, src/Mod/Mesh/App/Exporter.h, src/Mod/Mesh/App/Facet.cpp, src/Mod/Mesh/App/Facet.h, src/Mod/Mesh/App/FacetPyImp.cpp
=> [Mesh] App-Facet: remove unused includes

src/Mod/Path/Path/Post/Command.py
Fixed merge issue
Fixes https://github.com/FreeCAD/FreeCAD/issues/7762
=> [PATH] bugfix/fix-merge-issue-by-mangling-pr-7428

src/Base/ConsoleObserver.cpp, src/Gui/Action.cpp, src/Gui/Action.h, src/Gui/CMakeLists.txt, src/Gui/Command.cpp, src/Gui/Command.h, src/Gui/CommandCompleter.cpp, src/Gui/CommandCompleter.h, src/Gui/CommandPyImp.cpp, src/Gui/CommandView.cpp, src/Gui/DlgActionsImp.cpp, src/Gui/DlgActionsImp.h, src/Gui/DlgKeyboard.ui, src/Gui/DlgKeyboardImp.cpp, src/Gui/DlgKeyboardImp.h, src/Gui/DlgToolbars.ui, src/Gui/DlgToolbarsImp.cpp, src/Gui/DlgToolbarsImp.h, src/Gui/MenuManager.cpp, src/Gui/ShortcutManager.cpp, src/Gui/ShortcutManager.h, src/Gui/ToolBarManager.cpp, src/Gui/ToolBarManager.h, src/Gui/Widgets.cpp, src/Gui/Workbench.cpp
=> Gui: introduce ShortcutManager for shortcut management and conflict resolving

src/Mod/TechDraw/App/DrawViewPart.cpp, src/Mod/TechDraw/App/DrawViewSection.cpp, src/Mod/TechDraw/Gui/QGIViewPart.cpp, src/Mod/TechDraw/Gui/TaskComplexSection.cpp, src/Mod/TechDraw/Gui/TaskSectionView.cpp, src/Mod/TechDraw/Gui/TaskSectionView.h, src/Mod/TechDraw/Gui/TaskSectionView.ui
Fixes a fail in DrawViewPart::getSizeAlongVector for certain section line directions.  Also includes fixes for other problems discovered during fix development.
---
=> [TD]Fix fail in section line creation

src/Mod/Mesh/App/Importer.cpp, src/Mod/Mesh/App/Mesh.cpp, src/Mod/Mesh/App/Mesh.h, src/Mod/Mesh/App/MeshFeature.cpp, src/Mod/Mesh/App/MeshFeature.h, src/Mod/Mesh/App/MeshFeaturePyImp.cpp, src/Mod/Mesh/App/MeshPoint.h, src/Mod/Mesh/App/MeshPointPyImp.cpp, src/Mod/Mesh/App/MeshProperties.cpp, src/Mod/Mesh/App/MeshProperties.h, src/Mod/Mesh/App/MeshPyImp.cpp, src/Mod/Mesh/App/MeshTexture.cpp, src/Mod/Mesh/App/MeshTexture.h, src/Mod/Mesh/App/Segment.cpp, src/Mod/Mesh/App/Segment.h, src/Mod/Mesh/App/Types.h
=> [Mesh] Imp* - end: remove unused includes

src/Mod/AddonManager/AddonManager.py, src/Mod/AddonManager/CMakeLists.txt, src/Mod/AddonManager/addonmanager_connection_checker.py
Extracts the connection checking GUI code into its own class. Addresses, but does not close, #7747.
=> Addon Manager: Refactor to extract connection check GUI

src/Mod/Mesh/App/Core/Grid.h, src/Mod/Mesh/App/FeatureMeshCurvature.cpp, src/Mod/Mesh/App/FeatureMeshCurvature.h, src/Mod/Mesh/App/FeatureMeshDefects.cpp, src/Mod/Mesh/App/FeatureMeshDefects.h, src/Mod/Mesh/App/FeatureMeshExport.cpp, src/Mod/Mesh/App/FeatureMeshExport.h, src/Mod/Mesh/App/FeatureMeshImport.cpp, src/Mod/Mesh/App/FeatureMeshImport.h, src/Mod/Mesh/App/FeatureMeshSegmentByMesh.cpp, src/Mod/Mesh/App/FeatureMeshSegmentByMesh.h, src/Mod/Mesh/App/FeatureMeshSetOperations.cpp, src/Mod/Mesh/App/FeatureMeshSetOperations.h, src/Mod/Mesh/App/FeatureMeshSolid.cpp, src/Mod/Mesh/App/FeatureMeshSolid.h, src/Mod/Mesh/App/FeatureMeshTransform.cpp, src/Mod/Mesh/App/FeatureMeshTransform.h, src/Mod/Mesh/App/FeatureMeshTransformDemolding.cpp, src/Mod/Mesh/App/FeatureMeshTransformDemolding.h
=> [Mesh] Feature*: remove unused includes

src/Mod/TechDraw/Gui/TaskComplexSection.ui, src/Mod/TechDraw/Gui/TaskSectionView.ui, src/Mod/TechDraw/Gui/Widgets/CompassDialWidget.cpp
https://www.forum.freecadweb.org/viewtopic.php?f=35&t=73327&sid=96ce3b318d08e1a9c4396ca18e109081
---
=> [TD]Section dialog gui tweaks

src/Gui/Action.cpp, src/Gui/Action.h, src/Gui/CMakeLists.txt, src/Gui/DlgGeneralImp.cpp, src/Gui/DlgGeneralImp.h, src/Gui/MenuManager.cpp, src/Gui/MenuManager.h, src/Gui/UserSettings.cpp, src/Gui/UserSettings.h, src/Gui/Workbench.cpp
=> Fixes a couple of problems of [PR #7679]

src/Mod/TechDraw/App/DrawComplexSection.cpp, src/Mod/TechDraw/App/DrawViewPart.cpp
=> [TD]fix vertical alignment of section pieces

src/Mod/AddonManager/AddonManager.py, src/Mod/AddonManager/CMakeLists.txt, src/Mod/AddonManager/addonmanager_devmode_metadata_checker.py
---
Extract the metadata checking code from the main class. Addresses, but does not close, #7747.
=> Addon Manager: Refactor to extract metadata checker

src/Mod/TechDraw/App/DrawGeomHatch.cpp, src/Mod/TechDraw/App/DrawGeomHatch.h, src/Mod/TechDraw/App/DrawHatch.cpp, src/Mod/TechDraw/App/DrawHatch.h, src/Mod/TechDraw/App/DrawSVGTemplate.cpp, src/Mod/TechDraw/App/DrawSVGTemplate.h, src/Mod/TechDraw/App/DrawTemplate.cpp, src/Mod/TechDraw/App/DrawTemplate.h, src/Mod/TechDraw/App/DrawTileWeld.cpp, src/Mod/TechDraw/App/DrawTileWeld.h, src/Mod/TechDraw/App/DrawViewImage.cpp, src/Mod/TechDraw/App/DrawViewImage.h, src/Mod/TechDraw/App/DrawViewSection.cpp, src/Mod/TechDraw/App/DrawViewSection.h, src/Mod/TechDraw/Gui/QGISVGTemplate.cpp, src/Mod/TechDraw/Gui/QGISVGTemplate.h, src/Mod/TechDraw/Gui/TaskHatch.cpp, src/Mod/TechDraw/Gui/ViewProviderGeomHatch.cpp, src/Mod/TechDraw/Gui/ViewProviderGeomHatch.h, src/Mod/TechDraw/Gui/ViewProviderHatch.cpp, src/Mod/TechDraw/Gui/ViewProviderHatch.h, src/Mod/TechDraw/Gui/ViewProviderTemplate.cpp
Fixes https://github.com/FreeCAD/FreeCAD/issues/7714.  Also fixes similar behaviour in other uses of PropertyFileIncluded.
---
=> [TD]Fix Embedded Template File #7714

src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
As discussed with Abdullah. 
See https://github.com/FreeCAD/FreeCAD/pull/7567#issuecomment-1304724547
---
=> Sketcher: Fix element widget repaint delay bug.

src/Mod/TechDraw/App/DrawComplexSection.cpp, src/Mod/TechDraw/App/DrawComplexSection.h, src/Mod/TechDraw/App/DrawUtil.h, src/Mod/TechDraw/App/DrawViewSection.cpp, src/Mod/TechDraw/App/DrawViewSection.h, src/Mod/TechDraw/Gui/Command.cpp, src/Mod/TechDraw/Gui/QGIViewPart.cpp, src/Mod/TechDraw/Gui/TaskComplexSection.cpp
=> [TD]Prevent attempt to create complex section without base view

src/Mod/Arch/ArchSketchObject.py, src/Mod/Arch/ArchWall.py
=> [ArchWall]  Use and Create ArchSketch if add-on is present

src/Mod/TechDraw/Gui/QGISectionLine.cpp
https://www.forum.freecadweb.org/viewtopic.php?p=641069#p641069
---
=> [TD]fix alignment of section line marks on rotated base view

src/Mod/Arch/ArchIFCView.py, src/Mod/Arch/ArchSketchObject.py
Make uniforum all Arch headers
=> [Arch] fix header uniformity

LibraryVersions.h.cmake, src/App/Application.cpp, src/Gui/Splashscreen.cpp
- [ .]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
---
#7793
=> change ALL_UPPER_CASE constexpr definitions to camelCase

src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h, src/Mod/Sketcher/Gui/EditDatumDialog.cpp, src/Mod/Sketcher/Gui/EditDatumDialog.h, src/Mod/Sketcher/Gui/PropertyConstraintListItem.h, src/Mod/Sketcher/Gui/SoZoomTranslation.h, src/Mod/Sketcher/Init.py, src/Mod/Sketcher/InitGui.py, src/Mod/Sketcher/SketcherTests/TestSketchFillet.py, src/Mod/Sketcher/TestSketcherApp.py, src/Mod/Sketcher/TestSketcherGui.py
Make uniform all Sketcher headers.
=> [Sketcher] fix header uniformity

cMake/FindPySide2Tools.cmake, cMake/FindPySide6Tools.cmake
---
I could find no reference anywahere to the propose to be deleted code
=> Remove unused code in find pyside

src/Mod/Mesh/App/Core/IO/Reader3MF.cpp, src/Mod/Mesh/App/Core/IO/ReaderOBJ.cpp, src/Mod/Mesh/App/Core/IO/Writer3MF.cpp, src/Mod/Mesh/App/Core/IO/WriterOBJ.cpp
=> [Mesh] Core/IO: remove unused includes

src/Mod/Mesh/App/Core/Algorithm.cpp, src/Mod/Mesh/App/Core/Algorithm.h, src/Mod/Mesh/App/Core/Approximation.cpp, src/Mod/Mesh/App/Core/Approximation.h, src/Mod/Mesh/App/Core/Builder.cpp, src/Mod/Mesh/App/Core/Builder.h, src/Mod/Mesh/App/Core/Curvature.cpp, src/Mod/Mesh/App/Core/CylinderFit.cpp, src/Mod/Mesh/App/Core/CylinderFit.h, src/Mod/Mesh/App/Core/Decimation.cpp, src/Mod/Mesh/App/Core/Definitions.cpp, src/Mod/Mesh/App/Core/Definitions.h, src/Mod/Mesh/App/Core/Degeneration.cpp, src/Mod/Mesh/App/Core/Degeneration.h
=> [Mesh] Core A-D: remove unused includes

src/Mod/Mesh/App/Core/Elements.cpp, src/Mod/Mesh/App/Core/Elements.h, src/Mod/Mesh/App/Core/Evaluation.cpp, src/Mod/Mesh/App/Core/Evaluation.h, src/Mod/Mesh/App/Core/Functional.h, src/Mod/Mesh/App/Core/Grid.cpp, src/Mod/Mesh/App/Core/Helpers.h, src/Mod/Mesh/App/Core/Info.cpp, src/Mod/Mesh/App/Core/Iterator.h, src/Mod/Mesh/App/Core/KDTree.cpp, src/Mod/Mesh/App/Core/MeshIO.cpp, src/Mod/Mesh/App/Core/MeshIO.h, src/Mod/Mesh/App/Core/MeshKernel.cpp, src/Mod/Mesh/App/Core/MeshKernel.h
=> [Mesh] Core E-M: remove unused includes

src/Mod/Draft/draftgeoutils/arcs.py
Fixes #7806.
See there for details.
---
=> Draft: fix arcFromSpline midpoint bug

src/Mod/TechDraw/CMakeLists.txt, src/Mod/TechDraw/InitGui.py, src/Mod/TechDraw/TDTest/DrawViewDetailTest.py, src/Mod/TechDraw/TDTest/DrawViewPartTest.py, src/Mod/TechDraw/TDTest/DrawViewSectionTest.py, src/Mod/TechDraw/TestTechDrawApp.py, src/Mod/TechDraw/TestTechDrawGui.py
- check that edge geometry count is correct
- handle delay waiting for threads to complete
- add test for DrawViewDetail
---
=> [TD]Add tests for geometry creation

src/Mod/Mesh/App/Core/Projection.cpp, src/Mod/Mesh/App/Core/Projection.h, src/Mod/Mesh/App/Core/Segmentation.h, src/Mod/Mesh/App/Core/SetOperations.cpp, src/Mod/Mesh/App/Core/SetOperations.h, src/Mod/Mesh/App/Core/Simplify.h, src/Mod/Mesh/App/Core/Smoothing.cpp, src/Mod/Mesh/App/Core/Smoothing.h, src/Mod/Mesh/App/Core/SphereFit.cpp, src/Mod/Mesh/App/Core/SphereFit.h, src/Mod/Mesh/App/Core/Tools.cpp, src/Mod/Mesh/App/Core/Tools.h, src/Mod/Mesh/App/Core/TopoAlgorithm.cpp, src/Mod/Mesh/App/Core/TopoAlgorithm.h, src/Mod/Mesh/App/Core/Triangulation.cpp, src/Mod/Mesh/App/Core/Triangulation.h, src/Mod/Mesh/App/Core/Trim.cpp, src/Mod/Mesh/App/Core/Trim.h, src/Mod/Mesh/App/Core/TrimByPlane.cpp, src/Mod/Mesh/App/Core/TrimByPlane.h, src/Mod/Mesh/App/Core/Utilities.h, src/Mod/Mesh/App/Core/Visitor.cpp, src/Mod/Mesh/App/Core/Visitor.h, src/Mod/Mesh/App/PreCompiled.h
=> [Mesh] Core P-end: remove unused includes

src/Mod/TechDraw/App/DrawProjGroup.cpp, src/Mod/TechDraw/App/DrawProjGroup.h, src/Mod/TechDraw/Gui/TaskProjGroup.cpp, src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
=> [TD]prevent fail on missing base view (#7856)

src/Mod/Measure/App/Measurement.cpp
=> [Measure] remove unused includes

src/Mod/Sketcher/Gui/TaskSketcherElements.cpp, src/Mod/Sketcher/Gui/TaskSketcherElements.ui
They are saved as preference to be cross-session.
---
=> Sketcher: Element widget: - FilterBox and filter state improvement

src/Mod/MeshPart/Gui/AppMeshPartGui.cpp, src/Mod/MeshPart/Gui/Command.cpp, src/Mod/MeshPart/Gui/CrossSections.cpp, src/Mod/MeshPart/Gui/CrossSections.h, src/Mod/MeshPart/Gui/CurveOnMesh.cpp, src/Mod/MeshPart/Gui/CurveOnMesh.h, src/Mod/MeshPart/Gui/TaskCurveOnMesh.cpp, src/Mod/MeshPart/Gui/TaskCurveOnMesh.h, src/Mod/MeshPart/Gui/Tessellation.cpp, src/Mod/MeshPart/Gui/Tessellation.h, src/Mod/MeshPart/Gui/Workbench.cpp
=> [MeshPart] Gui: remove unused includes

src/Mod/Sketcher/Gui/TaskSketcherElements.ui
=> Sketcher: Element widget - fix toolbuttons height

src/Mod/Import/App/AppImport.cpp, src/Mod/Import/App/AppImportPy.cpp, src/Mod/Import/App/ExportOCAF.cpp, src/Mod/Import/App/ExportOCAF.h, src/Mod/Import/App/FeatureImportIges.cpp, src/Mod/Import/App/FeatureImportIges.h, src/Mod/Import/App/FeatureImportStep.cpp, src/Mod/Import/App/FeatureImportStep.h, src/Mod/Import/App/ImportOCAF.cpp, src/Mod/Import/App/ImportOCAF.h, src/Mod/Import/App/ImportOCAF2.cpp, src/Mod/Import/App/ImportOCAF2.h, src/Mod/Import/App/ImportOCAFAssembly.cpp, src/Mod/Import/App/ImportOCAFAssembly.h, src/Mod/Import/App/PreCompiled.h, src/Mod/Import/App/StepShape.cpp, src/Mod/Import/App/StepShapePyImp.cpp, src/Mod/Import/App/dxf/ImpExpDxf.cpp, src/Mod/Import/App/dxf/ImpExpDxf.h, src/Mod/Import/App/dxf/dxf.cpp, src/Mod/Import/App/dxf/dxf.h
=> [Import] remove unused includes

src/Mod/TechDraw/App/DrawComplexSection.cpp, src/Mod/TechDraw/App/DrawComplexSection.h
https://www.forum.freecadweb.org/viewtopic.php?p=643538#p643538
---
=> [TD]fix ComplexSection null cut shape

src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp, src/Mod/Spreadsheet/TestSpreadsheet.py
=> [Spreadsheet] Fix alias setting for empty cells

src/Mod/Import/Gui/AppImportGuiPy.cpp, src/Mod/Import/Gui/PreCompiled.h
- also some sorting
- also put some includes to precompiled headers
=> [Import] Gui: remove unused includes

src/Mod/Image/Gui/AppImageGui.cpp, src/Mod/Image/Gui/AppImageGuiPy.cpp, src/Mod/Image/Gui/ViewProviderImagePlane.cpp, src/Mod/Image/Gui/Workbench.cpp
=> [Image] Gui: remove unused includes

src/Mod/Draft/draftmake/make_clone.py, src/Mod/Draft/draftviewproviders/view_clone.py
Fixes https://github.com/FreeCAD/FreeCAD/issues/5765.
---
=> Draft: fix clone DiffuseColor

src/Mod/Image/App/PreCompiled.cpp, src/Mod/Image/App/PreCompiled.h, src/Mod/Image/Gui/PreCompiled.cpp, src/Mod/Image/Gui/PreCompiled.h, src/Mod/Image/ImageTools/_CommandImageScaling.py, src/Mod/Image/ImageTools/__init__.py, src/Mod/Image/Init.py, src/Mod/Image/InitGui.py
Make uniform all Image workbench headers.
=> Image: fix header uniformity

src/Gui/NaviCube.cpp
makes the corners bigger and therefore easier to click
~I still can't figure out why a square is still drawn on each side face, would appreciate some help on this, @realthunder @donovaly @Jolbas I think you guys have some knowledge on the navicube.~ …
=> use hexagon shape for navicube corners [fixes #7875]

src/App/MappedElement.cpp, src/Mod/Part/App/TopoShapeEx.cpp
Fixed some problems that the user [reported](https://github.com/realthunder/fcad_pcb/issues/61) as well as I discovered during my own testing.
=> Topo Naming accumulated fixes

src/Mod/TechDraw/App/DrawProjGroup.cpp, src/Mod/TechDraw/App/DrawProjGroup.h, src/Mod/TechDraw/Gui/TaskProjGroup.cpp, src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
=> [TD]backport fix for no Detail without BaseView

src/Mod/Inspection/App/InspectionFeature.cpp, src/Mod/Inspection/Gui/Command.cpp, src/Mod/Inspection/Gui/ViewProviderInspection.cpp, src/Mod/Inspection/Gui/ViewProviderInspection.h, src/Mod/Inspection/Gui/VisualInspection.cpp
=> [Inspection] remove unused includes

src/Mod/Points/App/AppPointsPy.cpp, src/Mod/Points/App/Points.cpp, src/Mod/Points/App/Points.h, src/Mod/Points/App/PointsAlgos.cpp, src/Mod/Points/App/PointsAlgos.h, src/Mod/Points/App/PointsFeature.cpp, src/Mod/Points/App/PointsFeature.h, src/Mod/Points/App/PointsGrid.cpp, src/Mod/Points/App/PointsGrid.h, src/Mod/Points/App/PointsPyImp.cpp, src/Mod/Points/App/PreCompiled.h, src/Mod/Points/App/Properties.cpp, src/Mod/Points/App/Properties.h, src/Mod/Points/App/PropertyPointKernel.cpp, src/Mod/Points/App/Structured.cpp, src/Mod/Points/Gui/AppPointsGui.cpp, src/Mod/Points/Gui/Command.cpp, src/Mod/Points/Gui/DlgPointsReadImp.cpp, src/Mod/Points/Gui/PreCompiled.h, src/Mod/Points/Gui/ViewProvider.cpp, src/Mod/Points/Gui/ViewProvider.h, src/Mod/Points/Gui/Workbench.cpp
=> [Points] remove unused includes

src/Doc/mainpage.dox.in, src/Mod/Complete/Init.py, src/Mod/Complete/InitGui.py, src/Mod/Idf/Init.py, src/Mod/Import/App/StepShapePyImp.cpp, src/Mod/Inspection/Init.py, src/Mod/Inspection/InitGui.py, src/Mod/Material/Init.py, src/Mod/Material/InitGui.py, src/Mod/Material/Material.py, src/Mod/Material/importFCMat.py, src/Mod/Measure/App/AppMeasure.cpp, src/Mod/Measure/App/Measurement.cpp, src/Mod/Measure/App/Measurement.h, src/Mod/Measure/App/MeasurementPyImp.cpp, src/Mod/Measure/App/PreCompiled.cpp, src/Mod/Measure/App/PreCompiled.h, src/Mod/Measure/Init.py, src/Mod/OpenSCAD/Init.py, src/Mod/OpenSCAD/InitGui.py, src/Mod/Points/Init.py, src/Mod/Points/InitGui.py, src/Mod/Sandbox/Init.py, src/Mod/Sandbox/InitGui.py, src/Mod/Start/Init.py, src/Mod/Start/InitGui.py, src/Tools/MakeNewBuildNbr.py, src/Tools/fcbt/NextBuildNumber.py
Also includes some trailing whitespace fixes
=> Fix header uniformity for various workbenches/directories

src/Gui/DlgObjectSelection.cpp, src/Gui/DlgObjectSelection.h, src/Gui/DlgObjectSelection.ui
Forum thread https://forum.freecadweb.org/viewtopic.php?f=3&t=68023
=> Gui: hiding detail dependency information in DlgObjectSelection

src/Mod/Arch/ArchSpace.py
=> Arch: Fix Arch_Space text position

src/Gui/TreeItemMode.h
---
Triggered from build warning
=> GUI: fix invalid unicode

src/Gui/UserSettings.cpp
=> Gui: QListSpecialMethodsBase<T>::indexOf returns qsizetype

src/Mod/Arch/ArchBuildingPart.py
=> Arch: Fix missing Windows in Arch Reference of BuildingPart

src/Mod/Sketcher/App/SketchObject.cpp
The solution is working but I have doubts, I had to construct the expression in different ways for named an unnamed constraints, for some reason `spath.toString()` returns the path with a leading `.` for the named case and without the leading `.` for index based path, would appreciate some clarification as to why this happens and if I dealt with this correctly.
here a file to test the feature (just remove zip extension)
[carbonCopyTest.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/9925569/carbonCopyTest.FCStd.zip)
when you create a new sketch and make a carbon copy of this the constraint that has a valid name will be linked using the name in the expression, and those that have invalid names or no name will be linked using the index based expression.
=> [fixes #5965] CarbonCopy: if existing use constraint name in expressions

src/Mod/Measure/App/Measurement.cpp
Measurement was expecting reference subElement names in the form "Edge5" but they are arriving as "Body001.Feature002.Edge5".  See issue #7914.
---
=> [Meas]handle long subElement names in reference (fixes #7914)

src/Mod/TechDraw/Gui/QGIWeldSymbol.cpp, src/Mod/TechDraw/Gui/QGMText.cpp, src/Mod/TechDraw/Gui/QGMText.h, src/Mod/TechDraw/Gui/QGSPage.cpp, src/Mod/TechDraw/Gui/QGSPage.h, src/Mod/TechDraw/Gui/QGTracker.cpp
=> [TD] QGIW* - QGT:remove unused includes

src/Mod/TechDraw/Gui/QGCustomBorder.cpp, src/Mod/TechDraw/Gui/QGCustomClip.cpp, src/Mod/TechDraw/Gui/QGCustomImage.cpp, src/Mod/TechDraw/Gui/QGCustomImage.h, src/Mod/TechDraw/Gui/QGCustomLabel.cpp, src/Mod/TechDraw/Gui/QGCustomLabel.h, src/Mod/TechDraw/Gui/QGCustomRect.cpp, src/Mod/TechDraw/Gui/QGCustomSvg.cpp, src/Mod/TechDraw/Gui/QGCustomText.cpp, src/Mod/TechDraw/Gui/QGDisplayArea.cpp, src/Mod/TechDraw/Gui/QGEPath.cpp
=> [TD] QGC* - QGE:remove unused includes

src/Mod/TechDraw/Gui/QGVNavStyle.cpp, src/Mod/TechDraw/Gui/QGVNavStyleBlender.cpp, src/Mod/TechDraw/Gui/QGVNavStyleCAD.cpp, src/Mod/TechDraw/Gui/QGVNavStyleGesture.cpp, src/Mod/TechDraw/Gui/QGVNavStyleInventor.cpp, src/Mod/TechDraw/Gui/QGVNavStyleMaya.cpp, src/Mod/TechDraw/Gui/QGVNavStyleOCC.cpp, src/Mod/TechDraw/Gui/QGVNavStyleOpenSCAD.cpp, src/Mod/TechDraw/Gui/QGVNavStyleRevit.cpp, src/Mod/TechDraw/Gui/QGVNavStyleTinkerCAD.cpp, src/Mod/TechDraw/Gui/QGVNavStyleTouchpad.cpp, src/Mod/TechDraw/Gui/QGVPage.cpp
=> [TD] QGV*:remove unused includes

src/Mod/TechDraw/Gui/QGIArrow.cpp, src/Mod/TechDraw/Gui/QGICMark.cpp, src/Mod/TechDraw/Gui/QGICaption.cpp, src/Mod/TechDraw/Gui/QGICenterLine.cpp, src/Mod/TechDraw/Gui/QGIDecoration.cpp, src/Mod/TechDraw/Gui/QGIDimLines.cpp, src/Mod/TechDraw/Gui/QGIDrawingTemplate.cpp, src/Mod/TechDraw/Gui/QGIEdge.cpp, src/Mod/TechDraw/Gui/QGIFace.cpp, src/Mod/TechDraw/Gui/QGIFace.h, src/Mod/TechDraw/Gui/QGIGhostHighlight.cpp, src/Mod/TechDraw/Gui/QGIHighlight.cpp, src/Mod/TechDraw/Gui/QGIHighlight.h
=> [TD] QGIA - QGIH:remove unused includes

src/Mod/TechDraw/Gui/QGILeaderLine.cpp, src/Mod/TechDraw/Gui/QGILeaderLine.h, src/Mod/TechDraw/Gui/QGIMatting.cpp, src/Mod/TechDraw/Gui/QGIMatting.h, src/Mod/TechDraw/Gui/QGIPrimPath.cpp, src/Mod/TechDraw/Gui/QGIProjGroup.cpp, src/Mod/TechDraw/Gui/QGIProjGroup.h, src/Mod/TechDraw/Gui/QGIRichAnno.cpp, src/Mod/TechDraw/Gui/QGIRichAnno.h, src/Mod/TechDraw/Gui/QGISVGTemplate.cpp, src/Mod/TechDraw/Gui/QGISVGTemplate.h, src/Mod/TechDraw/Gui/QGISectionLine.cpp, src/Mod/TechDraw/Gui/QGISectionLine.h, src/Mod/TechDraw/Gui/QGITemplate.cpp, src/Mod/TechDraw/Gui/QGITile.cpp, src/Mod/TechDraw/Gui/QGIVertex.cpp
=> [TD] QGIL - QGIVE:remove unused includes

src/Mod/TechDraw/Gui/PreCompiled.h, src/Mod/TechDraw/Gui/QGIView.cpp, src/Mod/TechDraw/Gui/QGIViewAnnotation.cpp, src/Mod/TechDraw/Gui/QGIViewBalloon.cpp, src/Mod/TechDraw/Gui/QGIViewBalloon.h, src/Mod/TechDraw/Gui/QGIViewClip.cpp, src/Mod/TechDraw/Gui/QGIViewCollection.cpp, src/Mod/TechDraw/Gui/QGIViewDimension.cpp, src/Mod/TechDraw/Gui/QGIViewImage.cpp, src/Mod/TechDraw/Gui/QGIViewPart.cpp, src/Mod/TechDraw/Gui/QGIViewPart.h, src/Mod/TechDraw/Gui/QGIViewSection.cpp, src/Mod/TechDraw/Gui/QGIViewSpreadsheet.cpp, src/Mod/TechDraw/Gui/QGIViewSymbol.cpp
=> [TD] QGIView*: remove unused includes

src/Mod/Mesh/Gui/AppMeshGui.cpp, src/Mod/Mesh/Gui/Command.cpp, src/Mod/Mesh/Gui/DlgDecimating.cpp, src/Mod/Mesh/Gui/DlgEvaluateMeshImp.cpp, src/Mod/Mesh/Gui/DlgEvaluateMeshImp.h, src/Mod/Mesh/Gui/DlgEvaluateSettings.cpp, src/Mod/Mesh/Gui/DlgRegularSolidImp.cpp, src/Mod/Mesh/Gui/DlgSettingsImportExportImp.cpp, src/Mod/Mesh/Gui/DlgSettingsImportExportImp.h, src/Mod/Mesh/Gui/DlgSettingsMeshView.cpp, src/Mod/Mesh/Gui/DlgSettingsMeshView.h, src/Mod/Mesh/Gui/DlgSmoothing.cpp, src/Mod/Mesh/Gui/MeshEditor.cpp, src/Mod/Mesh/Gui/MeshEditor.h, src/Mod/Mesh/Gui/MeshSelection.cpp, src/Mod/Mesh/Gui/MeshSelection.h, src/Mod/Mesh/Gui/PropertyEditorMesh.cpp, src/Mod/Mesh/Gui/PropertyEditorMesh.h
=> [Mesh] Gui: A-P: remove unused includes

src/Mod/PartDesign/App/FeatureSketchBased.cpp
- same fix as #7879
- also fix wording on an error message and improve a variable name
=> [PD] FeatureSketchBased.cpp: fix orthogonal check

src/Mod/Part/App/Geometry.cpp, src/Mod/Part/App/Geometry.h, src/Mod/Sketcher/App/SketchObject.cpp, src/Mod/Sketcher/App/SketchObject.h, src/Mod/Sketcher/App/SketchObjectPy.xml, src/Mod/Sketcher/App/SketchObjectPyImp.cpp, src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp, src/Mod/Sketcher/Gui/Resources/Sketcher.qrc, src/Mod/Sketcher/Gui/Resources/icons/splines/Sketcher_JoinCurves.svg, src/Mod/Sketcher/Gui/Workbench.cpp
Rudimentary tool to join two b-splines into a single curve. Theoretically it is possible to join other curves as well after converting them to NURBS.
What is not complete:
* Thorough testing: I was trying to get this in time for the 0.20 feature freeze so this ended up being a last minute rush.
* ~No icons: I didn't design an icon for this tool. I made a temp with just a red "J" but I can't get it to appear on the toolbar. All that's visible is a placeholder.~ @bitacovir provided the icons and I figured out I was using the wrong name in command's pixmap field.
UI forum post: https://forum.freecadweb.org/viewtopic.php?f=34&t=66785
=> Sketcher: Join curves

src/Mod/Mesh/Gui/RemeshGmsh.cpp, src/Mod/Mesh/Gui/RemeshGmsh.h, src/Mod/Mesh/Gui/RemoveComponents.cpp, src/Mod/Mesh/Gui/Segmentation.cpp, src/Mod/Mesh/Gui/Segmentation.h, src/Mod/Mesh/Gui/SegmentationBestFit.cpp, src/Mod/Mesh/Gui/SegmentationBestFit.h, src/Mod/Mesh/Gui/Selection.cpp, src/Mod/Mesh/Gui/Selection.h, src/Mod/Mesh/Gui/ThumbnailExtension.cpp, src/Mod/Mesh/Gui/Workbench.cpp, src/Mod/Mesh/Gui/Workbench.h
=> [Mesh] Gui: R-Se: remove unused includes

src/Mod/Mesh/Gui/SoFCIndexedFaceSet.cpp, src/Mod/Mesh/Gui/SoFCIndexedFaceSet.h, src/Mod/Mesh/Gui/SoFCMeshFaceSet.cpp, src/Mod/Mesh/Gui/SoFCMeshFaceSet.h, src/Mod/Mesh/Gui/SoFCMeshNode.cpp, src/Mod/Mesh/Gui/SoFCMeshNode.h, src/Mod/Mesh/Gui/SoFCMeshObject.cpp, src/Mod/Mesh/Gui/SoFCMeshObject.h, src/Mod/Mesh/Gui/SoFCMeshVertex.cpp, src/Mod/Mesh/Gui/SoFCMeshVertex.h, src/Mod/Mesh/Gui/SoPolygon.cpp, src/Mod/Mesh/Gui/SoPolygon.h
=> [Mesh] Gui: So*: remove unused includes

src/Mod/Mesh/Gui/PreCompiled.h, src/Mod/Mesh/Gui/ViewProvider.cpp, src/Mod/Mesh/Gui/ViewProvider.h, src/Mod/Mesh/Gui/ViewProviderCurvature.cpp, src/Mod/Mesh/Gui/ViewProviderCurvature.h, src/Mod/Mesh/Gui/ViewProviderDefects.cpp, src/Mod/Mesh/Gui/ViewProviderMeshFaceSet.cpp, src/Mod/Mesh/Gui/ViewProviderMeshPyImp.cpp, src/Mod/Mesh/Gui/ViewProviderTransform.cpp, src/Mod/Mesh/Gui/ViewProviderTransform.h, src/Mod/Mesh/Gui/ViewProviderTransformDemolding.cpp, src/Mod/Mesh/Gui/ViewProviderTransformDemolding.h
=> [Mesh] Gui: ViewProvider*: remove unused includes

src/Mod/Path/App/Path.cpp, src/Mod/Path/App/Path.h, src/Mod/Path/App/PathPyImp.cpp, src/Mod/Path/App/PathSegmentWalker.cpp, src/Mod/Path/App/PathSegmentWalker.h, src/Mod/Path/App/PropertyPath.cpp, src/Mod/Path/App/PropertyPath.h, src/Mod/Path/App/Voronoi.cpp, src/Mod/Path/App/VoronoiCell.cpp, src/Mod/Path/App/VoronoiCellPyImp.cpp, src/Mod/Path/App/VoronoiEdge.cpp, src/Mod/Path/App/VoronoiEdgePyImp.cpp, src/Mod/Path/App/VoronoiPyImp.cpp, src/Mod/Path/App/VoronoiVertex.cpp, src/Mod/Path/App/VoronoiVertexPyImp.cpp
=> [Path] P-End: remove unused includes

src/Mod/Path/Gui/AppPathGui.cpp, src/Mod/Path/Gui/AppPathGuiPy.cpp, src/Mod/Path/Gui/Command.cpp, src/Mod/Path/Gui/DlgProcessorChooser.cpp, src/Mod/Path/Gui/DlgProcessorChooser.h, src/Mod/Path/Gui/DlgSettingsPathColor.cpp, src/Mod/Path/Gui/PreCompiled.h, src/Mod/Path/Gui/TaskDlgPathCompound.cpp, src/Mod/Path/Gui/TaskDlgPathCompound.h, src/Mod/Path/Gui/ViewProviderArea.cpp, src/Mod/Path/Gui/ViewProviderPath.cpp, src/Mod/Path/Gui/ViewProviderPath.h, src/Mod/Path/Gui/ViewProviderPathCompound.cpp, src/Mod/Path/Gui/ViewProviderPathShape.cpp
=> [Path] Gui: remove unused includes

src/Base/Parameter.cpp
---
Apologies, second attempt.
Refer #7902
=> Base: Simplify Repetitious Code (2)

src/Mod/Path/App/AppPath.cpp, src/Mod/Path/App/AppPathPy.cpp, src/Mod/Path/App/Area.cpp, src/Mod/Path/App/Area.h, src/Mod/Path/App/AreaPyImp.cpp, src/Mod/Path/App/Command.cpp, src/Mod/Path/App/CommandPyImp.cpp, src/Mod/Path/App/FeatureArea.cpp, src/Mod/Path/App/FeatureArea.h, src/Mod/Path/App/FeatureAreaPyImp.cpp, src/Mod/Path/App/FeaturePath.cpp, src/Mod/Path/App/FeaturePath.h, src/Mod/Path/App/FeaturePathCompound.cpp, src/Mod/Path/App/FeaturePathCompound.h, src/Mod/Path/App/FeaturePathCompoundPyImp.cpp, src/Mod/Path/App/FeaturePathShape.cpp, src/Mod/Path/App/FeaturePathShape.h, src/Mod/Path/App/PreCompiled.h
=> [Path] A-F: remove unused includes

src/Mod/Arch/TestArch.py
This PR adds a BuildingPart unit test (also a regression test for #6178).
Additionally:
The testWindow function was improved.
Some minor edits.
---
=> Arch: add BuildingPart unit test

src/Mod/Raytracing/App/AppRaytracing.cpp, src/Mod/Raytracing/App/AppRaytracingPy.cpp, src/Mod/Raytracing/App/LuxFeature.cpp, src/Mod/Raytracing/App/LuxFeature.h, src/Mod/Raytracing/App/LuxProject.cpp, src/Mod/Raytracing/App/LuxProject.h, src/Mod/Raytracing/App/LuxTools.cpp, src/Mod/Raytracing/App/LuxTools.h, src/Mod/Raytracing/App/PovTools.cpp, src/Mod/Raytracing/App/PovTools.h, src/Mod/Raytracing/App/PreCompiled.h, src/Mod/Raytracing/App/RayFeature.cpp, src/Mod/Raytracing/App/RayFeature.h, src/Mod/Raytracing/App/RayProject.cpp, src/Mod/Raytracing/App/RayProject.h, src/Mod/Raytracing/App/RaySegment.cpp, src/Mod/Raytracing/App/RaySegment.h
=> [Raytracing] App: remove unused includes

src/Mod/Start/App/AppStart.cpp, src/Mod/Start/Gui/DlgStartPreferencesImp.h, src/Mod/Start/Gui/PreCompiled.h, src/Mod/Start/Gui/Workbench.cpp
=> [Start] remove unused includes

src/Mod/Web/App/PreCompiled.h, src/Mod/Web/Gui/AppWebGui.cpp, src/Mod/Web/Gui/BrowserView.cpp, src/Mod/Web/Gui/BrowserView.h, src/Mod/Web/Gui/CookieJar.cpp, src/Mod/Web/Gui/PreCompiled.h, src/Mod/Web/Gui/Workbench.cpp
=> [Web] remove unused includes

src/Mod/TechDraw/App/PreCompiled.h, src/Mod/TechDraw/Gui/PreCompiled.h, src/Mod/TechDraw/Gui/TaskBalloon.cpp, src/Mod/TechDraw/Gui/TaskBalloon.h, src/Mod/TechDraw/Gui/TaskCenterLine.cpp, src/Mod/TechDraw/Gui/TaskCenterLine.h, src/Mod/TechDraw/Gui/TaskComplexSection.cpp, src/Mod/TechDraw/Gui/TaskComplexSection.h, src/Mod/TechDraw/Gui/TaskCosVertex.cpp, src/Mod/TechDraw/Gui/TaskCosVertex.h, src/Mod/TechDraw/Gui/TaskCosmeticLine.cpp, src/Mod/TechDraw/Gui/TaskCosmeticLine.h, src/Mod/TechDraw/Gui/TaskCustomizeFormat.cpp, src/Mod/TechDraw/Gui/TaskCustomizeFormat.h, src/Mod/TechDraw/Gui/TaskDetail.cpp, src/Mod/TechDraw/Gui/TaskDetail.h, src/Mod/TechDraw/Gui/TaskDimension.cpp, src/Mod/TechDraw/Gui/TaskDimension.h, src/Mod/TechDraw/Gui/TaskGeomHatch.cpp, src/Mod/TechDraw/Gui/TaskGeomHatch.h, src/Mod/TechDraw/Gui/TaskHatch.cpp, src/Mod/TechDraw/Gui/TaskHatch.h, src/Mod/TechDraw/Gui/TaskLeaderLine.cpp, src/Mod/TechDraw/Gui/TaskLeaderLine.h, src/Mod/TechDraw/Gui/TaskLineDecor.cpp, src/Mod/TechDraw/Gui/TaskLineDecor.h, src/Mod/TechDraw/Gui/TaskLinkDim.cpp, src/Mod/TechDraw/Gui/TaskLinkDim.h, src/Mod/TechDraw/Gui/TaskProjection.cpp, src/Mod/TechDraw/Gui/TaskProjection.h
- also some sorting
- also take care of PreCompiled.h
=> [TD] Task*, part 2/2: remove unused includes

src/Mod/Part/App/OpenCascadeAll.h, src/Mod/Surface/App/Blending/FeatureBlendCurve.cpp, src/Mod/Surface/App/CMakeLists.txt, src/Mod/Surface/Gui/CMakeLists.txt, src/Mod/Surface/Gui/PreCompiled.h
=> [Surface] enable precompiled headers

src/Mod/MeshPart/App/CMakeLists.txt, src/Mod/MeshPart/Gui/CMakeLists.txt, src/Mod/MeshPart/Gui/CrossSections.cpp, src/Mod/MeshPart/Gui/PreCompiled.h
=> [MeshPart] enable precompiled headers

src/Mod/Drawing/App/AppDrawing.cpp, src/Mod/Drawing/App/AppDrawingPy.cpp, src/Mod/Drawing/App/CMakeLists.txt, src/Mod/Drawing/App/DrawingExport.cpp, src/Mod/Drawing/App/DrawingExport.h, src/Mod/Drawing/App/FeatureClip.cpp, src/Mod/Drawing/App/FeatureClip.h, src/Mod/Drawing/App/FeaturePage.cpp, src/Mod/Drawing/App/FeaturePage.h, src/Mod/Drawing/App/FeatureProjection.cpp, src/Mod/Drawing/App/FeatureProjection.h, src/Mod/Drawing/App/FeatureView.cpp, src/Mod/Drawing/App/FeatureView.h, src/Mod/Drawing/App/FeatureViewAnnotation.cpp, src/Mod/Drawing/App/FeatureViewAnnotation.h, src/Mod/Drawing/App/FeatureViewPart.cpp, src/Mod/Drawing/App/FeatureViewPart.h, src/Mod/Drawing/App/FeatureViewSpreadsheet.cpp, src/Mod/Drawing/App/FeatureViewSpreadsheet.h, src/Mod/Drawing/App/FeatureViewSymbol.cpp, src/Mod/Drawing/App/FeatureViewSymbol.h, src/Mod/Drawing/App/PageGroup.cpp, src/Mod/Drawing/App/PageGroup.h, src/Mod/Drawing/App/PreCompiled.h, src/Mod/Drawing/App/ProjectionAlgos.cpp, src/Mod/Drawing/App/ProjectionAlgos.h
- also some sorting
- also enable precompiled header
=> [Drawing] App: remove unused headers

src/Mod/Sketcher/App/Analyse.h, src/Mod/Sketcher/App/AppSketcher.cpp, src/Mod/Sketcher/App/AppSketcherPy.cpp, src/Mod/Sketcher/App/Constraint.cpp, src/Mod/Sketcher/App/Constraint.h, src/Mod/Sketcher/App/ConstraintPyImp.cpp, src/Mod/Sketcher/App/ExternalGeometryExtension.cpp, src/Mod/Sketcher/App/ExternalGeometryExtension.h, src/Mod/Sketcher/App/ExternalGeometryExtensionPyImp.cpp, src/Mod/Sketcher/App/ExternalGeometryFacade.cpp, src/Mod/Sketcher/App/ExternalGeometryFacade.h, src/Mod/Sketcher/App/ExternalGeometryFacadePyImp.cpp, src/Mod/Sketcher/App/GeoList.cpp, src/Mod/Sketcher/App/GeoList.h, src/Mod/Sketcher/App/GeometryFacade.cpp, src/Mod/Sketcher/App/GeometryFacade.h, src/Mod/Sketcher/App/GeometryFacadePyImp.cpp
=> [Sketch] App A - G: remove unused headers

src/Mod/Sketcher/Gui/AppSketcherGui.cpp, src/Mod/Sketcher/Gui/Command.cpp, src/Mod/Sketcher/Gui/CommandAlterGeometry.cpp, src/Mod/Sketcher/Gui/CommandConstraints.cpp, src/Mod/Sketcher/Gui/CommandCreateGeo.cpp, src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp, src/Mod/Sketcher/Gui/CommandSketcherTools.cpp, src/Mod/Sketcher/Gui/CommandSketcherVirtualSpace.cpp, src/Mod/Sketcher/Gui/DrawSketchHandler.cpp, src/Mod/Sketcher/Gui/DrawSketchHandler.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfHyperbola.h, src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfParabola.h, src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h, src/Mod/Sketcher/Gui/DrawSketchHandlerCarbonCopy.h, src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h, src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h, src/Mod/Sketcher/Gui/DrawSketchHandlerExtend.h, src/Mod/Sketcher/Gui/DrawSketchHandlerExternal.h, src/Mod/Sketcher/Gui/DrawSketchHandlerFillet.h, src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h, src/Mod/Sketcher/Gui/DrawSketchHandlerLineSet.h, src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h, src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h, src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h, src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h, src/Mod/Sketcher/Gui/DrawSketchHandlerSplitting.h, src/Mod/Sketcher/Gui/DrawSketchHandlerTrimming.h
=> [Sketch] Gui: A - D: remove unused headers

src/Mod/TechDraw/App/DrawViewImage.cpp, src/Mod/TechDraw/Gui/TaskActiveView.cpp
- also improve temp file name generation
---
=> [TD]fix wrong error message on load

src/Mod/Sketcher/Gui/EditDatumDialog.h, src/Mod/Sketcher/Gui/EditModeCoinManager.cpp, src/Mod/Sketcher/Gui/EditModeCoinManager.h, src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.cpp, src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h, src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp, src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.h, src/Mod/Sketcher/Gui/EditModeGeometryCoinConverter.cpp, src/Mod/Sketcher/Gui/EditModeGeometryCoinConverter.h, src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp, src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.h, src/Mod/Sketcher/Gui/EditModeInformationOverlayCoinConverter.cpp, src/Mod/Sketcher/Gui/EditModeInformationOverlayCoinConverter.h, src/Mod/Sketcher/Gui/PropertyConstraintListItem.cpp, src/Mod/Sketcher/Gui/PropertyConstraintListItem.h, src/Mod/Sketcher/Gui/ShortcutListener.cpp, src/Mod/Sketcher/Gui/ShortcutListener.h, src/Mod/Sketcher/Gui/ViewProviderSketchCoinAttorney.h
=> [Sketch] Gui: E - Short*: remove unused headers

src/App/PropertyLinks.cpp
Fixed potential lost of element reference tracking after undo/redo.
@donovaly @chennes please check.
=> TopoNaming: fix lost of element reference tracking on undo/redo

src/Mod/PartDesign/App/FeatureSketchBased.cpp
- this patch is from @FlachyJoe
- as reported here: https://forum.freecadweb.org/viewtopic.php?p=646231#p646231 it was impossible to pad to a face which is touching the sketch despite is is no parallel to the extrusion Direction
=> [PD] enable padding to touching planes

src/Mod/Sketcher/Gui/SketchMirrorDialog.cpp, src/Mod/Sketcher/Gui/SketchMirrorDialog.h, src/Mod/Sketcher/Gui/SketchOrientationDialog.cpp, src/Mod/Sketcher/Gui/SketchOrientationDialog.h, src/Mod/Sketcher/Gui/SketchRectangularArrayDialog.cpp, src/Mod/Sketcher/Gui/SketchRectangularArrayDialog.h, src/Mod/Sketcher/Gui/SketcherRegularPolygonDialog.cpp, src/Mod/Sketcher/Gui/SketcherRegularPolygonDialog.h, src/Mod/Sketcher/Gui/SketcherSettings.cpp, src/Mod/Sketcher/Gui/SketcherSettings.h, src/Mod/Sketcher/Gui/SoDatumLabel.cpp, src/Mod/Sketcher/Gui/SoDatumLabel.h, src/Mod/Sketcher/Gui/SoZoomTranslation.cpp, src/Mod/Sketcher/Gui/SoZoomTranslation.h
=> [Sketch] Gui: Sketch - So: remove unused headers

src/Base/Tools2D.h, src/Mod/Sketcher/Gui/PreCompiled.h, src/Mod/Sketcher/Gui/Utils.cpp, src/Mod/Sketcher/Gui/Utils.h, src/Mod/Sketcher/Gui/ViewProviderPython.cpp, src/Mod/Sketcher/Gui/ViewProviderPython.h, src/Mod/Sketcher/Gui/ViewProviderSketch.cpp, src/Mod/Sketcher/Gui/ViewProviderSketch.h, src/Mod/Sketcher/Gui/ViewProviderSketchCoinAttorney.cpp, src/Mod/Sketcher/Gui/ViewProviderSketchCoinAttorney.h, src/Mod/Sketcher/Gui/ViewProviderSketchGeometryExtension.cpp, src/Mod/Sketcher/Gui/ViewProviderSketchGeometryExtension.h, src/Mod/Sketcher/Gui/Workbench.cpp, src/Mod/Sketcher/Gui/Workbench.h
=> [Sketch] Gui: U - End: remove unused headers

src/Gui/CommandView.cpp, src/Gui/QuantitySpinBox.cpp, src/Gui/propertyeditor/PropertyModel.cpp, src/Mod/Drawing/App/FeatureViewSpreadsheet.cpp, src/Mod/Part/Gui/TaskCheckGeometry.cpp, src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
- checks for true/false and nullptr
=> remove some unnecessary Boolean checks

src/Mod/Sketcher/Gui/PreCompiled.h, src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp, src/Mod/Sketcher/Gui/TaskDlgEditSketch.h, src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp, src/Mod/Sketcher/Gui/TaskSketcherConstraints.h, src/Mod/Sketcher/Gui/TaskSketcherCreateCommands.cpp, src/Mod/Sketcher/Gui/TaskSketcherCreateCommands.h, src/Mod/Sketcher/Gui/TaskSketcherElements.cpp, src/Mod/Sketcher/Gui/TaskSketcherElements.h, src/Mod/Sketcher/Gui/TaskSketcherGeneral.cpp, src/Mod/Sketcher/Gui/TaskSketcherGeneral.h, src/Mod/Sketcher/Gui/TaskSketcherMessages.cpp, src/Mod/Sketcher/Gui/TaskSketcherMessages.h, src/Mod/Sketcher/Gui/TaskSketcherSolverAdvanced.cpp, src/Mod/Sketcher/Gui/TaskSketcherSolverAdvanced.h, src/Mod/Sketcher/Gui/TaskSketcherValidation.cpp, src/Mod/Sketcher/Gui/TaskSketcherValidation.h
=> [Sketch] Gui:Task*: remove unused headers

src/Mod/Path/App/CMakeLists.txt, src/Mod/Path/App/PreCompiled.h
- also change result name to be uniform to the other WBs
=> [Path] App: remove unused files from PreCompiled.h

src/Mod/Draft/draftfunctions/move.py
AngularDimension objects could not be moved or copied with Draft_Move.
---
=> Draft: fix move AngularDimension bug

src/Mod/Path/Path/Main/Gui/PreferencesJob.py
---
One more place that needed to be fixed after the Path file and directory structure rearrangement from a couple of months ago.
=> Path:  Fixed regression in import statement.

src/Mod/AddonManager/AddonManager.py, src/Mod/AddonManager/NetworkManager.py, src/Mod/AddonManager/addonmanager_devmode.py, src/Mod/AddonManager/addonmanager_devmode_predictor.py, src/Mod/AddonManager/addonmanager_installer.py, src/Mod/AddonManager/addonmanager_macro.py, src/Mod/AddonManager/addonmanager_utilities.py, src/Mod/AddonManager/addonmanager_workers_startup.py
Automated `pyupgrade --py38-plus` run on non-autogenerated files: only makes non-CST-changing modifications.
=> Addon Manager: Update to Python 3.8

src/Mod/Surface/Gui/TaskFilling.cpp, src/Mod/Surface/Gui/TaskFilling.h, src/Mod/Surface/Gui/TaskFilling.ui, src/Mod/Surface/Gui/TaskFillingEdge.cpp, src/Mod/Surface/Gui/TaskFillingEdge.h, src/Mod/Surface/Gui/TaskFillingEdge.ui, src/Mod/Surface/Gui/TaskFillingVertex.cpp, src/Mod/Surface/Gui/TaskFillingVertex.h, src/Mod/Surface/Gui/TaskFillingVertex.ui, src/Mod/Surface/Gui/TaskGeomFillSurface.cpp, src/Mod/Surface/Gui/TaskGeomFillSurface.h, src/Mod/Surface/Gui/TaskGeomFillSurface.ui, src/Mod/Surface/Gui/TaskSections.cpp, src/Mod/Surface/Gui/TaskSections.h, src/Mod/Surface/Gui/TaskSections.ui
See https://forum.freecadweb.org/viewtopic.php?f=3&t=57538&p=592134#p592134.
=> [Surface] Allow modal adding/removal of geometric entities

src/Mod/Path/Path/Post/Processor.py
remove deprecated python 2.7 code
---
=> Fixes #7834  Removes deprecated py2.7 try/except block

src/Mod/TechDraw/App/DrawView.cpp
https://www.forum.freecadweb.org/viewtopic.php?f=35&t=74590
---
=> [TD]fix expression in Scale fails to propagate

src/Mod/Sketcher/App/planegcs/Constraints.cpp, src/Mod/Sketcher/App/planegcs/Constraints.h
================================================================
Credit goes for forum user acolomitchi:
https://forum.freecadweb.org/viewtopic.php?p=648807#p648807
=> Solver: Pass map by const reference to avoid performance penalty

src/Mod/Start/StartPage/StartPage.py
Detect FCMacro files in Start and display the MacroEditor icon for them. Also uses the Addon Manager's Macro class to parse the Macro metadata and display the author information if available, and makes the image-detection code more robust.
Closes #7709.
=> Start: Add icon for FCMacro files

src/Mod/MeshPart/Gui/MeshFlatteningCommand.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/201.
---
=> MeshPart: Fix translation issues

src/Mod/TechDraw/App/DrawViewPart.cpp
=> [TD]Fix startup exception on empty compound

src/Mod/TechDraw/App/DrawPage.cpp, src/Mod/TechDraw/App/DrawPage.h, src/Mod/TechDraw/Gui/AppTechDrawGui.cpp, src/Mod/TechDraw/Gui/CMakeLists.txt, src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp, src/Mod/TechDraw/Gui/ViewProviderDrawingView.h, src/Mod/TechDraw/Gui/ViewProviderDrawingViewExtension.cpp, src/Mod/TechDraw/Gui/ViewProviderDrawingViewExtension.h, src/Mod/TechDraw/Gui/ViewProviderPage.cpp, src/Mod/TechDraw/Gui/ViewProviderPage.h, src/Mod/TechDraw/Gui/ViewProviderPageExtension.cpp, src/Mod/TechDraw/Gui/ViewProviderPageExtension.h, src/Mod/TechDraw/Gui/ViewProviderTemplate.cpp, src/Mod/TechDraw/Gui/ViewProviderTemplate.h, src/Mod/TechDraw/Gui/ViewProviderTemplateExtension.cpp, src/Mod/TechDraw/Gui/ViewProviderTemplateExtension.h
TechDraw did not always handle drag and drop correctly.  This PR prevents pages from  being broken when Templates or Views are dragged and dropped.
---
=> [TD]add extensions for drag and drop

src/Mod/Fem/femmesh/meshtools.py
=> FEM: femmesh: fix AttributeError: module 'numpy' has no attribute 'int'

src/Mod/TechDraw/App/DrawViewDetail.cpp, src/Mod/TechDraw/Gui/QGIDecoration.cpp, src/Mod/TechDraw/Gui/QGIDecoration.h, src/Mod/TechDraw/Gui/QGIHighlight.cpp, src/Mod/TechDraw/Gui/QGIHighlight.h, src/Mod/TechDraw/Gui/QGIViewPart.cpp, src/Mod/TechDraw/Gui/QGIViewPart.h, src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
- drag detail highlight to change detail anchor point
- change detail reference position using HighlightAdjust property
addresses
#7823 reference obscures drawing
#6016 drag detail view highlight
---
=> [TD]make detail highlight interactive  #7823 #6016

src/Mod/Path/PathTests/TestPathAdaptive.py, src/Mod/Path/PathTests/TestPathOpUtil.py, src/Mod/Path/PathTests/TestPathPost.py
Moved test file opening into instance methods so they don't get loade…d unless used.
=> [Path] bugfix/8087-dont-load-project-files-unless-tests-are-run fixes #8087

CONTRIBUTING.md
Addition to the contribute guide to explain how to attribute copyright to the FPA
---
=> Adding info to hand over the copyright to the FPA

src/Mod/TechDraw/Gui/ViewProviderDrawingViewExtension.cpp, src/Mod/TechDraw/Gui/ViewProviderDrawingViewExtension.h, src/Mod/TechDraw/Gui/ViewProviderPageExtension.cpp, src/Mod/TechDraw/Gui/ViewProviderPageExtension.h, src/Mod/TechDraw/Gui/ViewProviderTemplateExtension.cpp, src/Mod/TechDraw/Gui/ViewProviderTemplateExtension.h
Fix link errors on Win reported here:  https://github.com/FreeCAD/FreeCAD/pull/8097#issuecomment-1368630964
---
=> [TD]fix Win link error in ViewProvider extensions

src/Gui/QtAll.h, src/Mod/TechDraw/Gui/PreCompiled.h, src/Mod/TechDraw/Gui/QGISVGTemplate.cpp
=> [TD] fix compilation with PCH after d63ac0f7

src/Mod/Path/Path/Base/Drillable.py, src/Mod/Path/Path/Op/Gui/Selection.py
Relaxes the prohibition of partial arcs in the selection gate for drilling.
---
=> Fix for Partial edge drilling Fixes 8131

src/App/Application.cpp, src/Base/Parameter.cpp, src/Base/Parameter.h, src/Gui/DlgRevertToBackupConfigImp.cpp, src/Gui/PreferencePackManager.cpp
@chennes This fixes crash when loading preference pack.
=> Base/App/Gui: force using Base::Handle for ParameterManager

src/Mod/Sketcher/App/planegcs/GCS.cpp
======================================================================
1. Instead of excluding internal alignment constraints from popularity candidate selection, exclude them from the group altogether. This ensures no group is non-empty with uneligible candidates, which prevents an infinite loop in uncommon circumnstances (when DoFs collapse).
2. Ensure no internal alignment constraint is identified when conflict ensues.
=> GCS: Improvements to popularity contest and conflicting identification

src/Mod/Arch/ArchStairs.py
Props to david69 in https://crowdin.com/translate/freecad/6766/en-fr#6605247:drl:44875:david69
=> Crowdin: [skip ci] fix string in `Arch/ArchStairs.py` 

src/Mod/TechDraw/Gui/Command.cpp, src/Mod/TechDraw/Gui/DrawGuiUtil.cpp, src/Mod/TechDraw/Gui/QGIViewDimension.cpp
This PR fixes an issue reported here: https://www.forum.freecadweb.org/viewtopic.php?f=35&t=75107&sid=2537f947f570c70fdfcc475a7a64f360
---
=> [TD]Fix view direction precision

src/Gui/QtAll.h, src/Mod/TechDraw/App/AppTechDrawPy.cpp, src/Mod/TechDraw/App/DimensionFormatter.cpp, src/Mod/TechDraw/App/DimensionGeometry.cpp, src/Mod/TechDraw/App/DimensionReferences.cpp, src/Mod/TechDraw/App/DrawDimHelper.cpp, src/Mod/TechDraw/App/DrawDimHelper.h, src/Mod/TechDraw/App/DrawUtil.cpp, src/Mod/TechDraw/App/DrawViewDimension.h, src/Mod/TechDraw/Gui/DimensionValidators.cpp, src/Mod/TechDraw/Gui/DrawGuiUtil.cpp, src/Mod/TechDraw/Gui/PreCompiled.h, src/Mod/TechDraw/Gui/TaskDimRepair.cpp
=> [TD] attempt to fix compilation with PCH after #8141

src/Mod/TechDraw/App/AppTechDrawPy.cpp, src/Mod/TechDraw/App/DrawUtil.cpp, src/Mod/TechDraw/App/DrawViewSymbol.cpp, src/Mod/TechDraw/Gui/QGIViewAnnotation.cpp, src/Mod/TechDraw/Gui/QGIViewSymbol.cpp, src/Mod/TechDraw/Gui/ViewProviderPage.cpp
- typos and code formatting as reported by the CI
- some more re-sorting
=> [TD] minor fixes

src/Mod/TechDraw/Gui/DimensionValidators.cpp, src/Mod/TechDraw/Gui/DimensionValidators.h, src/Mod/TechDraw/Gui/PreCompiled.h, src/Mod/TechDraw/Gui/ViewProviderDrawingViewExtension.cpp, src/Mod/TechDraw/Gui/ViewProviderDrawingViewExtension.h, src/Mod/TechDraw/Gui/ViewProviderPageExtension.cpp, src/Mod/TechDraw/Gui/ViewProviderPageExtension.h, src/Mod/TechDraw/Gui/ViewProviderTemplateExtension.cpp, src/Mod/TechDraw/Gui/ViewProviderTemplateExtension.h
- in DimensionValidators.h the declarations must not be with TechDrawExport
- add missing precompiled headers
- also fix too long lines (fixed by clang)
- also some re-sorting
- also remove unused headers
=> [TD] final fix of compilation after #8141

src/Main/FreeCADGuiPy.cpp, src/Main/MainCmd.cpp, src/Main/MainGui.cpp
Closes #8130  
Note to merge dev, please squash commits
---
=> Increment year in copyright notice (2023)

README.md
* Link to github instead of mantis.  
* Update links on how to submit bugs + feature requests   
* Add link to CONTRIBUTING.md
---
=> README: [skip ci] update bugtracker related links and info

src/Mod/Path/Path/Op/Gui/Selection.py, src/Mod/Path/Path/Op/ThreadMilling.py
This might be a naive fix but it seems to work.  
Fixes #7855 
---
=> [Path] fix bug with threadmilling collision

src/Mod/Draft/draftgeoutils/offsets.py
This PR removes the call to isReallyClosed() from offsetWire(). And if the wire argument is a list the edges are no longer sorted.
As requested in the forum discussion:
https://forum.freecadweb.org/viewtopic.php?p=652253#p652253
---
=> Draft: improve offsets.offsetWire

src/Mod/Spreadsheet/Gui/qtcolorpicker.cpp
=> Spreadsheet: [skip ci] convert tabs to spaces

src/Gui/CallTips.cpp, src/Gui/DlgCustomizeSpaceball.cpp, src/Gui/DlgObjectSelection.cpp, src/Gui/DlgUndoRedo.cpp, src/Gui/ExpressionCompleter.cpp, src/Gui/FileDialog.cpp, src/Gui/InputField.cpp, src/Gui/ProgressDialog.cpp, src/Gui/SpinBox.cpp, src/Gui/TextEdit.cpp, src/Gui/ToolBox.cpp, src/Gui/Tree.cpp, src/Gui/Widgets.cpp, src/Gui/propertyeditor/PropertyEditor.cpp, src/Gui/propertyeditor/PropertyItem.cpp, src/Mod/Sketcher/Gui/TaskSketcherGeneral.cpp, src/Mod/Spreadsheet/Gui/qtcolorpicker.cpp
=> [Gui] modernize some connect() settings

src/Mod/Draft/draftutils/gui_utils.py
=> Draft: Update gui_utils.py

src/Mod/Draft/Resources/ui/TaskPanel_SetStyle.ui, src/Mod/Draft/draftguitools/gui_setstyle.py
Update of Draft_SetStyle related to #8081.
Changed the "Texts/dims" button to "Annotations". This option now also handles Draft_Labels.
---
=> Draft: Update Draft_SetStyle

src/Mod/Draft/draftguitools/gui_setstyle.py, src/Mod/Draft/draftutils/gui_utils.py
Further improvements related to #8081, #8190 and #8191.
---
=> Draft: Update gui_setstyle.py and gui_utils.py

src/Mod/Draft/draftguitools/gui_setstyle.py
=> Draft: gui_setstyle.py onApplyAnnot should check for doc

src/Mod/Path/CMakeLists.txt, src/Mod/Path/Gui/Resources/panels/PageOpDeburrEdit.ui, src/Mod/Path/Path/Op/Deburr.py, src/Mod/Path/PathTests/TestPathOpDeburr.py, src/Mod/Path/TestPathApp.py
fix offset calculation for arbitrary cutting edge angles.
=> [Path] Bugfix/issue 8185 deburr offset calculation

src/Mod/Path/Path/Post/UtilsArguments.py, src/Mod/Path/Path/Post/UtilsExport.py, src/Mod/Path/Path/Post/UtilsParse.py, src/Mod/Path/PathTests/TestRefactoredTestPost.py
This is the next chunk of changes for the "refactored" postprocessor work.  It also includes:
Used "with" for file writes, removed "pythonopen".
This is part of the work for  #6117.
---
=> Path:  Added more tests and fixed some parameter handling, refactored axis and feed number formatting.

src/Mod/Path/InitGui.py, src/Mod/Path/Path/Op/Surface.py, src/Mod/Path/Path/Op/Waterline.py
---
Hi there, I am a maintainer of OpenCAMLib and have made a new release, it contains a couple of speed improvements, and the opencamlib package is now also available on PyPi.
Since the "ocl" name was not available on PyPi …
=> Update opencamlib imports to support latest version

src/Mod/Arch/ArchStructure.py
Forum Discussion : [ArchSketch - Feature Preview] - Slab, Curtain Wall, ArchWall etc. on Same ArchSketch
- https://forum.freecadweb.org/viewtopic.php?f=23&t=73018
---
=> [ArchStructure] ArchSketch Feature : Select Edges to build shape

src/Mod/Arch/ArchWindow.py
This PR improves `invertHinge()` in ArchWindow.py. Instead of using fixed pairs of indices, the indices are derived from the Wires and the WindowParts.
Additionally `setupContextMenu()` was updated:
The **Invert hinge position** option is now only displayed for windows with a single hinge edge.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=3&t=75275
---
=> Arch: ArchWindow.py improve invertHinge

src/Mod/Sketcher/App/Sketch.cpp, src/Mod/Sketcher/App/Sketch.h, src/Mod/Sketcher/Gui/CommandConstraints.cpp
See the discussion from https://forum.freecadweb.org/viewtopic.php?f=9&t=71130&start=180#p652350.
=> [Sketcher] Add line tangent at knot through endpoint

src/Mod/TechDraw/App/DrawUtil.cpp, src/Mod/TechDraw/App/DrawUtil.h, src/Mod/TechDraw/Gui/CommandCreateDims.cpp, src/Mod/TechDraw/Gui/DimensionValidators.cpp, src/Mod/TechDraw/Gui/TaskDimRepair.cpp, src/Mod/TechDraw/Gui/TaskDimRepair.h, src/Mod/TechDraw/Gui/TaskDimRepair.ui, src/Mod/TechDraw/Gui/Workbench.cpp
This PR addresses issues raised by user testing here: https://www.forum.freecadweb.org/viewtopic.php?f=35&t=75331
---
=> [TD]Dim repair upgrade

src/Mod/TechDraw/Gui/DimensionValidators.cpp
This PR addresses an issue on Mac reported here: https://www.forum.freecadweb.org/viewtopic.php?p=652371#p652371
---
=> [TD]fix crash on dim create on Mac

README.md
lgtm was sunset in Dec 2022. https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
---
=> README: [skip ci] remove lgtm badges

src/Base/CMakeLists.txt
Remove trailing whitespace in `src/Base/CmakeLists.txt`
---
=> Fix trailing whitespace

src/Mod/Sketcher/App/Sketch.cpp, src/Mod/Sketcher/App/Sketch.h, src/Mod/Sketcher/App/planegcs/Constraints.cpp, src/Mod/Sketcher/App/planegcs/Constraints.h, src/Mod/Sketcher/App/planegcs/GCS.cpp, src/Mod/Sketcher/App/planegcs/GCS.h, src/Mod/Sketcher/Gui/CommandConstraints.cpp, src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
With these changes, point-on-curve constraints can be added to B-spline constraints.
This PR is part of [the B-spline constraint project](https://forum.freecadweb.org/viewtopic.php?f=9&t=71130).
See known issues [here](https://forum.freecadweb.org/viewtopic.php?f=9&t=71130&start=100#p632599).
=> Sketcher: point on B-spline constraint

src/Mod/TechDraw/App/DimensionGeometry.h, src/Mod/TechDraw/App/DimensionReferences.cpp, src/Mod/TechDraw/App/DimensionReferences.h, src/Mod/TechDraw/App/DrawView.cpp, src/Mod/TechDraw/App/Geometry.cpp, src/Mod/TechDraw/App/LandmarkDimension.cpp, src/Mod/TechDraw/App/LandmarkDimension.h, src/Mod/TechDraw/Gui/DimensionValidators.cpp, src/Mod/TechDraw/Gui/DimensionValidators.h, src/Mod/TechDraw/Gui/TaskCenterLine.cpp, src/Mod/TechDraw/Gui/TaskCosmeticLine.cpp, src/Mod/TechDraw/Gui/TaskDimRepair.cpp
Fixes header uniformity + fixes trailing whitespace
---
=> TechDraw: header uniformity + trailing whitespace

src/Mod/Draft/draftguitools/gui_setstyle.py, src/Mod/Draft/draftutils/utils.py, src/Mod/Draft/draftviewproviders/view_wpproxy.py
Alpha values of colors were not correct.
---
=> Draft: improve color handling in gui_setstyle.py

src/Mod/Draft/draftfunctions/rotate.py
=> Draft: rotate.py: remove Placement.rotate() workaround

src/Mod/Surface/App/FeatureSewing.cpp
Fix header uniformity in Surface wb code
---
=> Surface: fix header uniformity

src/Mod/Show/Containers.py, src/Mod/Show/DepGraphTools.py, src/Mod/Show/SceneDetail.py, src/Mod/Show/SceneDetails/Camera.py, src/Mod/Show/SceneDetails/ClipPlane.py, src/Mod/Show/SceneDetails/ObjectClipPlane.py, src/Mod/Show/SceneDetails/Pickability.py, src/Mod/Show/SceneDetails/VProperty.py, src/Mod/Show/SceneDetails/Workbench.py, src/Mod/Show/ShowUtils.py, src/Mod/Show/TVObserver.py, src/Mod/Show/TVStack.py, src/Mod/Show/mTempoVis.py
Make header uniformity + remove trailing whitespace
---
=> ShowWB: fix header uniformity

src/Mod/Spreadsheet/App/Cell.cpp, src/Mod/Spreadsheet/App/PropertyColumnWidthsPyImp.cpp, src/Mod/Spreadsheet/App/PropertyRowHeightsPyImp.cpp, src/Mod/Spreadsheet/App/PropertySheet.cpp, src/Mod/Spreadsheet/App/PropertySheetPyImp.cpp, src/Mod/Spreadsheet/Gui/DlgBindSheet.cpp, src/Mod/Spreadsheet/Gui/DlgSheetConf.cpp, src/Mod/Spreadsheet/Gui/DlgSheetConf.h, src/Mod/Spreadsheet/Gui/LineEdit.cpp, src/Mod/Spreadsheet/Gui/PropertiesDialog.h, src/Mod/Spreadsheet/Gui/SheetModel.h, src/Mod/Spreadsheet/Gui/SheetTableView.cpp, src/Mod/Spreadsheet/Gui/SheetTableView.h, src/Mod/Spreadsheet/Gui/SpreadsheetDelegate.cpp, src/Mod/Spreadsheet/TestSpreadsheet.py
includes trailing whitespace fixes
---
=> Spreadsheet: fix header uniformity

src/Mod/Sketcher/App/SketchObject.cpp, src/Mod/Sketcher/App/SketchObjectPyImp.cpp, src/Mod/Sketcher/App/planegcs/Constraints.cpp, src/Mod/Sketcher/App/planegcs/Constraints.h, src/Mod/Sketcher/Gui/TaskSketcherConstraints.ui, src/Mod/Sketcher/Gui/TaskSketcherElements.ui, src/Mod/Sketcher/ProfileLib/RegularPolygon.py
Convert tabs to spaces in `src/Mod/Sketcher/*`
---
=> Sketcher: convert indentations to spaces

src/Mod/PartDesign/App/BodyPy.xml, src/Mod/PartDesign/PartDesign_Model.xml, src/Mod/PartDesign/Scripts/DistanceBolt.py, src/Mod/PartDesign/Scripts/Parallelepiped.py
Convert tabs to spaces in `src/Mod/PartDesign/*`
---
=> PartDesign: convert indentations to spaces

src/Gui/AxisOriginPy.xml, src/Gui/GuiApplicationNativeEventAware.cpp, src/Gui/SelectionFilter.cpp, src/Gui/SoFCVectorizeSVGAction.cpp, src/Gui/SoNavigationDragger.cpp, src/Gui/TaskDlgRelocation.h, src/Gui/View3DInventorRiftViewer.cpp, src/Gui/ViewProviderDocumentObjectPy.xml, src/Gui/ViewProviderLinkPy.xml, src/Gui/core-gui.dox, src/Gui/lex.SelectionFilter.c
Convert tabs to whitespace in `src/Gui` files
---
=> Gui: convert indentations to spaces

src/Mod/Sketcher/Gui/CommandConstraints.cpp
See https://forum.freecadweb.org/viewtopic.php?f=9&t=71130&start=200#p654523.
Currently only replaces "knot to line tangent" + "knot to line endpoint coincident" -> "knot to endpoint tangent".
Other possibilities need to be listed and studied.
=> [Sketcher] Substitute knot tangent related constraints

src/Gui/Stylesheets/Behave-dark.qss, src/Gui/Stylesheets/Dark-blue.qss, src/Gui/Stylesheets/Dark-contrast.qss, src/Gui/Stylesheets/Dark-green.qss, src/Gui/Stylesheets/Dark-orange.qss, src/Gui/Stylesheets/Darker-blue.qss, src/Gui/Stylesheets/Darker-green.qss, src/Gui/Stylesheets/Darker-orange.qss, src/Gui/Stylesheets/ProDark.qss
Stylesheet housekeeping by converting indentations to spaces
---
=> Stylesheets: convert indentations to spaces

README.md
* Fix bugtracker link at the top of the README
---
=> README: fix bugtracker link

src/Mod/Draft/draftguitools/gui_offset.py
#8207 has removed param from utils.py.
---
=> Draft: fix gui_offset.py issue caused by PR8207

cMake/FreeCAD_Helpers/SetupPython.cmake
=> Update python min version check

CMakeLists.txt
- as discussed in #8054 add a comment with the link to the discussion about the version limits as quick reference
=> [CMake] improve comment about CMake limit

src/Gui/ExpressionCompleter.cpp, src/Gui/FreeCADGuiInit.py
Fix trailing whitespace in a couple of files.
---
=> Gui: fix trailing whitespace

src/Gui/ExpressionCompleter.cpp
- too long lines
- too short variable names
- also some reformatting according to our current clang file
=> [Gui] ExpressionCompleter: fix some GitHub Action reports

src/Mod/Part/App/AppPartPy.cpp, src/Mod/Part/App/FT2FC.cpp
This PR fixes issue #8271.
---
=> [Part][Draft]fix #8271 temporary files on windows

src/Mod/Path/Path/Post/scripts/estlcam_post.py
=> Path: add Estlcam postprocessor fix #8192

src/Mod/Part/TestPartGui.py
=> Part: add integration test for SectionCut command

src/Mod/AddonManager/AddonManager.py, src/Mod/AddonManager/AddonManagerTest/app/test_addon.py, src/Mod/AddonManager/AddonManagerTest/app/test_macro.py, src/Mod/AddonManager/AddonManagerTest/app/test_utilities.py, src/Mod/AddonManager/AddonManagerTest/gui/test_gui.py, src/Mod/AddonManager/AddonManagerTest/gui/test_workers_startup.py, src/Mod/AddonManager/AddonManagerTest/gui/test_workers_utility.py, src/Mod/AddonManager/NetworkManager.py, src/Mod/AddonManager/TestAddonManagerApp.py, src/Mod/AddonManager/TestAddonManagerGui.py, src/Mod/AddonManager/addonmanager_macro.py, src/Mod/AddonManager/addonmanager_utilities.py, src/Mod/AddonManager/addonmanager_workers_installation.py, src/Mod/AddonManager/addonmanager_workers_startup.py, src/Mod/AddonManager/addonmanager_workers_utility.py, src/Mod/AddonManager/change_branch.py, src/Mod/AddonManager/install_to_toolbar.py, src/Mod/AddonManager/manage_python_dependencies.py, src/Mod/AddonManager/package_details.py, src/Mod/AddonManager/package_list.py
Update all Addon Manager license headers to match the recommended language from the FSF's site.
---
=> Addon Manager: Update license headers

cMake/FreeCAD_Helpers/SetupPython.cmake
=> Remove obsolete cmake

src/Mod/Path/Path/Post/UtilsArguments.py, src/Mod/Path/Path/Post/UtilsExport.py, src/Mod/Path/Path/Post/UtilsParse.py
This is the next chunk of changes for the "refactored" postprocessor work.
This is part of the work for https://github.com/FreeCAD/FreeCAD/issues/6117.
---
=> Path:  Refactored PostUtilsParse.parse a lot.

src/Mod/Sketcher/Gui/CommandSketcherTools.cpp, src/Mod/Sketcher/Gui/Utils.cpp
This PR addresses an issue raised here: https://forum.freecadweb.org/viewtopic.php?p=656923#p656923
---
=> [Sketcher]fix cursor display of angles

src/Gui/ComboView.cpp, src/Gui/DAGView/DAGModel.cpp, src/Gui/DAGView/DAGView.cpp, src/Gui/DemoMode.cpp, src/Gui/DlgActionsImp.cpp, src/Gui/DlgCheckableMessageBox.cpp, src/Gui/DlgCommandsImp.cpp, src/Gui/DlgExpressionInput.cpp, src/Gui/DlgInputDialogImp.cpp, src/Gui/DlgObjectSelection.cpp, src/Gui/DlgProjectInformationImp.cpp, src/Gui/DlgSettingsNavigation.cpp
=> [Gui] modernize some UI connections

src/Gui/FreeCADGuiInit.py
- superfluous parens and loo long lines reported [here](https://github.com/FreeCAD/FreeCAD/pull/8260/commits/19712db498843950a8cd1f9daa09fd785915246d#diff-fe1bd12fc229253965f0c5fc201fcb834f679a42b5d4836813595b8e0a50b4ca)
=> [Gui] FreeCADGuiInit.py: address some GH action reports

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femsolver/elmer/writer.py, src/Mod/Fem/femsolver/equationbase.py
=> [FEM] sort equations alphabetically

src/Mod/Fem/femsolver/equationbase.py
=> [FEM] equationbase: sort equations alphabetically

src/Gui/NaviCube.cpp, src/Gui/NaviCube.h, src/Gui/View3DInventor.cpp
- there is a bug: when deleting any NaviCube parameter in the parameters dialog, the background color suddenly changes the fix is to register the NaviCube parameters to the view
- the PR also fixes the issue that the default font size was not properly calculated but hardcoded
=> [Gui] register NaviCube parameters to view

src/Mod/Draft/draftguitools/gui_dimensions.py, src/Mod/Draft/draftguitools/gui_trackers.py
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=75676
---
=> Draft: fix normal calculation for angular dims

src/Mod/Fem/femsolver/elmer/solver.py, src/Mod/Fem/femsolver/elmer/writer.py
- Elmer allows for all currently supported equations several coordinate systems
- also remove an unused variable
=> [FEM] Elmer: don't hardcode the coordinate system

src/Mod/Fem/femsolver/elmer/writer.py
- I mixed the normal stress solver with the elastic stress solver. For the normal stress solver plane stress is possible in all coordinate systems
=> [FEM] Elmer: revert wrong change from #8336

src/Mod/Part/Gui/Command.cpp
- since FC 0.20 we require OCC 7.4
=> [Part] [skip ci] update a tooltip

src/Mod/Material/FluidMaterial/Air.FCMat, src/Mod/Material/FluidMaterial/Argon.FCMat, src/Mod/Material/FluidMaterial/Carbon_dioxide.FCMat, src/Mod/Material/FluidMaterial/Nitrogen.FCMat, src/Mod/Material/FluidMaterial/Water.FCMat, src/Mod/Material/StandardMaterial/Aluminum-Generic.FCMat, src/Mod/Material/StandardMaterial/Copper-Generic.FCMat, src/Mod/Material/StandardMaterial/Graphite.FCMat, src/Mod/Material/StandardMaterial/Invar-Generic.FCMat, src/Mod/Material/StandardMaterial/TEMPLATE.FCMat, src/Mod/Material/Templatematerial.yml
- also rename property group to "electromagnetical" (this change has no influence on any existing simulation, is only the name in the material editor)
=> [Material] add support for magnetic permeability

src/App/FreeCADInit.py, src/Base/Unit.cpp, src/Base/Unit.h, src/Base/UnitsSchemaInternal.cpp, src/Base/UnitsSchemaMKS.cpp, src/Gui/DlgUnitsCalculatorImp.cpp
- necessary to implement electromagnetic features to the FEM WB
=> [Core] add current density

src/Gui/NaviCube.cpp, src/Mod/AddonManager/addonmanager_installer.py, src/Mod/Fem/femsolver/elmer/writer.py, src/Mod/Path/Data/Threads/sources.txt, src/Mod/TechDraw/Gui/TaskLeaderLine.cpp, src/Mod/TechDraw/TDTest/DrawViewDetailTest.py
Fix various trailing newlines, typos and grammar
---
=> Fix various trailing newlines, typos and grammar

src/Mod/Fem/femsolver/elmer/writer.py, src/Mod/Fem/femtest/data/elmer/box_static_0_mm.sif, src/Mod/Fem/femtest/data/elmer/ccxcantilever_faceload_0_mm.sif, src/Mod/Fem/femtest/data/elmer/ccxcantilever_faceload_1_si.sif, src/Mod/Fem/femtest/data/elmer/ccxcantilever_nodeload_0_mm.sif, src/Mod/Fem/femtest/data/elmer/ccxcantilever_prescribeddisplacement_0_mm.sif
- when looking at the Elmer input file 'case.sif' it is extremely helpful to thee also the name of the material Since the name is only form info, this does not change the actual simulation
=> [FEM] Elmer output material name

src/Mod/Start/Gui/DlgStartPreferences.ui
- as mentioned in #8330, new size set by QtDesigner
=> [Start] set sensible size for DlgStartPreferences.ui

src/Mod/Fem/femsolver/elmer/writer.py
=> [FEM] [skip ci] Elmer write: some cleanup

src/Mod/Start/StartPage/StartPage.css, src/Mod/Start/StartPage/StartPage.py
Fixes invalid css in #8330 
---
=> Fixes startpage css - fixes #8330

src/App/Application.cpp, src/App/PropertyUnits.cpp, src/App/PropertyUnits.h, src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/Gui/CMakeLists.txt, src/Mod/Fem/Gui/Command.cpp, src/Mod/Fem/Gui/Resources/Fem.qrc, src/Mod/Fem/Gui/Resources/icons/FEM_ConstraintCurrentDensity.svg, src/Mod/Fem/Gui/Resources/ui/CurrentDensity.ui, src/Mod/Fem/Gui/Workbench.cpp, src/Mod/Fem/ObjectsFem.py, src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femobjects/constraint_currentdensity.py, src/Mod/Fem/femtaskpanels/task_constraint_currentdensity.py, src/Mod/Fem/femtest/app/test_object.py, src/Mod/Fem/femtest/app/test_open.py, src/Mod/Fem/femtest/gui/test_open.py, src/Mod/Fem/femviewprovider/view_constraint_currentdensity.py
- also add corresponding App::PropertyCurrentDensity
=> [FEM] add current density constraint

src/Mod/TechDraw/CMakeLists.txt, src/Mod/TechDraw/Gui/Resources/TechDraw.qrc, src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_AxoLengthDimension.svg, src/Mod/TechDraw/Gui/Workbench.cpp, src/Mod/TechDraw/TechDrawTools/CommandAxoLengthDimension.py, src/Mod/TechDraw/TechDrawTools/__init__.py
=> [TD] Add Command Axo Length Dimension  (replaces 8300)

src/Gui/Command.cpp
Fix typo in source comment.
---
=> Gui: [skip ci] fix typo

src/Mod/Fem/femsolver/elmer/writer.py, src/Mod/Fem/femtools/constants.py
=> [FEM] Elmer: add permeability of vacuum

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/femsolver/elmer/equations/heat_writer.py, src/Mod/Fem/femsolver/elmer/writer.py
- sort out heat equation - next step to refactor writer.py
=> [FEM] Elmer writer: sort out heat equation

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/femsolver/elmer/equations/flux_writer.py, src/Mod/Fem/femsolver/elmer/writer.py
- sort out flux equation - next step to refactor writer.py
=> [FEM] Elmer writer: sort out flux equation

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/femsolver/elmer/equations/flow_writer.py, src/Mod/Fem/femsolver/elmer/writer.py
- sort out flow equation - next step to refactor writer.py
=> [FEM] Elmer writer: sort out flow equation

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/femsolver/elmer/equations/electricforce_writer.py, src/Mod/Fem/femsolver/elmer/writer.py
- sort out electricforce equation - next step to refactor writer.py
=> [FEM] Elmer writer: sort out electricforce equation

src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/femsolver/elmer/equations/elasticity_writer.py, src/Mod/Fem/femsolver/elmer/writer.py
- sort out elasticity equation - last step to refactor writer.py
=> [FEM] Elmer writer: sort out elasticity equation

src/Mod/Fem/femsolver/elmer/equations/electricforce_writer.py, src/Mod/Fem/femsolver/elmer/equations/electrostatic_writer.py, src/Mod/Fem/femsolver/elmer/equations/flow_writer.py, src/Mod/Fem/femsolver/elmer/equations/flux_writer.py, src/Mod/Fem/femsolver/elmer/equations/heat_writer.py, src/Mod/Fem/femsolver/elmer/writer.py
- update after the revision of writer.py
=> [FEM] Elmer writer: correct copyrights

src/Gui/DlgSettingsNavigation.cpp, src/Gui/DlgSettingsNavigation.h, src/Gui/DlgSettingsNavigation.ui, src/Gui/NaviCube.cpp, src/Gui/View3DInventor.cpp, src/Gui/View3DInventor.h, src/Gui/View3DInventorViewer.cpp, src/Gui/View3DInventorViewer.h
=> Refactoring viewer settings

src/Mod/Draft/draftmake/make_clone.py, src/Mod/Draft/drafttests/test_modification.py
Probably should have done this before...
---
=> [Draft] fix Draft_Clone DiffuseColor delay issue during unit test

src/Gui/ViewProviderDocumentObjectPy.xml, src/Gui/Workbench.cpp, src/Mod/Fem/femsolver/elmer/equations/magnetodynamic2D.py, src/Mod/Fem/femsolver/elmer/writer.py
Removed trailing newlines  
---
=> Fix trailing newlines

src/Mod/Fem/Gui/Resources/icons/FEM_ConstraintCurrentDensity.svg
=> [FEM] [skic ci] fix arrows in CurrentDensity icon

src/Mod/AddonManager/AddonManagerTest/gui/gui_mocks.py
On macOS modal dialogs do not have a title, so when looking for dialogs, just assume the found modal is the right one.
---
=> Addon Manager: Fix GUI tests on macOS

src/Mod/Material/MaterialEditor.py, src/Mod/Material/StandardMaterial/TEMPLATE.FCMat, src/Mod/Material/Templatematerial.yml, src/Mod/Material/materialtools/cardutils.py
- for electromagnetics we have vector fields and thus need to specify components
- as first step use the new material "Magnetization"
- also get rid of annoying debug messages output on normal use in the material dialog
=> [Material] allow to use vectorial properties

src/Mod/Fem/femsolver/elmer/equations/magnetodynamic2D_writer.py, src/Mod/Fem/femsolver/elmer/writer.py
- take magnetization into account for the magnetodynamic2D equation
=> [FEM] Elmer: magneto 2D use magnetization

src/Gui/DlgUnitsCalculatorImp.cpp, src/Mod/Fem/CMakeLists.txt, src/Mod/Fem/Gui/CMakeLists.txt, src/Mod/Fem/Gui/Command.cpp, src/Mod/Fem/Gui/Resources/Fem.qrc, src/Mod/Fem/Gui/Resources/icons/FEM_ConstraintMagnetization.svg, src/Mod/Fem/Gui/Resources/ui/Magnetization.ui, src/Mod/Fem/Gui/Workbench.cpp, src/Mod/Fem/ObjectsFem.py, src/Mod/Fem/femcommands/commands.py, src/Mod/Fem/femobjects/constraint_magnetization.py, src/Mod/Fem/femtaskpanels/task_constraint_magnetization.py, src/Mod/Fem/femtest/app/test_object.py, src/Mod/Fem/femtest/app/test_open.py, src/Mod/Fem/femtest/gui/test_open.py, src/Mod/Fem/femviewprovider/view_constraint_magnetization.py
- needed for electromagnetic simulations
=> [FEM] add new constraint for magnetization 

src/Mod/Path/Path/Post/UtilsParse.py
This is one in a series of PR's where I am taking code from at least 4 postprocessor files partially written by different people, combining them into three files, then trying to make the code more consistent and simpler.  The long term goal is to enable much simpler postprocessor files with much less copied code in each postprocessor file and much more "shared" code in the three Utils*.py files.
In this PR I replace the "add_parameters" routine by an array of individual functions (one for each parameter letter) and a simple piece of code that calls the appropriate parameter processing functions in the specified parameter order.  Some of the parameter letters can share the same parameter processing function in the default configuration.
This not only …
=> Path:  Refactored the add_parameters function into individual functions.

src/Mod/Fem/femsolver/elmer/equations/magnetodynamic2D_writer.py, src/Mod/Fem/femsolver/elmer/writer.py
- assure a 2D coordinate system is used
- get rid of annoying numerical artifacts
=> [FEM] Elmer: fixes for Magneto2D writer

src/3rdParty/salomesmesh/inc/SMDS_StdIterator.hxx
=> smesh: std::iterator<> is deprecated in C++17

src/Mod/Spreadsheet/Gui/SheetTableViewAccessibleInterface.cpp, src/Mod/Spreadsheet/Gui/SheetTableViewAccessibleInterface.h
=> Spreadsheet: fix some warnings and issues reported by GH actions

src/Mod/AddonManager/package_details.py
Partially addresses #8361 by ensuring that when an external link is followed, the internal page gets reloaded instead of showing an error page. Still to-do to fully resolve that issue is to add back, forward, and reload buttons.
---
=> Addon Manager: Reload page when following links

src/App/Metadata.cpp, src/App/Metadata.h, src/App/MetadataPy.xml, src/App/MetadataPyImp.cpp, tests/src/App/CMakeLists.txt, tests/src/App/Metadata.cpp
To be used in some forthcoming changes to the Addon Manager. This PR is divided into three commits:
1. The basic modification to the code
2. Some reformatting and clang-tidy work
3. Unit tests (some for practice, and one to exercise the new code)
---
=> App: Add support for in-memory Metadata creation

src/Mod/Fem/App/AppFemPy.cpp
=> FEM: raise an exception if no valid object is selected

src/Mod/AddonManager/AddonManagerTest/app/mocks.py, src/Mod/AddonManager/AddonManagerTest/gui/gui_mocks.py
Isolating these to a single PR since they don't touch anything else. They will be used in a set of upcoming test code.
---
=> Addon Manager: Add more unit test mocks

src/Mod/Fem/Gui/Resources/ui/ElectrostaticPotential.ui, src/Mod/Fem/femtaskpanels/task_constraint_electrostaticpotential.py
=> [FEM] fix bug in potential constraint task panel

src/Mod/TechDraw/App/DrawViewBalloon.cpp, src/Mod/TechDraw/App/DrawViewBalloon.h, src/Mod/TechDraw/App/Preferences.cpp, src/Mod/TechDraw/App/Preferences.h, src/Mod/TechDraw/Gui/DimensionValidators.cpp
This PR fixes a problem where hybrid dimensions (vertex and edge) were wrongly identified as invalid.
---
=> [TD]Fix dimension validator

src/App/Metadata.cpp
=> App: Fix warnings -Wignored-qualifiers

src/Mod/Draft/draftobjects/array.py
PR to fix a regression introduces with #8433.
---
=> [Draft] fix #8433 regression

src/Mod/TechDraw/Gui/QGIFace.cpp, src/Mod/TechDraw/Gui/QGIFace.h
This PR corrects an issue reported here: https://forum.freecad.org/viewtopic.php?t=76032
---
=> [TD]fix face hatch location in Svg export

src/App/PropertyStandard.cpp, src/Gui/propertyeditor/PropertyItem.cpp
Could have been solved by increasing decimal count to arbitrary number, but I thought it's better to add support for tuple of integers, so does this PR.
=> [Core] Add possibility to set color with tuple of integers, fixes #8344

src/Mod/Part/App/Geometry.cpp, src/Mod/Part/App/Geometry.h
See forum: https://forum.freecad.org/viewtopic.php?t=75846
---
=> Part: fixes to create a NURBS for the arc of a conic

src/App/FeaturePython.cpp, src/App/FeaturePython.h
=> App: support of method unsetupObject in Python feature classes

src/Mod/Fem/Gui/TaskPostBoxes.cpp
- also sorting to keep the overview
=> [FEM] register new result values to DataAtPoint filter

src/Mod/Arch/ArchSite.py
PR to fix several Arch_Site issues:
* A site's 3D representation would show 'ghosts' of the objects in its Group if Terrain was None.
* Wrong calculation of Perimeter.
* 3D Transformations were not correct if a site did not have a default position.
Forum topics:
https://forum.freecad.org/viewtopic.php?t=75658
https://forum.freecad.org/viewtopic.php?t=75883
---
=> [Arch] fix Arch_Site

src/Mod/Fem/femsolver/elmer/equations/magnetodynamic.py, src/Mod/Fem/femsolver/elmer/equations/magnetodynamic2D_writer.py, src/Mod/Fem/femsolver/elmer/equations/magnetodynamic_writer.py, src/Mod/Fem/femsolver/elmer/writer.py
=> FEM: fix trailing newlines

src/Mod/Fem/App/FemPostFilter.cpp, src/Mod/Fem/App/FemPostFilter.h, src/Mod/Fem/Gui/TaskPostBoxes.cpp, src/Mod/Fem/Gui/TaskPostBoxes.h, src/Mod/Fem/Gui/ViewProviderFemPostFilter.cpp, src/Mod/Fem/Gui/ViewProviderFemPostFilter.h
- sort the functions alphabetically to know where to scroll to - eases the reading at least a bit
- some automatic reformatting according to our current clang file
- split too long lines
=> [FEM] sort code of result filters

src/Mod/TechDraw/CMakeLists.txt, src/Mod/TechDraw/Gui/Resources/TechDraw.qrc, src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_HoleShaftFit.svg, src/Mod/TechDraw/Gui/TaskHoleShaftFit.ui, src/Mod/TechDraw/Gui/Workbench.cpp, src/Mod/TechDraw/TechDrawTools/CommandHoleShaftFit.py, src/Mod/TechDraw/TechDrawTools/TaskHoleShaftFit.py, src/Mod/TechDraw/TechDrawTools/__init__.py
New command creating hole /shaft fit using ISO 286 in TechDraw. This command does the same as the macro HoleShaftFitISO286.FCMacro which was presented in https://forum.freecad.org/viewtopic.php?t=71650&sid=9a92a404afff23b0c9a45d9974f6c6f4
Wiki will be updated in the next days. …
=> [TD] Add CommandHoleShaftFit a new command creating hole / shaft fit using ISO 286

src/Gui/DlgAddProperty.cpp
=> [Gui] Sort Add Property types list

src/Mod/AddonManager/AddonManagerTest/app/mocks.py, src/Mod/AddonManager/AddonManagerTest/app/test_addon.py, src/Mod/AddonManager/AddonManagerTest/app/test_macro_parser.py, src/Mod/AddonManager/AddonManagerTest/data/DoNothing.FCMacro, src/Mod/AddonManager/CMakeLists.txt, src/Mod/AddonManager/addonmanager_macro.py, src/Mod/AddonManager/addonmanager_macro_parser.py
Extract macro parsing code into its own class.
---
=> Addon Manager: Refactor Macro parser

src/Mod/Part/App/Geometry.cpp, src/Mod/Part/TestPartApp.py
=> Fix circle or ellipse to nurbs

src/Mod/Fem/App/FemPostFilter.cpp
Fix trailing whitespace in `Fem/App/FemPostFilter.cpp`
---
=> FEM: fix trailing whitespace

src/Mod/Fem/App/FemPostFilter.cpp, src/Mod/Fem/App/FemPostObject.cpp, src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp, src/Mod/Fem/Gui/ViewProviderFemPostPipeline.cpp
- check if datasets exists before we access them
- speed up the check for the datatype by testing after the downcast
=> [FEM] improve checks for datasets

src/Mod/Fem/Gui/TaskPostContours.ui, src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- otherwise the contour creating algorithm would be invoked on every keystroke
- also improve a code comment
=> [FEM] Contours: disable keyboard tracking

src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
=> Fem: fixes #8485: transparency of pipeline objects is visually lost

src/Gui/MainWindow.cpp
=> Gui: [skip ci] set object name to tabbar of MDI area

src/Gui/Action.cpp
=> Gui: fix removing item from recent files list

src/Mod/Arch/ArchComponent.py
The code to rotate the children of Components did not work if the rotation axis was parallel to Z.
---
=> [Arch] children of Component did not rotate with Host

.clang-format
Not sure how we all missed this one!
---
=> Enable comment reflow in clang-format

src/Mod/Arch/ArchStairs.py
=> [Arch] Allow Arch_stairs with 2 steps

.github/workflows/actions/linux/build/action.yml, .github/workflows/actions/linux/configure/action.yml, .github/workflows/actions/runTests/action.yml, .github/workflows/sub_buildUbuntu2004.yml, .github/workflows/sub_buildUbuntu2204.yml, .github/workflows/sub_lint.yml, .github/workflows/sub_prepare.yml
This PR offers a new bunch of improvements to CI:
* Customized timeouts for tests so if goes stuck, we don't have to wait for 6h to have the fail report
* Improve reporting in configure and build steps by providing (only) useful information for 1st level analysis
* Use 'continue-on-error' for silent failing of steps, so they will still be easy to catch through notifications and step exit codes
* Upload crash dumps in artifacts in case there was a core dump
* Improve test reporting by providing:
* A summary of failed tests
* A summary of tracebacks that appeared out of failing tests
=> CI: various improvements

src/Mod/Draft/importDXF.py, src/Mod/Path/libarea/Adaptive.cpp
=> Fix source comment and documentation typos

rpkg.macros
=> [COPR] tighten grep to avoid catching some random stuff

src/App/License.h, src/App/Metadata.cpp, src/App/Origin.cpp, src/App/PreCompiled.h
- also remove a superfluous private: statement
- also remove an unnecessary include
=> [App] sort includes in PreCompiled.h

src/Gui/NotificationBox.cpp
- #include "PreCompiled.h" is missing, see https://github.com/FreeCAD/FreeCAD/pull/8536#issuecomment-1435782841
=> [Gui] second hotfix for NotificationBox.cpp

src/Mod/Fem/femexamples/equation_electrostatics_capacitance_two_balls.py, src/Mod/Fem/femexamples/equation_electrostatics_electricforce_elmer_nongui6.py
- active already the analysis
- generate the mesh preferably directly, also if this fails, load the rough meshes
- use value for Air is they are in our Air material card
- apply material to the body (not necessary but good practice, the examples are there to teach people and for more complex models setting the material to a body is important)
=> [FEM] update Elmer examples

src/Mod/Material/MaterialEditor.py
- fixes bug number 7 of this list: https://forum.freecad.org/viewtopic.php?style=5&p=489666#p489666
- also fix too short variable name warning
=> [Material] fix card selection bug

src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- only filter when necessary
- avoid unnecessary function calls
- fix bug that objects were not made visible but invisible
=> [FEM] improve pvtu file filtering

src/Mod/Idf/Idf.py, src/Mod/Import/App/StepShape.h, src/Mod/Import/App/StepShapePy.xml, src/Mod/Import/App/dxf/ImpExpDxf.cpp, src/Mod/Import/App/dxf/dxf.cpp, src/Tools/embedded/Qt/cxx/plugin.cpp
Fix various trailing whitespace issues and typos
---
=> Fix various trailing whitespace issues and typos

tests/CMakeLists.txt
=> CMake: fix linking error in test function when linking Python statically

src/App/License.h
- as discussed here: https://forum.freecad.org/viewtopic.php?t=76184
=> [App] License.h: fix compiler warning

src/Mod/Fem/Gui/Command.cpp
- to be uniform as all other commands begin with "CmdFem..."
=> [FEM] fix typo in command

src/Mod/AddonManager/TestAddonManagerApp.py, src/Mod/AddonManager/TestAddonManagerGui.py, src/Mod/AddonManager/addonmanager_freecad_interface.py, src/Mod/AddonManager/loading.html, src/Mod/AddonManager/package_details.py, src/Mod/AddonManager/package_list.py
This PR collects a number of minor linter fixes and cleanup of some non-breaking issues.
---
=> Addon Manager: Small fixes for linter issues

cMake/FreeCAD_Helpers/PrintFinalReport.cmake, cMake/FreeCAD_Helpers/SetupLibFmt.cmake
Manually call find_package(fmt) before attempting to download the sources.
---
=> cMake: Add manual find_package() for fmt

src/Mod/AddonManager/addonmanager_dependency_installer.py, src/Mod/AddonManager/addonmanager_devmode.py, src/Mod/AddonManager/addonmanager_devmode_add_content.py, src/Mod/AddonManager/addonmanager_devmode_license_selector.py, src/Mod/AddonManager/addonmanager_devmode_licenses_table.py, src/Mod/AddonManager/addonmanager_devmode_metadata_checker.py, src/Mod/AddonManager/addonmanager_devmode_person_editor.py, src/Mod/AddonManager/addonmanager_devmode_predictor.py, src/Mod/AddonManager/addonmanager_devmode_validators.py, src/Mod/AddonManager/addonmanager_git.py, src/Mod/AddonManager/addonmanager_utilities.py
Cleanup issues identified by pylint in the DevMode functions.
---
=> Addon Manager: pylint cleanup of devmode

src/Mod/AddonManager/addonmanager_installer.py, src/Mod/AddonManager/addonmanager_installer_gui.py, src/Mod/AddonManager/addonmanager_utilities.py
The dependency installer doesn't shut down correctly, this fixes it.
---
=> Addon Manager: Fix bug in dependency installer

src/Mod/OpenSCAD/OpenSCADCommands.py
=> OpenSCAD: Correct QFileDialog usage

src/Mod/OpenSCAD/OpenSCADCommands.py
Also renames the clear button for clarity. Fixes #8576.
---
=> OpenSCAD: Make clearing field undoable

src/Mod/Part/Gui/DlgPrimitives.cpp
See discussion https://forum.freecad.org/viewtopic.php?t=76218
---
=> [Part] Fix Geometric Primitives task panel bug

src/Mod/Part/Gui/SectionCutting.ui
=> Part: don't restrict width of group boxes in section cutting dialog

src/Mod/Fem/femtaskpanels/task_material_common.py
- for some materials, just opening the material dialog and pressing OK to close it without any change resulted in a transient material
- for other materials this happened by clicking in the material dialog on a value to edit it, but not changing anything and press OK
=> [FEM] fix annoying material selection bug

src/Mod/Fem/femexamples/equation_magnetodynamics_2D_elmer.py
- thanks to the forum: https://forum.freecad.org/viewtopic.php?p=662830#p662830
=> [FEM] simplify Magnetodynamics 2D example

src/Mod/Fem/femtaskpanels/task_material_common.py
=> [FEM] [skip ci] fix typos

src/Gui/NotificationBox.cpp
=> Gui: Fix use of undocumented init() function

src/Base/Quantity.cpp, src/Base/Quantity.h, src/Mod/Part/Gui/DlgPrimitives.cpp, src/Mod/PartDesign/Gui/TaskPrimitiveParameters.cpp
Following PR #7219
[Bugfix] : fixes bug declared here : https://forum.freecadweb.org/viewtopic.php?f=3&t=73321
=> Part: better quantity values handling for primitives

src/Gui/TaskView/TaskDialogPython.cpp, src/Gui/TaskView/TaskDialogPython.h, src/Gui/UiLoader.cpp, src/Gui/UiLoader.h
---
This allows to handle language changes in a task panel:
```
from PySide import QtCore
from PySide import QtWidgets
class TaskDialog:
def __init__(self):
self.form = QtWidgets.QCalendarWidget()
def changeEvent(self, event): …
```
=> Language change

src/Mod/OpenSCAD/OpenSCADCommands.py
=> OpenSCAD: Support CSG loads from Load button

src/Mod/OpenSCAD/OpenSCADCommands.py
=> OpenSCAD: Translate file dialogs

src/Mod/Sketcher/Gui/Utils.cpp
=> [BugFix] Sketcher: correctly handles angle strings displayed at cursor for all locales

src/Mod/Part/Gui/DlgPrimitives.cpp
The values aren't transferred into the command line
=> [BugFix] Part: fix XSkew+YSkew editing not took into account for cylinders

src/Mod/Arch/ArchStairs.py
=> [Arch] Arch_Stairs TreadDepth was based on unprojected edge

src/Gui/TaskView/TaskDialogPython.cpp, src/Gui/TaskView/TaskDialogPython.h
=> PD: refactor the constructor of TaskDialogPython

src/Mod/Fem/femexamples/equation_electrostatics_capacitance_two_balls.py, src/Mod/Fem/femexamples/equation_electrostatics_electricforce_elmer_nongui6.py
- define Air so that it is recognized by material handling as existing card
=> [FEM] fix for electrostatics examples

src/Mod/OpenSCAD/OpenSCADUtils.py, src/Mod/OpenSCAD/importCSG.py
=> OpenSCAD: Remove old workaround code

src/Gui/DlgSettingsNavigation.cpp, src/Gui/NaviCube.cpp, src/Gui/NaviCube.h, src/Gui/View3DInventor.cpp
more minimallistic alternative to #8567
=> Fix NaviCube default font incorrect display in pref. page

tests/src/Base/CMakeLists.txt, tests/src/Base/Units.cpp
=> Tests: add tests for quantities

src/Mod/Arch/ArchStairs.py
=> [Arch] fix Arch_Stairs stringer code

src/Mod/AddonManager/addonmanager_utilities.py
=> Addon Manager: Linter cleanup of utilities

.github/workflows/sub_lint.yml
@chennes This should (theoretically) solve the issues you found here : https://github.com/FreeCAD/FreeCAD/pull/8584#issuecomment-1443857061
I will let the checks of this PR run to check nothing wrong happen, then merge, and finally re-run the test on the commented PR. Hopefully it will take into account the new CI and we'll see
=> CI: Install dependencies + run Cmake before Cpp lints (needed for Clang tools)

tests/src/Base/Units.cpp
=> Tests: fix linking error on Windows

src/Gui/NaviCube.cpp, src/Gui/NaviCube.h, src/Gui/View3DInventor.cpp
- add missing routines to save default values
- also fix color read in (transparency was read in wrong order)
=> [Gui] fixes for NaviCube parameters

src/Mod/Sketcher/Gui/SketcherSettingsDisplay.ui
- compiler stumbles over inexisting tabstop target the fix was automatically done Qt Designer
---
=> [Sketch] [skip ci] fix UI file

tests/src/Base/CMakeLists.txt, tests/src/Base/Matrix.cpp, tests/src/Base/Rotation.cpp
=> Tests: add unit tests for Matrix4D and Rotation

src/App/CMakeLists.txt, src/App/ExpressionTokenizer.cpp, src/App/ExpressionTokenizer.h, src/Gui/ExpressionCompleter.cpp, src/Gui/ExpressionCompleter.h, tests/src/App/CMakeLists.txt, tests/src/App/Expression.cpp
=> Refactor expression completer

src/Mod/Import/App/AppImportPy.cpp, src/Mod/Import/Init.py, src/Mod/Import/InitGui.py
=> Import: support to export to glTF file in headless mode

src/Tools/plugins/widget/customwidgets.cpp, src/Tools/plugins/widget/customwidgets.h
- at the moment it is not possible to set the property "allowTransparency" in Qt Designer
=> [Widgets] register transparency property of Gui::ColorButton

src/App/Color.cpp, src/Gui/NaviCube.cpp, src/Gui/View3DInventor.cpp, src/Mod/Import/App/AppImportPy.cpp, src/Mod/Import/Gui/AppImportGuiPy.cpp, tests/src/Base/Units.cpp
=> Misc issues

src/App/FreeCADInit.py, src/App/PropertyUnits.cpp, src/App/PropertyUnits.h, src/Base/Unit.cpp, src/Base/Unit.h, src/Base/UnitsSchemaInternal.cpp, src/Base/UnitsSchemaMKS.cpp, src/Gui/DlgUnitsCalculatorImp.cpp
This adds handling for some unusual units which are used in the CfdOF workbench, to prevent them being displayed in unconventional units or with strange scalings, e.g. mm^2/s^3 for the turbulent dissipation rate. This is just a straightforward extension of what is done for other units in the schemas.
Forum discussion: https://forum.freecadweb.org/viewtopic.php?f=37&t=21576&p=585747&sid=2117aa796c409dd139b76e26ad8a0712#p584248 and posts following.
---
=> Base: Add handling of additional units used in CfdOF workbench

src/Gui/View3DInventor.cpp, src/Gui/View3DSettings.cpp, src/Gui/View3DSettings.h
=> Gui: add function View3DSettings::stopAnimatingIfDeactivated()

src/App/PropertyUnits.cpp, src/Base/Unit.cpp
- fixes compilation because declared in header but no code
- also sort the properties to keep the overview
=> [Core] add missing velocity property

src/App/PropertyUnits.cpp, src/App/PropertyUnits.h
=> [App] sort properties
