- src/Mod/Fem/femtools/tokrules.py
- it is common to use equations like "x^2" but one currently get only an error
- this PR fixes this by adding parsing support for the '^' character as power function
This way is it now also possible to calculate a root by e.g. "x^(0.5).
> [FEM] add missing parser handling of '^' character

- src/Mod/Fem/femtools/tokrules.py
- fixes an annoying warning (that is output as error) about unused COMMENT
To reproduce:
- open a result object of a FEM analysis
- in the appearing dialog do nothing else than to press the button "Calculate"
result:
```
23:03:10  WARNING: Token 'COMMENT' defined, but not used
23:03:10  WARNING: There is 1 unused token
```
The warning is output in red and has error level (FC's report panel shows up) and is therefore annoying.
The PR fixes this according to https://www.dabeaz.com/ply/ply.html#ply_nn8 and https://groups.google.com/g/ply-hack/c/g0aPM7pEFoo
> [FEM] fix wrong error message about comments

- src/Mod/TechDraw/Gui/CommandCreateDims.cpp
- src/Mod/TechDraw/Gui/TaskCosVertex.cpp
This PR addresses an issue where the program attempts to dimension an edge for which radius/diameter can not be determined.
---
> [TD]Fix abort on bad edge

- src/Gui/NaviCube.cpp
When the NaviCube is relatively small, it looks clumsy on some screens. This PR tries to improve that.
Anybody, please test this PR and report back if this improves the rendering for you or not.
QOpenGLTexture::Nearest (master):
QOpenGLTexture::Linear:
QOpenGLTexture::LinearMipMapLinear (this PR):
The PR is the work of user asegura : https://forum.freecadweb.org/viewtopic.php?p=599543#p599543
> [Gui] attempt to improve NaviCube rendering

- src/Mod/Fem/femtaskpanels/task_result_mechanical.py
Relates to #6959 
An side advantage of using Tool flag is that dialog opens as a pure child of FC, without adding a tab in the OS task bar.
> [FEM] Implement a better dialog layout management for histogram

- src/Mod/Fem/Gui/TaskPostBoxes.cpp
the plot one can create from within the linear filter is at the moment detached from FreeCAD's main window.
This PR fixes it the same way as in https://github.com/FreeCAD/FreeCAD/commit/920e8e046
> [FEM] fix linear filter plot

- src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
- src/Mod/TechDraw/Gui/Resources/icons/MRTE/bgColor.svg
- src/Mod/TechDraw/Gui/Resources/icons/MRTE/fgColor.svg
- src/Mod/TechDraw/Gui/Resources/icons/MRTE/indentLess.svg
- src/Mod/TechDraw/Gui/Resources/icons/MRTE/indentMore.svg
- src/Mod/TechDraw/Gui/Resources/icons/MRTE/listBullet.svg
- src/Mod/TechDraw/Gui/Resources/icons/MRTE/menu.svg
- src/Mod/TechDraw/Gui/Resources/icons/MRTE/textBold.svg
- src/Mod/TechDraw/Gui/Resources/icons/MRTE/textItalic.svg
- src/Mod/TechDraw/Gui/Resources/icons/MRTE/textStrike.svg
- src/Mod/TechDraw/Gui/Resources/icons/MRTE/textUnderline.svg
The grey background on icons in the Rich Text Editor are difficult to read if a dark scheme is used.   See #6988 for details. 
---
> [TD]fix icons for dark schemes #6988

- src/Gui/Tree.cpp
If select non-Latin Language (Cyrillic, Hieroglyphics, etc)
run command "Create group" created _____ group name in Tree View
https://forum.freecadweb.org/viewtopic.php?f=8&t=69278
> Fix for non-Latin Group name in Tree View

- src/Mod/Arch/ArchSectionPlane.py
The code for ArchSectionPlane did not check the SymbolPlan property of windows and doors. This this meant that plan symbols always were included.
---
> Arch: ArchSectionPlane always showed plan symbols of windows

- src/App/PropertyExpressionEngine.h
Just like Apple, FreeBSD uses clang as it's main compiler, and thus
runs afoul of the same problem in src/App/PropertyExpressionEngine.cpp
like Apple (issue #5281): "error: no viable overloaded '='".
Extend the fix from #5281 for the BSDs (check macro FC_OS_BSD) -
at least OpenBSD uses clang, too (maybe this check should be reworked
to test for clang, but I can't test on Apple, so let's keep this fix
minimalistic).
References: #5281
And …
> fix Expressions assignment for FreeBSD

- src/Gui/Application.cpp
- src/Gui/SoFCOffscreenRenderer.cpp
- src/Gui/SoFCOffscreenRenderer.h
- src/Tools/make_snapshot.py
> Offscreen rendering

- src/Base/Interpreter.cpp
- src/Base/Interpreter.h
- src/Base/swigpyrun.inl
With this function is posible to get the Python types for SWIG interfaces.
Usage example with `PyArg_ParseTuple`:
```
...
PyObject* obj;
PyTypeObject* type = Base::Interpreter().getSWIGPointerTypeObj("pivy.coin","_p_SoNode");
if (!PyArg_ParseTuple(args, "O!", type, &obj)) {
...
``` 
**Note**: If you don't have wiki access, then please …
> Base: Add function to get Python object types for SWIG interfaces

- .clang-format
Recreating PR #6783 for clang support so the source branch is clangformat rather than master. Apologies for any inconvenience caused.
> created clang-format

- src/Gui/GestureNavigationStyle.cpp
Regression introduced by commit c23a30b
Diff of commit that introduced regression : https://github.com/FreeCAD/FreeCAD/commit/c23a30b91628c8f940f0262492b68bde34a3eb98#diff-76b2d842b8ac050b741529e577356508cb9f8a4af6bb423fa8edc57e9e24fc28
Forum report : https://forum.freecadweb.org/viewtopic.php?f=12&t=69653 (basically Gesture navigation mode is broken)
> [BUGFIX] Gui: fix mouse Gesture navigation mode

- src/Mod/Sketcher/App/Constraint.cpp
- src/Mod/Sketcher/App/Constraint.h
It does not add visible functionality to FC. It enables the Sketcher Constraints to provide a type string. This string matches the type name used for Python. Thought it can have a more general use, it is a prerequisite for the next PR.
> Sketcher: Constraints - add ability to generate constraint type string

- src/Mod/Path/PathScripts/PathGuiInit.py
The camotics python module is provided when the camotics application is installed.  This is not a dependency for FreeCAD, just another applicaiton that the user can install. If it's installed (and recent enough), Path can use it for simulation.
There was already a test in place when the Path workbench loaded which determined whether to enable the button.  But the camotics gui was being imported anyway and was, in turn, trying to import the python module.  this would throw an error.
Commit wraps the import in another test to avoid the error. …
> [Path] Fix import error if camotics not installed.

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
This commit does not provide visible improvements. It provides the ability to generate a programmatic cursor movement and/or preselection. It is intended to be used by other future PRs.
> ViewProviderSketch: Cursor movement and preselection at sketch coordinates

- src/Mod/Fem/femsolver/elmer/writer.py
FEM WB: error "Requested property: [Viscosity], not found" if used mixed solid and fluid simulation in Elmer is fixed.
When project uses thermal-flow simulation for solid and fluid together then Navier-Stokes equation is applied both for solid and fluid. But solid has not "Viscosity" property so Elmer prints warnings and calculation has very long time or may not converged.
This fix disables Stokes-Navier equation for Solid objects.
> FEM WB Elmer viscosity bug fix.

- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/Sketch.h
- src/Mod/Sketcher/App/SketchObject.h
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
This is useful since splines can get very long.
Not yet complete. Next steps include:
1. ~This currently doesn't work well with periodic B-splines.~ This is potentially fixed now. Could use more testing.
2. There should be options for both moving the entire B-spline or just one piece.
> [Sketcher] Only move one piece of B-spline when dragging

- src/Base/Tools2D.h
Base:Fix a vector2d Rotate function bug which use the intermediate result(x) as the basis for the next calculation(y).
> Vector2d:fix rotate bug

- lgtm.yml
Per https://lgtm.com/projects/g/FreeCAD/FreeCAD  
[skip ci]
> LGTM: omit src/Tools/wiki2qhelp.py from analysis

- src/Mod/Arch/ArchWall.py
- just to please the spellchecker CI, see https://github.com/FreeCAD/FreeCAD/runs/7118611287?check_suite_focus=true
> [Arch] fix typo in function name

- src/Mod/Arch/ArchWindowPresets.py
The opening symbol of the "Simple door" preset was incorrect. See image.
---
> Arch: Invert opening symbol Simple door

- src/Mod/Draft/draftguitools/gui_snapper.py
This PR fixes the inaccuracy of [Draft Snap Near](https://wiki.freecadweb.org/Draft_Snap_Near).
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=67289
Issue:
https://github.com/FreeCAD/FreeCAD/issues/6613
Additionally:
* Snap Perpendicular now also works for faces.
* Snap Perpendicular can now find multiple points. For example two points on a circular edge.
* For clarity the `snapToFace` function was renamed to `snapToCenterFace`.
* To snap to a vertex (f.e. a [Draft Point](https://wiki.freecadweb.org/Draft_Point)) Snap Endpoint must now be used. This makes more sense IMO and is also consistent with snapping to points in a point cloud.
---
> Draft: Fix near snap (issue #6613)

- src/Mod/Draft/Resources/ui/preferences-draftinterface.ui
The DisplayStatusbarScaleWidget checkbox should be checked in preferences-draftinterface.ui
The default elsewhere is True:
https://github.com/FreeCAD/FreeCAD/blob/05c250d7b5c7d67d4fd59a8b9a4160e00fc10521/src/Mod/Draft/draftutils/init_draft_statusbar.py#L341
---
> Draft: DisplayStatusbarScaleWidget should be checked in preferences-draftinterface.ui

- src/Mod/Sketcher/App/Sketch.cpp
Here, "small" means that the number of poles of the spline is so low that moving
any piece of the curve without changing shape would require moving all the
poles. In that case the rest of the algorithm in `initBSplinePieceMove()` only
complicates the matter.
Issue reported [here](https://github.com/FreeCAD/FreeCAD/pull/7110#issuecomment-1176059645).
> [Sketcher] Do regular drag for small B-splines

- src/Mod/Fem/Gui/DlgSettingsFemCcx.ui
- src/Mod/Fem/Gui/DlgSettingsFemCcxImp.cpp
- in the preferences one could specify more CPU cores than available
- also correct a label sine the number of cores is since FC 0.20 used for all CCX solver runs
- also remove unnecessary (doubled) slots from the UI file
> [FEM] fix CCX multi-threading bug

- src/Mod/Fem/femsolver/elmer/tasks.py
- src/Mod/Fem/femsolver/elmer/writer.py
- src/Mod/Fem/femsolver/z88/tasks.py
- src/Mod/Fem/femtools/femutils.py
- for Elmer and Z88 on Windows several window popup. This is maybe annoying and the user is wondering what is going on, but the main problem is that when you close them you break the solving process.
Therefore, on Windows only, hide the empty popup windows
> [FEM] fix solver console bugs

- src/Mod/Arch/importIFCmulticore.py
- src/Mod/Fem/femsolver/elmer/sifio.py
iterator.next() is deprecated in python3.
next(iterator) is the direct replacement.
A for() loop made more sense for import IFCmulticore.py where we were looping through the whole list anyway
---
> Mod: Replaced python2 usage of next()

- src/Mod/Path/PathScripts/PathArray.py
This regression was introduced in PR #4818 with the refactor.  The source of the regression is that the `rotatePath()` method was not included in the new `PathArray` class created in the refactor.
This commit relocates the missing method to the `PathArray` class where it belongs, and corrects the `path` argument where the method is called.
This PR is a great candidate for backporting to 0.20.x.
Error identified in forum at [bug of array of polar](https://forum.freecadweb.org/viewtopic.php?f=15&t=70032).
Source file in ZIP archive:
[PartDesignExample_PathArray_Fix.zip](https://github.com/FreeCAD/FreeCAD/files/9048540/PartDesignExample_PathArray_Fix.zip)
Change Type of Array object to Polar, and Copies to > 0, and Angle to other than 0.
Current master will throw error.  PR code will fix …
> Path: Fix Type=Polar regression in PathArray

- src/Mod/Draft/draftviewproviders/view_facebinder.py
- src/Mod/Draft/draftviewproviders/view_hatch.py
- src/Mod/Draft/draftviewproviders/view_shapestring.py
EditMode was not handled properly for hatch, facebinder and shapestring objects.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=8&t=70050
---
> Draft: Fix EditMode for hatch, facebinder and shapestring

- src/Gui/DlgSettingsViewColor.cpp
- src/Gui/DlgSettingsViewColor.h
- src/Gui/DlgSettingsViewColor.ui
- when finding a suitable background color gradient, it is annoying that there is no button to switch the begin/end color of the gradient. With the button one can quickly see the the changes and find a suitable gradient much quicker
This PR adds this button:
> [Gui] preferences: add button to switch gradient colors

- src/Gui/DlgPreferencesImp.cpp
- src/Mod/Part/Gui/AppPartGui.cpp
- users are confused that we have a preferences page named "Part design" that also defines things for the Part WB. The Wiki is clear that the preferences page is for both, Part and PD, however the UI is not.
This PR makes this clear.
Even experienced users stumble over this, see for example: https://github.com/FreeCAD/FreeCAD/pull/7148#issuecomment-1179571003
With the PR it should be clear.
> [Gui] preferences: clarify Part/PD page

- src/Mod/Arch/ArchCommands.py
Deriving the `u` vector from vertices does not work if the face is circular. Using points based on the parameter range instead.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=70320
---
> Arch: Fix getCutVolume in ArchCommands.py

- src/Mod/Draft/draftmake/make_point.py
The code relied on the `import DraftGui` statement at the top of the file in the previous version of view_facebinder.py. See https://github.com/FreeCAD/FreeCAD/pull/7174.
In the new situation `draftToolBar` can be missing and `color` can stay `None`.
Additionally:
* The section marked as `# TODO: Check if this is a repetition:` was indeed a repetition and was removed.
* There is no need for `obj.ViewObject.Visibility = True`.
---
> Draft: Fix color handling in make_point.py

- src/Mod/Draft/draftguitools/gui_hatch.py
Call to `resetEdit` was missing from `gui_hatch.py`.
---
> Draft: Add resetEdit to gui_hatch.py

- src/Mod/Draft/draftviewproviders/view_text.py
The `setEdit` function should import the `Draft` module to make sure the `draftToolBar` is available. Without this there is an error if a text is double-clicked and the Draft Workbench has not yet been loaded.
---
> Draft: Fix setEdit in view_text.py

- src/Mod/PartDesign/App/FeatureExtrude.cpp
- src/Mod/PartDesign/Gui/TaskPadParameters.cpp
- src/Mod/PartDesign/Gui/TaskPocketParameters.cpp
properly fix issue reported here: https://forum.freecadweb.org/viewtopic.php?f=3&t=70266
also reverted a previous commit that auto unchecked the midplane option in the task panel since it is now unnecessary with the fix and may result annoying if you want to go back to length mode expecting it to remain checked, also it is inconsistent since it only gets unchecked for two lengths but not the other modes were it is not a valid option either. IMO this was more a workaround than an actual fix for the bug as it could still be encountered through the property view or in old files.
This should be backported to 0.20 branch also
> [PD Pad/Pocket] Fix bug with midplane usage in TwoLengths mode

- src/Mod/Draft/Resources/ui/preferences-draftinterface.ui
- src/Mod/Draft/draftutils/init_draft_statusbar.py
This PR removes the `DisplayStatusbar` preference. This preference was not implemented properly. The checkbox in the preferences did not work. And having a Boole preference to override two other Boole preferences is unnecessary IMO.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=60400
Additionally:
* Minor code cleanup related to:
* `mw = Gui.getMainWindow()` will never return `None`. If the Gui is up the MainWindow is available
* `sb = mw.statusBar()` will never return `None`. It will create the statusbar if it is missing.
* Minor improvement of the `show_draft_statusbar` function. Changes to the `DisplayStatusbarScaleWidget` or the `DisplayStatusbarSnapWidget` preference now only require a workbench switch (f.e. Draft->Part->Draft) instead of a restart.
---
> Draft: Remove unnecessary DisplayStatusbar preference

- src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostObject.h
- fixes issue #7230
- to update the color bar for post objects, the Field property has to be reset to trigger this. This PR does this.
The PR fixes the bug properly:
but maybe there is another way that the update of the view trigger then colorbar update automatically.
> [Gui] fix missing colorbar update for FemPostObject

- src/Gui/Stylesheets/Behave-dark.qss
- src/Gui/Stylesheets/Dark-blue.qss
- src/Gui/Stylesheets/Dark-contrast.qss
- src/Gui/Stylesheets/Dark-green.qss
- src/Gui/Stylesheets/Dark-orange.qss
- src/Gui/Stylesheets/Darker-blue.qss
- src/Gui/Stylesheets/Darker-green.qss
- src/Gui/Stylesheets/Darker-orange.qss
- src/Gui/Stylesheets/Light-blue.qss
- src/Gui/Stylesheets/Light-green.qss
- src/Gui/Stylesheets/Light-orange.qss
- src/Gui/Stylesheets/ProDark.qss
---
> Please see also related PR: https://github.com/dracula/freecad/pull/6
> Further discussion in another issue: https://github.com/dracula/freecad/issues/4
All stylesheets included in the FreeCAD source have superfluous whitespace in dropdowns, but lack any highlighting for "checked" icons such as Orthographic vs Perspective view.
This PR adds solution proposed by [MisterMakerNL](https://github.com/MisterMakerNL) to all included stylesheets.
For every stylesheet, the `QMenu::item:pressed` color was chosen for the new checked highlight. Only Behave required a different color as its `pressed` color was difficult to see around the icon.
Example for one sheet:
Before:
After:
CC @luzpaz
> [Stylesheets] Remove whitespace and add "checked" icon style

- src/Ext/freecad/CMakeLists.txt
This solves an issue where `import freecad` does not work if you don't set CMAKE_INSTALL_LIBDIR to an absolute path during compilation.
This should simplify packaging a little, not sure if this is the correct way of doing this but it works for me. Can someone explain what is done in the windows portion of this?
> Prepend CMAKE_INSTALL_PREFIX if CMAKE_INSTALL_LIBDIR is not absolute

- src/Mod/Part/Gui/ViewProvider2DObject.cpp
It is better to advise to increase the grid spacing to a reasonable value since increasing the max lines usually results in a grid that is too fine to be of use unless you want to work zooming in **a lot** on a specific part of the sketch, I don't see this a common usecase since sketches are not meant to be finely adjusted by mouse but rather with constraints.
Here an example of how the grid might look when encountering this issue and following the advise to increase maximum lines:
vs the more sane approach of increasing grid spacing:
> Improve grid maxNumberOfLines warning message

- src/Gui/InputField.cpp
- src/Mod/Image/ImageTools/_CommandImageScaling.py
This PR makes the "distance" in Image Scaling command aware of user unit, i.e. it will : 
* Propose a default value using and showing user base unit
* If a unitless value is entered, it will consider it is given as user base unit
To do so, the QLineEdit has been replaced by a InputField (so that user also benefit from the checker). This is 2nd commit.
However to do so, I had to make a general change in InputField class (this is 1st commit).
This commit will let a InputField consider a unitless value is given as user base unit, if and only if value has been entered by user in the GUI (programmatically set values are still considered in FC core base unit if unitless).
This change will not only affect Image Scaling command, but all InputField across FC (eg. grid size in the working plane …
> Make image scaling command aware of user units

- CMakeLists.txt
This gets used here https://github.com/FreeCAD/FreeCAD/blob/5d49bf78de785a536f941f1a6d06d432582a95d3/src/XDGData/org.freecadweb.FreeCAD.appdata.xml.in#L61 and is the version picked up by flatpak so it should be updated too. Personally I don't understand why we have a PACKAGE_VERSION_PATCH and FREECAD_VERSION_PATCH as separate variables but I keep that way for now.
> Bump PACKAGE_VERSION_PATCH for next patch release

- src/Mod/Draft/draftfunctions/move.py
- src/Mod/Draft/draftfunctions/rotate.py
- src/Mod/Draft/draftutils/utils.py
Groups and layers were not handled properly by Draft_Move and Draft_Rotate if copy mode was ON.
I have started with `move.py` and have then adapted `rotate.py` accordingly.
To also handle nested groups it made more sense to fill the `newgroups` list in a separate, prior, loop.
Note that I have not changed the transformation algorithms although there are some strange inconsistencies. Notably in move.py there is the assumption that an object with a `Shape` also has a `Placement`, whereas in rotate.py `elif hasattr(obj,"Placement"):` is followed by `elif hasattr(obj,"Shape"):`.
Additionally:
* In move.py `elif utils.get_type(obj) == "Annotation":` did not work.
* In rotate.py `elif hasattr(obj,'Shape') and (utils.get_type(obj) not in ["WorkingPlaneProxy","BuildingPart"]):` was simplified to …
> Draft: Fix handling of groups on move-copy and rotate-copy

- src/Gui/QSint/actionpanel/actionpanelscheme.cpp
- fixes #6102
- the point is that we don't set any style for the group boxes, therefore the windows style steps as nothing was set yet. Its default style is the color #dddddd which is hardly visible on our blue default style.
as solution set an explicit color and use the grooved style.
This is the result:
> [Gui] QSint: fix QGroupBox visibility

- src/Mod/Path/App/AppPath.cpp
- src/Mod/Path/App/AppPathPy.cpp
- src/Mod/Path/App/VoronoiCellPy.xml
- src/Mod/Path/App/VoronoiCellPyImp.cpp
- src/Mod/Path/App/VoronoiEdgePy.xml
- src/Mod/Path/App/VoronoiEdgePyImp.cpp
- src/Mod/Path/App/VoronoiPy.xml
- src/Mod/Path/App/VoronoiPyImp.cpp
- src/Mod/Path/App/VoronoiVertexPy.xml
- src/Mod/Path/PathScripts/PathVcarve.py
- src/Mod/Path/PathTests/TestPathVoronoi.py
This fixes the behaviour noted in https://forum.freecadweb.org/viewtopic.php?f=15&t=70208.
boost::polygon::voronoi generates some edges that don't make a lot of sense to process - I called them "borderline", for lack of a better name.
Also, "Voronoi" is now a module underneath "Path" and the object names are simplified accordingly ("Path.VoronoiEdge" -> "Path.Voronoi.Edge", ....)
> PATH: Bugfix/vcarve c++ exception

- src/Base/PlacementPy.xml
- src/Base/PlacementPyImp.cpp
Documentation for Placement.rotate() claims this function would be
compatible to TopoShape.rotate() which isn't exactly correct as the
generated placements differ because of backwards multiplication.
This commit adds a "comp" (as in "compatible") keyword argument that -
when "True" (default is False) - produces a Placement that is interchangable with the one
that is generated from TopoShape.rotate().
And please remember to update the Wiki …
> Base: Fix Placement.rotate() to match documentation

- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.h
This PR addresses an issue with dragging multiple dimensions erported here: https://www.forum.freecadweb.org/viewtopic.php?p=616508#p616508
---
> [TD]fix multiple dimension drag

- src/Gui/ExpressionBindingPy.cpp
To reproduce the crash run in the console:
`Gui.ExpressionBinding()` -> crash
---
> Gui: Prevent crash when trying to create ExpressionBinding without arguments

- src/Mod/Part/App/BSplineCurvePy.xml
- src/Mod/Part/App/BSplineCurvePyImp.cpp
- src/Mod/Part/App/BSplineSurfacePy.xml
- src/Mod/Part/App/BSplineSurfacePyImp.cpp
- src/Mod/Part/App/Geometry.cpp
- src/Mod/Part/App/Geometry.h
and change the methods to use dedicated OCCT function
---
> [Part] Add scaleKnotsToBounds method to BSplineCurve

- src/XDGData/org.freecadweb.FreeCAD.xml
When the thumbnailer is not installed, the icon for files with mimetype of application/x-extension-fcstd should show, but it doesn't.
This is because the icon key in the mimetype file for .FCStd is wrong. It's `icon` when it should be `generic-icon`. This PR fixes that.
P.S. If you have the FreeCAD logo on your .FCStd file, not a white page with the corner folded and the FreeCAD logo on it - this is different. In this case you are seeing what the thumbnailer shows if you have it enabled but have chosen to not include a preview of the file in the thumbnail.
> XDGData: Fixes wrong xml element in mimetype file

- src/Mod/TechDraw/App/GeometryObject.cpp
- the logic for the perspective option with the precise
HLR algo was inadvertently removed in the multithread
modifications.
---
> [TD]fix perspective projection

- src/Mod/Draft/draftgeoutils/intersections.py
The `BoundBox` check in the `findIntersection` function did not account for floating point rounding errors.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=3&t=70988
---
> Draft: add tolerance to BoundBox check in intersections.py

- src/Mod/Part/App/AppPartPy.cpp
https://www.forum.freecadweb.org/viewtopic.php?f=3&t=71036
https://www.forum.freecadweb.org/viewtopic.php?f=23&t=71383
---
> [Part]fix makeWireString for Win & Py > 3.09

- src/Mod/Draft/draftobjects/array.py
The implementation of `Base.Placement.rotate()` is 'faulty': it is not compatible with `TopoShape.rotate()`. To deal with this, unnecessarily complex code was created. Which did not always work for circular arrays.
The new code uses a workaround provided on the forum:
https://forum.freecadweb.org/viewtopic.php?p=613196#p613196
---
> Draft: Avoid faulty Base.Placement.rotate() in draftobjects.array.py

- src/Mod/Arch/ArchWall.py
- src/Mod/Draft/draftgeoutils/faces.py
To fix the issue a new argument, `per_segment`, was introduced for the `bind` function in `faces.py`. Additionally the call to `face.fix()` was moved to that function.
Fixes #7370
Forum topics:
https://forum.freecadweb.org/viewtopic.php?f=23&t=67107&start=30
https://forum.freecadweb.org/viewtopic.php?f=23&t=71107
---
> Arch: Fix wall baseface generation for overlapping and self-intersecting traces

- src/Mod/Draft/draftgeoutils/wires.py
- src/Mod/Draft/draftviewproviders/view_bezcurve.py
- src/Mod/Draft/draftviewproviders/view_bspline.py
- src/Mod/Draft/draftviewproviders/view_fillet.py
- src/Mod/Draft/draftviewproviders/view_wire.py
The flatten command (context menu) did not work properly and did not respect the Draft working plane.
The context option has been removed for Draft_BSplines and Draft_BezCurves because properly flattening these objects (get a correct 2D projection, but also retain the original object type) is (probably?) not possible.
For Draft_Fillets, which are not parametric, the context option also does not make sense.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=60279
---
> Draft: Fix flatten wire

- src/Mod/Draft/draftviewproviders/view_layer.py
This PR tries to improve the drag-and-drop behavior for Layers (it does not rely on the Ctrl key):
If you drop an object from a Group/BuildingPart on a Layer the object is not removed from the Group/BP and vice versa.
To remove an object from a Layer it must be dropped on another Layer or on the document node.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?p=619107#p619107
---
> Draft: Improve drag-and-drop behavior for Layers

- src/Mod/PartDesign/App/ShapeBinder.cpp
https://forum.freecadweb.org/viewtopic.php?f=12&t=71615
Offset of SubShapeBinder wasn't working for closed or open wires.
> PartDesign: improve offset handling of SubShapeBinder

- src/Gui/propertyeditor/PropertyEditor.cpp
Fix a regression introduced by b42462ba14
It was no more possible to assign an expression using context menu in Property pane (eg. to a "Placement" property) if the value was currently being edited (left-click the value in the Property pane).
The "Expression..." context menu was still present but failed to open the expression dialog.
> [Bugfix]Gui: allow set up expression even if property value is currently being edited

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=71536
This bug appears because "Shift" in use in a "hold-to-act" way to disable constraints selectability when pressed.
With current implementation using viewprovider callback, if Shift is pressed with focus on Quarter widget, then focus is set to another widget, then only Shift is released (out of Quarter widget focus), the release event isn't catched by Quarter widget and so isn't forwarded to viewprovider.
When mouse back in the focus of the Quarter widget, the view provider still acts as if Shift key was presses. This basically lasts till the user does a Shift press+release cycle (with focus on Quarter widget).
The new implementation moves the Shift state detection to the `mouseMove` viewprovider function and read the state directly …
> [Bugfix]Sketcher: prevent dangling state of Shift key if key released out of Quarter

- src/Tools/fcinfo
ZipFile.read returns a bytes-like object so re.sub must be passed byte-like objects arguments when operating on those read files.
reported here: https://forum.freecadweb.org/viewtopic.php?p=625238
> [tools] fix `fcinfo -g` script

- src/Gui/DlgKeyboardImp.cpp
User was only warned in the report view which he/she may missed.
Use a warning message box.
Also provide advice about how to solve.
https://forum.freecadweb.org/viewtopic.php?f=8&t=39858
How it looks :
> Gui: when customizing shortcuts, warn user if command isn't in use with a message box

- .github/workflows/checks.yml
This PR allows manual launch of CI workflow.
This allows any contributor working on its fork to manually launch the CI workflow at any time during development without need to do a PR.
> CI: allow manual launch of CI

- src/Mod/PartDesign/Gui/TaskPrimitiveParameters.cpp
Currently, the X-min property of wedges are rounded to the nearest integer after pressing _OK_ under the _Tasks_ tab instead of the nearest hundredth like the other wedge properties. This small pull request adds the format parameter used with the other properties so X-min is handled the same as the other wedge properties. This fix does not affect the property table under the _Model_ tab since it has the correct behavior.
> PartDesign: Add format parameter for Wedge X-min under Task tab

- src/Mod/Sketcher/Gui/Resources/icons/constraints/Constraint_Diameter.svg
- src/Mod/Sketcher/Gui/Resources/icons/constraints/Constraint_Diameter_Driven.svg
- src/Mod/Sketcher/Gui/Resources/icons/constraints/Constraint_Radiam_Driven.svg
following https://wiki.freecadweb.org/Artwork_Guidelines, previous icons mixed red and blue colors (which was noticeable besides the other icons) and didn't use the official blue palette  (was brighter), also was missing one stroke in diameter icons, also was not saved as plain svg.
> [Sketcher] adjust some sketcher icons to better follow art style guide

- src/Mod/Part/Gui/DlgSettingsMeasure.ui
This PR improves two UI texts from #7148
The word "Dimension" is strange because the tools have "Measurement" in their names.
"measures" should be "measurements". See https://forum.freecadweb.org/viewtopic.php?f=3&t=71900&p=626329#p626320.
---
> Part: Measure preferences: Improve UI texts

- src/App/ApplicationPy.cpp
- src/App/DocumentObjectPyImp.cpp
- src/App/DocumentPyImp.cpp
- src/App/PropertyLinks.cpp
- src/Base/PyObjectBase.h
- src/Gui/LinkViewPyImp.cpp
- src/Gui/MDIViewPy.cpp
- src/Gui/Selection.cpp
- src/Gui/View3DPy.cpp
- src/Gui/ViewProviderPy.xml
- src/Gui/ViewProviderPyImp.cpp
- src/Mod/Part/TestPartGui.py
- src/Mod/Spreadsheet/App/SheetPyImp.cpp
Occasionally, a Python function argument may expect a specific type or `None`, by using the corresponding format unit in the parse function. The helper function `Base::PyTypeCheck` generates similar functionality to those format units, setting the `PyObject` pointer to `nullptr` in case the passed value is `None` and throwing an exception if the type is not correct.
In the ViewProvider Python implementation is restored the posibility to pass `None` to some arguments of the drag and drop functions to fix some regressions reported in the aseembly forum: https://forum.freecadweb.org/viewtopic.php?f=20&t=69777
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below …
> src: Add helper function to check Python types.

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
This PR has been extracted from #7478 
Commit 1 : in current state, even if condition aren't OK to apply 'point-on-object' (for example selected vertex belongs to selected curve) we try to substitute constraints (typically coincident + curve/curve tangency => smooth joint). This can lead to strange effect, like "command not working" but still "something else happens". Commit prevent trying constraint substitution if conditions aren't OK for the command to process
Commit 2 : fixes an indentation problem that makes code hard to understand properly
Commit 3 : improves command (undo transaction) management. In current code, constraint substitution in 'coincident' generates its own transaction. With commit it no more does and delegate the transaction management to the calling method, which is …
> Sketcher: various fixes in constraint commands

- src/App/Metadata.cpp
- src/App/Metadata.h
- src/App/MetadataPy.xml
- src/App/MetadataPyImp.cpp
- src/Mod/AddonManager/Addon.py
- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/addonmanager_devmode.py
- src/Mod/AddonManager/addonmanager_devmode_add_content.py
- src/Mod/AddonManager/addonmanager_macro.py
- src/Mod/AddonManager/addonmanager_utilities.py
- src/Mod/AddonManager/addonmanager_workers_installation.py
- src/Mod/AddonManager/addonmanager_workers_startup.py
- src/Mod/AddonManager/developer_mode.ui
Add support for a `<pythonmin>` tag in the package.xml metadata file, and add auto detection of the required Python version to Addon Manager Developer Mode.
> App and Addon Manager: Add min python version tag

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftguitools/gui_edit.py
- src/Mod/Draft/draftguitools/gui_edit_draft_objects.py
This PR implements several improvements for the Draft_Edit context menus:
1. The second Close button was removed from the task panel. Instead the context menus for edges now have a Close/Open option.
2. Add/Delete point is always the 1st option in a context menu.
3. Added Reverse and Close/Open options to the Draft_BezCurve edge context menu.
4. All options use sentence case and can be translated.
5. The Invert arc option is not displayed for circles.
Forum topic;
https://forum.freecadweb.org/viewtopic.php?f=23&p=510120#p510120
---
> Draft: Improve Draft_Edit context menus

- cMake/FreeCAD_Helpers/CompilerChecksAndSetups.cmake
C++14 has been previously deprecated for FreeCAD
> Remove redundant reference to C++14

- src/Gui/CommandView.cpp
- src/Gui/NavigationStyle.cpp
- src/Gui/Quarter/SoQTQuarterAdaptor.h
- src/Gui/Workbench.cpp
This PR moves 2 functions used to store/recall a document-specific temporary view in 3D viewport : 
- from hardcoded in the navigation style base class
- to 2 normal commands that user can use as needed (especially customize shortcuts)
The hardcoded behavior was creating some very weird effect to user in specific conditions (see forum link)
The commands are added at the end of the `standard view` submenu in the `view` menu.
Default shortcuts are `Shift+End` and `End` respectively for store and recall.
https://forum.freecadweb.org/viewtopic.php?f=3&t=72082
> Gui: functions to store/recall temporary working view moved from hardcoded to commands

- src/Gui/PythonEditor.cpp
Parameter observing (including observer deletion) is 100% managed by TextEditor superclass
I caught it because closing FreeCAD with macro editor opened reports `Observer 0xYYYYYYY already detached`
> Gui: do not detach parameter observer from PythonEditor

- src/Gui/TinkerCADNavigationStyle.cpp
https://forum.freecadweb.org/viewtopic.php?f=3&t=72174
Bugs comes from TinkerCAD mode using RMB dragging to rotate view.
So it has to itself handle when a user makes a short "single" click with RMB.
There was a problem with how conditions was nested, so actually it was always catching the mouse event -- stopping propagation -- even when the viewer was in Edit mode (which it shouldn't).
This for example prevents Sketcher tools to be exited with RMB.
The PR brings a correct behavior in case of short "single" RMB click : if viewer is not in Edit mode, the event is caught and processed ; if viewer is in Edit mode, the event is ignored and let free to propagate.
> [Bugfix]Gui: TinkerCAD mouse mode was always stopping RMB propagation

- src/Mod/Part/App/GeometryDefaultExtension.cpp
we don't support such old GCC versions anymore so I think this can be removed
> [Part] remove code for < GCC 4.8

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/manage_python_dependencies.py
For some users `pip` is timing out after 30 seconds, rather than returning a list of packages to update. It's not clear why this is happening yet, but in the meantime, try to improve the behavior of the code when it happens.
> Addon Manager: Improve failed pip behavior

- .github/workflows/checks.yml
https://forum.freecadweb.org/viewtopic.php?f=10&t=72142
@wwmayer @chennes @donovaly May one merge quickly please ? This makes CI fails for no reason. Detailed explanations on forum thread. Thx
> [Bugfix]CI: disable line-ending conversion as it damages .FCStd files

- src/Mod/Arch/ArchBuildingPart.py
- src/Mod/Arch/ArchSectionPlane.py
- src/Mod/Draft/draftviewproviders/view_dimension.py
- src/Mod/Draft/draftviewproviders/view_label.py
- src/Mod/Draft/draftviewproviders/view_wpproxy.py
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=72122
---
> Draft+Arch: Fix crash related to SoBrepEdgeSet

- src/Mod/Draft/draftguitools/gui_edit.py
This PR removes two checkboxes that have no purpose from the Draft_Edit node task panel.
---
> Draft: Improve Draft_Edit task panel

- src/Mod/Draft/drafttaskpanels/task_shapestring.py
Double quotes in the task panel input string need to be escaped.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=72342
---
> Draft: Fix handling of double quotes in shapestrings

- src/Gui/InputField.cpp
Reuse "ComboBoxWheelEventFilter" switch that already acts on combo and spin boxes
https://forum.freecadweb.org/viewtopic.php?f=10&t=30772&p=630804#p630788
> Gui: optionally disable wheel event when Gui::InputField doesn't have focus

- .github/codespellignore
All codespell ignore words should be lowercase.
> [skip ci] codespell: correct ignore list entry

- src/Gui/DlgEditorImp.cpp
- src/Gui/DlgReportViewImp.cpp
- src/Gui/PythonConsole.cpp
- src/Gui/ReportView.cpp
- src/Gui/SyntaxHighlighter.cpp
- src/Gui/TextEdit.cpp
Both problems solved here come when you apply an OS native dark theme -- keeping default FC theme --.
In this case you are provided with a dark background for widgets, but it's not ideally managed in FC.
1st commit solves a problem that when you have a blank config, the color of the normal messages color in the Report view is chosen by Qt. With a dark OS theme, this text turns to white -- good --. The problem is that when opening the Preferences editor, the default value is always initialized to black, so if you save your preferences (for any reason), you will now get black text over dark background, which is unreadable. With this commit, the default value in the Preferences editor is initialized with the current text color used in the FC app.
2nd commit solves another similar problem …
> Improve text color management in Report view + Python console + Macro editor

- src/Mod/Sketcher/App/planegcs/GCS.cpp
Some equations were mentioned by just the number without telling the resource they were from. The book was found couple years ago but not mentioned here.
There might be better places to mentioned the book but next to equation numbers can work for now.
> [Sketcher] [planegcs] [skip ci] Add references for equations

- src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
Snaps are failing because `signbit` isn't declared. Probably because of e29d1d03326035ffa32cffb9b2f8d2f67bf19d5a. One of the removed includes might have had a `using std` or such, which might also be present in some versions of the remaining includes (local, gitlab CI) but absent in others (snap CI).
Failed test details here: https://github.com/FreeCAD/FreeCAD-snap/actions/runs/3221426471/jobs/5269345313.
> [TD] Explicitly call `std::signbit`

- src/Mod/Draft/draftfunctions/svg.py
This was missed in https://github.com/FreeCAD/FreeCAD/pull/7453.
Additionally: Changed the sign of `tangle`.
Two issues to look at later:
1. The value of `pointratio` seems to be wrong. The arrows appear bigger in a TechDraw_DraftView than in the 3D view.
2. The texts of angular dimensions are rotated to a 'readable' angle in a TechDraw_DraftView, this does not happen in the 3D view.
---
> Draft: Fix alignment of angular dimension arrows in svg.py

- src/Mod/Draft/draftguitools/gui_pointarray.py
- src/Mod/Draft/draftmake/make_pointarray.py
- src/Mod/Draft/draftobjects/pointarray.py
The Placement of some point objects was ignored. And the number of supported point object types was rather restrictive.
Forum topics:
https://forum.freecadweb.org/viewtopic.php?f=23&t=59359
https://forum.freecadweb.org/viewtopic.php?f=3&t=61144&p=524241#p524233
https://forum.freecadweb.org/viewtopic.php?f=23&t=71957
---
> Draft: Point array: Take placement of point object into account and accept more point object types

- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
Fixes issue #7442.
There appears to be no reason to not allow construction points to be constrained. I may be wrong here though.
> [Sketcher] Allow driving constraint on construction geometry

- src/Mod/Draft/draftobjects/patharray.py
The 'avoid problems with float math' solution in `placements_on_path()` did not work properly. The issue has come to light after #7506 which revised the calculation order of the placements.
---
> Draft: Fix path array float math issue

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftguitools/gui_arcs.py
- src/Mod/Draft/draftguitools/gui_base_original.py
- src/Mod/Draft/draftguitools/gui_beziers.py
- src/Mod/Draft/draftguitools/gui_circulararray.py
- src/Mod/Draft/draftguitools/gui_clone.py
- src/Mod/Draft/draftguitools/gui_dimensions.py
- src/Mod/Draft/draftguitools/gui_edit.py
- src/Mod/Draft/draftguitools/gui_ellipses.py
- src/Mod/Draft/draftguitools/gui_fillets.py
- src/Mod/Draft/draftguitools/gui_labels.py
- src/Mod/Draft/draftguitools/gui_lines.py
- src/Mod/Draft/draftguitools/gui_mirror.py
- src/Mod/Draft/draftguitools/gui_move.py
- src/Mod/Draft/draftguitools/gui_offset.py
- src/Mod/Draft/draftguitools/gui_orthoarray.py
- src/Mod/Draft/draftguitools/gui_points.py
- src/Mod/Draft/draftguitools/gui_polararray.py
- src/Mod/Draft/draftguitools/gui_polygons.py
- src/Mod/Draft/draftguitools/gui_rectangles.py
- src/Mod/Draft/draftguitools/gui_rotate.py
- src/Mod/Draft/draftguitools/gui_scale.py
- src/Mod/Draft/draftguitools/gui_selectplane.py
- src/Mod/Draft/draftguitools/gui_shapestrings.py
- src/Mod/Draft/draftguitools/gui_splines.py
- src/Mod/Draft/draftguitools/gui_stretch.py
- src/Mod/Draft/draftguitools/gui_styles.py
- src/Mod/Draft/draftguitools/gui_texts.py
- src/Mod/Draft/draftguitools/gui_trimex.py
Using Esc should not set continueMode to False.
To fix this the `finish()` functions were modified and made more consistent. If the function can be called from DraftGui.py it always has a `cont` argument. In some cases this is a dummy argument. The `closed` argument is only added when the object in question can in fact be closed.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=59520
Additionally:
* DraftGui.py: Removed `spec = True` when inCommand "Exit" is used.
* gui_beziers.py, gui_ellipses.py, gui_lines.py and gui_rectangles.py: These contain a check `arg["Position"] == self.pos` which compares the current point with the previous point (coordinates in pixels). This check was not correctly implemented. Note that this check is completely absent from some of the other …
> Draft: Escape should not switch off continueMode

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
- in current implementation, backedit feature is lost if user changes camera mode (for example from orthographic to perspective, or oppositely). This happens because when changing camera mode, Coin actually do not just change a parameter of the camera node, but delete the current camera node and add a new one to the scenegraph. Thus the SoFieldSensor currently used (attached to camera orientation) is just detached and sensing is left -- notice is would be same with a SoNodeSensor attached to camera node --. The solution is to attach the sensor at scenegraph root node so it isn't lost when camera mode changed. No pre-check (such as checking if camera node changed since last call) has been added currently because it would not actually reduce callback execution time (and even worsen it).
> [Bugfix]Sketcher/BackEdit : Backedit lost if user changed camera mode

- src/Gui/MainWindow.cpp
This makes them use a translated string for the new document name
https://forum.freecadweb.org/viewtopic.php?f=10&t=69859&p=606617
@Kuzma30
> Use Std_New for startup document creation

- src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
- replace check of pages in selection with check of pages in document
- fix mixed {} conventions
- fix fail to exit on user cancel
---
> [TD]fix check of wrong variable

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
@wwmayer I actually introduced this flag because I did something stupid when testing corner cases when I introduced the last changes.
Your commit ee0a0817f shed light on my mistake ... at the price of some inconvenience for you. Sorry for that.
Another lesson learned. :)
> Sketcher: remove unneeded flag

- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/planegcs/Constraints.cpp
- src/Mod/Sketcher/App/planegcs/Constraints.h
- src/Mod/Sketcher/App/planegcs/GCS.cpp
- src/Mod/Sketcher/App/planegcs/GCS.h
================================================================
Master has a problem in that internal alignment constraints are suggested to the user for removal.
This is fundamentally wrong, as an internal alignment constraint are an inherent part of the geometry. They cannot be the ones suggested for removal.
The popularity contest algorithm is an heuristic algorithm that determines which redundant/conflicting constraints should be proposed for removal.
Basically, the algorithm works on groups of redundant/conflicting constraints detected via the QR decomposition. A constraint may belong to more than one group.
The algorithm runs some heuristics, each constraint scoring a value, the one constraint from each group scoring the highest is proposed (is more popular and wins the contest). …
> Sketcher: Solver - Improvement of popularity contest and bug fix

- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
`HoleCutDepth` is reset to 0 to force a recalculation of the depth when `HoleCutType` is set to a new value.
But the line
```cpp
pcHole->HoleCutCustomValues.setValue(false)
```
also forces a recalculation. So the depth was recalculated with the old value in `HoleCutType` which was not expected behaviour.
@donovaly This is the first tiny bugfix for https://forum.freecadweb.org/viewtopic.php?f=8&t=72404
And please remember to update the …
> [Bugfix] PartDesign: Fix HoleCutDepth not being recalculated correctly

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
---
Hi,
this is my first PR on this project, so please tell me, if I'm missing something.
**Rationale:**
I wanted to create a countersunk hole with an additional hole …
> PartDesign: Allow hole depth for countersinks

- src/Mod/Draft/draftobjects/point.py
Using the manipulator did not work for a Draft Point as its Placement got reset based on its X, Y and Z properties.
Reported here:
https://github.com/FreeCAD/FreeCAD/pull/4896#issuecomment-1280043096
---
> Draft: Make Std_TransformManip work for Draft_Point

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- as discussed in https://github.com/FreeCAD/FreeCAD/pull/7642 the backwards compatibility for deprecated holes was already lost since FC 0.19
- this PR removes the deprecated types and transform holes created with FC 0.19 or 0.20 to the corresponding countersinks/counterbores.
- also add Counterdrill for translations
> [PD] remove deprecated holes

- .github/workflows/checks.yml
QtWebKit is obsolete and will soon be removed from FreeCAD -- it is replaced by QtWebEngine (e.g. Chromium).
> CI: Switch to QtWebEngine instead of QtWebKit

- src/Tools/plugins/widget/CMakeLists.txt
We missed adding CMake code to also build the designer plugin against Qt6. See https://github.com/FreeCAD/FreeCAD/pull/7647#issuecomment-1297202448
This patch adds the code to enable this.
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net> …
> Core: Add additional CMake code for building with Qt6

- src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui
The Alternate Decimals setting is applied to new objects. The label should therefore be italic.
---
> TechDraw: "Alternate Decimals" label in prefs should be italic

- src/Gui/Application.cpp
- src/Gui/DlgGeneral.ui
- src/Gui/DlgGeneralImp.cpp
- src/Gui/DlgGeneralImp.h
- src/Gui/GuiApplication.cpp
- src/Gui/GuiApplication.h
- src/Gui/Language/Translator.cpp
- src/Gui/Language/Translator.h
This PR moves the decimal point converter (eventFitler) from GuiApplication to Translator.
This allows to have a hot enabling/disabling of the feature.
Also it harmonizes things as Translator now take cares of number format, which it is directly related.
> Gui: add decimal point converter to Translator

- src/Mod/Part/App/Attacher.cpp
- src/Mod/Part/App/FeatureExtrusion.cpp
Reported in https://forum.freecadweb.org/viewtopic.php?p=637174#p637035
The direct cause is that the topo naming generation in Part::FeatureExtrude is accidentally disabled, which is fixed in the first commit. The second commit improves attacher auto fix on name change.
> TopoNaming: fix attacher

- src/Gui/DlgDisplayPropertiesImp.cpp
- src/Mod/Part/Gui/TaskDimension.cpp
for consistency with other task dialogs, requested in https://forum.freecadweb.org/viewtopic.php?p=623239 (#7516 )
I have not actually tested yet if this works
> Move "Close" button to north in appearance and measure dialogs

- src/Gui/ToolBarManager.cpp
- src/Gui/ToolBarManager.h
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/Workbench.cpp
- src/Mod/Sketcher/Gui/Workbench.h
The offered change is to :
Commit 1 - split the main sketcher toolbar in 2. One for tools that are only in edit mode. One for tools that are only in non-edit-mode.
Commit 2 - This adds the systemwide possibility to hide toolbars at anytime while in a workbench.
Show/hide automatically toolbars depending if we are in edit mode or not.
More specifically it hides : Sketcher-edit-mode, Geometry, constraint, tools, virtualSpace toolbars when in sketcher-not-edit-mode.
And it hides : Sketcher and Structure toolbar when in sketcher-edit-mode
Video presentation : https://youtu.be/5HF8f648JlU
[See discussion : https://forum.freecadweb.org/viewtopic.php?f=8&t=72946](https://forum.freecadweb.org/viewtopic.php?f=17&t=72978)
Thank you for creating a pull request to contribute to FreeCAD! To ease …
> Sketcher: Gui: force-hide toolbars + Split sketcher toolbar

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
Enable the coincidence tool to select edges. If those edges are circle, ellipse, arc or arc of ellipse, then it create concentric constraint.
https://github.com/FreeCAD/FreeCAD/issues/7546#issuecomment-1302997618 …
> Sketcher: Add concentric capabilities to coincidence constraint.

- src/Mod/Fem/Gui/DlgSettingsFemElmerImp.cpp
- the code already assured that the number of used CPU cores for Elmer can only be > 1 if a valid path to the '_mpi' executable is specified. However, we can have the case that Elmer was uninstalled, then the path validity checker returns an empty path and then the check for the number of cores but handle this case. THis PR does exactly this.
- also fix typos and improve error message
- also add missing save guard for hardware check
> [FEM] safer Elmer executable path handling

- src/App/FreeCADInit.py
- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/addonmanager_utilities.py
- src/Mod/AddonManager/addonmanager_workers_installation.py
- src/Mod/AddonManager/manage_python_dependencies.py
Modify the Addon Manager to use different subdirectories for the automatic installation of Python dependencies. This is the first step towards automatically supporting changing Python versions, and potentially supporting multiple simultaneous versions.
Fixes #7686.
**NOTE TO TESTERS:** Back up your $FREECAD_USER_DIR/AdditionalPythonPackages directory before running a version of FreeCAD that includes this PR. One of the things it does is migrate your existing packages into a subdirectory, which is an irreversible process. Once it is merged, I will backport the part of it that searches the new location, so that someone switching between 0.21 and 0.20 doesn't have to worry about it.
> Addon Manager: use versioned Python package dirs

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/AddonManagerOptions.py
- src/Mod/AddonManager/NetworkManager.py
- src/Mod/AddonManager/addonmanager_devmode.py
- src/Mod/AddonManager/addonmanager_devmode_add_content.py
- src/Mod/AddonManager/addonmanager_devmode_license_selector.py
- src/Mod/AddonManager/addonmanager_devmode_licenses_table.py
- src/Mod/AddonManager/addonmanager_devmode_people_table.py
- src/Mod/AddonManager/addonmanager_devmode_person_editor.py
- src/Mod/AddonManager/addonmanager_devmode_validators.py
- src/Mod/AddonManager/addonmanager_macro.py
- src/Mod/AddonManager/addonmanager_utilities.py
- src/Mod/AddonManager/addonmanager_workers_installation.py
- src/Mod/AddonManager/addonmanager_workers_startup.py
- src/Mod/AddonManager/addonmanager_workers_utility.py
- src/Mod/AddonManager/change_branch.py
- src/Mod/AddonManager/compact_view.py
- src/Mod/AddonManager/expanded_view.py
- src/Mod/AddonManager/install_to_toolbar.py
- src/Mod/AddonManager/manage_python_dependencies.py
- src/Mod/AddonManager/package_details.py
- src/Mod/AddonManager/package_list.py
Migrate the Addon Manager to the "PySide" wrapper, replacing all instances of "PySide2" with the generated files. When FreeCAD is compiled with `FREECAD_QT_VERSION=6`,  this wrapper automatically uses PySide6 instead of PySide2.
> Addon Manager: Qt6 migration part 1, use PySide

- src/Gui/DlgMaterialProperties.ui
- src/Gui/ViewProviderGeometryObject.cpp
- src/Mod/Mesh/Gui/DlgSettingsMeshView.ui
- src/Mod/Mesh/Gui/ViewProvider.cpp
- src/Mod/Part/Gui/DlgSettingsObjectColor.ui
- as discussed here: https://github.com/FreeCAD/FreeCAD/pull/7103 we have different transparency spin button step sizes. This PR uniforms them all to 5%.
- (the other changes were automatically made by Qt Designer)
> [Gui][Mod]: uniform spin button step size to 5%

- src/Mod/Draft/draftfunctions/offset.py
- src/Mod/Draft/draftgeoutils/offsets.py
- src/Mod/Draft/draftgeoutils/wires.py
Fix for a bug that was introduced with #5496 (my bad). The wire argument can be a face in offsets.py and `isClosed()` always(?) returns `False` for faces. Which led to a problem when offsetting Draft_Rectangles with faces.
I have now fixed `isReallyClosed()`, which is used in several other places anyway.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?p=636954#p636954
---
> Draft: Fix rectangle with face offset bug

- src/Mod/Arch/InitGui.py
- src/Mod/Draft/InitGui.py
- src/Mod/Draft/draftguitools/gui_snapper.py
- src/Mod/Draft/draftguitools/gui_snaps.py
- src/Mod/Draft/draftutils/init_draft_statusbar.py
- src/Mod/Draft/draftutils/init_tools.py
- src/Mod/Tux/PersistentToolbarsGui.py
This PR changes the Draft snap toolbar to a standard toolbar.
Many thanks to @carlopav for all his work on the gui_snaps.py file. I have basically adopted his solution. See https://github.com/carlopav/FreeCAD/tree/Draft_SnapToolbarToStandard.
The code has been tested with the BIM Workbench, for which a standard toolbar cannot be introduced just yet as it still has to work with FC0.20. For the BIM Workbench the snap toolbar is built by reusing the GUI actions that are available because of its Snapping menu. Reusing the available actions is the key to keeping the buttons synchronized. This solution is also used for the updated statusbar snap widget.
The new version of the statusbar snap widget behaves slightly differently. If the Lock button is clicked (short click) snapping is …
> Draft: Change Snap toolbar to standard toolbar

- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/config.yml
Fixes #7687 by removing the hard requirement that an issue be discussed at the Forums first. The new language encourages, but does not require, such discussions. I've made some other changes to the template language as well, mostly switching from "bug" to "issue" so that it encompasses things that a normal reader wouldn't consider a "bug". If this PR is merged we can consider dropping the "Feature Request" template entirely.
> GitHub: Remove forums requirement from issue template

- src/Gui/DlgReportView.ui
- src/Gui/DlgReportViewImp.h
- src/Gui/PythonConsolePy.cpp
- src/Gui/PythonConsolePy.h
- src/Gui/ReportView.cpp
- src/Gui/ReportView.h
> Gui: Rename 'Output window' to 'Report view'

- src/Mod/AddonManager/NetworkManager.py
As reported by a user on Facebook: if the proxy is an invalid string, it's possible to have the integer port conversion fail. Protect it with a try/except block and act as though no port was set, displaying an error message to the console.
Fixes #7736 .
> Addon Manager: Add try/except to integer conversion

- src/Mod/Path/libarea/CMakeLists.txt
This update adds the OpenCASCADE headers and lib path to `src/Mod/Path/libarea/CMakeLists.txt`, to fix a linker error.
configure finds OCC and the other modules have `OCC_INCLUDE_DIR` and `OCC_LIBRARY_DIR` but it appears to be omitted from the Path/libarea  
```
-- OCC:                 7.6.0 [TKFillet;TKMesh;TKernel;TKG2d;TKG3d;TKMath;TKIGES;TKSTL;TKShHealing;TKXSBase;TKBool;TKBO;TKBRep;TKTopAlgo;TKGeomAlgo;TKGeomBase;TKOffset;TKPrim;TKSTEPBase;TKSTEPAttr;TKSTEP209;TKSTEP;TKHLR;TKFeat] [/usr/local/lib] [/usr/local/include/OpenCASCADE]
-- Found OCC: /usr/local/include/OpenCASCADE (found version "7.6.0") 
-- -- Found OCE/OpenCASCADE version: 7.6.0
-- -- OCE/OpenCASCADE include directory: /usr/local/include/OpenCASCADE
-- -- OCE/OpenCASCADE shared libraries directory: /usr/local/lib
... …
```
> [PATH] add OCC header/libdir to Path/libarea

- src/Gui/DlgDisplayProperties.ui
- src/Gui/DlgDisplayPropertiesImp.cpp
- src/Gui/DlgDisplayPropertiesImp.h
I missed having this button several times when editing the appearance of subhsapebinders and sketches, you can easily set the line color but then then the points stand out a lot and to change the point color you have to go to Property view > View tab > Point Color, making the appearance dialog useless.
> Gui: Add button to set point color in Appearance task dialog

- src/Mod/Draft/drafttests/test_modification.py
This PR  adds a test and modifies an existing test.
The old `test_offset_closed` function was renamed to `test_offset_rectangle_with_face`. 
It is now also a regression test for: https://github.com/FreeCAD/FreeCAD/pull/7670
The added `test_offset_closed_with_reversed_edge` function is a regression test for: https://github.com/FreeCAD/FreeCAD/pull/5496
---
> Draft: test_modification.py: modified test and added test

- .github/PULL_REQUEST_TEMPLATE.md
Use a much shorter PR template format, preferring to link to CONTRIBUTING.md instead of spelling out each requirement here. Closes #7752.
> Update the PR template to link to CONTRIBUTING.md

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/CMakeLists.txt
- src/Mod/AddonManager/addonmanager_firstrun.py
Extract the "first run" dialog into its own class to simplify AddonManager.py
Addresses (but does not close) #7747.
> Addon Manager: Refactor to extract first run dialog

- src/Mod/Spreadsheet/App/PropertySheet.cpp
- src/Mod/Spreadsheet/App/PropertySheet.h
- src/Mod/Spreadsheet/App/SheetPy.xml
- src/Mod/Spreadsheet/App/SheetPyImp.cpp
- src/Mod/Spreadsheet/TestSpreadsheet.py
Also adds access to `getNonEmptyCells()`, and unit tests for both. In a second commit, two new C++ functions are introduced to get the range of non-empty and used cells, `getNonEmptyRange()` and `getUsedRange()`. These functions return a pair of cell addresses representing the bounding box of the data in the sheet. Python wrappers and unit tests are also provided.
Designed to fix #7587.
> Spreadsheet: Add Python API for getUsedCells

- .clang-format
- we used in the past line breaks after a case statements to better overview. This should be kept.
> [.clang] use line break after case

- src/Gui/NaviCube.cpp
- when pressing the "dot" besides the NaviCube, the rotation to the backside was not in the center thus the view jumped
> [Gui] NaviCube: fix rotation to backside

- src/Gui/SoFCOffscreenRenderer.cpp
Set jpg screenshot capture to 100% quality vs qimage defaulting to -1
[Save Picture/Export PDF quality issues](https://forum.freecadweb.org/viewtopic.php?f=10&t=72707)
Working in github only. Do I need to do this?
Working in github only. I honestly don't know how to do this -_-
> Gui: Add default JPEG save quality

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
Fix bug mentioned by @0penBrain introduced in : https://github.com/FreeCAD/FreeCAD/pull/7703#issuecomment-1312756924
---
> Sketcher: Coincidence constraint: fix error introduced by concentric

- src/Mod/Measure/App/Measurement.cpp
Measurement does not take object placement into account.  This works fine as long as the measurement references are all in the same object.  To allow measurement between points on different objects, we need to apply placement before calculating the measurement value. …
> [Measurement]apply globalPlacement to geometry

- src/Mod/TechDraw/App/DrawView.cpp
- the routines for retrieving a view's parent page did not correctly deal with duplicate page entries
---
> [TD]fix handling of multiple pages

- src/Mod/TechDraw/App/DrawProjGroupItemPyImp.cpp
- src/Mod/TechDraw/App/DrawSVGTemplatePyImp.cpp
- src/Mod/TechDraw/App/DrawViewClipPyImp.cpp
- src/Mod/TechDraw/App/DrawViewCollectionPyImp.cpp
- src/Mod/TechDraw/App/DrawViewDimensionPyImp.cpp
- src/Mod/TechDraw/App/DrawViewSymbolPyImp.cpp
- src/Mod/TechDraw/App/GeomFormatPyImp.cpp
* `DrawProjGroupItemPy::autoPosition`:
Use `PyArg_ParseTuple` to check arguments.
* `DrawSVGTemplatePy::getEditFieldContent`:
`nullptr` must be returned only if a exception is raised.
* `DrawSVGTemplatePy::setEditFieldContent`:
Remove try-catch block and always return `None`.
* `DrawViewClipPy::addView`, `DrawViewClipPy::removeView`:
Cast from `DocumentObjectPy` to `DrawViewPy` is undefined behaviour, so check `DrawViewPy` type in `PyArg_ParseTuple`.
* `DrawViewClipPy::getChildViewNames`:
Fix initialization size in returned list.
* `DrawViewCollectionPy::addView`, `DrawViewCollectionPy::removeView`:
Cast from `DocumentObjectPy` to `DrawViewPy` is undefined behaviour, so check `DrawViewPy` type in `PyArg_ParseTuple`.
* DrawViewDimensionPyImp.cpp:
Use `PyArg_ParseTuple` to check arguments. …
> TechDraw: Improve and clean up code in some Python classes

- src/Mod/TechDraw/App/AppTechDrawPy.cpp
- src/Mod/TechDraw/App/DrawProjectSplit.cpp
- src/Mod/TechDraw/App/DrawProjectSplit.h
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewPart.h
- src/Mod/TechDraw/App/GeometryObject.h
@WandererFan 
Replacing the use of raw pointers of GeometryObject with shared pointers fixes the observed memory leaks when running the unit tests of TechDraw
[Forum thread](https://forum.freecadweb.org/viewtopic.php?p=640322#p640322) …
> TD: fix memory leaks with raw pointers of GeometryObject

- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
First commit fixes the problem coming when an arc of circle having its aperture constrained with an angle is cloned.
Described here : https://forum.freecadweb.org/viewtopic.php?f=3&t=73427
2nd commit disabled auto-constraining ability in Clone/Copy/Move commands as it is unusable but just create misleading behaviors.
> [Bugfix] Sketcher: fix issue with angle-constrained arc in Clone command

- src/Base/UnitsApi.cpp
- src/Base/UnitsApi.h
- src/Base/UnitsSchema.h
- src/Base/UnitsSchemaCentimeters.h
- src/Base/UnitsSchemaImperial1.h
TechDraw DrawViewDimension contains a routine which returns a unit of measure for each Unit Schema.  This routine contains a hard-coded list of schemata and a matching hard-coded list of length units, which is a maintenance issue. 
This PR adds a function to UnitsApi which returns the basic length unit of measure for the current user schema.  Most schemata return the default of "mm".  Exceptions override the default and return, for example, "in".
Please remember to update the Wiki with …
> [Units]Allow querying schema for unit of measure

- src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
- src/Mod/Sketcher/Gui/TaskSketcherElements.h
- src/Mod/Sketcher/Gui/TaskSketcherElements.ui
Improve the recently reworked Element widget.
It put the filter widget in a qactionmenu. Which looks much better, avoid resizing the task box.
This is following the good suggestion of @adrianinsaval 
This is matching the filter of currently opened 'Constraint widget rework' PR. …
> Sketcher: Element widget: Improve filter widget.

- src/Gui/RevitNavigationStyle.cpp
This fixes point 3 of the suggested changes from issue #5942, in short:
- Stops the rotation when scroll is released but SHIFT is still pressed
- Stops zooming when scroll is released but CTRL is still pressed
Issue #5942 also suggests some other things for the Revit navigation style. However, they deviate from the actual Revit navigation (tested in Revit 2023) so the other suggestions are not included.
Please remember to update the Wiki with the features added or changed once this PR is …
> Gui: Stop Revit rotation and zoom on scroll release

- src/Gui/Action.cpp
Problem solved:
In grouped actions (in toolbar), when user drops down then selects another action than the first, the tooltip is only partially updated.
Tooltip message is, but tooltip title isn't.
This leads to misleading situations
Solution proposed:
With this PR, the tooltip title is updated with the selected action text bringing consistency.
> Gui: ActionGroup also get its tooltip title updated

- src/Mod/AddonManager/AddonManagerTest/app/test_macro.py
- src/Mod/AddonManager/addonmanager_macro.py
Missed a change in the error handling code when adding translation strings to error messages.
> Addon Manager: Fix bad formatting in error handler

- src/Mod/Draft/drafttests/test_creation.py
This PR adds 3 unit tests:
test_shapestring (was already present as a dummy test)
test_workingplaneproxy
test_hatch
---
> Draft: test_creation.py add 3 tests

- src/Mod/Arch/ArchCutPlane.py
When using Arch_CutPlane on an object that is not a Component, the cut volume got a red shape color and a 75% transparency. The meant that the cut faces of the resulting object would also have these properties. To solve this `Draft.format_object()` is now applied to the cut volume.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=3&t=72070
---
> Arch: fix cutplane color

- .github/workflows/checks.yml
the building section of the CI might be faster like this, a run of the CI in my fork repo (so no ccache available yet) took more than 3.5h: https://github.com/adrianinsaval/FreeCAD/actions/runs/3559298775/jobs/5978923132
from my experience a clean (parallel) build without cache should take about 2.5h on github's runners:
https://github.com/adrianinsaval/pacman-repo/actions/runs/2382265820 …
> [github ci] run build in parallel

- src/Mod/AddonManager/ALLOWED_PYTHON_PACKAGES.txt
- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/AddonManagerTest/app/test_addon.py
- src/Mod/AddonManager/AddonManagerTest/app/test_macro.py
- src/Mod/AddonManager/AddonManagerTest/test_information.md
- src/Mod/AddonManager/package_details.py
Pretty self-explanatory. I also tacked on a small markdown tweek [11088a6](https://github.com/FreeCAD/FreeCAD/pull/7905/commits/11088a62ac2c43e440ba8db52a5ff10fa7ee6584), if that's OK?
> Addon Manager: Fix trailing whitespace

- src/Mod/TechDraw/Gui/TaskProjGroup.cpp
> QString.midRef is removed in Qt6

- src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
- src/Mod/Sketcher/Gui/TaskSketcherConstraints.h
This PR fixes most (if not all) the issues introduced by #7566 
@abdullahtahiriyo May you be kind to review ? These are quite massive changes at the end. Some changes are almost certainly suboptimal but may be reverted when we decide which parameters to keep as sketch-specific and which as global.
Also it would deserve to be refactored in a more elegant way, probably having the settings enclosed in a class inherited from QMenu. Again, I can probably tackle this when parameter owners are decided.
There are still things to see:
* Constraints hidden because "Show only filtered constraints" is set aren't correctly restored visible when same setting is disabled. Then they stay in virtual space even if filter is disabled completely
* Settings aren't translated directly when you change language. …
> Sketcher task constraint :  fix some issues introduced by PR #7566

- src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp
fixes #7931
Introduced by bf04c0e
@adrianinsaval may you please test it solves the issue for you ?
> [CrashFix]Sketcher: prevent crash at FC closure when edit control panel is disabled

- src/Mod/TechDraw/App/DrawGeomHatch.cpp
- src/Mod/TechDraw/App/DrawGeomHatch.h
- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/DrawViewSection.h
- src/Mod/TechDraw/Gui/QGIFace.cpp
- src/Mod/TechDraw/Gui/QGIFace.h
- src/Mod/TechDraw/Gui/QGIViewPart.cpp
- src/Mod/TechDraw/Gui/QGIViewSection.cpp
- src/Mod/TechDraw/Gui/TaskGeomHatch.cpp
- src/Mod/TechDraw/Gui/TaskGeomHatch.h
- src/Mod/TechDraw/Gui/TaskGeomHatch.ui
- src/Mod/TechDraw/Gui/TaskHatch.cpp
- src/Mod/TechDraw/Gui/TaskHatch.h
- src/Mod/TechDraw/Gui/TaskHatch.ui
- src/Mod/TechDraw/Gui/ViewProviderHatch.cpp
- src/Mod/TechDraw/Gui/ViewProviderHatch.h
- src/Mod/TechDraw/Gui/ViewProviderViewSection.cpp
Adjacent hatches should not use the exact same pattern...
- faces can have their svg and bitmap hatches rotated to match the view rotation or special situations
- section cut face can have svg hatch rotated
---
> [TD]allow rotation/shift of hatch patterns

- src/Mod/PartDesign/App/FeatureSketchBased.cpp
- src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
- src/Mod/PartDesign/Gui/TaskPadParameters.cpp
- src/Mod/PartDesign/Gui/TaskPocketParameters.cpp
- the error can also occur when the mode it not UpToFace (ToFirst or ToLast)
- also add note when Reversed checkbox is enabled since this is no obvious (as discussed in the forum)
- also some whitespace unification and include sorting
> [PD] Pad/pocket: fix wrong error message

- src/Mod/Raytracing/App/LuxProject.cpp
- src/Mod/Raytracing/App/PreCompiled.h
Currently in Manjaro/Arch/Linux there's this issue:
```
/.../src/Mod/Raytracing/App/LuxProject.cpp: In member function ‘virtual App::DocumentObjectExecReturn* Raytracing::LuxProject::execute()’:
/.../src/Mod/Raytracing/App/LuxProject.cpp:85:20: error: variable ‘std::ifstream file’ has initializer but incomplete type
85 |     ifstream file (fi.filePath().c_str());
|                    ^~
/.../src/Mod/Raytracing/App/LuxProject.cpp:89:20: error: variable ‘std::ofstream ofile’ has initializer but incomplete type
89 |     ofstream ofile(tempName.c_str());
|                    ^~~~~~~~
```
See https://stackoverflow.com/questions/50355130/variable-stdofstream-outfile-has-initializer-but-incomplete-type.
> [Raytracing] (Attempt to) fix compile issue in Raytracing

- src/Mod/Spreadsheet/Gui/qtcolorpicker.cpp
- "signals" is no longer accepted by Qt
- in QColorDialog::getColor the third argument must not be a nullptr
> [Spread] fix compilation issues with qtcolorpicker.cpp

- src/Gui/Language/Translator.h
This `memory` header is needed for `unique_ptr`, at least on Manjaro/Arch Linux with GCC.
> [GUI] Add missing include

- src/Mod/Draft/draftgeoutils/general.py
- src/Mod/Draft/draftmake/make_sketch.py
This PR fixes 3 make_sketch bugs:
1. The last segment of an unrotated Rectangle was not constrained horizontally/vertically.
2. The `isAligned` function worked without a tolerance. This meant that none of the edges of a 90 degree rotated Rectangle was constrained horizontally/vertically.
3. Filleted Wires, Rectangles and Polygons where skipped. [Forum topic](https://forum.freecadweb.org/viewtopic.php?f=23&t=74194).
---
> Draft: fix make_sketch bugs

- src/Mod/TechDraw/App/EdgeWalker.cpp
- boost check for planar graph was consuming memory until crashing.
- since all our edges have been projected onto a plane, we don't require this check
---
> [TD]remove problematic boost check for planarity

- src/Mod/AddonManager/AddonManagerTest/app/test_installer.py
- src/Mod/AddonManager/addonmanager_installer.py
Simplify the new Addon Manager API: the list of addons is not needed by that section of the code.
> Addon Manager: Tweak API

- src/Mod/TechDraw/App/DrawComplexSection.cpp
- src/Mod/TechDraw/App/DrawComplexSection.h
- src/Mod/TechDraw/App/DrawView.cpp
- src/Mod/TechDraw/App/DrawViewDetail.cpp
- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewPart.h
- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/DrawViewSection.h
- src/Mod/TechDraw/App/GeometryObject.cpp
- src/Mod/TechDraw/App/GeometryObject.h
- src/Mod/TechDraw/Gui/QGIViewPart.cpp
- src/Mod/TechDraw/Gui/TaskComplexSection.cpp
- src/Mod/TechDraw/Gui/TaskComplexSection.h
- src/Mod/TechDraw/Gui/TaskSectionView.cpp
- src/Mod/TechDraw/Gui/TaskSectionView.h
- src/Mod/TechDraw/Gui/ViewProviderDimension.cpp
- src/Mod/TechDraw/Gui/Widgets/CompassWidget.cpp
- src/Mod/TechDraw/Gui/Widgets/CompassWidget.h
- src/Mod/TechDraw/Gui/Widgets/VectorEditWidget.cpp
- src/Mod/TechDraw/Gui/Widgets/VectorEditWidget.h
addresses items raised in user testing of ComplexSections.  https://www.forum.freecadweb.org/viewtopic.php?p=645399#p645399
---
> [TD]ComplexSection Fixes

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/AddonManagerTest/app/mocks.py
- src/Mod/AddonManager/AddonManagerTest/app/test_dependency_installer.py
- src/Mod/AddonManager/AddonManagerTest/app/test_installer.py
- src/Mod/AddonManager/AddonManagerTest/app/test_macro.py
- src/Mod/AddonManager/AddonManagerTest/app/test_uninstaller.py
- src/Mod/AddonManager/AddonManagerTest/gui/gui_mocks.py
- src/Mod/AddonManager/AddonManagerTest/gui/test_installer_gui.py
- src/Mod/AddonManager/AddonManagerTest/gui/test_uninstaller_gui.py
- src/Mod/AddonManager/CMakeLists.txt
- src/Mod/AddonManager/TestAddonManagerApp.py
- src/Mod/AddonManager/TestAddonManagerGui.py
- src/Mod/AddonManager/addonmanager_devmode.py
- src/Mod/AddonManager/addonmanager_installer.py
- src/Mod/AddonManager/addonmanager_macro.py
- src/Mod/AddonManager/addonmanager_uninstaller.py
- src/Mod/AddonManager/addonmanager_uninstaller_gui.py
Refactor the uninstaller to provide a stable API to external code, separating GUI and non-GUI code, and adding tests for each.
> Addon Manager: refactor uninstall

- src/Gui/DlgSettingsNavigation.ui
- src/Gui/NavigationStyle.cpp
- src/Gui/NavigationStyle.h
- src/Mod/Tux/NavigationIndicatorGui.py
Adding a second Turntable orbit style but without primary rotation selection.
This aims to offer an environment similar to Blender.
---
> Gui: Added FreeTurntable orbit style

- src/Mod/AddonManager/AddonManagerTest/gui/gui_mocks.py
- src/Mod/AddonManager/AddonManagerTest/gui/test_installer_gui.py
- src/Mod/AddonManager/AddonManagerTest/gui/test_uninstaller_gui.py
Some incorrect translation contexts for dialog title strings are fixed, and the button search is switched to search for the Qt constants rather than the actual button text.
Fixes #8065
> Addon Manager: Fix test language dependency

- src/App/Document.h
- src/Gui/Application.cpp
- src/Gui/Application.h
- src/Gui/CommandDoc.cpp
- src/Gui/Document.cpp
- src/Mod/Part/App/Geometry.cpp
- src/Mod/Sketcher/App/Constraint.h
- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/Sketch.h
- src/Mod/Sketcher/App/SketchGeometryExtension.h
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandlerSplitting.h
- src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
- src/Mod/Web/Gui/BrowserView.cpp
Supercedes PR #6494. I expect to make some major changes to the method for a bit more code-reuse, ~so it's best to keep that PR as is~. 
UPDATE [2 July 2022]: After the recent removal of `DrawSketchHandlers` from `CommandCreateGeo.cpp` into their own classes, I chose to drop #6494 and only rebase this one.
Solves #5835.
Known issues:
1. Splitting parabolas makes constraints malformed. See issue #6969.
> Sketcher: Split more curves

- src/Mod/Draft/draftviewproviders/view_base.py
- src/Mod/Draft/draftviewproviders/view_bezcurve.py
- src/Mod/Draft/draftviewproviders/view_bspline.py
- src/Mod/Draft/draftviewproviders/view_dimension.py
- src/Mod/Draft/draftviewproviders/view_draft_annotation.py
- src/Mod/Draft/draftviewproviders/view_fillet.py
- src/Mod/Draft/draftviewproviders/view_hatch.py
- src/Mod/Draft/draftviewproviders/view_label.py
- src/Mod/Draft/draftviewproviders/view_layer.py
- src/Mod/Draft/draftviewproviders/view_shapestring.py
- src/Mod/Draft/draftviewproviders/view_text.py
- src/Mod/Draft/draftviewproviders/view_wire.py
This PR tries to improve the context menus of Draft objects.
Main changes:
1. Added an `Edit` option (for objects that can be edited). Similar to Part objects.
2. Objects without a face or that can only have a single face, no longer have a `Set colors...` option. This was previously only implemented for Hatches.
3. The Draft workbench is automatically loaded if required. This was previously only implemented for Shapestrings.
4. For most objects Edit modes 0 and 3 are handled. Edit mode 3 defaults to 0.
The automatic workbench loading may require some form of user confirmation ("Do you really want to..."). But let's first wait and see if users comment.
Some of the viewproviders files (view_bezcurve.py f.e.) have now become empty wrappers, but it is better to keep them for future use.
There …
> Draft: improve context menus

- src/Mod/Sketcher/App/GeometryFacade.h
- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/Sketch.h
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/planegcs/Constraints.cpp
- src/Mod/Sketcher/App/planegcs/Constraints.h
- src/Mod/Sketcher/App/planegcs/GCS.cpp
- src/Mod/Sketcher/App/planegcs/GCS.h
- src/Mod/Sketcher/App/planegcs/Geo.cpp
- src/Mod/Sketcher/App/planegcs/Geo.h
- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/Utils.cpp
With these changes, a line segment can be made tangent to a B-spline at a given knot. It also contains commits from #7484 since we need to constraint knot on to the line segment.
This PR is part of [the B-spline constraint project](https://forum.freecadweb.org/viewtopic.php?f=9&t=71130).
See known issues [here](https://forum.freecadweb.org/viewtopic.php?f=9&t=71130&start=100#p632599).
> [Sketcher] Constraint tangent at B-spline knot

- src/Mod/Start/StartPage/StartPage.py
due to the changes from #7955
reported in https://forum.freecadweb.org/viewtopic.php?p=649107#p649107
should also be backported IMO, this is how it's currently shown in stable release
> Adjust Startpage version info to new format

- src/Mod/Draft/draftfunctions/upgrade.py
This PR changes the Draft upgrade function so that it returns the new object when it's a draftify.  (Like the wiki documentation says, and like the other types of upgrade do)
> DRAFT: Make "draftify" type upgrades return the new object

- src/Mod/Draft/draftguitools/gui_snapper.py
Fixes #8079.
`getargspec` has been removed from the `inspect` module in Python 3.11.
See: https://docs.python.org/3/whatsnew/3.11.html
> Draft: update inspect.getargspec to inspect.getfullargspec

- src/Mod/Path/Path/Post/Command.py
- src/Mod/Path/Path/Post/UtilsArguments.py
- src/Mod/Path/Path/Post/UtilsExport.py
- src/Mod/Path/Path/Post/UtilsParse.py
- src/Mod/Path/Path/Post/scripts/refactored_centroid_post.py
- src/Mod/Path/Path/Post/scripts/refactored_grbl_post.py
- src/Mod/Path/Path/Post/scripts/refactored_linuxcnc_post.py
- src/Mod/Path/Path/Post/scripts/refactored_mach3_mach4_post.py
- src/Mod/Path/Path/Post/scripts/refactored_test_post.py
- src/Mod/Path/PathTests/TestRefactoredTestPost.py
This is the next chunk of changes for the "refactored" postprocessor work.  It incorporates feedback from the code reviews for a previous (but too complex) pull request that was split up into smaller pull requests.  This PR includes:
Reformatted to a line length of 88 using black.
Incorporating feedback; now using f-strings all over.
Incorporating changes from feedback.
Incorporated more refactoring feedback.
Changes for Path refactoring.
This is part of the work for issue #6117.
Please …
> Path:  Incorporating feedback from code reviews

- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
The oldest version we plan to support is 7.0.0 (which comes with Ubuntu 20.04).
See https://forum.freecadweb.org/viewtopic.php?f=10&p=650487#p650487.
> [Sketcher] Delete check for OCC >= 6.9.0

- src/Mod/Arch/ArchSite.py
Props to david69 https://crowdin.com/translate/freecad/6766/en-fr#6604817
> Crowdin: [skip ci] fix string in `Arch/ArchSite.py`

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
https://forum.freecadweb.org/viewtopic.php?p=650988#p650988
* The function ViewProviderSketch::isSelected should not modifiy its incoming parameter
* ViewProviderSketch::rmvSelection, ViewProviderSketch::addSelection, ViewProviderSketch::addSelection2 have not called the convertSubName function.
* Should the convertSubName not be called inside the function ViewProviderSketch::mouseButtonPressed, because now the convertSubName is called two times?
> Fix selection in sketcher development/toponaming

- .clang-format
---
I have made a few changes to clang-format and am …
> improved clang-format

- src/Mod/Sketcher/App/SketchObject.cpp
=======================================================================
In uncommon situations, the analysis of QR decomposition leads to full rank, but the result does not converge.
We avoid marking a sketch as fully constrained when no convergence is achieved.
> Sketcher: Do not mark as fully constrained sketches that do not converge

- src/Gui/CommandWindow.cpp
- src/Gui/Language/FreeCAD.ts
- src/Gui/MainWindow.cpp
- src/Gui/MainWindow.h
- src/Gui/Workbench.cpp
- src/Mod/Web/Gui/Workbench.cpp
In "Windows" menu there is option named "Arrange icons". Activating this command do the same thing as "Tile" command.
I think this should be removed because of duplication and misleading name.
Even on wiki this thing is described as obsolete: https://wiki.freecadweb.org/Std_Windows_Menu
I have removed command, menu entry and method MainWindow::arrangeIcons. 
I hope no 3rd party addon use `Gui.getMainWindow().arrangeIcons()`. :)
---
Please remember to update the Wiki with the features …
> [GUI] Removal of StdCmdArrangeIcons

- src/Mod/Draft/draftgeoutils/wires.py
This PR simplifies the wires.isReallyClosed function. For wires it just calls the isClosed method. This should avoid the false positive mentioned in the forum topic. Over time we should remove the isReallyClosed function.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?p=652171#p652171
---
> Draft: improve wires.isReallyClosed

- src/Mod/Arch/ArchSectionPlane.py
`FreeCADGui.ActiveDocument.ActiveView` can show a TechDraw page in which case it does not have a `getSceneGraph` attribute.
---
> Arch: fix ArchSectionPlane getSceneGraph problem

- src/Mod/AddonManager/AddonManagerOptions.ui
This PR switches pref entry/path from string to constant string for 2 AddonManager preferences were it was faulty.
The current situation has 2 problems :
* The 2 prefs entry/path are translatable (and translated) which can lead to different issues (non ASCII chars, preferences loss when changing language, ...)
* When opening the preference editor, 2 "Widget is already attached" warning messages are displayed
@chennes May you check this commit doesn't conflict with your current dev and either merge or cherry-pick ?
> AddonMgr: switch pref entry/path to const string

- src/Mod/Arch/ArchSectionPlane.py
The SVG result of an ArchSectionPlane would not update after moving a window for example. You would have to change a property of the plane first.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?p=652810#p652810
---
> Arch: ArchSectionPlane should trigger SVG update in execute

- src/Mod/Draft/Resources/ui/preferences-drafttexts.ui
- src/Mod/Draft/draftfunctions/svg.py
- src/Mod/Draft/draftmake/make_label.py
- src/Mod/Draft/draftmake/make_text.py
- src/Mod/Draft/draftobjects/dimension.py
- src/Mod/Draft/draftobjects/draft_annotation.py
- src/Mod/Draft/draftobjects/label.py
- src/Mod/Draft/draftobjects/text.py
- src/Mod/Draft/draftviewproviders/view_dimension.py
- src/Mod/Draft/draftviewproviders/view_draft_annotation.py
- src/Mod/Draft/draftviewproviders/view_label.py
- src/Mod/Draft/draftviewproviders/view_text.py
Fixes #7861.
This is a somewhat involved PR as it touches multiple files. Also while working I discovered some problems with how the viewprovider classes were organized. Code related to the setting of properties would be called up to 6 times when an object was created.
When dimension text was aligned with the screen it was handled differently (a factor 10 was applied to the FontSize) from Draft_Text and Draft_Label objects. I have removed that (and the related extra font node). There are still other things that seem inconsistent to me, but that may also be due to my lack of coin knowledge. …
> Draft: Fix inconsistent properties of Draft annotations

- src/Mod/Arch/ArchAxis.py
- src/Mod/Arch/ArchAxisSystem.py
- src/Mod/Arch/ArchBuildingPart.py
- src/Mod/Arch/ArchCommands.py
- src/Mod/Arch/ArchComponent.py
- src/Mod/Arch/ArchGrid.py
- src/Mod/Arch/ArchIFCView.py
- src/Mod/Arch/ArchMaterial.py
- src/Mod/Arch/ArchPanel.py
- src/Mod/Arch/ArchPrecast.py
- src/Mod/Arch/ArchProfile.py
- src/Mod/Arch/ArchRebar.py
- src/Mod/Arch/ArchReference.py
- src/Mod/Arch/ArchRoof.py
- src/Mod/Arch/ArchSchedule.py
- src/Mod/Arch/ArchSectionPlane.py
- src/Mod/Arch/ArchSite.py
- src/Mod/Arch/ArchSpace.py
- src/Mod/Arch/ArchStructure.py
- src/Mod/Arch/ArchWall.py
- src/Mod/Arch/ArchWindow.py
- src/Mod/Draft/draftviewproviders/view_base.py
This PR tries to improve the context menus of Arch objects. Similar to what was previously done for Draft objects, see #7970.
Small improvement related to #6215:
The BIM Workbench gets loaded only once per session when double clicking components.
---
> Arch: improve context menus

- src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
Fixes #8104.
As described in that issue, a crash happens under the following conditions:
1. A `DrawSketchHandler` is active.
2. No constraint is selected.
3. Context menu on the `ConstraintView` is triggered.
> [Sketcher] Prevent dereferencing `nullptr` in `ConstraintView`

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/AddonManagerTest/gui/gui_mocks.py
- src/Mod/AddonManager/AddonManagerTest/gui/test_installer_gui.py
- src/Mod/AddonManager/AddonManagerTest/gui/test_update_all_gui.py
- src/Mod/AddonManager/AddonManagerTest/gui/test_workers_startup.py
- src/Mod/AddonManager/AddonManagerTest/gui/test_workers_utility.py
- src/Mod/AddonManager/addonmanager_installer_gui.py
- src/Mod/AddonManager/addonmanager_uninstaller_gui.py
- src/Mod/AddonManager/addonmanager_update_all_gui.py
- src/Mod/AddonManager/addonmanager_utilities.py
The GUI unit tests were throwing some errors when run on some flavors of Linux: this turned out to be due primarily to my use of `terminate()` to forcibly kill threads that didn't respond to `quit()` in a timely manner. I've refactored to eliminate those calls to `terminate()`, as well as to make a few other tweaks to the tests that should make them faster, more concise, and more reliable (not hanging when the tests fail, etc.).
> Addon Manager: Fix GUI unit tests on Linux

- src/Mod/Part/App/BSplineCurvePyImp.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h
The infinite loop already doesn't happen, but the generated B-spline is still ill-formed if the degree is set to too high.
> Part/Sketcher: fix #8143

- src/Mod/Path/PathTests/TestPathAdaptive.py
While I'm working at CI and especially on having GUI tests with it, below error message came :
```
======================================================================
ERROR: test00 (PathTests.TestPathAdaptive.TestPathAdaptive)
----------------------------------------------------------------------
File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
yield
File "/usr/lib/python3.10/unittest/case.py", line 587, in run
self._callSetUp()
File "/usr/lib/python3.10/unittest/case.py", line 546, in _callSetUp
self.setUp()
File "/usr/local/Mod/Path/PathTests/TestPathAdaptive.py", line 95, in setUp
self.initClass()
File "/usr/local/Mod/Path/PathTests/TestPathAdaptive.py", line 64, in initClass
job.ViewObject.Proxy = …
```
> Path: fix bug in Path Gui tests

- src/Mod/Draft/Draft.py
- src/Mod/Draft/Resources/ui/dialog_AnnotationStyleEditor.ui
- src/Mod/Draft/draftfunctions/svg.py
- src/Mod/Draft/draftfunctions/svgshapes.py
- src/Mod/Draft/draftguitools/gui_annotationstyleeditor.py
- src/Mod/Draft/draftutils/utils.py
- src/Mod/Draft/draftviewproviders/view_draft_annotation.py
This PR fixes multiple issues with the [Draft_AnnotationStyleEditor](https://wiki.freecadweb.org/Draft_AnnotationStyleEditor) command. A button was added for the text color. The line color button was moved.
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=3&t=73222
It is probably a good idea to look at the Draft_AnnotationStyleEditor and [Draft_SetStyle](https://wiki.freecadweb.org/Draft_SetStyle) commands together at some later date. There is a lot of overlap as well as some inconsistencies.
---
> Draft: Fix and improve Draft_AnnotationStyleEditor

- src/Mod/Sketcher/App/SketchObject.cpp
Fixes #7770.
Until Point-on-B-spline (#7782) is actually merged this will result in a malformed constraint. It will however still allow a trim of the B-spline to result in a coincident constraint.
> [Sketcher] Do not filter out point-on-B-spline when trimming

- src/Mod/Sketcher/App/planegcs/Constraints.h
- the type change fixes this error: \src\Mod\Sketcher\App\planegcs\Constraints.cpp(509,54): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
- the scone change removes a non-existing definition
> [Sketch] Constraints.h: fix 2 compiler warnings

- CMakeLists.txt
---
Ubuntu 18.04 LTS ends early '23.
Logically master branch should now be targeting 20.04 which has 3.16.3-1ubuntu1.20.04.1.
This change also makes available a bunch of cmake enhancements.
> Bump minimum cmake version to 3.16.3

- src/Gui/ExpressionCompleter.cpp
- src/Gui/ExpressionCompleter.h
I've added support to do path completions after a property is selected in the auto completer line edit.
This allows:
It also fixes some UX issues I had with the completer - chaining completions when pressing Enter should work.
It is not perfect, as it cannot complete sub-path components, and has other limitations.
- `Sketch.Placement.` will propose `Base.x`, `Base.y`,... `Rotation.Angle`, `Rotation.Axis.x`
- `Sketch.Placement.Rotation.A` will fail to complete as the path split "Sketch/Placement/Rotation/A" is not in the completion tree, only Sketch/Placement/Rotation.Axis.x is 
- I don't believe arrays will work, if there isn't a named structure in place the completer will not have that in the completion tree: `Object.Prop[10].Something` will not work, as `Prop[10]` is not in the tree. …
> Expressions: path auto-completion fixes

- src/Gui/ExpressionCompleter.cpp
> Cleanup issues of PR 8228

- src/Mod/Part/Gui/SectionCutting.cpp
- src/Mod/Part/Gui/SectionCutting.h
- src/Mod/Part/Gui/SectionCutting.ui
- a typical use-case is to open a document with an existing cut and only this cut is visible. When now opening the section cutting tool, the user got the fault message that there were no visible objects to be cut.
- the transparency for the cut was not explicitly set. Therefore the default transparency for new objects was used instead of the transparency of the objects to be cut.
- workaround for a graphics issue: when cutting objects intersection each other (only then) the transparency setting is often ignored. The fix is simply to change the default color slightly. (By the way, this issue is independent on the color that is set in the Part preferences as color for new objects, seems to be a  graphics driver or OCC issue.)
- also avoid to recompute all cuts on color change. This it is …
> [Part] fixes for the section cutting feature

- src/Mod/Part/Gui/SectionCutting.cpp
It segfaults when executing the script below:
```
doc = App.ActiveDocument
box = doc.addObject("Part::Box", "SectionCutBoxX")
comp = doc.addObject("Part::Compound", "SectionCutCompound")
comp.Links = box
grp = doc.addObject("App::DocumentObjectGroup", "SectionCutX")
grp.addObject(comp)
doc.recompute()
```
> Part: fix crash in SectionCutting dialog

- src/Gui/DlgSettingsNavigation.cpp
- src/Gui/DlgSettingsNavigation.ui
- src/Gui/NaviCube.cpp
- src/Gui/NaviCube.h
- src/Gui/View3DInventorViewer.cpp
- src/Gui/View3DInventorViewer.h
- the problem is that depending on the OS, the font of the NaviCube is hardly readable. For example under Windows 11, there is no Helvetica font and therefore an ugly replacement font is used. On some laptop screens the font is too large or too small etc.
- as solution this PR add the change the NaviCube's font and font size
- the PR also fixes an issue that the position (corner) of the NaviCube was not respected when the NaviCube is recreated. This fix is necessary for the PR therefore included
- as by-product the PR fixes #8082 since every change in the preferences now properly recreates the NaviCube
- the PR also removes the strange and unused class "HuuhaaClassPy"
Here is the new NaviCube settings implemented by this PR:
> [Gui] allow to specify font for NaviCube

- src/Mod/Draft/drafttests/test_modification.py
The PR updates test_modification.py.
Two functions, `test_move` and `test_rotate`, needed to be adapted in relation to #8267.
All tolerances were changed to 1e-6.
---
> Draft: Update test_modification.py

- src/Gui/NaviCube.cpp
- it turned out that DejaVu Sans is not the best font since its letters are wide. Bahnschrift was designed to run narrow and it at least on all Win 10 since 2017. Therefore use this, if possible
> [Gui] NaviCube: improve default font

- src/Gui/View3DInventorViewer.cpp
- use sizeof instead of the hardcoded number
> [Gui] View3DInventorViewer: fix a GH action report

- src/Mod/Arch/ArchPrecast.py
This PR fixes #7765.
Additionally:
* Introduced a 'null shape' warning in case of invalid property values. The behavior is similar to f.e. Arch_Wall. If the object does not yet exist no shape is created. If the object already exists the old shape is retained. In both case the warning is displayed.
* Input fields in the 2nd section of the task panel now show units. This avoids the problem where, if a comma was used as the decimal separator, values would by multiplied by 10 after each use of the command.
---
> Arch: Fix ArchPrecast.py issues

- src/Mod/Arch/ArchCommands.py
Fixes #6013.
PD Bodies that were used as a base feature for other PD Bodies ([PartDesign_Clone](https://wiki.freecadweb.org/PartDesign_Clone)) were excluded by `Arch.pruneIncluded`.
---
> Arch: update Arch.pruneIncluded to include cloned PD Bodies

- src/Mod/Draft/draftfunctions/move.py
- src/Mod/Draft/draftfunctions/rotate.py
- src/Mod/Draft/draftguitools/gui_base_original.py
- src/Mod/Draft/draftmake/make_point.py
- src/Mod/Draft/draftobjects/array.py
- src/Mod/Draft/draftobjects/base.py
- src/Mod/Draft/draftobjects/bezcurve.py
- src/Mod/Draft/draftobjects/block.py
- src/Mod/Draft/draftobjects/bspline.py
- src/Mod/Draft/draftobjects/circle.py
- src/Mod/Draft/draftobjects/clone.py
- src/Mod/Draft/draftobjects/draftlink.py
- src/Mod/Draft/draftobjects/ellipse.py
- src/Mod/Draft/draftobjects/facebinder.py
- src/Mod/Draft/draftobjects/hatch.py
- src/Mod/Draft/draftobjects/patharray.py
- src/Mod/Draft/draftobjects/pathtwistedarray.py
- src/Mod/Draft/draftobjects/point.py
- src/Mod/Draft/draftobjects/pointarray.py
- src/Mod/Draft/draftobjects/polygon.py
- src/Mod/Draft/draftobjects/rectangle.py
- src/Mod/Draft/draftobjects/shape2dview.py
- src/Mod/Draft/draftobjects/shapestring.py
- src/Mod/Draft/draftobjects/wire.py
- src/Mod/Draft/drafttaskpanels/task_shapestring.py
This PR fixes #8044.
Two techniques are used:
1. Do not recompute inside the transaction.
2. Avoid the creation of a new Shape if only the Placement is changed.
Instead of updating all draftguitools, the recompute is removed from `self.commitList` in the `finish` function of the `DraftTool` class (see gui_base_original.py).
Only updating a Shape when required has the added advantage that f.e. moving a complex object such as a [Draft_ShapeString](https://wiki.freecadweb.org/Draft_ShapeString) or a [Draft_Shape2DView](https://wiki.freecadweb.org/Draft_Shape2DView) is almost instantaneous.
---
> Draft: fix issue with undo

- src/Mod/Draft/draftfunctions/move.py
- src/Mod/Draft/draftfunctions/rotate.py
- src/Mod/Draft/draftfunctions/scale.py
- src/Mod/Draft/draftguitools/gui_move.py
- src/Mod/Draft/draftguitools/gui_rotate.py
- src/Mod/Draft/draftguitools/gui_scale.py
Subelement mode of Draft_Move, Draft_Rotate and Draft_Scale ignored the nesting of the selected elements.
---
> Draft: subelement mode ignored nesting

- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/DrawViewSection.h
- src/Mod/TechDraw/Gui/QGIViewSection.cpp
- src/Mod/TechDraw/Gui/QGIViewSection.h
This PR addresses issue raised here; https://www.forum.freecadweb.org/viewtopic.php?f=35&t=75533&sid=66b5084cb840bfca92a6d4b14500d217
Investigating the hatch anomaly revealed 2 other problems with sections of sections - section line was not displayed if base view was a section and the shape used in a section was the original base view shape.
- [x ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTIN …
> [TD]Fix hatch anomaly

- src/Mod/Fem/femsolver/solver_taskpanel.py
- when an error occurred during the Write process, the Edit button must not be enabled In this case the machine state is still at femsolver.run.PREPARE. If no error occurred it went one step up.
> [FEM] solver_taskpanel: fix bug with Edit button

- src/Mod/Fem/femsolver/elmer/writer.py
- if user set no material for a body, we must raise an error
- also fix annoying output of permittivity in case.sif file
> [FEM] Elmer: fix error on wrong material settings

- src/Mod/Part/App/Tools.cpp
Mesh generation parameters are taken from PrusaSlicer's STEP importer, which does a just-in-time STEP->STL conversion in memory.
Resulting meshes have better geometry, but are a little larger as a result.
---
> [Part] Tweak mesh generation

- src/Mod/Start/Gui/DlgStartPreferences.ui
- src/Mod/Start/Gui/DlgStartPreferencesImp.cpp
- src/Mod/Start/StartPage/StartPage.css
- src/Mod/Start/StartPage/StartPage.py
This adds an option to the Start preferences that allow to hide the scrollbars on the start page. They are drawn in a different style than the other FreeCAD scrollbars, so they are ugly :) Scrolling with the mousewheel still works. …
> Start: Added option to hide start page scrollbars

- src/Mod/Material/StandardMaterial/Copper-Generic.FCMat
- the conductivity was by a factor 100 too low, use a common value as fix
> [Material] fix conductivity of Copper

- src/Mod/Draft/drafttests/test_modification.py
The DiffuseColor workaround requires a delay in the Draft_Clone unit test.
See https://forum.freecadweb.org/viewtopic.php?p=656362#p656362
---
> Draft: add delay in the Draft_Clone unit test

- src/Mod/Draft/draftviewproviders/view_dimension.py
`math.asin(halfarrowlength / radius)` would fail if halfarrowlength was larger than radius.
---
> [Draft] fix ang dim arrows alignment issue related to asin

- src/Mod/Fem/App/FemMesh.cpp
- src/Mod/Fem/App/FemMeshObject.cpp
- src/Mod/Fem/App/FemPostFilter.cpp
- src/Mod/Fem/App/FemPostFilter.h
- src/Mod/Fem/App/FemPostObject.cpp
- src/Mod/Fem/App/FemPostObject.h
- src/Mod/Fem/App/FemPostPipeline.cpp
- src/Mod/Fem/App/FemVTKTools.cpp
- src/Mod/Fem/App/PropertyPostDataObject.cpp
- src/Mod/Fem/Gui/Command.cpp
- src/Mod/Fem/Gui/TaskObjectName.cpp
- src/Mod/Fem/Gui/TaskPostBoxes.cpp
- src/Mod/Fem/Gui/TaskPostBoxes.h
- src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostPipeline.cpp
- reformatting was done by the MSVC formatter according to our current clang file
> [FEM] shorten too long lines in mesh code

- src/Mod/Fem/CMakeLists.txt
- src/Mod/Fem/femsolver/elmer/equations/electrostatic_writer.py
- src/Mod/Fem/femsolver/elmer/writer.py
- the writer.py is to large to keep the overview, thus sort out the handling of the different equations (also since more equations will be added)
- This PR sorts out the electrostatic equation handling is the test balloon if this works well (local tests are all OK)
> [FEM] Elmer: refactor writer

- src/Mod/Fem/Gui/Command.cpp
- the elctricforce equation is actually a postprocessor and thus should not be first in the list, but after the electrostatics equation (where it belongs to technically)
- also change menu name to be consistent with the other FEM menus
> [FEM] Elmer: better sorting of equations

- src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp
- src/Mod/Spreadsheet/Gui/CMakeLists.txt
- src/Mod/Spreadsheet/Gui/SheetTableViewAccessibleInterface.cpp
- src/Mod/Spreadsheet/Gui/SheetTableViewAccessibleInterface.h
Windows Accesibility will try to navigate through all the cells of the table, causing memory use and a 30 second freeze in the application. It can be reproduced by copying or selecting in an empty spreadsheet.
Issue Ref: https://github.com/FreeCAD/FreeCAD/issues/8265 
The proper solution is to implement a correct accessible interface for the SheetTableView, rather than rely on the built-in QT one.
This PR is the alternate solution - a workaround :( to disable the built-in accessibility support :( which is causing the delay.
APPSpreadSheetGui.cpp was reformatted using the latest rules.
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD …
> [workaround][GUI][Spreadsheet] Disable Accessibility on the SpreadSheetTableView

- src/Mod/Fem/Gui/Resources/ui/ElectrostaticPotential.ui
- src/Mod/Fem/femobjects/constraint_electrostaticpotential.py
- src/Mod/Fem/femtaskpanels/task_constraint_electrostaticpotential.py
- it is now possible to specify an electric potential vector field, necessary for electromagnetic analyses
- existing electrostatic analyses are not affected since the new values are not evaluated for them
> [FEM] Elmer: extend potential constraint

- src/Mod/Fem/femsolver/elmer/equations/magnetodynamic2D_writer.py
- src/Mod/Fem/femsolver/elmer/writer.py
- src/Mod/Fem/femtaskpanels/task_constraint_magnetization.py
- src/Mod/Material/MaterialEditor.py
- src/Mod/Material/StandardMaterial/TEMPLATE.FCMat
- src/Mod/Material/Templatematerial.yml
- src/Mod/Material/materialtools/cardutils.py
- uses the constraint for 2D magnetodynamics to perform e.g. Elmer's tutorial non. 15
- modify the Material manager to get rid of magnetization but keep the vectorial functionality because in future there will be support for e.g. birefringence materials etc.
> [FEM] use magnetization constraint for 2D

- src/Mod/Fem/Gui/Resources/ui/CurrentDensity.ui
- src/Mod/Fem/Gui/Resources/ui/Magnetization.ui
- src/Mod/Fem/femobjects/constraint_currentdensity.py
- src/Mod/Fem/femsolver/elmer/equations/magnetodynamic2D_writer.py
- src/Mod/Fem/femtaskpanels/task_constraint_currentdensity.py
- to be used also for the magnetodynamic 3D equation
- use the changed current density for the existing 2D equation, this way fix issue that it was not possible to specify imaginary current density
- also fix bug that there is no z-component of magnetization for the 2D equation
- also correct a label name in magnetization UI-file
> [FEM] extend current density to 3D

- src/Mod/Fem/femviewprovider/view_base_femobject.py
- the typical workflow is to change e.g. a constraint setting or material property and to check how and if this change changes the simulation result. It is therefore very annoying that on every call of a task panel the results are hidden.
- This PR changes this to hide only meshes and the filter functions but to keep the results. If a user don't like to see results for example to select faces, he hides results anyway.
> [FEM] change hiding logic on calling task panels

- src/Mod/AddonManager/Addon.py
Introduces a new function into Addon for getting the relative path to the icon. This ultimately results in the deprecation of the previous function. That function is left in place by this commit so that code can continue to use it. It will be removed when the full refactoring is complete.
---
> Addon Manager: Prep Addon for refactoring

- src/Mod/Material/MaterialEditor.py
- it is very annoying to get a dozen decimals on editing floats. 6 do the job for all cases and a spinBox is preferred
> [Material] editor: improve float input

- src/Mod/Draft/draftmake/make_clone.py
- src/Mod/Draft/draftviewproviders/view_clone.py
The `gui_utils.get_diffuse_color` function introduced with #8427 makes the `resetColors` method of the viewprovider obsolete.
Additionally:
The `reapply_diffuse_color` workaround in make_clone.py was not used for arch objects.
---
> [Draft] update of Draft_Clone related to gui_utils.get_diffuse_color

- src/Mod/Draft/draftobjects/array.py
- src/Mod/Draft/draftobjects/draftlink.py
The non-Link versions of Draft_OrthoArray, Draft_PolarArray and Draft_CircularArray did not have a `Count` property. This has been remarked upon before (in a Fasteners BOM related discussion). But the property can also used 'internally', for example when generating a `DiffuseColor` value.
---
> [Draft] some arrays did not have a Count property

- src/Mod/Draft/draftmake/make_array.py
- src/Mod/Draft/draftmake/make_patharray.py
- src/Mod/Draft/draftmake/make_pointarray.py
- src/Mod/Draft/draftviewproviders/view_array.py
Applying the DiffuseColor when creating arrays would fail. In some cases the value was incorrect for the number of faces of the array object. In all cases a workaround is required to actually show the applied color.
---
> [Draft] fix diffuse color issue when creating arrays

- src/Mod/Draft/draftutils/gui_utils.py
Fixed typo in `draftutils/gui_utils.py`
---
> Draft: [skip ci] fix typo in source comment

- src/App/Document.cpp
- src/Gui/DlgProjectInformationImp.cpp
- src/Gui/DlgSettingsDocument.ui
- src/Gui/DlgSettingsDocumentImp.cpp
---
CERN maintains 3 versions of an open hardware license ([https://ohwr.org/project/cernohl/wikis/Documents/CERN-OHL-version-2](https://ohwr.org/project/cernohl/wikis/Documents/CERN-OHL-version-2)). There are [some …
> Gui: Add CERN OHL to default licenses list

- src/App/License.cpp
- does otherwise not compile on Windows
> [App] License.cpp: add missing include

- src/Mod/Part/Gui/SectionCutting.cpp
- src/Mod/Part/Gui/SectionCutting.h
- src/Mod/Part/Gui/SectionCutting.ui
- it is a well-known and often feed-backed missing feature that SectionCuttings fails for intersecting objects. To resolve this, the objects must be put int a BooleanFragments object.
- this PR adds this functionality as option.
- since a BooleanFragments objects has a specific color, the different colors of the objects cannot be preserved. Because of this disadvantage, the BooleanFragments option will not be the default.
- the PR includes the fixes from #8251
Here is the result with master:
And here with the PR:
> [Part] extend SectionCutting feature for intersecting objects

- src/Mod/PartDesign/PartDesignTests/TestInvoluteGear.py
- src/Mod/PartDesign/fcgear/involute.py
- src/Mod/PartDesign/fcgear/svggear.py
Previously, the fillet started at a fixed value, tailored at 20° pressure angle, a fillet radius of 0.375 and a dedendum of 1.25. With PR #8184 those values became user-adjustable and thus the assumptions of the original code are not fullfilled any more. This resulted in significant artefacts, especially for higher pressure angles or smaller dedendums as commonly found in splines.
This commit actually calculates the junction between fillet and involute so that the tangents of the both curves match. The mathematical approach is described in source code comments.
The change in the fillet calculation also affects compatibility with files generated by earlier versions of FreeCAD. Those changes are way below 0.1% per tooth, however the earlier test required absolute equality down to the …
> PD: Improve InvoluteGear's fillets

- .github/workflows/CI_master.yml
- .github/workflows/actions/linux/build/action.yml
- .github/workflows/actions/linux/configure/action.yml
- .github/workflows/actions/linux/install/action.yml
- .github/workflows/actions/runTests/action.yml
- .github/workflows/sub_buildUbuntu2004.yml
- .github/workflows/sub_buildUbuntu2204.yml
- .github/workflows/sub_lint.yml
- .github/workflows/sub_wrapup.yml
This PR brings some improvements to CI.
Structure:
* Cmake configure, build & install steps are factorized in a composite action for both Linux jobs
Performance:
* Logging is improved for configure, build & install steps
* Line buffered output for stdout & stderr
* Full log contains both stdout & stderr (previously only stdout) so errors can be looked at contextually
Other:
* Rename Ubuntu build jobs for better comprehension
* Spell checker (lint) will silently fail. Not failing the workflow anymore, but still reporting errors
* In wrapup job, deleting used artifact is allowed to fail (already happened that it failed a job)
> CI various improvements

- src/Mod/Fem/App/FemPostFilter.cpp
- it is the cut, not the clip filter, was probably a copy/paste mistake
- also some automatic code-reformatting according to our current clang file
> [FEM] fix wrong name in cut filter

- .pylintrc
A few small changes to our pylint configuration:
* Correct exception type specification
* Don't require more than one public method
* Make max attributes match max locals
* Warn on use of PySide2 (rather than PySide)
Fixes #8367.
---
> CI: Tweaks to pylintrc

- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femtaskpanels/task_mesh_gmsh.py
- src/Mod/Fem/femviewprovider/view_mesh_gmsh.py
- no longer output an error on mesh from a BooleanFragments. There are cases when this fails, but other cases where one must use a BoopleanFragments compound and this works well, see https://forum.freecad.org/viewtopic.php?t=71070. Therefore a warning is sufficient.
- disable log messages not important for the average users.
- avoid code duplication
> [FEM] improve messages in mesh generation

- tests/src/App/Metadata.cpp
If an exception occurs while setting up Xerces-C, make the test framework handle it.
---
> Test(Metadata): Remove catch from Setup()

- src/Mod/Arch/ArchStairs.py
Bad indentation in `src/Mod/Arch/ArchStairs.py`
---
> Arch: fix incorrect indentation in ArchStairs.py

- src/Mod/Fem/App/FemPostFilter.cpp
- src/Mod/Fem/Gui/TaskPostBoxes.cpp
- src/Mod/Fem/Gui/TaskPostBoxes.h
- the ViewProvider sorting of the field can be different from the sorting in the dialog
- also hide a Contours property (I forgot this when the contours filter was added)
> [FEM] Contours: fix task panel logic

- src/Mod/Draft/draftfunctions/mirror.py
> [Draft] typo: Mirror object name should be capitalized

- src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostObject.h
- To speed up analyses one calculates on several CPU cores. The result is a partial VTU (*.ptvu) file. Unfortunately when applying a transparency the boundaries of the volumes computed by each CPU core are always visible. This makes it often unusable for visualizations. The solution is to filter the results the same way a clip filter does.
> [FEM] improve visualization of pvtu files

- src/Mod/Draft/draftmake/make_dimension.py
- src/Mod/Draft/draftutils/init_draft_statusbar.py
Fixes some Draft workbench source comment typos
---
> Draft: fix typos

- src/Mod/Fem/Gui/DlgSettingsFemElmer.ui
- src/Mod/Fem/Gui/DlgSettingsFemElmerImp.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- it is sensible to filter by default, however, it turned out that on some complex models Elmer fails to compute if the CPU mesh volume regions are too small (in most cases) or at a certain mesh region. By disabling the filtering, one gets at least for the latter case a visual feedback where the mesh volume of the different CPU are (by also setting a transparency to the result pipeline).
> [FEM] make pvtu file filtering optional

- src/Mod/Arch/ArchStairs.py
- Recompute should not be called from onDocumentRestored. It causes issues when updating complex stairs.
---
> [Arch] Arch_Stairs fix for #8444

- src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- if pvtu file filtering is on, there is by design not on every call of WriteColorData() data (on other occasions of GetArray(array) the result is checked, for two calls is was forgotten)
- also some automatic code formatting according to our current clang file
> [FEM] fix possible crash on changing the VectorMode

- .clang-format
---
Current setting pulls subsequent line onto same line …
> clang-format AlwaysBreakTemplateDeclarations

- src/Mod/Fem/femtaskpanels/task_result_mechanical.py
- src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py
- it was often criticized that our default solver CCX is not connected to the results pipeline system. One had to connect it manually, the create then different filters etc. But as soon as one changed a constraint and re-run the solver the whole work was gone and one had to recreate the pipeline. This is very annoying since only the pipelines allows to get persistent result objects, to measure values at certain nodes etc.
This PR solves this by creating a pipeline and by reloading new results to it on a solver re-run. The CCX results dialog feature is hereby not touched, since the pipeline is hidden when the dialog is active. So people can use the pipeline or not.
> [FEM] connect CCX solver to results pipeline

- src/Gui/CMakeLists.txt
- src/Gui/NotificationBox.cpp
- src/Gui/NotificationBox.h
This PR is the first of a series to introduce NotificationArea.
This PR introduces a new non-intrusive auto-closing notification box, that will be used by NotificationArea.
NotificationArea thread:
https://forum.freecad.org/viewtopic.php?p=651344#p651344
In short, a "tooltip" alike notification, where the user can continue working without having to interact with the notification. If the user is interested in the notification, he or she can stop to read it. If not interested, the user can ignore it and continue working. The notification will automatically disappear when the timer lapses or before that time, as described below.
A new widget similar to QToolTip, to have a similar look and feel and interface, while avoiding early closing on user action.
QToolTip is not intended for …
> [NotificationArea pre-requisite] NotificationBox

- src/Gui/NotificationBox.cpp
- master in uncompilable on Windows, see https://github.com/FreeCAD/FreeCAD/pull/8352#issuecomment-1435769625 and we already got reports about this. Thus a hotfix for the meantime.
- (the formatting change was automatically done by MSVC according to our clang file)
> [Gui] hotfix for NotificationBox.cpp

- src/Mod/Fem/Gui/ViewProviderAnalysis.cpp
- after activating an analysis the FEM toolbar buttons did not become active
> [FEM] fix analysis activation issue

- src/Mod/Material/CMakeLists.txt
- src/Mod/Material/MaterialEditor.py
- at the moment you get several warnings about missing icons when starting the Material editor The reason is that they are not registered in CMake
- also remove icon from Material icon editor. As it is a child of FreeCAD it should have the same FreeCAD icon as all other FreeCAD widgets.
- also fix warning about too short variable name
> [Material] fix bugs with missing icons

- src/Mod/Fem/femtaskpanels/task_material_common.py
- src/Mod/Fem/femtaskpanels/task_material_reinforced.py
- src/Mod/Material/MaterialEditor.py
- the material editor failed for Fluid materials because this info was not passed to it. Instead always solid materials were loaded.
- also fix warning about too long variable name and remove unnecessary debug code
> [FEM] fix material handling of fluids

- src/Mod/Fem/Gui/Resources/ui/Material.ui
- when the option "use this task panel" is not checked the edit fields must be disabled. This also fixes the often hard to understand issue that while scrolling to the end of the dialog the material suddenly changes to "_transient" because the scroll wheel can trigger to change the edit fields.
> [FEM] fix material dialog logic

- src/Mod/Fem/App/FemMesh.cpp
- src/Mod/Fem/App/FemMesh.h
- src/Mod/Fem/App/FemMeshPy.xml
- src/Mod/Fem/App/FemMeshPyImp.cpp
This function return a container of specific element IDs asociated to a given node ID.
Also some modifications are also made in the code of FemMeshPyImp.cpp to remove the use of logic blocks that associate Salome Element types to name types. …
> Fem: Implement getNodeElements function

- src/Gui/3Dconnexion/GuiNativeEventMac.cpp
The old call was deprecated by 3DConnexion.
> Core: Update Mac Spacemouse calls

- cMake/FreeCAD_Helpers/PrintFinalReport.cmake
The patch fixes a small issue, with the PrintFinalReport macro, where Shiboken and PySide where not properly reported.
Closes: https://github.com/FreeCAD/FreeCAD/issues/8573
- [ X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
**Note**: If you don't have wiki access, then please …
> properly report Shiboken and PySide if found

- src/Mod/Material/MaterialEditor.py
- handle case that material cards are chosen from folders outside of the standard material folders
- also reduce singleStep size for spin edits for more convenience
> [Material] fix bugs for external material files

- src/Mod/Fem/femtaskpanels/task_material_common.py
- on creating a new material object, don't pollute the console wit wrong error messages (if no material is yet selected, of course nothing can yet be found)
- fix that for new fluid materials the material editor was started with solid materials
> [FEM] fix material initialization

- src/Mod/PartDesign/InvoluteGearFeature.py
- src/Mod/PartDesign/InvoluteGearFeature.ui
This is a follow-up to #8184, extending the task panel with tool tips.
For the tool tips, the property descriptions are reused. This avoids maintaining the same information in two places. The property descriptions have been made translatable, too, to ensure a fully translatable UI.
Overall, this PR follows the same methodology as #5321. However, I did not managed to make an *open* task panel retranslate itself in case the UI language is changed. In C++ this is done by overwriting the TaskPanel's `changeEvent`, but this does not seem to be exposed to Python. @wwmayer, any ideas?
I did not find any Python task panel reacting on language-change while open. When closing and reopening the task panel, the new language setting is used, though.
---
Please remember to update the Wiki with the …
> PD: Make InvoluteGear's property descriptions translatable and reuse them as task panel tooltips

- src/Mod/Start/StartPage/LoadCustom.py
- src/Mod/Start/StartPage/LoadMRU.py
By setting a DefaultImportXXX preferences parameter under Mod/Start, one can specify a default import module to use when clicking a .XXX file on the Start page. This is specially useful for filetypes that have several importers, and the Start page would not let users choose which importer to use.
Later on if this proves useful we can set up an UI to let the user set their preferences better. …
> Start: Allow to change the default import module for a filetype

- src/Mod/Arch/CMakeLists.txt
- src/Mod/Arch/ifc_objects.py
- src/Mod/Arch/ifc_viewproviders.py
This commit adds two placeholder files to the Arch workbench, to allow opening files containing [NativeIFC](https://github.com/yorikvanhavre/FreeCAD-NativeIFC) objects without errors, same as we did already for the ArchSketch WB.
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438) …
> Arch: Placeholder modules to handle files containing NativeIFC objects

- src/Mod/Material/StandardMaterial/Graphite.FCMat
- decimal sign was mixed ',' and '.' causing problems
> [Material] [skip ci] fix card for Graphite

- src/Mod/Material/MaterialEditor.py
This PR fixes the long-standing major bug that for languages using ',' as decimal separator the material editor was useless. (bug no. 10 in https://forum.freecad.org/viewtopic.php?t=56912)
the issue was that the value was handled as text. This PR:
- using a spinbox instead if a text edit to modify numbers (has also the advantage to be able to change values by spinning)
- sets min/max properly for all number data types
> [material] fix major bug of wrong decimals

- src/Mod/PartDesign/PartDesignTests/TestInvoluteGear.py
- src/Mod/PartDesign/fcgear/involute.py
The arcs on the tip (around the addendum) and the root (between the fillets) used to have their bulge in the wrong direction for the internal gear profile: their center points has been on the outside. Since this error existed since the very first introcution of the internal gear I assume this was done by accident: Instead of only the fillets, all arcs have been inverted when the external profile was copied. This commit now inverts the tip and root arcs again, to be concentric with the pitch circle -- same as for the external profile.
While barely noticeable between the root fillets, on the addendum the error resulted in the internal diameter being smaller than it should be as the tooth used to protrude beyond the tip circle. (nb: the tip is on the inside here)
In the below screenshots, …
> PD: Fix the internal InvoluteGear's root/tip arc directions

- src/Gui/ExpressionCompleter.cpp
https://forum.freecad.org/viewtopic.php?t=76239
The problem is that in the tuple returned by `tokenizeExpression`, the std::string is converted to QString, but the character position is still stored as computed in the std::string. This breaks when using UTF-8 chars as their representation size isn't same in std::string and QString.
The PR fixes the problem by recomputing the character position in the QString representation.
> [Bugfix] Gui: fix bug in expression completer tokenizing

- src/Mod/Path/Path/Op/Adaptive.py
Path_Adaptive attempts to find the outline of a face using face.Wires[0], change to use face.OuterWire instead
---
> [Path] Adaptive - improve 'use outline' logic

- src/Mod/Part/Gui/DlgPrimitives.cpp
- fixes the regression by #7255 -> the degree sign cannot be decoded as Latin1
@0penBrain , I will apply this as hotfix, feel free to immediately improve or revert it for a better solution
> [Part] fix encoding bug

- src/Mod/Draft/Resources/ui/TaskPanel_CircularArray.ui
- src/Mod/Draft/Resources/ui/TaskPanel_OrthoArray.ui
- src/Mod/Draft/Resources/ui/TaskPanel_PolarArray.ui
The default max for spinboxes is 99. This PR increases it to 1 million for the number spin boxes of the array task panels.
---
> [Draft] increase number spinboxes max in array task panels to 1 million

- src/Mod/Fem/femexamples/equation_flow_elmer_2D.py
- src/Mod/Fem/femexamples/equation_magnetodynamics_2D_elmer.py
- src/Mod/Fem/femexamples/equation_magnetodynamics_elmer.py
- define materials so that they are recognized by material handling as existing card
- use "electrodynamics" as equation because this is the common name for the physics of these examples
- fix typos
> [FEM] fixes for flow and electrodynamics examples

- src/Gui/DlgSettingsNavigation.cpp
- as discussed here: https://forum.freecad.org/viewtopic.php?t=76233 maybe the conversion to ".toLatin1()" is unsafe on some systems for non-ASCII characters on the font names
> [Gui] attempt to fix getting NaviCube font name

- src/App/Expression.cpp
> [BugFix] Expression: always add space char before unit when converting to string

- src/Mod/OpenSCAD/OpenSCADUtils.py
Lint bad indentation, superfluous semicolons, superflous parathesis around returned function results
---
> OpenSCAD: lint OpenSCADUtils.py

- src/Base/Matrix.cpp
- src/Base/Rotation.cpp
- src/Mod/Test/BaseTests.py
When created a Rotation from a scaled matrix, the quaternion become malicious. This filters out the scale from the matrix if there is one. Fixes #8494
> Fix issue #8494

- src/Gui/DlgPreferencesImp.cpp
- src/Gui/DlgSettingsViewColor.cpp
- src/Gui/Tree.cpp
- is by default in the title bar of Qt dialogs, has to be removed explicitly when unused
- also fix too long code lines
> [Gui] remove unused help button from preferences dialog

- src/Mod/OpenSCAD/OpenSCADUtils.py
- src/Mod/OpenSCAD/importCSG.py
Move all imports to the top of the file, and replace the old hand-coded translate function with FreeCAD's. Also begin migration from the custom executable finder to the one built into shutil since Python 3.3.
---
> OpenSCAD: Linter cleanup

- src/Gui/DlgSettingsNavigation.cpp
- src/Gui/DlgSettingsNavigation.ui
- src/Gui/NaviCube.cpp
- src/Gui/NaviCube.h
- src/Gui/SoTextLabel.cpp
- src/Gui/View3DInventor.cpp
- it was frequently requested and people now even published videos since I documented this hidden feature in the Wiki. However, for a user it is a nightmare without a UI and users who like a bright background need to change the button color to keep the buttons visible.
> [Gui] add UI to change the NaviCube button size

- src/App/Link.h
- src/Gui/ViewProviderLink.cpp
Addresses Coverity [CID 356649](https://scan8.scan.coverity.com/reports.htm#v44798/p11555/fileInstanceId=71281382&defectInstanceId=12830107&mergedDefectId=356649), uninitialized scalar. This PR adds an explicit "None" option to the `App::Link::OnChangeCopyOptions` enumeration with a value of zero. The code that creates that type directly now initializes to that new (zero) option. It is not clear how many compilers were performing this initialization automatically, but doing so is not required by the C++ standard (as near as I can tell).
---
> App: Add None=0 to enumeration

- src/Gui/View3DInventor.cpp
- the color is stored in for RRGGBBAA and must be passed in form AARRGGBB to QColor. In NaviCube.cpp this is already done right and the same is necessary for View3DInventor.cpp
> [Gui] fix initialization of NaviCube colors

- src/Mod/Part/Gui/SectionCutting.cpp
Addresses Coverity [CID 356563](https://scan8.scan.coverity.com/reports.htm#v44798/p11555/fileInstanceId=71281803&defectInstanceId=12830295&mergedDefectId=356563): Uninitialized scalar. `cutTransparency` is later used, from the static analyzer's point of view possibly uninitialized, in a comparison operation. I don't think it's actually possible for that to happen given the logic of the code, but initialize the POD type anyway, for good measure. I chose a value that it can't be given so that if this analysis is incorrect, it should be obvious what happened when stepping through the code.
---
> Part: SectionCutting cutTransparency initialization

- src/Mod/Spreadsheet/Gui/SheetTableView.cpp
Fixes Coverity CID 184299. It's not clear to me that any of these `event==nullptr` checks are actually necessary, though. Is it really possible for `event` to be null here?
---
> Spreadsheet: Fix possible null dereference

- src/Gui/Workbench.cpp
- src/Gui/Workbench.h
Coverity complains about USE_AFTER_FREE here (CID 436695), and I found it was difficult to reason about the code to determine whether the analyzer was correct. To help address this, refactor to use different variables for the different parameter groups. Also change the function call to use a non-reference to `Reference`, for the same reason. @wwmayer I don't have a good sense of when I should be using a C++ reference to Base::Reference and when to just let the ref-counted copy be made, so I'd welcome any advice you have there. I don't think the changed function signature is an important part of the PR, and could be rolled back.
---
> Gui: Eliminate variable reuse

- src/Mod/Sketcher/App/SketchAnalysis.cpp
Coverity [CID 350580](https://scan8.scan.coverity.com/reports.htm#v44798/p11555/fileInstanceId=71280783&defectInstanceId=12830055&mergedDefectId=350580): Uninitialized scalar variable. The analyzer doesn't like the incomplete construction of the ConstraintId object (the 'Type' field was uninitialized). This PR switches to Uniform Initialization and explicitly spells out each field, including Type, which is unused in the following comparison. This should not affect the run of the code. I believe it is unlikely to represent a measurable speed difference, however if it is possible to check that, it might be a good idea.
---
> Sketcher: Silence Coverity warning

- src/App/Expression.cpp
- src/App/ExpressionParser.h
This adds a function cbrt(arg) to the freecad-expressions that computes the cube root of arg. Instead of arg^(1/3) this handles the units of the argument, so that one can compute units from p.e. ml to mm.
cbrt(27 ml) → 30 mm
instead of
(27 ml)^(1/3) → 30
see also:
https://forum.freecad.org/viewtopic.php?style=1&p=663161
⚠ I added the enum after sqrt, so renumbering following enums.
> add cbrt (cube root) to expressions

- src/Mod/PartDesign/PartDesignTests/TestInvoluteGear.py
- src/Mod/PartDesign/fcgear/involute.py
While gears without a root fillet may have limited real-live use cases, during number-input it happens regulary to have a zero fillet radius as intermediate state. With this commit such a situation is now handled gracefully.
----
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438) …
> PD: Fix exception from InvoluteGear with zero fillets

- src/App/Property.h
- "conversion from 'size_t' to 'int', possible loss of data" in for loops by modernizing the for loops
- fix warning about uninitialized variable
> [App] attempt to fix compiler warnings in Property.h

- CONTRIBUTING.md
This PR improves `CONTRIBUTING.md` by replacing some instances of the term `Platform` with `GitHub` for the following reasons:
* This was unnecessary legalese which made the document harder to comprehend.
* Fixes a few ambiguous usages of the term:
* In one usage there is ambiguity if there is a platform called "Platform".
* Ambiguous with other usages of the word when referring to the runtime platform.
* Fixes one incorrect usage of the term, where reference to `"Platform"` was intended to refer to any platform OTHER THAN `GitHub` or `"the Platform"`.
---
> Improve usage of the term 'platform' in CONTRIBUTING.md

- src/Mod/Spreadsheet/App/Sheet.cpp
- src/Mod/Spreadsheet/Gui/SheetTableView.cpp
Coverity identifies a few places in Spreadsheet where we could be using a reference instead of a copy in `for` loops: in some cases it's not correct because the object in question is a Range (which is a linked list and modifies itself via its `next()` calls and we do need the copy), but in some cases it is correct. This PR addresses CIDs:
* [356650](https://scan8.scan.coverity.com/reports.htm#v44815/p11555/fileInstanceId=71280029&defectInstanceId=12830097&mergedDefectId=356650)
* [356633](https://scan8.scan.coverity.com/reports.htm#v44815/p11555/fileInstanceId=71280029&defectInstanceId=12830083&mergedDefectId=356633)
* [356605](https://scan8.scan.coverity.com/reports.htm#v44815/p11555/fileInstanceId=71280029&defectInstanceId=12829772&mergedDefectId=356605)
* …
> Spreadsheet: Fix unintended copies

- src/App/Property.h
As discussed in PR #8683, this is just a small improvement to eliminate the manual indexing of the array in the first loop.
---
> App: Minor loop cleanup in Property.h

- src/Mod/Mesh/Gui/PreCompiled.h
- src/Mod/Spreadsheet/App/PreCompiled.h
- add 2 missing includes to be able to compile with precompiled headers
> [Mesh] [Spread] fix compilation with PCH

- src/Mod/Arch/ArchAxis.py
- src/Mod/Arch/exportIFC.py
- src/Mod/Arch/importIFC.py
- src/Mod/Arch/importIFCHelper.py
- src/Mod/Arch/importJSON.py
- src/Mod/Arch/importWebGL.py
- src/Mod/Draft/draftfunctions/svgtext.py
- src/Mod/Draft/draftutils/todo.py
- src/Mod/Draft/draftutils/translate.py
- src/Mod/Draft/importDWG.py
- src/Mod/Draft/importDXF.py
There were several unused remnants of uses of the python six module throughout Draft and Arch. This PR removes them.
---
> Arch, Draft: Remove use of six module

- src/Mod/Arch/ArchSchedule.py
- src/Mod/Arch/Resources/ui/ArchSchedule.ui
This PR fixes an [Arch_Schedule](https://wiki.freecad.org/Arch_Schedule) recompute issue. The error message was: "Result still touched after recompute".
Forum topic:
https://forum.freecadweb.org/viewtopic.php?f=23&t=67829
The old situation (as far as I understand):
After a recompute of the Schedule the Result spreadsheet would be in a 'to-be-recomputed' state. The next document recompute would include the spreadsheet, which in turn would recompute the Schedule, which finally left the spreadsheet again in a 'to-be-recomputed' state. Side-effect of this was that the Schedule was always up-to-date.
The new situation:
The property type of Result has been changed to `"App::PropertyLinkHidden"`. This alone solves the recompute issue. To still have the possibility of an always up-to-date …
> [Arch] fix Arch_Schedule recompute issue

- src/Mod/Arch/ArchSectionPlane.py
Fixes #6259.
Note that all Draft objects, except annotations, are processed as 'normal' objects. The produced results now more closely match what Draft_Shape2DView would create from a section plane.
Test file I have used (based on the file from the issue):
[staircase_test_roy.zip](https://github.com/FreeCAD/FreeCAD/files/10841246/staircase_test_roy.zip)
---
> [Arch] Arch_SectionPlane improve handling of non-solids

- src/Mod/Draft/DraftVecUtils.py
- src/Mod/Draft/WorkingPlane.py
- src/Mod/Draft/draftviewproviders/view_dimension.py
- src/Mod/Draft/importDXF.py
This will fix #8697. By normalizing vector u and make v and w perpendicularand normalized the returned matrix turns into a pure rotation without scales and shears. Using v vector to define xy plane. Leaves the third argument unused but keep it for backward compatibility.
> Return pure rotation from getPlaneRotation()

- src/Gui/MainWindow.cpp
- src/Gui/NaviCube.cpp
-set several font families for better matching on multiple systems
-set SansSerif stylehint again as it is needed for proper matching
-remove hack that saves the default font to parameters even when cancelling on DlgSettingsNavigation
-change return type of getDefaultSansserifFont to QString as only the font family is really used from this.
related to #8553 and https://forum.freecad.org/viewtopic.php?p=662155#p662155
@donovaly 
@chennes I would like to know what gets matched by this on macOS if you can test, if building is too much trouble getting the result from [this python snippet](https://forum.freecad.org/viewtopic.php?p=662267#p662267) could also help me.
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to …
> Improve navicube default font matching on linux

- src/Gui/ToolBarManager.cpp
- src/Gui/ToolBarManager.h
- src/Gui/Workbench.cpp
following forum discussions about toolbars, some users would like to have cut/copy/paste in the toolbar, by making it a separate toolbar it is easier to hide for those that don't want it. Same situation with the `what's this?` command, by making it a separate toolbar it is easily hidden by those not using it.
https://forum.freecadweb.org/viewtopic.php?f=8&t=71924&start=10
https://forum.freecadweb.org/viewtopic.php?p=626197#p626197
The undo/redo/refresh commands where moved into a separate `Edit` toolbar to be a little more consistent with the menus and to some extent with other software that have this separated, this also makes it easier to customize the location of toolbars, for example I would prefer to have the `Structure` toolbar between `File` and `Edit`. If this is undesired I will …
> Split "File" toolbar and add "Clipboard" toolbar

- src/Mod/PartDesign/InvoluteGearFeature.py
This makes use of the recent additions to `TaskPanelPython` and `UiLoader`, cf. #8602, to retranslate the UI without having to close and reopen it again.
Retranslation of the part from the UI file is now handled by FreeCAD internally, but the tool tips from the property descriptions still need to be reassigned with the translated versions.
This small addition finally completes #8247.
--- …
> PD: Retranslate InvoluteGear's Task Panel on language change

- src/Mod/TechDraw/TechDrawTools/TaskHoleShaftFit.py
Solve two issues:
1. Avoid future translation problems.
2. Hack to force zero tolerance values to be printed as (+0.000)
- [ X]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog …
> [TD] Solve two issues in CmdHoleShaftFit

- src/Gui/ToolBarManager.cpp
If the user e.g. activates the Clipboard toolbar then it should not be hidden any more if the user switches to another workbench. The way it is now the user has to make this toolbar visible over and over again when changing the workbench. This also has the negative effect that the workbench selector changes its position …
> Gui: fix regression with the default visibility of toolbars

- src/App/DocumentObject.cpp
- src/App/DocumentObject.h
- src/App/FreeCADInit.py
- src/Base/Builder3D.cpp
- src/Base/CMakeLists.txt
- src/Base/Console.cpp
- src/Base/Console.h
- src/Base/ConsoleObserver.cpp
- src/Base/ConsoleObserver.h
- src/Gui/Application.cpp
- src/Gui/CommandTest.cpp
- src/Gui/GuiConsole.cpp
- src/Gui/GuiConsole.h
- src/Gui/MainWindow.cpp
- src/Gui/MainWindow.h
- src/Gui/ReportView.cpp
- src/Gui/ReportView.h
- src/Gui/Splashscreen.cpp
- src/Gui/Tree.cpp
- src/Mod/Import/App/ImportOCAF2.cpp
- src/Mod/Import/App/dxf/ImpExpDxf.cpp
- src/Mod/Part/App/TopoShapePyImp.cpp
- src/Mod/Sketcher/App/planegcs/GCS.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/DrawComplexSection.cpp
- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/GeometryObject.cpp
- src/Mod/TechDraw/Gui/QGIViewPart.cpp
- src/Mod/Test/Gui/AppTestGui.cpp
This PR is the first of a series to introduce NotificationArea.
This PR is mostly directed to refactor Console and Extend it to new messages. It could have been great to first refactor and then extend, but actually the refactor became advisable during the extension.
The core of the refactor/extension lies in Console.h and Console.cpp. The rest of the changes are a consequence of it. When reviewing it makes sense to start there.
Console:
* For refactor:
- variadic functions are substituted with template functions with parameter packs.
- To provide support for the c style printf, fmt library is used.
- Template functions with parameter packs were moved to header file.
* For extension:
- Messages are extended to include a Notifier string, to indicate the originator of the …
> [NotificationArea pre-requisite] Console refactor and extension

- src/Mod/Fem/Gui/DlgSettingsFemCcxImp.cpp
- src/Mod/Fem/Gui/DlgSettingsFemElmerImp.cpp
- src/Mod/Fem/Gui/DlgSettingsFemElmerImp.h
I encountered problems with `std::thread::hardware_concurrency()` with mingw-w64 < v8.1.
`QThread::idealThreadCount()` is a better alternative.
I'm pushing another commit. In the first I did not set git right and Qt Creator made too many changes. I fixed the settings, remade the commit and now everything seems alright.
--- …
> [FEM] Replacement of `std::thread::hardware_concurrency` with `QThread::idealThreadCount`

- src/Gui/DlgSettingsLazyLoaded.ui
- src/Gui/DlgSettingsLazyLoadedImp.cpp
- src/Gui/DlgSettingsLazyLoadedImp.h
---
I added some improvements to the workbench settings:
- Bugfix: When loading workbenches in the settings dialog, manually selected autoload checkboxes were unselected. A faster implementation that only replaces the load …
> Bug fixes and improvements for workbenches settings

- src/Mod/Mesh/App/Core/Builder.cpp
- src/Mod/Mesh/App/Core/Evaluation.cpp
Removal of unnecessary comparison.
`QThread::idealThreadCount()` returns the ideal number of threads that the process can run in parallel or 1 if it fails to determine it.
---
---
> [Mesh] Minor code update

- src/Gui/Application.cpp
See also Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986821 For now enable this line only for Windows builds
---
> Gui: fix possibly garbled toolbars and menus

- src/Mod/MeshPart/App/MeshFlatteningPy.cpp
- fixes #8741
- in commit d62d41a53b66af1e824e the pybind headers were accidentally removed
> [MeshPart] fix unwrap feature

- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
=================================================
User Syres realised that some commands that are in use by the solver messages url referenced non-existing icons, which triggers errors in the report view while customising: https://forum.freecad.org/viewtopic.php?p=666167&sid=16ac6777c440d632e5f60083fb4327ca#p666167
This commit removes them.
> Sketcher: Remove references to non-existing icons

- src/Mod/Sketcher/Gui/SketcherSettings.cpp
- src/Mod/Sketcher/Gui/SketcherSettings.ui
=====================================================
In a previous commit the Edit Section and its preferences where removed, however Adrián Insaurralde realised that the setting for showing or not this section had been left behind: https://github.com/FreeCAD/FreeCAD/pull/8716#issuecomment-1462364487
This commit just removes that settings.
> Sketcher: Remove "Show Edit Section" from preferences

- src/Mod/AddonManager/Addon.py
- src/Mod/AddonManager/AddonManagerTest/app/mocks.py
- src/Mod/AddonManager/AddonManagerTest/app/test_addon.py
- src/Mod/AddonManager/AddonManagerTest/app/test_installer.py
- src/Mod/AddonManager/AddonManagerTest/app/test_macro.py
- src/Mod/AddonManager/AddonManagerTest/app/test_metadata.py
- src/Mod/AddonManager/CMakeLists.txt
- src/Mod/AddonManager/TestAddonManagerApp.py
- src/Mod/AddonManager/addonmanager_devmode_metadata_checker.py
- src/Mod/AddonManager/addonmanager_freecad_interface.py
- src/Mod/AddonManager/addonmanager_installer.py
- src/Mod/AddonManager/addonmanager_macro.py
- src/Mod/AddonManager/addonmanager_metadata.py
- src/Mod/AddonManager/addonmanager_utilities.py
- src/Mod/AddonManager/addonmanager_workers_installation.py
- src/Mod/AddonManager/addonmanager_workers_startup.py
- src/Mod/AddonManager/addonmanager_workers_utility.py
- src/Mod/AddonManager/package_details.py
- src/Mod/AddonManager/package_list.py
Create a Python-native metadata class. Includes unit tests, and some PyLint cleanup, as well as continuing to refine the separation between the Addon Manager and FreeCAD.
---
> Addon Manager: Refactor Metadata

- src/Mod/AddonManager/addonmanager_macro.py
- src/Mod/AddonManager/package_list.py
Icons that had query strings after their filename broke the Macro parser, and they are appearing with increasing frequency on the Wiki (possibly due to a configuration change?). This fixes that bug, as well as a couple of small issues from the last refactoring PR.
> Addon Manager: Handle icons with query strings

- src/Mod/Fem/Gui/BoxWidget.ui
- was reported and automatically fixed by Qt's Designer that the size in the file is incorrect, (the sum of the widget's widths is wider than the main widget's specified size)
> [FEM] [skip ci] BoxWidget.ui fix

- src/Gui/PrefWidgets.cpp
- onRestore did not read in transparencies because App::Color::fromPackedRGB was used instead of App::Color::fromPackedRGBA
> [Gui] fix bug on restoring PrefColorButton

- src/Mod/Draft/draftguitools/gui_patharray.py
- src/Mod/Draft/draftmake/make_patharray.py
- src/Mod/Draft/draftobjects/patharray.py
Allows user to specify a starting and ending offset to items in Draft PathArrays. The offsets must be positive. They specify the distance from the beginning or end that the start or end items are placed along the path.
---
> Add offset options to Draft PathArray

- src/Mod/Draft/DraftGui.py
This mitigates the crash reported in issue #8749.  The crash happens when using Draft_Edit and using keyboard to enter a coordinate in Edit node dialog.  This change partially restores behaviour before commit fc14567, after which FreeCADGui.Control.closeDialog and showDialog calls during execution of DraftToolBar.editUi are no longer made using the todo.delay mechanism.  The crash can still be triggered by artificially slowing down key event processing, so this is not a proper fix, just a mitigation.
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't …
> [Draft] Mitigate crash in Draft_Edit (#8749)

- src/App/Document.h
- src/Base/CMakeLists.txt
- src/Base/Observer.cpp
- src/Base/Observer.h
- src/Gui/CMakeLists.txt
- src/Gui/DlgSettingsNotificationArea.cpp
- src/Gui/DlgSettingsNotificationArea.h
- src/Gui/DlgSettingsNotificationArea.ui
- src/Gui/Document.cpp
- src/Gui/Icons/InTray.svg
- src/Gui/Icons/Warning.svg
- src/Gui/Icons/critical-info.svg
- src/Gui/Icons/info.svg
- src/Gui/Icons/resource.qrc
- src/Gui/MainWindow.cpp
- src/Gui/NotificationArea.cpp
- src/Gui/NotificationArea.h
- src/Gui/NotificationBox.cpp
- src/Gui/NotificationBox.h
- src/Gui/QtAll.h
- src/Gui/resource.cpp
- src/Mod/Sketcher/App/SketchObject.cpp
After the pre-requisites are merged, this PR brings the actual NotificationArea.
After this PR, there are two other PRs left for NotificationArea: 
- A first one relates to general functions to help WB to move from blocking QMessage::warning to the  non-intrusive framework.
- A first migration of the sketcher constraint creation to the new framework using those general functions.
What is the Notifications Area?
It consists of:
(a) Non-intrusive messages
(b) A widget showing errors, warnings, critical messages and notifications
How does it look like?
[Peek 2023-03-08 15-33.webm](https://user-images.githubusercontent.com/5249162/223741009-d9f267a6-0ea1-4a57-9590-e740c22e3fd2.webm)
> [NotificationArea] Notificationarea

- src/Gui/CMakeLists.txt
- src/Gui/Notifications.h
Functions to transparently send errors, warnings, notifications and translatednotifications, either as intrusive messages (modal pop-up QMessageBox style) or as non-intrusive messages (notificationarea), depending on the preferences of the user.
It is intended to substitute calls to QMessageBox with these functions in WBs, including the Sketcher WB.
Example:
QMessageBox::warning(Gui::getMainWindow(), QObject::tr("Wrong selection"),
QObject::tr("Cannot add a constraint between two external geometries."));
Can be rewritten as:
Gui::TranslatedNotification(obj,
QObject::tr("Wrong selection"),
QObject::tr("Cannot add a constraint between two external geometries."));
or
Gui::TranslatedNotification("Sketcher",
QObject::tr("Wrong selection"),
QObject::tr("Cannot add a constraint between two …
> [NotificationArea] Gui: Notifications - Convenience functions to send intrusive / non-intrusive notifications

- src/Mod/TechDraw/Gui/TaskLineDecor.cpp
This commit removes the last comma after enumeration.
---
---
> [TechDraw] Minor change in TaskLineDecor.cpp

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/Workbench.cpp
This is the first Sketcher package of conversion of intrusive notifications into the new framework, which provides intrusive or non-intrusive notifications depending on user preferences.
So far only for constraints.
In the same PR it also removes the deprecated framework of manual addition of internal geometries.
> [NotificationArea] Sketcher: Constraint - notification and internal geometry command clean up

- src/Gui/DlgDisplayProperties.ui
- src/Gui/DlgDisplayPropertiesImp.cpp
- src/Mod/Part/Gui/TaskDimension.cpp
I noticed that most task dialogs have their buttons north. I also noticed that the angular measure task had its buttons south despite the linear measure task was already changed to have them north. This is now fixed.
I also removed a redundant implementation of the close button in the display properties task (View -> Appearance...). This way it now also has its close button north per default.
The "Edit -> Placement" task still has the buttons at the south position but I am not sure if it is by design because of the additional reset button...
> Consistency of task button positions

- src/Gui/Stylesheets/Behave-dark.qss
- src/Gui/Stylesheets/Dark-blue.qss
- src/Gui/Stylesheets/Dark-contrast.qss
- src/Gui/Stylesheets/Dark-green.qss
- src/Gui/Stylesheets/Dark-orange.qss
- src/Gui/Stylesheets/Darker-blue.qss
- src/Gui/Stylesheets/Darker-green.qss
- src/Gui/Stylesheets/Darker-orange.qss
- src/Gui/Stylesheets/Light-blue.qss
- src/Gui/Stylesheets/Light-green.qss
- src/Gui/Stylesheets/Light-orange.qss
- src/Gui/Stylesheets/ProDark.qss
---
Fixes #8847 
the buttons and filter menu now look like this:
instead of:
> fix #8847 sketcher dialog tool buttons bad styling

- src/Mod/Draft/draftguitools/gui_base_original.py
- src/Mod/Draft/draftguitools/gui_grid.py
- src/Mod/Draft/draftguitools/gui_lines.py
- src/Mod/Draft/draftguitools/gui_snapper.py
- src/Mod/Draft/draftguitools/gui_trackers.py
Fixes faultly Draft grid behaviour. Now:
- If grid is on and auto grid on: Grid always appears
- If grid is on and auto grid off: Grid off at start, on when using a tool, off afterwards
- If grid is off: Grid never appears
---
> Draft: Fixes grid on/off behaviour - fixes #5878

- .github/workflows/actions/runCPPTests/action.yml
- .github/workflows/actions/runPythonTests/action.yml
- .github/workflows/sub_buildUbuntu2004.yml
- .github/workflows/sub_buildUbuntu2204.yml
Add running the C++ unit tests to the CI workflow. It generates a JSON output file that I don't do much with right now, but in the future we could get fancy with the parsing of the error results. Right now it just checks for errors or test failures and prints them in the summary.
Here's what it looks like when there are failing tests:
https://github.com/chennes/FreeCAD/actions/runs/4422559744
---
> CI: Run GTest suite

- src/Mod/Fem/feminout/importCcxFrdResults.py
- src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py
- it is a long-standing bug that the name of the result mesh object is not unique. For example for a frequency analysis you get for every result the same object "ResultMesh". When now a "ResultMesh" object is deleted because one result mode object should be deleted, all result modes loose their mesh. To fix this, use a unique name for the mesh object.
> [FEM] use unique result mesh name

- .github/workflows/sub_lint.yml
- there is no need to check for certain OS line endings, git handles them well apparently
> [Lint] remove checks for line endings

- src/Mod/TechDraw/App/DimensionFormatter.cpp
- src/Mod/TechDraw/App/DimensionFormatter.h
- bad format spec can break QString::asprintf
- this can probably be backported to v20, but it will have to be cut and paste, not cherry-pick.
**Note**: If you don't have wiki access, then please mention your contribution on …
> [TD]trap bad format spec - fix #8897 in master branch

- src/Mod/TechDraw/App/DimensionFormatter.cpp
- src/Mod/TechDraw/App/DrawComplexSection.cpp
- src/Mod/TechDraw/App/DrawComplexSection.h
- src/Mod/TechDraw/App/DrawViewDetail.cpp
- src/Mod/TechDraw/App/DrawViewDetail.h
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/DrawViewSection.h
- src/Mod/TechDraw/Gui/AppTechDrawGui.cpp
- src/Mod/TechDraw/Gui/QGSPage.cpp
- src/Mod/TechDraw/Gui/QGVPage.cpp
- src/Mod/TechDraw/Gui/QGVPage.h
- src/Mod/TechDraw/Gui/mrichtextedit.cpp
* in QtConcurrent::run the order of 1st and 2nd argument are swapped
* QtConcurrent::run asserts that the argument of the passed function pointer is not non-const
* Used methods of QFontDatabase are static in Qt5 and Qt6
* QTextStream::setCodec() has been removed in Qt6
* Argument of enterEvent() has changed from QEvent to QEnterEvent
* QTextCharFormat::setFamily() is deprecated
**Note**: If …
> TD: First step to port to Qt6

- src/Mod/TechDraw/Gui/QGIMatting.cpp
- src/Mod/TechDraw/Gui/QGIMatting.h
- src/Mod/TechDraw/Gui/QGIView.cpp
- src/Mod/TechDraw/TDTest/DrawViewDimensionTest.py
- src/Mod/TechDraw/TDTest/TechDrawTestUtilities.py
- src/Mod/TechDraw/TestTechDrawApp.py
- src/Mod/TechDraw/TestTechDrawGui.py
This PR is a collection of minor fixes.
- The dimension test script was failing as it did not allow for threads to complete. Wait added and test moved to gui test since it now depends on QApplication.
- Detail geometry was extending past the detail circle.
- View frames were over-large due to inclusion of arc center marks.
see https://forum.freecad.org/viewtopic.php?p=666838#p666838 and https://forum.freecad.org/viewtopic.php?t=76688&sid=85eb979404a709d7244d4397baec8ee6 for background. …
> [TD]Minor fixes

- src/App/DocumentPy.xml
- src/App/DocumentPyImp.cpp
The python Document class didn't have addProperty nor removeProperty but such behavior was available throw GUI.
Forum discussion (french): https://forum.freecad.org/viewtopic.php?t=76855
> App: Fix missing python addProperty and removeProperty of Document object

- src/Gui/DlgSettingsNotificationArea.cpp
- src/Gui/DlgSettingsNotificationArea.ui
- src/Gui/NotificationArea.cpp
- src/Gui/NotificationBox.cpp
- src/Gui/NotificationBox.h
It was reported that some non-intrusive notifications occupy the whole width of the screen and even then, they are so large that are not visible.
This PR:
- Enables normal wrapping of the notificationbox, so that text is automatically wrapped to fix the notification.
- Notification box are now provided of a fixed width. the width is configurable in preferences.
- Text is converted to HTML to properly preserve format as much as possible.
> [NotificationArea] Long message wrapping and preserve formatting

- src/Mod/Fem/femsolver/elmer/solver.py
- src/Mod/Fem/femsolver/elmer/writer.py
- src/Mod/Fem/femtest/data/elmer/box_static_0_mm.sif
- src/Mod/Fem/femtest/data/elmer/ccxcantilever_faceload_0_mm.sif
- src/Mod/Fem/femtest/data/elmer/ccxcantilever_faceload_1_si.sif
- src/Mod/Fem/femtest/data/elmer/ccxcantilever_nodeload_0_mm.sif
- src/Mod/Fem/femtest/data/elmer/ccxcantilever_prescribeddisplacement_0_mm.sif
- for new versions of Elmer the default coordinate system is "Cartesian". (if 2D or 3D is determined by the "Variable" setting for the equation)
> [FEM] Elmer: add new default coordinate system

- src/Mod/PartDesign/InvoluteGearFeature.py
- src/Mod/PartDesign/InvoluteGearFeature.ui
- src/Mod/PartDesign/PartDesignTests/TestInvoluteGear.py
- src/Mod/PartDesign/fcgear/involute.py
This commit adds the ability to shift the involute profile inside or outside. Profile shift is implemented as coefficient, i.e. normalized by the module, so that the whole profile scales with the module without changing shape.
To verify the profile, the tests implement an "over pins measurement" using formulae found in literature.
Backward compatibility with FreeCAD-v0.20 is garanteed by already existing tests, not touched by this commit.
This addresses issue #5618.
----
Please remember …
> PD: Implement Profile Shift for InvoluteGear

- src/App/Application.cpp
- was forgotten once the property was implemented some days ago
> [App] [skip ci] register PropertyVelocity

- src/Gui/Notifications.h
===============================================================
For translated notifications now the caption is included in the message, as the translation is already done, and this improves the semantics of existing messages.
See:
https://forum.freecad.org/viewtopic.php?p=668333#p668333
> Notifications: Extend translated notification to include caption

- src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
This should fix this (I cannot reproduce it):
https://forum.freecad.org/viewtopic.php?p=667579#p667579
Lately I added the geometry pointer to the item. This has indeed
the potential for an already deleted pointer being accessed.
This PR removes the geometry pointer from the item and relies on the
ViewProvider to indirectly access an updated pointer.
> Fix crash ElementsWidget

- src/Gui/DlgKeyboard.ui
- src/Gui/PropertyPage.cpp
- src/Gui/TaskView/TaskDialogPython.cpp
- src/Gui/UiLoader.cpp
- src/Gui/UiLoader.h
- src/Gui/WidgetFactory.cpp
This PR workarounds problems in QUiLoader/kde and fixes https://github.com/FreeCAD/FreeCAD/issues/8708. See the bug for details.
Due to a flaw in the QUiLoader, UiLoader were loading all designer plugins it can find in QApplication::libraryPaths(). This in general a bad practice and leads to bugs due to some plugins may perform some unexpected actions upon load which may interfere with FreeCAD's functionality.
To avoid such problems reset the libraryPaths before creation of a UiLoader object and restore afterwards.
Also:
- move setLanguageChangeEnabled(true) into constructor due to it's called every time it's being instanced anyway.
- Add a small tooltip on how to modify a shortcut.
> Gui: Prevent UiLoader from loading 3rd-party Qt plugins.

- src/Gui/Tree.cpp
For more details see: https://github.com/FreeCAD/FreeCAD/issues/8939#issuecomment-1474888902
---
> Gui: solves #8939: timers are moved between non-QThreads

- src/Mod/Sketcher/Gui/CMakeLists.txt
- src/Mod/Sketcher/Gui/Command.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h
- src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
- src/Mod/Sketcher/Gui/Resources/icons/general/Sketcher_Snap.svg
- src/Mod/Sketcher/Gui/Resources/icons/general/Sketcher_Snap_Deactivated.svg
- src/Mod/Sketcher/Gui/SnapManager.cpp
- src/Mod/Sketcher/Gui/SnapManager.h
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
- src/Mod/Sketcher/Gui/Workbench.cpp
- This PR creates a SnapManager which centralize the snapping features.
- Grid snap is moved to this SnapManager.
- Snap to object is added. A preference setting is added to toggle it.
- Snap at angle is added. A preference setting let user customize the angle. Snap at angle for arc and line only now.
The priority order is : snap at angle, then snap to object, then snap to grid. This is the order that makes sense in term of UX.
- Grid snap is activated by a toggle as before it didn't change.
- Snap to object is on by default and can be disabled in preferences, though it's not likely that users will need to disable it. This setting should perhaps be paired with auto-constraint?
- Snap at angle is activated by holding CTRL. The use of CTRL is software standard to snap movement along an …
> Sketcher: Snap initial implementation. 

- src/Mod/Fem/femguiutils/selection_widgets.py
- the console message how to use the feature is not useful since it is triggered by the GUI selection and in the GUI has already the info in form of tooltips how to use
> [FEM] output less messages

- src/Mod/Fem/Gui/Resources/ui/FlowVelocity.ui
- src/Mod/Fem/femexamples/equation_flow_elmer_2D.py
- src/Mod/Fem/femexamples/equation_flow_turbulent_elmer_2D.py
- src/Mod/Fem/femobjects/constraint_flowvelocity.py
- src/Mod/Fem/femsolver/elmer/equations/flow_writer.py
- src/Mod/Fem/femtaskpanels/task_constraint_flowvelocity.py
- complete revision of the velocity constraint.
This is a breaking change, meaning existing constraints won't work.
This is possible because since 2 days ago the whole flow equation did not work at all. Also the existing constraint implementation if buggy and cannot be used to do the Elmer tutorials. Also, the constraint is only used by Elmer and only be the Flow equation.
Since nobody complained about the obvious wrong results, we can assume the flow equation was not yet in practical usage (and for FC 0.20 we known that it does not work at all, first with FC 0.20.1).
It is necessary since it must be possible to either input a velocity or an equation. With an equation, a velocity profile can be specified.
- update the flow examples accordingly:
-- simplify them since an initial and and …
> [FEM] rewrite velocity constraint

- src/Mod/Sketcher/App/planegcs/Constraints.cpp
This small circle won't be fully constrained anymore:
> Fix circles distance constraint for concentrics

- src/Mod/Fem/femobjects/constraint_flowvelocity.py
- src/Mod/Fem/femsolver/elmer/equations/nonlinear.py
- src/Mod/Fem/femsolver/elmer/sifio.py
- src/Mod/Fem/femtaskpanels/task_constraint_flowvelocity.py
- fix whitespace in the SIF writer
- Elmer GUI uses only 20 nonlinear iterations, so we should do the same (500 were also not sensible)
- don't restrict nonlinear-Newton iterations to 100, 500 might be necessary for turbulent flow
- update author
> [FEM] several Elmer fixes

- src/Mod/Import/App/dxf/dxf.cpp
This addresses #8968. If the MTEXT exceeds 250 characters, the contents are broken up into several records in the DXF file. The C++ importer has been changed to collect all these pieces into a single string containing all the text.
- [X ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
> Issue 8968: Correct C++ DXF importer to get all of long MTEXT text

- src/Gui/Tree.cpp
> Gui: issue #8939: timers are moved between non-QThreads

- src/Mod/Mesh/App/WildMagic4/Wm4System.cpp
macro WIN32 is deprecated, but it is implicit defined by some certain environment including visual studio
---
> fix: use _WIN32 instead of WIN32

- src/Gui/DlgSettingsNotificationArea.cpp
- src/Gui/DlgSettingsNotificationArea.ui
- src/Gui/Icons/InTray_missed_notifications.svg
- src/Gui/Icons/resource.qrc
- src/Gui/MainWindow.cpp
- src/Gui/NotificationArea.cpp
- src/Gui/NotificationArea.h
- src/Gui/NotificationBox.cpp
- src/Gui/NotificationBox.h
This PR addresses that non-intrusive notifications where shown when the FreeCAD window was not active (e.g. the browser or okular was active) and this was unwelcome for some use cases (as when running simulations).
Based on preferences, it can now be selected that any existing notification disappears when the FreeCAD window becomes inactive, and that notifications raised while FreeCAD is inactive are inhibited.
To compensate, when a notification was inhibited, the notification area button changes color, so that when the user comes back to FreeCAD he can access any missed notification via the widget.
> [NotificationArea] Preference based handling of non-intrusive notifications

- src/Mod/TechDraw/App/AppTechDrawPy.cpp
- src/Mod/TechDraw/App/CMakeLists.txt
- src/Mod/TechDraw/App/DimensionGeometry.cpp
- src/Mod/TechDraw/App/DimensionGeometry.h
- src/Mod/TechDraw/App/DimensionReferences.cpp
- src/Mod/TechDraw/App/DimensionReferences.h
- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/App/DrawViewDimension.h
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/Geometry.cpp
- src/Mod/TechDraw/App/Geometry.h
- src/Mod/TechDraw/App/GeometryMatcher.cpp
- src/Mod/TechDraw/App/GeometryMatcher.h
- src/Mod/TechDraw/Gui/Command.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
- src/Mod/TechDraw/Gui/QGIView.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.h
This PR implements the first phase of a solution for issue #8878.
This phase detects changes in referenced geometry and corrects the reference if an exact match is available.
Phase 2 will address partial matches.
**Note**: If …
> [TD]Dimension Reference Error Detection and Correction Ph 1 [#8878]

- .github/workflows/CI_cleanup.yml
This PR introduces a new CI workflow that is triggered when the master CI workflow ends.
It aims at cleaning the CI outputs (currently it only targets the build caches), but it may be used in a broader way in the future.
The fact that is is triggered by a 'workflow_run' event allows it to run with a privileged token even in the case where CI is originally triggered by a PR (in which case the token has no privilege).
The goals of doing this are :
* Strongly limit risk that PR caches will "push" the master branch cache to the point where it will be automatically cleaned to free space.
* Again ensure that master branch cache will stay available by the time Windows or MacOS build workflow will be added (some basic Windows workflow should be ready soon, this PR is a prerequisite for this to go …
> CI: introduce cleanup workflow

- src/Mod/AddonManager/Addon.py
- src/Mod/AddonManager/addonmanager_workers_installation.py
Updates AddonManager to use the new `best_icon_relative_path` where it was missing. Fixes #9001.
> Addon Manager: Fixes #9001, icon was string

- src/App/CMakeLists.txt
- src/App/ElementMap.h
- src/Mod/Part/App/CMakeLists.txt
- src/Mod/Part/App/TopoShapeOpCode.h
- tests/src/App/CMakeLists.txt
- tests/src/App/ElementMap.cpp
`ElementMap.h` for now contains a list of constants which will be used in the `ElementMap` class in a future phase of toponaming solution.
Intended to fix #8768.
> [Core] Create `ElementMap.h` and tests

- src/Mod/Fem/Gui/ViewProviderAnalysis.cpp
- this PR addresses a long-standing annoying issue: You are already in the FEM WB and load a file. Then you cannot just start but first have to activate the Analysis. But one is in the FEM WB to work with analyses.
> [FEM] auto-activate Analyses

- src/Mod/TechDraw/App/GeometryMatcher.cpp
> [TD] GeometryMatcher.cpp: fix compiler warning

- src/Mod/Fem/Gui/ViewProviderAnalysis.cpp
- src/Mod/Fem/femcommands/commands.py
- src/Mod/Fem/femcommands/manager.py
- src/Mod/Fem/femtools/femutils.py
- for e.g. the solver objects it is important that the added equations are visible in the TreeView
- also improve activation of analyses for documents with multiple analyses: one activates one and can then subsequently add an object to it because the activation will also select
> [FEM] implement further object addition mode

- src/Mod/Sketcher/App/ConstraintPyImp.cpp
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/planegcs/GCS.cpp
- src/Mod/Sketcher/Gui/CMakeLists.txt
- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerBSplineByInterpolation.h
- src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateBSplineByInterpolation.svg
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateBSplineByInterpolation_Constr.svg
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_Create_Periodic_BSplineByInterpolation.svg
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_Create_Periodic_BSplineByInterpolation_Constr.svg
- src/Mod/Sketcher/Gui/Workbench.cpp
Adds a new `DrawSketchHandler` for creating B-splines by interpolation. Each provided point is treated as a knot.
Fixes #8529.
This project is being funded by the Open Toolchain Foundation under the title "Open Toolchain Foundation - Curve drawing tool in Sketcher Workbench"
> [Sketcher] Command for B-spline by knot

- src/Gui/MainWindow.cpp
- src/Gui/MainWindow.h
This PR aims at improving #8870 
Main improvements are :
* Use QPushButton for lighter style display and consistency in the status bar
* Fix issue that unit schema change in Preferences or through Python isn't too into account
* Live retranslate texts when user changes UI language
> Dimension indicator improvement, improves #8870

- src/Gui/DlgEditorImp.cpp
- src/Gui/DlgEditorImp.h
because in Qt6 QSpinBox::valueChanged(QString) and QComboBox::activated(QString) have been removed
---
> Gui: fix failure of QMetaObject::connectSlotsByName

- src/Mod/Fem/Gui/Workbench.cpp
- if there is e.g. no Z88 solver available, there is no need to pollute the toolbar with an icon for it
> [FEM] only show toolbar button for available solvers

- src/Mod/Import/App/AppImportPy.cpp
This PR is offered as a correction for issues #8884 and #8806
The change leaves loading the regular import options to the `ImpExpDXFRead` class object's ctor (where the code already existed). If the caller to `readDXF` passes a fourth argument specifying another options location, this will be given to the `ImpExpDXFRead` object to load from, but otherwise `readDXF` does not initiate any options loading.
The documentation string for readDXF has been updated to include the options_source argument, which was already in the code.
Because the removed code was causing the `ImpExpDXFRead` to load settings from a location where no settings had been stored, the settings from the dialog were being ignored, so no text was being imported, layers were never grouped into blocks, and the scaling factor …
> Issues 8884, 8806. Change readDXF settings handling

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
If no one steps up to take on the challenge, then **xtemp09** will. This pull request closes #8979. The issue reported crash using _PartDesign_.
Turns out some dialogs use `Gui::Control().reject()` to close opened dialog while all other dialogs use `Gui::Control().closeDialog()`. Replacement the former with the latter prevents the segmentation fault caused by _Sketcher_. The crash does not occur with other workbenches.
---
**Note 1**. The crash occurs on all platforms, while the issue was reported on Linux Mint 20.3. I checked my patch on Ubuntu 22.04.
**Note 2**. Lurking for the culprit in the crash, I used valgrind. It reported 27 kB definitely lost, 30 kB indirectly lost and 608 kB possibly lost of memory leaks. Compilation with `-fvar-tracking -fsanitize=address,undefined` also …
> [Sketcher] Fix segmentation fault in ViewProviderSketch::setEdit

- src/Mod/Fem/femsolver/elmer/solver.py
- src/Mod/Fem/femsolver/elmer/writer.py
- different time results were never output, only the final one the reason is that the Output Intervals intervals property was missing
- a second reason was that the result scaling solver must be executed every time an output should be generated
- the BDF Order property is a transient-only property
> [FEM] Elmer: fix transient analyses

- .github/workflows/sub_lint.yml
This PR fixes a bug in Codespell Lint.
It also introduces minor improvement to limit to only needed where the `set +e` bash is used.
Fix was tested here with a dummy typo : https://github.com/0penBrain/FreeCAD/actions/runs/4518563200
> CI: fix bug in Codespell Lint

- src/Mod/AddonManager/AddonManagerTest/app/test_metadata.py
Correct the cleanup post-test.
> Addon Manager: Fix tests breaking on second run

- src/Mod/TechDraw/App/DimensionGeometry.cpp
- src/Mod/TechDraw/App/DimensionGeometry.h
- src/Mod/TechDraw/App/DrawViewDimension.cpp
This PR fixes a problem reported here: https://forum.freecad.org/viewtopic.php?p=670757#p670757
- mapToPage was left in place when converting to using projectPoint instead of projectToPlane.
---
> [TD]fix bad 3d dimensions

- .github/workflows/sub_lint.yml
As they are already checked globally before
> CI: remove trailing whitespace checks in Pylint

- src/Mod/AddonManager/CMakeLists.txt
- src/Mod/AddonManager/addonmanager_dependency_installer.py
- src/Mod/AddonManager/addonmanager_git.py
- src/Mod/AddonManager/addonmanager_pyside_interface.py
- src/Mod/AddonManager/addonmanager_uninstaller.py
- src/Mod/AddonManager/package_details.py
Apply the "Extract Interface" refactoring to the three pieces of QtCore that can be treated as optional in some Addon Manager classes to enable external unit testing.
> Addon Manager: Extract PySide QtCore interface

- src/Mod/Draft/importDXF.py
This is a fix for an issue with the OpenSCAD workbench, as proposed in the forums by user "imm": see https://forum.freecad.org/viewtopic.php?p=669987#p669987
The function signature makes it seem like you can pass `None` for various values, but the original code fails if you actually do so. This new code provides default values for all three input values, ensuring that the function call will succeed.
> Draft: Handle wantedLayer is None

- src/3rdParty/libE57Format/include/E57Format.h
Adding missing header file. Also submitted this upstream here:
https://github.com/asmaloney/libE57Format/pull/243
> libE57Format: fix compile using gcc13

- src/Mod/Part/App/PropertyGeometryList.cpp
- src/Mod/Part/App/PropertyGeometryList.h
Since not all Geometry sub-classes fully implement Save() / Restore() raising an exception instead may invalidate a project. To avoid this PropertyGeometryList now explicitly handles NotImplementedError exceptions.
See also: https://forum.freecad.org/viewtopic.php?t=77148 …
> Part: make PropertyGeometryList more permissive

- src/Mod/Part/App/TopoShapePy.xml
---
[https://wiki.freecad.org/TopoShape_API](https://wiki.freecad.org/TopoShape_API) correctly describes this method, but the console tool-tip currently suggests using an incorrect extra argument.
> fix incorrect docstring for Part.Shape.extrude method

- src/Mod/OpenSCAD/OpenSCADUtils.py
Removed redundant python2 unicode syntax from `OpenSCADUtils.py`
---
> OpenSCAD: removed deprecated python2 unicode string

- src/Mod/PartDesign/App/FeatureChamfer.cpp
- src/Mod/PartDesign/App/FeatureDraft.cpp
- src/Mod/PartDesign/App/FeatureFillet.cpp
- src/Mod/PartDesign/App/FeatureThickness.cpp
- src/Mod/PartDesign/Gui/Command.cpp
- src/Mod/PartDesign/Gui/TaskChamferParameters.cpp
- src/Mod/PartDesign/Gui/TaskChamferParameters.h
- src/Mod/PartDesign/Gui/TaskChamferParameters.ui
- src/Mod/PartDesign/Gui/TaskDraftParameters.cpp
- src/Mod/PartDesign/Gui/TaskDraftParameters.h
- src/Mod/PartDesign/Gui/TaskDraftParameters.ui
- src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
- src/Mod/PartDesign/Gui/TaskDressUpParameters.h
- src/Mod/PartDesign/Gui/TaskFilletParameters.cpp
- src/Mod/PartDesign/Gui/TaskFilletParameters.h
- src/Mod/PartDesign/Gui/TaskFilletParameters.ui
- src/Mod/PartDesign/Gui/TaskThicknessParameters.cpp
- src/Mod/PartDesign/Gui/TaskThicknessParameters.h
- src/Mod/PartDesign/Gui/TaskThicknessParameters.ui
For the tools Fillet, Chamfer, Draft, Thickness in PartDesign : 
- Merge Add and Remove in one button.
- Enable those features to be empty. This let us start the tool before selection.
- Refactor the code that had needless duplicates.
- Fix bug (fillet, click addAllEdges after having a face in the list. Then the list has more entries than the feature has references. So if you delete the last element of the list, crash.)
Issue : https://github.com/FreeCAD/FreeCAD/issues/8909
Forum Dicussion :
https://forum.freecad.org/viewtopic.php?t=76989&start=10
Video explanation : 
https://youtu.be/3mHUwT8-pwQ
Testers and reviewers welcome !
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the …
> PartDesign: Fillet, Chamfer, Draft, Thickness rework.

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftfunctions/svgtext.py
- src/Mod/Draft/draftutils/translate.py
- src/Mod/Draft/importAirfoilDAT.py
- src/Mod/Draft/importDXF.py
- src/Mod/Draft/importOCA.py
- src/Mod/Draft/importSVG.py
Since switching to Python 3 the decode code is obsolete. See: #9021.
---
> [Draft] Remove obsolete decode code

- src/Mod/Part/App/FT2FC.cpp
This PR addresses an issue with non-ascii filename on the windows platform as reported here: https://forum.freecad.org/viewtopic.php?t=77191
hank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.
---
> [Part]handle unicode filename on win

- src/Mod/PartDesign/App/FeatureLinearPattern.cpp
- src/Mod/PartDesign/App/FeaturePolarPattern.cpp
In LinearPattern and PolarPattern. Skip all checks if occurrences is 1. Allows Expressions on Length/Angle that evaluates to 0 if Occurrences is 1.
This PR fixes issue #8935
> PartDesign: Patterns, return directly if occurrences is 1

- src/Mod/Part/Gui/TaskOffset.cpp
- src/Mod/Part/Gui/TaskThickness.cpp
- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
This PR is an attempt to solve crashes on MacOS described here :
https://forum.freecad.org/viewtopic.php?t=75442
https://forum.freecad.org/viewtopic.php?t=77234
> Gui: prevent crashes on MacOS using boost::format

- src/Mod/TechDraw/App/CMakeLists.txt
- src/Mod/TechDraw/App/XMLQuery.cpp
- src/Mod/TechDraw/App/XMLQuery.h
- src/Mod/TechDraw/Gui/CMakeLists.txt
> Techdraw: finish Qt6 port

- conda/environment.devenv.yml
---
Upstream conda-forge moved their pinning from `libcxx==15` to `libcxx==16` which led to build failures for projects that include boost.  Boost utilizes `std::unary_function` which has been removed in C++17 and is not …
> Pin conda package libcxx<16 to build with boost 1.78.0.

- .clang-tidy
Get rid of `readability-qualified-auto` (which enforces the LLVM coding standard of qualifying pointer-typed auto variables with a *, e.g. `auto *myPointer` instead of `auto myPointer`). IMO the last thing C++ needs is more punctuation marks 😄 .
> Clang-Tidy: Remove readability-qualified-auto

- .pre-commit-config.yaml
This is the first step towards resolving #8232 (and towards unifying our formatting so that we can eliminate superfluous formatting changes from PRs, speeding up the review process).
As [discussed in the forums](https://forum.freecad.org/viewtopic.php?t=77205), this is the first step in a multi-step process of unifying our code formatting. The overall idea is to use [pre-commit hooks](https://pre-commit.com) to auto format the code, _prior to the creation of the commit_. This all happens locally, and depends on developers installing the "pre-commit" Python package (e.g. `pip install pre-commit` and then `pre-commit install`). If a file in a proposed commit fails the checks, the hook automatically modifies the file in questions, and the developer must `git add` the modified file again to …
> Git: Add pre-commit configuration

- src/Mod/Points/App/AppPointsPy.cpp
* Added one return statement into try-catch block which returns the appropriate object (instead of `None`).
* Behaviour now in line with `Part.show`.
Example:
```Python
>>> import Points
>>> pp = Points.Points()
>>> pp.addPoints([(1,2,3),(4,5,6)])
>>> go = Points.show(pp)
>>> go  # Former behaviour was to return None
<GeoFeature object>
>>> go.ViewObject.ShapeColor = (1.,0.,0.)
>>> go.ViewObject.PointSize = 20
```
Please remember to update the Wiki with the features added or changed once …
> Points: `show` now returns an `GeoFeature` object

- src/Mod/Path/Path/Base/Drillable.py
This fixes one cause of valid holes not getting included in Drill/Helix Ops due to a list iteraton off-by-one counter.  Detailed explanation at https://forum.freecad.org/viewtopic.php?style=5&t=77055 (the first cause discussed on that post, disregard the 2nd as I'm still investigating/working on that one) …
> [PATH] Update getDrillableTargets() to evaluate all faces 1..<n>

- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/DrawUtil.h
- src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
- src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
This PR does the following:
1) Move the helper function **getTrianglePoint** to the file DrawUtil.
2) Extend the command **CmdExtensionPositionSectionView** to manage rotated section views.
---
> [TD] Extend command CmdExtensionPositionSectionView to manage rotated section views

- src/App/Expression.cpp
https://forum.freecad.org/viewtopic.php?t=77287
I should say I didn't really understand current code.
`std::numeric_limits<double>::digits10` is exactly the maximum precision to ensure no floating point rounding issue.
So setting it to `+ 1` is just making a step to the world of problems. :smile:
> Expression: use a precision that ensures no floating point issue

- .github/workflows/CI_master.yml
- .github/workflows/actions/windows/getCcache/action.yml
- .github/workflows/actions/windows/getLibpack/action.yml
- .github/workflows/sub_buildWindows.yml
Well, this is what I ended up as an initial Windows workflow.
It has following structure :
* Uses ccache as a caching program
* Builds with MSVC
* 2 actions are created so we can use a GH cached version of LibPack and CCache to reduce compilation time
* Only CLI tests (unit tests seems to not be here -- didn't investigate much -- and I didn't looked at GUI tests yet)
* No report is generated yet, just the status is reported in the summary (PowerShell isn't my friend actually)
I tried to optimize running delay but still it's generally longer than the Ubuntu builds (from about 5 to 15 min) and so will be the bottleneck of the CI.
One of things that takes some minutes is copying the libpack bin folder to build directory.
I tried to instead add the folder to PATH but tests fail. So it looks …
> CI: initial release of Windows build workflow

- src/Mod/Sketcher/App/planegcs/GCS.cpp
As requested by @abdullahtahiriyo. See https://forum.freecad.org/viewtopic.php?t=76724#p673116.
Still needs to eliminate the switch/case from `GCS::free(std::vector<Constraint*>)`, to simply [delete the constraint instead of `static_casting` the many possible derived classes](https://github.com/FreeCAD/FreeCAD/blob/84808ef7bd0752e60e8050b3f8e5edef2afa5e29/src/Mod/Sketcher/App/planegcs/GCS.cpp#L5590).
---
It does not. Sorry!
Tests did not pass clean, but they did not pass clean using the …
> Deletes GCS::Constraint directly instead of calling GCS::free().

- .pre-commit-config.yaml
The enables pre-commit for the `test/src` subdirectory (and shows how to add additional paths using the verbose regex syntax).
> Precommit: Enable in tests/src

- .github/workflows/sub_buildWindows.yml
This PR aims at reducing CI execution time for Windows job.
By moving the bin folder "manually" instead of using the CMake option that copies it, time is reduced by 2 to 3 minutes.
> CI: move libpack dir instead of copying it

- src/Mod/Path/Path/Op/Drilling.py
Recent changes to had G98/G99, ended up causing horizontal feedrate to be used these drilling operations.  This fix corrects that and does some fluke8 clean ups. …
> Path WB: Correct bug causing incorrect feedrate to be used.

- src/Base/CMakeLists.txt
- src/Base/PythonTypeExt.cpp
- src/Base/PythonTypeExt.h
- src/CXX/Python3/ExtensionType.hxx
- src/Gui/Application.cpp
- src/Gui/CMakeLists.txt
- src/Gui/Command.cpp
- src/Gui/Command.h
- src/Gui/CommandActionPy.cpp
- src/Gui/CommandActionPy.h
- src/Gui/Workbench.cpp
- src/Tools/generateBase/generateMetaModel_Module.xsd
- src/Tools/generateBase/generateModel_Module.py
- src/Tools/generateTemplates/templateClassPyExport.py
This PR contains two commits:
The first  add support for descriptor objects.
On the PyCXX side, the `set_tp_descr_get` and `set_tp_descr_set` functions are added to the `Py::PythonType` class.
For C++ extensions generated via xml files, the boolean attributes `DescriptorSetter` and `DescriptorGetter` are added to the initial tag of the `PythonExport` element.
then in the file `MyClassPyImp.cpp` you must add the definition of the functions:
`PyObject* MyClassPy::descriptorGetter(PyObject* self, PyObject* obj, PyObject* type)`
`int MyClassPy::descriptorSetter(PyObject* self, PyObject* obj, PyObject* value)`
\
\
In the second commit  the `CommandActionPy` class is added (as an example of the use of descriptors) which allows full access to the action of the commands from Python code through a …
> src: Add descriptor protocol support for Python C++ extension modules

- src/Mod/TechDraw/App/CosmeticVertex.cpp
- src/Mod/TechDraw/App/CosmeticVertex.h
A clean recompile on Windows was failing because of a couple of precompiled header issues.
> TechDraw: Fix Windows compilation

- src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
This PR fixes issue #9223.
- Area dimension extension was not checking that only faces were in the selection. …
> [TD]fix missing selection guard (#9223)

- src/Mod/Draft/draftguitools/gui_trackers.py
This is a fix for the issue described in [the forum](https://forum.freecad.org/viewtopic.php?t=77293)
`coin.SoCoordinate3()` used in the `EditTracker` class rounds the x,y,z values. The loss of precision is not a lot (few micrometers) but it's apparently enough to create problems with planar faces and boolean operations.
This PR modifies the `set` and `get` functions of `EditTracker` so that the position is saved with precision in a `App.Vector`
Set as draft because I didn't test it a lot.
------
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't …
> Draft: Fix inaccuracy in Draft Edit command

- src/Gui/Workbench.cpp
The menu item "View -> Toggle visibility" is redundant. It is also available via "View -> Visibility -> Toggle visibility" right next to it.
The FreeCAD menu is already quite cluttered and I propose to remove the redundant entry.
---
> removed redundant "Toggle visibility" menu item from View menu

- src/Mod/Import/App/dxf/dxf.cpp
- src/Mod/Import/App/dxf/dxf.h
This addresses #8704 and replaces #8862 which I accidentally closed while trying to clean up.
The C++ importer incorrectly treated the contents of all TEXT and MTEXT objects as beind encoded as UTF-8, but this is not true for DXF files before AutoCAD 2007, where the encoding is "plain ASCII" plus some in-band \U+dddd encoding. This would cause errors if the text contained non-ASCII characters such as the Degree Sign.
This change causes the correct encoding to be used.
- [X ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
> Fix encoding error for import from older DXF files

- .github/workflows/sub_buildUbuntu2204.yml
Problems have been fixed upstream
> CI: remove pivy patching on Ubuntu 22.04 workflow

- src/Gui/NaviCube.cpp
The navigation cube labels are user visible and therefore need i18n and L10n. This pull request adds the necessary i18n.
---
> added i18n for navicube labels

- src/Gui/CommandView.cpp
The WindowTitle was changed to match the menu text of the Std_ViewLoadImage command.
---
> Gui: CommandView.cpp: Fix typos and more consistent WindowTitle

- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui
This PR corrects the default values for extension line gaps.  The default should be zero for both ISO and ASME. …
> [TD]Correct default extension line gaps

- src/Mod/Part/App/FT2FC.cpp
I compiled FreeCAD with leak sanitizer, did some things in Draft. When I closed the program, it reported enormous memory leak. Staring into the code, I found out that FreeCAD allocates memory to load font file, however, nowhere deallocates.
The quick one-line patch with automatic memory management fixed it.
I also deleted unnecessary includes.
---
<details><summary>Standard form</summary> …
> Fix memory leak when loading a font file

- src/Gui/Tree.cpp
- src/Gui/Tree.h
The current implementation of hiding/showing objects in the tree view is cumbersome (only one single item can be toggled per execution) and inconsistent (hidden objects are still shown, even when the option to show them is disabled, only works after enabling and disabling the option again).
The patch in this pull request fixes these issues.
---
> added support for multi selection when toggling visibility in tree view

- src/Mod/Part/App/FT2FC.cpp
In my previous PR I replaced `char* buffer = new char[bytesNeeded];` with `auto buffer = std::unique_ptr <char> (new char[bytesNeeded]);`
The line should be `std::unique_ptr <char[]> buffer (new char[bytesNeeded]);`
I don't know the reasons why the leak disappeared, but I have two theories
-	it results from compilers optimizations
-	the leak became undetectable
Please, apply this patch.
---
<details><summary>Standard form</summary>
Please remember to update the Wiki with the features …
> Fix the typo in #9267

- src/Mod/Path/Path/Op/Base.py
This allows subclasses to override opPropertyEnumerations and have their defaults set by ObjectOp.__init__
Started a conversation here. https://forum.freecad.org/viewtopic.php?t=77274
The Path unit tests run as expected with this change in place, so I believe this should have no side effects.
> Path: set enumeration default properties after `.initOperation`

- src/Mod/TechDraw/App/GeometryObject.cpp
- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/App/Preferences.h
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvancedImp.cpp
This PR adds a function to preprocess the result of the HLR algorithm and remove overlapping edges.  In some cases, multiple passes of the edge scrubbing algorithm are required, so a preference has been added to control the number of passes. 
Please remember to update the Wiki with the features added or changed once this …
> [TD]Remove Overlapping HLR Edges

- src/Tools/updatets.py
The updatets.py script fails because the Image workbench is no longer there. This PR fixes this issue.
But this PR is still incomplete, there are some more fixes needed to improve i18n and L10n, but I need your help. Please allow me to elaborate:
I am working at a university in Switzerland, using the Swiss German locale. While general i18n and a German L10n of FreeCAD is there, me and my students always run into untranslated user visible strings that stick out like a sore thumb.
All I wanted to do yesterday was to fix the issue that new documents show up untranslated as "Unnamed" instead of "Unbenannt" in German.
The string "Unnamed" can be found at the Crowdin-Website:
https://crowdin.com/translate/freecad/549/en-de?filter=basic&value=0#6497188
... but it was already translated a long …
> removed Image workbench from directories list

- src/Mod/Sketcher/Gui/Command.cpp
---
This specific boolean variable could be used uninitialized. Assigning it a default value is cheap and it avoids the issue.
I have been able to detect the issue thanks to UBSAN, which unfortunately _just_ detected an …
> Fix uninitialized member variable

- src/Gui/Widgets.cpp
This commit fixes issue #7322. When setting option the initial color is discarded. It needs to be reset, like it's done in `void ColorButton::showModal()`.
<details><summary>Before</summary>
https://user-images.githubusercontent.com/9303235/232278731-bcfd38b8-0655-4fc2-a5ab-1b8d9bd00d0d.mp4
</details>
<details><summary>After</summary>
https://user-images.githubusercontent.com/9303235/232278734-5d32ccf1-4ab9-4961-901a-73e2be9eb0b4.mp4
</details>
---
<details><summary>Standard form</summary>
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't …
> [GUI] Setting initial color of QColorDialog

- src/Mod/TechDraw/App/DrawProjectSplit.cpp
- src/Mod/TechDraw/App/DrawProjectSplit.h
- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/DrawUtil.h
- src/Mod/TechDraw/App/GeometryObject.cpp
This PR corrects an unwanted Y coordinate inversion when cleaning edges from HLR. …
> [TD]fix unwanted inversion in edge scrubbing

- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewPart.h
- src/Mod/TechDraw/App/GeometryObject.cpp
- src/Mod/TechDraw/App/GeometryObject.h
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
This PR adds a property for the number of edge cleaning passes to be made.  Previously this number was a system wide preference.
---
> [TD]make scrubbing count a property of view

- src/Gui/Quarter/QuarterWidget.cpp
---
When an event type is `QEvent::Wheel`, the event type is `QWheelEvent`, which is not a `QMouseEvent`. This caused a undefined behavior that can be cached by ubsan.
> Fix wrong downcasting of QEvent

- src/Gui/QuantitySpinBox.cpp
[GUI] QuantitySpinBox: more intuitive parsing before handoff to expression parser.
More robust parentheses, multiplication, division, exponent handling.
---
Contains modifications discussed here: …
> [GUI] QuantitySpinBox: more intuitive parsing

- src/Mod/Sketcher/Gui/TaskSketcherMessages.cpp
- src/Mod/Sketcher/Gui/TaskSketcherMessages.h
================================================
I promised Uwe I would look into improving the information of the solver messages, including the abbreviation DoF.
I wanted to keep the effort by Paddle to reduce the width of the taskbar.
This commit introduces new explanatory tooltips for the hyperlinks, a different tooltip per type of information.
UrlLabel sets the tooltips automatically to the url text on change. This commit modifies the tooltip just after the change, so that the meaningful tooltip is shown.
> Sketcher: Tooltips for solver message hyperlinks

- src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp
=========================================================
Fixes an issue reported directly by Chrisb.
On overlapping points, such as due to coincidence, selection and preselection (e.g. from the ElementsWidget) is not shown for those points which are rendered first.
Solution: To raise the points to the highlight height.
> Sketcher: Fix overlapped points not selecting/preselecting

- src/Mod/TechDraw/App/ArrowPropEnum.cpp
- src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/46. The base enum is unchanged by this operation (which uses NOOP to ensure the char * is unchanged). Only on actual display in the user interface is the translated value used. It appears that this was actually the original intent, but it didn't work because the translatable strings were never added to the database. Internally, only the numeric index of the current entry is used, so the actual displayed text can be anything.
> TechDraw: Translate leader line arrow shapes

- src/Gui/PythonWrapper.cpp
- src/Gui/PythonWrapper.h
This PR overloads the existing toQGraphicswItem and toQGraphicsObject methods in PythonWrapper to accept a reference.
This PR is a prerequisite for future PRs which will add functions for adding graphics to TechDraw Pages from Python. …
> [Gui]overload toQGraphicsItem, toQGraphicsObject for PyObject

- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/App/Geometry.cpp
- src/Mod/TechDraw/App/Geometry.h
- src/Mod/TechDraw/App/GeometryMatcher.cpp
This PR corrects a situation where straight lines which are actually BSplines were not being handled correctly in the GeometryMatcher. …
> [TD]Handle BSpline Straight Lines

- src/Mod/Sketcher/Gui/CommandAlterGeometry.cpp
Forum:
https://forum.freecad.org/viewtopic.php?p=677304#p677304
A common operation is to toggle a group of geometry to/from construction. This happens often in connection with carbon copy operations.
When this happens, geometry is often selected using box selection.
If there are geometry points (which are generally construction), and selection box is used, this results in construction points being toggled to normal defining mode. This situation is undesirable in 99% of the cases. It requires to reselect only the points and toggle them back.
When construction points need be made defining geometry (for example to use them as attachments), the general workflow is to select only those points and toggle them.
In order to improve the efficiency, it has been decided to provide a special …
> Sketcher: Change behaviour of toggle of mixed group of edges and vertices

- src/Mod/Mesh/Gui/DlgRegularSolid.ui
We got a question on CrowdIn about this one. I don't think there's any reason to maintain this shortcut, it's totally unintuitive, and Esc closes the dialog just fine. Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/129
> Mesh: Eliminate Alt+O as a shortcut for close

- src/Gui/DlgSettingsNavigation.cpp
- src/Gui/DlgSettingsNavigation.h
- src/Gui/DlgSettingsNavigation.ui
- src/Gui/NaviCube.cpp
- src/Gui/NaviCube.h
- src/Gui/View3DInventor.cpp
- src/Gui/View3DInventorViewer.cpp
- src/Gui/View3DInventorViewer.h
- src/Gui/View3DSettings.cpp
- src/Gui/View3DSettings.h
This PR does not conform to the one issue recommendation. Hopefully you can bear reviewing it anyway.
Fixes #9262 
Fixes #6935 
Fixed #6818 
But also a non registered issue from the forum:
[https://forum.freecad.org/viewtopic.php?t=77768](url)
Will hopefully also fix a problem on Raspberry Pi
[https://forum.freecad.org/viewtopic.php?t=76438](url)
Here is a list of changes
- Uses std commands in menu coming with icons
- Cube only draggable if activated in menu 
- ![Skärmavbild 2023-04-22 kl  17 14 49](https://user-images.githubusercontent.com/39026960/233792751-12f7bc02-80a9-41f0-a2f3-50d6f673e724.png)
- Ortographic and Perspective reflected in Navigation Cube
- ![Skärmavbild 2023-04-22 kl  17 18 21](https://user-images.githubusercontent.com/39026960/233792902-76bc45e6-f92c-4f41-8773-7155 …
> Refactor Navigation Cube

- src/App/Origin.cpp
I think it is very unkind of the Z-axis to turn its back on us by default. Therefore, I propose the following change, so that the labels of all axes and planes are readable by default:
---
> changed Z-axis rotation so that it is readable by default

- src/Mod/TechDraw/Gui/QGIViewAnnotation.cpp
Version 0.19 stored annotations as escaped unicode, but v0.20 expects utf8.  This PR implements a check for "\x" in the text, and, if present, treats the text as escaped unicode, otherwise it treats the text as utf8.  This change affects display only, it does not change how text is stored.
Please remember to update the …
> [TD]display escaped unicode annotations

- src/Mod/Path/Path/Main/Gui/Job.py
Removes trailing whitespace from `src/Mod/Path/Path/Main/Gui/Job.py` and adds capitalization.  
Closes #9383
---
> Path: move trailing whitespace out of l10n string

- src/Mod/PartDesign/WizardShaft/WizardShaft.py
- src/Mod/PartDesign/WizardShaft/WizardShaftTable.py
This addresses some of the translation problems with the Part Design shaft wizard. Many of the combobox entries are directly used as the name of constraints in FEM, however, so in the current implementation cannot be translated without breaking the Wizard. This design should be changed. Addresses some of the issues in https://github.com/FreeCAD/FreeCAD-translations/issues/4
---
> PD/ShaftWizard: Correct some translation issues

- src/Gui/Application.cpp
- src/Gui/Application.h
- src/Gui/ApplicationPy.cpp
- src/Gui/CommandStd.cpp
The tip text was extracted from the Wiki. Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/102
This took more code than anticipated (considering that this button isn't even visible by default anymore). I'm not thrilled with the design, but it didn't seem worth putting in more time. If anyone objects I'll happily take suggestions.
---
> GUI: Translate the tooltip for EditMode menu

- src/Mod/PartDesign/Gui/TaskHelixParameters.cpp
This probably fixes https://github.com/FreeCAD/FreeCAD-translations/issues/22, but it will require verification because the messages don't quite match the reported error.
> PD: Helix parameters status translation

- src/Mod/TechDraw/App/DrawViewAnnotation.cpp
- src/Mod/TechDraw/App/DrawViewAnnotation.h
- src/Mod/TechDraw/Gui/QGIViewAnnotation.cpp
This PR implements a partial fix for issue 9365.  It is the v021 equivalent of PR #9389 which applied to v0.20.
From PR9389:
Version 0.19 stored annotations as escaped unicode, but v0.20 expects utf8. This PR implements a check for "\x" in the text, and, if present, treats the text as escaped unicode, otherwise it treats the text as utf8. This change affects display only, it does not change how text is stored.
- [ x]  Your Pull Request meets the requirements outlined in section 5 of …
> [TD]Handle escaped unicode from old versions (partial fix for 9365)

- src/Mod/Draft/importSVG.py
Handle 'none' color => Default to black (+ print message)
Handle #RRGGBBAA color => Return alpha (+ print, message)
Handle 'rgba(float, float, float, float) => Return alpha (+ print message)
Reorganize function to return ASAP + print warning if unknown color format
https://forum.freecad.org/viewtopic.php?p=675119#p675119
> Draft: Improve color handling of SVG geometry importer

- src/Mod/Draft/Resources/ui/preferences-dxf.ui
- src/Mod/Draft/draftfunctions/dxf.py
- src/Mod/Draft/importDXF.py
This PR removes the (hopefully) last bits of Drawing WB related code.
As mentioned here:
https://github.com/FreeCAD/FreeCAD/pull/8918#issuecomment-1493297591
Please note that both the old and the new code have their issues. Some of it seems semi obsolete. The new code works but `TechDraw.projectToDXF` does not always produce output that matches the view.
---
> Draft: Remove Drawing WB related code from DXF related files

- src/Mod/TechDraw/App/CMakeLists.txt
- src/Mod/TechDraw/App/XMLQuery.cpp
This PR removes code based on the Qt5 Svg handling classes that are no longer available in Qt6. Code using a replacement was implemented by #9421 and #9104.
---
> [TD]remove Qt5 Svg handling code

- .github/workflows/actions/runCPPTests/runAllTests/action.yml
- .github/workflows/actions/runCPPTests/runSingleTest/action.yml
- .github/workflows/sub_buildUbuntu2004.yml
- .github/workflows/sub_buildUbuntu2204.yml
Now that Sketcher has independent C++ tests, it needs to be explicitly added to the CI.
> Tests: Add Sketcher tests to CI

- src/Mod/Sketcher/Gui/Command.cpp
Should fix https://github.com/FreeCAD/FreeCAD-translations/issues/157 -- this dialog is created in two different places, this PR syncs them up (but does not eliminate the duplication).
---
> Sketcher: Translate the menu entries in attach dialog

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
Suggested for consistency by david69 on CrowdIn.
> Sketcher: Tweak wording as suggested by translators

- src/Gui/DlgGeneralImp.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/207
Qt's translation facilities render Serbian, Latin (which CrowdIn delivers as *_sr-CS.ts) in Cyrillic, which gives us two entries for Српски, rather than one for Српски (Serbian, Cyrillic) and one for Srpski (Serbian, Latin). This ugly hack simply replaces the country-coded BCP 47 value with the script-coded variant during construction of the menu. This doesn't affect anything else in FreeCAD, and all translations work as before.
---
> GUI: Transform sr-CS to sr_Latn in menu entry

- src/Mod/Sketcher/App/planegcs/GCS.cpp
==========================================
fixes #6174
Problem
=======
The popularity contest heuristic was designed to assume that removing one solver constraint from a redundant group would potentially satisfy it.
This means that for sketcher constraints comprising several solver constraints, the sketcher constraint would never be notified as redundant, but always partially redundant (where the case may be that it is redundant or that it is partially redundant). This happens because after removing one solver constraint, it may happen:
(a) that no other solver constraint corresponding to the sketcher constraint remains in the redundant group (so it is indeed partially redundant) (b) that at least one other solver constraint corresponding to the sketcher constraint remains in the …
> Sketcher: Fixes wrong redundancy reporting

- src/Mod/Path/Path/Op/Gui/Base.py
This updates the GUI Base Geometry Import button to iterate through all bases of the source op and add each of them to the current op.
---
> PATH: Change GUI Op Base Geometry Import button to support multiple bases

- src/Mod/PartDesign/Gui/Utils.cpp
Closes #9382. [usakhelo](https://github.com/usakhelo), the original author of the function `isFeatureMovable`, politely [refused](https://github.com/FreeCAD/FreeCAD/issues/9382#issuecomment-1522224360) to contribute to FreeCAD.
The cause of segmentation fault was attempted access to nonexistent `App::DocumentObject* const feat` (it was `nullptr`).
I concluded that if there is no object, so it cannot be moved. I can be wrong.
---
<details><summary>Standard form</summary>
Please remember to …
> Fixed segmentation fault in PartDesign workbench

- src/Gui/ViewProviderOrigin.cpp
- src/Gui/ViewProviderOrigin.h
- src/Gui/ViewProviderOriginFeature.cpp
- src/Gui/ViewProviderPlane.cpp
The planes of the origin currently consist only of the surrounding lines, which are very difficult to distinguish visually, especially when rotating.
In this pull request I have added a semi transparent face to each plane, which improves their visibility.
---
> Gui: added semi transparent face to origin planes

- src/Gui/ViewProviderOrigin.cpp
This way the backside of the label is displayed with the same color as the front side. Otherwise it may be black.
---
> Gui: disable lighting for the label of an axis

- src/App/Document.cpp
A message that is displayed in Report View telling users to check Report View is not terribly useful. Even when this displays in the new notifications system, it's probably not necessary.
---
> GUI: Don't have report view message tell users to see report view

- src/Mod/Draft/importDWG.py
Fixes #9400.
Fixes #9401.
For each of the supported converters there is now a `get` function and things have been made more consistent in general. Some error message have been improved.
For all converters the `"TeighaFileConverter"` parameter is checked for the presence of the correct string in the file name.
For LibreDWG `os.getenv("PATH")` is used to find the actual file.
For QCAD the common paths for Linux and Windows are searched. On Windows QCAD's dwg2dwg.bat requires changing the working directory with `cwd`.
In all cases checks are made to ensure that the path exists and is in fact a file.
The code has been tested on Windows (all 3 converters) and Ubuntu (LibreDWG and QCAD, I could get the ODA converter installed but it won't run for some reason).
---
> Draft: improve handling of DWG-converters

- src/Mod/Arch/ArchPanel.py
- src/Mod/Draft/draftviewproviders/view_base.py
- src/Mod/Draft/draftviewproviders/view_fillet.py
- src/Mod/Draft/draftviewproviders/view_point.py
The object then seems to be put into edit mode twice (?) and Esc will not cancel the command.
Forum post:
https://forum.freecad.org/viewtopic.php?p=677099#p677099
As a workaround `doubleClicked` is used. This function takes precedence over all double-click edit modes. It can be used here because the affected objects (Fillet, Point, Shape2DView and PanelCut) currently only support a single edit mode.
---
> Draft: Std_TransformManip should not be called from setEdit

- src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
In the Elements context menu (Sketcher task panel) the menu text for Sketcher_ToggleConstruction is "Toggle construction line", this should be "Toggle construction geometry". It is not just lines that can be toggled, and this is also the menu text in the main Sketcher menu.
---
> Sketcher: improve context menu text for Sketcher_ToggleConstruction

- src/Mod/Sketcher/Gui/EditModeCoinManager.cpp
- src/Mod/Sketcher/Gui/EditModeCoinManager.h
- src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h
- src/Mod/Sketcher/Gui/EditModeGeometryCoinConverter.cpp
- src/Mod/Sketcher/Gui/EditModeGeometryCoinConverter.h
- src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp
- src/Mod/Sketcher/Gui/EditModeInformationOverlayCoinConverter.cpp
- src/Mod/Sketcher/Gui/EditModeInformationOverlayCoinConverter.h
Fix #9177
The circle overlay is enabled by default and removable by setting Mod/Sketcher/General/ArcCircleHelperVisible preference to False.
> Sketcher: add a circle overlay for arcs

- src/Gui/NaviCube.cpp
- src/Gui/SplitView3DInventor.cpp
- src/Gui/View3DSettings.cpp
* initialize base and hilite color with more snesible default values
* handle case if no font name is set
* apply user preferences to NaviCube
---
> Gui: fix NaviCube in split views:

- src/Gui/NaviCube.cpp
---
This PR replaces the huge switch that determined the camera orientation after clicking on a NaviCube face. The standard orientation is now stored in the face when it is created and a method is added to find the nearest …
> Gui: Refactor NaviCube camera orientation handling

- src/Mod/Path/Gui/Resources/panels/PageOpCustomEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpDrillingEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpEngraveEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpProbeEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpSlotEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpSurfaceEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpVcarveEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpWaterlineEdit.ui
- src/Mod/Path/Gui/Resources/panels/SurfaceEdit.ui
In cases where this isn't being used specifically to access the property in code (e.g. it's just a UI label), put a space between the terms.
---
> Path: 'ToolController' -> 'Tool Controller' in UI panels

- src/Mod/Draft/importSVG.py
Styles applied to groups will now be applied to all their children, unless overridden
fixes #6900
> Draft: Support group styles in SVG import - fixes #6900

- src/Mod/Draft/Resources/ui/TaskPanel_SetStyle.ui
- src/Mod/Draft/draftguitools/gui_setstyle.py
Dim Overshoot, Ext Lines and Ext Overshoot parameters were missing from the Draft "Set Style" button task dialog
---
> Draft: Added dim overshoot parameters to Style task dialog

- src/Mod/Draft/Resources/ui/preferences-dxf.ui
On the Import/Export -> DXF preferences page, user has the option to use the legacy py importer or exporter, instead of the newer C++ ones. But not all options apply to both importers/exporters. This PR indicates next to the different options which is used by the legacy scripts only.
fixes #6001
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog …
> Draft: Indicate which DXF pref option is for legacy importer/exporter only

- src/Mod/Start/StartPage/LoadCustom.py
Clicking a file in a custom folder did not call the correct module because of a difference between FreeCAD.loadFile() and FreeCADGui.loadFile()
> Start: Fixed loading from custom folder

- src/Mod/Draft/Resources/ui/preferences-draftvisual.ui
- src/Mod/Draft/draftfunctions/svg.py
Better defaults for dashed, dotted and dashdotted lines in TechDraw DraftView objects
fixes #6733
> Draft: Better svg linestyle settings - fixes #6733

- src/Mod/Arch/ArchWall.py
If the length of a sketch based wall was changed the new point was not converted to the coordinate system of the sketch.
Additionally:
Added a recompute as a workaround for the 'GeoId index out range' error.
---
> Arch: endpoint after Wall length change was not in local sketch coords

- src/Tools/updatecrowdin.py
Using `system` to execute `lrelease` causes problems with Windows paths when run from within MinGW (and is discouraged for a host of other reasons). This PR migrates to an identical call that uses subprocess instead.
---
> Tools: switch to subprocess

- src/Base/UnitsApi.cpp
- src/Base/UnitsApi.h
- src/Base/UnitsApiPy.cpp
- src/Gui/DlgGeneralImp.cpp
- src/Gui/DlgUnitsCalculatorImp.cpp
- src/Gui/MainWindow.cpp
When we modified the preferences dialogs we lost the translation of the unit system text. This restores it, and attempts to ensure that the translated text is *always* used. There shouldn't be any reason to use the untranslated base strings, so they are no longer available to calling code, which always gets the translated strings now. Closes https://github.com/FreeCAD/FreeCAD-translations/issues/220
---
> Gui: Translate unit system UI

- src/Mod/OpenSCAD/Resources/ui/openscadprefs-base.ui
> OpenSCAD: Minor wording tweak in preferences

- src/Gui/Splashscreen.cpp
As promised in #9596, here's the equivalent hack to get the proper Windows 11 version based on the current build number.
> Gui: Hack to get Windows 11 version

- src/Gui/Window.cpp
- src/Gui/Window.h
If a observer is connected directly to the signal of the ParameterManager, the observer is only notifed when a parameter value changes. So if is necessary to avoid recomputations, this strategy can by used instead the traditional `OnChange` function.
Sub-classes  of `WindowParameter` class can define a slot function with the appropiate signature:
`void MyClass::slot(ParameterGrp*, ParameterGrp::ParamType, const char*, const char*)`
and then connect using `setSlotParamChanged(&MyClass::slot, this)`
In `setGroupName` the group path is now checked using a regular expression.
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD …
> Gui: Add function in WindowParameter class to connect slot to ParameterManager signal

- src/Gui/Language/FreeCAD_es-ES.ts
- src/Mod/AddonManager/AddonManager.py
- src/Mod/Arch/InitGui.py
- src/Mod/Draft/InitGui.py
- src/Mod/Mesh/Gui/AppMeshGui.cpp
- src/Mod/Path/Gui/AppPathGui.cpp
- src/Mod/Path/InitGui.py
- src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp
- src/Mod/Start/Gui/AppStartGui.cpp
- src/Mod/TechDraw/Gui/AppTechDrawGui.cpp
Preference page title strings must be in QObject (translation is done on-the-fly during generation of the Preferences dialog via a call to `QObject::tr` because at the point the page is instantiated the language is not yet set).
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/213
---
> Gui: Correct translation context of pref pages

- src/Mod/Draft/draftobjects/array.py
- src/Mod/Draft/draftobjects/base.py
- src/Mod/Draft/draftobjects/block.py
- src/Mod/Draft/draftobjects/clone.py
- src/Mod/Draft/draftobjects/facebinder.py
- src/Mod/Draft/draftobjects/hatch.py
- src/Mod/Draft/draftobjects/patharray.py
- src/Mod/Draft/draftobjects/pathtwistedarray.py
- src/Mod/Draft/draftobjects/pointarray.py
- src/Mod/Draft/draftobjects/shape2dview.py
- src/Mod/Draft/draftobjects/wire.py
- src/Mod/Draft/drafttests/test_modification.py
For an attached object whose Shape depends on one or more source objects `props_changed_placement_only` should always return `False`.
Arrays do not have attachment properties by default but these can be added with the Part_EditAttachment command. So arrays are also affected.
A test function `test_attached_clone_behavior` has been added to test_modification.py.
Fixes #8771.
---
> Draft: fix props_changed_placement_only for attached clones and similar

- src/Tools/updatecrowdin.py
For all of the C++ workbenches, generation of the QM files happens during build, so only the Python WBs still need the QM files to be generated (and the QRCs modified).
> Tools: Modify CrowdIn to only generate QMs when needed

- src/Mod/Arch/ArchSectionPlane.py
fixes #6208 
Filling of cut objects was still happening, but it had an invisible, while default color and it was not updated when the object changed.
> Arch: Fixed SVG fill

- src/Base/Builder3D.cpp
- src/Base/Console.cpp
- src/Base/Console.h
- src/Base/ConsoleObserver.cpp
- src/Base/ConsoleObserver.h
- src/Base/Interpreter.cpp
- src/Gui/CommandTest.cpp
- src/Gui/DlgSettingsNotificationArea.cpp
- src/Gui/DlgSettingsNotificationArea.ui
- src/Gui/GuiConsole.cpp
- src/Gui/GuiConsole.h
- src/Gui/MainWindow.cpp
- src/Gui/MainWindow.h
- src/Gui/NotificationArea.cpp
- src/Gui/NotificationArea.h
- src/Gui/Notifications.h
- src/Gui/ReportView.cpp
- src/Gui/ReportView.h
- src/Gui/Splashscreen.cpp
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
- src/Mod/Test/Gui/AppTestGui.cpp
This PR proposes an extension of the console interface intended to fix the limitations identified here:
https://github.com/FreeCAD/FreeCAD-translations/issues/223
https://forum.freecad.org/viewtopic.php?t=77673
In essence:
1. The console framework is extended to include additional information, the intended recipient and the translation status of the message. The TranslatedNotification message is removed, as it is covered by a notification where the translation status is "translated".
2. The notifications framework is adapted to the new console framework.
3. Base interpreter is adapted to report the exception with intended recipients being only Developers
4. The Notification Area is adapted. It won't show a message that is intended for developers or that is untranslatable (such a stack), …
> [Base/Gui/Sketcher] Console improvement and application to Sketcher WB

- src/Mod/Draft/draftguitools/gui_dimensions.py
Fixes BIM horizontal/vertical dimensions used in continue mode - fixes #9507
> Draft: Fixes continuing dimensions - fixes #9507

- src/Base/Console.h
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfHyperbola.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfParabola.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerBSplineByInterpolation.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerCarbonCopy.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerExtend.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerExternal.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerLineSet.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerSplitting.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerTrimming.h
- src/Mod/Sketcher/Gui/EditModeCoinManager.cpp
- src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
- src/Mod/Sketcher/Gui/EditModeGeometryCoinConverter.cpp
- src/Mod/Sketcher/Gui/EditModeInformationOverlayCoinConverter.cpp
- src/Mod/Sketcher/Gui/SketcherSettings.cpp
- src/Mod/Sketcher/Gui/SnapManager.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
Revisiting all console calls:
- Using the Notification Framework when the user needs to be notified
- Turning them into DeveloperError/DeveloperWarnings when messages are intended only for developers
> Sketcher console error split

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftguitools/gui_snapper.py
The function did not handle global and relative mode properly.
It was not updated when global mode was introduced. This primarily affected Arch commands. As a consequence it was impossible to place a column at the origin of a custom Draft working plane through keyboard input.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=78538
---
> Draft: fix getcoords in gui_snapper.py

- src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
===============================================
Issue description:
https://forum.freecad.org/viewtopic.php?f=3&t=70325 https://github.com/FreeCAD/FreeCAD/issues/7520
The general algorithm to calculate normals miserably fails when the curve is a line segment and the point through which the normal to a curve is to be drawn is colinear with the line segment.
The solution is to provide specific code for this corner case.
fixes #7520
> Sketcher: Fix bug angle via point visualisation

- src/Mod/Sketcher/App/PreCompiled.h
- src/Mod/Sketcher/App/PythonConverter.cpp
- src/Mod/Sketcher/App/PythonConverter.h
- src/Mod/Sketcher/App/SketchObjectPy.xml
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
Bug fix:
- PythonConverter did not respect the creation order when normal and construction geometries were interleaved.
Sketch dumper:
- small new feature to help produce functional unit tests.
Often we have very nice sketches showing problems, for example bugs. Some of them would be invaluable as functional tests (for example those involving the solver, such as the popularity contest algorithm). Yet, there is an important barrier in turning already made sketches into the Python statements necessary to build them.
Sketch dumper is a small, fully-detached, Python-only utility to easily get that Python code (see commit description). My expectation is that this would help reduce that barrier.
> Sketch dumper and fixes to PythonConverter

- src/Mod/Arch/ArchReference.py
In #9316 I wrongly removed all decode code from ArchReference.py. But for bytes objects this code is still required.
---
> Arch: Fix ArchReference (broken after #9316)

- src/Mod/Arch/Resources/ui/ArchSchedule.ui
HTML makes translation more difficult, so should be avoided when it's not needed.
Makes progress towards fixing https://github.com/FreeCAD/FreeCAD-translations/issues/105
Fixes screwed #9515
> Arch: Removed html from tooltips (try 2)

- src/Mod/Arch/ArchAxis.py
- src/Mod/Arch/ArchAxisSystem.py
- src/Mod/Arch/ArchBuilding.py
- src/Mod/Arch/ArchBuildingPart.py
- src/Mod/Arch/ArchCommands.py
- src/Mod/Arch/ArchCurtainWall.py
- src/Mod/Arch/ArchEquipment.py
- src/Mod/Arch/ArchFloor.py
- src/Mod/Arch/ArchFrame.py
- src/Mod/Arch/ArchGrid.py
- src/Mod/Arch/ArchMaterial.py
- src/Mod/Arch/ArchPanel.py
- src/Mod/Arch/ArchPipe.py
- src/Mod/Arch/ArchProject.py
- src/Mod/Arch/ArchRebar.py
- src/Mod/Arch/ArchReference.py
- src/Mod/Arch/ArchRoof.py
- src/Mod/Arch/ArchSectionPlane.py
- src/Mod/Arch/ArchSite.py
- src/Mod/Arch/ArchSpace.py
- src/Mod/Arch/ArchStairs.py
- src/Mod/Arch/ArchStructure.py
- src/Mod/Arch/ArchTruss.py
Following the example of Arch_Wall:
- Fixed object name.
- Default label is translatable.
- Name argument should only be used for the label and not be translated.
---
> Arch: more consistent object naming and labelling

- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawColors.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui
- src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.ui
This PR addresses an issue involving html escape codes embedded in text to be translated reported here: https://forum.freecad.org/viewtopic.php?p=684625#p684625 …
> [TD]remove html escape sequences from tooltips

- src/Mod/Arch/ArchReference.py
The 2nd layout was wrongly added to the form which already has a layout.
This resulted in a warning:
QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
---
> Arch: Arch_Reference: task panel layout was added incorrectly

- src/Base/UnitsSchemaImperial1.cpp
---
This makes a few changes to how US Building Scheme displays/calculates units:
1. Sign is carried through multiple units: -1'2.5" -> -1'2" - 1/2" https://github.com/FreeCAD/FreeCAD/issues/8426
2. Inches is notated with a …
> [Base] US Building Schema correct sign on fraction

- src/Gui/NavigationStyle.cpp
Fix #6836 by moving camera backwards the same length as the height of view port.
---
> Fix clipping near camera in orthogonal view

- src/Mod/Path/Gui/DlgSettingsPathColor.ui
- src/Mod/Path/Gui/Resources/panels/PageOpPocketExtEdit.ui
- src/Mod/Path/Gui/Resources/panels/PathEdit.ui
- src/Mod/Path/Gui/Resources/preferences/Advanced.ui
- src/Mod/Path/Gui/Resources/preferences/PathJob.ui
- src/Mod/Path/Path/Main/Gui/Inspect.py
- src/Mod/Path/Path/Main/Job.py
As discussed on CrowdIn (and Telegram), this PR:
* Standardizes on "post processor" (with a space, and no hyphen)
* Tweaks the wording of a confusing tooltip
* Removes the deprecated "machine extents color" preference
* Removes the HTML in the description of the OpenCAMlib preference, and changes it to a `QLabel`.
* Standardizes the capitalization in DlgSettingsPathColor.ui
All other changes are just Qt Designer rearranging things: I did not normalize the file.
---
> Path: Minor translation fixes

- src/Mod/Draft/Resources/ui/dialog_AnnotationStyleEditor.ui
- src/Mod/Draft/draftutils/utils.py
Also reordered the dialog a little:
"Lines and arrows" section above "Units".
"Dimension details" last in a separate section.
---
> Draft: Add TextSpacing to Draft_AnnotationStyleEditor

- src/Gui/Tree.cpp
- src/Gui/TreeParams.cpp
- src/Gui/TreeParams.py
This PR solve this : https://forum.freecad.org/viewtopic.php?t=78555&sid=6c1c30d9b4ae46d34c3b0d929d6ab34e&start=10
It does 2 things : 
A - Remove the useless "Application" root item.
B - Hide by default the seldomly used "Description" column. Also when it is hidden, the labels are now hidden too.
Below a comparaison picture : on the left after this PR, on the right before.
**Note**: If you …
> Core: Tree : Remove useless root item and hide description by default.

- src/Gui/DlgSettingsNavigation.cpp
- src/Gui/DlgSettingsNavigation.ui
- src/Gui/MainWindow.cpp
- src/Gui/NaviCube.cpp
- src/Gui/View3DSettings.cpp
- src/Gui/View3DSettings.h
Adding anisotropy texture mapping for better readability on steep angles. Tip from aapo in this post https://forum.freecad.org/viewtopic.php?p=657880#p657880
Before:
After:
Don't save a font name to parameters if none is chosen in preferences
Fix #9672 because the "FreeCAD NaviCube" is no longer created.
> Improved font handling on Navigation cube

- src/Gui/DlgSettingsNavigation.ui
BaseColor tooltip was not updated in #9356.
---
> Core: fix navigation cube BaseColor pref tooltip

- tests/CMakeLists.txt
Building the C++ unit tests failed for `tests/src/App/Metadata.cpp` and `tests/src/Base/Reader.cpp` because some XML headers were not found. This was because the XercesC include dir was not in the search list for headers. I cannot say why only macOS seems to be affected, but it's not the first time, see e.g https://github.com/FreeCAD/FreeCAD/commit/a1776d3e744075e54cf95c68a9264fa0d937cc2d
--- …
> Fix build of "tests" on macOS

- src/Gui/View3DSettings.cpp
The navigation cube didn't load parameters OffsetX and OffsetY on creation of a new 3D view. See https://forum.freecad.org/viewtopic.php?p=686678#p686678
> Navicube OffsetX and OffsetY fix

- src/Mod/TechDraw/Gui/TaskSurfaceFinishSymbols.cpp
This PR addresses an issue with the surface roughness symbol reported here: https://forum.freecad.org/viewtopic.php?t=78917
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog …
> [TD]fix nonstandard representation

- src/Mod/Sketcher/App/SketchObjectPy.xml
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
Expose redundancy/conflicting/dofs/malformed information to the solver.
DoFs: returns a long with the current amount of DoFs.
The others: return a list with the constraints that are detected as redundant, partially redundant, conflicting or malformed.
Example:
```
>>> ActiveSketch.RedundantConstraints
[7]
```
This should enable functional unit tests of popularity contest:
https://forum.freecad.org/viewtopic.php?p=686535#p686535
> Sketcher: Expose constraint redundancy information to Python

- src/Mod/Arch/importWebGL.py
Get the Points attribute of MeshObject at each step of the loop,  drastically penalizes the importer's performance (depending on the object, it could take several minutes in the loop). With these changes, this loop takes only a fraction of a second. …
> Arch: Improve performance of WebGL importer

- src/Mod/PartDesign/App/FeaturePad.cpp
- src/Mod/PartDesign/App/FeaturePocket.cpp
---
replaces #9740
better validation is  already done for both at FeatureExtrude::generatePrism instead:
https://github.com/FreeCAD/FreeCAD/blob/bf8c59ba2ab4a2e6bd2060544130a0a4693ba4d8/src/Mod/PartDesign/App/FeatureExtrude.cpp# …
> PartDesign: clean redundant/incorrect length validation for pad & pocket

- src/Mod/TechDraw/App/DrawComplexSection.cpp
- src/Mod/TechDraw/App/DrawComplexSection.h
- src/Mod/TechDraw/App/DrawViewSection.cpp
This PR addresses an issue where the section normal is slightly off from the expected direction as reported here: https://forum.freecad.org/viewtopic.php?t=79017
- [X ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR …
> [TD]warn on skewed ComplexSection profile

- src/Mod/Arch/ArchEquipment.py
- src/Mod/Arch/ArchPipe.py
- src/Mod/Arch/ArchProfile.py
- src/Mod/Arch/ArchStructure.py
- src/Mod/Arch/Presets/ifc_products_IFC2X3.json
- src/Mod/Arch/Presets/ifc_products_IFC4.json
- src/Mod/Arch/TestArch.py
Removes the "Undefined" IFC type and uses "IfcBuildingElementProxy" as default instead, which is the de-facto "undefined" type of the IFC standard.
Fixes #8774 
---
> Arch remove undefined type

- src/Gui/Action.cpp
- src/Gui/Action.h
- src/Gui/Application.h
- src/Gui/ApplicationPy.cpp
- src/Gui/DlgSettingsWorkbenchesImp.cpp
To solve : https://github.com/FreeCAD/FreeCAD/issues/9479
I came upon what seemed to be unecessarily convoluted code (please tell me if I'm missing something). So I simplified it and solved the mentioned issue. 
Also it now have the advantage of not requiring a restart of the application when the wb are activated / moved.
I may have missed some advanced usecase (such as changing of workbench using python) so if you know of them could you test if they are still ok?
Please remember to …
> Core: rework WorkbenchGroup & WorkbenchComboBox

- src/Mod/Start/StartPage/StartPage.html
Fixes the CI failure introduced by #9777. This attribute is obsolete. CSS should be used instead to achieve the effect. This is causing the GUI tests to fail because the HTML valuation fails.
> Start: Remove frameborder attribute from iframe

- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femtest/data/elmer/group_mesh.geo
I sometimes use the FEM workbench to create meshes for a problem that I'll solve with an external FE solver that doesn't yet have workbench integration, or to prepare a Gmsh file for tweaks from directly running Gmsh. The `.unv` format is pretty limited on technical grounds so I rename the file to `.msh` (can express everything Gmsh can) or a parallel-friendly format. Explicitly setting `Mesh.Format = 2` is confusing because this line also needs to be fixed (or deleted) when renaming the output file name.
I would consider going further and also removing the `Save "Shape_Mesh.unv"` line from the file, then invoking as `gmsh -3 path/to/shape2mesh.geo -o path/to/Shape_Mesh.unv`. The reason is that it's ready for a person/script to invoke `gmsh` directly or to load the `shape2mesh.geo` for …
> FEM: let gmsh infer format from file name

- src/Mod/TechDraw/Gui/MDIViewPage.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.h
- src/Mod/TechDraw/Gui/ViewProviderPage.cpp
- src/Mod/TechDraw/Gui/ViewProviderPage.h
- src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
- src/Mod/TechDraw/Gui/ViewProviderViewPart.h
This PR addresses an issue where QGraphicsItems are not reparented correctly following an undo as reported here: https://forum.freecad.org/viewtopic.php?p=688817#p688817
**Note**: If you don't have wiki access, then please …
> [TD]fix lost parent on undo

- src/Mod/PartDesign/fcgear/involute.py
> Part: fix source comment typo

- src/Gui/Action.cpp
Utilize the `+=` assignment operator for readability
---
> Gui: `Action.cpp` minor code formatting tweak

- src/Mod/Draft/importDWG.py
This PR adds adds handling of macOS paths to importDWG.py.
Paths taken from this forum topic:
https://forum.freecad.org/viewtopic.php?t=79125&start=10
---
> Draft: Add macOS paths to importDWG.py

- src/Mod/TechDraw/Gui/MDIViewPage.cpp
This PR addresses a problem with SVG hatch of section face when exported to PDF as reported here: https://forum.freecad.org/viewtopic.php?t=79331&sid=3d4bcb889a053b48ef4da21f69518214 …
> [TD]fix missing section svg hatch in pdf

- src/Mod/AddonManager/AddonManager.py
- src/Mod/Spreadsheet/importXLSX.py
- src/Mod/TechDraw/TDTest/DLeaderRText.py
- src/Mod/TechDraw/TDTest/DrawHatchTest.py
- src/Mod/TechDraw/TDTest/DrawViewDetailTest.py
- src/Mod/TechDraw/TDTest/DrawViewPartTest.py
- src/Mod/TechDraw/TDTest/TDPyTest.py
- src/Mod/Test/testmakeWireString.py
- src/Mod/Test/unittestgui.py
This fixes lintian warning "unusual-interpreter".
Part of the Debian edition of FreeCAD since 2023.
> Use python3 as the interpreter instead of python (ie v2)

- src/Mod/Sketcher/App/Sketch.cpp
Create c2c distance constraint with one external geometry raised a malformed constraint error
https://forum.freecad.org/viewtopic.php?p=688538#p688538
The precommit hook also clang-formats some lines…
---
> Sketcher: fix CircleToCircle distance constraint with external

- src/XDGData/org.freecadweb.FreeCAD.appdata.xml.in
This fixes the following appstream warning and make program show up in the appstream data set:
asv-desktop-app-launchable-missing
This `desktop-application` component is missing a `desktop-id` launchable tag. This means that this application can not be launched and has no association with its desktop-entry file. It also means no icon data or category information from the desktop-entry file will be available, which will result in this application being ignored entirely.
Part of Debian FreeCAD edition since 2023.
> Adjusted Appstream metadata component type and added launchable tag

- tools/build/Docker/ubuntu.sh
---
Missing dependencies qwebengine5-dev and qtwayland5 in Ubuntu Docker install script
Add missing dependencies qwebengine5-dev and qtwayland5 to Ubuntu Docker install script. Details are provided in the  issue #9869 …
> Missing dependencies qwebengine5-dev and qtwayland5 in Ubuntu Docker install script

- src/Mod/Mesh/App/MeshTestsApp.py
- src/Mod/Robot/KukaExporter.py
- src/Mod/Robot/MovieTool.py
This fixes lintian warning "unusual-interpreter".
Part of the Debian edition of FreeCAD since 2023.
> Use python3 as the interpreter instead of python (ie v2) more places.

- src/Mod/TechDraw/App/DrawDimHelper.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawColors.ui
This PR addresses
a) a tooltip in preferences reported here: https://forum.freecad.org/viewtopic.php?t=79492
b) an error in extent dimensions reported here: https://forum.freecad.org/viewtopic.php?t=79472
**Note**: If you …
> [TD]2 small fixes

- src/Mod/TechDraw/TechDrawTools/CommandHoleShaftFit.py
As reported by  FBXL5 on Crowdin:
Typo: "openes" has one e too many
---
> TechDraw: Fix typo in HoleShafFit tooltip

- src/Mod/PartDesign/Gui/Utils.cpp
> Fix #9792: PD tasks fail to launch if body is inside Part and activated

- src/Mod/Arch/InitGui.py
Ticket:  https://github.com/FreeCAD/FreeCAD-translations/issues/224
Reinforcement workbench translations automatically loaded along with Arch Workbench 
**Reference commit to Reinforcement WB**: https://github.com/amrit3701/FreeCAD-Reinforcement/commit/ade0085b3b1dac99afc353d246b903d814240315
---
---
> Bug: Loaded Reinforcement WB translations along with Arch WB

- src/Mod/Start/StartPage/StartPage.html
When starting FreeCAD for the first time, it load the HTML content of src/Mod/Start/StartPage/StartPage.html and show it as a friendly startup page. Unfortunately, one of the tabs in the startup page is an iframe loading the content of https://blog.freecadorg/.  The effect is that every time one start FreeCAD, it dial home over the Internet with a HTTP request to the mentioned URL.  This is a privacy problem.  At the moment the blog page in turn will connect to https//i0.wp.com/ and https//s0.wp.com/, in effect also reporting the startup to Wordpress.  Please do not dial out without the expressed approval and on request of the user of the program.
This patch change the startup page to instead of putting the blog posts in a tab, it will link to the blog and the connection is only …
> Change Start page to no longer dial home by default.

- src/Mod/Fem/femtest/app/test_open.py
The load of the current file in test_open_head is fine, but open_de9b3fb438 goes into an OOM even in huge (e.g. 10GB) systemd. This probably needs a proper fix by upstream in regard to the migration modules that load the old code, but until then (since the rest works on s390x) this unblocks the package self-test in Debian & Ubuntu.
Patch by Christian Ehrhardt <christian.ehrhardt@canonical.com>.
This is Debian bug https://bugs.debian.org/984952 and Ubuntu bug https://bugs.launchpad.net/ubuntu/+source/freecad/+bug/1918474.
Been part of the Debian edition of FreeCAD since 2021.
> Skip open_de9b3fb438 s390x to avoid OOM.

- src/Mod/TechDraw/Gui/ViewProviderViewPart.cpp
- deleting a dvp will now delete any hatches, dimensions or balloons belonging to it.
- deleting a dvp that is the base view for a section or detail is still blocked.
- https://forum.freecad.org/viewtopic.php?t=79548
-  …
> [TD]allow delete of dependents on delete of parent

- src/Mod/OpenSCAD/OpenSCADTest/app/test_importCSG.py
If not all 3rd party packages are installed the DXF importer opens a modal dialog and blocks the tests
---
> OpenSCAD: a test internally uses the DXF importer

- src/Mod/AddonManager/addonmanager_utilities.py
Add some error checking to ensure valid results are returned by blocking_get.
> Addon Manager: Fix #9828, hang on no internet

- src/Mod/TechDraw/Gui/QGIRichAnno.cpp
This PR addresses the issue of RichTextAnnotation not respecting the setting of the LockPosition property reported here: https://forum.freecad.org/viewtopic.php?p=693044#p693044
- [c ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
**Note**: If you don't have wiki access, then …
> [TD]fix lock in Rich Text Anno

- src/Main/FreeCADGuiPy.cpp
---
When starting the FreeCAD GUI from a Python Interpreter (via `FreeCADGui.showMainWindow()`), some steps are missing in the function `setupMainWindow` compared to a normal start of FreeCAD. One of these missing steps is that …
> set toolbar icon size when starting FreeCAD GUI from Python

- src/App/ComplexGeoData.cpp
- src/App/ComplexGeoData.h
MSVC seems to prefer this destructor: in debug mode on Windows I get a segmentation fault on the destruction of a shared_ptr with the original code, and this eliminates the problem. @wwmayer do you have any insight?
> App/Toponaming: Tweak ComplexGeoData destructor

- src/Mod/Draft/draftutils/gui_utils.py
- src/Mod/Draft/draftutils/todo.py
The get_diffuse_color function wrongly assumed that all Part::Feature objects have a DiffuseColor property. Added handling of objects with a ColoredElements property (Link, Link array, LinkGroup).
Fixes #9900.
Additionally: While debugging found a missing import in todo.py.
---
> Draft: Fix get_diffuse_color function

- src/boost_regex.hpp
I had to add this in order to get FreeCAD to compile on windows with conda and boost 1.78
see https://forum.freecad.org/viewtopic.php?t=79268 and https://github.com/boostorg/regex/blob/boost-1.78.0/include/boost/regex/v5/w32_regex_traits.hpp#L119-L236 …
> Fix boost 1.78 workaround

- src/Gui/Application.cpp
- src/Gui/Application.h
- src/Gui/MainWindow.cpp
A minimal version of #9668. Only warns the user to manually change the backup system to `FCBak`.
#9668 fails only in the github CI (outside of tests), and only with the commit not included here.
> [Core] Warn user if using deprecated backup extension

- src/Mod/Fem/femmesh/gmshtools.py
- src/Mod/Fem/femtest/data/elmer/group_mesh.geo
Relative paths appearing in Gmsh .geo files are relative to the .geo file, not relative to the cwd when the gmsh executable was invoked. This is okay when using absolute paths with the default "Temporary directories" mode, but if one selects (in Preferences -> FEM) "Beside .FCStd file", then relative paths are written to the .geo file. This causes a (suppressed in FreeCAD output) warning from Gmsh that the brep file is missing as well as the error:
```
Unexpected error when creating mesh: File to load not existing or not readable: partname/FEMMeshGmsh/BaseFeature_Mesh.unv
```
In this commit we just use relative paths, which is also convenient if users move these files elsewhere (e.g., to work directly with advanced features in Gmsh).
---
Thank you for creating a pull request to contribute …
> FEM: fix gmsh relative paths

- src/Gui/propertyeditor/PropertyItem.cpp
---
When editing from property view or a properties associated task panel. Save all interpreted decimals to the internal property.
Fix #9570
> Save all decimals when property is edited

- src/Mod/TechDraw/Gui/Workbench.cpp
This PR fixes issues with the TechDraw menu reported here: https://forum.freecad.org/viewtopic.php?t=79715&sid=bfce3778265fdb6c518b48c016a08514
- 3 point angle was not in menu
- grouped menu items …
> [TD]add missing command to menu

- src/Base/FileInfo.cpp
Current implementation can freeze the app if called on specific files
This was detected in the CI of #9668.
#9668 CI should be retriggered and hopefully can be merged when this present PR is merged.
I didn't search which file / kind of files exactly triggers the problem, but it may be done if of interest.
> [Bugfix]Base: fix implementation of isFile() so it is safe to use

- src/App/StringHasher.h
Need to ensure the Qt 'slots' macro is undefined by including FCConfig.h.
> App/Toponaming: Fix Python 3.11 compile issue

- src/Gui/SoFCCSysDragger.cpp
This is an attempt to fix #9465 
I can't test at all (no Mac) but AFAIK nobody really can as this only happens on prebuilt versions, and not on own build ones.
So at some time, only way to test may be to merge and see. :smile:
I did this because the reported framestack makes me think to symptoms of a Coin sensor that wouldn't be correctly detached.
Looking at the code, I indeed found the `fieldSensor` of `TDragger` and `RDragger` to not be detached.*They now are detached in instance dtor.
As sensor data is instance itself (`this`) and because Coin can still call the static callback after the instance is destructed, I make sure to nullify the sensor data in dtor and check for it being not null in sensor callback.
:crossed_fingers: for Mac users :rofl:
> [Bugfix]Gui: detach field sensor of draggers and handle post-call of callbacks

- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/App/Preferences.h
- src/Mod/TechDraw/Gui/QGIFace.cpp
This PR is a follow-on to  #9985.  It reduces the number of svg tiles used to create the face overlay.  Additional detail here: https://forum.freecad.org/viewtopic.php?t=79823
- reduce the size of the overlay area from 200% to an adjustable size with a default of 125%.
Please remember to update the Wiki with the features …
> [TD]reduce number of tiles for svg hatching

- src/Mod/TechDraw/Gui/Command.cpp
This PR removes an unsupport file type (dxf) from the new page from template dialog.
Additional background here: https://forum.freecad.org/viewtopic.php?t=79904 …
> [TD]remove unsupported file type from dialog

- src/Gui/MainWindow.cpp
This fixes the segfault described in issue #10003. This was caused by a change introduced in pull request #9758.
The solution proposed here avoids dereferencing the null pointer without affecting order of execution of other code in the function.
cc @0penBrain 
- [ X ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
Please remember to update the Wiki with the features added …
> Gui: Avoid segfault if window is not an MDIView

- src/Gui/AutoSaver.cpp
- src/Gui/DlgSettingsDocument.ui
- src/Gui/Document.cpp
Change the default state of the setting 'Save thumbnail on doc save' to true.
With this the thumbnail is saved by default.
@sliptonic 
---
> [Pref] Change the default of 'Save thumbnail on doc save'

- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawHLR.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawHLRImp.cpp
- src/Mod/TechDraw/Gui/QGILeaderLine.cpp
- src/Mod/TechDraw/Gui/QGIRichAnno.cpp
This PR includes 3 fixes to be included in v0.21:
- add 1 line of code to support scaling of end symbol on leaders
- change the default preference for seam lines to false
- improve text scaling and position in RichTextAnnotations exported to Svg …
> [TD]Last minute fixes for v0.21

- src/Mod/Path/PathTests/TestPathPost.py
The two path names have different path separators and thus are considered as different
---
> Path: fix test failure with MSYS2 build

- src/Gui/SoFCCSysDragger.cpp
This is continuation of #9975 in an attempt to fix #9465 
I found sensor callbacks that hadn't been covered in #9975 and fix them.
Also detach all "standard" callbacks in dtor and add asserts so at least if they are culprit for the crash we have a trace.
> [Bugfix]Gui: in draggers, remove/detach all callbacks + add checks and asserts

- CMakeLists.txt
- src/App/Application.cpp
- src/Build/Version.h.cmake
- src/Gui/Application.cpp
- src/Gui/MainWindow.cpp
- src/Gui/MainWindow.h
- src/Gui/Splashscreen.cpp
This PR sets the version to 0.22.0dev. It then ensures that the "dev" suffix shows in the places where we show the version (including the title bar), and adds a prominent (translatable) warning label to the splashscreen.
> Bump build version to 0.22 and make it obvious it's a developer build

- src/Base/Builder3D.h
note: in other headers there is a mix of including #ifdef __GNUC__
Sadly I did not catch this during the RC window but a patch in the aport can make this work for Alpine specifically, cannot say if this affects other systems.
> add cstdint behind ifdef __GNUC__ for compiling under alpine linux

- tests/CMakeLists.txt
Enable gmock (not previously linked) so it can be used in google tests
---
> link gmock

- src/Gui/QuantitySpinBox.cpp
---
Addressing issue https://github.com/FreeCAD/FreeCAD/issues/9864, regex performance improvements.
> [GUI] QuantitySpinBox: Regex optimization.

- src/Mod/Part/App/AppPartPy.cpp
Hello,
This simple commit adds a 3D tolerance option to the python binding of Part.sortEdges, as available in the C++ function.
I know we are in freeze period, so feel free to merge after release if you wish.
Thanks
---
> Part: add optional tolerance to python sortEdges()

- src/Mod/Mesh/App/FacetPyImp.cpp
The underlying C++ class use an unsigned long to reference neighbour facets. ULONG_MAX is used to indicate a missing neighbour facet. Since the value of ULONG_MAX is platform dependent and can be confusing in Python the Python wrapper FacetPy now explicitly uses -1 to indicate missing neighbour facets …
> Mesh: for invalid neighbour facet indexes explicitly use -1

- .clang-format
If the line is too long, parameters and arguments will now wrap on the next lines with one block indent, one arguments or parameter per line.
---
> [Repo] Always break parameters and arguments

- src/Mod/Surface/App/Blending/BlendCurve.cpp
A size value independent of the number of control points is more intuitive.
And the curve shape will be more stable upon continuity changes.
---
> Surface: fix BlendCurve relative size

- src/Gui/DlgSettingsNavigation.cpp
- src/Gui/DlgSettingsNavigation.ui
- src/Gui/NavigationStyle.cpp
- src/Gui/NavigationStyle.h
- src/Gui/PreferencePackTemplates/View.cfg
- src/Gui/View3DInventorViewer.cpp
- src/Gui/View3DInventorViewer.h
---
Adds an option to show the rotation center while dragging. I personally like to see the center of rotation while dragging, maybe other people like it too. Besides, it could be useful for finding problems regarding the rotation center.
https://github.com/FreeCAD/FreeCAD/assets/14298143/ab540721-3a36-41bd-a7a1-252a301b8b00
> Gui: Add rotation center indicator

- src/Mod/Part/Gui/ViewProviderExt.cpp
---
**Problem description**
To display a shape, the ViewProvider creates a mesh of the shape data. The resolution depends also on the two parameters "Angular Deflection" and "Deviation" in the View properties. (The values of …
> allow reduction of Part ViewProvider tesselation resolution

- src/Mod/Path/PathGlobal.h
- src/Mod/Path/PathSimulator/App/PreCompiled.h
It's not recommended any more to keep the export macro in the PreCompiled.h because many IDEs fail to fetch the export macro and raise a parsing error instead.
---
> Path: make export macro accessible in header file

- src/Main/MainGui.cpp
---
The added initialization of the locales will prevent the wrong ascii-only filesystem encoding.
Further description of the problem, tracking down the cause and the solution can be seen at my topic in the forum: …
> fix wrong filesystem encoding in GUI with Python 3.11 on Linux

- .clang-format
> clang-format: Align long function arguments

- src/Gui/PreferencePages/DlgSettingsGeneral.cpp
- src/Gui/PreferencePages/DlgSettingsTheme.cpp
Solves #10136
> - The Classic, Dark or Light theme modifies the background color of the 3d view. If after switching to another theme and adjusting the background colors under Display > Colors then the colors won't be accepted and rejected to the default colors of the theme. The only way to get the custom colors accepted is to close the the preferences dialog after changing the theme and reopening it again. This is extremely annoying behaviour.
> - Whenever choosing a style sheet in the Theme tab a warning "Hello" is written to the report view
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD …
> Pref: Theme: Solves #10136

- src/Mod/Spreadsheet/Gui/SheetModel.cpp
- src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp
The recent migration from boost::bind to std::bind, see [1], broke the build on Mac (Apple clang version 13.0.0 (clang-1300.0.29.30) on macOS-11.7.8).
In all other cases the `boost::bind` was replaced by `std::bind` (among with the place holders) but in these two spread sheet files
- src/Mod/Spreadsheet/Gui/SheetModel.cpp
- src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp
the original code only referenced `bind`, which used to get resolved to `boost::bind` but now raises this error:
```
/Users/jonas/src/FreeCAD/FreeCAD-git/src/Mod/Spreadsheet/Gui/SheetModel.cpp:50:36: error: use of undeclared identifier 'bind'; did you mean 'boost::bind'?
sheet->cellUpdated.connect(bind(&SheetModel::cellUpdated, this, sp::_1));
^~~~
boost::bind
```
This commit changes this to `std::bind` expicitly, just like …
> Spreadsheet: Fix build on macOS

- src/Gui/MainWindow.cpp
- src/Gui/MainWindow.h
Ensure that the warning adapts to the font size and text length as needed.
> Gui: Tweak size of developer warning

- src/Mod/AddonManager/addonmanager_devmode_add_content.py
See #6015.
No huge speed improvements expected here.
---
> AddonManager: Avoid dictionary.keys() where possible

- src/Mod/TechDraw/Gui/TaskComplexSection.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/261
> TD: Correct translation in TaskComplexSection

- src/Mod/TechDraw/TechDrawTools/TaskHoleShaftFit.py
Direct UI access should use translate(). Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/262
> TD: Correct use of TRANSLATE_NOOP

- src/Mod/Draft/draftmake/make_sketch.py
Changing the Autoconstraints property of the new sketch's ViewObject is unnecessary and confuses users.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=80367
Additionally:
Removed the `deletable` variable as it was not used.
---
> Draft: make_sketch should not change Autoconstraints of sketch

- src/App/Application.cpp
- src/App/StringHasherPyImp.cpp
- src/App/StringIDPyImp.cpp
- src/Mod/Test/CMakeLists.txt
- src/Mod/Test/Init.py
- src/Mod/Test/StringHasher.py
The `StringHasherPy::getID` function crash if the first argument is an integer less or equal to 0.
If the first argument is a string, the signature is changed to explicitly receive a boolean in the optional second argument.
In `StringHasherPy::isSame` and `StringID::isSame` currently returns a result with an exception set if the argument isn't `App.StringHasherPy` (`App.StringID`). This is undefined behavior and must be avoided.
Other changes:
- In `StringHasherPy::PyInit` explicitly avoid parameters.
- In `StringHasherPy::getCount` and `StringHasherPy::getSize` use `PyLong_FromSize_t` to get the `PyLongObject` from `size_t`.
- Change PyCXX `Py::Int` to `Py::Long`.
The second commit change indentation to four spaces.
Thank you for creating a pull request to contribute to FreeCAD! Place an …
> App: Fix crash and undefined behavior in StringHasherPy and StringIDPy

- .github/PULL_REQUEST_TEMPLATE.md
Closes https://github.com/FreeCAD/FreeCAD/discussions/10196 and https://github.com/FreeCAD/FreeCAD/discussions/10195
The template text appears to have almost the exact opposite of the intended effect: by having pre-filled text in the description field, many contributors are not adding a description of their PR at all, and they are unlikely to be reading the text that is present. This PR removes the text entirely: one of the jobs of Maintainers is to onboard new contributors. If a PR does not meet the requirements of CONTRIBUTING.md, a Maintainer should respond to the PR personally and help guide the new contributor through the process.
We discussed this at the Vancouver FreeCAD Hackathon in 2023 and came to the general consensus that we should try running without the template text.
> Remove the PR template text

- src/Gui/NavigationStyle.cpp
- src/Gui/View3DInventorViewer.cpp
- src/Gui/View3DInventorViewer.h
- src/Gui/ViewProvider.h
- src/Gui/ViewProviderMeasureDistance.cpp
- src/Gui/ViewProviderMeasureDistance.h
---
This is my attempt to fix #9911. I created a group in `pcViewProviderRoot` called `objectGroup` which contains basically everything that is allowed to affect the rotation center. Things that should not affect the rotation center are directly added as a child of `pcViewProviderRoot`. The axis cross is directly added to `pcViewProviderRoot` and should no longer affect the rotation center. I also excluded the measure distance tool from `objectGroup` because I think it could affect the rotation center too much in some cases.
I am not sure if this is the best way to fix the object center rotation mode but I think it is a step in the right direction. If there is a better way to fix this or if there are more things that should be excluded from the `objectGroup` please let me know.
This PR …
> Gui: Improve object center rotation mode

- src/App/Expression.cpp
Removes superfluous `std::move`, and addresses a couple of other minor issues with the function identified by clang-tidy.
> App: clang-tidy cleanup of Expression::_renameObjectIdentifier

- src/Mod/Plot/Plot.py
While FC don't depend on PyQt anymore, patch is needed to have
matplotlib working correctly
https://github.com/FreeCAD/FreeCAD/commit/876601d34d7596fd61041263a9c56b611fd04777#r108628060
> [Bugfix]Plot: reintroduce patch removed by #9103

- src/Gui/QuantitySpinBox.cpp
---
Addendum to #10067, A bug in line 210 where the unitStr variable didn't get reversed when line 213 was added, causing the appended string to be *(1tinu) instead of the correct *(1unit). …
> [GUI] QuantitySpinBox Regex Optimization #10067 Ammendum

- src/Mod/Path/Path/GuiInit.py
packaging.version.parse() will raise InvalidVersion in some cases but the error isn't caught.
---
> fixes #10113

- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/Cosmetic.h
- src/Mod/TechDraw/App/CosmeticExtension.cpp
- src/Mod/TechDraw/App/CosmeticVertex.cpp
- src/Mod/TechDraw/App/CosmeticVertex.h
- src/Mod/TechDraw/Gui/CommandAnnotate.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.cpp
- src/Mod/TechDraw/Gui/TaskCosVertex.cpp
- src/Mod/TechDraw/Gui/TaskCosmeticLine.cpp
- src/Mod/TechDraw/Gui/Workbench.cpp
This PR 
- fixes an issue with pdf export reported here: https://forum.freecad.org/viewtopic.php?t=80532&sid=39976b8ae9944d1bf07cc52c4b231882
- fixes a mistake in the splitting of GeometryObject
- allow cosmetic vertices and edges to rotate with the parent view.
> [TD]small fixes

- src/Mod/Inspection/App/AppInspection.cpp
- src/Mod/Inspection/App/InspectionFeature.cpp
- src/Mod/Inspection/App/InspectionFeature.h
- src/Mod/Inspection/Gui/AppInspectionGui.cpp
- src/Mod/Inspection/Gui/ViewProviderInspection.cpp
- src/Mod/Inspection/Gui/VisualInspection.cpp
- src/Mod/Inspection/Gui/Workbench.cpp
This PR affects the code of the Inspection module.
> Inspection: modernize C++: use equals default

- src/3rdParty/salomesmesh/src/SMDS/SMDS_Mesh.cpp
The SMDS memory check cause the build to fail on on BSD-systems. It would be better to disable it only on BSD-platforms, or use http://code.google.com/p/sysinfo-bsd/source/browse/sysinfo.c for them.
This fixes Debian bug https://bugs.debian.org/623560 .
Patch by Anton Gladky <gladk@debian.org>.
Been part of the Debian edition of FreeCAD since 2011.
> Disable memory-check in SMDS because sysinfo.h is not working on BSD.

- src/3rdParty/salomesmesh/inc/Rn.h
- src/3rdParty/salomesmesh/inc/StdMeshers_MEFISTO_2D.hxx
- src/3rdParty/salomesmesh/inc/aptrte.h
- src/3rdParty/salomesmesh/src/MEFISTO2/aptrte.cpp
- src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_MEFISTO_2D.cpp
Fix compilation on Armel due to coincident variables R2, R3 and R4 in <sys/ucontext.h>.
Based on suggestion by Paul Brook in
<URL: http://lists.alioth.debian.org/pipermail/debian-science-maintainers/2011-October/009876.html >.
Patch by Anton Gladky <gladk@debian.org>.
Patch has been used by the Debian edition of FreeCAD since 2011.
> Rename R2, R3 and R4 in salomesmesh to fix building on armel.

- src/Mod/Path/App/Area.cpp
- src/Mod/Path/App/Area.h
- src/Mod/Path/App/AreaPy.xml
- src/Mod/Path/App/AreaPyImp.cpp
- src/Mod/Path/Gui/Resources/panels/PageOpPocketFullEdit.ui
- src/Mod/Path/Path/Op/Area.py
- src/Mod/Path/Path/Op/Gui/Pocket.py
- src/Mod/Path/Path/Op/Gui/PocketBase.py
- src/Mod/Path/Path/Op/Gui/PocketShape.py
- src/Mod/Path/Path/Op/Pocket.py
- src/Mod/Path/Path/Op/PocketBase.py
WIP, but mostly done. Still TODO:
Forum thread: https://forum.freecad.org/viewtopic.php?t=78773
Issue: https://github.com/FreeCAD/FreeCAD/issues/9756
---
> Rest Machining for Path and Path3D Operations

- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/DrawViewSection.h
- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/App/Preferences.h
This PR is a follow on from PR #10281 / 69523b5ea4.  It adds a property to section views that allows the user to make a section based on the result of a previous section.  The default behaviour on a second section is to use the original shape.
Discussion here: https://forum.freecad.org/viewtopic.php?t=80362
> [TD]allow use of section cut shape in next section

- src/Mod/Surface/App/AppSurface.cpp
- src/Mod/Surface/App/FeatureExtend.cpp
- src/Mod/Surface/App/FeatureExtend.h
- src/Mod/Surface/App/FeatureSections.cpp
- src/Mod/Surface/App/FeatureSections.h
- src/Mod/Surface/Gui/AppSurfaceGui.cpp
- src/Mod/Surface/Gui/TaskFilling.cpp
- src/Mod/Surface/Gui/TaskFilling.h
- src/Mod/Surface/Gui/TaskGeomFillSurface.cpp
- src/Mod/Surface/Gui/TaskGeomFillSurface.h
- src/Mod/Surface/Gui/TaskSections.cpp
- src/Mod/Surface/Gui/TaskSections.h
- src/Mod/Surface/Gui/Workbench.cpp
This PR affects the code of the Surface module.
> Surface: modernize C++: use equals default

- src/Mod/ReverseEngineering/App/AppReverseEngineering.cpp
- src/Mod/ReverseEngineering/App/ApproxSurface.cpp
- src/Mod/ReverseEngineering/App/ApproxSurface.h
- src/Mod/ReverseEngineering/Gui/AppReverseEngineeringGui.cpp
- src/Mod/ReverseEngineering/Gui/FitBSplineSurface.cpp
- src/Mod/ReverseEngineering/Gui/FitBSplineSurface.h
- src/Mod/ReverseEngineering/Gui/Poisson.cpp
- src/Mod/ReverseEngineering/Gui/Segmentation.cpp
- src/Mod/ReverseEngineering/Gui/Segmentation.h
- src/Mod/ReverseEngineering/Gui/SegmentationManual.cpp
- src/Mod/ReverseEngineering/Gui/SegmentationManual.h
- src/Mod/ReverseEngineering/Gui/Workbench.cpp
This PR affects the code of the ReverseEngineering module.
> RE: modernize C++: use equals default

- .github/workflows/sub_buildUbuntu2004.yml
- .github/workflows/sub_buildUbuntu2204.yml
This is preparatory to the Materials WB, which requires this library. Note that the Windows CI will require a change to the LibPack.
> CI: Add libyaml-cpp-dev to Linux CI

- src/Mod/Draft/draftguitools/gui_base_original.py
It makes sense to have this attribute. It will also facilitate the coming work related to the Plane class.
Additionally: Removed the `not self.doc` check from `Activated` as `IsActive` already handles this.
> Draft: Add wp attribute to DraftTool class

- src/Gui/Stylesheets/Behave-dark.qss
- src/Gui/Stylesheets/Dark-contrast.qss
- src/Gui/Stylesheets/Dark-modern.qss
- src/Gui/Stylesheets/Dark.qss
- src/Gui/Stylesheets/Darker.qss
- src/Gui/Stylesheets/Light-modern.qss
- src/Gui/Stylesheets/Light.qss
- src/Gui/Stylesheets/ProDark.qss
As the title says I replaced some static colors with the accent colors, also for ProDark and Behave-Dark and Dark-contrast.
I also added gradient to the modern styles, as you can now manually disable gradients by making the 2 colors the same.
We might need to look into some "reset to default" option for the theme's.
> [Stylesheets] Replaced more static colors with the accent colors.

- src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp
- src/Mod/PartDesign/Gui/TaskPadPocketParameters.ui
Based on the discussion here https://forum.freecad.org/viewtopic.php?t=80413 I made the following changes to the Pad/Pocket task dialog:
- reorder UI elements
- hide "Select Face" if not necessary
- improve tab stop order
> Improve Pad/Pocket Task Dialog

- src/Mod/PartDesign/App/FeatureLinearPattern.cpp
- src/Mod/PartDesign/App/FeatureLinearPattern.h
- src/Mod/PartDesign/App/FeaturePolarPattern.cpp
- src/Mod/PartDesign/App/FeaturePolarPattern.h
- src/Mod/PartDesign/Gui/TaskLinearPatternParameters.cpp
- src/Mod/PartDesign/Gui/TaskLinearPatternParameters.h
- src/Mod/PartDesign/Gui/TaskLinearPatternParameters.ui
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.cpp
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.h
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.ui
This PR adds support for providing not only overall length or angle for patterns like it works now, but also allows user to specify exact length or angle for spacing consecutive features. It's based on previous work of @sugol-a at https://github.com/sugol-a/FreeCAD/tree/lp-offset which I rebased and build upon.
Related forum topic: https://forum.freecad.org/viewtopic.php?p=596742 - I don't know If it is required to create issue for the PR - if it is, I'll make one based on that topic.
As for the nomenclature I chose to stick to **Offset**  and **Overall Length / Angle** for the mode names, but I'm not particularly proud of them. I can't however think of clearly better alternatives. Fusion 360 uses **"Spacing"** and **"Extent"**, but I don't think that they are obvious without …
> PartDesign: Add offset modes for patterns

- src/Main/MainGui.cpp
The fix for https://forum.freecad.org/viewtopic.php?t=79192 may have caused a regression with Py3.10 on Windows as reported here https://forum.freecad.org/viewtopic.php?t=80659
This PR activates the previous fix for Linux & UNIX systems only
> Main: Fix for Windows with Py3.10

- src/Gui/PreferencePages/DlgSettingsWorkbenchesImp.cpp
- src/Gui/PreferencePages/DlgSettingsWorkbenchesImp.h
Fix https://github.com/FreeCAD/FreeCAD/issues/10351
The ability to sort alphabetically the workbench list in preferences has been lost and needs to be reimplemented.+
This PR adds a contextual menu to the workbench list in preferences. By right clicking on the list you have the option to sort alphabetically.
> Pref: wb: Add contextual menu to sort alphabetically.

- src/Mod/TechDraw/Gui/CMakeLists.txt
FreeCAD\src\Mod\TechDraw\Gui\CommandExtensionDims.cpp(174) has a utf-8 character
> fix: windows build need /utf-8

- src/Mod/Path/Path/Dressup/Gui/RampEntry.py
Fixes #10317 
Most of the time, creatRampEdge is invoked on an arc with the arc's start and end points as parameters (either matching its argument names or swapped). In this case, the existing computation of arcMid is a correct computation of the arc midpoint, and results in returning the correct arc.
However, in createRampMethod1 (and maybe other places? I haven't checked), this method can be invoked on a subsection of an arc (see lines 554, 559, 566) . In this case, the existing computation of arcMid produces the midpoint of the original arc, not the subsection of the arc. The computed point may lie on the outside of the intended arc, producing instead the arc that goes the other way around the circle from start to end.
My fix is to compute the parameters of the provided startPoint and …
> [Path] Fix bug where ramp dressup makes big circles

- src/Mod/Sketcher/Gui/Workbench.cpp
Fix #10310 The Sketcher Visual toolbox can't be displayed as it doesn't appear in the context menu.
> Sketcher: Fix Visual toolbox visibility

- src/Mod/Path/Path/Post/UtilsArguments.py
- src/Mod/Path/Path/Post/UtilsExport.py
- src/Mod/Path/Path/Post/UtilsParse.py
This is part of the work for https://github.com/FreeCAD/FreeCAD/issues/6117.
This is one in a series of PR's where I am taking code from at least 4 postprocessor files partially written by different people, combining them into three files, then trying to make the code more consistent and simpler. The long term goal is to enable much simpler postprocessor files with much less copied code in each postprocessor file and much more "shared" code in the three Utils*.py files.
In this PR I create the "init_parameter_functions" routine so that it can be called from a postprocessor file to set the "values[PARAMETER_FUNCTIONS]" dictionary/hash value which is then used to call the parameter functions in the proper order.
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in …
> Path:  Now can set parameter_functions from a postprocessor file.

- src/Gui/PreferencePacks/Classic/Classic.cfg
- src/Mod/Start/Gui/DlgStartPreferences.ui
- src/Mod/Start/Gui/DlgStartPreferencesImp.cpp
- src/Mod/Start/StartPage/StartPage.css
- src/Mod/Start/StartPage/StartPage.py
This PR is a follow up to https://github.com/FreeCAD/FreeCAD/pull/10391 and https://github.com/FreeCAD/FreeCAD/issues/10381
Changes the default BackgroundTextColor and adds two new preferences for changing the visibility and size of file thumbnail icons
> StartPage: Visual fixes follow-up

- src/Gui/SoFCSelectionContext.cpp
- src/Gui/SoFCUnifiedSelection.cpp
Fixes some issues added with PR #9285:
* no need to check for nullptr when using dynamic_cast
* do not call back() on an empty container
> Fix possible issues in selection node

- CONTRIBUTING.md
CONTRIBUTING.md is vague about the role of the Project Administrators, how they are selected, and who they are.  
Fixes #10324
> Clarify the role of the Project Administrators

- src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
As reported in issue #10424 FreeCAD crashes with a segmentation fault when opening/editing a sketch.
The cause was a change in #9559 that evaluated a geometry of the second constraint position before the check if the second constraint position was valid.
The crash then happend because the second position of a DistanceX constraint was `GeoEnum::GeoUndef` (-2000). This value means that the distance point is the origin of the sketch and not a geometry object.
This PR restores the old order, i.e. the geometry will be evaluated and assigned _after_ the check.
For me, the change of the order in #9559 seems to be a mishap -- I cannot grasp the reasoning behind that change.
> Sketcher: fix segfault on distance constraints without SecondPos

- src/Gui/Selection.cpp
- src/Gui/SelectionFilterPy.h
When setting the selection filter below and hovering over an object causes a segmentation fault: filter = Gui.Selection.Filter('SELECT Part::Feature') Gui.Selection.addSelectionGate(filter)
> Gui: fix crash with the move to the new-style of class SelectionFilterPy

- src/3rdParty/libkdtree/kdtree++/iterator.hpp
definition of implicit copy assignment operator for '_Base_iterator' is deprecated because it has a user-provided copy constructor [-Wdeprecated-copy-with-user-provided-copy]
> libkdtree++: fix deprecation warning

- src/Mod/Surface/App/Blending/FeatureBlendCurve.cpp
- src/Mod/Surface/App/Blending/FeatureBlendCurve.h
Hello,
Since Surface::BlendCurve feature doesn't compute any automatic initial property values, I think it is better to allow live update of properties, for easier tweaking.
Thanks
---
> Surface: allow instant update of BlendCurve properties

- .github/labels.yml
In lieu of #10427 which kickstarted Assembly development, we can add auto-tag assembly wb PRs back in again. Note: I've also re-activated the WB Assembly tag. 
[skip ci]
> labels.yml: Add Assembly workbench auto-tag back in

- .github/labels.yml
Syntax error in GitHub YAML file.
> CI: Fix syntax in labeler

- src/Gui/Command.cpp
- src/Gui/Command.h
Currently the GroupCommand by default sets the action group as non-exclusive, checkable and having a drop-down menu which isn't always the desired behaviour in sub-classes. Thus, some new methods are added to let a sub-class in its constructor decide how it should behave.
> Gui: make GroupCommand more flexible

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
Edit: It is now working and solves https://github.com/FreeCAD/FreeCAD/issues/10443
Initial text:
> Try to solve https://github.com/FreeCAD/FreeCAD/issues/10443
> However there is an interesting issue.
> I handle the initial selection in the DSH activated function.
> 
> ```
> class DrawSketchHandlerDimension : public DrawSketchHandler
> {
>     void activated() override
>     {
>         ....
>         handleInitialSelection();
>     }
> ```
> 
> It works, you can select a line, trigger the tool, then it creates the correct constraint.
> 
> However it appears that in this case the opened transation is commited immediately after.
> 
> Having a closer look, it does not come from my code. I think the open transaction is automatically closed after the command activated function is finished : …
> Sketcher_Dimension : Implement selection->tool workflow

- .github/ISSUE_TEMPLATE/PROBLEM_REPORT.yml
This updates description of Problem report issue template to be more descriptive and to include what kinds of issues could be reported. Field with description is moved to be second one so it will be rendered on the top of issue instead of near the end.
Fixes #10448
> GitHub: Better layout and description for Problem template

- src/Mod/TechDraw/Gui/QGVNavStyle.cpp
- src/Mod/TechDraw/Gui/QGVNavStyle.h
- src/Mod/TechDraw/Gui/QGVNavStyleTouchpad.cpp
This PR implements a partial fix for #10406.  It adds ctl++ and ctl+- zooming in Touchpad mode.
Zooming from the View menu remains to be fixed.
> [TD]fix keyboard zoomIn/zoomOut for Touchpad mode

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
Fix crash reported in https://github.com/FreeCAD/FreeCAD/pull/10463#issuecomment-1702920531
and introduced in https://github.com/FreeCAD/FreeCAD/commit/c72c9eaaa3b8ff91b9c872ac9887fdf1de322766 by mistake
@howie-j @wwmayer 
Can you please confirm if this solves the issue on your side too?
> Sketcher_Dimension fix crash.

- src/WindowsInstaller/lang/english.nsh
If you have FreeCad running and start the installer it will produce a message that says "You must close FreeCAD at first!" This is not proper grammar. This PR removes "at" to make the message correct.
> Fix slight grammar error in Windows installer (English)

- src/Mod/Fem/Gui/Workbench.cpp
Temporarily disable the Constraints without Solver submenu from the GUI.
+ a forgotten separator
https://github.com/FreeCAD/FreeCAD/issues/10135
please squash with #10457
Chennes, thank you for guiding me.
> FEM: disable the Constraints without solver submenu - part2

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
> Sketcher_Dimension Replace SubNames by std::move(SubNames)

- .github/workflows/sub_lint.yml
In anticipation of adding the Material WB in PR #10368.
> CI: Add yaml-cpp dependency to sub_lint.yml

- src/Mod/Draft/draftguitools/gui_edit.py
`self.gui_tools_repository` is an instance of a class that manages a dictionary, it is not a dictionary itself.
> Draft: Correct mistake in PR10160

- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
This PR corrects an issue with highlighting dimensions when selected in the tree.  The issue was reported here: https://forum.freecad.org/viewtopic.php?t=80854&sid=39a4cd69612c508912097cc484ed2d8b
> [TD]fix selection highlighting from tree

- src/Mod/Fem/Gui/Command.cpp
- src/Mod/Fem/Gui/DlgSettingsFemExportAbaqus.ui
- src/Mod/Fem/Gui/DlgSettingsFemGeneral.ui
- src/Mod/Fem/Gui/Resources/ui/BodyHeatSource.ui
- src/Mod/Fem/Gui/Resources/ui/CurrentDensity.ui
- src/Mod/Fem/Gui/Resources/ui/ElectrostaticPotential.ui
- src/Mod/Fem/Gui/Resources/ui/FlowVelocity.ui
- src/Mod/Fem/Gui/Resources/ui/InitialFlowVelocity.ui
- src/Mod/Fem/Gui/Resources/ui/InitialPressure.ui
- src/Mod/Fem/Gui/Resources/ui/Magnetization.ui
- src/Mod/Fem/Gui/TaskAnalysisInfo.ui
- src/Mod/Fem/Gui/TaskFemConstraint.cpp
- src/Mod/Fem/Gui/TaskFemConstraintContact.cpp
- src/Mod/Fem/Gui/TaskFemConstraintDisplacement.cpp
- src/Mod/Fem/Gui/TaskFemConstraintFixed.cpp
- src/Mod/Fem/Gui/TaskFemConstraintFluidBoundary.cpp
- src/Mod/Fem/Gui/TaskFemConstraintForce.cpp
- src/Mod/Fem/Gui/TaskFemConstraintHeatflux.cpp
- src/Mod/Fem/Gui/TaskFemConstraintHeatflux.ui
- src/Mod/Fem/Gui/TaskFemConstraintPlaneRotation.cpp
- src/Mod/Fem/Gui/TaskFemConstraintPressure.cpp
- src/Mod/Fem/Gui/TaskFemConstraintTemperature.cpp
- src/Mod/Fem/Gui/TaskFemConstraintTransform.cpp
- src/Mod/Fem/Gui/ViewProviderFemConstraint.cpp
- src/Mod/Fem/Gui/Workbench.cpp
- src/Mod/Fem/femcommands/commands.py
Removing "constraint" from the names of most FEM workbench features.
https://github.com/FreeCAD/FreeCAD/discussions/10217
> FEM: removing "constraint" from the names

- src/Mod/Draft/draftmake/make_hatch.py
Not able to import  `Draft` workbench in FreeCAD docker image compiled without GUI element.
Here is the dockerfile: [https://github.com/amrit3701/docker-freecad-cli/blob/master/0.21/amd64/Dockerfile](https://github.com/amrit3701/docker-freecad-cli/blob/master/0.21/amd64/Dockerfile)
Image already published: [https://hub.docker.com/r/amrit3701/freecad-cli/tags](https://hub.docker.com/r/amrit3701/freecad-cli/tags)
> Bug fix: Allow Draft WB to import in FreeCAD headless docker container

- src/Mod/Sketcher/App/SketchObject.h
While working on the python docs for SketchObject, I stumbled upon this little outdated c++ comment.
Since the docstring was initially written, an additional error code was added.
Just following the boy-scout rule here...
> Sketcher: minor fix of c++ source docs for solve(..)

- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
While working on the python docs for SketchObject, I noticed two wrong usages of the `PyArg_ParseTuple` format strings, resulting in strange error messages.
The part behind the column represents the function name itself, not an error message. So previously, an argument error looked like this: ("Give an object" is not the method name)
```
>>> obj.carbonCopy()
File "<input>", line 1, in <module>
TypeError: Give an object() takes at least 1 argument (0 given)
>>> obj.carbonCopy(123)
File "<input>", line 1, in <module>
TypeError: Give an object() argument 1 must be str, not int
```
While the format string also supports a text for the complete error message (using a semicolon instead), I decided against this: Pythons …
> Sketcher: Fix wrong format string in PyArg_ParseTuple

- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
Presumably due to a copy/paste error, carbonCopy used to verify the referenced object via `isExternalAllowed` (just like addExternal). Now using `isCarbonCopyAllowed`, the resulting error message is the expected one for wrong objects, not a generic one after the operation failed.
> Sketcher: Fix check in carbonCopy's python interface

- src/Gui/View3DInventorViewer.cpp
Currently, in `~View3DInventorViewer()`, the scenegraph is freed first and then the `NavigationStyle` is freed. However, with the recently added rotation center indicator combined with refactored navigation animations in #9446, it could happen that `NavigationStyle` tries to access an already freed scenegraph and result in segmentation faults. This happens because the destructor of `NavigationStyle` would (indirectly) stop the animation and after that, try to remove the center indicator in a null scenegraph.
Freeing the `NavigationStyle` before the scenegraph could prevent this. Instead, I added a null check in `View3DInventorViewer::showRotationCenter` to make sure that method never tries to access a null scenegraph.
> Gui: Add nullptr check in showRotationCenter

- src/Mod/Path/Path/Base/Generator/helix.py
- src/Mod/Path/PathTests/TestPathHelixGenerator.py
A check in the helix toolpath generation code was rejecting Extra Offset values, even though there was enough space for the Extra Offset plus the tool inside the designed hole diameter.  
[[Problem] Path: Helix operation positive Extra Offset error](https://github.com/FreeCAD/FreeCAD/issues/10157) (https://github.com/FreeCAD/FreeCAD/issues/10157)
[Helix Extra Offset error in v0.21](https://github.com/FreeCAD/FreeCAD/issues/10336) (https://github.com/FreeCAD/FreeCAD/issues/10336)
[Problem with Helix operation](https://forum.freecad.org/viewtopic.php?t=80599)
[Helix Extra Offset error in v0.21](https://forum.freecad.org/viewtopic.php?p=673606)
> Path: helix toolpath was not allowing Extra Offset values that it should

- .git-blame-ignore-revs
Adds recent clang-format and pre-commit formatting change commits to the .git-blame-ignore-revs file -- generated with:
```
git log --format="%H # %s" --grep="format" --since="2023-08-1" >> .git-blame-ignore-revs
git log --format="%H # %s" --grep="pre-commit" --since="2023-08-1" >> .git-blame-ignore-revs
```
(and then hand-edited to remove a few that shouldn't be ignored).
> Git: Add recent formatting commits to ignore-revs

- src/Mod/Start/Gui/DlgStartPreferences.ui
Make it clearer that this property is different from the "Start up workbench".
See #10580.
> Start: Improve "Switch workbench after loading" tooltip

- src/Mod/TechDraw/Gui/DlgStringListEditor.cpp
This PR corrects a failure if all lines of an annotation are deleted as reported here: https://forum.freecad.org/viewtopic.php?t=80972
> [TD]fix fail on multiple empty annotation

- src/Mod/Sandbox/Gui/CMakeLists.txt
> Deprecate Qt4 for Qt6 in CMakeLists.txt

- src/Mod/Draft/draftguitools/gui_trackers.py
Steps to verify the issue:
1. Open FreeCAD.
2. Switch to Std_ViewTop.
3. Click one of the curved arrows of the Navigation Cube.
4. Switch to the Draft WB.
5. Make sure Draft_SelectPlane is set to "Auto".
6. Start Draft_Arc and click 2 points (for the radius and the start angle).
7. Result: The displayed arc does not match the start angle or the current point.
Additonally:
* Removed the normal argument from `__init__`. The tracker does not work properly with just a normal. AFAICT there is no code that specifies this normal.
* Minor improvement to `getAngle`: Switched the vectors.
> Draft: arcTracker did not take Working Plane rotation into account

- src/Mod/Fem/App/FemPostFilter.cpp
fix VTK checks version.
Before, any version V > 5.y or V > X.1 pass the 2 verifications.
> FEM: fix 3rd party VTK > 6.1 check

- src/Mod/Draft/Resources/ui/preferences-drafttexts.ui
- src/Mod/Draft/draftviewproviders/view_dimension.py
Currently the Draft dimensions, when set to display measurement in Building US units, simply removes the + symbol. With 0.21, Building US add an additional " symbol to overcome ambiguity. So 1' 2 3/4" is represented internally as 1' + 2" 3/4". Currently, this is rendered in Draft ad 1' 2" 3/4"
This PR:
1) removes the intermediary " so 1' +  2" 3/4" is rendered as 1' 2 3/4"
2) adds a preference setting under Draft -> Text settings to specify a custom feet separator. So for ex. by specifying a long dash ( — ), the measurement is rendered as 1' — 2 3/4"
TODO: Update https://wiki.freecad.org/Draft_Dimension
> Draft: Allow to set a custom feet separator for dimensions

- src/Gui/OpenCascadeNavigationStyle.cpp
When dragging in OpenCascade navigation style, the rotation center indicator is not shown because the rotation center is not found. The added lines make sure the rotation center is found.
> Gui: Fix rotation center indicator for OpenCascade style

- src/Gui/CommandDoc.cpp
- src/Gui/GraphvizView.cpp
- src/Gui/Workbench.cpp
This PR adds a new command to directly export the dependency graph to a .gv file. Additionally, when the Graphviz view is shown the global Save command allows to export in .gv format, too.
> Gui: fixes issue #9422: Dependency Graph: export to .dot/.gv

- src/Gui/TaskCSysDragger.cpp
- src/Gui/TaskCSysDragger.h
- src/Gui/ViewProviderDragger.cpp
- src/Gui/ViewProviderDragger.h
Fixes #7517
This PR replaces https://github.com/FreeCAD/FreeCAD/pull/10518 because something with the merging went wrong.
> Gui: Add cancel button to transform task UI dialog

- src/App/PropertyPythonObject.cpp
- src/Mod/Start/StartPage/StartPage.py
On Python 3.11 (tested using Debian 12) UnicodeDecodeErrors are raised when running All Tests, this PR addresses those errors.
Example Error :
```
File "/home/john/freecad-daily-build/Mod/Start/StartPage/StartPage.py", line 422, in handle
ALTCSS = f.read()
^^^^^^^^
File "/usr/lib/python3.11/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 421: ordinal not in range(128)
```
> [Start] Fix Python 3.11 Unicode Errors

- src/Mod/Part/Gui/TaskCheckGeometry.cpp
A UTF-8 encoded string is passed to Message_ProgressScope but the transformation back was done with latin1 which may show garbage.
> Part: fix encoding issue in BOPProgressIndicator::Show
