FreeCAD/FreeCAD

- src/Tools/plugins/widget/customwidgets.cpp
- src/Tools/plugins/widget/customwidgets.h
> Plugin: harmonize with FreeCAD widgets

- src/Base/Unit.cpp
- src/Base/UnitsSchemaInternal.cpp
- src/Base/UnitsSchemaMKS.cpp
- also sort units for better overview
> [Base] fix issues with new units

- src/App/PropertyUnits.h
- src/Gui/DlgUnitsCalculatorImp.cpp
> [App] [skip ci] some comment fixes

- src/Mod/Arch/importIFCHelper.py
---
In case there is some method it point me and we can close the PR without merge
> IFC: import helper, add method to convert IFC color to RGB col

- src/Mod/Fem/femexamples/equation_flow_elmer_2D.py
- the heat solver settings were wrong so that the heat was actually not calculated for convection
- also set more realistic temperatures
> [FEM] [skip ci] fixes for flow example

- src/Base/Quantity.cpp
- tests/src/Base/Units.cpp
> Base: fix pow() of Quantity

- src/Mod/TechDraw/App/AppTechDrawPy.cpp
- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/CosmeticEdgePyImp.cpp
- src/Mod/TechDraw/App/CosmeticExtension.cpp
- src/Mod/TechDraw/App/DimensionReferences.cpp
- src/Mod/TechDraw/App/DrawDimHelper.cpp
- src/Mod/TechDraw/App/DrawProjectSplit.cpp
- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
- src/Mod/TechDraw/App/Geometry.cpp
- src/Mod/TechDraw/App/Geometry.h
- src/Mod/TechDraw/App/GeometryObject.cpp
- src/Mod/TechDraw/Gui/CommandAnnotate.cpp
- src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
- src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
- src/Mod/TechDraw/Gui/DimensionValidators.cpp
- src/Mod/TechDraw/Gui/QGIDrawingTemplate.cpp
- src/Mod/TechDraw/Gui/QGIViewPart.cpp
- src/Mod/TechDraw/Gui/TaskLineDecor.cpp
This PR implements a solution for issue #8691.
- make attributes private (or protected) and use getters and setters instead of accessing attributes directly. …
> [TD]getters and setters for geometry ( #8691)

- src/Base/Quantity.cpp
- src/Base/Quantity.h
- tests/src/Base/Units.cpp
> Base: fix Lint warnings in Quantity

- tests/src/Base/Rotation.cpp
> Tests: add test of a matrix without rotation part to raise an exception

- src/Mod/Part/App/AppPart.cpp
- src/Mod/Part/App/CMakeLists.txt
- src/Mod/Part/App/PropertyTopoShapeList.cpp
- src/Mod/Part/App/PropertyTopoShapeList.h
- src/Mod/Part/App/TopoShape.cpp
- src/Mod/Part/App/TopoShape.h
- src/Mod/Part/CMakeLists.txt
- src/Mod/Part/TestPartApp.py
- src/Mod/Part/parttests/TopoShapeListTest.py
This PR implements a solution to Feature Request #8545.  It adds PropertyTopoShapeList to the Part module. …
> [Part]add PropertyTopoShapeList (FR 8545)

- src/Mod/Part/parttests/TopoShapeListTest.py
> Part: fix TopoShapeListTest

- src/Base/PlacementPyImp.cpp
- src/Base/RotationPyImp.cpp
- src/Mod/Import/App/ImportOCAF.cpp
- src/Mod/Import/App/ImportOCAF.h
- src/Mod/Mesh/App/MeshFeature.cpp
- src/Mod/Part/App/PartFeature.cpp
- src/Mod/Points/App/PointsFeature.cpp
- src/Mod/Test/BaseTests.py
> Catch exceptions

- src/Mod/AddonManager/package_details.py
Search-and-replace mistake.
---
> Addon Manager: Correct typo

- src/Mod/Part/App/TopoShape.cpp
* If the compound contains solids then other shape types like faces or edges are ignored
* If the compound contains no solids but faces then edges are ignored
* If the compound contains no faces but edges then vertexes are ignored …
> Part: Compute center of gravity for compounds

- tests/src/Base/CMakeLists.txt
- tests/src/Base/Quantity.cpp
- tests/src/Base/Unit.cpp
---
Keeping files under test in separate files simplifies test build for each.
> Multiple files under test in same test file

- src/Mod/Sketcher/Gui/SketcherSettings.h
> Sketcher: remove unused private field 'form'

- src/Mod/OpenSCAD/importCSG.py
A couple of OpenSCAD fixes from @KeithSloan.
---
> OpenSCAD: Improve shape-checking in group action

- src/Mod/Fem/App/FemMesh.cpp
- src/Mod/Fem/App/FemMesh.h
- src/Mod/Fem/App/FemMeshObject.cpp
- src/Mod/Fem/App/FemMeshObject.h
> FEM: implement interface of ComplexGeoData

- src/Mod/Part/BasicShapes/Utils.py
- src/Mod/Part/CMakeLists.txt
- src/Mod/Part/Gui/CommandSimple.cpp
> Part: extend command Part_PointsFromMesh to support any geometric type

- src/Mod/TechDraw/App/DrawViewSpreadsheet.cpp
This commit makes `DrawViewSpreadsheet::getAvailColumns()` more readable.
---
> [TechDraw] Improved readability of DrawViewSpreadsheet.cpp

- src/Mod/Cloud/Gui/CMakeLists.txt
- src/Tools/_TEMPLATE_/Gui/CMakeLists.txt
> Qt6: port template and Cloud module to Qt6

- package/fedora/freecad.spec
> [COPR] Fix COPR build

- src/Mod/Part/Gui/DlgSettings3DViewPart.ui
See also forum: https://forum.freecad.org/viewtopic.php?t=76614
---
> Part: set minimum angular deflection to 1 deg

- src/Tools/generateBase/generateDS.py
- src/Tools/generateBase/generateModel_Module.py
> Tools: Update generateDS.py file to Python3

- src/Mod/Fem/App/AppFem.cpp
- src/Mod/Fem/App/FemPostFunction.cpp
- src/Mod/Fem/App/FemPostFunction.h
- src/Mod/Fem/Gui/AppFemGui.cpp
- src/Mod/Fem/Gui/CMakeLists.txt
- src/Mod/Fem/Gui/Command.cpp
- src/Mod/Fem/Gui/CylinderWidget.ui
- src/Mod/Fem/Gui/ViewProviderFemPostFunction.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostFunction.h
it is now possible to work with a cylindrical filter function.
---
> FEM: Add cylinder filter function

- src/Gui/DlgSettingsNavigation.cpp
- as discussed here: https://github.com/FreeCAD/FreeCAD/pull/8567#issuecomment-1445283127 and following)
> [Gui] NaviCube: don't write font size on loading preferences

- src/Mod/Fem/App/FemPostFunction.cpp
- src/Mod/Fem/Gui/CMakeLists.txt
- src/Mod/Fem/Gui/CylinderWidget.ui
- src/Mod/Fem/Gui/ViewProviderFemPostFunction.cpp
- vector must be initialized and vector size requires a const int
- also some sorting
- also some formatting changes to be consistent (either always "x." or "x.0")
> [FEM] fix compilation of new Cylinder function

- src/Mod/PartDesign/App/FeatureLoft.cpp
Closes: https://github.com/FreeCAD/FreeCAD/issues/6156
---
> PD: Fix Loft's Closed option

- src/Mod/Fem/App/FemPostFunction.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostFunction.cpp
- just for consistency use always the form "x.0"
> [FEM] [skip ci] fine-tune FEM function filter

- src/Gui/ExpressionBinding.cpp
- src/Gui/ExpressionBinding.h
- src/Gui/ExpressionBindingPy.cpp
- src/Gui/ExpressionBindingPy.h
- src/Gui/InputField.cpp
- src/Gui/InputField.h
- src/Gui/SpinBox.h
- src/Gui/Widgets.h
> Split expression binding

- src/App/License.h
> App: add CC 3.0 licenses

- src/Gui/CommandStd.cpp
- src/Gui/Icons/Std_RecentMacros.svg
- src/Gui/Icons/resource.qrc
See https://forum.freecad.org/viewtopic.php?t=76641
To give some consistency I've based it on Std_RecentFiles
---
> [Gui] Add an icon for Std_RecentMacros command

- src/Gui/Icons/Std_RecentMacros.svg
- remove the Python logo in it (not visible in this size and can be license issue in future)
- save as plain SVG
> [Gui] [skip ci] improve new icon

- src/Gui/Action.cpp
> [Gui] Fix display names of Recent Macros

- src/Mod/Fem/App/FemPostFunction.cpp
- src/Mod/Fem/App/FemPostFunction.h
- src/Mod/Fem/Gui/Command.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostFunction.cpp
- set better initial position and size
- add misting triggering of ViewProvider
- some code style improvements (fix too long lines, consistency etc.)
> [FEM] improve cylinder function

- src/Tools/thumbs/ThumbnailProvider/CMakeLists.txt
> [skip ci] update ThumbnailProvider project

- src/Mod/TechDraw/App/Geometry.cpp
This PR fixes an error in the handling of BSpline as circles, reported here: https://forum.freecad.org/viewtopic.php?p=663890#p663890
---
> [TD]fix error from BSpline.asCircle

- src/Mod/PartDesign/App/Feature.cpp
- src/Mod/PartDesign/App/Feature.h
Forum post https://forum.freecad.org/viewtopic.php?p=663974#p663974
> PartDesign: do not include transform for sub-object in Feature

- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.cpp
- src/Mod/PartDesign/Gui/TaskHoleParameters.ui
- tooltip makes clear what the depth means for countersinks
- add comment why a calculation cannot be performed
- shorten some long lines
> [PD] add tooltip for Hole feature

- src/Mod/Part/App/Attacher.h
> remove unnecessary include

- src/Mod/PartDesign/PartDesignTests/TestLoft.py
> PD: add unit test for issue #6156 or PR #8748

- src/Mod/PartDesign/PartDesignTests/TestShapeBinder.py
> PD: add unit test for PR #8763

- src/Mod/Fem/App/AppFem.cpp
- src/Mod/Fem/App/FemPostFunction.cpp
- src/Mod/Fem/App/FemPostFunction.h
- src/Mod/Fem/Gui/AppFemGui.cpp
- src/Mod/Fem/Gui/BoxWidget.ui
- src/Mod/Fem/Gui/CMakeLists.txt
- src/Mod/Fem/Gui/Command.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostFunction.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostFunction.h
> Fem: Add box filter function

- tests/src/App/License.cpp
> Test: fix license unit test

- src/Mod/Fem/Gui/ViewProviderFemPostFunction.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostFunction.h
Some minor change in code style and and switch from comparing strings (error prone) to comparing property references.
---
> Fem: Remove property name comparison

- src/zipios++/collcoll.h
- after #8807 testing was broken due to a linking error, the fix was proposed in https://github.com/FreeCAD/FreeCAD/pull/8807#issuecomment-1464295791
- the formatting changes were automatically done according to our current clang file
> [Zipios] fix testing

- src/Mod/Draft/draftobjects/draftlink.py
> [Draft] fix regression introduced with #8433

- src/Mod/Fem/Gui/BoxWidget.ui
- src/Mod/Fem/Gui/Command.cpp
> [FEM] adjust initial position of new box filter

- src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp
- src/Mod/TechDraw/Gui/ViewProviderLeader.h
- src/Mod/TechDraw/Gui/ViewProviderPage.cpp
- src/Mod/TechDraw/Gui/ViewProviderPage.h
- src/Mod/TechDraw/Gui/ViewProviderProjGroup.cpp
- src/Mod/TechDraw/Gui/ViewProviderProjGroup.h
- src/Mod/TechDraw/Gui/ViewProviderProjGroupItem.cpp
- src/Mod/TechDraw/Gui/ViewProviderProjGroupItem.h
- src/Mod/TechDraw/Gui/ViewProviderTemplate.cpp
- src/Mod/TechDraw/Gui/ViewProviderViewClip.cpp
This PR is a clean up of unnecessary code.
---
> [TD]remove unused override methods

- src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp
- src/Mod/Sketcher/Gui/TaskSketcherMessages.cpp
- src/Mod/Sketcher/Gui/TaskSketcherMessages.h
- src/Mod/Sketcher/Gui/TaskSketcherMessages.ui
@abdullahtahiriyo Solver Message as we discussed.
---
> Sketcher: Solver Message Widget simplification.

- src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp
- src/Mod/Sketcher/Gui/TaskSketcherMessages.cpp
- src/Mod/Sketcher/Gui/TaskSketcherMessages.h
- src/Mod/Sketcher/Gui/TaskSketcherMessages.ui
- as discussed in #8838 (the PR will be improved after the weekend)
> [Sketch] reverse commit 944c02f12be37

- src/Mod/Sandbox/Gui/Command.cpp
- src/Mod/Sandbox/Gui/GLGraphicsView.cpp
- src/Tools/plugins/widget/plugin.cpp
- src/Tools/plugins/widget/plugin.h
> Removal of unused code due to old <5.2 QT ibrary

- src/Base/Observer.h
- src/Gui/PreCompiled.h
> Fix Windows builds

- tests/CMakeLists.txt
> Tests: suppress warnings C4251 in test module

- src/Mod/Path/libarea/kurve/kurve.cpp
Fix whitespace in `Path/libarea/kurve/kurve.cpp`
---
> libarea: fix whitespace

- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewPart.h
This PR addressing a problem where the image of the shape was not quite correctly positioned. …
> [TD]fix centering of shape in view

- src/Mod/TechDraw/Gui/QGCustomSvg.cpp
- src/Mod/TechDraw/Gui/QGCustomSvg.h
> [TD]allow loading SVG item from file

- src/Base/Factory.h
- src/Mod/AddonManager/addonmanager_utilities.py
- src/Mod/Fem/femexamples/equation_magnetodynamics_2D_elmer.py
- src/Mod/Fem/femexamples/equation_magnetostatics_2D_elmer.py
Grammar and whitespace fixes
---
> Fix misc. grammar and whitespace

- src/Gui/ToolBarManager.cpp
> Gui: [skip ci] fix whitespaces

- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/App/Preferences.h
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvancedImp.cpp
- src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
- src/Mod/TechDraw/Gui/Resources/icons/TechDraw_RefError.svg
This PR is preparatory work for dimension autocorrection. …
> [TD]add autocorrect preference

- src/Base/Factory.h
Per wmayer's suggestion in https://github.com/FreeCAD/FreeCAD/pull/8866#pullrequestreview-1337509742
---
> Refine previous fix for #8866

- tests/src/Misc/CMakeLists.txt
---
Remove original proof of concept test files as some fail, and that won't work too well with future possible CI !
> Clean_up_old_tests_designed_to_fail

- src/Mod/Import/App/AppImport.cpp
- src/Mod/Import/App/AppImportPy.cpp
- src/Mod/Import/App/FeatureImportIges.cpp
- src/Mod/Import/App/FeatureImportIges.h
- src/Mod/Import/App/FeatureImportStep.cpp
- src/Mod/Import/App/FeatureImportStep.h
- src/Mod/Import/App/ImportOCAF2.cpp
- src/Mod/Import/App/ImportOCAFAssembly.cpp
- src/Mod/Import/App/StepShape.cpp
- src/Mod/Import/Gui/AppImportGuiPy.cpp
> Clean mod import

- src/Mod/AddonManager/addonmanager_update_all_gui.py
> Addon Manager: Fix install after update all

- src/Mod/Import/App/AppImportPy.cpp
- src/Mod/Import/App/ImportOCAF2.cpp
- src/Mod/Import/Gui/AppImportGuiPy.cpp
- src/Mod/Part/App/TopoShape.cpp
> Import/Part: [skip ci] restore some comments

- src/App/CMakeLists.txt
- src/App/IndexedName.cpp
- src/App/IndexedName.h
- tests/src/App/CMakeLists.txt
- tests/src/App/IndexedName.cpp
Fixes #8765 -- extracts IndexedName into its own header and source files, performs clang-format and clang-tidy cleanups on it, refactors to clarify and correct some issues, and adds unit tests.
> App: Toponaming indexed name

- src/Mod/Draft/Resources/Draft.qrc
- src/Mod/Draft/Resources/icons/Draft_LayerManager.svg
- src/Mod/Draft/Resources/ui/dialogLayers.ui
- src/Mod/Draft/draftguitools/gui_layers.py
- src/Mod/Draft/draftutils/init_tools.py
This migrates the LayerManager command from BIM WB to Draft. The "Draft_Layer" Draft toolbar button is replaced with "Draft_LayerManager"
---
> Draft: Added LayerManager command from BIM

- src/Mod/Fem/Gui/ViewProviderFemPostPipeline.cpp
- src/Mod/Fem/ObjectsFem.py
- src/Mod/Fem/feminout/importCcxFrdResults.py
- src/Mod/Fem/femtaskpanels/task_result_mechanical.py
- src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py
- src/Mod/Fem/femtest/app/test_object.py
- make the connection also working for frequency and buckling analysis by directly creating/updating the pipeline where the CalculiX results are loaded
> [FEM] better pipeline connection for CalculiX

- src/Mod/Fem/Gui/ViewProviderAnalysis.cpp
- src/Mod/Fem/Gui/ViewProviderAnalysis.h
- src/Mod/Fem/Gui/ViewProviderFemPostFunction.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- src/Mod/Fem/Gui/ViewProviderSolver.cpp
- don't popup a warning if all childs of an object are selected too when deleting the object
> [FEM] improve deletion warning

- src/Mod/Fem/femsolver/elmer/equations/flow_writer.py
- the density must be output using the correct units. Due to this bug also the viscosity was written with wrong units-
- if there is a dynamic viscosity given for a material, use it directly
> [FEM] fix flow equation

- src/Gui/MainWindow.cpp
> Gui: add missing include for Qt6 build

- src/Mod/TechDraw/App/DrawViewDimension.cpp
- src/Mod/TechDraw/App/DrawViewDimension.h
- [X ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
---
> [TD]fix #8897 in v0.20

- src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
- src/Mod/Sketcher/Gui/TaskSketcherElements.h
https://forum.freecad.org/viewtopic.php?p=667426#p667426
> Elements widget crash

- src/Mod/TechDraw/App/CMakeLists.txt
- src/Mod/TechDraw/App/DrawSVGTemplate.cpp
- src/Mod/TechDraw/App/DrawViewSymbol.cpp
- src/Mod/TechDraw/App/QDomNodeModel.cpp
- src/Mod/TechDraw/App/XMLQuery.cpp
- src/Mod/TechDraw/App/XMLQuery.h
- src/Mod/TechDraw/Gui/QGISVGTemplate.cpp
> TD: move all XML query handling to a single function

- src/Gui/PropertyPage.cpp
- src/Gui/PropertyPage.h
- src/Gui/UiLoader.cpp
- src/Gui/UiLoader.h
> Gui: fix some lint warnings

- src/Mod/Sketcher/App/ConstraintPyImp.cpp
- src/Mod/Sketcher/App/PythonConverter.cpp
- src/Mod/Sketcher/App/Sketch.cpp
- src/Mod/Sketcher/App/Sketch.h
- src/Mod/Sketcher/App/planegcs/Constraints.cpp
- src/Mod/Sketcher/App/planegcs/Constraints.h
- src/Mod/Sketcher/App/planegcs/GCS.cpp
- src/Mod/Sketcher/App/planegcs/GCS.h
- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
- src/Mod/Sketcher/Gui/Utils.cpp
- src/Mod/Sketcher/Gui/Utils.h
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
Implements a circle to circle distance sketcher constraint, including concentric case.
Replace #8745
Forum discussion: https://forum.freecad.org/viewtopic.php?p=564607
@abdullahtahiriyo I took your remarks into account but I broke my git branch somewhere so this is the new place to commit.
> Sketcher : Circle to circle distance constraints

- src/Mod/Fem/femsolver/elmer/sifio.py
- Elmer offers the "Variable" calls do define variables via math equations. These are for example used to define as constraint a certain velocity profile
> [FEM] Elmer: support for variable strings

- src/Mod/Fem/femexamples/equation_flow_elmer_2D.py
- src/Mod/Fem/femexamples/equation_flow_initial_elmer_2D.py
- src/Mod/Fem/femexamples/equation_flow_turbulent_elmer_2D.py
- src/Mod/Fem/femsolver/elmer/equations/nonlinear.py
- use a more sensible velocity distribution
- change inlet temperature for 2 examples
- also change step size for nonlinear iterations for more convenience for practical usage
> [FEM] fine-tune flow examples

- src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py
- src/Mod/TechDraw/TDTest/DrawViewDimensionTest.py
- src/Mod/TechDraw/TDTest/TechDrawTestUtilities.py
- src/Tools/ThumbnailProvider/Main.cpp
- src/Tools/ThumbnailProvider/ThumbnailProvider.cpp
Fixes misc. whitespace issues.
---
> Fix various whitespace issues

- src/Mod/Sketcher/App/planegcs/Constraints.cpp
- fix too long lines
- also let clang reformat the file to uniform the formatting
> [Sketch] Constraints.cpp: formatting fixes

- src/App/CMakeLists.txt
- src/App/MappedName.cpp
- src/App/MappedName.h
- tests/src/App/CMakeLists.txt
- tests/src/App/MappedName.cpp
---
I'm giving a shot at #8766 
I've basically isolated the MappedName class into its own files and renamed a couple of variables to make the code more understandable, but apart from that I haven't changed anything.
I feel like …
> Toponaming: Added MappedName class

- src/Mod/Fem/femtaskpanels/task_solver_ccxtools.py
> FEM: [skip ci] fix grammar for console message

- src/Mod/Fem/femsolver/elmer/equations/deformation.py
- src/Mod/Fem/femsolver/elmer/equations/deformation_writer.py
- deformation is a nonlinear equation
- use the default that Elmer GUI uses for this equation
> [FEM] fixes for deformation equation

- src/Gui/3Dconnexion/GuiAbstractNativeEvent.h
- src/Gui/3Dconnexion/GuiNativeEventLinux.cpp
- src/Gui/3Dconnexion/GuiNativeEventLinux.h
- src/Gui/3Dconnexion/GuiNativeEventLinuxX11.cpp
- src/Gui/3Dconnexion/GuiNativeEventLinuxX11.h
- src/Gui/3Dconnexion/GuiNativeEventMac.cpp
- src/Gui/3Dconnexion/GuiNativeEventMac.h
- src/Gui/3Dconnexion/GuiNativeEventWin32.cpp
- src/Gui/3Dconnexion/GuiNativeEventWin32.h
- src/Gui/3Dconnexion/I3dMouseParams.h
Migrating tab indents to single space based indents in src/Gui/3Dconnexion/*
---
> Migrate tabs to spaces in `src/Gui/3Dconnexion/*`

- src/Mod/Import/App/AppImportPy.cpp
This reverts commit e1ebcef39e8
---
> Import: issue #8884: C++ DXF importer never imports text (annotations

- src/Mod/Fem/femcommands/commands.py
- src/Mod/Fem/femcommands/manager.py
- for e.g. the Elmer equations it is important that one can add several equations subsequently and that the added equations are visible in the TreeView
> [FEM] implement new object addition mode

- src/Mod/Fem/femcommands/commands.py
- src/Mod/Fem/femsolver/settings.py
- if there are other solvers found, we should handle all solvers equally
- also reduce amount of console output on every analysis run
> [FEM] don't add CCX solver by default for new analyses

- src/Mod/AddonManager/addonmanager_macro.py
> Addon Manager: Fix wiki macro icon cleanup

- src/Gui/Application.cpp
- for better readability (less scrolling in the IDE)
> [Gui] Application.cpp: fix too long lines

- src/Mod/Fem/Gui/DlgSettingsFemGeneral.ui
- src/Mod/Fem/Gui/DlgSettingsFemGeneralImp.cpp
- src/Mod/Fem/femcommands/commands.py
- src/Mod/Fem/femsolver/settings.py
> Fem: Add option to select default solver when creating Analysis

- src/Mod/Fem/femcommands/manager.py
- for the solvers the workflow should be that one can directly after adding a solver child to it via the toolbar Therefore select the added solver object
> [FEM] improve recently added addition method

- src/Ext/freecad/CMakeLists.txt
- src/Ext/freecad/project_utility.py
- src/Gui/DlgProjectUtility.cpp
- src/Gui/DlgProjectUtility.h
> Gui: move built-in Python code of DlgProjectUtility to script file

- src/Mod/Fem/Gui/DlgSettingsFemCcxImp.cpp
- src/Mod/Fem/Gui/DlgSettingsFemGeneral.ui
- src/Mod/Fem/Gui/DlgSettingsFemGeneralImp.cpp
- src/Mod/Fem/femcommands/commands.py
- src/Mod/Fem/femcommands/manager.py
- src/Mod/Fem/femsolver/settings.py
- fix bug if no solver should be default
- only provide solvers that are available to be the default
- also add commit opened transactions
- also remove unused include and correct an include
> [FEM] improve new default solver setting

- src/Mod/Fem/Gui/DlgSettingsFemGeneralImp.cpp
- if the default solver has not yet been set and there is only one solver available, set this as default
> [FEM] fine-tune default solver setting

- src/Mod/Fem/femexamples/equation_deformation_spring_elmer.py
- get outputs every 25 % and the last one is the final time
> [FEM] update transient analysis example file

- src/Mod/Fem/Gui/Command.cpp
> Fem: Remove unnecessary type check for active analysis

- src/Mod/Fem/femsolver/elmer/solver.py
- src/Mod/Fem/femsolver/elmer/writer.py
I have no clue what went wrong, thus reverting for now
> [FEM] revert a04c33c40f2

- src/App/CMakeLists.txt
- src/App/MappedElement.cpp
- src/App/MappedElement.h
- tests/src/App/CMakeLists.txt
- tests/src/App/MappedElement.cpp
> App/Toponaming: Add MappedElement

- src/Gui/CommandStd.cpp
- src/Gui/DlgPreferencesImp.cpp
- src/Gui/DlgPreferencesImp.h
See also: https://forum.freecad.org/viewtopic.php?t=77071
---
> Gui: by default restore the last visited page in the preferences dialog

- src/Mod/Fem/Gui/PreCompiled.h
- only include necessary Qt files
- remove unused OCC includes
- sort entries and remove duplicates
> [FEM] Gui: improve PreCompiled.h

- src/Mod/Fem/App/PreCompiled.h
- remove unused includes
- sort entries and remove duplicates
> [FEM] App: improve PreCompiled.h

- src/Mod/TechDraw/Gui/QGIViewDimension.h
> [TD] QGIViewDimension.h: fix compiler warning

- src/Base/FileInfo.cpp
- src/Mod/Fem/femsolver/elmer/solver.py
- also some formatting changes done by clang
> [FEM] Elmer: add missing deformation info

- src/Mod/Fem/femexamples/equation_deformation_spring_elmer.py
- make mesh more coarse to save calculation time
- since it is the example for transient solving, get one more result
> [FEM] change example file

- src/Mod/Fem/femsolver/elmer/solver.py
- src/Mod/Fem/femsolver/elmer/tasks.py
- src/Mod/Fem/femsolver/elmer/writer.py
- src/Mod/Fem/femtest/data/elmer/box_static_0_mm.sif
- src/Mod/Fem/femtest/data/elmer/ccxcantilever_faceload_0_mm.sif
- src/Mod/Fem/femtest/data/elmer/ccxcantilever_faceload_1_si.sif
- src/Mod/Fem/femtest/data/elmer/ccxcantilever_nodeload_0_mm.sif
- src/Mod/Fem/femtest/data/elmer/ccxcantilever_prescribeddisplacement_0_mm.sif
- for the first time ever you get now for every time step a result in FreeCAD
- this way also change output filename prefix to "FreeCAD" to avoid we depend on the default name Elmer gives and that was already changed in the past and to distinguish the *.vtu files from those created e.g. directly by ElmerGui
- also remove an unnecessary output to the case.sif file
> [FEM] proper support for transient analyses

- src/Base/Console.h
- src/Gui/DlgSettingsNotificationArea.cpp
- src/Gui/DlgSettingsNotificationArea.ui
- src/Gui/NotificationArea.cpp
Ability to configure whether errors and warnings will be subscribed to by the NotificationArea.
https://forum.freecad.org/viewtopic.php?p=670546#p670546
> [NotificationArea] select sources warning error

- src/App/Application.cpp
- src/App/ImagePlane.cpp
- src/App/ImagePlane.h
- src/Gui/FileHandler.cpp
- src/Gui/TaskView/TaskImageScale.cpp
- src/Gui/TaskView/TaskImageScale.h
- src/Gui/ViewProviderImagePlane.cpp
See forum: https://forum.freecad.org/viewtopic.php?p=670545#p670545
---
> Core: support to load old project files containing image planes

- .github/workflows/CI_cleanup.yml
I checked the dry runs and made some extra tests on my fork. Ready to go. 😄
> CI: enable CI cleaning for real

- src/Gui/Command.cpp
- src/Gui/Macro.cpp
- src/Gui/Macro.h
- src/Mod/PartDesign/Gui/Utils.cpp
- src/Mod/Sketcher/Gui/CommandConstraints.cpp
> Macro recording

- src/Mod/Fem/App/FemTools.cpp
- src/Mod/Fem/App/FemTools.h
- src/Mod/Fem/App/PreCompiled.h
- src/Mod/Fem/Gui/DlgSettingsFemGeneralImp.cpp
- src/Mod/Fem/Gui/Workbench.cpp
- src/Mod/Fem/femsolver/elmer/tasks.py
- the current implementation only considers explicitly given binaries (with full path) and ignores the setting to check the environment paths
> [FEM] fix binary check

- src/Gui/NotificationArea.cpp
===========================================
QT has a open bug regarding filling the contents of a QMenu in aboutShow: https://bugreports.qt.io/browse/QTBUG-54421
This commit presents a work-around this bug.
The two step procedure of this commit, forces a recalculation of the size from the slot and then manually moves the widget to the right position.
https://forum.freecad.org/viewtopic.php?p=669921#p669921
> NotificationArea: Correct painting position

- src/Mod/Sketcher/App/planegcs/Constraints.cpp
- src/Mod/Sketcher/App/planegcs/Constraints.h
- src/Mod/Sketcher/App/planegcs/GCS.cpp
- src/Mod/Sketcher/App/planegcs/GCS.h
- src/Mod/Sketcher/App/planegcs/Geo.cpp
- src/Mod/Sketcher/App/planegcs/Geo.h
- src/Mod/Sketcher/App/planegcs/SubSystem.cpp
- src/Mod/Sketcher/App/planegcs/SubSystem.h
- src/Mod/Sketcher/App/planegcs/Util.h
- also sort includes
- also fix too long lines etc. (done by clang formatter)
> [Sketch] placecgs: remove unused includes

- tests/src/App/IndexedName.cpp
> App/Toponaming: Add test for EDGE2<EDGE12

- src/Mod/Fem/femsolver/calculix/write_constraint_centrif.py
- src/Mod/Fem/femsolver/calculix/write_constraint_fluidsection.py
- src/Mod/Fem/femsolver/calculix/write_femelement_matgeosets.py
- src/Mod/Fem/femsolver/elmer/sifio.py
- src/Mod/Fem/femviewprovider/view_base_femobject.py
- src/Mod/Import/stepZ.py
- src/Mod/Path/Path/Base/Util.py
> remove remaining six dependencies

- src/Mod/Material/MaterialEditor.py
> Material: fix icon path

- src/Mod/OpenSCAD/prototype.py
> Fix typo in Mod/OpenSCAD/prototype.py

- src/Mod/Draft/importDWG.py
Exporting to DWG was giving a wrong message when no convertor could be found
---
> Draft: Better DWG export message - issue #8887

- src/Mod/OpenSCAD/OpenSCADFeatures.py
Fix bad indentation and separated import statements
---
> OpenSCAD: linting OpenSCADFeatures.py

- src/Mod/OpenSCAD/OpenSCAD2Dgeom.py
Fix bad indentation and separate import statements
---
> OpenSCAD: linting OpenSCAD2Dgeom.py

- .github/workflows/CI_cleanup.yml
Fix an issue failing cleanup workflow when date has no decimal part for seconds
> CI: fix issue in cleanup workflow

- src/Mod/Fem/App/FemConstraintInitialTemperature.cpp
- src/Mod/Fem/App/FemConstraintInitialTemperature.h
- src/Mod/Fem/App/FemConstraintTemperature.cpp
- src/Mod/Fem/App/FemConstraintTemperature.h
- src/Mod/Fem/Gui/TaskFemConstraintInitialTemperature.cpp
- src/Mod/Fem/Gui/TaskFemConstraintInitialTemperature.h
- src/Mod/Fem/Gui/TaskFemConstraintInitialTemperature.ui
- src/Mod/Fem/Gui/TaskFemConstraintTemperature.cpp
- src/Mod/Fem/Gui/TaskFemConstraintTemperature.h
- src/Mod/Fem/Gui/TaskFemConstraintTemperature.ui
- src/Mod/Fem/femsolver/calculix/write_constraint_initialtemperature.py
- src/Mod/Fem/femsolver/calculix/write_constraint_temperature.py
- src/Mod/Fem/femsolver/elmer/equations/deformation_writer.py
- src/Mod/Fem/femsolver/elmer/equations/elasticity_writer.py
- src/Mod/Fem/femsolver/elmer/equations/flow_writer.py
- src/Mod/Fem/femsolver/elmer/equations/heat_writer.py
- src/Mod/Fem/femtest/data/calculix/thermomech_bimetall.inp
- src/Mod/Fem/femtest/data/calculix/thermomech_spine.inp
- fix bug that changing constraint type in dialog lost flux value
- accept and not immediately save any changed value
- make the temperatures a PropertyTemperature to get rid of hacks
- also fix some too long code lines
> [FEM] Temperature constraints overhaul

- src/Mod/PartDesign/App/FeaturePipe.cpp
- remove commented includes (once mistakenly added by me)
- also fix too long lines
> [PD] FeaturePipe.cpp formatting fixes

- src/Mod/Fem/App/FemConstraintTransform.cpp
- src/Mod/Fem/App/FemConstraintTransform.h
- src/Mod/Fem/Gui/TaskFemConstraintTransform.cpp
- src/Mod/Fem/Gui/TaskFemConstraintTransform.h
- src/Mod/Fem/Gui/TaskFemConstraintTransform.ui
- make the angles a PropertyAngle to handle the unit
- also fix some too long code lines
> [FEM] Transform constraint polish

- src/Mod/OpenSCAD/OpenSCADCommands.py
Fixes bad indentation, seperate import statements, remove py2 syntax
---
> OpenSCAD: linting OpenSCADCommands.py

- src/Gui/ViewProviderImagePlane.cpp
> Gui: do not change size properties when loading an image

- src/Mod/Sketcher/Gui/SketcherSettingsGrid.ui
@abdullahtahiriyo name changes as asked here : https://forum.freecad.org/viewtopic.php?t=73420&start=30
---
> Sketcher: Grid pref: Change names.

- src/Mod/Draft/DraftGui.py
Remove obsolete code that was missed in #8327.
---
> [Draft] Remove obsolete ShapeString code from DraftGui.py

- src/Mod/Draft/DraftGui.py
PR to remove some leftover obsolete code. See also #9102.
---
> [Draft] small DraftGui.py cleanup

- cMake/FreeCAD_Helpers/InitializeFreeCADBuildOptions.cmake
- ci/Dockerfile
- src/Gui/PythonWrapper.cpp
- src/Mod/PartDesign/FeatureHole/HoleGui.py
- src/Mod/PartDesign/FeatureHole/TaskHole.py
- src/Mod/Plot/Plot.py
- src/Mod/Sandbox/Gui/Command.cpp
- src/Mod/Sandbox/Gui/Workbench.cpp
---
Fixes #9073 
Please do check this is all correct as my understanding of the FreeCAD codebase is still limited
> Remove all PyQt references

- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/Gui/QGIView.cpp
> [TechDraw] Improve readability of scripts

- src/Mod/Mesh/Gui/DlgRegularSolidImp.cpp
- src/Mod/Mesh/Gui/DlgRegularSolidImp.h
- src/Mod/Mesh/Gui/DlgSmoothing.cpp
- src/Mod/Mesh/Gui/DlgSmoothing.h
- src/Mod/Mesh/Gui/RemeshGmsh.cpp
- src/Mod/Mesh/Gui/RemeshGmsh.h
- src/Mod/Mesh/Gui/RemoveComponents.cpp
- src/Mod/Mesh/Gui/RemoveComponents.h
- src/Mod/Mesh/Gui/SegmentationBestFit.cpp
- src/Mod/Mesh/Gui/SegmentationBestFit.h
- src/Mod/Mesh/Gui/Selection.cpp
- src/Mod/Mesh/Gui/Selection.h
> Mesh: fix -Wclazy-connect-by-name

- tests/src/Misc/fmt.cpp
> Tests: add some more fmt tests

- src/Gui/TaskView/TaskImageScale.cpp
- src/Gui/TaskView/TaskImageScale.h
- src/Gui/TaskView/TaskImageScale.ui
- src/Gui/TaskView/TaskOrientation.cpp
- src/Gui/ViewProviderImagePlane.cpp
> Interactive image scale

- src/Mod/TechDraw/Gui/QGIView.cpp
This PR corrects a mistake in PR #9129.
---
> [TD]fix oversight in PR9129

- tests/src/App/MappedName.cpp
Fix whitespace in toponaming test file
---
> Toponaming: fix whitespace in App/MappedName.cpp

- src/Mod/Draft/WorkingPlane.py
fix for mistake in pr https://github.com/FreeCAD/FreeCAD/pull/8698. See comment https://github.com/FreeCAD/FreeCAD/pull/8698/files/649857b58f7b100242a2e948e07e11ff2fe64f67#r1155160709
> Draft: fix error in PR #8698

- src/Mod/OpenSCAD/importCSG.py
Various linting fixes applied to `OpenSCAD/importCSG.py`
---
> OpenSCAD: linting importCSG.py

- src/Gui/DlgSettingsViewColor.cpp
- src/Gui/DlgSettingsViewColor.ui
- src/Gui/PreferencePackTemplates/Window_Colors.cfg
- src/Gui/PreferencePacks/FreeCAD Classic Colors/FreeCAD Classic Colors.cfg
- src/Gui/SoFCBackgroundGradient.cpp
- src/Gui/SoFCBackgroundGradient.h
- src/Gui/SplitView3DInventor.cpp
- src/Gui/View3DInventorViewer.cpp
- src/Gui/View3DInventorViewer.h
- src/Gui/View3DSettings.cpp
- src/Gui/View3DViewerPy.cpp
This commit implements radial gradient as background and adds the option to settings. It also renames "Color gradient" as "Linear gradient", keeping Linear gradient default. Internally, it remains unchanged for compatibility.
Radio gradient is more suitable for CAD, since it gives a more balanced color distribution across the screen, improving visibility of model and sketches with a halo-like effect.
This pull request closes #8297. I advise to set radial gradient default in the upcoming version of FreeCAD.
<details><summary>Options</summary>
</details>
<details><summary>Screenshot 2</summary>
</details>
<details><summary>Screenshot 3</summary>
</details>
<details><summary>Screenshot 4</summary>
</details>
<details><summary>ProDark</summary>
</details>
<details><summary>ProDark2</summary> …
> [GUI] Radial gradient implementation

- src/Gui/SoFCBackgroundGradient.cpp
- src/Gui/SoFCBackgroundGradient.h
- src/Gui/SplitView3DInventor.cpp
- src/Gui/View3DSettings.cpp
> Gui: by default radial gradient is off

- src/Gui/SoFCBackgroundGradient.cpp
- src/Gui/SoFCBackgroundGradient.h
- src/Gui/SplitView3DInventor.cpp
- src/Gui/SplitView3DInventor.h
- src/Gui/View3DInventorViewer.cpp
- src/Gui/View3DInventorViewer.h
- src/Gui/View3DSettings.cpp
- src/Gui/View3DSettings.h
- src/Gui/View3DViewerPy.cpp
- src/Gui/View3DViewerPy.h
> Improve handling of viewer settings and background colors

- src/Gui/Action.cpp
- src/Gui/ApplicationPy.cpp
- src/Gui/CommandStd.cpp
- src/Gui/DlgPreferencesImp.cpp
- src/Gui/DlgPreferencesImp.h
- src/Gui/DlgSettingsWorkbenchesImp.cpp
- src/Gui/DlgSettingsWorkbenchesImp.h
- src/Gui/PropertyPage.cpp
- src/Gui/PropertyPage.h
- src/Mod/AddonManager/Addon.py
- src/Mod/AddonManager/addonmanager_installer.py
- src/Mod/AddonManager/addonmanager_uninstaller.py
Fixes following @wwmayer comments on https://github.com/FreeCAD/FreeCAD/pull/9026
Remove the list of disabled wb.
Added functions to subscribe / unsubscribe wb from enabled list.
```
DlgSettingsWorkbenchesImp::addToEnabledWorkenches(const QString wbToAddName)
DlgSettingsWorkbenchesImp::removeFromEnabledWorkenches(const QString wbToRemoveName)
```
TODO: Addon manager should add workbenches to the list of enabled wb on installation. And remove on uninstall.
TODO 2: Addon-manager "disable" methode should be removed and replaced with the core disabling system.
Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD …
> Wb pref fixes

- SECURITY.md
GitHub recommends that projects have a security policy, so I have drafted one, based on some earlier writing by @sliptonic.
> Project: Add Security Policy

- src/Gui/DlgActionsImp.cpp
- src/Gui/DlgActionsImp.h
- src/Gui/DlgCustomizeSpNavSettings.cpp
- src/Gui/DlgCustomizeSpNavSettings.h
- src/Gui/DlgKeyboardImp.cpp
- src/Gui/DlgKeyboardImp.h
- src/Gui/DlgMacroExecuteImp.cpp
- src/Gui/DlgMacroExecuteImp.h
- src/Gui/DlgMacroRecord.ui
- src/Gui/DlgMacroRecordImp.cpp
- src/Gui/DlgMacroRecordImp.h
- src/Gui/DlgMaterialPropertiesImp.cpp
- src/Gui/DlgMaterialPropertiesImp.h
- src/Gui/DlgParameterFind.cpp
- src/Gui/DlgParameterFind.h
- src/Gui/DlgParameterImp.cpp
- src/Gui/DlgParameterImp.h
- src/Gui/DlgPropertyLink.cpp
- src/Gui/DlgPropertyLink.h
- src/Gui/DlgSettingsImageImp.cpp
- src/Gui/DlgSettingsImageImp.h
- src/Gui/DlgSettingsNavigation.cpp
- src/Gui/DlgSettingsNavigation.h
- src/Gui/DlgToolbarsImp.cpp
- src/Gui/DlgToolbarsImp.h
- src/Gui/DlgUnitsCalculatorImp.cpp
- src/Gui/DlgUnitsCalculatorImp.h
> Replace QMetaObject::connectSlotsByName with explicit connect()

- src/Mod/TechDraw/App/DrawGeomHatch.cpp
- src/Mod/TechDraw/App/DrawHatch.cpp
- src/Mod/TechDraw/App/DrawLeaderLine.cpp
> [TechDraw] Improve readability of APP scripts

- src/Mod/TechDraw/App/DrawPage.cpp
- src/Mod/TechDraw/App/DrawParametricTemplate.cpp
- src/Mod/TechDraw/App/DrawParametricTemplatePyImp.cpp
- src/Mod/TechDraw/App/DrawProjectSplit.cpp
> [TechDraw] Improve readability of APP scripts 2

- src/Mod/TechDraw/App/DrawProjGroup.cpp
- src/Mod/TechDraw/App/DrawProjGroupItem.cpp
- src/Mod/TechDraw/App/DrawProjGroupItemPyImp.cpp
> [TechDraw] Improve readability of APP scripts 3

- src/Mod/Import/stepZ.py
fixing stepZ for exporting
fixing error builtin instead of builtins
on https://github.com/FreeCAD/FreeCAD/commit/42cb7565223ac602ab21ecfb41cac8c70156ee98
---
> fixing stepZ for exporting

- src/Gui/ListWidgetDragBugFix.cpp
- src/Mod/PartDesign/Gui/TaskBooleanParameters.ui
- src/Mod/PartDesign/Gui/TaskChamferParameters.ui
- src/Mod/PartDesign/Gui/TaskDraftParameters.ui
- src/Mod/PartDesign/Gui/TaskFilletParameters.ui
- src/Mod/PartDesign/Gui/TaskHelixParameters.ui
- src/Mod/PartDesign/Gui/TaskLinearPatternParameters.ui
- src/Mod/PartDesign/Gui/TaskLoftParameters.ui
- src/Mod/PartDesign/Gui/TaskMirroredParameters.ui
- src/Mod/PartDesign/Gui/TaskMultiTransformParameters.ui
- src/Mod/PartDesign/Gui/TaskPadPocketParameters.ui
- src/Mod/PartDesign/Gui/TaskPipeParameters.ui
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.ui
- src/Mod/PartDesign/Gui/TaskRevolutionParameters.ui
- src/Mod/PartDesign/Gui/TaskScaledParameters.ui
- src/Mod/PartDesign/Gui/TaskShapeBinder.ui
- src/Mod/PartDesign/Gui/TaskThicknessParameters.ui
> Minor fixes

- src/Mod/TechDraw/App/DrawTemplatePyImp.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/DrawViewSymbol.cpp
- src/Mod/TechDraw/App/EdgeWalker.cpp
> [TechDraw] Improve readability of APP scripts 4

- tests/src/App/Branding.cpp
- tests/src/App/ElementMap.cpp
- tests/src/App/IndexedName.cpp
- tests/src/App/License.cpp
- tests/src/App/MappedName.cpp
- tests/src/App/Metadata.cpp
- tests/src/Base/Builder3D.cpp
- tests/src/Base/Quantity.cpp
- tests/src/Base/Rotation.cpp
- tests/src/Base/Unit.cpp
- tests/src/Gui/Assistant.cpp
- tests/src/Misc/fmt.cpp
- tests/src/Qt/InventorBuilder.cpp
- tests/src/zipios++/collectioncollection.cpp
- tests/src/zipios++/zipfile.cpp
This applies all of our pre-commit hooks to the files in tests/src -- it serves as a final test of our clang-format file before we choose to apply it elsewhere. 
---
> Formatting: Apply pre-commit to tests/src

- src/Mod/Draft/importDWG.py
> Draft: fix typo in importDWG.py

- src/App/Application.cpp
- src/App/ProgramOptionsUtilities.h
- src/App/PropertyUnits.cpp
- tests/src/App/Application.cpp
- tests/src/App/CMakeLists.txt
---
Dramatic simplification of legacy code by separating code and data and applying some newer C++.
I couldn't figure out how to put the function directly under test as it is in an anonymous namespace, so kludged by copying it …
> More separate code and data

- src/App/Application.cpp
- src/App/ProgramOptionsUtilities.h
> App: fix some lint warnings

- src/Mod/Path/App/PathSegmentWalker.cpp
- src/Mod/Path/App/PathSegmentWalker.h
- src/Mod/Path/Gui/Resources/panels/PageOpDrillingEdit.ui
- src/Mod/Path/Path/Op/Drilling.py
- src/Mod/Path/Path/Op/Gui/Drilling.py
- src/Mod/Path/Path/Post/scripts/grbl_post.py
---
This is a clean up of previous #9153 with no code changes ( lint white space mainly ).
> Path: make drilling paths G99 aware and NIST compliant (tidy up)

- src/Mod/TechDraw/App/CenterLine.cpp
- src/Mod/TechDraw/App/ShapeExtractor.cpp
This PR fixes a problem with infinite shapes reported here: https://forum.freecad.org/viewtopic.php?t=69196 …
> [TD]Fix infinite shape transform

- src/Gui/View3DInventorViewer.cpp
> Gui: [skip ci] fix typo View3DInventorViewer::toQPoint

- src/Mod/TechDraw/App/Preferences.cpp
- src/Mod/TechDraw/App/Preferences.h
- src/Mod/TechDraw/Gui/PreferencesGui.cpp
> [TechDraw] Simplify retrievement of user preferences

- src/Mod/TechDraw/App/DrawProjGroup.cpp
This PR fixes an error reported here: https://forum.freecad.org/viewtopic.php?t=77479 …
> [TD]fix error in DPG from bf00a1afc9

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
Regression introduced by 58a9af2 (PR #9151)
https://forum.freecad.org/viewtopic.php?t=77452
I'm guilty for this. :yum:
> [Bugfix]Sketcher: edge/point colors in preferences aren't took into account

- src/Mod/Arch/ArchPanel.py
- src/Mod/Arch/ArchSectionPlane.py
- src/Mod/Arch/Resources/Arch.qrc
- src/Mod/Arch/Resources/icons/Arch_Panel_Sheet_Tree.svg
- src/Mod/Arch/TestArch.py
This PR removes obsolete code related to the Drawing WB.
Additionally:
* Arch_Panel_Sheet_Tree.svg to replace Draft_Drawing.svg
* Removed the underscore from Draft base class names.
---
> [Arch] Remove obsolete code related to the Drawing WB

- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/CosmeticExtension.cpp
- src/Mod/TechDraw/App/DrawView.cpp
- src/Mod/TechDraw/App/DrawViewArch.cpp
- src/Mod/TechDraw/App/DrawViewBalloon.cpp
- src/Mod/TechDraw/App/DrawViewDimExtentPyImp.cpp
- src/Mod/TechDraw/App/DrawViewDraft.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewSymbol.cpp
- src/Mod/TechDraw/App/GeometryObject.cpp
- src/Mod/TechDraw/App/HatchLine.cpp
- src/Mod/TechDraw/App/LandmarkDimension.cpp
- src/Mod/TechDraw/App/LineGroup.cpp
- src/Mod/TechDraw/Gui/DimensionValidators.cpp
- src/Mod/TechDraw/Gui/DlgTemplateField.cpp
- src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
- src/Mod/TechDraw/Gui/QGCustomImage.cpp
- src/Mod/TechDraw/Gui/QGIMatting.cpp
- src/Mod/TechDraw/Gui/QGIRichAnno.cpp
- src/Mod/TechDraw/Gui/QGISectionLine.cpp
- src/Mod/TechDraw/Gui/Rez.cpp
- src/Mod/TechDraw/Gui/TaskDetail.cpp
- src/Mod/TechDraw/Gui/TaskSelectLineAttributes.cpp
- src/Mod/TechDraw/Gui/ViewProviderLeader.cpp
- src/Mod/TechDraw/Gui/mrichtextedit.cpp
> [TechDraw] Simplify return logic, part 1

- src/Mod/TechDraw/App/CosmeticExtension.cpp
- src/Mod/TechDraw/App/DrawProjGroupItem.cpp
- src/Mod/TechDraw/App/DrawView.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/GeometryObject.cpp
- src/Mod/TechDraw/App/HatchLine.cpp
- src/Mod/TechDraw/App/ShapeExtractor.cpp
- src/Mod/TechDraw/Gui/DlgPageChooser.cpp
- src/Mod/TechDraw/Gui/QGIArrow.cpp
- src/Mod/TechDraw/Gui/QGIFace.cpp
- src/Mod/TechDraw/Gui/QGILeaderLine.cpp
- src/Mod/TechDraw/Gui/QGIPrimPath.cpp
- src/Mod/TechDraw/Gui/QGIRichAnno.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
- src/Mod/TechDraw/Gui/mrichtextedit.cpp
> [TechDraw] Simplify return logic, part 2

- src/Base/PythonTypeExt.cpp
- src/Gui/CommandActionPy.cpp
> MSVC: fix build failure related to PCH

- src/Mod/Mesh/Gui/SoFCIndexedFaceSet.cpp
> Mesh: [skip ci] restore comment

- src/Gui/DlgSettings3DView.ui
- src/Gui/DlgSettings3DViewImp.cpp
- src/Gui/DlgSettingsSelection.cpp
- src/Gui/DlgSettingsSelection.ui
Issue https://github.com/FreeCAD/FreeCAD/issues/9205
This only moves the preference to Selection tab.
---
> Pref: Move pick radius to selection.

- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvancedImp.cpp
This PR adds a preference checkbox to the advanced tab of TechDraw preferences to control which face finding algorithm should be used.
---
> [TD]add preference for new face finder

- src/Mod/AddonManager/addonmanager_macro.py
Macros whose GitHub source code contained a URL weren't being correctly cleaned: this fixes that.
> Addon Manager: Fix git icons on wiki

- src/Mod/Part/Gui/ViewProviderExt.cpp
Also with docstring just below modified line
> Gui: consistent angular deflection between Part and Preferences

- src/Mod/PartDesign/Gui/TaskChamferParameters.cpp
- src/Mod/PartDesign/Gui/TaskDraftParameters.cpp
- src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
- src/Mod/PartDesign/Gui/TaskDressUpParameters.h
- src/Mod/PartDesign/Gui/TaskFilletParameters.cpp
- src/Mod/PartDesign/Gui/TaskThicknessParameters.cpp
> PD: fix crash on Windows when loading PD workbench

- src/Gui/DlgGeneral.ui
Just reorganizing the page to fix some things. Please see the commits for the individual fixes.
Below how it looks after this PR: 
Including https://github.com/FreeCAD/FreeCAD/issues/9255
---
> Pref: general: Re-organize page.

- src/Mod/TechDraw/Gui/DlgPrefsTechDrawDimensions.ui
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.h
- src/Mod/TechDraw/Gui/ViewProviderDimension.cpp
- src/Mod/TechDraw/Gui/ViewProviderDimension.h
> [TechDraw] Add customizability for dimension line spacing

- src/Mod/Path/CMakeLists.txt
- src/Mod/Path/Path/Post/scripts/fangling_post.py
Added post processor for Fangling plasma cutter to path workbench.
Fangling plasma cutters seems to be a rather common in Chinese plasma cutters and is probably used in many different brands. It have been tried using the engrave operation in demo mode on real hardware and seems to work but not yet cut real metal.
**Note**: If you don't have wiki access, then please mention your contribution on …
> Path: Added post processor for Fangling plasma cutter

- src/Gui/SoFCColorGradient.h
- src/Gui/SoFCColorLegend.h
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/196
---
> Gui: Add translations for color bar labels

- src/Gui/DlgSettingsWorkbenchesImp.cpp
https://forum.freecad.org/viewtopic.php?p=676426#p676426
---
> Pref: Wb: disabling wb do not disable auto-load.

- src/Tools/updatets.py
The main purpose here is to resolve https://github.com/FreeCAD/FreeCAD-translations/issues/194 by forcing UTF-8 encoding in a couple of places. This also does a reformatting pass using Black (as a separate commit).
---
> Translate tool remove BOM

- src/Mod/Arch/ArchStairs.py
Fixed bad indentation, long line, superflous parathesis, and formatting
---
> Arch: fix linting for ArchStairs.py

- src/Mod/Arch/ArchPanel.py
* src/Mod/Arch/ArchPanel.py: Remove deprecated "utf8_decode=True" from "translate" calls.
---
> ArchPanel: Remove "utf8_decode=True" from "translate" calls

- src/Mod/PartDesign/Gui/CommandBody.cpp
The labels of new bodies are not localized. This PR fixes this issue.
---
> i18n for CommandBody

- src/Gui/Workbench.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/8
---
> GUI: Add missing toolbar translation strings

- src/Mod/Part/BasicShapes/ShapeContent.py
- src/Mod/Part/Gui/TaskCheckGeometry.cpp
Translate the strings that it's possible to translate in the Part->CheckGeometry results. The various Principal Properties are not as easy to translate, so I haven't included those here. Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/182
---
> Part: translate geometry check results

- src/Mod/Arch/ArchAxisSystem.py
- src/Mod/Arch/ArchCommands.py
- src/Mod/Arch/ArchComponent.py
- src/Mod/Arch/ArchFence.py
- src/Mod/Arch/ArchSite.py
- src/Mod/Arch/ArchSpace.py
- src/Mod/Arch/ArchVRM.py
- src/Mod/Arch/ArchWall.py
- src/Mod/Arch/ArchWindow.py
- src/Mod/Arch/OfflineRenderingUtils.py
- src/Mod/Arch/exportIFC.py
- src/Mod/Arch/exportIFCStructuralTools.py
- src/Mod/Arch/ifc_objects.py
- src/Mod/Arch/importGBXML.py
- src/Mod/Arch/importIFC.py
- src/Mod/Arch/importOBJ.py
> Arch: lint bad indentation, superfluous formatting

- src/Mod/Draft/draftfunctions/upgrade.py
- src/Mod/Draft/draftgeoutils/general.py
- src/Mod/Draft/draftguitools/gui_groups.py
- src/Mod/Draft/draftguitools/gui_points.py
- src/Mod/Draft/draftguitools/gui_trackers.py
- src/Mod/Draft/draftmake/make_sketch.py
- src/Mod/Draft/draftobjects/bezcurve.py
- src/Mod/Draft/draftobjects/shape2dview.py
- src/Mod/Draft/draftobjects/shapestring.py
- src/Mod/Draft/importAirfoilDAT.py
> Draft: linting bad indentations, superflous markup

- src/Mod/Arch/ArchCommands.py
- src/Mod/Arch/ArchPanel.py
- src/Mod/Arch/ArchReference.py
- src/Mod/Arch/ArchWall.py
- src/Mod/Arch/import3DS.py
- src/Mod/Arch/importDAE.py
- src/Mod/Arch/importIFClegacy.py
- src/Mod/Arch/importOBJ.py
- src/Mod/Arch/importSH3D.py
- src/Mod/Arch/importSHP.py
> [Arch] remove obsolete decode code

- src/Gui/DlgParameterFind.h
- src/Gui/TextureMapping.h
> Gui: declare methods as override

- src/Mod/Draft/draftguitools/gui_groups.py
Forum topic:
https://forum.freecad.org/viewtopic.php?p=676875#p676875
---
> [Draft] Disable Draft_AddConstruction if there is no selection

- src/Gui/TaskView/TaskImage.cpp
- src/Gui/TaskView/TaskImage.h
* refactor some functions
* do not use mdi view of active document as parent for spin box because this can be the wrong widget
* fix compiler warnings of unused variables
* fix typo
* handle Qt::Key_Return in event filter
* fix lint error …
> Gui: fix several pending issues of image scale

- src/App/Origin.cpp
- src/App/Origin.h
- src/Mod/Test/Document.py
This PR adds i18n for axes and planes.
---
> added i18n for axes and planes

- src/Mod/Fem/Gui/TaskFemConstraintDisplacement.ui
Bug identified by FEA-eng on CrowdIn.
> FEM: Correct mis-spelled 'Elmer'

- src/App/OriginGroupExtension.cpp
- src/App/OriginGroupExtension.h
This patch adds i18n for the origin.
---
> added i18n for the origin

- src/Mod/Fem/femguiutils/selection_widgets.py
> FEM: some small pep8 code formatting changes 

- src/Mod/Fem/feminout/importFenicsMesh.py
- src/Mod/Fem/feminout/readFenicsXDMF.py
- src/Mod/Fem/feminout/readFenicsXML.py
- src/Mod/Fem/feminout/writeFenicsXDMF.py
- src/Mod/Fem/feminout/writeFenicsXML.py
* XDMF: capital "V" in version attribute in XDMF tag
* XDMF: capitalizing element names to be in line with specification
* XML: removed data section to prevent warning in meshio reading
---
> FEM: feminout: XDMF and XML writing: fixed minor errors and format now in line with meshio

- src/Mod/Arch/ArchStairs.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/18
> Arch: Fix translation context for Stairs

- src/Mod/TechDraw/Gui/DlgPrefsTechDrawAdvanced.ui
Suggested by david69 on CrowdIn
> TechDraw: Preferences wording tweak

- src/Mod/Sketcher/Gui/Command.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/73
---
> Sketcher: Translate the attacher GUI dropdown

- src/Mod/TechDraw/App/DrawProjGroupItem.cpp
- src/Mod/TechDraw/Gui/QGIView.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/71
---
> TechDraw: Translate direction labels

- src/Mod/Part/BOPTools/JoinFeatures.py
- src/Mod/Part/BOPTools/SplitFeatures.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/66
> Part: Fix context of Part->Split commands

- src/Mod/Fem/femcommands/commands.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/94
---
> FEM: Translate Solver Calculix

- src/Mod/Part/Gui/TaskCheckGeometry.cpp
Cleanup of translation issues related to https://github.com/FreeCAD/FreeCAD-translations/issues/182 (note that this does not close that issue, which has many sub-issues).
> Gui: TaskCheckGeometry message translation

- src/Mod/Sketcher/App/planegcs/Constraints.h
- src/Mod/Sketcher/App/planegcs/GCS.h
- tests/CMakeLists.txt
- tests/src/Mod/Sketcher/App/CMakeLists.txt
- tests/src/Mod/Sketcher/App/planegcs/CMakeLists.txt
- tests/src/Mod/Sketcher/App/planegcs/GCS.cpp
- tests/src/Mod/Sketcher/CMakeLists.txt
Begin the process of adding Google Test C++ unit tests to Sketcher.
---
> Sketcher: Add gtest unit test framework

- src/Mod/TechDraw/Gui/Workbench.cpp
Added the three missing entries, and sorted them alphabetically to make them easier to find in the future. Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/134
> TechDraw: Add a few missing translation strings

- src/Mod/TechDraw/TechDrawTools/TaskMoveView.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/147
> TechDraw: Fix translations of TaskMoveView

- src/Mod/TechDraw/TechDrawTools/TaskShareView.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/146
> TechDraw: Fix translations of TaskShareView

- src/Tools/updatecrowdin.py
This was missing from the script (note that I have manually uploaded the TS file, this is just to ensure sync later on).
> Tools: Add Inspection to Updatecrowdin

- src/Mod/Part/Gui/Command.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/75
> Part: Translate offset toolbar dropdown

- src/Mod/Path/Path/Main/Gui/Fixture.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/173
> Path: Correct context for Path_Fixture translations

- src/Doc/CONTRIBUTORS
- src/Doc/templates/doxy-boot.js
- src/Gui/NaviCube.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
- src/Tools/params_utils.py
Trim whitespace; move imports to separate lines, fix typos
---
> Fix misc. linting and typos

- .gitignore
Adds the CLion default cmake build locations to gitignore like cmake-build-debug and cmake-build-release.
---
> Add CLion default cmake-build locations to gitignore

- src/Mod/TechDraw/App/XMLQuery.cpp
This PR addresses issue 9394 and discussion here: https://forum.freecad.org/viewtopic.php?t=77905
---
> [TD]Handle changed xml namespace

- src/Mod/TechDraw/Gui/TaskCustomizeFormat.ui
This PR addresses a request made here: https://forum.freecad.org/viewtopic.php?t=77959
---
> [TD]fix minimum width in TaskCustomizeFormat

- src/Mod/Import/App/dxf/dxf.cpp
> Import: fixes #9438: Crash when loading DXF file with a text element

- src/Gui/View3DInventorViewer.cpp
- src/Gui/View3DInventorViewer.h
> Fix black image

- src/Gui/PythonConsole.cpp
- src/Gui/PythonConsolePy.cpp
- src/Gui/PythonConsolePy.h
- src/Main/FreeCADGuiPy.cpp
> Core: do not override sys.stdin when using FreeCAD as Python module

- src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
- src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp
- src/Mod/PartDesign/Gui/ViewProviderChamfer.cpp
- src/Mod/PartDesign/Gui/ViewProviderChamfer.h
- src/Mod/PartDesign/Gui/ViewProviderDraft.cpp
- src/Mod/PartDesign/Gui/ViewProviderDraft.h
- src/Mod/PartDesign/Gui/ViewProviderDressUp.cpp
- src/Mod/PartDesign/Gui/ViewProviderDressUp.h
- src/Mod/PartDesign/Gui/ViewProviderFillet.cpp
- src/Mod/PartDesign/Gui/ViewProviderFillet.h
- src/Mod/PartDesign/Gui/ViewProviderLinearPattern.cpp
- src/Mod/PartDesign/Gui/ViewProviderLinearPattern.h
- src/Mod/PartDesign/Gui/ViewProviderMirrored.cpp
- src/Mod/PartDesign/Gui/ViewProviderMirrored.h
- src/Mod/PartDesign/Gui/ViewProviderMultiTransform.cpp
- src/Mod/PartDesign/Gui/ViewProviderMultiTransform.h
- src/Mod/PartDesign/Gui/ViewProviderPolarPattern.cpp
- src/Mod/PartDesign/Gui/ViewProviderPolarPattern.h
- src/Mod/PartDesign/Gui/ViewProviderScaled.cpp
- src/Mod/PartDesign/Gui/ViewProviderScaled.h
- src/Mod/PartDesign/Gui/ViewProviderThickness.cpp
- src/Mod/PartDesign/Gui/ViewProviderThickness.h
- src/Mod/PartDesign/Gui/ViewProviderTransformed.cpp
- src/Mod/PartDesign/Gui/ViewProviderTransformed.h
> PD: translation of context-menu item

- package/fedora/freecad.spec
> [COPR] Restore dynamic release numbering

- src/Gui/View3DInventorViewer.cpp
> Gui: do not enable lighting when rendering from image or framebuffer

- src/Mod/TechDraw/App/ShapeExtractor.cpp
- src/Mod/TechDraw/App/ShapeExtractor.h
This PR addresses an issue with the rotation of linked objects in views as reported here: https://forum.freecad.org/viewtopic.php?t=78067&sid=6daac18adce71ac932501d62c84f8d04
---
> [TD]fix rotation of App::Link

- src/Mod/Sketcher/Gui/Resources/icons/elements/Sketcher_Element_Arc_EndPoint.svg
- src/Mod/Sketcher/Gui/Resources/icons/elements/Sketcher_Element_Arc_StartingPoint.svg
> Sketcher: element arc icons have start and end point switched

- src/Mod/Web/Gui/AppWebGui.cpp
- src/Mod/Web/Gui/PreCompiled.h
> fixes #9364: WM_INPUTLANGCHANGEREQUEST seems to freeze FreeCAD

- src/Gui/NaviCube.cpp
This is a follow up to https://github.com/FreeCAD/FreeCAD/pull/9356
Addresses issue in forum thread [https://forum.freecad.org/viewtopic.php?p=678992#p678992](https://forum.freecad.org/viewtopic.php?p=678992#p678992)
Replace glPolygonMode() and GL_POLYGON with GL_LINE_LOOP Replace glDepthRange() with glPolygonOffset()
Some cleanup in configuring openGL
> Compatibility with OpenGL ES

- src/Mod/Fem/femcommands/commands.py
> FEM: Adjust translation context for SolverCalculiX

- src/Mod/TechDraw/Gui/Workbench.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/209
---
> TechDraw: Add missing translation string

- src/Mod/Plot/Plot.py
> Plot: tweak missing matplotlib warning

- package/fedora/freecad.spec
> [COPR] Remove Raytracing

- src/Mod/Draft/draftguitools/gui_selectplane.py
- src/Mod/Draft/draftutils/translate.py
Also tweaked code formatting  
Closes #9406
---
> Draft: Add l10n context for ambiguous string

- src/Mod/AddonManager/AddonManager.ui
- src/Mod/AddonManager/addonmanager_installer_gui.py
- src/Mod/AddonManager/expanded_view.py
Minor issues as identified on CrowdIn by various contributors.
> Addon Manager: Translation issues

- src/Mod/Path/Gui/Resources/panels/PageOpSurfaceEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpWaterlineEdit.ui
- src/Mod/Path/InitGui.py
- src/Mod/Path/Path/Main/Gui/Sanity.py
- src/Mod/Path/Path/Main/Gui/Simulator.py
- src/Mod/Path/Path/Main/Job.py
- src/Mod/Path/Path/Op/Custom.py
- src/Mod/Path/Path/Op/Deburr.py
- src/Mod/Path/Path/Op/Gui/Custom.py
- src/Mod/Path/Path/Op/Surface.py
- src/Mod/Path/Path/Op/Waterline.py
- src/Mod/Path/Path/Post/scripts/KineticNCBeamicon2_post.py
- src/Mod/Path/Path/Post/scripts/centroid_post.py
- src/Mod/Path/Path/Post/scripts/comparams_post.py
- src/Mod/Path/Path/Post/scripts/dxf_post.py
- src/Mod/Path/Path/Post/scripts/dynapath_4060_post.py
- src/Mod/Path/Path/Post/scripts/dynapath_post.py
- src/Mod/Path/Path/Post/scripts/estlcam_post.py
- src/Mod/Path/Path/Post/scripts/fangling_post.py
- src/Mod/Path/Path/Post/scripts/fanuc_post.py
- src/Mod/Path/Path/Post/scripts/jtech_post.py
- src/Mod/Path/Path/Post/scripts/linuxcnc_post.py
- src/Mod/Path/Path/Post/scripts/mach3_mach4_post.py
- src/Mod/Path/Path/Post/scripts/nccad_post.py
- src/Mod/Path/Path/Post/scripts/refactored_centroid_post.py
- src/Mod/Path/Path/Post/scripts/refactored_linuxcnc_post.py
- src/Mod/Path/Path/Post/scripts/refactored_mach3_mach4_post.py
- src/Mod/Path/Path/Post/scripts/refactored_test_post.py
- src/Mod/Path/Path/Post/scripts/smoothie_post.py
- src/Mod/Path/Path/Post/scripts/uccnc_post.py
Mostly as suggested on CrowdIn by David69.
---
> Path: Minor translation cleanup

- src/Tools/updatets.py
The reason Path translations were not getting updated was because one of the files in Path was causing lupdate to hang. As a workaround, this PR adds an "excluded files" list. None of the files in the current list have any translatable strings in them, so this does not affect the UI.
---
> Tools: Add exclusion list to lupdate calls

- src/Mod/Path/Gui/Resources/panels/DlgJobTemplateExport.ui
- src/Mod/Path/Gui/Resources/panels/DressupPathBoundary.ui
- src/Mod/Path/Gui/Resources/panels/PageOpSlotEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpSurfaceEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpWaterlineEdit.ui
- src/Mod/Path/Gui/Resources/panels/PathEdit.ui
- src/Mod/Path/Gui/Resources/preferences/PathJob.ui
- src/Mod/Path/Path/Op/Slot.py
Translators were concerned about the various uses of terms that all meant "Bounding Box" -- this PR standardizes path on that term.
---
> Path: Unify use of 'bounding box' terminology

- src/Mod/Path/Path/Main/Gui/Inspect.py
> Fix #9485: PathInspector broken by #8459

- src/Mod/Path/Gui/Resources/preferences/PathDressupHoldingTags.ui
- src/Mod/Path/Path/Base/SetupSheet.py
- src/Mod/Path/Path/Dressup/DogboneII.py
- src/Mod/Path/Path/Dressup/Gui/Boundary.py
- src/Mod/Path/Path/Dressup/Gui/Dogbone.py
- src/Mod/Path/Path/Main/Gui/Fixture.py
- src/Mod/Path/Path/Main/Gui/JobCmd.py
- src/Mod/Path/Path/Op/Area.py
- src/Mod/Path/Path/Op/Gui/Drilling.py
- src/Mod/Path/Path/Op/Gui/Helix.py
- src/Mod/Path/Path/Op/Gui/Pocket.py
- src/Mod/Path/Path/Op/Vcarve.py
- src/Mod/Path/PathCommands.py
Another round of fixes, most suggested on CrowdIn by david69. A couple of these are just making two strings the same when they were different before: I just picked the one that sounded best to me.
---
> Path: Minor translation fixes part 2

- src/Mod/TechDraw/App/CenterLine.cpp
- src/Mod/TechDraw/App/Geometry.cpp
- src/Mod/TechDraw/App/GeometryMatcher.cpp
- src/Mod/TechDraw/Gui/TaskCenterLine.cpp
- src/Mod/TechDraw/Gui/TaskCenterLine.h
> [TD]fix #9471 - prevent impossible centerline

- src/Gui/ExpressionCompleter.cpp
- src/Gui/ExpressionCompleter.h
Thanks to @acpopescu for the help on this regression
---
> [020] [Expressions] auto-completion fixes

- src/Mod/TechDraw/App/DrawViewImage.cpp
- src/Mod/TechDraw/Gui/CommandDecorate.cpp
This PR adds bmp to the allowable formats for the insert image function. …
> [TD]allow bmp as image format

- src/Gui/ViewProviderImagePlane.cpp
- src/Gui/ViewProviderImagePlane.h
See forum: https://forum.freecad.org/viewtopic.php?p=680800#p680800
---
> Gui: when loading SVG images get default size and keep aspect ratio

- src/Mod/Mesh/InitGui.py
> Mesh: fixes #9447: Rename Mesh Design to Mesh workbench

- src/3rdParty/lazy_loader/CMakeLists.txt
> fixes #9342: Build: 'cmake --install --prefix' no effect to lazy_loader

- src/Mod/PartDesign/Gui/Command.cpp
> fixes #8161: Clones do not copy colour

- src/Mod/Part/Gui/TaskCheckGeometry.cpp
- src/Mod/PartDesign/App/FeatureBoolean.cpp
- src/Mod/PartDesign/App/FeatureChamfer.cpp
- src/Mod/PartDesign/App/FeatureDraft.cpp
- src/Mod/PartDesign/App/FeatureFillet.cpp
- src/Mod/PartDesign/App/FeatureGroove.cpp
- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/App/FeatureLoft.cpp
- src/Mod/PartDesign/App/FeaturePad.cpp
- src/Mod/PartDesign/App/FeaturePipe.cpp
- src/Mod/PartDesign/App/FeaturePocket.cpp
- src/Mod/PartDesign/App/FeaturePrimitive.cpp
- src/Mod/PartDesign/App/FeatureTransformed.cpp
- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandlerCarbonCopy.h
Fixes some inconsistencies identified by translators.
---
> Gui: Minor translation fixes

- src/Gui/DlgSettingsWorkbenchesImp.cpp
Prevents : https://github.com/FreeCAD/FreeCAD/issues/9539
@chennes 
---
> Pref: Wb: prevent duplicate workbenches in the lists.

- src/Mod/Points/App/CMakeLists.txt
- src/Mod/Points/App/Tools.h
- src/Mod/Points/Gui/Command.cpp
> fixes #9134: Points Merge doesn't keep Color information

- src/App/DocumentObject.cpp
- src/App/DocumentObject.h
> App: add method DocumentObject::getFirstParent()

- src/Mod/Draft/importSVG.py
> Draft: Skip SVG import DPI dialog if a unit is specified in the file

- src/Mod/Draft/Resources/ui/TaskPanel_SetStyle.ui
The Annotations button applies to labels as well.
---
> Draft: Draft_SetStyle tooltip tweak

- src/Gui/Language/Translator.cpp
> Gui: check for QApplication instance to avoid crash

- src/Mod/Path/InitGui.py
- src/Mod/Path/Path/Main/Gui/Sanity.py
GuiInit.py fix to make the feature not experimental
Turn off debug logging
---
> Minor bug fixes for path sanity

- src/Mod/Path/PathSimulator/App/PathSim.cpp
- src/Mod/Path/PathSimulator/App/PathSim.h
- src/Mod/Path/PathSimulator/App/PathSimPyImp.cpp
> Path: fixes #9403: Memory leak in Path

- src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
- src/Mod/TechDraw/Gui/DrawGuiUtil.h
This PR implements a solution for issue #9572.
---
> [TD]fix direction precision error #9572

- CONTRIBUTING.md
> Fix typo in Roles

- src/App/CMakeLists.txt
- src/App/StringHasher.cpp
- src/App/StringHasher.h
- src/App/StringHasherPy.xml
- src/App/StringHasherPyImp.cpp
- src/App/StringIDPy.xml
- src/App/StringIDPyImp.cpp
- src/Base/Bitmask.h
- src/Base/Reader.cpp
- src/Base/Reader.h
- src/Base/Writer.cpp
- src/Base/Writer.h
- tests/CMakeLists.txt
- tests/src/App/CMakeLists.txt
- tests/src/App/StringHasher.cpp
- tests/src/Base/Bitmask.cpp
- tests/src/Base/CMakeLists.txt
- tests/src/Base/Reader.cpp
- tests/src/Base/Writer.cpp
This PR will close #9127 -- it is mostly focused on StringHasher, but to pull that code into master it also requires some modifications to Reader, XMLWriter, and Bitmask.
I've marked this as ready for review: there are still a few missing tests related to serialization, but we can consider merging it without those in the interest of getting the other cards moving.
---
> App/Toponaming: String hasher

- src/Mod/Fem/Gui/TaskFemConstraintTemperature.cpp
I just run across this one while compiling master.
> Fem: Remove Unused variable

- src/Mod/Spreadsheet/App/Sheet.cpp
https://forum.freecad.org/viewtopic.php?t=77448
> Sheet: display an error in console when a cyclic dependency is detected

- src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
- src/Mod/Sketcher/Gui/TaskSketcherElements.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/219
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/218
> Sketcher: Translate context menu

- src/Mod/Draft/draftguitools/gui_move.py
> Draft: Draft_Move continue mode failed with numeric input

- src/Mod/AddonManager/compact_view.py
> Addon Manager: Fix typo

- src/Gui/Splashscreen.cpp
Fixes https://github.com/FreeCAD/FreeCAD/issues/9481
---
> Gui: Mac version info hack

- src/Mod/AddonManager/AddonManagerOptions.ui
- src/Mod/AddonManager/developer_mode_add_content.ui
> Addon Manager: Minor linguistic fixes

- src/Mod/TechDraw/App/ShapeExtractor.cpp
- src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
This PR implements a fix for issue #9598.
---
> [TD]fix chain dims fail on bad selection (#9598)

- src/Mod/AddonManager/AddonManagerTest/app/test_metadata.py
- src/Mod/AddonManager/addonmanager_metadata.py
Fixes bug reported in https://forum.freecad.org/viewtopic.php?p=682952#p682952
---
> Addon Manager: Improve error handling for Version

- src/Mod/Path/Gui/Resources/panels/DlgJobTemplateExport.ui
- src/Mod/Path/Gui/Resources/panels/PageOpSurfaceEdit.ui
- src/Mod/Path/Gui/Resources/panels/PageOpVcarveEdit.ui
- src/Mod/Path/Gui/Resources/panels/PathEdit.ui
- src/Mod/Path/Gui/Resources/panels/SetupGlobal.ui
- src/Mod/Path/Path/Base/Util.py
- src/Mod/Path/Path/Main/Gui/Sanity.py
I missed a few HTML strings last time. Also fixes a few minor string issues identified on CrowdIn.
> Path: Remove HTML where not needed

- src/Mod/OpenSCAD/OpenSCADCommands.py
> OpenSCAD: Hull/Minkowski also work for a single selected object

- src/Mod/Arch/ArchComponent.py
Fixes https://github.com/yorikvanhavre/BIM_Workbench/issues/110
> Arch: Minor fix to IFC exporter

- src/Mod/MeshPart/Gui/Command.cpp
> MeshPart: Allow to cancel trim by plane

- src/Doc/CONTRIBUTORS
As per [§4.3 of the contibution guideline](https://github.com/FreeCAD/FreeCAD/blob/12c20003b3421aa02d6de47b34c673f73cb03cbd/CONTRIBUTING.md#4-licensing-ownership-and-credit) I'd like to identify myself to the list of contributors.
For Reference:
* [my commits](https://github.com/FreeCAD/FreeCAD/commits?author=jbaehr)
---- …
> Doc: Add myself to CONTRIBUTORS

- src/Mod/TechDraw/Gui/TaskBalloon.cpp
- src/Mod/TechDraw/Gui/TaskBalloon.h
- src/Mod/TechDraw/Gui/ViewProviderBalloon.cpp
- src/Mod/TechDraw/Gui/ViewProviderBalloon.h
This PR implements a fix for issue #9626.
---
> [TD]handle object deletion during task dialog (#9626)

- src/Gui/Notifications.h
- src/Mod/Sketcher/Gui/Command.cpp
- src/Mod/Sketcher/Gui/CommandAlterGeometry.cpp
- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
- src/Mod/Sketcher/Gui/CommandSketcherVirtualSpace.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandlerFillet.h
- src/Mod/Sketcher/Gui/EditDatumDialog.cpp
- src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
- src/Mod/Sketcher/Gui/TaskSketcherValidation.cpp
==========================================================
This commit turns the remaining blocking pop-ups in which the user can only click "ok" into non-intrusive notifications, depending on the user preferences in settings.
> Sketcher: Obey non-intrusive preferences for modal pop-ups

- src/Mod/Draft/draftguitools/gui_beziers.py
While the command is active set EnableSelection to False to correctly detect mouse up events.
Fixes #6452.
---
> Draft: Draft_CubicBezCurve: set EnableSelection to False, fixes #6452

- src/Gui/Widgets.cpp
As discussed in https://github.com/FreeCAD/FreeCAD-translations/issues/184
---
> Gui: Don't show raw exception to user

- package/fedora/freecad.spec
> [COPR] Add BuildRequires:  qqc2-desktop-style

- src/Mod/Path/Path/Main/Gui/Sanity.py
Minor issue with PathSanity file size display
---
> fix label and file size

- src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerBSplineByInterpolation.h
As suggested by [Asier Sarasua (asiersarasua)](https://crowdin.com/profile/asiersarasua) on CrowdIn.
> Sketcher: 'B-spline' consistency

- src/Mod/TechDraw/Gui/QGSPage.cpp
This PR implements a fix for a problem with template fields on Svg exports reported here: https://forum.freecad.org/viewtopic.php?p=684285#p684285
---
> [TD]fix Svg export of template fields

- src/Mod/Draft/draftfunctions/svg.py
This would f.e. result in filled open arcs.
Forum topic:
https://forum.freecad.org/viewtopic.php?p=684721#p684571
---
> Draft: get_svg: loose edges in obj with faces also received a fill

- src/Mod/Arch/ArchBuildingPart.py
- src/Mod/Arch/ArchEquipment.py
- src/Mod/Arch/ArchProfile.py
- src/Mod/Arch/ArchSite.py
- src/Mod/Arch/ArchStairs.py
- src/Mod/Arch/ArchStructure.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/221
> Arch: removed 'object' from command tooltips

- src/Base/Console.h
- src/Base/Interpreter.cpp
- src/Gui/CommandT.h
Various minor improvement/fixes to avoid developer information to be shown to regular users (unless they have opted-in for it).
> Error reporting improvements

- conda/environment.devenv.yml
fix 
[CVE-2023-0465](https://www.cve.org/CVERecord?id=CVE-2023-0465)
[CVE-2023-1255](https://www.cve.org/CVERecord?id=CVE-2023-1255)
[CVE-2023-0464](https://www.cve.org/CVERecord?id=CVE-2023-0464)
---
> fix library vulnerability

- src/Gui/PreferencePackTemplates/Path_Colors.cfg
- src/Gui/PreferencePacks/FreeCAD Classic Colors/FreeCAD Classic Colors.cfg
- src/Mod/Path/Gui/DlgSettingsPathColor.cpp
Fixes compilation problem introduced by #9677
---
> Path: Remove DefaultExtentsColor

- src/Mod/TechDraw/Gui/Workbench.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/241
> TechDraw: Translate Stacking

- src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/240
> TechDraw: Translate some window titles

- src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
Fixes a number of translation issues.
> TechDraw: Translate more window titles

- src/Mod/Draft/draftguitools/gui_snapper.py
Fixes a regression introduced in V0.21
Forum topic:
https://forum.freecad.org/viewtopic.php?t=78771
---
> Draft: fix near snap for meshes

- src/Mod/Sketcher/Gui/Workbench.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/242
> Sketcher: Add missing translations

- src/Mod/Fem/Gui/Workbench.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/232
> FEM: Add translation for Electromagnetic Constraints

- src/Mod/Sketcher/Gui/Command.cpp
> Sketcher: Minor improvements to some GUI texts

- src/Mod/Sketcher/Gui/Workbench.cpp
- [ x ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
---
reported at …
> [Sketcher] Fix incorrect toolbar name uppercase

- src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfHyperbola.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfParabola.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerBSpline.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerBSplineByInterpolation.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerCarbonCopy.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerExtend.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerExternal.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerLineSet.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerSplitting.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerTrimming.h
- src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp
> Sketcher: unused variable fixes

- src/Mod/Fem/Gui/Resources/icons/FEM_ClippingPlaneAdd.svg
SVG was incorrectly edited in a previous commit.   
Fixes #9550
---
> Fix FEM_ClippingPlaneAdd.svg (#9550)

- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
Menu texts for new B-spline tools were inconsistent.
See https://forum.freecad.org/viewtopic.php?t=78808
---
> Sketcher: Minor improvements for some GUI texts

- .gitignore
- .vscode/.gitignore
---
fix wrong gitignore path for auto generated file from conda devenv
> Update .gitignore files (vscode + conda integration)

- src/App/CMakeLists.txt
- src/App/ComplexGeoData.cpp
- src/App/ComplexGeoData.h
- src/App/DocumentObject.cpp
- src/App/DocumentObserver.cpp
- src/App/ElementMap.cpp
- src/App/ElementMap.h
- src/App/ElementNamingUtils.cpp
- src/App/ElementNamingUtils.h
- src/App/GeoFeature.cpp
- src/App/Link.cpp
- src/App/MappedName.cpp
- src/App/MappedName.h
- src/App/PostfixStringReferences.h
- src/Base/Writer.h
- src/Gui/CommandLink.cpp
- src/Gui/Document.cpp
- src/Gui/SoFCUnifiedSelection.cpp
- src/Gui/TaskElementColors.cpp
- src/Gui/ViewProviderLink.cpp
- src/Mod/Part/App/AppPartPy.cpp
- src/Mod/Part/App/PartFeature.cpp
- src/Mod/Part/App/TopoShape.cpp
- src/Mod/PartDesign/App/Feature.cpp
- src/Mod/PartDesign/App/ShapeBinder.cpp
- tests/src/App/ElementMap.cpp
- tests/src/App/MappedName.cpp
> [Toponaming] create ElementMap class

- src/Gui/NaviCube.cpp
https://forum.freecad.org/viewtopic.php?t=79030
> Navicube: Fix rotation direction on north and south buttons

- src/App/ElementMap.cpp
- src/App/ElementMap.h
- src/App/ElementNamingUtils.cpp
- src/App/ElementNamingUtils.h
- src/App/MappedName.cpp
Windows clean rebuild errors. Also fixes some trailing whitespace issues
> App/Toponaming: Compilation cleanup after #9175

- src/Mod/TechDraw/Gui/MDIViewPage.cpp
More details can be found under: https://www.kdab.com/creating-pdfa-documents-qt/
---
> Update printAllPDF to print a PDF that complies with PDF/A-1b

- src/Mod/Start/StartPage/StartPage.css
- src/Mod/Start/StartPage/StartPage.html
---
This is what it looks like:
> Added freecad blog tab to start page

- src/Mod/Arch/exportIFC.py
- src/Mod/Arch/ifc_viewproviders.py
- src/Mod/Draft/draftutils/gui_utils.py
A couple of minor adjustments to support future development of the NativeIFC addon
---
---
> Arch nativeifc provisions

- src/Mod/Path/Path/Post/scripts/heidenhain_post.py
This patch was submitted via email with very little context.  This is not my code and I have not tested it thoroughly. 
I believe the patch is valid and would like feedback before merging
---
> fix submitted by Zibibbo84 for proxy error

- .github/workflows/sub_buildWindows.yml
microsoft/setup-msbuild from 1.1 to 1.3
---
> Update microsoft / setup-msbuild into sub_buildWindows.yml

- src/Mod/Path/PathScripts/PathUtils.py
> Path: fix typo in source comments

- src/Gui/Action.cpp
> Fix #9775 - incorrect pref. path on hint

- src/Mod/Arch/import3DS.py
- src/Mod/Arch/importDAE.py
- src/Mod/Arch/importOBJ.py
- src/Mod/Arch/importSH3D.py
Forum topic:
https://forum.freecad.org/viewtopic.php?t=79276
---
> Arch: Fix encoding error (caused by #9316)

- src/Gui/MainWindow.cpp
- src/Mod/Sketcher/Gui/Workbench.cpp
==================================================
As described here:
https://forum.freecad.org/viewtopic.php?p=687188#p687188
---
> MainWindow: Fix for Automatic WB and edit mode WBs

- src/Mod/TechDraw/Gui/CommandExtensionDims.cpp
- src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
This PR addresses some translation issues reported here: https://github.com/FreeCAD/FreeCAD-translations/issues/240 and here: https://github.com/FreeCAD/FreeCAD-translations/issues/239
---
> [TD]fix missing translations

- src/App/MappedName.cpp
- src/Gui/SoFCUnifiedSelection.cpp
- src/Mod/Fem/App/FemVTKTools.cpp
- src/Mod/Fem/femcommands/manager.py
- src/Mod/PartDesign/TestPartDesignGui.py
- src/Mod/Path/Path/Op/Pocket.py
- src/Mod/Path/Path/Post/scripts/uccnc_post.py
Various source comment typos
---
> Fix various typos

- src/XDGData/org.freecadweb.FreeCAD.desktop
Patch from Tobias Frost <tobi@debian.org>.
Solves Debian bug <URL: https://bugs.debian.org/993089 >.
Been used in the Debian edition of FreeCAD since 2022.
> Add several supported MIME types to desktop file.

- src/Mod/Path/Path/Post/Command.py
While working on https://github.com/FreeCAD/FreeCAD/pull/9867 I noticed my patch showed up with a lot of linting issues in code I did not touch, to a point where the view was very cluttered by lintian issues.  Here is my try to reduce the number of issues discovered by the linter.  Some issues are left, as I fail to see how to sensibly reduce the number of parameters or local variable used.
> Get rid of some lintian complaints from github Python linter.

- src/Mod/TechDraw/App/CenterLine.cpp
- src/Mod/TechDraw/Gui/TaskCenterLine.cpp
- src/Mod/TechDraw/Gui/TaskCenterLine.h
This PR addresses an issue with centerline between points reported here: https://forum.freecad.org/viewtopic.php?p=691722#p691722 …
> [TD]fix pathological centerline for points

- src/Mod/Path/Path/Post/Command.py
While working on https://github.com/FreeCAD/FreeCAD/pull/9867 I noticed my patch showed up with a lot of linting issues in code I did not touch, to a point where the view was very cluttered by lintian issues.  Here is my second try to reduce the number of issues discovered by the linter.  Some issues are still left, as I fail to see how to sensibly reduce the number of parameters or local variable used.
> Get rid of more lintian complaints from github Python linter.

- src/Mod/Fem/Gui/Workbench.cpp
> FEM: Add missing translation string

- src/Mod/Arch/ArchWindowPresets.py
Fixes yorikvanhavre/BIM_Workbench#116
---
> Arch: Fixed error on null window preset creation parameters

- src/Base/CoordinateSystem.cpp
> Base: fix bug in CoordinateSystem::setYDirection

- src/Mod/TechDraw/Gui/MDIViewPage.cpp
- src/Mod/TechDraw/Gui/QGIRichAnno.cpp
- src/Mod/TechDraw/Gui/QGIRichAnno.h
- src/Mod/TechDraw/Gui/QGSPage.cpp
- src/Mod/TechDraw/Gui/QGSPage.h
- src/Mod/TechDraw/Gui/QGVPage.h
This PR implements a fix for issue #9908.
---
> [TD]fix rich text font size in pdf - fix 9908

- src/Mod/Part/CMakeLists.txt
- src/Mod/Part/TestPartGui.py
- src/Mod/Part/parttests/ColorPerFaceTest.py
> Part: add a unit test for PR #9905

- package/fedora/freecad.spec
> [COPR] Add flatmesh to plugins

- src/App/ComplexGeoData.cpp
- src/App/ComplexGeoData.h
- src/App/ElementMap.cpp
- src/App/ElementMap.h
- src/App/MappedElement.h
- src/App/MappedName.h
- src/App/StringHasher.h
- src/Mod/PartDesign/Gui/PreCompiled.h
- tests/src/App/CMakeLists.txt
- tests/src/App/ComplexGeoData.cpp
- tests/src/App/ElementMap.cpp
- tests/src/App/MappedName.cpp
Closes https://github.com/FreeCAD/FreeCAD/issues/9116
> Toponaming: ComplexGeoData dressing

- src/App/MappedName.cpp
- src/App/MappedName.h
- tests/src/App/MappedName.cpp
Also apply clang-tidy to that function, and fix an error with the postfix return.
> App/Toponaming: Add tests for findTagInElementName

- src/Mod/Part/Gui/DlgImportStep.ui
> [Part] Make tooltip match label

- src/Mod/Draft/draftfunctions/downgrade.py
> Draft: Improve downgrading of PD bodies

- src/Mod/Show/mTempoVis.py
- src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h
- src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp
Fix some bugs in Sketcher backside edit
* 1st commit: bug in section view not correctly changing side. Was here since feature introduction
* 2nd commit: bug in vertex selection from backside. Was introduced by a6adfc5 (@abdullahtahiriyo , not a reproach, just you know next time :smile: )
* 3rd commit: improvement coping with specific cases where cross section may be not correctly behaving
https://forum.freecad.org/viewtopic.php?p=688843#p688843
> Sketcher: bugfixes and improvements in backside edit and section view

- cMake/FreeCAD_Helpers/SetupQt.cmake
- cMake/FreeCAD_Helpers/SetupShibokenAndPyside.cmake
- src/FCConfig.h
- src/Gui/DlgMacroExecuteImp.cpp
- src/Gui/DlgPreferencesImp.cpp
- src/Gui/MainWindow.cpp
- src/Gui/ProgressBar.cpp
- src/Gui/ProgressDialog.cpp
- src/Gui/QSint/actionpanel/actionbox.cpp
- src/Gui/QSint/actionpanel/actionpanel.cpp
- src/Gui/Quarter/ContextMenu.cpp
- src/Gui/Quarter/EventFilter.cpp
- src/Gui/Quarter/QuarterWidget.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
> [v0.21] Qt6: Fix build issues

- src/Mod/Draft/WorkingPlane.py
> Draft: Auto workingplane ignored rotation around axis

- src/Mod/Sketcher/App/GeoEnum.h
- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
- tests/CMakeLists.txt
- tests/src/Mod/Sketcher/App/CMakeLists.txt
- tests/src/Mod/Sketcher/App/SketchObject.cpp
> [Sketcher][Part] SketchObject Dressing for TopoNaming

- src/App/Document.cpp
- src/Gui/DlgSettingsDocument.ui
> [Core] Fix ordering confusion in backups

- src/App/Document.cpp
> App: fix removing object while recomputing

- src/Mod/TechDraw/Gui/QGIFace.cpp
- src/Mod/TechDraw/Gui/QGIFace.h
This PR implements a fix for issue #9976 
---
> [TD]fix face colour preference ignored issue #9976

- src/Mod/Spreadsheet/App/Cell.cpp
- src/Mod/Spreadsheet/TestSpreadsheet.py
See also https://forum.freecad.org/viewtopic.php?t=78204
> Spreadsheet: fix string save/restore, fixes #6395

- src/Mod/Draft/CMakeLists.txt
- src/Mod/Draft/TestDraft.py
- src/Mod/Draft/drafttests/test_array.py
> Draft: add unit test for issue #9912

- src/Mod/PartDesign/App/FeatureBase.cpp
- src/Mod/PartDesign/App/FeatureBase.h
If the BaseFeature link of the Body of a Clone feature isn't set then do not update it. Forum thread: https://forum.freecad.org/viewtopic.php?p=675644#p675644
---
> PD: fix out of scope warnings of Clone feature

- src/Base/MatrixPyImp.cpp
> Base: Fix warnings -Wredundant-move

- src/App/DocumentObjectPy.xml
- src/App/DocumentObjectPyImp.cpp
- src/Base/Tools.cpp
- src/Base/Tools.h
- src/Mod/Part/BOPTools/BOPFeatures.py
- src/Mod/Part/CMakeLists.txt
- src/Mod/Part/Gui/Command.cpp
- src/Mod/Part/Gui/DlgBooleanOperation.cpp
- src/Mod/Part/TestPartApp.py
- tests/src/Base/tst_Tools.cpp
>  Part: fixes #9549: Part Fuse not working inside Part container 

- src/Mod/TechDraw/Gui/QGIFace.cpp
- src/Mod/TechDraw/Gui/QGIFace.h
This PR addresses an issue with slow updates reported here: https://forum.freecad.org/viewtopic.php?p=694424#p694424 …
> [TD]use shared renderer for svg tiles

- src/Gui/Application.cpp
> Gui: also print category string of Qt messages

- src/Mod/Start/StartPage/StartPage.py
> fix encoding on StartPage file information

- src/Gui/CommandStd.cpp
- src/Gui/Workbench.cpp
Solve https://github.com/FreeCAD/FreeCAD/issues/10001
---
> Move 'Recent Files' menu entry and rename it 'Open Recent'

- src/Gui/Application.cpp
This will also be back ported to the 0.21 branch for inclusion in the 0.21.0 release.
> Gui: Clarify message about FCbak

- src/Gui/Application.cpp
> Backport of FCBak message cleanup

- src/Gui/PythonWrapper.cpp
- src/Gui/PythonWrapper.h
- src/Gui/View3DViewerPy.cpp
- src/Gui/View3DViewerPy.h
> Expose getFramebuffer() to Python

- src/Tools/macos_sign_and_notarize.sh
This is the beginnings of a script that does the Mac OS signing and notarization. Plenty of room for improvement as scripts go, but this is what I did to sign the 0.21 release.
> Tools: Add script to sign and notarize on Mac OS

- .clang-format
This was proposed quite some time ago and I recall enjoyed strong support, except one squeaky wheel.
This is a new attempt to install IMHO a very worthwile setting.
---
> clang format InsertBraces true

- src/App/Document.cpp
> Core: report the real error of a failed feature after a recompute

- src/Gui/SoFCOffscreenRenderer.cpp
- src/Gui/View3DInventorViewer.cpp
- src/Mod/Sketcher/Gui/EditModeConstraintCoinManager.cpp
> removed coin<3 references

- src/Gui/Quarter/CMakeLists.txt
> remove qt4 unused wrap

- .github/ISSUE_TEMPLATE/PROBLEM_REPORT.yml
> Remove the version select data item from the github issue template

- src/App/ElementMap.h
- src/App/StringHasherPyImp.cpp
- src/Base/Parameter.cpp
- src/Base/Parameter.h
- src/Gui/Tree.h
- src/Gui/UiLoader.h
- src/Gui/ViewProviderLink.cpp
- src/Mod/Import/App/dxf/dxf.cpp
- src/Mod/Sketcher/App/SketchObjectPyImp.cpp
- src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp
- src/Mod/Surface/Gui/Command.cpp
- src/Tools/generateTemplates/templateClassPyExport.py
> modernize C++: use nullptr

- SECURITY.md
Bump the version numbers now that 0.21 is the official release version
> Update SECURITY.md to v0.21

- src/Gui/ApplicationPy.cpp
- src/Gui/EditorView.cpp
- src/Gui/MDIView.cpp
- src/Gui/View3DInventor.cpp
- src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.cpp
for more details about this look at: https://www.kdab.com/creating-pdfa-documents-qt/
this dous the same as Pull-Request: #9779
---
> added PDF/A-1b compliancy to all PDF export functions

- src/App/DocumentPyImp.cpp
- src/App/Expression.cpp
- src/Gui/ExpressionCompleter.cpp
- src/Gui/Selection.cpp
- src/Gui/Tree.cpp
- src/Gui/View3DSettings.cpp
- src/Gui/ViewProviderLink.cpp
- src/Gui/WidgetFactory.cpp
- src/Mod/Fem/Gui/TaskFemConstraintHeatflux.cpp
- src/Mod/Fem/Gui/TaskFemConstraintTemperature.cpp
- src/Mod/Fem/Gui/TaskFemConstraintTransform.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- src/Mod/Import/App/ExportOCAF.cpp
- src/Mod/Import/App/ImportOCAF2.cpp
- src/Mod/MeshPart/App/MeshFlatteningLscmRelax.cpp
- src/Mod/Part/App/Geometry.cpp
- src/Mod/PartDesign/App/FeatureExtrude.cpp
- src/Mod/PartDesign/App/FeatureHelix.cpp
- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/Gui/Utils.cpp
- src/Mod/Path/App/Area.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/Gui/QGIViewPart.cpp
- src/Mod/TechDraw/Gui/QGVPage.cpp
- src/Mod/TechDraw/Gui/TaskLineDecor.cpp
> modernize C++: use bool literals

- src/App/DocumentObserverPython.h
- src/App/ElementMap.h
- src/Base/Writer.cpp
- src/Gui/DocumentObserverPython.h
- src/Gui/Quarter/SoQTQuarterAdaptor.h
- src/Gui/SoFCSelectionContext.h
- src/Gui/SoFCUnifiedSelection.cpp
- src/Mod/PartDesign/App/FeatureHole.h
> modernize C++: use using

- src/Mod/Fem/Gui/DlgSettingsFemGeneralImp.cpp
- src/Mod/MeshPart/App/MeshFlatteningLscmRelax.cpp
- src/Mod/MeshPart/App/MeshFlatteningNurbs.cpp
- src/Mod/Part/App/PropertyTopoShapeList.cpp
> modernize C++: use emplace

- src/App/ElementMap.h
- src/Gui/ShortcutManager.cpp
- src/Mod/Mesh/App/Core/Builder.cpp
- src/Mod/Mesh/App/Core/Degeneration.cpp
- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
- src/Mod/Spreadsheet/Gui/SheetTableView.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
> modernize C++: use transparent functors

- src/App/Document.cpp
- src/App/PropertyExpressionEngine.cpp
- src/App/PropertyPythonObject.cpp
- src/Gui/CallTips.cpp
- src/Gui/CommandStd.cpp
- src/Gui/DlgCreateNewPreferencePackImp.cpp
- src/Gui/DlgSettingsImageImp.cpp
- src/Gui/FileDialog.cpp
- src/Gui/MDIView.cpp
- src/Gui/Placement.cpp
- src/Gui/SelectionView.cpp
- src/Gui/SoFCDB.cpp
- src/Gui/SoFCVectorizeSVGAction.cpp
- src/Gui/Splashscreen.cpp
- src/Mod/Mesh/App/Core/IO/ReaderOBJ.cpp
- src/Mod/Mesh/App/Core/MeshIO.cpp
- src/Mod/Part/Gui/Command.cpp
- src/Mod/Part/Gui/Mirroring.cpp
- src/Mod/PartDesign/Gui/TaskSketchBasedParameters.cpp
- src/Mod/ReverseEngineering/Gui/FitBSplineSurface.cpp
- src/Mod/Spreadsheet/App/PropertySheet.cpp
> modernize C++: raw string literal

- src/App/Document.cpp
- src/App/Expression.cpp
- src/App/PropertyExpressionEngine.cpp
- src/App/PropertyLinks.cpp
- src/Base/Parameter.cpp
- src/Base/ProgressIndicatorPy.cpp
- src/Gui/Action.cpp
- src/Gui/Command.cpp
- src/Gui/CommandView.cpp
- src/Gui/Tree.cpp
- src/Gui/ViewProviderLink.cpp
- src/Gui/ViewProviderPlacement.cpp
- src/Mod/Mesh/App/AppMeshPy.cpp
- src/Mod/Mesh/App/Exporter.cpp
- src/Mod/Mesh/App/Mesh.cpp
- src/Mod/Mesh/App/MeshPyImp.cpp
- src/Mod/Mesh/App/MeshTexture.cpp
- src/Mod/Part/App/BSplineCurvePyImp.cpp
- src/Mod/Part/App/FaceMakerBullseye.cpp
- src/Mod/Part/App/Geom2d/BSplineCurve2dPyImp.cpp
- src/Mod/Part/App/GeomPlate/CurveConstraintPyImp.cpp
- src/Mod/Part/App/GeomPlate/PointConstraintPyImp.cpp
- src/Mod/Part/App/Geometry.cpp
- src/Mod/Part/App/Geometry2d.cpp
- src/Mod/Part/Gui/SoBrepFaceSet.cpp
- src/Mod/Path/App/Area.cpp
- src/Mod/Points/App/AppPointsPy.cpp
- src/Mod/Robot/App/Trajectory.cpp
- src/Mod/Spreadsheet/App/Cell.cpp
- src/Mod/Spreadsheet/App/Sheet.cpp
> modernize C++: make unique

- src/Mod/Import/App/SCL/Part21.py
- src/Mod/Import/App/SCL/SimpleReader.py
> Import: Avoid dictionary.keys() where possible

- src/Mod/Drawing/DrawingPatterns.py
> Drawing: Avoid dictionary.keys() where possible

- src/Gui/PreferencePages/DlgSettingsTheme.ui
Remove some junk from DlgSettingsTheme.ui file. Mentioned by @benj5378 in #10015 
---
> Preference Page Theme : remove junk from .ui file.

- src/Gui/PreferencePages/DlgSettingsViewColor.ui
> fixes #10105: Tabstop assignment compilation warning

- tests/src/Base/Reader.cpp
> MSVC: fix build failure caused by PR #10138

- src/Tools/generateBase/generateDS.py
- src/Tools/updatecrowdin.py
> Tools: Avoid dictionary.keys() where possible

- src/Mod/PartDesign/FeatureHole/Standards.py
- src/Mod/PartDesign/SprocketFeature.py
- src/Mod/PartDesign/WizardShaft/SegmentFunction.py
- src/Mod/PartDesign/WizardShaft/WizardShaftTable.py
> PartDesign: Avoid dictionary.keys() where possible

- src/Mod/Material/MaterialEditor.py
- src/Mod/Material/importFCMat.py
- src/Mod/Material/materialtools/cardutils.py
> Material: Avoid dictionary.keys() where possible

- tests/src/Base/Reader.cpp
> gcc: support to build with v7.5

- src/Gui/PreferencePages/DlgSettingsViewColor.ui
> Gui: fix another tabstop compilation warning

- src/App/AutoTransaction.h
- src/App/DocumentObserver.h
- src/App/Property.h
- src/App/PropertyContainer.h
- src/Base/Builder3D.h
- src/Base/Handle.cpp
- src/Base/Handle.h
- src/Base/InputSource.cpp
- src/Base/InputSource.h
- src/Base/Parameter.cpp
- src/Base/Sequencer.h
- src/Base/Stream.h
- src/Base/Writer.h
- src/Gui/DocumentObserver.h
- src/Gui/NavigationStyle.h
- src/Gui/NotificationBox.h
- src/Gui/SoFCOffscreenRenderer.h
- src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp
- src/Mod/Mesh/App/Core/Info.h
- src/Mod/Mesh/App/Core/Iterator.h
- src/Mod/Mesh/App/Core/KDTree.h
- src/Mod/Mesh/App/Core/Tools.h
- src/Mod/Mesh/Gui/SoFCMeshObject.h
- src/Mod/Part/App/Geometry.h
- src/Mod/Part/App/Geometry2d.h
- src/Mod/Points/App/PointsAlgos.cpp
> modernize C++: use equals delete

- src/Mod/Test/Gui/UnitTestImp.cpp
> Test: avoid to expand test dialog if label text is too long

- src/Base/PrecisionPyImp.cpp
> Base: Explicitly avoid parameters in PrecisionPy methods

- src/Mod/Drawing/Gui/Command.cpp
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/263
> Gui: Translate 'page' for new pages

- src/Mod/Draft/draftfunctions/move.py
- src/Mod/Draft/draftfunctions/rotate.py
- src/Mod/Draft/draftguitools/gui_annotationstyleeditor.py
- src/Mod/Draft/draftguitools/gui_edit.py
- src/Mod/Draft/draftguitools/gui_setstyle.py
- src/Mod/Draft/draftviewproviders/view_base.py
> Draft: Avoid dictionary.keys() where possible

- src/Mod/Arch/ArchCommands.py
- src/Mod/Arch/ArchComponent.py
- src/Mod/Arch/ArchIFC.py
- src/Mod/Arch/ArchIFCView.py
- src/Mod/Arch/ArchMaterial.py
- src/Mod/Arch/ArchReference.py
- src/Mod/Arch/exportIFC.py
- src/Mod/Arch/importDAE.py
- src/Mod/Arch/importIFC.py
- src/Mod/Arch/importIFCHelper.py
- src/Mod/Arch/importIFClegacy.py
- src/Mod/Arch/importSH3D.py
> Arch: Avoid dictionary.keys() where possible

- tests/CMakeLists.txt
This is a back port of PR #10169
---
> Fix build of "tests" on macOS for v0.21

- src/App/Application.cpp
- src/App/ApplicationPy.cpp
- src/App/ComplexGeoDataPyImp.cpp
- src/App/Document.cpp
- src/App/DocumentObjectPyImp.cpp
- src/App/DocumentPyImp.cpp
- src/App/Enumeration.cpp
- src/App/Expression.cpp
- src/App/Graphviz.cpp
- src/App/GroupExtension.cpp
- src/App/Link.cpp
- src/App/LinkBaseExtensionPyImp.cpp
- src/App/ObjectIdentifier.cpp
- src/App/PropertyContainer.cpp
- src/App/PropertyContainerPyImp.cpp
- src/App/PropertyExpressionEngine.cpp
- src/App/PropertyGeo.cpp
- src/App/PropertyLinks.cpp
- src/App/PropertyPythonObject.cpp
- src/App/PropertyStandard.cpp
- src/App/Transactions.cpp
- src/App/VRMLObject.cpp
Replaces old-style for loops with the more efficient range-based for loops. This PR affects the code in App.
> App: modernize C++: use range-based for loop

- src/Mod/Inspection/App/InspectionFeature.cpp
- src/Mod/Inspection/App/PreCompiled.h
- src/Mod/Inspection/Gui/ViewProviderInspection.cpp
- src/Mod/Inspection/Gui/VisualInspection.cpp
Replaces old-style for loops with the more efficient range-based for loops. This PR affects the code in the Inspection module.
> Inspection: modernize C++: use range-based for loop

- src/Mod/Start/Gui/DlgStartPreferencesImp.cpp
- src/Mod/Start/Gui/Workbench.cpp
- src/Mod/Web/Gui/CookieJar.cpp
Replaces old-style for loops with the more efficient range-based for loops. This PR affects the code in the Web/Start module.
> Web: modernize C++: use range-based for loop

- src/Mod/Points/App/Points.cpp
- src/Mod/Points/App/PointsAlgos.cpp
- src/Mod/Points/App/PointsGrid.cpp
- src/Mod/Points/App/PointsPyImp.cpp
- src/Mod/Points/App/Properties.cpp
- src/Mod/Points/Gui/Command.cpp
- src/Mod/Points/Gui/ViewProvider.cpp
- src/Mod/ReverseEngineering/App/AppReverseEngineering.cpp
- src/Mod/ReverseEngineering/App/ApproxSurface.cpp
- src/Mod/ReverseEngineering/Gui/Command.cpp
- src/Mod/ReverseEngineering/Gui/Segmentation.cpp
- src/Mod/Surface/App/FeatureGeomFillSurface.cpp
- src/Mod/Surface/App/FeatureSewing.cpp
Replaces old-style for loops with the more efficient range-based for loops. This PR affects the code in the Points, Reverse Engineering and Surface modules.
> Points modernize use range based for loop

- src/Mod/Robot/App/Edge2TracObject.cpp
- src/Mod/Robot/App/Robot6Axis.cpp
- src/Mod/Robot/App/Trajectory.cpp
- src/Mod/Robot/App/TrajectoryCompound.cpp
- src/Mod/Robot/App/TrajectoryDressUpObject.cpp
Replaces old-style for loops with the more efficient range-based for loops. This PR affects the code in the Robot module.
> Robot: modernize C++: use range-based for loop

- src/Mod/Spreadsheet/App/PropertySheet.cpp
- src/Mod/Spreadsheet/App/Sheet.cpp
- src/Mod/Spreadsheet/App/SheetPyImp.cpp
- src/Mod/Spreadsheet/Gui/Command.cpp
- src/Mod/Spreadsheet/Gui/SheetModel.cpp
- src/Mod/Spreadsheet/Gui/SheetTableView.cpp
Replaces old-style for loops with the more efficient range-based for loops. This PR affects the code in the Spreadsheet module.
> Sheet: modernize C++: use range-based for loop

- src/Gui/Application.cpp
- src/Gui/CMakeLists.txt
- src/Gui/Selection.cpp
- src/Gui/SelectionFilter.cpp
- src/Gui/SelectionFilter.h
- src/Gui/SelectionFilterPy.cpp
- src/Gui/SelectionFilterPy.h
Move class to its own files.
Add `SelectionFilterPy::getFilter` method.
Change class name from `SelectionFilter` to `Gui.SelectionFilter`.
Use range-based loop in `SelectionFilterPy::result`
> Gui: Change SelectionFilterPy to new PyCXX extension type

- src/Gui/PreferencePages/DlgSettings3DView.ui
> [Preferences] Fix #9206 - Sketcher Marker Size setting is misplaced

- src/Mod/Path/CMakeLists.txt
> Path: add estlcam_post.py to CMakeList.txt

- src/Mod/PartDesign/App/Body.cpp
- src/Mod/PartDesign/App/FeatureExtrude.cpp
- src/Mod/PartDesign/App/FeatureFillet.cpp
- src/Mod/PartDesign/App/FeatureHole.cpp
- src/Mod/PartDesign/App/FeatureMultiTransform.cpp
- src/Mod/PartDesign/App/FeaturePipe.cpp
- src/Mod/PartDesign/App/FeatureSketchBased.cpp
- src/Mod/PartDesign/App/FeatureThickness.cpp
- src/Mod/PartDesign/App/FeatureTransformed.cpp
- src/Mod/PartDesign/Gui/Command.cpp
- src/Mod/PartDesign/Gui/ReferenceSelection.cpp
- src/Mod/PartDesign/Gui/TaskBooleanParameters.cpp
- src/Mod/PartDesign/Gui/TaskChamferParameters.cpp
- src/Mod/PartDesign/Gui/TaskDraftParameters.cpp
- src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
- src/Mod/PartDesign/Gui/TaskFeaturePick.cpp
- src/Mod/PartDesign/Gui/TaskFilletParameters.cpp
- src/Mod/PartDesign/Gui/TaskLinearPatternParameters.cpp
- src/Mod/PartDesign/Gui/TaskLoftParameters.cpp
- src/Mod/PartDesign/Gui/TaskMirroredParameters.cpp
- src/Mod/PartDesign/Gui/TaskMultiTransformParameters.cpp
- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.cpp
- src/Mod/PartDesign/Gui/TaskScaledParameters.cpp
- src/Mod/PartDesign/Gui/TaskShapeBinder.cpp
- src/Mod/PartDesign/Gui/TaskSketchBasedParameters.cpp
- src/Mod/PartDesign/Gui/TaskThicknessParameters.cpp
- src/Mod/PartDesign/Gui/TaskTransformedParameters.cpp
- src/Mod/PartDesign/Gui/ViewProviderBoolean.cpp
- src/Mod/PartDesign/Gui/ViewProviderMultiTransform.cpp
Replaces old-style for loops with the more efficient range-based for loops. This PR affects the code in the PartDesign module.
> PD: modernize C++: use range-based for loop

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftobjects/label.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/259
> Draft: Translate label type combobox

- src/Mod/Draft/draftguitools/gui_beziers.py
- src/Mod/Draft/draftguitools/gui_ellipses.py
- src/Mod/Draft/draftguitools/gui_fillets.py
- src/Mod/Draft/draftguitools/gui_lines.py
- src/Mod/Draft/draftguitools/gui_polygons.py
- src/Mod/Draft/draftguitools/gui_rectangles.py
- src/Mod/Draft/draftguitools/gui_splines.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/260
> Draft: Translate task titles for draft tools

- src/App/Graphviz.cpp
- src/App/PropertyContainer.h
- src/Base/Parameter.cpp
- src/Base/Rotation.cpp
- src/Gui/DocumentModel.cpp
- src/Gui/NotificationArea.cpp
Fix some minor issues discovered by clazy and clang-tidy.
> Fix lint issues

- src/Mod/Start/Gui/Workbench.cpp
See also https://forum.freecad.org/viewtopic.php?t=80498
> Start workbench should show the basic commands in the context-menus

- src/Mod/TechDraw/Gui/PathBuilder.h
This PR fixes an error in the declaration of PathBuilder reported here https://forum.freecad.org/viewtopic.php?t=80512,
> [TD]Fix wrong export macro

- src/Mod/TechDraw/App/AppTechDrawPy.cpp
- src/Mod/TechDraw/App/CMakeLists.txt
- src/Mod/TechDraw/App/CenterLine.cpp
- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/CosmeticExtension.cpp
- src/Mod/TechDraw/App/DimensionReferences.cpp
- src/Mod/TechDraw/App/DrawComplexSection.cpp
- src/Mod/TechDraw/App/DrawGeomHatch.cpp
- src/Mod/TechDraw/App/DrawProjGroupItem.cpp
- src/Mod/TechDraw/App/DrawProjectSplit.cpp
- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/DrawViewDetail.cpp
- src/Mod/TechDraw/App/DrawViewMulti.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/Geometry.cpp
- src/Mod/TechDraw/App/GeometryObject.cpp
- src/Mod/TechDraw/App/GeometryObject.h
- src/Mod/TechDraw/App/PropertyCenterLineList.cpp
- src/Mod/TechDraw/App/PropertyCosmeticEdgeList.cpp
- src/Mod/TechDraw/App/ShapeUtils.cpp
- src/Mod/TechDraw/App/ShapeUtils.h
This PR fixes a memory leak reported in issue #9265.
It also includes a refactoring of GeometryObject into 2 pieces.
> [TD]fix memory leak #9265

- src/Mod/TechDraw/App/CenterLine.cpp
- src/Mod/TechDraw/App/CenterLine.h
- src/Mod/TechDraw/App/Cosmetic.cpp
- src/Mod/TechDraw/App/Cosmetic.h
- src/Mod/TechDraw/App/CosmeticExtension.cpp
- src/Mod/TechDraw/App/CosmeticExtension.h
- src/Mod/TechDraw/App/CosmeticVertex.cpp
- src/Mod/TechDraw/App/CosmeticVertex.h
- src/Mod/TechDraw/App/DimensionFormatter.cpp
- src/Mod/TechDraw/App/DimensionFormatter.h
- src/Mod/TechDraw/App/DimensionGeometry.cpp
- src/Mod/TechDraw/App/DimensionGeometry.h
> [TechDraw] Improve typing 

- src/Mod/TechDraw/App/DrawSVGTemplate.cpp
- src/Mod/TechDraw/App/DrawSVGTemplate.h
- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/DrawUtil.h
- src/Mod/TechDraw/App/DrawViewDetail.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/DrawViewSection.h
- src/Mod/TechDraw/App/ShapeExtractor.cpp
- src/Mod/TechDraw/App/ShapeExtractor.h
This PR contains fixes for #9990, #10013, and a problem with sections of sections reported here: https://forum.freecad.org/viewtopic.php?t=80362
> [TD]fix #9990, #10013 and Section of Section

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/draftguitools/gui_dimensions.py
Fixes https://github.com/FreeCAD/FreeCAD-translations/issues/258
> Draft: translate draft axis labels

- src/Mod/PartDesign/App/FeatureExtrude.cpp
Fix #7189 in many cases but still fails if the sketch has a hole at it center of gravity.
---
> PartDesign: Fix uptolast ends too soon

- src/Mod/Draft/App/AppDraftUtilsPy.cpp
- src/Mod/Start/App/AppStart.cpp
- src/Mod/Start/Gui/AppStartGui.cpp
- src/Mod/Start/Gui/DlgStartPreferencesImp.cpp
- src/Mod/Start/Gui/Workbench.cpp
- src/Mod/Test/Gui/AppTestGui.cpp
- src/Mod/Test/Gui/UnitTestImp.cpp
- src/Mod/Test/Gui/UnitTestPy.cpp
- src/Mod/Web/App/AppWeb.cpp
- src/Mod/Web/App/Server.cpp
- src/Mod/Web/Gui/AppWebGui.cpp
- src/Mod/Web/Gui/BrowserView.cpp
- src/Mod/Web/Gui/Workbench.cpp
This PR affects the code of some modules.
> Mod: modernize C++: use equals default

- src/Mod/Path/Path/Dressup/Gui/RampEntry.py
https://github.com/FreeCAD/FreeCAD/issues/10178
---
> [Path] Make RampDressup accept other dressups as its base operation

- src/Mod/Points/App/AppPointsPy.cpp
- src/Mod/Points/App/Points.cpp
- src/Mod/Points/App/Points.h
- src/Mod/Points/App/PointsAlgos.cpp
- src/Mod/Points/App/PointsAlgos.h
- src/Mod/Points/App/PointsFeature.cpp
- src/Mod/Points/App/PointsFeature.h
- src/Mod/Points/App/PointsGrid.h
- src/Mod/Points/App/Properties.cpp
- src/Mod/Points/App/Properties.h
- src/Mod/Points/App/PropertyPointKernel.cpp
- src/Mod/Points/App/PropertyPointKernel.h
- src/Mod/Points/App/Structured.cpp
- src/Mod/Points/App/Structured.h
- src/Mod/Points/Gui/AppPointsGui.cpp
- src/Mod/Points/Gui/DlgPointsReadImp.cpp
- src/Mod/Points/Gui/ViewProvider.h
- src/Mod/Points/Gui/Workbench.cpp
This PR affects the code of the Points module.
> Points: modernize C++: use equals default

- src/Mod/Spreadsheet/App/AppSpreadsheet.cpp
- src/Mod/Spreadsheet/App/Cell.cpp
- src/Mod/Spreadsheet/App/PropertyColumnWidths.cpp
- src/Mod/Spreadsheet/App/PropertyRowHeights.cpp
- src/Mod/Spreadsheet/App/Sheet.h
- src/Mod/Spreadsheet/App/SheetObserver.h
- src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp
- src/Mod/Spreadsheet/Gui/DlgSettingsImp.cpp
- src/Mod/Spreadsheet/Gui/SheetTableView.cpp
- src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp
- src/Mod/Spreadsheet/Gui/Workbench.cpp
This PR affects the code of the Spreadsheet module.
> Sheet: modernize C++: use equals default

- src/Mod/Robot/App/AppRobot.cpp
- src/Mod/Robot/App/Edge2TracObject.cpp
- src/Mod/Robot/App/Edge2TracObject.h
- src/Mod/Robot/App/PropertyTrajectory.cpp
- src/Mod/Robot/App/Robot6Axis.cpp
- src/Mod/Robot/App/Robot6Axis.h
- src/Mod/Robot/App/RobotAlgos.cpp
- src/Mod/Robot/App/RobotObject.cpp
- src/Mod/Robot/App/RobotObject.h
- src/Mod/Robot/App/Simulation.cpp
- src/Mod/Robot/App/TrajectoryCompound.cpp
- src/Mod/Robot/App/TrajectoryCompound.h
- src/Mod/Robot/App/TrajectoryDressUpObject.cpp
- src/Mod/Robot/App/TrajectoryDressUpObject.h
- src/Mod/Robot/App/TrajectoryObject.cpp
- src/Mod/Robot/App/TrajectoryObject.h
- src/Mod/Robot/App/Waypoint.cpp
- src/Mod/Robot/Gui/AppRobotGui.cpp
- src/Mod/Robot/Gui/TaskDlgEdge2Trac.cpp
- src/Mod/Robot/Gui/TaskDlgEdge2Trac.h
- src/Mod/Robot/Gui/TaskDlgSimulate.cpp
- src/Mod/Robot/Gui/TaskDlgSimulate.h
- src/Mod/Robot/Gui/TaskDlgTrajectoryCompound.cpp
- src/Mod/Robot/Gui/TaskDlgTrajectoryCompound.h
- src/Mod/Robot/Gui/TaskDlgTrajectoryDressUp.cpp
- src/Mod/Robot/Gui/TaskDlgTrajectoryDressUp.h
- src/Mod/Robot/Gui/TaskWatcher.cpp
- src/Mod/Robot/Gui/TaskWatcher.h
- src/Mod/Robot/Gui/TrajectorySimulate.cpp
- src/Mod/Robot/Gui/Workbench.cpp
This PR affects the code of the Robot module.
> Robot: modernize C++: use equals default

- src/Gui/SoQtOffscreenRendererPy.cpp
Fix build failure when PCH is enabled.
> Gui: add missing precompiled header

- src/Mod/Draft/DraftGeomUtils.py
- src/Mod/Draft/WorkingPlane.py
- src/Mod/Draft/draftgeoutils/geometry.py
- src/Mod/Draft/draftguitools/gui_trackers.py
This somewhat convoluted function was only used by gui_trackers.
> Draft: remove getPlacementFromPoints function

- src/Mod/Draft/DraftGeomUtils.py
- src/Mod/Draft/WorkingPlane.py
- src/Mod/Draft/draftgeoutils/geometry.py
Changed getPlacementFromFace function in WorkingPlane.py to a compatibility function that calls placement_from_face.
> Draft: Add placement_from_face to geometry.py

- src/Mod/Draft/draftguitools/gui_base.py
- src/Mod/Draft/draftguitools/gui_base_original.py
- src/Mod/Draft/draftguitools/gui_lines.py
Main changes:
* Removed the noplanesetup parameter from gui_base_original.py. The parameter was not used.
* Removed handling of oldWP from gui_lines.py. This is now handled by the base class.
> Draft: Housekeeping and minor improvements for some draftguitools

- src/Base/BoundBox.h
- src/Mod/Mesh/App/Core/TrimByPlane.cpp
- src/Mod/Mesh/App/Mesh.cpp
Fix issue discovered by clang-tidy
> Base: fix clang-tidy warnings in BoundBox.h

- src/Mod/Draft/draftguitools/gui_tool_utils.py
The get_support function did not work for objects nested in, for example, Std_Parts.
Additionally improved and cleaned up the code, and reduced the docstrings.
> Draft: Make gui_tool_utils.get_support nesting aware

- src/Gui/View3DPy.cpp
For more details see: https://forum.freecad.org/viewtopic.php?p=702475#p702475
Kudos go to forum user bdm!
> Gui: use '%Y-%m-%d %H:%M:%S' as format string for date

- .github/workflows/actions/runCPPTests/runAllTests/action.yml
Add C++ tests for Mesh, Part, and Points to the CI runs.
> CI: Add new test targets

- src/Mod/Arch/ArchWindow.py
Also improve alignment relative to random workingplane if no face has been hovered
> Arch: Implement placement_from_face in ArchWindow.py

- src/Mod/Fem/Gui/BoxWidget.ui
- src/Mod/Fem/Gui/CylinderWidget.ui
- src/Mod/Part/AttachmentEditor/TaskAttachmentEditor.ui
- src/Mod/PartDesign/FeatureHole/TaskHole.ui
- src/Mod/PartDesign/Gui/TaskBooleanParameters.ui
- src/Mod/PartDesign/Gui/TaskChamferParameters.ui
- src/Mod/PartDesign/Gui/TaskDraftParameters.ui
- src/Mod/PartDesign/Gui/TaskFeaturePick.ui
- src/Mod/PartDesign/Gui/TaskFilletParameters.ui
- src/Mod/PartDesign/Gui/TaskHelixParameters.ui
- src/Mod/PartDesign/Gui/TaskLinearPatternParameters.ui
- src/Mod/PartDesign/Gui/TaskLoftParameters.ui
- src/Mod/PartDesign/Gui/TaskMirroredParameters.ui
- src/Mod/PartDesign/Gui/TaskMultiTransformParameters.ui
- src/Mod/PartDesign/Gui/TaskPadPocketParameters.ui
- src/Mod/PartDesign/Gui/TaskPipeOrientation.ui
- src/Mod/PartDesign/Gui/TaskPipeParameters.ui
- src/Mod/PartDesign/Gui/TaskPipeScaling.ui
- src/Mod/PartDesign/Gui/TaskPolarPatternParameters.ui
- src/Mod/PartDesign/Gui/TaskRevolutionParameters.ui
- src/Mod/PartDesign/Gui/TaskScaledParameters.ui
- src/Mod/PartDesign/Gui/TaskShapeBinder.ui
- src/Mod/PartDesign/Gui/TaskThicknessParameters.ui
- src/Mod/Sketcher/Gui/TaskSketcherElements.ui
Cleaning Crowdin of "garbage". Second approach.
https://github.com/FreeCAD/FreeCAD-translations/issues/270
Part 3, anticipates one or two more parts. :wink:
> Cleaning code from unnecessary strings generated to Crowdin 3

- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/App/DrawViewSection.h
- src/Mod/TechDraw/App/PropertyCenterLineList.cpp
This PR fixes a failure on deletion of a center line reported here: https://forum.freecad.org/viewtopic.php?p=702789#p702789
This PR also implements a feature for adjustable section line length requested here: https://forum.freecad.org/viewtopic.php?t=80633
> [TD]Fix fail on center line delete

- src/Gui/PreferencePackTemplates/Shortcuts.cfg
Template created on a clean FC setup using the following macro: https://github.com/howie-j/freecad-setup/blob/main/macro/shortcuts_to_prefpack.FCMacro
Updates template to newest shortcuts and include all new commands (selection filter, sketcher dimension etc)
> [Pref Pack Template] Update Shortcuts.cfg to newest changes

- src/Mod/Path/CMakeLists.txt
- src/Mod/Path/Path/Dressup/Gui/RampEntry.py
- src/Mod/Path/Path/GuiInit.py
> backport commits for Path WB

- src/Mod/Draft/importDWG.py
Forum topic:
https://forum.freecad.org/viewtopic.php?p=703063#p703061
> Draft: importDWG.py wrongly assumed that opt directory always exists on Linux

- src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
This PR implements a fix for issue #10440.
> [TD]fix #10440 Balloon arrow end point

- .pre-commit-config.yaml
- src/Mod/Assembly/AssemblyGlobal.h
- src/Mod/Assembly/Commands.py
- src/Mod/Assembly/InitGui.py
After this merge, anyone working on Assembly should make sure they have installed pre-commit into their local clone of the repo.  https://freecad.github.io/DevelopersHandbook/gettingstarted/ (see item 3 in "Setting up for development")
> Assembly: Add Assembly to precommit

- src/Mod/Fem/Gui/Workbench.cpp
Temporarily disable the Constraints without Solver submenu from the GUI. 
https://github.com/FreeCAD/FreeCAD/issues/10135
> FEM: disable the Constraints without solver submenu

- src/Mod/Draft/DraftGeomUtils.py
- src/Mod/Draft/draftgeoutils/geometry.py
- src/Mod/Draft/draftguitools/gui_mirror.py
- src/Mod/Draft/draftguitools/gui_trackers.py
When using Draft_Mirror there is currently no preview when the user has picked the 1st point of the mirror line. This PR fixes that.
> Draft: Fix Draft_Mirror preview

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
In sketcher_dimension : 
- Implement Point-to-Circle distance.
- Disable Arc-circle, arc-arc, arc-line distances as they are not implemented in sketcher yet.
@adrianinsaval @FlachyJoe
> Sketcher_Dimension: Implement Point-to-Circle distance.

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
* fix -Wunused-parameter
* fix -Wsign-compare
> Sketcher: fix several warnings:

- src/Mod/Assembly/Commands.py
This PR rewrite some of the code, of the Insert Link command. I think there is now only original code.
@chennes
> Assembly : Improve code of Insert Link command

- src/Base/PersistencePyImp.cpp
- src/Mod/ReverseEngineering/App/AppReverseEngineering.cpp
I missed these in the last PR (they are only conditionally compiled). To verify correctness you need to compile with `HAVE_PCL_SURFACE`.
> RE: Correct use of Wrapped_ParseTupleAndKeywords

- src/Mod/TechDraw/Gui/TaskDimension.cpp
This PR implements a fix for an issue in TaskDimension reported here: https://forum.freecad.org/viewtopic.php?t=80852&sid=b68421b71258c95e86a38f0b6c14a581
> [TD]fix Tolerance format issue in dialog

- src/Tools/RegExp/regexpdialog.cpp
- src/Tools/ThumbnailProvider/ClassFactory.cpp
- src/Tools/ThumbnailProvider/Common.h
- src/Tools/ThumbnailProvider/Main.cpp
- src/Tools/ThumbnailProvider/ThumbnailProvider.cpp
- src/Tools/embedded/Qt/cxx/main.cpp
- src/Tools/embedded/Win32/FreeCAD_widget/FreeCAD_widget.cpp
- src/Tools/embedded/glib/main.c
- src/Tools/plugins/imageformats/svg/main.cpp
- src/Tools/plugins/imageformats/svg/qsvgiohandler.cpp
- src/Tools/plugins/widget/customwidgets.cpp
- src/Tools/plugins/widget/customwidgets.h
- src/Tools/plugins/widget/wizard.cpp
Update Tools directory to the latest clang-format settings.
> Tools: Reformat to current clang-format standard

- tests/src/App/Application.cpp
- tests/src/App/ElementMap.cpp
- tests/src/Base/Bitmask.cpp
- tests/src/Base/Writer.cpp
- tests/src/Mod/Sketcher/App/SketchObject.cpp
- tests/src/Mod/Sketcher/App/planegcs/GCS.cpp
Update Tests to latest clang-format settings.
> Tests: Reformat to current clang-format standard

- src/Mod/Draft/draftobjects/shape2dview.py
Added a workaround in shape2Dview when multifuse fails
> Draft: Workaround failing multifuse in shape2Dview

- src/Mod/Draft/draftguitools/gui_arcs.py
- src/Mod/Draft/draftmake/make_circle.py
> Draft: Fix angle range issue of make_circle

- src/Mod/AddonManager/AddonManager.py
- src/Mod/AddonManager/AddonManagerTest/app/mocks.py
- src/Mod/AddonManager/AddonManagerTest/app/test_cache.py
- src/Mod/AddonManager/CMakeLists.txt
- src/Mod/AddonManager/TestAddonManagerApp.py
- src/Mod/AddonManager/addonmanager_cache.py
Extract this method from the AddonManager class, add tests, and refactor.
> Addon Manager: Refactor local cache update check

- src/Mod/TechDraw/Gui/MDIViewPage.cpp
- src/Mod/TechDraw/Gui/MDIViewPage.h
- src/Mod/TechDraw/Gui/QGVPage.cpp
- src/Mod/TechDraw/Gui/QGVPage.h
This PR implements the second part of a  fix for issue #10406.
The first part was implemented by PR #10456.
> [TD]add support for view menu zoom

- src/Gui/DlgLocationAngle.ui
- src/Mod/Draft/Resources/ui/TaskPanel_CircularArray.ui
- src/Mod/Fem/femcommands/commands.py
Patches for https://github.com/FreeCAD/FreeCAD/pull/10459 and https://github.com/FreeCAD/FreeCAD/pull/10426...
a few small details escaped attention need to be fixed 😉
Removing unnecessary strings from Crowdin and improving typos.
> Removing unnecessary strings from Crowdin + improving typos

- src/Gui/MainWindow.cpp
Fixed a small typo in the warning about 0.22 being the dev version not for production use.
> Fixed a small typo in the splash screen warning

- src/Mod/Part/App/AppPart.cpp
- src/Mod/Part/App/CMakeLists.txt
- src/Mod/Part/App/FeatureScale.cpp
- src/Mod/Part/App/FeatureScale.h
- src/Mod/Part/Gui/AppPartGui.cpp
- src/Mod/Part/Gui/CMakeLists.txt
- src/Mod/Part/Gui/Command.cpp
- src/Mod/Part/Gui/DlgScale.cpp
- src/Mod/Part/Gui/DlgScale.h
- src/Mod/Part/Gui/DlgScale.ui
- src/Mod/Part/Gui/Resources/Part.qrc
- src/Mod/Part/Gui/Resources/icons/tools/Part_Scale.svg
- src/Mod/Part/Gui/ViewProviderScale.cpp
- src/Mod/Part/Gui/ViewProviderScale.h
- src/Mod/Part/Gui/Workbench.cpp
This PR provides a solution to #10536 Scaling a Part shape is awkward.  It adds a scale function to the Part module.   The code is largely based on FeatureExtrusion and related code for task dialog and viewprovider.
> [Part]add scale command & feature

- src/Tools/updatets.py
Should be `StartPage` not just `Start`.
> Tools: Fix Start translation TS file name

- src/Gui/Application.cpp
Forum thread: https://forum.freecad.org/viewtopic.php?t=80981
> Gui: filter warning about dead keys

- src/Gui/PythonConsole.cpp
fix compilation warning
-if/else with return 
-uninitialized variables
> fix compilation warning

- src/Mod/Part/Gui/DlgScale.cpp
This PR corrects the handling of preselected objects in the new FeatureScale.
> [Part]correct handling of preselected objects

- src/Gui/CMakeLists.txt
- src/Gui/PreferencePages/DlgSettingsPythonConsole.cpp
- src/Gui/PreferencePages/DlgSettingsPythonConsole.ui
- src/Gui/PythonConsole.cpp
- src/Gui/PythonConsole.h
- src/Gui/PythonTracing.cpp
- src/Gui/PythonTracing.h
This is a reworked PR to replace #6720
> Gui: Fix app not responding when executing long-running Python code

- src/Gui/3Dconnexion/GuiNativeEventLinuxX11.cpp
- src/Gui/3Dconnexion/GuiNativeEventWin32.cpp
Freecad 0.19 use qt5.4 or higher.
> Removed old code using qt<5.4

- src/Tools/DownloadStatistics.py
The DownloadStatistics.py file is the duplication of the githubstats.py
> Remove  DownloadStatistics.py

- src/Gui/MainWindow.cpp
- src/Gui/Selection.h
- src/Gui/View3DInventorViewer.cpp
See forum: https://forum.freecad.org/viewtopic.php?t=81051
> Gui: fix some MSVC truncation warnings

- src/Mod/TechDraw/App/DrawViewSection.cpp
- src/Mod/TechDraw/Gui/TaskComplexSection.cpp
- src/Mod/TechDraw/Gui/TaskComplexSection.h
- src/Mod/TechDraw/Gui/TaskSectionView.cpp
- src/Mod/TechDraw/Gui/TaskSectionView.h
This PR corrects an issue with object labels in simple and complex sections reported here: https://forum.freecad.org/viewtopic.php?t=81026
> [TD]Fix label generation

- src/Mod/TechDraw/Gui/QGVPage.cpp
- src/Mod/TechDraw/Gui/QGVPage.h
Fix compiler warning: -Wunused-private-field
> TD: remove unused class member

- src/Mod/Drawing/Gui/TaskOrthoViews.h
- src/Mod/Part/Gui/Workbench.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
- src/Mod/Sketcher/Gui/Workbench.cpp
See https://github.com/FreeCAD/FreeCAD/pull/10583#issuecomment-1716187490
> Part: move scale command

- src/Mod/Draft/importSVG.py
> Draft: importSVG.py: check and fix path faces

- src/Mod/Part/Gui/DlgScale.ui
This PR implements a suggestion made here https://github.com/FreeCAD/FreeCAD/issues/10536#issuecomment-1715764354 to allow negative scale factors in the Scale tool.
> [Part]allow negative scale factors

- src/Mod/Draft/draftfunctions/svg.py
- src/Mod/Draft/draftobjects/dimension.py
- src/Mod/Draft/draftviewproviders/view_dimension.py
Related to issue #7573
**Forum discussion**
https://forum.freecadweb.org/viewtopic.php?p=631252#p631252
These modifications don't add the new properties suggested on the issue mentioned above and suggested on the forum discussion but just remove the center arrow
Other info and discussion can be found at https://gitlab.com/calligarov/FreeCAD/-/merge_requests/1
> [Feature Request] [Draft] [UI/UX] Remove the center arrow on radial dimensions

- src/Mod/TechDraw/App/CenterLine.cpp
- src/Mod/TechDraw/App/CenterLine.h
This PR allows center lines to rotate with the owning View.
> [TD]rotate centerlines with view

- src/Mod/TechDraw/App/DrawGeomHatch.cpp
- src/Mod/TechDraw/App/DrawGeomHatch.h
- src/Mod/TechDraw/App/DrawGeomHatchPy.xml
- src/Mod/TechDraw/App/DrawGeomHatchPyImp.cpp
- src/Mod/TechDraw/App/DrawHatch.cpp
- src/Mod/TechDraw/App/DrawHatch.h
- src/Mod/TechDraw/App/DrawHatchPy.xml
- src/Mod/TechDraw/App/DrawHatchPyImp.cpp
This PR implements for a fix for a problem with hatching reported here: https://forum.freecad.org/viewtopic.php?t=81135&sid=4dec18f323bebc2b0284da7b08188298
> [TD]fix hatch fail due to missing translate method

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
Fixes #10550
Enable user to deselect geos when using Sketcher_Dimension.
> Sketcher_Dimension : enable user to deselect geos by clicking on them again

- src/Mod/TechDraw/App/ShapeExtractor.cpp
This PR implements a solution to a problem reported here https://forum.freecad.org/viewtopic.php?t=81166&sid=098ef35a50c97e722403decc65d42d44 where objects containing a mix of 3d and 2d elements are drawn inverted in detail views.
> [TD]fix inverted detail of body

- src/Mod/Part/App/CMakeLists.txt
removed unnecessary include directory into cmake
> removed unnecessary include into cmake

- src/Mod/Arch/exportIFC.py
Simple fix to workaround face index errors.
Could be backported. I'll make a separate PR
> Arch: Fixed IFC export of compsolids

- src/Mod/Draft/draftguitools/gui_edit.py
Forum topic:
https://forum.freecad.org/viewtopic.php?t=81186
> Draft: gui_edit called displayPoint without mask

- src/Mod/Draft/draftviewproviders/view_dimension.py
Fixes an issue that was missed in #10673.
> Draft: Fix for PR10673

- src/Gui/SoDatumLabel.cpp
- src/Gui/SoDatumLabel.h
https://github.com/FreeCAD/FreeCAD/pull/10674 is merged that is supposed to handle a selection issue of constraints.
This PR now cleans up some  code that shouldn't be needed any more but it's best to wait until we see that the merged PR 100% does its job.
> Gui: Remove bounding box computation from SoDatumLabel::GLRender()

- src/Base/Matrix.cpp
- src/Base/Matrix.h
- src/Base/MatrixPy.xml
- src/Base/MatrixPyImp.cpp
- src/Mod/Test/BaseTests.py
- tests/src/Base/Matrix.cpp
* Fix many clang-tidy warnings of Matrix class
* Fix incorrect method names about diagonal and trace of a matrix
* Add more unit tests
> More Matrix test cases

- src/Mod/Arch/ArchFence.py
The code relied on the old implementation of Draft patharray where the calculated placements were not returned in sequence.
Forum topic:
https://forum.freecad.org/viewtopic.php?t=81246
> Arch: Fix Arch_Fence section placement

- src/Gui/SoFCCSysDragger.cpp
- src/Gui/SoFCCSysDragger.h
- src/Gui/ViewParams.h
- src/Gui/ViewProviderDragger.cpp
This PR improves the Transform tool dragger. It isn't based on an issue, I can open a discussion issue if necessary.
This PR:
- Improves the appearance of the dragger making it look more modern and user friendly:
- Implements additional sub-draggers to move object on a plane (see video below):
[vokoscreenNG-2023-09-17_00-06-27.webm](https://github.com/FreeCAD/FreeCAD/assets/69015181/3a016158-f053-4e82-bcbb-386480ddca68)
- Adds new parameters for "axis colors". Currently only the Transform dragger uses these colors but FreeCAD has quite a bit of axis elements and it would be great to unify their colors and make them configurable in `Preferences > Display > Colors` in the future. 
Any reviews and feedback is appreciated.
> Gui: Transform dragger improvements

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- use TypeId helpers
- use auto for variable declaration which use static cast
- change empty lines
> Sketcher: refactor CommandConstraint.cpp

- tests/src/App/MappedName.cpp
https://forum.freecad.org/viewtopic.php?t=81263
> fix qbytearray length out of bound

- src/Mod/Part/App/Geometry.cpp
- src/Mod/Part/App/Geometry.h
- src/Mod/Sketcher/Gui/CommandConstraints.cpp
This PR adds arc angle mode to sketcher_dimension.
It also adds a tiny convenience function, cf commits.
Fixes https://github.com/FreeCAD/FreeCAD/issues/10605
> Sketcher_Dimension: Adds arc angle mode.

- src/Mod/Sketcher/App/SketchObject.cpp
- src/Mod/Sketcher/App/SketchObject.h
- src/Mod/Sketcher/Gui/CommandConstraints.cpp
* fix compiler warning about unused variable
* fix const correctness
* fix access type of setExpression()
* removed duplicated method
> Sketch: fix a few minor issues

- src/Gui/NaviCube.cpp
Makes the navigation cube's rotate to nearest feature more accurate. Previously the current camera orientation was used in the final result from the calculations. This led slightly different values every time a face was selected and resulted in some near zero values. Now, the fixed standard orientations are used in the final calculation. This makes sure the results are consistent and prevent some, but not all, near zero values. This PR is related to https://forum.freecad.org/viewtopic.php?t=81043
> Gui: Improve accuracy for navigation cube's rotate to nearest feature

- src/Mod/TechDraw/App/DrawComplexSection.cpp
- src/Mod/TechDraw/App/DrawViewDetail.cpp
- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/App/DrawViewSection.cpp
We use a lambda function with a copy of variables that  might be destructed in the original calling thread, possibly producing dangling references.
See:
https://forum.freecad.org/viewtopic.php?t=81260
All tests have passed.
> TechDraw: create closure for concurrent thread context

- src/Gui/SoFCCSysDragger.cpp
- src/Gui/SoFCCSysDragger.h
- src/Gui/ViewParams.h
- src/Gui/ViewProviderDragger.cpp
Fixes for https://github.com/FreeCAD/FreeCAD/issues/10719
CC. @wwmayer
> Gui: Transform dragger fixes for PR #10706

- src/Mod/TechDraw/App/DrawViewPartPy.xml
- src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
- src/Mod/TechDraw/App/Geometry.cpp
- src/Mod/TechDraw/App/Geometry.h
- src/Mod/TechDraw/Gui/CMakeLists.txt
- src/Mod/TechDraw/Gui/CommandAnnotate.cpp
- src/Mod/TechDraw/Gui/Resources/TechDraw.qrc
- src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_CosmeticCircle.svg
- src/Mod/TechDraw/Gui/TaskCosmeticCircle.cpp
- src/Mod/TechDraw/Gui/TaskCosmeticCircle.h
- src/Mod/TechDraw/Gui/TaskCosmeticCircle.ui
- src/Mod/TechDraw/Gui/Workbench.cpp
This PR implements a solution to #10352.
> [TD]initial implementation of cosmetic cicle command (fix #10352)

- src/Mod/Part/App/Geom2d/BezierCurve2dPy.xml
> Part: remove leftover comment markup

- src/Mod/Draft/Resources/ui/TaskShapeString.ui
- src/Mod/Draft/Resources/ui/preferences-drafttexts.ui
Forum topic:
https://forum.freecad.org/viewtopic.php?t=81280
> Draft: ShapeString: add font file filter

- src/Mod/Assembly/JointObject.py
- src/Mod/Assembly/UtilsAssembly.py
Completes https://github.com/FreeCAD/FreeCAD/issues/10745 and https://github.com/FreeCAD/FreeCAD/issues/10746
CC @PaddleStroke 
Preview video:
[vokoscreenNG-2023-09-21_19-30-07.webm](https://github.com/FreeCAD/FreeCAD/assets/69015181/603f1a3e-a20b-4d7f-ad4c-c64695311c3f)
> Assembly: Improve JCS appearance and implement autoscale

- src/Doc/CONTRIBUTORS
Adding myself to contributors.
> Add Rexbas to contributors

- src/Gui/FileDialog.cpp
- src/Gui/FileDialog.h
Fixes https://github.com/FreeCAD/FreeCAD/issues/10782
> Gui: fixes #10782: Unable to cancel Select module Open obj messagebox

- src/Mod/Draft/WorkingPlane.py
This PR introduces the new PlaneBase class.
Most of its functions are rewritten versions of the functions in the original Plane class, with the exception of align_to_point_and_axis_svg.
Note that after this PR the original Plane class does not yet inherit from PlaneBase. This will be done in several following PRs. I will then also explain the reasons behind some of the revised functions in PlaneBase.
The introduction of the PlaneGui class will follow after that.
Issue: #5603.
> Draft: Introduction of the PlaneBase class

- src/Mod/Draft/draftobjects/shapestring.py
> Draft: ShapeString: add ObliqueAngle property

- src/App/PropertyPythonObject.cpp
- src/Mod/Test/Document.py
Adds some tests to demonstrate issue #10460 with Py3.11
> Test: add unit tests for PropertyPythonObject

- src/Mod/Path/Path/Post/scripts/estlcam_post.py
> Path: refactor Utils imports in estlcam_post.py

- src/Mod/Material/App/MaterialLibrary.h
- src/Mod/Material/App/MaterialManager.h
- src/Mod/Material/App/Model.h
- src/Mod/Material/App/ModelLibrary.h
- src/Mod/Material/App/ModelManager.h
- tests/src/Mod/Material/App/Model.cpp
* -Winconsistent-missing-override
* -Wtautological-undefined-compare
> Mat: fix several compiler warnings:

- src/Mod/TechDraw/App/DimensionReferences.cpp
- src/Mod/TechDraw/App/DimensionReferences.h
- src/Mod/TechDraw/App/DrawViewDimension.cpp
This PR addresses the handling of Dimension references that are missing their reference geometry.
> [TD]fix missing reference geometry

- src/Mod/Material/App/ModelUuids.h
- src/Mod/Material/App/trim.h
- src/Mod/Material/Gui/Array3D.cpp
- src/Mod/Material/Gui/Array3D.h
- src/Mod/Material/Gui/ModelSelect.cpp
- src/Mod/Material/Gui/ModelSelect.h
as otherwise the parser of the clang code model raises a lot of error messages
> Material: include some more required header files

- src/Mod/Draft/importDXF.py
Forum topics:
https://forum.freecad.org/viewtopic.php?t=81422
https://forum.freecad.org/viewtopic.php?t=81523
> Draft: ImportDXF: CURRENTDXFLIB is not obsolete and should be kept

- src/Mod/Draft/draftutils/groups.py
Forum topic:
https://forum.freecad.org/viewtopic.php?t=81547
> Draft: get_movable_children: prevent endless loop

- src/Gui/MetaTypes.h
- src/Mod/Material/App/MaterialLibrary.cpp
- src/Mod/Material/App/MaterialPyImpl.cpp
- src/Mod/Material/App/MaterialValue.h
https://forum.freecad.org/viewtopic.php?t=81572
> Material: fix build failure with Qt6

- src/Mod/Import/App/AppImportPy.cpp
- src/Mod/Import/App/CMakeLists.txt
- src/Mod/Import/App/ReaderIges.cpp
- src/Mod/Import/App/ReaderIges.h
- src/Mod/Import/App/ReaderStep.cpp
- src/Mod/Import/App/ReaderStep.h
- src/Mod/Import/App/WriterIges.cpp
- src/Mod/Import/App/WriterIges.h
- src/Mod/Import/App/WriterStep.cpp
- src/Mod/Import/App/WriterStep.h
- src/Mod/Import/Gui/AppImportGuiPy.cpp
* move STEP reader & writer to own classes
* move IGES reader & writer to own classes
> Import: code refactoring

- src/Mod/Import/App/AppImportPy.cpp
- src/Mod/Import/App/ReaderGltf.cpp
- src/Mod/Import/App/ReaderIges.cpp
- src/Mod/Import/App/ReaderStep.cpp
- src/Mod/Import/App/WriterGltf.cpp
- src/Mod/Import/App/WriterGltf.h
- src/Mod/Import/App/WriterIges.cpp
- src/Mod/Import/App/WriterIges.h
- src/Mod/Import/App/WriterStep.cpp
- src/Mod/Import/App/WriterStep.h
- src/Mod/Import/Gui/AppImportGuiPy.cpp
* Make constructors explicit
* Fix a regression from PR 10783
> Import: fix lint warnings

- src/Mod/TechDraw/App/DrawViewDimension.cpp
This PR implements a fix for issue #10880.
> [TD]Fix no dimensions from old document (#10880)

- src/Mod/Import/App/AppImportPy.cpp
- src/Mod/Import/App/PreCompiled.h
* fix legacy STEP/IGES/glTF export function to support colors per face in headless mode
* improve new STEP/IGES/glTF export function to support colors per face in headless mode
> Import: Fixes issue #10861

- src/Mod/Path/App/Area.cpp
- src/Mod/Path/App/AreaPy.xml
- src/Mod/Path/App/AreaPyImp.cpp
* fix -Wunused-parameter
* fix -Wunused-but-set-variable
> Path: fix compiler warnings

- src/Mod/Spreadsheet/Gui/Command.cpp
Fixes #10829
This pull request replaces #10853 as a rebased branch instead
Compiled and tested.
> Spreadsheet: export CSV file extension by default

- src/Mod/Fem/Gui/Resources/icons/FEM_SolverControl.svg
- src/Mod/Fem/Gui/Resources/icons/FEM_SolverRun.svg
- src/Mod/Fem/Gui/Resources/icons/FEM_SolverStandard.svg
Resolves #10824 - the new icons (created by [bitacovir](https://forum.freecad.org/memberlist.php?mode=viewprofile&u=3136)) are much more intuitive than the old ones
> FEM: Added more intuitive FEM solver icons

- src/Mod/Path/Path/Post/scripts/centroid_post.py
- src/Mod/Path/PathTests/TestCentroidPost.py
Reverts FreeCAD/FreeCAD#10857
PR introduced a failing test.
> Revert "Add G43 tool height compensation to centroid post"

- src/Mod/Import/App/CMakeLists.txt
- src/Mod/Import/App/ExportOCAF2.cpp
- src/Mod/Import/App/ExportOCAF2.h
- src/Mod/Import/App/ImportOCAF2.cpp
- src/Mod/Import/App/ImportOCAF2.h
- src/Mod/Import/App/Tools.cpp
- src/Mod/Import/App/Tools.h
and move global functions to Tools class
> Imoprt: move ExportOCAF2 to own source files

- src/Mod/TechDraw/App/DimensionReferences.cpp
Fix #10919 crash at geometry deletion
> TechDraw: Fix #10919 crash at geometry deletion

- src/Mod/Draft/importSVG.py
Forum topic:
https://forum.freecad.org/viewtopic.php?t=81696
> Draft: importSVG: handle viewBox in mm

- src/Mod/Draft/WorkingPlane.py
Related issue:
#5603.
Previous PRs:
#10766
#10838
The remaining Plane class functions have been processed (some are unchanged):
`setup`
* Updated to use new functions.
* The `direction` etc. arguments are never used AFAICT.
* Added `from draftutils import gui_utils`.
`reset`
* Unchanged.
`setTop`
* Calls `super().set_to_top()`. That function does not use `align_to_point_and_axis` but specifies exact vectors for improved accuracy.
* `import FreeCADGui` already happens at the top of the file.
* The code block after `if FreeCAD.GuiUp:` was kept for now.
`setFront`
* Idem.
`setSide`
* This function sets the WP to the left side position, and not to the right side postion as in the Draft_SelectPlane command.
* Idem.
`getRotation`
* Revised.
* The function has an akward name as it returns a …
> Draft: Update the Plane class (step 2)

- src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_WeldSymbol.svg
This PR implements a fix for issue #10916.
> [TD]upgrade WeldSymbol icon (#10916)

- src/Mod/TechDraw/App/GeometryObject.cpp
This PR implements a fix for issue #10944.
> [TD]fix fail on unmeshed shape

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/CommandConstraints.h
First step to solve https://github.com/FreeCAD/FreeCAD/issues/10524
This PR reduce code duplicity in the command angle and in sketcher_dimension.
> [Sketcher] Angle constraint refactor

- src/Base/BaseClass.h
- src/Mod/Sketcher/App/SketchObject.cpp
Original idea of Werner:
https://github.com/FreeCAD/FreeCAD/pull/10643#issuecomment-1712966545
I really liked this syntax to avoid repetition and even explicit consideration of Types when type checking.
I thought it would be a pity to get it lost.
It includes a small demonstrator of usage.
> Base: Class - Type checking template functions

- src/Mod/Draft/draftfunctions/svgtext.py
Forum topic:
https://forum.freecad.org/viewtopic.php?p=711184#p711184
> Draft: fix multiline offset for rotated SVG texts

- src/Mod/Arch/importOBJ.py
> Arch: Read and write object.Label on Wavefront OBJ import and export

- src/Mod/Draft/draftguitools/gui_snapper.py
> Draft: Fix cursor scaling issue

- src/App/Document.cpp
> Fix #10910 Authoring and Licence, Empty Licence URL breaks

- src/Gui/Tree.cpp
https://forum.freecad.org/viewtopic.php?t=77214
Supersedes #9124
> Gui: fix selection of nested object in App::Part

- src/Mod/Import/App/dxf/dxf.h
- src/Mod/TechDraw/App/DrawViewDimension.cpp
- tests/src/App/StringHasher.cpp
Fixes several compiler warnings in different modules.
> Fix clang warnings

- src/Mod/Draft/importDXF.py
> Draft: Import DXF: handle arc angles larger than 360 degrees

- src/Mod/Fem/App/FemPostFilter.cpp
- src/Mod/Fem/App/FemPostFilter.h
- src/Mod/Fem/Gui/TaskPostBoxes.cpp
Enumeration property is added to reference the vector component to be plotted.
> Fem: Plot vector components in FemPostDataAlongLineFilter - fixes #5916

- src/Mod/Draft/WorkingPlane.py
Related issue:
#5603.
Previous PRs:
#10766
#10838
#10931
Short explanation:
* The PlaneGui class handles several GUI related aspects of the WP including a WP history.
* The `get_working_plane` function should be used to get a WP.
* Some of the code was taken from gui_selectplane.py. The intention is to remove almost all WP related code from that file. The icon, tooltip and label for the draftToolBar are also handled by PlaneGui.
* The tooltip shows extended information about the WP (position and axes vectors). An asteriks is appended to the label if the origin does not match the global origin.
* The `_update_all` function still updates FreeCAD.DraftWorkingPlane for compatibility.
* Some confusing names from the Plane class have been changed: `weak` -> `auto`, `reset` -> `set_to_auto`, …
> Draft: Introduction of the PlaneGui class

- src/Gui/OverlayManager.cpp
- src/Gui/OverlayManager.h
- src/Gui/TreeParams.py
Replaces PR #10994 because of some merge conflicts.
> [Gui] Prefer Dark-Outline as default overlay stylesheet - #7888

- src/Gui/EditableDatumLabel.cpp
- src/Gui/EditableDatumLabel.h
- src/Gui/SoDatumLabel.cpp
- src/Gui/SoDatumLabel.h
> @PaddleStroke
> 
> Please cherry pick into current master and PR separately (all three in a single PR):
> https://github.com/FreeCAD/FreeCAD/commit/0c72708480c2bc20b104774ed1bb8d4b3ca09c8c
> https://github.com/FreeCAD/FreeCAD/commit/7ae1e53761e591aad79e7964c87ff8866c1af193
> https://github.com/FreeCAD/FreeCAD/commit/754747a0ab31f0179cb3c227039780816dface1f
@abdullahtahiriyo the 3 commits in a separate PR as asked
> Changes to editableDatumLabel and 

- src/Gui/QSint/actionpanel/actiongroup.cpp
- src/Gui/QSint/actionpanel/actiongroup.h
@abdullahtahiriyo as asked changes to actiongroup in a separate PR.
> Add setHeaderIcon to actiongroup.h

- src/Mod/Draft/WorkingPlane.py
> Draft: PlaneGui: some updates and fixes.

- src/Mod/Draft/WorkingPlane.py
> Draft: PlaneGui: minor fix

- src/Mod/Sketcher/Gui/CMakeLists.txt
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.h
- src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.cpp
- src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.h
- src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.ui
- src/Mod/Sketcher/Gui/TaskDlgEditSketch.cpp
- src/Mod/Sketcher/Gui/TaskDlgEditSketch.h
- src/Mod/Sketcher/Gui/TaskSketcherTool.cpp
- src/Mod/Sketcher/Gui/TaskSketcherTool.h
- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
@abdullahtahiriyo The 3 commits for first step of tool settings.
> Tool setting - Initial framework

- src/Mod/Path/Path/Post/UtilsArguments.py
- src/Mod/Path/Path/Post/scripts/refactored_test_post.py
- src/Mod/Path/PathTests/TestRefactoredTestPost.py
This is one in a series of PR's where I am taking code from at least 4 postprocessor files partially written by different people, combining them into three files, then trying to make the code more consistent and simpler.  The long term goal is to enable much simpler postprocessor files with much less copied code in each postprocessor file and much more "shared" code in the the three Utils*.py files.
In this PR I added type annotations along with some required refactoring.
> Path:  Added type annotations along with some refactoring.

- src/Mod/Fem/App/FemPostFilter.cpp
- src/Mod/Fem/App/FemPostFilter.h
- src/Mod/Fem/Gui/TaskPostBoxes.cpp
- src/Mod/Fem/Gui/TaskPostBoxes.h
- src/Mod/Fem/Gui/ViewProviderFemPostFilter.cpp
- src/Mod/Fem/Gui/ViewProviderFemPostFilter.h
This fix #5719.
Now the object has a property to set the size to give it more visibility.
Also remove `DataAtPointMarker` as it became unnecessary.
> Fem: Remove FemPostDataAtPointFilter Radius property and add PointSize - fixes #5719

- src/Mod/Path/Path/Base/Language.py
- src/Mod/Path/Path/Dressup/DogboneII.py
- src/Mod/Path/Path/Dressup/Gui/LeadInOut.py
- src/Mod/Path/Path/Dressup/Gui/RampEntry.py
- src/Mod/Path/Path/Dressup/Tags.py
- src/Mod/Path/PathPythonGui/simple_edit_panel.py
- src/Mod/Path/PathTests/TestPathDressupDogboneII.py
A rewrite of the core functionality of LeadInOutDressup using functionality from Language.py. The behaviour should be mostly the same but the readability of the code is hopefully improved.
Forum topic: https://forum.freecad.org/viewtopic.php?t=81591
> Path: rework LeadInOutDressup

- src/Gui/DlgExpressionInput.ui
- src/Gui/QuantitySpinBox_p.h
- src/Mod/Path/Path/Base/Gui/Util.py
> Add hotkey to expression tooltip, rename Formula editor

- src/Gui/Application.cpp
- src/Gui/Application.h
- src/Gui/ApplicationPy.cpp
- src/Gui/CMakeLists.txt
- src/Gui/WorkbenchManipulator.cpp
- src/Gui/WorkbenchManipulator.h
- src/Gui/WorkbenchManipulatorPython.cpp
- src/Gui/WorkbenchManipulatorPython.h
See https://github.com/FreeCAD/FreeCAD/pull/10732#issuecomment-1746496249
> Gui: Python support of workbench manipulation

- src/Mod/Path/Path/Dressup/Gui/ZCorrect.py
> Add F-word to output on zcorrect dressup

- src/Mod/AddonManager/addonmanager_utilities.py
> AddonManager: handle the case of symlinked addon when uninstalling

- src/Mod/Draft/draftguitools/gui_facebinders.py
- src/Mod/Draft/draftobjects/facebinder.py
Forum topic:
https://forum.freecad.org/viewtopic.php?t=81997
Additionally:
* Fixed offset and extrusion for non-planar faces.
* Improved the addSubobjects function,
* Cleaned up the code a little bit.
> Draft: Make Facebinders link-aware

- src/Mod/Draft/DraftGui.py
- src/Mod/Draft/DraftTools.py
- src/Mod/Draft/draftguitools/gui_arcs.py
- src/Mod/Draft/draftguitools/gui_base_original.py
- src/Mod/Draft/draftguitools/gui_dimensions.py
- src/Mod/Draft/draftguitools/gui_edit.py
- src/Mod/Draft/draftguitools/gui_labels.py
- src/Mod/Draft/draftguitools/gui_lines.py
- src/Mod/Draft/draftguitools/gui_planeproxy.py
- src/Mod/Draft/draftguitools/gui_scale.py
- src/Mod/Draft/draftguitools/gui_tool_utils.py
> Draft: Updates related to the PlaneGui class

- src/Mod/TechDraw/App/GeometryMatcher.cpp
> TD: fix GeometryMatcher::compareBSplines

- src/Mod/Spreadsheet/Gui/SheetTableView.cpp
> Sheet: remove double call of 'mimeData->hasText()'

- src/Mod/Draft/importDXF.py
> Draft: importDXF: fix off layer bug

- src/Mod/Mesh/App/WildMagic4/Wm4TRational.h
- src/Mod/Mesh/App/WildMagic4/Wm4TRational.inl
> Mesh: disable potentially unsafe code in Wm4 library

- src/Gui/DlgRevertToBackupConfigImp.cpp
- src/Mod/Part/Gui/TaskAttacher.cpp
- src/Mod/PartDesign/Gui/TaskFilletParameters.cpp
> Remove redundant std::string

- src/Mod/TechDraw/App/DrawViewPart.cpp
- src/Mod/TechDraw/Gui/QGIView.cpp
- src/Mod/TechDraw/Gui/QGIView.h
This PR removes some obsolete code and fixes a incorrect comparison as reported in items 1, 12 of issue #11091.
> [TD]Fix Pvs errors #11091

- src/Gui/EditableDatumLabel.cpp
- src/Gui/EditableDatumLabel.h
Following discussion on https://github.com/FreeCAD/FreeCAD/pull/10892
@abdullahtahiriyo cherry pick changes from editable datum label.
> EditableDatumLabel add support for angle labels.

- src/Mod/TechDraw/Gui/PagePrinter.cpp
- src/Mod/TechDraw/Gui/PagePrinter.h
This PR implements a fix for issue #11087.
> [TD]fix printAllPdf info block text #11087

- src/Mod/Draft/draftguitools/gui_planeproxy.py
The previous code resulted in a syntax error.
> Draft: Fix Gui.doCommand issue in gui_planeproxy caused by PR11080

- src/Mod/Draft/importSVG.py
> Draft: importSVG: handle viewBox in mm (PR10929 fix was not correct)

- src/Mod/TechDraw/Gui/CMakeLists.txt
- src/Mod/TechDraw/Gui/PATPathMaker.cpp
- src/Mod/TechDraw/Gui/PATPathMaker.h
- src/Mod/TechDraw/Gui/PagePrinter.cpp
- src/Mod/TechDraw/Gui/QGIFace.cpp
- src/Mod/TechDraw/Gui/QGIFace.h
- src/Mod/TechDraw/Gui/QGIPrimPath.cpp
- src/Mod/TechDraw/Gui/QGIPrimPath.h
- src/Mod/TechDraw/Gui/QGIViewPart.cpp
- src/Mod/TechDraw/Gui/QGIViewPart.h
- src/Mod/TechDraw/Gui/QGIViewSection.cpp
- src/Mod/TechDraw/Gui/QGSPage.cpp
- src/Mod/TechDraw/Gui/QGSPage.h
This PR implements a fix for issue #11088.  It also includes a refactoring of QGIFace and and changes to PagePrinter.
> [TD]Fix pdf hatch (#11088)

- src/Mod/Draft/CMakeLists.txt
- src/Mod/Draft/InitGui.py
- src/Mod/Draft/draftguitools/gui_hyperlink.py
Fixes #7062
**Forum discussion**
https://forum.freecad.org/viewtopic.php?f=23&t=69528
> [Feature Request] [Draft] [UI/UX] new Draft_Hyperlink command

- src/Mod/Arch/ArchBuildingPart.py
- src/Mod/Arch/ArchCurtainWall.py
- src/Mod/Arch/ArchCutPlane.py
- src/Mod/Arch/ArchNesting.py
- src/Mod/Arch/ArchPanel.py
- src/Mod/Arch/ArchSectionPlane.py
- src/Mod/Arch/ArchStructure.py
- src/Mod/Arch/ArchTruss.py
- src/Mod/Arch/ArchVRM.py
- src/Mod/Arch/ArchWall.py
- src/Mod/Arch/ArchWindow.py
- src/Mod/Arch/importIFCHelper.py
> Arch: Updates related to the PlaneGui class

- src/Mod/Draft/draftobjects/facebinder.py
> Draft: Make Facebinders link-aware (fix errors in previous PR)

- src/Mod/Draft/draftguitools/gui_selectplane.py
> Draft: Draft_SelectPlane was not correctly finished in case of a pre-selection

- src/Gui/EditableDatumLabel.cpp
- src/Gui/EditableDatumLabel.h
- src/Gui/TaskView/TaskImage.cpp
@abdullahtahiriyo PR of 
https://github.com/FreeCAD/FreeCAD/commit/8128e3eb9d993d1ba761f07c4c2dfdd810c16a65
https://github.com/FreeCAD/FreeCAD/commit/1727c153876e779ab72e5fcf340a3c28b79fd317
https://github.com/FreeCAD/FreeCAD/commit/5a976ade2a24a2e6f996fede4c28fbeef532ff90
> [Core] EditableDatumLabel : Sketcher Tool settings card 4

- src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.cpp
- src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.h
SketcherToolDefaultWidget : 
- Add 3 parameter configuration functions.
- And remove the units from setParameter.
> [Sketcher] Tool setting card 6 : changes to SketcherToolDefaultWidget

- src/Mod/Draft/draftobjects/facebinder.py
Previous PRs: #11081 and #11156.
> Draft: Make Facebinders link-aware (2nd error fix)

- src/Mod/Part/App/AppPartPy.cpp
For confirmation see:
https://github.com/realthunder/FreeCAD/blob/cad29253a493084a1c52d09fe164d4d91428b265/src/Mod/Draft/draftguitools/gui_selectplane.py#L198
> Part: Fix mistake in Part.getShape docstring

- src/Mod/TechDraw/Gui/QGIEdge.cpp
- src/Mod/TechDraw/Gui/QGIPrimPath.cpp
- src/Mod/TechDraw/Gui/QGIViewPart.cpp
This PR implements a fix for a problem where line style is not respected as reported here: https://forum.freecad.org/viewtopic.php?t=82213&sid=7d06f04f8a8f6295a70db9409a6edddc
> [TD]fix loss of line style

- src/Mod/Draft/draftfunctions/dxf.py
- src/Mod/Draft/draftfunctions/mirror.py
- src/Mod/Draft/draftfunctions/svg.py
- src/Mod/Draft/draftfunctions/svgshapes.py
- src/Mod/Draft/draftgeoutils/wires.py
- src/Mod/Draft/draftguitools/__init__.py
- src/Mod/Draft/draftmake/make_dimension.py
- src/Mod/Draft/draftviewproviders/view_wire.py
- src/Mod/Draft/importDXF.py
Related issue:
#5603.
Additionally:
Fixed the issue where the texts of Arch_Space objects were not exported to DXF.
> Draft: Updates related to the PlaneGui class (step 2)

- src/Mod/Draft/draftobjects/dimension.py
- src/Mod/Draft/drafttaskpanels/task_circulararray.py
- src/Mod/Draft/drafttaskpanels/task_polararray.py
> Draft: Updates related to the PlaneGui class (step 3)

- src/Gui/SoFCCSysDragger.cpp
[Problem] Coin version on Mac Conda builds causes transform crash - see [issue](https://github.com/FreeCAD/FreeCAD/issues/9465) for detailed explanation.
> Fix issue #9465 

- src/Mod/Spreadsheet/Gui/AppSpreadsheetGui.cpp
> Bugfix/issue #10144 FreeCAD freezes when clicking inside spreadsheet

- src/Mod/TechDraw/Gui/TaskDetail.cpp
This PR implements a fix for a problem reported here: https://forum.freecad.org/viewtopic.php?t=82230&sid=d382f26e9af7d8507061c285b72efa24
> [TD]fix spurious missing object message

- src/Mod/Draft/importSVG.py
consider object linewidths in SVG export
fixes #6034
> Draft: Fixed linewidths in SVG export

- src/Tools/xmlformat/main.cpp
* Avoid adding `&#xd;` to the output
* Sort attributes of PythonExport element
* Remove trailing whitespaces from UserDocu text and replace tabs with 4 spaces
> Tools: improve XML formatter

- src/Mod/Part/Gui/SectionCutting.cpp
- src/Mod/Part/Gui/SectionCutting.h
> Part: Refactor of Section cutting (Step 1)

- src/Mod/TechDraw/Gui/QGIEdge.cpp
- src/Mod/TechDraw/Gui/TaskLineDecor.cpp
This PR corrects 2 warnings from #11188.
> [TD]fix 2 tidy warnings

- src/Mod/Draft/draftguitools/gui_snapper.py
- src/Mod/Draft/draftguitools/gui_trackers.py
Related issue:
#5603.
For gui_snapper.py and gui_trackers.py an intermediate solution has been adopted. They still rely on App.DraftWorkingPlane, but now use a small function to retreive it.
Simply switching to the PlaneGui class is problematic for the trackers as this results in an endless recursion (wp->grid->wp->...). Using the old App.DraftWorkingPlane (which is kept up-to-date by PlaneGui) solves this for now. I will try to return to this later (which may be after the next release though).
> Draft: Updates related to the PlaneGui class (step 4)

- src/Mod/Arch/ArchWindow.py
Fixes #11185.
Same problem as in #6617.
> Arch: fix Placement multiplication for subvolumes

- src/Mod/Draft/draftmake/make_clone.py
> Draft: clone IfcType and Subvolume properties

- src/Mod/TechDraw/Gui/CommandDecorate.cpp
I would like to add the checked state for the TechDraw_ToggleFrame menu item. Though this is far from being something essential, I believe in complex drawings the state reflected by the button is really helpful.
As usual, in case of any issues, please let me know.
> [TechDraw] Checkable menu item for Turn View Frames On/Off

- src/Gui/TaskView/TaskView.cpp
- src/Gui/TaskView/TaskView.h
> Fix #11032 flickering when switching to Part Design

- src/Mod/Sketcher/Gui/CommandSketcherTools.cpp
- src/Mod/Sketcher/Gui/DrawSketchController.h
- src/Mod/Sketcher/Gui/DrawSketchDefaultWidgetController.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h
- src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
- src/Mod/Sketcher/Gui/Resources/icons/pointers/Sketcher_Pointer_Create_Offset.svg
- src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.cpp
- src/Mod/Sketcher/Gui/SketcherToolDefaultWidget.h
Follow up on #11174.
Make small improvements. Fix some small edge-cases bugs. For example if user enters 0 and 0 for length and width of a line, we prevent validation of an null line.
> [Sketcher] Follow up on sketcher 'Tool parameters' PR.

- src/Base/Interpreter.cpp
https://forum.freecad.org/viewtopic.php?p=716961#p716961
> Base: fix crash in PyException::ReportException()

- src/Tools/updatets.py
removed unused pylupdate4.
pylupdate4 are used with qt4.
> removed pylupdate4 used in qt4

- src/Tools/entitlements.plist
- src/Tools/macos_sign_and_notarize.sh
> Tools: Add entitlements to MacOS signing

- src/Mod/TechDraw/TechDrawTools/CommandAxoLengthDimension.py
> [TechDraw] Fix issue #10094

- src/Gui/CommandView.cpp
- src/Gui/Icons/Std_ToggleTransparency.svg
- src/Gui/Icons/resource.qrc
- src/Gui/Workbench.cpp
Add a tool to toggle transparency.
It works with single solids. But also with App::Parts containing links to multiple files.
Fixes #10770
Forum discuss : https://forum.freecad.org/viewtopic.php?t=81275
> Std_Transparency : Toggle transparency of objects.

- src/Mod/Draft/InitGui.py
- src/Mod/Draft/WorkingPlane.py
Related issue:
#5603.
Additionally:
* Minor improvements to _update_grid and _update_gui.
> Draft: PlaneGui: view observer to update the Tray

- src/Mod/Arch/ArchBuildingPart.py
- src/Mod/Arch/ArchSite.py
> Arch: Fix issue with getSceneGraph

- src/Mod/Arch/InitGui.py
> Arch: start and stop WP view observer

- src/Mod/Draft/importDXF.py
> Draft: fix import scale for Legacy DXF importer

- src/Mod/Arch/ArchCutPlane.py
Forum topic:
https://forum.freecad.org/viewtopic.php?t=82340
> Arch: make Arch_CutPlane nesting and link aware

- src/Mod/TechDraw/Gui/PagePrinter.cpp
- src/Mod/TechDraw/Gui/QGIViewPart.cpp
- src/Mod/TechDraw/Gui/QGIViewPart.h
This PR implements fixes for #11308 and #11309.
> [TD]Fix #11308 Pdf margins and #11309 center mark 

- src/Mod/Sketcher/Gui/DrawSketchControllableHandler.h
- src/Mod/Sketcher/Gui/DrawSketchController.h
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerPoint.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h
As per:
https://github.com/FreeCAD/FreeCAD/pull/11327
> Sketcher: Control Cursor text based on OVP visibility

- src/Mod/TechDraw/App/DrawUtil.cpp
- src/Mod/TechDraw/App/DrawUtil.h
- src/Mod/TechDraw/Gui/CommandExtensionPack.cpp
This PR implements a fix for issue #11310.
> [TD]fix 3 extension methods #11310

- src/Mod/Mesh/App/Exporter.cpp
> Fix #10545 #11200 by using position of array members

- src/Mod/Sketcher/Gui/ViewProviderSketch.cpp
- src/Mod/Sketcher/Gui/ViewProviderSketch.h
- Fix for selection issue with hyperbola and parabola.
- Full refactor of the doBoxSelection function.
> Sketcher: Box selection - Hyperbola/Parabola endpoint fix

- src/Gui/PreferencePages/DlgSettingsLightSources.cpp
> Gui: Fixes #11341: Adjusting Light Sources in Preferences

- src/Mod/Sketcher/Gui/CMakeLists.txt
- src/Mod/Sketcher/Gui/CircleEllipseConstructionMethod.h
- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/DrawSketchController.h
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h
- src/Mod/Sketcher/Gui/Utils.cpp
- src/Mod/Sketcher/Gui/Utils.h
Arc/Circle/Ellipse : implement tool parameters.
Requires merge of : 
https://github.com/FreeCAD/FreeCAD/pull/11294
> [Sketcher] Arc/Circle/Ellipse : implement tool parameters.

- src/Mod/Sketcher/Gui/CMakeLists.txt
- src/Mod/Sketcher/Gui/CommandAlterGeometry.cpp
- src/Mod/Sketcher/Gui/CommandCreateGeo.cpp
- src/Mod/Sketcher/Gui/DrawSketchController.h
- src/Mod/Sketcher/Gui/DrawSketchHandler.cpp
- src/Mod/Sketcher/Gui/DrawSketchHandler.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArcSlot.h
- src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateArcSlot.svg
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateArcSlot_Constr.svg
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateRectangleSlot.svg
- src/Mod/Sketcher/Gui/Resources/icons/geometry/Sketcher_CreateRectangleSlot_Constr.svg
- src/Mod/Sketcher/Gui/Resources/icons/pointers/Sketcher_Pointer_Create_ArcSlot.svg
- src/Mod/Sketcher/Gui/Resources/icons/pointers/Sketcher_Pointer_Create_RectangleSlot.svg
- src/Mod/Sketcher/Gui/Workbench.cpp
Implement an arc slot tool for sketcher. It also has a methode to make rectangular slots.
> [Sketcher] ArcSlot DSH : implement the Arc slot tool

- src/Mod/Part/App/BRepOffsetAPI_MakePipeShellPy.xml
- src/Mod/Part/App/BezierCurvePy.xml
- src/Mod/Part/App/BezierSurfacePy.xml
- src/Mod/Part/App/BoundedCurvePy.xml
- src/Mod/Part/App/ConePy.xml
- src/Mod/Part/App/CylinderPy.xml
- src/Mod/Part/App/EllipsePy.xml
- src/Mod/Part/App/Geom2d/BSplineCurve2dPy.xml
- src/Mod/Part/App/Geom2d/BezierCurve2dPy.xml
- src/Mod/Part/App/Geom2d/Curve2dPy.xml
- src/Mod/Part/App/Geom2d/Ellipse2dPy.xml
- src/Mod/Part/App/Geom2d/Hyperbola2dPy.xml
- src/Mod/Part/App/Geom2d/OffsetCurve2dPy.xml
- src/Mod/Part/App/Geom2d/Parabola2dPy.xml
- src/Mod/Part/App/GeometryCurvePy.xml
- src/Mod/Part/App/GeometrySurfacePy.xml
- src/Mod/Part/App/HyperbolaPy.xml
- src/Mod/Part/App/OffsetCurvePy.xml
- src/Mod/Part/App/OffsetSurfacePy.xml
- src/Mod/Part/App/ParabolaPy.xml
- src/Mod/Part/App/PlateSurfacePy.xml
- src/Mod/Part/App/RectangularTrimmedSurfacePy.xml
- src/Mod/Part/App/SpherePy.xml
- src/Mod/Part/App/SurfaceOfExtrusionPy.xml
- src/Mod/Part/App/SurfaceOfRevolutionPy.xml
- src/Mod/Part/App/TopoShapeVertexPy.xml
- src/Mod/Part/App/ToroidPy.xml
- src/Mod/Part/App/TrimmedCurvePy.xml
This PR is about applying formatting rules to our XML files. It's basically about replacing tabs with four spaces.
The files have been formatted with the utility at https://github.com/FreeCAD/FreeCAD/tree/main/src/Tools/xmlformat
> Part: format XML files

- src/Mod/Sketcher/Gui/DrawSketchController.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerArc.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerCircle.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerEllipse.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerLine.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerPolygon.h
- src/Mod/Sketcher/Gui/DrawSketchHandlerRectangle.h
> SketcherGui: Fix lints

- src/Mod/Sketcher/Gui/DrawSketchHandlerArcSlot.h
> SketcherGui: ArcSlot lints

- src/Mod/Path/PathTests/TestRefactoredTestPost.py
This is one in a series of PR's where I am taking code from at least 4 postprocessor files partially written by different people, combining them into a few files, then trying to make the code more consistent and simpler. The long term goal is to enable much simpler postprocessor files with much less copied code in each postprocessor file and much more "shared" code in the Utils*.py files.
In this PR I rearranged and renumbered some of the tests in TestRefactoredTestPost.py.
> Path:  Rearranged and renumbered some of the tests

- src/Mod/TechDraw/App/ShapeExtractor.cpp
This PR implements a fix for a problem with the scaling of links as reported here: https://forum.freecad.org/viewtopic.php?t=82659&sid=0dc17912438cb1ce9a55ed94c9eed0e3
> [TD]fix regression on Links with scale

- src/Mod/Sketcher/Gui/DrawSketchHandlerSlot.h
Implement tool parameters for the Slot tool in sketcher.
> [Sketcher] Slot DSH : implement tool parameters.

- src/Mod/Draft/draftguitools/gui_base_original.py
- src/Mod/Draft/draftguitools/gui_snapper.py
- src/Mod/Draft/draftguitools/gui_trackers.py
> Draft: cleanup related to PR11336

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
Fixes https://github.com/FreeCAD/FreeCAD/issues/11343
ESC button not working for sketcher_dimension
> Fix ESC key for Sketcher_Dimension

- src/Mod/PartDesign/Gui/TaskPipeParameters.cpp
> Refresh body after pipe created

- tests/src/Gui/QuantitySpinBox.cpp
> Tests: add test for QuantitySpinBox::setValue(double)

- src/Mod/Draft/draftguitools/gui_join.py
Also removed an obsolete comment.
> Draft: Draft_Join should call join_wires

- src/Mod/Draft/DraftGui.py
> Draft: make in-command shortcuts non-global

- src/Mod/Draft/draftguitools/gui_snapper.py
> Draft: constraining did not respect global mode

- src/Mod/Arch/ArchRebar.py
- src/Mod/Arch/ArchSite.py
> Parse inventor format without commas between points

- src/Mod/Part/CMakeLists.txt
- src/Mod/Part/TestPartApp.py
- src/Mod/Part/parttests/Geom2d_tests.py
> Part: add test for Geom2d.toShape

- src/Mod/PartDesign/App/FeatureGroove.cpp
- src/Mod/PartDesign/App/FeatureGroove.h
- src/Mod/PartDesign/App/FeatureRevolution.cpp
- src/Mod/PartDesign/App/FeatureRevolution.h
- src/Mod/PartDesign/Gui/TaskRevolutionParameters.cpp
- src/Mod/PartDesign/Gui/TaskRevolutionParameters.h
- src/Mod/PartDesign/Gui/TaskRevolutionParameters.ui
Attempts to fix #7179.
I am trying to copy the code from pad/pocket but they are somewhat different.
> PD: more options for revolution/groove

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
- src/Mod/Sketcher/Gui/Resources/Sketcher.qrc
- src/Mod/Sketcher/Gui/Resources/icons/constraints/Constraint_HorVer.svg
- src/Mod/Sketcher/Gui/Utils.h
- src/Mod/Sketcher/Gui/Workbench.cpp
Adds a auto horizontal / vertical constraint and command group.
Refactor horizontal/vertical commands which had lot of duplicates.
Fixes #10320 
Fixes #10261
Also participate solving https://github.com/FreeCAD/FreeCAD/issues/11208
> [Sketcher] Auto horizontal/vertical

- src/Gui/Selection.cpp
- src/Gui/SoFCSelection.cpp
- src/Gui/SoFCUnifiedSelection.cpp
Fixes #10837
@wwmayer can you give your opinion on this ? Also if you have an idea where we could put a function to avoid this 3 time copy paste.
Thanks
> [Core] Status bar : reduce number of decimals

- src/3rdParty/libE57Format/src/Decoder.cpp
> [3rdParty] fix typo in Decoder.cpp

- src/Mod/Draft/draftguitools/gui_trackers.py
* The gridBorder pref was ignored.
* BimProject has been renamed to BimProjectManager.
> Draft: gridShowHuman did not work

- .clang-tidy
- src/Base/Vector3D.cpp
- src/Base/Vector3D.h
See [#11409](https://github.com/FreeCAD/FreeCAD/pull/11409#discussion_r1394868201)
> Base: fix bugprone reserved identifier

- src/Mod/Draft/draftguitools/gui_snapper.py
- src/Mod/Draft/draftguitools/gui_trackers.py
* Some trackers had 2 color nodes.
* Added a setColor function to some trackers.
* Added a set_snap_style function to the Snapper class.
> Draft: improved handling of snap prefs

- src/Mod/Draft/CMakeLists.txt
- src/Mod/Draft/InitGui.py
- src/Mod/Draft/draftutils/params.py
To avoid having to restart FreeCAD after changing parameters.
> Draft: add parameter observer

- tests/CMakeLists.txt
> Tests: Set test executables in a central place

- src/Mod/TechDraw/Gui/QGIRichAnno.cpp
- src/Mod/TechDraw/Gui/QGIRichAnno.h
This PR fixes 2 issues with the Rich Text Annotation as reported here https://forum.freecad.org/viewtopic.php?t=82715  and here https://forum.freecad.org/viewtopic.php?t=82730
> [TD]Fix RichTextAnnotation Export As Svg

- src/Mod/Arch/InitGui.py
> Arch: start Draft param observer

- src/Mod/Draft/Resources/ui/preferences-draft.ui
- src/Mod/Draft/draftguitools/gui_arcs.py
- src/Mod/Draft/draftguitools/gui_base.py
- src/Mod/Draft/draftguitools/gui_base_original.py
- src/Mod/Draft/draftguitools/gui_beziers.py
- src/Mod/Draft/draftguitools/gui_circulararray.py
- src/Mod/Draft/draftguitools/gui_dimensions.py
- src/Mod/Draft/draftguitools/gui_edit_draft_objects.py
- src/Mod/Draft/draftguitools/gui_ellipses.py
- src/Mod/Draft/draftguitools/gui_fillets.py
- src/Mod/Draft/draftguitools/gui_hyperlink.py
- src/Mod/Draft/draftguitools/gui_join.py
- src/Mod/Draft/draftguitools/gui_labels.py
- src/Mod/Draft/draftguitools/gui_lines.py
- src/Mod/Draft/draftguitools/gui_mirror.py
- src/Mod/Draft/draftguitools/gui_move.py
- src/Mod/Draft/draftguitools/gui_offset.py
- src/Mod/Draft/draftguitools/gui_polygons.py
- src/Mod/Draft/draftguitools/gui_rectangles.py
- src/Mod/Draft/draftguitools/gui_rotate.py
- src/Mod/Draft/draftguitools/gui_scale.py
- src/Mod/Draft/draftguitools/gui_shapestrings.py
- src/Mod/Draft/draftguitools/gui_splines.py
- src/Mod/Draft/draftguitools/gui_split.py
- src/Mod/Draft/draftguitools/gui_stretch.py
- src/Mod/Draft/draftguitools/gui_texts.py
- src/Mod/Draft/draftguitools/gui_trimex.py
- src/Mod/Draft/draftutils/messages.py
New property: Draft -> General -> Show tool messages (off by default)
Fixes #7078
> Draft: Added a preference to turn on/off tool messages

- src/Mod/Draft/draftutils/gui_utils.py
> Draft: Gui.ActiveDocument.ActiveView.getActiveObject has changed

- src/Mod/Draft/Resources/ui/preferences-draftsnap.ui
- src/Mod/Draft/draftguitools/gui_snapper.py
- src/Mod/Draft/draftguitools/gui_snaps.py
- src/Mod/Draft/draftutils/params.py
- src/Mod/Draft/draftutils/utils.py
This PR replaces the showSnapBar and hideSnapBar preferences with a single new preference: SnapBarShowOnlyDuringCommands.
Additonally:
Improved some param observer callbacks.
> Draft: improve Snap bar show-hide preference

- src/Gui/Selection.cpp
- src/Mod/Part/App/Geom2d/BSplineCurve2dPyImp.cpp
- src/Mod/Part/App/TopoShapePyImp.cpp
- src/Mod/Part/parttests/Geom2d_tests.py
- src/Mod/Part/parttests/regression_tests.py
- src/Mod/Test/Document.py
Fixes https://github.com/FreeCAD/FreeCAD/issues/11505
> Fixes #11505

- src/Mod/TechDraw/Gui/QGIViewBalloon.cpp
- src/Mod/TechDraw/Gui/QGIViewDimension.cpp
- src/Mod/TechDraw/Gui/QGVNavStyle.cpp
- src/Mod/TechDraw/Gui/QGVNavStyle.h
- src/Mod/TechDraw/Gui/QGVNavStyleBlender.cpp
- src/Mod/TechDraw/Gui/QGVNavStyleCAD.cpp
- src/Mod/TechDraw/Gui/QGVNavStyleGesture.cpp
- src/Mod/TechDraw/Gui/QGVNavStyleInventor.cpp
- src/Mod/TechDraw/Gui/QGVNavStyleMaya.cpp
- src/Mod/TechDraw/Gui/QGVNavStyleOCC.cpp
- src/Mod/TechDraw/Gui/QGVNavStyleOpenSCAD.cpp
- src/Mod/TechDraw/Gui/QGVNavStyleRevit.cpp
- src/Mod/TechDraw/Gui/QGVNavStyleTinkerCAD.cpp
- src/Mod/TechDraw/Gui/QGVNavStyleTouchpad.cpp
This PR implements a fix to dimension positioning reported here: https://forum.freecad.org/viewtopic.php?t=82882.
The same problem occurs in balloons and a fix is included.
A different problem involving the balloon cursor when initially placing a balloon was discovered while fixing the positioning issue, and a fix for that is also included.
> [TD]Fix dimension and balloon position

- src/Mod/Material/App/PreCompiled.h
https://forum.freecad.org/viewtopic.php?t=83029
> Material: add QRegularExpression to PCH

- src/Mod/Sketcher/Gui/CommandConstraints.cpp
hor/ver tool, remove unused variables
@wwmayer
> [Sketcher] hor/ver tool, remove unused variables

- src/Mod/PartDesign/App/FeatureHelix.cpp
> Correct PartDesign Helix feature negative angles
